### ISSUE TITLE
How should throttling be detected?

### ISSUE THREAD

**Issue by zoe-mcelderry** [Azure/azure-iot-sdk-c#1001]
Hi all,

I'd like to know how to detect if a device has hit the throttling threshold?

I want to be able to send data as fast as possible to my Azure IoT Hub, but I don't necessarily know what else is sending data to the IoT Hub at the same time.  The frequency that I can send device to cloud messages depends on how many devices are currently sending data (and the frequency at which they are sending data) to the IoT Hub (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling), which makes it difficult to predict the speed that I can send data at.

So my question is -- is there a way to detect that a throttling limit has been reached via the SDK (e.g. a callback that I could set up)?

Thanks in advance for your help.

**Comment by massand** [comment]
@zoe-mcelderry The SDK follows the recommended guidance for transient failures (throttling), which implies performing message (or connection) retries responsibly, using the retry patterns documented here - https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-reliability-features-in-sdks#retry-patterns

The Azure IoT Hub C SDK specific implementation for handling throttling status code (429) is not exposed in the public API (i.e. undocumented policy in our SDK) at the moment. Generally though, it behaves differently for each protocol- 
1) MQTT- The device connection is severed and a message callback (if you registered using SetMessageCallback) after the two message send retries fail. You should also receive a connection callback (if you registered using SetConnectionStatusCallback) for the severed connection. 
2) AMQP - The device connection is kept alive and messages are retried over the connection three times, after which you will receive the message callback (if you registered using SetMessageCallback). 

In both cases, you would need to retry the message send after you receive the message callback. But, that is upto the application. Hope that helps.

**Comment by massand** [comment]
@zoe-mcelderry If you have a specific transient error scenario in mind, please let us know along with the transport protocol of interest. Thanks to @ewertons for answering the AMQP question offline!

**Comment by zoe-mcelderry** [comment]
@massand  Thank you for your explanation.

We are having an issue where a device gets disconnected semi-permanently from the Azure IoT Hub because we are hitting the throttling limit.  Without being able to tell if a message has failed to send because of throttling or because of another issue it makes it hard to know how to handle the status received from the message callback.  If it has failed because of network issues (for example), we would want to try again straight away, but if it has failed because of throttling we would want to sleep (and delay sending any further messages) before trying again.

We are observing this behaviour whilst using the default retry pattern, which seems to be the recommended approach.

We need our solution to work across all transport protocols as this is a configurable option for our end users.

**Comment by massand** [comment]
@zoe-mcelderry Sorry for the delay in response. You could use the metrics functionality on the Azure portal - https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-metrics#iot-hub-metrics-and-how-to-use-them. 

From the device side, I am afraid there isn't too many options. Our recommendation for network issues and throttling scenarios is identical. The policy in the application's logic needs to treat those conditions consistently because the service doesn't report back throttle for telemetry message (it only does so for device twin patch failures I believe). Hope that helps explain reasons we cannot handle these scenarios on the device SDK side to meet your needs. If there is a retry logic bug you spot, please create a bug type issue and provide a sample, C SDK traces to better help you. Thanks!

**Comment by az-iot-builder-01** [comment]
@massand, @zoe-mcelderry, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by zoe-mcelderry** [comment]
@massand Thanks for the link to the IoT Hub metrics page, from that it looks like the Azure Monitor requires some (initial) set up on the Azure portal side in order to access the metrics... is that right?

@massand It seems like an oversight on the server to not report back about throttling issues -- is there anyway I can feed that back to the server development team?
