### ISSUE TITLE
Deleting a device and recreating it with the same credentials does not end up in device reconnecting

### ISSUE THREAD

**Issue by dcristoloveanu** [Azure/azure-iot-sdk-c#102]
- **OS and version used:** <VERSION> Windows 10

- **SDK version used:** <VERSION> db0ea8d977c52f0543d8fa23642576d11835b88f

# Description of the issue:
Repro steps:
1. Create a device in Device explorer
2. Put the device connection string in iothub_client_sample_amqp
3. Run iothub_client_sample_amqp (will nicely send messages)
4. Delete the device from Device Explorer while the sample is connected. Oh No!
5. Create the same device again (same device Id, same primary key). Myeah, I am evil.

Expected result: Device will reconnect.
Actual result: It does not, see log below.

# Code sample exhibiting the issue:
iothub_client_sample_amqp.

# Console log of the issue:
Visual Leak Detector read settings from: C:\Program Files (x86)\Visual Leak Detector\vld.ini
Visual Leak Detector Version 2.5 installed.
Starting the IoTHub client sample AMQP...
Info: IoT Hub SDK for C, version 1.1.10
IoTHubClient_SetMessageCallback...successful.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
-> Header (AMQP 0.1.0.0)
<- Header (AMQP 0.1.0.0)
-> [OPEN]* {fbfdd025-5e07-4510-b6cb-94c1801c349e,iothub-client-02.azure-devices.net,4294967295,65535,240000}
<- [OPEN]* {DeviceGateway_e08ad9f71aa146beb4e492d0728e2da1,10.0.4.49,65536,8191,240000,NULL,NULL,NULL,NULL,NULL}
-> [BEGIN]* {NULL,0,4294967295,100,4294967295}
<- [BEGIN]* {0,1,100,5000,262143,NULL,NULL,NULL}
-> [ATTACH]* {cbs-sender,0,false,0,0,* {$cbs},* {$cbs},NULL,NULL,0,65535}
-> [ATTACH]* {cbs-receiver,1,true,0,0,* {$cbs},* {$cbs},NULL,NULL,NULL,65535}
<- [ATTACH]* {cbs-sender,0,true,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,65535,NULL,NULL,NULL}
<- [FLOW]* {0,100,1,5000,0,0,100,0,NULL,false,NULL}
<- [ATTACH]* {cbs-receiver,1,false,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65535,NULL,NULL,NULL}
-> [FLOW]* {1,4294967295,0,100,1,0,10000}
-> [TRANSFER]* {0,0,<01 00 00 00>,0,false,false}
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
<- [TRANSFER]* {1,0,<01 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,0,0,true,* {}}
-> [ATTACH]* {link-snd-0000_dcristo-10d57521-f631-4f56-b358-f34cb5824641,2,false,0,0,* {link-snd-0000_dcristo-10d57521-f631-4f56-b358-f34cb5824641-source},* {amqps://iothub-client-02.azure-devices.net/devices/0000_dcristo/messages/events},NULL,NULL,0,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.1.10]}}
<- [ATTACH]* {link-snd-0000_dcristo-10d57521-f631-4f56-b358-f34cb5824641,2,true,0,NULL,* {link-snd-0000_dcristo-10d57521-f631-4f56-b358-f34cb5824641-source,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {amqps://iothub-client-02.azure-devices.net/devices/0000_dcristo/messages/events,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.1.10]}}
-> [ATTACH]* {link-rcv-0000_dcristo-75e6f862-b507-4716-9624-17c3fa29de27,3,true,0,0,* {amqps://iothub-client-02.azure-devices.net/devices/0000_dcristo/messages/devicebound},* {link-rcv-0000_dcristo-75e6f862-b507-4716-9624-17c3fa29de27-target},NULL,NULL,NULL,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.1.10]}}
<- [FLOW]* {1,100,2,4294967295,2,0,1000,0,NULL,false,NULL}
-> [TRANSFER]* {2,1,<01 00 00 00>,0,false,false}
-> [TRANSFER]* {2,2,<02 00 00 00>,0,false,false}
-> [TRANSFER]* {2,3,<03 00 00 00>,0,false,false}
-> [TRANSFER]* {2,4,<04 00 00 00>,0,false,false}
-> [TRANSFER]* {2,5,<05 00 00 00>,0,false,false}
<- [ATTACH]* {link-rcv-0000_dcristo-75e6f862-b507-4716-9624-17c3fa29de27,3,false,0,0,* {amqps://iothub-client-02.azure-devices.net/devices/0000_dcristo/messages/devicebound,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {link-rcv-0000_dcristo-75e6f862-b507-4716-9624-17c3fa29de27-target,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.1.10]}}
-> [FLOW]* {2,4294967294,6,94,3,0,10000}
<- [DISPOSITION]* {true,1,NULL,true,* {},NULL}
Confirmation[0] received for message tracking id = 0 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- [DISPOSITION]* {true,2,3,true,* {},NULL}
Confirmation[1] received for message tracking id = 1 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[2] received for message tracking id = 2 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- [DISPOSITION]* {true,4,5,true,* {},NULL}
Confirmation[3] received for message tracking id = 3 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[4] received for message tracking id = 4 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- [DETACH]* {3,true,* {amqp:internal-error,"Device 0000_dcristo at IotHub iothub-client-02 not registered",{[exception:ErrorCode: DeviceNotFound
Message: "Device 0000_dcristo at IotHub iothub-client-02 not registered"
Timestamp: 03/29/2017 06:41:10
Tracking ID: 5b643d3377294956ac973852a445b55f-TimeStamp:03/29/2017 06:41:10
Public Message: 0000_dcristo
Public Info: null
Exception: Microsoft.Azure.Devices.Common.Cloud.Exceptions.IotHubException: "Device 0000_dcristo at IotHub iothub-client-02 not registered"
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Devices.Common.Cloud.TaskHelpers.<WithTimeoutInternal>d__27`1.MoveNext() in D:\jenkins\workspace\Build\common\Microsoft.Azure.Devices.Common\TaskHelpers.cs:line 458
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Container.Service.PeekWaiterManager.<WaitAsync>d__5.MoveNext() in D:\jenkins\workspace\Build\container\Microsoft.Azure.Devices.Container.Service\PeekWaiter.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Container.Service.DeviceServiceReplica.<PeekMessageAsync>d__134.MoveNext() in D:\jenkins\workspace\Build\container\Microsoft.Azure.Devices.Container.Service\DeviceServiceReplica.cs:line 2193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Devices.Container.Service.ContainerDeviceBoundLink.<PumpMessagesAsync>d__31.MoveNext() in D:\jenkins\workspace\Build\container\Microsoft.Azure.Devices.Container.Service\ContainerDeviceBoundLink.cs:line 400]}}}
-> [DETACH]* {3}
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_messenger.c Func:_process_state_changes Line:1530 messagereceiver reported unexpected state 4 while messenger is starting
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_device.c Func:_device_do_work Line:888 Device '0000_dcristo' is started but messenger reported unexpected state 4
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 6; number of previous failures: 0)
-> [DETACH]* {2,true}
-> [TRANSFER]* {0,6,<02 00 00 00>,0,false,false}
<- [DETACH]* {2,true,NULL}
-> [END]* {* {amqp:session:unattached-handle,}}
<- [DISPOSITION]* {true,6,NULL,true,* {},NULL}
<- [TRANSFER]* {1,1,<02 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_cbs_auth.c Func:_on_cbs_put_token_complete_callback Line:272 CBS reported status code 404, error: '"Device 0000_dcristo at IotHub iothub-client-02 not registered"' for put-token operation for device '0000_dcristo'
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_cbs_auth.c Func:_mark_current_device_key_as_invalid Line:216 Primary key of device '0000_dcristo' was marked as invalid. No other device keys available
-> [DISPOSITION]* {true,1,1,true,* {}}
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 1)
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 2)
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 3)
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 4)
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_DoWork Line:1343 Device '0000_dcristo' reported a critical failure; connection retry will be triggered.
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_DoWork Line:1304 An error occured on AMQP connection. The connection will be restablished.
-> [CLOSE]* {}
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 0)
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 1)
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 2)
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 3)
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 4)
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_DoWork Line:1343 Device '0000_dcristo' reported a critical failure; connection retry will be triggered.
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_DoWork Line:1304 An error occured on AMQP connection. The connection will be restablished.
Error: Time:Tue Mar 28 23:41:09 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_connection.c Func:_on_cbs_open_complete Line:149 CBS open failed
-> [CLOSE]* {}

... log continues

Error: Time:Tue Mar 28 23:41:33 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 0)
Error: Time:Tue Mar 28 23:41:33 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 1)
Error: Time:Tue Mar 28 23:41:33 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 2)
Error: Time:Tue Mar 28 23:41:33 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 3)
Error: Time:Tue Mar 28 23:41:33 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '0000_dcristo' (device reported state 4; number of previous failures: 4)
Error: Time:Tue Mar 28 23:41:33 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_DoWork Line:1343 Device '0000_dcristo' reported a critical failure; connection retry will be triggered.
Error: Time:Tue Mar 28 23:41:33 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_DoWork Line:1304 An error occured on AMQP connection. The connection will be restablished.
Error: Time:Tue Mar 28 23:41:33 2017 File:D:\repos\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_connection.c Func:_on_cbs_open_complete Line:149 CBS open failed
-

**Comment by ewertons** [comment]
Thanks for reporting this issue, @dcristoloveanu .

We will investigate it soon.
Thanks for using the Azure IoT SDK.

**Comment by ewertons** [comment]
We were able to get a repro following the steps you provided.
We are working on a fix, which will be checked in soon.

**Comment by tameraw** [comment]
@dcristoloveanu - A lot of fixes have gone into retry logic. Please try with latest release and reopen of still an issue.
