### ISSUE TITLE
Support for private keys that live on crypto devices

### ISSUE THREAD

**Issue by OYTIS** [Azure/azure-iot-sdk-c#1022]
Greetings,

we've got a device that can perform security operations with private keys never leaving the device, and we'd like to have it supported with Azure IoT SDK. The problem is in the Azure SDK private key is abstracted as a string, and all existing tlsio adapters interpret this string as plain text PEM key, which is not what we'd like to have.

There was a [similar request](https://github.com/Azure/azure-iot-sdk-c/issues/509) about a year ago, and the proposed solution was to implement new tlsio adapter that would interpret the string it gets in a special way, and interact with the security device.

The problem I see with this solution is that existing adapters already contain a lot of code not related to private key management, and creating a duplicate with changed private key logic would make poor architecture and increase the maintenance burden. Moreover, tlsio adapters abstract TLS libraries, not crypto devices (which are in turn abstracted by `HSM_CLIENT_X509_INTERFACE`).

What I would propose is adding private key abstraction to tlsio, that would represent a private key in a more generic way, e.g.

```
struct tlsio_private_key {
  int (*sign)(const char*, int, char*, int*, void*); // (hash, length, output, out_length, priv) -> result
  int (*decrypt)(const char*, int, char*, int*, void*); // (data, length, output, out_length, priv) -> result
  union {
    struct rsa_params {...};
    struct ecc_params {...};
  };
};
```

It could then be converted by the adapters to a library-specific private key representation.

It's definitely quite a few changes to multiple repos (c-utility, uhttp, c SDK), but will also improve the security dramatically.

Would be grateful for any feedback, guidance and help.

**Comment by CIPop** [comment]
Thanks @OYTIS. I have recently joined the C SDK group (please bare with me as I ramp-up). We have discussed the proposal and came up with the following functional requirements:
1. No new public APIs should be added (if possible).
2. Our SDK repo will not contain the custom HSM code. (We cannot maintain drivers specific to certain hardware but we can implement some of the existing standards such as PKCS#11, TPM etc.)
3. A new 3rd party custom HSM module must be easy to integrate with our SDK. This should be achievable without having access to source-code of the driver.
4. The HSM custom module be usable with or without DPS (e.g. X509 auth with the IoT Hub).

The plan for the current SDK is to offer a way to implement a custom TLS xio that is configurable by the application and can take full advantage of the HSM features. Some (if not all the configuration) should be passed through existing APIs that can be repurposed (e.g. the cert key could be a slot# in the HSM).

**Comment by ericwol-msft** [comment]
This issue has been placed on our back log. We will allow more flexibility to the TLS stack for HSM support

**Comment by az-iot-builder-01** [comment]
@OYTIS, @CIPop, @ericwol-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
