### ISSUE TITLE
Connect to the iot-hub using MQTT

### ISSUE THREAD

**Issue by v-jiq** [Azure/azure-iot-sdk-c#1024]
Considering the problem of system resources and have standard MQTT library, I do not want to rely on SDK to access to the iot-hub server, but only through the standard MQTT. Is there any tutorial about this? If not, how can I have the SDK library cropped to a minimum and connected to the server using MQTT.

Thanks!!

**Comment by YoDaMa** [comment]
@v-jiq here's a guide for directly connecting to IoT Hub via mqtt vs. using the sdk:

 https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support

In terms of reducing the size for the C SDK on your device, you can manually compile it (as opposed to using the vcpkg or apt-get package), specifying through CMake the parts of the SDK you would like to include and un-include. These options can be found in the main `CMakeLists.txt`:

https://github.com/Azure/azure-iot-sdk-c/blob/master/CMakeLists.txt

For instance, if you just want MQTT, by default MQTT, AMQP, and HTTP support is compiled with the SDK. To compile the SDK without AMQP and HTTP support, when running cmake add `-D` options as below: 

```
$ cmake -Duse_amqp=OFF -Duse_http=OFF 
```

**Comment by atlascollege** [comment]
@YoDaMa  Thanks for your feedback!

**Comment by az-iot-builder-01** [comment]
@v-jiq, @YoDaMa, @atlascollege, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by yzhong94** [comment]
@atlascollege @v-jiq You can find the instruction for compiling a smaller SDK here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-develop-for-constrained-devices

For our reference, can you provide more details (RAM/ROM/OS etc) on the devices?  We want to make sure the SDK works with as many devices as possible.

In addition, if the MQTT library used by the SDK is modular (meaning that you can use the library you have on the device), would you consider using the SDK?

// @massand FYI
