### ISSUE TITLE
IoT Hub Device Streams info in README

### ISSUE THREAD

**Issue by Alberto-Vega-MSFT** [Azure/azure-iot-sdk-c#1027]
**Is your feature request related to a problem? Please describe.**

It seems like the README needs an update to mention about IoT Hub device streams being available to avoid confusion please see https://github.com/MicrosoftDocs/azure-docs/issues/31913

**Describe the solution you'd like**
update the README section https://github.com/Azure/azure-iot-sdk-c#key-features-and-roadmap

**Comment by danewalton** [comment]
PR Created
https://github.com/Azure/azure-iot-sdk-c/pull/1166

**Comment by az-iot-builder-01** [comment]
@Alberto-Vega-MSFT, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
