### ISSUE TITLE
AICS Tesst Report

### ISSUE THREAD

**Issue by engineerPapa** [Azure/azure-iot-sdk-c#1028]
GM Guys,
I am looking for steps to generate AICS Test report for my android device.

I was able to cross compile the sdk code for using Android ndk.
Is there any application or steps that can help me to generate the AICS report.

Please guide.
Thanks

**Comment by massand** [comment]
@engineerPapa - in order obtain an AICS test report for any device, you would need to visit register as a 'Azure Certified for IoT device' partner first through the portal - 
https://catalog.azureiotsolutions.com/register

You can then submit your device for certification via the Partner dashboard, which will walk you through the process. Thanks for the great question!

**Comment by az-iot-builder-01** [comment]
@engineerPapa, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
