### ISSUE TITLE
Failure setting "TrustedCerts" for AMQP_Protocol_over_WebSocketsTls

### ISSUE THREAD

**Issue by Norman0406** [Azure/azure-iot-sdk-c#103]
- **OS and version used:** <VERSION> Windows 10 

- **SDK version used:** 1.1.10 

# Description of the issue:

Hi there,
When creating the IoTHubClient with AMQP_Protocol_over_WebSocketsTls, the function to set the "TrustedCerts" option returns with an error. No problem with MQTT_WebSocket_Protocol though. This was tested with the sample project _iothub_client_sample_amqp_websockets_ from the latest release 1.1.10 (release_2017_03_24).

# Code sample exhibiting the issue:

```cpp
if (IoTHubClient_SetOption(iotHubClientHandle, "TrustedCerts", certificates) != IOTHUB_CLIENT_OK)
{
    printf("failure to set option \"TrustedCerts\"\r\n");
}
```

# Console log of the issue:

> Starting the IoTHub client sample AMQP over WebSockets...
Info: IoT Hub SDK for C, version 1.1.10
Error: Time:Wed Mar 29 15:05:37 2017 File:D:\dev\external\azure-iot-sdk-c\c-utility\src\uws_client.c Func:_uws_client_set_option Line:1851 xio_setoption failed.
Error: Time:Wed Mar 29 15:05:37 2017 File:D:\dev\external\azure-iot-sdk-c\c-utility\src\wsio.c Func:_wsio_setoption Line:688 Setting the option TrustedCerts failed
Error: Time:Wed Mar 29 15:05:37 2017 File:D:\dev\external\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_SetOption Line:1747 transport failed setting option 'TrustedCerts' (xio_setoption failed)
Error: Time:Wed Mar 29 15:05:37 2017 File:D:\dev\external\azure-iot-sdk-c\iothub_client\src\iothub_client_ll.c Func:_IoTHubClient_LL_SetOption Line:1486 underlying transport failed, returned = IOTHUB_CLIENT_ERROR
Error: Time:Wed Mar 29 15:05:37 2017 File:D:\dev\external\azure-iot-sdk-c\iothub_client\src\iothub_client.c Func:_IoTHubClient_SetOption Line:1349 IoTHubClient_LL_SetOption failed
failure to set option "TrustedCerts"

**Comment by ewertons** [comment]
Thanks for reporting this issue, @Norman0406 .

We will investigate it soon and reply back with our findings.
Thanks for using the Azure IoT SDK

**Comment by ewertons** [comment]
Hi @Norman0406 ,

the message you are observing is an expected failure when trying to set "TrustedCerts" on a Windows platform using schannel (Windows native API) for TLS.

You will not experience the same failure if running the samples on Linux, for example, since OpenSSL is used there and it consumes the TrustedCerts option.

**Comment by ewertons** [comment]
Another point is regarding your comment about not observing this failure on iothub_client_sample_mqtt_websockets. 

Here are the log traces for both samples running on **Windows 10**, using **schannel for TLS**:

```c
Starting the IoTHub client sample AMQP over WebSockets...
Info: IoT Hub SDK for C, version 1.1.10
Info: Retry policy set (5, timeout = 0)
Error: Time:Wed Apr  5 08:44:03 2017 File:C:\Code\azure-iot-sdk-c\c-utility\src\uws_client.c Func:_uws_client_set_option Line:1851 xio_setoption failed.
Error: Time:Wed Apr  5 08:44:03 2017 File:C:\Code\azure-iot-sdk-c\c-utility\src\wsio.c Func:_wsio_setoption Line:688 Setting the option TrustedCerts failed
Error: Time:Wed Apr  5 08:44:03 2017 File:C:\Code\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_SetOption Line:1804 transport failed setting option 'TrustedCerts' (xio_setoption failed)
Error: Time:Wed Apr  5 08:44:03 2017 File:C:\Code\azure-iot-sdk-c\iothub_client\src\iothub_client_ll.c Func:_IoTHubClient_LL_SetOption Line:1512 underlying transport failed, returned = IOTHUB_CLIENT_ERROR
Error: Time:Wed Apr  5 08:44:03 2017 File:C:\Code\azure-iot-sdk-c\iothub_client\src\iothub_client.c Func:_IoTHubClient_SetOption Line:1349 IoTHubClient_LL_SetOption failed
failure to set option "TrustedCerts"
IoTHubClient_SetMessageCallback...successful.
Info: Transport state changed from AMQP_TRANSPORT_STATE_NOT_CONNECTED to AMQP_TRANSPORT_STATE_CONNECTING
Info: Transport state changed from AMQP_TRANSPORT_STATE_CONNECTING to AMQP_TRANSPORT_STATE_CONNECTED
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
Press any key to exit the application.
Confirmation[0] received for message tracking id = 1 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[1] received for message tracking id = 2 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[2] received for message tracking id = 3 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[3] received for message tracking id = 4 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[4] received for message tracking id = 0 with result = IOTHUB_CLIENT_CONFIRMATION_OK
```


```c
Info: IoT Hub SDK for C, version 1.1.10
Error: Time:Wed Apr  5 08:47:38 2017 File:C:\Code\azure-iot-sdk-c\c-utility\src\uws_client.c Func:_uws_client_set_option Line:1851 xio_setoption failed.
Error: Time:Wed Apr  5 08:47:38 2017 File:C:\Code\azure-iot-sdk-c\c-utility\src\wsio.c Func:_wsio_setoption Line:688 Setting the option TrustedCerts failed
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [3] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [4] for transmission to IoT Hub.
Confirmation[0] received for message tracking id = 0 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[1] received for message tracking id = 1 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[2] received for message tracking id = 2 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[3] received for message tracking id = 3 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[4] received for message tracking id = 4 with result = IOTHUB_CLIENT_CONFIRMATION_OK
```

**Comment by ewertons** [comment]
Could you confirm you see the same behavior for **iothub_client_mqtt_ws_transport** on your end?
