### ISSUE TITLE
Redirection of Azure SDK console output

### ISSUE THREAD

**Issue by ohmyandy** [Azure/azure-iot-sdk-c#1032]
In there a way to redirect Azure SDK console output to say syslog by design?
What would be the best way to do it? The goal is to store the output, for later access at some point.

**Comment by YoDaMa** [comment]
Maybe this SO answer will help:

https://unix.stackexchange.com/questions/124455/linux-how-to-redirect-stdout-stderr-to-logger

For instance, if you are running the convenience sample this would look like:

```bash
home/sdk/iothub_client/samples/iothub_convenience_sample -v 2>&1 | logger &
```

**Comment by TizianoFranzoi** [comment]
We use something like this: 
There is a redirect function in the azure sdk: 

xlogging_set_log_function(azure_log);

void azure_log(LOG_CATEGORY log_category, const char* file, const char* func, int line, unsigned int options, const char* format, ...)
{
    (void)log_category;
    (void)file;
    (void)func;
    (void)line;
    (void)options;
    (void)format;
.... 
}

**Comment by rafilho** [comment]
@ohmyandy, thanks for reporting the question. Please check TizianoFranzoi response above (and @TizianoFranzoi, thanks for contributing to the response). I am closing this for now since it is addressed. Please reopen if necessary.

**Comment by az-iot-builder-01** [comment]
@ohmyandy, @YoDaMa, @TizianoFranzoi, @rafilho, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
