### ISSUE TITLE
Azure-iot-sdk-c build error with Cmake dynamic-library switch

### ISSUE THREAD

**Issue by jaydee11** [Azure/azure-iot-sdk-c#1037]
**SDK Release: 2019-05-16**
**OS Version:**
embedded Poky linux version 3.14.28-generic running on an ARM-based target
gcc version 4.8.2 (GCC)

**Description:**
Build error in crt_abstractions.h (see below) appears when cmake -Dbuild_as_dynamic:BOOL=ON option is used.
No build errors occur when static libraries are built.

**Steps to replicate issue:**
1. Run cmake command
cmake -Duse_prov_client=ON -Dbuild_as_dynamic:BOOL=ON ..

`root@imx6dlsabresd:/src/azure-iot-sdk-c-16-05-2019/cmake-dynamic# cmake -Duse_prov_client=ON -Dbuild_as_dynamic:BOOL=ON ..`
`-- The C compiler identification is GNU 4.8.2`
`-- The CXX compiler identification is GNU 4.8.2`
`-- Check for working C compiler: /usr/bin/cc`
`-- Check for working C compiler: /usr/bin/cc -- works`
`-- Detecting C compiler ABI info`
`-- Detecting C compiler ABI info - done`
`-- Detecting C compile features`
`-- Detecting C compile features - done`
`-- Check for working CXX compiler: /usr/bin/c++`
`-- Check for working CXX compiler: /usr/bin/c++ -- works`
`-- Detecting CXX compiler ABI info`
`-- Detecting CXX compiler ABI info - done`
`-- Detecting CXX compile features`
`-- Detecting CXX compile features - done`
`-- IoT Client SDK Version = 1.3.3`
`-- Provisioning SDK Version = 1.3.3`
`-- Looking for include file stdint.h`
`-- Looking for include file stdint.h - found`
`-- Looking for include file stdbool.h`
`-- Looking for include file stdbool.h - found`
`-- target architecture: ARM`
`-- Performing Test CXX_FLAG_CXX11`
`-- Performing Test CXX_FLAG_CXX11 - Success`
`-- Found OpenSSL: /usr/lib/libssl.so;/lib/libcrypto.so (found version "1.0.1j")`
`-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")`
`-- Checking for module 'libcurl'`
`--   Found libcurl, version 7.35.0`
`-- Found CURL: curl`
`-- target architecture: ARM`
`-- iothub architecture: ARM`
`-- Configuring done`
`-- Generating done`
`-- Build files have been written to: /src/azure-iot-sdk-c-16-05-2019/cmake-dynamic`

2. Run build command
cmake --build .

` root@imx6dlsabresd:/src/azure-iot-sdk-c-16-05-2019/cmake-dynamic# cmake --build .` 
`Scanning dependencies of target parson`
`[  0%] Building C object CMakeFiles/parson.dir/deps/parson/parson.c.o`
`[  0%] Linking C static library libparson.a`
`[  0%] Built target parson`
`Scanning dependencies of target umock_c`
`[  0%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umock_c.c.o`
`[  0%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umock_c_negative_tests.c.o`
`[  1%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umockalloc.c.o`
`[  1%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umockcall.c.o`
`[  1%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umockcallrecorder.c.o`
`[  1%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umocktypename.c.o`
`[  1%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umocktypes.c.o`
`[  2%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umocktypes_bool.c.o`
`[  2%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umocktypes_c.c.o`
`[  2%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umocktypes_stdint.c.o`
`[  2%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umocktypes_charptr.c.o`
`[  3%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umockcallpairs.c.o`
`[  3%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umockstring.c.o`
`[  3%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umockautoignoreargs.c.o`
`[  3%] Building C object deps/umock-c/CMakeFiles/umock_c.dir/src/umock_log.c.o`
`[  4%] Linking C static library libumock_c.a`
`[  4%] Built target umock_c`
`Scanning dependencies of target aziotsharedutil_dll`
`[  4%] Building C object c-utility/CMakeFiles/aziotsharedutil_dll.dir/src/azure_base32.c.o`
`[  4%] Building C object c-utility/CMakeFiles/aziotsharedutil_dll.dir/src/azure_base64.c.o`
`[  4%] Building C object c-utility/CMakeFiles/aziotsharedutil_dll.dir/src/buffer.c.o`
`[  4%] Building C object c-utility/CMakeFiles/aziotsharedutil_dll.dir/src/constbuffer_array.c.o`
`[  5%] Building C object c-utility/CMakeFiles/aziotsharedutil_dll.dir/src/connection_string_parser.c.o`
`In file included from /src/azure-iot-sdk-c-16-05-2019/c-utility/inc/azure_c_shared_utility/map.h:14:0,`
`                 from /src/azure-iot-sdk-c-16-05-2019/c-utility/inc/azure_c_shared_utility/connection_string_parser.h:8,`
`                 from /src/azure-iot-sdk-c-16-05-2019/c-utility/src/connection_string_parser.c:4:`
`/src/azure-iot-sdk-c-16-05-2019/c-utility/inc/azure_c_shared_utility/crt_abstractions.h:55:23: error: two or more data types in declaration specifiers`
` typedef unsigned char _Bool;`
`                       ^`
`/src/azure-iot-sdk-c-16-05-2019/c-utility/inc/azure_c_shared_utility/crt_abstractions.h:55:1: error: useless type name in empty declaration [-Werror]`
` typedef unsigned char _Bool;`
` ^`
`In file included from /src/azure-iot-sdk-c-16-05-2019/c-utility/inc/azure_c_shared_utility/map.h:14:0,`
`                 from /src/azure-iot-sdk-c-16-05-2019/c-utility/inc/azure_c_shared_utility/connection_string_parser.h:8,`
`                 from /src/azure-iot-sdk-c-16-05-2019/c-utility/src/connection_string_parser.c:4:`
`/src/azure-iot-sdk-c-16-05-2019/c-utility/inc/azure_c_shared_utility/crt_abstractions.h:122:2: error: #error unknown (or C89) compiler, provide ISNAN with the same meaning as isnan in C99 standard`
` #error unknown (or C89) compiler, provide ISNAN with the same meaning as isnan in C99 standard`
`  ^`
`cc1: all warnings being treated as errors`
`c-utility/CMakeFiles/aziotsharedutil_dll.dir/build.make:158: recipe for target 'c-utility/CMakeFiles/aziotsharedutil_dll.dir/src/connection_string_parser.c.o' failed`
`make[2]: *** [c-utility/CMakeFiles/aziotsharedutil_dll.dir/src/connection_string_parser.c.o] Error 1`
`CMakeFiles/Makefile2:1093: recipe for target 'c-utility/CMakeFiles/aziotsharedutil_dll.dir/all' failed`
`make[1]: *** [c-utility/CMakeFiles/aziotsharedutil_dll.dir/all] Error 2`
`Makefile:138: recipe for target 'all' failed`
`make: *** [all] Error 2`

**Comment by RivaStyle** [comment]
Ran into the same issue some time ago, it seems that a C/C++ standard declaration is required by CMake.

Try adding these lines to your Makefile to see if it works:
```
	-DCMAKE_C_STANDARD=## \
	-DCMAKE_CXX_STANDARD=## \
```
where ## are the standards for C and C++ (for example, -DCMAKE_C_STANDARD=99 will make the program be compiled against C99 standards).

**Comment by massand** [comment]
Thanks for reporting this and @RivaStyle for your suggestion. I could not reproduce this issue on our end. I tested building the dynamic library using the same cmake flags, with a recent version of GCC (gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609) on Ubuntu 16.04.5 LTS. 

Please update the version of your build infrastructure to meet our well-tested configurations documented here - https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-platform-support#supported-platforms

**Comment by az-iot-builder-01** [comment]
@jaydee11, @RivaStyle, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
