### ISSUE TITLE
Image file gets uploaded in c chars in iothub storage space instead of image file.

### ISSUE THREAD

**Issue by basavarajph** [Azure/azure-iot-sdk-c#1038]
Hi Team,
 I am trying to upload a image file to iothub using device connection string in ios.
I used the sample code provided. I convert image to NSData using UIImagePNGRepresentation api, then I convert that to base64 string and then finally to char* using UTF8string api. 
after that I uploaded that char*(source) to iothub storage, when I see the image in the azure storage account at mentioned destination path in the upload function.
image is available but when i download and try to open, it says file data damaged. 
so please tell me what I am missing ?

Thanks
Basavaraj

**Comment by danewalton** [comment]
Hi @basavarajph 
I assume because you converted the image to base64 and then to UTF8 you would need to do the reverse before you can successfully open it locally on your machine.

**Comment by danewalton** [comment]
@basavarajph I'm going to go ahead and close this for now but if you are still having issues please feel free to open another issue and we will try and help as best we can.

**Comment by az-iot-builder-01** [comment]
@basavarajph, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
