### ISSUE TITLE
Wrong status from IoTHubDeviceClient_LL_GetSendStatus during reconnect

### ISSUE THREAD

**Issue by basyskom-jvoe** [Azure/azure-iot-sdk-c#1039]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Ubuntu 16.04

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2019-05-16

**Protocol**

AMQP

**Describe the Bug**

Hi,

the application I am building is supposed to establish an IoT Hub connection when it is needed and close it after a certain timeout when there are no new messages and after all messages in the queue have been sent (IoTHubDeviceClient_LL_GetSendStatus() returns IOTHUB_CLIENT_SEND_STATUS_IDLE).

As a measure against losing messages when the network goes down, I am resending messages in the confirm callback if the result is IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT or IOTHUB_CLIENT_CONFIRMATION_ERROR.

If the connection stays down long enough for the SDK to run into a timeout and start attempts to reestablish the AMQP connection, the confirm callback is called with result IOTHUB_CLIENT_CONFIRMATION_ERROR. Sending the message again now via IoTHubDeviceClient_LL_SendEventAsync() returns IOTHUB_CLIENT_OK, but IoTHubDeviceClient_LL_GetSendStatus() returns IOTHUB_CLIENT_SEND_STATUS_IDLE.

If the IoT Hub client is destroyed now because my application assumes that there are no pending messages, the confirm callback for the message that has just been put into the queue is called with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY.

I would expect IoTHubDeviceClient_LL_GetSendStatus() to return IOTHUB_CLIENT_SEND_STATUS_BUSY as long as there are messages waiting to be sent, no matter if they were enqueued while the transport is connected or not.
Or is there a different official way to find out if there are any pending messages in the queue?

EDIT: The behavior does not occur with the MQTT transport

**Comment by ewertons** [comment]
This has been root-caused. Indeed there is a bug in the AMQP transport for this scenario.
A PR will follow soon with the fix.

**Comment by ewertons** [comment]
This issue is now fixed.
Please feel free to reopen it if you would like to follow up.
Thanks for contributing to the Azure IoT SDKs.

**Comment by az-iot-builder-01** [comment]
@basyskom-jvoe, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
