### ISSUE TITLE
Unable to cross compile iot c sdk for ppc 

### ISSUE THREAD

**Issue by tikluganguly** [Azure/azure-iot-sdk-c#104]
- **OS and version used:** Ubuntu 14.04 64 bit

- **SDK version used:**  clone of the repo taken today

# Description of the issue:
Hi All,
         I am trying to build the sdk for a PowerPC processor based microcontroller. I do have the toolchain with me. It contains both openssl and libcurl for the target platform. The build seems to be going pretty well. There are object files as well. But there are no final .so file for the project. What am I doing wrong? I have attached the console output. The CMakeError and CMakeOutput log files along with the cmake file I  have used for cross compilation. I hope I have provided all the required info. Please do let me know if I have missed anything

# Console log of the issue:
[buildlog-201703301335.txt](https://github.com/Azure/azure-iot-sdk-c/files/883437/buildlog-201703301335.txt)

[CMakeError.txt](https://github.com/Azure/azure-iot-sdk-c/files/883458/CMakeError.txt)
[CMakeOutput.txt](https://github.com/Azure/azure-iot-sdk-c/files/883460/CMakeOutput.txt)
[ppc-stw.cmake.txt](https://github.com/Azure/azure-iot-sdk-c/files/883461/ppc-stw.cmake.txt)

**Comment by tikluganguly** [comment]
Hi,
   I am guessing that I may need to port the azure c shared utility (https://github.com/Azure/azure-c-shared-utility) to this platform to make sure that the sdk compiles. So I have taken a clone of the same and would try to cross compile it.

Regards
Tiklu

**Comment by tikluganguly** [comment]
Hi Guys,
       I was able to find the static .a files under ./cmake/iotsdk_linux/iothub_client/ . How do I build .so file instead of .a?

Regards
Anirban

**Comment by jebrando** [comment]
Anirban,

Currently our sdk doesn't produce so files, we only produce static libs for all our binaris.  If you want to use the static lib you'll just have to add the -l flag on your build.  Is there a technical reason that you're looking for .so files?

**Comment by czyba** [comment]
@tikluganguly, 
I believe you can build shared libraries by setting the cmake define: `build_as_dynamic`

If you use ccmake in the build directory you can set it to ON. A subsequent call to make will then build .so files instead of .a files. I have not tested this procedure any programs build against the shared libraries however, so I cannot guarantee that linking and running program will work, but it's worth a try.

Kind Regards,
Christopher Czyba

**Comment by tikluganguly** [comment]
@jebrando and @czyba thanks to both of you for your reply. Yes, I can live with .a files for now. I just need one more info. I see a bunch of .a files in the ./azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client folder. For example libiothub_client.a, libiothub_client_amqp_transport.a, libiothub_client_amqp_ws_transport.a,libiothub_client_http_transport.a etc. So  I am assuming that if I am using iothub client with amqp I would need to use both   libiothub_client.a and libiothub_client_amqp_transport.a. 
  Please let me know if my assumption is correct or not.

**Comment by czyba** [comment]
@tikluganguly 

Yes, you most likely need to link the libaziosharedutil.a, as well as the direct dependencies -lssl, -lcrypto and -luuid and possibly -lcurl if you want to use upload_to_blob or the http_protocol. Also be mindful of the order. First client -> transport -> sharedutil -> system libs, otherwise you will most likely encounter undefined symbols.

You could also call the generated makefile in the build directory with `VERBOSE=1` to see the compiler invocations. You can infer the libraries that are required for linking from the compiler invocations for the samples.

Kind Regards,
Christopher Czyba

**Comment by tikluganguly** [comment]
@czyba  
Hi Christopher,

             Thanks for your reply. Following is the command that I am using right now to link the object file.

powerpc-stw-linux-uclibc-g++ azure1.o -L/home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/c-utility/ -L/home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/ -L/opt/powerpc-gcc-4.4.3-uclib/powerpc-stw-linux-uclibc/sysroot/usr/lib/ -L/home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/uamqp -L/home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/serializer -L/home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/umqtt -laziotsharedutil -luamqp -lserializer -lumqtt -liothub_client -liothub_client_amqp_transport -liothub_client_http_transport -lpthread -lssl -lcrypto -liothub_client_amqp_ws_transport -liothub_client_mqtt_ws_transport -oazure1

and the error that I am getting is attached below 
[buildlog-201704031614.txt](https://github.com/Azure/azure-iot-sdk-c/files/891444/buildlog-201704031614.txt)

any idea what I am doing wrong? I am not really an expert in c/c++

Thanks 
Tiklu

**Comment by tikluganguly** [comment]
Hi Guys,

       I made some more changes and instead of g++ now I am using gcc. But I am still getting a lot of errors. The screengrab is attached below. 
[buildlog-201704031634.txt](https://github.com/Azure/azure-iot-sdk-c/files/891487/buildlog-201704031634.txt)

Thanks
Tiklu

**Comment by tikluganguly** [comment]
Hi Guys,
        For compilation I am now stuck here

tiklu@stwbuildrootvm2:~/mazik/clone/Peterson%20IOT%20C$powerpc-stw-linux-uclibc-gcc -Wall -std=c99 -L/opt/powerpc-gcc-4.4.3-uclib/powerpc-stw-linux-uclibc/sysroot/usr/lib/ -L/opt/powerpc-gcc-4.4.3-uclib/powerpc-stw-linux-uclibc/sysroot/lib -luClibc-0.9.33.2  -lpthread -lssl -lcrypto -lcurl -luuid -lm -lwebsockets /home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/c-utility/libaziotsharedutil.a /home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/serializer/libserializer.a /home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/libiothub_client_amqp_transport.a /home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/libiothub_client.a azure1.o -oazure1
azure1.o: In function `SendConfirmationCallback':
azure1.c:(.text+0x54): undefined reference to `IOTHUB_CLIENT_CONFIRMATION_RESULTStrings'
azure1.c:(.text+0xa0): undefined reference to `IoTHubMessage_Destroy'
azure1.o: In function `main':
azure1.c:(.text+0xf0): undefined reference to `platform_init'
azure1.c:(.text+0x122): undefined reference to `AMQP_Protocol'
azure1.c:(.text+0x126): undefined reference to `AMQP_Protocol'
azure1.c:(.text+0x128): undefined reference to `IoTHubClient_LL_CreateFromConnectionString'
azure1.c:(.text+0x174): undefined reference to `IoTHubClient_LL_SetOption'
azure1.c:(.text+0x194): undefined reference to `sprintf_s'
azure1.c:(.text+0x1b8): undefined reference to `IoTHubMessage_CreateFromByteArray'
azure1.c:(.text+0x268): undefined reference to `IoTHubClient_LL_SendEventAsync'
azure1.c:(.text+0x298): undefined reference to `IoTHubClient_LL_DoWork'
azure1.c:(.text+0x2a0): undefined reference to `ThreadAPI_Sleep'
azure1.c:(.text+0x2a8): undefined reference to `IoTHubClient_LL_Destroy'
azure1.c:(.text+0x2ac): undefined reference to `platform_deinit'
collect2: ld returned 1 exit status

Any Ideas would be much appreciated.

Regards
Tiklu

**Comment by tikluganguly** [comment]
Guys,
        Finally, I was able to compile the code it turned out that I was putting the library path wrong. Following is the code that worked for me.

powerpc-stw-linux-uclibc-gcc -std=c99 -I/opt/powerpc-gcc-4.4.3-uclib/powerpc-stw-linux-uclibc/sysroot/usr/include -I/opt/powerpc-gcc-4.4.3-uclib/powerpc-stw-linux-uclibc/sysroot/include -I/home/tiklu/azure/azure-iot-sdk-c/c-utility/inc -I/home/tiklu/azure/azure-iot-sdk-c/iothub_client/inc  -c -o azure1.o azure1.c

powerpc-stw-linux-uclibc-gcc -Wall -std=c99 -L/opt/powerpc-gcc-4.4.3-uclib/powerpc-stw-linux-uclibc/sysroot/usr/lib/ -L/opt/powerpc-gcc-4.4.3-uclib/powerpc-stw-linux-uclibc/sysroot/lib -luClibc-0.9.33.2  -lpthread -lssl -lcrypto -lcurl -luuid -lm -lwebsockets azure1.o /home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/libiothub_client_amqp_transport.a /home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/libiothub_client.a /home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/serializer/libserializer.a /home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/uamqp/libuamqp.a /home/tiklu/azure/azure-iot-sdk-c/cmake/iotsdk_linux/c-utility/libaziotsharedutil.a -oazure1 

Thanks for your support
Tiklu
