### ISSUE TITLE
Issue while running, iothub_client_sample_mqtt_dm

### ISSUE THREAD

**Issue by Nishchayg7** [Azure/azure-iot-sdk-c#1045]
![image](https://user-images.githubusercontent.com/20509941/59190556-a28ec200-8b9a-11e9-8920-1b47450388dc.png)

**Comment by danewalton** [comment]
Hi @Nishchayg7 did you try running it with sudo? The error seems like it stems from that.

**Comment by danewalton** [comment]
Hey @Nishchayg7 I'm going to go ahead and close this for now for inactivity. If you have any other issues or questions feel free to open another issue.

**Comment by az-iot-builder-01** [comment]
@Nishchayg7, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
