### ISSUE TITLE
Cross compile Azure IOT SDK c for silabs gecko platform (WGM160P)

### ISSUE THREAD

**Issue by gennarinoca** [Azure/azure-iot-sdk-c#1048]
I need too cross compile azure-iot-sdk-c for an arm target (WGM160P Wi-Fi). I created the toolchain.cmake as advised by @markrad, I entered into a cmake folder and used command:

cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=..\toolchain.cmake ..

First question:
should I use cygwin or normal cmd prompt in Win 10 to cross compile?

The cmake stops with the following errors:

```
The C compiler identification is GNU 7.2.1
The CXX compiler identification is GNU 7.2.1
Check for working C compiler: C:/Users/MyUser/Documents/gecko/sdk-wgm160p/4.0.18-2139/tools/toolchains/gcc/arm/win32/gcc.exe
Check for working C compiler: C:/Users/MyUser/Documents/gecko/sdk-wgm160p/4.0.18-2139/tools/toolchains/gcc/arm/win32/gcc.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Users/adibacco/Documents/gecko/sdk-wgm160p/4.0.18-2139/tools/toolchains/gcc/arm/win32/gcc.exe"

  is not able to compile a simple test program.

  It fails with the following output:
    Change Dir: C:/Users/MyUser/Documents/gecko/azure-iot-sdk-c/cmake/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/Users/MyUser/Documents/gecko/sdk-wgm160p/4.0.18-2139/tools/common/win32/make.exe cmTC_c414a/fast
    /common/win32/make -f CMakeFiles/cmTC_c414a.dir/build.make CMakeFiles/cmTC_c414a.dir/build
    make[1]: Entering directory '/cygdrive/c/Users/MyUser/Documents/gecko/azure-iot-sdk-c/cmake/CMakeFiles/CMakeTmp'
    make[1]: /bin/sh: Command not found
    make[1]: *** [CMakeFiles/cmTC_c414a.dir/build.make:65: CMakeFiles/cmTC_c414a.dir/testCCompiler.c.o] Error 127
    make[1]: Leaving directory '/cygdrive/c/Users/MyUser/Documents/gecko/azure-iot-sdk-c/cmake/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_c414a/fast] Error 2

```

I attach toolchain.cmake

[toolchain.cmake.txt](https://github.com/Azure/azure-iot-sdk-c/files/3275458/toolchain.cmake.txt)

**Comment by markrad** [comment]
Looking at your toolchain file, the fact that it has win32 in the directory path would lead me to believe that your cross compiler is designed to run on Windows. I was unable to find the toolchain for myself. Possibly it is not public. However, you are using the CMake generator of "Unix Makefiles" which causes CMake to try and use make as its build tool. It also apparently tried to find a Linux shell too. You could try using a Windows generator such as -G "Visual Studio 16 2019" or just let it default by not specifying a generator. You will likely need to do this in a VS developer command prompt. 

Typically I cross compile in a Linux environment. You don't even need a Linux VM. The Linux subsystem for Windows will usually be sufficient for this type of operation. If there is a Linux cross compile toolchain available I would suggest you try that instead.

If the toolchain is public please post a link to it. Thanks.

_Mark Radbourne MSFT_

**Comment by jebrando** [comment]
Thank you @markrad I believe that under the Linux environment cross compiling is a lot easier.

**Comment by az-iot-builder-01** [comment]
@gennarinoca, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
