### ISSUE TITLE
Unable to use virtual folder in destinationFileName with IoTHubClient_LL_UploadToBlob()

### ISSUE THREAD

**Issue by tobiasBoren** [Azure/azure-iot-sdk-c#105]
I'm running on RPi 3, cross compiled azure-iot-sdk-c with arm-linux-gnueabihf-gcc (Raspbian 4.9.2-10) 4.9.2 on WSL.

- **OS and version used:** <VERSION> Ubuntu 14.04 / Raspbian 8.0 

- **SDK version used:** <VERSION> 1.1.10

# Description of the issue:
 Upload to blob fails when destination file name includes a virtual folder e.g. "testfolder/hello_world.txt". The sample application iothub_client_sample_upload_to_blob works as expected with a single file name "hello_world.txt", but fails with a folder prefix "testfolder/hello_world.txt".   

# Code sample exhibiting the issue:
 
`IoTHubClient_LL_UploadToBlob(iotHubClientHandle, "testfolder/hello_world.txt", (const unsigned char*)HELLO_WORLD, sizeof(HELLO_WORLD) - 1)`

# Console log of the issue:

Info: IoT Hub SDK for C, version 1.1.10
Error: Time:Mon Apr  3 08:36:34 2017 File:/mnt/p/SDKS/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:594 Failure in HTTP communication: server reply code is 404
Info: HTTP Response:
Error: Time:Mon Apr  3 08:36:34 2017 File:/mnt/p/SDKS/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_step1and2 Line:363 HTTP code was 404
Error: Time:Mon Apr  3 08:36:34 2017 File:/mnt/p/SDKS/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_Impl Line:790 error in IoTHubClient_LL_UploadToBlob_step1
hello world failed to upload

**Comment by olivierbloch** [comment]
Hi @tobiasBoren , I confirm that this is not a feature that we support just yet in our C SDK for FileUpload. I am adding it to our backlog, but I am afraid we won't be able to get to it before a couple month at least. Is it something blocking in your project development or can you live with what we have for some time?

**Comment by thomas-t1** [comment]
This feature is supported in the C# SDK, so it means that this issue is actually an incompatibility between the C# and the C SDK, so I would argue that this issue is important to address to enable cross-platform interop/uniformity. We already use a blob name format which includes virtual folders in our existing data processing pipeline, so this means that changing to IoT hub and the C SDK would require changing the data processing pipeline, which is running on both .NET and Python

**Comment by tobiasBoren** [comment]
Thank you for your quick reply, @olivierbloch . We're already using virtual folders from other nodes in our system, running .NET C# SDK.  As @thomas-t1 commented, this limits the uniformity in the system to what's supported in the C SDK. 

Priority of this feature would be much appreciated, as the C SDK is most suited for cross-platform. As an alternative I'll pay attention to the release of .NET Core support for the C# SDK.

**Comment by olivierbloch** [comment]
Hi @tobiasBoren 
I perfectly agree with you that it is high priority to align the SDKs. Note thought that for the other languages we use the Azrue Storage SDKs which have full support for all functionality and are maintained by the Azure Storage team, while for the C SDK we had to develop one ourselves (IoT Hub SDK team) as the Storage team doesn't have a C SDK and don't intend to publish one at this point.
We definitively intend to improve our Azure Storage support for C and as mentioned have this in our backlog. That now needs to be prioritized against other features that we need to tackle.

Regarding the C# SDK support for .Net Core, it is work in progress and should be available real soon. You can actually already start playing with it using the code version of the library (look for the .Net Standard version of the lib in the device solution as we have done the work but have not pushed this to the NuGet package as we need some more testing. Feel free to go play cloning the C# SDK and let us know if you see anything off when using it in a .Net Core app.

**Comment by olivierbloch** [comment]
Now tracked on [User Voice](https://feedback.azure.com/forums/321918-azure-iot/suggestions/19109176-support-virtual-folders-for-blob-upload-in-the-c-d). Please vote the feature up there.
Thanks
