### ISSUE TITLE
provisioningclient with tpm: deps of libhsm_security_client.a don't get installed: libutpm.a, libmsr_riot.a

### ISSUE THREAD

**Issue by mlilien** [Azure/azure-iot-sdk-c#1052]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

alpine:edge arm7hf Docker build; musl libc

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2019-05-16

**Protocol**

hsm_sastoken

**Describe the Bug**

If i build the sdk with 
```
cmake -DCMAKE_INSTALL_PREFIX=/usr -Duse_prov_client:BOOL=ON -Dhsm_type_sastoken:BOOL=ON 
```` 
the dependcies of **libhsm_security_client.a: libutpm.a and libmsr_riot.a** don't get installed.

**Comment by truschival** [comment]
I can confirm this behavior. In our build environment I have a post build script that copies the files to the staging environment

**Comment by massand** [comment]
Thanks for reporting! There were some make install changes that occurred in our repos in that release. I assume this was working prior to 2019-05-16?

**Comment by mlilien** [comment]
@massand I dont know. I did not use older versions of the sdk.

**Comment by jebrando** [comment]
I have a fix for this error and will be committed within the few days.

**Comment by az-iot-builder-01** [comment]
@truschival, @massand, @mlilien, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by SchroterQuentin** [comment]
@jebrando Did you push your fixes ? We are facing the same issue. Even if we copy the libraries it needs the header files to work.

@massand we try with the 2019-05-16 SDK and are facing the same issue.
