### ISSUE TITLE
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md needs to be updated for VS2019

### ISSUE THREAD

**Issue by Almagnus1** [Azure/azure-iot-sdk-c#1053]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Doc bug

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Azure IoT C SDK head version as seen on 2019 June 17 at 17:29 CST

**Describe the Bug**

https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md needs to be updated to include information on VS 2019, as it only goes up to VS 2017.

**Comment by massand** [comment]
Thanks for reporting. PR #1046 will be moved in shortly to address this. Closing the issue.

**Comment by az-iot-builder-01** [comment]
@Almagnus1, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
