### ISSUE TITLE
After device is deprovisioned from cloud, azure library is still trying to reconnect and therefore consuming huge amount of data.  

### ISSUE THREAD

**Issue by nitu011** [Azure/azure-iot-sdk-c#1061]
After device is deprovisioned from cloud, azure library is still trying to reconnect and therefore consuming huge amount of data.  How to handle this scenario , do we need to call any specific azure api for closing connection . Right now I am only getting connection status as unauthenticated and reason Bad Credential.

Thanks

**Comment by massand** [comment]
@nitu011 thanks for your question. 

To explain, I assume the scenario is the iothub_ll_telemetry_sample using MQTT protocol. The current SDK behavior for MQTT is as follows (assuming the device is disabled but IotHubDeviceClient_LL_DoWork is being invoked continuously on the same device client handle):
- The default retry policy is exponential backoff (with no maximum). If the policy is changed to something else (like fixed interval), then the device will attempt to reconnect more often than the default.
- The SDK usually invokes the connection status callback method (passed in using IoTHubDeviceClient_LL_SetConnectionStatusCallback) each time that retry occurs. It sends events in the following order after device is disabled:
IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL
IOTHUB_CLIENT_CONNECTION_NO_NETWORK
IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL
IOTHUB_CLIENT_CONNECTION_NO_NETWORK
IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL
IOTHUB_CLIENT_CONNECTION_NO_NETWORK

.. followed by the following status after each retry thereafter ...

IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED
IOTHUB_CLIENT_CONNECTION_NO_NETWORK
IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED
IOTHUB_CLIENT_CONNECTION_NO_NETWORK
IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED
IOTHUB_CLIENT_CONNECTION_NO_NETWORK

The best way to handle this is to signal the device application (using some other means such as an app service) to recreate the device client handle. This will help reduce your data intake. 

Hope that helps.

**Comment by az-iot-builder-01** [comment]
@nitu011, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
