### ISSUE TITLE
Time warp during DPS-Connect causes parsing error

### ISSUE THREAD

**Issue by truschival** [Azure/azure-iot-sdk-c#1066]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
* Target Linux 4.14.115-rt
* Azure IoT SDK-C Release 2019-03.18
* Cross Compiled for arm-linux-gnueabihf
* gcc version 7.2.1 20171011 (Linaro GCC 7.2-2017.11) 
* Openssl 1.1.1b

**Protocol**
DPS authentication using TPM individual enrollments.  

**Describe the Bug**
It may happen the device boots with the defaul unix date 1970-01-01. tlsdated and/or ntp will later set the time to the correct time. 
The connection to the DPS fails (as expected) with ``PROV_DEVICE_RESULT_TRANSPORT`` because the certificat is not valid.
If the time is set to the current time some time later the connection to the DPS is established (``PROV_DEVICE_REG_STATUS_CONNECTED``) correctly.  However in the register_device_callback we receive a ``PROV_DEVICE_PARSING`` error, and will not get assigned a deviceid or iot-hub.

We can reproduce the issue using the ``date `` command:

1. Set date to past:  ``date -s "2005-02-03 03:02:12"``
2. Start the daemon that should connect to DPS and IOT hub. 
3. Time warp to present: ``date -s "2019-06-17 09:00:01"``

We see this log output from the IoT-SDK stack:
```
Error: Time:Mon Jun 17 09:00:11 2019 File:/home/me/platform/firmware/.builds/festo_zynq_cpx-iot/azure-iot-sdk-complete/azure-iot-sdk-complete-2019-03-18/provisioning_client/src/prov_device_ll_client.c Func:prov_transport_process_json_reply Line:323 failure retrieving json auth key value
Error: Time:Mon Jun 17 09:00:11 2019 File:/home/me/platform/firmware/.builds/festo_zynq_cpx-iot/azure-iot-sdk-complete/azure-iot-sdk-complete-2019-03-18/provisioning_client/src/prov_transport_http_client.c Func:prov_transport_http_dowork Line:941 Unable to process registration reply.
Error: Time:Mon Jun 17 09:00:11 2019 File:/home/me/platform/firmware/.builds/festo_zynq_cpx-iot/azure-iot-sdk-complete/azure-iot-sdk-complete-2019-03-18/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:572 Failure retrieving data from the provisioning service
```

**Comment by jebrando** [comment]
I will dig into this next week, does it matter when in the process of connect that the time is adjusted?

**Comment by truschival** [comment]
@jebrando - I couldn't control setting the time at a definied time point. 
I just tried to do it as quickly as possible on the command line of my device. I guess it doesn't really matter when exactly the timewarp occurs, but I guess it has to be after connecting to the DPS and before being assinged an IoT-Hub.

**Comment by CIPop** [comment]
I've tried it and got the following certificate validation error:

```
Provisioning API Version: 1.6.0
Iothub API Version: 1.6.0
Error: Time:Thu Feb  3 03:02:17 2005 File:/home/crispop/c-sdk/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:724 error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
```

This is expected: it's mandatory to have the real-time clock configured prior to using any of our Azure IoT clients. This is required by the TLS stack when verifying the validity of the server certificate chains. Ideally the service should only be started after NTP finished syncing the time and date. 

In case this isn't possible, the application should exit and allow the service manager to restart it: our provisioning client does not support retries.
