### ISSUE TITLE
IoTHubDeviceClient_SendReportedState / IoTHubDeviceClient_SendEventAsync only allows one callback for all reports

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1068]
(Note that below applies to `IoTHubDeviceClient_SendEventAsync` as well by analogy)

When invoking `IoTHubDeviceClient_SendReportedState` (or its module cousin), we only record the last callback function.

Consider for example

```c
IoTHubClientCore_SendReportedState(handle, "state-data-1",..., callback1);
IoTHubClientCore_SendReportedState(handle, "state-data-2",..., callback2);
```

`IoTHubClientCore_SendReportedState` (which does all the work) is saving the callback function at a handle-wide level, namely
```c
iotHubClientInstance->reported_state_callback = reportedStateCallback;
```

This makes the code above not work, because the `callback2` will end up over-writing `callback1` in the per-handle.  While this is OK for stuff like taking incoming device methods and properties to just have 1 dispatcher per handle, for device initiated sending there maybe legit reasons for having different callbacks for different types of reported properties / telemetry.

Note that the `LL` layer does this correctly - it tracks the callback function per the context (e.g. `IOTHUB_DEVICE_TWIN`) that is created per sending property.

**Comment by alexmrtn** [comment]
Hi,

Do you have a estimated time / delivery to fix this bug?

Can you confirm that that the LL API does the correct job for both SendReportedState and SendEventAsync ?

This bug is quite important for us as we use the threaded (convenient) API and we do required to have separate callback for each messages/reporting

Thanks,
Alexis.

**Comment by jspaith** [comment]
ETA is very soon :).  https://github.com/Azure/azure-iot-sdk-c/pull/1100

Feel free to pre-test if you have a chance or offer PR feedback as it's always welcome.

**Comment by jspaith** [comment]
Fixed and merged into master.

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
