### ISSUE TITLE
Cross compile with WSL fail

### ISSUE THREAD

**Issue by ericmitt** [Azure/azure-iot-sdk-c#1072]
I follow the steps in the cross compile tuto, but from WSL.
The following command fail with a permission denied:
rsync -rl --safe-links pi@192.168.0.124:/{lib,usr} .
Do you have advice for using wsl in this case.
==============
ericmitt@SurfaceEM02:/mnt/c/code/azure-iot-sdk-c/RPitools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf$ rsync -rl --safe-links pi@192.168.0.124:/{lib,usr} .
pi@192.168.0.124's password:
rsync: rename "/mnt/c/code/azure-iot-sdk-c/RPitools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/lib/udev/.hwdb.bin.zrouXM" -> "lib/udev/hwdb.bin": Permission denied (13)
rsync: send_files failed to open "/usr/lib/cups/backend/vnc": Permission denied (13)

**Comment by markrad** [comment]
The directory /usr/lib/cups/backend/vnc appears to only be readable by root. However, you don't need that directory so simply exclude it in the rsync command. See this page for examples: https://linoxide.com/linux-how-to/linux-rsync-examples-exclude-files-directories/.

_Mark Radbourne MSFT_

**Comment by cindydeng1998** [comment]
Hello Mark,

The cross compile doc has been updated to include a new rsync command. Thank you for sharing the reference link! Let us know if you run into anything else during the cross compiling process

**Comment by az-iot-builder-01** [comment]
@cindydeng1998, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
