### ISSUE TITLE
after sas-token expiry device is not able to reconnect again

### ISSUE THREAD

**Issue by nitu011** [Azure/azure-iot-sdk-c#1074]
Hi ,
I am using following version of azure iot sdk C :
git://github.com/Azure/azure-iot-sdk-c.git;rev=290d45da2751245b5c5d43aac4a2850e0679a7da
git://github.com/Azure/azure-c-shared-utility.git;rev=8290634e5c2d005643d5a7dd5f8e65ad7a4353c2
git://github.com/Azure/azure-umqtt-c.git;rev=65b6c9ef58c3f65ff48e95e295d4d13761fc4324
git://github.com/Azure/azure-uamqp-c.git;rev=6f562bf9283ebed84bee19ad71b536b10dc71890
git://github.com/kgabis/parson.git;rev=bef4969d258d5bcce0d686b7bf514550e2ac346d
git://github.com/Azure/azure-uhttp-c.git;rev=6e12a591ecd9e606399b12097fab4ef5e3bbd3c8

Protocol : AMQP WS
I am getting sas-token from azure only  and it has expiry time of 20 minutes .Till 20 minutes , all events are going fine but after 20 minutes getting "sas token invalid" error:
Error: Time:Wed Jun  5 10:46:31 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:create_and_put_SAS_token_to_cbs Line:270 sas token is invalid.

My first question is sas-token is not refreshed automatically from azure ?
I also tried to regenerate token but still its complaining same error

Error: Time:Mon Jun 10 09:39:42 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_twin_messenger.c Func:on_amqp_messenger_subscription_changed_callback Line:1640 Unexpected AMQP messenger state (xxxxxxxx, TWIN_MESSENGER_STATE_STARTED, 0)
Error: Time:Mon Jun 10 09:39:42 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_device.c Func:device_do_work Line:1079 Device 'xxxxxxxxx' is started but TWIN messenger reported unexpected state 1
Error: Time:Mon Jun 10 09:39:43 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:on_cbs_put_token_complete_callback Line:168 CBS reported status code 0, error: '(null)' for put-token operation for device 'xxxxxxxxxxxx'
Error: Time:Mon Jun 10 09:39:43 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_connection.c Func:on_cbs_error Line:160 CBS Error occured
Error: Time:Mon Jun 10 09:39:43 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:1132 Failed performing DoWork for device 'xxxxxxxxxxxxxxx' (device reported state 4; number of previous failures: 1)
Error: Time:Mon Jun 10 09:39:43 2019 File:/usr/src/debug/azure-uamqp-c/1.2.4-r0/git/src/cbs.c Func:cbs_put_token_async Line:483 put token called while closed or in error
Error: Time:Mon Jun 10 09:39:43 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:put_SAS_token_to_cbs Line:208 Failed putting SAS token to CBS for device 'xxxxxxxxxxxxxxx' (cbs_put_token failed)
Error: Time:Mon Jun 10 09:39:43 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:create_and_put_SAS_token_to_cbs Line:313 Failed putting SAS token to CBS
Error: Time:Mon Jun 10 09:39:43 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:authentication_do_work Line:658 Failed authenticating device 'xxxxxxxxxxxx' using device keys
Error: Time:Mon Jun 10 09:39:43 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:1132 Failed performing DoWork for device 'xxxxxxxxx' (device reported state 4; number of previous failures: 2)

I really need the support to fix this issue

**Comment by massand** [comment]
@nitu011 Thanks for reporting the issue. You will need to regenerate the SAS token manually and recreate the handle in your scenario. When the SAS token is no longer valid, IoTHub will no longer allow you to operate over the existing AMQP link. You would need to create a new device client handle with the new SAS token and handle the reconnection yourself. 
The only time the SDK auto generates a new SAS token is when you use other credential types - symmetric key or X.509 - where the SAS token is obtained from IoTHub with default TTL 1 hour. The SDK performs the SAS token auto-refresh process over the existing link at the 45 minute mark. Failing that auto-refresh, the link is re-established again via the retry logic (which performs the full reconnect).

**Comment by az-iot-builder-01** [comment]
@nitu011, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by nitu011** [comment]
@massand, thanks for the response 
right now before reconnecting , I am destroying the existing client like this :
  ::IoTHubClient_Destroy(this->iothub_client_handle);
  ::platform_deinit();
then creating new instance of iothub_client_handle and registering all the callbacks again.
Is there anything else I need to do cleanup before reconnecting ?
