### ISSUE TITLE
PROV_DEVICE_RESULT_DEV_AUTH_ERROR when use DPS with openssl generated X509 certificates and custom_hsm instance

### ISSUE THREAD

**Issue by LaptevPasha** [Azure/azure-iot-sdk-c#1075]
- OS and version used: Ubuntu 18.04.02 LTS

- SDK version used: master

**Description of the issue:**

The idea is to use custom self-signed X509 certificate for device individual enrollment similar to this article: https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509

I built prov_dev_client_sample linked with custom_hsm static library.
Custom_hsm has hardcoded X509 cerificate and private key. 

That's how I build prov_dev_client_sample with custom_hsm:
`cmake clean .
cmake -Duse_prov_client:BOOL=ON -Dhsm_custom_lib=~/azure-iot-sdk-c/cmake/provisioning_client/samples/custom_hsm_example/libcustom_hsm_example.a ..
cmake --build .`

Certificate and p.k. were generated using openssl:
1. Generate root key and X509 cert
openssl req -x509 -newkey rsa:2048 -keyout root_private.pem -nodes -days 3650 -out root_cert.pem
2. Create verification key
openssl genrsa -out verification.key 2048
3. Upload the Certificate to Device Provisioning Service and generate verification code
openssl req -new -key verification.key -out verification.csr
verification code is used as "Common Name"
4. Create the proof of possession certificate and upload it to Azure DPS
openssl x509 -req -in verification.csr -CA root_cert.pem -CAkey root_private.pem -CAcreateserial -out verificationCert.pem -days 1024 -sha256

as it's described here: https://www.silabs.com/community/wireless/wi-fi/knowledge-base.entry.html/2019/04/16/working_with_azured-EnPC

I'm using individual enrollment, Azure DPS device ID is the same as X509 certificate common name.
MQTT is used, ID scope is correct.
After running the code I'm getting PROV_DEVICE_RESULT_DEV_AUTH_ERROR. As I understand it means my certificate is incorrect.

Could you please specify what I should exactly do for getting valid certificate and how it must be uploaded to Azure DPS for getting correct individual enrollment ?

Also I tried to delete verified x509 certificate from Azure DPS because it's not necessary to have it there for individual enrollment but result is the same.

**Full output:**
Provisioning API Version: 1.3.3

Registering Device

Error: Time:Thu Jul  4 18:22:56 2019 File:/home/pavel/azure-iot-sdk-c/provisioning_client/src/prov_tr
ansport_mqtt_common.c Func:mqtt_operation_complete_callback Line:208 Connection Not Accepted: 0x5: Not Authorized
Error: Time:Thu Jul  4 18:22:56 2019 File:/home/pavel/azure-iot-sdk-c/provisioning_client/src/prov_tr
ansport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Thu Jul  4 18:22:56 2019 File:/home/pavel/azure-iot-sdk-c/provisioning_client/src/prov_de
vice_ll_client.c Func:on_transport_registration_data Line:763 Failure retrieving data from the provis
ioning service

Failure registering device: PROV_DEVICE_RESULT_DEV_AUTH_ERROR
Press enter key to exit:

**Comment by LaptevPasha** [comment]
Provisioning works with PowerShell script generated certificate, which use elliptic curves but I don't know why it doesn't work with OpenSSL generated ones RSA based.

**Comment by jebrando** [comment]
@LaptevPasha Is the certificate a device certificate or a CA certificate?  DPS does not allow Certificate Authority certs.  Can you please check this and let me know.  I'll have time to run these commands mid next week and see if I can see something.

**Comment by az-iot-builder-01** [comment]
@LaptevPasha, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by LaptevPasha** [comment]
Device certificate, shure

**Comment by LaptevPasha** [comment]
@jebrando

**Comment by wesmc7777** [comment]
The following fix to the bash scripts that use OpenSSL should fix the problem

[https://github.com/Azure/azure-iot-sdk-c/pull/1519](https://github.com/Azure/azure-iot-sdk-c/pull/1519)
