### ISSUE TITLE
RDP over device streaming connection issue.

### ISSUE THREAD

**Issue by vsanjeevagowda-s** [Azure/azure-iot-sdk-c#1077]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
OS: Ubuntu 16.04 
gcc: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
cmake version 3.5.1
xrdp: Version 0.6.1 (sudo apt-get install xrdp)
desktop environment used : lxde-core (sudo apt-get install lxde-core)

**SDK Version (Please Give Commit SHA if Manually Compiling)**

$ git clone https://github.com/Azure/azure-iot-sdk-c.git --recursive -b public-preview.
Refered:
https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-device-streams-proxy-c

**Describe the Bug**
Trying RDP over the device stream.

Code used:
1. Device Proxy: azure-iot-c-sdk 
  reference: https://github.com/Azure/azure-iot-sdk-c/blob/public-preview/iothub_client/samples/iothub_client_c2d_streaming_proxy_sample/iothub_client_c2d_streaming_proxy_sample.c

2. Node Proxy (Running on the service side(nodejs socket server)): 
  reference: 
    1. https://github.com/Azure-Samples/azure-iot-samples-node/archive/streams-preview.zip
    2. azure-iot-samples-node-streams-preview/iot-hub/Quickstarts/device-streams-service/proxy.js

Steps followed (Device Proxy):
- /* Paste in the your iothub connection string  */
static const char* connectionString = "device connection string";
static const char* localHost = "127.0.0.1"; // Address of the local server to connect to.
static const int localPort = 3389;

Edited the below file with above code
https://github.com/Azure/azure-iot-sdk-c/blob/public-preview/iothub_client/samples/iothub_client_c2d_streaming_proxy_sample/iothub_client_c2d_streaming_proxy_sample.c

- Followed steps same as in  https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-device-streams-proxy-c

Steps followed (Service Local Proxy):

- azure-iot-samples-node-streams-preview/iot-hub/Quickstarts/device-streams-service/proxy.js

- changed port to 2222

- updated IOT_HUB_STRING 
   var client = ServiceClient.fromConnectionString('IOT hub string');

-  $node proxy.js
- Followed steps same as in  https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-device-streams-proxy-c

**Console Logs**

-> 02:29:18 PINGREQ
<- 02:29:18 PINGRESP
on_ws_peer_closed (Code: 1001, Data: Connection timeout)
Error: Time:Wed Jul 10 02:29:20 2019 File:/home/venku/Desktop/azure-iot-sdk-c/c-utility/adapt
ers/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_
received_bytes.
Error: Time:Wed Jul 10 02:29:20 2019 File:/home/venku/Desktop/azure-iot-sdk-c/c-utility/adapt
ers/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_receive
d_bytes.
-> 02:29:20 DISCONNECT
Press any key to continue

$ip=0.0.0.0 | PAYLOAD_LEN: 0
Received stream request (TestStream1)
-> 03:09:42 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $io
thub/streams/res/200/?$rid=1
Client connected to the streaming gateway (WS_OPEN_OK)
Reporting traffic statistics every 10 seconds.
[2019-07-10 03:09:45 UTC+0000] Network traffic (in bytes) (sent=11; received=481)
[2019-07-10 03:09:55 UTC+0000] Network traffic (in bytes) (sent=23966; received=1435)
Error: Time:Wed Jul 10 03:09:56 2019 File:/home/venku/Desktop/azure-iot-sdk-c/c-utility/adapt
ers/socketio_berkeley.c Func:socketio_dowork Line:998 Socketio_Failure: Receiving data from e
ndpoint: errno=104.
on_ws_error (WS_ERROR_UNDERLYING_IO_ERROR)
-> 03:09:56 DISCONNECT

**Comment by gregman-msft** [comment]
@vsanjeevagowda-s Thanks for reporting this issue. We've had a few fixes on device streaming that could have caused this issue, can you please retry with the latest version of the device streaming public preview branch?

**Comment by mms-** [comment]
Any idea when Device Streams will go out of preview?

**Comment by ewertons** [comment]
Hi @mms- , unfortunately we have other high-priority features being completed at this moment, and we have no ETA for when device streaming will go GA. Thanks for checking it out.

**Comment by ewertons** [comment]
According to our planning, Device Streaming might have a release date defined within the first semester of 2021.

If you would like to follow up on this matter please feel free to file a new issue.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@vsanjeevagowda-s, @mms-, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by kasper112** [comment]
@ewertons 

According to our planning, Device Streaming might have a release date defined within the first semester of 2021.

If you would like to follow up on this matter please feel free to file a new issue.
Thanks,
Azure IoT SDK Team.

Any news on this ?

**Comment by kasper112** [comment]
@ewertons @ewinnerMSFT bump
