### ISSUE TITLE
after sas token expired ,application is crashed when there is no network

### ISSUE THREAD

**Issue by nitu011** [Azure/azure-iot-sdk-c#1080]
Error: Time:Mon Jun 10 17:05:42 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:1132 Failed performing DoWork for device '98d95e84-0c18-4f18-9471-c5c3dd5a554a' (device reported state 5; number of previous failures: 4)
Error: Time:Mon Jun 10 17:05:42 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_DoWork Line:1611 Device '98d95e84-0c18-4f18-9471-c5c3dd5a554a' reported a critical failure; connection retry will be triggered.
Info: Preparing transport for re-connection
Error: Time:Mon Jun 10 17:05:42 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransportamqp_methods.c Func:iothubtransportamqp_methods_unsubscribe Line:819 unsubscribe called while not subscribed
Error: Time:Mon Jun 10 17:05:42 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:on_cbs_put_token_complete_callback Line:168 CBS reported status code 0, error: '(null)' for put-token operation for device '98d95e84-0c18-4f18-9471-c5c3dd5a554a'
Error: Time:Mon Jun 10 17:05:42 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:on_cbs_put_token_complete_callback Line:168 CBS reported status code 0, error: '(null)' for put-token operation for device '98d95e84-0c18-4f18-9471-c5c3dd5a554a'
Error: Time:Mon Jun 10 17:05:42 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:on_cbs_put_token_complete_callback Line:168 CBS reported status code 0, error: '(null)' for put-token operation for device '98d95e84-0c18-4f18-9471-c5c3dd5a554a'
Error: Time:Mon Jun 10 17:05:42 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:on_cbs_put_token_complete_callback Line:168 CBS reported status code 0, error: '(null)' for put-token operation for device '98d95e84-0c18-4f18-9471-c5c3dd5a554a'

After this , application crashed with segmentation fault

**Comment by nitu011** [comment]
I am using  amqp WS protocol and mobile hotspot for network connection
When the device is connected with internet , its throwing error 
/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:1132 Failed performing DoWork for device 'xxxxxxx' (device reported state 4; number of previous failures: 0)
But after this , if network is interrupted , state chanegs to 5 
Error: Time:Mon Jun 10 14:20:26 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-2019 Jun 10 14:20:26 f1 ./GatewayApp 6756 [local1.info] GentDriverEvent.cpp[60]--cloudConnectionMonitor()--Disconnected: Communication_Error:Communication_Error
2019 Jun 10 14:20:26 f1 ./GatewayApp 6756 [local1.info] GentDriverEvent.cpp[60]--cloudConnectionMonitor()--Disconnected: Connection_Ok:Connection_Ok
2019 Jun 10 14:20:31 f1 ./GatewayApp 6756 [local1.info] Checking Internet : g03loaddevregui.dsentience.net
2019 Jun 10 14:20:31 f1 ./GatewayApp 6756 [r0/git/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:1132 Failed performing DoWork for device 'xxxxxxxxxx' (device reported state 5; number of previous failures: 1)
local1.info] Checking Internet : g03loaddevpkisystemauthenticationv2.dsentience.net
2019 Jun 10 14:20:31 f1 ./GatewayApp 6756 [local1.info] Internet status iRetval : -1
Error: Time:Mon Jun 10 14:20:56 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:1132 Failed performing DoWork for device '98d95e84-0c18-4f18-9471-c5c3dd5a554a' (device reported state 5; number of previous failures: 2)

Error: Time:Mon Jun 10 14:21:26 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:1132 Failed performing DoWork for device 'xxxxxxxxxx' (device reported state 5; number of previous failures: 3)

Error: Time:Mon Jun 10 14:21:56 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:1132 Failed performing DoWork for device 'xxxxxxxxxxxx' (device reported state 5; number of previous failures: 4)
Error: Time:Mon Jun 10 14:21:56 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_DoWork Line:1611 Device 'xxxxxxxxxxxxx' reported a critical failure; connection retry will be triggered.
Info: Preparing transport for re-connection
Error: Time:Mon Jun 10 14:21:56 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransportamqp_methods.c Func:iothubtransportamqp_methods_unsubscribe Line:819 unsubscribe called while not subscribed
Error: Time:Mon Jun 10 14:21:56 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:on_cbs_put_token_complete_callback Line:168 CBS reported status code 0, error: '(null)' for put-token operation for device 'xxxxxxxxx'
Error: Time:Mon Jun 10 14:21:56 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:on_cbs_put_token_complete_callback Line:168 CBS reported status code 0, error: '(null)' for put-token operation for device 'xxxxxxxxxxxx'
Error: Time:Mon Jun 10 14:21:56 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:on_cbs_put_token_complete_callback Line:168 CBS reported status code 0, error: '(null)' for put-token operation for device 'xxxxxxxxxxxx'
Error: Time:Mon Jun 10 14:21:56 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:on_cbs_put_token_complete_callback Line:168 CBS reported status code 0, error: '(null)' for put-token operation for device 'xxxxxxxxxxxx'
2019 Jun 10 14:21:56 localhost kernel  [kern.notice] audit: type=1701 audit(1560176516.000:16): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=6756 comm="appname" exe="appname" sig=11
2019 Jun 10 14:21:56 f1 ./GatewayApp 6756 [local1.info] GentDriverEvent.cpp[60]--cloudConnectionMonitor()--Disconnected: Communication_Error:Communication_Error
2019 Jun 10 14:21:56 f1 audit 6756 [auth.notice] ANOM_ABEND auid=4294967295 uid=0 gid=0 ses=4294967295 pid=6756 comm="appname" exe="appname" sig=11
2019 Jun 10 14:21:56 f1 kernel  [kern.notice] audit: type=1701 audit(1560176516.000:16): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=6756 comm="appname" exe="appname" sig=11

please help me ..its really important to fix this issue

**Comment by danewalton** [comment]
Hi thanks for your patience. Are you able to get a stack trace when you get the error? It might be easier for me to reproduce your issue and better find a solution.

**Comment by danewalton** [comment]
Hi nitu011 I am going to close this issue for now but if you would like to follow up in the future feel free to open it again.

**Comment by az-iot-builder-01** [comment]
@nitu011, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
