### ISSUE TITLE
Guidance for asynchronous device method handling

### ISSUE THREAD

**Issue by Arty29** [Azure/azure-iot-sdk-c#1081]
Hello,

I’m trying to understand how to safely use asynchronous device method notifications with the IoT Hub Client.  In my application I am using MQTT as the transport layer.

I have registered a callback of type `IOTHUB_CLIENT_INBOUND_DEVICE_METHOD_CALLBACK` with the IoT Hub Client in which I handle device methods.  When that callback is executed, one of the arguments passed to it is the `method_id` (of type `METHOD_HANDLE`).  My application does not fully process the device method in this callback, so a copy of the device method and the associated method_id value are placed into a queue.  Once the device method has been executed and the response is ready, a call to `IoTHubClient_LL_DeviceMethodResponse()` is used to return the response and its `method_id` value to the IoT Hub Client.

I am concerned about the allocated memory associated with the `method_id` handle, in particular how it relates to a particular instance of IoT Hub Client.  At first I thought that it would be bad to call `IoTHubClient_LL_DeviceMethodResponse()` and pass it a `method_id` value that had been assigned by a different instance of IoT Hub Client because the handle may refer to memory that was released when the original instance of IoT Hub Client was destroyed.  However, I dug deeper and found that the method_if handle is actually a `STRING_HANDLE` data type.  From what I can tell the only way to free that memory is by calling `IoTHubClient_LL_DeviceMethodResponse()`, even if that is in the context of a different instance of IoT Hub Client.  It also means that if the IoT Hub Client is destroyed before all asynchronous device methods have completed there is no (graceful) way to free the memory allocated to the underlying `method_id` object.

Could you provide some guidance on the proper way to implement asynchronous device method handling to ensure memory is not leaked or accessed after it has been released?

Thank you.

**Comment by danewalton** [comment]
Hi Arty thank you for your patience. Can I get some more information about your use case here and what you are processing later? Specifically is there a way that you can implement this without copying the method_id struct. In theory handles are used to "handle" opaque data since it is subject to change.

**Comment by Arty29** [comment]
Hello danewalton, thank you for your response.

I only copy the handle, not the underlying data structure to which it refers (which as you point out is opaque).

For example, let's say that I have two tasks.  One task (Task A) is running the IoT Hub Client and the other (Task B) is controlling other parts of my application.  When a direct method is received by IoT Hub Client it cannot be serviced immediately in the `IOTHUB_CLIENT_INBOUND_DEVICE_METHOD_CALLBACK` callback because the request has to be queued up for Task B to actually do the work.  For example, moving a mechanical part and confirming that it is in position, which can take some time to do.  Once the direct method has completed, the result is passed back to the IoT Hub Client by a call to `IoTHubClient_LL_DeviceMethodResponse()`.  This call is made from the context of Task A and passes in the very same `METHOD_HANDLE` object that was provided by IoT Hub Client when the direct method was first received. 

This all works fine until you consider the cases where, while Task B is actually servicing the direct method, either of the following occur:

1. Task A destroys the instance of the IoT Hub Client
2. Task A destroys the instance of the IoT Hub Client and creates a new instance. 

In the first case it is no longer possible to call `IoTHubClient_LL_DeviceMethodResponse()` because to do so requires a handle to an instance of IoT Hub Client.
In the second case, without knowledge of the IoT Hub Client internals it is not guaranteed that the new instance of IoT Hub Client is able to use the `METHOD_HANDLE` object of the outstanding device method.

What I have discovered is that it appears that the only way that the underlying dynamically allocated memory associated with the `METHOD_HANDLE` instance can ever be released is through a call to `IoTHubClient_LL_DeviceMethodResponse()`.  As far as I can tell, it is not released when the IoT Hub Client is destroyed.

**Comment by danewalton** [comment]
Hi Arty,
If you would like to offload the processing to another thread and essentially handle it asynchronously, then you most likely will need some mechanism to notify the destroy attempt that there are still methods being processed. As mentioned before, because the data is opaque, it only gets free'd via the call to `IoTHubClient_LL_DeviceMethodResponse()`. I hope that helps and let me know if you need any further clarification or have any additional questions.

**Comment by Arty29** [comment]
Hi danewalton,
That is the approach that I am taking now that I understand what is happening inside IoT Hub and its lower layers.  I still can't help but think that it would be cleaner if the component that allocated the memory resources is responsible for releasing those resources automatically if it is destroyed prematurely.  However, it still gets messy if the device method call is completed later using a handle created by an earlier IoT Hub instance.  In any case the correct usage of the API should really be documented to avoid run-time issues by developers who are using the SDK.

**Comment by az-iot-builder-01** [comment]
@danewalton, @Arty29, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
