### ISSUE TITLE
using custom_hsm_get_common_name as device ID at provisioning

### ISSUE THREAD

**Issue by bukarev** [Azure/azure-iot-sdk-c#1082]
The document on custom HSM says that the method "custom_hsm_get_common_name" of the API  is supposed to return the common name from the x509 certificate, which is then "Passed to the Device Provisioning Service as a registration Id"

Question, then - in group enrollment provisioning, how should I provide different IDs for my IoT devices that I'm enrolling with that group? Or am I missing some part of this process?

**Comment by jebrando** [comment]
Using x509 (group or individual enrollment) the device Id is the same as the common name.  Each device will have to have a unique name for this.

In future releases the SDK will query the certificate to get the common name and will not need the user to retrieve it.

**Comment by az-iot-builder-01** [comment]
@bukarev, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
