### ISSUE TITLE
fatal error: umock_c/umock_c_prod.h: No such file or directory

### ISSUE THREAD

**Issue by abhipony** [Azure/azure-iot-sdk-c#1086]
OS version : 
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.6 (Maipo)
Release:	7.6
Codename:	Maipo

SDK Release: 2019-05-16

### Description:
I am trying to build the azure-iot-sdk-c inside a docker. 
The base image that I am using is
**FROM resin/beaglebone-black-node:latest**
Previously I used debian:jessie.

### **The commands I am using inside the Dockerfile is**
git clone --recursive https://github.com/Azure/azure-iot-sdk-c/                  
cd azure-iot-sdk-c/build_all/linux                                               
./setup.sh                                                                       
./build.sh --no-logging

### **After everything is built, I get the below error.**
[Build]   main In file included from /usr/src/app/azure-iot-sdk-c/c-utility/inc/azure_c_shared_utility/platform.h:7:0,
[Build]   main                  from src/pusher.cpp:8:
[Build]   main /usr/src/app/azure-iot-sdk-c/c-utility/inc/azure_c_shared_utility/strings.h:7:34: fatal error: umock_c/umock_c_prod.h: No such file or directory
[Build]   main  #include "umock_c/umock_c_prod.h"
[Build]   main                                   ^
[Build]   main compilation terminated.

**pusher is the name of my application which is using the SDK.**

When I build inside the docker, the header file included in string.h is **umock_c/umock_c_prod.h** which it is **not able to find**.

Can someone please help me in this case.

**Comment by cindydeng1998** [comment]
Hello!

Do you mind sharing your Dockerfile so we can take a better look at the container you are running the SDK build in? I tried to run the base image **resin/beaglebone-black-node:latest** and I have been getting the following error:

`[WARN  tini (26)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
'No CMD command was set in Dockerfile! Details about CMD command could be found in Dockerfile Guide section in our Docs. Here's the link: http://docs.resin.io/deployment/dockerfile`

You also mentioned that you were previously running a debian:jessie image. Have you also encountered the same issue?

Thanks,
Cindy D.

**Comment by RandySRSOL** [comment]
I'm running Ubuntu 18.04 gcc 7.4.0 updated from 2019-02-11 to 2019-07-01 and now when I compile I'm getting following error.

/..../azure-iot-sdk/src/azure-iot/iothub_client/inc/iothub.h:7:10: fatal error: umock_c/umock_c_prod.h: No such file or directory
 #include "umock_c/umock_c_prod.h".



ExternalProject_Add(
    azure-iot
    GIT_REPOSITORY https://github.com/Azure/azure-iot-sdk-c.git
    GIT_TAG "2019-07-01"
    GIT_SHALLOW true
    PREFIX ${IOT_PREFIX}
    INSTALL_COMMAND ""
    CMAKE_ARGS "${CMAKE_ARGS}"
)

**Comment by RandySRSOL** [comment]
FYI Switching back to 2019-02-11 the iothub.h has this include  #include "azure_c_shared_utility/umock_c_prod.h"  and 2019-07-01 has #include "umock_c/umock_c_prod.h"

**Comment by massand** [comment]
In order to prevent caching within the Docker container, could you rerun the docker build command with --no-cache. This will ensure your image is updated with the latest clone. There were changes made to our internal header locations to reduce clone + build times. If this resolves your issues, please let us know and close the issue. Thanks!

**Comment by massand** [comment]
@RandySRSOL @abhipony  Please reopen a new issue if this issue reproduces after running the --no-cache option for docker build. Thanks!

**Comment by az-iot-builder-01** [comment]
@abhipony, @RandySRSOL, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by RandySRSOL** [comment]
@massand not sure what you mean running the --no-cache option, I'm not using docker. I did delete the entire azure-iot-sdk folder and I'm still getting the error - azure-iot-sdk/src/azure-iot/iothub_client/inc/iothub.h:7:10: fatal error: umock_c/umock_c_prod.h: No such file or directory
 #include "umock_c/umock_c_prod.h"

**Comment by massand** [comment]
@RandySRSOL OP had posted issues building within docker. If you are building locally on Linux, there is certainly an older version of SDK headers being included in the project. Please [follow instructions in our docs for running samples](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/ubuntu_apt-get_sample_setup.md) to ensure the latest version of SDK is present. I cannot reproduce your issue on my Linux Mint (18.04) machine.

**Comment by dnsmirnoff** [comment]
Hello! I get the same error in Xcode iOS project after switching to  2019-07-01 from April version.
/Users/user/Documents/development/.../libs/azure-iot-sdk-c/iothub_client/inc/iothub.h:7:10: 'umock_c/umock_c_prod.h' file not found

**Comment by abhipony** [comment]
@massand @cindydeng1998  @rafilho  Still getting the same error after doing a --no-chache

**The headers included in the files are :**
#include "azure_c_shared_utility/platform.h
#include "azure_c_shared_utility/threadapi.
#include "iothub_client.h"                 
#include "iothubtransportmqtt_websockets.h"

**My makefile for the appplication:**
AZURE_SDK_PATH:=$(CURDIR)/azure-iot-sdk-c
CXXFLAGS += -I$(AZURE_SDK_PATH)/iothub_client/inc -I$(AZURE_SDK_PATH)/c-utility/inc -I/usr/include/azureiot -I/usr/include/azureiot/inc -I$(AZURE_SDK_PATH)/deps/parson -I .

binary/pusher: \
	src/pusher.o \
	lib/logging/easylogging++.a \
	parson.o
	$(CXX) -o $@ $^ -L$(AZURE_SDK_PATH)/cmake/iotsdk_linux/c-utility -L$(AZURE_SDK_PATH)/cmake/iotsdk_linux/umqtt -L$(AZURE_SDK_PATH)/cmake/iotsdk_linux/iothub_client $(LDLIBS) -lm -liothub_client_mqtt_ws_transport -lumqtt -l:libiothub_client.a -lpthread -laziotsharedutil -lssl -lcrypto -lcurl

parson.o: $(AZURE_SDK_PATH)/deps/parson/parson.c $(AZURE_SDK_PATH)/deps/parson/parson.h
	gcc -c $(AZURE_SDK_PATH)/deps/parson/parson.c -o "parson.o"

I am currently working with an older version of this repo. Please look into this issue and suggest a solution. Let me know if you have any doubts or queries.

**Comment by rafilho** [comment]
Reopening the issue and assigning to current owners. Thanks.

**Comment by scout208** [comment]
I'm encountering this issue too trying to build a sample in Visual Studio with the latest SDK for Windows.

**Comment by nickbarrantes** [comment]
I have this issue in macOS 10.15.2 as well.

Directories I have are:
~/esp/esp-idf
~/azure-iot-sdk-c
~/esp-azure

I'm trying to build from 
~/esp/iothub_client_sample_mqtt

using:

`. $HOME /esp/esp-idf/export.sh`
`make menuconfig` to set serial port
'make flash'

which results in:

`In file included from /Users/nick/esp/iothub_client_sample_mqtt/main/azure_main.c:17:
/Users/nick/esp/esp-idf/components/esp_event/include/esp_event_loop.h:2:2: warning: #warning "esp_event_loop.h is deprecated, please include esp_event.h instead" [-Wcpp]
 #warning "esp_event_loop.h is deprecated, please include esp_event.h instead"
  ^~~~~~~
/Users/nick/esp/iothub_client_sample_mqtt/main/azure_main.c: In function 'initialise_wifi':
/Users/nick/esp/iothub_client_sample_mqtt/main/azure_main.c:61:5: warning: 'tcpip_adapter_init' is deprecated [-Wdeprecated-declarations]
     tcpip_adapter_init();
     ^~~~~~~~~~~~~~~~~~
In file included from /Users/nick/esp/esp-idf/components/esp_netif/include/esp_netif.h:39,
                 from /Users/nick/esp/esp-idf/components/esp_event/include/esp_event_legacy.h:22,
                 from /Users/nick/esp/esp-idf/components/esp_event/include/esp_event.h:26,
                 from /Users/nick/esp/esp-idf/components/esp_wifi/include/esp_wifi.h:64,
                 from /Users/nick/esp/iothub_client_sample_mqtt/main/azure_main.c:16:
/Users/nick/esp/esp-idf/components/tcpip_adapter/include/tcpip_adapter.h:30:6: note: declared here
 void tcpip_adapter_init(void)  __attribute__ ((deprecated));
      ^~~~~~~~~~~~~~~~~~
/Users/nick/esp/iothub_client_sample_mqtt/main/azure_main.c:63:5: warning: 'esp_event_loop_init' is deprecated [-Wdeprecated-declarations]
     ESP_ERROR_CHECK( esp_event_loop_init(event_handler, NULL) );
     ^~~~~~~~~~~~~~~
In file included from /Users/nick/esp/esp-idf/components/esp_event/include/esp_event.h:26,
                 from /Users/nick/esp/esp-idf/components/esp_wifi/include/esp_wifi.h:64,
                 from /Users/nick/esp/iothub_client_sample_mqtt/main/azure_main.c:16:
/Users/nick/esp/esp-idf/components/esp_event/include/esp_event_legacy.h:227:11: note: declared here
 esp_err_t esp_event_loop_init(system_event_cb_t cb, void *ctx) __attribute__ ((deprecated));
           ^~~~~~~~~~~~~~~~~~~
CC build/main/iothub_client_sample_mqtt.o
In file included from /Users/nick/esp/iothub_client_sample_mqtt/main/iothub_client_sample_mqtt.c:7:
/Users/nick/esp/iothub_client_sample_mqtt/main/iothub_client.h:21:10: fatal error: umock_c/umock_c_prod.h: No such file or directory
 #include "umock_c/umock_c_prod.h"
`

**Comment by b-s-e** [comment]
Hi,
I have the same problem here with the latest version LTS_02_2020, sdk compiled with the buildroot system.
When I include any header of the azure sdk (e.g. #include "iothub.h") I get:
[PATH]/arm-buildroot-linux-gnueabihf/sysroot/usr/include/iothub.h:7: error: umock_c/umock_c_prod.h: No such file or directory
 #include "umock_c/umock_c_prod.h"

Are you still working on a solution or is there any workaround?

Thanks!

**Comment by abhipony** [comment]
@b-s-e Hi,
I solved the problem by including the umock library in the path while building the application.
In my Makefile
Before
**CXXFLAGS += -I$(AZURE_SDK_PATH)/iothub_client/inc -I$(AZURE_SDK_PATH)/c-utility/inc -I/usr/include/azureiot 
-I/usr/include/azureiot/inc -I$(AZURE_SDK_PATH)/deps/parson**

Now
**CXXFLAGS += -I$(AZURE_SDK_PATH)/iothub_client/inc -I$(AZURE_SDK_PATH)/c-utility/inc -I/usr/include/azureiot 
-I/usr/include/azureiot/inc
-I$(AZURE_SDK_PATH)/deps/parson -I$(AZURE_SDK_PATH)/deps/umock-c/inc -I$(AZURE_SDK_PATH)/c-utility/deps/azure-macro-utils-c/inc -I .**

As you can see, the umock-c and the azure-macro-utils-c are extra includes in the second one. 
Please let me know if that solved your issue.

**Comment by b-s-e** [comment]
@abhipony Hi,
sorry for the late answer - yes it solved my problem.
Thanks!

In total I had to include the following libs to get the client to work:
-liothub_client
-liothub_client_amqp_transport
-laziotsharedutil
-liothub_service_client
-lparson
-lserializer
-luamqp
-lumock_c
-lcurl
-lssl
-lcrypto
-luuid
-liothub_client_http_transport

**Comment by abhipony** [comment]
@b-s-e 
Great. Good to know.
I hope this fixes everyone's issue in this thread.
