### ISSUE TITLE
Cannot communicate with websocket protocols when behind ANY ssl decrypting http proxy

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#1088]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**: Ubuntu 18.04 LTS, clang 6.0.0, Intel Core i5.  I feel this is operating system independent as I had same issue on macOS 10.13.4 with XCode 9.
**OpenSSL version**: 1.1.0g
**cURL version**: 7.58.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**: master b67aca0  

**Protocol**: MQTT_WS and AMQP_WS

**Describe the Bug**: At my corporate office, on my work machine behind SSL decrypting corporate proxy, I noticed that SDK iothub_convenient_sample ([1](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_convenience_sample)) cannot communicate over MQTT_WS/AMQP_WS protocol. But, the sample working well when the protocol was HTTP. I initially thought this to be a case of bad corporate proxy interfering with WS traffic.

Later I came home and started Charles ([2](https://www.charlesproxy.com/)) and used it is a proxy. The iothub_convenient_sample worked well over all protocols through Charles proxy as well. But, the moment I turned on SSL decryption in Charles ([3](https://www.charlesproxy.com/documentation/proxying/ssl-proxying/)), I saw a repeat of the corporate proxy behaviour. The iothub_convenient_sample worked well with HTTP protocol but not with either of MQTT_WS/AMQP_WS protocol.

Now to make sure this is related to IoT Hub or SDK, I switched to Fiddler proxy ([4](https://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/UseFiddlerAsReverseProxy)). Again the issue was consistently reproducible the moment we turn on SSL decryption. This issue is quickly and consistently reproducible with Charles or any SSL decrypting proxy. 

**MCVE**:  I used https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_convenience_sample. But any of the iothub_client samples could be used to reproduce the issue. Please use `OPTION_TRUSTED_CERT` with proxy ca when enabling ssl decrypt.

**Console Logs**

> xxxxxx@xxxxxxxxx:~/src/github/azure-iot-sdk-c/cmake$ ./iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample 
>
> This sample will send messages continuously and accept C2D messages.
> Press Ctrl+C to terminate the sample.
> 
> Creating IoTHub handle
> 
> Sending message 1 to IoTHub
> Message: {"temperature":31.037,"humidity":61.377,"scale":"Celcius"}
> XLOG: -> 08:56:16 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: xxxxxxxxxxxxxxxx.azure-devices.net/device01/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.4%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
> 
> Sending message 2 to IoTHub
> Message: {"temperature":22.339,"humidity":73.472,"scale":"Celcius"}
> 
> Sending message 3 to IoTHub
> Message: {"temperature":31.719,"humidity":62.258,"scale":"Celcius"}
> 
> Sending message 4 to IoTHub
> Message: {"temperature":31.880,"humidity":74.027,"scale":"Celcius"}
> XLOG: mqtt_client timed out waiting for CONNACK
> XLOG: SSL channel closed in decode_ssl_received_bytes.
> XLOG: Error in decode_ssl_received_bytes.

**More Logs**: I am attaching Wireshark traces (between Charles proxy and Azure Iot Hub) and application [logs](https://github.com/Azure/azure-iot-sdk-c/files/3440025/logs.zip) for the cases in which it worked (ssl decrypt off) and didn't work (ssl decrypt on). 

<sub>Usecase: We have end-customers in factories behind HTTP proxies. Tomorrow they might switch to an SSL decrypting proxy and then aplplication using this SDK would fail.</sub>

**Comment by rafilho** [comment]
@hihigupt, can you please investigate? Hopefully this will fall under the same WS/proxy issues we have been addressing it. Thanks.

**Comment by hihigupt** [comment]
We have recently added few fixes related to this. I re-ran our current master iothub_convenient_sample with proxy, which works for me. Can you please retry this on our current master.

**Comment by kiranpradeep** [comment]
@hihigupt The issue persists in the current master. Please let me know if I should share any further info.

**Comment by hihigupt** [comment]
@kiranpradeep 
Please share following things:
1. What tls lib you are now using. (e.g tls, openssl)
2. Your wireshark trace for IOTHUB connection.
3. Logs of skd with line numbers.
4. Protocol used via client to connect to IOTHUB.

This will help me to reproduce the scenario on my end.

**Comment by kiranpradeep** [comment]
@hihigupt Queries 1,2 and 4 are already provided in initial bug description with MCVE. I had also shared the console logs in same bug description. It will not take more than 1 run of the MCVE sample with Charles/Fiddler to reproduce the issue at your end. It is consitently reproducible.

**Comment by hihigupt** [comment]
@kiranpradeep  
Looks like fix for port in c-utility has not yet been picked. We are working on bringing that fix to our sdk next release. Till then can you please update your c-utility to consume that change. Use following steps to update the c-utilitiy locally and test if things works for you.

cd $ROOT_SDK
cd c-utility/
git fetch 
git cherry-pick b62e183307dbb6a3c4bad95f780e3b62289a14ae

Compile the sample and re-run.

**Comment by kiranpradeep** [comment]
@hihigupt The issue persists. The issue is very much easily reproducible with Charles/Fiddler on every computer I have tried. I am not sure if we should keep doing this back and forth.

**Comment by hihigupt** [comment]
@kiranpradeep FYI I am able to connect to IOTHUB and send telemetry using the proxy (Fiddler). [Image](https://kartosstorage.blob.core.windows.net/data/proxy_mqtt_ws.png?sp=r&st=2019-09-11T17:26:23Z&se=2019-11-26T02:26:23Z&spr=https&sv=2018-03-28&sig=ZXF5UI0r6dWqFICgx0t2Zv9%2FFgWsCOEkBqdzFFn3yZo%3D&sr=b).

**Comment by kiranpradeep** [comment]
@hihigupt You have not enabled SSL decrypt in Fiddler/Charles. That would force you to use option OPTION_TRUSTED_CERT with Fidder/Charles CA. **This is mentioned in MCVE of bug report**. The error happen only if you turn on SSL decrypt in Charles/Fiddler or any SSL decrypt capable proxy.

**Comment by kiranpradeep** [comment]
Ok @hihigupt. I have never tested (neither the _iothub_convenience_sample_ nor the SSL proxy hosting) with Windows computer and so didn't mention Windows in the bug report. Below are the 5 computers on which I have tested the _iothub_convenience_sample_.

1. Ubuntu 18.04 behind SSL decrypting corporate proxy (at work).
2. Ubuntu 16.04 behind SSL decrypting corporate proxy (at work).
3. macOS 10.13.4 behind SSL decrypting corporate proxy (at work).
4. Ubuntu 18.04 behind Charles (running on same computer) with SSL decrypt enabled (at home)
5. Ubuntu 18.04 behind Fiddler (running on same computer) with SSL decrypt enabled (at home).

I could share Wireshark traces and SDK logs in each of the above 5 scenarios. In bug report, I shared traces and logs of case 4. The issue is still consistently reproducible in above 5 scenarios. If that is not considered good enough for the bug, I will close this issue. Please let me know.

**Comment by hihigupt** [comment]
@kiranpradeep I am using docker for ubuntu environment, that should provide linux run-time. Only thing that I can think of now is when fiddler act as a MITM. When being MITM, it act as a client to IOTHUB, and this client needs to have renegotiation enable to work with WS. If you check the last wireshark trace you attached in your **MCVE**, client (i.e fiddler 192.168.1.100:38506) sends a Encrypt alert message (packet num: 74) after encrypted handshake(packet number: 71), which causes this disconnect. Generally for WS, server require to renegotiate over tls connection and client can refuse to renegotiate connection. Renegotiation is generally configured in tls lib you use (both runtime and compile time). 

To remove these OS related variables I will try on Linux vm both proxy and sample (sample which I was already).

**Comment by hihigupt** [comment]
If IOTHUB client runs on Windows or Linux and connects to fiddler proxy running on windows with decrypt enable, everything works fine. I also tried with Fiddler on Linux with mono. But with latest version of mono (6.4.0), I am not able to decrypt https traffic even when fiddler decrypt option is enabled. In older version of Fiddler(4.6.2) I could see that when I enabled decrypt option connection is getting decrypt, but fiddler client was dropping connection to IOTHUB, which in-turn was causing IOTHUB client to fail. This looks to be Fiddler client issue running on mono, that needs to be debugged on Fiddler end.

**Comment by kiranpradeep** [comment]
@hihigupt Assuming you have the repro.

1. The issue is not specific to Fiddler on Linux. I raised the bug because, I saw (and still consistent) the issue with 3 independent proxies (Fiddler,  Charles and corporate proxy) as specified in the bug report. If you can name any other SSL decrypting proxy, I can test the same on Linux.
2. Over the exact same setup, I could communicate to Azure Event Hub (AmqpWs), Azure Cosmos DB, Azure  Storage Blob/Queue, debug Azure Durable Functions with job storage setup on Azure, and even receive/publish data from **EventHub endpoint (AmqpWs) of same Azure IoT Hub**. If the whole world works over exact same setup, I cannot blame the proxy. As an end-user, I see either Azure IoT Hub service side or the SDK as the wrongdoer or at least provoking the wrong behaviour from Fiddler/Charles and other SSL decrypting proxies.

This may be a biased opinion. Please let me know if I should close this ticket.

**Comment by hihigupt** [comment]
Is the attached trace with MCVE is for fiddler in Linux?

**Comment by kiranpradeep** [comment]
@hihigupt The trace was for Charles on Linux.

**Comment by hihigupt** [comment]
@kiranpradeep I tired with [mitmproxy](https://mitmproxy.org/) in Ubuntu and[ proxy was able see the handshake was getting completed with IOTHUB properly](https://kartosstorage.blob.core.windows.net/data/github_issue.png?sp=r&st=2019-09-28T00:10:23Z&se=2019-12-26T09:10:23Z&spr=https&sv=2018-03-28&sig=%2BoUhnVVeQ%2BZuSJ6KaXgRu67LDJ1cq%2F1ZMSZ8jSRsn1A%3D&sr=b). This proxy has one bug which get surface after handshake completes(NOT Related to IOTHUB Client). Bug is because of using blocking read calls on sockets. As a work around for the bug, you can add following temporary fix by updating a file:

sudo vim <depending_on_your_path>/mitmproxy/proxy/protocol/websocket.py
Update [line ](https://github.com/mitmproxy/mitmproxy/blob/3cd37652709292cffa1bc733134cef5483489341/mitmproxy/proxy/protocol/websocket.py#L192) by adding

import time
time.sleep(1)

Once updated use the following command to start proxy:
sudo  /usr/local/bin/mitmdump --listen-port=8888  --ssl-insecure

Then run your sample pointing to this proxy, i.e 8888 port. Path to find the proxy cert:  
/root/.mitmproxy/mitmproxy-ca-cert.pem


To install this proxy on ubuntu, you can follow following steps:
sudo apt install python3-pip
sudo pip3 install -U pip
sudo pip3 install mitmproxy


Also, after analyzing the traffic of Fiddler in linux, I saw that fiddler tls connection is not using tls1.2 which is required for IOTHUB secure connection. FYI Fiddler in linux does not [support tls 1.1 and tls1.2](https://www.telerik.com/blogs/fiddler-for-linux-beta-is-here).

**Comment by kiranpradeep** [comment]
@hihigupt Ok. The point made is: IoT Hub works with 1 out of 4 tested real-world SSL decrypting proxies and so there is nothing wrong IoT Hub service or sdk side. Closing. 
Charles was tested with TLS 1.2. Thanks.

**Comment by az-iot-builder-01** [comment]
@rafilho, @hihigupt, @kiranpradeep, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
