### ISSUE TITLE
iothub_client.h vs iothub_device_client.h

### ISSUE THREAD

**Issue by adhoore** [Azure/azure-iot-sdk-c#1090]
Hey,

We are building a new IOT device. What API do we use?
What is the difference between **iothub_client.h** and **iothub_device_client.h** ?
What is the future of these two APIs? Will both of them be supported in the future?
Along the same line: iothub_client_ll.h vs iothub_device_client_ll.h?

Kind regards,
Alexander D'hoore

**Comment by smcd253** [comment]
Hi Alexander,

All great questions! 

Let me get you started by pointing you to the SDK samples. Whenever starting up an IoT project, I like to dig into the samples to see which looks closest to my application I then modify that sample to suit my specific needs. Here's the link: https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples

This will also give you a concrete introduction on how to use our APIs.

[iothub_device_client.h](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_device_client.h
) and [iothub_client.h](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client.h) are both extensions of iothub_client_core.h. However, iothub_device_client.h houses the up-to-date APIs for these methods. iothub_client.h is deprecated.

All of the **_LL_**  "Lower Layer" clients that you see provide the exact same functionality as the IoTHubClient_... APIs except one key difference: The user is responsible for scheduling the work done by each method. This is useful for constrained devices where spinning a separate thread is often not desired.

I recommend you start with one of provided samples and then build upon the functionality from there. This will give you a good idea of how to set up your device before you dive into the nitty-gritty details.

I hope I was able to answer your questions.

Happy hacking!

**Comment by adhoore** [comment]
Ok, great answers! Thanks!

Just one more: how am I supposed to know that iothub_client.h is deprecated?
Maybe you should add that to the documentation somehow or to the source file at least.

Kind regards,
Alexander

**Comment by smcd253** [comment]
Hi Alexander,

That is a good point and we will take note of it.

Thanks for your feedback! 

I'm going to close this issue for now. Please feel free to reopen it if you have any further questions related to this topic.

**Comment by az-iot-builder-01** [comment]
@smcd253, @adhoore, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by baybal** [comment]
@smcd253 Is it documented now? Right now we have 4 supposed "client" APIs, and its a huge confusion to any newcomer.

**Comment by adhoore** [comment]
Ha, brilliant. I'm glad we aren't using Azure anymore.

**Comment by aewp2** [comment]
@smcd253 Thanks for answering this question so clearly. We also just spent hours trying to figure out which API to use so it is good to find this answer.

**Comment by ahmet-kara** [comment]
Documents and samples are not up-to-date and there is no easy way to understand how to use this SDK. Is there anybody to take action at this point?
