### ISSUE TITLE
Asynchronous blob upload with LL API (revisited) 

### ISSUE THREAD

**Issue by dfabianZF** [Azure/azure-iot-sdk-c#1091]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

X86_64 OpenSuse Leap 15.1

**SDK Version (Please Give Commit SHA if Manually Compiling)**

LTS-07-2019

**Protocol**

AMQP

**Describe the Bug**

I use the SDK in a single-threaded C++ application that uses `boost::asio`. I only use the LL API and do my own scheduling by invoking `IoTHubDeviceClient_LL_DoWork()` in a timer. I came across the issue mentioned in #562 and I would like to add my point of view to the resolution presented there.

> Oh, I see.
 So this is part of the overall concept of what the LL layer and what the convenience layer are.
 The Low Level (LL) layer is non-threaded, blocking.

Actually, this is not entirely true. The LL API contains asynchronous (non-blocking) event messaging. I can do a lot of non-blocking code within a single thread and send messages to the hub without any trouble using `IoTHubDeviceClient_LL_SendEventAsync()`. This function does not block and allows me to wait for the result using a callback. I expected a similar behavior from the blob upload function but as stated above, it does not work that way.

The proposed solution in #562 is to use the convenience API but then I would have mixed code with LL and non-LL functions and most importantly I cannot overcome the incompatibility between the LL and non-LL connection handles (and I cannot afford to create two connections to the hub). There really should be something like `IoTHubClient_LL_UploadMultipleBlocksToBlobAsyncEx()` which retains the original declaration but calls the callback asynchronously when a chunk has been sent. That way one could do blob uploads and messaging in a single thread using nothing but the LL API (which should be a self-contained API layer in my opinion). This might involve redesigning the blob upload core code which uses the HTTP library in a blocking manner to support chunk uploads via `IoTHubDeviceClient_LL_DoWork()`.

**Comment by rafilho** [comment]
Thanks for reporting this issue, @dfabianZF. You are correct on your analysis. We have this in our backlog, but there is no timeline yet for us to address it. I will keep this issue open for now until we have a better idea about how we are going to address it. Thanks.

**Comment by ericwol-msft** [comment]
blob upload will be handled in the [azure-c-shared-utility](https://github.com/Azure/azure-c-shared-utility) sdk

**Comment by az-iot-builder-01** [comment]
@dfabianZF, @rafilho, @ericwol-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
