### ISSUE TITLE
Bad Certificate error In client while authenticating servers chain certificate from *.azure-devices.net

### ISSUE THREAD

**Issue by chinnaece** [Azure/azure-iot-sdk-c#1092]
**OS : Threadx 
SSL V3
TLS Version : 1.0**

I am trying to run azure sample code on my Device which has SSL V3 / TLS V1.0 . I added the **root certificate** of the server which i have taken form  azure-iot-sdk-c/certs/certs.c (placed only the /* DigiCert Baltimore Root */) .

 When i compare the info (openssl x509 -text  #453  -in) of root with the server chain certificate from the azure server which i have received, I noticed one important mismatch. 

> That is the subject of the root certificate and the issuer of the chain certificate are different.

**Subject of  /* DigiCert Baltimore Root */**

 `Subject:` C=IE, O=Baltimore, OU=CyberTrust, CN=Baltimore CyberTrust Root

 **Issuer of the chain cert from the HUB** 

 `Issuer:` C=US, ST=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT TLS CA 2

 **Is that the main reason for server certificate authentication failure?** 

 _If it is the reason , what will be the root of the azure server need to upload in client. I attached the pictures from Beyond-compare tool and Wireshark packet captures between Client and Hub._

If there are  other causes for this Bad certificate Error , Please Mention in reply . Hope  It would help me to solve this issue. The more consider thing is my device doesn't have file system , certificate trusted store like in Linux. We are passing certificates as string. 

Any help would be appreciated. 

Thank You

**Comment by chinnaece** [comment]
I am closing this issue because no response from anyone , opened a new issue with more clarity #1105 .

**Comment by az-iot-builder-01** [comment]
@chinnaece, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
