### ISSUE TITLE
Critical bug fix not available in the LTS branch

### ISSUE THREAD

**Issue by JesvinJoseph** [Azure/azure-iot-sdk-c#1096]
An important bug fix #842 is not available in the branch lts_10_2018. Can you please explain the reason.

**Comment by ewertons** [comment]
Hi @JesvinJoseph ,
unfortunately this was not included because the amount of changes to port that fix to the old code base was too costly at the time.
We apologize for that, and for the delay on the reply.

**Comment by az-iot-builder-01** [comment]
@JesvinJoseph, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by JesvinJoseph** [comment]
ok. Then, please remove LTS from the branch name.
