### ISSUE TITLE
In OpenWrt envrionment, failure to execute Iot client samples (http and amqp)

### ISSUE THREAD

**Issue by Senthamizhgp** [Azure/azure-iot-sdk-c#110]
- **OS and version used:** OpenWrt (Customized version)

- **SDK version used:** IoT Hub SDK for C, version 1.1.10

# Description of the issue:
Under the customized OpenWrt version for arm architecture, the IOT Device SDK was successfully compiled and generated the libraries. Failure to execute the iot hub client samples (iothub_client_sample_amqp and iothub_client_sample_http samples) under the 'azure-iot-sdk-c\iothub_client\samples' on the target board running OpenWrt.
Note : Target board connects to external world using a 3G connection.

# Console log of the issue:
1.	Executing the HTTP sample application ‘azure-iot-sdk-c\iothub_client\samples\iothub_client_sample_http’ fails with error below (highlighted)
curl_easy_perform resulted in failure with stderr as ‘Error’. But quickly tried out a sample performing the curl_easy_perform is successful against a handle pointing to a simple google.com endpoint  and it worked successfully. Hence no connection issues.

Log : 
Starting the IoTHub client sample HTTP...
Info: IoT Hub SDK for C, version 1.1.10
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
Error: Time:Wed Apr  5 12:20:54 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azure-iot-sdks-1/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:552 curl_easy_perform() failed: Error
 
Error: Time:Wed Apr  5 12:20:54 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azure-iot-sdks-1/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:554 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Wed Apr  5 12:20:54 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azure-iot-sdks-1/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Wed Apr  5 12:20:54 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azure-iot-sdks-1/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1629 unable to HTTPAPIEX_SAS_ExecuteRequest

2.	Executing the AMQP application in ‘azure-iot-sdk-c\iothub_client\samples\iothub_client_sample_amqp’ fails with below error (highlighted)
Throws primary key error eventhough the same device works in the Ubuntu target flavor of same application

Starting the IoTHub client sample AMQP...
Info: IoT Hub SDK for C, version 1.1.10
IoTHubClient_SetMessageCallback...successful.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
Error: Time:Wed Apr  5 12:14:17 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azre-iot-sdks-1/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:mark_current_device_key_as_invalid Line:216 Primary key of device 'UbuntuTestDevice' was marked as invalid. No other device keys available
Error: Time:Wed Apr  5 12:14:17 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azre-iot-sdks-1/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for devce 'UbuntuTestDevice' (device reported state 5; number of previous failures: 0)
Error: Time:Wed Apr  5 12:14:17 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azre-iot-sdks-1/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for devce 'UbuntuTestDevice' (device reported state 4; number of previous failures: 1)
Error: Time:Wed Apr  5 12:14:17 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azre-iot-sdks-1/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for devce 'UbuntuTestDevice' (device reported state 4; number of previous failures: 2)
Error: Time:Wed Apr  5 12:14:17 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azre-iot-sdks-1/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for devce 'UbuntuTestDevice' (device reported state 4; number of previous failures: 3)
Error: Time:Wed Apr  5 12:14:17 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azre-iot-sdks-1/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for devce 'UbuntuTestDevice' (device reported state 4; number of previous failures: 4)
Error: Time:Wed Apr  5 12:14:17 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azre-iot-sdks-1/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_DoWork Line:1343 Device 'UbuntuTestDevice' reported a citical failure; connection retry will be triggered.
Error: Time:Wed Apr  5 12:14:17 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azre-iot-sdks-1/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_DoWork Line:1304 An error occured on AMQP connection. Te connection will be restablished.
Error: Time:Wed Apr  5 12:14:17 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azre-iot-sdks-1/iothub_client/src/iothubtransport_amqp_connection.c Func:on_cbs_open_complete Line:149 CBS open failed
Error: Time:Wed Apr  5 12:14:17 2017 File:/home/azure/WIP/CloudGate-SDK-x86_64-v1.53.0/build_dir/target-arm_v5te_uClibc-0.9.30.3_eabi/azre-iot-sdks-1/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:on_cbs_put_token_complete_callback Line:272 CBS reported status code 0, error: '(ull)' for put-token operation for device 'UbuntuTestDevice'
-> [CLOSE]* {}

**Comment by ewertons** [comment]
@Senthamizhgp , thanks for the report.

We need more information to figure out why your connection is not succeeding.
I see you tried curl against google.com, but did you try running it against your IoT Hub FQDN?
Have you tried using MQTT as well?
If you share your IoT hub fqdn I can verify if there are any log traces from the service side.

**Comment by Senthamizhgp** [comment]
@ewertons,
I am yet to try curl with the FQDN and also with the MQTT as well.
FQDN - gfrgwwiothub.azure-devices.net  
Also find below few snippets of tcpdump taken during the data transfer between the IOT Hub client and IOT Hub. It showed unknown CA and tried checking in the target board whether it is holding invalid certificates (client machine). Re-installed the certificates and now could see AMQP working. But still the HTTP requests fail with Open failure. (can it be because of openssl issue?)

![tcpdump](https://cloud.githubusercontent.com/assets/19814196/24798795/3ac5a5f4-1b98-11e7-87f0-e8c695806a4f.JPG)

**Comment by ewertons** [comment]
If you were able to use the Azure IoT C SDK with AMQP from your device running OpenWRT, it means it used openssl. So since you see AMQP working, openssl succeeded as well. We are glad that part is working now.

As for the HTTP-based sample, what do you see on the network capture? would you have the client logs to share?

**Comment by Senthamizhgp** [comment]
Note that in the above network capture snapshot I shared, there is a highlighted part showing Unknown CA (client 10.138.44.213 and destination (IOT Hub) is 40.118.27.192. Is that because of invalid certificate?

**Comment by ewertons** [comment]
Oh, yes, that would be a possible cause of the problem, resulting in failed TLS negotiation.

On your sample, are you calling SetOption("TrustedCerts", ... ?

**Comment by ewertons** [comment]
If you are running https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_http/iothub_client_sample_http.c, I see that it has these lines conditioned to running on MBED.
```c
#ifdef MBED_BUILD_TIMESTAMP
            // For mbed add the certificate information
            if (IoTHubClient_LL_SetOption(iotHubClientHandle, "TrustedCerts", certificates) != IOTHUB_CLIENT_OK)
            {
                printf("failure to set option \"TrustedCerts\"\r\n");
            }
#endif // MBED_BUILD_TIMESTAMP
```

I would suggest you to enable setting TrustedCerts on your platform and running the sample again.
Notice we have the certificates info in https://github.com/Azure/azure-iot-sdk-c/tree/master/certs

**Comment by tameraw** [comment]
@Senthamizhgp - Please reopen or file new issue if still encountering problems. Thanks.
