### ISSUE TITLE
Issue with connecting to IOT hub using MQTT for yocto OS 

### ISSUE THREAD

**Issue by cher1510** [Azure/azure-iot-sdk-c#1102]
I have crossed compiled the the Azure C SDK .
Ported it on to the ARM 32 bit device with Yocto OS .

When I try to connect to the iothub using the sample application iothub_ll_telemetry_sample , I am getting the following errors .

Creating IoTHub Device handle
Sending message 1 to IoTHub
Error: Time:Fri Aug  9 20:26:20 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:277 Failure: getad.
Error: Time:Fri Aug  9 20:26:20 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:760 lookup_address_and_connect_socket failed
The device client has been disconnected
Error: Time:Fri Aug  9 20:26:20 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected sta.
Error: Time:Fri Aug  9 20:26:20 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Fri Aug  9 20:26:20 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1005 Error: io_open failed
Error: Time:Fri Aug  9 20:26:20 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2262 failure connecting to address r.
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
Error: Time:Fri Aug  9 20:26:21 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:277 Failure: getad.
Error: Time:Fri Aug  9 20:26:21 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:760 lookup_address_and_connect_socket failed
The device client has been disconnected
Error: Time:Fri Aug  9 20:26:21 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected sta.
Error: Time:Fri Aug  9 20:26:21 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Fri Aug  9 20:26:21 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1005 Error: io_open failed
Error: Time:Fri Aug  9 20:26:21 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2262 failure connecting to address r.
Error: Time:Fri Aug  9 20:26:23 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:277 Failure: getad.
Error: Time:Fri Aug  9 20:26:23 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:760 lookup_address_and_connect_socket failed
The device client has been disconnected
Error: Time:Fri Aug  9 20:26:23 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected sta.
Error: Time:Fri Aug  9 20:26:23 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Fri Aug  9 20:26:23 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1005 Error: io_open failed
Error: Time:Fri Aug  9 20:26:23 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2262 failure connecting to address r.
Error: Time:Fri Aug  9 20:26:27 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:277 Failure: getad.
Error: Time:Fri Aug  9 20:26:27 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:760 lookup_address_and_connect_socket failed
The device client has been disconnected

I am using a valid connection string  . 

Can anyone please help me with the issue .Thanks

**Comment by cher1510** [comment]
I have noticed that the error caused above were mostly due to the network connection problems of the device .
But even when the device successfully connects to the internet , I am facing the following errors due to the issue regarding the certificates .

Creating IoTHub Device handle
Sending message 1 to IoTHub
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
Error: Time:Tue Aug 13 13:55:34 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:673 error:14090086:SSL routines:ssl3_get_servercertificate:certificate verify failed
The device client has been disconnected
Error: Time:Tue Aug 13 13:55:35 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:673 error:14090086:SSL routines:ssl3_get_servercertificate:certificate verify failed
The device client has been disconnected
Error: Time:Tue Aug 13 13:55:37 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:673 error:14090086:SSL routines:ssl3_get_servercertificate:certificate verify failed
The device client has been disconnected
Error: Time:Tue Aug 13 13:55:41 2019 File:/home/scheruku/Documents/source/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:673 error:14090086:SSL routines:ssl3_get_servercertificate:certificate verify failed
The device client has been disconnected

**Comment by cher1510** [comment]
hi @rafilho  . I am still facing this issue . Can you please help me with this issue if you have any idea .

**Comment by rafilho** [comment]
Thanks for reporting the issue, @cher1510. We are investigating and will let you know once we have an update. Thanks.

**Comment by cher1510** [comment]
The issue was with the OpenSSL unable to get the local issuer certificate . I was able to solve my problem . Thank You

**Comment by az-iot-builder-01** [comment]
@cher1510, @rafilho, @jbobotek, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by LedRunway** [comment]
@cher1510: I also want to use azure mqtt on Yocto, but struggling to compile the iothub_ll_telemetry_sample. Header file can not be found. Could you provide the recipes you used in Yocto? That would very helpful to me!
