### ISSUE TITLE
Server's chain certificate verification failed on Azure iot-sdk-c Client running on Threadx treck stack

### ISSUE THREAD

**Issue by chinnaece** [Azure/azure-iot-sdk-c#1105]
I am trying to run my IoT-client on Threadx-Os Client which doesn't have file- system/certificate trusted store kind of things like in linux. When i look into Wireshark the client closing connection with Fatal,Bad certificate error. I tried all possible options which are suggested in different forums to solve this issue. Which haven't solved my problem. The solution i tried mentioned below.

By using below API to added only above Baltimore root certificate available in cert.c

> IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_TRUSTED_CERT, certificates);

`It's not working for me because we don't have trusted store like linux.`

> I need answers for two important questions.

1) Do i need to Add entire certificate string in cert.c (or) only first Baltimore root as CA root to my client.
2) Without trusted store, how client can tell to azure-cloud i have trusted root.

**Comment by az-iot-builder-01** [comment]
@chinnaece, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
