### ISSUE TITLE
Instruction unclear for setting up device to provision using IoT Hub Device Provisioning Service

### ISSUE THREAD

**Issue by chinmaychhajed** [Azure/azure-iot-sdk-c#1106]
I'm using a UNIX machine. 

- There is no procedure for provisioning an IoT Hub device from UNIX machine [here](https://docs.microsoft.com/en-us/azure/iot-dps/tutorial-set-up-device#simulated-devices). Can you please add it. Please add command line support also for Simulating device
- For enrolling individual device for provisioning ([here](https://docs.microsoft.com/en-us/azure/iot-dps/tutorial-provision-device-to-hub#enroll-the-device)) for X.509 certificates, it asks for primary and secondary certificates. Where can I get them?

Thanks for your support

**Comment by chrissie926** [comment]
@chinmaychhajed , I am the owner in this area. Before I update the docs, I have a few questions. For the first bullet point, does the customer wants to use a UNIX device ? 
For the second bullet point, you can go to the "certificate" blade to upload your certificate. To learn more, please follow the article here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-x509ca-overview

**Comment by chinmaychhajed** [comment]
By UNIX machine I meant provisioning an IoT device by following a setup on UNIX machine. Steps mentioned in link in my previous comment uses Windows environment (eg. to run Simulator.exe) but I needed similar steps for OS X.

**Comment by chinmaychhajed** [comment]
I followed instructions given here (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-x509ca-overview) and when I'm provisioning my device, I'm getting error as shown in image.

![image](https://user-images.githubusercontent.com/42715380/63265299-eee93300-c2aa-11e9-88ca-da05a154b5ff.png)


I used `certs/new-device.cert.pem` as leaf certificate and `private/new-device.key.pem` as private key for my deivce. Can you please help.

**Comment by chinmaychhajed** [comment]
Hello, any update on this? @chrissie926

**Comment by danewalton** [comment]
Hi @chinmaychhajed 
Are you able to try this version of [certGen.sh](https://github.com/Azure/azure-iot-sdk-c/blob/dawalton/certGen/tools/CACertificates/certGen.sh)? I'm assuming that's what you used to generate `new-device.key.pem` and `new-device.cert.pem`.
You can also checkout the `dawalton/certGen` branch of the sdk.

**Comment by chinmaychhajed** [comment]
Nevermind, somehow I resolved it myself, hence closing.

**Comment by az-iot-builder-01** [comment]
@chrissie926, @chinmaychhajed, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
