### ISSUE TITLE
iothubmessage-getstring needs better documentation

### ISSUE THREAD

**Issue by ericwol-msft** [Azure/azure-iot-sdk-c#1109]
**Repro:**
https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-message-h/iothubmessage-getstring

**Issue:**
Need to document who owns freeing the string.

**Comment by gregman-msft** [comment]
Proposed PR to header from which this document is generated: https://github.com/Azure/azure-iot-sdk-c/pull/1121

**Comment by danewalton** [comment]
The PR has been merged

**Comment by az-iot-builder-01** [comment]
@ericwol-msft, @gregman-msft, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
