### ISSUE TITLE
 iothub-client-core-common-h enum values lack any documentation

### ISSUE THREAD

**Issue by ericwol-msft** [Azure/azure-iot-sdk-c#1111]
**Repro:**
https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-client-core-common-h
What is IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY???

**Issue:**
All these enum values need code/public documentation.

**Comment by gregman-msft** [comment]
@ericwol-msft I added definitions for the ones that are not self explanatory, please see the PR

**Comment by jspaith** [comment]
Doing this correctly requires fixing the MU_DEFINE_ENUM stuff, since doxygen won't play nicely with what we have.  We have a draft PR of this up at https://github.com/Azure/azure-iot-sdk-c/pull/1342 which may or may not come in but it's blocked until then.

**Comment by az-iot-builder-01** [comment]
@ericwol-msft, @gregman-msft, @jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
