### ISSUE TITLE
IoTHubDeviceClient_LL_SetOption option "TrustedCerts" is not documented

### ISSUE THREAD

**Issue by ericwol-msft** [Azure/azure-iot-sdk-c#1112]
**Repro:**
When routing telemetry thu a IOT edge gateway, you need to specify the CA Root certificate.
This is done via the "TrustedCerts" option in the call to IoTHubDeviceClient_LL_SetOption().

**Issue:**
"TrustedCerts" is not publicly documented.
https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-device-client-ll-h/iothubdeviceclient-ll-setoption

**Comment by danewalton** [comment]
PR has been merged

**Comment by az-iot-builder-01** [comment]
@ericwol-msft, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by ericmitt** [comment]
The documentation still doesn't reflect the change. The line added in the .h doesn't explain what this option does and when to use it. created a new issue: 
https://github.com/Azure/azure-iot-sdk-c/issues/1242
