### ISSUE TITLE
Custom hsm sample memory leak

### ISSUE THREAD

**Issue by ukluk** [Azure/azure-iot-sdk-c#1113]
Platform mBed and FreeRTOS
SDK 1.3.4 (DPS and IoTHub Client)

I am running a forever loop connecting and disconnecting on a very constrained device.
Eventually, it throws a Hard Fault under `mallocAndStrcpy_s` I don't have a profiler running and I don't have the stack trace, (the fault is an interrupt so I am only able to look at the disassembly for `stacked_lr`)

What I noticed is that the HSM properties are requested multiple times but never released. I acknowledge that it might be my code, but I am following the sample as much as I can.

I will keep my investigation going but appreciate if you have some flow or suggestion how to free the memory for `custom_hsm_get_common_name`, `custom_hsm_get_certificate `and `custom_hsm_get_key`

**Console Logs**

Opening IoT Hub...

DEBUG:   iothubapp_open L#893 iothubapp_open
DEBUG:   iothubapp_open L#901 platform_init
DEBUG:   iothubapp_open L#908 serializer_init
DEBUG:   device_model_create L#1710 CREATE_MODEL_INSTANCE _devModel
Provisioning API Version: 1.3.4
DEBUG:   RegisterDps L#951 prov_dev_security_init
DEBUG:   RegisterDps L#959 Prov_Device_LL_Create
DEBUG:   RegisterDps L#992 Prov_Device_LL_Register_Device
custom_hsm_get_common_name
custom_hsm_get_certificate
custom_hsm_get_key
DEBUG:   RegisterDps L#1000
***     Prov_Device_LL_DoWork   ***

DNS:global.azure-devices-provisioning.net = 40.112.221.188
Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
Registration Information received from service: [server].azure-devices.net!
DEBUG:   RegisterDps L#1014 Prov_Device_LL_Destroy
DEBUG:   custom_hsm_destroy
DEBUG:   RegisterDps L#1016 prov_dev_security_deinit
***  D E V I C E  P R O V I S I O N E D  ***
Uri: [hostname].azure-devices.net
ID: c0529817-fc37-4f61-821b-3ac325b6e748
custom_hsm_get_certificate
custom_hsm_get_key
IoTHub Client API Version: 1.3.4
custom_hsm_get_certificate
custom_hsm_get_key

**Comment by danewalton** [comment]
There should be a function in your custom hsm .c called custom_hsm_destroy which allows you to free the components such as the CN, cert, key etc. Do you have that implemented?

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now but if you still need some help and want to reopen it in the future feel free.
