### ISSUE TITLE
Message get queued with IoTHubDeviceClient_LL_SendEventAsync()

### ISSUE THREAD

**Issue by fanshaoshan** [Azure/azure-iot-sdk-c#1129]
In my code, I send message with IoTHubDeviceClient_LL_SendEventAsync() and noticed that message sometime get queued in low layer and only after a while it been sent out and eventConfirmationCallback get invoked. Initially I thought that it's because I didn't call IoTHubDeviceClient_LL_DoWork() frequent enough, but even after I call it every 1s, eventConfigmationCallback() still get invoked few seconds later and delay is unpredictable.

In our platform, we have limited memory budget, message been queued in SDK layer will use memory and cause our application eventually get killed by lowmemorymonitor.

How to avoid message get queued in SDK layer and flush out ASAP? Is there an API to force flush of the message queue?

**Comment by danewalton** [comment]
Hey @fanshaoshan I'm going to close this for now but if you have any other questions/problems feel free to open another github issue. Thanks!

**Comment by az-iot-builder-01** [comment]
@fanshaoshan, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
