### ISSUE TITLE
How to use deivce group enrollments

### ISSUE THREAD

**Issue by v-jiq** [Azure/azure-iot-sdk-c#1131]
* ## system:
ubuntu16.04-x86

* ## problem:

The azure-document about dps[1] not clearly introduce that how to use azure-sdk-c to complete group enrollments in device end , not like java-sdk will tell you should use which sample code to complete group enrollments  in device end.  

by reference the document[2] , I guess whether can to implement  group enrollments in the device end using the way that  build the prov_dev_client_ll_sample program by connect the libcustom_hsm_example.a  (fill in the leaf device certificate from this document[3] to the custom_hsm_example.c Before generating libcustom_hsm_example.a).

Fowlling is Specific operation:

 i fill the variable of  COMMON_NAME 、PRIVATE_KEY、CERTIFICATE in custom_hsm_example.c file  by using the value of generated by the documents[3].

common_name -->   COMMON_NAME
./certs/new-device.cert.pem --> CERTIFICATE 
./private/new-device.key.pem --> PRIVATE_KEY

and then build to the libcustom_hsm_example.a.

finaly, execute the command  "cmake -Duse_prov_client:BOOL=ON -Dhsm_custom_lib=[CUSTOM HSM PATH] [PATH_TO_AZURE_IOT_SDK]" to build prov_dev_client_ll_sample.

but when i run the prov_dev_client_ll_sample,will occur follow error:
![图片](https://user-images.githubusercontent.com/39880470/63329062-d6891f00-c363-11e9-9687-268afa89579f.png)

my question is that the above way whether can realize the group enrollments using azure-sdk-iot-c in device end, if it can, i should how to resovle this problem,  if it not can, How do i implement this using azure-SDK-iot-c?

thanks!

[1]  https://docs.microsoft.com/en-us/Azure/iot-dps/tutorial-group-enrollments
[2] https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_custom_hsm.md
[3]https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md

**Comment by danewalton** [comment]
Did you set the id_scope in the sample? It should be line 68 on [prov_dev_client_sample.c](https://github.com/Azure/azure-iot-sdk-c/blob/d760a0f2a1e405331902851d287a04f24bfa013c/provisioning_client/samples/prov_dev_client_ll_sample/prov_dev_client_ll_sample.c#L68)

**Comment by v-jiq** [comment]
yes, it had been setted.
![图片](https://user-images.githubusercontent.com/39880470/63480432-6fcf4700-c4c4-11e9-9ff9-bb830b77584c.png)

**Comment by az-iot-builder-01** [comment]
@danewalton, @v-jiq, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
