### ISSUE TITLE
proxy error when using mbedtls adapter

### ISSUE THREAD

**Issue by alexmrtn** [Azure/azure-iot-sdk-c#1137]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Ubuntu 18.04 using GCC 7.4.0
libmbedtls 2.8.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2019-07-01 - 1.3.4

**Protocol**

MQTT_WS

**Describe the Bug**

When using the mbedtls adapter, device can not connect to iothub through a proxy. When using openssl adapter all is working fine.

**[MCVE](https://stackoverflow.com/help/mcve)**

Behavior can be reproduced using `iothub_convenience_sample` samples from iothub_client.

**Console Logs**

`iothub_convenience_sample` with [proxy set](https://github.com/Azure/azure-iot-sdk-c/blob/1.3.4/iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample.c#L67-L70) 

```
This sample will send messages continuously and accept C2D messages.
Press Ctrl+C to terminate the sample.

Creating IoTHub handle
Error: Time:Wed Aug 21 18:22:49 2019 File:/home/alex/Sources/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:IoTHubTransport_MQTT_Common_SetOption Line:3284 Cannot set proxy option once the underlying IO is created
Error: Time:Wed Aug 21 18:22:49 2019 File:/home/alex/Sources/azure-iot-sdk-c/iothub_client/src/iothub_client_core_ll.c Func:IoTHubClientCore_LL_SetOption Line:2331 unable to IoTHubTransport_SetOption
Error: Time:Wed Aug 21 18:22:49 2019 File:/home/alex/Sources/azure-iot-sdk-c/iothub_client/src/iothub_client_core.c Func:IoTHubClientCore_SetOption Line:1762 IoTHubClientCore_LL_SetOption failed
failure to set proxy
```

I moved the [setting of proxy](https://github.com/Azure/azure-iot-sdk-c/blob/1.3.4/iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample.c#L282-L294) before creation of ballback (that actually create all xio stack) [line 242](https://github.com/Azure/azure-iot-sdk-c/blob/1.3.4/iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample.c#L242). But I get another error:

```
Creating IoTHub Device handle
Sending message 1 to IoTHub
Error: Time:Wed Aug 21 18:23:05 2019 File:/home/alex/Sources/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_send Line:850 Invalid HTTP proxy IO state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Error: Time:Wed Aug 21 18:23:05 2019 File:/home/alex/Sources/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_close Line:784 Invalid tlsio_state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
The device client has been disconnected
Error: Time:Wed Aug 21 18:23:05 2019 File:/home/alex/Sources/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_send Line:850 Invalid HTTP proxy IO state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
The device client has been disconnected
Error: Time:Wed Aug 21 18:23:05 2019 File:/home/alex/Sources/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_send Line:850 Invalid HTTP proxy IO state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Sending message 2 to IoTHub
Error: Time:Wed Aug 21 18:23:05 2019 File:/home/alex/Sources/azure-iot-sdk-c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Error: Time:Wed Aug 21 18:23:05 2019 File:/home/alex/Sources/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_send Line:850 Invalid HTTP proxy IO state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Error: Time:Wed Aug 21 18:23:05 2019 File:/home/alex/Sources/azure-iot-sdk-c/c-utility/src/http_proxy_io.c Func:http_proxy_io_close Line:784 Invalid tlsio_state. Expected state is HTTP_PROXY_IO_STATE_OPEN.
Sending message 3 to IoTHub
```

**Comment by hihigupt** [comment]
Hey @alexmrtn can cherry-pick e8227dcf9152238bf05e88d92db06f924c2416eb to see if this fix works for you and you are unblocked on this.

**Comment by alexmrtn** [comment]
Hi,

I tested the fix you updated and it partially solves the problem:
- the behavior of the `iothub_convenience_sample` is exactly the same one as before, and I get the same error log : `Cannot set proxy option once the underlying IO is created`
- If I move the proxy set option in the same way descrive in my previous message it is now working without any error.

I currently use this workaround: setting the proxy before any other options that may create the background thread in the convenient API.
```C
g_iotHubClientHandle = IoTHubClient_CreateFromConnectionString(connectionString, MQTT_WebSocket_Protocol);
if (g_iotHubClientHandle == NULL)
{
   LOG_ERROR("Could not create connection to IoTHub");
}
else if (proxy.host_address != NULL && IoTHubClient_SetOption(g_iotHubClientHandle, OPTION_HTTP_PROXY, (void *)&proxy) != IOTHUB_CLIENT_OK)
{
    LOG_ERROR("Set proxy fails");
}
else if (IoTHubClient_SetOption(g_iotHubClientHandle, OPTION_TRUSTED_CERT, certificates) != IOTHUB_CLIENT_OK)
{
    LOG_ERROR("Set iothub certificate fails");
}
else if(IoTHubClient_SetOption(g_iotHubClientHandle, OPTION_LOG_TRACE, &trace) != IOTHUB_CLIENT_OK)
{
    LOG_ERROR("Set log fails");
}
else if(IoTHubClient_SetOption(g_iotHubClientHandle, OPTION_AUTO_URL_ENCODE_DECODE, &auto_url_decode) != IOTHUB_CLIENT_OK)
{
    LOG_ERROR("Set auto url decode fails");
}
else if (IoTHubClient_SetMessageCallback(g_iotHubClientHandle, receiveMessageCallback, NULL) != IOTHUB_CLIENT_OK)
{
     LOG_ERROR("Unable to register receiver callback");
}
else if (IoTHubClient_SetConnectionStatusCallback(g_iotHubClientHandle, onConnectionStatusChanges, NULL) != IOTHUB_CLIENT_OK)
{
    LOG_ERROR("Unable to register connection status callback");
}
```

**Comment by hihigupt** [comment]
Good. so pal works for you... Yes, sample needs to be fixed, I will update sample.

**Comment by hihigupt** [comment]
Sample has been updated in master.

**Comment by az-iot-builder-01** [comment]
@hihigupt, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
