### ISSUE TITLE
Can we invoke device methods while device is behind an authenticated http proxy and using mqtt websocket protocol ??

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#114]
- **OS and version used:** I use OS X 10.11.6. But I feel, this issue is independent of operating system 

- **SDK version used:** release_2017_04_07 

# Description of the issue:
My device is behind an authenticated http  proxy. I am able to send device to cloud messages over mqtt websocket protocol from behind proxy. But I **cannot** invoke direct method from cloud, if  the device is behind the proxy.

# Code sample exhibiting the issue:
I used the azure sample iothub_client_sample_device_method.c([1](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_device_method/iothub_client_sample_device_method.c)) as is. Minor changes being communication protocol changed to `MQTT_WebSocket_Protocol` and proxy addition with

```
HTTP_PROXY_OPTIONS proxy = { "192.168.1.90", 8080, "username", "password" };
if (IoTHubClient_LL_SetOption(iotHubClientHandle, "proxy_data", &proxy) != IOTHUB_CLIENT_OK) {
	printf("failure to set option \"proxy\"\r\n");
}
```

# Console log of the issue:
_Info: IoT Hub SDK for C, version 1.1.10
IoTHubClient_LL_SetDeviceMethodCallback...successful._

Please note that all code samples work perfectly, I am directly connected to internet without a proxy in middle.

**Comment by jebrando** [comment]
I believe device method should work behind a proxy.  The proxy should not inhibit any functionality.

**Comment by jtanner-msft** [comment]
Hi @kiranpradeep,
  As Jelani mentioned above we believe this should work thru a proxy.  One other test I was curious if you could try is to send a Cloud 2 Device message.  Does that work for you?  Meaning is it only Direct Methods that have an issue or all cloud 2 device communications?

**Comment by kiranpradeep** [comment]
@jtanner-msft Not just direct methods, all cloud to device communications are affected. Have you seen cloud to device messages working over http proxy with this C sdk ?

**Comment by kiranpradeep** [comment]
I needed to use the certs and that was the root cause. Thanks.
