### ISSUE TITLE
Connection Not Accepted: 0x5: Not Authorized

### ISSUE THREAD

**Issue by lph65724** [Azure/azure-iot-sdk-c#1141]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

macOS Mojave version 10.14.6
Windows 10

**SDK Version (Please Give Commit SHA if Manually Compiling)**

macOS:  SDK-c  AzureIoTHubClient (1.2.11), AzureIoTUtility (1.1.11), AzureIoTuAmqp (1.2.11), AzureIoTuMqtt (1.1.11)
Windows 10: SDK-c version 1.3.4 & SDK-java device-client: 1.17.5

**Protocol**

MQTT

**Describe the Bug**

we followed the steps described in [https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md](url) to create a certificate chain and  the sample [https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_client_x509_sample/iothub_ll_client_x509_sample.c](url), but we always get **Connection Not Accepted: 0x5: Not Authorized** repeatedly on both iOS device and ESP32 device.  However, if we use the very same procedures with Java, our Android device can successfully connect to the IoT Hub. When we check the connection status on both iOS device and ESP32, the status is always IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED, but both devices are actually enabled in the portal.

**Console Logs**

IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED
Error: Time:Fri Aug 23 16:45:24 2019 File:/.../azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTHubClient/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1607 Connection Not Accepted: 0x5: Not Authorized

**Comment by lph65724** [comment]
Hi @danewalton, we are using trusted certs.  Thank you

**Comment by danewalton** [comment]
The last line of the console logs leads me to believe that either the trusted cert or the generated device cert is not as it should. Specifically the "`Not Authorized`" part. Here in our sdk ([link](https://github.com/Azure/azure-iot-sdk-c/blob/b67aca086d90bb94cf06909d2f09458565573c9b/iothub_client/src/iothubtransport_mqtt_common.c#L1729)) there are two opportunities for the return callback to receive the `IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED` value: there and [line 1738](https://github.com/Azure/azure-iot-sdk-c/blob/b67aca086d90bb94cf06909d2f09458565573c9b/iothub_client/src/iothubtransport_mqtt_common.c#L1738). Does the same cert you create work on the other platforms?

**Comment by lph65724** [comment]
Hi @danewalton, we haven't tried using the very same cert.pem and key.pem on the other platform yet.  However, we followed the instructions at [link](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md) with our own certificate to generate key.pem and cert.pem for each device.  The created key.pem and cert.pem work flawlessly on Java, but both sets of key.pem and cert.pem created specifically for iOS and ESP32 devices don't work, and both consoles showed above error messages.  Nevertheless, with very same key.pem and cert.pem we created for ESP32, it is working now if we use the ESP-IDF, instead of VS code.

**Comment by danewalton** [comment]
that's very odd. and you didn't change the code at all moving from vscode to ESP-IDF? just changed the environment?

**Comment by lph65724** [comment]
No, we didn't modify the code.

**Comment by danewalton** [comment]
okay as far as the iOS device goes, are you using the native tls stack? because currently we don't support native macOS and iOS stacks for x509. [Discussion here](https://github.com/Azure/azure-iot-sdk-python/issues/271#issuecomment-490698956). The alternative is to use openssl for iOS/macOS. And for the ESP32 case, are you able to give me some more information on the tls stack you are using for that?

**Comment by lph65724** [comment]
Hi @danewalton, would you please let me know what specific information you need?  thank you

**Comment by danewalton** [comment]
Are you using mbedtls, wolfssl, etc. I was also notified that one of my coworkers has had some issues in the past when the local clock of the device was not configured correctly (out of sync with real time) and would get rejected from connecting. Might want to double check that as well.

**Comment by lph65724** [comment]
Hi @danewalton, thank you so much for your help. it was the time out of sync.  Appreciate your help

**Comment by az-iot-builder-01** [comment]
@danewalton, @lph65724, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by danewalton** [comment]
@lph65724 awesome to hear! thanks for your patience and glad we could help!
