### ISSUE TITLE
ENUM_TO_STRING not defined

### ISSUE THREAD

**Issue by formulahendry** [Azure/azure-iot-sdk-c#1144]
Follow the steps in https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-c-module
Customer has met with build errors, see details in https://github.com/MicrosoftDocs/azure-docs/issues/36983

![image](https://user-images.githubusercontent.com/1050213/63673116-18a7da00-c816-11e9-9dc5-39386686877a.png)

Previously, `ENUM_TO_STRING` is OK to use.

**Comment by az-iot-builder-01** [comment]
@formulahendry, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
