### ISSUE TITLE
Issue while installing Azure c sdk for cc3200

### ISSUE THREAD

**Issue by kcpoduru** [Azure/azure-iot-sdk-c#115]
cannot install azure sdk-c  tirtos for cc3200....

- **OS and version used:** <VERSION>  Windows 7

# Description of the issue:
 I was trying to install Azure c-sdk ti rtos for cc3200 and followed the instructions given in https://github.com/Azure/azure-iot-device-ecosystem/blob/master/get_started/ti-rtos-ti-cc3200-c.md
and got errors when executing. C:\ti\xdctools_3_31_01_33_core\gmake.exe all

# Console log of the issue:
 check the image [attached](url
![capture](https://cloud.githubusercontent.com/assets/25354759/25013167/3b170e90-2038-11e7-81df-b411c7c442a3.PNG)
)

**Comment by tameraw** [comment]
It seems that you are missing dependencies that should've been brought in during the cloning of the repo. So please confirm that you have cloned the repo recursively by running this command (per the instructions):
"git clone --recursive https://github.com/Azure/azure-iot-sdks.git"

**Comment by kcpoduru** [comment]
Yep I have done that.. i used --recursive while Installing

**Comment by kcpoduru** [comment]
![capture](https://cloud.githubusercontent.com/assets/25354759/25100571/42225b40-2376-11e7-8830-7c5a078889d6.PNG)

Can you verify the number of files getting downloaded. 

I also tried to install azure shared directory in the Aure-iot-sdk-c manually. Still I found no use

**Comment by olivierbloch** [comment]
You shouldn't use the azure-iot-sdks repository any more, it is deprecated.
Please use azure-iot-sdk-c instead.
We need to update the md file for the CC3200 device instructions.

**Comment by kcpoduru** [comment]
Yes. I have used Azure-iot-sdk-c in the first place. the first error above occured when I am working with Azure-iot-sdk-c

**Comment by olivierbloch** [comment]
I see.
Can you try and build for Windows to make sure you have all the bits in place? Do not use the script in build-all (as we are deprecating them), instead follow the instructions here: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md
Also I notice in your traces that your local repository folder is azure-iot-sdk-c-master. Did you download the repo as a zip or did you actually clone it?

**Comment by kcpoduru** [comment]
I did download it as zip.

**Comment by olivierbloch** [comment]
Got it.
Try and run the following command at the root the repo folder:
git submodule update --init --recursive

**Comment by kcpoduru** [comment]
Thanks It works!!!
