### ISSUE TITLE
WS_ERROR_UNDERLYING_IO_ERROR when using C SDK's device streams

### ISSUE THREAD

**Issue by rezasherafat** [Azure/azure-iot-sdk-c#1157]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Issue is reproducable in Linux (ubuntu 18.04)

**SDK Version (Please Give Commit SHA if Manually Compiling)**

public-preview branch

**Protocol**

MQTT

**Describe the Bug**

After successfully creating device streams WS tunnel, the transfer abruptly disconnects with `WS_ERROR_UNDERLYING_IO_ERROR` error.

**Console Logs**

```
[2019-08-21 21:42:44 UTC+0530] Network traffic (in bytes) (sent=21; received=0)
[2019-08-21 21:42:54 UTC+0530] Network traffic (in bytes) (sent=364092; received=5534)
on_ws_error (WS_ERROR_UNDERLYING_IO_ERROR)
-> [DETACH]* {5,true}
-> [DETACH]* {6,true}
-> [DETACH]* {2,true}
-> [DETACH]* {3,true}
-> [DETACH]* {4,true}
-> [DETACH]* {0,true}
-> [DETACH]* {1,true}
-> [END]* {}
-> [CLOSE]* {}
```

**Comment by rafilho** [comment]
Closing this issue since the fix was already merged. Please reopen in case you are still hitting the same issue. Thanks.

**Comment by az-iot-builder-01** [comment]
@rezasherafat, @rafilho, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
