### ISSUE TITLE
Problem in uploading file using iothub_client_sample_upload_to_blob

### ISSUE THREAD

**Issue by PRAVEENBADIGER** [Azure/azure-iot-sdk-c#1159]
Hi Team,

--> **Am using Ubuntu 14.0**
--> **Programming language c**

I'm trying to upload file using **iothub_client_sample_upload_to_blob** from **azure-iot-sdk-c** .

**Steps followed till now** :

1.  IOT HUB created.
2.  IOT Device created.
3.  Storage account created.
4.  Linked the storage account to IOT hub by using **File upload** option ,as per the given below link ,
   **https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-configure-file-upload**

5. Used the IOT Device **connecting string**  in iothub_client_sample_upload_to_blob example, but after running the binary the below error is listing ,

          **error logs start**

Starting the IoTHub client sample upload to blob...
Info: IoT Hub SDK for C, version 1.1.28
Error: Time:Wed Sep  4 18:10:59 2019 File:/home/praveen/workspace/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:598 Failure in HTTP communication: server reply code is 403
Info: HTTP Response:﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:0d693ac5-901e-0094-3c1e-63e4ca000000
Time:2019-09-04T12:41:00.8460821Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was rw

2019-09-04T13:40:59Z
/blob/v2xfilestorage/v2x/TELE/hello_world.txt

2017-04-17

</AuthenticationErrorDetail></Error>
Error: Time:Wed Sep  4 18:10:59 2019 File:/home/praveen/workspace/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:598 Failure in HTTP communication: server reply code is 400
Info: HTTP Response:{"Message":"{\"errorCode\":400019,\"trackingId\":\"07752a84a18a4b3b866bbf507aaa3946-G:10-TimeStamp:09/04/2019 12:41:01\",\"message\":\"File upload completion status is invalid\",\"timestampUtc\":\"2019-09-04T12:41:01.0790471Z\"}","ExceptionMessage":""}
Error: Time:Wed Sep  4 18:10:59 2019 File:/home/praveen/workspace/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_step3 Line:710 HTTP code was 400
Error: Time:Wed Sep  4 18:10:59 2019 File:/home/praveen/workspace/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_Impl Line:934 IoTHubClient_LL_UploadToBlob_step3 failed
hello world failed to upload

        **error logs end**

**My source code looks like,**

```
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

#ifdef DONT_USE_UPLOADTOBLOB
#error "trying to compile iothub_client_sample_upload_to_blob.c while DONT_USE_UPLOADTOBLOB is #define'd"
#else

#include <stdio.h>
#include <stdlib.h>

/* This sample uses the _LL APIs of iothub_client for example purposes.
That does not mean that HTTP only works with the _LL APIs.
Simply changing the using the convenience layer (functions not having _LL)
and removing calls to _DoWork will yield the same results. */

#ifdef ARDUINO
#include "AzureIoT.h"
#else
#include "azure_c_shared_utility/crt_abstractions.h"
#include "azure_c_shared_utility/platform.h"
#include "azure_c_shared_utility/shared_util_options.h"
#include "iothub_client_ll.h"
#include "iothub_message.h"
#include "iothubtransporthttp.h"
#include "certs.h"
#endif

#ifdef MBED_BUILD_TIMESTAMP
#include "certs.h"
#endif // MBED_BUILD_TIMESTAMP

/*String containing Hostname, Device Id & Device Key in the format:                         */
/*  "HostName=<host_name>;DeviceId=<device_id>;SharedAccessKey=<device_key>"                */
/*  "HostName=<host_name>;DeviceId=<device_id>;SharedAccessSignature=<device_sas_token>"    */
 

static` const char* connectionString = "HostName=V2X-KPIT.azure-devices.net;DeviceId=TELE;SharedAccessKey=ZzbC9lYyQeC5dWG/fBTER8NZrto0Uyol0juSoV1YNsU=";


/*Optional string with http proxy host and integer for http proxy port (Linux only)         */
static const char* proxyHost = NULL; 
static int proxyPort = 0;

#define HELLO_WORLD "Hello World from IoTHubClient_LL_UploadToBlob"

void iothub_client_sample_upload_to_blob_run(void)
{
    IOTHUB_CLIENT_LL_HANDLE iotHubClientHandle;

    if (platform_init() != 0)
    {
        (void)printf("Failed to initialize the platform.\r\n");
        
    }
    else
    {
       // (void)printf("\r\n***************************1**********************************\r\n");
        (void)printf("Starting the IoTHub client sample upload to blob...\r\n");

        if ((iotHubClientHandle = IoTHubClient_LL_CreateFromConnectionString(connectionString, HTTP_Protocol)) == NULL)
        {
            (void)printf("ERROR1: iotHubClientHandle is NULL!\r\n");
        }
        else
        {
              // (void)printf("\r\n**************************2***********************************\r\n");
            if (IoTHubClient_LL_SetOption(iotHubClientHandle, OPTION_TRUSTED_CERT, certificates) != IOTHUB_CLIENT_OK)
            {
                (void)printf("failure in IoTHubClient_LL_SetOption (TrustedCerts)");
            }
            else
            {
                 //  (void)printf("\r\n****************************3*********************************\r\n");
                HTTP_PROXY_OPTIONS http_proxy_options = {0};
                http_proxy_options.host_address = proxyHost;
                http_proxy_options.port = proxyPort;

                if (proxyHost != NULL && IoTHubClient_LL_SetOption(iotHubClientHandle, OPTION_HTTP_PROXY, &http_proxy_options) != IOTHUB_CLIENT_OK)
                {
                    (void)printf("failure to set proxy\n");
                }
                else
                {
                    //   (void)printf("\r\n*****************************4********************************\r\n");
                    if (IoTHubClient_LL_UploadToBlob(iotHubClientHandle, "./hello_world.txt", (const unsigned char*)HELLO_WORLD, sizeof(HELLO_WORLD) - 1) != IOTHUB_CLIENT_OK)
                    {
                        (void)printf("hello world failed to upload\n");
                    }
                    else
                    {
                          // (void)printf("\r\n****************************5*********************************\r\n");
                        (void)printf("hello world has been created\n");
                    }
                }
            }
            IoTHubClient_LL_Destroy(iotHubClientHandle);
        }
        platform_deinit();
    }
}
#endif /*DONT_USE_UPLOADTOBLOB*/
```

**please let me know what is the modification i need to do in the above code to resolve this issue**

Thanking you ,

Praveen

**Comment by danewalton** [comment]
Hey @PRAVEENBADIGER 
Are you able to remove the `./` prefix on the filename endpoint? So instead of `"./hello_world.txt"` just have `"hello_world.txt"`

**Comment by PRAVEENBADIGER** [comment]
Hi danewalton,

thank you so much for your quick response,i was able to resolve my problem.

Regards,
Praveen

**Comment by PRAVEENBADIGER** [comment]
Hi danewalton,

I have one more doubt ,in the above example  **iothub_client_sample_upload_to_blob**
which take input as **const unsigned char*** ,

( ie. as per my understanding : which takes buffer as a input and creates  file as per user given name and up-loads the file to storage account).

as given below,

```
 if (IoTHubClient_LL_UploadToBlob(iotHubClientHandle, "hello_world.txt", (const unsigned char*)HELLO_WORLD, sizeof(HELLO_WORLD) - 1) != IOTHUB_CLIENT_OK)
                    {
                        (void)printf("hello world failed to upload\n");
                    }
                    else
                    {
                          // (void)printf("\r\n****************************5*********************************\r\n");
                        (void)printf("hello world has been created\n");
                    }
```

**But my requirement is ,**

**I need to up-load already existing  file from my system to storage account** 

1) Is there any possibility to perform above requirement by modifying code from  **iothub_client_sample_upload_to_blob**.

**if ,YES,**
how it can be done?

**if NO,**
is the any other alternative method, it can be achieved through  **azure-iot-sdk-c** or **using c language.**


Thanks and Regards
Praveen

**Comment by az-iot-builder-01** [comment]
@danewalton, @PRAVEENBADIGER, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by PRAVEENBADIGER** [comment]
Hi danewalton,

I have one more doubt ,in the above example **iothub_client_sample_upload_to_blob**
which take input as **const unsigned char**

( ie. as per my understanding : which takes buffer as a input and creates file as per user given name and up-loads the file to storage account).

**as given below,**
```
if (IoTHubClient_LL_UploadToBlob(iotHubClientHandle, "hello_world.txt", (const unsigned char*)HELLO_WORLD, sizeof(HELLO_WORLD) - 1) != IOTHUB_CLIENT_OK)
                    {
                        (void)printf("hello world failed to upload\n");
                    }
                    else
                    {
                          // (void)printf("\r\n****************************5*********************************\r\n");
                        (void)printf("hello world has been created\n");
                    }


```
**But my requirement is ,**

**I need to up-load already existing file from my system to storage account**

Is there any possibility to perform above requirement by modifying code from **iothub_client_sample_upload_to_blob.**

**if ,YES,**
how it can be done?

**if NO,**
is the any other alternative method, it can be achieved through **azure-iot-sdk-c** or using c language.

Thanks and Regards
Praveen

**Comment by danewalton** [comment]
yes as long as you can read the file into a buffer you can pass that buffer to the upload to blob api and it will be uploaded.

**Comment by PRAVEENBADIGER** [comment]
Hi danewalton,

I agree with your answer, as long as i was able read the file into buffer i can able to push file to cloud.

But in my case i was using **.pcapng**  wireshark files and size can reach up to 1.5 -2 MB ,

Here,

1) My problem is,  i cannot read **.pcapng** as const unsigned char* buffer ?
2) Reading such big file and storing into a buffer, which seems to me time consuming and additional overhead in the program.

So my concern is,

**Is there any way which i can upload file to cloud directly without doing any file operations (ie. read to buffer) using c language**

**example** : The below curl command can able to upload file to storage account without any file operations to cloud.
`
curl -X PUT -T ./{file.dat} -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://{storageaccount}.blob.core.windows.net/backups/{file.dat}?{sas-token}"`


**any possibility i can establish FTP to azure cloud using c ?**  

Regards,
Praveen Badiger

**Comment by danewalton** [comment]
We do not have any api's which allow you to pass in a filename and upload to a blob. The api's we expose require the user to put whatever bytes they want to upload into a buffer and then push to a blob. However you decide to populate that buffer is up to you. The iot sdk also does not support ftp connections. If you wanted to do that you would have to find another way to do it.

I do want to ask though. Why are you not able to read the .pcapng file in to a buffer?

**Comment by PRAVEENBADIGER** [comment]
Hi danewalton,

Thanks for your inputs ,

Yes, i was able to read .pcapng files and uploaded  successfully to storage account .

Regards

Praveen Badiger

**Comment by PRAVEENBADIGER** [comment]
Hi danewalton,

Info: IoT Hub SDK for C, version **1.1.28**

When i run above SDK on **ubuntu 14.04** it works without any errors,

BUT , when i try to run the same SDK in **IMX6** with  **iothub_client_sample_upload_to_blob example, following errors  are generating** 

`
ASAWZ-Andriodwireshark-log.pcapng

/run/media/mmcblk0p3/log/pcap/ASAWZ-Andriodwireshark-log.pcapng
Wed Sep 18 12:03:08 UTC 2019
Error: Time:Wed Sep 18 12:03:08 2019 File:/usr/azure-iot-sdk-c/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_SetOption Line:800 failure in curl_easy_setopt - CURLOPT_SSL_CTX_FUNCTION
Error: Time:Wed Sep 18 12:03:08 2019 File:/usr/azure-iot-sdk-c/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:400 HTTPAPI_SetOption failed when called for option TrustedCerts
Error: Time:Wed Sep 18 12:03:10 2019 File:/usr/azure-iot-sdk-c/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_SetOption Line:800 failure in curl_easy_setopt - CURLOPT_SSL_CTX_FUNCTION
Error: Time:Wed Sep 18 12:03:10 2019 File:/usr/azure-iot-sdk-c/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:400 HTTPAPI_SetOption failed when called for option TrustedCerts
Wed Sep 18 12:03:13 UTC 2019

ASAWZ-Andriodwireshark-log.pcapng : file uploded to cloud


*************************************************************
IMA-Andriodwireshark-log2.pcapng

/run/media/mmcblk0p3/log/pcap/IMA-Andriodwireshark-log2.pcapng
Wed Sep 18 12:03:13 UTC 2019
Error: Time:Wed Sep 18 12:03:13 2019 File:/usr/azure-iot-sdk-c/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_SetOption Line:800 failure in curl_easy_setopt - CURLOPT_SSL_CTX_FUNCTION
Error: Time:Wed Sep 18 12:03:13 2019 File:/usr/azure-iot-sdk-c/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:400 HTTPAPI_SetOption failed when called for option TrustedCerts
Error: Time:Wed Sep 18 12:03:14 2019 File:/usr/azure-iot-sdk-c/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_SetOption Line:800 failure in curl_easy_setopt - CURLOPT_SSL_CTX_FUNCTION
Error: Time:Wed Sep 18 12:03:14 2019 File:/usr/azure-iot-sdk-c/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:400 HTTPAPI_SetOption failed when called for option TrustedCerts
Wed Sep 18 12:03:17 UTC 2019

IMA-Andriodwireshark-log2.pcapng : file uploded to cloud


`
The above errors are not effecting the functionality ,i was able to upload file to cloud .
But i want to resolve this errors ,can you please let me know how can i resolve this  ?

Regards,

Praveen Badiger

**Comment by danewalton** [comment]
Hey @PRAVEENBADIGER are you able to rerun this building with the latest sdk? Make sure to update the submodules with `git submodule update --init --recursive` from the root sdk directory. I know we had a fix/update in `httpapiex.c` and am curious if that helps your situation at all.

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now but if the issue rears it's head again please let us know in another github issue.

**Comment by danewalton** [comment]
Hey @PRAVEENBADIGER it seems after some further looking into that someone else that is using the imx6 board gets the same behavior. Could you give me some more information about what TLS stack you're using?
I think what's happening is the failure on line ~800 of httpapi_curl.c is returning `CURLE_NOT_BUILT_IN` because that cross-compile port of curl and the TLS you're using doesn't have this functionality. In other words we're setting options that aren't necessary for your configuration.

**Comment by danewalton** [comment]
I have a feeling you could be building curl with the `--without-ssl` option set. So the device would not be checking the cert from the service. If you look [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Docker_SDK_Cross_Compile.md) and search for the section of the script with the `# Build cURL`, we build curl with `--with-ssl` enabled.

**Comment by danewalton** [comment]
Closing the issue for now due to staleness.
