### ISSUE TITLE
Cloud-to-Device AMQP messages with IDs of type UUID are rejected

### ISSUE THREAD

**Issue by peterdn** [Azure/azure-iot-sdk-c#116]
- **OS and version used:** Ubuntu 14.0.4

- **SDK version used:** Git tag v 2017-04-07

# Description of the issue:
Cloud-to-Device AMQP messages with IDs of type UUID are rejected by the IoTHub Client.

It appears that the [readPropertiesFromuAMQPMessage function in uamqp_messaging.c](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/uamqp_messaging.c#L239) expects the message ID to be a string, even though the [AMPQ spec allows it to be ulong, UUID, binary, or string](http://docs.oasis-open.org/amqp/core/v1.0/amqp-core-messaging-v1.0.html#type-message-id-ulong).

This is particularly an issue as the iothub-explorer send command creates messages with IDs of type UUID.

# Console log of the issue:
Errors in log output:
```
In ~/code/caesium-azure-iot-sdks/src/iothub_client/src/uamqp_messaging.c: readPropertiesFromuAMQPMessage: line 242: Failed to get value of uAMQP message 'message-id' property (985).

In ~/code/caesium-azure-iot-sdks/src/iothub_client/src/uamqp_messaging.c: IoTHubMessage_CreateFromUamqpMessage: line 434: Failed reading properties of the uamqp message.
```

**Comment by olivierbloch** [comment]
Actually the MessageId is expected to be a string when communicating with Azure IoT Hub as per [the doc](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messaging#message-format).
