### ISSUE TITLE
Is Azure IOT C SDK compatible with Ingenico Telium 2 OS?

### ISSUE THREAD

**Issue by BhupalPatil** [Azure/azure-iot-sdk-c#1164]
Hi Team,
Is [Azure IoT C SDKs and Libraries](https://github.com/Azure/azure-iot-sdk-c) and [sample](https://github.com/Azure/azure-iot-sdk-c/blob/7a426159c1187715934a793e3e0b84bf955ea2a4/iothub_client/tests/iothubclient_uploadtoblob_e2e/iothubclient_uploadtoblob_e2e.c) compatible with Ingenico Telium 2 OS?

Thanks
Bhupal

**Comment by rafilho** [comment]
Thanks for your question, @BhupalPatil. The Azure IoT C SDK is implemented in C99 to allow portability. Therefore, you should be able to port our C SDK to Ingenico Telium 2 OS (or almost any other platform). Our [porting guide](https://github.com/Azure/azure-c-shared-utility/blob/master/devdoc/porting_guide.md) gives you details about what is needed from the platform to be able to support our SDK, as well give you instructions on how to achieve that. Thanks.

**Comment by az-iot-builder-01** [comment]
@BhupalPatil, @rafilho, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
