### ISSUE TITLE
UNIX/Linux support for creating token lifetime policies

### ISSUE THREAD

**Issue by chinmaychhajed** [Azure/azure-iot-sdk-c#1175]
Hello,

- Are there any variables/macros which can be set to change token lifetime?
- I came across [this](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#example-token-lifetime-policies) to set token lifetime through CLI but it is present for powershell and I need support for UNIX/Linux. Is there any link which I'm unable to find? If yes, please share.

Are there tokens used in multiple ways? If yes, I'm talking about login token.

Thanks in advance.

**Comment by danewalton** [comment]
Hi @chinmaychhajed are you sure this is an IoT issue? This seems like it is something to be directed towards Azure Active Directory. [This is the link to their help page](https://docs.microsoft.com/en-us/azure/active-directory/develop/developer-support-help-options) and [this is a link to their various github repos.](https://docs.microsoft.com/en-us/azure/active-directory/develop/developer-support-help-options) Hope that helps!

**Comment by chinmaychhajed** [comment]
Oh cool, actually I was using this repo and stumbled upon this issue so I filed this issue here! Anyways thanks for help.

**Comment by az-iot-builder-01** [comment]
@danewalton, @chinmaychhajed, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
