### ISSUE TITLE
Confusion about D2C message size limits

### ISSUE THREAD

**Issue by Hmaalla** [Azure/azure-iot-sdk-c#1180]
Hi,
We have some confusion about D2C message size limits
According azure documentation, D2C message is limited to 256KB, but there's no information whatever this limits concerns only payload or the whole message.  
We have tested the following cases using the "sample iothub_convenience_sample" available in deps/azure-iot-sdk-c/iothub_client/samples/ :

### Test 1 :
Sending a message with '255KB' as payload and '1KB' for (msg id + correlation + properties) => the test passes

### Test 2 :
Sending a message with '1KB' payload and '255kB' for (msg id + correlation + properties) => the test fails, the log is below:

```
Creating IoTHub handle
The device client is connected to iothub
Error: Time:Tue Sep 17 14:38:34 2019 File:mqtt_client.c Func:mqtt_client_publish Line:1052 Error: mqtt_codec_publish failed
Error: Time:Tue Sep 17 14:38:34 2019 File:iothubtransport_mqtt_common.c Func:publish_mqtt_telemetry_msg Line:865 Failed attempting to publish mqtt message
Confirmation callback received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_ERROR
```

### Test 3 :
Sending a message with '30KB' as payload and 128K for (msg id + correlation + properties) => the test fails, the log is below:

```
Creating IoTHub handle
The device client is connected to iothub
Error: Time:Tue Sep 17 14:40:54 2019 File:mqtt_client.c Func:mqtt_client_publish Line:1052 Error: mqtt_codec_publish failed
Error: Time:Tue Sep 17 14:40:54 2019 File:iothubtransport_mqtt_common.c Func:publish_mqtt_telemetry_msg Line:865 Failed attempting to publish mqtt message
Confirmation callback received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_ERROR
```

### Test 4 :
Sending a message with '30KB' as payload and 60KB for (msg id + correlation + properties) => the test passes

After a code inspection, we found that topic name size is limited to '64KB', and it's composed by device name+url+message id + correlation id + properties
Could you please give us more details about message limits for each field?

**Comment by ewertons** [comment]
Hi @Hmaalla ,
thank you very much for the detailed testing and explanation.
Indeed we apologize, but we do not have a clear documentation about message size limits. We have that in our stack to fix in the docs.

Inspecting the [code](https://github.com/Azure/azure-umqtt-c/blob/7557db6de094b67818d3c410dc95a3cf07cd86a6/src/mqtt_codec.c#L740), you will see that the maximum payload size is 255 KB,

and 

According to the MQTT spec, topic names cannot be bigger than 65535 bytes long.
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf

1450:    Names and Topic Filters are UTF-8 encoded strings, they MUST NOT encode to more than 
1451:    65535 bytes [MQTT-4.7.3-3]. See Section 1.5.3 1451

Many aspects play into the maximum size and number of custom properties the user is left with when using MQTT. 
The topic names supported by Azure IoT Hub contain
- a fixed path per feature, which uses the device ID in it (e.g., [devices/\<device-id\>/messages/devicebound/#](https://github.com/Azure/azure-iot-sdk-c/blob/2019-10-07/iothub_client/src/iothubtransport_mqtt_common.c#L66)),
- predefined "properties" (key and value strings concatenated after the fixed path above) pertaining to the feature being used (for telemetry, e.g., if message is a [security message](https://github.com/Azure/azure-iot-sdk-c/blob/2019-10-07/iothub_client/src/iothubtransport_mqtt_common.c#L735)),
- then the actual client message (IOTHUB_MESSAGE_HANDLE) contains pre-defined system properties supported by the Azure IoT Hub (e.g., correlation-id, content-type)
- and finally the custom properties from IOTHUB_MESSAGE_HANDLE that are also concatenated.

So the total amount of bytes left for custom properties depend on the other 3 components above.
To be more precise we will need to compile all the possible permutations above, for all features we use, and update the documentation, but we hope this will help bring some clarity about how it works throughout the code.

**Comment by Hmaalla** [comment]
@ewertons - Thanks for the detailed answer!

**Comment by gregman-msft** [comment]
@Hmaalla Thank you for the feedback. You can also find this and our other limits in [this document](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#iot-hub-limits). We're working on adding it to other docs to make this easier to find, as well.

**Comment by az-iot-builder-01** [comment]
@ewertons, @Hmaalla, @gregman-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
