### ISSUE TITLE
Upload blob to storage account without IoT Hub

### ISSUE THREAD

**Issue by BenPYeh** [Azure/azure-iot-sdk-c#1181]
We have an IoT Hub with a Storage Account connected, and we call  IoTHubClient_UploadToBlobAsync with the IoT Hub handle and it uploads the blob to the associated storage account as expected. Is there an API to upload directly to the storage account? The reason is we'd like to use IoT Central instead, and we can't associate a storage account in the same way and use the same API.

**Comment by danewalton** [comment]
Hi @BenPYeh 
Currently the storage team offers a C++ sdk to upload to blob [here](https://github.com/Azure/azure-storage-cpp). This is what you would need to use to upload to a blob directly.

**Comment by danewalton** [comment]
I'm going to go ahead and close this issue for now. If you have any further problems feel free to open another issue.

**Comment by az-iot-builder-01** [comment]
@BenPYeh, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
