### ISSUE TITLE
Document LL versus convenience layer

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1186]
We need clearer documentation about when and how to use LL versus convenience layer.

There's some explanation in specs and some references to samples, but this feels like it deserves a separate topic in docs.

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
