### ISSUE TITLE
Azure IOT hub channel closing issue(IoTHubDeviceClient_LL_Destroy(handle)).

### ISSUE THREAD

**Issue by PraveenKolipaka1** [Azure/azure-iot-sdk-c#1187]
------------------------------- delete below -------------------------------

Objective:
We want to start Azure IOT hub connection dynamically (on demand). And similarly stop/close the same dynamically.
Platform details: Mac OSX 10.14.5,Azure IOT Hub SDK version: 1.3.3,Xcode 10.2
Issue:
Though we can open Azure IOT Hub channel with the help of API’s, we are unable to locate an API to stop/close the same.
 
Description:
Initially, I thought that API IoTHubDeviceClient_LL_Destroy(handle) will do the required thing by closing the channel.
But, I have noticed that even after destroying the handle, App is still receiving the direct method calls from Azure IOT Hub.
 
Current Approach to disconnect( sample code):
void disconnect(){
   
IOTHUB_DEVICE_CLIENT_LL_HANDLE local_device_ll_handle;
   
/* global_device_handle is created during Azure IOT Hub start up, Using API  IoTHubDeviceClient_LL_CreateFromConnectionString(connection String, protocol); */
 
    local_device_ll_handle =   global_device_handle;
    global_device_handle = NULL;
 
    if(local_device_ll_handle !=NULL){
        (void)IoTHubDeviceClient_LL_SetDeviceMethodCallback(local_device_ll_handle, NULL, NULL);
    }
}
 
Need Help:
I would like to make sure whether my current approach is safe. if not, would need sample code to do the same as I don’t see in any of the Azure IOT sdk samples does this.

------------------------------- delete above -------------------------------

**Comment by markrad** [comment]
Hi Praveen,

Since I am assisting you with this question in a support request, I am closing this issue.

_Mark Radbourne MSFT_

**Comment by az-iot-builder-01** [comment]
@PraveenKolipaka1, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
