### ISSUE TITLE
Allow all `install(EXPORT ...)` to be disabled for bare-metal projects

### ISSUE THREAD

**Issue by FreddieChopin** [Azure/azure-iot-sdk-c#1188]
**Is your feature request related to a problem? Please describe.**
When using azure-iot-sdk-c as a submodule for an embedded bare-metal project (e.g. STM32F7 microcontroller) one would prefer to reuse as much of build system as possible - ideal solution is to reuse it entirely, with zero changes, as any change requires either a fork or working with a snapshot, which will soon become outdated. In such scenario you would link your bare-metal RTOS and other libraries (like TCP/IP stack, mbedTLS, clock drivers, ...) directly to `aziotsharedutil` library with `target_link_libraries(...)`. However here's the problem. For a bare-metal application there is zero support (and zero need) to have any "install" and "export" functionality, so it's just not there. However Azure IoT SDK has such support. In this situation CMake rejects such `target_link_libraries(...)` with following error: `install (EXPORT "B" ...) includes target "B" which requires target "A" that is not in the export set.` Fixing this - by adding dummy "install" and "export" support to the RTOS and other libs - is non-trivial, because then CMake requires all of them to have include folders _NOT_ prefixed with source directory absolute paths. So this would instead require forking other bare-metal libraries (or working with snapshots) - for example lwIP. Such non-trivial work would be also completely pointless, as there is zero need to "install" or "export" anything in such scenario.

**Describe the solution you'd like**
Actually the easiest solution is to make all `install(EXPORT ...)` in azure-iot-sdk-c and all of the submodules conditional - either on some user-selectable option or maybe just a global variable/property or maybe even auto-detected condition. With all `install(EXPORT ...)` disabled, CMake no longer complains and you can link anything you like to `aziotsharedutil`.

**Describe alternatives you've considered**
Adding support to "install" and "export" to all the libraries you would like to link to `aziotsharedutil` is not simple, as each library would have to be modified to never use absolute include paths. No bare-metal library for microcontrollers has that provided (as it is not needed at all), so this is not really a solution - you would have to fork/copy a lot of different projects and modify them with a dummy change which has zero usage.

**Additional context**
There is no way to disable `install(EXPORT ...)` other than modifying azure-iot-sdk-c and all of the submodules.

**Comment by danewalton** [comment]
Hi @FreddieChopin 
Are you able to give me more details about how to reproduce this? I think it might be easier for me to understand this problem if I can get it to occur myself.
My initial reaction to this is that we allow the option to use installed dependencies or the build system's resulting libraries. Am I wrong in assuming that your scenario calls for the latter? And how might that option be falling short here?

**Comment by FreddieChopin** [comment]
I think you misunderstood me, but no worries - I'm used to that (; It's just that people working with "high-level" programming (targeting Linux, Windows and so on) don't understand the workflow that is used in "small embedded". Please note that I'm not talking about "embedded Linux" and things like Raspberry Pi. I'm talking about small microcontrollers, which do NOT have any "real" operating systems. There is no OS, no processes, no shell, no bootloader, you don't have an executable which you can start or stop. Everything you compile is a single image which you load directly into the chips ROM memory. You power the chip up - it starts executing the code.

For such cases you are cross-compiling everything. You almost never "install" anything, as each project requires slightly different configuration (for example just one manufacturer produces chips with 4 different ARM Cortex-M cores (ARM Cortex-M0, -M3, -M4 nad -M7), some of them without an FPU, some of them with one or another type of FPU. Installing anything would be a PITA.

So libraries for such systems are not installed, because it makes no sense at all - you recompile everything directly from source in each project. Therefore such libraries - if they use CMake - do not provide any configuration for installation/export - there are no `install(EXPORT ...)` functions in the build system.

Such libraries are (among others):
- RTOS which provides threading, synchronization and sleeps,
- TCP/IP stack which provides networking - like lwIP,
- crypto stack - like mbed TLS.

The whole build system for azure SDK is constructed so that you want to link these low-level libraries to the lowest possible library provided by azure - which is aziotsharedutil (possibly via an intermediate "integration" library which wraps functions from these libraries into APIs expected by azure, but this doesn't matter here).

To simulate something like that just open `c-utility/CMakeLists.txt` and at the very end add:
```

add_library(rtos STATIC dummy.c)
target_link_libraries(aziotsharedutil PUBLIC rtos)

add_library(tcpip STATIC dummy.c)
target_link_libraries(aziotsharedutil PUBLIC tcpip)

add_library(crypto STATIC dummy.c)
target_link_libraries(aziotsharedutil PUBLIC crypto)
```
(in the real application you could have something like this in the main `CMakeLists.txt` for the application, "above" azure)

Create an empty `dummy.c` in `c-utility` and try to build it:

```
CMake Error: install(EXPORT "aziotsharedutilTargets" ...) includes target "aziotsharedutil" which requires target "rtos" that is not in the export set.
CMake Error: install(EXPORT "aziotsharedutilTargets" ...) includes target "aziotsharedutil" which requires target "tcpip" that is not in the export set.
CMake Error: install(EXPORT "aziotsharedutilTargets" ...) includes target "aziotsharedutil" which requires target "crypto" that is not in the export set.
```

This is the problem I'm talking about.

The easiest solution is to make all `install(EXPORT ...)` functions in azure conditional - by default they can be enabled, and the option which enables that may be hidden (for example marked as "advanced" in CMake). Or it may be just a plan variable, which you set only if you wish to disable installation and exports. This is the only viable solution to this problem which would not require modifying every external library just to have a dummy non-functional and completely useless "install/export" configuration.

**Comment by danewalton** [comment]
Ahhh okay I see what you're saying. Let me try a couple things and get back to your here.

**Comment by danewalton** [comment]
Hey @FreddieChopin quick question. Are you able to run cmake and build successfully if you link your static libs using PRIVATE instead of using PUBLIC?

**Comment by ewertons** [comment]
Hi @FreddieChopin ,

We apologize for the long delay, but we were assigned to work on new code development and that affected our github response time.

There is now a better option for bare-metal systems for connecting with the Azure IoT services.
Please check the new [Azure SDK for Embedded C](https://github.com/azure/azure-sdk-for-c) solution.
That should be a better fit for your project.

We will close this issue, but if you would like it to be reopened and follow up on this matter, please post a comment requesting so.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@FreddieChopin, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
