### ISSUE TITLE
IoTHubClient accepted the message for delivery

### ISSUE THREAD

**Issue by SpaBruis** [Azure/azure-iot-sdk-c#1190]
![afbeelding](https://user-images.githubusercontent.com/55592439/65336814-53a7ee00-dbc7-11e9-93da-d38ef9e4cc01.png)
The code gets stuck after "IoTHubClient accepted the message for delivery"
Thanks in advance

**Main code:**

// Wifi libraries
#include <ESP8266WiFi.h>
#include <WiFiClientSecure.h>
#include <WiFiUdp.h>

// IoT hub libraries
#include <AzureIoTHub.h>
#include <AzureIoTProtocol_MQTT.h>
#include <AzureIoTUtility.h>

// Set variables
#define SSID_LEN 32 // Max length of the SSID
#define PASS_LEN 32 // Max length of the Password
#define CONNECTION_STRING_LEN 256 // Max length Connection String
#define MESSAGE_MAX_LEN 256
#define DEVICE_ID "something_Plant1"
#define MESSAGE_ID "Aloe Vera"

// Wifi login credentials
static char *connectionString = "HostName=somethinghub.azure-devices.net;DeviceId=something_Plant1;SharedAccessKey=something";
static char *ssid = "something";
static char *pass = "something";

static bool messagePending = false;
static bool messageSending = true;
static IOTHUB_CLIENT_LL_HANDLE iotHubClientHandle;
void setup()
{   
    Serial.begin(115200);
    initWifi(); // Setup the wifi connection
    iotHubClientHandle = IoTHubClient_LL_CreateFromConnectionString(connectionString, MQTT_Protocol);
    if (iotHubClientHandle == NULL)
    {
        Serial.println("Failed on IoTHubClient_CreateFromConnectionString.");
        while (1);
    }
    IoTHubClient_LL_SetOption(iotHubClientHandle, "product_info", "something");
    IoTHubClient_LL_SetMessageCallback(iotHubClientHandle, receiveMessageCallback, NULL);
    IoTHubClient_LL_SetDeviceMethodCallback(iotHubClientHandle, deviceMethodCallback, NULL);
    IoTHubClient_LL_SetDeviceTwinCallback(iotHubClientHandle, twinCallback, NULL);
}

void loop() {
  if (!messagePending && messageSending)
    {
        char messagePayload[MESSAGE_MAX_LEN];
        readMessage(MESSAGE_ID, messagePayload);
        sendMessage(iotHubClientHandle, messagePayload);
    }
    IoTHubClient_LL_DoWork(iotHubClientHandle);
    delay(10);
}

**IoT hub client code:**
static WiFiClientSecure sslClient; // for ESP8266

const char *onSuccess = ""Successfully invoke device method"";
const char *notFound = ""No method found"";

static void sendCallback(IOTHUB_CLIENT_CONFIRMATION_RESULT result, void *userContextCallback)
{
if (IOTHUB_CLIENT_CONFIRMATION_OK == result)
{
Serial.println("Message sent to Azure IoT Hub");
}
else
{
Serial.println("Failed to send message to Azure IoT Hub");
}
messagePending = false;
}

static void sendMessage(IOTHUB_CLIENT_LL_HANDLE iotHubClientHandle, char *buffer)
{
IOTHUB_MESSAGE_HANDLE messageHandle = IoTHubMessage_CreateFromByteArray((const unsigned char *)buffer, strlen(buffer));
if (messageHandle == NULL)
{
Serial.println("Unable to create a new IoTHubMessage.");
}
else
{
MAP_HANDLE properties = IoTHubMessage_Properties(messageHandle);
Serial.printf("Sending message: %s.\r\n", buffer);
if (IoTHubClient_LL_SendEventAsync(iotHubClientHandle, messageHandle, sendCallback, NULL) != IOTHUB_CLIENT_OK)
{
Serial.println("Failed to hand over the message to IoTHubClient.");
}
else
{
messagePending = true;
Serial.println("IoTHubClient accepted the message for delivery.");
}

    IoTHubMessage_Destroy(messageHandle);
}

}

void start()
{
Serial.println("Start sending temperature and humidity data.");
messageSending = true;
}

void stop()
{
Serial.println("Stop sending temperature and humidity data.");
messageSending = false;
}

IOTHUBMESSAGE_DISPOSITION_RESULT receiveMessageCallback(IOTHUB_MESSAGE_HANDLE message, void *userContextCallback)
{
IOTHUBMESSAGE_DISPOSITION_RESULT result;
const unsigned char *buffer;
size_t size;
if (IoTHubMessage_GetByteArray(message, &buffer, &size) != IOTHUB_MESSAGE_OK)
{
Serial.println("Unable to IoTHubMessage_GetByteArray.");
result = IOTHUBMESSAGE_REJECTED;
}
else
{
/buffer is not zero terminated/
char *temp = (char *)malloc(size + 1);

    if (temp == NULL)
    {
        return IOTHUBMESSAGE_ABANDONED;
    }

    strncpy(temp, (const char *)buffer, size);
    temp[size] = '\0';
    Serial.printf("Receive C2D message: %s.\r\n", temp);
    free(temp);
}
return IOTHUBMESSAGE_ACCEPTED;

}

int deviceMethodCallback(
const char *methodName,
const unsigned char *payload,
size_t size,
unsigned char **response,
size_t *response_size,
void *userContextCallback)
{
Serial.printf("Try to invoke method %s.\r\n", methodName);
const char *responseMessage = onSuccess;
int result = 200;

if (strcmp(methodName, "start") == 0)
{
    start();
}
else if (strcmp(methodName, "stop") == 0)
{
    stop();
}
else
{
    Serial.printf("No method %s found.\r\n", methodName);
    responseMessage = notFound;
    result = 404;
}

*response_size = strlen(responseMessage);
*response = (unsigned char *)malloc(*response_size);
strncpy((char *)(*response), responseMessage, *response_size);

return result;

}

void twinCallback(
DEVICE_TWIN_UPDATE_STATE updateState,
const unsigned char *payLoad,
size_t size,
void *userContextCallback)
{
char *temp = (char *)malloc(size + 1);
for (int i = 0; i < size; i++)
{
temp[i] = (char)(payLoad[i]);
}
temp[size] = '\0';
parseTwinMessage(temp);
free(temp);
}

**Comment by SpaBruis** [comment]
static WiFiClientSecure sslClient; // for ESP8266

const char *onSuccess = "\"Successfully invoke device method\"";
const char *notFound = "\"No method found\"";

static void sendCallback(IOTHUB_CLIENT_CONFIRMATION_RESULT result, void *userContextCallback)
{
    if (IOTHUB_CLIENT_CONFIRMATION_OK == result)
    {
        Serial.println("Message sent to Azure IoT Hub");
    }
    else
    {
        Serial.println("Failed to send message to Azure IoT Hub");
    }
    messagePending = false;
}

static void sendMessage(IOTHUB_CLIENT_LL_HANDLE iotHubClientHandle, char *buffer)//, bool temperatureAlert)
{
    IOTHUB_MESSAGE_HANDLE messageHandle = IoTHubMessage_CreateFromByteArray((const unsigned char *)buffer, strlen(buffer));
    if (messageHandle == NULL)
    {
        Serial.println("Unable to create a new IoTHubMessage.");
    }
    else
    {
        MAP_HANDLE properties = IoTHubMessage_Properties(messageHandle);
        Serial.printf("Sending message: %s.\r\n", buffer);
        if (IoTHubClient_LL_SendEventAsync(iotHubClientHandle, messageHandle, sendCallback, NULL) != IOTHUB_CLIENT_OK)
        {
            Serial.println("Failed to hand over the message to IoTHubClient.");
        }
        else
        {
            messagePending = true;
            Serial.println("IoTHubClient accepted the message for delivery.");
        }

        IoTHubMessage_Destroy(messageHandle);
    }
}

void start()
{
    Serial.println("Start sending temperature and humidity data.");
    messageSending = true;
}

void stop()
{
    Serial.println("Stop sending temperature and humidity data.");
    messageSending = false;
}

IOTHUBMESSAGE_DISPOSITION_RESULT receiveMessageCallback(IOTHUB_MESSAGE_HANDLE message, void *userContextCallback)
{
    IOTHUBMESSAGE_DISPOSITION_RESULT result;
    const unsigned char *buffer;
    size_t size;
    if (IoTHubMessage_GetByteArray(message, &buffer, &size) != IOTHUB_MESSAGE_OK)
    {
        Serial.println("Unable to IoTHubMessage_GetByteArray.");
        result = IOTHUBMESSAGE_REJECTED;
    }
    else
    {
        /*buffer is not zero terminated*/
        char *temp = (char *)malloc(size + 1);

        if (temp == NULL)
        {
            return IOTHUBMESSAGE_ABANDONED;
        }

        strncpy(temp, (const char *)buffer, size);
        temp[size] = '\0';
        Serial.printf("Receive C2D message: %s.\r\n", temp);
        free(temp);
    }
    return IOTHUBMESSAGE_ACCEPTED;
}

int deviceMethodCallback(
    const char *methodName,
    const unsigned char *payload,
    size_t size,
    unsigned char **response,
    size_t *response_size,
    void *userContextCallback)
{
    Serial.printf("Try to invoke method %s.\r\n", methodName);
    const char *responseMessage = onSuccess;
    int result = 200;

    if (strcmp(methodName, "start") == 0)
    {
        start();
    }
    else if (strcmp(methodName, "stop") == 0)
    {
        stop();
    }
    else
    {
        Serial.printf("No method %s found.\r\n", methodName);
        responseMessage = notFound;
        result = 404;
    }

    *response_size = strlen(responseMessage);
    *response = (unsigned char *)malloc(*response_size);
    strncpy((char *)(*response), responseMessage, *response_size);

    return result;
}

void twinCallback(
    DEVICE_TWIN_UPDATE_STATE updateState,
    const unsigned char *payLoad,
    size_t size,
    void *userContextCallback)
{
    char *temp = (char *)malloc(size + 1);
    for (int i = 0; i < size; i++)
    {
        temp[i] = (char)(payLoad[i]);
    }
    temp[size] = '\0';
    parseTwinMessage(temp);
    free(temp);
}

**Comment by danewalton** [comment]
Hi @SpaBruis 
Is it possible you are running out of memory? Often times interrupt handlers for an out of memory exception are defaulted to a `while(1){ }` loop. Are you able to add a breakpoint at that exception?

**Comment by SpaBruis** [comment]
Hi @danewalton ,
Thanks for your reply! I am running this code directly on a NodeMCU v1.0 and also tried to run it on an ESP8266 - 01. I develop in Arduino IDE so i guess a breakpoint is not an option?

**Comment by danewalton** [comment]
Are you able to turn on logging at all? it's hard to diagnose the problem without some logging or confirmation of breakpoint hits or something like that. Can you maybe print a message in the interrupt handler for an out of memory exception?

**Comment by SpaBruis** [comment]
@danewalton TLS to the IoT hub fails:
![failure](https://user-images.githubusercontent.com/55592439/66033525-bffbe900-e507-11e9-8e32-a44ec44d01b7.PNG)

**Comment by SpaBruis** [comment]
I have found the solution:
https://github.com/Azure/azure-iot-arduino/issues/89
Thanks for your time, @danewalton

**Comment by danewalton** [comment]
Awesome to hear @SpaBruis! If you have any other issues feel free to open another issue.

**Comment by az-iot-builder-01** [comment]
@danewalton, @SpaBruis, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
