### ISSUE TITLE
DIGITALTWIN_CLIENT_ASYNC_COMMAND_UPDATE.propertyData isn't consistent type

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1191]
In general for C SDK, we have our payloads as "unsigned const char" just so we have some flexibility if we use a non-JSON format.

Except - in `DIGITALTWIN_CLIENT_ASYNC_COMMAND_UPDATE`, this is a char* propertyData but not unsigned const char*.

Same feedback for `DigitalTwin_InterfaceClient_SendTelemetryAsync` and `DigitalTwin_InterfaceClient_ReportPropertyAsync`.  Needs to be consistent.

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
