### ISSUE TITLE
Have ability to disable sending SDKInformation

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1192]
When an application calls `DigitalTwin_DeviceClient_RegisterInterfacesAsync`, we automatically send over the SDKInformation (basically {language=C, C SDK version, vendor=Microsoft}).  

This is needed for device certification AND for is also handy for solutions developers to be able to depend on it.

However there maybe cases where customer doesn't want it, either for bandwidth or quotaing or just because.  Add an API to disable sending. 

Instead of a "SetOption", as DeviceClient has historically followed, we're probably going to go with a properly typed API at top level.  So something like `DigitalTwin_DeviceClient_DisableSDKInformation` (e.g.).  The Device Client needs untyped SetOption to shoot commands down to the PAL layer, PnP won't communicate this low so does't need a raw `DeviceIoControl` style un-typed pipe.

**Comment by jasmineymlo** [comment]
SDK Information component is implemented as sample and no longer send by default on successful DigitalTwin_DeviceClient_RegisterInterfacesAsync().  Fix in beadb055ed53a7c4c523777b58dd32db0dbc9f38.

**Comment by az-iot-builder-01** [comment]
@jspaith, @jasmineymlo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
