### ISSUE TITLE
 Optimize command / property subscription

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1196]
If no interfaces have registered command callbacks (or analogously properties), then C SDK should not subscribe on command channel (or device twin). Reason is to save bandwidth and customer $$ from extra topics in play.

There's two ways to do this:
* At runtime.  Very easy to run through list of interface handles and see if anything needs it.  Benefit is no customer changing of this code, through drawback is that the ROM hit for DeviceTwin and/or commands is still there.  Linker optimizer can't figure out to remove unused code the way PnP is structured.
* At build time.  Basically application can say "I don't want to use commands and/or properties"  and code implementing these is removed at build time.  

The build time adds complexity though, to customers and us (because build time may expand the UT matrix).  Need to figure out just how much this would save.

**Comment by jasmineymlo** [comment]
This will be addressed by having application in control of command/property subscription which is included in the task for breaking down register interfaces into multiple APIs.

**Comment by az-iot-builder-01** [comment]
@jspaith, @jasmineymlo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
