### ISSUE TITLE
Move to standard enums in PnP public headers

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1200]
DigitalTwin client followed the convention of rest of IoTHub in using `MU_DEFINE_ENUM` to specify enums, so it'd be easy to stringify errors.

I don't think having an easy stringify is worth this.  Because:
* It gets pre-processor into our business, never a good thing.  In particular...
* Extra cognitive load on developer to understand this construct, rather than an enum.
* Any source editor that doesn't build up a full AST (e.g. Source Insight) will get confused on this.
* Won't work with doxygen, and @danewalton and I both certainly tried.
* Brings extra overhead for string table into all functions.

So recommend under .\digitaltwin_client directory making everything a pure enum.  I don't think we need stringify helpers either - a simple error code as a %d should suffice.

**Comment by ewertons** [comment]
Be noted that this will break from the guidance on the rest of the API.
I would suggest we align the strategy across the SDK instead.

**Comment by jspaith** [comment]
Yes, let's talk before we do this.  I don't know if the rest of the SDK can follow suit for back-compat, especially anyone using the ENUM_TO_STRING.

**Comment by jspaith** [comment]
[Fixed](https://github.com/Azure/azure-iot-sdk-c/pull/1560).  Per offline discussion, agreed it's OK(-ish) to have non-consistency across SDK.  We wanted to get PnP change in now no matter what happened with rest of SDK.
