### ISSUE TITLE
Remove model definition interface from default samples

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1201]
Would like to figure out a way to remove model definition from our default samples.  It adds extra overhead and especially on constrained devices we want to demonstrated smallest possible footprint.

The issue is our initial onboarding experience becomes a lot harder without it, since it requires developers to register these interfaces in repos before they can do basic device<=>Cloud experimentation.

**Comment by jasmineymlo** [comment]
Dup of #1199

**Comment by az-iot-builder-01** [comment]
@jspaith, @jasmineymlo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
