### ISSUE TITLE
MQTT : NO Ping Response from IOT hub

### ISSUE THREAD

**Issue by eramitsh** [Azure/azure-iot-sdk-c#1207]
Hi,
I connected using MQTT protocl with IOT hub and with keepAlive settings, 
the connection is build but its not able to keepit Alive because when MQTT makes the ping response it gets 
I (6585) azure_manager: Transport    : TLS/1
I (6585) azure_manager: Remote Port  : 8883
I (6595) azure_manager: Free memory  : 177296 bytes
I (8135) MQTT_CLIENT: Sending MQTT CONNECT message, type: 1, id: 0000
touch_test
I (8215) azure_manager: CONNECTED
filtered value of touch 5 is 2839
I (8295) azure_manager: SUBSCRIBED, msg_id=51222
I (8295) transport_manager: Listening to cloud
I (8305) smart_geyser: Listening to device NOW**===================**
I (8365) azure_manager: SUBSCRIBED, msg_id=16076
I (8365) transport_manager: Listening to cloud
I (8375) smart_geyser: Listening to device NOW**===================**

**E (192455) MQTT_CLIENT: No PING_RESP, disconnected
I (192455) azure_manager: DISCONNECTED**

So I know the bydefault value is approx 8 mins in AZURE iot client SDK , 
how my MQTT connection will recive the pings to know the connection state.

**Comment by anhashia** [comment]
I am assuming you are using third party MQTT client library

What is the **keep-alive** value you are using in MQTT CONNECT packet ?  IoT Hub will follow MQTT spec on this.

**For example**
If keep-alive value is 4 minutes, IoT Hub will wait **1.5x** times (6 minutes) before disconnecting the client  if there is 6 minutes period of inactivity. 

What is the **timeout**  in you are client library while sending  MQTT PING REQUEST (PINGREQ) ?  I am wondering if you are not waiting enough to process PINGRESP send by IoT Hub. 

Also, is client actually sending PINGREQ in first place ?
Do you see this issue once in a while or always ?

**Comment by eramitsh** [comment]
i will verify all the points  and post the obersvations.

till now my obervation are : - 
on keepalive of 120 sec i am getting the above logs that NO PING_RESP , so discconnect , i will verify the response wait time from IOT Hub.

and  observations made by changing keepalive in mqtt client  of Espressif azure library

1.	Keepalive > 10 sec
  observation: no ping response from broker and client disconnects.
2.	 Keepalive < 10 sec
  obervation: Client connection was alive. 
      also verified with public broker (HIVEmq), connection was alive irrespective of keepalive range.

**Comment by anhashia** [comment]
**Don't** see any issue.. Tired with 30 second keep-alive using IoT C SDK. There are no known issue around MQTT PING on IoT Hub service side.

```
// MQTT remote idle
int timevalue = 30;
IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_KEEP_ALIVE, &timevalue);
```

**LOG snippet**

-> 12:08:45 PINGREQ
<- 12:08:47 PINGRESP
-> 12:09:15 PINGREQ
<- 12:09:17 PINGRESP
-> 12:09:45 PINGREQ
<- 12:09:47 PINGRESP
-> 12:10:15 PINGREQ
<- 12:10:17 PINGRESP
-> 12:10:45 PINGREQ
<- 12:10:47 PINGRESP
-> 12:11:15 PINGREQ
<- 12:11:17 PINGRESP
-> 12:11:45 PINGREQ
<- 12:11:47 PINGRESP

**Comment by ewertons** [comment]
Hi @eramitsh ,
as verified if connecting to the IoT Hub directly the keepalives presented no issue.
It would be necessary to verify if your platform is not sending or receiving the keep alives, or if your broker has some influence on this issue.

We cannot debug this issue further without logs from the azure-iot-sdk-c suite.
If you are still facing problems, please [enable verbose logging](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L125) on the azure-iot-sdk-c client and reactivate this issue to share.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@eramitsh, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
