### ISSUE TITLE
Rename DigitalTwin's "interface instance" => component

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1208]
We're moving away from "interface instance" in DigitalTwin/PnP to "component".

So we need to make changes along lines of below (doing right with capitalization and spacing of course): 
"InterfaceInstance" => "Component"
"InterfaceInstanceName"=>"componentName"

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
