### ISSUE TITLE
Remove duplicate STRING_construct_sprintf call in dt_interface_client.c

### ISSUE THREAD

**Issue by jrdouceur** [Azure/azure-iot-sdk-c#1209]
dt_interface_client.c contains the following lines:

    if ((desiredPathForInterface = STRING_construct_sprintf("%s%s", DT_INTERFACE_PREFIX, dtInterfaceClient->componentName)) == NULL)
    {   
        LogError("Cannot build desiredPathForInterface string");
    }
    else if ((reportedPathForInterface = STRING_construct_sprintf("%s%s", DT_INTERFACE_PREFIX, dtInterfaceClient->componentName)) == NULL)
    {
        LogError("Cannot build reportedPathForInterface string");
    }

The call that constructs desiredPathForInterface is identical to the call that constructs reportedPathForInterface.  This should really just be a single call and a single variable, perhaps named pathForInterface.

No functional impact, but an unnecessary duplicate call, including memory allocation.

**Comment by az-iot-builder-01** [comment]
@jrdouceur, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
