### ISSUE TITLE
Clarify model definition that it can retrieve interfaces and DCM's

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1212]
The question in #1154 makes it clear that our naming of ` DigitalTwin_ModelDefinition_Publish_Interface` needs to be improved.

Model Definition can return not just interfaces, but also Device Capability Models.  The fact that it is called just "Interface" has understandably confused the first customer who came across it and likely will cause more confusion.

We need to think about a better name for this "InterfaceOrDeviceCapabilityModel" that is not quite so long:), but that captures its intent.

**Comment by jasmineymlo** [comment]
refer to #1199

**Comment by az-iot-builder-01** [comment]
@jspaith, @jasmineymlo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
