### ISSUE TITLE
Charging for Device Twin update when SAS token renewal

### ISSUE THREAD

**Issue by Patrik-Berglund** [Azure/azure-iot-sdk-c#1213]
Hi,

When the SAS token is renewed (roughly once every hour), the device disconnects and reconnects. After the connection is reestablished the Device Twin is sent out, is that included in the IoT Hub charging?

Best Regards
Patrik Berglund

**Comment by ewertons** [comment]
Hi @Patrik-Berglund ,
we are sharing your question with the organization and will reply as soon we have a clarification.

**Comment by ewertons** [comment]
Adding @gregman-msft to help with this question, since it is related to Azure IoT Hub rates.

**Comment by rezasherafat** [comment]
Assuming you are performing a new GetTwin operation after reconnecting, then the answer is yes.

**Comment by gregman-msft** [comment]
Thanks @rezasherafat. @Patrik-Berglund I am going to close this for now, but please reopen (or open a new issue) if you have any other questions on this topic.

**Comment by az-iot-builder-01** [comment]
@Patrik-Berglund, @ewertons, @rezasherafat, @gregman-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by Patrik-Berglund** [comment]
@rezasherafat We are not doing a GetTwin in our code, It's probably the SDK who does it behind the scene. Btw, we are using the C SDK together with the Serializer lib...

Upon receiving the twin we send back the reported props.

So using a short SAS token timeout, or having many customers with poor network connectivity will increase the Twin operations that we need to pay for... so to speak. Since a Iot Hub reconnection due to poor network will trigger a Twin update...

**Comment by gregman-msft** [comment]
Hi @Patrik-Berglund, it sounds like you've hit GitHub issue #1291. Can you up-vote/add your additional comments on impact for you in that issue to help us priortize this appropriately?
