### ISSUE TITLE
Send Fails(No Send confirmation) over Cellular Network 

### ISSUE THREAD

**Issue by sarangkalbande** [Azure/azure-iot-sdk-c#122]
OS Using Ubuntu 14.04
SDK Version 1.0.8

# Description of the issue:
I have been using MQTT C SDK for quite a while now,
I tried with wifi and ethernet networks It worked well all the time.
But Currently I am testing this SDK over cellular network(Verizon) having dynamic IP and I faced weird behavior as mentioned below.
when I try to send data over cellular Sendto function never gets confirmation  but my callback function gets invoked if I send something back to my device.I have verified internet is working on my device over cellular but Not sure about this weird behavior.

Sendto function again starts working after restarting my Application on device but for very first time 
It wont work at all till I restart it.

[2] Second issue.
when MQTT C Example is perfectly running over either wifi or ethernet and if I turn off one interface (ex wifi )and turn on other(ex.ethernet),My application stops sending data back to cloud till I restart 
the application again.

**Comment by ollyw** [comment]
Second issue may be related to https://github.com/Azure/azure-iot-sdk-c/issues/135

**Comment by tameraw** [comment]
Related to #135 which has been fixed.
