### ISSUE TITLE
IoTHubDeviceClient_CreateFromConnectionString doesn't check for invalid connection string

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-c#1220]
**Repro System**
Debian Stretch
SDK Release 2019-07-01

**Protocol**
MQTT

**Describe the Bug**
I was missing a character at the end of the connection string, but I didn't get any error when creating the DeviceClient handle. Errors came only later and were rather cryptic and not helpful for diagnosing the root cause.

To repro, just use the iothub_convenience_sample and supply a connection string that is missing its last character.

**Console Logs**

Sending message 1 to IoTHub
Message: {"temperature":27.794,"humidity":62.254,"scale":"Celcius"}
Error: Time:Fri Sep 27 00:36:47 2019 File:/home/wickste/azure-iot-sdk-c/c-utility/src/azure_base64.c Func:Azure_Base64_Decode Line:201 Invalid length Base64 string!
Error: Time:Fri Sep 27 00:36:47 2019 File:/home/wickste/azure-iot-sdk-c/c-utility/src/sastoken.c Func:construct_sas_token Line:217 Unable to decode the key for generating the SAS.
Error: Time:Fri Sep 27 00:36:47 2019 File:/home/wickste/azure-iot-sdk-c/iothub_client/src/iothub_client_authorization.c Func:IoTHubClient_Auth_Get_SasToken Line:460 Failed creating sas_token
Error: Time:Fri Sep 27 00:36:47 2019 File:/home/wickste/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2168 failure getting sas token from IoTHubClient_Auth_Get_SasToken.

**Comment by mamokarz** [comment]
Hi @wickste ,

I've just pushed the fix for this issue.

Thanks,
-Marcos

**Comment by az-iot-builder-01** [comment]
@wickste, @mamokarz, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
