### ISSUE TITLE
iothub_client_sample_mqtt_run(void) Stuck on Function call - IoTHubClient_LL_DoWork(iotHubClientHandle);

### ISSUE THREAD

**Issue by surajdagar** [Azure/azure-iot-sdk-c#1222]
Hi, 
I am using mbed-os 5.14, I am trying to port sample program(https://os.mbed.com/users/AzureIoTClient/code/iothub_client_sample_mqtt/) for mbed-os 5 on target nRF52840_DK.
I am using ESP8266 for the network interface. I did set the log options but I am not getting any internal Azure SDK logs 
            bool traceOn = true;
            IoTHubClient_LL_SetOption(iotHubClientHandle, OPTION_LOG_TRACE, &traceOn);

Below are my Terminal logs- 
**[EasyConnect] Using WIFI_ESP8266
[EasyConnect] Connected to Network successfully
[EasyConnect] MAC address 18:fe:34:dd:6e:91
[EasyConnect] IP address 192.168.43.107
[ Platform  ] ESP8266 ................
[ Platform  ] Time set to Mon Sep 30 17:53:35 2019

Platform init Success.
Trace Log init Success.
Setting message callback Success.
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.**

**Comment by danewalton** [comment]
Hi @surajdagar 
do you know if [this](https://github.com/Azure/azure-iot-arduino/issues/89) helps you at all? someone else was using an ESP8266 and that seemed to help them out.

**Comment by surajdagar** [comment]
Hi @danewalton I am not getting any TLS messages, I am using even different build platform, I am using mbed-os TLS libs.

**Comment by danewalton** [comment]
I see. It's hard to tell from these log messages what's going on. Are you able to step through the code at all and see if it's hanging somewhere or if it's hitting some ISR?

**Comment by surajdagar** [comment]
yes, It just stuck inside this function -IoTHubClient_LL_DoWork(iotHubClientHandle)

**Comment by danewalton** [comment]
Unfortunately a lot happens inside of that function (this could be failing in the sdk, tls, tcp, etc layers). In order to diagnose the problem it would help to get as specific as possible with the place where it is hanging. Like I mentioned before it could be a hard fault, an out of memory execption etc which are usually defaulted to `while(1)` loops. I'm going to need some more information to help so anything you can find out will help!

**Comment by az-iot-builder-01** [comment]
@danewalton, @surajdagar, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
