### ISSUE TITLE
Increase buffer size in socket communication layer

### ISSUE THREAD

**Issue by rezasherafat** [Azure/azure-iot-sdk-c#1223]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

All

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Current (9/30/2019)

**Protocol**

All

**Describe the Bug**

The C SDK's socket layer has a read buffer size of 64 which may become a bottle neck when sending large amounts of data.

**[MCVE](https://stackoverflow.com/help/mcve)**
n/a

**Console Logs**
n/a

**Comment by mamokarz** [comment]
Hi @rezasherafat ,

Can you provide more information about it? Each file/function can I find this buffer?

Thanks,
-Marcos

**Comment by rezasherafat** [comment]
@ewertons, can you help fill in the details?

**Comment by ewertons** [comment]
This is related to the hard-coded size of the read buffer used by our socketio interfaces, like here:
https://github.com/Azure/azure-c-shared-utility/blob/254dcaba38f45ea3610f4fa96d3174863a909503/adapters/socketio_win32.c#L54
and
https://github.com/Azure/azure-c-shared-utility/blob/254dcaba38f45ea3610f4fa96d3174863a909503/adapters/socketio_berkeley.c#L96

The value is defined here:
https://github.com/Azure/azure-c-shared-utility/blob/04a89186592628d216a9023e82be4c65320452e4/inc/azure_c_shared_utility/socketio.h#L34
```
#define RECEIVE_BYTES_VALUE     64
```

In reality anyone can change this value according to their needs and recompile the entire azure-iot-sdk-c, without having to introduce this extra dynamic allocation on the socket layers (i.e., not the most appropriate direction).

The steps to accomplish that would be:
1. git clone --recursive https://github.com/azure/azure-iot-sdk-c
2. Edit azure-iot-sdk-c\c-utility\inc\azure_c_shared_utility/socketio.h, change "#define RECEIVE_BYTES_VALUE     64" to the desired value;
3. Proceed with normal compilation of the C SDK (e.g., [on windows](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#build-the-c-sdk-with-cmake-on-windows)).

**Comment by ewertons** [comment]
Other than that, we will need to make the receive buffers dynamically allocated on the socketio layers, then expose an option from c-utility all the way up to the iothubdeviceclient to change it, and handle changes properly on the socketio (i.e., resize the buffer during DoWork, increasing the cost-per-loop-iteration and possibly affecting the throughput due to that).

**Comment by az-iot-builder-01** [comment]
@mamokarz, @rezasherafat, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
