### ISSUE TITLE
PnP SDK: Support for incrementally registering interfaces 

### ISSUE THREAD

**Issue by Shyamal-V** [Azure/azure-iot-sdk-c#1224]
We've been talking to PnP SDK folks about some pain points around DigitalTwin_DeviceClient_RegisterInterfacesAsync

**Is your feature request related to a problem? Please describe.**
We're building a bridge for gateways running Windows and Linux, to publish PnP interfaces for peripheral devices attached to it. The bridge is extensible through simple adapters that enable peripherals/protocols like Modbus, Camera, USB, MCUs etc. 

One significant complication in the design arises because DigitalTwin_DeviceClient_RegisterInterfacesAsync doesn’t allow incremental publishing of new interfaces on a digital twin client handle. Without this, each time a device is discovered, the bridge has to go through a complex teardown and re-registration process. Further, because each adapter cannot independently register its interfaces, the registration needs to be synchronized across all adapters, making “StartInterface” and “StopInterface” callbacks in the adapters necessary.

**Describe the solution you'd like**
If DigitalTwin_DeviceClient_RegisterInterfacesAsync can allow us to incrementally publish interfaces our design would be greatly simplified.

**Describe alternatives you've considered**
We've worked around this for now, but the solution is complex and adds abstractions we would like to avoid.

**Additional context**
@jspaith has more context on this and requested we track this here. Thanks to him for all the support so far.

**Comment by jasmineymlo** [comment]
This is obsolete as registering interfaces will be removed/refactored.  Tracking in #1198.

**Comment by az-iot-builder-01** [comment]
@Shyamal-V, @jasmineymlo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
