### ISSUE TITLE
unable to connect azure iot 

### ISSUE THREAD

**Issue by enerdata** [Azure/azure-iot-sdk-c#1225]
Hi there,

iam working on esp32 azure , unable to connect azure hub 
the following code shown below i don't know what exact the error is please give me the solution regarding this error

--- idf_monitor on /dev/ttyUSB0 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6492
load:0x40078000,len:12016
load:0x40080400,len:6632
entry 0x40080768
I (29) boot: ESP-IDF v4.0-dev-1443-g39f090a4f-dirty 2nd stage bootloader
I (29) boot: compile time 10:57:35
I (30) boot: Enabling RNG early entropy source...
I (35) boot: SPI Speed      : 40MHz
I (40) boot: SPI Mode       : DIO
I (44) boot: SPI Flash Size : 4MB
I (48) boot: Partition Table:
I (51) boot: ## Label            Usage          Type ST Offset   Length
I (58) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (66) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (73) boot:  2 factory          factory app      00 00 00010000 00100000
I (81) boot: End of partition table
I (85) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x248a8 (149672) map
I (147) esp_image: segment 1: paddr=0x000348d0 vaddr=0x3ffb0000 size=0x03378 ( 13176) load
I (153) esp_image: segment 2: paddr=0x00037c50 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at /home/saiteja_vdeal/esp/esp-idf/components/freertos/xtensa_vectors.S:1778

I (154) esp_image: segment 3: paddr=0x00038058 vaddr=0x40080400 size=0x07fb8 ( 32696) load
I (176) esp_image: segment 4: paddr=0x00040018 vaddr=0x400d0018 size=0x97f04 (622340) map
0x400d0018: _stext at ??:?

I (397) esp_image: segment 5: paddr=0x000d7f24 vaddr=0x400883b8 size=0x082e0 ( 33504) load
0x400883b8: ppResortTxAMPDU at ??:?

I (422) boot: Loaded app from partition at offset 0x10000
I (422) boot: Disabling RNG early entropy source...
I (422) cpu_start: Pro cpu up.
I (426) cpu_start: Application information:
I (431) cpu_start: Project name:     iothub_client_sample_mqtt
I (437) cpu_start: App version:      v1.0-6-g5f421bb-dirty
I (444) cpu_start: Compile time:     Oct  1 2019 10:57:40
I (450) cpu_start: ELF file SHA256:  6d03d022b65b339b...
I (456) cpu_start: ESP-IDF:          v4.0-dev-1443-g39f090a4f-dirty
I (463) cpu_start: Starting app cpu, entry point is 0x400812c8
0x400812c8: call_start_cpu1 at /home/saiteja_vdeal/esp/esp-idf/components/esp32/cpu_start.c:281

I (0) cpu_start: App cpu up.
I (473) heap_init: Initializing. RAM available for dynamic allocation:
I (480) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (486) heap_init: At 3FFB9BC8 len 00026438 (153 KiB): DRAM
I (492) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (498) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (505) heap_init: At 40090698 len 0000F968 (62 KiB): IRAM
I (511) cpu_start: Pro cpu start user code
I (529) spi_flash: detected chip: generic
I (530) spi_flash: flash io: dio
I (531) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (613) wifi: wifi driver task: 3ffc1650, prio:23, stack:3584, core=0
I (613) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (613) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (643) wifi: wifi firmware version: 27f2f06
I (643) wifi: config NVS flash: enabled
I (643) wifi: config nano formating: disabled
I (643) wifi: Init dynamic tx buffer num: 32
I (643) wifi: Init data frame dynamic rx buffer num: 32
I (653) wifi: Init management frame dynamic rx buffer num: 32
I (653) wifi: Init management short buffer num: 32
I (663) wifi: Init static rx buffer size: 1600
I (663) wifi: Init static rx buffer num: 10
I (673) wifi: Init dynamic rx buffer num: 32
I (673) azure: Setting WiFi configuration SSID TP-LINK_BD4E43...
I (783) phy: phy_version: 4102, 2fa7a43, Jul 15 2019, 13:06:06, 0, 0
I (783) wifi: mode : sta (3c:71:bf:f4:52:40)
I (1153) wifi: new:<3,0>, old:<1,0>, ap:<255,255>, sta:<3,0>, prof:1
I (1153) wifi: state: init -> auth (b0)
I (1153) wifi: state: auth -> assoc (0)
I (1163) wifi: state: assoc -> run (10)
I (1273) wifi: ampdu: ignore deleting tx BA0
I (2063) wifi: connected with TP-LINK_BD4E43, channel 3, BW20, bssid = 18:a6:f7:bd:4e:43
I (2063) wifi: pm start, type: 1

I (3103) tcpip_adapter: sta ip: 192.168.1.199, mask: 255.255.255.0, gw: 192.168.1.251
I (3103) azure: Connected to AP success!
Initializing SNTP
ESP platform sntp inited!
Time is not set yet. Connecting to WiFi and getting time over NTP. timeinfo.tm_year:70
Waiting for system time to be set... tm_year:0[times:1]
Waiting for system time to be set... tm_year:70[times:2]
Waiting for system time to be set... tm_year:70[times:3]
I (9123) platform: The current date/time is: Tue Oct  1 05:35:38 2019
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
E (9663) esp-tls: mbedtls_ssl_handshake returned -0x4c
I (9663) esp-tls: Certificate verified.
Error: Time:Tue Oct  1 05:36:09 2019 File:/home/saiteja_vdeal/esp/esp-idf/components/esp-azure/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2355 mqtt_client timed out waiting for CONNACK
Error: Time:Tue Oct  1 05:36:09 2019 File:/home/saiteja_vdeal/esp/esp-idf/components/esp-azure/port/src/tlsio_esp_tls.c Func:tlsio_esp_tls_destroy Line:152 tlsio_esp_tls_destroy called while not in TLSIO_STATE_CLOSED.
E (40483) esp-tls: mbedtls_ssl_handshake returned -0x4c
I (40483) esp-tls: Certificate verified.
Error: Time:Tue Oct  1 05:36:40 2019 File:/home/saiteja_vdeal/esp/esp-idf/components/esp-azure/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2355 mqtt_client timed out waiting for CONNACK
Error: Time:Tue Oct  1 05:36:40 2019 File:/home/saiteja_vdeal/esp/esp-idf/components/esp-azure/port/src/tlsio_esp_tls.c Func:tlsio_esp_tls_destroy Line:152 tlsio_esp_tls_destroy called while not in TLSIO_STATE_CLOSED.
E (71823) esp-tls: mbedtls_ssl_handshake returned -0x4c
I (71823) esp-tls: Certificate verified.
Error: Time:Tue Oct  1 05:37:11 2019 File:/home/saiteja_vdeal/esp/esp-idf/components/esp-azure/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2355 mqtt_client timed out waiting for CONNACK
Error: Time:Tue Oct  1 05:37:11 2019 File:/home/saiteja_vdeal/esp/esp-idf/components/esp-azure/port/src/tlsio_esp_tls.c Func:tlsio_esp_tls_destroy Line:152 tlsio_esp_tls_destroy called while not in TLSIO_STATE_CLOSED.
E (102563) esp-tls: mbedtls_ssl_handshake returned -0x4c

**Comment by danewalton** [comment]
Hi @enerdata 
Do you have retry enabled or disabled?

**Comment by enerdata** [comment]
Hi @danewalton 
can you please elaborate this where to enable or disable?
Thank you!!!

**Comment by danewalton** [comment]
It is on by default so I don't think that would be the problem. Are you able to use [wireshark](https://www.wireshark.org/) to see what is going on in the connection and post the logs?

**Comment by ewertons** [comment]
Hi @enerdata ,
based on [this documentation](https://tls.mbed.org/api/ssl_8h.html#a4a37e497cd08c896870a42b1b618186e) the error show tells there was some issue on the SSL negotiation anywhere, and is causing the client to disconnect (which is the correct action from the IoTHubDEvice Client, acc. to the documentation in the link above).

On this code you are running, did you get it from any of our samples? if yes, could you post the link to which one please?
Also, are you setting the trusted certificates on the code?

**Comment by ewertons** [comment]
We will close this issue since it has been stale for a while, but please feel free to reopen it if you would like to follow up.
Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment]
@danewalton, @enerdata, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
