### ISSUE TITLE
ECDSA Ciphersuites

### ISSUE THREAD

**Issue by alexnix** [Azure/azure-iot-sdk-c#1226]
I suspect Azure IoT Hub does not accept ECDSA cipher suites for device authentication using X.509 certificate issued by CA. Is that true?
I tried to initiate a connection with a Client Hello only proposing ECDSA ciphers and the server terminates immediately. If I propose RSA ciphers too, than the server will choose an RSA cipher.

PS: The tests are not done using the C SDK but C with some TLS and MQTT libraries.
PSS: There are examples on generating ECC key/certificate for a device and seam to work BUT at a closed inspection, in Wireshark, the server is still choosing an RSA cipher and probably the client is doing RSA with the ECC key (=>security issue! since RSA keys need to be much longer than ECC keys, to provide the same level of security)

**Comment by rezasherafat** [comment]
@alexnix, IoT Hub currently does not support ECC for server identity verification and ECDSA ciphers are not accepted. The TLS handshake goes through only when the client requests one of the supported ciphers, i.e., the RSA one, in your second try.

Also, if you don't mind sharing, do email me at rezas @ microsoft . com your use case of Elliptic curve ciphers so we take that as a feature request into account for the future.

**Comment by alexnix** [comment]
Thanks for your answer. I figured out what was going on. The server does not have an ECC certificate but the client is free to use whatever certificate. This is why the online examples worked while my code did not, because I tough the client has to use the same type of certificate as the server (I have an ECC device certificate).

It is all clear now. Thanks

**Comment by danewalton** [comment]
It seems like this issue has been resolved so I'm going to go ahead and close it. Feel free to open another issue if you have any other problems!

**Comment by az-iot-builder-01** [comment]
@rezasherafat, @alexnix, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
