### ISSUE TITLE
X509 device provisioning with group enrollment

### ISSUE THREAD

**Issue by krokoko** [Azure/azure-iot-sdk-c#1229]
Hey guys,

  I'm trying to provision a X509 device to IoT Hub DPS using the IoT C SDK and group enrollment. I used some information from [this doc](https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509). For the group enrollment, as i'm using the C SDK, I need to use a custom HSM (Java, C# and Python SDK provide APIs to add custom certificates). 

Workflow : 

1) I generated the cert chain (root, intermediate and device certificates) using as ```deviceId``` the id of the device that i want to see in the iot hub after registration. It was done using the script provided in the c sdk  (certGen.sh) with [these instructions](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md)
2) Upload and verfication of the root certificate to the DPS linked to the right IoT hub
3) I created in DPS the group enrollment with the following param : 
```
IoT edge device : false
Certificate type : CA certificate
Primary certificate : the root certificate uploaded just before
IoT hub : the correct one
```
4) On the device i want to provision, build the custom HSM by updating the following fields : 
```
static const char* const COMMON_NAME = "custom-hsm-example";
static const char* const CERTIFICATE = "-----BEGIN CERTIFICATE-----""\n"
"BASE64 Encoded certificate Here""\n"
"-----END CERTIFICATE-----";
static const char* const PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----""\n"
"BASE64 Encoded certificate Here""\n"
"-----END PRIVATE KEY-----";
```
where : 
- COMMON_NAME : ```deviceId``` used in step 1)
- CERTIFICATE : content of (./certs/new-device.cert.pem)
- PRIVATE_KEY : content of (./private/new-device.key.pem)
5) Update in ```prov_dev_client_sample``` the id scope using the value from "overview" in DPS
6) Rebuild the SDK and link with the custom HSM lib
7) Run the provisioning sample (custom hsm is correctly called following the custom logs added,see below)

Output : 
```
run the provisioning sample...
Provisioning API Version: 1.3.5
Not using proxy
custom_hsm_get_common_name
custom_hsm_get_certificate
custom_hsm_get_key

Registering Device

-> 10:26:25 CONNECT | VER: 4 | KEEPALIVE: 0 | FLAGS: 130 | USERNAME: SCOPE_ID/registrations/REGISTRATION_ID/api-version=2019-03-31&ClientVersion=1.3.5 | CLEAN: 1
<- 10:26:25 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Thu Oct  3 10:26:25 2019 File:/home/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_operation_complete_callback Line:208 Connection Not Accepted: 0x5: Not Authorized
Error: Time:Thu Oct  3 10:26:25 2019 File:/home/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Thu Oct  3 10:26:25 2019 File:/home/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:770 Failure retrieving data from the provisioning service

Failure registering device: PROV_DEVICE_RESULT_INVALID_STATE
Press enter key to exit:

```

Additional information : 
- For testing purpose, the device is an Ubuntu 16.04 VM using the latest version of the SDK.
- I did try to use the intermediate certificate instead of root on custom HSM side as suggested [here](https://github.com/Azure/azure-iot-sdk-csharp/issues/232#issuecomment-350841033) (is there support for validation using rootCA in DPS ? )
- IoT C SDK release [2019-07-01](https://github.com/Azure/azure-iot-sdk-c/releases/tag/2019-07-01) 

**Actual result** : device not provisioned
**Expected result** : device correctly provisioned and registered

Thank you !

**Comment by krokoko** [comment]
https://github.com/Azure/azure-iot-sdk-c/issues/1055 might be useful, seems this scenario is not working either and generating the same output

**Comment by danewalton** [comment]
Hi @krokoko
We have a bug in certGen.sh as brought up [here](https://github.com/Azure/azure-iot-sdk-c/issues/580). Is there any way you can run the powershell version of the cert generation for now to unblock yourself?

**Comment by krokoko** [comment]
Hi @danewalton , thank you for your quick reply. It seems indeed to be the same issue. I'll try it and let you know

**Comment by krokoko** [comment]
Hey

I was just reading the example with the C# SDK, and in the provisioning sample we have to provide the intermediate cert which signed the device certs (public and private keys) through the APIs (using [this](https://docs.microsoft.com/bs-latn-ba/azure/iot-dps/tutorial-group-enrollments#simulate-the-device))

By adding to the ```prov_dev_sample.c``` the content of the intermediate cert ( ./certs/azure-iot-test-only.intermediate.cert.pem) with :

Prov_Device_SetOption(prov_device_handle, OPTION_TRUSTED_CERT, CERTIFICATE);

And by changing in the group enrollment the ```Certificate type :``` property to use the intermediate cert instead of the root CA, it seems to provision correctly : 

```
run the provisioning sample...
Provisioning API Version: 1.3.5
Not using proxy
custom_hsm_get_common_name
custom_hsm_get_certificate
custom_hsm_get_key

Registering Device

-> 11:12:36 CONNECT | VER: 4 | KEEPALIVE: 0 | FLAGS: 130 | USERNAME: SCOPE_ID/registrations/REGISTRATION_ID/api-version=2019-03-31&ClientVersion=1.3.5 | CLEAN: 1
<- 11:12:36 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0
-> 11:12:36 SUBSCRIBE | PACKET_ID: 1 | TOPIC_NAME: $dps/registrations/res/# | QOS: 1
Provisioning Status: PROV_DEVICE_REG_STATUS_INVALID
<- 11:12:36 SUBACK | PACKET_ID: 1 | RETURN_CODE: 1
-> 11:12:36 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/PUT/iotdps-register/?$rid=1 | PAYLOAD_LEN: 29
<- 11:12:36 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/res/202/?$rid=1&retry-after=3 | PACKET_ID: 2 | PAYLOAD_LEN: 94
Provisioning Status: PROV_DEVICE_REG_STATUS_REGISTERING
-> 11:12:36 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/GET/iotdps-get-operationstatus/?$rid=2&operationId=4.5fdbf7a9b6727138.b3830166-57e6-4db0-bece-4277323451fc | PAYLOAD_LEN: 29
<- 11:12:36 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/res/202/?$rid=2&retry-after=3 | PACKET_ID: 2 | PAYLOAD_LEN: 165
Provisioning Status: PROV_DEVICE_REG_STATUS_REGISTERING
-> 11:12:39 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/GET/iotdps-get-operationstatus/?$rid=3&operationId=4.5fdbf7a9b6727138.b3830166-57e6-4db0-bece-4277323451fc | PAYLOAD_LEN: 29
<- 11:12:39 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/res/200/?$rid=3 | PACKET_ID: 2 | PAYLOAD_LEN: 475

Registration Information received from service: MY_HUB.azure-devices.net, deviceId: REGISTRATION_ID
-> 11:12:39 DISCONNECT
Press enter key to exit: 
```

What do you think ?

**Comment by danewalton** [comment]
Yea I've been looking into this since yesterday and noticed that the powershell script signs the device cert with root while the bash signs with the intermediate. I believe the intention of these scripts should be to keep things as simple as possible for users since certs themselves can be complicated. I'm getting together a fix which signs the device cert as the powershell script does which is with the root. That way you can upload the root, generate the device cert, and therefore only have one cert to compile in your code.

Great find though on the use of the intermediate! Feel free to use either scenario for testing purposes. Just know that as we label everywhere in and around the cert gen scripts, this is not to be used for production.

**Comment by krokoko** [comment]
Ok cool ! Yes absolutely it's for testing purpose only, i'm just trying to build a more complex scenario. 

For now i was trying this "direct" provisioning, while my end goal is to provision a downstream device behind an edge device in transparent mode. I'm just working step by step. 

I'll let you close this ticket when you merge your fix I guess, the workaround with the usage of the intermediate cert is acceptable for me in the meantime.  

Thank you for the support @danewalton !

**Comment by danewalton** [comment]
PR has been opened
https://github.com/Azure/azure-iot-sdk-c/pull/1230

**Comment by danewalton** [comment]
PR merged to master

**Comment by az-iot-builder-01** [comment]
@krokoko, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
