### ISSUE TITLE
Intel NUC and the Azure IoT Gateway

### ISSUE THREAD

**Issue by remcoploeg** [Azure/azure-iot-sdk-c#123]
- **OS and version used:** Intel NUC / Wind River 7.0.0.13 

- **SDK version used:** latest build 

# Description of the issue:
I have bought the Seed Studio Azure IoT Gateway device. (with Intel NUC) If I run the BLE sample from  the azure doc [website ](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-gateway-kit-c-iot-gateway-connect-device-to-cloud)on my Intel NUC.  I receive the following error, after the Senortag sends his temperature:

`
> [2017:04:29T12:02:38] Temperature: (17.000000, 23.593750)
> [2017:04:29T12:02:39] Temperature: (17.093750, 23.593750)
> Error: Time:Sat Apr 29 12:02:40 2017 File:/iotdk2/scott/Projects/iot-cloud/build-intel-baytrail-64-wrlinux-7-0013/bitbake_build/tmp/work/corei7-64-wrs-linux/azure-iot-sdk/1.1.10-r0/git/c/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:mark_current_device_key_as_invalid Line:216 Primary key of device 'DemoIntel' was marked as invalid. No other device keys available
> 
`
I known for sure that key is allright (I have tested the exact keys with other programs and that worked). Now I say this case: 

https://github.com/Azure/azure-iot-sdk-c/issues/106

I have a SSL cert:
`
root@WR-IDP-4A2F:/usr/share/azureiotgatewaysdk/samples/ble_gateway# ls -al /etc/ssl/certs/ | grep -i baltimore
lrwxrwxrwx 1 root root     64 May 12  2016 Baltimore_CyberTrust_Root.pem -> /usr/share/ca-certificates/mozilla/Baltimore_CyberTrust_Root.crt
`

but I receive this error when I try to connect to the Azure IoT Hub with OPENSSL:

`root@WR-IDP-4A2F:/usr/share/azureiotgatewaysdk/samples/ble_gateway#` openssl s_client -connect iotworkshopwinvision.azure-devices.net:5671
CONNECTED(00000003)
depth=1 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, OU = Microsoft IT, CN = Microsoft IT SSL SHA2
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/CN=*.azure-devices.net
   i:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
 1 s:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGcjCCBFqgAwIBAgITWgABtrNbz7vBeV0QWwABAAG2szANBgkqhkiG9w0BAQsF
ADCBizELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEVMBMGA1UE
CxMMTWljcm9zb2Z0IElUMR4wHAYDVQQDExVNaWNyb3NvZnQgSVQgU1NMIFNIQTIw
HhcNMTUwODI3MDMxODA0WhcNMTcwODI2MDMxODA0WjAeMRwwGgYDVQQDDBMqLmF6
dXJlLWRldmljZXMubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
nXC/qBUdlnfIm5K3HYu0o/Mb5tNNcsr0xy4Do0Puwq2W1tz0ZHvIIS9VOANhkNCb
VyOncnP6dvmM/rYYKth/NQ8RUiZOYlROZ0SYC8cvxq9WOln4GXtEU8vNVqJbYrJj
rPMHfxqLzTE/0ZnQffnDT3iMUE9kFLHow0YgaSRU0KZsc9KAROmzBzu+QIB1WGKX
D7CN361tG1UuN68Bz7MSnbgk98Z+DjDxfusoDhiiy/Y9MLOJMt4WIy5BqL3lfLnn
r+JLqmpiFuyVUDacFQDprYJ1/AFgcsKYu/ydmASARPzqJhOGaC2sZP0U5oBOoBzI
bz4tfn8Bi0kJKmS53mQt+wIDAQABo4ICOTCCAjUwCwYDVR0PBAQDAgSwMB0GA1Ud
JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQUKpYehBSNA53Oxivn
aLCz3+eFUJ0wXQYDVR0RBFYwVIITKi5henVyZS1kZXZpY2VzLm5ldIIaKi5hbXFw
d3MuYXp1cmUtZGV2aWNlcy5uZXSCISouc3UubWFuYWdlbWVudC1henVyZS1kZXZp
Y2VzLm5ldDAfBgNVHSMEGDAWgBRRryQmnPRoIleAJis7RmIVex7MpTB9BgNVHR8E
djB0MHKgcKBuhjZodHRwOi8vbXNjcmwubWljcm9zb2Z0LmNvbS9wa2kvbXNjb3Jw
L2NybC9tc2l0d3d3Mi5jcmyGNGh0dHA6Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kv
bXNjb3JwL2NybC9tc2l0d3d3Mi5jcmwwcAYIKwYBBQUHAQEEZDBiMDwGCCsGAQUF
BzAChjBodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL21zY29ycC9tc2l0d3d3
Mi5jcnQwIgYIKwYBBQUHMAGGFmh0dHA6Ly9vY3NwLm1zb2NzcC5jb20wTgYDVR0g
BEcwRTBDBgkrBgEEAYI3KgEwNjA0BggrBgEFBQcCARYoaHR0cDovL3d3dy5taWNy
b3NvZnQuY29tL3BraS9tc2NvcnAvY3BzADAnBgkrBgEEAYI3FQoEGjAYMAoGCCsG
AQUFBwMBMAoGCCsGAQUFBwMCMA0GCSqGSIb3DQEBCwUAA4ICAQCrjzOSW+X6v+UC
u+JkYyuypXN14pPLcGFbknJWj6DAyFWXKC8ihIYdtf/szWIO7VooplSTZ05u/JYu
ZYh7fAw27qih9CLhhfncXi5yzjgLMlD0mlbORvMJR/nMl7Yh1ki9GyLnpOqMmO+E
yTpOiE07Uyt2uWelLHjMY8kwy2bSRXIp7/+A8qHRaIIdXNtAKIK5jo068BJpo77h
4PljCb9JFdEt6sAKKuaP86Y+8oRZ7YzU4TLDCiK8P8n/gQXH0vvhOE/O0n7gWPqB
n8KxsnRicop6tB6GZy32Stn8w0qktmQNXOGU+hp8OL6irULWZw/781po6d78nmwk
1IFl2TB4+jgyblvJdTM0rx8vPf3F2O2kgsRNs9M5qCI7m+he43Bhue0Fj/h3oIIo
Qx7X/uqc8j3VTNE9hf2A4wksSRgRydjAYoo+bduNagC5s7Eucb4mBG0MMk7HAQU9
m/gyaxqth6ygDLK58wojSV0i4RiU01qZkHzqIWv5FhhMjbFwyKEc6U35Ps7kP/1O
fdGm13ONaYqDl44RyFsLFFiiDYxZFDSsKM0WDxbl9ULAlVc3WR85kEBK6I+pSQj+
7/Z5z2zTz9qOFWgB15SegTbjSR7uk9mEVnj9KDlGtG8W1or0EGrrEDP2CMsp0oEj
VTJbZAxEaZ3cVCKva5sQUxFMjwG32g==
-----END CERTIFICATE-----
subject=/CN=*.azure-devices.net
issuer=/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
---
No client certificate CA names sent
---
SSL handshake has read 3248 bytes and written 477 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
    Session-ID: CA240000E872FB77B8484D194926A781F742BC118DDB9B108240462B6D5F1EC0
    Session-ID-ctx:
    Master-Key: E7CE9B003941EAD6E4796C9ECA6C170AA39525C5F39CE1CD27541313A462E60BB31FCB65587E0077E9E86AF375DCF786
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1493468551
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---
`

So I looks like that I have an issue with my CERT. Can somebody help me?

**Comment by tameraw** [comment]
@remcoploeg 
- In regards to the Invalid key issue. Please make sure that the clock on your device is not skewed by any chance.
- In regards to the cert issue, please attempt to use the SetOption with the "TrustedCerts" as shown in our [sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp.c) and see if this resolves your issue. If it does, then you possibly do not have the right cert in your cert store, or for some reason the SSL lib could not locate the cert store.

**Comment by remcoploeg** [comment]
@tameraw Thanks; the clock is corect. I will give it a try tonight. But if I connect with openssl I see that the cert is not valided. how can I import the right certificate?

**Comment by remcoploeg** [comment]
How can I rebuild this? Because I am using an Intel NUC with packages from Intel (out of the box solution...)

**Comment by tameraw** [comment]
@remcoploeg - If you have the code for the SDK as part of that Intel NUC package, you should be able to use the SetOption with the "TrustedCerts" as shown in this [sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp.c).
If not, try to refresh the certs on your box running this command if possible:
apt-get install ca-certificates
Let us know if that helps.

**Comment by czyba** [comment]
@remcoploeg, there may be some other issue if you use a Linux distribution with OpenSSL though. I had an embedded device which had the symlink you have but did not have the "hashed" symlinks. This may be a wild shot though, since most linux distributions provide these links on install of some ca-certificates package. Which would usually be fixed by @tameraw's suggestion of reinstalling ca-certificates. It should look somewhat like this:

```
czyba@X1:~> ll /etc/ssl/certs/ | grep Baltimore
lrwxrwxrwx 1 root root     29 Apr 18 21:20 653b494a.0 -> Baltimore_CyberTrust_Root.pem
lrwxrwxrwx 1 root root     72 Apr 13 17:24 Baltimore_CyberTrust_Root.pem -> ../../../usr/share/ca-certificates/mozilla/Baltimore_CyberTrust_Root.crt
```

I recall that debian provides 2 hashed symlinks instead of the single one I showed here, although if I'm correct this is the only one you need. From your grep command I would assume that these are missing. You can find a perl script in the debian package for installing the respective symlinks.

This may be a long shot, but I hope it helps.

Kind Regards
Christopher Czyba

**Comment by tameraw** [comment]
@remcoploeg - Feel free to reopen if still having issues.
