### ISSUE TITLE
Invoke module / device should accept any 2** status code as success

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1231]
In a quick glance at code I noticed this in `sendHttpRequestMethod` in file `iothub_client_edge.c`.

Basically we get an HTTP status code back from Edge and need to translate that back to an IoT result.

```c
            if (statusCode == 200)
            {
                result = IOTHUB_CLIENT_OK;
            }
            else
            {
                LogError("Http Failure status code %d.", statusCode);
                result = IOTHUB_CLIENT_ERROR;
            }
```

What happens if the Edge returns a 202 though?  This should still be a success case for any 200* range.

**Comment by ewertons** [comment]
To make is more explicit, this is the line this issue refers to:
https://github.com/Azure/azure-iot-sdk-c/blob/2019-10-07/iothub_client/src/iothub_client_edge.c#L443

**Comment by ewertons** [comment]
Fixed.
