### ISSUE TITLE
Minimum memory or hardware requirement

### ISSUE THREAD

**Issue by manishmicrosoft** [Azure/azure-iot-sdk-c#124]
Team,

Rather than issue, this is more a question. Do we have any minimum memory/hardware requirements for this device SDK to work?

One of our customer has a device of following configuration. Is it sufficient to run this SDK?

Processor: ARM Cortex 32 bit
RAM: 64 KB
Flash: 512 KB

**Comment by tameraw** [comment]
@manishmicrosoft - This should be sufficient for running the C - SDK as indicated in the [Readme](https://github.com/Azure/azure-iot-sdk-c#os-platforms-and-hardware-compatibility).
However, you have to take into account the application using the SDK and how much resources it consumes.
