### ISSUE TITLE
"TrustedCerts" is not publicly well explained

### ISSUE THREAD

**Issue by ericmitt** [Azure/azure-iot-sdk-c#1242]
"TrustedCerts" is not publicly documented.
https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-device-client-ll-h/iothubdeviceclient-ll-setoption

The issue #1112 has been closed, with just a line in the header file.
https://github.com/Azure/azure-iot-sdk-c/pull/1124/files
 
This line is not enough to explains what this option is doing and when to use it. Please update the documentation with more details.

**Comment by ewertons** [comment]
Hi @ericmitt ,

thanks for bringing that to our attention.
The documentation page you referenced is not maintained by this repo, so I filed an issue on them on your behalf.
Please track through:
https://github.com/MicrosoftDocs/Azure-IoT-C-SDK-Reference/issues/29 

If you would like to leave feedback like this on that documentation, please use the "Feedback" button on the top right.

In regards of what that option means to the Azure IoT Hub device client, we do have a reference here:
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Iothub_sdk_options.md#iothub_client

We will close this issue, but please feel free to reopen it if you would like to follow up.

Thanks for contributing to the Azure IoT SDKs.
