### ISSUE TITLE
With no network, connecting via MQTT lags significantly with current head, works in 2019-07-01

### ISSUE THREAD

**Issue by FreddieChopin** [Azure/azure-iot-sdk-c#1243]
I have a very simple test code, which is basically a mix of `iothub_ll_telemetry_sample` with `prov_dev_client_ll_sample` (I can post it, but it is really simple, however pretty long). I'm trying to run it on a STM32F7 microcontroller with a RTOS, the device has Ethernet connection to the network. The most important fact is that there is no network for about 10 seconds after the device is powered-up, becasue the TCP/IP stack is still talking to the DHCP server.

When I use snapshot from 2019-07-01 then everything works fine. First few attempts to connect fail (as there is no network), but then everything connects quickly once the network is fully up.
Direct connection - https://gist.github.com/FreddieChopin/da8789bb9d9015555b99556df652762a
DPS connection - https://gist.github.com/FreddieChopin/a9585f255431ced9636df07c8d28006d

With current head (well, 805405039e8fc2b61943c8431e1d3d1a08b6ce61 from 2019-10-05 01:28:12, but there is nothing interesing after that) the very same code with no changes behaves differently. There's a 30 second timeout when using direct connection (at 2019-10-09 11:47:39)
https://gist.github.com/FreddieChopin/b756c3b38c5ded955c937ca6472799b7
When using DPS there's an extremely long lag of 5 minutes (at 2019-10-09 11:54:30)
https://gist.github.com/FreddieChopin/8f89daf06819d1f238eb9234f885e699

Neither of these is present with the snapshot from July.

I suspect this may be related to the changes in umqtt code introduced around August, but it's hard to bisect, as I have to sync all the other submodules to proper revisions too (you cannot use HEAD of azure-iot-sdk-c and head of c-utility with an older version of umqtt, because they are not compatible).

Possibly this can be simulated on a PC by disconnecting it from the network, then running some sample program and then - after it starts connecting - enabling network. However I did not check it.

Let me know if you need some more details.

**Comment by gregman-msft** [comment]
@hihigupt can you investigate and find out if this is related to the other issue we just assigned to you?

**Comment by ewertons** [comment]
Hi @FreddieChopin , we apologize for the delay. We have been reassigned for new code development and that affected our response time.

Is this still a valid issue for you, or you found a workaround?

**Comment by FreddieChopin** [comment]
I haven't checked whether this is still an issue in current HEAD, as I need to use a forked (based on the working tag mentioned above) and slightly modified version of Azure's SDK. Updating my fork and re-applying all the required changes is something I cannot do right now.

**Comment by ewertons** [comment]
@FreddieChopin ,
thanks for your reply. Unfortunately we have not been able to prioritizing working on this issue, since many fixes and improvements have been done to the MQTT transport since this issue was opened. 
We have no indications of any slowdown of MQTT transport traffic on the latest versions of the code.
If you have a chance of refreshing your fork and still experience the same issue, please feel free to file a new issue and we will follow up.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@FreddieChopin, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
