### ISSUE TITLE
How to implement x509 authentication in iOS?

### ISSUE THREAD

**Issue by alain-noa** [Azure/azure-iot-sdk-c#1247]
I am trying connect Azure IOT Hub from **iOS** devices by using MQTT protocol with **x509** certificate and private key. 
I am using [Azure iOS sample project](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/ios) with iOS SDK from cocoaPods. I modified the [iothub_sample.m](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/ios/AzureIoTSample/AzureIoTSample/iothub_sample.m)  with [x509 sample c code](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_client_x509_sample/iothub_ll_client_x509_sample.c) for x509 testing. And it failed with error "**Unsupported x509**".

From [issue 1115](https://github.com/Azure/azure-iot-sdk-c/issues/1115) and [issue 942](https://github.com/Azure/azure-iot-sdk-c/issues/942), it tells that x509 authentication is currently not support in iOS SDK but it is in backlog and it can be workaround by building the C SDK using OpenSSL.

Now i succeed to build the C SDK using OpenSSL and it looks correct with c executable file on my mac:
`Creating IoTHub handle
Sending message 1 to IoTHub
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
Confirmation callback received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 2 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 3 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 4 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 5 with result IOTHUB_CLIENT_CONFIRMATION_OK
`

I want to know **how to use those C SDK in iOS** and **when will x509 be available in iOS SDK(cocoaPods)?**
(I found several .a libraries and header file in the C SDK project but i am not sure how to correctly import them into my iOS project).

**Comment by alain-noa** [comment]
Hi @rafilho @YoDaMa , could you help?

**Comment by gregman-msft** [comment]
Hi @alain-noa, 

Please refer to our documentation for getting started with development on iOS: https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-ios
If this is missing the information you are looking for, please let us know so that we can update the documentation.

Also, thanks for the feedback on x509 support. This is currently in our backlog but do not have an ETA for this yet. Please vote on this [User voice item](https://feedback.azure.com/forums/321918-azure-iot/suggestions/38826169-support-for-x509-authentication-on-ios), which can also be used for tracking our plans. I just added it, so it may not appear immediately, so please check back later in the day if the link doesn't work yet.

Thanks!

**Comment by alain-noa** [comment]
Hi @gregman-msft thanks for explanation! We will vote it on Azure feedback forums.

x509 authentication is very important for us and we are currently blocked by iOS platform. We will keep trying to workaround it before it is officially supported in iOS, any advice or guidance would be greatly appreciated!

**Comment by alain-noa** [comment]
Still cannot vote the item for "This idea is awaiting moderator approval".

**Comment by alain-noa** [comment]
Succeed to integrate the c sdk in my iOS project and works with x509 authentication through openssl. Below are the steps what i did, hope it helps other poor iOS guys like me. I don't know cmake so it must looks stupid that i build the sdk, please don't hesitate to help to improve, thx :)


### 1. Import OpenSSL library and cURL library to iOS project

You can easily find their source code on github but it's not friendly to generate libraries for iOS. After a million times try, finally i found workable [pod library](https://github.com/krzyzanowskim/OpenSSL) for OpenSSL and [framework](https://github.com/Cogosense/iOSCurlFramework/releases) for cURL, just add the pod for OpenSSL and import the framework for cURL in the iOS project.

> It's still recommended to build the c sdk from source code if it is comfortable for you.


### 2. Build C SDK for iOS

1. Clone C SDK
- `git clone git@github.com:Azure/azure-iot-sdk-c.git`.

2. Generate an XCode Project, set to use openssl
-    cd C SDK root directory
-   `mkdir cmake`
-   `cd cmake`
-   `cmake -G Xcode -DOPENSSL_ROOT_DIR:PATH=/usr/local/opt/openssl -Duse_openssl:bool=ON ..`

3. Config build settings
-   Open `azure_iot_sdks.xcodeproj` in cmake folder
-   Edit **Build Settings** for all library targets (`aziotsharedutil`, `iothub_client` ...)
    -  Change **Base SDK** from `macos` to `ios`
    -  Add architectures whatever you need
-   Edit **Search Paths** for target `aziotsharedutil` to link `OpenSSL` library and `cURL` library
    -  If you use static library, there are `include` and `lib` folders on the library, add `include` to **Header Search Paths** and `lib` to **Library Search Paths**
    -  If you use framework, just add the path to **Framework Search Paths**

4. Build C SDK
-   If all the configuration are correct, you should be able to build all the libraries with iOS device or iOS simulator in `azure_iot_sdks.xcodeproj`

### 3. Import C SDK to iOS project
- After step 2, you will get all C SDK libraries you need in /cmake folder in your C SDK project. However,  the headers and static libraries are scattered in different paths, you have to link them to your iOS project.
- You can refer to C SDK sample project to check all the header search path, for example, open `azure_iot_sdks.xcodeproj`, go to **Build Settings** > **Search Paths** of any target for sample (like iothub_II_Client_x509_sample), you can see the search path for each library.

  
You can refer to  https://github.com/Azure/azure-iot-sdk-c/issues/1260 if you there is a problem.

**Comment by alain-noa** [comment]
Add a missing detail:

![Screen Shot 2019-10-31 at 1 39 01 PM](https://user-images.githubusercontent.com/56292091/67922056-8c82ac00-fbe4-11e9-9ff2-c381c9f70aa6.png)

Add `-lz` to **Other Linker Flags** in your project build settings, this will against the built-in zlib.

Which resolve below compile error:

> Undefined symbols for architecture x86_64:
  "_inflate", referenced from:
      _inflate_stream in curl(libcurl_la-content_encoding.o)
  "_zlibVersion", referenced from:
      _gzip_init_writer in curl(libcurl_la-content_encoding.o)
      _curl_version in curl(libcurl_la-version.o)
      _curl_version_info in curl(libcurl_la-version.o)
  "_inflateEnd", referenced from:
      _inflate_stream in curl(libcurl_la-content_encoding.o)
      _exit_zlib in curl(libcurl_la-content_encoding.o)
  "_inflateInit2_", referenced from:
      _inflate_stream in curl(libcurl_la-content_encoding.o)
      _gzip_init_writer in curl(libcurl_la-content_encoding.o)
  "_inflateInit_", referenced from:
      _deflate_init_writer in curl(libcurl_la-content_encoding.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by alain-noa** [comment]
I create a [template](https://github.com/alain-noa/AzureIotTemplate) project for reference.

**Comment by ewertons** [comment]
Thank you very much, @alain-noa !

**Comment by az-iot-builder-01** [comment]
@alain-noa, @gregman-msft, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by cbauer10** [comment]
@ewertons Any update on this situation as it has been 2.5 years now and we need support for x509 certs in iOS?  Several team members have tried the steps outlined by @ghost and the project no longer compiles due to errors with the C code and not linkage issues with OpenSSL or cURL.  Please let me know if there is something we can try to resolve this issue.
