### ISSUE TITLE
PnP Environmental sensor does not follow HTTP status code conventions

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1248]
Our environmental sensor PnP sample interface today has an async command as part of its DTDL.

The way the code works:
* Returns a 202 on the initial acceptance of the request.
* A second later sends another 202 back indicating request is in progress.
* A second later sends a 200 to show the request is done.

The subsequent send of the 202 is not correct per my reading of HTTP status codes and some discussions.  We need instead to return a 102 to show processing on step2 above.

See https://httpstatuses.com/202 and https://httpstatuses.com/102.

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
