### ISSUE TITLE
Cannot build DPS with vcpkg's

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1251]
It is not possible to specify DPS when using vcpkg in the C SDK.  The issue is that when `use_prov_client` cmake flag is specified, then ALL HSM's are also set.

```cmake
if (${use_prov_client})
    set(use_prov_client_core ON)

    if ("${hsm_custom_lib}" STREQUAL "")
        set(hsm_type_x509 ON)
        set(hsm_type_sastoken ON)
        set(hsm_type_symm_key ON)
    else()
        set(hsm_type_custom ON)
    endif()
endif()
```
This works OK when a git clone of repo is used, because all these HSM* just reference code that's already brought in via git submodules.

When using vcpkg, we do not have vcpkg's for all the hsm's.  And we're not planning on doing so, as OEMs for productization will likely just use their own anyway.  Using `hsm_type_symm_key` cmake option will aways just work, though, as the logic to this does not require an extra submodule.  And for many scenarios around vcpkg, we think that is sufficient.

So the fix here is to make is so that if any HSM_* is set, do NOT automatically turn others on as we trust user is opting into on.  If no HSM* is set, then we leave default behavior so as not to break stuff.

See attached PATCH file for what this would look like:
[cmake-hsm-option.patch.txt](https://github.com/Azure/azure-iot-sdk-c/files/3713877/cmake-hsm-option.patch.txt)

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
