### ISSUE TITLE
Missing statement in switch()

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1254]
In the file `prov_transport_amqp_common.c`, we have the function `on_message_receiver_state_changed_callback`

```c
    switch (amqp_info->msg_recv_state)
    {
    case MESSAGE_RECEIVER_STATE_IDLE:
    case MESSAGE_RECEIVER_STATE_OPENING:
    case MESSAGE_RECEIVER_STATE_CLOSING:
        break;
    case MESSAGE_RECEIVER_STATE_OPEN:
        if (amqp_info->msg_send_state == MESSAGE_SENDER_STATE_OPEN)
        // removing for clarity...
        break;
    case MESSAGE_RECEIVER_STATE_ERROR:
        // removing for clarity...
        break;
    }
```

Note that there's no `default` here.  That was fine before as we covered all the cases, but some macro utils change I believe introduced an implicit `MESSAGE_SENDER_STATE_INVALID` type.  

Because this is not handled in the case statement and there is no default, clang on at least some configuration setting complained.

**Comment by ewertons** [comment]
Fixed.

**Comment by az-iot-builder-01** [comment]
@jspaith, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
