### ISSUE TITLE
C SDK not support in iOS (Catalina)

### ISSUE THREAD

**Issue by alain-noa** [Azure/azure-iot-sdk-c#1260]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

macOS Catalina version 10.15
Xcode version 11.1

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2019-10-07

**Protocol**

MQTT

**Describe the Bug**

I am working on x509 authentication in iOS, due to [this issue](https://github.com/Azure/azure-iot-sdk-c/issues/1247), i have to use C SDK iInstead of directly integrate via cocoapods.

I follow [this guide](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#macos) to build the C SDK on macOS. In the iOS sample project i import the libraries and add header search path.

![Screen Shot 2019-10-15 at 11 02 23 AM](https://user-images.githubusercontent.com/56292091/66796786-4f0ef500-ef3b-11e9-9339-8be890854e1a.png)

Project build failed with SDK errors.

**Xcode Error Logs**

"building for iOS Simulator, but linking in object file ... built for macOS"

**Comment by alain-noa** [comment]
I rebuild C SDK with iOS Simulator, and the error "building for iOS Simulator, but linking in object file ... built for macOS" no more exist.

But a new compile error happen:

![Screen Shot 2019-10-15 at 6 26 49 PM](https://user-images.githubusercontent.com/56292091/66823721-6371e280-ef79-11e9-8cd8-e5aeebd15724.png)

The error looks caused by **libaziotsharedutil.a** , possibly related to my operation that modify the SDK architecture from macOS to iOS.

**Comment by ewertons** [comment]
Hi @alain-noa ,

sorry for not having a more recent release of the azure-iot-SDK-c through cocoapods. We are working on getting that packaging system live again for our solution, but with no defined ETA yet.

Let's see if we can assist with the issue you are experiencing:

All these undefined symbols are related to OpenSSL library.

1. Is openssl installed in your system?
2. Are you linking your solution to the openssl library?

**Comment by alain-noa** [comment]
Hi @ewertons , thank you very much for the reply!
I am not sure about for your questions, but i will try import openssl library to iOS project and see if it works.

**Comment by alain-noa** [comment]
Imported [OpenSSL](https://github.com/krzyzanowskim/OpenSSL) via cocoapods, still not working.

![Screen Shot 2019-10-16 at 6 47 32 PM](https://user-images.githubusercontent.com/56292091/66912671-9a152f00-f045-11e9-9870-1238e5a9a4ee.png)

**Comment by alain-noa** [comment]
Build succeeded after integrated OpenSSL library and cURL library to the project!!!

Run iOS project (reference from [x509 sample code](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_client_x509_sample/iothub_ll_client_x509_sample.c) and config with x509 cer) and got error:

![Screen Shot 2019-10-17 at 6 19 29 PM](https://user-images.githubusercontent.com/56292091/67001023-79171180-f10b-11e9-8b9b-55317d207c24.png)

**Comment by alain-noa** [comment]
Updated cURL library still not works.

I tried [iothub_II_telemetry_sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c) and it also failed:
in send_confirm_callback, received result **IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED** and reason **IOTHUB_CLIENT_CONNECTION_NO_NETWORK**

I am not sure if it caused by the C SDK.

**Comment by ewertons** [comment]
Hi @alain-noa ,
I'm glad you passed the compilation error.

The failures you posted above are related to server certificate validation.

Could you confirm if you are calling the function to set the trusted certs on the IoT Hub device client?
If you are using the LL layer, it should be similar to [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L131).

Make sure you add the define in your project to enable setting trusted certs (see SET_TRUSTED_CERT_IN_SAMPLES in the sample)

**Comment by alain-noa** [comment]
Hi @ewertons,  i used x509 certificate generated by ourself, it works properly with the cmake executable file on the mac, so i think the cer should be correct.

Here is the main function:

    IOTHUB_DEVICE_CLIENT_LL_HANDLE device_ll_handle;

    // Used to initialize IoTHub SDK subsystem
    (void)IoTHub_Init();

    (void)printf("Creating IoTHub handle\r\n");

    device_ll_handle = IoTHubDeviceClient_LL_CreateFromConnectionString(connectionString, protocol);
    if (device_ll_handle == NULL)
    {
        (void)printf("Failure createing Iothub device.  Hint: Check you connection string.\r\n");
    }
    else
    {
        bool traceOn = true;
        IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_LOG_TRACE, &traceOn);

        if (
            (IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_X509_CERT, x509certificate) != IOTHUB_CLIENT_OK) ||
            (IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_X509_PRIVATE_KEY, x509privatekey) != IOTHUB_CLIENT_OK)
            )
        {
            printf("failure to set options for x509, aborting\r\n");
        }
        else
        {
            do
            {
                if (messages_sent < MESSAGE_COUNT)
                {
                    message_handle = IoTHubMessage_CreateFromString(telemetry_msg);

                    (void)IoTHubMessage_SetMessageId(message_handle, "MSG_ID");
                    (void)IoTHubMessage_SetCorrelationId(message_handle, "CORE_ID");
                    (void)IoTHubMessage_SetContentTypeSystemProperty(message_handle, "application%2Fjson");
                    (void)IoTHubMessage_SetContentEncodingSystemProperty(message_handle, "utf-8");

                    (void)IoTHubMessage_SetProperty(message_handle, "property_key", "property_value");

                    (void)printf("Sending message %d to IoTHub\r\n", (int)(messages_sent + 1));
                    IoTHubDeviceClient_LL_SendEventAsync(device_ll_handle, message_handle, send_confirm_callback, NULL);

                    IoTHubMessage_Destroy(message_handle);

                    messages_sent++;
                }
                else if (g_message_count_send_confirmations >= MESSAGE_COUNT)
                {
                    g_continueRunning = false;
                }

                IoTHubDeviceClient_LL_DoWork(device_ll_handle);
                ThreadAPI_Sleep(1);

            } while (g_continueRunning);
        }
        IoTHubDeviceClient_LL_Destroy(device_ll_handle);
    }
    IoTHub_Deinit();

    printf("Press any key to continue");
    (void)getchar();

I tried enable setting trusted certs and  calling the function to set the trusted certs on the IoT Hub device client, also got errors:

> -> 09:56:56 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: onebagtag-luggagetags-west-us.azure-devices.net/pl2-luggagetag99-d1e36411-d01a-4e07-94f7-a2dd8fe445c0/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.6%20(native%3b%20Darwin%3b%20iPhone11%2c8) | CLEAN: 0
<- 09:56:56 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Thu Oct 24 09:56:56 2019 File:/Users/noa-labs/Desktop/azure-iot-sdk-c 2/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1755 Connection Not Accepted: 0x5: Not Authorized

**Comment by alain-noa** [comment]
**It works now!** Verified with iPhone 7 (12.1.2) and iPhoneXR(13.1.3) and iOS simulator(13.1).

Without new changes and it just works... I guess there may be some problem of the network.

**Comment by az-iot-builder-01** [comment]
@alain-noa, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
