### ISSUE TITLE
PnP telemetry e2e tests should include validation of the received message at the EventHub  

### ISSUE THREAD

**Issue by jasmineymlo** [Azure/azure-iot-sdk-c#1263]
Current PnP E2E telemetry tests only validate on acknowledgements.  Telemetry should be checked at the receiving end (EventHub endpoint) for completeness.

**Comment by az-iot-builder-01** [comment]
@jasmineymlo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
