### ISSUE TITLE
PnP e2e tests suite should take dependency on node service client official released npm package

### ISSUE THREAD

**Issue by jasmineymlo** [Azure/azure-iot-sdk-c#1264]
The service application code in the PnP e2e test suite is written in TypeScript using the Digital Twin service SDK.  We should move to taking dependency on the official released npm package of the Node digital twin service client SDK, instead of a copy of the node sdk in our repo.

**Comment by az-iot-builder-01** [comment]
@jasmineymlo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
