### ISSUE TITLE
PropertiesUpdatedCallback should be renamed to PropertiesNotificationCallback

### ISSUE THREAD

**Issue by jasmineymlo** [Azure/azure-iot-sdk-c#1268]
"PropertiesUpdatedCallback" causes confusion as it is being triggered for 2 scenario:
1) During device initialization on get Twin call 
2) writable property updates from the service side

For 1), the callback could be triggered without any "real" updates on the properties' values.  Rename it to "notification" to minimize confusion.

**Comment by jasmineymlo** [comment]
duplicate of #1271

**Comment by az-iot-builder-01** [comment]
@jasmineymlo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
