### ISSUE TITLE
Components should be notify for stand-alone reported properties on initialization

### ISSUE THREAD

**Issue by jasmineymlo** [Azure/azure-iot-sdk-c#1269]
During device initialization where get Twin is called for syncing with the service's side of the stored properties values, SDK provides the current value of the Desired AND the Reported (if the Reported exists) property to the user callback function.  Stand-alone reported properties values (in the full twin) should be provided to the components as well using the same callback function.

**Comment by jasmineymlo** [comment]
duplicate of #1270

**Comment by az-iot-builder-01** [comment]
@jasmineymlo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
