### ISSUE TITLE
C SDK Low Level Documentation is needed 

### ISSUE THREAD

**Issue by sarangkalbande** [Azure/azure-iot-sdk-c#127]
# Description of the issue:
I don't see any documentation for Low Level APIs and its working.We should have low level API Design
Documentation for newbies to understand how these SDK is working internally.

Like few questions I had encountered for which I did not get answer unless I see the code at low level.
[1] What happens if current network drops?
[2] Internal Message Queue Size
[3] When I switch between networks like Ethernet to wifi and vice versa ,Was the previous handle created
is still valid or we need to recreate it again?

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by tameraw** [comment]
@sarangkalbande - This is currently on our list of documentation updates. We'll update this post once released.

**Comment by jebrando** [comment]
The documentation has be extensively change and it should be complete.  If you see any information that you would like to see please open a new issue

**Comment by az-iot-builder-01** [comment]
@sarangkalbande, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by yzhong94** [comment]
In addition, the API documentation for ll can be found here: https://azure.github.io/azure-iot-sdk-c/iothub__client__ll_8h.html
