### ISSUE TITLE
PnP should provide reported properties to app always

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1270]
Currently for C SDK, when we get a full twin we report properties to application *only* if there are desired properties in the list.  If there is a reported property but not a desired property, we just swallow it.

This isn't right.  We should always provide reported properties.  This will help bandwidth conscious interfaces to be thoughtful about whether they report back a given reported property again or whether they realize the server has what they were going to send up anyway and save the round-trip.

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
