### ISSUE TITLE
Rename PnP property "update" concept

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1271]
We've got feedback that calling pnp property notification callbacks as "updates" is confusing.  The issue is that on initial connection, the PnP SDK will report back all properties that came from the twin regardless of whether they were updated or not.  (The PNP SDK cannot cache all this, after all.)

But... calling this an "update" makes it sound like something has changed.  

We think a better name is "PropertyNotification".  So stuff that would have to change would be like `DIGITALTWIN_CLIENT_PROPERTY_UPDATE` and places we use words like "updated property" and `DIGITALTWIN_PROPERTY_UPDATE_CALLBACK` and ...

**Comment by jasmineymlo** [comment]
close as it is part of #1200 effort.

**Comment by az-iot-builder-01** [comment]
@jspaith, @jasmineymlo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
