### ISSUE TITLE
Please remove this behavior will change once DPS support is added.

### ISSUE THREAD

**Issue by MugunthanMugundanMSFT** [Azure/azure-iot-sdk-c#1273]
There is a comment in the samples saying this behavior will change once the DPS support is added. Please doublecheck this.
// The call to DigitalTwin_DeviceClient_CreateFromDeviceHandle() transfers ownership
    // of this handle (including destroying it) to the DigitalTwin layer, analogous to a .release()
    // in some C++ helpers.  DO NOT USE deviceHandle after this point.  Note this behavior
    // will change once DPS integration becomes available later.

**Comment by jspaith** [comment]
We just need to remove the "Note this behavior
// will change once DPS integration becomes available later." comments.

We're not planning on IoTHub client / DPS integration at present.

**Comment by az-iot-builder-01** [comment]
@MugunthanMugundanMSFT, @jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
