### ISSUE TITLE
Segmentation Fault when Network is Down

### ISSUE THREAD

**Issue by FrankSHLi** [Azure/azure-iot-sdk-c#1275]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Debian 9

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2019-10-07

**Protocol**

MQTT

**Describe the Bug**

The sample code iothub_ll_telemetry_sample.c segmentation fault if the network is down.

```

**Console Logs**

Creating IoTHub Device handle
Sending message 1 to IoTHub
Info: Failed DNS lookup for XXX.azure-devices.net: -2
Segmentation fault

**Comment by Patrik-Berglund** [comment]
Hi, 

What we have seen so far is that there are a couple of bugs introduced in the 2019-10-07 release for mbedtls, mqtt and berkley sockets combination. Haven't had time to file all issues them yet due to other development tasks, so we are sticking with the 2019-07-01 release.

Here's one of them though, 
https://github.com/Azure/azure-iot-sdk-c/issues/1202

Have you tested the 2019-07-01 release, for us that is working as expected.

**Comment by FrankSHLi** [comment]
Hi @Patrik-Berglund ,

I've already rolled back to 2019-07-01 release as soon as I found the reconnect issue, to make sure our applications won't crash.

However, OPTION_RETRY_INTERVAL_SEC isn't yet introduced in 2019-07-01, so I'd still like to know if there's any progress, thanks.

**Comment by aog2000a** [comment]
Same problem here, running 1.3.5 using MQTT on Linux/Arm i hit this segfault when the network goes down.

**Comment by rajaggrawal** [comment]
c-utility/adapters/socketio_berkeley.c
static int initiate_socket_connection(SOCKET_IO_INSTANCE* socket_io_instance)
{
if(!dns_resolver_is_lookup_complete(socket_io_instance->dns_resolver))
        {
            LogError("DNS did not resolve IP address");
            result = MU_FAILURE;
        }
        else
        {
            addr = dns_resolver_get_addrInfo(socket_io_instance->dns_resolver);
            **connect_addr = addr->ai_addr;**
            connect_addr_len = sizeof(*addr->ai_addr);
            result = 0;
        }
}
addr is NULL when Network is down and DNS doesnt resolve.
crash due to below line of code.
connect_addr = addr->ai_addr

**Comment by Patrik-Berglund** [comment]
Hi, there's a pull req for this in the azure-c-shared-utility. it's not submitted by me (or our company), https://github.com/Azure/azure-c-shared-utility/pull/400

**Comment by ewertons** [comment]
Thanks @Patrik-Berglund , we used that PR as part of the fix.
The [new PR](https://github.com/Azure/azure-c-shared-utility/pull/415) is out with the complete fix, and will be merged and integrated into azure-iot-sdk-c repo soon.

**Comment by rajaggrawal** [comment]
when i know when this would be integrated . Any Approximate date ?.
this is a critical/blocker for us.

**Comment by ewertons** [comment]
Hi @rajaggrawal , the fixed version of azure-c-shared-utility will be integrated to this repo today, 11/22/2019. Packages will be available at a later date.

**Comment by rajaggrawal** [comment]
@ewertons let me know if I can pull the changes if its available.

**Comment by ewertons** [comment]
@rajaggrawal , apologies for the delay. There was an additional change to complete the fix and we are working on it right now. We will update you briefly of the status.

**Comment by ewertons** [comment]
Hi @rajaggrawal , the fix is in master now. 
Could you please verify on your end that you no longer see the crash?

**Comment by ewertons** [comment]
We will close this issue as a fix has been checked in.
Please feel free to reopen it if you need to follow up.
Thanks for contributing to the Azure IoT SDKs.

**Comment by az-iot-builder-01** [comment]
@Patrik-Berglund, @aog2000a, @rajaggrawal, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
