### ISSUE TITLE
iot edge module sample code - memory leak

### ISSUE THREAD

**Issue by Anil-Poolayulla-Chelottillam** [Azure/azure-iot-sdk-c#1276]
I am referring to the following iot edge module C sample code :

https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_module_filter/iothub_client_sample_module_filter.c

In function InputQueue1FilterCallback(), the message instance variabl "filteredMessageInstance" memory is cleared only in IoTHubModuleClient_LL_SendEventToOutputAsync() failed case. (Line #154)

Why it is not cleared in IoTHubModuleClient_LL_SendEventToOutputAsync() success case?

It can cause memory leak isn't it?

**Comment by ewertons** [comment]
Hi @Anil-Poolayulla-Chelottillam ,

if you search for "free(filteredMessageInstance)" you will find it gets invoked also in SendConfirmationCallbackFromFilter, which is the callback invoked by IoTHubModuleClient_LL_SendEventToOutputAsync when it is done sending the event.

In this case, there wouldn't be a memory leak.

Also, just as an important note, our samples are not intended to be used directly as production code. They do not handle all the possible failure cases, they contain only examples of how to invoke the azure-iot-SDK-c API function.
It is up to the discretion of the developers to implement the proper controls for error checking and cleanup.

Thanks for your question.
If you would like to follow up, please feel free to reopen this issue.
Azure IoT SDKs Team

**Comment by az-iot-builder-01** [comment]
@Anil-Poolayulla-Chelottillam, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
