### ISSUE TITLE
iothub_convenience_sample example "INT_RSA_VERIFY:wrong signature length“ error

### ISSUE THREAD

**Issue by ghaucience** [Azure/azure-iot-sdk-c#1278]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

MT7688
OpenWrt-SDK-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2

**SDK Version (Please Give Commit SHA if Manually Compiling)**

the newest

**Protocol**

MQTT

**Describe the Bug**

when run the example on my board, it reports "INT_RSA_VERIFY:wrong signature length"

**Console Logs**

This sample will send messages continuously and accept C2D messages.
Press Ctrl+C to terminate the sample.

Creating IoTHub handle

Sending message 1 to IoTHub
Message: {"temperature":27.231,"humidity":77.956,"scale":"Celcius"}
Error: Time:Wed Oct 23 07:01:42 2019 File:/home/luyong/au/azure/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:673 error:04091077:rsa routines:INT_RSA_VERIFY:wrong signature length
Error: Time:Wed Oct 23 07:01:42 2019 File:/home/luyong/au/azure/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
The device client has been disconnected
Error: Time:Wed Oct 23 07:01:43 2019 File:/home/luyong/au/azure/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:673 error:04091077:rsa routines:INT_RSA_VERIFY:wrong signature length
Error: Time:Wed Oct 23 07:01:43 2019 File:/home/luyong/au/azure/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
The device client has been disconnected
Error: Time:Wed Oct 23 07:01:43 2019 File:/home/luyong/au/azure/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:673 error:04091077:rsa routines:INT_RSA_VERIFY:wrong signature length
Error: Time:Wed Oct 23 07:01:43 2019 File:/home/luyong/au/azure/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
The device client has been disconnected

**Comment by ghaucience** [comment]
#define SAMPLE_MQTT
#define SET_TRUSTED_CERT_IN_SAMPLES,

**Comment by ghaucience** [comment]
#define SAMPLE_MQTT
#define SET_TRUSTED_CERT_IN_SAMPLES
I have define this two switch, use the /certs/certs.c

**Comment by ewertons** [comment]
Hi @ghaucience ,
looks like you figured out you had to enable SET_TRUSTED_CERT_IN_SAMPLES.
We will close this issue, but please feel free to reopen it if you would like to follow up.
Thanks,
Azure IoT SDKs Team

**Comment by az-iot-builder-01** [comment]
@ghaucience, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
