### ISSUE TITLE
Segfault after calling singlylinked_list_remove()

### ISSUE THREAD

**Issue by MoMeneam** [Azure/azure-iot-sdk-c#1279]
Stm32f765ii, FreeRTOS 
Cross Compiled on Windows10  using ARM v5

SDK Version 1.3.6

Protocol

MQTT

* Bug Description*
When trying to remove an item is already removed  by singlylinkedlist_remove(list,item) the list parameter holds  protected memory location which causes a hard fault

```
static void on_underlying_io_send_complete(void* context, IO_SEND_RESULT send_result)
{
    if (context == NULL)
    {
        /* Codes_SRS_UWS_CLIENT_01_435: [ When on_underlying_io_send_complete is called with a NULL context, it shall do nothing. ]*/
        LogError("on_underlying_io_send_complete called with NULL context");
    }
    else
    {
        LIST_ITEM_HANDLE ws_pending_send_list_item = (LIST_ITEM_HANDLE)context;
        WS_PENDING_SEND* ws_pending_send = (WS_PENDING_SEND*)singlylinkedlist_item_get_value(ws_pending_send_list_item);
        if (ws_pending_send != NULL)
        {
            UWS_CLIENT_HANDLE uws_client = ws_pending_send->uws_client;
            WS_SEND_FRAME_RESULT ws_send_frame_result;

            switch (send_result)
            {
                /* Codes_SRS_UWS_CLIENT_01_436: [ When on_underlying_io_send_complete is called with any other error code, the send shall be indicated to the uws user by calling on_ws_send_frame_complete with WS_SEND_FRAME_ERROR. ]*/
            default:
            case IO_SEND_ERROR:

                ws_send_frame_result = WS_SEND_FRAME_ERROR;
                break;

            case IO_SEND_OK:
               
                ws_send_frame_result = WS_SEND_FRAME_OK;
                break;

            case IO_SEND_CANCELLED:
               
                ws_send_frame_result = WS_SEND_FRAME_CANCELLED;
                break;
            }
						
						
/*when hashing the if condition the segfault doesn't happen * */
            if (complete_send_frame(ws_pending_send, ws_pending_send_list_item, ws_send_frame_result) != 0)
            {

                indicate_ws_error(uws_client, WS_ERROR_CANNOT_REMOVE_SENT_ITEM_FROM_LIST);
            } 
        }
        else
        {
            LogError("Failing getting singlylinkedlist_item_get_value on_underlying_io_send_complete");
        }
    }
}
static int complete_send_frame(WS_PENDING_SEND* ws_pending_send, LIST_ITEM_HANDLE pending_send_frame_item, WS_SEND_FRAME_RESULT ws_send_frame_result)
{
    int result;
    UWS_CLIENT_INSTANCE* uws_client = ws_pending_send->uws_client;

    /* Codes_SRS_UWS_CLIENT_01_432: [ The indicated sent frame shall be removed from the list by calling singlylinkedlist_remove. ]*/
//it crashes after calling singlylinkedlist_remove and passing reserved address of list  
    if (singlylinkedlist_remove(uws_client->pending_sends, pending_send_frame_item) != 0)
    {
        LogError("Failed removing item from list");
        result = MU_FAILURE;
    }
    else
    {
        if (ws_pending_send->on_ws_send_frame_complete != NULL)
        {
            /* Codes_SRS_UWS_CLIENT_01_037: [ When indicating pending send frames as cancelled the callback context passed to the on_ws_send_frame_complete callback shall be the context given to uws_client_send_frame_async. ]*/
            ws_pending_send->on_ws_send_frame_complete(ws_pending_send->context, ws_send_frame_result);
        }

        /* Codes_SRS_UWS_CLIENT_01_434: [ The memory associated with the sent frame shall be freed. ]*/
        free(ws_pending_send);

        result = 0;
    }

    return result;
}
//azure-iot-sdk-c\c-utility\src/uws_client.c
```

**Console Logs**
TRY SEND IOT Message
-MbedTLS Handshake Start...                                                      
MbedTLS HANDSHAKE Done

**Comment by MoMeneam** [comment]
Hi @ewertons ,

Yes i'm using the LL functions in iothub_device_client_ll.h.

**Comment by ewertons** [comment]
Have you verified that you are locking properly to not call any of the API functions in parallel?
Like, _DoWork should not be called ever while or after _Destroy is called.

**Comment by MoMeneam** [comment]
If you mean IoTHubClient_LL_Destroy ,No because of handshaking that takes long time so i do it once at the beginning and the connection isn't closed.

My flow is :
1. create iotHubClientHandle using "IoTHubClient_LL_CreateFromConnectionString" api  
2. set some options (e.g. TrustedCerts, OPTION_HTTP_PROXY........ ) using "IoTHubClient_LL_SetOption"
3. set massage calback  usnig "IoTHubClient_LL_SetMessageCallback" api
4."IoTHubMessage_CreateFromByteArray"
5. "IoTHubClient_LL_SendEventAsync"
6. "IoTHubClient_LL_DoWork".

Currently we don't destroy the iotHubClientHandle after sending/receiving data, but we keep using same the iotHubClientHandle at all times unless the internet connection was disconnectcd then we will create new handle.

We did that "not destroy the handle" to save new connection initialization time "handshake time which  takes very long time".

May be not calling _Destroy causes some errors or demands some flow handling that missed?

**Comment by ewertons** [comment]
If you keep using the same iothubclient_ll handle, there is no issue at all.
You only need to call IoTHubClient_LL_Destroy when you no longer need the handle. If you do not call it before terminating your application, you will run into a memory leak.

This will require some deeper analysis either by running your code in platform that gives you some tools to track memory issues (e.g., Linux, valgrind) or get an in-house repro and debug in a traditional way. We will verify what we need to do to get the repro done.

**Comment by MoMeneam** [comment]
If there are any updates, please let me know?
waiting you.

**Comment by jasmineymlo** [comment]
@MoMeneam would you check that if uws_client->pending_sends is a valid memory address and is the same as when the the struct was initialized??  Thanks.

**Comment by MoMeneam** [comment]
hi @jasmineymlo the address of uws_client->pending_sends sometimes takes an address  that is already freed and the other case is uws_client->pending_sends  takes a protected memory location which cause a crash.

**Comment by jasmineymlo** [comment]
@MoMeneam Would you try to repro on Linux as suggested by ewertons earlier?  Thanks.

**Comment by MoMeneam** [comment]
@jasmineflorencio  Unfortunately, running on Linux requires building up from scratch which isn't applicable now  so, can you suggest other ideas for debugging.

**Comment by jbobotek** [comment]
Hi @MoMeneam , do you have a J-Link or onboard debugging tool on your board?

**Comment by MoMeneam** [comment]
Hi @jbobotek  J-link.

**Comment by jbobotek** [comment]
So assuming you are using Arm Development Studio, you should be able to put breakpoints in the code while you have a J-Link connected: https://developer.arm.com/tools-and-software/embedded/arm-development-studio/components/arm-debugger

**Comment by MoMeneam** [comment]
@jbobotek I'm using keil uvision and sure, I can put breakpoints.
can you please clarify what you want to see in a debug session to provide you back.

**Comment by jbobotek** [comment]
We kind of want to see where the memory corruption happens. If you can trace it back, we might be able to point to either an issue in sequence or an error in the sdk.

**Comment by ewertons** [comment]
Hi @MoMeneam ,

Were you able to collect the data requested by @jbobotek ?

We will close this issue for now, but please feel free to reopen it if you would like to follow up.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@MoMeneam, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
