### ISSUE TITLE
mqtt not working for tirtos cc3200 

### ISSUE THREAD

**Issue by kcpoduru** [Azure/azure-iot-sdk-c#128]
azure-iot-sdk/c mqtt example

- **OS and version used:** <VERSION> 
windows 10

- **SDK version used:** <VERSION> 

azure-iot-sdk-c verison 1.0.12

# Description of the issue:
I am trying to work with simplesample_mqtt example with cc3200(tirtos). The example does'nt support tirtos. So I copied  tirtos files from simplesample_http example and made necessary changes for compiling with simplesample_mqtt example. The program compiled so perfectly but while linking I found the following problem(in the attached image). I thought there is some mistake with transporthubmqtt file but in the first place the initial build did not create transporthubmqtt.o file in iothubclient build section.

# Console log of the issue:
![capture](https://cloud.githubusercontent.com/assets/25354759/25676331/49555c58-3007-11e7-83ea-a3056a62dd0e.PNG)

**Comment by v-gogur** [comment]
Thanks for reporting this issue, @kcpoduru 

We need more information to figure out. If you made any changes (simplesample_http), please share with us, would help.

**Comment by kcpoduru** [comment]
1. I copied entire tirtos folder from simplesample_http example and paste in simplesample_mqtt.
2. in main.c Instead of # include <simplesample_http.h> I have included # <simplesample_mqtt.h> , And instead of simplesample_http_run i have changed it to simplesample_mqtt_run.
3. And in make file  i have changed all related http to mqtt 

_**all: simplesample_mqtt.bin

simplesample_mqtt.out: main.o simplesample_mqtt.o rom_pin_mux_config.o netwifi.o UARTUtils.o CC3200_LAUNCHXL.o network_common.o CC3200_LAUNCHXL.cmd $(CONFIG)/linker.cmd $(LIBS)
	@echo building $@ ..
	@$(LD) -o $@ $^ -x -m $@.map $(LFLAGS)

simplesample_mqtt.bin: simplesample_mqtt.out
	@$(binconv) $^ $@**_

**Comment by markrad** [comment]
MQTT is currently not supported on the CC3200 when using the Azure IoT SDK. Some customers have had success using the Paho library. Research is on going to see if support can be added.

**Comment by MaHaXWS** [comment]
Hi
We are trying to develope a device (cc3200) with azure sdk and MQTT. (OS: RIOT-OS
What is the problem with MQTT on CC3200? Why is it not supported or what is not supported.

Is there an alternative to MQTT_Protocol!

Thanks for your help.

**Comment by markrad** [comment]
CC3200 is currently not a certified device.

**Comment by MaHaXWS** [comment]
According to https://catalog.azureiotsuite.com/details?title=TI_CC3200&source=null cc3200 should be a certified device.

**Comment by markrad** [comment]
Sorry my bad. The CC3200 is not certified for _MQTT_. HTTP only. The reason is that the adapter was written before the Azure IoT Hub supported MQTT. An adaptation layer for the CC32**2**0 might be available later this year.
