### ISSUE TITLE
undefined reference error on cmake bui

### ISSUE THREAD

**Issue by cjdomingo** [Azure/azure-iot-sdk-c#1280]
I am trying to cross compile the pnp sample_device with Mips32 architecture. I am having a lot of 'undefined reference error' when I build using cmake.

Here is a some of the errors:

CMakeFiles/sample_device.dir/nano_test.c.o: In function `main':
nano_test.c:(.text+0xd7c): multiple definition of `main'
CMakeFiles/sample_device.dir/main.c.o:main.c:(.text+0x0): first defined here
CMakeFiles/sample_device.dir/main.c.o: In function `main':
main.c:(.text+0x28): undefined reference to `xlogging_get_log_function'
main.c:(.text+0xc0): undefined reference to `xlogging_get_log_function'
main.c:(.text+0x130): undefined reference to `ThreadAPI_Sleep'
CMakeFiles/sample_device.dir/nano_test.c.o: In function `interrupt_guard':
nano_test.c:(.text+0xbec): undefined reference to `gpiod_chip_open_lookup'
nano_test.c:(.text+0xc30): undefined reference to `gpiod_chip_get_line'
nano_test.c:(.text+0xc70): undefined reference to `gpiod_line_request_falling_edge_events'
nano_test.c:(.text+0xca0): undefined reference to `gpiod_line_event_wait'
nano_test.c:(.text+0xcb4): undefined reference to `gpiod_line_event_read'
nano_test.c:(.text+0xce8): undefined reference to `gpiod_line_release'
CMakeFiles/sample_device.dir/pnp_device.c.o: In function `pnp_device_initialize':
pnp_device.c:(.text+0x18): undefined reference to `tickcounter_create'
pnp_device.c:(.text+0x40): undefined reference to `xlogging_get_log_function'
pnp_device.c:(.text+0xe8): undefined reference to `xlogging_get_log_function'
pnp_device.c:(.text+0x178): undefined reference to `xlogging_get_log_function'
pnp_device.c:(.text+0x210): undefined reference to `xlogging_get_log_function'
pnp_device.c:(.text+0x2a4): undefined reference to `xlogging_get_log_function'
pnp_device.c:(.text+0x334): undefined reference to `tickcounter_get_current_ms'
CMakeFiles/sample_device.dir/pnp_device.c.o: In function `pnp_device_run':
pnp_device.c:(.text+0x37c): undefined reference to `tickcounter_get_current_ms'
pnp_device.c:(.text+0x3a4): undefined reference to `xlogging_get_log_function'
pnp_device.c:(.text+0x418): undefined reference to `tickcounter_get_current_ms'
CMakeFiles/sample_device.dir/remote_monitoring.c.o: In function `serializeToJson':
remote_monitoring.c:(.text+0x16c): undefined reference to `json_value_init_object'
remote_monitoring.c:(.text+0x17c): undefined reference to `json_value_get_object'
remote_monitoring.c:(.text+0x1a8): undefined reference to `json_object_set_string'
remote_monitoring.c:(.text+0x1d0): undefined reference to `json_object_set_string'
remote_monitoring.c:(.text+0x1f8): undefined reference to `json_object_set_string'
remote_monitoring.c:(.text+0x220): undefined reference to `json_object_set_string'
remote_monitoring.c:(.text+0x254): undefined reference to `json_object_set_string'
CMakeFiles/sample_device.dir/remote_monitoring.c.o:remote_monitoring.c:(.text+0x27c): more undefined references to `json_object_set_string' follow
CMakeFiles/sample_device.dir/remote_monitoring.c.o: In function `serializeToJson':
remote_monitoring.c:(.text+0x2a8): undefined reference to `json_object_set_number'
remote_monitoring.c:(.text+0x2d4): undefined reference to `json_object_set_number'
remote_monitoring.c:(.text+0x2fc): undefined reference to `json_object_dotset_string'
remote_monitoring.c:(.text+0x324): undefined reference to `json_object_dotset_string'
remote_monitoring.c:(.text+0x34c): undefined reference to `json_object_dotset_string'
remote_monitoring.c:(.text+0x358): undefined reference to `json_serialize_to_string'
remote_monitoring.c:(.text+0x368): undefined reference to `json_value_free'
……

What could be the cause of this problem?

**Comment by ewertons** [comment]
Hi @cjdomingo ,
we will not comment on files that are not part of the Azure IoT SDK Suite, but the undefined references you see related to xlogging, tickcounter are because you are not linking your project to [azure-c-shared-utility](https://github.com/Azure/azure-c-shared-utility), and the ones related to json_ are because you are not linking to [parson](https://github.com/kgabis/parson/tree/master).

**Comment by ewertons** [comment]
We will close this issue for now, but please feel free to reopen it if you would like to follow up on the subject.
Thanks for using the Azure IoT SDKs!

**Comment by az-iot-builder-01** [comment]
@cjdomingo, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
