### ISSUE TITLE
Unable to Connect to Device Provisioning Service using X509 Certificates 

### ISSUE THREAD

**Issue by Pavan2358** [Azure/azure-iot-sdk-c#1281]
Development Machine: Linux 18.04, OpenSSL Version: OpenSSL 1.1.1  11 Sep 2018
SDK Version: 23-09-2019(SDK Version 1.3.5)
Protocol : HTTP/MQTT

Issue:
Steps: 
1) Run Provisioning client example with public and private key certificates used from custom_hsm_sample the file(Attached custom_hsm_sample.c and prov_dev_client_ll_sample.c present in Issue.zip file)
Provisioning API Version: 1.3.5
Iothub API Version: 1.3.5
**Error: Time:Thu Oct 24 16:56:39 2019 File:/home/pavan/Azure_Clone_Latest/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:29 Failure creating private key evp_key
Error: Time:Thu Oct 24 16:56:39 2019 File:/home/pavan/Azure_Clone_Latest/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36   [0] error:0909006C:PEM routines:get_name:no start line**
Error: Time:Thu Oct 24 16:56:39 2019 File:/home/pavan/Azure_Clone_Latest/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:log_ERR_get_error Line:428 unable to use x509 authentication
Error: Time:Thu Oct 24 16:56:39 2019 File:/home/pavan/Azure_Clone_Latest/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1251 Failed creating the OpenSSL instance.
Error: Time:Thu Oct 24 16:56:39 2019 File:/home/pavan/Azure_Clone_Latest/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1042 Error: io_open failed
Error: Time:Thu Oct 24 16:56:39 2019 File:/home/pavan/Azure_Clone_Latest/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:create_connection Line:644 Failure connecting to mqtt server
Error: Time:Thu Oct 24 16:56:39 2019 File:/home/pavan/Azure_Clone_Latest/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:prov_transport_common_mqtt_dowork Line:945 unable to create mqtt connection
Error: Time:Thu Oct 24 16:56:39 2019 File:/home/pavan/Azure_Clone_Latest/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:770 Failure retrieving data from the provisioning service
Failure encountered on registration 5
registration failed!
Press any enter to continue:

**Note: Private Key embedded in the source code is not the same as the one used.**

**Note:If the same certificates are embedded into the custom_hsm_example.c(attached), then the SDK is connecting successfully to the device provision service and to IoT Hub. Can you please provide the solution to this bug as I have checked the issue in this as well as in other forums, but the error code seems to be different from the one I have posted and there seems to be no extra characters added in the file. Device Certs are attached in the Issue.zip file(Private Certs are not same as used). Also note that snapshot of public key is added in issue.zip file(PublicKey.png)**
Update: 1) It was verified in openssl tool as well (attached file Openssl.png), but still the same issue
              2) tried changing the file to dos using unix2dos command, but still facing the same issue

[Issue.zip](https://github.com/Azure/azure-iot-sdk-c/files/3767453/Issue.zip)
![Openssl](https://user-images.githubusercontent.com/37648135/67558946-94020b00-f735-11e9-84ac-318c1822c511.PNG)

**Comment by narendranaren14** [comment]
Hi All,

I have similar issue, unable to connect to IoThub. I get similar error "Failure creating private key evp_key". Something wrong with the certificates or the way it generates, IoThub is not liking it,

Machine details are same as above - Linux 18.04 and same openssl version.

Regards
Narendra Setty

**Comment by CIPop** [comment]
There are two separate issues you must consider when using Device Provisioning:

### 1. Provisioning Service Certificate Requirements

Please refer to https://github.com/Azure/azure-sdk-for-c/tree/master/sdk/samples/iot#create-a-device-using-x509-self-signed-certificate-authentication for correct certificate generation.

You can also use Azure KeyVault to create certificates:

The IoT Provisioning Service has several client certificate requirements that the one attached doesn't have:
1. The certificate must have CN=registration-id.
1. Registration ID must follow guidance for allowed characters (i.e. no upper letters, special characters: https://docs.microsoft.com/en-us/azure/iot-dps/concepts-service#registration-id)
1. Key Usage must be configured (depending on certificate type ECC vs RSA: Digital Signature, Key Encipherment)
1. The certificate must contain the V3 attribute of Enhanced Key Usage: Client Authentication OID (1.3.6.1.5.5.7.3.2)
1. The certificate must have the Basic Constraint / Subject Type of End Entity (CA:FALSE in OpenSSL).

### 2. C-SDK Certificate Support

The C-SDK only supports ECC certificates for Device Provisioning authentication. This is not a service limitation: I've tested RSA certificates to work with the service and our Embedded C-SDK: https://github.com/Azure/azure-sdk-for-c

E.g. relevant code for MQTT is hardcoding for ECC certificate type here: https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/src/prov_transport_mqtt_common.c#L565

**Comment by KSroido** [comment]
same error log
I have double checked my crt file and it seems meet all requirement

```
Subject: C = EU, ST = <masked>, L = 0000000, OU = 000000, UID = <masked>, O = 0000, CN = 0x123456<masked, only numbers>, DC = <masked>, DC = <masked>, DC = <masked>

 Signature Algorithm: ecdsa-with-SHA256

 ASN1 OID: prime256v1
                NIST CURVE: P-256

 Authority Information Access:
                <masked>
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Key Agreement
            X509v3 Extended Key Usage:
                TLS Web Client Authentication

```


my error log:

```

Error: Time:Mon Apr 28 09:59:28 2025 File:<root>/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:33 failure creating private
key evp_key
Error: Time:Mon Apr 28 09:59:28 2025 File:<root>/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:40   [0] error:0909006C:PEM
routines:get_name:no start line
Error: Time:Mon Apr 28 09:59:28 2025 File:<root>/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:log_ERR_get_error Line:490 unable to use x509 auth
entication
Error: Time:Mon Apr 28 09:59:28 2025 File:<root>/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1449 Failed creating the O
penSSL instance.
Error: Time:Mon Apr 28 09:59:28 2025 File:<root>/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1124 Error: io_open failed
Error: Time:Mon Apr 28 09:59:28 2025 File:<root>/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:create_connection Line:645 Failu
re connecting to mqtt server
Error: Time:Mon Apr 28 09:59:28 2025 File:<root>/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:prov_transport_common_mqtt_dowor
k Line:919 unable to create mqtt connection

```
