### ISSUE TITLE
Too Much Time to Install! -->   !conda install -c conda-forge wordcloud==1.4.1 --yes

### ISSUE THREAD

**Issue by hhmahmoud** [Azure/azure-iot-sdk-c#1283]
Dear Sir/Madam,

Thanks in advance for reading my Technical Question.

I am running the following command on Python3 using Jupyter Notebook:

!conda install -c conda-forge wordcloud==1.4.1 --yes

The problem is that it is not installing.  For how much time do I need to wait for it to get installed?  I already waited for 20 minutes!

Help please!

Regards,

**Comment by hhmahmoud** [comment]
I was able to resolve it by using the following command:
conda install -c conda-forge word cloud

**Comment by az-iot-builder-01** [comment]
@hhmahmoud, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by ewertons** [comment]
Hi @hhmahmoud ,
did you mean to file this issue against another repo? Conda is not related to Microsoft Azure IoT SDK.
