### ISSUE TITLE
iothub/twin/PATCH/properties/desired/?$version

### ISSUE THREAD

**Issue by PezzoniL** [Azure/azure-iot-sdk-c#1286]
Using the latest version of Azure C-SDK using the public-preview branch

I had seen that I receive the following command from IoT Central PnP when I want to set a desired property:
$iothub/twin/**PATCH**/properties/desired/?$version= .....

So the **parse_device_twin_topic_info** function return the flag for **patch_msg==true**… when I had for example checked one boolean desired property:

IoTHubClientCore_LL_RetrievePropertyComplete= [{"$iotin:settings":{"LedBlink":{"value":false}},"$version":21}]

So I’m not able to answer to the change on the desired property because the status of the Digital Twin will be set to 
**DEVICE_TWIN_UPDATE_PARTIAL**

And for calling my callback the status of the Digital twin should be:
**DEVICE_TWIN_UPDATE_COMPLETE**

Until few days ago I never seen the PATCH and I was able to call my callback when I change some desired properties..

So  is there a way for managing this “Patch” from my code?
Or avoiding that the IoTCentral sent to me the modification of the desiderd property with this “PATCH”

**Comment by az-iot-builder-01** [comment]
@PezzoniL, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
