### ISSUE TITLE
Maximum file name length in blob storage

### ISSUE THREAD

**Issue by Hmaalla** [Azure/azure-iot-sdk-c#1288]
We notice that the file name presents a limit equal to 139 characters.
In fact, we always receive an HTTP 400 error if the file name exceeds this limit

```
Failure in HTTP communication: server reply code is 400
HTTP Response:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>
HTTP code was 400
unable to execute HTTPAPIEX_ExecuteRequest
IoTHubClient_LL_UploadToBlob_step3 failed
```
Could you please confirm this limit and give us more details?

**Comment by rafilho** [comment]
We are working on a fix for that which should be available in our master branch soon. Thanks.

**Comment by Hmaalla** [comment]
Thanks a lot for your feedback, we still waiting for a fix

**Comment by danewalton** [comment]
Hi @Hmaalla 
This will likely not be merged into master until next week but feel free to give it a try and let me know if it fixes your problem in the mean time.
[Link to Branch](https://github.com/Azure/azure-iot-sdk-c/tree/dawalton/uploadblob)

**Comment by Hmaalla** [comment]
Hi @danewalton
I tested the fix committed in your branch "/ dawalton / uploadblob" and I confirm that the problem is well solved
I tested with several configurations, and I remarked that there's now no limit in the blob file name

**Comment by az-iot-builder-01** [comment]
@rafilho, @Hmaalla, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by danewalton** [comment]
@Hmaalla this has been merged to master. thanks for pointing it out!
