### ISSUE TITLE
IoTHubMessage_SetProperty IOTHUB_MESSAGE_ERROR should discern between out of memory situations and input errors

### ISSUE THREAD

**Issue by Ozaq** [Azure/azure-iot-sdk-c#1290]
I have done my best to figure out if this has been requested earlier but I could not find any information. 

When working with `IoTHubMessage_SetProperty` I noticed that only printable US-ACSII characters are allowed for keys / values since `IoTHubMessage_CreateFromByteArray` and `IoTHubMessage_CreateFromString` set a ValidateAsciiCharactersFilter for the internal property map.

`IoTHubMessage_SetProperty` any error in this call will return a `IOTHUB_MESSAGE_ERROR` making it impossible to discern between out-of-memory situations and "ordinary" input validation. 

Please introduce another error state that make those cases differentiable.

Also please update the documentation to include the constraint about printable US-ASCII characters in https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-message-h/iothubmessage-setproperty.

**Comment by az-iot-builder-01** [comment]
@Ozaq, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
