### ISSUE TITLE
Subscribe for twin should have a "skip auto gettwin option"

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1291]
Currently for MQTT at least (and presumably AMQP), if a connection drops and we are subscribed for twin property notifications then we will automatically redownload the entire twin.

We need to leave this behavior as-is for back-compat.  But we should consider a SetOPtion() where client can say "Please don't do this auto-get twin; i'll handle GetTwin() calls myself".

It's a lot more work on client and brings in some risk of losing coherence, but for bandwidth conscious it could help them save bandwidth. 

If we want to do this then doing so prior to PnP being too locked down would be goodness, because we may plumb this up to PnP layer.

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
