### ISSUE TITLE
Unable to build with cocoapod AzureIoTHubClient 1.3.6 enabled

### ISSUE THREAD

**Issue by alexeystrakh** [Azure/azure-iot-sdk-c#1296]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Mac OS Catalina 10.15.1, Xcode 11.2

**SDK Version (Please Give Commit SHA if Manually Compiling)**

AzureIoTHubClient 1.3.6

**Describe the Bug**

I'm trying to create a framework that depends on the [AzureIoTHubClient 1.3.6](https://cocoapods.org/pods/AzureIoTHubClient) pod. This repository contains an empty ObjectiveC framework with an initialized pod workspace. Once the AzureIoTHubClient is added, the Xcode project is no longer compilable:

I've followed instructions and added headers search paths [defined here](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/sdk_cocoapods.md) but wasn't able to compile the project anyways.

Here you can find a [repo with an empty app](https://github.com/alexeystrakh/test-azureiothubclient-cocoapod) with the only pod integrated which reproduces the issue

**Console Logs**

```
testIoTHubFramework/Pods/AzureIoTUtility/src/azure_base32.c:7:10: 'azure_c_shared_utility/buffer_.h' file not found
testIoTHubFramework/Pods/AzureIoTUtility/src/buffer.c:7:10: 'azure_c_shared_utility/gballoc.h' file not found
testIoTHubFramework/Pods/AzureIoTUtility/src/connection_string_parser.c:5:10: 'azure_c_shared_utility/connection_string_parser.h' file not found
testIoTHubFramework/Pods/AzureIoTUtility/src/azure_base64.c:6:10: 'azure_c_shared_utility/gballoc.h' file not found
testIoTHubFramework/Pods/AzureIoTUtility/pal/agenttime.c:4:10: 'azure_c_shared_utility/gballoc.h' file not found
```

**Comment by ewertons** [comment]
You are missing the installation of the dependent cocoapods.

**Comment by abouroubi** [comment]
Which dependent cocoapods ?

I have all of these in my Podfile but still get the same error.

  # Pods for IoT Hub
  pod 'AzureIoTUtility'
  pod 'AzureIoTuMqtt'
  pod 'AzureIoTuAmqp'
  pod 'AzureIoTHubClient'

**Comment by ewertons** [comment]
@jbobotek , would you have the updated instructions?
Maybe we need to update this document: https://github.com/Azure/azure-iot-sdk-c/blob/2019-11-08/doc/sdk_cocoapods.md

**Comment by jbobotek** [comment]
Working directly with him, I should definitely update documentation. Need to ensure I'm adding project wide defines properly in xcode as well.

**Comment by jbobotek** [comment]
That document also makes mention of samples, so that will have to be update when samples are updated and working as well.

**Comment by jbobotek** [comment]
The following pod versions solved issuer's issues:
 'AzureIoTHubClient', '=1.3.6-nightly-a'
 'AzureIoTUtility', '=1.1.12d'
 'AzureIoTuMqtt', '=1.1.12d'
 'AzureIoTuAmqp', '=1.2.12d'

**Comment by az-iot-builder-01** [comment]
@alexeystrakh, @ewertons, @abouroubi, @jbobotek, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
