### ISSUE TITLE
Resend reported properties

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1297]
The SDK does not automatically resend reported properties on timeouts / network disconnections.

We should add some basic retry logic to keep us inline with telemetry message resending.

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
