### ISSUE TITLE
[mbed] Is there a plan to support mbed-os ?

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdk-c#13]
Hi,

We are looking at mbed support in the SDK.
It seems thats sample are based on mbed (the lib) and mbed-rtos. While trying to upgrade (don't know if upgrade is appropriate here) to mbed-os we found that the mbed adapter is based on mbed/mbed-rtos/EthernetInterface.
So upgrading requires slight changes at the adapter level. Is there a plan to do so or mbed-os is not a tarrget for the SDK ?

Thanks.

**Comment by damonbarry** [comment]
We don't have any near-term plans to do this work. We might consider doing it in the future. Contributions welcome! :)
