### ISSUE TITLE
Build failure with -Duse_amqp=OFF

### ISSUE THREAD

**Issue by barronbarnett** [Azure/azure-iot-sdk-c#130]
- **OS and version used:** <VERSION> 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial- **SDK version used:** <VERSION> 
2014-04-21

# Description of the issue:

There is a bug in the iothub_client_samples/CMakeLists.txt in how it handles -Duse_amqp=OFF

# Code sample exhibiting the issue:

cmake -Duse_amqp=OFF -Dbuild_as_dynamic=OFF -DBUILD_SHARED_LIBS=OFF ..
-- Shared_Util architecture: x86_64
-- iothub architecture: x86_64
-- MQTT Target architecture: x86_64
-- iothub architecture: x86_64
-- iothub_service_client build is disabled (AMQP and HTTP support are required)
CMake Warning at CMakeLists.txt:266 (message):
  This package may only be installed when 'use_installed_dependencies' is ON

-- Configuring done
-- Generating done
-- Build files have been written to: /home/v-babarn/Project/test/azure-iot-sdk-c/cmake
v-babarn@barron-linux-dev:~/Project/test/azure-iot-sdk-c/cmake⟫ make clean
v-babarn@barron-linux-dev:~/Project/test/azure-iot-sdk-c/cmake⟫ make
....
# Console log of the issue:
[ 74%] Linking C executable iothub_client_sample_device_method
/usr/bin/ld: cannot find -liothub_client_amqp_transport
/usr/bin/ld: cannot find -luamqp
collect2: error: ld returned 1 exit status
iothub_client/samples/iothub_client_sample_device_method/CMakeFiles/iothub_client_sample_device_method.dir/build.make:100: recipe for target 'iothub_client/samples/iothub_client_sample_device_method/iothub_client_sample_device_method' failed
make[2]: *** [iothub_client/samples/iothub_client_sample_device_method/iothub_client_sample_device_method] Error 1
CMakeFiles/Makefile2:1829: recipe for target 'iothub_client/samples/iothub_client_sample_device_method/CMakeFiles/iothub_client_sample_device_method.dir/all' failed
make[1]: *** [iothub_client/samples/iothub_client_sample_device_method/CMakeFiles/iothub_client_sample_device_method.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

This can quickly be fixed by modifying the CMakeLists.txt  to also check if use_amqp is set before adding the sample directory.

if(${use_amqp}) 
      add_sample_directory(iothub_client_sample_device_method)
endif()

I don't want to submit a pull request because the bug could also be in the iothub_client_sample_device_method in that it links against AMQP but it is actually unnecessary.

**Comment by ewertons** [comment]
Hi @barronbarnett ,
thanks for reporting it, indeed there is a disconnect here. 
We will take care of this issue and reply back soon

**Comment by ewertons** [comment]
Hi @barronbarnett ,
a fix for the issue has been checked in.
Could you get the latest code from master, and try using -Duse_amqp=OFF again please?
Please let us know the result.

**Comment by barronbarnett** [comment]
Latest pull from master worked with -Duse_ampqp=OFF.  Awesome work.

**Comment by ewertons** [comment]
Thanks for using the Azure IoT SDK, and for reporting the issue. Much appreciated!
