### ISSUE TITLE
communicate with azure iot with esp32 via LTE

### ISSUE THREAD

**Issue by kannannair084** [Azure/azure-iot-sdk-c#1303]
Dear All,

i am trying to quickly set-up a system that is able to send data to azure via LTE. 
Mcu is esp32, and i can't use wifi due to project restrictions. 

i am currently in the quest to get it integrated with LTE ( cat m1) to azure.  **is there a way to use azure-iot-sdk-c** to make my life easier?

- my LTE module is SIM7000E ( currently using AT commands via serial port)

if there another module that could easily be integrated to azure sdk, please recommend.

also, if possible provide a sample code or project to guide.

**Comment by danewalton** [comment]
Hi @kannannair084 
Qualcomm has SDK support [here](https://developer.qualcomm.com/blog/connecting-iot-devices-aws-and-azure-cloud-services) for some of their modules to use with Azure. We have an IoT Show episode [here](https://www.youtube.com/watch?v=JFKsggHrRXw) which goes over using it. And lastly [here](https://developer.qualcomm.com/software/lte-iot-sdk/development-kits-reference-device-kits) is a link to some of those SDKs.
Hopefully that helps you along your quest :)

**Comment by danewalton** [comment]
Hey @kannannair084 I'm going to go ahead and close this for now. Please open another issue if you need any more help.

**Comment by az-iot-builder-01** [comment]
@kannannair084, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
