### ISSUE TITLE
Add headers to messages: contentType: application/json and contentEncoding:utf-8 (or utf-16, utf-32)

### ISSUE THREAD

**Issue by Shyamal-V** [Azure/azure-iot-sdk-c#1306]
DT_InterfaceClient_CreateTelemetryMessage is calling IoTHubMessage_SetContentTypeSystemProperty to set “application/json”, but not calling IoTHubMessage_SetContentEncodingSystemProperty for utf8. This was requested by a customer here: 
[Link to pnp bridge issue](https://github.com/Azure/AzurePnPBridgePreview/issues/29)

Filing an issue per request from @jspaith

**Comment by az-iot-builder-01** [comment]
@Shyamal-V, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
