### ISSUE TITLE
Process of Certificate Change in IotHub

### ISSUE THREAD

**Issue by reaction1989** [Azure/azure-iot-sdk-c#1308]
Hello,

atm we are trying to define our process for all related certificates in our chain. We only have a problem atm with the certificate of the iothub because it is not in our responsibility.

Do you have a defined process of the certificate change? E.g do you announce it somewhere in advance? Or do we need to monitor this repo for changes in the cert files? 

Somewhere was sayd that for the next certificate Baltimore will also be used. Do you start adding the cert to this sdk immediatly after it got published?

**Comment by ewertons** [comment]
Thanks for your question, @reaction1989 .
We are gathering some information and will reply to you soon.

**Comment by alexmrtn** [comment]
Hi all,

I have the similar question and more particular regarding the certs you include [in the sources ](https://github.com/Azure/azure-iot-sdk-c/blob/master/certs/certs.c). The wildcard certificate used on iothub is signed by an intermediate MS cert, which is itself signed by the Baltimore root cert. This certificate will expire on 2025. 

I guess you will have at some point two certificates in this file so that devices on the field will go through change seamlessly. If you have detail on this process of certificate renewal it would be great! I'm thinking about date of new certificate availability and notification process.

Thanks!

**Comment by reaction1989** [comment]
@ewertons have you been able to gather the needed informations?

**Comment by ewertons** [comment]
Hi @reaction1989 ,
we did gather part of the information you are looking for, however I am working to verify if we can convey it in a more official way as part of the Microsoft Azure online documentation.

The certificates that Microsoft Azure IoT handle are the ones related to the certificate chain for TLS negotiation: the root (e.g., Baltimore), intermediate (Microsoft CA) and leaf cert associated with your Azure IoT Hub. The leaf certificate can change without notice but should not negatively impact the device client functionality.
But what you are interested on are the root and intermediate certs, which we do ship in [our repo](https://github.com/Azure/azure-iot-sdk-c/tree/master/certs) (and must be used in the Azure IoT C SDK client for validating the IoT Hub leaf cert, either through a cert store if the platform supports it or using our [API functions](https://github.com/Azure/azure-iot-sdk-c/blob/2019-11-08/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L131)). These are rolled with less frequency, and when they do there is communication in advance to customers that they should update the certs in their devices.
The piece I am looking for to provide you is all this information put in an official page in our online documentation. There is work being done to provide that, and I will update you as soon as it is available.

**Comment by wduraes** [comment]
Hi @reaction1989, 

Your question became an item on the IoT Hub team backlog which will be prioritized for implementation, but there is no timeline yet for the team to address it yet.

Until we have this implemented, the release notes (https://github.com/Azure/azure-iot-sdk-c/releases) on the SDK repo will be the best place to get that information. 

We will close this issue for now, but if you would like it to be reopened and follow up on this matter, please post a comment requesting so.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@reaction1989, @wduraes, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
