### ISSUE TITLE
IoTHubClient_LL_SendEventAsync/IoTHubMessage_Destroy - memory management and example consistency

### ISSUE THREAD

**Issue by alaendle** [Azure/azure-iot-sdk-c#1309]
The question is when is it safe to destroy the message - call IoTHubMessage_Destroy?

E.g. the following code immediately calls Destroy after SendEventAsync - which seems strange to me, because of the asynchronous character!? So couldn't it be that the message is freed before it is even sent?

https://github.com/Azure/azure-iot-sdk-c/blob/241b66eb6499e2c019682f252d911ef2b28d1302/iothub_client/samples/iothub_ll_client_sample_amqp_shared/iothub_ll_client_sample_amqp_shared.c#L283-L297

Also other code - like...

https://github.com/Azure/azure-iot-sdk-c/blob/241b66eb6499e2c019682f252d911ef2b28d1302/iothub_client/samples/iothub_client_sample_module_filter/iothub_client_sample_module_filter.c#L151-L154

https://github.com/Azure/azure-iot-sdk-c/blob/241b66eb6499e2c019682f252d911ef2b28d1302/iothub_client/samples/iothub_client_sample_module_filter/iothub_client_sample_module_filter.c#L86-L91

only destroys the message if the call to SendEventAsync fails - and otherwise postpones the disposal into the confirmation callback - this seems logically more correct. But if this is correct, then there is the bonus question - what happens if the callback is NULL - is the message freed implicitly by SendEventAsync in this case? Or are we just having a memory leak since there is no defined event at which we can be sure it is ok to dispose the sent messages?

Unfortunately the documentation (https://docs.microsoft.com/de-de/azure/iot-hub/iot-c-sdk-ref/iothub-client-core-ll-h/iothubclientcore-ll-sendeventasync) is just not meaningful and the sample code is as explained contradictive.

Thanks in advance for any hints and please don't hesitate to ask if I kept to short and you need additional input to get the intention.

**Comment by ewertons** [comment]
Hi @alaendle ,
we apologize for the documentation not being straightforward about that aspect. Indeed we are constantly reviewing and updating our docs, but some information might still be missing.

Answering your question, IoTHubClient_LL_SendEventAsync, IoTHubDeviceClient_LL_SendEventAsync and IoTHubDeviceClient_SendEventAsync all create an internal copy of the IOTHUB_MESSAGE_HANDLE instance provided as argument.
That is why you can destroy the message right after calling any of these functions above.
The internal copy is then owned by the IoT Hub client layer, that destroys the message as soon as it is effectively sent out on the wire to the Azure IoT Hub.

**Comment by alaendle** [comment]
Many thanks @ewertons for the immediate and detailed answer - that sounds good; since this simplifies the handling a lot I will adjust my code correspondingly. From my side we could close this issue - unless you want to keep it as a reminder to improve the documentation/examples.

**Comment by ewertons** [comment]
@alaendle ,
let us make an update to the documentation and we will then close this issue.
Thanks.

**Comment by ewertons** [comment]
Updated merged. 
Once again, thanks for your contribution, @alaendle .

Azure IoT Team.

**Comment by az-iot-builder-01** [comment]
@ewertons, @alaendle, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
