### ISSUE TITLE
Don't directly reference `DIGITALTWIN_CLIENT_SDK_VERSION` in SDK Information

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1311]
PnP's sample of SDKInformation has a hardcoded reference of `DIGITALTWIN_CLIENT_SDK_VERSION` in it to specify the version.

If the dev updates the SDK and statically links the code in, then we'll be fine because `DIGITALTWIN_CLIENT_SDK_VERSION` will be updated and they'll recompile.

If they're using pnp_sdk.dll and not recompiling, directly referencing `DIGITALTWIN_CLIENT_SDK_VERSION` is a problem.

Instead we should:
* Fix SDKInformation to use `DigitalTwin_Client_GetVersionString`.
* Remove `DIGITALTWIN_CLIENT_SDK_VERSION` from the header so that other people don't make the same mistake.

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
