### ISSUE TITLE
Issue importing AzureIoTHubClient in Xcode (Could not build Objective-C module 'AzureIoTHubClient')

### ISSUE THREAD

**Issue by bradmclaughlin** [Azure/azure-iot-sdk-c#1314]
When running the sample code (from guide: https://docs.microsoft.com/en-gb/azure/iot-hub/quickstart-send-telemetry-ios ) in Xcode (.xcworkspace), I get the error: Could not build Objective-C module 'AzureIoTHubClient'.

I am running Xcode 11.2.1 and Cocoapods 1.8.4.

Without this package, I cannot connect the IoT Hub at all

The Podfile defines iOS 9.0 but I have also tried uncommenting the line to default it to iOS 10.2.

**Comment by ewertons** [comment]
Hi @bradmclaughlin ,
with the message "Could not build Objective-C module 'AzureIoTHubClient'." we don't have any information at all to work with.
Do you get any other compilation error messages?

**Comment by bradmclaughlin** [comment]
Hi @ewertons, thanks for the rapid response. 

I appreciate I haven't given vast details but I am not doing anything custom, I am simply taking the example code from Microsoft (link in original post) and trying to build it. 

So I installed the relevant pods as mentioned in the guide, and opened the xcworkspace. Following this, I opened ViewController.swift and see the error. Perhaps you could download the sample code and see if you get the same error?

The AzureIoTHubClient pod seems to be Objective-C rather than Swift, which Xcode seems to not like, throwing the error: "Could not build Objective-C module 'AzureIoTHubClient'".

**Comment by jbobotek** [comment]
What version of AzureIoTHubClient is it downloading? Also, is it giving you more error information than that? Could it be that it's looking for a framework for the Client pod?

**Comment by bradmclaughlin** [comment]
Hi @jbobotek, it is using AzureIoTHubClient version 1.3.6. The only other information I get is the error: “‘azure_c_shared_utility/gballoc.h’ file not found”, and a warning about architecture?

I’m not sure what you mean about looking for a framework of the pod. 

I’ve attached a screenshot of the Xcode errors/warnings. 

<img width="1138" alt="FBE43B4E-4B7D-4D3D-98D7-2CD67DAF00D0" src="https://user-images.githubusercontent.com/36672294/68902415-293e6100-0730-11ea-9217-649667484a9a.png">

**Comment by jbobotek** [comment]
@bradmclaughlin You may need to also include AzureIoTUtility, AzureIoTuMqtt and AzureIoTuAmqp in your Podfile as well.

**Comment by bradmclaughlin** [comment]
Hi @jbobotek, the Podfile already includes these.
![image](https://user-images.githubusercontent.com/36672294/68906371-ed10fd80-073b-11ea-9b8e-b37a1c159aa1.png)

**Comment by jbobotek** [comment]
That 1.3.6 was actually a bit of a prerelease version, these following later versions may solve some of your issues: 
pod 'AzureIoTUtility', '=1.1.12c'
pod 'AzureIoTuAmqp', '=1.2.12c'
pod 'AzureIoTuMqtt', '=1.1.12c'
pod 'AzureIoTHubClient', '=1.3.6-nightly'

Note that these are in progress versions, but I have found them to fully compile with certain samples. Feel free to try them out and get ahead of the curve.

**Comment by bradmclaughlin** [comment]
Hi @jbobotek, this actually caused way more errors than before. Have you tried running the example code yourself to see if it is just my machine or a more general problem?

<img width="268" alt="1" src="https://user-images.githubusercontent.com/36672294/68919882-78ee4e00-076b-11ea-872e-e533226e9fdc.png">
<img width="268" alt="2" src="https://user-images.githubusercontent.com/36672294/68919881-78ee4e00-076b-11ea-9de2-bb0c0c4682ce.png">
<img width="268" alt="3" src="https://user-images.githubusercontent.com/36672294/68919884-7986e480-076b-11ea-99a9-1e01b74bb002.png">
<img width="268" alt="4" src="https://user-images.githubusercontent.com/36672294/68919883-78ee4e00-076b-11ea-9f25-8c0291826829.png">

**Comment by jbobotek** [comment]
There's an error in generating the modulemap, pushing an update, you can also just delete all file references in the umock module map save for umock_c_prod.h

**Comment by jbobotek** [comment]
@bradmclaughlin 
Please use these following pod versions to address these issues:
 'AzureIoTHubClient', '=1.3.6-nightly-a'
 'AzureIoTUtility', '=1.1.12d'
 'AzureIoTuMqtt', '=1.1.12d'
 'AzureIoTuAmqp', '=1.2.12d'

**Comment by az-iot-builder-01** [comment]
@ewertons, @bradmclaughlin, @jbobotek, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by bradmclaughlin** [comment]
Thank you @jbobotek for all your help. I can confirm the updates to the pods have worked!

**Comment by shadone** [comment]
This issue is happening (again) with the latest version of Azure IoT SDKs.
I am using Xcode 11.3.1 (11C504); cocoa pods 1.9.1 and see the same issue when trying to compile the example project (https://github.com/Azure-Samples/azure-iot-samples-ios):

```
/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureuMockC/inc/module.modulemap:2:12: Header 'umock_c/umock_c.h' not found

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/agenttime.h:28:19: Expected parameter declarator

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/agenttime.h:35:19: Expected parameter declarator

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/agenttime.h:35:1: Conflicting types for 'MOCKABLE_FUNCTION'

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/agenttime.h:42:19: Expected parameter declarator

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/agenttime.h:42:1: Conflicting types for 'MOCKABLE_FUNCTION'

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/agenttime.h:49:19: Expected parameter declarator

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/agenttime.h:49:1: Conflicting types for 'MOCKABLE_FUNCTION'

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/agenttime.h:57:19: Expected parameter declarator

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/agenttime.h:57:1: Conflicting types for 'MOCKABLE_FUNCTION'

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureuMockC/inc/module.modulemap:2:12: Header 'umock_c/umock_c.h' not found

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/strings.h:21:19: Expected parameter declarator

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/strings.h:21:1: Conflicting types for 'MOCKABLE_FUNCTION'

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/strings.h:22:19: Expected parameter declarator

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/strings.h:22:1: Conflicting types for 'MOCKABLE_FUNCTION'

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/strings.h:23:19: Expected parameter declarator

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/strings.h:23:1: Conflicting types for 'MOCKABLE_FUNCTION'

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/strings.h:24:19: Expected parameter declarator

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTUtility/inc/azure_c_shared_utility/strings.h:24:1: Conflicting types for 'MOCKABLE_FUNCTION'

Too many errors emitted, stopping now

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/Pods/AzureIoTHubClient/inc/agenttypesystem.h:20:10: Could not build module 'AzureIoTUtility'

/Users/denis/dev/random/azure-iot-samples-ios/quickstart/sample-device/MQTT Client Sample/ViewController.swift:5:8: Could not build Objective-C module 'AzureIoTHubClient'
```

If I pin the SDKs version to the older one suggested above (https://github.com/Azure/azure-iot-sdk-c/issues/1314#issuecomment-555227314) then it works just fine.

Am I correct to assume this is the same issue happening again?

**Comment by jbobotek** [comment]
What do you mean by latest version? are you using these versions in your Podfile?: 'AzureIoTHubClient', '=1.3.8a' 'AzureIoTUtility', '=1.3.8a' 'AzureIoTuMqtt', '=1.3.8a' 'AzureIoTuAmqp', '=1.3.8a'

**Comment by shadone** [comment]
I tried with latest SDK that is published to CocoaPods which is this:
```
Installing AzureIoTHubClient (1.3.8)
Installing AzureIoTUtility (1.3.8)
Installing AzureIoTuAmqp (1.3.8)
Installing AzureIoTuMqtt (1.3.8)
Installing AzureMacroUtils (1.1.0)
Installing AzureuMockC (1.1.19c)
```

You should be able to reproduce the issue in the example project https://github.com/Azure-Samples/azure-iot-samples-ios

```
$ g clone git@github.com:Azure-Samples/azure-iot-samples-ios.git
Cloning into 'azure-iot-samples-ios'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 161 (delta 0), reused 0 (delta 0), pack-reused 158
Receiving objects: 100% (161/161), 124.52 KiB | 579.00 KiB/s, done.
Resolving deltas: 100% (60/60), done.
$ cd ./azure-iot-samples-ios/quickstart/sample-device/
$ ls
MQTT Client Sample/                   MQTT Client Sample-Bridging-Header.h  MQTT Client Sample.xcodeproj/         Podfile
$ cat Podfile
# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

workspace 'MQTT Client Sample'

target 'MQTT Client Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MQTT Client Sample
  pod 'AzureIoTUtility'
  pod 'AzureIoTuMqtt'
  pod 'AzureIoTuAmqp'
  pod 'AzureIoTHubClient'
end
$ pod install
Analyzing dependencies
Downloading dependencies
Installing AzureIoTHubClient (1.3.8)
Installing AzureIoTUtility (1.3.8)
Installing AzureIoTuAmqp (1.3.8)
Installing AzureIoTuMqtt (1.3.8)
Installing AzureMacroUtils (1.1.0)
Installing AzureuMockC (1.1.19c)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `MQTT Client Sample.xcworkspace` for this project from now on.
Pod installation complete! There are 4 dependencies from the Podfile and 6 total pods installed.
$ xed .
```

**Comment by jbobotek** [comment]
Yes, please try with the 'a' versions.
