### ISSUE TITLE
The latest mbed OS 5 support

### ISSUE THREAD

**Issue by Osamu-Nakamura** [Azure/azure-iot-sdk-c#132]
- **OS and version used:** <VERSION> 
mbed
- **SDK version used:** <VERSION> 
TBD

# Description of the issue:

At present, it seems that there are no sample program running on the latest mbed OS 5. We would like to use not mbed OS 2 that is currently supported but mbed OS 5. Is any sample program for mbed OS 5 available? Also, if no program is available, is there any plan to support mbed OS 5 from now on?
# Code sample exhibiting the issue:

N/A
# Console log of the issue:

N/A

**Comment by tameraw** [comment]
@Osamu-Nakamura - Currently we do not provide samples of the SDK running on MBED OS 5 and this has not bubbled up in priority in our backlog as of yet.

**Comment by Osamu-Nakamura** [comment]
Thank you for the clarification. If there is no plan for mbed OS 5, should we still use mbed OS 2 in order to obtain the certification of "Azure Certified for IoT"? Or can we use our own mbed OS 5 based environment?

**Comment by tameraw** [comment]
If you got MBED OS 5 working on your device with our SDK and can provide reliable detailed steps to the users, then you should be able to certify with that OS if you wish to do so.

**Comment by Osamu-Nakamura** [comment]
@tameraw Thank for you the clarification. Your info could answer my question and so, I close this issue.
