### ISSUE TITLE
device info sample should utilize a header where values are set

### ISSUE THREAD

**Issue by gregman-msft** [Azure/azure-iot-sdk-c#1325]
The values provided for the device info interface sample are in the c file, these should instead be #defines in a header, with default values provided if not defined. I would also recommend following the following guidelines for the default values: A.B.C.D for version where each is an integer and 1-64 chars, alphanumeric, dot and dash only for other fields.

**Comment by az-iot-builder-01** [comment]
@gregman-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
