### ISSUE TITLE
Remove DIGITALTWIN_LOGGING_ENABLED and move to standard log

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1326]
Today DigitalTwin has a special macro for logging out info, though it falls directly to the C SDK `LogInfo`.  There's no equivalent `DigitalTwinLogError` - the code in DT uses `LogError` directly - so the lack of symmetry is one problem.

We should remove `DigitalTwinLogInfo` and replace it with `LogInfo` like everything else across C SDK.  The intent was to allow DT logs to be not included but C SDK to be, but don't think this is worth pattern mismatch.  Also need to remove references to `DIGITALTWIN_LOGGING_ENABLED` in docs / .c files a few places.

```c
#ifdef DIGITALTWIN_LOGGING_ENABLED
#define DigitalTwinLogInfo LogInfo
#else
#define DigitalTwinLogInfo(...)
#endif
```

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
