### ISSUE TITLE
Need a space between "[" and "-s" in file jenkins/raspberrypi/Dockerfile

### ISSUE THREAD

**Issue by wangluochao902** [Azure/azure-iot-sdk-c#1327]
In file https://github.com/Azure/azure-iot-sdk-c/blob/4414e93ee92d0be04b201dae4195737d3d8b042d/jenkins/raspberrypi/Dockerfile#L131
there should be a space between "[" and "-s". Is it a bug?

**Comment by ewertons** [comment]
Hi @wangluochao902 ,

would you like to send us a PR? We will review and merge right away.

**Comment by ewertons** [comment]
Thank you @wangluochao902 !
The PR is approved, and it will be merged briefly.

**Comment by gregman-msft** [comment]
Thanks so much for contributing to our repository!

**Comment by az-iot-builder-01** [comment]
@wangluochao902, @ewertons, @gregman-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
