### ISSUE TITLE
Linking error related to libcurl while building azure-iot-sdk-c sample code

### ISSUE THREAD

**Issue by divakarvannalli** [Azure/azure-iot-sdk-c#1334]
While porting azure-iot-sdk-c (version 1.3.4)on one of  our platform i found out that there are  bugs inside `CMakeLists.txt `files of sample applications.
```
iothub_client/samples/iothub_client_sample_upload_to_blob/linux/CMakeLists.txt
iothub_client/samples/iothub_client_sample_mqtt_dm/CMakeLists.txt
iothub_client/samples/iothub_ll_c2d_sample/linux/CMakeLists.txt
iothub_client/samples/iothub_ll_client_sample_amqp_shared/linux/CMakeLists.txt
iothub_client/samples/iothub_client_sample_upload_to_blob_mb/linux/CMakeLists.txt
iothub_client/samples/iothub_ll_telemetry_sample/linux/CMakeLists.txt
iothub_client/samples/iothub_ll_client_x509_sample/linux/CMakeLists.txt
```

Basically issue is that you people are directly referring curl library before doing proper `find_library(CURL)` or `find_package(CURL)`.
for example in the below code, which is part of  `iothub_client/samples/iothub_ll_client_x509_sample/linux/CMakeLists.txt `, you people could have done something like `find_package(CURL)` before calling  `target_link_libraries` .Due to this  during the linking  linker is referring to `libcurl.so` from `/sysroot/curl/lib/libcurl.so` not from the path which we have passed to `cmake` via `toolchain.cmake` (i.e it is not taking curl path referred by `CURL_LIBRARY`)

```
target_link_libraries(iothub_client_x509_sample
    iothub_client_mqtt_transport
    iothub_client_amqp_transport
    iothub_client_http_transport
    iothub_client
    umqtt
    prov_auth_client
    hsm_security_client
    uhttp
    aziotsharedutil
    parson
    uuid
    pthread
    curl
    ssl
    crypto
    m
)
```

Same issue exists with all the above mentioned `CMakeLists.txt`.i want to know is there any fix for it ?
Also i have posted the issue details and fix on [stackoverflow](https://stackoverflow.com/questions/58859841/linking-error-related-to-libcurl-while-building-azure-iot-sdk-c-sample-code) ,please look into it .
Also i found out  by looking into `azure-iot-sdk-c/CMakeLists.txt` that , by default building of sample applications are disabled as per below line of code
`set(skip_samples ON)`
but it is not making any effect (i guess this line is at the wrong place , you people should have defined `set(skip_samples ON)` above `set(original_skip_samples ${skip_samples})`).so the sample application's build is happening by default.

**Comment by ewertons** [comment]
@divakarvannalli  , we will close this issue according to our prioritization.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@divakarvannalli, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
