### ISSUE TITLE
Is blob uploaded working?

### ISSUE THREAD

**Issue by liudr** [Azure/azure-iot-sdk-c#1343]
Since there isn't any example on blob upload, I'm wondering if this feature is available in this port.

More specifically, is either function actually working?

IoTHubDeviceClient_LL_UploadToBlob()
IoTHubDeviceClient_UploadToBlobAsync()

Is this thing defined or where should I find it if it is defined:

#ifndef DONT_USE_UPLOADTOBLOB

I found their definitions in the source code. What is the LL? Lower level? What is the difference? The non_LL has a callback and a pointer probably for the callback's parameters. Is that the difference? The non_LL is asyn because it creates a task and hands off the work to the task? Any pointer to the main azure iot port doc is greatly appreciated.

**Comment by liudr** [comment]
Tried to compile code that involves call to IoTHubDeviceClient_LL_UploadToBlob() and linker error. Is the blob actually supported? I have doubts now.

> D:/Downloads/msys32_iot/home/user/esp/Projects/iot_scanner/build/esp-azure\libesp-azure.a(httpapiex.o):(.literal.HTTPAPIEX_ExecuteRequest+0x10): undefined reference to `HTTPAPI_Init'
D:/Downloads/msys32_iot/home/user/esp/Projects/iot_scanner/build/esp-azure\libesp-azure.a(httpapiex.o):(.literal.HTTPAPIEX_ExecuteRequest+0x14): undefined reference to `HTTPAPI_CreateConnection'
D:/Downloads/msys32_iot/home/user/esp/Projects/iot_scanner/build/esp-azure\libesp-azure.a(httpapiex.o):(.literal.HTTPAPIEX_ExecuteRequest+0x18): undefined reference to `HTTPAPI_SetOption'
D:/Downloads/msys32_iot/home/user/esp/Projects/iot_scanner/build/esp-azure\libesp-azure.a(httpapiex.o):(.literal.HTTPAPIEX_ExecuteRequest+0x1c): undefined reference to `HTTPAPI_ExecuteRequest'
D:/Downloads/msys32_iot/home/user/esp/Projects/iot_scanner/build/esp-azure\libesp-azure.a(httpapiex.o):(.literal.HTTPAPIEX_ExecuteRequest+0x20): undefined reference to `HTTPAPI_Deinit'
D:/Downloads/msys32_iot/home/user/esp/Projects/iot_scanner/build/esp-azure\libesp-azure.a(httpapiex.o):(.literal.HTTPAPIEX_ExecuteRequest+0x24): undefined reference to `HTTPAPI_CloseConnection'
D:/Downloads/msys32_iot/home/user/esp/Projects/iot_scanner/build/esp-azure\libesp-azure.a(httpapiex.o):(.literal.HTTPAPIEX_SetOption+0x4): undefined reference to `HTTPAPI_CloneOption'
D:/Downloads/msys32_iot/home/user/esp/Projects/iot_scanner/build/esp-azure\libesp-azure.a(httpapiex.o): In function `HTTPAPIEX_ExecuteRequest':
D:/Downloads/msys32_iot/home/user/esp/esp-azure/azure-iot-sdk-c/c-utility/src/httpapiex.c:363: undefined reference to `HTTPAPI_Init'
D:/Downloads/msys32_iot/home/user/esp/esp-azure/azure-iot-sdk-c/c-utility/src/httpapiex.c:373: undefined reference to `HTTPAPI_CreateConnection'
D:/Downloads/msys32_iot/home/user/esp/esp-azure/azure-iot-sdk-c/c-utility/src/httpapiex.c:397: undefined reference to `HTTPAPI_SetOption'
D:/Downloads/msys32_iot/home/user/esp/esp-azure/azure-iot-sdk-c/c-utility/src/httpapiex.c:411: undefined reference to `HTTPAPI_ExecuteRequest'
D:/Downloads/msys32_iot/home/user/esp/esp-azure/azure-iot-sdk-c/c-utility/src/httpapiex.c:447: undefined reference to `HTTPAPI_Deinit'
D:/Downloads/msys32_iot/home/user/esp/esp-azure/azure-iot-sdk-c/c-utility/src/httpapiex.c:448: undefined reference to `HTTPAPI_CloseConnection'
D:/Downloads/msys32_iot/home/user/esp/Projects/iot_scanner/build/esp-azure\libesp-azure.a(httpapiex.o): In function `HTTPAPIEX_Destroy':
D:/Downloads/msys32_iot/home/user/esp/esp-azure/azure-iot-sdk-c/c-utility/src/httpapiex.c:336: undefined reference to `HTTPAPI_CloseConnection'
D:/Downloads/msys32_iot/home/user/esp/esp-azure/azure-iot-sdk-c/c-utility/src/httpapiex.c:313: undefined reference to `HTTPAPI_Deinit'
D:/Downloads/msys32_iot/home/user/esp/Projects/iot_scanner/build/esp-azure\libesp-azure.a(httpapiex.o): In function `HTTPAPIEX_SetOption':
D:/Downloads/msys32_iot/home/user/esp/esp-azure/azure-iot-sdk-c/c-utility/src/httpapiex.c:603: undefined reference to `HTTPAPI_CloneOption'
D:/Downloads/msys32_iot/home/user/esp/esp-azure/azure-iot-sdk-c/c-utility/src/httpapiex.c:625: undefined reference to `HTTPAPI_SetOption'
D:/Downloads/msys32_iot/home/user/esp/Projects/iot_scanner/build/esp-azure\libesp-azure.a(iothub_client_ll_uploadtoblob.o):(.literal.IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl+0x68): undefined reference to `Blob_UploadMultipleBlocksFromSasUri'
D:/Downloads/msys32_iot/home/user/esp/Projects/iot_scanner/build/esp-azure\libesp-azure.a(iothub_client_ll_uploadtoblob.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
D:/Downloads/msys32_iot/home/user/esp/esp-azure/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c:780: undefined reference to `Blob_UploadMultipleBlocksFromSasUri'

**Comment by az-iot-builder-01** [comment]
@liudr, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
