### ISSUE TITLE
Could the pnp c smaple be cross compiled on android platform?

### ISSUE THREAD

**Issue by yuanjun-123** [Azure/azure-iot-sdk-c#1345]
when I coross compile azure-iot-sdk-c and pnp sample using arm-linux-androideabi toolchain (generated by NDK tools). it occurs error:

cannot find -lpthread

I did some research and found that andorid did not provice pthread lib.
So, I want to comfirm whether the pnp sample can be  complied with android platform.

**scenario: android device pnp certification.**
target android version : 4.4.2
target sdk version: 19
Is there another advices about the scenario
look forward your reply.
Thanks

**Comment by danewalton** [comment]
Hi @yuanjun-123 
It seems [here](https://stackoverflow.com/questions/38666609/cant-find-lpthread-when-cross-compile-to-arm) that pthread support is built in to android, in which case the inclusion of the pthread library is unnecessary. Could you try going to the sample you might be trying to compile and remove the `pthread` included in the `CMakeLists.txt` for that sample. An example where it is located is [here in this sample](https://github.com/Azure/azure-iot-sdk-c/blob/df87ef116d24038851a8d0b43e1c4ce638c407ed/iothub_client/samples/iothub_ll_telemetry_sample/linux/CMakeLists.txt#L41).

**Comment by jasmineymlo** [comment]
Closed inactive.  @yuanjun-123, Please file new issue or reopen if you need further assistance.

**Comment by az-iot-builder-01** [comment]
@yuanjun-123, @danewalton, @jasmineymlo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
