### ISSUE TITLE
Test CA certs step 3: Proof-Of-Possession failed.

### ISSUE THREAD

**Issue by coderbyheart** [Azure/azure-iot-sdk-c#1347]
Following the [Managing test CA certificates for samples and tutorials](https://github.com/Azure/azure-iot-sdk-c/blob/2f98248899d486a0fed1c1ffc2c7226a77327845/tools/CACertificates/CACertificateOverview.md) Step 3 fails for me, after running

    ./certGen.sh create_verification_certificate <verification code>

I select the `verification-code.cert.pem` file in the UI but the proof-of-possession fails with:

> Proof-Of-Possession failed. Issuer certificate 'CN=Azure IoT Hub Intermediate Cert Test Only' cannot be found in the certificate chain. If you contact a support representative please include this correlation identifier: 341bf1b2-d7c8-4761-b36e-66976f57d92d, timestamp: 2019-11-26 12:01:32Z, errorcode: IH400053.

➜ openssl version
OpenSSL 1.1.1d  10 Sep 2019

**Comment by coderbyheart** [comment]
The root certificate is the one that needs to be uploaded `azure-iot-test-only.root.ca.cert.pem`. This then can be verified with the `verification-code.cert.pem`.

**Comment by az-iot-builder-01** [comment]
@coderbyheart, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
