### ISSUE TITLE
Terminate a thread by using ThreadAPI_Exit()

### ISSUE THREAD

**Issue by Hmaalla** [Azure/azure-iot-sdk-c#1348]
Hello,
We are using the multithreading abstraction layer given by the "c - utility" to develop a multithreading application.
We have some memory leaks if we exit a thread by calling ThreadAPI_Exit () without joining it with ThreadAPI_Join ().
If fact, the free of "threadHandle" ressources is done only by calling ThreadAPI_Join ().
The question here, it's possible to free "threadHandle" also in ThreadAPI_Exit () to give more flexibility to the user to exit the created thread without joining it?

**Comment by ewertons** [comment]
Hi @Hmaalla , 
this seems filed in the wrong repository. Here is the correct issue to follow:
https://github.com/Azure/azure-c-shared-utility/issues/418

**Comment by az-iot-builder-01** [comment]
@Hmaalla, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
