### ISSUE TITLE
Setting AMQP reconnection interval does not work

### ISSUE THREAD

**Issue by mlilien** [Azure/azure-iot-sdk-c#1349]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Raspberry Pi, Balena OS 2.43, gcc, musl-libc

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2019-10-07, LTS_02_2020_Ref01

**Protocol**

AMQP

**Describe the Bug**

I use a AMQP connection to iothub and configure to try to reconnect every 30 seconds with the interval retry strategy:

```
int _interval=30;
if (IOTHUB_CLIENT_OK != IoTHubClient_SetRetryPolicy( _iotHubClientHandle, IOTHUB_CLIENT_RETRY_INTERVAL, 0))
{
	...
}
else if ( IOTHUB_CLIENT_OK != IoTHubClient_SetOption( _iotHubClientHandle, OPTION_RETRY_INTERVAL_SEC ,&_interval))
{
	...
}
```
What I see, is that my application tries to reconnect every 4 Minutes. So setting the police to IOTHUB_CLIENT_RETRY_INTERVAL works.
But setting OPTION_RETRY_INTERVAL_SEC seems not to work as expected.

**Comment by ewertons** [comment]
Hi @mlilien ,
this is unexpected. Could you paste a complete log (with obfuscated iothub fqdn) showing the reconnection traces please? Use [this](https://github.com/Azure/azure-iot-sdk-c/blob/2019-11-08/iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample.c#L271) to enable verbose logs.

**Comment by mlilien** [comment]
Hi @ewertons,
here is the corresponding trace 
-> Header (AMQP 0.1.0.0)
<- Header (AMQP 0.1.0.0)
-> [OPEN]* {???,???.azure-devices.net,4294967295,65535,240000}
<- [OPEN]* {DeviceGateway_???,10.0.8.38,65536,8191,240000,NULL,NULL,NULL,NULL,NULL}
-> [BEGIN]* {NULL,0,4294967295,100,4294967295}
<- [BEGIN]* {0,1,5000,4294967295,262143,NULL,NULL,NULL}
-> [ATTACH]* {$cbs-sender,0,false,0,0,* {$cbs},* {$cbs},NULL,NULL,0,0}
-> [ATTACH]* {$cbs-receiver,1,true,0,0,* {$cbs},* {$cbs},NULL,NULL,NULL,0}
<- [ATTACH]* {$cbs-sender,0,true,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,NULL}
<- [FLOW]* {0,5000,1,4294967295,0,0,100,0,NULL,false,NULL}
-> [TRANSFER]* {0,0,<01 00 00 00>,0,false,false}
<- [ATTACH]* {$cbs-receiver,1,false,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,1048576,NULL,NULL,NULL}
-> [FLOW]* {1,4294967295,1,99,1,0,10000}
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
<- [TRANSFER]* {1,0,<01 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,0,0,true,* {}}
-> [ATTACH]* {link-snd-???-???,2,false,0,0,* {link-snd-???-???-source},* {amqps://???.azure-devices.net/devices/???/messages/events},NULL,NULL,0,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.3.6 (native; Linux; armv7l)]}}
-> [ATTACH]* {link-snd-???-???,3,false,0,0,* {link-snd-???-???-source},* {amqps://???.azure-devices.net/devices/???/twin},NULL,NULL,0,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.3.6 (native; Linux; armv7l)],[com.microsoft:channel-correlation-id:twin:???],[com.microsoft:api-version:2016-11-14]}}
<- [ATTACH]* {link-snd-???-???,2,true,0,NULL,* {link-snd-???-???-source,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {amqps://???.azure-devices.net/devices/???/messages/events,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.3.6 (native; Linux; armv7l)]}}
<- [FLOW]* {1,5000,2,4294967295,2,0,1000,0,NULL,false,NULL}
<- [ATTACH]* {link-snd-???-???,3,true,1,0,* {link-snd-???-???-source,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {amqps://???.azure-devices.net/devices/???/twin,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.3.6 (native; Linux; armv7l)],[com.microsoft:channel-correlation-id:twin:???],[com.microsoft:api-version:2016-11-14]}}
<- [FLOW]* {1,5000,2,4294967295,3,0,1000,0,NULL,false,NULL}
-> [ATTACH]* {link-rcv-???-???,4,true,0,0,* {amqps://???.azure-devices.net/devices/???/messages/devicebound},* {link-rcv-???-???-target},NULL,NULL,NULL,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.3.6 (native; Linux; armv7l)]}}
-> [ATTACH]* {link-rcv-???-???,5,true,0,0,* {amqps://???.azure-devices.net/devices/???/twin},* {link-rcv-???-???-target},NULL,NULL,NULL,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.3.6 (native; Linux; armv7l)],[com.microsoft:channel-correlation-id:twin:???],[com.microsoft:api-version:2016-11-14]}}
<- [ATTACH]* {link-rcv-???-???,4,false,NULL,1,* {amqps://???.azure-devices.net/devices/???/messages/devicebound,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {link-rcv-???-???-target,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.3.6 (native; Linux; armv7l)]}}
-> [FLOW]* {2,4294967294,1,99,4,0,10000}
<- [ATTACH]* {link-rcv-???-???,5,false,1,0,* {amqps://???.azure-devices.net/devices/???/twin,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {link-rcv-???-???-target,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.3.6 (native; Linux; armv7l)],[com.microsoft:channel-correlation-id:twin:???],[com.microsoft:api-version:2016-11-14]}}
-> [FLOW]* {2,4294967294,1,99,5,0,10000}
-> [TRANSFER]* {2,1,<01 00 00 00>,2147563264,false,false}
-> [TRANSFER]* {2,2,<02 00 00 00>,2147563264,false,false}
-> [TRANSFER]* {2,3,<03 00 00 00>,2147563264,false,false}
-> [TRANSFER]* {2,4,<04 00 00 00>,2147563264,false,false}
-> [TRANSFER]* {2,5,<05 00 00 00>,2147563264,false,false}
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:on_amqp_connection_state_changed Line:778 Transport received an ERROR from the amqp_connection (state changed AMQP_CONNECTION_STATE_CLOSED -> NULL); it will be flagged for connection retry.
Info: Preparing transport for re-connection
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/iothub_client/src/iothubtransportamqp_methods.c Func:iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while not subscribed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_encode_frame Line:2048 Connection not open
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:send_detach Line:235 Sending detach frame failed in session send
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:link_detach Line:1256 Sending detach frame failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/message_sender.c Func:messagesender_close Line:816 Detaching link failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_encode_frame Line:2048 Connection not open
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:send_detach Line:235 Sending detach frame failed in session send
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:link_detach Line:1256 Sending detach frame failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_encode_frame Line:2048 Connection not open
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:send_detach Line:235 Sending detach frame failed in session send
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:link_detach Line:1256 Sending detach frame failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/message_receiver.c Func:messagereceiver_close Line:401 link detach failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_telemetry_messenger.c Func:destroy_message_receiver Line:518 Failed closing the AMQP message receiver (this failure will be ignored).
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_encode_frame Line:2048 Connection not open
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:send_detach Line:235 Sending detach frame failed in session send
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:link_detach Line:1256 Sending detach frame failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_encode_frame Line:2048 Connection not open
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:send_detach Line:235 Sending detach frame failed in session send
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:link_detach Line:1256 Sending detach frame failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/message_sender.c Func:messagesender_close Line:816 Detaching link failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_encode_frame Line:2048 Connection not open
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:send_detach Line:235 Sending detach frame failed in session send
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:link_detach Line:1256 Sending detach frame failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_encode_frame Line:2048 Connection not open
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:send_detach Line:235 Sending detach frame failed in session send
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:link_detach Line:1256 Sending detach frame failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/message_receiver.c Func:messagereceiver_close Line:401 link detach failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_messenger.c Func:destroy_message_receiver Line:693 Failed closing the AMQP message receiver (this failure will be ignored).
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_encode_frame Line:2048 Connection not open
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:send_detach Line:235 Sending detach frame failed in session send
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:link_detach Line:1256 Sending detach frame failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_encode_frame Line:2048 Connection not open
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:send_detach Line:235 Sending detach frame failed in session send
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:link_detach Line:1256 Sending detach frame failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/message_sender.c Func:messagesender_close Line:816 Detaching link failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_connection.c Func:on_cbs_error Line:160 CBS Error occured
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/amqp_management.c Func:amqp_management_close Line:1041 messagesender_close failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_encode_frame Line:2048 Connection not open
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:send_detach Line:235 Sending detach frame failed in session send
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:link_detach Line:1256 Sending detach frame failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/message_receiver.c Func:messagereceiver_close Line:401 link detach failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/amqp_management.c Func:amqp_management_close Line:1048 messagereceiver_close failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_encode_frame Line:2048 Connection not open
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:send_detach Line:235 Sending detach frame failed in session send
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:link_detach Line:1256 Sending detach frame failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_encode_frame Line:2048 Connection not open
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:send_detach Line:235 Sending detach frame failed in session send
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/link.c Func:link_detach Line:1256 Sending detach frame failed
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_encode_frame Line:2048 Connection not open
-> [CLOSE]* {}
Info: Failed DNS lookup for ???.azure-devices.net: -3
Error: Time:Tue Dec  3 15:22:06 2019 File:/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:initiate_socket_connection Line:303 DNS revolve failed
Error: Time:Tue Dec  3 15:22:06 2019 File:/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:924 Failure: sending socket failed. errno=32 (Broken pipe).
Error: Time:Tue Dec  3 15:22:06 2019 File:/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:write_outgoing_bytes Line:641 Error in xio_send.
Error: Time:Tue Dec  3 15:22:06 2019 File:/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:685 Error in write_outgoing_bytes.
Error: Time:Tue Dec  3 15:22:06 2019 File:/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:1049 Socketio_Failure: Receiving data from endpoint: errno=107.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Tue Dec  3 15:26:01 2019 File:/azure-iot-sdk-c/uamqp/src/saslclientio.c Func:saslclientio_send_async Line:1181 send called while not open
Error: Time:Tue Dec  3 15:26:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:on_bytes_encoded Line:268 Cannot send encoded bytes
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Tue Dec  3 15:26:01 2019 File:/azure-iot-sdk-c/uamqp/src/amqp_management.c Func:amqp_management_close Line:1020 AMQP management instance not open
Error: Time:Tue Dec  3 15:26:01 2019 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_connection.c Func:on_cbs_open_complete Line:152 CBS open failed
Error: Time:Tue Dec  3 15:26:01 2019 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:on_amqp_connection_state_changed Line:778 Transport received an ERROR from the amqp_connection (state changed AMQP_CONNECTION_STATE_ERROR -> NULL); it will be flagged for connection retry.
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
Info: Preparing transport for re-connection
Error: Time:Tue Dec  3 15:26:01 2019 File:/azure-iot-sdk-c/iothub_client/src/iothubtransportamqp_methods.c Func:iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while not subscribed
Error: Time:Tue Dec  3 15:26:01 2019 File:/azure-iot-sdk-c/uamqp/src/saslclientio.c Func:saslclientio_send_async Line:1181 send called while not open
Error: Time:Tue Dec  3 15:26:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:on_bytes_encoded Line:268 Cannot send encoded bytes
Error: Time:Tue Dec  3 15:26:01 2019 File:/azure-iot-sdk-c/uamqp/src/saslclientio.c Func:saslclientio_close_async Line:1130 saslclientio_close called while not open
Error: Time:Tue Dec  3 15:26:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:on_bytes_encoded Line:272 xio_close failed
-> [CLOSE]* {}
Error: Time:Tue Dec  3 15:26:01 2019 File:/azure-iot-sdk-c/uamqp/src/saslclientio.c Func:saslclientio_close_async Line:1130 saslclientio_close called while not open
Error: Time:Tue Dec  3 15:26:01 2019 File:/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_close Line:1437 xio_close failed
Info: Failed DNS lookup for ???.azure-devices.net: -3
Error: Time:Tue Dec  3 15:26:06 2019 File:/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:

**Comment by anhashia** [comment]
Hi @mlilien 

I tested with **latest** available C SDK master and simulated the connection loss scenario.  I used retry interval of **30** seconds to mimic your scenario.

I am **not** able to reproduce the issue on my setup

Copying relevant log snippet only which shows **re-connection** attempt  timestamp.

**My log**
There is retry happening every **30 seconds**

`
Info: Preparing transport for re-connection
Error: Time:Fri Dec 13 18:38:25 2019 File:C:\works\release8\azure-iot-sdk-c\iothub_client\src\iothubtransportamqp_methods.c Func:_iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while not subscribed
Info: Preparing transport for re-connection
Error: Time:Fri Dec 13 18:38:55 2019 File:C:\works\release8\azure-iot-sdk-c\iothub_client\src\iothubtransportamqp_methods.c Func:_iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while not subscribed
Info: Preparing transport for re-connection
Error: Time:Fri Dec 13 18:39:25 2019 File:C:\works\release8\azure-iot-sdk-c\iothub_client\src\iothubtransportamqp_methods.c Func:_iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while not subscribed
Info: Preparing transport for re-connection
Error: Time:Fri Dec 13 18:39:55 2019 File:C:\works\release8\azure-iot-sdk-c\iothub_client\src\iothubtransportamqp_methods.c Func:_iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while not subscribed
`


**Your log**
In your case retry is happening at **4 minute** interval as you have mentioned. That doesn't  look right. 
``
Info: Preparing transport for re-connection
Error: Time:Tue Dec  3 15:22:01 2019 File:/azure-iot-sdk-c/iothub_client/src/iothubtransportamqp_methods.c Func:iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while not subscribed
Info: Preparing transport for re-connection
Error: Time:Tue Dec  3 15:26:01 2019 File:/azure-iot-sdk-c/iothub_client/src/iothubtransportamqp_methods.c Func:iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while not subscribed
``

So it is  **odd**

**Question** : How did you simulate connection loss ?
Something you can try to see if helps.  **Test with latest master**

**Comment by mlilien** [comment]
Hi @anhashia,

I simulated connection loss by stopping the networkmanagers gsm connection. I'm connected via ethernet and ethernet has no connection to wan.
I'll try 1.3.7.

**Comment by mlilien** [comment]
I can reproduce the issue with 1.3.7.

This is how I build the azure-sdk:

git clone -b 1.3.7 https://github.com/Azure/azure-iot-sdk-c.git \
    && cd azure-iot-sdk-c \
    && git submodule update --init

CMAKE_C_FLAGS="-O3 -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -funsafe-math-optimizations"

cd cmake \
    && cmake -DCMAKE_INSTALL_PREFIX=/usr -DcompileOption_C="${CMAKE_C_FLAGS}" -Duse_prov_client:BOOL=ON -Dhsm_type_sastoken:BOOL=ON -Duse_amqp:BOOL=ON -DBUILD_TESTING:BOOL=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo .. \

**Comment by anhashia** [comment]
Hi @mlilien 
Thanks for the update !

It is odd that in your case retry interval of 4 minutes is being used.

Below are code locations that can help to debug

https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothub_client_retry_control.c#L164

Default a is **5 seconds** . In your case it will be 30 seconds (user set)

https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothub_client_retry_control.c#L137

``
else if (get_difftime(current_time, retry_control->last_retry_time) < retry_control->current_wait_time_in_secs)
``

- This would rely on platform clock for time. I assume there are **no** issues around reading from the underlying clock for time..

The issue looks specific to your setup and needs to be debugged further. 

Things to check at your end for debugging purposes.

1.) Test with the **sample** application as it is
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c

I am wondering if in your case there is some issue with  IoTHubDeviceClient_LL_DoWork(device_ll_handle) call in your sample application
This need to be called repeatedly as shown in the sample

2.) 
Don't set

`` 
IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_RETRY_INTERVAL_SEC, &_interval))
``
And see if it makes different in the outcome

3.) If you **don't** set any retry policy and just go with the default, what are the test results in your case ? Does default work or does default also has an issue ?

**Comment by anhashia** [comment]
Tested also on **Raspberry Pi 3**. OS  Raspian Stretch. 

- No local reproduction. Reconnect happens every **30 seconds**. Log snippet is below

```````
Info: Preparing transport for re-connection
Error: Time:Tue Jan 28 01:28:04 2020 File:/home/pi/works/azure-iot-sdk-c/iothub_client/src/iothubtransportamqp_methods.c Func:iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while no                                   

Info: Preparing transport for re-connection
Error: Time:Tue Jan 28 01:28:34 2020 File:/home/pi/works/azure-iot-sdk-c/iothub_client/src/iothubtransportamqp_methods.c Func:iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while not subscribed

Info: Preparing transport for re-connection
Error: Time:Tue Jan 28 01:29:04 2020 File:/home/pi/works/azure-iot-sdk-c/iothub_client/src/iothubtransportamqp_methods.c Func:iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while not subscribed
Sending message 767 to IoTHub
````````

**Comment by mlilien** [comment]
Hi, meanwhile we switched to the LTS branch. There the reconnect timeframe is not configurable and happens most of the time after 5 secs, sometimes longer (~4 mins as well). 

to 1) I didn't have time to debug with the sample you mentioned. 
We don't use the LL api, so we don't call IoTHubDeviceClient_LL_DoWork ourselves.

to 2) The default retry policy (IOTHUB_CLIENT_RETRY_EXPONENTIAL_BACKOFF_WITH_JITTER ) is not what we want.

**Comment by az-iot-builder-01** [comment]
@ewertons, @mlilien, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by mlilien** [comment]
It seems to make a difference if name resolution works, or not.

My test scenario above was setting the device into airplaine mode. In this case name resolution does not work. In this case reconnection attempts are in interval of 4 minutes instead of 30sec.

If I use another test scenario where I remove the default gateway but still get correct name resolution from dns the device attempts to reconnect every 30secs.

**Comment by anhashia** [comment]
@mlilien : okay.. Thanks for update around test results  !

**Comment by ewertons** [comment]
Hi @mlilien ,

sorry for the long delay here... Coming back to this issue, I re-read your description and would like to clarify a few things.

There are two aspects of the way the SDK handles reconnections: 1) how it detects that a reconnection is necessary, 2) the reconnection attempts themselves.

For 2) we have what we call the retry policies. These policies only affect the frequency with which the SDK attempts to reconnect in case of successive failed attempts to connect. For example, when you set the retry policy to RETRY_INTERVAL with OPTION_RETRY_INTERVAL_SEC equals 30 seconds, it means that the SDK, **once it detects that a reconnection is needed**, will attempt to reconnect right away, then again in 30 seconds if the first attempt fails, then again in 30 seconds if it fails again and so on.

Now comes the first aspect of reconnection, item 1) above, which is how the SDK detects that a connection is faulty and must kick the reconnection attempts. The SDK has 2 mechanisms for detecting faulty connections: a) through callbacks originated from the OS socket API or TLS informing that an error occurred sending or receiving data, and b) through message timeouts.

In the case of a), the SDK will know right away that there is an issue (example, a ECONNRESET returned from send() in the socket layer) and will start the reconnection procedure immediately.

However there are platforms that do not return failures right away from send() and recv() calls, so the SDK must find other ways to safeguard (otherwise it would get stuck thinking the network is fine, but the OS never notifies the SDK of any errors. That is where we have b), message timeouts. With the AMQP transport, it has a KEEP-ALIVE feature, where it by default sends one keep-alive every 2 minutes to the Hub, and the Hub responds back with another keep-alive. If the AMQP transport does not get a response from the Azure IoT Hub in twice that frequency (4 minutes), it assumes the connection is failing, then triggers errors callbacks that result in the SDK starting its reconnection process.

In your case, you are experiencing the scenario b) above.
I would assume for now that there is nothing related to DNS-resolution.

As a workaround, we do have an option for you to control the timeout for the keep-alive pings (which are by default every 4 minutes). If you want to test it, try setting the keep-alive timeout with:

```c
size_t keep_alive_interval_in_secs = 30;
IoTHubClient_SetOption( _iotHubClientHandle, OPTION_SERVICE_SIDE_KEEP_ALIVE_FREQ_SECS, &keep_alive_interval_in_secs);
```

Yes, the option is called OPTION_SERVICE_SIDE_KEEP_ALIVE_FREQ_SECS despite controlling a **timeout**.

Please try that and see if you achieve the functionality you are looking for.
And if you want more details, here is a [documentation](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/connection_and_messaging_reliability.md#current-configuration-options) for you.

**Comment by mlilien** [comment]
Hi @evertons,

thank you. I don't work on the project, which triggered this question, anymore.
