### ISSUE TITLE
How to create a fake Azure endpoint that uses MQTT over web-sockets for internal testing?

### ISSUE THREAD

**Issue by Ozaq** [Azure/azure-iot-sdk-c#1350]
Hello,

I am trying to create a Fake Azure endpoint to test my application w.o. connecting to the real Azure cloud. Using plain MQTT and a Mosquito MQTT server this has been easy. The problems start when using MQTT over web-sockets. In this case I also used a mosquito server to fake the azure endpoint but configured mosquito to use web-sockets.

In this scenario the mosquito server expects a `GET /mqtt ..` but the Azure SDK sends `GET /$iothub/websocket ... `, this resource is unknown to mosquito and hence ignored. 

I managed to patch mosquito to also accept `GET /$iothub/websocket ... ` but as soon as I publish a value from the azure-sdk to my patched mosquito I receive an underlying IO error on the azure-sdk side. So I guess my patch is bogus or there are other things in how mqtt over websocksts from azure c sdk differs from the protocol implemented by mosquito.

So with that introduction: How can I fake an azure endpoint with MQTT over web-sockets? This is important for our CI/CD pipeline because we do not want to initiate sending data to external sources. (and then get them back for validation)

Surely there must be a way to test w.o. cloud connectivity that also includes web-sockets, right?

**Comment by ewertons** [comment]
Hi @Ozaq ,
we understand what you are attempting to achieve, however there are a few technical details you should take into consideration.
The Azure IoT Hub is not a full MQTT broker.
So attempting to simulate an Azure IoT Hub with any third-party library will probably diverge from the actual functionality of a real Azure IoT Hub.

We recommend you use a free basic tier Azure IoT Hub for your software development, that will guarantee your application can properly communicate with the Azure cloud.

**Comment by Ozaq** [comment]
Thanks @ewertons for the reply, very much appreciated. I was afraid that the answer was along those lines :/ 
Creating a few tests that use a free tier instance is something we are working on but we wanted to create a larger set of end-to-end testcases that run many times a day per developer and ideally support fault-injection on the endpoint side (timeouts, slow responses)

Can you point out where the Protocol diverges? E.g. hint where too look at specifically in the SDK code?

**Comment by ewertons** [comment]
@Ozaq , yes we understand that might block you on your intended plans, we apologize for that.
For details about how the Azure IoT Hub MQTT communication works, please check [this documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support). If it still does not have the information you need, please leave a feedback on the article (see how on the bottom of the page). The feedback is filed as an issue to the appropriate team.

**Comment by ewertons** [comment]
We will close this issue for now, but please feel free to reopen it if you would like to follow up on the topic.
Thanks for your question.
Azure IoT SDKs Team

**Comment by az-iot-builder-01** [comment]
@ewertons, @Ozaq, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
