### ISSUE TITLE
IoT Hub Upload to Blob: Upload to specific container instead of device name 

### ISSUE THREAD

**Issue by jubueche** [Azure/azure-iot-sdk-c#1352]
I noticed that the function ```IoTHubDeviceClient_LL_UploadMultipleBlocksToBlob``` uploads the specified file to ```device_name/file_name.txt```. Now I want to upload to a different container, like this:
```my_container/file_name.txt```. If I add ```container/``` to the file name, simply a new subfolder is created.
I was wondering if there is a way. Or can one disable that the files are directly uploaded to a folder specified by the device name?

**Comment by ewertons** [comment]
Hi @jubueche ,
good question. 

Unfortunately the way upload to blob is implemented in Azure IoT these paths are fixed.

These are the places in the code that show the fixed paths:

Azure IoT Hub dictates the container name:
https://github.com/Azure/azure-iot-sdk-c/blob/2019-11-08/iothub_client/src/iothub_client_ll_uploadtoblob.c#L214

The SDK code defines the file path:
https://github.com/Azure/azure-iot-sdk-c/blob/2019-11-08/iothub_client/src/iothub_client_ll_uploadtoblob.c#L341

**Comment by jubueche** [comment]
Ok I guess we will find another solution to that problem.

**Comment by az-iot-builder-01** [comment]
@ewertons, @jubueche, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
