### ISSUE TITLE
Add doxygen documentation to headers for enums

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1354]
Once we merge #1342, we'll be using proper C enums which will play nicely with doxygen.  We won't be doing documentation for this PR to avoid confusing the issues.

Once this change goes in, we should actually document these with doxygen.

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
