### ISSUE TITLE
Hostname validation of IoT Hub certificate

### ISSUE THREAD

**Issue by becz** [Azure/azure-iot-sdk-c#1356]
Hello,

this is a follow up  question to issue #943. Unfortunately I can not reopen the question, therfore I create a new one.

@ewertons describes how to use the `SSL_CTX_set_cert_verify_callback` to implement custom verification routine .  Thank you for this insight!

I am still wondering how to validate the hostname of the Azure IoT Hub, even with implementing custom verification routine, as Azure IoT Hub presents an certificate with wildcard CN (*.azure-devices.net)?

![handshake](https://user-images.githubusercontent.com/13221101/70127997-6a18fe00-167c-11ea-8141-fe4df4da5f98.png)

**Comment by ewertons** [comment]
Hi @becz ,
are you using directly the client from azure-iot-sdk-c?
If you are, all the validation for the Azure IoT Hub certificate is done automatically.
Indeed the Azure IoT Hub certificate does not contain the IoT Hub name. 

If you are not using the azure-iot-sdk-c client and are connecting to your hub through other means, this would be a question directly to the team responsible for the Azure IoT Hubs. If that is the case, we can guide you to convey your question to the proper channel.

**Comment by jspaith** [comment]
@becz - since this thread has been quiet for a while, I'm closing it out.  As before though with #943 and this issue, if you have followups please open a new GitHub issue and also please address @ewertons questions.  Thanks

**Comment by az-iot-builder-01** [comment]
@becz, @ewertons, @jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
