### ISSUE TITLE
device streams: websocket server cert verify fails when using bundled certs.h

### ISSUE THREAD

**Issue by larsonmpdx** [Azure/azure-iot-sdk-c#1358]
I have an embedded linux device that ships with an openssl that's missing certs.  I bundle this project's certs.h as seen in some examples and this works fine for regular azure iot operations.  It fails to verify the server's cert when starting a device streams connection.

The same code works fine on an embedded device that has openssl with the normal certs, and in a linux VM.

see this example for how the bundled certs.h is specified:
https://github.com/Azure/azure-iot-sdk-c/blob/DeviceStreaming/iothub_client/samples/iothub_client_c2d_streaming_proxy_sample/iothub_client_c2d_streaming_proxy_sample.c

I think maybe the bundling setting is not being applied to the device streams websocket connection, or it doesn't include the cert needed.  I can see with strace that openssl tries to load its own certs.pem at the time I try to start the connection

**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

an embedded linux device with openssh that's missing any of its own certs

**SDK Version (Please Give Commit SHA if Manually Compiling)**

branch DeviceStreaming Oct 24

**Protocol**

MQTT + devicestreams

**Describe the Bug**

the device works fine but when I initiate a device streams connection from a PC, the iot device can't start and gives this message:

```
Error: Time:Wed Dec  4 23:45:12 2019 File:/home/user/third_party/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:673 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Client connected to the streaming gateway WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
on_ws_open_complete() error

**Comment by ewertons** [comment]
Hi @larsonmpdx ,

Notice that nowhere in that code the trusted certs are set on the TLS instance created for the communication with the Azure IoT Streaming Gateway. So if a platform does not have a cert store with the certs installed it would be expected to see a failure there.

Could you verify if this resolves the issue for you?

Add the following before the call to `uws_client_open_async`:

```c
uws_client_set_option(result, OPTION_TRUSTED_CERT, certificates);
```

**Comment by larsonmpdx** [comment]
that option worked, thank you

**Comment by az-iot-builder-01** [comment]
@ewertons, @larsonmpdx, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
