### ISSUE TITLE
Duplicate DPS Registration IDs with TPM?

### ISSUE THREAD

**Issue by truschival** [Azure/azure-iot-sdk-c#1359]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
-    Target Linux 4.14.115-rt
-    Azure IoT SDK-C Release 2019-03.18
-    Cross Compiled for arm-linux-gnueabihf
-    gcc version 7.2.1 20171011 (Linaro GCC 7.2-2017.11)
-    Openssl 1.1.1b

**TPM:**
- Infineon Optiga SLB9670  (I will check the exact part number)
```
tpm2_getcap -c properties-fixed -Tdevice
WARN: More data to be queried: capability: 0x6, property: 0x100

TPM_PT_FAMILY_INDICATOR:
  as UINT32:                0x08322e3000
  as string:                "2.0"
TPM_PT_LEVEL:               0
TPM_PT_REVISION:            1.16
TPM_PT_DAY_OF_YEAR:         0x000000d1
TPM_PT_YEAR:                0x000007df
TPM_PT_MANUFACTURER:        0x49465800
TPM_PT_VENDOR_STRING_1:
  as UINT32:                0x534c4239
  as string:                "SLB9"
TPM_PT_VENDOR_STRING_2:
  as UINT32:                0x36373000
  as string:                "670"
```

**Protocol**
DPS authentication using TPM individual enrollments.

**Description**

I don't know how _this is even possible with TPM_ but we have duplicate Registration IDs and Endorsement Keys for entirely different devices.
In total we have 6 pairs of devices in the database that share a EK and RegID. I double checked if during production there was an error/retry. None of the devices that share a EK have been produced adjacent one right after the other. The upload is done by each device not from the production system. The production system does not transmit any EK or RegID to the device it just requests the device to upload the data. 

I read [TPM attestation](https://docs.microsoft.com/de-de/azure/iot-dps/concepts-tpm-attestation) and as far as I understood the procedure involves taking ownership and using the SRK (Storage Root Key) . However what I observed using ```tpm2_tools``` is that the TPMs are not in owned state after the procedure (and never have been but so far I didn't care since everything from DPS provisioning to communication with iot-hub worked fine)

Below is the infromation of a non-duplicate device that works just fine with DPS. 
```
cpx-iot79-developer ~$ tpm2_getcap -c properties-variable -Tdevice
TPM_PT_PERSISTENT:
  ownerAuthSet:              clear
  endorsementAuthSet:        clear
  lockoutAuthSet:            clear
  reserved1:                 clear
  disableClear:              clear
  inLockout:                 clear
  tpmGeneratedEPS:           clear
  reserved2:                 clear
TPM_PT_STARTUP_CLEAR:
  phEnable:                  set
  shEnable:                  set
  ehEnable:                  set
  phEnableNV:                set
  reserved1:                 clear
  orderly:                   clear
TPM_PT_HR_NV_INDEX:          0x00000002
TPM_PT_HR_LOADED:            0x00000000
TPM_PT_HR_LOADED_AVAIL:      0x00000003
TPM_PT_HR_ACTIVE:            0x00000000
TPM_PT_HR_ACTIVE_AVAIL:      0x00000040
TPM_PT_HR_TRANSIENT_AVAIL:   0x00000003
TPM_PT_HR_PERSISTENT:        0x00000003
TPM_PT_HR_PERSISTENT_AVAIL:  0x0000000f
TPM_PT_NV_COUNTERS:          0x00000000
TPM_PT_NV_COUNTERS_AVAIL:    0x0000000d
TPM_PT_ALGORITHM_SET:        0x00000000
TPM_PT_LOADED_CURVES:        0x00000002
TPM_PT_LOCKOUT_COUNTER:      0x0000001e
TPM_PT_MAX_AUTH_FAIL:        0x00000020
TPM_PT_LOCKOUT_INTERVAL:     0x00001c20
TPM_PT_LOCKOUT_RECOVERY:     0x00015180
TPM_PT_AUDIT_COUNTER_0:      0x00000000
TPM_PT_AUDIT_COUNTER_1:      0x00000000

```

The sequence to get the EK and RegID looks more less like this (not including error handling and retries):
```
platform_init();
prov_dev_security_init(SECURE_DEVICE_TYPE_TPM);
security_handle = prov_auth_create();
BUFFER_HANDLE endorsement_key = prov_auth_get_endorsement_key(security_handle);
encoded_ek = Azure_Base64_Encode(endorsement_key)
char* registration_id = prov_auth_get_registration_id(security_handle);
```

**Comment by truschival** [comment]
False alarm - it is a database error.

**Comment by az-iot-builder-01** [comment]
@truschival, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
