### ISSUE TITLE
SDK sample failed to compile with the newest SDK version

### ISSUE THREAD

**Issue by yuwzho** [Azure/azure-iot-sdk-c#136]
- **OS and version used:** <VERSION> 
Raspberry Pi

- **SDK version used:** <VERSION> 
The newest version. Installed as [this doc](https://github.com/Azure/azure-iot-sdk-c/blob/14dfffcc5f1e3fc707d51f6a4987cbcaf71ccfb0/doc/ubuntu_apt-get_sample_setup.md)  says

# Description of the issue:

When compile the device side sample code in SDK, it is failed to compile it. 
Break since [this commit](https://github.com/Azure/azure-iot-sdk-c/blob/1afc32528367f9e9411a78c1e85f8a6c0f34724f/iothub_client/src/iothub_client_ll.c). 

# Code sample exhibiting the issue:

[Sample code](https://github.com/Azure/azure-iot-sdk-c/blob/1f2c3f2d368e6d9044d342c988e049d8b2da2e40/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c) provided by SDK

# Console log of the issue:

``` bash
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothub_client_ll.c.o): In function `make_product_info':
(.text+0xa): undefined reference to `platform_get_platform_info'
collect2: error: ld returned 1 exit statu
```

**Comment by jebrando** [comment]
We believe this issue is fixed in the latest SDK.  Please let us know if you believe otherwise.
