### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by aneesalappatt** [Azure/azure-iot-sdk-c#1360]
Hi,

Iam using the azure-iot-sdk-c master source code and I used the iot_conveninece_sample.c code to push the data in to azure iot hub using MQTT protocol. The data are sending to cloud every 30 seconds and every 1 minutes we send two messages. The last two weeks are working fine and after the two weeks the cloud data shows the duplication randomly. I used the QOS level 1 and got the confirmations. I used the log all the messages before sending to cloud and also check the confirmations ok with message id. So please let me know the duplication cause for this? Last two weeks the edge device is working fine without any duplications of data. 

Regards
Anees

**Comment by ewertons** [comment]
Hi @aneesalappatt ,
we will verify our long-haul tests to confirm if we are getting any duplication.
However, to help get more info about your scenario, could you share the following?
- Are you sending telemetry messages (using the *_SendAsync function)?
- how are you verifying that the messages are duplicated?
- When you say "I used the QOS level 1 and got the confirmations.", does it mean you 
- Did you explicitly set any retry policy?
- Is the connection with IoT Hub showing reconnections? You can check the logs to see if there is any co-relation between reconnections and duplication.

**Comment by aneesalappatt** [comment]
Hi ,

Please see my reply inline below


   - Are you sending telemetry messages (using the *_SendAsync function)?:
   - Ans:- Yes we are sending using "IoTHubDeviceClient_SendEventAsync".
   Its telemetry.
   azure-iot-sdk-c/iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample.c


   - how are you verifying that the messages are duplicated? :
   - Ans:- We have cloud development team. they have some graphical
   representation which shows the data being received in the cloud. When they
   cross check the data from graph, they got duplication.


   - When you say "I used the QOS level 1 and got the confirmations.", does
   it mean you :
   - Ans:-we get confirmation from server like "confirmation callback
   received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_OK"



   - Did you explicitly set any retry policy? :
   - Ans:-No
   -
   - Is the connection with IoT Hub showing reconnections? You can check
   the logs to see if there is any co-relation between reconnections and
   duplication.
   - Ans:-No. When we are running the same connection string
   simultaneously , then it will show reconnection message.

Regards
Anees

**Comment by ewertons** [comment]
Hi @aneesalappatt ,

We apologize for the long delay, but we were assigned to work on new code development and that affected our github response time.

The next step would be to ask client logs to verify if you are getting messages resent.

Could you [enable verbose logging](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample.c#L271) in the C SDK, grab logs for a session where you see the duplication happening, and share them here with us?

**Comment by ewertons** [comment]
@aneesalappatt , we could not validate the loss of messages through the tests we run over our code base.
If you would like to follow up, please provide the verbose logs requested. Feel free to reopen the issue or file a new one to follow up.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@aneesalappatt, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
