### ISSUE TITLE
IoTHubClientCore_LL_* APIs are publicly documented and header file does not discourage use

### ISSUE THREAD

**Issue by drwill-ms** [Azure/azure-iot-sdk-c#1362]
There are lots of these APIs listed on docs.microsoft.com:

https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-client-core-ll-h
•	https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-client-core-ll-h/iothubclientcore-ll-setdevicemethodcallback
•	https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-client-core-ll-h/iothubclientcore-ll-setdevicemethodcallback-ex

I don't see anything in the [header file](https://github.com/Azure/azure-iot-sdk-c/blob/cf5aaf33e1202b0e87ce054c911e9b979a4cfc59/iothub_client/inc/iothub_client_core_ll.h) to discourage use.

From: John Spaith
The IoTHubClientCore* API’s should never be used directly.  You should be using IoTHubDeviceClient_(LL_)_* or else the module equivalent.

I could’ve sworn that we documented this – especially in the header file itself - but clearly it’s not.   Could you please open up a GitHub issue on this?  Ugh :

You’ll notice is the proper API set there’s only a IoTHubDeviceClient_LL_SetDeviceMethodCallback().  The _Ex_ function is a (poorly named) internal only thingy used between the convenience layer and the _LL_ if I’m remembering correctly, which is why it wasn’t into the device* side.

From: David R. Williamson
Can you point me to any good examples for IoTHubClientCore_LL_SetDeviceMethodCallback_Ex?

**Comment by ewertons** [comment]
@drwill-ms ,
you are absolutely correct. I am not sure what happened with the documentation we had, but we will follow up on this right away.
Thanks.

**Comment by ewertons** [comment]
Hi @drwill-ms ,
after reviewing the documentation we concluded that that particular header file documentation was not supposed to be published, since it is an internal header. 
It has since been removed from the public documentation.
Thanks for bringing this issue to our attention.
-Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@drwill-ms, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
