### ISSUE TITLE
Provision Device Client Errors with Simulated TPM SampleCode.

### ISSUE THREAD

**Issue by Garry-Anderson** [Azure/azure-iot-sdk-c#1363]
Support Request:

I am following the "_Quickstart: Provision a simulated TPM device using the Azure IoT C SDK_" from:  https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device.

All works well until step 7 of "simulate first boot sequence for the device".  The process seems to complete, but throws a couple of error messages that relate to a VOID value being passed in the "message" parameter after the first attempt works.

I have traced through the code with VS debugger, but I get lost easily because of the lack of comments in the code and I have no idea how this works or what it is supposed to do.

Here is the Debug Message that I have captured:

============ begin screen capture
Provisioning API Version: 1.3.6

Registering Device

Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
Error: Time:Fri Dec  6 15:22:38 2019 File:C:\azure-iot-sdk-c\uamqp\src\amqpvalue.c Func:_amqpvalue_get_inplace_described_value Line:7038 NULL value argument given
Error: Time:Fri Dec  6 15:22:38 2019 File:C:\azure-iot-sdk-c\provisioning_client\src\prov_transport_amqp_common.c Func:_get_retry_after_property Line:344 Failure getting application property description
Error: Time:Fri Dec  6 15:22:38 2019 File:C:\azure-iot-sdk-c\uamqp\src\amqpvalue.c Func:_amqpvalue_destroy Line:4849 NULL value

Registration Information received from service: aih-senz-iot-canadacentral-proto.azure-devices.net, deviceId: Test_Garry2
Press enter key to exit:

end screen capture ===============

According to the documentation () I am supposed to have no errors.

Can anybody help isolate the reason for these errors, or should I assume they do not matter (in which case they should be warnings, no ? )

Thanks,
Garry Anderson.

**Comment by ewertons** [comment]
Hi @Garry-Anderson , could you provide the details we usually request in the issue template?
What version of the c SDK are you using (release tag or commit id)?
What platform are you compiling to?
Thanks.

**Comment by Garry-Anderson** [comment]
Hi ewertons:

I will provide that information, as soon as I get back to work.  Sick at home with the flu.

BTW, where do I find this “Issue Template”?  I looked for it but could not find it.

Thanks,
Garry.

**Comment by ewertons** [comment]
@Garry-Anderson , I apologize for the misunderstanding; the template for "Technical Question" when you file an issue does not contain the same requirements as when you file a bug. 
Thanks for providing the information.

**Comment by ehsaeed** [comment]
@ewertons 
Any progress on this issue? 
I am also facing the same issue.

**Comment by Garry-Anderson** [comment]
For the moment, I have given up on Azure.
Garry.

**Comment by ehsaeed** [comment]
@ewertons 
Any workaround for this?
As the device does get registered but still these errors appear.

**Comment by ericwol-msft** [comment]
We recommend that you go with OpenSSL engine TPM usage. 

https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/devdoc/iothubclient_c_library.md#openssl-engine-examples
