### ISSUE TITLE
fatal error: umock_c/umock_c_prod.h: No such file or directory

### ISSUE THREAD

**Issue by abhipony** [Azure/azure-iot-sdk-c#1364]
OS version :
Distributor ID: RedHatEnterpriseServer
Description: Red Hat Enterprise Linux Server release 7.6 (Maipo)
Release: 7.6
Codename: Maipo

SDK Release: latest

**Description**:
I built  azure-iot-sdk-c inside a docker.
**My Dockerfile** :
FROM balenalib/beaglebone-black:buster                                       
COPY azure-iot-sdk-c /usr/src/app/azure-iot-sdk-c                            
WORKDIR /usr/src/app/azure-iot-sdk-c/build_all/linux                         
RUN apt-get -q update && apt-get install -yq --no-install-recommends git sudo
RUN ./setup.sh                                                               
RUN ./build.sh --no-logging                                                  
WORKDIR /usr/src/app/                                                        

After everything is built, I started using it in my application called pusher. I get the below error with the latest version of this library.

**[Build] main In file included from /usr/src/app/azure-iot-sdk-c/c-utility/inc/azure_c_shared_utility/platform.h:7:0,
[Build] main from src/pusher.cpp:8:
[Build] main /usr/src/app/azure-iot-sdk-c/c-utility/inc/azure_c_shared_utility/strings.h:7:34: fatal error: umock_c/umock_c_prod.h: No such file or directory
[Build] main #include "umock_c/umock_c_prod.h"
[Build] main ^
[Build] main compilation terminated.**

**The headers included my file are** :
#include "azure_c_shared_utility/platform.h
#include "azure_c_shared_utility/threadapi.
#include "iothub_client.h"
#include "iothubtransportmqtt_websockets.h"

**My makefile for the appplication**:
AZURE_SDK_PATH:=$(CURDIR)/azure-iot-sdk-c
CXXFLAGS += -I$(AZURE_SDK_PATH)/iothub_client/inc -I$(AZURE_SDK_PATH)/c-utility/inc -I/usr/include/azureiot -I/usr/include/azureiot/inc -I$(AZURE_SDK_PATH)/deps/parson -I .

binary/pusher: \
src/pusher.o \
parson.o
$(CXX) -o $@ $^ -L$(AZURE_SDK_PATH)/cmake/iotsdk_linux/c-utility -L$(AZURE_SDK_PATH)/cmake/iotsdk_linux/umqtt -L$(AZURE_SDK_PATH)/cmake/iotsdk_linux/iothub_client $(LDLIBS) -lm -liothub_client_mqtt_ws_transport -lumqtt -l:libiothub_client.a -lpthread -laziotsharedutil -lssl -lcrypto -lcurl

parson.o: $(AZURE_SDK_PATH)/deps/parson/parson.c $(AZURE_SDK_PATH)/deps/parson/parson.h
gcc -c $(AZURE_SDK_PATH)/deps/parson/parson.c -o "parson.o"

**I am currently working with an older version of this repo and I have to move to the latest version urgently. Please look into this issue and suggest a solution. Let me know if you have any doubts or queries.**

**Comment by danewalton** [comment]
Hi @abhipony 
If you are using the latest version of the sdk can you make sure to run
```bash
git submodule update --init --recursive
```
to make sure you have all the latest submodules. 

After that, make sure to have in your include path `-I$(AZURE_SDK_PATH)/deps/umock-c/inc`. That should include the necessary files that the compiler is complaining about. Let me know if that helps at all!

**Comment by scout208** [comment]
I'm having this same issue only on Windows with the latest SDK release.

**Comment by danewalton** [comment]
@scout208 how are you building the code? Is it a hand rolled make, cmake, etc

**Comment by scout208** [comment]
I'm using the Visual Studio integration with vcpkg and trying to build one of the samples

**Comment by scout208** [comment]
@danewalton I'm wondering is there a particular version of the azure-iot-sdk-c vcpkg that I need to have installed?

**Comment by danewalton** [comment]
are you using the latest version?

**Comment by scout208** [comment]
Yeah, I am. I really just tried to follow the instructions at https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#windows and https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/setting_up_vcpkg.md#setup-c-sdk-vcpkg-for-windows-development-environment and it doesn't work when I try to build the sample.

**Comment by abhipony** [comment]
@danewalton Hey, I was able to build it successfully using the latest version. I had to include -I$(AZURE_SDK_PATH)/deps/umock-c/inc and -I$(AZURE_SDK_PATH)/c-utility/deps/azure-macro-utils-c/inc to my path. Thanks for helping me out. :)

**Comment by danewalton** [comment]
@abhipony awesome good to hear!

@scout208 would you mind opening another issue with your problem so that we can track it separately? I'm going to go ahead and close this one.

**Comment by az-iot-builder-01** [comment]
@danewalton, @abhipony, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
