### ISSUE TITLE
401002 error didn't handle(or a specific callback) in the azure-iot-sdk-c when certificate expired

### ISSUE THREAD

**Issue by NOA-Vernon** [Azure/azure-iot-sdk-c#1367]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

NRF52840 + Cellular module
Cross Compiled on Win10 using SEGGER EMBEDDED STUDIO 4.18(arm-none-gcc )

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Provisioning API Version: 1.3.4
Iothub API Version: 1.3.4

**Protocol**

HTTP

**Describe the Bug**

If MQTT is unable to establish a connection, it will keep trying and once it succeeds queued messages will be sent to the Cloud. However, if for some reason we can't get past the initial connection phase, then SDK does not respect message timeouts. 

**[MCVE](https://stackoverflow.com/help/mcve)**
I want to test the certificate expired problem with the error code 401002 that reply from the Azure cloud when the device trying to DPS or connect to iothub with an expired certificate. However, the error code didn't handle the 401002 separately from the azure-iot-sdk-c, it only categorized the error code to else{}, see the https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/src/prov_device_ll_client.c#L670. How does the application know that the 401001 error code reply from Azure cloud separately?

**Console Logs**

Unsuccessful json encountered: {"errorCode":401002,"trackingId":"199b014e-4ecd-4dcc-a809-b9958ce67c8c","message":"Unauthorized","timestampUtc":"2019-12-11T03:17:54.6781386Z"}
error D:/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c: line 670
error D:/azure-iot-sdk-c/provisioning_client/src/prov_transport_http_client.c: line 941
error D:/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c: line 770

**Comment by ewertons** [comment]
Hi @NOA-Vernon ,

We apologize for the long delay, but we were assigned to work on new code development and that affected our github response time.

So looks like you actually have two questions on this issue.

1. If the client never connects, why messages do not timeout (and callback gets invoked to user)?
> That is unlikely; but we will verify it to make sure.

2. Why the provisioning client SDK considers that an error?
> Well, that is an authentication error, so the code seems correct to consider it a failure. It will do so if the json received does not have the expected fields to check registration state and operation id.  Although the error message is more generic than you would expect, the code is still doing the right thing. 

Also, you mention that the protocol is HTTP, but later in the description mention MQTT. Which one are you using?

**Comment by NOA-Vernon** [comment]
Hi @ewertons, 
I try to register the device and certificate against the DPS through MQTT, but no succeed, if register against DPS through HTTP, then it works. 
Also, I want to catch the 401002 error code for re-new the certificate if the certificate expired, are you intend to implement this function in the near future

**Comment by ewertons** [comment]
Hi @NOA-Vernon ,
despite the usefulness you properly explained, we do not plan to provide any further validation of certificates in the SDK itself for now.
Any verification of expiration of the certificate must be done by the calling application.

**Comment by ewertons** [comment]
One final update on this issue: we verified in the code and telemetry messages are inspected for time out on every situation, no matter if the client is disconnected or not.

When telemetry is sent the instance is saved in the `waitToSend` queue. This queue is shared between the iothub_client_core_ll and the transport layers. Once the transport PUBLISHES a telemetry, it removes the instance from the `waitToSend` queue and moves it to `telemetry_waitingForAck`. The first is controlled for time outs by the iothub_client_core_ll layer, and the second is controlled by the transport layer.

HTTP transport does not have a `pendingAck` queue, so no timeout is needed.
