### ISSUE TITLE
Azure IoT Hub DateTime API

### ISSUE THREAD

**Issue by snobu** [Azure/azure-iot-sdk-c#1368]
Is there API surface in Azure IoT Hub that i can query (HTTP/MQTT/AMQP) for current DateTime to set my devices to?

Related SO thread:
https://stackoverflow.com/questions/59289678/how-can-i-get-datetime-on-my-device-from-azure-iot-hub/59290025

**Comment by ewertons** [comment]
Hi @snobu ,
that capability is not present in the Azure IoT SDKs. Indeed it is a requirement for the SDKs to work properly to have the system already set with the correct current date and time.

If you would like to ask for that capability in the Azure IoT Hub, please submit your question [here](https://techcommunity.microsoft.com/t5/Azure-IoT/bd-p/Azure-IoT).

Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment]
@snobu, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
