### ISSUE TITLE
pnp Codegen v0.6.7 Description=Schema not found

### ISSUE THREAD

**Issue by uriel-kluk** [Azure/azure-iot-sdk-c#1370]
The codegen is not able to produce C stubs for semantic type: `Location`  and the `geopoint` schema

**Comment by uriel-kluk** [comment]
I moved this issue to the IoTPlugandPlay repo as it is not an SDK problem

**Comment by az-iot-builder-01** [comment]
@uriel-kluk, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
