### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by wlisac** [Azure/azure-iot-sdk-c#1371]
Hi there,

I'm looking to use the Azure IoT Device SDK in a Swift app. 

It looks like there is already [support for CocoaPods](https://cocoapods.org/pods/AzureIoTHubClient), but I'm wondering if you would consider adding support for [Swift Package Manager](https://github.com/apple/swift-package-manager), too?

Swift Package Manager (SPM) supports iOS, macOS, and watchOS like CocoaPods, but it also supports Linux.

Support for SPM could enable the Azure IoT SDK to be used in server-side Swift apps and in Swift IoT apps that run on Linux. 

It would also make the SDK easier to use in iOS, macOS, and watchOS targets now that SPM is directly integrated into Xcode 11.

SPM has some [documentation for creating C targets](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#creating-c-language-targets) that might be helpful.

Let me know if there is any additional information I can provide.

Best,
Will

**Comment by ewertons** [comment]
Hi @wlisac, 
thank you very much for your suggestion. 
We have evaluated the request and, unfortunately, we will not have a chance to add support for Swift package manager for now.
There are already options for packages for the systems you listed (cocoapods for iOS and vcpkg for Linux/Mac/Windows), so it would be somehow redundant, with the addition of extra code we would need to maintain, plus it would enlarge our release process. To best serve the community we find it better to continue investing in the code distribution systems we currently already support.
In any ways, thanks for recommendation.
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment]
@wlisac, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by wlisac** [comment]
@ewertons Thanks for the update. 

As SPM continues to become the de facto standard for integrating 3rd party libraries in Xcode (on all Apple platforms and on Linux), I hope this decision will be reconsidered in the future.

**Comment by ewertons** [comment]
@wlisac , for sure we are always watching the trends. 
If SPM becomes an option with stronger adoption than the current ones we certainly will reconsider it.

**Comment by johndelong** [comment]
Hello @ewertons. It's a little over a year later and SPM has continued to grow in popularity and functionality. Would it be possible to reconsider re-opening this ticket to gain this support. Right now this dependency is the only one (out of ~15 other dependencies that we pull in) that requires us to use cocoapods to install. All others we have been able to successfully implement and use with SPM.

**Comment by danewalton** [comment]
Hi all,

I would like to note that we now have a sample of our [Azure SDK for C](https://github.com/Azure/azure-sdk-for-c) wrapped in a Swift interface here:

https://github.com/Azure-Samples/azure-sdk-for-c-swift

It is available as a Swift package and you may find the demo for use [here](https://github.com/Azure-Samples/azure-sdk-for-c-swift/blob/main/Sources/demo/main.swift).

Notable feature capabilities are **Device Provisioning Service** and **X509 certificate authentication** (both of which weren't supported in the Cocoapods version referenced in this issues) using the native iOS TLS stack. This includes Trusted Store support for trusted CA Certs.

**Comment by wlisac** [comment]
@danewalton thanks for the update! I can see how the bring your own network stack approach can be very useful, but are there plans to have the C SDK provide a network stack as an option instead of having to depend on 3rd party providers?

**Comment by danewalton** [comment]
Good question. I have to say at this time we don't currently have plans for that. 

The bring-your-own networking approach may not be perfect but it does provide options in this case such as [CocoaMQTT](https://github.com/emqx/CocoaMQTT) and [MQTT-NIO](https://github.com/adam-fowler/mqtt-nio), both of which have support for WebSockets as well.

Just another note, we have another repo with a sample on how to use this library in an XCode project with an iOS user interface:

https://github.com/Azure-Samples/azure-sdk-for-c-ios
