### ISSUE TITLE
Version 1.3.7 Reports Version 1.3.6

### ISSUE THREAD

**Issue by ling0015** [Azure/azure-iot-sdk-c#1372]
Release 1.3.7 is tagged at db8d1bdf0afebfa98c6fb0562cc105b23f7e9b9e, however in that commit iothub_client/inc/iothub_client_version.h specifies a version of 1.3.6.

It seems that [601e0cb9](https://github.com/Azure/azure-iot-sdk-c/commit/601e0cb90130e3289365af55ef71844a6ea29e8d) should in fact be the release commit.

Also it appears that the CI pipeline was working before 601e0cb9 and is now failing on that commit, which only bumped version numbers. Can you clarify what is failing in the pipeline?

**Comment by danewalton** [comment]
thanks for letting us know. we are looking into getting those corrected.

**Comment by ewertons** [comment]
Hi @ling0015 , we had a small glitch in our release system, now that is fixed in the GitHub releases.
Tags 2019-12-11 and 1.3.7 are now correctly pointing to 509228d0641878a714b91771aae9c3990808079f

Thanks for your contribution!
Azure IoT SDKs Team

**Comment by az-iot-builder-01** [comment]
@ling0015, @danewalton, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
