### ISSUE TITLE
Auto URL encode/decode call not working

### ISSUE THREAD

**Issue by dangerousHobo** [Azure/azure-iot-sdk-c#1373]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Cross Compiled on Ubuntu 18.04 using GCC 6.4.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release LTS_07_2019_Ref01

**Protocol**

MQTT

**Describe the Bug**

Trying to enable automatic URL encode/decoding with MQTT but get an error.

```
tp_iothub_ll_handle = 
        IoTHubClient_LL_CreateFromConnectionString (
            tpszConnectionString,
            MQTT_Protocol );

bool urlEncodeOn = true;
(void) IoTHubClient_LL_SetOption(
            tp_iothub_ll_handle, 
            OPTION_AUTO_URL_ENCODE_DECODE, 
            &urlEncodeOn );
```

**Console Logs**

```
Error: Time:Fri Dec 13 14:46:07 2019 File:src/iothub_client_ll.c Func:IoTHubClient_LL_SetOption Line:1794 underlying transport failed, returned = IOTHUB_CLIENT_INVALID_ARG
```

**Comment by ewertons** [comment]
Hi @dangerousHobo ,

could you verify if you are indeed using the release you are mentioning, [LTS_07_2019_Ref01](https://github.com/Azure/azure-iot-sdk-c/tree/LTS_07_2019_Ref01)?

In LTS_07_2019_Ref01, if you check [iothub_client_ll.c](https://github.com/Azure/azure-iot-sdk-c/blob/LTS_07_2019_Ref01/iothub_client/src/iothub_client_ll.c) it does not have that trace (of line 1794 as mentioned in your description), which tells me you might be using a much older version of the SDK.

**Comment by dangerousHobo** [comment]
Hi @ewertons,

I see what you mean about no trace at line 1794. 
I've used buildroot to build the azure-iot-sdk-c package. The selected package-version is `azure-iot-sdk-c-LTS_07_2019_Ref01`
The `version.txt` file in the root of the directory says `1.3.4`.

**Comment by dangerousHobo** [comment]
I've found the issue, there are two versions of libumqtt.so on the board and the soft link didn't get properly updated. After fixing this I was able to set the option to auto encode the URL and all worked as expected.

**Comment by az-iot-builder-01** [comment]
@ewertons, @dangerousHobo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
