### ISSUE TITLE
Using MQTT how to set QoS to 0?

### ISSUE THREAD

**Issue by ellainec** [Azure/azure-iot-sdk-c#1376]
I tried looking through docs and I see that by default is 1 but I can't find how to change this setting. 

I'm currently calling IoTHubClient_LL_CreateFromConnectionString(connectionString, MQTT_PROTOCOL) and it works fine, but I want to put my BG96 on power save mode which means it will only be able to send and not receive. 

Is there anything like a SetOption for this?
Thanks!

**Comment by etcetc** [comment]
Am also interested in this.

**Comment by etcetc** [comment]
Looking through the code, in `publish_mqtt_telemetry_msg` it seems that the QOS is hardcoded to DELIVER_AT_LEAST_ONCE.  

```
static int publish_mqtt_telemetry_msg(PMQTTTRANSPORT_HANDLE_DATA transport_data, MQTT_MESSAGE_DETAILS_LIST* mqttMsgEntry, const unsigned char* payload, size_t len)
{
    int result;
    STRING_HANDLE msgTopic = addPropertiesTouMqttMessage(mqttMsgEntry->iotHubMessageEntry->messageHandle, STRING_c_str(transport_data->topic_MqttEvent), transport_data->auto_url_encode_decode);
    if (msgTopic == NULL)
    {
        LogError("Failed adding properties to mqtt message");
        result = __FAILURE__;
    }
    else
    {
        MQTT_MESSAGE_HANDLE mqttMsg = mqttmessage_create(mqttMsgEntry->packet_id, STRING_c_str(msgTopic), DELIVER_AT_LEAST_ONCE, payload, len);
        if (mqttMsg == NULL)
        {
            LogError("Failed creating mqtt message");
            result = __FAILURE__;
```

**Comment by dangerousHobo** [comment]
I'm also interested in this.
Looking through the `azure-umqtt-c` library it appears the standard MQTT modes are [defined](https://github.com/Azure/azure-umqtt-c/blob/e295afba33f9073a9b5ae8979b13781d5a1d7883/inc/azure_umqtt_c/mqttconst.h).

```
#define QOS_VALUE_VALUES \
    DELIVER_AT_MOST_ONCE, 0x00, \
    DELIVER_AT_LEAST_ONCE, 0x01, \
    DELIVER_EXACTLY_ONCE, 0x02, \
    DELIVER_FAILURE, 0x80

MU_DEFINE_ENUM_2(QOS_VALUE, QOS_VALUE_VALUES)
```

The documentation [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support) also states:

> IoT Hub does not support QoS 2 messages. If a device app publishes a message with QoS 2, IoT Hub closes the network connection.

So it the hard-coding to `DELIVER_AT_LEAST_ONCE` due to some limitation on the Hub side?

It would be nice if the documentation states either how to set the QoS or why the other QoS modes are not available.

**Comment by ewertons** [comment]
Hi @ellainec  and @dangerousHobo ,
as you have verified, the Azure IoT Hub is not a full MQTT broker, and the messaging features (telemetry, C2D events, direct methods, device twin) all have predefined QoS values and are expected to be sent as defined in the SDK.

Even uMQTT is developed with a very thin design, made to be used by the azure-iot-sdk-c SDK. By itself, it won't support all QoS levels.

We apologize for the long delay, but we were assigned to work on new code development and that affected our github response time.

We will close this issue, but if you would like it to be reopened and follow up on this matter, please post a comment requesting so.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@ellainec, @etcetc, @dangerousHobo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
