### ISSUE TITLE
please update the public preview branch with the segfault fix from #1275

### ISSUE THREAD

**Issue by larsonmpdx** [Azure/azure-iot-sdk-c#1377]
the same segfault affects the november public preview merge

see #1275

**Comment by ewertons** [comment]
Hi @larsonmpdx ,
public-preview branch will have a new update and release early next month.

**Comment by larsonmpdx** [comment]
any update?

**Comment by AshokPeddakotla-MSFT** [comment]
Please provide an update on this issue.

**Comment by ewertons** [comment]
Hi @larsonmpdx apologies for the delayed response.

Unfortunately we hadn't updated public-preview with those fixes yet. We will update you once that is scheduled.

**Comment by ewertons** [comment]
@larsonmpdx , our public-preview branch has just been updated with the latest bits from master.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@larsonmpdx, @AshokPeddakotla-MSFT, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
