### ISSUE TITLE
Getting segmentation faults while trying to send large number of messages 

### ISSUE THREAD

**Issue by abhipony** [Azure/azure-iot-sdk-c#1380]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
balena OS, Linux

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Latest

**Protocol**

MQTT

I have a program (pusher) which uses azure iot sdk c to send messages to cloud from device. When trying to send messages below 200, my program works just fine. But when I try to send large number of messages (for example 400) , **it starts throwing segmentation faults.** **Out of this 400 messages, it is successfully able to send just a couple of them (like 10 or 20)**. I have tried sending messages in batch of 50 and that works well, except when there are many devices trying to send messages at once. I know there is a throttle limit and I have upgraded my plan to S2. 

**Where is this segmentation fault coming from?
Is there a way to avoid this?**

This is one of the logs of my pusher application.
19.12.19 15:28:12 (+0530)  main  Total number of messages to be sent : 1705
19.12.19 15:28:12 (+0530)  main  Messages to be sent in this batch : 50
19.12.19 15:28:15 (+0530)  main  Messages acknowledged until now : 50
19.12.19 15:28:15 (+0530)  main  Messages to be sent in this batch : 50
19.12.19 15:28:18 (+0530)  main  Messages acknowledged until now : 100
19.12.19 15:28:18 (+0530)  main  Messages to be sent in this batch : 50
19.12.19 15:28:20 (+0530)  main  Messages acknowledged until now : 150
19.12.19 15:28:20 (+0530)  main  Messages to be sent in this batch : 50
19.12.19 15:28:22 (+0530)  main  Messages acknowledged until now : 200
19.12.19 15:28:22 (+0530)  main  Messages to be sent in this batch : 50
19.12.19 15:28:25 (+0530)  main  Messages acknowledged until now : 250
19.12.19 15:28:25 (+0530)  main  Messages to be sent in this batch : 50
19.12.19 15:28:28 (+0530)  main  Messages acknowledged until now : 300
19.12.19 15:28:28 (+0530)  main  Messages to be sent in this batch : 50
19.12.19 15:28:29 (+0530)  main  /usr/src/app/autobin.sh: line 29:  3324 Segmentation fault      (core dumped) ./pusher $file >> pusher_ack.json
19.12.19 15:28:29 (+0530)  main  Messages acknowledged until now : 303
19.12.19 15:28:29 (+0530)  main  Messages to be sent in this batch : 50
19.12.19 15:28:30 (+0530)  main  /usr/src/app/autobin.sh: line 29:  3330 Segmentation fault      (core dumped) ./pusher $file >> pusher_ack.json

Let me know if you want more info.

**Comment by abhipony** [comment]
It would be great help if someone picks this issue.

**Comment by ewertons** [comment]
Hi @abhipony, since you are running your application under linux, could you run it with valgring?
Valgrind will print all the memory AVs and help identify what the problem is.
Run valgrind with:
```shell
valgrind <your executable> --track-origins=yes --leak-check=full
```

**Comment by abhipony** [comment]
Thanks @ewertons . Valgrind indicated that the seg fault was coming from the logging library I was using. I have rectified it. This can be closed.

**Comment by jasmineymlo** [comment]
@abhipony Thanks for letting us know.

**Comment by az-iot-builder-01** [comment]
@abhipony, @ewertons, @jasmineymlo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
