### ISSUE TITLE
Pulling down submodules fails

### ISSUE THREAD

**Issue by dangerousHobo** [Azure/azure-iot-sdk-c#1388]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Cross Compiled on Ubuntu 18.04 using GCC 6.3.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2019_12_11

**Protocol**

MQTT

**Describe the Bug**

I've cloned the repo and tried to pull down the submodules with `git submodule update --init` and this returns (without error) without downloading any of the submodules, causing the build to fail.
I'm following the wiki steps here for setting up the build environment.
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#linux
What am I missing? Shouldn't this pull down the source for the submodules?

**Comment by az-iot-builder-01** [comment]
@dangerousHobo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
