### ISSUE TITLE
Release tarball fails to build due to missing dependencies

### ISSUE THREAD

**Issue by dangerousHobo** [Azure/azure-iot-sdk-c#1389]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Cross Compiled on Ubuntu 18.04 using GCC 6.3.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2019-12-11

**Protocol**

MQTT

**Describe the Bug**

I've downloaded the release tarball for 2019-12-11, extracted, and tried to build only to find that the submodules are missing. Running `git submodule update --init` does not work because there's no `.git` directory. Running `git init` and then the submodule command still doesn't work.
How can I build the release since it's missing the dependencies/submodules?
Is it possible to have these included in the release tarballs?

**Comment by ewertons** [comment]
Hi @dangerousHobo ,
that is by design.

To get the complete code with all the dependencies, either clone from git and run a `git submodule update --init --recursive`, or use [vcpkg](https://github.com/Azure/azure-iot-sdk-c/blob/2019-12-11/doc/setting_up_vcpkg.md) (suitable if building for Windows or Linux).

**Comment by dangerousHobo** [comment]
Hi @ewertons,

This makes packaging on Linux difficult. Most of these Linux build systems need a source tarball that they download and build. I've got it working by manually download each submodule, at the specified commit and unpacked each one at the necessary directory.
https://github.com/alpinelinux/aports/commit/1d2aa57717d54e74db0787fa44d83685c88b7079

**Comment by az-iot-builder-01** [comment]
@ewertons, @dangerousHobo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
