### ISSUE TITLE
SASToken Expired Exception was not getting thrown by the IoTHubClient_LL_CreateFromConnectionString or IoTHubClient_LL_SendEventAsync

### ISSUE THREAD

**Issue by scharish2** [Azure/azure-iot-sdk-c#139]
Hi Support,
We are  developing a Linux cloud connector for our business application. Unlike the Azure IoT Device Client provided by the .Net SDK , in case of using an expired SAS token to Open / Send events to IoTHub the azure c SDK is not throwing any exceptions and still trying to send the message which is eventually resulting in IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY of the packet.

OS and version used: Linux Ubuntu 14.04

SDK version used: azure-iot-sdk-c Dec 17 2016

# Description of the issue:

Azure c sdk is not throwing an exception when it uses an Expired SAS token to send an event to the Azure IoTHub. This was working perfect with the Microsoft .Net SDK i.e. DeviceClient . We were not able to manage the state of the application SAS Token without this exception handling.

# Code sample exhibiting the issue:
try {
		if (platform_init() != 0) {
			logger->info(
				"ERROR: failed initializing the platform.\r\n");
		}  		
		 if (this->protocol.compare("websocket") == 0) {
			if ((iotHubClientHandle = IoTHubClient_CreateFromConnectionString(
					connectionString.c_str(), AMQP_Protocol_over_WebSocketsTls))
					== NULL) {
				logger->info(
					"ERROR: iotHubClientHandle is NULL!\r\n");
				platform_deinit();
				initializationFail = true;
			}
}
catch (common_lib::GwException &e)
 {
//Here the exception is not get caught like the .Net SDK for an Expired SAS Token
			logger->info("CloudTransceiver::sendEventAsync() Error:: %s",
					e.getMessage().c_str());
}

**Comment by ewertons** [comment]
Hello @scharish2 ,
the .Net SDK and the C SDK are different in this aspect, there will be no exception coming from the C SDK.

If you get a more recent version of the C SDK (latest from master), you should be able to use the ConnectionStatusCallback API to track if the client got unauthenticated.

Could you give it a try?

**Comment by jkriba** [comment]
Hi ewertons,
  Thanks for the rapid response, 
We have faced similar issue with the Microsoft IoT  Device SDK for Java and have raised a request which has been accepted as a BUG by the Microsoft support.
https://github.com/Azure/azure-iot-sdk-java/issues/94

Hence we thought this was also an issue with respect to the C SDK. Kindly let us know your opinion, thanks

Regards
JK

**Comment by tameraw** [comment]
@scharish2 - As Ewerton stated, the C SDK will rely on the callback to let you know that you have an authentication issue.
Please try the latest SDK in master and register a ConnectionStatusCallback.
Let us know your findings.
