### ISSUE TITLE
Connection Status Callback gives "IOTHUB_CLIENT_CONNECTION_NO_NETWORK"

### ISSUE THREAD

**Issue by abdeldiaz** [Azure/azure-iot-sdk-c#1392]
- **OS:** Mentor Embedded Linux 2015.12  (v1.6.7.2)
- **Cross Compiled on**: gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf
- **SDK Version**: C SDK,  lastest version
- **Protocol**: MQTT

**Description of the issue:**

I am running a code similar to telemetry sample in a device using MQTT protocol. After successfully performing a bootstrap call to register the device and get the connection string, I try to connect and the callback returns IOTHUB_CLIENT_CONNECTION_NO_NETWORK error. I switch to AMQP after reading some issues here to get more information and I get the Log below. Any ideas? 

Thanks

**Console Logs:**

Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:364 Failure: select failure. socket: 42  error: 0
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:764 wait_for_connection failed
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/uamqp/src/saslclientio.c Func:saslclientio_open_async Line:1097 xio_open failed
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_open Line:1344 Opening the underlying IO failed
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/uamqp/src/link.c Func:link_attach Line:1154 Begin session failed
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/uamqp/src/message_receiver.c Func:messagereceiver_open Line:362 Link attach failed
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/uamqp/src/amqp_management.c Func:amqp_management_close Line:1020 AMQP management instance not open
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_connection.c Func:on_cbs_open_complete Line:152 CBS open failed
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:on_amqp_connection_state_changed Line:778 Transport received an ERROR from the amqp_connection (state changed AMQP_CONNECTION_STATE_CLOSED -> AMQP_CONNECTION_STATE_ERROR); it will be flagged for connection retry.
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/uamqp/src/amqp_management.c Func:amqp_management_open_async Line:981 Failed opening message receiver
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_connection.c Func:create_cbs_handle Line:279 Failed to open the connection with CBS.
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_connection.c Func:amqp_connection_create Line:422 amqp_connection_create failed (failed creating the CBS handle)
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:establish_amqp_connection Line:858 Failed establishing connection (failed to create the amqp_connection instance).
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_DoWork Line:1592 AMQP transport failed to establish connection with service.
Info: Preparing transport for re-connection
Error: Time:Thu Jan  9 11:42:34 2020 File:~/my_path/cross_compile/azure-iot-sdk-c/iothub_client/src/iothubtransportamqp_methods.c Func:iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while not subscribed

**Comment by abdeldiaz** [comment]
I found the solution. It was a drift in the device clock that invalidated the TLS certificates. I tested again and works. Thanks

**Comment by az-iot-builder-01** [comment]
@abdeldiaz, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by abdeldiaz** [comment]
After adding a function to sync device clock I still get same error. My test had a false positive with a hard-coded connection string to a different device. Any idea why I am getting such error?

**Comment by abdeldiaz** [comment]
As suggested in other issues I switch protocol to amqp to be more verbose and the issue is replicated. I could collect more information from the issue:
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/uamqp/src/saslclientio.c Func:saslclientio_open_async Line:1097 xio_open failed
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_open Line:1344 Opening the underlying IO failed
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/uamqp/src/link.c Func:link_attach Line:1154 Begin session failed
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/uamqp/src/message_receiver.c Func:messagereceiver_open Line:362 Link attach failed
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/uamqp/src/amqp_management.c Func:amqp_management_close Line:1020 AMQP management instance not open
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_connection.c Func:on_cbs_open_complete Line:152 CBS open failed
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:on_amqp_connection_state_changed Line:778 Transport received an ERROR from the amqp_connection (state changed AMQP_CONNECTION_STATE_CLOSED -> AMQP_CONNECTION_STATE_ERROR); it will be flagged for connection retry.
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/uamqp/src/amqp_management.c Func:amqp_management_open_async Line:981 Failed opening message receiver
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_connection.c Func:create_cbs_handle Line:279 Failed to open the connection with CBS.
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_connection.c Func:amqp_connection_create Line:422 amqp_connection_create failed (failed creating the CBS handle)
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:establish_amqp_connection Line:858 Failed establishing connection (failed to create the amqp_connection instance).
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_DoWork Line:1592 AMQP transport failed to establish connection with service.
Info: Preparing transport for re-connection
Error: Time:Tue Jan 28 19:43:37 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/iothub_client/src/iothubtransportamqp_methods.c Func:iothubtransportamqp_methods_unsubscribe Line:892 unsubscribe called while not subscribed
Error: Time:Tue Jan 28 19:43:47 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:print_socket_bound_address Line:345 listening on x.x.x.x:58494
Error: Time:Tue Jan 28 19:43:47 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:381 Failure: select failure. socket: 24  error: 115
Error: Time:Tue Jan 28 19:43:47 2020 File:/path/to/my/sdk/code/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:781 wait_for_connection failed
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR

**Comment by abdeldiaz** [comment]
Solved. Server is not accepting certificate from device. Communication timeout.

**Comment by COTASPAR** [comment]
@abdeldiaz Hi. I'm running into the same issue as you. Could you elaborate on how you got around the communication timeout?

**Comment by abdeldiaz** [comment]
Sorry @COTASPAR , I did not see your question. The new reality have me crazy. In a nutshell the timeout for me could happen for two reasons: 
1 - The SSL negotiation stopped because the server does not accept the certificates. Sometimes is because server and client have different time
2 - The communication stall and the socket timeout after negotiation. That is harder to solve. I just try to keep a bit traffic in a delta time so keeps the socket active.

Hope it helps. Cheers
