### ISSUE TITLE
Intermittent data loss when network segment of connected device is changed after registration.

### ISSUE THREAD

**Issue by gksreal** [Azure/azure-iot-sdk-c#1396]
My system works flawlessly especially the Azure IOT connection piece.  This has been tested for enduring more than a week.    However if the device side N/W segment characteristics especially ( IP address ) is changed, I get to see this data indeterminacy issue.

Scenario recreation steps:
1) Setup a network to connect to the Internet ( say a 4G dongle from service provider A )
2) Register a new device to the Azure IOT hub.
3) Continue to transfer telemetry data.
4) Stop the application.
5) Setup a new network to connect to the Internet( say another 4G dongle from a different service provider B )
6) Continue to transfer telemetry data.

Observations made:-
At step 5, the device connecting to Azure IOT hub has a new N/W segment IP.
The device is not re-registered.

Queries:-
1)  Is the scenario a right way to  conduct the experiment ?
2)  Should the device re-register because of the new IP it has acquired ( Has the Twin caching got anything to do with it ? )

Thanks.

**Comment by ewertons** [comment]
Hi @gksreal , just to make sure, when you are mentioning "register" you are not talking about DPS, right? You are just connecting to your Azure IoT Hub using the device connection string, correct?

If that is the case, see, if your device changes it's IP address, the device client will most likely loose its connection with the IoT Hub (send and recv will start failing with the previously established socket), and at a certain point the device client code will detect that and attempt to re-establish the connection (re-connect, re-authenticate). 
Depending on your system, it might take a while for the code to detect the lack of connectivity and trigger the reconnection (considering you have not changed any of the default mechanisms to do so, like keep alive frequency and retry policy).

If you wait long enough (4 minutes or more), do you see a successful reconnection? Can you [collect logs](https://github.com/Azure/azure-iot-sdk-c/blob/2019-12-11/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L125) to verify that?

**Comment by ewertons** [comment]
Hi @gksreal ,

We apologize for the long delay, but we were assigned to work on new code development and that affected our github response time.

We will close this issue, but if you would like it to be reopened and follow up on this matter, please post a comment requesting so.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@gksreal, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
