### ISSUE TITLE
iothub file upload sample, doesn't work with all proxies on which web browsers work consistently

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#140]
- **OS and version used:** Ubuntu 14.04 LTS( tried both on Linux kernel and WSL )

- **SDK version used:** release_2017_05_19

# Description of the issue:
The iothub sample for file upload([1](https://github.com/Azure/azure-iot-sdk-c/blob/2017-05-19/iothub_client/samples/iothub_client_sample_upload_to_blob/iothub_client_sample_upload_to_blob.c)) works on most https proxies. But fails consistently on some https proxies. I saw it first failing in my official work environment with Ubuntu 14.04 LTS behind a corporate proxy. I used `export https_proxy=83.239.58.162:8080` since the iothub client sample picks proxy from environment.

Web browsers work perfectly with all proxies I tried. Just that iothub client file upload fails. Please use any of below proxies to reproduce this issue.

# List of proxies on which I could reproduce this issue
0. Work proxy
1. export https_proxy=163.121.188.3:8080
2. export https_proxy=83.239.58.162:8080
3. export https_proxy=52.58.249.129:8083
4. more will be updated here

# Code sample exhibiting the issue:
iothub_client_sample_upload_to_blob code sample( [link](https://github.com/Azure/azure-iot-sdk-c/tree/2017-05-19/iothub_client/samples/iothub_client_sample_upload_to_blob) ) as is with out any change exhibits this issue.

# Console log of the issue:

> root@DESKTOP-QR77TIC:/mnt/e/git/azure-iot-sdk-c/cmake# **export https_proxy=83.239.58.162:8080**
> root@DESKTOP-QR77TIC:/mnt/e/git/azure-iot-sdk-c/cmake# **./iothub_client/samples/iothub_client_sample_upload_to_blob/iothub_client_sample_upload_to_blob**
> Starting the IoTHub client sample upload to blob...
> Info: IoT Hub SDK for C, version 1.1.14
> Error: Time:Sat May 20 13:52:43 2017 File:/mnt/e/git/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c **Func:HTTPAPI_ExecuteRequest Line:552 curl_easy_perform() failed: Failure when receiving data from the peer**
> 
> Error: Time:Sat May 20 13:52:44 2017 File:/mnt/e/git/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:554 (result = HTTPAPI_OPEN_REQUEST_FAILED)
> Error: Time:Sat May 20 13:52:44 2017 File:/mnt/e/git/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
> Error: Time:Sat May 20 13:52:44 2017 File:/mnt/e/git/azure-iot-sdk-c/iothub_client/src/blob.c Func:Blob_UploadFromSasUri Line:142 failed to HTTPAPIEX_ExecuteRequest
> Error: Time:Sat May 20 13:52:44 2017 File:/mnt/e/git/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_Impl Line:812 unable to Blob_UploadFromSasUri
> hello world failed to upload

**Comment by markrad** [comment]
Hi @kiranpradeep,

Can you clone an alternative branch called mrfileupload and tell me if it exhibits the same behavior please?

Thank you.

_Mark Radbourne MSFT_

**Comment by kiranpradeep** [comment]
@markrad Yes. The same behavior persists on _mrfileupload_ branch.

To avoid any misunderstanding, the issue is not specific to my machine. With the proxy I have given in issue description, the issue is reproducible from any Ubuntu machine. I believe, you too will get the same error, should you try with the proxy I have given.

I haven't made any changes to code ( other than connection string )

**Comment by markrad** [comment]
Hi @kiranpradeep,

I understand that this is not specific to your machine. I will try it for myself. I just didn't want to debug code that is going to go away soon. The file upload has changed quite significantly.

I'll test it for myself with the proxy you have provided.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @kiranpradeep,

I have researched your issue. It appears that curl expects the export to be in the form of
export https_proxy=http://83.239.58.162:8080
You need to add the **http://** at the start of the IP address or server name. This is not a limitation of our code but is apparently how curl_easy_perform expects the environment variable to be formatted. Here is my network trace that clearly shows the proxy in use when it is exported in that format:
```
MessageNumber   Source              Destination                         Summary 
263             157.59.113.172      83.239.58.162                       TCP Flags: ......S., SrcPort: 36010, DstPort: HTTPAlternate(8080), Length: 0, Seq Range: 4294404772 - 4294404773, Ack: 0, Win: 29200(negotiating scale factor: 7)   
272             83.239.58.162       157.59.113.172                      TCP Flags: ...A..S., SrcPort: HTTPAlternate(8080), DstPort: 36010, Length: 0, Seq Range: 2582362259 - 2582362260, Ack: 4294404773, Win: 5792(negotiating scale factor: 1)   
273             157.59.113.172      83.239.58.162                       TCP Flags: ...A...., SrcPort: 36010, DstPort: HTTPAlternate(8080), Length: 0, Seq Range: 4294404773 - 4294404773, Ack: 2582362260, Win: 29312(scale factor: 7)  
274             157.59.113.172      MarkRadHub1.azure-devices.net:443   HTTP    Operation, Status: Connection Established (200), CONNECT MarkRadHub1.azure-devices.net:443, Version: HTTP/1.1   
286             157.59.113.172      83.239.58.162                       TLS Records: [Handshake: [Client Hello]]    
290             83.239.58.162       157.59.113.172                      TLS Records: [Handshake: [Server Hello, Certificate, Server Key Exchange, Server Hello Done]]   
306             157.59.113.172      83.239.58.162                       TLS Records: [Handshake: [Client Key Exchange], ChangeCipherSpec, Handshake(Encrypted)] 
```

_Mark Radbourne MSFT_

**Comment by kiranpradeep** [comment]
@markrad Thanks for the suggestion. But, that didn't help. Did you try on an Ubuntu 14.04 LTS ? Did you get the blob upload confirmation message telling "_hello world has been created_" ?

For me, on an Ubuntu 14.04 LTS, I am continuing to get the same old error reported in issue description. I am copying the terminal below. I am on master branch.

```
user_name@machine_name:~/azure/azure-iot-sdk-c/cmake$ export https_proxy=http://83.239.58.162:8080
user_name@machine_name:~/azure/azure-iot-sdk-c/cmake$ ./iothub_client/samples/iothub_client_sample_upload_to_blob/iothub_client_sample_upload_to_blob 
Starting the IoTHub client sample upload to blob...
Info: IoT Hub SDK for C, version 1.1.12
Error: Time:Thu Jun  1 11:32:59 2017 File:/home/user_name/azure/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:552 curl_easy_perform() failed: Failure when receiving data from the peer

Error: Time:Thu Jun  1 11:32:59 2017 File:/home/user_name/azure/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:554 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Thu Jun  1 11:32:59 2017 File:/home/user_name/azure/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Thu Jun  1 11:32:59 2017 File:/home/user_name/azure/azure-iot-sdk-c/iothub_client/src/blob.c Func:Blob_UploadFromSasUri Line:142 failed to HTTPAPIEX_ExecuteRequest
Error: Time:Thu Jun  1 11:32:59 2017 File:/home/user_name/azure/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_Impl Line:812 unable to Blob_UploadFromSasUri
hello world failed to upload
user_name@machine_name:~/azure/azure-iot-sdk-c/cmake$ 
```

**Comment by markrad** [comment]
Hi @kiranpradeep,

According to your log, curl_easy_perform is returning error 56. Since I am able to use the same web proxy, this would suggest that it is your network that is preventing your successful connection. Can you use tcpdump and grab a network trace during the file upload failure please. Attach the file here.

Thank you.

_Mark Radbourne MSFT_

**Comment by kiranpradeep** [comment]
@markrad Thanks for the response. I have attached wireshark capture([1](https://github.com/Azure/azure-iot-sdk-c/files/1049423/proxy.zip)).

I have tried on 4 different Ubuntu machines( 2 at work and 2 at home ) and got the same error in each machine. So it is hard for me to join with assumption - "_your network is preventing successful connection_". 

Also, I want to make sure we all are using same code base. I am on _master_ branch and a `git describe` shows _2017-03-24-144-g52958b5_.

If we both are on master and you got the  confirmation message("_hello world has been created_") on blob upload over the same proxy, then I also want to make sure we have similar environment variables( as the blob upload samples takes options from environment! ). So I am pasting output of `env `command below. 

```
SHELL=/bin/bash
TERM=xterm
OLDPWD=/root
USER=root
NAME=DESKTOP-QR77TIC
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
HOSTTYPE=x86_64
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/mnt/e/git/azure-iot-sdk-c/cmake
LANG=en_US.UTF-8
https_proxy=http://83.239.58.162:8080
SHLVL=1
HOME=/root
LOGNAME=root
LESSOPEN=| /usr/bin/lesspipe %s
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
```

**Comment by markrad** [comment]
Hi @kiranpradeep,

I have picked up the service request you opened. I'll keep this issue open until we have some resolution in the context of your service request and update this when we are done.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
In order to close the loop, I was able to reproduce this issue with Curl at version 3.35 which is standard on Ubuntu 14. On Ubuntu 16 with Curl at 3.52 I could not reproduce this issue. 

I cloned the latest version of Curl from GitHub and built it on my Ubuntu 14 system. This was version 3.54. Having retested the file upload using the later version of Curl the upload was successful. I can only conclude that the defect is in the Curl library not our SDK.

_Mark Radbourne MSFT_

**Comment by kiranpradeep** [comment]
Thanks @markrad . For any one else who could face same issue, please update to curl 7.52+( not 3.52 ) to fix this issue.  Curl 7.52.0 added support to _https_proxy_ ( [CURLOPT_PROXY](https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html) ) with scheme as _https://_ which fixed the issue.
