### ISSUE TITLE
Get "OpenSSL::Crypto" not build error if use CMake 3.10.2 with public-preview vcpkg

### ISSUE THREAD

**Issue by hellyzh** [Azure/azure-iot-sdk-c#1402]
Repro Steps:
1. Follow this [tutorial](https://docs.microsoft.com/en-us/azure/iot-pnp/quickstart-create-pnp-device-linux) to generate Plug and Play device code and compile with device c sdk public-preview Vcpkg.
2. When triggered "cmake .. -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake -Duse_prov_client=ON -Dhsm_type_symm_key:BOOL=ON", we got error like this.
````
 Cannot specify link libraries for target "OpenSSL::Crypto" which is not
  built by this project.
````
If use CMake version 3.11.0 or above, there is no issue. 
The issue starts after the [commit](https://github.com/microsoft/vcpkg/commit/837fcab0ef8395b6da130c04c81f640d96669276#diff-6c27b248ea89b1da624be538c0ac49ab).

**Additional info**
Operating System: Ubuntu 1804

**Comment by vpaladino778** [comment]
Hello, I am also seeing this issue. I the latest master branch

**Comment by hellyzh** [comment]
Issue is gone, CMake 3.10.2 works now.

**Comment by ewertons** [comment]
Hey @vpaladino778  and @hellyzh ,

We apologize for the long delay, but we were assigned to work on new code development and that affected our github response time.

Thank you very much for posting back your findings, that will help the community in case they see the same issue.

We will close this issue, but if you would like it to be reopened and follow up on this matter, please post a comment requesting so.

Thanks for your contribution.
- Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@vpaladino778, @hellyzh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
