### ISSUE TITLE
Broken links in the readme

### ISSUE THREAD

**Issue by lokijota** [Azure/azure-iot-sdk-c#1404]
There are several broken links in the documentation page. For example, the one to the detail on how to install, or when you click "Setting up a Linux development environment" [for a custom build].

**Comment by ericwol-msft** [comment]
I ran a link checker and resolved reported broken links.

**Comment by az-iot-builder-01** [comment]
@lokijota, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
