### ISSUE TITLE
can't resolve symbol 'SSL_load_error_strings'

### ISSUE THREAD

**Issue by tdhj** [Azure/azure-iot-sdk-c#1405]
/iothub_ll_telemetry_sample: can't resolve symbol 'SSL_load_error_strings'

**Comment by tdhj** [comment]
1416F086:SSL routines:tls_process_server_certificate:certificate verify fail

**Comment by ewertons** [comment]
Hi @tdhj ,
this issue contains very few details and we are not able to provide any insight based only on these traces.
This SDK gets built daily for Linux and openssl and is validated.
If you still need assistance, please feel free to reopen this issue once you have all the details about your platform (OS flavor, version, architecture), version of the SDK used, version of openssl, gcc, you have installed, build logs. Please follow the instructions when filing the issue so we can have actionable data available.

**Comment by az-iot-builder-01** [comment]
@tdhj, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
