### ISSUE TITLE
Sample digitaltwin_sample_ll_device disconnects to IoT Central every 40+ minutes

### ISSUE THREAD

**Issue by JerryYangKai** [Azure/azure-iot-sdk-c#1406]
Development Machine: Windows 10
Compiler: Visual Studio 2019
SDK Version: tag 2019-11-15-public-preview-pnp

**Describe the Bug**
Sample [digitaltwin_sample_ll_device ](https://github.com/Azure/azure-iot-sdk-c/tree/2019-11-15-public-preview-pnp/digitaltwin_client/samples/digitaltwin_sample_ll_device). It can connect to IoT Central and send telemetry well but disconnected every 48 minutes.  
The console logs shows that the sample started in 17:05 and reconnected in 17:52.
 
**Console Logs**
![image](https://user-images.githubusercontent.com/53805504/72706893-187bf280-3b9a-11ea-9ee5-9e2f33380894.png)
![image](https://user-images.githubusercontent.com/53805504/72706906-1fa30080-3b9a-11ea-930c-aa9727b40d70.png)

**Comment by ericwol-msft** [comment]
Below is the steps to debug IoT Hub continuity issues. Azure IoT Central does not expose these Hub features. You might need to open a service request on your Azure IoT Central application.

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-troubleshoot-connectivity

**Comment by ericwol-msft** [comment]
This is happening because the SAS token expires every hour. If you use certificate auth the connection will be maintained.

**Comment by az-iot-builder-01** [comment]
@JerryYangKai, @ericwol-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by ericwol-msft** [comment]
question resolved
