### ISSUE TITLE
AzureIoTUtility Installation Failure via Cocoapods

### ISSUE THREAD

**Issue by bryanposas** [Azure/azure-iot-sdk-c#1407]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Mac OS Catalina 10.15.2, Xcode 11.3.1

**SDK Version (Please Give Commit SHA if Manually Compiling)**

[AzureIoTUtility](https://cocoapods.org/pods/AzureIoTUtility) 1.1.12

**Describe the Bug**

I'm trying to install the framework using cocoapods but it's not passing through because the branch `jbobotek-test-cocoa` is missing. It was still ok before I think 3 weeks to a month ago.
**Console Logs**
```
Installing AzureIoTUtility (1.1.12)

[!] Error installing AzureIoTUtility
[!] /usr/bin/git clone https://github.com/Azure/azure-c-shared-utility.git /var/folders/f9/zvsz4k2j56d35r49dq33cc0r0000gp/T/d20200121-63608-jah89 --template= --single-branch --depth 1 --branch jbobotek-test-cocoa

Cloning into '/var/folders/f9/zvsz4k2j56d35r49dq33cc0r0000gp/T/d20200121-63608-jah89'...
warning: Could not find remote branch jbobotek-test-cocoa to clone.
fatal: Remote branch jbobotek-test-cocoa not found in upstream origin
```

**Comment by kartben** [comment]
@bryanposas Thanks for taking the time to file this issue! For reference, see also StackOverflow question that Bryan posted: https://stackoverflow.com/questions/59834251/azureiotutility-cocoapods-installation-failed.

@jbobotek any idea why the branch got deleted, and/or will an official 1.1.12 tag be created?

**Comment by kartben** [comment]
@bryanposas Thanks for taking the time to file this issue! For reference, see also StackOverflow question that Bryan posted: https://stackoverflow.com/questions/59834251/azureiotutility-cocoapods-installation-failed.

@jbobotek any idea why the branch got deleted, and/or will an official 1.1.12 tag be created?

**Comment by jbobotek** [comment]
Looking into it now.

**Comment by jbobotek** [comment]
Can you verify if putting these library versions in your podfile works?: 'AzureIoTHubClient', '=1.3.6-nightly-a' 'AzureIoTUtility', '=1.1.12d' 'AzureIoTuMqtt', '=1.1.12d' 'AzureIoTuAmqp', '=1.2.12d'

**Comment by bryanposas** [comment]
@kartben This is me as well https://stackoverflow.com/questions/59834251/azureiotutility-cocoapods-installation-failed. So I tried all solutions I found before posting here. And it seems your solution in the stackoverflow post have worked. Thanks!

**Comment by kartben** [comment]
The spec for AzureIoTUtility@1.1.12d refers to a branch that does not exist
anymore:
https://github.com/CocoaPods/Specs/blob/2f7880d545700890e385dab1c55376621b952f37/Specs/1/4/0/AzureIoTUtility/1.1.12d/AzureIoTUtility.podspec.json#L16

**Comment by kartben** [comment]
@bryanposas I know it's you :) I wanted to make sure to cross-post the link to document that the issue needed to be followed up on in two threads :)

**Comment by jbobotek** [comment]
> The spec for AzureIoTUtility@1.1.12d refers to a branch that does not exist
> anymore:
> https://github.com/CocoaPods/Specs/blob/2f7880d545700890e385dab1c55376621b952f37/Specs/1/4/0/AzureIoTUtility/1.1.12d/AzureIoTUtility.podspec.json#L16
>
yeah, if I can get it just pulling the latest instead, may be due for a podspec update.

**Comment by jbobotek** [comment]
@bryanposas Try now, restored the branch.

**Comment by bryanposas** [comment]
@jbobotek I can confirm that this issue is now resolved.

Can use this now:
'AzureIoTHubClient', '=1.3.6-nightly-a' 
'AzureIoTUtility', '=1.1.12d' 
'AzureIoTuMqtt', '=1.1.12d' 
'AzureIoTuAmqp', '=1.2.12d'

**Comment by ericwol-msft** [comment]
issue is now resolved

**Comment by az-iot-builder-01** [comment]
@kartben, @jbobotek, @bryanposas, @ericwol-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
