### ISSUE TITLE
Unable to receive device telemetry : iothub_ll_client_x509_sample.c

### ISSUE THREAD

**Issue by prohith46** [Azure/azure-iot-sdk-c#1408]
azure-iot-sdk-c/iothub_client/samples/iothub_ll_client_x509_sample/iothub_ll_client_x509_sample.c

I'm running the above mentioned file with my x509 certificate, IoT Hub details, Device. I'm receiving successful callback with IOTHUB_CLIENT_CONFIRMATION_OK .

I have configured events to receive telemetry to a particular endpoint to storage queue, but not receiving them.

However when i send C2D message I'm able to receive it.

Also I have configured event for device created, device deleted, device connected and device disconnected. There I'm receiving message in my storage queue when device connected and disconnected.
Can some one please help me

**Comment by ericwol-msft** [comment]
You can monitor the telemetry events on the hub using the az hub monitor command. That will tell you if the message from the device is making it to the hub.

az iot hub monitor-events --device-id myiOSdevice --hub-name {YourIoTHubName}

More info found here:
https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-ios

**Comment by ewertons** [comment]
Hi @prohith46 ,
did you have a chance to look into the suggestions made by @ericwol-msft ?
We will close this issue for now, but please feel free to reopen it if you would like to follow up on this issue.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@prohith46, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
