### ISSUE TITLE
Planning to port device SDK to support NDK on TI-RTOS

### ISSUE THREAD

**Issue by ayyappa-swamy** [Azure/azure-iot-sdk-c#141]
# Description of the issue:
I would like to port the azure-iot-sdk-c to TI-RTOS based on TI's NDK. The existing port for TI-RTOS is based on Simple-Link library, which is not supported by other launchpads. 
I use TM4C1294XL launchpad, which meets all the hardware requirements. It has an onboard Ethernet port for connectivity. 
Please let me know, if this is in your backlog? If yes, I can sync with you for contribution.
#Contribution

**Comment by tameraw** [comment]
@ayyappa-swamy - Currently this is not in our backlog. We are working to define a process for working with third party ports.
In the meantime, if you would like to pursue this port, we suggest you fork or have your own repo and we would happily review your code and can also feature it as a link in our repo.

**Comment by ayyappa-swamy** [comment]
Thank you @tameraw for the clarification. I shall come back for code review once I am done with the port in my forked repo. I shall get back for any help, if required, in the porting process.

**Comment by tameraw** [comment]
Please let us know when ready.
