### ISSUE TITLE
pnp codegen some suggestions

### ISSUE THREAD

**Issue by uriel-kluk** [Azure/azure-iot-sdk-c#1412]
# [Name]_Interface_Telemetry_SendAll()  is poorly written
A chance for buffer overrun and stack corruption
These should not be on the stack as MAX_MESSAGE_SIZE is 512 and these should be
implemented with `snprintf` instead of `sprintf`.

# File structure
The implementation files are on root but the interfaces are inside utilities. this is confusing

**Comment by JerryYangKai** [comment]
@uriel-kluk  Thanks for your feedback. I will fix them in our further released

**Comment by jspaith** [comment]
Thanks for feedback @uriel-kluk .  Like other one I recently closed, I'm closing this as well since it's not our repo directly that can fix and @JerryYangKai is tracking.

**Comment by az-iot-builder-01** [comment]
@uriel-kluk, @JerryYangKai, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
