### ISSUE TITLE
Where to find source used for building cocoapods (.podspec)

### ISSUE THREAD

**Issue by SashaMilic** [Azure/azure-iot-sdk-c#1414]
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

>
Can't find .podspec. Here is the link to .json:
https://github.com/CocoaPods/Specs/blob/master/Specs/3/8/4/AzureIoTHubClient/1.2.4/AzureIoTHubClient.podspec.json
But it is the compiled version
The original one is in ruby. Where we can find link to it?
>

### Expected/desired behavior
If it's open source project where is .podspec file?
>

### OS and Version?
iOS
Versions  13.3
>
We are trying to port lib for iOS to work on watchOS. .podspec will be helpfull.
Where to find source used for building cocoapods (.podspec) for using AureIoTHub for iOS?
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/ios/CocoaPods.md
> ---------------------------------------------------------------

**Comment by jbobotek** [comment]
Please edit your podspec to include the module versions listed here: https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/ios/CocoaPods-Samples.md

**Comment by SashaMilic** [comment]
@jbobotek: Thank you for link, but I already know that. But source.. where is source code from cocoapods?

**Comment by jbobotek** [comment]
Alright, the official sample is listed in the .md I just linked, for the SDK, those are built from this repo. As for the .podspecs, if you want to provide a place where I can drop them that's fine, or I can release just the podspecs as a repo itself.

**Comment by SashaMilic** [comment]
@jbobotek 
Please, if you could release podspec as a repo itself, that will great.. It will help so much.
Thank you in advance.

**Comment by SashaMilic** [comment]
Just to clarify. The point is that I need podspec files for all the libraries that azure-iot-sdk-c uses. If it was only for azure-iot-sdk the chase would be that bad
So, azure-iot-sdk-c uses include a bunch of other libraries that have their own podspec files.

**Comment by jbobotek** [comment]
https://github.com/jbobotek/azure-iot-sdk-c-podspecs

**Comment by jbobotek** [comment]
podspec files released, marking as resolved. If you have any new issues, please open a new issue.

Thanks

**Comment by az-iot-builder-01** [comment]
@jbobotek, @SashaMilic, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
