### ISSUE TITLE
Only one connection per device ID possible

### ISSUE THREAD

**Issue by koalo** [Azure/azure-iot-sdk-c#1416]
I need to maintain simultaneous connections to the IoT Hub from several programs running on the same device with the same device ID.

When using MQTT, the first connection is disconnected with IOTHUB_CLIENT_CONNECTION_NO_NETWORK as soon as the second connection is established. While I do not get the rationale behind this, this behavior is at least documented at https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support ("IoT Hub only supports one active MQTT connection per device. Any new MQTT connection on behalf of the same device ID causes IoT Hub to drop the existing connection.").

Since I could not find a corresponding note in the AMQP documentation, my expectation is, that it is possible with AMQP. However, when testing it with AMQP over Websockets (with version 1.3.0), the first connection is again disconnected, but now with IOTHUB_CLIENT_CONNECTION_COMMUNICATION_ERROR.

What is the rationale behind allowing only one active MQTT connection per device ID?
Why is there a similar behavior for AMQP? Is this a bug in the SDK or a missing note in the documentation?
Is there any other way how I can achieve my goal?

**Comment by ewertons** [comment]
Hi @koalo ,
This is part of a design of any client-server system that is based on an identity (device ID in this case).
The Azure IoT Hub is designed to allow only one endpoint connected with the same identity (device ID).

If you need multiple endpoints connected to the Azure IoT Hub you can either use unique device IDs per endpoint or use [AMQP device multiplexing](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_ll_client_shared_sample) (please note we do have bugs currently on this feature on azure-iot-sdk-c).

**Comment by az-iot-builder-01** [comment]
@koalo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
