### ISSUE TITLE
PnP E2E tests do not run in Linux

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1417]
Our E2E tests for Linux for PnP are currently disabled.  The gist of the issue is that the C SDK requires one version of openssl, whereas npm (the tests are written in NodeJs) wants a different one.

Some possible ways of mitigating this:
* Running the tests from a Docker container.  This isn't really how our test infra is setup - one container spinning another - so I'd rather not go down that route.
* https://github.com/pyenv/pyenv/issues/945 apparently has some tricks on this.
* Possibly using nvs, from https://github.com/jasongin/nvs

```script
Export NVS_HOME="$HOME/.nvs" 
git clone https://github.com/jasongin/nvs "$NVS_HOME"
.  "$NVS_HOME/nvs.sh" install
```
* ??

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
