### ISSUE TITLE
Better error reporting when dealing with SAS requests.

### ISSUE THREAD

**Issue by yaroslav-zhurakovskiy** [Azure/azure-iot-sdk-c#1418]
## Description
Right now when an error occurs during IoTHubClient_UploadToBlobAsync there is no clear reporting on what went wrong.  Deep inside the library```send_http_sas_request``` prints ```status code``` of the response and it is not very helpful. For instance it can print ```HTTP code was 400```. It does not tell what exactly went wrong, while ```response_buff``` contains a json with the useful information.

## Summary
**Is your feature request related to a problem? Please describe.**
When ```HTTPAPIEX_SAS_ExecuteRequest``` returns an error there is no informative reporting on what went wrong.

**Describe the solution you'd like**
I am not that big fan of printing errors, but in this case ```response_buff``` can be printed  along with ```statusCode```.

**Describe alternatives you've considered**
The only alternative is to go deep in the code base and print ```response_buff``` using a debugger or modifying the source code by adding a print statement.

**Additional context**
None

**Comment by ewertons** [comment]
Hi @yaroslav-zhurakovskiy ,
Thanks for reporting this issue and apologies for the long delay.

Would you be interested in posting a PR with your suggestion, so we can record your contribution on the history of our repo?

**Comment by ewertons** [comment]
@yaroslav-zhurakovskiy  ,
We will close this issue for now, but if you would like to follow up please feel free to reopen the issue or file a new one.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@yaroslav-zhurakovskiy, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
