### ISSUE TITLE
How do I retrieve the operation info (particularly operationId) from Azure Hub & DPS?

### ISSUE THREAD

**Issue by ethensnow** [Azure/azure-iot-sdk-c#1428]
Hi guys,

I have done a bit of research on this and only manage to find this:

https://docs.microsoft.com/en-us/azure/marketplace/cloud-partner-portal-orig/cloud-partner-portal-api-retrieve-operations#body-example

Device-wise, we are using the STM32L07X and the codes are in C, so I am trying to find the solution in C language.

After some searching, I found this:

https://stiffstream.com/en/docs/restinio/0.6/gettingstarted.html

But I am wondering if I can extract the operationId simply using MQTT commands like AT+QMTSUB/AT+QMTPUB?

I find this relevant (below) but I am not sure where to find the correct command string to extract the operation information.

https://github.com/Azure/azure-iot-sdk-c/issues/660

**Comment by ewertons** [comment]
Hi @ethensnow ,

We apologize for the long delay, but we were assigned to work on new code development and that affected our github response time.

There is now a much better solution for embedded systems like yours.
Please check the new [Azure SDK for Embedded C](https://github.com/azure/azure-sdk-for-c) suite.
You can find [samples for Device Provisioning](https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/provisioning/src/paho_iot_provisioning_example.c#L429) in that repo as well..

We will close this issue, but if you would like it to be reopened and follow up on this matter, please post a comment requesting so.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@ethensnow, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
