### ISSUE TITLE
can't link libraries on Windows using Qt...

### ISSUE THREAD

**Issue by drhalftone** [Azure/azure-iot-sdk-c#1429]
I've followed the instructions for building the libraries on Windows, with the one caveat that I used the x64 flag.  All is great; however, I am now trying to link the libraries in Qt, not VS.  So I am using the following in my .pro file:

        INCLUDEPATH   += $$quote(C:/usr/AzureIotSDK/include) \
                         $$quote(C:/usr/AzureIotSDK/include/azureiot) \
                         $$quote(C:/usr/AzureIotSDK/include/azure_macro_utils) \
                         $$quote(C:/usr/AzureIotSDK/include/umock_c)
        DEPENDPATH    += $$quote(C:/usr/AzureIotSDK/include) \
                         $$quote(C:/usr/AzureIotSDK/include/azureiot) \
                         $$quote(C:/usr/AzureIotSDK/include/azure_macro_utils) \
                         $$quote(C:/usr/AzureIotSDK/include/umock_c)
        LIBS          += -L$$quote(C:/usr/AzureIotSDK/debug/lib) -laziotsharedutil \
                         -lhsm_security_client -liothub_client -liothub_client_amqp_transport \
                         -liothub_client_amqp_ws_transport -liothub_client_http_transport \
                         -liothub_client_mqtt_transport -liothub_client_mqtt_ws_transport \
                         -liothub_service_client -lparson -lprov_auth_client \
                         -lserializer -luamqp -luhttp -lumock_c -lumqtt

However, while the code compiles, it can't find it IoTHub_Init() or any other symbol in the library.  Any suggestions what I am doing wrong?

**Comment by drhalftone** [comment]
Fixed it.  Here is what I should have had in my .pro file:

    iot {
        INCLUDEPATH   += $$quote(C:/usr/AzureIotSDK/include) \
                         $$quote(C:/usr/AzureIotSDK/include/azureiot)
        DEPENDPATH    += $$quote(C:/usr/AzureIotSDK/include) \
                         $$quote(C:/usr/AzureIotSDK/include/azureiot)
        LIBS          += -lwsock32 -lwinhttp -lws2_32 -lsecur32 -lcrypt32 -lNcrypt -lAdvapi32
        LIBS          += $$quote(C:/usr/AzureIotSDK/debug/lib/aziotsharedutil.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/hsm_security_client.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/iothub_client.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/iothub_client_amqp_transport.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/iothub_client_amqp_ws_transport.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/iothub_client_http_transport.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/iothub_client_mqtt_transport.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/iothub_client_mqtt_ws_transport.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/iothub_service_client.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/parson.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/prov_auth_client.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/serializer.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/uamqp.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/uhttp.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/umock_c.lib) \
                         $$quote(C:/usr/AzureIotSDK/debug/lib/umqtt.lib)
    }

**Comment by az-iot-builder-01** [comment]
@drhalftone, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
