### ISSUE TITLE
Exponential backoff with jitter retry strategy does not work

### ISSUE THREAD

**Issue by czyba** [Azure/azure-iot-sdk-c#143]
The exponential backoff retry strategy does not work. Due to integer division it degrades into a simple exponential backoff strategy.

The [misbehaving line](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothub_client_retry_control.c#L217) reads as follows:

`double jitter_percent = (retry_control->max_jitter_percent / 100) * (rand() / RAND_MAX);`

All parts of the expression are integer type variables. max_jitter_percent is in the interval [0,100] wheras rand() returns [0, RAND_MAX]. Due to truncating integer divisions this results in:
`(double)((0 or 1) * (0 or 1))`, which is most likely always 0, thus resulting in a simple exponential backoff strategy.

In order to fix this issue, at least one member of each division must be transformed into a double beforehand. So something like:

`double jitter_percent = (retry_control->max_jitter_percent / 100.0) * (rand() / double(RAND_MAX));`

should work. Alternatively it could be rewritten to:

`double jitter_percent = ((retry_control->max_jitter_percent * rand()) / 100.0) / RAND_MAX;`

in case the temporary integer type is large enough to hold the result of the expression `retry_control->max_jitter_percent * rand()`

The intereseted reader may want to play around with [this](https://godbolt.org/g/Hou2v9) to see what happens.

Kind Regards,
Christopher Czyba

**Comment by ewertons** [comment]
Thanks, we will verify your point and make the fixes briefly.

**Comment by tameraw** [comment]
@czyba - If you're willing to contribute your fix, we'd be happy to review your pull request. Thanks.

**Comment by ewertons** [comment]
Thanks for your contribution, it has been merged into master.
Please let us know if you have any other questions, comments or suggestions.

**Comment by czyba** [comment]
Great. works fine.

For a quick check I used this:
```
#include <iothub_client_retry_control.h>
#include <iothub_client_retry_control.c>

int main() {
  RETRY_CONTROL_HANDLE j = retry_control_create(IOTHUB_CLIENT_RETRY_EXPONENTIAL_BACKOFF_WITH_JITTER, 10000);

  j->retry_count = 10;
  j->max_jitter_percent = 100;

  int i;
  int k;
  for (k = 0; k < 100; ++k) {
    i = calculate_next_wait_time(j);
    printf("%i\n", i);
  }
}
```

Compiled with: `gcc a.c -I iothub_client/src/ -I iothub_client/inc/ -I c-utility/inc/ -L cmake/iotsdk_linux/iothub_client -l iothub_client -L cmake/iotsdk_linux/c-utility/ -l aziotsharedutil -lm`

Result before merge:
`512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512
512`

result after merge:
`942
713
912
920
978
613
683
905
654
795
756
833
698
774
999
981
837
879
584
822
520
636
582
923
592
717
578
567
1023
623
774
941
825
663
838
780
764
1010
661
906
781
906
716
968
657
692
925
982
547
998
781
556
610
851
967
690
544
522
746
544
633
1008
973
947
648
788
704
901
774
853
784
532
736
989
988
881
657
890
839
693
864
596
737
962
936
681
629
969
691
863
1001
813
848
951
737
985
715
929
862
978`
