### ISSUE TITLE
AMQP Mutltiplexing Connection Status Callback Defect

### ISSUE THREAD

**Issue by markrad** [Azure/azure-iot-sdk-c#1434]
**Windows 10
Windows SDK version 10.0.18362.0
C compiler identification is MSVC 19.24.28314.0**

**https://github.com/Azure/azure-iot-sdk-c/tree/2019-10-07**

**Protocol: Multiplexed AMQP**

Created an application that connects five devices to the IoT hub via a multiplexed AMQP connection. For each of these devices I added a connection status callback passing a user word that contained the index of the device handle in an array thus they were 0, 1, 2, 3, 4. Into my connection callback function I print the value of the user word along with the status and the result. This is what I see upon successful connection:
```
ConnectionStatusCallback: device=0;result=IOTHUB_CLIENT_CONNECTION_AUTHENTICATED;reason=IOTHUB_CLIENT_CONNECTION_OK
ConnectionStatusCallback: device=1;result=IOTHUB_CLIENT_CONNECTION_AUTHENTICATED;reason=IOTHUB_CLIENT_CONNECTION_OK
ConnectionStatusCallback: device=2;result=IOTHUB_CLIENT_CONNECTION_AUTHENTICATED;reason=IOTHUB_CLIENT_CONNECTION_OK
ConnectionStatusCallback: device=3;result=IOTHUB_CLIENT_CONNECTION_AUTHENTICATED;reason=IOTHUB_CLIENT_CONNECTION_OK
ConnectionStatusCallback: device=4;result=IOTHUB_CLIENT_CONNECTION_AUTHENTICATED;reason=IOTHUB_CLIENT_CONNECTION_OK
```
As expected there is one callback for each device. 

Now I create a network failure by removing the Ethernet cable from my hub and await the connection failed messages in the callback. However, where is where the problem is. The callback is called five times but all of the user words have the value of the last device I registered with the callback:
```
ConnectionStatusCallback: device=4;result=IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED;reason=IOTHUB_CLIENT_CONNECTION_NO_NETWORK
ConnectionStatusCallback: device=4;result=IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED;reason=IOTHUB_CLIENT_CONNECTION_NO_NETWORK
ConnectionStatusCallback: device=4;result=IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED;reason=IOTHUB_CLIENT_CONNECTION_NO_NETWORK
ConnectionStatusCallback: device=4;result=IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED;reason=IOTHUB_CLIENT_CONNECTION_NO_NETWORK
ConnectionStatusCallback: device=4;result=IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED;reason=IOTHUB_CLIENT_CONNECTION_NO_NETWORK
```
Note that I deleted all of the SDK reconnection messages for the sake of brevity.

**Comment by ewertons** [comment]
Issue fixed. Please feel free to reopen it if you find any additional issues regarding this failure.

Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment]
@markrad, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
