### ISSUE TITLE
Failure to generate SAS token

### ISSUE THREAD

**Issue by dangerousHobo** [Azure/azure-iot-sdk-c#1435]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Cross Complied Linux (Buildroot) using GCC 6.4.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 1.3.4 (LTS_07_2019_Ref01)

**Protocol**

MQTT

**Describe the Bug**

Trying to send an MQTT message from the device to the cloud, and get the following error output:

```
Error: Time:Fri Feb 14 19:38:14 2020 File:src/azure_base64.c Func:Azure_Base64_Decode Line:201 Invalid length Base64 string!
Error: Time:Fri Feb 14 19:38:14 2020 File:src/sastoken.c Func:construct_sas_token Line:217 Unable to decode the key for generating the SAS.
Error: Time:Fri Feb 14 19:38:14 2020 File:src/iothub_client_authorization.c Func:IoTHubClient_Auth_Get_SasToken Line:460 Failed creating sas_token
Error: Time:Fri Feb 14 19:38:14 2020 File:src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2169 failure getting sas token from IoTHubClient_Auth_Get_SasToken.

```

This is running on an ARM Cortex-A5 (Microchip SAMA5D36 ).

**Comment by dangerousHobo** [comment]
Updating to Release 1.3.8 solved this issue.

**Comment by az-iot-builder-01** [comment]
@dangerousHobo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
