### ISSUE TITLE
[MQTT] Retry policy could return huge values.

### ISSUE THREAD

**Issue by pgonzalezJean** [Azure/azure-iot-sdk-c#144]
Hello,

as the user yphuangms stated in a closed issue ( #18 ), in "azure-iot-sdks\c\iothub_client\src\iothubtransport_mqtt_common.c", the delay calculation could return huge values when the retry count comes to be big, as you can see in the next lines of 'RetryPolicy_Exponential_BackOff_With_Jitter' method:

>  size_t halfDelta = ((1 << numOfFailures) - 1) / 4;
        if (halfDelta > 0)
        {
            *delay = halfDelta + (rand() % (int)halfDelta);
        }
        else
        {
            *delay = halfDelta;
        }

I know that's how an exponential policy works, but in a real case, the max delay should be truncated to some value or else we could end with not reasonable delays.

In our scenario, some devices (which run 24/7) lost connection for several hours (3 or 4, perhaps). The MQTT reconnection ocurred more than one day later, which doesn't make sense.

As I say, this was stated by yphuangms, but not solved in that issue.

Also, yphuangms stated another issue in 'CanRetry' method.
When the diff time between the current time and the last retry is hit, the delay is re-evaluated with the code above (using the same 'retryCount' value).
If the new delay is bigger than the previous (because of the rand()), we have to keep waiting WITHOUT any retry happening.
The retry will only happen when the re-evaluated value is lower than the last one. Things like the one in the next screenshot are happening (3 re-evalutions before an actual retry).

![image](https://cloud.githubusercontent.com/assets/26146170/26492444/6cea0d52-4214-11e7-8b43-fcb5406881b3.png)

**Comment by ewertons** [comment]
Hi @pgonzalezJean ,
thanks for the suggestion, indeed it makes all the sense to have a cap on the maximum retry delay.
We will bring this to discussion and make the necessary changes.

**Comment by ewertons** [comment]
+ @olivierbloch 

Hi @pgonzalezJean , 
according to a discussion I had with Olivier, the suggestion is to keep the retry policy EXPONENTIAL_WITH_BACKOFF without a cap.
In case you want to have a less aggressive wait time progression, you could use a different retry policy, like 
IOTHUB_CLIENT_RETRY_INTERVAL.

The one detail is that on MQTT transport, EXPONENTIAL_WITH_BACKOFF is the only policy currently supported, but we have the task in our backlog to implement the others.
If you want to use IOTHUB_CLIENT_RETRY_INTERVAL, you can switch to using the AMQP transport, which supports all the retry policies.

**Comment by pgonzalezJean** [comment]
Hi @ewertons ,

We will await for the implementation of the rest of the policies in the MQTT protocol.
Thanks for your feedback.

Regards.

**Comment by ewertons** [comment]
Hi @pgonzalezJean ,
sorry for the delay on the reply, but MQTT now supports all the retry policies previously available using the AMQP transport.

You can select the policy using the following API [function](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client.h#L182).

Please let us know if it addresses the issue you originally opened, and if we can assist in any other way.

**Comment by FrankZhcz** [comment]
Hello,
I encountered the Error as below: 
......
Thu Nov 02 18:07:37.701 2017] Create socket client OK. g_socketfd:3
[Thu Nov 02 18:07:37.701 2017] Info: IoT Hub SDK for C, version 1.1.15
[Thu Nov 02 18:07:37.701 2017] Error: Time:Thu Nov  2 10:07:37 2017 File:/home/user/bin/qsdk/build_dir/target-mips_34kc_uClibc-1.0.14/azure-iot-sdk-2017-05-19/iothub_client/src/iothubtransport_mqtt_common.c Func:CreateRetryLogic Line:359 Use IOTHUB_CLIENT_RETRY_LINEAR_BACKOFF Policy
[Thu Nov 02 18:07:37.701 2017] IoTHubClient_LL_SetMessageCallback...successful.
......
The detail log was attached. 

How could I do to resolve the problem?

**Comment by ewertons** [comment]
Hey @FrankZhcz ,
despite being related to retry policies the same way as this original issue, your issue is different since it seems like a mismatch between SDK version and API implementation. Please make sure to file a separate issue when you find a problem (unless clearly related) so we do not miss your question.

To address your question, you are using a version of the SDK that is too old (1.1.15). Retry policies were not fully implemented for MQTT transport on that version.

**Comment by ewertons** [comment]
This issue (original post) has been addressed long time ago, but not closed at the time.
Since the retry policies are already all implemented, we are closing it.
Thanks for using the Azure IoT SDK!
