### ISSUE TITLE
IoT hub doesn't report file upload notifications for error cases

### ISSUE THREAD

**Issue by ramandeep-singh-1983** [Azure/azure-iot-sdk-c#1443]
We are uploading files using Azure IoT C SDK to IoT hub. As per https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload#notify-iot-hub-of-a-completed-file-upload, the following JSON structure is reported via the C SDK:

`{
    "correlationId": "{correlation ID received from the initial request}",
    "isSuccess": bool,
    "statusCode": XXX,
    "statusDescription": "Description of status"
}`

Now, from C SDK, we can only pass either SUCCESS or ABORT i.e FAILURE.

We are using following SDK method for file upload-
 
`IOTHUB_CLIENT_RESULT IoTHubDeviceClient_UploadMultipleBlocksToBlobAsync(
  IOTHUB_DEVICE_CLIENT_HANDLE                     iotHubClientHandle,
  const char *                                    destinationFileName,
  IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_CALLBACK_EX  getDataCallbackEx,
  void *                                          context
);`
 
From “getDataCallbackEx” callback, device is returning-
1.	In case of success device is returning (IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_OK).
2.	In case of failure, device is returning (IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_ABORT). 

We are getting the notification message from IoTHub for successful file upload, however in case of failure, IoTHub is not generating any message.

**Comment by jbobotek** [comment]
Looks like this is fixed by using IoTHubDeviceClient_UploadMultipleBlocksToBlobAsync**Ex**, as noted here: [UploadMultipleBlocksToBlobAsync is depricated](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/devdoc/requirement_docs/iothubclient_requirements.md#iothubclient_uploadmultipleblockstoblobasync)

**Comment by ramandeep-singh-1983** [comment]
Thanks @jbobotek . Will check this and get back soon.

**Comment by ewertons** [comment]
Hi @ramandeep-singh-1983 ,
we have verified the functionality and where not able to repro the issue you are describing.

In our attempt we tried:
- On a Linux host, 
- to upload a file with 100 blocks, 
- delaying the return from the getDataCallback by 300 milliseconds. 
- Then after 30 blocks are uploaded, we disable the internet connection in the host.
- Waited for about 4 minutes.

As you can see below, the callback is invoked with the expected result:

Error: Time:Thu Mar 12 14:59:50 2020 File:/home/ewertons/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:526 unable to recover sending to a working state
Error: Time:Thu Mar 12 14:59:50 2020 File:/home/ewertons/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:send_http_sas_request Line:120 unable to HTTPAPIEX_ExecuteRequest
Error: Time:Thu Mar 12 14:59:50 2020 File:/home/ewertons/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_step3 Line:603 unable to execute HTTPAPIEX_ExecuteRequest
Error: Time:Thu Mar 12 14:59:50 2020 File:/home/ewertons/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl Line:860 IoTHubClient_LL_UploadToBlob_step3 failed
**Received unexpected result FILE_UPLOAD_ERROR**

Could you please try to use the latest API (as mentioned by @jbobotek ) and also post a specific set of repro steps so we can follow? Thanks

**Comment by sanjeev-magoo** [comment]
@ewertons , thanks for analysis. 
The issue is slightly different here. We are indeed getting the success/failure from API at device side. Please note that, the issue is with IoTHub. IoTHub provide facility to subscribe for file upload event. 
 Please check ioTHub configuration ->file upload. There is an option "File notification settings-Receive notifications for uploaded files".  We are getting successful file upload notification however for failure case, IoTHub is not providing any notification.
Ideally, 
- If device is sending the error as mentioned in the original issue, IoTHub should throw an error event.
-  If failure is due to device disconnection, IoTHub should have timeout configuration and in this case, if IoTHub does not receive file chunk from device within timeout period, IoTHub should raise an timeout event.

**Comment by ramandeep-singh-1983** [comment]
Exactly, the issue is not on IoT device SDK side but on IoT hub side.

**Comment by ewertons** [comment]
@ramandeep-singh-1983 , @sanjeev-magoo , thanks for the clarification.
I checked around and the support team mentioned that the best way to transfer this case to them is to open a ticket on your Azure Portal directly.

On your Azure Portal, 
1. Click on Help (upper right corner)
2. Click on Help + Support
3. Click on New support request and fill the form appropriately (add the description as you wrote above). You can even mention the link to this issue, even after we close it.

Sorry for the separate way requesting support, but that comes with the fact that the SDKs are open source.
So for any issues that are related to any other parts of Azure IoT **other than the SDK functionality** shall be filed using the Azure Portal directly.

Let me know if you need further help to achieve that, and please leave a comment once you get it filed, so we can close this GitHub issue.

Thanks,
Azure IoT SDK Team

**Comment by ramandeep-singh-1983** [comment]
@ewertons thanks for the update, i will file a ticket on Azure portal, will update here once it's filed.

**Comment by ramandeep-singh-1983** [comment]
We got a response on our Azure ticket. Exact response is as under:

> **As of current design of IoT Hub, only successful file upload events are published to service  facing endpoint(/messages/servicebound/filenotifications), you can consider this as limitation for failed file uploads scenario.

I find similar user voice request (https://feedback.azure.com/forums/321918-azure-iot/suggestions/17936725-support-iot-hub-upload-requests-monitoring) which is monitored by development team**

So, to sum it up: IoT hub only provides notification for successful file uploads and not for upload progress or failures.

**Comment by az-iot-builder-01** [comment]
@jbobotek, @ramandeep-singh-1983, @ewertons, @sanjeev-magoo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
