### ISSUE TITLE
[dps] Steps to integrate device provisioing service with Azure SDk

### ISSUE THREAD

**Issue by ShanmathiP** [Azure/azure-iot-sdk-c#1445]
Hi Team,
I am using [azure-iot-sdk-c-public-preview](https://github.com/Azure/azure-iot-sdk-c/tree/public-preview) branch for my development.
Mode of attestation  - X.509
Progress so far - 
- Generated certificates for leaf device as mentioned in [CACertificateOverview.md file](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md)
- Certificate format *.der files
- Generated device capability models and code stub. Now device is able to send the telemetry and properties to the cloud.
- Created DPS in cloud and added new individual enrollment for a device.

Steps to be done -
- Integrate Device Provisioning Service using x.509 attestation mechanism in code.
- Based  on the reference documents following changes in code have been added.
- Example used as reference- provisioning_client/samples/prov_dev_client_ll_sample

- C FLAGS definitions in makefile
`-D USE_PROV_MODULE=1 \
-D HSM_TYPE_X509=1 \`

- Function calls and definitions
`static const char* global_prov_uri = "global.azure-devices-provisioning.net";
static const char* id_scope = "xxxyyyzzz";
static SECURE_DEVICE_TYPE hsm_type = SECURE_DEVICE_TYPE_X509 ;
static PROV_DEVICE_TRANSPORT_PROVIDER_FUNCTION prov_transport = Prov_Device_MQTT_Protocol;
typedef struct DeviceProvisioningInfo_S
{
    unsigned int sleep_time;
    char* iothub_uri;
    char* access_key_name;
    char* device_key;
    char* device_id;
    int registration_complete;
};
typedef struct DeviceProvisioningInfo_S DeviceProvisioningInfo_T;
static DeviceProvisioningInfo_T deviceInfo;

    if(0 != prov_dev_security_init(hsm_type))
    {
        (void)printf("failed initializing prov_dev_security_init\r\n");
        return RETCODE_INVALID_PARAM;
    }
    deviceInfo.registration_complete = 0;
    deviceInfo.sleep_time = 10;
    printf("Provisioning API Version: %s\r\n", Prov_Device_LL_GetVersionString());
    printf("IoT Hub API Version: %s\r\n", IoTHubClient_GetVersionString());

    PROV_DEVICE_LL_HANDLE handle;
    if ((handle = Prov_Device_LL_Create(global_prov_uri, id_scope, prov_transport)) == NULL)
    {
        (void)printf("failed calling Prov_Device_LL_Create\r\n");
    }
    else
    {
        Prov_Device_LL_SetOption(handle, PROV_OPTION_LOG_TRACE, &traceOn);
        if (Prov_Device_LL_Register_Device(handle, register_device_callback, &deviceInfo, registration_status_callback, &deviceInfo) != PROV_DEVICE_RESULT_OK)
        {
                (void)printf("failed calling Prov_Device_LL_Register_Device\r\n");
        }
        else
        {
            do
            {
                    Prov_Device_LL_DoWork(handle);
                    ThreadAPI_Sleep(deviceInfo.sleep_time);
            } while (deviceInfo.registration_complete == 0);
        }
        Prov_Device_LL_Destroy(handle);
    }

    if (deviceInfo.registration_complete != 1)
    {
              (void)printf("registration failed!\r\n");
    }`
Upon compilation, issues related to **"undefined reference"** for various API's under simulator/reference aroused in hxm_clinet_riot.c file 
- DERInitContext(...)
- X509GetDeviceCertTBS(...)
- RiotCrypt_Sign(...)
- X509MakeRootCert(...)
- DERtoPEM(...)
- X509GetDEREcc(...) etc... 
Should the source files under reference/simulator also be included? or should we consider these API's as  weak function and implement??? Not sure how to proceed as I guess these API's are used for the simulated example.
For the actual implementation, with certificates already generated with X.509 attestation and stored in the device's chip(flash area of WiFi chip), how to proceed further and integrate DPS?
Is a custom hsm mandatory?

**Comment by hihigupt** [comment]
Our top level cmake handles the dependencies properly. Please use the following command to compile:

git clone https://github.com/Azure/azure-iot-sdk-c.git    
git checkout public-preview    
git submodule update --init --recursive --depth 1 
mkdir cmake
cd cmake
cmake -Duse_prov_client=1  -Dhsm_type_x509=1 ..
cmake --build .


this should build your prov_dev_client_ll_sample under path

<githubroot>/cmake/provisioning_client/samples/prov_dev_client_ll_sample

**Comment by hihigupt** [comment]
Also please check following issue, when using custom HSM
https://github.com/Azure/azure-iot-sdk-c/issues/1516#issuecomment-648450676

**Comment by az-iot-builder-01** [comment]
@ShanmathiP, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by hihigupt** [comment]
Please feel free to open new issue, if you still need help on this.
