### ISSUE TITLE
SDK should support UUID type (AMQP Spec) for MessageId and CorrelationId

### ISSUE THREAD

**Issue by pierreca** [Azure/azure-iot-sdk-c#146]
This issue is a follow up to the original one opened on the iothub-explorer repo:
https://github.com/azure/iothub-explorer/issues/18

These are the actions needed:
- Fix AMQP transport to read the message-id and correlation-id according to supported AMQP 1.0 types;
- Add a STRING<->UUID translation to AMQP transport (so we don't need to modify IoTHubMessage_Get/SetMessageID() )

Originally submitted by @czyba

**Comment by ewertons** [comment]
This PR addresses the issue:
https://github.com/Azure/azure-iot-sdk-c/pull/237

It will be checked in briefly.

**Comment by ewertons** [comment]
The fix has been checked in, and is available on the master branch.

Thanks for using and contributing to the Azure IoT SDK!
