### ISSUE TITLE
link broken in readme.md of branch public-preview-pnp

### ISSUE THREAD

**Issue by IvanJobs** [Azure/azure-iot-sdk-c#1461]
This link https://docs.microsoft.com/en-us/azure/iot-pnp/howto-use-iot-device-workbench got 404 now.
As described in the title, the broken link is in file of  https://raw.githubusercontent.com/Azure/azure-iot-sdk-c/public-preview-pnp/digitaltwin_client/readme.md

**Comment by ericwol-msft** [comment]
fixed

**Comment by az-iot-builder-01** [comment]
@IvanJobs, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
