### ISSUE TITLE
Hiding IOTHUB_*_HANDLE from DIGITALTWIN_*_HANDLE

### ISSUE THREAD

**Issue by IvanJobs** [Azure/azure-iot-sdk-c#1463]
According to  this link: https://github.com/Azure/azure-iot-sdk-c/blob/public-preview-pnp/digitaltwin_client/doc/connection_setup.md , 
I found that DIGITALTWIN_\*\_HANDLE is coupling with IOTHUB_\*\_HANDLE. 
Why not just hiding?

**Comment by ewertons** [comment]
Hi @IvanJobs ,
hiding the handle would mean we would need to expose a lot of the API functions from iothub_device_client on the Digital Twin API as well, creating a lot of duplication.
The design we have is aimed at simplifying the code and reducing memory usage, with the cost of having the handles individually managed by the user.

Thanks for your question, and please feel free to reopen this issue if you would like to follow up on this matter.
-Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@IvanJobs, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
