### ISSUE TITLE
Telemetry message metadata confusion

### ISSUE THREAD

**Issue by gri6507** [Azure/azure-iot-sdk-c#1464]
I am using the [example Telemetry Message sender code](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_module_sender/iothub_client_sample_module_sender.c) as reference but I have several questions:

1. What is the relationship between and the meaning of the following telemetry message metadata?
   - MessageId, as settable by [IoTHubMessage_SetMessageId](https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-message-h/iothubmessage-setmessageid)
   - CorrelationId, as settable by [IoTHubMessage_SetCorrelationId](https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-message-h/iothubmessage-setcorrelationid)
   - PropertyMap, as settable by [IoTHubMessage_Properties](https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-message-h/iothubmessage-properties) followed by [Map_AddOrUpdate](https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/map-h/map-addorupdate) 
   - MessageTrackingId, as used in [another example](https://github.com/Azure-Samples/azure-iot-edge-c-linux-arm-container-debug-sample/blob/master/IotEdgeModule1/main.c)
   - The `outputName` argument in  [IoTHubModuleClient_LL_SendEventToOutputAsync](https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-module-client-ll-h/iothubmoduleclient-ll-sendeventtooutputasync)

It would be great if there was a write-up explaining how Microsoft intends developers to use the SDK for telemetry messages, which included the high level explanation of what all of the above features are actually used for. The SDK documentation itself is too low level and, shall we say, not very explanatory.

2. None of the examples use the following API. When would I need to use it?
   - IoTHubMessage_SetContentTypeSystemProperty
   - IoTHubMessage_SetContentEncodingSystemProperty
   - IoTHubMessage_SetProperty

3. When I run ` az iot hub monitor-events -n myhub` I can see telemetry messages sent from my module, but they do not contain any of the metadata fields from above, even though I set all of the items from item 1 above. What am I missing?

4. It looks like at least the CorrelationId may be somehow related to [distributed tracing](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-distributed-tracing). However, the API to enable distributed tracing uses `IoTHubDeviceClient_LL_EnablePolicyConfiguration()` function which takes a device handle, not a edge module handle. What is the proper way to enable this feature for modules?

**Comment by ericwol-msft** [comment]
These APIs are for setting the HTML headers when using the HTML transport. The sample is using MQTT transport.

**Comment by gri6507** [comment]
> These APIs are for setting the HTML headers when using the HTML transport. The sample is using MQTT transport.

@ericwol-msft - Thank you for the reply. I think your response was to questions in item number 2. Can you please confirm?

An update on item number 3. I can see much of the metadata set in item number 1 (except for the `outputName` and `MessageTrackingId`) in az cli when I start it with

```bash
az iot hub monitor-events --hub-name myhub --properties=all
```

I am using MQTT in my module (same as example) and therefore, it seems like items from number 1 are not HTTP related. However, I still do not understand the relationship between that metadata. How is it expected to be used?

Also, what about item number 4?

**Comment by ericwol-msft** [comment]
Yes, this was for item #2, please see commit https://github.com/Azure/azure-iot-sdk-c/commit/3dedba48c44d48e49b5ec5c6990928b92dc16fdd

**Comment by ericwol-msft** [comment]
For issue 1, it is for support distributed tracing.

Please see this stackoverflow thread https://stackoverflow.com/questions/58665226/what-is-practical-usage-of-correlationid-and-messageid-when-sending-telemetry

**Comment by ericwol-msft** [comment]
Issue 3, yes, only the payload is displayed, not properties/header info. I wish it did also.

**Comment by gri6507** [comment]
@ericwol-msft Thank you for the clarifications. The only remaining question is item 4 - how to enable Distributed Tracing from a Module (not a device, like the example shows)

**Comment by ericwol-msft** [comment]
Modules should still use IoTHubDeviceClient_LL_SendEventAsync, but the module name is added to the path. Ex: devices/{device_id}/modules/{module_id}/messages/events/

**Comment by gri6507** [comment]
> Modules should still use IoTHubDeviceClient_LL_SendEventAsync, but the module name is added to the path. Ex: devices/{device_id}/modules/{module_id}/messages/events/

@ericwol-msft Than you for the response. Can you please clarify how I would do that? In my module, I currently have 
```c
#include <iothub_module_client_ll.h>

int main()
{
  IOTHUB_MODULE_CLIENT_LL_HANDLE handle = IoTHubModuleClient_LL_CreateFromEnvironment(CUR_PROTOCOL);
  
  <snip>
}
```

This means that my `handle` is of the wrong type to be passed to ` IoTHubDeviceClient_LL_SendEventAsync()` which expects a `IOTHUB_DEVICE_CLIENT_LL_HANDLE`. How can I obtain a `IOTHUB_DEVICE_CLIENT_LL_HANDLE` from within my module?

**Comment by ericwol-msft** [comment]
IoTHubModuleClient_LL_SendEventAsync in iothub_module_client_ll.c

**Comment by ewertons** [comment]
Hi @gri6507 ,

IOTHUB_MODULE_CLIENT_LL_HANDLE is only used by IoTHubModuleClient_LL_* functions, the same way that IOTHUB_DEVICE_CLIENT_LL_HANDLE is only used by IoTHubDeviceClient_LL_* functions.
There is no way to cross use these types!

Please see additional information for the questions you had:

>It looks like at least the CorrelationId may be somehow related to distributed tracing. However, the API to enable distributed tracing uses IoTHubDeviceClient_LL_EnablePolicyConfiguration() function which takes a device handle, not a edge module handle. What is the proper way to enable this feature for modules?

Distributed tracing is a feature in public preview phase, not supported by IoT Edge or Modules yet.

We will close this issue for now, but please feel free to reopen it if you would like to follow up.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@gri6507, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
