### ISSUE TITLE
Trouble using provisioning client sample

### ISSUE THREAD

**Issue by dangerousHobo** [Azure/azure-iot-sdk-c#1467]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Host: Ubuntu 18.04 
Target: Cross Compiled running on Linux 4.19.
Compiler: gcc 6.4.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release LTS_02_2020_Ref01 (1.3.8)

**Protocol**

MQTT

**Describe the Bug**

I've took the sample from provisioning_client (provisioning_client/samples/prov_dev_client_sample) and added my `id_scope` and assigned cert. Able to compile and run but I get the following error below. It looks like it may be an issue on the server end due to the message 'Failure retrieving data from the provisioning service'. I'm just trying to figure out where to start troubleshooting.

```
Provisioning API Version: 1.3.8

Registering Device

-> 13:37:49 CONNECT | VER: 4 | KEEPALIVE: 0 | FLAGS: 130 | USERNAME: 0ne000XXXXX/registrations/riot-device-cert/api-version=2019-03-31&ClientVersion=1.3.8 | CLEAN: 1
<- 13:37:49 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0
-> 13:37:49 SUBSCRIBE | PACKET_ID: 1 | TOPIC_NAME: $dps/registrations/res/# | QOS: 1
Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
<- 13:37:49 SUBACK | PACKET_ID: 1 | RETURN_CODE: 1
-> 13:37:49 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/PUT/iotdps-register/?$rid=1 | PAYLOAD_LEN: 37
<- 13:37:49 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/res/401/?$rid=1 | PACKET_ID: 2 | PAYLOAD_LEN: 151
Error: Time:Tue Mar 17 13:37:49 2020 File:src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Tue Mar 17 13:37:49 2020 File:src/prov_device_ll_client.c Func:on_transport_registration_data Line:770 Failure retrieving data from the provisioning service

Failure registering device: PROV_DEVICE_RESULT_TRANSPORT
Error: Time:Tue Mar 17 13:37:49 2020 File:src/mqtt_client.c Func:sendPacketItem Line:395 Failure sending control packet data
Error: Time:Tue Mar 17 13:37:49 2020 File:src/mqtt_client.c Func:mqtt_client_disconnect Line:1249 Error: mqtt_client_disconnect send failed
```

**Comment by ericwol-msft** [comment]
>> $dps/registrations/res/401

401 is an unauth error when talking to DPS service

**Comment by dangerousHobo** [comment]
@ericwol-msft unauth error meaning the x509 verification failed? I see the 401 means:

> The authorization token cannot be validated; for example, it is expired or does not apply to the request’s URI. This error code is also returned to devices as part of the TPM attestation flow.

My x509 cert is valid for the next 6 months, and the URI used is `global.azure-devices-provisioning.net`. Is there a different authorization piece that I'm missing?

**Comment by ericwol-msft** [comment]
Have you created an enrollment group in DPS and set the Attestation Type to "Certificate" and set the CA Certificate/Intermediate Certificate

Is there errors in the DPS activity log?

**Comment by dangerousHobo** [comment]
@ericwol-msft, Group enrollment is enabled, with Attestation Type set to Certificate, and with the intermediate cert set.

DPS log shows:

> Exception of type 'Microsoft.Azure.Devices.Registration.Thrift.ProvisioningServiceException' was thrown.

I haven't been able to find any more information on what that means.

**Comment by ericwol-msft** [comment]
Is there any error message with this?

Else, you can create a support request under "Help+Support" against Device Provisioning Services

**Comment by dangerousHobo** [comment]
That is the full message shown in the log.

I can report we've ran through provisioning with the .Net/C# Azure IoT SDK and it was successful. This appears to be specific to the C SDK.

**Comment by danewalton** [comment]
Hey @dangerousHobo great name btw.

How are you adding your cert in the sample? Are you using the custom hsm example?

**Comment by dangerousHobo** [comment]
Hey @danewalton, my issue was in the custom_hsm_example.c. Issue has been resolved, just forgot about this ticket!

**Comment by az-iot-builder-01** [comment]
@ericwol-msft, @dangerousHobo, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
