### ISSUE TITLE
Make connection retry initial delay configurable

### ISSUE THREAD

**Issue by ewertons** [Azure/azure-iot-sdk-c#1470]
**Is your feature request related to a problem? Please describe.**
When the C SDK attempts to reconnect, it does it right away by default, waiting 0 seconds on the first delay.
The code for that is here: https://github.com/Azure/azure-iot-sdk-c/blob/2020-01-22/iothub_client/src/iothub_client_retry_control.c#L181

Please make it configurable.

**Describe the solution you'd like**
User should be able to configure the minimum delay for reconnection retries.

**Describe alternatives you've considered**
Since the 0-sec delay is hardcoded, there is no workaround.

**Additional context**
According to input, having a 0-sec delay can be impactful in Windows systems. 
The same is not true for other systems like Linux.

**Comment by az-iot-builder-01** [comment]
@ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
