### ISSUE TITLE
Readme notes say release version is of form <yyyy-mm-dd>

### ISSUE THREAD

**Issue by jareilly** [Azure/azure-iot-sdk-c#1473]
Readme notes say release version is of form yyyy-mm-dd
but actually it is more like:
git clone -b lts_02_2020 https://github.com/Azure/azure-iot-sdk-c.git
?

**Comment by az-iot-builder-01** [comment]
@jareilly, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
