### ISSUE TITLE
Include Paths?

### ISSUE THREAD

**Issue by apostrophesoftware** [Azure/azure-iot-sdk-c#1480]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

```
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

```
I am trying to write an application using the latest version of the SDK.  I have followed the instructions on how to build the SDK and it builds correctly and the install copies the include and library files to the relevant folders under /user/local.  When I attempt to compile my code I get the following error

1>/usr/local/include/azureiot/azure_c_shared_utility/map.h(19,10): error : azure_c_shared_utility/strings.h: No such file or directory
1>/usr/local/include/azureiot/azure_c_shared_utility/map.h(19,10): error :  #include "azure_c_shared_utility/strings.h"

map.h has the following include lines

```
#include "azure_c_shared_utility/strings.h"
#include "azure_c_shared_utility/crt_abstractions.h"
```

However the azure_c_shared_utility is under the azureiot folder therefore strings.h cannot be found

Changing the includes to

```
#include "azureiot/azure_c_shared_utility/strings.h"
#include "azureiot/azure_c_shared_utility/crt_abstractions.h"
```

allows the build to work correctly?

Is there a problem with the make files or the header files or am I missing something?

Thanks

**Comment by az-iot-builder-01** [comment]
@apostrophesoftware, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
