### ISSUE TITLE
How to Build for Raspberry Pi?

### ISSUE THREAD

**Issue by apostrophesoftware** [Azure/azure-iot-sdk-c#1481]
Which method should I be using to build the SDK on a Raspberry Pi?

I am currently using the following steps, which work!

```
sudo apt-get update
sudo apt-get install -y git cmake build-essential curl libcurl4-openssl-dev libssl-dev uuid-dev

cd ~
mkdir source
cd source
git clone https://github.com/Azure/azure-iot-sdk-c.git
cd azure-iot-sdk-c
git submodule update --init --recursive

mkdir cmake
cd cmake
cmake ..
sudo cmake --build . --target install
```

This works creates all of the required libraries and include files in /usr/local.

I am using Visual Studio 2019 to write a C++ cross platform application, when I build the solution I am getting link errors, such as the ones below

```
1>/usr/bin/ld : error : //usr/local/lib/libiothub_client.a(iothub.c.o): in function `IoTHub_Init':
1>iothub.c : error : (.text+0xc): undefined reference to `platform_init'
1>/usr/bin/ld : error : iothub.c:(.text+0x1c): undefined reference to `xlogging_get_log_function'
1>/usr/bin/ld : error : //usr/local/lib/libiothub_client.a(iothub.c.o): in function `IoTHub_Deinit':
1>iothub.c : error : (.text+0x9c): undefined reference to `platform_deinit'
1>/usr/bin/ld : error : //usr/local/lib/libiothub_client.a(iothub_client_core.c.o): in function `freeHttpWorkerThreadInfo':
1>iothub_client_core.c : error : (.text+0x138): undefined reference to `Lock_Deinit'
1>/usr/bin/ld : error : //usr/local/lib/libiothub_client.a(iothub_client_core.c.o): in function `garbageCollectorImpl':
1>iothub_client_core.c : error : (.text+0x1f0): undefined reference to `singlylinkedlist_get_head_item'
1>/usr/bin/ld : error : iothub_client_core.c:(.text+0x200): undefined reference to `singlylinkedlist_item_get_value'
1>/usr/bin/ld : error : iothub_client_core.c:(.text+0x214): undefined reference to `singlylinkedlist_get_next_item'
1>/usr/bin/ld : error : iothub_client_core.c:(.text+0x228): undefined reference to `Lock'
1>/usr/bin/ld : error : iothub_client_core.c:(.text+0x238): undefined reference to `xlogging_get_log_function'
1>/usr/bin/ld : error : iothub_client_core.c:(.text+0x2a8): undefined reference to `ThreadAPI_Join'
1>/usr/bin/ld : error : iothub_client_core.c:(.text+0x2b8): undefined reference to `xlogging_get_log_function'
1>/usr/bin/ld : error : iothub_client_core.c:(.text+0x310): undefined reference to `singlylinkedlist_remove'
1>/usr/bin/ld : error : iothub_client_core.c:(.text+0x320): undefined reference to `Unlock'
1>/usr/bin/ld : error : iothub_client_core.c:(.text+0x330): undefined reference to `xlogging_get_log_function'
1>/usr/bin/ld : error : iothub_client_core.c:(.text+0x390): undefined reference to `Unlock'
1>/usr/bin/ld : error : iothub_client_core.c:(.text+0x3a0): undefined reference to `xlogging_get_log_function'
1>/usr/bin/ld : error : //usr/local/lib/libiothub_client.a(iothub_client_core.c.o): in function `iothub_ll_message_callback':

```
I am linking against `aziotsharedutil;iothub_client;iothub_client_mqtt_transport;iothub_service_client;parson;umock_c;umqtt`
in the Linker->Input->Library Dependencies section of the project property pages, whch gives this on the command line

`-l"aziotsharedutil" -l"iothub_client" -l"iothub_client_mqtt_transport" -l"iothub_service_client" -l"parson" -l"umock_c" -l"umqtt" `

Should I use a different method to build the initial library on the Pi such as the scripts in~/Source/azure-iot-sdk-c/build_all/linux 

Thanks

**Comment by ewertons** [comment]
@apostrophesoftware , there is a chance the issue you are seeing is because of the order of your link arguments.
Could you try a different sequence, most likely having 
`-l"iothub_client" -l"iothub_client_mqtt_transport" -l"iothub_service_client" -l"umqtt" -l"aziotsharedutil" -l"umock_c" -l"parson"`

Other than that your sequence above seems correct.

**Comment by ewertons** [comment]
We will close this issue for now but if you would like it to be reopened and follow up on this matter, please post a comment requesting so.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@apostrophesoftware, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
