### ISSUE TITLE
Remove DT_InterfaceList_CreateRegistrationMessage

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1484]
`DT_InterfaceList_CreateRegistrationMessage` isn't being called anymore with the new device registration mechanism.  It - and any functions only it calls, along with UT of course - should be removed.

**Comment by jspaith** [comment]
Fixed in some PR.

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
