### ISSUE TITLE
wrong include in provision sample

### ISSUE THREAD

**Issue by malcolmdimeglio** [Azure/azure-iot-sdk-c#1485]
**OS and version used:** Windows 10 Enterprise LTSC
**SDK version used:** LTS_02_2020_Ref01
**Description of the issue:**

It seems that prov_dev_client_sample.c (in _provisioning_client/samples/prov_dev_client_sample/_) is including the wrong header file when the protocol used is HTTP.
```C
#ifdef SAMPLE_HTTP
#include "iothubtransportmqtt.h"
#include "azure_prov_client/prov_transport_http_client.h"
#endif // SAMPLE_HTTP
```

it should include ```"iothubtransporthttp.h"``` instead of ```"iothubtransportmqtt.h"```

**Comment by ericwol-msft** [comment]
thanks will fix this

**Comment by az-iot-builder-01** [comment]
@malcolmdimeglio, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
