### ISSUE TITLE
Unknown CMake command "compileAsC99" Raspbian

### ISSUE THREAD

**Issue by Faratt** [Azure/azure-iot-sdk-c#149]
- **OS and version used:** Raspbian Jessie on R Pi 

- **SDK version used:** 2017-05-05 

# Description of the issue:
On a raspberry Pi running raspbian (with all packages updated), I followed all the steps to setup my dev env, which went smoothly (https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#linux).

However, when I try to execute cmake on a sample, I get the following error message : 
**Unknown CMake command "compileAsC99"**

# Console log of the issue:
pi@raspberrypi:~/test/azure-iot-sdk-c/iothub_client/samples/iothub_client_sample_mqtt $ cmake . && make
CMake Error at CMakeLists.txt:10 (compileAsC99):
  Unknown CMake command "compileAsC99".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

   cmake_minimum_required(VERSION 3.6)

 should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/pi/test/azure-iot-sdk-c/iothub_client/samples/iothub_client_sample_mqtt/CMakeFiles/CMakeOutput.log".

**Comment by enuysa-msft** [comment]
Hi @Faratt ,

Did you  build the SDK as explained at https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#build-the-c-sdk-1 ?

cd azure-iot-sdk-c
mkdir cmake
cd cmake
cmake ..
cmake --build .   

Once you built it you can go and run the sample by using following command:
 
../azure-iot-sdk-c/cmake/iothub_client/samples/iothub_client_sample_mqtt$ ./iothub_client_sample_mqtt

**Comment by enesuysal** [comment]
Hi @Faratt,

Did you test above solution ? Is it worked for you?

**Comment by Faratt** [comment]
I tested again in a fresh installation of raspbian, it works now.
Thank you enesuysal for your help!
