### ISSUE TITLE
crt_abstractions.c is not easy to build with IAR compiler

### ISSUE THREAD

**Issue by Christer-Ekholm** [Azure/azure-iot-sdk-c#1494]
Define in crt_abstractions.c has strong effect in IAR compiler environment
`#define __STDC_WANT_LIB_EXT1__ 1`
It will mark lot of functionsto be deprecated like

`Error[Pe1215]: function "__nounwind memcpy" (declared at line 56 of "C:\swsetup\Iar8.2\arm\inc\c\DLib_Product_string.h") was declared deprecated `

Also following defines are missing in IAR environment
```
#define EINVAL ...
#define ENOMEM ..
```

Version: IAR embedded workbench for ARM. 8.32.2

**Comment by Christer-Ekholm** [comment]
Following would be nice

#ifndef __STDC_WANT_LIB_EXT1__ 
#define __STDC_WANT_LIB_EXT1__ 1
#endif

#ifndef EINVAL 
#define EINVAL -1
#endif

#ifndef EINVAL 
#define ENOMEM -1
#endif

**Comment by ewertons** [comment]
@Christer-Ekholm ,
thanks for your investigation and suggestion.
However, these are defines that are expected to be exposed by the development tool being used.
It would not be advisable to include these macros in the Azure IoT C SDK code itself.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@Christer-Ekholm, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
