### ISSUE TITLE
Using this SDK with Mbed-OS 5.15 or 6.0-alpha

### ISSUE THREAD

**Issue by florianhumblot** [Azure/azure-iot-sdk-c#1499]
Hi,

I am trying to use the AMQP protocol to connect to IOTHub and possibly another AMQP host/gateway.
I have seen a few examples of the use of this library for Mbed-OS 2.0 (such as this one: https://os.mbed.com/users/AzureIoTClient/code/simplesample_amqp/dependencies) but unfortunately I am unable to fetch the library for use in Mbed-studio when using the Mbed-os 6.0 release.

I am using the ESP8266 driver to connect my MCU to the internet, and am also wondering if this library can work with that.

Is there any way to use this SDK with newer MBed versions? or do I need to create my own?

I saw issue #13 but that is 3 years old already and hasn't been updated since.

**Comment by jbobotek** [comment]
Formally we do support mbed 5 on the MXCHIP, so I'm sure the OS will work with our SDK. Are you planning on using an esp8266? It's available RAM could be a limiting factor. 

Overall, important to adaption are filling in/linking with the adapter layers (socketio, tls). Does your release of mbed include a tls library?

**Comment by ewertons** [comment]
@florianhumblot ,
thanks for your request but we do not have plans to upgrade the support for the new versions of the MBED OS.
For that platform, please explore the new embedded C SDK: https://github.com/azure/azure-sdk-for-c
Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment]
@florianhumblot, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
