### ISSUE TITLE
How to convert ek.pub got from tpm2_tools for enrolling Azure IoT via TPM

### ISSUE THREAD

**Issue by RandyWang131** [Azure/azure-iot-sdk-c#1502]
Hi,
I use raspberry pi 0 with Infineon TPM SLB9670 , and install tpm2-tss, tpm2-tools
I can successfully create TPM EK with tpm2_getpubek -H 0x81010000 -g 0x01 -f ek.pub

I used command #base64 ek.pub then copy the output to enroll to Azure IoT.
but it show the endorsement key is invalid. as following

{"message":"BadRequest:{\r\n \"errorCode\": 400004,\r\n \"trackingId\": \"3778640d-0ac1-413f-b2de-2f4bcf937ec2\",\r\n \"message\": \"Endorsement
 key is invalid, or does not match the Enrollment.\",\r\n \"timestampUtc\": \"2020-03-10T15:08:16.429478Z\"\r\n}"}

1) I'm using Real TPM the Infineon SLB9670

2) The OS is Raspbian and kernel 4.4.22+

otherwise, the TPM ek.pub I got via Azure IoT SDK:

AToAAQALAAMAsgAgg3GXZ0SEs/gakMyNRqXXJP1S124GUgtk8qHaGzMUaaoABgCAAEMAEAgAAAAAAAEAwNpubnU/fnpf2wdPnmkzsgZFEXd5A3vTrk442yWnvfMjLu2dXddR63sNdbCUKodl3wlShfYqz5KPhoCyZsgLehD/2JBORUfloQBJJiyNvDuv81KyuyJHkYAQl0devdbzMN4wl1J4rV11eUHm9OJGlW3fAL6g2p6MLxwdYw0umbr51RcN1ufMK15AhBNXb/IPT3vTDk2wXV5Nus22g4HDsoO2J773dAnrHHu0ukvfxb1ElEz1mrk6t57ccN06iTfoxIWoLQYus1VI8BrOfLX0I3hl5ooJQezNEppsjtbtKsKIbUQzdzQkBLSM+1unxITZVo3QbOYwje/6LpEDDSLT2w==

and the TPM ek.pub I got by tpm2-tools:

OgEAAAEACwCyAAMAIACDcZdnRISz+BqQzI1Gpdck/VLXbgZSC2TyodobMxRpqgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAIAAQwAQAAAAAAAACAAAAAAAAAABkC9CFpVqCBJPG3Pbu+uO/6w0C+ab14Zhq5BTa3Z8dngozK0dFx14ltj/V6yO9DoboWdcchpsXfeQXVThFuiBmjrbO4VpyzlE5CPBjd0sODoOFvow+X/m2A+HhDea+iRujKaj3CvYjfwKbOQl01s8Am0X8RJpQ/FmH9lL4Zon6HXfcCDZ6IaW+XagyMjCH1tqh0SXbGVAgyLNO5W8laTJcQiIirk/kQ6EfxvWYnXhatvLBNg90qcFl3MjdnWz+ouZOiez6fB9Bpi17YtMvMaE1PEXElY0hujEoMP+VHzcqYKsZdViARBBfnCFWD0e8dIE3yzayU9kWHaMpxOoisIDUQAA

How to convert it to enroll Azure IoT ?

Thanks.

**Comment by CIPop** [comment]
@amarochk Do you know what the EK / handle needs to be for the TPM EK key to be extracted the way Azure Provisioning wants it?

@RandyWang131 I don't know the details on how our TSS driver exports the key. I suspect it's something to do with the options you're passing to the tool: according to https://manpages.debian.org/testing/tpm2-tools/tpm2_getpubek.8, -g specifies the algorithm (0x0001 is TPM_ALG_RSA for example, -H is the handle). Outside of the source-code we don't document the details of what our Provisioning Service algorithm requires.

In general, we advise against using a tool outside of the maintained SDK. That guards your application against any future Provisioning with TPM algorithm changes in the future.

**Comment by az-iot-builder-01** [comment]
@RandyWang131, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by amarochk** [comment]
The valid range for EK handles (as defined by TCG) is 0x81010000 – 0x810100FF. Windows normally uses 0x81010000. You may want to have a look at the SDK code to double check.

**Comment by asergaz** [comment]
@RandyWang131 is your question answered? 

@CIPop @amarochk @ewertons  fyi this started on a thread on MSDN: https://social.msdn.microsoft.com/Forums/en-US/f3783986-3cd4-4ca6-969b-c302840ac775/how-to-convert-ekpub-for-enrolling-azure-iot-via-tpm?forum=azureiothub
