### ISSUE TITLE
Sending pending telemetry messages on module termination

### ISSUE THREAD

**Issue by gri6507** [Azure/azure-iot-sdk-c#1506]
I have a module which queues up data to be sent to the cloud in accumulated batches via `IoTHubModuleClient_LL_SendEventAsync()` where I pass a completion callback function pointer. My completion function is very simple: `printf("Result is: %s\n",  result_msg(MU_ENUM_TO_STRING(IOTHUB_CLIENT_CONFIRMATION_RESULT, result)));`

Typically, the result code is `IOTHUB_CLIENT_CONFIRMATION_OK`. However, I also want to flush any pending accumulated data in one last message to the cloud when my module instance is being updated due to a deployment policy change. I have a signal handler in my module which catches TERM signal that iotedge runtime sends when the old module instance is being stopped. I added a call to send my unsent accumulated data into this signal handler. However, no message goes out and the callback function prints `IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY`.

What is the correct way to send a telemetry message **when** the module is asked to terminate for any reason (e.g. due to upgrade)?

**Comment by ewertons** [comment]
Hi @gri6507 ,
the azure-iot-sdk-c code seems to be behaving accordingly.
Your question is more related to the logic contained in the Azure IoT Edge code.
We posted an issue on the proper repo on your behalf.
https://github.com/Azure/iotedge/issues/3287

Please feel free to reopen this issue if you would like to follow up on any points related to the code of azure-iot-sdk-c.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@gri6507, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
