### ISSUE TITLE
I am trying to use Azure Iothub sdk for the mbed devices, however, there are two libraries that can not be accessed, which are azureiot_common and proton-c-mbed. Is there anyone know why?

### ISSUE THREAD

**Issue by shaoenliu** [Azure/azure-iot-sdk-c#151]
- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by olivierbloch** [comment]
Hi @shaoenliu 
I think you are using an older version of our mbed library.
Can you please go through the get-started doc [here ](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/mbed_get_started.md)and let us know if that works for you?
Note that we now also have an mqtt sample that is not yet referenced in the doc: https://developer.mbed.org/users/AzureIoTClient/code/iothub_client_sample_mqtt/
Thanks

**Comment by shaoenliu** [comment]
Hi @olivierbloch 
Thanks a lot for the information, I think the amqp example works good for me, here is what is showing from the terminal`tarting the IoTHub client sample AMQP...
Info: IoT Hub SDK for C, version 1.1.16
Info: Retry policy set (5, timeout = 0)
IoTHubClient_SetMessageCallback...successful.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
Info: Transport state changed from AMQP_TRANSPORT_STATE_NOT_CONNECTED to AMQP_TRANSPORT_STATE_CONNECTING
Info: Transport state changed from AMQP_TRANSPORT_STATE_CONNECTING to AMQP_TRANSPORT_STATE_CONNECTED`

But when I try the temp_sensor_anomaly code, there are compile errors that I can not fix, so I am guessing that it is because of lacking of those two libraries, because I saw those two libraries from your video, but for me, my access was denied when i try to access those two libraries. I guess that might be the reason that the code that can not be compiled. Do you know what could be the reason?

**Comment by tameraw** [comment]
@shaoenliu - Sorry for the inconvenience. The temp_sensor_anomaly is an outdated sample and will be removed. Please use the sample by @olivierbloch. Thanks.

**Comment by shaoenliu** [comment]
hi @tameraw Thank you, so is it possible to send the data from sensor to IoThub by amqp sample? For example the temperature...

**Comment by shaoenliu** [comment]
Because when I run the amqp sample, it is only showing that the device is connected to the IoThub, but no data z.B. windspeed was sent. What could be the problem?

**Comment by tameraw** [comment]
Closing this issue. Let us know if you were not able to run the most recent samples.
