### ISSUE TITLE
Why is there no azure-iot-sdk-go?

### ISSUE THREAD

**Issue by shaunco** [Azure/azure-iot-sdk-c#1512]
Apologies for posting this in the C sdk, but the general azure-iot-sdks project is no longer accepting issues...

Why is there no azure-iot-sdk for go? There are ones for C, Python, Node.js, Java, and .NET, but no go. On the management side there is the azure-sdk-for-go, but it doesn't do any of the client side things you'd want on a edge device talking to IoT Hub. Sure, I can cgo this SDK, but that introduces a whole host of headaches for the average go developer, especially the part where go's cross compiling from any platform to any platform is disabled when you use cgo to bring in C libraries. 

There are a handful of projects that have started to implement IoT Hub support, the most complete being https://github.com/amenzhinsky/iothub ... which is mostly complete (D2C, C2D, twin state, and direct messages), but only over MQTT with private keys or X.509, and just recently added MQTT over WebSockets. No AMQP, no HTTP, and no retry logic.

The one that I'm really wishing for at the moment is a provisioning client SDK for go, but it looks like I'll end up writing one.

All that said, please pass along a request to the powers that be that the go world would really love an official MS IoT client SDK for go.

**Comment by ericwol-msft** [comment]
The official repo for azure go is https://github.com/Azure/azure-sdk-for-go
There is a plan for a IoT sdk for go, but I have no dates to communicate. 

When it is available, it will be in the above repo

**Comment by az-iot-builder-01** [comment]
@shaunco, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
