### ISSUE TITLE
prov_dev_client_sample

### ISSUE THREAD

**Issue by omersalam** [Azure/azure-iot-sdk-c#1516]
Hi
I am unable to find, where to pass certificate which i created using c sdk in prov_dev_client_sample. This sample is only taking IDScope and global URI.

**Comment by danewalton** [comment]
Hi @omersalam 
DPS uses the HSM API's to use the certificates but it requires a little work to get started with the samples.
[Here in the CMakeLists.txt file](https://github.com/Azure/azure-iot-sdk-c/blob/354cd4297897008f203132f78ff573d31739a5a2/CMakeLists.txt#L53-L54) we have options for setting a custom HSM. You can use the example which is [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/samples/custom_hsm_example/custom_hsm_example.c) for the purposes of these samples.

So the flow would work like this:
- Go into the `.c` file I listed above and input your `COMMON_NAME` [here](https://github.com/Azure/azure-iot-sdk-c/blob/354cd4297897008f203132f78ff573d31739a5a2/provisioning_client/samples/custom_hsm_example/custom_hsm_example.c#L11), the `CERTIFICATE` [here](https://github.com/Azure/azure-iot-sdk-c/blob/354cd4297897008f203132f78ff573d31739a5a2/provisioning_client/samples/custom_hsm_example/custom_hsm_example.c#L12), and the `PRIVATE_KEY` [here](https://github.com/Azure/azure-iot-sdk-c/blob/354cd4297897008f203132f78ff573d31739a5a2/provisioning_client/samples/custom_hsm_example/custom_hsm_example.c#L15).
- From CMake, your generation command would look something like:
```bash
cmake -Duse_prov_client=ON -Dhsm_type_custom=ON -Dhsm_custom_lib="/home/dwalton/repos/azure-iot-sdk-c/build/provisioning_client/samples/custom_hsm_example/libcustom_hsm_example.a"
```

Notice I have the full path to the compiled `.a` file for the custom hsm. After that, the provisioning client should be using your custom hsm to get the necessary certificate information to connect and provision.

Hopefully that helps!

**Comment by danewalton** [comment]
Hi @omersalam if you have any further issues please reopen this or open another issue

**Comment by az-iot-builder-01** [comment]
@omersalam, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
