### ISSUE TITLE
Unable de recurse correctly on all modules

### ISSUE THREAD

**Issue by Moncefmd** [Azure/azure-iot-sdk-c#152]
- **OS and version used:** Ubuntu 16.04 

- **SDK version used:** 2017-06-02 

# Description of the issue:

Impossible to recurse into all submodules, which makes the build fail (2017-05-05 works just fine)

# Console log of the issue:

`:~/Source$ git clone -b 2017-06-02 --recursive https://github.com/Azure/azure-iot-sdk-c.git
Cloning into 'azure-iot-sdk-c'...
remote: Counting objects: 48610, done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 48610 (delta 84), reused 62 (delta 30), pack-reused 48443
Receiving objects: 100% (48610/48610), 43.44 MiB | 3.93 MiB/s, done.
Resolving deltas: 100% (30575/30575), done.
Checking connectivity... done.
Note: checking out '54ada512f80cff0c710cb1ede2199380888e0f1a'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Submodule 'azure-c-shared-utility' (https://github.com/Azure/azure-c-shared-utility.git) registered for path 'c-utility'
Submodule 'iothub_service_client/parson' (https://github.com/kgabis/parson) registered for path 'iothub_service_client/parson'
Submodule 'parson' (https://github.com/kgabis/parson) registered for path 'parson'
Submodule 'azure-uamqp-c' (https://github.com/Azure/azure-uamqp-c.git) registered for path 'uamqp'
Submodule 'azure-umqtt-c' (https://github.com/Azure/azure-umqtt-c.git) registered for path 'umqtt'
Cloning into 'c-utility'...
remote: Counting objects: 15119, done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 15119 (delta 41), reused 63 (delta 18), pack-reused 15009
Receiving objects: 100% (15119/15119), 8.44 MiB | 3.66 MiB/s, done.
Resolving deltas: 100% (10524/10524), done.
Checking connectivity... done.
Submodule path 'c-utility': checked out '9133cf2f5831e29fef82a176f27b2b492f9b5fb9'
Submodule 'testtools/ctest' (https://github.com/Azure/azure-ctest.git) registered for path 'testtools/ctest'
Submodule 'testtools/testrunner' (https://github.com/Azure/azure-c-testrunnerswitcher.git) registered for path 'testtools/testrunner'
Submodule 'testtools/umock-c' (https://github.com/Azure/umock-c.git) registered for path 'testtools/umock-c'
Cloning into 'testtools/ctest'...
remote: Counting objects: 254, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 254 (delta 0), reused 1 (delta 0), pack-reused 251
Receiving objects: 100% (254/254), 166.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (123/123), done.
Checking connectivity... done.
Submodule path 'c-utility/testtools/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'testtools/testrunner'...
remote: Counting objects: 212, done.
remote: Total 212 (delta 0), reused 0 (delta 0), pack-reused 212
Receiving objects: 100% (212/212), 837.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (106/106), done.
Checking connectivity... done.
Submodule path 'c-utility/testtools/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Cloning into 'testtools/umock-c'...
remote: Counting objects: 911, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 911 (delta 0), reused 2 (delta 0), pack-reused 907
Receiving objects: 100% (911/911), 397.34 KiB | 0 bytes/s, done.
Resolving deltas: 100% (619/619), done.
Checking connectivity... done.
Submodule path 'c-utility/testtools/umock-c': checked out '0a71d26c3adf36292620f83210ae6f4b60703c1b'
Submodule 'deps/azure-ctest' (https://github.com/Azure/azure-ctest.git) registered for path 'deps/ctest'
Submodule 'deps/testrunner' (https://github.com/Azure/azure-c-testrunnerswitcher.git) registered for path 'deps/testrunner'
Cloning into 'deps/ctest'...
remote: Counting objects: 254, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 254 (delta 0), reused 1 (delta 0), pack-reused 251
Receiving objects: 100% (254/254), 166.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (123/123), done.
Checking connectivity... done.
Submodule path 'c-utility/testtools/umock-c/deps/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'deps/testrunner'...
remote: Counting objects: 212, done.
remote: Total 212 (delta 0), reused 0 (delta 0), pack-reused 212
Receiving objects: 100% (212/212), 837.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (106/106), done.
Checking connectivity... done.
Submodule path 'c-utility/testtools/umock-c/deps/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Cloning into 'iothub_service_client/parson'...
remote: Counting objects: 511, done.
remote: Total 511 (delta 0), reused 0 (delta 0), pack-reused 511
Receiving objects: 100% (511/511), 275.29 KiB | 0 bytes/s, done.
Resolving deltas: 100% (271/271), done.
Checking connectivity... done.
Submodule path 'iothub_service_client/parson': checked out 'ba2a854c27b24068977e5827bd129d0531f4503c'
Cloning into 'parson'...
remote: Counting objects: 511, done.
remote: Total 511 (delta 0), reused 0 (delta 0), pack-reused 511
Receiving objects: 100% (511/511), 275.29 KiB | 0 bytes/s, done.
Resolving deltas: 100% (271/271), done.
Checking connectivity... done.
Submodule path 'parson': checked out 'ba2a854c27b24068977e5827bd129d0531f4503c'
Cloning into 'uamqp'...
remote: Counting objects: 4380, done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 4380 (delta 22), reused 28 (delta 10), pack-reused 4325
Receiving objects: 100% (4380/4380), 2.74 MiB | 3.68 MiB/s, done.
Resolving deltas: 100% (2742/2742), done.
Checking connectivity... done.
Submodule path 'uamqp': checked out '52a8d79075643a485a02314f541cb46733e7e45d'
Submodule 'deps/azure-c-shared-utility' (https://www.github.com/Azure/azure-c-shared-utility) registered for path 'deps/azure-c-shared-utility'
Submodule 'deps/azure-c-testrunnerswitcher' (https://www.github.com/Azure/azure-c-testrunnerswitcher) registered for path 'deps/azure-c-testrunnerswitcher'
Submodule 'deps/azure-ctest' (https://www.github.com/Azure/azure-ctest) registered for path 'deps/azure-ctest'
Submodule 'deps/umock-c' (https://www.github.com/Azure/umock-c) registered for path 'deps/umock-c'
Cloning into 'deps/azure-c-shared-utility'...
remote: Counting objects: 15119, done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 15119 (delta 41), reused 63 (delta 18), pack-reused 15009
Receiving objects: 100% (15119/15119), 8.44 MiB | 3.89 MiB/s, done.
Resolving deltas: 100% (10524/10524), done.
Checking connectivity... done.
Submodule path 'uamqp/deps/azure-c-shared-utility': checked out '9133cf2f5831e29fef82a176f27b2b492f9b5fb9'
Submodule 'testtools/ctest' (https://github.com/Azure/azure-ctest.git) registered for path 'testtools/ctest'
Submodule 'testtools/testrunner' (https://github.com/Azure/azure-c-testrunnerswitcher.git) registered for path 'testtools/testrunner'
Submodule 'testtools/umock-c' (https://github.com/Azure/umock-c.git) registered for path 'testtools/umock-c'
Cloning into 'testtools/ctest'...
remote: Counting objects: 254, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 254 (delta 0), reused 1 (delta 0), pack-reused 251
Receiving objects: 100% (254/254), 166.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (123/123), done.
Checking connectivity... done.
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'testtools/testrunner'...
remote: Counting objects: 212, done.
remote: Total 212 (delta 0), reused 0 (delta 0), pack-reused 212
Receiving objects: 100% (212/212), 837.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (106/106), done.
Checking connectivity... done.
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Cloning into 'testtools/umock-c'...
remote: Counting objects: 911, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 911 (delta 0), reused 2 (delta 0), pack-reused 907
Receiving objects: 100% (911/911), 397.34 KiB | 0 bytes/s, done.
Resolving deltas: 100% (619/619), done.
Checking connectivity... done.
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/umock-c': checked out '0a71d26c3adf36292620f83210ae6f4b60703c1b'
Submodule 'deps/azure-ctest' (https://github.com/Azure/azure-ctest.git) registered for path 'deps/ctest'
Submodule 'deps/testrunner' (https://github.com/Azure/azure-c-testrunnerswitcher.git) registered for path 'deps/testrunner'
Cloning into 'deps/ctest'...
remote: Counting objects: 254, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 254 (delta 0), reused 1 (delta 0), pack-reused 251
Receiving objects: 100% (254/254), 166.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (123/123), done.
Checking connectivity... done.
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/umock-c/deps/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'deps/testrunner'...
remote: Counting objects: 212, done.
remote: Total 212 (delta 0), reused 0 (delta 0), pack-reused 212
Receiving objects: 100% (212/212), 837.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (106/106), done.
Checking connectivity... done.
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/umock-c/deps/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Cloning into 'deps/azure-c-testrunnerswitcher'...
remote: Counting objects: 212, done.
remote: Total 212 (delta 0), reused 0 (delta 0), pack-reused 212
Receiving objects: 100% (212/212), 837.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (106/106), done.
Checking connectivity... done.
fatal: reference is not a tree: 5c8504fd77485b092ad0f16bbab755f899da09f1
Cloning into 'deps/azure-ctest'...
remote: Counting objects: 254, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 254 (delta 0), reused 1 (delta 0), pack-reused 251
Receiving objects: 100% (254/254), 166.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (123/123), done.
Checking connectivity... done.
Submodule path 'uamqp/deps/azure-ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'deps/umock-c'...
remote: Counting objects: 911, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 911 (delta 0), reused 2 (delta 0), pack-reused 907
Receiving objects: 100% (911/911), 397.34 KiB | 0 bytes/s, done.
Resolving deltas: 100% (619/619), done.
Checking connectivity... done.
Submodule path 'uamqp/deps/umock-c': checked out '0a71d26c3adf36292620f83210ae6f4b60703c1b'
Submodule 'deps/azure-ctest' (https://github.com/Azure/azure-ctest.git) registered for path 'deps/ctest'
Submodule 'deps/testrunner' (https://github.com/Azure/azure-c-testrunnerswitcher.git) registered for path 'deps/testrunner'
Cloning into 'deps/ctest'...
remote: Counting objects: 254, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 254 (delta 0), reused 1 (delta 0), pack-reused 251
Receiving objects: 100% (254/254), 166.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (123/123), done.
Checking connectivity... done.
Submodule path 'uamqp/deps/umock-c/deps/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'deps/testrunner'...
remote: Counting objects: 212, done.
remote: Total 212 (delta 0), reused 0 (delta 0), pack-reused 212
Receiving objects: 100% (212/212), 837.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (106/106), done.
Checking connectivity... done.
Submodule path 'uamqp/deps/umock-c/deps/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Unable to checkout '5c8504fd77485b092ad0f16bbab755f899da09f1' in submodule path 'uamqp/deps/azure-c-testrunnerswitcher'
Cloning into 'umqtt'...
remote: Counting objects: 2142, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 2142 (delta 13), reused 18 (delta 4), pack-reused 2104
Receiving objects: 100% (2142/2142), 583.56 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1148/1148), done.
Checking connectivity... done.
Submodule path 'umqtt': checked out '5bddc79c282b99ba9e1bdf988206ed268d785824'
Submodule 'azure-c-shared-utility' (https://github.com/Azure/azure-c-shared-utility.git) registered for path 'c-utility'
Cloning into 'c-utility'...
remote: Counting objects: 15119, done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 15119 (delta 41), reused 63 (delta 18), pack-reused 15009
Receiving objects: 100% (15119/15119), 8.44 MiB | 3.90 MiB/s, done.
Resolving deltas: 100% (10524/10524), done.
Checking connectivity... done.
Submodule path 'umqtt/c-utility': checked out '9133cf2f5831e29fef82a176f27b2b492f9b5fb9'
Submodule 'testtools/ctest' (https://github.com/Azure/azure-ctest.git) registered for path 'testtools/ctest'
Submodule 'testtools/testrunner' (https://github.com/Azure/azure-c-testrunnerswitcher.git) registered for path 'testtools/testrunner'
Submodule 'testtools/umock-c' (https://github.com/Azure/umock-c.git) registered for path 'testtools/umock-c'
Cloning into 'testtools/ctest'...
remote: Counting objects: 254, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 254 (delta 0), reused 1 (delta 0), pack-reused 251
Receiving objects: 100% (254/254), 166.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (123/123), done.
Checking connectivity... done.
Submodule path 'umqtt/c-utility/testtools/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'testtools/testrunner'...
remote: Counting objects: 212, done.
remote: Total 212 (delta 0), reused 0 (delta 0), pack-reused 212
Receiving objects: 100% (212/212), 837.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (106/106), done.
Checking connectivity... done.
Submodule path 'umqtt/c-utility/testtools/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Cloning into 'testtools/umock-c'...
remote: Counting objects: 911, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 911 (delta 0), reused 2 (delta 0), pack-reused 907
Receiving objects: 100% (911/911), 397.34 KiB | 0 bytes/s, done.
Resolving deltas: 100% (619/619), done.
Checking connectivity... done.
Submodule path 'umqtt/c-utility/testtools/umock-c': checked out '0a71d26c3adf36292620f83210ae6f4b60703c1b'
Submodule 'deps/azure-ctest' (https://github.com/Azure/azure-ctest.git) registered for path 'deps/ctest'
Submodule 'deps/testrunner' (https://github.com/Azure/azure-c-testrunnerswitcher.git) registered for path 'deps/testrunner'
Cloning into 'deps/ctest'...
remote: Counting objects: 254, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 254 (delta 0), reused 1 (delta 0), pack-reused 251
Receiving objects: 100% (254/254), 166.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (123/123), done.
Checking connectivity... done.
Submodule path 'umqtt/c-utility/testtools/umock-c/deps/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'deps/testrunner'...
remote: Counting objects: 212, done.
remote: Total 212 (delta 0), reused 0 (delta 0), pack-reused 212
Receiving objects: 100% (212/212), 837.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (106/106), done.
Checking connectivity... done.
Submodule path 'umqtt/c-utility/testtools/umock-c/deps/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Failed to recurse into submodule path 'uamqp'`

**Comment by ewertons** [comment]
Hi @Moncefmd , this has been fixed.
Could you please verify? 

Here is my output (verbose traces removed for better presentation):

```
ewertons@ewertons-ubuntu02:~/temp$ git clone -b 2017-06-02 --recursive https://github.com/Azure/azure-iot-sdk-c.git
Cloning into 'azure-iot-sdk-c'...
...
Note: checking out 'a2a5a87f4e04ec339b7603d88a567d91bf5d18b6'.
...
Cloning into 'c-utility'...
Submodule path 'c-utility': checked out '9133cf2f5831e29fef82a176f27b2b492f9b5fb9'
Cloning into 'testtools/ctest'...
Submodule path 'c-utility/testtools/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'testtools/testrunner'...
Submodule path 'c-utility/testtools/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Cloning into 'testtools/umock-c'...
Submodule path 'c-utility/testtools/umock-c': checked out '0a71d26c3adf36292620f83210ae6f4b60703c1b'
Cloning into 'deps/ctest'...
Submodule path 'c-utility/testtools/umock-c/deps/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'deps/testrunner'...
Submodule path 'c-utility/testtools/umock-c/deps/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Cloning into 'iothub_service_client/parson'...
Submodule path 'iothub_service_client/parson': checked out 'ba2a854c27b24068977e5827bd129d0531f4503c'
Cloning into 'parson'...
Submodule path 'parson': checked out 'ba2a854c27b24068977e5827bd129d0531f4503c'
Cloning into 'uamqp'...
Submodule path 'uamqp': checked out 'ccd94c06a8a44c0920f3f22f40f0b3a911faae67'
Cloning into 'deps/azure-c-shared-utility'...
Submodule path 'uamqp/deps/azure-c-shared-utility': checked out '9133cf2f5831e29fef82a176f27b2b492f9b5fb9'
Cloning into 'testtools/ctest'...
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'testtools/testrunner'...
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Cloning into 'testtools/umock-c'...
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/umock-c': checked out '0a71d26c3adf36292620f83210ae6f4b60703c1b'
Cloning into 'deps/ctest'...
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/umock-c/deps/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'deps/testrunner'...
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/umock-c/deps/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Cloning into 'deps/azure-c-testrunnerswitcher'...
Submodule path 'uamqp/deps/azure-c-testrunnerswitcher': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Cloning into 'deps/azure-ctest'...
Submodule path 'uamqp/deps/azure-ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'deps/umock-c'...
Submodule path 'uamqp/deps/umock-c': checked out '0a71d26c3adf36292620f83210ae6f4b60703c1b'
Cloning into 'deps/ctest'...
Submodule path 'uamqp/deps/umock-c/deps/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'deps/testrunner'...
Submodule path 'uamqp/deps/umock-c/deps/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Cloning into 'umqtt'...
Submodule path 'umqtt': checked out '5bddc79c282b99ba9e1bdf988206ed268d785824'
Cloning into 'c-utility'...
Submodule path 'umqtt/c-utility': checked out '9133cf2f5831e29fef82a176f27b2b492f9b5fb9'
Cloning into 'testtools/ctest'...
Submodule path 'umqtt/c-utility/testtools/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'testtools/testrunner'...
Submodule path 'umqtt/c-utility/testtools/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
Cloning into 'testtools/umock-c'...
Submodule path 'umqtt/c-utility/testtools/umock-c': checked out '0a71d26c3adf36292620f83210ae6f4b60703c1b'
Cloning into 'deps/ctest'...
Submodule path 'umqtt/c-utility/testtools/umock-c/deps/ctest': checked out 'cc484ce3ce657893262b94933dae0964dda0edcc'
Cloning into 'deps/testrunner'...
Submodule path 'umqtt/c-utility/testtools/umock-c/deps/testrunner': checked out '92a70ae1b38ad1ae014f46c0b8821cc6b4650247'
```

**Comment by Moncefmd** [comment]
Problem is solved. No more errors ! Thank you.
