### ISSUE TITLE
tls error in iothub_client_sample_mqtt_esp8266 

### ISSUE THREAD

**Issue by tinfoilbroker** [Azure/azure-iot-sdk-c#1520]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Lenovo Thinkpad T480s, Manjaro, esp-idf v4.1-beta1, esp-idf toolchain

**SDK Version (Please Give Commit SHA if Manually Compiling)**

esp-azure uses the following commit: 5d9a19a5e

**Protocol**

MQTT

**Describe the Bug**
When I run iothub_client_sample_mqtt from the esp-azure repository, which is basically the same program as iothub_client_sample_mqtt_esp8266, I get a tls error after some time. The time differs though. Sometimes it's 20 minutes, sometimes just 6.

It doesn't happen in the sample program only. I actually encountered the problem in another project and worked backwards until I was only using the sample.

**Console Logs**
Sometimes it's this error: 

E (436901) esp-tls: couldn't get hostname for : iothub.azure-devices.net:
Error: Time:Thu Apr  9 07:41:45 2020 File:/home/tinfoilbroker/esp/esp-azure/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2355 mqtt_client timed out waiting for CONNACK
Error: Time:Thu Apr  9 07:41:45 2020 File:/home/tinfoilbroker/esp/esp-azure/port/src/tlsio_esp_tls.c Func:tlsio_esp_tls_destroy Line:152 tlsio_esp_tls_destroy called while not in TLSIO_STATE_CLOSED.

Other times it's this one:

-> 10:50:15 PINGREQ
<- 10:50:15 PINGRESP
IoTHubClient_LL_SendEventAsync accepted message [9] for transmission to IoT Hub.
-> 10:51:16 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/test-ota/messages/events/temperatureAlert=false | PACKET_ID: 12 | PAYLOAD_LEN: 83
<- 10:51:16 PUBACK | PACKET_ID: 12
Confirmation[9] received for message tracking id = 9 with result = IOTHUB_CLIENT_CONFIRMATION_OK
-> 10:54:08 DISCONNECT

Connection Status result:IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, Connection Status reason: IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN

-> 10:54:11 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: XXX | PWD: XXXX | CLEAN: 0
<- 10:54:11 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0

Connection Status result:IOTHUB_CLIENT_CONNECTION_AUTHENTICATED, Connection Status reason: IOTHUB_CLIENT_CONNECTION_OK

-> 10:54:11 SUBSCRIBE | PACKET_ID: 13 | TOPIC_NAME: devices/test-ota/messages/devicebound/# | QOS: 1
<- 10:54:13 SUBACK | PACKET_ID: 13 | RETURN_CODE: 1
IoTHubClient_LL_SendEventAsync accepted message [10] for transmission to IoT Hub.
-> 10:56:17 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/test-ota/messages/events/temperatureAlert=true | PACKET_ID: 14 | PAYLOAD_LEN: 83
<- 10:56:17 PUBACK | PACKET_ID: 14
Confirmation[10] received for message tracking id = 10 with result = IOTHUB_CLIENT_CONFIRMATION_OK
I (3180693) wifi: state: run -> init (6c0)
I (3180693) wifi: pm stop, total sleep time: 2938810211 us / 3175733157 us

I (3180693) wifi: new:<10,0>, old:<10,0>, ap:<255,255>, sta:<10,0>, prof:1
W (3180713) mbedtls: ssl_tls.c:4973 mbedtls_ssl_fetch_input() returned -76 (-0x004c)

W (3180713) mbedtls: ssl_tls.c:4344 ssl_get_next_record() returned -76 (-0x004c)

W (3180713) mbedtls: ssl_tls.c:8335 mbedtls_ssl_read_record() returned -76 (-0x004c)

E (3180723) esp-tls-mbedtls: read error :-76:
I (3180823) wifi: new:<10,0>, old:<10,0>, ap:<255,255>, sta:<10,0>, prof:1
I (3180823) wifi: state: init -> auth (b0)
I (3180823) wifi: state: auth -> assoc (0)
I (3180833) wifi: state: assoc -> run (10)
I (3180853) wifi: connected with XXX, aid = 9, channel 10, BW20, bssid = XXX
I (3180853) wifi: security type: 3, phy: bgn, rssi: -64
I (3180863) wifi: pm start, type: 1

I (3180883) wifi: AP's beacon interval = 102400 us, DTIM period = 5
I (3182693) esp_netif_handlers: sta ip: 192.168.1.245, mask: 255.255.255.0, gw: 192.168.1.1
Error: Time:Wed Apr 29 11:00:17 2020 File:/home/tinfoilbroker/esp/esp-azure/port/src/tlsio_esp_tls.c Func:tlsio_esp_tls_send_async Line:551 tlsio_esp_tls_send_async without a prior successful open
Error: Time:Wed Apr 29 11:00:17 2020 File:/home/tinfoilbroker/esp/esp-azure/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:371 550: Failure sending control packet data
-> 11:00:17 PINGREQ

**Comment by ericwol-msft** [comment]
You should see this IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN when the SAS token expires. The default duration is 1 hour, and when it expires, it will reconnect with an updated SAS token. You can extend the SAS valid lifetime, or use cert based auth, which will not cause reconnects.

**Comment by ewertons** [comment]
If you would like to get more information about SAS token logic with MQTT, please refer to our documentation: 
https://github.com/Azure/azure-iot-sdk-c/blob/LTS_07_2020_Ref01/doc/connection_and_messaging_reliability.md#connection-authentication
and 
https://github.com/Azure/azure-iot-sdk-c/blob/LTS_07_2020_Ref01/doc/Iothub_sdk_options.md#standard-transport (please see option `OPTION_SAS_TOKEN_LIFETIME`).

We will close this issue for now, but please feel free to reopen it if you would like to follow up on this matter.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@tinfoilbroker, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
