### ISSUE TITLE
PnP components should not require the interface id

### ISSUE THREAD

**Issue by rido-min** [Azure/azure-iot-sdk-c#1528]
.. from https://github.com/Azure/azure-iot-sdk-c/pull/1527#discussion_r423374428

With the latest PnP discovery protocol, the interface id of the PnP component should not be included in the component implementation.

https://github.com/Azure/azure-iot-sdk-c/blob/07dc45d067f482c838446e290e35ec99b7c59336/digitaltwin_client/src/dt_interface_client.c#L559

The same rule should be applied to other languages

/cc @jspaith @jebrando

**Comment by jspaith** [comment]
Closing for now as `public-preview-pnp` isn't currently planned release mechanism.  #pnp-archive

**Comment by az-iot-builder-01** [comment]
@rido-min, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
