### ISSUE TITLE
A reconnect is only executed if a PING packet couldn't be transmitted (MQTT)

### ISSUE THREAD

**Issue by Fyusel** [Azure/azure-iot-sdk-c#1541]
**Development Machine, OS, Compiler**

Lenovo Thinkpad T480s
OS: Ubuntu 18.04
Target: esp32 (esp-idf v4.2)

**SDK Version**

based on https://github.com/espressif/esp-azure which is using
azure-iot-sdk-c commit 5d9a19a5e5ce6f4974d333bd28f432ee9284f70b

**Protocol**

MQTT

**Short description of our program**

There is a transmitter task which is executed every minute in order to send sensor data to Azure (using IoTHubClient).
The _keepAliveInterval_ of IoTHubClient is set to 240 seconds per default (https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L43 ).

**Description of the problem**

As long as there is a stable connection everything works fine. If the connection is lost somehow e.g. unstable WLAN or internet connection the connection is cut and not reconnected.

**Steps to reproduce**

This behavior can also be reproduced by using the _iothub_client_sample_mqtt_ sample (https://github.com/espressif/esp-azure/tree/master/examples/iothub_client_sample_mqtt).

• set the "Time delay in Milliseconds between two consecutive message" to 30000ms (menuconfig)
• build and flash the program
• after some packages were sent successfully perform one of the following steps:
∘ disable your WLAN for some minutes
∘ deactivate the IoT device in Azure (prefered one -> easier and faster)
• In the moment you have deactivated the device in Azure you will see the following output:
∘ E (71254) esp-tls-mbedtls: read error :-76:
• Output when trying to sent a new package in this state::
```esp-azure/port/src/tlsio_esp_tls.c Func:tlsio_esp_tls_send_async Line:551 tlsio_esp_tls_send_async without a prior successful open
esp-azure/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:377 550: Failure sending control packet data
esp-azure/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_publish Line:1067 Error: mqtt_client_publish send failed
esp-azure/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:publish_mqtt_telemetry_msg Line:865 Failed attempting to publish mqtt message
```
• Afterwards nothing happens anymore. The example is stuck.
(Our program continues trying to send packets, so the above log will appear each time a packet is "sent")

**Current workaround**

The example and our own program will recover from this state when the _keepAliveInterval_ is smaller than the send interval e.g. sending data every minute but setting the _keepAliveInterval_ to 30 seconds.

In this case a PING packet is sent every 30 seconds. This fails because there is no connection anymore. This is tracked for a PING packet therefore a reconnect is performed.
In the error case mentioned above (keepAliveInterval = 240s, send interval = 30s) such a PING packet will not be sent because the _packetSendTimeMs_ is updated every 30 seconds and _keepAliveInterval_ is 240 seconds so this
`if (((current_ms - mqtt_client->packetSendTimeMs) / 1000) >= mqtt_client->keepAliveInterval) `
(see https://github.com/Azure/azure-umqtt-c/blob/master/src/mqtt_client.c#L1319 )

will never evaluate to true.

**Expected Behavior**

Current behavior is that there is no error handling for data packets but only for PING packets.
I would expect that there is also some kind of error handling for data packets not only for PING packets in order to recover from such a state.

**Comment by ewertons** [comment]
Hi @Fyusel , if the TLS or socket layers are not returning failures, there is no way the code can identify network other than the ping timeouts.
Could you share the complete, verbose logs, please? If you have any error messages from tlsio* or socketio* layers, we could consider evaluating an enhancement for this platform, otherwise the SDK code has no option other than the pings.

**Comment by Fyusel** [comment]
Hi @ewertons , thanks for your answer.
I activated "Enable mbedTLS debugging", set it to verbose level and rerun the example like described above. That are the errors I see on my side:


```
...

I (42110) mbedtls: ssl_tls.c:2697 in_left: 0, nb_want: 5

I (42120) mbedtls: ssl_tls.c:2721 in_left: 0, nb_want: 5

I (42130) mbedtls: ssl_tls.c:8270 => read

I (42130) mbedtls: ssl_tls.c:4311 => read record

I (42140) mbedtls: ssl_tls.c:2536 => fetch input

I (42140) mbedtls: ssl_tls.c:2697 in_left: 0, nb_want: 5

I (42150) mbedtls: ssl_tls.c:2721 in_left: 0, nb_want: 5

I (42160) mbedtls: ssl_tls.c:8270 => read

I (42160) mbedtls: ssl_tls.c:4311 => read record

I (42160) mbedtls: ssl_tls.c:2536 => fetch input

I (42170) mbedtls: ssl_tls.c:2697 in_left: 0, nb_want: 5

I (42180) mbedtls: ssl_tls.c:2721 in_left: 0, nb_want: 5

I (42180) mbedtls: ssl_tls.c:2722 ssl->f_recv(_timeout)() returned 0 (-0x0000)

W (42190) mbedtls: ssl_tls.c:4973 mbedtls_ssl_fetch_input() returned -29312 (-0x7280)

W (42200) mbedtls: ssl_tls.c:4344 ssl_get_next_record() returned -29312 (-0x7280)

I (42220) mbedtls: ssl_tls.c:8270 => read

I (42220) mbedtls: ssl_tls.c:4311 => read record

I (42220) mbedtls: ssl_tls.c:2536 => fetch input

I (42220) mbedtls: ssl_tls.c:2697 in_left: 0, nb_want: 5

I (42230) mbedtls: ssl_tls.c:2721 in_left: 0, nb_want: 5

I (42230) mbedtls: ssl_tls.c:2722 ssl->f_recv(_timeout)() returned -76 (-0x004c)

W (42240) mbedtls: ssl_tls.c:4973 mbedtls_ssl_fetch_input() returned -76 (-0x004c)

W (42250) mbedtls: ssl_tls.c:4344 ssl_get_next_record() returned -76 (-0x004c)

W (42260) mbedtls: ssl_tls.c:8335 mbedtls_ssl_read_record() returned -76 (-0x004c)

E (42270) esp-tls-mbedtls: read error :-76:
IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.
Error: Time:Fri Aug  7 05:51:23 2020 File:/home/alexander/Dokumente/Themenmanagement/esp32/esp32-firmware/externals/esp-azure/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:IoTHubTransport_MQTT_Common_DoWork Line:3144 IoTHubTransport_MQTT_Common_DoWork: before publish_mqtt_telemetry_msg
Error: Time:Fri Aug  7 05:51:23 2020 File:/home/alexander/Dokumente/Themenmanagement/esp32/esp32-firmware/externals/esp-azure/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_publish Line:1049 mqtt_client_publish: packet_id = 5


sendPacketItem:

2�>devices/test-esp32-alex/messages/events/temperatureAlert=false{"deviceId":"myFirstDevice","windSpeed":12.00,"temperature":23.00,"humidity":70.00}

Error: Time:Fri Aug  7 05:51:23 2020 File:/home/alexander/Dokumente/Themenmanagement/esp32/esp32-firmware/externals/esp-azure/port/src/tlsio_esp_tls.c Func:tlsio_esp_tls_send_async Line:551 tlsio_esp_tls_send_async without a prior successful open
Error: Time:Fri Aug  7 05:51:23 2020 File:/home/alexander/Dokumente/Themenmanagement/esp32/esp32-firmware/externals/esp-azure/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:377 550: Failure sending control packet data
Error: Time:Fri Aug  7 05:51:23 2020 File:/home/alexander/Dokumente/Themenmanagement/esp32/esp32-firmware/externals/esp-azure/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_publish Line:1067 Error: mqtt_client_publish send failed
Error: Time:Fri Aug  7 05:51:23 2020 File:/home/alexander/Dokumente/Themenmanagement/esp32/esp32-firmware/externals/esp-azure/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:publish_mqtt_telemetry_msg Line:865 Failed attempting to publish mqtt message
Error: Time:Fri Aug  7 05:51:23 2020 File:/home/alexander/Dokumente/Themenmanagement/esp32/esp32-firmware/externals/esp-azure/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:IoTHubTransport_MQTT_Common_DoWork Line:3150 IoTHubTransport_MQTT_Common_DoWork: publish_mqtt_telemetry_msg error
```

I hope it helps.

**Comment by ewertons** [comment]
Fix: https://github.com/Azure/azure-umqtt-c/pull/129
