### ISSUE TITLE
Yocto bitbake recipe for project

### ISSUE THREAD

**Issue by dvescovi1** [Azure/azure-iot-sdk-c#1542]
**Is your feature request related to a problem? Please describe.**
Has anyone implemented a yocto bitbake recipe for this project?
cmake projects can be used as inputs to yocto recipes.
This would greatly expand to reach of this library. 

**Describe the solution you'd like**
A yocto layer/bitbake recipe for the azure-iot-sdk-c project.

**Describe alternatives you've considered**
I have a partly implemented recipe that builds but having trouble packaging all the libraries.

**Additional context**

**Comment by ewertons** [comment]
Hi @dvescovi1 , apologies for the delay.
We will post an update soon with our findings.

**Comment by ewertons** [comment]
@dvescovi1 , unfortunately we do not have a bitbake recipe.

**Comment by dvescovi1** [comment]
Of course I know you don't have a bitbake recipe or else I would not have created an issue. Duh.
I am saying you should create one as it would greatly expand the reach and usefulness of this project.

**Comment by ewertons** [comment]
@dvescovi1 ,
thanks for your reply. At this moment we do not have plans to add a recipe for bitbake.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@dvescovi1, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
