### ISSUE TITLE
Module Method Callback response memory - who frees it?

### ISSUE THREAD

**Issue by vipeller** [Azure/azure-iot-sdk-c#1543]
see the description submitted to Edge:

https://github.com/Azure/iotedge/issues/2995

**Comment by danewalton** [comment]
Hi @vipeller can you take a look at the response to the linked issue and see if it resolves your question?

**Comment by ewertons** [comment]
We apologize for the long delay, but we were assigned to work on new code development and that affected our github response time.

We will close this issue, but if you would like it to be reopened and follow up on this matter, please post a comment requesting so.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@vipeller, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
