### ISSUE TITLE
IoTHubModuleClient_LL_SendEventToOutputAsync memory issue

### ISSUE THREAD

**Issue by vipeller** [Azure/azure-iot-sdk-c#1544]
see the description submitted to edge:

https://github.com/Azure/iotedge/issues/3004

**Comment by ewertons** [comment]
Please follow up on the original issue if needed.
Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment]
@vipeller, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
