### ISSUE TITLE
The cstdbool header is deprecated in C++17

### ISSUE THREAD

**Issue by StephanTLavavej** [Azure/azure-iot-sdk-c#155]
Many SDK headers are including `<cstdbool>`, which is deprecated in the C++17 Standard (D.4.3 [depr.cstdbool.syn]). A future update to VS 2017 (the second toolset update; not VS 2017 15.3 which is the first toolset update) will emit deprecation warnings for this (implemented by me), affecting users of the SDK.

The way to avoid these deprecation warnings is to stop including `<cstdbool>` for C++; this header has never been useful (because `bool` has always been a fundamental type in C++), so this will be a backward-compatible change.

**Comment by tameraw** [comment]
@StephanTLavavej - Thanks for the heads up on this. If there is a chance you can provide a PR to address this, we'd happily review it.
