### ISSUE TITLE
Failure to create Intermediate Device CA certificate

### ISSUE THREAD

**Issue by IndefiniteBen** [Azure/azure-iot-sdk-c#1554]
Using the certificate guide [tools/CACertificates/CACertificateOverview.md](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md) with the bash commands fails for me. This has previously been discussed in #349 and #580. I have not tried the same process in PowerShell with OpenSSL.

#### Development Machine, OS, Compiler (and Other Relevant Toolchain Info)
Windows Subsystem for Linux Ubuntu 18.04

#### SDK Version
Clone from master

#### Describe the Bug

As mentioned in #349 I run command `./certGen.sh create_root_and_intermediate` and after the Root CA Certificate details are output to console, the creation of the Intermediate Device CA CSR fails as seen in the logs below.

#### Console Logs
```
$ ./certGen.sh create_root_and_intermediate
[Root CA Certificate details...]
Creating the Intermediate Device CA
-----------------------------------
Generating RSA private key, 4096 bit long modulus (2 primes)
.++++
...........................................................................................................................................++++
e is 65537 (0x010001)
Creating the Intermediate Device CA CSR
-----------------------------------
Signing the Intermediate Certificate with Root CA Cert
-----------------------------------
Using configuration from ./openssl_root_ca.cnf
Can't open ./certs/azure-iot-test-only.intermediate.cert.pem for reading, No such file or directory
140638769123776:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:72:fopen('./certs/azure-iot-test-only.intermediate.cert.pem','r')
140638769123776:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:79:
unable to load certificate
```

**Comment by ericwol-msft** [comment]
I just tried this on my machine and it worked correctly (using WSL). What version of openSSL (mine OpenSSL 1.1.1f  31 Mar 2020)? what files are in the certs directory? Is this a clean directory?

**Comment by IndefiniteBen** [comment]
* Master branch of SDK
* Yes it is a clean directory. I also tried in both a (windows) user directory and a new directory created in C:\
* `$ openssl version` returns `OpenSSL 1.1.1  11 Sep 2018`
*  `$ ls azure-iot-sdk-c/certs/` returns `certs.c  certs.h`, same as https://github.com/Azure/azure-iot-sdk-c/tree/master/certs 
   - unless you mean in the generated directory? In that case `$ ls certs/` returns `azure-iot-test-only.root.ca.cert.pem`
* Perhaps relevant: I have Microsoft Windows [Version 10.0.18363.900] which means I'm using WSL v1

**Comment by ericwol-msft** [comment]
I have the same windows version. Why is your openssl so old?

**Comment by IndefiniteBen** [comment]
I have no idea. I'm using Ubuntu 18.04 in WSL and installed it a while ago, so that might be why?
I ran
```
sudo apt-get update
sudo apt-get upgrade
```
Which did not upgrade it and specifically running `sudo apt-get install openssl` returns: 
`openssl is already the newest version (1.1.1-1ubuntu2.1~18.04.6).`
I guess 1.1.1f is not available via apt-get so I would need to download it directly from openSSL or build from source?
I got another method working for generating my test certs so I don't really want to go through that effort to upgrade openSSL

**Comment by danewalton** [comment]
Hi all. Sorry for the delay but I have a PR [here](https://github.com/Azure/azure-iot-sdk-c/pull/1713) which exits the script on failure. I have a feeling something in the script is silently failing which is why that intermediate isn't found. If one of you that had the issue could run it with these options turned on and let us know where it might be failing that would be much appreciated.

**Comment by danewalton** [comment]
Also turned the trace option on to see which commands are run at each stage of the script.

**Comment by danewalton** [comment]
I'm going to close this for now but if someone hits this issue again with the latest changes and can provide some detail on where it is failing please add the details here and we can reopen to investigate.

**Comment by az-iot-builder-01** [comment]
@MichaelGiger, @ericwol-msft, @IndefiniteBen, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
