### ISSUE TITLE
broken link to build instructions

### ISSUE THREAD

**Issue by sjothunj** [Azure/azure-iot-sdk-c#156]
Link to instructions to build the example referenced in readme at https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_http/mbed
Has markdown to a link https://github.com/Azure/azure-iot-sdk-c/blob/doc/get_started/mbed-freescale-k64f-c.md which is missing.

**Comment by tameraw** [comment]
@sjothunj - The link has now been fixed. Thanks for spotting this!
