### ISSUE TITLE
prov_dev_client_ll_sample.c for provisioning a new device 

### ISSUE THREAD

**Issue by pmulligan-rk** [Azure/azure-iot-sdk-c#1563]
I'm struggling to get the example _prov_dev_client_ll_sample.c_ to work and provision a device using a signed X.509 certificate. I'm cross-compiling the SDK for an ARM chip. All the other samples are working for me, except this.

Here are the steps I took : 

- I've created a Device Provisioning Service on the Azure Portal and linked my IoT Hub with it. 

- I added my root CA certificate to the certificates of the Device Provisioning Service.

- I then went to "Manage Enrollments", created an Enrollment group, and set my CA certificate as the Primary Certificate.

The modifications I make to the prov_dev_client_ll_sample.c are as follows : 

-  Set _global_prov_ur_i to  "global.azure-devices-provisioning.net"
-  Set _id_scope_ to that of my Provisioning Service 
-  _Prov_Device_LL_SetOption(handle, OPTION_TRUSTED_CERT, certificates);_     certificates contains the Baltimore server certificate
- _IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_TRUSTED_CERT, client_certificate);_    client_certificate contains my device certificate which has already been signed by my CA certificate

Should this be enough to provision a new device? I have a feeling that I am missing out on something obvious.

When I run my application on the target, it fails with the following below messages. Thanks in advance for any support with this :  

`Provisioning API Version: 1.3.8`
`Iothub API Version: 1.3.8 `

`Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED`

`Error: Time:Wed Jun 17 14:02:35 2020 File:/home/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error`

`Error: Time:Wed Jun 17 14:02:35 2020 File:/home/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:771 Failure retrieving data from the provisioning service`

`Failure encountered on registration PROV_DEVICE_RESULT_TRANSPORT`

`Error: Time:Wed Jun 17 14:02:35 2020 File:/home/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:395 Failure sending control packet data`

`Error: Time:Wed Jun 17 14:02:35 2020 File:/home/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1249 Error: mqtt_client_disconnect send failed`

`registration failed!`

`Press any enter to continue:
`

**Comment by danewalton** [comment]
Hi @pmulligan-rk. Just out of curiosity how did you generate your certificates? RSA, ECC, etc

**Comment by asergaz** [comment]
@pmulligan-rk you asked the same on SO can you confirm so we cross-reference? Thanks

https://stackoverflow.com/questions/62433478/using-the-azure-iot-sdk-for-c-to-provision-a-new-device

**Comment by danewalton** [comment]
I'm going to go ahead and close this for inactivity. If you are still having the issue please reply here and we can reopen.

**Comment by az-iot-builder-01** [comment]
@pmulligan-rk, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
