### ISSUE TITLE
agenttypesystem.c  build error

### ISSUE THREAD

**Issue by abdoul91** [Azure/azure-iot-sdk-c#1567]
when try to build , i get in  function agenttypesystem.c  this error : 'uint32Value' may be used uninitialized in this function [-Werror=maybe-uninitialized]
Help Please.

**Comment by az-iot-builder-01** [comment]
@abdoul91, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
