### ISSUE TITLE
CreationTimeUtc for D2C message

### ISSUE THREAD

**Issue by sanjeev-magoo** [Azure/azure-iot-sdk-c#1568]
This is regarding setting of system property(CreationTimeUtc) to D2C message. Basically, we wanted to set CreationTimeUtc timestamp in every telemetry message originated from device. It is possible that device is generating D2C messages when working in offline mode, when these messages reached to cloud, we want to know the actual creation time of these messages. 
**Our findings-**
1.	We checked and found that “CreationTimeUtc” property on Message is only supported by C# and Java SDK. We are not able to find support in C SDK. Refer reference #1.
2.	Looks like CreationTimeUtc property on Message in the C# SDK results in SystemProperty “iothub-creation-time-utc” to be added on the message that is sent to IoT Hub, refer reference #2. 
3.	Refer readme.md file mentioned in reference #3, Refer the following section- 

Send   device-to-cloud message | ✔️* | ✔️* | ✔️* | ✔️* | ✔️* | Send   device-to-cloud messages (max 256KB) to IoT Hub with the option to add custom   properties. IoT Hub only supports batch send over AMQP and HTTPS only at the   moment. This SDK supports batch send over HTTP. * Batch send over AMQP and   AMQP-WS, and **add system properties on D2C messages are in progress.**
-- | -- | -- | -- | -- | -- | --
4.	Refer another reference #4 for same property.

**Questions-**

1. Could you please let us when this feature will be available with C SDK? 
2. Let us know, If there is way to set “iothub-creation-time-utc“ property programmatically in system properties of D2C message?

Note- We can temporarily set this property in application properties, but we are looking for solution using system properties as recommended by MS and to minimize the changes later.

**References-**

1. https://github.com/Azure/azure-iot-sdk-java/issues/397
2. https://github.com/Azure/azure-iot-sdk-csharp/blob/cd93e75fd8914b6247f23eb6a5cfd7aea459676f/iothub/device/src/MessageSystemPropertyNames.cs.
3. https://github.com/Azure/azure-iot-sdk-c/blob/master/readme.md
4. https://github.com/Azure/azure-iot-sdk-csharp/issues/376

**Comment by ericwol-msft** [comment]
I can add this work to the backlog. Does this actually work for you?? When I do it, the creation time is not on the system properties, but on the message properties. Routing to blob storage does not respect the creation time. How are you using this??


{
  "body": {
    "foo": "bar"
  },
  "enqueuedTime": "2020-06-24T23:19:20.263Z",
  "properties": {
    **"iothub-creation-time-utc": "2020-05-01T21:21:02.264Z"**
  },
  "systemProperties": {
    "iothub-connection-device-id": "01233EAD58E86797FE",
    "iothub-connection-auth-method": "{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}",
    "iothub-connection-auth-generation-id": "637279390182254368",
    "iothub-enqueuedtime": 1593040760216,
    "iothub-message-source": "Telemetry",
    "x-opt-sequence-number": 17839,
    "x-opt-offset": "34359746048",
    "x-opt-enqueued-time": 1593040760263
  }
}

**Comment by rajaggrawal** [comment]
we can route D2C messages to kusto/blob storage and purpose is to store **creation time** for each messages. 
could you please let us know the correct way to send **creation time** along with D2C message and same can be redirect to kusto/blob?

**Comment by sanjeev-magoo** [comment]
@ericwol-msft - If application properties are not available this it will not solve our use case. We wanted to route data to following resources-
1. Blob storage
2. Event Hub
3. Kusto DB

We are providing interface to work with Azure IoT. Multiple teams will consuming this interface. One option(#1) is, each message body shall contain the creation-timestamp, in this case, each team consuming our interface will need to add this in message body, other option (#2) is, we add creation-timestamp in system properties at common place.

we wanted to go with 2nd option. how do we support this? suggestions are highly appreciated. Any plan to support this property in system properties via C SDK?

**Comment by sanjeev-magoo** [comment]
@ericwol-msft - Thanks for the PR. Hoping this feature is supported for MQTT over websocket protocol from device to IoTHub.

**Comment by ericwol-msft** [comment]
This is now in master branch. Please use IoTHubMessage_SetMessageCreationTimeUtcSystemProperty to set the creation time on the message

**Comment by az-iot-builder-01** [comment]
@rajaggrawal, @sanjeev-magoo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
