### ISSUE TITLE
[DM] devicetwin_simplesample desired callback is not called

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdk-c#157]
- **OS and version used:** Ubuntu 16.04 LTS
- **SDK version used:** Head of master (4a4d26d90a6ed27a6b46504845477a03f8b092d0)

# Description of the issue:
Run devicetwin_simplesample with modification to use MQTT over Websocket and conection string.
Use iothub-explorer to update the desired speed setting

> iothub-explorer update-twin Ludo "{\"properties\":{\"desired\":{\"settings\":{\"desired_maxSpeed\":50,\"location\":{\"longitude\":15,\"latitude\":42}}}}}"

The callback on the device side is not triggered

# Console log of the issue:
Here is the first run of the sample

> lmussier@lmussier-virtual-machine:~/workspace/azure-iot-sdk-c/cmake/iotsdk_linux/serializer/samples/devicetwin_simplesample$ ./devicetwin_simplesample 
> Info: IoT Hub SDK for C, version 1.1.16
> Reported state will be send to IoTHub
> press ENTER to end the sample
> -> 15:04:36 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: ***************/api-version=2016-11-14&DeviceClientType=iothubclient%2f1.1.16%20(Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
> <- 15:04:36 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0
> -> 15:04:36 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: $iothub/twin/res/# | QOS: 0 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/# | QOS: 0 | TOPIC_NAME: $iothub/methods/POST/# | QOS: 0
> -> 15:04:36 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=3 | PAYLOAD_LEN: 252
> <- 15:04:36 SUBACK | PACKET_ID: 2 | RETURN_CODE: 0 | RETURN_CODE: 0 | RETURN_CODE: 0
> -> 15:04:36 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/GET/?$rid=4
> <- 15:04:37 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/204/?$rid=3&$version=2 | PAYLOAD_LEN: 0
> IoTHub: reported properties delivered with status_code = 204
> <- 15:04:37 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/200/?$rid=4 | PAYLOAD_LEN: 335
> Device Twin properties received: update=DEVICE_TWIN_UPDATE_COMPLETE payload={
>   "desired": {
>     "$version": 1
>   },
>   "reported": {
>     "state": {
>       "softwareVersion": 1,
>       "reported_maxSpeed": 100,
>       "vanityPlate": "1I1"
>     },
>     "maker": {
>       "makerName": "Fabrikam",
>       "style": "sedan",
>       "year": 2014
>     },
>     "lastOilChangeDate": "2016",
>     "$version": 2
>   }
> }U�!d���, size=335
> 

A get-twin -r from the iothub explorer 

> lmussier@lmussier-virtual-machine:~/workspace/IoTHubAgent$ iothub-explorer get-twin Ludo -r
> {"deviceId":"Ludo","etag":"AAAAAAAAAAE=","properties":{"desired":{"$metadata":{"$lastUpdated":"2017-06-15T13:04:26.7241672Z"},"$version":1},"reported":{"state":{"softwareVersion":1,"reported_maxSpeed":100,"vanityPlate":"1I1"},"maker":{"makerName":"Fabrikam","style":"sedan","year":2014},"lastOilChangeDate":"2016","$metadata":{"$lastUpdated":"2017-06-15T13:04:37.0012052Z","state":{"$lastUpdated":"2017-06-15T13:04:37.0012052Z","softwareVersion":{"$lastUpdated":"2017-06-15T13:04:37.0012052Z"},"reported_maxSpeed":{"$lastUpdated":"2017-06-15T13:04:37.0012052Z"},"vanityPlate":{"$lastUpdated":"2017-06-15T13:04:37.0012052Z"}},"maker":{"$lastUpdated":"2017-06-15T13:04:37.0012052Z","makerName":{"$lastUpdated":"2017-06-15T13:04:37.0012052Z"},"style":{"$lastUpdated":"2017-06-15T13:04:37.0012052Z"},"year":{"$lastUpdated":"2017-06-15T13:04:37.0012052Z"}},"lastOilChangeDate":{"$lastUpdated":"2017-06-15T13:04:37.0012052Z"}},"$version":2}},"tags":{}}

Update twin value
 
> lmussier@lmussier-virtual-machine:~/workspace/IoTHubAgent$ iothub-explorer update-twin Ludo "{\"properties\":{\"desired\":{\"settings\":{\"desired_maxSpeed\":50,\"location\":{\"longitude\":15,\"latitude\":42}}}}}"
> properties: 
>   desired: 
>     settings: 
>       desired_maxSpeed: 50
>       location: 
>         longitude: 15
>         latitude:  42
>     $metadata: 
>       $lastUpdated:        2017-06-15T13:08:41.6202072Z
>       $lastUpdatedVersion: 2
>       settings: 
>         $lastUpdated:        2017-06-15T13:08:41.6202072Z
>         $lastUpdatedVersion: 2
>         desired_maxSpeed: 
>           $lastUpdated:        2017-06-15T13:08:41.6202072Z
>           $lastUpdatedVersion: 2
>         location: 
>           $lastUpdated:        2017-06-15T13:08:41.6202072Z
>           $lastUpdatedVersion: 2
>           longitude: 
>             $lastUpdated:        2017-06-15T13:08:41.6202072Z
>             $lastUpdatedVersion: 2
>           latitude: 
>             $lastUpdated:        2017-06-15T13:08:41.6202072Z
>             $lastUpdatedVersion: 2
>     $version:  2
>   reported: 
>     state: 
>       softwareVersion:   1
>       reported_maxSpeed: 100
>       vanityPlate:       1I1
>     maker: 
>       makerName: Fabrikam
>       style:     sedan
>       year:      2014
>     lastOilChangeDate: 2016
>     $metadata: 
>       $lastUpdated:      2017-06-15T13:04:37.0012052Z
>       state: 
>         $lastUpdated:      2017-06-15T13:04:37.0012052Z
>         softwareVersion: 
>           $lastUpdated: 2017-06-15T13:04:37.0012052Z
>         reported_maxSpeed: 
>           $lastUpdated: 2017-06-15T13:04:37.0012052Z
>         vanityPlate: 
>           $lastUpdated: 2017-06-15T13:04:37.0012052Z
>       maker: 
>         $lastUpdated: 2017-06-15T13:04:37.0012052Z
>         makerName: 
>           $lastUpdated: 2017-06-15T13:04:37.0012052Z
>         style: 
>           $lastUpdated: 2017-06-15T13:04:37.0012052Z
>         year: 
>           $lastUpdated: 2017-06-15T13:04:37.0012052Z
>       lastOilChangeDate: 
>         $lastUpdated: 2017-06-15T13:04:37.0012052Z
>     $version:          2
> deviceId:   Ludo
> etag:       AAAAAAAAAAI=
> tags: 

It seems that the twin desired values are correctly from a iothub-explorer point of view. But on the device side only the twinupdate callback is triggered, onDesiredMaxSpeed does not seems to be called.

> -> 15:08:26 PINGREQ
> <- 15:08:27 PINGRESP
> <- 15:08:41 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/?$version=2 | PAYLOAD_LEN: 145
> Device Twin properties received: update=DEVICE_TWIN_UPDATE_PARTIAL payload={
>   "settings": {
>     "desired_maxSpeed": 50,
>     "location": {
>       "longitude": 15,
>       "latitude": 42
>     }
>   },
>   "$version": 2
> }, size=145
> -> 15:12:17 PINGREQ
> <- 15:12:18 PINGRESP

**Comment by lmussier** [comment]
I managed to get the callback called but I had to comment

>       //if (IoTHubClient_SetDeviceTwinCallback(iotHubClientHandle, deviceTwinGetStateCallback, NULL) != IOTHUB_CLIENT_OK)
>                         //{
>                         //    (void)printf("Failed subscribing for device twin properties\n");
>                        // }

It seems that we can't get the twin update notification and a specific callback running together.
Is it the normal behavior or a bug?

**Comment by zolvarga** [comment]
@lmussier,

Thank you for using our SDKs.

Yes, it is by design. You can not get both notification in the same time. Either you enable the TwinSateCallback and you parsing the JSON yourself or rely on the existing parameter update callback.

I am going to make a note in the sample to make that clear.

Best Regards,
Zoltan
