### ISSUE TITLE
Functionality of IOTHUB_CLIENT_REPORTED_STATE_CALLBACK, best way to verify if devicetwin has been updated correctly

### ISSUE THREAD

**Issue by mucar-bmk** [Azure/azure-iot-sdk-c#1574]
Hello,

how does the send-callback for device-twin-updates actually work?
Which informations contains the status_code ?
Is this callback-function based on the QoS1-Service of MQTT ( at least once ) if the SDK is used with MQTT?
Or how can I verify if the devicetwin is updated properly, do you have any suggestions?

SDK Version used: LTS 2019/07

thanks!

**Comment by ericwol-msft** [comment]
_>>how does the send-callback for device-twin-updates actually work?_
When a twin update is send to the hub, the hub will respond on our subscription to the hubs topic $iothub/twin/res/{status}/?$rid={request id}. The response will invoke your func set by IoTHubDeviceClient_SetDeviceTwinCallback()

More detail in hub MQTT can be found here https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support

_>>Which information contains the status_code ?_

When you call the IoTHubDeviceClient_SendReportedState(), you pass in the callback that receives the status

reportedStateCallback(int **status_code**, void* userContextCallback)

_>>Is this callback-function based on the QoS1-Service of MQTT ( at least once ) if the SDK is used with MQTT?_
QoS 0

_>>Or how can I verify if the devicetwin is updated properly, do you have any suggestions?_
Goto the device on the Azure Hub portal, and look at the device twin. Or you can use the device explorer https://docs.microsoft.com/en-us/azure/iot-pnp/howto-install-iot-explorer

**Comment by mucar-bmk** [comment]
Hello,

thanks for your answer, is there a way that i can verify the successfull update on device-side?
As far as I know, QoS 0 does not guarantee the delivery. Is there any configurations to gain QoS 1 ?
But when the callback is only invoked with an positive Status if the hub responses to the devicetwin-update,  can I be sure that the data has been transmitted?

**Comment by ericwol-msft** [comment]
_>>is there a way that i can verify the successfull update on device-side?_
the reportedStateCallback will have a status of 200

_>>As far as I know, QoS 0 does not guarantee the delivery. Is there any configurations to gain QoS 1 ?_
No. You need to monitor the reportedStateCallback, and if not received within a given time, send the update again.

_>>But when the callback is only invoked with an positive Status if the hub responses to the devicetwin-update, can I be sure that the data has been transmitted?_
Yes

**Comment by ewertons** [comment]
Hi @mucar-bmk ,

we will close this issue for now, but please feel free to reopen it if you would like to follow up.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@mucar-bmk, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
