### ISSUE TITLE
Confusing Instructions on Proof Of Possession Step

### ISSUE THREAD

**Issue by rgamage** [Azure/azure-iot-sdk-c#1575]
In the doc, CACertificateOverview.md, in Step 3, it says:
"Only perform this step if you're setting up CA Certificates and proof of possession. For simple device certificates, such as Edge certificates, skip to the next step"

I have an Edge device, and want to use production CA Certificates to authenticate it to the hub.  Do I need to do Step 3 or not?  The statement in the doc is very confusing and offers contradictory guidance.

It seems to imply that an Edge certificate is a 'simple device certificate' - is it?  I thought the Edge devices, for production, should also use Production, CA signed certificates to authenticate with the hub?

Please clarify whether the proof of possession step is needed in the case of installing CA-signed certificates onto an Edge device.

Also confusing, this doc is referenced by this article:
[https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-security-x509-get-started](url)

That article is for installing Production certificates.  And yet the warning at the top of CACertificateOverview.md says that "Certificates created by these scripts **MUST NOT** be used for production."  Of course that is incorrect.  These outputs of these scripts CAN be used for production, if you started with a CA-signed root, it just depends on which steps you are performing, etc.  But that warning is so emphatic it could scare off developers, assuming they are in the wrong place.

Please remove, or clarify this warning.

**Comment by ericwol-msft** [comment]
It's explained in the first paragraph why you should not use the generated certs _They contain hard-coded passwords ("123"), expire after 30 days, and most importantly are provided for demonstration purposes to help you quickly understand CA Certificates._ 

As always, when productizing against CA Certificates, you'll need to use your own security best practices for certification creation and lifetime management.

**Comment by ericwol-msft** [comment]
The CACertificateOverview.md is for using device certs. (see step #4)

Please reference this link for Azure IoT Edge certificates
https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-certs

**Comment by rgamage** [comment]
My point is that these scripts are clearly stating they are not for
production use, and yet this repo is directly referenced by instructions on
how to create/ install production certificates, for both devices and Edge
devices.  It makes for a confusing dev experience for someone trying to get
their system ready for production.

**Comment by ericwol-msft** [comment]
suggestions on how this should be reworded?

**Comment by rgamage** [comment]
The best re-wording would be "Certificates created by these scripts MUST
NOT be used for production.  If you are managing certificates for
Production use, please use the scripts in this other, separate repo, <link
here> that includes production script templates and a walk-through of the
steps required for Production scenarios."

Of course I don't believe this separate repo, or template or walk-through
exists, which is the problem.  In an effort to be efficient, all of the
Production instructions just point to these development scripts, which is a
dead end if you're not familiar with all the changes you will need to make
to the scripts to use them for Production.

The problem is at a higher level.  Imagine I want to secure my Edge device
for Production, using CA-signed certificates.  Here is my work-flow:
1) Read this article:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-security-x509-get-started
2) Which, following the CA-signed paragraph, refers you to this article:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-x509ca-overview#sign-devices-into-the-certificate-chain-of-trust
3) Which refers you to this document:
https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md

So it's not that this last document has poor wording, it's that this is the
wrong document / repo to reference when someone wants to create and install
production certificates.  There is a big piece missing from the
documentation: how to secure your Edge device for production.  I honestly
don't know how anyone does it, without paying consultants to do it for
them.  I've been working on this task for several weeks on and off, and am
continually frustrated and give up.

Randy

**Comment by ericwol-msft** [comment]
Most companies already have well defined procedure for creating and managing certificates in their production environment. The sample script creates a cert with a weak password for the private key, along with a short cert lifetime. The cert is signed in a manor with a CA, but the CA trust chain is also generated and does not come from a certificate issuer. You would not want to use this cert in any production environment. 

It's up to the user to determine the correct cert generation tool set based on their certificate issuer and the leaf cert should created/signed in a manor in which the intermediate cert is never exposed (except by an high level IT admin).

For one example, using Azure key vault (with a correct Certificate Authority issuer) to create certs with either DigiCert or GlobalSign as the issuer can be found here:
https://docs.microsoft.com/en-us/azure/key-vault/certificates/about-certificates

Obviously, you are free to use any CA and we don't want to dictate their tool chain for creating their certs.

**Comment by rgamage** [comment]
Eric,
Thanks for your response.  I spent 90 minutes with a Microsoft support
person on this issue, and we made very little progress. I have the root CA
cert, I've uploaded it to the hub.  I have an intermediate cert signed by
that root CA.  I have a set of powershell scripts that are only useful in
dev scenarios, and I have the documentation in the links from my last
message.. With all of these we were still not able to understand how to get
a certificate created and installed for my Edge device.  You say our
company should have our own procedures for cert management, and we do, for
all scenarios except this one.  IoT is new, Edge devices are new, nobody
understands this stuff, so we need step-by-step instructions.  My IT group
says, "we can help you with any cert you need, you just need to tell us
exactly what you need", and you say, "we can help you create dev certs, but
for production you must already have your own processes."  I'm stuck in the
middle here.  The Azure key vault example link you sent is not helpful.

Thanks,
Randy

**Comment by ericwol-msft** [comment]
please describe your topology to better understand what your asking.

**Comment by ericwol-msft** [comment]
you can reach me directly via my email address in the profile, if you don't want to discuss this publicly.

**Comment by danewalton** [comment]
I'm going to go ahead and close this for inactivity for now. @rgamage if you would like some additional help please post a comment and we can reopen it.

**Comment by az-iot-builder-01** [comment]
@rgamage, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by rgamage** [comment]
I would like to re-open this issue, and request a simple addition to the docs, to add this sentence, shown prominently: "Azure Edge Devices do NOT currently support the use of CA-signed certificates".  It took me a month of working with Microsoft to arrive at this conclusion.  No wonder nobody could show me how - it's not supported!  Only simple devices currently support CA-signed certificates.  Edge devices support SAS key or Self-signed certs only.
