### ISSUE TITLE
certGen.sh unable to create module certificates

### ISSUE THREAD

**Issue by slwojt** [Azure/azure-iot-sdk-c#1578]
I am developing the IoT devices driver for Linux (currently Ubuntu 19.10 distribution).
I have created an IoT device that has a few modules which I'd like to authorize with X.509 certificates.
And I'd like to use certGen.sh script to generate public/private certificates for those modules.
But the script seems unable to do it.
When I run
```
./certGen.sh create_device_certificate my_device/my_module
```
I get errors probably due to the `/` presence in the module id (which is perhaps interpreted as a directory/file separator).

**Comment by ericwol-msft** [comment]
For IoT Hub the certificate Subject / CN for self-signed certificate identities doesn’t matter. Hub will only verify the thumbprint. Normally people just set the subject name to just the module name.

**Comment by az-iot-builder-01** [comment]
@slwojt, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
