### ISSUE TITLE
[DM] Inconsistent desired properties

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdk-c#158]
- **OS and version used:** Ubuntu 16.04 LTS

- **SDK version used:** Head of master (4a4d26d90a6ed27a6b46504845477a03f8b092d0)

# Description of the issue:
Modify the devicetwin_simplesample to have onDesiredMaxSpeed called, comment IoTHubClient_SetDeviceTwinCallback block (see #157), and log the location properties

> @@ -80,7 +80,7 @@ void onDesiredMaxSpeed(void* argument)
>      /*in this case, it is 'CarSettings'*/
>  
>      CarSettings* car = argument;
> -    printf("received a new desired_maxSpeed = %" PRIu8 "\n", car->desired_maxSpeed);
> +    printf("received a new desired_maxSpeed = %" PRIu8 " - location [%f-%f]\n", car->desired_maxSpeed, car->location.longitude, car->location.latitude);
>  
>  }

Update the twin value with iothub-explorer

> iothub-explorer update-twin Ludo "{\"properties\":{\"desired\":{\"settings\":{\"desired_maxSpeed\":50,\"location\":{\"longitude\":15,\"latitude\":42}}}}}"

On the first update you'll see this log

> received a new desired_maxSpeed = 50 - location [0.000000-0.000000]

Update twin a second time with the same values
> iothub-explorer update-twin Ludo "{\"properties\":{\"desired\":{\"settings\":{\"desired_maxSpeed\":50,\"location\":{\"longitude\":15,\"latitude\":42}}}}}"

On the device you'll see this log
> received a new desired_maxSpeed = 50 - location [15.000000-42.000000]

Update a third time with new values

> iothub-explorer update-twin Ludo "{\"properties\":{\"desired\":{\"settings\":{\"desired_maxSpeed\":50,\"location\":{\"longitude\":4,\"latitude\":42}}}}}"

On the device you'll see this log
> received a new desired_maxSpeed = 50 - location [15.000000-42.000000]

Update a forth time with new values

> iothub-explorer update-twin Ludo "{\"properties\":{\"desired\":{\"settings\":{\"desired_maxSpeed\":50,\"location\":{\"longitude\":100,\"latitude\":100}}}}}"
On the device you'll see this log
> received a new desired_maxSpeed = 50 - location [4.000000-42.000000]

The desired properties are always one step behind. Note that the value on witch the callback is attached is always consistent.

# Console log of the issue:

> <- 16:21:21 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0
> -> 16:21:21 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: $iothub/twin/res/# | QOS: 0 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/# | QOS: 0 | TOPIC_NAME: $iothub/methods/POST/# | QOS: 0
> -> 16:21:21 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=3 | PAYLOAD_LEN: 252
> <- 16:21:21 SUBACK | PACKET_ID: 2 | RETURN_CODE: 0 | RETURN_CODE: 0 | RETURN_CODE: 0
> -> 16:21:21 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/GET/?$rid=4
> <- 16:21:21 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/204/?$rid=3&$version=2 | PAYLOAD_LEN: 0
> IoTHub: reported properties delivered with status_code = 204
> <- 16:21:21 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/200/?$rid=4 | PAYLOAD_LEN: 335
> <- 16:21:27 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/?$version=2 | PAYLOAD_LEN: 145
> received a new desired_maxSpeed = 50 - location [0.000000-0.000000]
> -> 16:25:11 PINGREQ
> <- 16:25:12 PINGRESP
> -> 16:29:02 PINGREQ
> <- 16:29:03 PINGRESP
> <- 16:31:12 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/?$version=3 | PAYLOAD_LEN: 145
> received a new desired_maxSpeed = 50 - location [15.000000-42.000000]
> -> 16:32:53 PINGREQ
> <- 16:32:54 PINGRESP
> <- 16:33:34 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/?$version=4 | PAYLOAD_LEN: 144
> received a new desired_maxSpeed = 50 - location [15.000000-42.000000]
> iothub-explorer update-twin Ludo "{\"properties\":{\"desired\":{\"settings\":{\"desired_maxSpeed\":50,\"location\":{\"longitude\":4,\"latitude\":42}}}}}"<- 16:35:24 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/?$version=5 | PAYLOAD_LEN: 147
> received a new desired_maxSpeed = 50 - location [4.000000-42.000000]
> -> 16:36:44 PINGREQ
> <- 16:36:45 PINGRESP

**Comment by lmussier** [comment]
On tag 2017-06-30, the issues is still present. 
The location is not even updated, I've run the exact same test, the location is always 0,0

Could you at least tell us if it is a bug, or this is how it is supposed to work.

**Comment by tameraw** [comment]
@lmussier - Apologies for the delay on this one. We're taking a look and will update you.

**Comment by ewertons** [comment]
Hi @lmussier, I'll take a look on this one later today.

**Comment by lmussier** [comment]
@ewertons any new on this one ?
Is the fix done for #170 is related to this one?

**Comment by ewertons** [comment]
Hi @lmussier , apologize for the delay, there was another issue higher priority we had to address.

**Comment by ewertons** [comment]
Interesting that if you register a callback for the location, you get it called correctly every time that location info is updated on twin.

```
@@ -37,7 +37,7 @@ DECLARE_MODEL(CarState,
 DECLARE_MODEL(CarSettings,
     WITH_DESIRED_PROPERTY(uint8_t, desired_maxSpeed, onDesiredMaxSpeed),
-    WITH_DESIRED_PROPERTY(Geo, location)
+    WITH_DESIRED_PROPERTY(Geo, location, onDesiredLocation)
 );

@@ -80,8 +80,18 @@ void onDesiredMaxSpeed(void* argument)
+void onDesiredLocation(void* argument)
+{
+       /*by convention 'argument' is of the type of the MODEL encompassing the desired property*/
+       /*in this case, it is 'CarSettings'*/

+       CarSettings* car = argument;
+       //printf("received a new desired_maxSpeed = %" PRIu8 "\n", car->desired_maxSpeed);
+       printf("222 received a new desired_maxSpeed = %" PRIu8 " - location [%f-%f]\n", car->desired_maxSpeed, car->location.longitude, car->location.latitude);
 }

<- 15:52:53 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/204/?$rid=3&$version=14 | PAYLOAD_LEN: 0
IoTHub: reported properties delivered with status_code = 204
<- 15:53:02 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/?$version=18 | PAYLOAD_LEN: 146
111 received a new desired_maxSpeed = 50 - location [0.000000-0.000000]
222 received a new desired_maxSpeed = 50 - location [22.000000-49.000000]

```

**Comment by ewertons** [comment]
So it seems that the bug is related to why the model calls onDesiredMaxSpeed if only "location" has been updated. It should not be invoked in this case, I believe. 
I will reply soon with my findings.

**Comment by ewertons** [comment]
@lmussier ,
after digging more into the code I can confirm that as it is the behavior should be expected.

The Serializer code traverses node by node of the JSON and updates the in-memory copy as it goes, and invokes any callback right after. The process is then repeated for the next node as the tree is traversed.

That means that when Serializer hits "desired_maxSpeed" in 
{
     "settings": {
        "desired_maxSpeed": 50,
        "location": {
          "longitude": 21,
          "latitude": 41
        }
      }
}
it will update the value of "desired_maxSpeed" and invoke the registered callback passing the whole parent model ("setting"). Notice that at this point "location" hasn't been updated, so that's why you see the behavior you are describing.

Then it moves to the next node, "location", updating the child nodes values and invoking the callback for that node. At this point you see the values you would expect.

So this is not a bug per se, since you can get the updates for the values if you define the correct callbacks.
But I do agree that there is one design issue: the whole tree should be updated before invoking any callbacks.
That would be a breaking change though. I will work with our PM to add this to the specification of the next version of the Azure IoT C SDK.

**Comment by lmussier** [comment]
Thanks for the detailled info, we will deal with that until the next
feature update.

**Comment by ewertons** [comment]
Just an update, this was accepted as a bug, and is in our backlog.
There is no ETA yet, but I'll update this once it gets fixed.
