### ISSUE TITLE
Create Individual Enrollment with Symmetric Key using API

### ISSUE THREAD

**Issue by frayedknot** [Azure/azure-iot-sdk-c#1586]
I'm trying to figure out how I can create an individual enrollment for a device using symmetric key. It seems that there are no methods in provisioning_sc_attestation_mechanism.h to do this. Is this just not supported?

All of the documentation at https://docs.microsoft.com/en-us/azure/iot-dps/ seems to have you create symmetric key enrollment by hand.

**Comment by ericwol-msft** [comment]
Correct, this does not take a symmetric key. Most people use the IoT Service SDK from the other languages, which does support this. 

https://github.com/Azure/azure-iot-sdk-csharp
https://github.com/Azure/azure-iot-sdk-python
https://github.com/Azure/azure-iot-sdk-java
https://github.com/Azure/azure-iot-sdk-node

**Comment by danewalton** [comment]
This seems to be resolved so I'm going to go ahead and close this for now. Please post a comment if you would like to have it reopened.

**Comment by az-iot-builder-01** [comment]
@frayedknot, @ericwol-msft, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
