### ISSUE TITLE
IoTHubDeviceClient_SendEventAsync call back issue

### ISSUE THREAD

**Issue by williamaccuenergy** [Azure/azure-iot-sdk-c#1587]
@Hi All,
I send 10 messages via IoTHubDeviceClient_SendEventAsync() function every 30 seconds. And I use an integer message id as a userContextCallback parameter, I will sleep 10 ms after IoTHubDeviceClient_SendEventAsync() . But In callback function, I find that there are duplicate userContextCallback parameters which is message id I set up when send message. I don't know what happened.
static uint16_t g_messageTrackingId = 0;
sendMessage(String postJson)
{
uint16_t msgId;
msgId = g_messageTrackingId++;
message_handle = IoTHubMessage_CreateFromString(postJson.c_str());
IoTHubDeviceClient_SendEventAsync(_device_handle, message_handle, send_confirm_callback, &msgId);
printf( "IoTHubDeviceClient_SendEventAsync--> msgTrackId:%u !!!\n",msgId);
ThreadAPI_Sleep(10);
}

static void send_confirm_callback(IOTHUB_CLIENT_CONFIRMATION_RESULT result, void* userContextCallback)
{

   uint16_t id = *(uint16_t *)userContextCallback;
    
    if(IOTHUB_CLIENT_CONFIRMATION_OK == result)
    {
    	printf( "send_confirm_callback--> msgTrackId:%u, send successful !!!\n",id);
    }
    else
    {
    	printf( "send_confirm_callback--> msgTrackId:%u, send failure!!!\n",id);
    }
}

void main()
{

   IOTHUB_DEVICE_CLIENT_HANDLE  _device_handle = IoTHubDeviceClient_CreateFromConnectionString(_azure.primaryConnectionString.c_str(), MQTT_Protocol);
    int keep_alive_interval_sec = 30;
    IoTHubDeviceClient_SetOption(_device_handle, OPTION_KEEP_ALIVE, &keep_alive_interval_sec);
    /* Set message timeout */
    uint32_t azure_message_timeout_msec = 30 * 1000; /* 30 sec */
    IoTHubDeviceClient_SetOption(_device_handle, OPTION_MESSAGE_TIMEOUT,&azure_message_timeout_msec);
    tickcounter_ms_t ms_delay = 1;
    (void)IoTHubDeviceClient_SetOption(_device_handle, OPTION_DO_WORK_FREQUENCY_IN_MS, &ms_delay);
    //  (void)IoTHubDeviceClient_SetDeviceTwinCallback(_device_handle, deviceTwinCallback, NULL);
    (void)IoTHubDeviceClient_SetConnectionStatusCallback(_device_handle, connection_status_callback, NULL);
   while(true)
  {
     for(int i = 0; i < 30; i++)
    {
        sendMessage("XXXXX");
    }
   sleep(30);
  }
}

print information:
IoTHubDeviceClient_SendEventAsync--> msgTrackId:0
IoTHubDeviceClient_SendEventAsync--> msgTrackId:1
IoTHubDeviceClient_SendEventAsync--> msgTrackId:2
send_confirm_callback--> msgTrackId:2,, send successful !!!
send_confirm_callback--> msgTrackId:2,, send successful !!!
send_confirm_callback--> msgTrackId:2,, send successful !!!
IoTHubDeviceClient_SendEventAsync--> msgTrackId:3
IoTHubDeviceClient_SendEventAsync--> msgTrackId:4
IoTHubDeviceClient_SendEventAsync--> msgTrackId:5
IoTHubDeviceClient_SendEventAsync--> msgTrackId:6
IoTHubDeviceClient_SendEventAsync--> msgTrackId:7
IoTHubDeviceClient_SendEventAsync--> msgTrackId:8
IoTHubDeviceClient_SendEventAsync--> msgTrackId:9
send_confirm_callback--> msgTrackId:9,, send successful !!!
send_confirm_callback--> msgTrackId:9,, send successful !!!
send_confirm_callback--> msgTrackId:9,, send successful !!!
send_confirm_callback--> msgTrackId:9,, send successful !!!
send_confirm_callback--> msgTrackId:9,, send successful !!!
send_confirm_callback--> msgTrackId:9,, send successful !!!
send_confirm_callback--> msgTrackId:9,, send successful !!!

So, I don't know where are  message id 0,1,3,4,5,6,7,8 ? if they are overlapped? What I should do? I will appreciate for your help

-> 10:30:30 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/GET/?$rid=4
-> 10:30:30 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=5 | PAYLOAD_LEN: 557
[DEBUG-MqttClient-publishAFile<1057>] 810 send message! message id :1.file:/opt/data/azure/postLog/94-1198be83-58ed-442b-b90a-1bfea4eb6137.json
-> 10:30:30 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/AcuLink810-william/messages/events/%24.cid=CORE_ID&%24.mid=1&%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 6 | PAYLOAD_LEN: 8219
[DEBUG-MqttClient-publishAFile<1057>] 810 send message! message id :2.file:/opt/data/azure/postLog/94-799d080d-f1b7-0054-18d4-0a7a3b7b5580.json
-> 10:30:30 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/AcuLink810-william/messages/events/%24.cid=CORE_ID&%24.mid=2&%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 7 | PAYLOAD_LEN: 8221
<- 10:30:30 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: QOS_VALUE_INVALID | TOPIC_NAME: $iothub/twin/res/200/?$rid=4 | PAYLOAD_LEN: 608
-> 10:30:30 SUBSCRIBE | PACKET_ID: 8 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/# | QOS: 0
[DEBUG-MqttClient-publishAFile<1057>] 810 send message! message id :3.file:/opt/data/azure/postLog/DigitInput-4d1f5fd3-37fb-d66c-5a98-69920d2ddf52.json
-> 10:30:30 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/AcuLink810-william/messages/events/%24.cid=CORE_ID&%24.mid=3&%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 9 | PAYLOAD_LEN: 752
<- 10:30:30 SUBACK | PACKET_ID: 8 | RETURN_CODE: 0
<- 10:30:30 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: QOS_VALUE_INVALID | TOPIC_NAME: $iothub/twin/res/204/?$rid=5&$version=147 | PAYLOAD_LEN: 0
Device Twin reported properties update completed with result: 204

[DEBUG-MqttClient-send_confirm_callback<399>] send_confirm_callback!!! msgid is:3,result:0!!!
[DEBUG-MqttClient-removeFile<498>] publish ok and remove file, filePath=/opt/data/azure/postLog/DigitInput-4d1f5fd3-37fb-d66c-5a98-69920d2ddf52.json
[DEBUG-MqttClient-send_confirm_callback<407>] send_confirm_callback--> msgTrackId:3, send successful !!!

<- 10:30:30 PUBACK | PACKET_ID: 6
[DEBUG-MqttClient-removeFile<498>] publish ok and remove file, filePath=/opt/data/azure/postLog/DigitInput-4d1f5fd3-37fb-d66c-5a98-69920d2ddf52.json
[DEBUG-MqttClient-send_confirm_callback<407>] send_confirm_callback--> msgTrackId:3, send successful !!!

<- 10:30:30 PUBACK | PACKET_ID: 7
[DEBUG-MqttClient-send_confirm_callback<399>] send_confirm_callback!!! msgid is:3,result:0!!!
[ERR-MqttClient-removeFile<503>] cann't find file!
[DEBUG-MqttClient-send_confirm_callback<407>] send_confirm_callback--> msgTrackId:3, send successful !!!

<- 10:30:30 PUBACK | PACKET_ID: 9
[DEBUG-MqttClient-send_confirm_callback<399>] send_confirm_callback!!! msgid is:3,result:0!!!
[ERR-MqttClient-removeFile<503>] cann't find file!
[DEBUG-MqttClient-send_confirm_callback<407>] send_confirm_callback--> msgTrackId:3, send successful !!!

Request:
My Message ID | Azure Package ID
   1                     | 6
   2                     | 7
  3                      | 9

Receive Response and invoke callback function
Message ID from callback | Azure Package ID

3                                        | 6
3                                        | 7
3                                        | 9

It is fine if I send one message during one sending rececle. But if I send multiple messages during one sending cycle, why brought argument by callback function is always the one that latest package is corresponding with?

**Comment by ericwol-msft** [comment]
msgId is allocated on the stack. IoTHubDeviceClient_SendEventAsync is an async call. ThreadAPI_Sleep sleeps for X milliseconds, so you are sleeping for 10ms. I doubt the hub call was less than 10ms, so this stack memory is gone.

userContextCallback is a void*, so nothing is stopping you using a size_t as the value. It does not need to be an actual pointer.

**Comment by williamaccuenergy** [comment]
@ericwol-msft Thanks for your replying.
msgId allocated on the stack, but it is assigned to a static global counter and it is different every time.
IoTHubDeviceClient_SendEventAsync is an async call. Yes. So I slow down send rate by ThreadAPI_Sleep on my application thread, But callback function should run on another thread. So I think ThreadAPI_Sleep 10ms should not result in hub memory gone.
I suspect hub cannot invoke IoTHubDeviceClient_SendEventAsync callback immediately. and parameter brought always is parameter of last package

**Comment by ericwol-msft** [comment]
>>msgId allocated on the stack, but it is assigned to a static global counter and it is different every time.

That is not how C works. You are still passing a pointer to the stack memory.

>>userContextCallback is assigned msgId in IoTHubDeviceClient_SendEventAsync. I want to get msgId in callback function
Yes, expect you are referencing stack memory that is no longer valid in the callback thread.

>>I suspect hub cannot invoke IoTHubDeviceClient_SendEventAsync callback immediately. and parameter brought always is parameter of last package
That is in correct. You can look at the implementation in the source code.

**Comment by williamaccuenergy** [comment]
@ericwol-msft Thank you very much. I will try it.

**Comment by az-iot-builder-01** [comment]
@williamaccuenergy, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by williamaccuenergy** [comment]
@ericwol-msft It works fine now. thanks for your helping
