### ISSUE TITLE
Hub client X509 Not Authorized

### ISSUE THREAD

**Issue by williamaccuenergy** [Azure/azure-iot-sdk-c#1589]
1. I followed the steps described in [https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md] to create root CA, certificate and private key. certificate file is new-device-full-chain.cert.pem 
2.Register CA and verify it
3.create IoT device on https://portal.azure.com/. Device ID:AcuLink810-X509
4.follow sample [https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_client_x509_sample/iothub_ll_client_x509_sample.c](url) create IoT Hub client  application.
1)_device_handle = IoTHubDeviceClient_CreateFromConnectionString(_azure.primaryConnectionString.c_str(), MQTT_Protocol);
primaryConnectionString:"HostName=AcuLink810.azure-devices.net;DeviceId=AcuLink810-X509;x509=true"
2)IoTHubDeviceClient_SetOption(_device_handle, OPTION_TRUSTED_CERT, readFileIntoString(AZURE_ROOT_FILE).c_str());
AZURE_ROOT_FILE  :azure-iot-test-only.root.ca.cert.pem
3)  if ( (IoTHubDeviceClient_SetOption(_device_handle, OPTION_X509_CERT, readFileIntoString(AZURE_CERT_FILE).c_str()) != IOTHUB_CLIENT_OK) ||
        (IoTHubDeviceClient_SetOption(_device_handle, OPTION_X509_PRIVATE_KEY,readFileIntoString(AZURE_KEY_FILE).c_str()) != IOTHUB_CLIENT_OK))
AZURE_CERT_FILE:new-device-full-chain.cert.pem
AZURE_KEY_FILE:new-device.key.pem
In my code string read from all file is same as content of files. I verified it.
5.failed to create connection:
-> 13:51:48 CONNECT | VER: 4 | KEEPALIVE: 30 | FLAGS: 128 | USERNAME: AcuLink810.azure-devices.net/AcuLink810-X509/?api-version=2019-10-01&DeviceClientType=iothubclient%2f1.3.8%20(native%3b%20Linux%3b%20armv7l) | CLEAN: 0
<- 13:51:48 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Thu Jul 16 13:51:48 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1755 Connection Not Accepted: 0x5: Not Authorized
Error: Time:Thu Jul 16 13:51:48 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:29 Failure creating private key evp_key
Error: Time:Thu Jul 16 13:51:48 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36   [0] error:0906D06C:PEM routines:PEM_read_bio:no start line
Error: Time:Thu Jul 16 13:51:48 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36   [1] error:0906D064:PEM routines:PEM_read_bio:bad base64 decode
Error: Time:Thu Jul 16 13:51:48 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:log_ERR_get_error Line:429 unable to use x509 authentication
Error: Time:Thu Jul 16 13:51:48 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1273 Failed creating the OpenSSL instance.
Error: Time:Thu Jul 16 13:51:48 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1042 Error: io_open failed
Error: Time:Thu Jul 16 13:51:48 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2329 failure connecting to address AcuLink810.azure-devices.net.
Error: Time:Thu Jul 16 13:51:49 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:29 Failure creating private key evp_key
Error: Time:Thu Jul 16 13:51:49 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36   [0] error:0906D06C:PEM routines:PEM_read_bio:no start line
Error: Time:Thu Jul 16 13:51:49 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36   [1] error:0906D064:PEM routines:PEM_read_bio:bad base64 decode
Error: Time:Thu Jul 16 13:51:49 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:log_ERR_get_error Line:429 unable to use x509 authentication
Error: Time:Thu Jul 16 13:51:49 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1273 Failed creating the OpenSSL instance.
Error: Time:Thu Jul 16 13:51:49 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1042 Error: io_open failed
Error: Time:Thu Jul 16 13:51:49 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2329 failure connecting to address AcuLink810.azure-devices.net.

If I delete step 4.2 code, The error information is :
-> 17:17:07 CONNECT | VER: 4 | KEEPALIVE: 30 | FLAGS: 128 | USERNAME: AcuLink810.azure-devices.net/AcuLink810-X509/?api-version=2019-10-01&DeviceClientType=iothubclient%2f1.3.8%20(native%3b%20Linux%3b%20armv7l) | CLEAN: 0
<- 17:17:07 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Thu Jul 16 17:17:07 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1755 Connection Not Accepted: 0x5: Not Authorized

sdk: iot-sdk-c
enviroment: embedded arm 7 device with Linux openssl
timestamp: time of  making certificate machine  is same as target machine
I don't know what's wrong with me.  Thanks for all your reply!

**Comment by ericwol-msft** [comment]
The error on the back end is "Remote IP Endpoint: 70.28.52.XXX, Details: **Password is empty**"

How is the device in the hub configured? When you created the device did you select X.509 Self-Signed or X.509 CA Signed?

You can try the simple SimulateX509Device.exe to see if it's a cert or hub config issue, or a config issue on your C application.

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-security-x509-get-started#:~:text=Register%20X.509%20CA%20certificates%20to%20your%20IoT%20hub,previous%20section%20from%20your%20computer.%20More%20items...%20

**Comment by williamaccuenergy** [comment]
Thanks for your reply. The device in the hub is X.509 CA signed. I create IoT device follow https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-security-x509-get-started.

 

Thanks you again. I will try it

 

Regards

**Comment by williamaccuenergy** [comment]
1.IoTHubDeviceClient_SetOption(_device_handle, OPTION_TRUSTED_CERT, readFileIntoString(AZURE_CERT_FILE).c_str())
Do I need set OPTION_TRUSTED_CERT? If I want to read CA file to string. is this CA file extension  crt or pem?

2.IoTHubDeviceClient_SetOption(_device_handle, OPTION_X509_CERT, readFileIntoString(AZURE_CERT_FILE).c_str()) 
If I want to read device cert file to string. is this cert file extension  crt or pem?

3. IoTHubDeviceClient_SetOption(_device_handle, OPTION_X509_PRIVATE_KEY,readFileIntoString(AZURE_KEY_FILE).c_str())
If I want to read device private key file to string. is this key file extension  key or pem?

Thanks for any help!

**Comment by ericwol-msft** [comment]
**Do I need set OPTION_TRUSTED_CERT? or When I need to set OPTION_TRUSTED_CERT? If I want to read CA file to string. is this CA file extension crt or pem?**
This is the trusted root of the IoT hub endpoint. For azure this is DigiCert Baltimore Root. Do you need this? depends on your device and your tls stack. From your trace, it looks like you did connect to the hub using tls, even though you passed in the wrong cert to the OPTION_TRUSTED_CERT option. So in you case, probably not.

**If I want to read device cert file to string. is this cert file extension crt or pem?
If I want to read device private key file to string. is this key file extension key or pem?**

A .pem file should contain -----BEGIN CERTIFICATE-----

You can verify your tls cert exchange by using wireshark and looking at the client hello message
https://www.linuxbabe.com/security/ssltls-handshake-process-explained-with-wireshark-screenshot

**Comment by ericwol-msft** [comment]
**jut to be clear, yo do have cert parsing issues.**

```
Error: Time:Thu Jul 16 13:51:48 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36 [0] error:0906D06C:PEM routines:PEM_read_bio:no start line
Error: Time:Thu Jul 16 13:51:48 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36 [1] **error:0906D064:PEM routines:PEM_read_bio:bad base64 decode**
```

**Comment by williamaccuenergy** [comment]
@ericwol-msft  thanks for your reply.
I just use openssl to create CA,cert, key, and try to connect hub using crt file. it is failed, so find the error information. thanks. But I am also failed to authorize to  Iot hub following your instruction:  https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md. I don't why

**Comment by danewalton** [comment]
@williamaccuenergy just to be clear. `.crt` files could be encoded in as binary or pem. Can you make sure to convert the cert and key to base64 pem? Both the extensions should be `.pem`

**Comment by williamaccuenergy** [comment]
@danewalton  thanks a lot.
Azure IoT device's certificate and device key file  should be pem file. right?

**Comment by danewalton** [comment]
@williamaccuenergy are you doing CA signed with no intermediate or do you have an intermediate cert? Either way though, if you're getting the log message which @ericwol-msft copied above, you likely won't make any headway. There's something about the reading in of the cert that isn't working. 

Could you try reading through this (https://github.com/Azure/azure-iot-sdk-c/issues/1572) and see if you can mimic the debugging listed there? In their case the `strcmp` failed to validate that what was read in was in fact the same as copied in.

**Comment by williamaccuenergy** [comment]
@danewalton 
>>>are you doing CA signed with no intermediate or do you have an intermediate cert?
Actually, I am just a developer don't care about intermediate or no intermediate. I will test again follow https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md.

>>>if you're getting the log message which @ericwol-msft copied above, you likely won't make any headway
My log info: 
/third-party/azure-iot-sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1755 Connection Not Accepted: 0x5: Not Authorized

>>>Could you try reading through this (#1572) and see if you can mimic the debugging listed there? In their case the strcmp failed to validate that what was read in was in fact the same as copied in
Sure, I will try strcmp(), Actually I copy cert log info to file and compare file, all is same except file tail, Linux is LF, Windows is CR-LF.
Anyway, Thank you very much

**Comment by danewalton** [comment]
@williamaccuenergy hope you don't mind me editing your reply for formatting.

Yea while that log message might be true, the other underlying messages seem to point to the root cause of the "unauthorized" error. That being reading the private key (bolding mine):

>Error: Time:Thu Jul 16 13:51:49 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:29 Failure creating **private key evp_key**
Error: Time:Thu Jul 16 13:51:49 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36 [0] error:0906D06C:PEM routines:**PEM_read_bio:no start line**
Error: Time:Thu Jul 16 13:51:49 2020 File:/opt/accuenergy/third-party/azure-iot-sdk/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36 [1] error:0906D064:PEM routines:PEM_read_bio:**bad base64 decode**

Could you try instead copying in to your sample file the cert and private and connect that way? If it connects in that case we know it's likely how it is being read in. Otherwise we can continue debugging.

**Comment by williamaccuenergy** [comment]
@danewalton 
I think it works fine now. the cause is :I create cert for device name as "deviceA", but I create X.509 signed device named another device id, so it failed to authorize. when I create a X.509 signed device named "deviceA". it work fine.
Anyway, Thank you taking your so much  time! Thanks again

Regards

**Comment by az-iot-builder-01** [comment]
@williamaccuenergy, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by williamaccuenergy** [comment]
Thanks all people who helped me! Thanks!

**Comment by williamaccuenergy** [comment]
@danewalton, I am failed to authorize again now. I passed authorization several days ago. I switch to SAS, it is fine. I switch back to X.509, it is failed again.  I create X509 cert following https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md. and create IoT device coresponding cert's common name on Azure IoT portal. But I always faile to authorize. log information: "/third-party/azure-iot-sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1755 Connection Not Accepted: 0x5: Not Authorized". Do you have any idea? thanks advanced.

**Comment by danewalton** [comment]
Is this a new cert or the old one? Could it have expired?

**Comment by williamaccuenergy** [comment]
@danewalton, this is a new cert. the linititation is 30 days. I confirm that it is not expired

**Comment by williamaccuenergy** [comment]
I create a new cert today

**Comment by danewalton** [comment]
Getting the "Not Authorized" error could be from a variety of causes. Do you have any details on the cert or connection via Wireshark? Feel free to email me on the email in my profile if you think that info is sensitive.

**Comment by williamaccuenergy** [comment]
@danewalton,thanks for your great help. I create a project on PC computer, and re-create certificate, key, and a new IoT device. it seems to work fine. I will validate it on target machine. Thank you again!

**Comment by williamaccuenergy** [comment]
@danewalton,I have another question:
`(void)IoTHub_Init();
......
 IoTHubDeviceClient_Destroy(_device_handle);
IoTHub_Deinit();`
code like aboe works fine.But If I change configuration and donnt reboot device I will do:
` IoTHubDeviceClient_Destroy(_device_handle);
IoTHub_Deinit();
(void)IoTHub_Init();
......
`
But I cannot connect to IoT Hub. For example both SAS and X.509 work fine. If I switch SAS to X.509 I am failed to authorize.but If I reboot device all is fine. Do you have any suggestion? thanks

**Comment by danewalton** [comment]
Hey @williamaccuenergy can you try a flow like the following:
```c
(void)IoTHub_Init();
IoTHubDeviceClient_Create(_device_handle);
......
IoTHubDeviceClient_Destroy(_device_handle);

IoTHubDeviceClient_Create(_device_handle);
......
IoTHubDeviceClient_Destroy(_device_handle);

IoTHub_Deinit();
```
Essentially `_init` and `_deinit` should only be called once during program execution.

**Comment by ewertons** [comment]
Also, please make sure you are not using the same device id with different types of authentication.
And there can be only one IoTHubDeviceClient for a given device ID at a given time.

**Comment by williamaccuenergy** [comment]
@danewalton @ewertons Thanks a lot .   If _init and _deinit are called multiple times there will be some problem. So I reboot thread  after I chang Azure configuration, it works fine now. I remember  important information from @ewertons. Thank you both!
