### ISSUE TITLE
AMQP reconnect failing

### ISSUE THREAD

**Issue by darobs** [Azure/azure-iot-sdk-c#159]
- **OS and version used:** unknown 

- **SDK version used:** 2017-03-24 

# Description of the issue:

Gateway user is experiencing a reconnection problem in AMQP.  User states that connection is inconsistent, but fails to recover when connection comes back. 

There are some error logs, but user did not find any unique errors that might point to root cause.
https://github.com/Azure/iot-edge/issues/288

# Code sample exhibiting the issue:

# Console log of the issue:

sample logs from issue, more are available at link:

>  2017-05-24 16:30:40.1010|ERROR|IS.FieldGateway.logger.CLogger|File: \iothubtransport_amqp_messenger.c 
> Function: process_state_changes:1530 
> message: messagereceiver reported unexpected state %d while messenger is starting
> 2017-05-24 16:30:40.1166|ERROR|IS.FieldGateway.logger.CLogger|File: \iothubtransport_amqp_device.c 
> Function: device_do_work:888 
> message: Device '%s' is started but messenger reported unexpected state %d
> 2017-05-24 16:30:40.1322|ERROR|IS.FieldGateway.logger.CLogger|File: \iothubtransport_amqp_common.c 
> Function: IoTHubTransport_AMQP_Common_Device_DoWork:979 
> message: Failed performing DoWork for device '%s' (device reported state %d; number of previous failures: %d)
> 2017-05-24 16:30:40.3041|ERROR|IS.FieldGateway.logger.CLogger|File: \iothubtransport_amqp_messenger.c 
> Function: process_state_changes:1508 

Note the "%s/%d" in the log output.  Even if we can't find root cause right now, getting those logs fixed might give us better insight into what's going wrong.  If this has already been fixed, we can pull a newer release into the gateway and find out more.

**Comment by ewertons** [comment]
We need to get full logs, and the (full) description of the platform, so we can try a repro.
Please work with the customer to get these, and we will be able to investigate.
Thanks,
Ewerton

**Comment by ewertons** [comment]
As we talked, please ask the customer to update the GW version to get the latest C client SDK used.
Then let the solution run and grab the logs ( it would be good to have the traces for a few reconnection attempts so we can investigate better).

**Comment by ewertons** [comment]
Hi @darobs ,
may we close this issue? When you get more details of the failure we can reopen it if necessary.

**Comment by darobs** [comment]
Yes, if I get more information, I'll raise this (or another) issue.
