### ISSUE TITLE
Leaf device registration using x509 certificates via IoT Edge gateway

### ISSUE THREAD

**Issue by sanjeev-magoo** [Azure/azure-iot-sdk-c#1592]
We are trying to implement a transparent gateway use case using Azure IoT Edge. Our Edge device and leaf devices have their identity in the form of x509 certificates.
Requirement- 
We want to register the leaf device having x509 certificate as identity using DPS service via IoT Edge.
Leaf device will not have internet connectivity, it can reach to internet via edge device only.

We are not able to find a direct support to register the leaf device using DPS service via edge device.

One possible solution- 
1. First IoT edge device will get register to IoTHub using x509 certificate as its identity using DPS service. Once edge device get registered, it will have its IoTHub details. 
2. Expose an interface to leaf devices from edge module to get the IoTHub detail where leaf device should be registered as child of edge device.
3. Leaf device will fetch IoTHub details via interface defined in step #2.
4. Leaf device will initialize the HSM module (custom HSM module) to read the certificates and provide the device id to SDK.
5. Leaf device will use IoTHub connection (with x509 option) with GatewayHostName to register itself to IoTHub using x509 certificate.

We have not yet implemented the above steps but we think that this should work.
however, we wanted to know the best way to implement the mentioned use case. Could you please guide us on suitable approach to fulfill this use case?

**Comment by ewertons** [comment]
Hi @sanjeev-magoo ,

the plan you listed seems pretty good, and should work.

Unfortunately our device provisioning client cannot connect through the IoT Edge, it can only connect directly to the DPS service.

**Comment by sanjeev-magoo** [comment]
Thanks @ewertons for your response.
We would also like to understand, if say leaf device has connectivity (for registration only) and is getting registered using DPS to IoTHub, edge device is also registered to same IoTHub. what is the MS recommendation on -
1. Establishment of parent/child relation between edge and leaf device (looking for non-manual solution). if we use "GatewayHostName" in IoTHub connection string from child device to connect to IoTHub, will it automatically establish the parent/child relation between edge and leaf device?
2. How child device will come to know about its edge device (GatewayHostName) for further interacting with IoTHub via edge.

**Comment by ewertons** [comment]
Hi @sanjeev-magoo ,
thanks for your questions but they seem to be related to Azure IoT Edge, not the C SDK client itself.
It would be something to be posted on https://github.com/azure/iotedge, however to save you a hoop I will direct the question internally.

**Comment by ewertons** [comment]
Closing this issue as it has been tracked by azure/iotedge#3419
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@sanjeev-magoo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
