### ISSUE TITLE
Device cannot connect to IoT Hub after several hours of correct communication  - IOTHUB_CLIENT_CONNECTION_NO_NETWORK

### ISSUE THREAD

**Issue by andpc** [Azure/azure-iot-sdk-c#1595]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Raspberry Pi Zero W with Raspberry Pi OS - Lite (release 2020-05-27).
Cross Compiled on Docker Debian:stretch using arm-rpi-4.9.3-linux-gnueabihf.

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Using latest LTS_07_2020_Ref1 - 2eab39c37bd31740f05e12599379ea83f4dd8802

**Protocol**

MQTT

**Describe the Bug**

I'm having problems reconnecting my devices to IoT Hub after I leave them connected for several hours. 
The steps I have to reproduce are:

1) Register the device to IoT Hub using a self-signed x509 certificate
2) Let the device connect to IoT Hub and sync device twin for several hours
3) After some time, the device is not able to connect to IoT Hub (log provided below)
4) If I change connection credentials (ID and certificates) to another device, it starts to communicate again.

For me, it looks like this specific device ID's connection is being dropped since it cannot even validate the certificate. 

Note: internet connection is reliable. I can reach the internet and also connect with other device id and credentials as explained above

Code used to connect to IoT Hub (simplified to present only SDK related code)
```
IOTHUB_DEVICE_CLIENT_LL_HANDLE device_ll_handle = otHubUtils::getIotHubLLHandle(generalConfig.value("fixedAsset",""));

IoTHubDeviceClient_LL_SetOption(deviceHandle, OPTION_X509_CERT, cert_read.c_str());
IoTHubDeviceClient_LL_SetOption(deviceHandle, OPTION_X509_PRIVATE_KEY, priv_read.c_str());

if (IoTHubDeviceClient_LL_SetMessageCallback(device_ll_handle, receive_msg_callback, &messages_count) != IOTHUB_CLIENT_OK)
{
    (void)printf("ERROR: IoTHubClient_LL_SetMessageCallback..........FAILED!\r\n");
}

IoTHubClientCore_LL_SetConnectionStatusCallback(device_ll_handle, iothub_status_callback, &messages_count)

size_t retrytimeoutlimit = 300;
IoTHubDeviceClient_LL_SetRetryPolicy(device_ll_handle, IOTHUB_CLIENT_RETRY_RANDOM, retrytimeoutlimit);

bool traceOn = true;
IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_LOG_TRACE, &traceOn);

do{
    ThreadAPI_Sleep(1000);
    IoTHubDeviceClient_LL_DoWork(device_ll_handle);
   
}while(true);

```

**Console Logs**

-> 16:48:03 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME:**********/********/?api-version=2019-10-01&DeviceClientType=iothubclient%2f1.3.9%20(native%3b%20Linux%3b%20armv6l) | CLEAN: 0
IoTHub connection status: NOK - IOTHUB_CLIENT_CONNECTION_NO_NETWORK

Until retry expires 
IoTHub connection status: NOK - IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED

**Comment by ewertons** [comment]
Hi @andpc ,
the log you provided actually doesn't show the errors that caused the connection to be dropped.
What can be inferred from your snipped is that the device client had some connection issue, and couldn't reconnect for 300 seconds (5 minutes), which then caused the retry logic to simply stop retrying to reconnect.
If you do not want the client to stop retrying, use retryTimeoutLimit = 0, or just don't set it and let the client use the default retry logic (exponential backoff with jitter, never expires).
As per the comment you made - "For me, it looks like this specific device ID's connection is being dropped since it cannot even validate the certificate." - please provide full verbose console logs so we can try to investigate what is going on.

**Comment by ewertons** [comment]
Hi @andpc ,
we will close this issue for now, but please feel free to reopen it or create a new one if you would like to follow up.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@andpc, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
