### ISSUE TITLE
Bug in sample iothub_ll_telemetry_sample file iothub_ll_telemetry_sample.c 

### ISSUE THREAD

**Issue by Lisa999** [Azure/azure-iot-sdk-c#1599]
This code:

> #if defined SAMPLE_MQTT || defined SAMPLE_MQTT_WS
>         //Setting the auto URL Encoder (recommended for MQTT). Please use this option unless
>         //you are URL Encoding inputs yourself.
>         //ONLY valid for use with MQTT
>         //bool urlEncodeOn = true;
>         //IoTHubDeviceClient_LL_SetOption(iothub_ll_handle, OPTION_AUTO_URL_ENCODE_DECODE, &urlEncodeOn);
> #endif

Should be:

> #if defined SAMPLE_MQTT || defined SAMPLE_MQTT_WS
>         //Setting the auto URL Encoder (recommended for MQTT). Please use this option unless
>         //you are URL Encoding inputs yourself.
>         //ONLY valid for use with MQTT
>         //bool urlEncodeOn = true;
>         //IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_AUTO_URL_ENCODE_DECODE, &urlEncodeOn);
> 
> #endif

The line:
 **//IoTHubDeviceClient_LL_SetOption(iothub_ll_handle, OPTION_AUTO_URL_ENCODE_DECODE, &urlEncodeOn);** 
is containing a non-existing variable (iothub_ll_handle)...

**Comment by ewertons** [comment]
You are absolutely correct, @Lisa999 .
Thanks for reporting the issue.
We will fix it promptly. 
For next issues like this, feel free to submit a PR as well. We greatly appreciate the community contributions.
-Azure IoT Team

**Comment by ewertons** [comment]
Fixed, thanks.

**Comment by az-iot-builder-01** [comment]
@Lisa999, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
