### ISSUE TITLE
Calling convention not explicitly declared in headers

### ISSUE THREAD

**Issue by tameraw** [Azure/azure-iot-sdk-c#16]
_From @paulmon on December 2, 2016 0:7_

The calling convention of the nuget libraries is __cdecl but it's not explicitly declared in the headers.  This means if the compiler option /Gd is not specified for msvc projects that there will by unresolved symbol errors because of the differing calling conventions.

_Copied from original issue: Azure/azure-iot-sdks#1005_

**Comment by tameraw** [comment]
_From @anporumb on January 9, 2017 21:56_

Hello @paulmon,

Our nugets (binaries)are produced with __cdecl convention. Our headers do not have the convention explicitly stated. We do not have nugets build with __stdcall convention.

Trying to use the nugets in a project with __stdcall convention will fail at link time.

There are several ways to advance this topic:
1) in the short term, I could recommend writing a workaround. This workaround is a passthrough layer that simply changes calling convention.
2) in the long term produce nugets that have both calling conventions in them. I would very much appreciate any constribution in this area, even as "advice" (how to pack two calling conventions in the same nuget).

Best Regards,
Andrei Porumb

**Comment by tameraw** [comment]
_From @paulmon on January 9, 2017 22:0_

Yes. That's the problem.  The headers do not work in a build environment where __cdecl is not the default calling convention.  If you explicitly declare the library methods as __cdecl you don't need 2 libraries or 2 sets of headers.

**Comment by tameraw** [comment]
_From @anporumb on January 9, 2017 22:17_

Got it! I will label this with "Enhancement". (and copy it to our internal backlog)

Thank you!

**Comment by zolvarga** [comment]
Hi Paul,

Thanks for reporting this, I am working on the issue reported and will let you know when it is checked in.

Best Regards,
Zoltan

**Comment by tameraw** [comment]
@paulmon - Please use the /Gd option. If this is still a blocking issue, please open new issue. Thanks.
