### ISSUE TITLE
configure -Dhsm_type_symm when using vcpkg

### ISSUE THREAD

**Issue by alonf** [Azure/azure-iot-sdk-c#1602]
------------------------------- delete below -------------------------------
I am trying to follow this quickstart: https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-symm-key
But instead of git clone, and cmake -Dhsm_type_symm_key:BOOL=ON -Duse_prov_client:BOOL=ON  ..
I'd like to use the VCPKG package manager.
I tried to run this: vcpkg install azure-iot-sdk-c[use-prov-client,core]:x64-windows
But it does not set the hsm_type_symm

In the cmake file, there is this line:
set(hsm_type_symm_key OFF CACHE BOOL "Symmetric key type of hsm used with the Provisioning client")

and later below, there is this:

Set Provisioning Information.  This will also setup appropriate HSM
if (${use_prov_client})
    set(use_prov_client_core ON)
    if ("${hsm_custom_lib}" STREQUAL "")
        if ((NOT ${hsm_type_x509}) AND (NOT ${hsm_type_sastoken}) AND (NOT ${hsm_type_symm_key}))
            # If the cmake option did not explicitly configure an hsm type, then enable them all.
            set(hsm_type_x509 ON)
            set(hsm_type_sastoken ON)
            set(hsm_type_symm_key ON)
        endif()
    else()
        set(hsm_type_custom ON)
    endif()
endif()

But I don't see any option that I can provide to the vcpkg to enable it.
How should I do it?

Thanks,

Alon.

**Comment by mlunt-msft** [comment]
Hi Alon,

Inside the port file (portfile.cmake, under ...\vcpkg\ports\azure-iot-sdk-c ) you'll see: 

vcpkg_configure_cmake(SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS ${FEATURE_OPTIONS}
        -Dskip_samples=ON
        -Duse_installed_dependencies=ON
        -Duse_default_uuid=ON
        -Dbuild_as_dynamic=OFF
        -Duse_edge_modules=ON
        **-Dhsm_type_symm_key=${use_prov_client}**
)

You can add any value here to set the option for vcpkg. Note that this only applies to your local config.

Thanks,
Morgan

**Comment by alonf** [comment]
Hi,

Thanks, this is what I did, and it solved the problem.
I've got an answer that this issue will be fixed in the next release.

Alon.

**Comment by danewalton** [comment]
Hi @alonf it seems this was resolved so I'm going to go ahead and close this for now. Please let us know if you would like it reopened.

**Comment by az-iot-builder-01** [comment]
@mlunt-msft, @alonf, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
