### ISSUE TITLE
Missing include files from azure-iot-c-sdk apt-get package

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/azure-iot-sdk-c#1604]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Raspberry Pi4: arm32v7/ubuntu:xenial

**SDK Version (Please Give Commit SHA if Manually Compiling)**

apt-get package as of 2020-07-28

**Protocol**

**Describe the Bug**

Cannot compile sample code [Get started with IoT Hub module identity and module twin (C)](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-c-c-module-twin-getstarted).   Installed azure-iot-sdk-c using directions at: [Use apt-get to create a C device client project on Ubuntu](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/ubuntu_apt-get_sample_setup.md).

This is the machine installation in a DockerFile.

```
FROM arm32v7/ubuntu:xenial AS base
RUN apt-get update && \
    apt-get install -y --no-install-recommends apt-utils software-properties-common && \
    add-apt-repository -y ppa:aziotsdklinux/ppa-azureiot && \
    apt-get update && \
    apt-get install -y azure-iot-sdk-c-dev
```

The following files are not in the package.

iothub_service_client_auth.h
iothub_registrymanager.h

The github repo still has these C++ objects.  Installing the SDK from git is not easy since it's in an Edge Module container.  I am stuck with C++ since there are 3rd party C++ library dependencies.  Are there any options?

**Comment by ewertons** [comment]
Hi @RotateAt60MPH , this is not expected, you should be able to install the published packages.
We will verify that and reply to you shortly.

**Comment by RotateAt60MPH** [comment]
Looks like a few more header files are missing:

iothub_devicetwin.h
iothub_service_client_auth.h

**Comment by RotateAt60MPH** [comment]
While this is being reviewed, is my only alternative to load the azureiot SDK into the module container and compile it?

**Comment by RotateAt60MPH** [comment]
@ewertons <nudge>

**Comment by jbobotek** [comment]
@RotateAt60MPH Yes, I would download the whole repo.

**Comment by RotateAt60MPH** [comment]
@jbobotek Thanks.  Will that be my only choice, or will this eventually be addressed in the apt-get package?  It's a lot of work to include the loading/building of the repo in/out of the RPI4 docker container.

**Comment by jbobotek** [comment]
We are looking into this missing file issue as we speak.

**Comment by ewertons** [comment]
@RotateAt60MPH ,
we have been split between maintaining this SDK and working on the new azure-sdk-for-c SDK, so response to github issues might be delayed. We apologize for that.

Giving a deeper look into this issue, the short answer is that the headers you are asking about are not supposed to be distributed through our apt packages anymore.

The service client in the azure-iot-sdk-c is not [being actively supported anymore](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_service_client#end-of-active-development-for-service-sdk), giving space for our other sister SDKs (https://github.com/Azure/azure-iot-sdk-csharp, https://github.com/Azure/azure-iot-sdk-java, https://github.com/Azure/azure-iot-sdk-node) to fill that gap. We are only keeping the library in the code base for backwards support, but with minimum maintenance. 
That is the reason why you do not see in the article you mentioned anything related to apt packages.
Following that documentation, the approach available is to access the code directly from github. 
But be advised that the service client in this C SDK is not being actively supported and should not be used for new development.

**Comment by ewertons** [comment]
@RotateAt60MPH ,
if you would like to follow up on this question, please feel free to reopen the issue or file a new one.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@RotateAt60MPH, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
