### ISSUE TITLE
How to cross compile IoT C-sample code for RPI?

### ISSUE THREAD

**Issue by bbpaulvanharen** [Azure/azure-iot-sdk-c#1606]
I've followed the instructions on https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md to create / set-up the cross compilation environment for the Azure IoT SDK for the Raspberry Pi. 

Now, I'm looking for guidance how to build the sample code from the iothub_client/samples and the provisioning_client/samples. What are the next steps once the SDK is build?

**Comment by ewertons** [comment]
@jbobotek , do we have documentation showing how to build our samples using installed azure-iot-sdk-c libraries?

**Comment by jbobotek** [comment]
Thanks @ewertons for passing this my way. @bbpaulvanharen if you have already set up the cross compile environment like you say, the samples should be built as a part of the build.sh. [This Readme](https://github.com/Azure/azure-iot-sdk-c/tree/master/samples#azure-iot-c-sdk-samples) has a link to the various samples. Make sure you fill in your hub and DPS credentials in places like [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L53) and [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/samples/prov_dev_client_sample/prov_dev_client_sample.c#L63) before compiling.

**Comment by bbpaulvanharen** [comment]
@jbobotek : I've reloaded and rebuild the SDK and I can now find the sample executables as expected. 

May I suggest to describe the structure of the SDK file tree somewhere?

**Comment by ewertons** [comment]
Hi @bbpaulvanharen , thanks for letting us know that your project is unblocked.

We also thank you for the suggestion, however the internal file structure of the SDK changes with a certain frequency and it might not add as much value as we would expect.
There are other work items open internally to improve documentation, so we have plans for improvement there.

Thanks for your question.
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@bbpaulvanharen, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
