### ISSUE TITLE
NULL iothubClientHandle issue

### ISSUE THREAD

**Issue by blackzw** [Azure/azure-iot-sdk-c#1613]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
Linux

**SDK Version (Please Give Commit SHA if Manually Compiling)**

tag 1.3.8

**Protocol**

MQTT

**Describe the Bug**

the connection between device and IoTHub is crashed with the log follow:
```bash
msg_azure_process   recvfrom azure  <<  {"From":"azure-msg","RES":"Connect","Errno":-1}
Error: Time:Tue Jul 28 10:41:59 2020 File:/wdisk/wxj/work/t21/project/azure-iot-sdk-c/iothub_client/src/iothub_client_core.c Func:IoTHubClientCore_SendEventAsync Line:1322 NULL iothubClientHandle
```

**Console Logs**

```bash
msg_azure_process   recvfrom azure  <<  {"From":"azure-msg","RES":"Connect","Errno":-1}
Error: Time:Tue Jul 28 10:41:59 2020 File:/wdisk/wxj/work/t21/project/azure-iot-sdk-c/iothub_client/src/iothub_client_core.c Func:IoTHubClientCore_SendEventAsync Line:1322 NULL iothubClientHandle
````

**Comment by ewertons** [comment]
Hi @blackzw ,
please attach a debugger and verify if you are using the SDK properly.
This error message is accurate and it is exactly what it means, you are passing a NULL reference for the handle argument to that particular function.
Please debug and fix that on your application, and you should then have it working.

-Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@blackzw, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by ewertons** [comment]
For more details please use one of our samples as reference: https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples
