### ISSUE TITLE
Incorrect Log message in Prov_Device_LL_SetOption

### ISSUE THREAD

**Issue by contre** [Azure/azure-iot-sdk-c#1614]
When passing the PROV_OPTION_TIMEOUT option name, the error message will say "setting proxy options" which is incorrect as the timeout is being set.

https://github.com/Azure/azure-iot-sdk-c/blob/e6244f3664e86fc8c15d395ccd2375dda3dd404c/provisioning_client/src/prov_device_ll_client.c#L1281

This appears to be a copy paste error and I believe the message should be different.

**Comment by ewertons** [comment]
Absolutely correct, thanks for reporting it.

**Comment by ewertons** [comment]
Fixed.
Thanks for contributing to the Azure IoT SDKs!

**Comment by az-iot-builder-01** [comment]
@contre, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
