### ISSUE TITLE
No Reconnect attempt or device disabled notification

### ISSUE THREAD

**Issue by schroedermarius** [Azure/azure-iot-sdk-c#1617]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
Mac OS - ESP-IDF

ESP32-WROOM32

**Protocol**

MQTT

**Describe the Bug**

When the ESP32 loses the connection to the Azure IoT Hub, I cant see any reconnect-attempt. Also If im deactivating the device in azure iot hub, I cant see any callback happening in the client.
Im expecting to get at least a IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED...

**Comment by schroedermarius** [comment]
Seems to only happen when navigating through an iot edge gateway running on ubuntu.

**Comment by ewertons** [comment]
@schroedermarius , we need more information to be able to help.
Could you share where you got our code from, which version/commit hash and which sample you used?
Also would you be able to collect verbose logs?

**Comment by schroedermarius** [comment]
@ewertons Thanks for your response! I've done that by using the sample code "iothub_client_sample_mqtt" from the esp-azure project current master, which is using the azure-iot-sdk-c library.

I was able to narrow down the error a little more. It seems that the library does not notice if there is a communication error if you just send messages. By only sending messages every 5 seconds, the client is not sending any Keep Alive message which would react onto state changes. The keep alive time is resetted every time you send a message. So there is never happening a keep alive which also seems to trigger a retry.

Hopefully you can understand what I mean.

**Comment by ericwol-msft** [comment]
> the client is not sending any Keep Alive message which would react onto state changes. The keep alive time is resetted every time you send a message.

This is per the MQTT spec.

 _In the absence of sending any other Control Packets, the Client MUST send a PINGREQ Packet_

https://docs.solace.com/MQTT-311-Prtl-Conformance-Spec/MQTT%20Control%20Packets.htm#_Ref363645900

**Comment by schroedermarius** [comment]
@ericwol-msft 
Thats right, and I can understand that. But when sending messages every 5 seconds, there will never be a PINGREQ Packet, which is also right regarding the MQTT spec. But the Keep-Alive timer gets also resetted, when the MQTT Packet (my message) fails to send, which should not happen, right?

**Comment by ericwol-msft** [comment]
I assume if your MQTT packet fails to send, so will the PINGREQ packet, most likely due to network connectivity issue. Are you saying that PINGREQ packets are successful, but your MQTT packets are not?

**Comment by schroedermarius** [comment]
Please excuse me, I must have put myself wrong.

I have messages that are sent every 5 seconds.
If I now leave the KeepAlive timer at the default value, a PINGREQ is never sent even with faulty messages, which means that the client does not rehabilitate itself and continues to run with a faulty connection.

**Comment by ericwol-msft** [comment]
#1541
