### ISSUE TITLE
Azure C SDK is omitting the first 2 minutes of queued telemetry on connection loss

### ISSUE THREAD

**Issue by coffeeaddict19** [Azure/azure-iot-sdk-c#1621]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

I compiled the Azure SDK for C on a raspberry pi with GCC 6.3.0
I compiled my project on the same raspberry pi against the Azure SDK with GCC 9.2
I ran my project on a Freewave ZumIQ loaded with Debian 9

**SDK Version (Please Give Commit SHA if Manually Compiling)**

tag: LTS_07_2020_Ref01
commit: 2bff372a9b22b54d3d4bc9a3e74e349f68fcde46
git clone --recursive -b LTS_07_2020_Ref01 https://github.com/Azure/azure-iot-sdk-c.git

**Protocol**

MQTT

**Describe the Bug**

I'm sending telemetry via the Azure SDK (MQTT) once per second. The SDK performs flawlessly while connected to the internet.

This option is set:
`		IOTHUB_CLIENT_RESULT result = IoTHubDeviceClient_LL_SetRetryPolicy(
			device_ll_handle,
			IOTHUB_CLIENT_RETRY_INTERVAL,
			0
		);`
the result is IOTHUB_CLIENT_OK

I ran a test, while sending telemetry to the Azure SDK once a second:
1. disconnect the cable to the internet
2. wait 10 minutes
3. plug the internet cable back in

I expect to see the SDK re-send all of the queued telemetry from the time that it was disconnected from Azure IoT Hub. It does this correctly, EXCEPT for the first two minutes after the disconnection. For the 10 minutes that Azure SDK was disconnected I only see 8 minutes of data out of 10. The first 2 minutes are always missing.

When I receive the send event information callback, I print the result. I see a 2 minute gap here:

...
08/07/20 20:11:12: Azure - Send Event Confirmation Callback. Result: 'IOTHUB_CLIENT_CONFIRMATION_OK'
08/07/20 20:11:13: Azure - Send Event Confirmation Callback. Result: 'IOTHUB_CLIENT_CONFIRMATION_OK'
08/07/20 20:11:14: Azure - Send Event Confirmation Callback. Result: 'IOTHUB_CLIENT_CONFIRMATION_OK'
08/07/20 20:11:15: Azure - Send Event Confirmation Callback. Result: 'IOTHUB_CLIENT_CONFIRMATION_OK'
08/07/20 20:11:17: Azure - Send Event Confirmation Callback. Result: 'IOTHUB_CLIENT_CONFIRMATION_OK'
08/07/20 20:11:18: Azure - Send Event Confirmation Callback. Result: 'IOTHUB_CLIENT_CONFIRMATION_OK'
08/07/20 20:11:19: Azure - Send Event Confirmation Callback. Result: 'IOTHUB_CLIENT_CONFIRMATION_OK'
08/07/20 20:13:22: Azure - Send Event Confirmation Callback. Result: 'IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT'
08/07/20 20:13:45: Azure - Send Event Confirmation Callback. Result: 'IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT'
08/07/20 20:13:45: Azure - Send Event Confirmation Callback. Result: 'IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT'
08/07/20 20:13:45: Azure - Send Event Confirmation Callback. Result: 'IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT'
...

In regard to the Azure SDK logging itself, I see nothing until the 2 minute break elapses:

Error: Time:Fri Aug  7 20:13:45 2020 File:/home/pi/pkgs/src/azure/LTS_07_2020_Ref01/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:initiate_socket_connection Line:304 DNS resolution failed
Error: Time:Fri Aug  7 20:13:45 2020 File:/home/pi/pkgs/src/azure/LTS_07_2020_Ref01/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:825 lookup_address_and_connect_socket failed
Error: Time:Fri Aug  7 20:13:45 2020 File:/home/pi/pkgs/src/azure/LTS_07_2020_Ref01/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint

I don't know if this is a bug or if there is an option I need to set in the SDK. Please help.

**Comment by ericwol-msft** [comment]
Setting IOTHUB_CLIENT_RETRY_INTERVAL as your retry policy, parameter of the IoTHubClient_LL_SetRetryPolicy function is not the message retry interval, but the timeout after which any "connection retry" attempt is given up.

The OPTION_EVENT_SEND_TIMEOUT_SECS message retry option only applies if using AMQP protocol (not MQTT).

For MQTT the retry is controled by defines in [iothubtransport_mqtt_common.c](https://github.com/Azure/azure-iot-sdk-c/blob/ecdef3bbb2ff0e6434b6cca43a7b71abe799d0f7/iothub_client/src/iothubtransport_mqtt_common.c) which totals 2 mins.

```
#define RESEND_TIMEOUT_VALUE_MIN          1*60
#define MAX_SEND_RECOUNT_LIMIT              2
```

If your app receives a IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT message, the message is removed from the internal queue. It will not be retried, it is the responsibility of the app to re-queue these messages.

**Comment by coffeeaddict19** [comment]
> If your app receives a IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT message, the message is removed from the internal queue. It will not be retried, it is the responsibility of the app to re-queue these messages.

@ericwol-msft  This is very helpful.

I'll pass a pointer to my queue into the void pointer argument set in IoTHubDeviceClient_LL_SendEventAsync. If IOTHUB_CLIENT_CONFIRMATION_RESULT in the callback says IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT then I'll insert into my queue.

I'll do the same with IoTHubDeviceClient_LL_SetConnectionStatusCallback and depopulate the queue when the connection is restored.

**Comment by az-iot-builder-01** [comment]
@ericwol-msft, @coffeeaddict19, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
