### ISSUE TITLE
 iothub_convenience_sample works fine outside docker container but gives error certificate verify failed when run inside a docker container

### ISSUE THREAD

**Issue by MogheesBinZahid** [Azure/azure-iot-sdk-c#1622]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Raspberry Pi, Raspbian Stretch Lite (Release 2018-11-13)
Cross Compiled on (Raspbian 8.3.0-6+rpi1) using GCC  8.3.0
Docker file based on debian
 
**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2019-01-31

**Protocol**

MQTT

**Describe the Bug**
I am using [azure iot c sdk](https://github.com/Azure/azure-iot-sdk-c). I using iothub_convenience_sample from this [link](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_convenience_sample). I want to run this on a docker container. When I run the code outside docker container locally on my machine it works fine but when I run this inside docker container it is giving me following error

**Console Logs**
tlsio_openssl.c Func:send_handshake_bytes Line:674 error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

-  timezone and date time matching within container
- Connection string checking inside container
- Internet working inside container
- no proxy inside container
- normal wget on https is working inside container

timezone and date time is matched by using following command:
`
    ln -sf /usr/share/zoneinfo/Asia/Karachi /etc/localtime
`

**Comment by ewertons** [comment]
You are most likely not setting the trusted certificate for validating the server cert.

Please verify the code is being compiled to set the [trusted cert](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample.c#L284).

**Comment by MogheesBinZahid** [comment]
Thanks got it

**Comment by ewertons** [comment]
Thanks @MogheesBinZahid 
We will close this issue as resolved, but please post a comment if you would like to follow up.
- Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@MogheesBinZahid, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
