### ISSUE TITLE
Deb package with tpm_device_provision

### ISSUE THREAD

**Issue by alevincenzi** [Azure/azure-iot-sdk-c#1623]
Hello

following your documentation, we are using the tool `tpm_device_provision` to extract the endorsement key from the tpm and register it in a DPS service. We clearly understood that we should not use the tpm2-tools (the ek is not accepted) but with your tool everithing works fine.

We are making this process automatic and to do so we would like to have a deb package that install `tpm_device_provision` and run it when we build our images and register the device. Is there any way to have it installed in a linux distribution?

We see that you [release something on launchpad](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/ubuntu_apt-get_sample_setup.md#update-and-install-the-azure-iot-sdk-c-dev-package-on-your-machine) but that package include only the SDK, not the provisioning tools. Am I right?

The only solution that we found is to clone your repo, build it with our pipes and generate the artifact.

Do you offer any alternative?

Thanks

**Comment by ewertons** [comment]
Hi @alevincenzi ,

the only options for getting access to the tpm_device_provision tool would be directly cloning the repo or through vcpkg (which is a code distribution tool as well).

We do not have plans to expand the scope of the current deb packages.

**Comment by az-iot-builder-01** [comment]
@alevincenzi, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
