### ISSUE TITLE
Custom HSM exposing interface to get private key

### ISSUE THREAD

**Issue by sanjeev-magoo** [Azure/azure-iot-sdk-c#1629]
We are using custom HSM to register IoT devices using x509 certificate to IoTHub using DPS. We have followed example given at https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/samples/custom_hsm_example/custom_hsm_example.c for custom HSM module.

This module return a structure of function pointers where one of the function (custom_hsm_get_key) is to return the private key.

static const HSM_CLIENT_X509_INTERFACE x509_interface =
{
    custom_hsm_create,
    custom_hsm_destroy,
    custom_hsm_get_certificate,
    **_custom_hsm_get_key,_**
    custom_hsm_get_common_name
};

Following are my questions-
1. Currently we are storing private key on encrypted disk and reading it from custom HSM module, however our preference is to store private key inside the custom HSM module.  is this currently possible? Any documentation reference will be a great help.
2. is there a way that private key don't leave HSM module? Above mentioned function pointer from custom HSM module can be used to get the private key.
3. Support of PKCS #11 standard?

**Comment by sanjeev-magoo** [comment]
Can someone please help on above query?
If this doesn't make sense, please help me with documentation to correct my understanding.

**Comment by danewalton** [comment]
Hi @sanjeev-magoo 
There seems to be several platform specific requirements which would be difficult for us to ramp up support for. I would suggest you try our [Embedded C SDK here](https://github.com/Azure/azure-sdk-for-c) which provides you all the flexibility you might need for your solution. There, the TLS setup is up to you including any HSM module you might be using.

**Comment by danewalton** [comment]
I'm going to go ahead and close this for inactivity but feel free to open another issue or add a comment here if you would like it reopened.

**Comment by az-iot-builder-01** [comment]
@sanjeev-magoo, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
