### ISSUE TITLE
Azure IoT Hub SAS Token expires

### ISSUE THREAD

**Issue by LJenny** [Azure/azure-iot-sdk-c#163]
- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

I'm using the mosquitto library to connect my device directly to azure iot via MQTT protocol.
For the connection, the SAS token is used.
(Actually, I'm not using the Azure sdk..)

My device publishes some data at regular intervals to azure iot,
(topic : devices/mydevice1/messages/events/)
but the device continues publishing to azure iot even after the expiration of the token.

I found a similar problem in the stackoverflow.
https://stackoverflow.com/questions/42345527/azure-iot-hub-sas-token-doesnt-expire
I'm wondering if it's really a bug reported.

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by tameraw** [comment]
@LJenny - Thanks for filing this. Have you tried sending data to the hub beyond 5 minutes after the token has expired? There is a 5 min grace period after token expiration before the hub rejects the connection from a device.

**Comment by LJenny** [comment]
@tameraw - Thank you very much for your response.
I've tested, but I was able to continue publishing more than five minutes after the tokens expired.(Continuing publish ack was delivered.) I'm not sure what's wrong with it.

**Comment by tameraw** [comment]
@LJenny - Thanks for confirming. We confirmed it's a bug on our side and will be providing a fix in a future release. Will keep you posted once available.
Regards.

**Comment by FrankZhcz** [comment]
Any update for this bug, was it fixed?

**Comment by yzhong94** [comment]
@FrankZhcz We are rolling out a fix now.  We will update this thread when the rollout is completed.

**Comment by amogh79** [comment]
@yzhong94 our device team is facing the exact same issue. Can you please let me know when the fix would be rolled out? This fix would be on C sdk or this fix is on IoT Hub?

**Comment by jspaith** [comment]
This required a server change and it has been rolled out now, so we can close this.

**Comment by az-iot-builder-01** [comment]
@LJenny, @FrankZhcz, @amogh79, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
