### ISSUE TITLE
C SDK AMQP_WS Network Disconnect and Reconnect

### ISSUE THREAD

**Issue by nitu011** [Azure/azure-iot-sdk-c#1635]
------------------------------- delete below -------------------------------

Azure C SDK is taking 4 minutes to identify the Network Disconnection and Network Availability while using AMQP_WS protocol. 
In this forum , I got solution:

size_t keepAliveFrequencySecs = 60;
IoTHubClient_SetOption(iothubClientHandle, OPTION_SERVICE_SIDE_KEEP_ALIVE_FREQ_SECS, &keepAliveFrequencySecs);

After this , its not taking 4 minutes , but wanted to understand if I keep it to 30 seconds what will be consequences. After network disconnect or any other issue , will it report within 30 seconds . What if my device is not sending heart beat for 30 seconds interval ?
------------------------------- delete above -------------------------------

**Comment by nitu011** [comment]
I am also seeing in case iot disconnection or network disconnect , it takes 10-15 seconds with latest change but in this time interval, events are getting missed since device dont know  iot disconnected . Any suggestion ?

**Comment by nitu011** [comment]
raising a bug so closing this one

**Comment by az-iot-builder-01** [comment]
@nitu011, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
