### ISSUE TITLE
Azure IoT SDK cross compiling and next steps

### ISSUE THREAD

**Issue by ma2teo** [Azure/azure-iot-sdk-c#1636]
Dear all,
I have some difficulties to understand how proceed after I cross compile the Azure IoT SDK.

Following the document https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md , I am able to cross compile the Azure IoT SDK without errors.
Once I have built the SDK, how can I use the cross compiled SDK to build a simple program? How do I have to use the .a files resulting from the cross compilation?. 

Thanks in advance for any kinds of suggestions.
Regards

**Comment by ma2teo** [comment]
Hi @danewalton ,
Thanks for the interest to the matter.

I am trying to use Microsoft Azure IoT device SDK for C for my BeagleBone Black.

So I have followed the document https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md as guideline for the cross compilation. I have modified the toolchain-rpi.cmake file with the appropriate C compiler and the file system root, then I have built the entire SDK. In this way I have obtained several static libraries and numerous cross compiled sample applications ready to use.

At this point I would like to introduce some custom code.
This is my first experience with the compiling and linking from the terminal (cmake, gcc, …), so I have simply modified the sample applications and then I have rebuilt the entire SDK as described in the document for the cross compilation. I suppose that this approach is incorrect because it shouldn’t be necessary rebuild all the SDK for little modifies in the custom code.
I would simply “link” my custom main.c to the cross compiled libraries, but I have difficulties to understand how start, so I haven't selected a specific build process.

Do you have some indications to begin to use the Microsoft Azure IoT device SDK with a simple custom main.c?.
Thanks a lot for your support.
Regards.

**Comment by markrad** [comment]
Hi @ma2teo 

I recommend that you take a look at this document: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Docker_SDK_Cross_Compile.md. Though you may not wish to use a docker container to cross compile the SDK, it still provides the steps needed to accomplish that in the dockerfile. You can simply run those commands at the console if you wish.

However, unlike the document you referenced, this one provides samples of how you can utilize your cmake toolchain file to build your application and link it to the IoT libraries.

**Comment by ma2teo** [comment]
Hi @markrad,
Thanks a lot for your suggestions,

I have followed that document and now I am able to cross compile my custom code without cross compile all the Microsoft Azure IoT device SDK each time.

Thanks again.
Regards

**Comment by az-iot-builder-01** [comment]
@danewalton, @ma2teo, @markrad, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by ma2teo** [comment]
Hi @markrad,
Thanks a lot for your suggestions,

I have followed that document and now I am able to cross compile my custom code without cross compile all the Microsoft Azure IoT device SDK each time.

Thanks again.
Regards
