### ISSUE TITLE
events getting lost when  C SDK AMQP_WS Network Disconnect 

### ISSUE THREAD

**Issue by nitu011** [Azure/azure-iot-sdk-c#1637]
------------------------------- delete below -------------------------------
Azure C SDK is taking 4 minutes to identify the Network Disconnection and Network Availability while using AMQP_WS protocol.
In this forum , I got solution:

size_t keepAliveFrequencySecs = 60;
IoTHubClient_SetOption(iothubClientHandle, OPTION_SERVICE_SIDE_KEEP_ALIVE_FREQ_SECS, &keepAliveFrequencySecs);

After this , its not taking 4 minutes , but wanted to understand if I keep it to 30 seconds what will be consequences. After network disconnect or any other issue , will it report within 30 seconds . What if my device is not sending heart beat for 30 seconds interval ?

I am also seeing in case iot disconnection or network disconnect , it takes 10-15 seconds with latest change but in this time interval, events are getting missed since device dont know iot disconnected . Any suggestion ?

**Comment by ewertons** [comment]
Hi @nitu011 , you found the correct option to control the frequency of keep alives sent by the SDK.
The shorter the interval you set, more keep alives are sent. Also, higher is the chance that a response will not be received for some of the pings, causing the SDK client to start reconnecting more aggressively, and disrupting the connectivity with the IoT Hub.
The optimal point depends on the quality of your device's internet connectivity, and must be set according to an empirical evaluation. 
You should not be seeing any loss of  messages (memory loss). If the client is not connected, telemetry messages are  queued and not sent. They will expire eventually (the default timeout period for telemetry messages is around 4 minutes), so you should start getting callback invocations for each unsent message with a *TIMEOUT* reason.
If you are not getting those callbacks, please gather logs from valgrind to evaluate if you are really having any memory loss.
command:
`valgrind --leak-check=full --track-origins=yes ./your_binary`
The command above is valid for linux only, and the binary should be compiled with debug info in it.

**Comment by ewertons** [comment]
Hi @nitu011 ,
we will close this issue for now, but please feel free to post a comment or create a new one if you would like to follow up.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@nitu011, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
