### ISSUE TITLE
[AMQP]D2C events are getting lost when network is disconnected and not resent after network connects

### ISSUE THREAD

**Issue by nitu011** [Azure/azure-iot-sdk-c#1638]
------------------------------- delete below -------------------------------

azure iot c sdk :1.3.4

During network disconnect , I am getting event sent failed message but after network reconnect, event is not resent.
I am using IoTHubModuleClient_SendEventAsync function for sending D2C events.
We have a provision where if internet is not there , message will not be sent but the device detect network failure in 10-15 seconds. In this transient phase , if event is triggered its getting lost ,it never reaches cloud after network comes back.

Please help me to fix this issue

**Comment by nitu011** [comment]
Any update ? its really critical for me to fix

**Comment by danewalton** [comment]
Hi @nitu011 can you please take a look at this issue:
https://github.com/Azure/azure-iot-sdk-c/issues/1621
to see if it helps at all?

**Comment by ewertons** [comment]
Hi @nitu011 ,
similar to the other issue you filed, are you sure you are not getting invocations of the callback you passed to IoTHubDevice_LL_SendEventAsync()?
If you are really not, please provide valgrind logs as mentioned in the other issue (#1637 )

**Comment by ewertons** [comment]
Hi @nitu011 ,
we will close this issue for now but please feel free to reopen it if you have the logs and would like to follow up.
Note that if the device client code is leaking memory as your post suggests, valgrind will report those failures. So far we did not have any repros of this issue.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@coffeeaddict19, @nitu011, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
