### ISSUE TITLE
Direct method "DeviceMethodCallback" response not in valid JSON format

### ISSUE THREAD

**Issue by harikeshydv** [Azure/azure-iot-sdk-c#1641]
I am running IoT Hub sample project on ESP32 device using Azure IoT Device SDK for C. It's returning the following response for a direct method when I am calling it from Azure portal:
"Successfully invoke device method"

However, we are using the Node SDK's invokeDeviceMethod() of azure-iothub to invoke the direct method. I get an exception on this method with the following error string:
'Unexpected token  in JSON at position 70'

As per my research, C direct method is not sending data is proper json format which is required by node APIs.

https://github.com/Azure/azure-iot-sdk-node/issues/736

Kindly help!

**Comment by danewalton** [comment]
Can you detail what sample you are using or how you are using the API's?

**Comment by harikeshydv** [comment]
Thanks @danewalton for your quick reply

I have setup ESP32 Device as per the steps mentioned in article below to integrate with Azure IoT Hub:
https://docs.microsoft.com/en-us/samples/azure-samples/esp32-iot-devkit-get-started/sample/


And I am using NodeJS BackEndApplication.js file to call the direct method as mentioned in this link:
https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-control-device-node#call-the-direct-method

Apart from connection strings and device details, there are no other coding changes done in these examples.

Please let me know if any additional information is needed from my end.

**Comment by danewalton** [comment]
Are you able to verify using the [IoT Explorer](https://github.com/Azure/azure-iot-explorer/releases) what the message is that comes in?

**Comment by harikeshydv** [comment]
Getting exactly the same error as I was getting in NodeJs application:
**Error: Unexpected token  in JSON at position 70**

**Comment by danewalton** [comment]
What is the message you are sending back from the method? At least from what I can tell with the sample, the response would be valid JSON.

**Comment by harikeshydv** [comment]
I have not changed the response message. it's exactly the same which is mentioned in example:
**const char *responseMessage = "\"Successfully invoke device method\"";**

**Comment by danewalton** [comment]
Interesting....the error says unexpected token at position 70 but the message is only 33 characters long? And if I put it  in that wrapper from the other issue:
```json
"{"status":200,"payload":{"Successfully invoke device method"}}"
```
that's only 62 characters long. Can you post the raw data that the hub is receiving? So in the NodeJS case print out what the application receives before parsing the doc.

**Comment by harikeshydv** [comment]
Just a small correction. The error is happening at position no 59 with default response message.
Response Message:
`const char *responseMessage = "\"Successfully invoke device method\"";`

Error:
**Failed to invoke method on device ESP32*********: Error: Unexpected token  in JSON at position 59**

**Comment by danewalton** [comment]
Ah okay here's what's happening. So
```json
"Successfully invoke device method"
```
is valid JSON by itself. This would parse out correctly. Now underneath the covers, this value is getting wrapped in the 
```json
{"status":200,"payload":{"Successfully invoke device method"}}
```
wrapper. This is no longer valid JSON. Try changing the `*responseMessage`
to
```c
\"value\":\"Successfully invoked device method\"
```

**Comment by harikeshydv** [comment]
Hi @danewalton 

I already tried all these options, but it doesn't work.

Here is the error I am getting when passing the *responseMessage as the string you mentioned:
{"message":"{\"Message\":\"{\\\"errorCode\\\":502101,\\\"trackingId\\\":\\\"0b205c42b5f94fef980fab9e7bf12f9a-G:21-TimeStamp:09/05/2020 09:50:22-G:9-TimeStamp:09/05/2020 09:50:22\\\",\\\"message\\\":\\\"Payload is not a valid document of type `application/json`.\\\",\\\"info\\\":{},\\\"timestampUtc\\\":\\\"2020-09-05T09:50:22.6747425Z\\\"}\",\"ExceptionMessage\":\"\"}"}

As per my understanding the default *responseMessage message structure is correct. However, the issue is happening because somehow C SDK is sending the response message string in single quote instead of double quotes, which is not a valid JSON format.

Please suggest.

**Comment by danewalton** [comment]
Damn that's weird. So the core "wrapper" code seems to be living here:
https://github.com/VSChina/ESP32_AzureIoT_Arduino
They do a wrapping around our SDK that could be doing some unintended stuff. I'll have to get a board to try this out for myself so might take a bit of time. Thanks for your patience here.

**Comment by harikeshydv** [comment]
Thanks for the update

**Comment by harikeshydv** [comment]
Hi @danewalton 

JFYI...I tried the steps mentioned in below git repo, but getting exactly the same error:
https://github.com/VSChina/ESP32_AzureIoT_Arduino

**Comment by harikeshydv** [comment]
@danewalton : Any update on this?

**Comment by danewalton** [comment]
Hi @harikeshydv,
I haven't been able to find an answer yet but I would suggest you issue a GH issue on the above repo (https://github.com/VSChina/ESP32_AzureIoT_Arduino) since it seems to be a bug in their code. If I find some new info I will post it here.

**Comment by danewalton** [comment]
Oh wait I got it.
So debugging the service side, here is what it looks like:

![image](https://user-images.githubusercontent.com/36710865/93834209-e55d9780-fc2f-11ea-9dd6-97d73e3c85b6.png)

Everything looks to be okay but copying the value of the string over looks like this
```json
"{\"status\":200,\"payload\":{\"payload\":\"Successfully invoke device method\"}\u0000}"
```

So it seems a `NULL` character is getting tacked on. Looking at the device code, [here's the culprit](https://github.com/VSChina/ESP32_AzureIoT_Arduino/blob/29d647b8fb9583065c1aa165d041485c7e7b19ba/examples/GetStarted/GetStarted.ino#L95):
```c
*response_size = strlen(responseMessage) + 1;
*response = (unsigned char *)strdup(responseMessage);
```

The response size should be the length of the string NOT including the `NULL`. So change it to
```c
*response_size = strlen(responseMessage);
*response = (unsigned char *)strdup(responseMessage);
```

**Comment by harikeshydv** [comment]
Thanks @danewalton. It's working fine now.

**Comment by az-iot-builder-01** [comment]
@danewalton, @harikeshydv, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by mgonzalez738** [comment]
Had exactly the same problem. You saved me a lot of time. Thanks

**Comment by critchards** [comment]
AND MY AXE!
But really I had been trying to figure this out all afternoon. Thank you for finding and explaining this issue so well!
