### ISSUE TITLE
[azure-iot-sdk-c-1.3.4] : segfault when ThreadAPI_Sleep(x), x is changes to 1000

### ISSUE THREAD

**Issue by Nnalawade-eic** [Azure/azure-iot-sdk-c#1642]
machine - congatec IA5 Intel(R) Atom(TM) Processor E3930 @ 1.30GHz
build environment - yocto warrier
machine instruction set - 64 bit
SDK version - azure-iot-sdk-c-1.3.4
protocol MQTT

**Describe the Bug**
At the time of registration, if the value passed to ThreadAPI_Sleep() is changed to 1000, it crashes immediately with below error - 

kern.info,2020-08-25 19:16:28,99889N,kernel:,communication-m[1878]: segfault at 4 ip 00007f4b991ed7d6 sp 00007f4b9701a4a8 error 4 in libc-2.29.so[7f4b9917a000+142000]
kern.info,2020-08-25 19:16:28,99889N,kernel:,Code: 0f 1f 40 00 66 0f ef c0 66 0f ef c9 66 0f ef d2 66 0f ef db 48 89 f8 48 89 f9 48 81 e1 ff 0f 00 00 48 81 f9 cf 0f 00 00 77 6a <f3> 0f 6f 20 66 0f 74 e0 66 0f d7 d4 85 d2 74 04 0f bc c2 c3 48 83

I tried to change the value to 10 in  ThreadAPI_Sleep(), it does not crash, but does not get connected as well. Please help ASAP as I have invested 4 days debugging this without any success.

PFA valgrind_output.txt
[valgrind_output.txt](https://github.com/Azure/azure-iot-sdk-c/files/5136422/valgrind_output.txt)

**Comment by danewalton** [comment]
The failure seems to not be in our SDK from those logs. Can you see something like [this](https://github.com/sddm/sddm/issues/1179) to see if it helps at all?

**Comment by danewalton** [comment]
Related issue from that link above: https://github.com/sddm/sddm/issues/1206

**Comment by Nnalawade-eic** [comment]
Thank you @danewalton  for replay. 

I am not sure, why segfault stops after changing the value in ThreadAPI_Sleep(). Is there anything specific thing require for 64bit machine in yocto linux ?

**Comment by danewalton** [comment]
are you able to use this to try and diagnose what caused this segfault?
https://stackoverflow.com/questions/2179403/how-do-you-read-a-segfault-kernel-log-message

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now. Please feel free to open another issue if you have further issues.

**Comment by az-iot-builder-01** [comment]
@danewalton, @Nnalawade-eic, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
