### ISSUE TITLE
@azure-iot-sdk - When the IoT hub Connection error occur due to the reason "IOTHUB_CLIENT_CONNECTION_NO_PING_RESPONSE" ?

### ISSUE THREAD

**Issue by neethuantony42** [Azure/azure-iot-sdk-c#1644]
We are using the azure-iot-sdk -c 1.3.8 version.
When this IoT hub Connection error occurs due to the reason "IOTHUB_CLIENT_CONNECTION_NO_PING_RESPONSE". It is not reconnecting back. 
Could you please tell us when this error reason IOTHUB_CLIENT_CONNECTION_NO_PING_RESPONSE occurs.
At the same time we could ping to google that means network is available.
Please help us in this case.

Thanks,
Neethu

**Comment by danewalton** [comment]
Hi @neethuantony42 
A decent explanation for this dynamic can be found [here](http://www.steves-internet-guide.com/mqtt-keep-alive-by-example/). It has to do with the keep alive and whether the service responds back with a ping response. Are you having issues with this functionality? Could you provide more details about how you think it might be misbehaving?

**Comment by ericwol-msft** [comment]
This is part of the MQTT protocal (not ICMP ping)

http://www.steves-internet-guide.com/mqtt-keep-alive-by-example/

**Comment by neethuantony42** [comment]
Hi @danewalton ,
Thank you for your reply.
We are  developing an C++ QT application using azure-iot-sdk -c. And we are testing using roaming sim.
In our scenario the connection to iot hub fails due to  IOTHUB_CLIENT_CONNECTION_NO_PING_RESPONSE reason. 
 And our connection status callback invoked only for around 30 mins from the time of disconnection after that the callback is not invoked.

While establishing the iot hub connection we have only set 
IoTHubDeviceClient_SetOption(m_hDeviceHandle, OPTION_KEEP_ALIVE, &nPingInterval);   // pinginterval was set to 5 sec.

Please find our application log in which call back function executed time can be viewed.

_I|03.09.2020 02:50:49:705 [0.008239 s]|     |343   |0x713ff3e0| AzureIoTHubClientManager::connectionStatusCallback AICL_IOTHUBCONNSTATUS_NO_PING_RESPONSE 
I|03.09.2020 02:51:17:699 [0.005161 s]|     |343   |0x713ff3e0| AzureIoTHubClientManager::connectionStatusCallback AICL_IOTHUBCONNSTATUS_NO_PING_RESPONSE 
I|03.09.2020 02:51:55:703 [0.009026 s]|     |343   |0x713ff3e0| AzureIoTHubClientManager::connectionStatusCallback AICL_IOTHUBCONNSTATUS_NO_PING_RESPONSE 
I|03.09.2020 02:52:24:704 [0.008234 s]|     |343   |0x713ff3e0| AzureIoTHubClientManager::connectionStatusCallback AICL_IOTHUBCONNSTATUS_NO_PING_RESPONSE 
I|03.09.2020 03:00:35:701 [0.005864 s]|     |343   |0x713ff3e0| AzureIoTHubClientManager::connectionStatusCallback AICL_IOTHUBCONNSTATUS_NO_PING_RESPONSE 
I|03.09.2020 03:26:43:698 [0.005227 s]|     |343   |0x713ff3e0| AzureIoTHubClientManager::connectionStatusCallback AICL_IOTHUBCONNSTATUS_NO_PING_RESPONSE__ 

Could you please help us to resolve the issue. Why the call back is not executed after this?

Thanks,
Neethu

**Comment by danewalton** [comment]
Are you able to post the full log from the application using
```c
bool traceOn = true;
IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_LOG_TRACE, &traceOn);
```
for verbose logs.

**Comment by neethuantony42** [comment]
> Are you able to post the full log from the application using
> 
> ```c
> bool traceOn = true;
> IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_LOG_TRACE, &traceOn);
> ```
> 
> for verbose logs.

Thank you.
Will share the log as soon as possible.

**Comment by ericwol-msft** [comment]
Please don't set OPTION_KEEP_ALIVE. Use the SDK default.

**Comment by neethuantony42** [comment]
@ericwol-msft 
Could you please explain reason why don't we use the OPTION_KEEP_ALIVE?
It will be more helpful for us.
What will be the SDK default value how can we set it?

Could you please share us an example.

Can we set retry policy :
IoTHubDeviceClient_SetOption(m_hDeviceHandle, OPTION_RETRY_INTERVAL_SEC,&nPingInterval); // pinginterval was set to 5 sec. 
Is it ok to set the retry policy?

**Comment by ericwol-msft** [comment]
Setting the OPTION_KEEP_ALIVE outside the recommended value can cause disconnects if the send interval is too aggressive.
The default OPTION_KEEP_ALIVE value is defined below.

`#define DEFAULT_MQTT_KEEPALIVE              4*60 // 4 min`


Setting the `OPTION_RETRY_INTERVAL_SEC` only effects the retry interval of the device re-connection to the hub service if there is a disconnect. Setting a low number may increase your network bandwidth usage (especially an issue with devices using cellular networks) and the device is disabled in the hub or there is a network issue with the device connection to the hub service.

**Comment by neethuantony42** [comment]
Hi @ericwol-msft 
Thank you for the clarification.
If OPTION_KEEP_ALIVE  value is less than 4 mins it can cause cloud disconnection and it will not be retained again?


Our problem is after some period when the disconnection occurs due to   AICL_IOTHUBCONNSTATUS_NO_PING_RESPONSE      re connection to cloud IoT hub is not done and connectionstatuscallback is not invoked (means retry is not happening) even if the network is available.
When connection is not there we are not sending the telemetry. 

In this scenario what all option to be set get connection retry should be done.

Can we set the retry policy as shown below. 

IoTHubDeviceClient_SetOption(m_hDeviceHandle, OPTION_RETRY_INTERVAL_SEC,&nPingInterval); IoTHubDeviceClient_SetRetryPolicy(m_hDeviceHandle, IOTHUB_CLIENT_RETRY_INTERVAL,0);

what should be the better retry policy can be used to retain the cloud connection after disconnect in minimum span of time. Some cases the connectionstatuscallback  is invoked only after 20 or 25 mins or more. So that there  delay in getting the connection back.

Thanks,
Neethu.

**Comment by neethuantony42** [comment]
Hi @ericwol-msft
Could you please help us on this?

Thanks,
Neethu.

**Comment by ewertons** [comment]
Hi @neethuantony42 ,
So as you noticed, umqtt (the MQTT client within the Azure IoT C SDK) sends PINGs to the Azure IoT Hub frequently (by default, every 4 minutes as @ericwol-msft mentioned).
When there is no response to those PING requests, the SDK raises the callback to the user (you) with the status IOTHUB_CLIENT_CONNECTION_NO_PING_RESPONSE.
Please see here the exact code that raises the callback:
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L1924

If you got to this part of the code during runtime, it means you were able to connect to the Azure IoT Hub at least once.
There might have been an issue that caused lack of network connectivity, resulting in no responses received for the PING requests sent by the Azure IoT C SDK.

To understand what happened, we need the full Azure IoT C SDK verbose logs to verify.
Could you please collect the complete verbose logs (from beginning of SDK connection all the way to the PING response failure and later if anything gets printed) and attach them back here for us to verify?
Please use the command as posted by @danewalton above to enable the verbose logs.

**Comment by ewertons** [comment]
Regarding your question:
"If OPTION_KEEP_ALIVE value is less than 4 mins it can cause cloud disconnection and it will not be retained again?"

If the Keep Alive option (which controls the MQTT PINGs) is less than 4 minutes, it does not mean it will cause disconnections. 
However, it is all about network stability and throughput... if you send pings every 5 seconds, you increase the chance of one or more not receiving the PING responses in time (within those 5 seconds), causing the SDK to think there is a network problem, and try to reconnect to the Azure IoT Hub. 
So changing the PINGs to 5 seconds do not increase the reliability of your connection, it that's what you are asking.
If the SDK sends pings every 4 minutes, it may be able to detect loss of network only after 8 minutes (2 times the PING frequency), so you may reduce the PING frequency to increase the SDK sensitivity to notice loss of network. Changing it to 2 minutes or even 1 minute should be OK (depending on how good your network is), but 5 seconds is overkill.
I am not sure what you mean by "and it will not be retained again?". If you have a loss of network **and if you didn't change any of the default retry policy values of the Azure IoT C SDK**, the SDK should try to reconnect as soon as it detects loss of network and connect back after the internet is reachable again.

**Comment by neethuantony42** [comment]
Hi @ewertons ,
Thank you for the detail explanation.
We are getting this error only continuously running the application for 4 days. We will collect the log and share once the issue is reproduced.

Thanks,
Neethu

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now but please leave a comment if you would like this reopened. Possibly when you have the logs.

**Comment by az-iot-builder-01** [comment]
@danewalton, @ericwol-msft, @neethuantony42, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by leksh123** [comment]
Hi @danewalton,
I am writing this on behalf of @neethuantony42 . We would like to have this issue reopened since we are observing 
the error "Func:mqtt_error_callback Line:1882 Mqtt Ping Response was not encountered.  Reconnecting device..." in the trace logs attached. Please suggest....

[30Oct1.45pm.txt](https://github.com/Azure/azure-iot-sdk-c/files/5463873/30Oct1.45pm.txt)

**Comment by leksh123** [comment]
Hi @danewalton, could you please give an update for this issue?

**Comment by danewalton** [comment]
Hi @leksh123 having a look now.

**Comment by danewalton** [comment]
Hey @leksh123 looking at the logs, the time stamps lead me to believe that the mqtt keep alive might be a very low number:
![image](https://user-images.githubusercontent.com/36710865/98026330-cec66680-1dbf-11eb-9515-14a1fd7458fa.png)

The last received ping response is `11:35:17` and the timeout message is then `11:35:29`.

Also in the log file is this line:
```
-> 11:36:00 CONNECT | VER: 4 | KEEPALIVE: 5
```
So it seems your keep alive is set to 5 seconds.

**Comment by leksh123** [comment]
Thanks for the reply @danewalton.
I understand that the keep alive value depends on the network but is 1 minute the recommended value to improve the condition?

**Comment by danewalton** [comment]
Ideally we recommend keeping it at the default value
```c
#define DEFAULT_MQTT_KEEPALIVE 4*60 // 4 min
```
However 1 minute would be much better than 5 seconds.

**Comment by ericwol-msft** [comment]
You should only be changing the default value if your network stack does not correctly handle disconnect notifications.

**Comment by danewalton** [comment]
The origin of the issue seems to be mitigated for now so going to close it. Feel free to comment here again if you have related issues.
