### ISSUE TITLE
GCC 9.3 compiler gives error when use azure-iot-sdk-c with my application

### ISSUE THREAD

**Issue by hpatel2** [Azure/azure-iot-sdk-c#1646]
Hello,

I am using this SDK with my application. Till now I was using GCC 7.3 for my application build and it was working properly. Recently I have upgraded the GCC version to 9.3 and I am getting below error. Please help me to debug and resolve this issue. Below is log for the error.

Is there any compiler flag using which I can disable this error so that GCC 9 allows backward compatibility?

LOGS:

 arm-linux-gnueabi-gcc  -march=armv7ve -mthumb -mfpu=neon -mfloat-abi=hard --sysroot=/home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0=/usr/src/debug/gw/1.0-r0                      -fdebug-prefix-map=/home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0=/usr/src/debug/gw/1.0-r0                      -fdebug-prefix-map=/home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot-native=  -Os -rdynamic -Wall -funwind-tables -fstack-protector-all -I /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot -L /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/lib -DuECC_ENABLE_VLI_API -DuECC_VLI_NATIVE_LITTLE_ENDIAN=1 -DuECC_SQUARE_FUNC=1 -DuECC_SUPPORTS_secp256r1=1 -DuECC_SUPPORT_COMPRESSED_POINT=0 -DuECC_OPTIMIZATION_LEVEL=3 -DEARLY_DEBUG_PASSWD -DSTATIC="" -c -o iothub_seqnum.o iothub_seqnum.c
| In file included from /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_ll.h:31,
|                  from /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client.h:24,
|                  from iothub.c:56:
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:125:5: error: expected declaration specifiers or '...' before 'IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN'
|   125 |     IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN,            \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:125:5: note: in definition of macro 'IOTHUB_CLIENT_CONNECTION_STATUS_REASON_VALUES'
|   125 |     IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN,            \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:126:5: error: expected declaration specifiers or '...' before 'IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED'
|   126 |     IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED,              \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:126:5: note: in definition of macro 'IOTHUB_CLIENT_CONNECTION_STATUS_REASON_VALUES'
|   126 |     IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED,              \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:127:5: error: expected declaration specifiers or '...' before 'IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL'
|   127 |     IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL,               \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:127:5: note: in definition of macro 'IOTHUB_CLIENT_CONNECTION_STATUS_REASON_VALUES'
|   127 |     IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL,               \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:128:5: error: expected declaration specifiers or '...' before 'IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED'
|   128 |     IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED,                \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:128:5: note: in definition of macro 'IOTHUB_CLIENT_CONNECTION_STATUS_REASON_VALUES'
|   128 |     IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED,                \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:129:5: error: expected declaration specifiers or '...' before 'IOTHUB_CLIENT_CONNECTION_NO_NETWORK'
|   129 |     IOTHUB_CLIENT_CONNECTION_NO_NETWORK,                   \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:129:5: note: in definition of macro 'IOTHUB_CLIENT_CONNECTION_STATUS_REASON_VALUES'
|   129 |     IOTHUB_CLIENT_CONNECTION_NO_NETWORK,                   \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:130:5: error: expected declaration specifiers or '...' before 'IOTHUB_CLIENT_CONNECTION_COMMUNICATION_ERROR'
|   130 |     IOTHUB_CLIENT_CONNECTION_COMMUNICATION_ERROR,          \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:130:5: note: in definition of macro 'IOTHUB_CLIENT_CONNECTION_STATUS_REASON_VALUES'
|   130 |     IOTHUB_CLIENT_CONNECTION_COMMUNICATION_ERROR,          \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:131:5: error: expected declaration specifiers or '...' before 'IOTHUB_CLIENT_CONNECTION_OK'
|   131 |     IOTHUB_CLIENT_CONNECTION_OK,                           \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
| iothub.c:86:61: note: in expansion of macro 'IOTHUB_CLIENT_CONNECTION_STATUS_REASON_VALUES'
|    86 | DEFINE_ENUM_STRINGS(IOTHUB_CLIENT_CONNECTION_STATUS_REASON, IOTHUB_CLIENT_CONNECTION_STATUS_REASON_VALUES);
|       |                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:132:5: error: expected declaration specifiers or '...' before 'IOTHUB_CLIENT_CONNECTION_NO_PING_RESPONSE'
|   132 |     IOTHUB_CLIENT_CONNECTION_NO_PING_RESPONSE              \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:132:5: note: in definition of macro 'IOTHUB_CLIENT_CONNECTION_STATUS_REASON_VALUES'
|   132 |     IOTHUB_CLIENT_CONNECTION_NO_PING_RESPONSE              \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:114:5: error: expected declaration specifiers or '...' before 'IOTHUB_CLIENT_CONNECTION_AUTHENTICATED'
|   114 |     IOTHUB_CLIENT_CONNECTION_AUTHENTICATED,                \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:114:5: note: in definition of macro 'IOTHUB_CLIENT_CONNECTION_STATUS_VALUES'
|   114 |     IOTHUB_CLIENT_CONNECTION_AUTHENTICATED,                \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:115:5: error: expected declaration specifiers or '...' before 'IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED'
|   115 |     IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED               \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:115:5: note: in definition of macro 'IOTHUB_CLIENT_CONNECTION_STATUS_VALUES'
|   115 |     IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED               \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| iothub.c: In function 'connection_status_cb':
| iothub.c:805:15: warning: implicit declaration of function 'ENUM_TO_STRING'; did you mean 'MU_ENUM_TO_STRING'? [-Wimplicit-function-declaration]
|   805 |              (ENUM_TO_STRING(IOTHUB_CLIENT_CONNECTION_STATUS, result)), result,
|       |               ^~~~~~~~~~~~~~
|       |               MU_ENUM_TO_STRING
| iothub.c:805:30: error: expected expression before 'IOTHUB_CLIENT_CONNECTION_STATUS'
|   805 |              (ENUM_TO_STRING(IOTHUB_CLIENT_CONNECTION_STATUS, result)), result,
|       |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| iothub.c:806:30: error: expected expression before 'IOTHUB_CLIENT_CONNECTION_STATUS_REASON'
|   806 |              (ENUM_TO_STRING(IOTHUB_CLIENT_CONNECTION_STATUS_REASON, reason)), reason);
|       |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| iothub.c: In function 'azure_send_cb':
| iothub.c:1054:119: error: expected expression before 'IOTHUB_CLIENT_CONFIRMATION_RESULT'
|  1054 |                 glog(GLOG_ERROR, "[%s] Received NULL IoT event packet, with result = %s.\n", __func__, ENUM_TO_STRING(IOTHUB_CLIENT_CONFIRMATION_RESULT, result));
|       |                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| iothub.c:1076:44: error: expected expression before 'IOTHUB_CLIENT_CONFIRMATION_RESULT'
|  1076 |              ev->packet_id, ENUM_TO_STRING(IOTHUB_CLIENT_CONFIRMATION_RESULT, result), seq_num - ack_cnt - 1);
|       |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| make: *** [Makefile:87: iothub.o] Error 1

**Comment by hpatel2** [comment]
I found that the resolution for this issue is present under below pull request.
https://github.com/Azure/azure-iot-sdk-c/pull/1342

But it is not yet merged with master.

Is there any plan to merge this with master?

**Comment by danewalton** [comment]
It seems you might have various versions of the SDK and its submodule dependencies.

> | iothub.c:805:15: warning: implicit declaration of function 'ENUM_TO_STRING'; did you mean 'MU_ENUM_TO_STRING'? [-Wimplicit-function-declaration]

and then later

> | 1076 | ev->packet_id, ENUM_TO_STRING(IOTHUB_CLIENT_CONFIRMATION_RESULT, result), seq_num - ack_cnt - 1);
| | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| make: *** [Makefile:87: iothub.o] Error 1

That `ENUM_TO_STRING` had a name change to `MU_ENUM_TO_STRING`. For verification, I checked and compiled using GCC version 9.3 and everything works okay.

If you want to stay pinned to a certain LTS or commit, reset it to that commit and try running:

```bash
git submodule update --init --recursive
```

**Comment by hpatel2** [comment]
Thank you for the information.

That is true the error regarding ENUM_TO_STRING is because of the change in name and those errors are resolved by changing the enum as MU_ENUM_TO_STRING.

But here the main issue is other errors stated as **"error: expected declaration specifiers or '...' before"**

I am using yocto dunfell version to build this SDK. In my case also the SDK is compiling successfully without any error but errors comes when yocto starts to build my application which includes the header file from this SDK. The errors are because of the way used for define enum using the #define. 

#define IOTHUB_CLIENT_CONNECTION_STATUS_REASON_VALUES      \
    IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN,            \
    IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED,              \
    IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL,               \
    IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED,                \
    IOTHUB_CLIENT_CONNECTION_NO_NETWORK,                   \
    IOTHUB_CLIENT_CONNECTION_COMMUNICATION_ERROR,          \
    IOTHUB_CLIENT_CONNECTION_NO_PING_RESPONSE,             \
    IOTHUB_CLIENT_CONNECTION_OK                            \

MU_DEFINE_ENUM_WITHOUT_INVALID(IOTHUB_CLIENT_CONNECTION_STATUS_REASON, IOTHUB_CLIENT_CONNECTION_STATUS_REASON_VALUES);

In https://github.com/Azure/azure-iot-sdk-c/pull/1342 pull request I can see this #define is changed to enum and so compiler is not giving any issue if I use that code.

Please find the updated logs for this issue as below.

| arm-linux-gnueabi-gcc  -march=armv7ve -mthumb -mfpu=neon -mfloat-abi=hard --sysroot=/home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0=/usr/src/debug/gw/1.0-r0                      -fdebug-prefix-map=/home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0=/usr/src/debug/gw/1.0-r0                      -fdebug-prefix-map=/home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot-native=  -Os -rdynamic -funwind-tables -fstack-protector-all -I /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot -L /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/lib -DuECC_ENABLE_VLI_API -DuECC_VLI_NATIVE_LITTLE_ENDIAN=1 -DuECC_SQUARE_FUNC=1 -DuECC_SUPPORTS_secp256r1=1 -DuECC_SUPPORT_COMPRESSED_POINT=0 -DuECC_OPTIMIZATION_LEVEL=3 -DEARLY_DEBUG_PASSWD -DSTATIC="" -c -o firewall.o firewall.c
| In file included from /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_ll.h:31,
|                  from /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client.h:24,
|                  from iothub.c:56:
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:125:5: error: expected declaration specifiers or '...' before 'IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN'
|   125 |     IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN,            \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:125:5: note: in definition of macro 'IOTHUB_CLIENT_CONNECTION_STATUS_REASON_VALUES'
|   125 |     IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN,            \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:126:5: error: expected declaration specifiers or '...' before 'IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED'
|   126 |     IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED,              \
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| /home/user/gw_dunfell/gw/tmp/work/armv7vet2hf-neon-linux-gnueabi/gw/1.0-r0/recipe-sysroot/usr/include/azureiot/iothub_client_core_common.h:126:5: note: in definition of macro 'IOTHUB_CLIENT_CONNECTION_STATUS_REASON_VALUES'
|   126 |     IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED,              \

**Comment by hpatel2** [comment]
Thank you for your quick support.

Issue is resolved after updating the defines in my application.

**Comment by danewalton** [comment]
awesome thanks for the question. feel free to open another GH issue if you have any more!

**Comment by az-iot-builder-01** [comment]
@hpatel2, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
