### ISSUE TITLE
Status variable in function on_underlying_io_bytes_received of tlsio_Schannel.c is coming as Unknown Number

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-c#1650]
When i am trying to get the status value from function "on_underlying_io_bytes_received" of file tlsio_Schannel.c is coming as some default value.

Code from tlsio_Schannel.cs file.

status = InitializeSecurityContext(&tls_io_instance->credential_handle,
                    &tls_io_instance->security_context, tls_io_instance->host_name, flags, 0, 0, &input_buffers_desc, 0,
                    &tls_io_instance->security_context, &output_buffers_desc,
                    &context_attributes, NULL);

I need urgent help to finish my work..

**Comment by Abhi2109** [comment]
Any Pointers highly appreciated , as i need the solution ASAP.

**Comment by ericwol-msft** [comment]
Here is the documentation on schannel
 https://docs.microsoft.com/en-us/windows/win32/secauthn/initializesecuritycontext--schannel

What is the return value on InitializeSecurityContext?

FYI, you need to provide more details on your issues and what you posted is pretty vague.

**Comment by ewertons** [comment]
Hi @Abhi2109 ,
this library is for internal use of the Azure IoT C SDK and is not supported for direct external use.
At the moment, there is no indication that there is disruption of the Azure IoT C SDK functionality, so this will not be an issue we will be able to prioritize.
If you would like to elaborate on the issue and provide a PR, we will evaluate it.
Thanks,
Azure IoT SDK team.

**Comment by Abhi2109** [comment]
Hi ewertons,
I am taking the help of azure iot sdk to develop wrapper for my device connectivity to hub. So during this operation when i am trying to send the data to my iot hub. Issue arise when it will perform the operation of **mqtt_client_dowork**  , when i debug into it then i got that the status value is coming as default s
![Mqtt_error](https://user-images.githubusercontent.com/33317345/92985024-8af46680-f4cc-11ea-8bd7-a024854e4d1a.jpg)
o mqtt is trying to close the connection and i got an error as  :
Func:_on_underlying_io_bytes_received Line:815 [0x80090322] , moreover i have attached the error on console here.

**Comment by Abhi2109** [comment]
Hi Eric,
This is the return value that i am getting for status: -2146893022 for default case:

**Comment by Abhi2109** [comment]
I know i might have done something wrong, i want to know the pointers of that.

**Comment by ericwol-msft** [comment]
That error code is SEC_E_WRONG_PRINCIPAL.  

`The principal that received the authentication request is not the same as the one passed into the pszTargetName parameter. This indicates a failure in mutual authentication.`

https://docs.microsoft.com/en-us/windows/win32/secauthn/initializesecuritycontext--general

**Comment by Abhi2109** [comment]
Hi Eric,
Do you know how i can fix this ?

**Comment by Abhi2109** [comment]
One observation that i have is regarding &output_buffers_desc , so what is happening is for the case where this exception is coming the &output_buffers_desc is showing following values : cbBuffer = 0;BufferType = 2; pBuffers {cbBuffers = 0;BufferTypes=2;pvbuffers = 0x0000000} so i guess nothing is actually getting written in output buffers. Is it because of  SEC_E_WRONG_PRINCIPAL or vice versa? Not sure about that.

**Comment by ericwol-msft** [comment]
This is indicative of your TLS certificates are wrong. You can validate what you're sending to what is actually sent via wireshark.

**Comment by Abhi2109** [comment]
ok, then i guess i need to include all the shared utility header files with corresponding .c files in my projects i guess that might fix the issue.

**Comment by Abhi2109** [comment]
Hi Eric,
As per your suggestion i have taken the wire shark trace and here are the traces:

1) NotWorkingTrace
2) Working trace

[WiresharkTraces.zip](https://github.com/Azure/azure-iot-sdk-c/files/5238853/WiresharkTraces.zip)

**Comment by Abhi2109** [comment]
Hi Eric,
From the already existing code and Wireshark trace it seems like my flow is correct as from Client side Hello is sent which is acknowledged by server, now after that as the status would be 590610 then only TLS certificate will be required as the status code would be SEC_E_OK , but for my case what is happening is status never comes as 590610 resulting which the default case kicked off so there is no chance of going till the point of TLS certificate issue.

Please guide me in this regards and as per me the real cause of error is why the &output_buffers_desc is appearing without any pointers for all the loops.

**Comment by ericwol-msft** [comment]
I don't see any MQTT protocol in the traces. What is the IP address of the IoT Hub service you are talking to?

**Comment by Abhi2109** [comment]
So the protocol in wireshark is TCP as the MQTT will make use of that, and the IoT hub IP : 13.76.217.46 My IP address : 192.168.0.102

**Comment by ericwol-msft** [comment]
In the working trace the SNI of the Client Hello (frame 2293) is correctly set to your hub name
`Server Name: SGMSADIAIOTHUB.azure-devices.net`


In the non-working trace the SNI is garbage (frame 318). The service does not complete the TLS negotiation because of this.
`Server Name: ��������������������������������������������������������`

**Comment by Abhi2109** [comment]
Please tell me how i should handle this "any pointers will be good" since for both the cases connection string and code flow is same.

**Comment by Abhi2109** [comment]
Just for info what is SNI..

**Comment by Abhi2109** [comment]
As i am struggling with this issue from past very long.

**Comment by ericwol-msft** [comment]
https://www.cloudflare.com/learning/ssl/what-is-sni/

You need to trace thru send_client_hello() in tlsio_schannel.c
What is the host name passing in InitializeSecurityContext() via tls_io_instance->host_name

**Comment by Abhi2109** [comment]
host name is same i.e. for both the cases i have checked that already, it's same as you mentioned above.

**Comment by Abhi2109** [comment]
As the connection string is same.

**Comment by Abhi2109** [comment]
send_client_hello() in tlsio_schannel.c isworking fine as in trace we can see that Client Hello is send over TLSv1.2

**Comment by Abhi2109** [comment]
tlsiotls_io_instance->host_name "SGMSADIAIOTHUB.azure-devices.net"

**Comment by Abhi2109** [comment]
tls_io_instance->host_name
![image](https://user-images.githubusercontent.com/33317345/93740344-ea0e5580-fc07-11ea-8b7a-e51e6b4b0ec0.png)

Here you can clearly see the server name

**Comment by Abhi2109** [comment]
We can close this issue now.

**Comment by az-iot-builder-01** [comment]
@Abhi2109, @ericwol-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
