### ISSUE TITLE
Send telemetry messages via offline Gateway

### ISSUE THREAD

**Issue by schroedermarius** [Azure/azure-iot-sdk-c#1651]
Hi there,

I am trying to send telemetry messages via MQTT to an gateway.
Is there a way this is possible while the gateway is offline so the device has no internet connection?
My gateway has an access point which my ESP32 is connecting to.
But my ESP should also send messages when there is no internet sharing on the access point active.

In the init method of the SDK its always polling the NTP server like the following, so my ESP will never send without an active internet connection:

I (3900) wifi:AP's beacon interval = 102400 us, DTIM period = 3
I (4920) tcpip_adapter: sta ip: 10.0.60.32, mask: 255.255.255.0, gw: 10.0.60.1
I (4920) wifi: got ip:10.0.60.32
I (4920) wifi: Connected to AP success.
Waiting for system time to be set... tm_year:70[times:2]
Waiting for system time to be set... tm_year:70[times:3]
Waiting for system time to be set... tm_year:70[times:4]
Waiting for system time to be set... tm_year:70[times:5]
Waiting for system time to be set... tm_year:70[times:6]

**Comment by ericwol-msft** [comment]
ESP32 does not have a realtime clock. Current device security needs to have an accurate clock set for device cryptography like TLS. You would need either a RTC on your board or setup an NTP server behind your gateway.

**Comment by schroedermarius** [comment]
> ESP32 does not have a realtime clock. Current device security needs to have an accurate clock set for device cryptography like TLS. You would need either a RTC on your board or setup an NTP server behind your gateway.

Thanks you very much for the fast answer!

**Comment by az-iot-builder-01** [comment]
@ericwol-msft, @schroedermarius, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
