### ISSUE TITLE
Recommended approach to update root ca cert in device to connect to azure services (DPS/IOTHub/storage)

### ISSUE THREAD

**Issue by sanjeev-magoo** [Azure/azure-iot-sdk-c#1652]
Referring to https://channel9.msdn.com/Shows/Internet-of-Things-Show/Azure-IoT-TLS-Changes-are-coming.
I understand, MS is going to change the TLS certificate for Azure services.

We are working to adapt to latest certificates as recommended by MS, however we would like to understand MS recommended approach on updating these certificates on device rather than building some custom homegrown solution.

**Comment by ericwol-msft** [comment]
Only the intermediate certificate is changing. If your device is set to use the Baltimore root ca, than you should not see an impact.

**Comment by ewertons** [comment]
Hi @sanjeev-magoo ,
thanks for the question. 
We will close this issue for now, but if you would like to follow up on the matter please post a comment or open a new issue if needed.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@sanjeev-magoo, @ericwol-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
