### ISSUE TITLE
Creating Library package (SDK) of Static Library

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-c#1657]
Hi,
I want to create a Library packaging of .lib files , need some pointers how to proceed on that. It's bit urgent so any help will be highly appreciated.

**Comment by ewertons** [comment]
Hi @Abhi2109 ,
what is your specific question?
For which platform are you wanting to create a azure-iot-sdk-c package for?
Please provide as many specific details as possible.

**Comment by ewertons** [comment]
Hi @Abhi2109 ,
we will close this issue for now, but please feel free to post a comment or file a new one if you would like to follow up.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@Abhi2109, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
