### ISSUE TITLE
Issue in device cert generated using certGen.sh 

### ISSUE THREAD

**Issue by amit12cool** [Azure/azure-iot-sdk-c#1660]
It seems the comment at line [334 ](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/certGen.sh#L334)seems to be wrong.
###############################################################################
# Generates a certificate for a device, chained to the intermediate.
###############################################################################

The device certificate seems to be created from the root ca certificate rather than the intermediate certificate check this [line](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/certGen.sh#L348) and this [line](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/certGen.sh#L347).So it's not chained to the intermediate certificate as mentioned in the comment at line 334.

**Comment by ewertons** [comment]
Fixed.
Thanks for reporting this issue.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@amit12cool, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
