### ISSUE TITLE
Upload json in azure IoT using SDK c

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-c#1671]
Hi,
I want to upload json string as well as file in azure cloud , can any one help me how to achieve that?

**Comment by danewalton** [comment]
Hi @Abhi2109 can you give a little more detail? Are you trying to use upload to blob, telemetry, methods, etc.

**Comment by Abhi2109** [comment]
Hi Dane,
So what i want is to upload a .json content not the file in my Azure IoT blob container and when i refer the Azure IoT SDK C code i can find only to upload the file not just the raw content without file.

Lets say i have a json (key:value) and like that so is there a option i can use these data to straight away put into my blob

**Comment by Abhi2109** [comment]
One more doubt i have while executing "if (HTTPAPIEX_SAS_ExecuteRequest(http_sas_handle, http_api_handle, HTTPAPI_REQUEST_POST, relative_path, request_header,
            blobBuffer, &statusCode, NULL, response_buff) != HTTPAPIEX_OK)" this piece of code i am getting statusCode 400 please let me know what input i need to correct in here.

**Comment by Abhi2109** [comment]
I have not given any input apart from Connection String.
Please let me know do the Azure IoT SDK Upload feature need any other input apart from connection string.

**Comment by Abhi2109** [comment]
From debugging it seems like the headers is not getting formed correctly and because of that 400 status code is coming while uploading.
Ideally as the insertNewKeyValuePair is not working correctly since it's job is to append the new keys and values in the existing one.

**Comment by Abhi2109** [comment]
As you can see in this attachment , expectation is 
"Content-Type": "application/json" "Accept": "application/json" "User-Agent": "iothubclient/" IOTHUB_SDK_VERSION*/

But got this ..

![image](https://user-images.githubusercontent.com/33317345/94268665-2240cb80-ff5b-11ea-90b6-858b8783633a.png)

But

**Comment by Abhi2109** [comment]
Seems like after i have the correct rights on Azure IoT i can push the default subdir/hello_World.txt got posted please ignore the questions from second onwards , But my first question still valid.. Please help me get resolve that.

**Comment by danewalton** [comment]
Have you tried using the `IoTHubDeviceClient_LL_UploadToBlob()` API?

**Comment by Abhi2109** [comment]
Yes , that's the one API i am trying to upload the data with , so if instead of Hello_World.txt if i will give the plain json content will that be ok. Or it's compulsory to upload only the file?

**Comment by danewalton** [comment]
The function signature takes in a destination file name (to be stored in blob) and an input `char*` which can originate from wherever you would like. You can read it in as a file or use a `char*` literal like our sample does [here](https://github.com/Azure/azure-iot-sdk-c/blob/ff1393162fe5624d02abe6deabc3509ee6d9b08e/iothub_client/samples/iothub_client_sample_upload_to_blob/iothub_client_sample_upload_to_blob.c#L38).

Hope that helps!

**Comment by Abhi2109** [comment]
Thanks Dane!!!

**Comment by danewalton** [comment]
You're very welcome! I'll go ahead and close this for now and feel free to leave a comment if you would like it reopened.

**Comment by az-iot-builder-01** [comment]
@danewalton, @Abhi2109, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
