### ISSUE TITLE
esp tests failing when create a PR from forked repo

### ISSUE THREAD

**Issue by momuno** [Azure/azure-iot-sdk-c#1672]
**Describe the Bug**

Using a forked repo of azure-iot-sdk-c, upon creating a PR to merge a branch of that forked repo into the master Azure/azure-iot-sdk-c, two esp tests are failing (test_esp32 and test_esp8266).  These tests all fail to access C-Canary secrets in the "Download secrets: c-canary" step.  The message viewed instead is: "References service endpoint. PRs from repository forks are not allowed to access secrets in the pipeline. For more information see https://go.microsoft.com/fwlink/?linkid=862029"

The current workaround is to not use a forked repo, but instead create a branch off Azure/azure-iot-sdk-c and then create PR from that branch to merge into master.

**Comment by wesmc7777** [comment]
@momuno  I don't have permissions to create my own working branch on the repo.  Wondering if I'm now supposed to push to some existing working branch that will be merged into master later.  Thoughts?

**Comment by momuno** [comment]
Either you could request permissions, or I can create a working branch for you.

**Comment by ericwol-msft** [comment]
I added Wesley

**Comment by momuno** [comment]
Removing issue tracking from github since it is an internal build issue.

**Comment by az-iot-builder-01** [comment]
@ericwol-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
