### ISSUE TITLE
How to get update of only recently updated desired properties?

### ISSUE THREAD

**Issue by hizzawaseem** [Azure/azure-iot-sdk-c#1674]
My device twin has the following structure where properties A, B and C and so on are being added on run time (not predefined).  The JSON object “States” can have up to 160 objects inside.

 "desired":
      "States": {
        "PropertyA": {
          "x": 0,
          "y": "A"
        },
        " PropertyB": {
          "x": 1,
          "y": "B"
        },
        " PropertyC": {
          "x": 2,
          "y": "C"
        }
     }

Currently the complete device twin structure is provided at startup including desired and reported properties, and partial updates are received afterwards. In the device twin partial update I receive the complete object of desired properties. 
How can I receive the newly added property only e.g “Property D” or only the most recent changes in a specific property? Is there a predefined function in Azure for this operation?
I do not want to iterate over all the objects inside the “States” object.

**Comment by danewalton** [comment]
Hi @hizzawaseem 
Currently, when updated `PATCH` requests for twin properties (desired properties) come in to the device, all of the desired properties are sent. So in your example, PropertyA through PropertyD will indeed come in. We do not currently have functionality which only shows the updated "diff".

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now but please leave a comment if you would like this reopened.

**Comment by az-iot-builder-01** [comment]
@hizzawaseem, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
