### ISSUE TITLE
Can we use azure-iot-sdk-c for development on android.

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/azure-iot-sdk-c#1675]
Hi,

We have developed (c/c++)IoT-device -application using azure-iot-sdk-c for linux .
Recently we have a requirement for android.
To avoid rework, we are planning to use our existing implementation on android which is developed in C(using azure c-sdk).
Is there any possibility to use existing implementation using azure-c-sdk for android.
Or please let us know if this can be done with minimal changes also.

Thanks
Raj

**Comment by danewalton** [comment]
Hi @rajaggrawal 
There have been cases where people have tried to compile it for Android (example [here](https://github.com/Azure/azure-iot-sdk-c/issues/1345)). We do not officially support that scenario, however if you can maybe use the other issues to help guide you in using it that might help. Try searching all issues for "Android" and hopefully some of those previous questions can help you out!

**Comment by ewertons** [comment]
Also, please check our Java SDK. It is our recommended Azure IoT SDK for Android.
https://github.com/azure/azure-iot-sdk-java

**Comment by ewertons** [comment]
Hi @rajaggrawal,
we will close this issue, but please feel free to open a new one if you would like to follow up on any discussion related to the Azure IoT C SDK.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@rajaggrawal, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
