### ISSUE TITLE
how can prov_dev_client_ll_sample go HTTP path?

### ISSUE THREAD

**Issue by neotrip** [Azure/azure-iot-sdk-c#1678]
https://github.com/Azure/azure-iot-sdk-c/blob/ff1393162fe5624d02abe6deabc3509ee6d9b08e/provisioning_client/samples/prov_dev_client_ll_sample/prov_dev_client_ll_sample.c#L252-L254

Why HTTPs use MQTT_Protocol here?
How can I manage to go pure HTTPs path?

**Comment by ericwol-msft** [comment]
The sample is to demonstrate device provisioning to Azure DPS. You can see a complete device to Azure hub sample using HTTP here https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now but please leave a comment if you would like this reopened.

**Comment by az-iot-builder-01** [comment]
@neotrip, @ericwol-msft, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
