### ISSUE TITLE
Add Escape character in json

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-c#1681]
Hi,
I am trying to get the method that i can use to add escape character in my string so that it can be json compliance. For example if my user Pass "{A:22,B:33}" and the output can be "{\"A\":22,\"B\":33}". So is there any function that i can use from Azure IOT SDK C to achieve this.

**Comment by ericwol-msft** [comment]
No. There are projects on github to do this, but none in C language.

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now but please leave a comment if you would like this reopened.

**Comment by az-iot-builder-01** [comment]
@Abhi2109, @ericwol-msft, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
