### ISSUE TITLE
Having trouble in running iothub_messaging_sample.c

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-c#1683]
Hi,
After providing the Connection string and deviceId , i am having no Idea why the code is asking for Key as it's failing for that.

**Comment by Abhi2109** [comment]
I am getting this error.
authInfo->keyName input parameter cannot be NULL

And the interesting part here is in Code it's mentioned that 

Both %s and %s in connection string were set, they are mutually exclusive", IOTHUBSHAREDACESSKEYNAME, IOTHUBDEVICEID
So the SDK expected that SharedKeyName and DeviceId won't be there together.

Please help me in getting this resolved.

**Comment by danewalton** [comment]
Hi @Abhi2109 a couple things. I want to make sure you indeed want to use the service sample `iothub_message_sample.c`. This is not a device side sample.

Second, if you do want to run the service sample, can you double check that you are using a "Service" connection string? On the hub it will look like this:
![image](https://user-images.githubusercontent.com/36710865/94709634-c1b6e300-02fa-11eb-80aa-d35eecde54dc.png)

This is what it would look like: `HostName=contoso.azure-devices.net;SharedAccessKeyName=service;SharedAccessKey=12345672cKdNP1rUfdIIuUS1MklY76c5S1jlv/idII=`. Note the second value in that is `SharedAccessKeyName` and not `DeviceId`.

**Comment by danewalton** [comment]
I'm going to go ahead and close this issue for now. If you would like it reopened, please feel free to leave a comment stating so.

**Comment by az-iot-builder-01** [comment]
@Abhi2109, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
