### ISSUE TITLE
Certificates update in certs.h and certs.c

### ISSUE THREAD

**Issue by dzuda11** [Azure/azure-iot-sdk-c#1689]
Since Azure updated certificates and my code is not working right now so I have a question about updating certs.h and certs.c.

What is the best way for updating my certs.c, will someone update it on this repo, or I have to do it manually and how?
Will Azure update certificates again and when, and most important question is how to prevet running into the issue again if the project relay on certs.h/.c files and if there is no OS support?

Reference: https://techcommunity.microsoft.com/t5/internet-of-things/azure-iot-tls-changes-are-coming-and-why-you-should-care/ba-p/1658456

**Comment by danewalton** [comment]
From that link:

> The following services used by Azure IoT devices will remain chained to the Baltimore CyberTrust Root*, but their TLS server certificates will be issued by new Intermediate Certificate Authorities (ICAs) starting October 5, 2020 progressing regionally through the month on a measured deployment schedule:
>
>    Azure IoT Hub
>   Azure IoT Hub Device Provisioning Service (DPS)
>    Azure Storage Services

The Baltimore Root in `certs.c` should still work. Are you able to give more details about what is going wrong?

**Comment by dzuda11** [comment]
Heyy, I am so sorry, the issue wasn't about certificates after all, but it happened on October 5. It was a problem with upper and lower case letters in deviceId. I will research more about it and if it's an issue and not a leak of my knowledge, I will open an issue on the Azure portal. 
Thank you for your help, you did an amazing job helping me to understand that certificate didn't cause the problem. :D :D

**Comment by az-iot-builder-01** [comment]
@danewalton, @dzuda11, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
