### ISSUE TITLE
Message sent as .json format  is not visible during Stream analytics

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-c#1690]
Hi,
When i have tried sending one message in .json format through Telemetry Send sample code it got posted on IoT hub but as i tried to output it using Azure Stream Analytics expect my message all the parameters are shown.

Here is the snapshot:

Telemtry Message : "{"A":23,"B":34}" but it this output no where i can see these.

{"EnqueuedTimeUtc":"2020-10-09T13:22:23.0000000Z","Properties":{},"SystemProperties":{"connectionDeviceId":"TestAbhishekIOTDevice","connectionAuthMethod":"{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}","connectionDeviceGenerationId":"637336075019173184","enqueuedTime":"2020-10-09T13:22:23.0000000Z"},"Body":"eyJBIjozNCwiQiI6NDV9"}

Please help me to get this issue solved.

**Comment by ewertons** [comment]
Hi @Abhi2109 ,
this channel is for issues related to Azure IoT SDKs only.
To have your issue addressed properly, please open a support ticket through the Azure Portal for the resource you are having issues with.
https://ms.portal.azure.com/#create/Microsoft.Support

Thanks,
Azure SDK Team.

**Comment by az-iot-builder-01** [comment]
@Abhi2109, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
