### ISSUE TITLE
Unable to build sample project using vcpkg

### ISSUE THREAD

**Issue by SergioMasson** [Azure/azure-iot-sdk-c#1691]
I`m trying to build the sample project iothub_ll_telemetry_sample using a windows console application on x64 architecture. The SDK is installed using vcpkg. All header files are correctly found. However, I get multiple linker errors when trying to build the console app. 

Error list: 
aziotsharedutil.lib(platform_win32.c.obj) : error LNK2001: unresolved external symbol __imp_WSAStartup
1>aziotsharedutil.lib(platform_win32.c.obj) : error LNK2001: unresolved external symbol __imp_WSACleanup
1>aziotsharedutil.lib(tlsio_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CertFreeCertificateContext
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_CertFreeCertificateContext
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CertFreeCertificateContext
1>aziotsharedutil.lib(tlsio_schannel.c.obj) : error LNK2001: unresolved external symbol AcquireCredentialsHandleA
1>aziotsharedutil.lib(tlsio_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_FreeCredentialsHandle
1>aziotsharedutil.lib(tlsio_schannel.c.obj) : error LNK2001: unresolved external symbol InitializeSecurityContextA
1>aziotsharedutil.lib(tlsio_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_DeleteSecurityContext
1>aziotsharedutil.lib(tlsio_schannel.c.obj) : error LNK2001: unresolved external symbol QueryContextAttributesA
1>aziotsharedutil.lib(tlsio_schannel.c.obj) : error LNK2001: unresolved external symbol EncryptMessage
1>aziotsharedutil.lib(tlsio_schannel.c.obj) : error LNK2001: unresolved external symbol DecryptMessage
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpSetStatusCallback
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpOpen
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpCloseHandle
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpConnect
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpReadData
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpQueryDataAvailable
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpQueryOption
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpSetOption
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpSetTimeouts
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpOpenRequest
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpSendRequest
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpSetCredentials
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpReceiveResponse
1>aziotsharedutil.lib(httpapi_winhttp.c.obj) : error LNK2001: unresolved external symbol __imp_WinHttpQueryHeaders
1>aziotsharedutil.lib(socketio_win32.c.obj) : error LNK2001: unresolved external symbol __imp_closesocket
1>aziotsharedutil.lib(socketio_win32.c.obj) : error LNK2001: unresolved external symbol __imp_connect
1>aziotsharedutil.lib(socketio_win32.c.obj) : error LNK2001: unresolved external symbol __imp_ioctlsocket
1>aziotsharedutil.lib(socketio_win32.c.obj) : error LNK2001: unresolved external symbol __imp_recv
1>aziotsharedutil.lib(socketio_win32.c.obj) : error LNK2001: unresolved external symbol __imp_send
1>aziotsharedutil.lib(socketio_win32.c.obj) : error LNK2001: unresolved external symbol __imp_socket
1>aziotsharedutil.lib(socketio_win32.c.obj) : error LNK2001: unresolved external symbol __imp_WSAGetLastError
1>aziotsharedutil.lib(socketio_win32.c.obj) : error LNK2001: unresolved external symbol __imp_WSAIoctl
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol NCryptOpenStorageProvider
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol NCryptImportKey
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol NCryptFreeObject
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CryptDecodeObjectEx
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CertOpenStore
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CertCloseStore
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CertCreateCertificateContext
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CertSetCertificateContextProperty
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CertAddEncodedCertificateToStore
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CertCreateCertificateChainEngine
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CertFreeCertificateChainEngine
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CertGetCertificateChain
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CertFreeCertificateChain
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CertVerifyCertificateChainPolicy
1>aziotsharedutil.lib(x509_schannel.c.obj) : error LNK2001: unresolved external symbol __imp_CryptStringToBinaryA
1>aziotsharedutil.lib(dns_resolver_sync.c.obj) : error LNK2001: unresolved external symbol __imp_getaddrinfo
1>aziotsharedutil.lib(dns_resolver_sync.c.obj) : error LNK2001: unresolved external symbol __imp_freeaddrinfo

Vcpkg installed:
azure-c-shared-utility:x64-windows                 2020-07-19       Azure C SDKs common code
azure-c-shared-utility:x86-windows                 2020-07-19       Azure C SDKs common code
azure-iot-sdk-c:x64-windows                        2020-07-19#1     A C99 SDK for connecting devices to Microsoft Az...
azure-iot-sdk-c:x86-windows                        2020-07-19#1     A C99 SDK for connecting devices to Microsoft Az...
azure-macro-utils-c:x64-windows                    2020-06-17-1     A library of macros for the Azure IoT SDK Suite
azure-macro-utils-c:x86-windows                    2020-06-17-1     A library of macros for the Azure IoT SDK Suite
azure-uamqp-c:x64-windows                          2020-07-19       AMQP library for C
azure-uamqp-c:x86-windows                          2020-07-19       AMQP library for C
azure-uhttp-c:x64-windows                          2020-07-19       Azure HTTP Library written in C
azure-uhttp-c:x86-windows                          2020-07-19       Azure HTTP Library written in C
azure-umqtt-c:x64-windows                          2020-07-19       General purpose library for communication over t...
azure-umqtt-c:x86-windows                          2020-07-19

**Comment by jbobotek** [comment]
Just checking that you've followed the official guide: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/setting_up_vcpkg.md#setup-c-sdk-vcpkg-for-windows-development-environment

**Comment by az-iot-builder-01** [comment]
@SergioMasson, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by ewertons** [comment]
Please note that these Visual Studio projects are being re-evaluated and might be changed and/or moved in the near future.
