### ISSUE TITLE
Cannot send certain ASCII characters to IoTHub when using MQTT

### ISSUE THREAD

**Issue by momuno** [Azure/azure-iot-sdk-c#1695]
Running C-SDK sample iothub_ll_telemetry_sample, and using MQTT, the following behavior is observed:

characters '#', '&', '+', '/', '=' do not work for key or property values.
The client disconnects and either
1) no telemetry is received by IoTHub.(EX: "#":"a")
2) a null property is received  (EX: "a":"/")
```
{
  "body": "test_message",
  "enqueuedTime": "2020-10-14T20:36:18.890Z",
  "properties": {
    "a": null
  }
}
```

All other ASCII characters from [space] to '\~' work as expected.
(EX: "0123456789 qwertyuiopasdfghjklzxcvbnm QWERTYUIOPASDFGHJKLZXCVBNM !\"$%'()\*,-.:;<>?@[\\]\^\_\`{|}\~":"0123456789 qwertyuiopasdfghjklzxcvbnm QWERTYUIOPASDFGHJKLZXCVBNM !\"$%'()\*,-.:;<>?@[\\]^_\`{|}~")

IoTHub has validated that all characters [space] to '~' work when using MQTT and running .net SDKs.  It is suspected, therefore, that the server is able to receive the characters and that the C SDK may not be sending the message properly.

**To reproduce:**
In the source code for the sample, adjust the call to IoTHubMessage_SetProperty(), updating the key and property values passed in as parameters.  Rebuild the sample using instructions for building the samples (cmake --build .), and run the sample.  Use Azure IoT Explorer to observe IoTHub received telemetry messages.

A failed console log will look like the following:

```
Creating IoTHub Device handle
Sending message 1 to IoTHub
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
-> 13:48:05 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: momuno-hub.azure-devices.net/hub-sas-test/?api-version=2019-10-01&DeviceClientType=iothubclient%2f1.3.9%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
<- 13:48:05 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
The device client is connected to iothub
-> 13:48:05 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/hub-sas-test/messages/events/a=/a | PACKET_ID: 2 | PAYLOAD_LEN: 12
-> 13:48:05 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/hub-sas-test/messages/events/a=/a | PACKET_ID: 3 | PAYLOAD_LEN: 12
-> 13:48:05 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/hub-sas-test/messages/events/a=/a | PACKET_ID: 4 | PAYLOAD_LEN: 12
-> 13:48:05 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/hub-sas-test/messages/events/a=/a | PACKET_ID: 5 | PAYLOAD_LEN: 12
-> 13:48:05 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/hub-sas-test/messages/events/a=/a | PACKET_ID: 6 | PAYLOAD_LEN: 12
The device client has been disconnected
-> 13:48:06 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: momuno-hub.azure-devices.net/hub-sas-test/?api-version=2019-10-01&DeviceClientType=iothubclient%2f1.3.9%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
<- 13:48:06 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
The device client is connected to iothub
```

A successful log will look like:
```
Creating IoTHub Device handle
Sending message 1 to IoTHub
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
-> 13:44:15 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: momuno-hub.azure-devices.net/hub-sas-test/?api-version=2019-10-01&DeviceClientType=iothubclient%2f1.3.9%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
<- 13:44:15 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
The device client is connected to iothub
-> 13:44:15 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/hub-sas-test/messages/events/a=3426jbv sdfe thsth  | PACKET_ID: 2 | PAYLOAD_LEN: 12
-> 13:44:15 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/hub-sas-test/messages/events/a=3426jbv sdfe thsth  | PACKET_ID: 3 | PAYLOAD_LEN: 12
-> 13:44:15 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/hub-sas-test/messages/events/a=3426jbv sdfe thsth  | PACKET_ID: 4 | PAYLOAD_LEN: 12
-> 13:44:15 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/hub-sas-test/messages/events/a=3426jbv sdfe thsth  | PACKET_ID: 5 | PAYLOAD_LEN: 12
-> 13:44:15 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/hub-sas-test/messages/events/a=3426jbv sdfe thsth  | PACKET_ID: 6 | PAYLOAD_LEN: 12
<- 13:44:15 PUBACK | PACKET_ID: 2
Confirmation callback received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 13:44:15 PUBACK | PACKET_ID: 3
Confirmation callback received for message 2 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 13:44:15 PUBACK | PACKET_ID: 4
Confirmation callback received for message 3 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 13:44:15 PUBACK | PACKET_ID: 5
Confirmation callback received for message 4 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 13:44:15 PUBACK | PACKET_ID: 6
Confirmation callback received for message 5 with result IOTHUB_CLIENT_CONFIRMATION_OK
-> 13:44:15 DISCONNECT
Press any key to continue
```

**Comment by jspaith** [comment]
The issue I'm almost positive is the fact that the characters you're using require URL encoding.  This sadly is NOT on by default for MQTT for IoT C SDK.  We shipped SDK without it and could not flip it on automatically later because customers were already doing pre-URL encodes before sending properties down.

So if on default MQTT you send those characters, the hub will see them are garbage URL and be unhappy.

Enter - `OPTION_AUTO_URL_ENCODE_DECODE` option.  If you look in the sample, there's actually commented out code that uses it.  It will tell underlying IoT/MQTT layer to please encode for URL since we want the SDK, and not app itself, doing this.

@momuno, I'm like 95% sure that if you comment out below block everything will just work.
```c
        //Setting the auto URL Encoder (recommended for MQTT). Please use this option unless
        //you are URL Encoding inputs yourself.
        //ONLY valid for use with MQTT
        //bool urlEncodeOn = true;
        //IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_AUTO_URL_ENCODE_DECODE, &urlEncodeOn);
```

If you can confirm that, I recommend this item is used to track just changing this (and any other sample) to set this automatically so we default people into behavior they should be using vast majority of time anyway.

**Comment by momuno** [comment]
@jspaith This indeed solved the problem.  I will close the issue.  However, do you know if this is documented anywhere?

**Comment by jspaith** [comment]
In our reference docs I recently cleaned up ./doc/iothub_sdk_options.md so that it was bolded that this option should be set.  But it's easy to lose all that.  I recommend using this GH issue to track that we should update our samples and add some comment there on this as that's initial touch point for most customers.
