### ISSUE TITLE
Cannot receive the message from cloud

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-c#1697]
Hi,
I am using c2d ample code for accessing the messages from my IoT hub but seems like the call back method "receive_msg_callback" is not getting called at all need urgent help in this. I am using Azure IoT SDK C.

**Comment by ewertons** [comment]
Hi @Abhi2109 ,
we need more details to be able to assist.
1. What version of the C SDK code are you using?
2. What device/OS are you running the code on?
3. Are you usign any specific sample from our repo? please provide the specific name of the sample
4. Did you make any changes to the sample?

**Comment by Abhi2109** [comment]
1) 1.3.9
2) Windows.
3) I have used "iothub_ll_telemetry_sample" for sending messaging telemetry message.
4) No.

My Question now here is:
I need to know how to read the message from Cloud , i was looking into this doc : https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-read-builtin but nothing concrete for C.

**Comment by Abhi2109** [comment]
To do this "I need to know how to read the message from Cloud" operation i am using "iothub_ll_c2d_sample.c" but i am not able to see the flow going in "static IOTHUBMESSAGE_DISPOSITION_RESULT receive_msg_callback(IOTHUB_MESSAGE_HANDLE message, void* user_context)" so my question is why the call is not going in above mentioned method.

**Comment by ewertons** [comment]
Ok, so if we understand it correctly:
1. You are being able to send device-to-cloud messages (aka, telemetry) successfully;
2. Now you want to access those messages in the hub, so you can consume them.

If that understanding correct?
Maybe there is more reading for you to learn about Azure IoT.
The client SDK that sends messages from the device to the hub is called a "device client".
The client SDK that reads telemetry from the hub to your application in the cloud is called a "service client".
We do not have a supported service client in C, but we do have it in C#, Node.JS.
Please read more starting here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messaging

**Comment by ewertons** [comment]
Hi @Abhi2109 ,
we will close this issue for now, but please feel free to reopen it or file a new one if you would like to follow up.
Thanks,
Azure SDK Team.

**Comment by az-iot-builder-01** [comment]
@Abhi2109, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
