### ISSUE TITLE
SetOptions documentation needs cleanup

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#1711]
[Set options docs](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Iothub_sdk_options.md) needs spring cleaning.

Off top of my head, and I'm sure there's others:
* Need to document the `modelId` logic that was added for PnP.
* Need to document which options are applicable for UploadToBlob (which are not 100% set, because UploadToBlob uses HTTP handle whereas everything else is xio based)
* Need to document in the UploadToBlob API reference itself a note about not options being supported.
* Run through other options in C SDK and see what if anything is missing.
* Remove documentation of `XIO_RECEIVE_BUFFER_SIZE`.  (Do NOT remove its implementation, just fact it's doc'd.)  This isn't really the type of thing I want encouraging folks to use.

**Comment by kiranpradeep** [comment]
@jspaith Can SetOptions documentation also be extended to include OPTION_DO_WORK_FREQUENCY_IN_MS?

**Comment by jspaith** [comment]
> @jspaith Can SetOptions documentation also be extended to include OPTION_DO_WORK_FREQUENCY_IN_MS?

Yes, it'll get done as part of this too.

**Comment by jspaith** [comment]
Fixed #1714.

**Comment by az-iot-builder-01** [comment]
@kiranpradeep, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
