### ISSUE TITLE
Will this run on Tizen

### ISSUE THREAD

**Issue by TheisStellaCare** [Azure/azure-iot-sdk-c#1712]
Hi. Will this work with Tizen NOT Tizen RT.

I'm trying to make a GPS Tracker on Tizen Smart Watch

**Comment by TheisStellaCare** [comment]
And if. How would i go about compiling it?

**Comment by ewertons** [comment]
Hi @TheisStellaCare ,

by what we can see [here](https://www.tizen.org/), Tizen is an embedded Linux OS.
If that is the same you are talking about, yes the azure-iot-sdk-c might be able to run on it.
Notice that we have not validated the azure-iot-sdk-c in this platform.
Given the device might have a restricted amount of memory, you might find the new [azure-sdk-for-c](https://github.com/azure/azure-sdk-for-c) more suitable to your project.

**Comment by TheisStellaCare** [comment]
Hi. Tizen is the software that is running on smart tv, and smartwatches like Samsung galaxy watch active 2.

**Comment by ewertons** [comment]
Please look into https://github.com/Azure/azure-sdk-for-c, it might be a better option for these platforms.
It will require you to put together the MQTT/TLS/socket stack, but you will have a more concise solution at the end.

**Comment by TheisStellaCare** [comment]
Ok, Thanks. I Will look into it

**Comment by az-iot-builder-01** [comment]
@TheisStellaCare, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
