### ISSUE TITLE
azure-iot-sdk-c-release_2017_06_30 build issue

### ISSUE THREAD

**Issue by amiya068** [Azure/azure-iot-sdk-c#172]
OS and version: Ubuntu 14.04.5 (GNU/Linux 4.4.0-31)
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

SDK version used: release_2017_06_30

Description of the issue:
=========================
Have taken the release_2017_06_30 from https://github.com/Azure/azure-iot-sdk-c.

Used the following command to build the C SDK,

cd azure-iot-sdk-c
mkdir cmake
cd cmake
cmake ..
cmake -debug --build .

getting the following build error,

==================================================================================================================================
azure-iot-sdk-c-release_2017_06_30/azure-iot-sdk-c/cmake$ cmake ..
-- Shared_Util architecture: x86_64
-- AMQP Target architecture: x86_64
-- MQTT Target architecture: x86_64
-- iothub architecture: x86_64
CMake Warning at CMakeLists.txt:268 (message):
  This package may only be installed when 'use_installed_dependencies' is ON

**-- Configuring done
-- Generating done
-- Build files have been written to: azure-iot-sdk-c-release_2017_06_30/azure-iot-sdk-c/cmake
azure-iot-sdk-c-release_2017_06_30/azure-iot-sdk-c/cmake$ cmake --build .
[ 22%] Built target aziotsharedutil
Linking C executable iot_c_utility
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `tlsio_openssl_deinit':
/azure-iot-sdk-c-release_2017_06_30/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c:1029: undefined reference to `SSL_COMP_free_compression_methods'
collect2: error: ld returned 1 exit status
make[2]: *** [c-utility/samples/iot_c_utility/iot_c_utility] Error 1
make[1]: *** [c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/all] Error 2
make: *** [all] Error 2
azure-iot-sdk-c-release_2017_06_30/azure-iot-sdk-c/cmake$**

==================================================================================================================================

This issue is due to the function tlsio_openssl_deinit in file tlsio_openssl.c.

The function tlsio_openssl_deinit, definition is as below,

void tlsio_openssl_deinit(void)
{
    openssl_dynamic_locks_uninstall();
    openssl_static_locks_uninstall();
#if (OPENSSL_VERSION_NUMBER >= 0x00907000L) && (OPENSSL_VERSION_NUMBER < 0x20000000L)
    FIPS_mode_set(0);
#endif
    CRYPTO_set_locking_callback(NULL);
    CRYPTO_set_id_callback(NULL);
    ERR_free_strings();
    EVP_cleanup();
#ifndef OPENSSL_NO_DEPRECATED
    ERR_remove_state(0);
**#if (OPENSSL_VERSION_NUMBER >= 0x10002003L) && (OPENSSL_VERSION_NUMBER < 0x10002FFFL)
    SSL_COMP_free_compression_methods();
#endif**
#endif
    CRYPTO_cleanup_all_ex_data();
}

Can you please help me why this issue is exists and what can be done resolve this?
Advanced thanks for the support.

**Comment by tameraw** [comment]
@amiya068 - Please confirm that you have cloned the repo recursively.
https://github.com/Azure/azure-iot-sdk-c#how-to-clone-the-repository

**Comment by amiya068** [comment]
Yes, it is cloned recursively.
As per the https://github.com/curl/curl/issues/860, my understanding is that "SSL_COMP_free_compression_methods" is deprecated. 
Any quick help to resolve the issue would be very much helpful.

Thanks.

**Comment by kiranpradeep** [comment]
@amiya068 I initially did get this error. But after a took **new clean** recursive clone, it went away. I am at 1.0.2k openssl and curl 7.49.1 on a mac osx.

**Comment by amiya068** [comment]
This issue is solved after new clean recursive clone. So closing the issue.
