### ISSUE TITLE
ssl3_get_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by jackhyc** [Azure/azure-iot-sdk-c#1722]
I have built one of the samples to test if my embedded device is possible to connect to the Azure IOT. when I try to execute it, it shows me the info as below:
![image](https://user-images.githubusercontent.com/4330075/97421864-f644ab80-1947-11eb-96c0-029e3e3fbb40.png)

it seems the ca file issue, but I ave no idea how to fix it. Does someone meet the same issue when use the SDK?
Thanks,

**Comment by jbobotek** [comment]
Does your embedded device use openssl as its underlying TLS layer?

**Comment by ericwol-msft** [comment]
yes? the adapter is **tlsio_openssl**
@jackhyc  did you set the baltimore root cert?

**Comment by jackhyc** [comment]
> 
> 
> Does your embedded device use openssl as its underlying TLS layer?

yes, it shows like this:
![image](https://user-images.githubusercontent.com/4330075/97826485-a6296880-1cfc-11eb-878e-b0d00330ddfc.png)

**Comment by jackhyc** [comment]
> 
> 
> yes? the adapter is **tlsio_openssl**
> @jackhyc did you set the baltimore root cert?

I think so, but how can I set the other adapters?
thanks,

**Comment by jackhyc** [comment]
I finally figure out the issue, it is the time of my device out of date

**Comment by az-iot-builder-01** [comment]
@ericwol-msft, @jackhyc, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
