### ISSUE TITLE
Which API to use for getting device List

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-c#1723]
Hi,
When checking for a ways to get he device List i have found this "IoTHubRegistryManager_GetDeviceList" but seems like this is a depreciating function. Please let me know what would be the replacement function for this.

**Comment by ericwol-msft** [comment]
The IoT service APIs in the C SDK is no longer being maintained.

The latest IoT service APIs are available in the other SDKs Python/Node.js/Java/.NET 

https://github.com/Azure/azure-iot-sdks#:~:text=%20Microsoft%20Azure%20IoT%20SDKs%20for%20Azure%20IoT,5%20Azure%20IoT%20SDK%20for%20.NET%20More%20

**Comment by ewertons** [comment]
@Abhi2109 ,
for that functionality please use one of the other Azure IoT SDKs:
On C# SDK, use the CreateQuery API in the RegistryManager class:
https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/service/src/RegistryManager.cs#L534

**Comment by ewertons** [comment]
Hi @Abhi2109 ,
we will close this issue for now, but please feel free to reopen it or create a new one if you would like to follow up.
thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@Abhi2109, @ericwol-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
