### ISSUE TITLE
A question about Prov_Device_XX_Register_Device()

### ISSUE THREAD

**Issue by neotrip** [Azure/azure-iot-sdk-c#1724]
@jspaith 

I have a question about APIs Prov_Device_LL_Register_Device() or Prov_Device_Register_Device().

Per example in SDK, these two APIs are unblocked, so APP need add checking loop after them as following:

  **_Prov_Device_XX_Register_Device(...)
  do
  {
   ......
  } while(status == ....)__**

  Is there any  **blocking** API for registration without "do ... while..." check, for simplicity? 
 
thanks a lot!

**Comment by neotrip** [comment]
adding @ewertons

**Comment by ewertons** [comment]
Hey @neotrip ,
no, none of our APIs in this repo that do I/O are blocking.
So the ones you are asking about are the only options for device provisioning, we do not have a blocking option.

**Comment by neotrip** [comment]
okay, thanks for your reply:)

**Comment by ewertons** [comment]
No problem.
Feel free to contact us any time.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@neotrip, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
