### ISSUE TITLE
@azure-iot-sdk - The client register device callback in Device provisioning received after a delay

### ISSUE THREAD

**Issue by leksh123** [Azure/azure-iot-sdk-c#1727]
We are developing an C++ QT application using azure-iot-sdk -c. We observed from logs that after the device registering status 
callback returned CONNECTED and ASSIGNING status the register client device callback took a delay of 15 minutes to return the error PROV_DEVICE_RESULT_TRANSPORT. The same issue occured on first retry also. Everything worked fine after the second retry.
Could you please suggest the possible reasons for the above mentioned delay ...

**Comment by ewertons** [comment]
Hi @leksh123 ,
the usual issue to cause the error you are mentioning is if you have a connection issue (like loss of internet connection, dns resolution failure, etc) with the remote service, in this case the DPS service.
You can enable verbose logs from the device provisioning client to verify when you have connection issues.
Please see here: https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/samples/prov_dev_client_sample/prov_dev_client_sample.c#L151

Could you please provide the basic info so we can leave it recorded in the issue? E.g, 
- version of the code you are using, 
- platform you are running the code on, 
- type of network connection, 
- if you are using the convenience layer API functions (i.e., non "__ll__" functions),
- if you are downloading the code directly from github or using our packages (apt or vcpkg).

**Comment by ewertons** [comment]
Hi @leksh123 , we will close this issue for now, but please feel free to reopen it or open a new one if you would like to follow up.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@leksh123, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
