### ISSUE TITLE
'azure_macro_utils/macro_utils.h' file not found in Xcode 12

### ISSUE THREAD

**Issue by cbauer10** [Azure/azure-iot-sdk-c#1729]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

MacBook Pro, iOS 14, Xcode 12.1

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 1.3.9

**Describe the Bug**

CocoaPod no longer compiles with the following three errors:

`'azure_macro_utils/macro_utils.h' file not found: serializer_e2e.c`
`'azure_c_shared_utility/threadapi.h' file not found: simple sample_mqtt.c`
`'umock_c/umock_c.h' file not found: schemaserializer_ut.c`

Simply use the sample that you have provided to see these issues:
https://github.com/Azure-Samples/azure-iot-samples-ios

**Comment by Frank-vdm** [comment]
im also having this issue, reading the pod files does not help the issue

**Comment by cbauer10** [comment]
Just curious if there is any update on this issue?

**Comment by jbobotek** [comment]
I am investigating it as we speak. No updates other than that those ut and e2e files shouldn't be even in the pod. Currently fresh downloads of the sample and pods are not giving me the IoTHubClient framework, so working through that first.

**Comment by cbauer10** [comment]
Really appreciate it! Let me know if you need any further info from me to assist. Thank you!

**Comment by Frank-vdm** [comment]
I found an ugly work around, maybe this helps somehow solve the issue more permanently, I updated the files in the box to import from `macro_utils` instead of `azure_macro_utils`.

**Comment by jbobotek** [comment]
Ok, I have not been able to repro your issue. If you're using the latest Pods, you shouldn't be getting these e2e and ut errors as they are not included files. They may have been included previously many updates ago.
I will soon be updating the pods and Podfile to fix another issue found in iOS 14.1. I'll test it again after fixing this issue.

**Comment by cbauer10** [comment]
@jbobotek I am not sure what else I can provide you with to assist.  If you pull the sample and try to compile it does not work.  Those samples are pointed at `1.3.9-LTS`, but if I set it to point at the most recent it has the same issue.  It should be very easy to reproduce.

Can you give an estimate on the update you are releasing?  Perhaps that will solve it.

**Comment by jbobotek** [comment]
I agree, I was having issues compiling for iOS 12 as well, but I did not run into the same bug. Did you try @Frank-vdm 's fix?

**Comment by cbauer10** [comment]
Appreciate it.  I will try the work around.

**Comment by cbauer10** [comment]
I have submitted a PR to resolve this issue.  Please have a look when you can.

**Comment by jbobotek** [comment]
Please try this branch: https://github.com/Azure-Samples/azure-iot-samples-ios/tree/jbobotek-patch-1729

**Comment by cbauer10** [comment]
> Please try this branch, or update your podfile as changed in it: https://github.com/Azure-Samples/azure-iot-samples-ios/tree/jbobotek-patch-1729

These lines are not correctly formatted in the Podfile:
```
pod 'AzureIoTUtility', '=1.3.9=1.3.9-LTS-patch-2'
pod 'AzureIoTuMqtt', '=1.3.9=1.3.9-LTS-patch-1'
pod 'AzureIoTuAmqp', '=1.3.9=1.3.9-LTS-patch-1'
```

I changed them to:
```
pod 'AzureIoTUtility', '=1.3.9-LTS-patch-2'
pod 'AzureIoTuMqtt', '=1.3.9-LTS-patch-1'
pod 'AzureIoTuAmqp', '=1.3.9-LTS-patch-1'
```

However, it is not able to find these branches.  I wonder if it is because you have a local PodSpec repo that you are referencing and I only have the ability to access the pods that are in the global PodSpec.  Unless you can point me to the PodSpec repo these tags reside in.

**Comment by jbobotek** [comment]
Apologies, fixed, try now.

**Comment by jbobotek** [comment]
Pods should have been:
pod 'AzureIoTUtility', '=1.3.9-patch-2'
pod 'AzureIoTuMqtt', '=1.3.9-patch-1'
pod 'AzureIoTuAmqp', '=1.3.9-patch-1'
pod 'AzureIoTHubClient', '=1.3.9-LTS-patch-1'
pod 'OpenSSL-Universal'

**Comment by cbauer10** [comment]
I had to update the `VALID_ARCHS` parameter in the project to `arm64 arm64e armv7 armv7s x86_64` to get it to compile on the iPhone12 simulator, but you seem to have fixed it.  I tried pushing my commit to your branch, but I don't have permissions, so I am just letting you know what I had to do to get it to work.  Thank you!!!

**Comment by jbobotek** [comment]
Could you link what file contains those VALID_ARCHS parameters so that I can fix it?

**Comment by cbauer10** [comment]
> Could you link what file contains those VALID_ARCHS parameters so that I can fix it?

https://github.com/Azure-Samples/azure-iot-samples-ios/blob/master/quickstart/sample-device/MQTT%20Client%20Sample.xcodeproj/project.pbxproj

I only played with the `sample-device` project, but I wouldn't be surprised if the `sample-service` project had the same issue.

**Comment by jbobotek** [comment]
I actually remember having issues related to those ARCHs as well, oddly when I had armv7 as a valid_arch it was complaining for me, which is why I simplified to amd64. I'll have to make sure adding all those will work for me on the sample.

**Comment by cbauer10** [comment]
We have had this in several of our libraries as well.  `arm64` messes up the simulator.  So you are probably running on a real device.

**Comment by az-iot-builder-01** [comment]
@Frank-vdm, @cbauer10, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by cbauer10** [comment]
@jbobotek Are you saying that the patch releases above are the official release, or are we still waiting for an official release on this?

**Comment by jbobotek** [comment]
We may have a versioned release later this month, but you should consider the above pods supported. Also, we have discontinued support for the C service sdk. The node, python, and C# service sdks are quite useable however.

**Comment by cbauer10** [comment]
Thank you for the update and interesting news about the service SDK.

**Comment by jbobotek** [comment]
@cbauer10 See https://github.com/Azure-Samples/azure-iot-samples-ios/pull/17 with updated cocoapods and fixed VALID_ARCHS lines.
