### ISSUE TITLE
Will Device SDK for C be compatible for iOS devices

### ISSUE THREAD

**Issue by jkriba** [Azure/azure-iot-sdk-c#173]
- **OS and version used:** <VERSION> iOS 10

- **SDK version used:** <VERSION> Device SDK for C 20170616

# Description of the issue:
Kindly consider this as a technical question. Please let us know if the Device SDK for C is compatible with iOS 10 devices since we need to wrap the Object C client application to establish communication with the Azure IoT Hub.

Is there any workaround possible or any alternate provision given by Microsoft to develop an Device client application from iOS environment other than the PCL. thanks

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by olivierbloch** [comment]
Hi @jkriba 
the short answer to your question is yes, we intend to make our C SDK support iOS. We don't have an answer for timing yet though as we are prioritizing against other features as well.
You can upvote the feature on [User Voice](https://feedback.azure.com/forums/321918-azure-iot/suggestions/16433716-native-ios-support-for-iot-hub-sdks), which help us track interest for features and support for new platforms.
Thanks

**Comment by jkriba** [comment]
Hi , can you please update if there was any update available on the same lines here..We need to do our PI Planning based upon the tentative release time lines of the iOS support, thanks

Regards
JK

**Comment by tameraw** [comment]
@jkriba - Unfortunately, we do not have an ETA on that yet.

**Comment by tameraw** [comment]
@jkriba  - This is currently a work-in-progress.

**Comment by jspaith** [comment]
While we don't have an official ETA yet, as an update the work is actively in progress.  https://github.com/Azure/azure-iot-sdk-c/tree/ios

**Comment by tameraw** [comment]
This has now shipped.

**Comment by yzhong94** [comment]
@jkriba , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
