### ISSUE TITLE
Compiling Azure IoT SDK C with MCUXpresso for NXP devices

### ISSUE THREAD

**Issue by abhijitnathwani** [Azure/azure-iot-sdk-c#1731]
Hi,

I am trying to compile the Azure SDK for NXP devices using the MCUXpresso IDE based on Eclipse. I am mainly trying to get the IoT PnP to work with FRDM k64F board. The problem is IDE does not support CMake build and it generates the Makefiles from the source folders added. NXP provides a sample for basic D2C messaging. I have added the `provisioning_client` folder and it's dependencies to allow DPS as required for IoT PnP. However, I am facing a lot many compilation issues regarding the source. I can confirm the headers files are included correctly. Has anyone tried compiling the SDK using MCUXpresso? 
The latest error I'm facing is:
```
incompatible types when initializing type 'enum <anonymous>' using type 'char *'	md.c	/frdmk64f_azure_mqtt_pnp/azure_iot/provisioning_client/deps/RIoT/Simulation/RIoT/Core/RIoTCrypt	line 98	C/C++ Problem
```
Host OS: Windows 10
Compiler: `gcc-arm-none-eabi`

Folder Structure:
![image](https://user-images.githubusercontent.com/5513984/98331634-fbc68380-2022-11eb-8a57-fe4d9f844810.png)

I am happy to share any more details if required. I could compile the SDK perfectly on Linux using `cmake`.

**Comment by danewalton** [comment]
Hi @abhijitnathwani can you give some more details on specific errors in files you are getting? I can't see which file you are getting the posted error in.

**Comment by danewalton** [comment]
Hi @abhijitnathwani I'm going to go ahead and close this for now. Please let me know if you need additional help and if I should reopen the issue.

**Comment by az-iot-builder-01** [comment]
@abhijitnathwani, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
