### ISSUE TITLE
Failed to open connection for device twin API (IoTHubDeviceClient_LL_GetTwinAsync) using MQTT protocol

### ISSUE THREAD

**Issue by motoxyz** [Azure/azure-iot-sdk-c#1732]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Cross Compiled on Ubuntu 12.04.4 LTS

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release LTS_07_2020_Ref01

**Protocol**

MQTT

**Describe the Bug**

Unable to open connection to retrieve device twin in Linux device (WIFI-connected) . (refer below Consoles Logs)
```
(void)IoTHubDeviceClient_LL_GetTwinAsync(iotHubClientHandle, getCompleteDeviceTwinOnDemandCallback, NULL);

```
When tried to print logs in socketio_berkeley.c, function: wait_for_connection, the retval  return 0. Which believe to be hitting timeout issue.
```
retval = select(socket_io_instance->socket + 1, NULL, &fdset, NULL, &tv);

```

But when I try to run in Ubuntu 18.04.4 LTS, able to get the device twin without issue.

**Console Logs**

Error: Time:Fri Nov  6 09:47:43 2020 File:/home/hola/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:424 Failure: select failure.
Error: Time:Fri Nov  6 09:47:43 2020 File:/home/hola/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:844 wait_for_connection failed
Error: Time:Fri Nov  6 09:47:43 2020 File:/home/hola/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
Error: Time:Fri Nov  6 09:47:43 2020 File:/home/hola/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:761 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Fri Nov  6 09:47:43 2020 File:/home/hola/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1281 Failed opening the underlying I/O.
Error: Time:Fri Nov  6 09:47:43 2020 File:/home/hola/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1042 Error: io_open failed
Error: Time:Fri Nov  6 09:47:43 2020 File:/home/hola/azure-iot-sdk-c-toolchain/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2282 failure connecting to address ADDRESS

**Comment by ewertons** [comment]
Hi @motoxyz ,
thanks for the the log. I clearly shows what the error is, which is good.
**select failure.**
The SDK can only run if the requirements are satisfied for the application to access the internet.
Please verify the permissions of your application to make sure it can use the network stack and devices in that platform.
On linux, you can set the perms of an application to access the network stack using setcap.
Example:
`sudo setcap cap_net_raw,cap_net_admin+ep ./your_executable`

**Comment by motoxyz** [comment]
Hi @ewertons.
Thanks for the reply. 
Tried the DPS with x509 code and it able to connect and assign with callback return for IOThub and device ID (Refer to below Console Logs). So there are no issue for application to access network stack and internet.

And noticed that both DPS and above device twin API run thru the socketio_berkeley.c, function: wait_for_connection.
But no issue for DPS in select function.
```
retval = select(socket_io_instance->socket + 1, NULL, &fdset, NULL, &tv);
```

**Console Logs**
Info: call tlsio_openssl_open in tlsio_openssl.c
Info: call socketio_open in socketio_berkeley.c
registration_status_callback: Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
PUT /"IDScope"/registrations/"device id"/register?api-version=2019-03-31 HTTP/1.1
UserAgent: prov_device_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
content-length: 31

{"registrationId":""registrationID""}

HTTP Status: 202

{"operationId":""operationID"","status":"assigning"}

registration_status_callback: Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
GET /'IDScope"/registrations/"device id"/operations/"operationID"?ap
UserAgent: prov_device_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
content-length: 0

HTTP Status: 200

{"operationId":""operationID"","status":"assigned","registrationStateDevNew"},"registrationId":""registrationID"","createdDateTimeUtc":"2020-11-08T05:52:26.9124435Z","assignedHub":""IOTHUB"":""deviceID"","status":"assigned","substatus":"initialAssignment","lastUpdatedDateTimeUtc":"2020-11-08T05:52:WwerrtMDAWqeerTVmQWerMDAWererCI="}}

**Comment by ewertons** [comment]
Hi @motoxyz ,
thanks for confirming.
We would need to attempt a repro and investigate the reason why select might be failing.
However, this issue will not meet the bar for us to prioritize its investigation, given:
- the issue you are facing is only on Ubuntu 12.04,
- the fact that this version [has already reached its end-of-life](http://releases.ubuntu.com/12.04/#:~:text=Ubuntu%2012.04.5%20LTS%20%28Precise%20Pangolin%29%20Ubuntu%2012.04%20LTS,will%20be%20accepted%20to%20the%2012.04%20primary%20archive.),
- the issue is not on an existing solution already running on the field (i.e., new development).

So unless this issue is reproduced on a platform/OS with active support, we will not be able to investigate it.

We apologize for that.

**Comment by motoxyz** [comment]
Hi @ewertons,
Additional information for the compiler toolchain and device's Linux version:
1. Used Compiler toolchain 8.3.0 to cross compile the IOT SDK C
2. Run in embedded device with Linux 2.6.34
