### ISSUE TITLE
memory loss after reconnect

### ISSUE THREAD

**Issue by gonglutao** [Azure/azure-iot-sdk-c#174]
Hi,
I find memory loss after reconnect cloud. 
There is 51856byte free memory befor reconnection, but there is 51552byte after reconnection.
I try this code:
```

1. void azure_thread(uint32_t inContext)
2. {
3.     bool traceOn = true;
4. 	azure_main_log("connecting IoTHub.....");
5.     if ((iotHubClientHandle = IoTHubClient_LL_CreateFromConnectionString(connectionString, MQTT_Protocol)) != NULL)
6.     {
7.         goto exit;
8.     }
9.     azure_main_log("connected IoTHub");
10. 
11.     IoTHubClient_LL_SetOption(iotHubClientHandle, "logtrace", &traceOn);
12.     while(1)
13. 	{
14. 		IoTHubClient_LL_DoWork(iotHubClientHandle);
15. 		mico_thread_msleep(500);
16. 		azure_main_log("Memory info: total %d, free %d.", MicoGetMemoryInfo()->total_memory, MicoGetMemoryInfo()->free_memory);
17. 	}
18. exit:
19. 	mico_rtos_delete_thread( NULL );
20. }

```
[memory_loss_log.txt](https://github.com/Azure/azure-iot-sdk-c/files/1126851/memory_loss_log.txt)

**Comment by ewertons** [comment]
Hi @gonglutao ,
thanks for reporting this issue.
I checked a fix for it. It is available on the latest code from the master branch of azure-iot-sdk-c.
If you can, please double-verify the fix and let us know if you confirm you no longer experience the bug.

Thanks for using and contributing to Azure IoT SDKs.
