### ISSUE TITLE
Can primary_key and secondary_key be used at the same time for DPS?

### ISSUE THREAD

**Issue by neotrip** [Azure/azure-iot-sdk-c#1748]
For DPS scenario, can primary key and secondary key be used at the same time?

When I try to register to DPS from a client device, I use primary key and secondary key alternatively.
For example, I register to DPS via primary key, and then register to DPS via secondary key  a minute later.

I found if registration succeeds by primary key, then secondary key will fail for registration.  And get following error messages:

Error: Time:Mon Nov 16 23:20:06 2020 File:/home/lbg/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:prov_transport_process_json_reply Line:670 Unsuccessful json encountered: {"errorCode":401002,"trackingId":"dd82c8ca-1572-4bf0-952a-a480082760cd","message":"Unauthorized","timestampUtc":"2020-11-16T15:20:06.2855197Z"}
Error: Time:Mon Nov 16 23:20:06 2020 File:/home/lbg/azure-iot-sdk-c/provisioning_client/src/prov_transport_http_client.c Func:prov_transport_http_dowork Line:941 Unable to process registration reply.
Error: Time:Mon Nov 16 23:20:06 2020 File:/home/lbg/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:771 Failure retrieving data from the provisioning service

1) Is it  the default behavior of server side?
2) what does errorCode "401002"  mean?

Thanks!

**Comment by ericwol-msft** [comment]
From the documentation at https://github.com/Azure/azure-iot-sdk-c/blob/86c0884e9a0c4332aafba70ca201384495915d7f/doc/Iothub_sdk_options.md

Timeout in seconds of initial connection establishment to IoT Hub. NOTE: **This does not specify the end-to-end time of the upload, which is currently not configurable.**

**Comment by ericwol-msft** [comment]
Currently, if a device registers with DPS using a primary or a secondary key, the key is cached for 30 mins. During this period, it will not be able to register with the other key.

**Comment by neotrip** [comment]
thanks, @ericwol-msft

But why DPS has such strategy?
There seems no such issue for IotHub ?

**Comment by ericwol-msft** [comment]
I don't know. That is what the DPS team responded with.

**Comment by danewalton** [comment]
This seems to be resolved for now so I'll go ahead and close it. Please let us know if you have any other questions.
