### ISSUE TITLE
IoT Hub devices continuously generate connected and disconnected events

### ISSUE THREAD

**Issue by sarthakvijayvergiya** [Azure/azure-iot-sdk-c#1752]
I think it might be some sdk issues ?

**Comment by az-iot-builder-01** [comment]
@sarthakvijayvergiya, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by danewalton** [comment]
Hey @sarthakvijayvergiya can you give some more details on what you're seeing? Log messages, error codes, etc. Turning on verbose logs would help us help you:
https://github.com/Azure/azure-iot-sdk-c/blob/d10d0fddc96aae9021440308213aa52abcce2946/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L124-L125

**Comment by sarthakvijayvergiya** [comment]
@danewalton sure, yes actually we implemented event notification on device connected and disconnected and suddenly it started trigger many times...

**Comment by danewalton** [comment]
Gotcha. In order to diagnose what is happening, we are going to need more concrete details of what is going on with the device. Theoretically it could be a handful of reasons: expired sas tokens, network going down, multiple devices connecting with the same credentials, etc. Logs would be wonderful if you could get those.

**Comment by sarthakvijayvergiya** [comment]
Is there is any way so we can debug from IoT Hub, without getting hardware logs ?

**Comment by danewalton** [comment]
Do you have details like device id or an iothub name?

**Comment by sarthakvijayvergiya** [comment]
yes

**Comment by sarthakvijayvergiya** [comment]
@danewalton might it is the case when firmware is updating on device ?
