### ISSUE TITLE
building with icc, compile error

### ISSUE THREAD

**Issue by yoshinao-takada** [Azure/azure-iot-sdk-c#1755]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
Epson AT-991, Clear Linux OS Version 1, Intel icc 2021.1 Beta 20200827 and icpc 2021.1 Beta 20200827 for intel 64

**SDK Version (Please Give Commit SHA if Manually Compiling)**

LTS_07_2020_Ref01

**Protocol**

Not applicable

**Describe the Bug**
At line 949 of c-utility/adapters/socketio_berkeley.c, there is an arithmetic addition of void* and size_t. My compiler failed to compile.
 if (add_pending_io(socket_io_instance, buffer + bytes_sent, size - bytes_sent, on_send_complete, callback_context) != 0)
I modified as below and built.
if (add_pending_io(socket_io_instance, (unsigned char*)buffer + bytes_sent, size - bytes_sent, on_send_complete, callback_context) != 0)

**Comment by ericwol-msft** [comment]
PR @ https://github.com/Azure/azure-c-shared-utility/pull/478

**Comment by ericwol-msft** [comment]
merged

**Comment by az-iot-builder-01** [comment]
@yoshinao-takada, @ericwol-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
