### ISSUE TITLE
Understanding Cloud to Device messaging memory allocation and lifetime.

### ISSUE THREAD

**Issue by fanzhe98** [Azure/azure-iot-sdk-c#1764]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Azure Sphere 20.10 OS

**SDK Version (Please Give Commit SHA if Manually Compiling)**

July LTS

**Protocol**

MQTT

**Context**
oom was hit when receiving message on Azure Sphere.

**Question on allocation:**
When receiving large message from IoTHub, I see quite large overheads. For example, when I send a 30k message from iothub,  the overhead I saw is around 50k and totally memory allocated is around 80k. We would like to understand where such overhead comes from. 

**Question on message lifetime:**
This question comes from trial that sending 30k message and a 10k message following. The allocation of 80k did not change after the 10k message is received. However, sending a 10k message alone seems only introducing around ~25k allocation. This poses a question on the lifetime of the memory allocation when receiving a message.

**Comment by ericwol-msft** [comment]
The memory usage is approximately the payload size, plus protocol header overhead. How did you come to the conclusion that 50k was allocated on a 30k message? It is possible on a memory constrained device that you can run into heap fragmentation. 

To debug this, you can use memory growth flame graphs to track the allocations.
http://www.brendangregg.com/FlameGraphs/memoryflamegraphs.html

**Comment by az-iot-builder-01** [comment]
@fanzhe98, @ericwol-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by momuno** [comment]
Closing as issue is now understood.
