### ISSUE TITLE
How to calculate size of system properties and user properties of a telemetry message ?

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/azure-iot-sdk-c#1765]
Hi

we have open an issue earlier , but response was not pretty much clear. so opening a new issue.

following is older one.
https://github.com/Azure/azure-iot-sdk-c/issues/1701

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-construct#message-size
As per above link message size include below 3 points

- The body size in bytes.
- The size in bytes of all the values of the message system properties.
- The size in bytes of all user property names and values.

Could you please let me know how to calculate size of system properties and user properties of a telemetry message using c-device-sdk ?
i mean how user will know the size  before sending to iothub ?

**Comment by ericwol-msft** [comment]
System properties are set via
                (void)IoTHubMessage_SetMessageId(message_handle, "MSG_ID");
                (void)IoTHubMessage_SetCorrelationId(message_handle, "CORE_ID");
                (void)IoTHubMessage_SetContentTypeSystemProperty(message_handle, "application%2fjson");
                (void)IoTHubMessage_SetContentEncodingSystemProperty(message_handle, "utf-8");
                (void)IoTHubMessage_SetMessageCreationTimeUtcSystemProperty(message_handle, "2020-07-01T01:00:00.346Z");
So for example message ID vaule size would be 6 bytes.

User properties are set via this API
                (void)IoTHubMessage_SetProperty(message_handle, "property_key", "property_value");
So in this case it would be 12 + 14 = 26 bytes

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now. @rajaggrawal please let us know if you would like this reopened.
