### ISSUE TITLE
azure c sdk doesnt give throttling error(429) to user.

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/azure-iot-sdk-c#1766]
Hi,

As per following link iothub sends throttling error to user once quota is reached

references 

1. https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling
2. https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-reliability-features-in-sdks#retry-patterns

As far as i know c-sdk retry the messages which is failed due to throttling.
but how the user will know the messages are failed due to throttling ?

Following are the response code, but i dont see any error code which describe throttling error.
#define IOTHUB_CLIENT_CONFIRMATION_RESULT_VALUES     \
    IOTHUB_CLIENT_CONFIRMATION_OK,                   \
    IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY,      \
    IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT,      \
    IOTHUB_CLIENT_CONFIRMATION_ERROR         

it seems it was done for java-sdk. we need this to c-sdk as well.
https://github.com/Azure/azure-iot-sdk-java/issues/240

We want to retry the messages which is failed due to throttling. 
Could you please let me know how to get throttling error using c-sdk ?

**Comment by ericwol-msft** [comment]
Here is a previous thread on this topic. https://github.com/Azure/azure-iot-sdk-c/issues/1001
429 errors are only respective to the HTTP transport. For MQTT the connection is closed but the hub. The current MQTT version does not facilitate the reason code of the closure. This has been added to the MQTT v5 spec.

**Comment by danewalton** [comment]
This seems to be answered for now. I will go ahead and close it. @rajaggrawal please let us know if you would like it reopened
