### ISSUE TITLE
is there a way to send desired and direct method to edge-hub directly in offline mode.

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/azure-iot-sdk-c#1768]
Hi,

let say our leaf-device and edge device is registered  to iot-hub.
we want to send data (desired/directMethod/C2D) to edge-device/leaf-device directly in offline mode without iothub.

let say one of our app(user-app) is running on same device where edge hub is running and it needs to communicate directly with edge-hub .
user-app <--> edge-hub

is there a way to communicate(user-app) with edge-hub directly without any intervention of iothub ?

**Comment by rajaggrawal** [comment]
closing this , will raise this to iotedge.

**Comment by az-iot-builder-01** [comment]
@rajaggrawal, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
