### ISSUE TITLE
MQTT protocol is not working

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-c#1769]
Hi,
I was using "auto_url_encode_decode" while sending telemetry data to hub but failing with this message "Func:_HTTPAPI_CloneOption Line:1238 unknown option auto_url_encode_decode" please help me to choose the right set_option.

**Comment by danewalton** [comment]
Hey @Abhi2109 the error makes me believe you have the HTTP protocol enabled? Are you sure you are using MQTT?

**Comment by Abhi2109** [comment]
Thanks Dane this got solved..

**Comment by az-iot-builder-01** [comment]
@danewalton, @Abhi2109, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
