### ISSUE TITLE
How to securely download a firmware/blob ?

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#177]
This SDK provides an API to securely upload a blob ( `IoTHubClient_LL_UploadToBlob `). But when it comes to needs like firmware download, samples are using _wget_. Is this intentional ? Is it possible to provide us some thing like `IoTHubClient_LL_DownloadFromBlob` ? So that device can securely download a firmware/software, with out  exposing it to whole world.

**Comment by nberdy** [comment]
Thanks for the suggestion! We're tracking this improvement on [UserVoice](https://feedback.azure.com/forums/321918-azure-iot/suggestions/19109089-add-samples-support-for-azure-storage-blob-downloa) - can you please upvote it there and add your details?

**Comment by kiranpradeep** [comment]
Upvoted. But should it have gone via UserVoice ? I thought UserVoice was for functional requirements. This is more of a non functional ( security ) requirement. For. e.g. If I wanted a golang sdk for iot-edge, I would put that in UserVoice.

May be I am wrong. But, IMHO, this is a clear security gap in this SDK:  No way for user to securely share a firmware which is a [documented](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-firmware-update) feature of Azure. Currently, we reduce attack surface with expiring URLs for firmware.

**Comment by nberdy** [comment]
Thanks. This goes in UserVoice since there is a functionality component required for the service to be able to support this - it's not just an SDK issue.
