### ISSUE TITLE
Sending telemetry data

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-c#1772]
Hi,
I am sending the telemetry data through an application (MFC) and once data is sent using a button click, when i am trying to send the data again it's not uploading on hub as when i debugged into that for both the time flow is same there is no exception at all i just don't understand why this behavior. Please help me understand this issue.

**Comment by Abhi2109** [comment]
What is the location where i can find these logs, sorry i am bit new in this.

**Comment by Abhi2109** [comment]
Whether it would be inside my cmake folder?

**Comment by ericwol-msft** [comment]
the logs are output to stdout

**Comment by Abhi2109** [comment]
Can i share wireshark traces?

**Comment by Abhi2109** [comment]
Hi,
ip.addr == 13.76.217.46. 

[Re-Send_Scenario.zip](https://github.com/Azure/azure-iot-sdk-c/files/5626601/Re-Send_Scenario.zip)

**Comment by Abhi2109** [comment]
Seems like this issue is only with "AMQP" and "MQTT" with HTTP it's working like charm.

**Comment by ericwol-msft** [comment]
The Wireshark traces are TLS encrypted and are not useful except to debug connection or TLS cert negotiations issues (unless you have the TLS session key?).

You need to provide more detailed information of your issue. My understanding is that you are trying to send multiple telemetry messages, and using AMQP, not all the telemetry messages are making it to the hub?

To further investigate this issue, we really need the SDK device logs to analyze. Is there a reason you are using AMQP over MQTT? MQTT is definitely a lighter protocol to use with devices.

**Comment by Abhi2109** [comment]
yes your assumption is right regarding " My understanding is that you are trying to send multiple telemetry messages, and using _AMQP_ ### i am using MQTT as well, not all the telemetry messages are making it to the hub?"

As i have mentioned in my earlier remark :"Seems like this issue is only with "AMQP" and "MQTT" with HTTP it's working like charm."

**Comment by danewalton** [comment]
Hey @Abhi2109 can you set the verbose logs to on and try running again? Example:
https://github.com/Azure/azure-iot-sdk-c/blob/593e81183e962c402790e76b41a63c776e78f420/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L124-L125

**Comment by danewalton** [comment]
@Abhi2109 any updates here?

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now. Please let us know if you continue to have issues.
