### ISSUE TITLE
Need to know about changes for adapting to Azure China

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-c#1775]
Hi,
I have developed few functions using azure SDK IOT C, now my question is do i need to do any changes for accessing using Azure China(21vianet) while communicating with Hub of Azure China.

**Comment by danewalton** [comment]
Yes your device will have to have the cert [here](https://github.com/Azure/azure-iot-sdk-c/blob/c5c6258b0a1166710979d9df31c13aaebcd76667/certs/certs.c#L46-L71) to connect to a hub with a `.cn` domain name. If you have none of these macros defined, all of them should be on your device. But if using something with limited memory and maybe you only had the Baltimore Root before, you will have to switch it to the one listed.

**Comment by Abhi2109** [comment]
Thanks Dane for your answer.
I would like to know one thing.

So lets say when i will be building my solution using CMake then based on the region do i need to set for china region those certificate definition?

**Comment by danewalton** [comment]
If you want to only include one root cert, you would yes. Here are the options:
https://github.com/Azure/azure-iot-sdk-c/blob/a1dfa62cd66e597b6b873ae4299fac999d94f613/CMakeLists.txt#L76-L78

All of the root certs are included by default as you can see here:
https://github.com/Azure/azure-iot-sdk-c/blob/a1dfa62cd66e597b6b873ae4299fac999d94f613/certs/certs.c#L12-L17

**Comment by Abhi2109** [comment]
Yep, i guess include option based on region would be good else all the certificates would be loaded by default which will waste some space/memory.

Can you please help me with one more thing.

Do you know how in Cmakelist we can adjust for region?

**Comment by danewalton** [comment]
Yup sure. You can add a line in your CMake which does something like the following:
```
set(use_portal_azure_cn_cert ON CACHE BOOL "Set China domain cert" FORCE)
```
Similarly for the other cert options if you wish to set them. You could even set your own CMake option to switch those "set" commands on or off.

**Comment by Abhi2109** [comment]
Thanks Dane Alot..

I have one last question on this "While receiving Telemetry message using EventHub do we require Certificate there as well"?

**Comment by danewalton** [comment]
are you using a service client to monitor the Event Hub messages?

**Comment by danewalton** [comment]
Going to go ahead and close this for now. Let me know if you would like it reopened for further questions.

**Comment by az-iot-builder-01** [comment]
@danewalton, @Abhi2109, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
