### ISSUE TITLE
inclusion for sys/errno.h in socket_async_os.h will trigger warning under musl libc runtime

### ISSUE THREAD

**Issue by fanzhe98** [Azure/azure-iot-sdk-c#1776]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Azure Sphere OS

**SDK Version (Please Give Commit SHA if Manually Compiling)**

**Protocol**

MQTT

**Describe the Bug**

Compilation of socket_async_os will throw warning for inclusion of sys/errno.h (as opposed for errno.h) for musl libc runtime.

**Comment by fanzhe98** [comment]
Issue for patch2 discussed in the last meeting. 

cc @suhuruli @momuno

**Comment by fanzhe98** [comment]
waiting for an agreement on ifdef to proceed

**Comment by reubeno** [comment]
The POSIX standard lists `<errno.h>`; is there a reason this change needs to be guarded by an ifdef?  Are there platforms that require otherwise?

**Comment by fanzhe98** [comment]
@reubeno Ah, I forgot this is a POSIX standard, I will put a PR then

**Comment by fanzhe98** [comment]
Moving to https://github.com/Azure/azure-c-shared-utility/issues/484

**Comment by az-iot-builder-01** [comment]
@fanzhe98, @reubeno, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
