### ISSUE TITLE
UNUSED parameter in process_option under tlsio_wolfssl.c

### ISSUE THREAD

**Issue by fanzhe98** [Azure/azure-iot-sdk-c#1777]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
Ubuntu 20.04
Azure Sphere OS
**SDK Version (Please Give Commit SHA if Manually Compiling)**

2020-07lts

**Protocol**

MQTT

**Describe the Bug**

UNUSED parameter in process_option under tlsio_wolfssl.c

**Comment by fanzhe98** [comment]
issue for patch#4 discussed in the last meeting
cc. @suhuruli @momuno

**Comment by fanzhe98** [comment]
Move to https://github.com/Azure/azure-c-shared-utility/issues/480 since the fix should be in that repo

**Comment by az-iot-builder-01** [comment]
@fanzhe98, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
