### ISSUE TITLE
[Azure Sphere] hiding device id

### ISSUE THREAD

**Issue by fanzhe98** [Azure/azure-iot-sdk-c#1778]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
Ubuntu 20.04 Azure Sphere

**SDK Version (Please Give Commit SHA if Manually Compiling)**

20-07 lts

**Protocol**

MQTT

**Describe the Bug**

hiding device id in provision client callback.

**Comment by fanzhe98** [comment]
patch #3 discussed in the last meeting.

cc @momuno @suhuruli

**Comment by fanzhe98** [comment]
Waiting for an agreement on ifdef before proceeding

**Comment by momuno** [comment]
Leaving as is. Not worth an additional build flag.
