### ISSUE TITLE
Potential memory leak in examples

### ISSUE THREAD

**Issue by dbuijsma** [Azure/azure-iot-sdk-c#178]
Version: lts_07_2017 (version  1.1.18)

# Description of the issue:
In several examples where IoTHubClient_LL_SendEventAsync() is called, IoTHubMessage_Destroy() is not called to free the memory allocated by IoTHubMessage_CreateFromByteArray() in the case where IoTHubClient_LL_SendEventAsync() fails.

# Code sample exhibiting the issue:
For example in ".../iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c"

`
  if (IoTHubClient_LL_SendEventAsync(iotHubClientHandle, messages[iterator].messageHandle, SendConfirmationCallback, &messages[iterator]) != IOTHUB_CLIENT_OK)
  {
          (void)printf("ERROR: IoTHubClient_LL_SendEventAsync..........FAILED!\r\n");

          // !@! cleanup here: eg: 
          IoTHubMessage_Destroy(messages[iterator].messageHandle);
  }
`

Not to be nitpicky, but since I have your attention, there's also a small typo in a comment: 
"If we receive the **work** 'quit' then we stop running"

That should be **word**

**Comment by tameraw** [comment]
@dbuijsma - Thanks for filing this issue. If you're able to send a PR that would help a lot. Thanks.

**Comment by dbuijsma** [comment]
No problem. Do create a pull request, do I have to be added as a contributer? 

I have another bug in the socketio_berkeley.c module to file as well and I'll open an issue for that later next week (needs more testing).

**Comment by jebrando** [comment]
You do not need to be a contributor for this, if you create a PR it will come through.

**Comment by dbuijsma** [comment]
As a non-contributor I'd have to create a fork to be able to do a PR if I understand [this article](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) correctly. I can do that, but it seems like a lot of trouble. What does it take to become a contributor?

**Comment by ewertons** [comment]
All you need is to:
1. create a fork;
2. create a branch for the change
3. Make the changes, commit and push online;
4. Send a PR from your fork to us.
