### ISSUE TITLE
Failed to set up Ubuntu 14.04 environment

### ISSUE THREAD

**Issue by Howhowshow** [Azure/azure-iot-sdk-c#1781]
**Development Machine** : 
Ubuntu 14.04.6 LTS
Gcc : 4.8.4
cmake :  2.8.2.12
CURL : 7.35

**SDK Version (Please Give Commit SHA if Manually Compiling)**
LTS_07_2020_Ref01

**Protocol**
MQTT

**Describe the Bug**
I follow this guideline as below to set up my Linux environment and got some problem.
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md

When I started "Build the C SDK on Linux " steps, there are errors with 'cmake ..' command.

```
cd azure-iot-sdk-c
mkdir cmake
cd cmake
cmake .. 
```
**Console Logs**
johnny@johnny-HP:~/azure-iot-sdk-c/cmake$ cmake ..
-- IoT Client SDK Version = 1.3.9
-- This version of CMake does not support interface targets. Only the Azure Macro Utils header file will be installed. To use Azure Macro Utils, simply add "MACRO_UTILS_INC_FOLDER" to your include directories as specified in the instructions on the GitHub README.
CMake Error at deps/umock-c/CMakeLists.txt:52 (message):  Could not find azure_macro_utils_c

-- Configuring incomplete, errors occurred!
See also "/home/johnny/azure-iot-sdk-c/cmake/CMakeFiles/CMakeOutput.log".

**Comment by danewalton** [comment]
Hi @Howhowshow we don't have official support for Ubuntu 14.04. This does look like an issue with the CMake version that you have installed. You might be able to try installing CMake from source and installing it to a version newer than what `apt-get` will give you?

**Comment by Howhowshow** [comment]
Hi @danewalton 
I install CMake 3.2.2 from source,it worked. 
Thank you !

**Comment by danewalton** [comment]
Awesome glad to hear! I'll go ahead and close this issue for now but feel free to open another if you hit other problems!

**Comment by az-iot-builder-01** [comment]
@danewalton, @Howhowshow, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by danewalton** [comment]
@Howhowshow to your edit yes we can take a look at our required CMake version and see if that should be bumped based on our usage. Thanks for the suggestion.
