### ISSUE TITLE
Not able to provision a device to iothub using DPS service.

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/azure-iot-sdk-c#1789]
Recently our devices in production are not getting registered to IoTHub through DPS
service.

we are seeing following error code.
ErrorCode:IotHubUnauthorizedAccess;Unauthorized

{"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:fb98cf343f2a4021957955f06926ed1e-G:10-TimeStamp:12/10/2020 06:42:31"}

Could you please let me know what is the reason of this ?

below are logs

```
[INFO] AZURE_PLATFORM:Device provision status update: PROV_DEVICE_REG_STATUS_CONNECTED
2020-12-10T06:41:26.342147+00:00 ClickShare-1862350839 iotagent[791]: [INFO] AZURE_PLATFORM:Device provision status update: PROV_DEVICE_REG_STATUS_ASSIGNING
[INFO] AZURE_PLATFORM:Device provision status update: PROV_DEVICE_REG_STATUS_ASSIGNING
[CRITICAL] AZURE_PLATFORM:Provisioning Failure: OperationId: 4.5cda764d087b4e5a.6c6a7983-b979-44eb-8611-7f08bf1fc331 - Date: 2020-12-10T06:42:32.1308829Z - Msg: {"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:fb98cf343f2a4021957955f06926ed1e-G:10-TimeStamp:12/10/2020 06:42:31"}

```

**Comment by ericwol-msft** [comment]
The connection string of the Hub registered with DPS is either incorrect, stale or does not have the requisite registry read/write access.

One solution maybe to unlink and re-link that Hub to DPS again.

**Comment by rajaggrawal** [comment]
Unlink and re-link  IoTHub to DPS has resolved the issue.
Thanks.

**Comment by danewalton** [comment]
Seems this was resolved so going to go ahead and close. Let us know if you have any further questions!

**Comment by az-iot-builder-01** [comment]
@ericwol-msft, @rajaggrawal, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
