### ISSUE TITLE
Android NDK with pthread issue, help needed. thanks.

### ISSUE THREAD

**Issue by radezheng** [Azure/azure-iot-sdk-c#179]
- Ubuntu 17.04 

- C  for Android NDK android-18 

# Description of the issue:

Our customer want to use the C SDK in Android NDK environment, need to use cross compiling,
I setup the dev env in Ubuntu, with toolchain for ARM , I managed to compile with toolchain make file.
but still encountered issue for the pthread. can you help? this is a very large case for connected car in China, thanks.

# Code sample exhibiting the issue:

toolchain.cmake:
INCLUDE(CMakeForceCompiler)

SET(OPENSSL_ROOT_DIR  /usr/local/ssl/android-18/)
SET(OPENSSL_LIBRARIES /usr/local/ssl/android-18/lib)
SET(CURL /usr/lib/i386-linux-gnu/ )
SET(CURL_LIBRARIES /usr/include/i386-linux-gnu/curl/)
SET(OPENSSL_INCLUDE_DIR  /usr/local/ssl/android-18/include/)

SET(CMAKE_SYSTEM_NAME Linux)     # this one is important
SET(CMAKE_SYSTEM_VERSION 1)     # this one not so much

# this is the location of the amd64 toolchain targeting the Raspberry Pi
SET(CMAKE_C_COMPILER /root/toolchain/bin/arm-linux-androideabi-gcc-4.8)

# this is the file system root of the target
SET(CMAKE_FIND_ROOT_PATH /root/toolchain/sysroot)

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Console log of the issue:
[ 11%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/usha.c.o
[ 11%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/vector.c.o
[ 11%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/xlogging.c.o
[ 12%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/optionhandler.c.o
[ 12%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/agenttime.c.o
[ 13%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/condition_pthreads.c.o
/root/azure-iot-sdk-c/c-utility/adapters/condition_pthreads.c: In function 'create_cond':
/root/azure-iot-sdk-c/c-utility/adapters/condition_pthreads.c:26:9: error: implicit declaration of function 'pthread_condattr_setclock' [-Werror=implicit-function-declaration]
         pthread_condattr_setclock(&cattr, time_basis);
         ^
cc1: all warnings being treated as errors
c-utility/CMakeFiles/aziotsharedutil.dir/build.make:782: recipe for target 'c-utility/CMakeFiles/aziotsharedutil.dir/adapters/condition_pthreads.c.o' failed
make[2]: *** [c-utility/CMakeFiles/aziotsharedutil.dir/adapters/condition_pthreads.c.o] Error 1
CMakeFiles/Makefile2:983: recipe for target 'c-utility/CMakeFiles/aziotsharedutil.dir/all' failed
make[1]: *** [c-utility/CMakeFiles/aziotsharedutil.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by olivierbloch** [comment]
We have a fork that was created some time ago and that we still need to test clean up and merge [here](https://github.com/msjaosborn/azure-iot-sdk-c). We will be looking into this merge soon, but in the meantime the fork might help you getting unblocked.

**Comment by ewertons** [comment]
Hi @radezheng ,
were you able to get unblocked by the suggestion @olivierbloch provided?
Thanks.

**Comment by ewertons** [comment]
Hi @radezheng ,
were you able to get unblocked by the suggestion @olivierbloch provided?
Thanks.

**Comment by jspaith** [comment]
Closing this issue as we haven't heard back yet.  @radezheng please feel free to reactivate this issue or create a new one if there's further issues here.
