### ISSUE TITLE
Time conversion

### ISSUE THREAD

**Issue by dzuda11** [Azure/azure-iot-sdk-c#1799]
Hi,

I have a question regarding time conversion. As far as I understand so far, most of (or every) azure services use ISO8601 date format (e.g. "2020-11-16T04:25:03Z"). Sometimes those dates can be sent to a device in string format. C and C++ don't support that format natively and UNIX time is more common in the embedded world. 

Do you have any recommendations about how the ISO8601 date string should be converted to UNIX time (time_t) and vice versa?

Thank you!!

**Comment by ewertons** [comment]
Hi @dzuda11 ,
thanks for your question, but it is not related to Azure IoT. This is a generic question related to C and Date conversion.
Examples: 
https://stackoverflow.com/questions/5383439/how-do-i-convert-an-iso-8601-string-to-time-t-in-c
https://stackoverflow.com/questions/6618111/iso-8601-to-time-t-conversion-in-c-or-vice-versa

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@dzuda11, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
