### ISSUE TITLE
[MQTT][Defect] connection retry policy implementation has chance to never able to retry at all

### ISSUE THREAD

**Issue by yphuangms** [Azure/azure-iot-sdk-c#18]
In "azure-iot-sdks\c\iothub_client\src\iothubtransport_mqtt_common.c", 
there exist chances that retry will never happen due to the implemenation of function "RetryPolicy_Exponential_BackOff_With_Jitter()", and "CanRetry()".

In "RetryPolicy_Exponential_BackOff_With_Jitter()", 

     int numOfFailures = (int) retryLogic->retrycount;
     size_t halfDelta = ((1 << numOfFailures) - 1) / 4;
     *delay = halfDelta + (rand() % (int)halfDelta);

The numOfFailures comes from current retryCount, and halfDelta based on retry count it could be a very big number due to (1 << numOfFailure), and delay value will be restricted as (halfDelta <= delay < halfDelta*2). 

If retryCount = 30, halfDelta could be very huge, for halfDelta will be approximately  2 powered (retryCount - 2), which is 2 powered 28, a very huge number of seconds (for days) for next retry, and it lose the meaning of retry in reality.

Suggest to restrict delay between few seconds to few minutes, or **just provide a way to configure a interval that's more predicable/reliable for real world scenario**.

In "CanRetry()", the flow should be review again, for there exists logics that cause result never be set to true. Especially in these two part:

    
        if (retryLogic->retryStarted)
        {
            double diffTime = get_difftime(now, retryLogic->lastConnect);
            if (diffTime <= ERROR_TIME_FOR_RETRY_SECS)
            {
                // Just right time to retry
                if(diffTime > WAIT_TIME_SECS)
                {
                    retryLogic->lastConnect = now;
                    retryLogic->retrycount++;
                    result = true;
                }
                else
                {
                    // As do_work can be called within as little as 1 ms, wait to avoid throtling server
                    result = false;
                }
            }           

Here the code restricts retry happening only when the code entry time (since last retry) is luckly between 
 ((ERROR_TIME_FOR_RETRY_SECS-1)< diffTime <= ERROR_TIME_FOR_RETRY_SECS). If this piece of code is not hit, then the next chance to retry is in next code section:

           else
            {
                // last retry time evaluated have crossed, determine when to try next
                bool permit = false;
                size_t delay;

                if (retryLogic->fnRetryPolicy != NULL && (retryLogic->fnRetryPolicy(&permit, &delay, retryLogic) == 0))
                {
                    if ((permit == true) && ((retryLogic->retryTimeoutLimitInSeconds == 0) || retryLogic->retryTimeoutLimitInSeconds >= (delay + get_difftime(now, retryLogic->start))))
                    {
                        retryLogic->delayFromLastConnectToRetry = delay;

                        LogInfo("Evaluated delay %d at %d attempt to retry\n", delay, retryLogic->retrycount);

                        if (retryLogic->delayFromLastConnectToRetry <= ERROR_TIME_FOR_RETRY_SECS)
                        {
                            retryLogic->lastConnect = now;
                            retryLogic->retrycount++;
                            result = true;
                        }
                        else
                        {
                            result = false;
                        }
                    }

In the above code section, the "delay" time will be update again in "RetryPolicy_Exponential_BackOff_With_Jitter()" function, which means, when elapsed time exceeds delay time, it won't connect right away, it then updates "delay" time again, and this time, this delay time could be even larger than last time before, and hence it's possible that no connection retry will be executed ever.

Usually we expect a connection retry will be executed when the elapsed time (since last retry) exceeds "delay" time, so at the time "diffTime > retryLogic->delayFromLastConnectToRetry", it should set result to true to enable execution of connection retry, not just to update "delay" time.

The above mentioned issue is found by running the sample code with manually disconnect/resume the network, and such kind of network error handling should be taken care in the code carefully for it might happen in real world case often.

**Comment by prmathur-microsoft** [comment]
Hi yphuangms,

Thank you for your comment. You are talking about two cases here.

1." just provide a way to configure a interval that's more predicable/reliable for real world scenario."
We do have retry timeout limit which is the best knob you have to control the retry attempts. We have limited the maximum amount of time permissible by providing a specific data type for retry timeout which basically means we can control large numbers by setting a reasonable value to retry timeout limit. In which case  retryLogic->fnRetryPolicy will not be evaluated.

2. Window of timeout error - Because of the way our SDK works, which calls do_work every now and often, it turns out that we cannot guarantee when will CanRetry be called. So we have to do our best to make an attempt to evaluate retry and trigger it. Hence we use error times, which is our way to give best effort try to attempt to retry. If canRetry falls in the window of error after a delay has been evaluated then we give a go signal to retry. However, if canRetry falls out of the window of error everytime then yes you are right about never having to retry. For this reason we have carefully used a number to decide on the window of error ( which is not too huge to force use stale values and not so small to slip always). In your case if you still feel it doesn't fit your platform, please let us know so that we can prune it further.

Thanks
Priyanka

**Comment by yphuangms** [comment]
Hi Priyanka,

Sorry for not being able to understand your two cases based on the understanding of the code. It would be very appreciate if you could trace the code to get exactly what the code is doing.

This  "retryLogic->retryTimeoutLimitInSeconds" variable controls the limit to stop retry. A limit to stop retry is different from the "interval" (delay) to next retry.  In your case 1, you said there's a way to set a reasonable value to retry timeout limit, but for IoT device, we don't want to stop retry, we want the retry continue and retry should happen in an expected/predicable way until network resumed. We would like the retry policy to provide a way for us to set a retry interval, not a TIMEOUT TO STOP RETRY.

If the underlying retry stopped, which means this IoT device will never be able to connect to IoT Hub, even if the network issue is resolved.

So "retryLogic->retryTimeoutLimitInSeconds" is not the parameter useful to common use cases. In a common use case for IoT device, we would like the mqtt connection being recovered automatically if the network condition is resumed to connected. This is why "retry" function important to real world scenario. We are glad that "RetryPolicy" is implemented / enabled in MQTT transportation, we would be happy to see this "RetryPolicy" becomes more predicable and reliable.

Thanks!

**Comment by yphuangms** [comment]
To be specific to the "defect" found in the code (iothubtransport_mqtt_command.c):

-- DoWork() will always try to ensure the connection to be initialized by calling to "InitializeConnect()" . If network is disconnected (socket cannot be opened to connect to target IoT hub), calling to "InitializeConnect()" will fail, and this function will be called again in next "DoWork()" call. The call to "DoWork()" will be managed in a loop in application program.

-- When calls to "InitializeConnect()", if no connection is maintained, this function will try to create the connection ( "SendMqttConnectMsg()" ) again if "CanRetry()" returns true. If the "CanRetry()" always return false, then no connection will ever be established again, even if the network problem is resolved.

-- There's no way to select retry policy in MQTT transportation. In "CreateRetryLogic()", the code shows "retryLogic->fnRetryPolicy = &RetryPolicy_Exponential_BackOff_With_Jitter" for all of retry policy options, even for retry policy == IOTHUB_CLIENT_RETRY_NONE.

-- In "CanRetry()",  there are 3 conditions to return true:

1. 

```
    if (retryLogic == NULL)
    {
        LogError("Retry Logic is not created, retrying forever");
        result = true;
    }

```
But due to a retry policy is set (hardcoded in iothub_client), this condition will never be met.

2. 

```
    if (retryLogic->retryStarted)
    {
        double diffTime = get_difftime(now, retryLogic->lastConnect);
        if (diffTime <= ERROR_TIME_FOR_RETRY_SECS)
        {
            // Just right time to retry
            if(diffTime > WAIT_TIME_SECS)
            {
                retryLogic->lastConnect = now;
                retryLogic->retrycount++;
                result = true;
            }
            else
            {
                // As do_work can be called within as little as 1 ms, wait to avoid throtling server
                result = false;
            }
        }

```

Due to the fact "difftime()" return the time difference in seconds, only when the elapsed time (since last connection retry) is equal to "ERROR_TIME_FOR_RETRY_SECS" (5 seconds), CanRetry will return true. This time window is narrow, and the worst case is, if missing one chance to hit this time window, then the delay time will be again updated (to a even larger number), and the "retryLogic->lastConnect" time is not changed, so the next CanRetry() will get a larger number of elapsed time, so this condition will never be met again before any retry is run. The next chance to run retry is 

            if (retryLogic->fnRetryPolicy != NULL && (retryLogic->fnRetryPolicy(&permit, &delay, retryLogic) == 0))
            {
                if ((permit == true) && ((retryLogic->retryTimeoutLimitInSeconds == 0) || retryLogic->retryTimeoutLimitInSeconds >= (delay + get_difftime(now, retryLogic->start))))
                {
                    retryLogic->delayFromLastConnectToRetry = delay;

                    LogInfo("Evaluated delay %d at %d attempt to retry\n", delay, retryLogic->retrycount);

                    if (retryLogic->delayFromLastConnectToRetry <= ERROR_TIME_FOR_RETRY_SECS)
                    {
                        retryLogic->lastConnect = now;
                        retryLogic->retrycount++;
                        result = true;
                    }
                    else
                    {
                        result = false;
                    }
                }

In this condition, only when the "delay" time returned from "RetryPolicy_Exponential_BackOff_With_Jitter()" is less then or equal to "ERROR_TIME_FOR_RETRY_SECS" (5 seconds), CanRetry() will return true. So, let's do a code trace and see how's the probability this "delay" number will be >= 5, in "RetryPolicy_Exponential_BackOff_With_Jitter()", this delay number will become bigger along with this value "retryLogic->retrycount". This means, as the network error situation continues, this "retryLogic->retrycount" gets bigger, if "DoWork" function is not called at a proper time window, so the program misses one time to retry at the time window of (elapsed time == 5), then it will get a big delay ( >= 5) that will cause the retry never be executed again.

If this "CanRetry()" logic is not changed, then no matter how "ERROR_TIME_FOR_RETRY_SECS" is set, there are always chances the code will fall into a condition that no retry will ever be run. If a retry policy will fall into a hole that no retry will be executed, then this is not an expected "RetryPolicy" should be in a way to common sense. This the reason I report this as a "defect".

Please consider to review the whole retry process, some could be the policy design issue, some could be the coding bug.
Please also consider to enable retry to run in a fixed interval basis (configurable interval).

Thanks!

**Comment by BertKleewein** [comment]
Fixed committed: e923565e176aa58a604da007c67118d65a16dcaf

We will close this issue when the fix is released.

**Comment by anporumb** [comment]
Published.

**Comment by Nakul93** [comment]
Hello people,
Can anyone suggest how to retry for a specific period of time and then return back toIoTHubClient_LL_DoWork
