### ISSUE TITLE
OPTION_MESSAGE_TIMEOUT value documentation mismatch

### ISSUE THREAD

**Issue by Shakti213** [Azure/azure-iot-sdk-c#180]
- **OS and version used:** Windows 10

- **SDK version used:** master 

# Description of the issue:

Looking at the source for IoTHubClient_LL_SetOption the comments say that the value for "messageTimeout" should be a pointer to uin64:
Codes_SRS_IOTHUBCLIENT_LL_02_039: [ "messageTimeout" - once IoTHubClient_LL_SendEventAsync is called the message shall timeout after value miliseconds. Value is a pointer to a uint64. ]

Looking at the code though value is actually supposed to be a pointer to tickcounter_ms_t:
`handleData->currentMessageTimeout = *(const tickcounter_ms_t*)value;` which is typedefed to uint_fast32_t in tickcounter.h:
`typedef uint_fast32_t tickcounter_ms_t;` which must be 32 bits but depending on platform may or may not be 64 bits.

**Comment by jebrando** [comment]
Thanks for the issue.  The option is correctly documented here: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Iothub_sdk_options.md

The code shall be updated soon.

Thank you.
