### ISSUE TITLE
LWM2M Support in the SDK

### ISSUE THREAD

**Issue by funmbi-gd** [Azure/azure-iot-sdk-c#1801]
Hi All,

I've done some searching on if the Azure SDK supports the LWM2M (Lightweight Machine to Machine) protocol but cannot get a definitive answer. I would like to ask if there is a means in which LWM2M can be implemented between Azure IoT Hub and a device? If not, is there a plan to support in the future?

Thank you.

**Comment by danewalton** [comment]
Our SDK here does not natively support it. We do have a new release (6.1.3) for Azure RTOS which adds LWM2M to their networking stack. See here for details:
https://github.com/azure-rtos/netxduo/releases

There also is a bridge sample [here which uses LWM2M](https://github.com/Azure-Samples/iot-hub-lwm2m-bridge). Feel free to check that out and see if it helps!

**Comment by danewalton** [comment]
This issue seems resolved so going to close it for now. Please let us know if you have any more questions!
