### ISSUE TITLE
C SDK append Serializer Buffer

### ISSUE THREAD

**Issue by pucki91** [Azure/azure-iot-sdk-c#1803]
Hi Team,

is there any possibility or Idea how to append an existing Buffer by using the Serializer Method?
Background: I have individual update rates of the sensor signals and want to send only changed values of those signals. 
It would be appreciated just if the sensor value has changed to append to the buffer and finally send all the send signals in a fix time interval.
Eg. 
time1: SERIALIZE(&destination, &destinationSize, thermostat->Temperature)
time1+100ms APPEND SERIALIZER(thermostat->Humidity)
t2 (every x seconds) -> SendEventAssync

Thanks a lot

**Comment by danewalton** [comment]
Hey @pucki91 are you able to append the same data to a buffer and send that as one telemetry message?

**Comment by pucki91** [comment]
Hi @danewalton, that's exactly what I finally did, but if you have declared multiple structures you have to take care yourself to append to the proper Model

**Comment by danewalton** [comment]
Gotcha yea for simplicity I would recommend appending it to the same telemetry and parsing it out on the receiving end. I'm going to mark this as closed for now but if you have any follow up questions feel free to leave them here and I can reopen.
Thanks a bunch!

**Comment by az-iot-builder-01** [comment]
@danewalton, @pucki91, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
