### ISSUE TITLE
Persistant Buffering after Program Exit

### ISSUE THREAD

**Issue by pucki91** [Azure/azure-iot-sdk-c#1804]
Hi,

I have read about the Reliability features and wonder what will happen if the Program exits while Connection is lost?
Is there any file based mechanism to keep sent data in persistant buffer?

Eg. 
Send Data -> OK
Send Data -> Connection Lost -> IOTSdk keeps buffer/updates queue
Send Data -> Program Exit -> What happens with the queue? 

Or is there any possibility to save the queue when program is exit and restore the queue after restart?

Thanks

**Comment by danewalton** [comment]
Hi @pucki91 just to understand correctly. So on program exit (termination), you are curious if the queue could be saved and restored once the program is restarted?

Any queue that is created in the program is dynamically allocated within the process. Once the program terminates, the memory used by the program is released. If you wanted to store unprocessed messages between executions, you would have to store messages to persistent storage and re-up the messages from there. Keep in mind, the queue in dynamic memory would have to be kept up to date with the persistent storage one. Making sure those are up to date relative to each other could be a large task.

**Comment by pucki91** [comment]
Hi @danewalton,

thanks for your response, this is actually the Use Case you have described.
Is there any other possibility you have in mind? 

Actually another opportunity I have figured out is to use the Message Callback to react on TimeOut and store the un-sent data 
within a persistent storage. 

It seems if the Callback is triggered with != OK, the Message is not anymore kept in the queue, right?

I have played a litte round with all the possibilities of settings the SDK supports 
IoTHubClient_LL_SetOption(iotHubClientHandle_ll, OPTION_KEEP_ALIVE,&messagetimeout);
IoTHubClient_LL_SetRetryPolicy(iotHubClientHandle_ll,IOTHUB_CLIENT_RETRY_INTERVAL,&messageintervall); but even this
does not react than expected using the MQTT protocol.

At least what I want to achieve is to keep the queue for hours (as long as no internet connection is available) and by Program exit to use the Message callback to save all the unsent Messages in a persistent buffer.

Any ideas?

Thanks

**Comment by ericwol-msft** [comment]
_>>Actually another opportunity I have figured out is to use the Message Callback to react on TimeOut and store the un-sent data
within a persistent storage._

Correct, that is how it would be implemented.

_>>It seems if the Callback is triggered with != OK, the Message is not anymore kept in the queue, right?_

Also correct.

**Comment by pucki91** [comment]
@ericwol-msft thanks for the quick feedback, any comments to 
IoTHubClient_LL_SetOption(iotHubClientHandle_ll, OPTION_KEEP_ALIVE,&messagetimeout);
IoTHubClient_LL_SetRetryPolicy(iotHubClientHandle_ll,IOTHUB_CLIENT_RETRY_INTERVAL,&messageintervall) ?

Nevertheless what i configure there seems to be a hard limit of 120s... is there anything in addition I would need to consider?
(I am using MQTT)

Thanks a lot

**Comment by ericwol-msft** [comment]
The message queue is here https://github.com/Azure/azure-iot-sdk-c/blob/8f6b4823b7f6652578016ae3b19af871204beafb/iothub_client/src/message_queue.c

I believe the option to set this is SAVED_OPTION_MAX_ENQUEUE_TIME_SECS

**Comment by pucki91** [comment]
Hi Eric, 
ok, that's actually bad - I wouldn't mind if I have to switch to AMQP - do you see here any possibility to adjust?
2 mins persisting the queue is not really much...

**Comment by ericwol-msft** [comment]
The primary purpose of this is to handle disconnects due to access token expiring and temporary loss of network conductivity.

**Comment by pucki91** [comment]
Hi Eric, thanks for the feedback, things gone clear now :)
One last question implementing to save the queue - when the Callback function is called - is there any hint how big the queue is?
E.g. if the CALLBACK_BECAUSE_DESTROY is called and I want to save it to a file, how to know how many Callbacks will follow to keep the file open, and not to close and reopen it immediately if the queue has a lot of entries?

Thanks,

**Comment by ericwol-msft** [comment]
There is no queue size and is purely based off of time in the queue. You will need to track that when ever you send a message and align it up with the callback.

**Comment by danewalton** [comment]
This issue seems resolved so going to close it for now. Please let us know if you have any more questions!
