### ISSUE TITLE
Running unit tests of azure-c-shared-utility failed with "Cannot open include file: 'CppUnitTest.h'"

### ISSUE THREAD

**Issue by lirenhe** [Azure/azure-iot-sdk-c#181]
OS: Windows 10

 Description of the issue:

I follow the guide in https://github.com/Azure/azure-c-shared-utility/blob/e66121061623d2ecf0167c935b3fc036418295dc/README.md to setup all unit test for azure-c-shared-utility.
However, when I tried to open and build generated 'azure_c_shared_utility.sln' in VS
, I got the following errors(total 214 errors )

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'CppUnitTest.h': No such file or directory	refcount_ut_testsonly_lib	E:\azure-iot-sdk-c\c-utility\testtools\testrunner\inc\testrunnerswitcher.h	86	

....

It seems the project does not include the lib and header file for vs unit tests.
I could fix it by adding  '$(VCInstallDir)UnitTest\include;'  '$(VCInstallDir)UnitTest\lib;'
But that is a huge effort as there are hundreds of projects in the sln.

Is there any plan/workaround for this problem?

**Comment by ewertons** [comment]
Hi @lirenhe ,
have you tried building from the Visual Studio command prompt? That is a requirement.

**Comment by lirenhe** [comment]
hi @ewertons ,
I follow the guide in https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md.
I do it step by step and when I run:

cmake -G "Visual Studio 14 2015" -Drun_unittests=ON ..
cmake --build . -- /m /p:Configuration=Debug

I still got a lot of file not found error:


     "E:\azure-iot-sdk-c\cmake\ALL_BUILD.vcxproj" (default target) (1) ->
     "E:\azure-iot-sdk-c\cmake\c-utility\tests\x509_schannel_ut\x509_schannel_ut_dll.vcxproj" (default target) (409)
     ->
     "E:\azure-iot-sdk-c\cmake\c-utility\tests\x509_schannel_ut\x509_schannel_ut_testsonly_lib.vcxproj" (default targ
     et) (410) ->
       E:\azure-iot-sdk-c\c-utility\testtools\testrunner\inc\testrunnerswitcher.h(86): fatal error C1083: Cannot open
      include file: 'CppUnitTest.h': No such file or directory [E:\azure-iot-sdk-c\cmake\c-utility\tests\x509_schanne
     l_ut\x509_schannel_ut_testsonly_lib.vcxproj]

**Comment by ewertons** [comment]
Hi @lirenhe ,
thanks for the details.

I followed the same steps in my machine, and the build succeeded (you can disregard that warning at the end):

![capture0](https://user-images.githubusercontent.com/12401690/28935607-ff2948da-7839-11e7-8867-9e9e39e6f9e1.PNG)


You are having a failure related to your build not finding CppUnitTests.h.
If you run the search below do you get the same output?

![capture](https://user-images.githubusercontent.com/12401690/28935632-0f0b24f8-783a-11e7-9d39-eac57d6bdbcb.PNG)

**Comment by lirenhe** [comment]
Thanks @ewertons 
I think I know the root cause: all commands must be run in VS2005 command prompt.
If I start a normal cmd window to run those commands, I would get file CppUnitTests.h not found error.
Seems https://github.com/Azure/azure-c-shared-utility/blob/master/README.md does not mention this part.

**Comment by ewertons** [comment]
Hi @lirenhe , thanks for confirming.

C-Shared utility, despite being a public repo, is not intended to be used by itself. Our goal is to keep the documentation within azure-iot-sdk-c repo.

As you mentioned, you correctly looked for instructions at https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md.

If you go to [Build the C SDK](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#build-the-c-sdk) you will see the requirement written:
`Open a "Developer Command Prompt for VS2015".`

So the documentation is correct.
Please let us know if we can help in any other way.

Thanks,
Azure IoT Team.
