### ISSUE TITLE
Cross compile sample code error SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by Howhowshow** [Azure/azure-iot-sdk-c#1811]
Dear All :
I followed (https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md) 
guideline and tried to cross compile azure-iot-sdk-c SDK sample code (iothub_convenience_sample)by TI toolchain for sending telemetry to IOT Hub.
When I put the sample code application to the target device and executed it that got some errors.

**Description of the issue:**
SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Func:onOpenComplete Line:454 Error: failure opening connection to endpoint

**Host Machine OS :**
Ubuntu 14.04.7 i386 LTS
**Target :**
 TI AM335x toolchain (ti-processor-sdk-linux-am335x-evm-01.00.00.03)
Openssl version : 1.0.1m
openssl certificates location :  "/etc/ssl/certs/ca-certificates.crt"
openssl directory : "/usr/lib/ssl"

**SDK Version (Please Give Commit SHA if Manually Compiling)**
LTS_07_2020_Ref02 

**export TI_ROOT path** 
echo $TI_ROOT$ 
/home/johnny/ti-processor-sdk-linux-am335x-evm-01.00.00.03/linux-devkit/sysroots/cortexa8t2hf-vfp-neon-linux-gnueabi

### My toolchain-ti.cmake
```
INCLUDE(CMakeForceCompiler)
SET(CMAKE_SYSTEM_NAME Linux)     # this one is important
SET(CMAKE_SYSTEM_VERSION 1)     # this one not so much

# this is the location of the ARM toolchain targeting the TI
SET(CMAKE_C_COMPILER $ENV{TI_ROOT}/../i686-arago-linux/usr/bin/arm-linux-gnueabihf-gcc)

# this is the file system root of the target
SET(CMAKE_FIND_ROOT_PATH $ENV{TI_ROOT})

# set OpenSSL path
set(OPENSSL_ROOT_DIR $ENV{TI_ROOT})

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```
### Host build command
./build.sh --toolchain-file toolchain-ti.cmake -cl --sysroot=$TI_ROOT

### Console log of the issue:
```
Creating IoTHub handle
Sending message 1 to IoTHub
Message: {"temperature":23.134,"humidity":67.966,"scale":"Celsius"}
Error: Time:Tue Dec 29 07:11:35 2020 File:/home/johnny/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c 
Func:send_handshake_bytes Line:674 error:14090086:
SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Error: Time:Tue Dec 29 07:11:35 2020 File:/home/johnny/azure-iot-sdk-c/umqtt/src/mqtt_client.c 
Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
The device client has been disconnected
^C
am335x-evm:/home# time date
Tue Dec 29 07:11:40 UTC 2020
real    0m 0.00s
user    0m 0.00s
sys     0m 0.00s
am335x-evm:/home#
```

**Comment by Howhowshow** [comment]
Device certs expired.
Use the SDK trusted certs in the samples.

**Comment by az-iot-builder-01** [comment]
@Howhowshow, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
