### ISSUE TITLE
Azure IoT C SDK Support for Hololens UWP

### ISSUE THREAD

**Issue by SergioMasson** [Azure/azure-iot-sdk-c#1813]
Hi, 

I would like to know if is it possible to user the azure IoT C SDK in a C++ DirectX application built for Hololens 2 (UWP ARM64). I`ve been trying to get the uwp-arm version of the SDK using vcpkg:

vcpkg install azure-iot-sdk-c:arm-uwp

but it says it is not possible to build for this particular platform:

"Target 'UWP' not supported by azure-c-shared-utility!" 

Thank you very much for you time.
Sergio R. Z. Masson

**Comment by ewertons** [comment]
Hi @SergioMasson , the azure-iot-sdk-c solution can be compiled for c++, but we do not have direct support for UWP. 
For UWP I believe we have our offering in C# (https://github.com/azure/azure-iot-sdk-csharp).

**Comment by ewertons** [comment]
@SergioMasson ,
we will close this issue for now, but please feel free to reopen it if you would like follow up.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@SergioMasson, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
