### ISSUE TITLE
'segment fault' - after closing SSH session to a device via device streams #1767

### ISSUE THREAD

**Issue by gerhard67** [Azure/azure-iot-sdk-c#1817]
I saw you fix the issue of the segmentation fault, but only in the branch "DeviceStreaming" (see issue #1767). 

But if you look to the official documentation "[Quickstart: Enable SSH and RDP over an IoT Hub device stream by using a C proxy application (preview)](https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-device-streams-proxy-c#prepare-the-development-environment)" to test device streams, we should use the "public-preview" branch. 

Either the documentation is wrong or you need to merged the commit also to the public-preview branch

**Comment by ewertons** [comment]
The public-preview branch was just updated.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@gerhard67, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
