### ISSUE TITLE
Connection parameter for cc3200

### ISSUE THREAD

**Issue by MaHaXWS** [Azure/azure-iot-sdk-c#182]
Hi 
We are currently developing a device with the Azure Iot SDK C for the TI cc3200 Prozessor.

As OS we are using the RIOT-OS

SDK version used: (not sure)1.1.15

We tried to implement the mqtt_client_sample in our project.
For this reason we wrote the neseccary adapters for cc3200.

# Description of the issue:
We are trying to connect to the Azure IOT hub: 
- By debuging our tslio_cc3200 I only managed to get an unsecured connection to the IOT-HUB but do not manage to connect the cc3200 to the IOT hub using SSL/TLS secured connection.
- For this device I need to have a certificate for the secured connection, but I do not find the current working certificate.
- For an direkt connection without AzureIOTsdk I tried to implement the connection part from https://github.com/remixed123/IoT/blob/master/LaunchPads/CC3200_Azure/main.c 
But there there was the same problem!

After implementing an unsecured Connection the AzureIotSDK tried to send some MQTT Messages to the IotHub, but we do not get any answers! Acording to ISSUE https://github.com/Azure/azure-iot-sdk-c/issues/128 MQTT-Protocoll might not work but shouldn't there be any return Message?

# Code sample exhibiting the issue:
https://github.com/remixed123/IoT/blob/master/LaunchPads/CC3200_Azure/main.c

# Console log of the issue:
This is our main problem! We do not get any return messages

Help:
- Valid certificate
- Parameters for the Connection(secured (TLS/SSL)) or is unsecured Connection OK
- Is there any possibility to capture all messages directly in the IotHub
- What can we try?

**Comment by markrad** [comment]
Hi @MaHaXWS,

You should only require the root certificate which you should pass to the API using the "TrustedCerts" option. You can find this in /certs.c. Only use the first certificate in the list. The other two are not required. 

The Azure IoT Hub will only accept connections that are secured with SSL or TLS.

Texas Instruments have been successful connecting the CC3200 to the Azure IoT Hub. At this time they have not issued a pull request for their code modifications. 

I briefly reviewed the code you linked to above. I don't see any calls to the Azure IoT SDK in that code nor any reference to MQTT so I am not sure what it is trying to accomplish. I recommend that you first get one of the MQTT samples provided in the SDK working before you write anything more extensive.

_Mark Radbourne MSFT_

**Comment by MaHaXWS** [comment]
Thank you or the answer!

Yes I am looking for the root certificate is this the same like ms.der? I think cc3200 can not work with the certs.c file.

Sorry! In the example code, there is only the conection part which I am also in my tlsio_cc3200.c adapter!
So my questions are:
- Can I get a .der file which I can upload to the flash of my cc3200 device
- Is the SL_SO_SEC_METHOD_SSLv3_TLSV1_2 connection OK?
- is there any security mask necessary ( e.g. SL_SEC_MASK_SSL_RSA_WITH_RC4_128_SHA; ...)

Markus

**Comment by markrad** [comment]
If you are getting a certificate date verification error you should ensure that the date and time on your device are correct. If the date and time are outside the certificate's valid period you will see this error.

Yes the ms.der file is the der file format of the root certificate. The certs.c version is pem format.

_Mark Radbourne MSFT_

**Comment by MaHaXWS** [comment]
Thank You a lot! This Problem is solved!
