### ISSUE TITLE
iothubclientcore_ut.c has one incorrect buffer size for sprintf

### ISSUE THREAD

**Issue by fanzhe98** [Azure/azure-iot-sdk-c#1824]
one line 2732 of iothubclientcore_ut.c
There is one sprintf

```
char tmp_msg[64];	      
sprintf(tmp_msg, "IoTHubClientCore_SetDeviceMethodCallback failure in test %lu/%lu", (unsigned long)index, (unsigned long)count);
```
where the format content is well beyond the buffer size

**Comment by az-iot-builder-01** [comment]
@fanzhe98, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
