### ISSUE TITLE
pnp_simple_thermostat certificate verify failed for embedded device

### ISSUE THREAD

**Issue by eddylawsurgere** [Azure/azure-iot-sdk-c#1828]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Toolchain: ETK for Speeyway R420 RFID device.
Cross Compiled on Ubuntu 20 using:
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /home/etk/impinj_etk/arm-toolchain/bin/arm-none-linux-gnueabi-gcc
-- Check for working C compiler: /home/etk/impinj_etk/arm-toolchain/bin/arm-none-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/etk/impinj_etk/arm-toolchain/bin/arm-none-linux-gnueabi-g++
-- Check for working CXX compiler: /home/etk/impinj_etk/arm-toolchain/bin/arm-none-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IoT Client SDK Version = 1.3.9
-- Provisioning SDK Version = 1.3.9

**SDK Version (Please Give Commit SHA if Manually Compiling)**
Version 1.3.9

**Protocol**

MQTT

** Build & run instrunctions **
- Set flag prov_auth=ON, prov_use_tpm_simulator=OFF, use_edge_modules=OFF in ./build_all/linux/build.sh file and add these
- flags -Duse_sample_trusted_cert:BOOL=on -Duse_default_uuid:BOOL=on at the end of the line with "cmake $toolchainfile ..." in the build.sh file.
- Run the script file build.sh with toolchain file.
- In order to run the sample pnp_simple_themostat which is located at ../iothub_client/samples/pnp/ folder, set environmental variables such as  export IOTHUB_DEVICE_SECURITY_TYPE="DPS"
export IOTHUB_DEVICE_DPS_ID_SCOPE="?"
export IOTHUB_DEVICE_DPS_DEVICE_ID="?"
export IOTHUB_DEVICE_DPS_DEVICE_KEY="?"
export IOTHUB_DEVICE_DPS_ENDPOINT="global.azure-devices-provisioning.net"
- Run the pnp_simple_themostat app on the embedded device.

**Console Logs**

root@SpeedwayR-12-C8-A7:/cust/iot# ./pnp_simple_thermostat
Info: Initiating DPS client to retrieve IoT Hub connection information
Error: Time:Tue Jan 19 18:35:16 2021 File:/home/etk/Projects/lib_sources/iot-plug-and-play-bridge/pnpbridge/deps/azure-iot-sdk-c-pnp/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:674 error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Error: Time:Tue Jan 19 18:35:16 2021 File:/home/etk/Projects/lib_sources/iot-plug-and-play-bridge/pnpbridge/deps/azure-iot-sdk-c-pnp/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
Error: Time:Tue Jan 19 18:35:16 2021 File:/home/etk/Projects/lib_sources/iot-plug-and-play-bridge/pnpbridge/deps/azure-iot-sdk-c-pnp/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Tue Jan 19 18:35:16 2021 File:/home/etk/Projects/lib_sources/iot-plug-and-play-bridge/pnpbridge/deps/azure-iot-sdk-c-pnp/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:771 Failure retrieving data from the provisioning service
Error: Time:Tue Jan 19 18:35:16 2021 File:/home/etk/Projects/lib_sources/iot-plug-and-play-bridge/pnpbridge/deps/azure-iot-sdk-c-pnp/iothub_client/samples/pnp/common/pnp_dps_ll.c Func:provisioningRegisterCallback Line:59 DPS Provisioning callback called with error state 5
Error: Time:Tue Jan 19 18:35:17 2021 File:/home/etk/Projects/lib_sources/iot-plug-and-play-bridge/pnpbridge/deps/azure-iot-sdk-c-pnp/iothub_client/samples/pnp/common/pnp_dps_ll.c Func:PnP_CreateDeviceClientLLHandle_ViaDps Line:147 Error registering device for DPS
Error: Time:Tue Jan 19 18:35:17 2021 File:/home/etk/Projects/lib_sources/iot-plug-and-play-bridge/pnpbridge/deps/azure-iot-sdk-c-pnp/iothub_client/samples/pnp/pnp_simple_thermostat/pnp_simple_thermostat.c Func:CreateAndConfigureDeviceClientHandleForPnP Line:655 Failure creating IotHub client.  Hint: Check your connection string or DPS configuration
Error: Time:Tue Jan 19 18:35:17 2021 File:/home/etk/Projects/lib_sources/iot-plug-and-play-bridge/pnpbridge/deps/azure-iot-sdk-c-pnp/iothub_client/samples/pnp/pnp_simple_thermostat/pnp_simple_thermostat.c Func:main Line:733 Failed creating IotHub device client
root@SpeedwayR-12-C8-A7:/cust/iot#

**Comment by ericwol-msft** [comment]
Looks like the DPS TLS cert can't be verified against the root trust. Make sure 'use_baltimore_cert' camke flag is enabled

**Comment by eddylawsurgere** [comment]
Thanks @ericwol-msft.
I modified the file pnp_dps_ll.c to fix the issue:
1) add these include statements for certs:
> #ifdef SET_TRUSTED_CERT_IN_SAMPLES
> //Eddy
> #include "azure_c_shared_utility/shared_util_options.h"
> #include "certs.h"
> #endif

2) add this code in function  PnP_CreateDeviceClientLLHandle_ViaDps:
> #ifdef SET_TRUSTED_CERT_IN_SAMPLES
>     //Eddy
>     // Setting the Trusted Certificate. This is only necessary on systems without
>     // built in certificate stores.
>     else if ((provDeviceResult = Prov_Device_LL_SetOption(provDeviceHandle, OPTION_TRUSTED_CERT, certificates)) != PROV_DEVICE_RESULT_OK)
>     {    
>         LogError("Setting provisioning tracing on failed, error=%d", provDeviceResult);
>         result = false;
>     }
> #endif
 
Thanks

**Comment by az-iot-builder-01** [comment]
@ericwol-msft, @eddylawsurgere, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
