### ISSUE TITLE
HTTP fails with wolfSSL

### ISSUE THREAD

**Issue by momuno** [Azure/azure-iot-sdk-c#1829]
Ubuntu 20.04

Release LTS_07_2020

HTTP, wolfSSL

Running iothub_ll_telemetry sample with original IoTHub or public preview IoTHub, with HTTP and wolfSSL.  The sample fails.  All other protocols (AMQP, AMQP/WS, MQTT, MQTT/WS work.)

**Console Logs**

Creating IoTHub Device handle
Sending message 1 to IoTHub
Error: Time:Tue Jan 19 21:17:41 2021 File:/mnt/c/Repos/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:ssl_ctx_callback Line:293 failure in adding trusted certificate to client
Error: Time:Tue Jan 19 21:17:41 2021 File:/mnt/c/Repos/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:648 curl_easy_perform() failed: Problem with the local SSL certificate

Error: Time:Tue Jan 19 21:17:41 2021 File:/mnt/c/Repos/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:650 (result = HTTPAPI_OPEN_REQUEST_FAILED (4))
Error: Time:Tue Jan 19 21:17:41 2021 File:/mnt/c/Repos/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:526 unable to recover sending to a working state
Error: Time:Tue Jan 19 21:17:41 2021 File:/mnt/c/Repos/azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1806 unable to HTTPAPIEX_SAS_ExecuteRequest
Confirmation callback received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_ERROR

**Comment by hihigupt** [comment]
I tried following steps and I was able to see HTTP working with wolfssl current master and curl.

Please follow following steps to make it work.

git clone https://github.com/wolfSSL/wolfssl.git
./autogen.sh
./configure CFLAGS="-DSHOW_SECRETS -DWOLFSSL_SSLKEYLOGFILE -w" --enable-postauth --enable-tls13 --enable-libwebsockets --enable-harden --enable-aesni --enable-psk --enable-sni --enable-alpn --enable-trustedca --enable-truncatedhmac --enable-stunnel --enable-certservice --enable-enckeys --enable-debug --enable-secure-renegotiation
make
make install

git clone https://github.com/curl/curl.git
cd curl
autoreconf -fi
./configure --with-wolfssl=/usr/local --without-ssl --without-zlib --enable-debug
make
make install

Then build the sample of telemetry,

git clone https://github.com/Azure/azure-iot-sdk-c.git
mkdir build_wolfssl
cd wolfssl
cmake -DCMAKE_BUILD_TYPE=Debug -Duse_openssl=OFF -Duse_wolfssl=ON  ..

**Comment by momuno** [comment]
I was unable to get it working with the above alone.  I also needed to install `libcurl4-openssl-dev` it seems.  I am going to resetup my environment and try this all again to confirm.  If we do need the above curl installed, not just via `sudo apt-get install curl`, then we will need to update documentation.  

Reopening for now.

**Comment by hihigupt** [comment]
Did you install openssl support for wolf ssl?

**Comment by momuno** [comment]
I tested and the only difference between the instructions for Linux environment setup [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#set-up-a-linux-development-environment) and what actually works is the extra curl installation pointing to the wolfSSL installed library:

using `sudo apt-get install curl` I have version 
```
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 b
```

using
```
git clone https://github.com/curl/curl.git
cd curl
./configure --with-wolfssl=/usr/local
make
make install
```
I have version 
```
curl 7.75.1-DEV (x86_64-pc-linux-gnu) libcurl/7.75.1-DEV wolfSSL/4.6.0 (OpenSSL/1.1.1f)
```

I will update the documentation to close this issue.

**Comment by momuno** [comment]
What is annoying though is that now whenever I build, I get the following for every build line:
```
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
```
