### ISSUE TITLE
Cipher suite option for DPS

### ISSUE THREAD

**Issue by motoxyz** [Azure/azure-iot-sdk-c#1843]
Found out that there are no option to set cipher suite for DPS in provisioning_client src code.

While for iothub_client, I tried the option called "OPTION_OPENSSL_CIPHER_SUITE" and successfully set the hardcoded cipher suite without any issue.
IoTHubDeviceClient_LL_SetOption(iotHubClientHandle, OPTION_OPENSSL_CIPHER_SUITE, "hardcodedciphersuite")

Is there an option or does it have a way to set cipher suite for DPS? Thanks

**Comment by danewalton** [comment]
Hi @motoxyz,
The option belongs to shared utility [here](https://github.com/Azure/azure-c-shared-utility/blob/7e60c583096f5a73bae05031c6a97cf25e4fd1c2/inc/azure_c_shared_utility/shared_util_options.h#L29) where it is then set [here](https://github.com/Azure/azure-c-shared-utility/blob/7e60c583096f5a73bae05031c6a97cf25e4fd1c2/adapters/tlsio_openssl.c#L1649-L1668) in `tlsio_openssl.c`.

What specific issue are you having with this?

**Comment by motoxyz** [comment]
When added this OPTION_OPENSSL_CIPHER_SUITE set option,
Prov_Device_LL_SetOption(m_DPSHandle, OPTION_OPENSSL_CIPHER_SUITE, hardcodedciphersuite)

the application failed with error below:
Error: Time:Wed Feb  3 13:47:04 2021 File:/ssp_azure_iot_sdk_c/azure-iot-sdk-c-LTS_07_2020_Ref01/provisioning_client/src/prov_device_ll_client.c Func:Prov_Device_LL_SetOption Line:1332 Failure in prov transport set option

**Comment by danewalton** [comment]
Interesting I just tried it and the option seems to be setting correctly.
Couple questions:
1) Just want to double check that you are compiling with openSSL on. This option won't resolve if you aren't.
2) Are you able to follow the stack down to see where the option is specifically not getting set? Essentially where is the error originally returned?

**Comment by motoxyz** [comment]
For question 1:
Ya, compiled with openssl on.

For question 2:
If removed the OPTION_OPENSSL_CIPHER_SUITE, the application able to connect to DPS without any error.

In provisioning_client/src/prov_device_ll_client.c, noticed that there are no OPTION_OPENSSL_CIPHER_SUITE which I think is the root cause for the error.

![image](https://user-images.githubusercontent.com/74048421/106782838-987dd900-6685-11eb-98e7-361d4381760a.png)

**Comment by danewalton** [comment]
In the picture you posted, the call then goes to the `else` and the `->prov_transport_set_option()`.
It then makes its way through the mqtt layer and then down to the TLS where it is then set [here](https://github.com/Azure/azure-c-shared-utility/blob/7e60c583096f5a73bae05031c6a97cf25e4fd1c2/adapters/tlsio_openssl.c#L1649-L1668). So if that fails then it bubbles up to the error you're seeing.

Are you able to follow that call down and see where it goes and where it really returns the error?

**Comment by motoxyz** [comment]
When tried to change to MQTT protocol, there are no issue to set below cipher suite option.
Prov_Device_LL_SetOption(m_DPSHandle, OPTION_OPENSSL_CIPHER_SUITE, hardcodedciphersuite)

However, if change to HTTP protocol, the error is happening.

After trace provision code for HTTP, noticed that **HTTP_CLIENT_OK** is returned from **uhttp_client_set_option** function.
And eventually **prov_transport_set_option** function return 1 (which is enum for **HTTP_CLIENT_OK**) which will lead to result = PROV_DEVICE_RESULT_ERROR;


https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/src/prov_device_ll_client.c#L1343
![image](https://user-images.githubusercontent.com/74048421/107345477-8f19c400-6afe-11eb-814d-0dcf2d47909d.png)


https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/src/prov_transport_http_client.c#L1234
![image](https://user-images.githubusercontent.com/74048421/107345381-74474f80-6afe-11eb-95b0-cdb1949e53a7.png)


https://github.com/Azure/azure-uhttp-c/blob/85c426c972ad52b27bb4820c6c43a56b1ef48753/src/uhttp.c#L1513
![image](https://user-images.githubusercontent.com/74048421/107455346-a5209680-6b89-11eb-840c-baa8186ade88.png)

**Comment by danewalton** [comment]
Ahhhhhh I see yes yes I was just able to recreate this. Okay let me see about a fix thanks for pointing this out!

**Comment by CCSrl** [comment]
Hi danewalton,
Is it possible caused by the MU_DEFINE_ENUM in uhttp.h?
![image](https://user-images.githubusercontent.com/78889420/107596806-d1a0e500-6c53-11eb-929b-7952336b6dfd.png)

**Comment by danewalton** [comment]
Yes the update I made would fix this since it changes the base value from `1` to `0`. But as @momuno pointed out we should instead be checking an `HTTP_CLIENT_RESULT` and changing it to the proper `int`.
I have a new PR here:
https://github.com/Azure/azure-iot-sdk-c/pull/1857

**Comment by CCSrl** [comment]
Hi danewalton,
May i know which type is the Tag for this update?

**Comment by danewalton** [comment]
Do you mean Git tag?

**Comment by CCSrl** [comment]
Hi @danewalton,
For this update, do it require to create whole azure to pick up? Can you show me how to get this latest update?

**Comment by momuno** [comment]
Hi @CCSrl.  Our most recent LTS release is LTS_01_2021_Ref01 found at https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_01_2021_Ref01.  In general, I recommend using that release since it includes other fixes and updates.

However, since Dane's fix went in after this most recent release, his fix will be in the following release planned for this July.  Likely it will be LTS_07_2021_Ref01.
