### ISSUE TITLE
/provisioning_service_client/src/provisioning_service_client.c Func:rest_call Line:466 HTTP error

### ISSUE THREAD

**Issue by PradeepKiruvale** [Azure/azure-iot-sdk-c#1844]
I have updated all the defaults with my certs and connection string, device id , registration id.

When I run I am getting below error

Starting Individual Enrollment sample...
Connecting to the Provisioning Service...
after platform init Connecting to the Provisioning Service...
Creating an Individual Enrollment structure...
Creating an Individual Enrollment on the Provisioning Service...
PUT /enrollments/dev01?api-version=2018-04-01 HTTP/1.1
UserAgent: iothub_dps_prov_client/1.0
Accept: application/json
Content-Type: application/json; charset=utf-8
Authorization: SharedAccessSignature sr=Dpshub123.azure-devices.net&sig=hJS%2bAxxatkGhOKs7NulowDbPL9uGUFZ6codbEl%2bc8Is%3d&se=1612197910&skn=iothubowner
Host: Dpshub123.azure-devices.net:443
content-length: 2812

len: 2812
{"capabilities":{"iotEdge":false},"registrationId":"dev01","deviceId":"dev01","attestation":{"type":"x509","x509":{"clientCertificates":{"primary":{"certificate":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZlekNDQTJPZ0F3SUJBZ0lCQXpBTkJna3Foa2lHOXcwQkFRc0ZBREFxTVNnd0pnWURWUVFEREI5QmVuVnkKWlNCSmIxUWdTSFZpSUVOQklFTmxjblFnVkdWemRDQlBibXg1TUI0WERUSXhNREl3TVRFMU5EQXdPRm9YRFRJeApNRE13TXpFMU5EQXdPRm93RURFT01Bd0dBMVVFQXd3RlpHVjJNREV3Z2dJaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUNEd0F3Z2dJS0FvSUNBUUNsNEJBaHlZMi9lTCtXSU96eml3Y1pHM0VGby9maTRDTi9aUVMyWlVHUTZHclYKdURoYVQ3bXpCTmNXdis3L2FhQ2RLcEt2UTJpaTh6NzFGRWlTWkxGZ2ZoN0JCbVYxbGpqOVNBaDd3UGJPdUo2RQo0M0ZrczE3aUFuQ0tWNHhuTjVQRFZ0eWZMaEo3VW1wNVYzRVhOSnF0SE1WaDA2RWYxWVFwQ2FMRk9qTkxWVm1tCjNUYUQyRitkcFR5enNyWlA3ZDY1Nmg1Vld6blJySkJoeVk1bjJldkloWTE0ZTg4WjMxdDFveWpJbHk2L1BUaVIKSVVLWFhucmk0QnUvbDVqZ2p0U05aS3JNRTlCSVpUUStIZ09Yd1hsNVY5bU1BSEswQlQvWG1RNk5uRnh4UzFxWQpIK1Y5WmwzNWh0T25NMHBjcmJ0Rm9kaU5oa0xReUVESXFvUUtPWmJORHlwQWY3Ri9jeGxjV05qOG1oV2UwZzExCmZvS1hlNUZFVUdjMy9KcUFZL3Q3eitKZmRpUVJ2KzR3aEszZkZiUVhyNXhSZktQS2tlOVdiQ0MzZDZ5dkRvQlcKRDBvSFNKTEp6STF2eFkxWEVkeGVmOHRGYWNlN21ZNDc1Y2xPZndQcE82L1Vad00wYU8vb0tZZ3pzUjR5cXBTNAp4YmE0blJNcGczSk5NaTdJWXdtRlR1ZGFNRWhnS3k3L0pCajdQdWJ6dmpoU3FuTGZvK3Y0WTdtcVBFMkh4Tk5QCnh0RTFCK1dVRDZsSzhKVUthWlRyV2VleGdHVjcwQUxGYkg4WG50cFVsaGpYaVg1NFdXRk1nU0R1SkNMZTlVcHIKVWVZb2NaY3lmM2plOHAzK29mM1NlMk5NYmxrRFlCU20vYmd2V2RDd3JKa3FuZVd1UW9veUJROHo2cG8rTndJRApBUUFCbzRIRk1JSENNQWtHQTFVZEV3UUNNQUF3RVFZSllJWklBWWI0UWdFQkJBUURBZ1dnTURNR0NXQ0dTQUdHCitFSUJEUVFtRmlSUGNHVnVVMU5NSUVkbGJtVnlZWFJsWkNCRGJHbGxiblFnUTJWeWRHbG1hV05oZEdVd0hRWUQKVlIwT0JCWUVGRkdKVVNRYk1udy9MQlFEQmJ2cHpwUjhvcmc1TUI4R0ExVWRJd1FZTUJhQUZNL2IvNUhhdHcvcwpXa09TQkhweENuU1VmWm1zTUE0R0ExVWREd0VCL3dRRUF3SUY0REFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNECkFnWUlLd1lCQlFVSEF3UXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBR2twN0tPOUNpamczSlMwc1BaakZOVmoKQVZncWlVcjBJT013M1pjWUExUlRGUWpkclZmVU9zKzV2dWtxNHM5TXN2ZGRqeGc4Q09HeWZrTE1DUEo4SWJKdwplMlZpL0FBczk2czAvcVNobEg4eFZFY0lkU0FIUm1OSTVwQURCM3JiS3dGa05pUEtzTWgyTFRnY25RaTF0dnBhCnJYWFZlMjREczl3V3JiaXZjczgvUFZLUlJJemxaWUhMMUR2bmdnZ1BSZURDM0lYdFVyWUprMCtMeDRkZDY4OE8KQVYzZis3Zkg4SE9mc1MzSTR5dk5ZeWV1TkZ3WW1mQkFwWmhBcDZRanpaV2N1dGl1QzZVejluaThHbGQzeGVPNwpJWUFOTU43S1h6VUVDTk1oaXFINUpnc1JBR3BaZjdma0dqVi9GUFVWOG9yeFdwWVM5N0xmV2kyd0JkaTdaV3U4CmkvUnBOQWJyaTNMekorWDcxaWVpdWhEalZnNlhaV1R1UE5TS2k1OTFWUmNOR3VjUXZab3dqL2NmakRPVG5xa24KbXRhdm82bnZTVkMwNXB3V2IvWDZ4VGJDL1doQUhoeHMwT3d3akZTaFdPVU5JdDlBVG9zWGc5T0FXc0ZQN3BwYQp3WllUODVZWVJkL0VlQlAwQU5hek51UkZpeHRueXpQSHUvTnZpMjdmWTZ6ajJLRjFKNjVmMEswbHZNZWFQeFQrClRwSkRSZUEvVHNtRVZaM0MzbDEvWm5mR0V2VlF3b1l3eFl4eFVFaXhNd2EvdEJGWHVaVVdub0ZxRi9DcXRLS1YKQWxqV3hwRVJFS1ppR1VSeFJQVm1lQ3lPbnJUMzZSNzF1YVJ6UXVVY3J0elhvY3R0UzBpSDZMYm1FeE9uZUI2Wgo2Ym9sbnBoNEJkZHZGZFBPN3lPTQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"}}}},"provisioningStatus":"enabled"}

HTTP Status: 404

Error: Time:Mon Feb  1 21:15:12 2021 File:/home/ubuntu/RND/edge/azure-iot-sdk-c/provisioning_service_client/src/provisioning_service_client.c Func:rest_call Line:466 HTTP error
Error: Time:Mon Feb  1 21:15:12 2021 File:/home/ubuntu/RND/edge/azure-iot-sdk-c/provisioning_service_client/src/provisioning_service_client.c Func:prov_sc_create_or_update_record Line:550 Rest call failed
Retrieving an Individual Enrollment from the Provisioning Service...
GET /enrollments/dev01?api-version=2018-04-01 HTTP/1.1
UserAgent: iothub_dps_prov_client/1.0
Accept: application/json
Content-Type: application/json; charset=utf-8
Authorization: SharedAccessSignature sr=Dpshub123.azure-devices.net&sig=v9LKAjS8pNMLkDL6fkzCMBuERmzQ2stj4R91ZSUdo1Q%3d&se=1612197912&skn=iothubowner
Host: Dpshub123.azure-devices.net:443
content-length: 0

HTTP Status: 404

Error: Time:Mon Feb  1 21:15:15 2021 File:/home/ubuntu/RND/edge/azure-iot-sdk-c/provisioning_service_client/src/provisioning_service_client.c Func:rest_call Line:466 HTTP error
Updated an Individual Enrollment structure
Segmentation fault (core dumped)

**Comment by hihigupt** [comment]
Based on your token it looks like you are using IotHub connection string (see your skn=iothub). Please use the connection string of dps that has registration permission. You can find it on portal under your DPS : Shared Access Policies -> provisioningserviceowner and then click on policy and you will get the connection string.

Note: your connection string should have : SharedAccessKeyName=<policy name>, for above policy example connection strin should have SharedAccessKeyName=provisioningserviceowner

Please let us know if you still hit the issue.

**Comment by hihigupt** [comment]
Please let us know if you still hit this issue.
