### ISSUE TITLE
Building unit test with functions not enabled

### ISSUE THREAD

**Issue by fanzhe98** [Azure/azure-iot-sdk-c#1845]
When building unit tests, all the function(amqp, http, mqtt) need to be enabled, otherwise the build will fail. For example, if using the option to disable the amqp and http,  and compile with run_unittests and use_mqtt enabled, the compilation will fail.

**Comment by ericwol-msft** [comment]
This is by design. There are no plans to refactor unit tests specific to platform permutations.
