### ISSUE TITLE
Disable check for CXX compiler ...

### ISSUE THREAD

**Issue by jamesiotech** [Azure/azure-iot-sdk-c#1865]
In process of porting the sdk for use on various linux distributions. Build seems dependent on g++ ... dont really want to install g++ just want to build sdk with gcc .... is there a way i can disable check for CXX compiler and any CXX related tests ?

If current CMakeLists.txt does not handle this would it be possible to add for future release .... ?

**Comment by ericwol-msft** [comment]
There is nothing in our cmake files that would enforce this. You can try settings the appropriate CMAKE_CXX_COMPILER_WORKS and CMAKE_C_COMPILER_WORKS flags for your specific environment. 

cmake -DCMAKE_CXX_COMPILER_WORKS=1 -DCMAKE_C_COMPILER_WORKS=1  ..

**Comment by jamesiotech** [comment]
If you do not specify any LANGUAGES when you call the cmake project function (https://github.com/Azure/azure-iot-sdk-c/blob/master/CMakeLists.txt#L5) by default C and CXX are enabled, see https://cmake.org/cmake/help/latest/command/project.html.

If this is a C sdk - instead of "project(azure_iot_sdks)" couldnt we have "project(azure_iot_sdks LANGUAGES C) in the top-level CMakeLists.txt ?

Thanks again.

**Comment by ericwol-msft** [comment]
That is because we also support applications written in C++ to use our SDK. This is our header definitions in the SDK

```
#ifdef __cplusplus
extern "C"
{
#else
#endif
```
