### ISSUE TITLE
Application believes network is lost, locks up

### ISSUE THREAD

**Issue by dangerousHobo** [Azure/azure-iot-sdk-c#1866]
I'm currently started seeing this error while trying to send telemetry:

```
Feb 18 16:46:09 cm1sd azure-telemetry[849]: W(1613666769): Connection Status: result=IOTHUB_CLIENT_CONNECTION_AUTHENTICATED reason=IOTHUB_CLIENT_CONNECTION_OK
Feb 18 16:46:10 cm1sd azure-telemetry[849]: W(1613666770): Connection Status: result=IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED reason=IOTHUB_CLIENT_CONNECTION_NO_NETWORK
Feb 18 16:46:11 cm1sd azure-telemetry[849]: W(1613666771): Connection Status: result=IOTHUB_CLIENT_CONNECTION_AUTHENTICATED reason=IOTHUB_CLIENT_CONNECTION_OK
Feb 18 16:46:11 cm1sd azure-telemetry[849]: W(1613666771): Connection Status: result=IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED reason=IOTHUB_CLIENT_CONNECTION_NO_NETWORK
Feb 18 16:46:12 cm1sd azure-telemetry[849]: W(1613666772): Connection Status: result=IOTHUB_CLIENT_CONNECTION_AUTHENTICATED reason=IOTHUB_CLIENT_CONNECTION_OK
Feb 18 16:46:12 cm1sd azure-telemetry[849]: W(1613666772): Connection Status: result=IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED reason=IOTHUB_CLIENT_CONNECTION_NO_NETWORK
Feb 18 16:46:13 cm1sd azure-telemetry[849]: W(1613666773): Connection Status: result=IOTHUB_CLIENT_CONNECTION_AUTHENTICATED reason=IOTHUB_CLIENT_CONNECTION_OK
Feb 18 16:46:13 cm1sd azure-telemetry[849]: W(1613666773): Connection Status: result=IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED reason=IOTHUB_CLIENT_CONNECTION_NO_NETWORK
Feb 18 16:46:14 cm1sd azure-telemetry[849]: W(1613666774): Connection Status: result=IOTHUB_CLIENT_CONNECTION_AUTHENTICATED reason=IOTHUB_CLIENT_CONNECTION_OK
Feb 18 16:46:15 cm1sd azure-telemetry[849]: W(1613666775): Connection Status: result=IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED reason=IOTHUB_CLIENT_CONNECTION_NO_NETWORK
```

I'm using the `IoTHubDeviceClient_LL` library and the LTS_01_2021_Ref01 release. These errors are from my callback function for `IoTHubDeviceClient_LL_SetConnectionStatusCallback`. After these messages are displayed for a few seconds the process then locks up. It's been working for months and has had no changes to the code so I'm trying to determine what's interfering with the communication.

The device is connected to the internet still. This is on Linux (custom), ARM7.

Looking for what I can dig further into in troubleshooting this error.

Thanks.

**Comment by dangerousHobo** [comment]
Believe I've found the issue. We recently added another application to handle the device-twin. It appears this connection is taking down the connection for the telemetry application. In my research it appears IoT Hub supports a single connection, so looks like I'll need to combine this two applications.

**Comment by danewalton** [comment]
Yes you can only have a single device connected with a given identity. That is likely the issue. I'm going to go ahead and close this but feel free to leave a comment if you need additional help.
