### ISSUE TITLE
IoTHub client status: 1, Reason: 4 

### ISSUE THREAD

**Issue by SURAJTHEGREAT** [Azure/azure-iot-sdk-c#1869]
Hi Team,

My gateway device has suddenly started throwing the below error codes

IoTHub client status: 1, Reason: 4 .

No network changes for a long time . Since from a week ago this error has started popping.

Can you please help on what is going wrong here ? what is the expectation?

**Comment by ericwol-msft** [comment]
The enum status values are defined here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-client-core-common-h

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now @SURAJTHEGREAT. Let us know if you would like this reopened
