### ISSUE TITLE
iterative sleep loop inside close_connection(...)

### ISSUE THREAD

**Issue by maxpeng** [Azure/azure-iot-sdk-c#187]
OS and version used: Non-RTOS, bare metal system
SDK version: IOTHUB_SDK_VERSION "1.1.20"

If I am correct, bare metal system is one of the supported environments of Azure IoT SDK for C, however in ```mqtt_client.c```, there is a iterative sleep loop inside ```close_connection(...)``` as follows, it is unfriendly for bare metal system:
```
static void close_connection(MQTT_CLIENT* mqtt_client)
{
    size_t close_complete = 0;
    (void)xio_close(mqtt_client->xioHandle, on_connection_closed, &close_complete);

    size_t counter = 0;
    do
    {
        xio_dowork(mqtt_client->xioHandle);
        counter++;
        ThreadAPI_Sleep(10);
    } while (close_complete == 0 && counter < MAX_CLOSE_RETRIES);
    mqtt_client->socketConnected = false;
    mqtt_client->clientConnected = false;
}
```
Could we change above iterative sleep loop by just calling ```xio_dowork(...)``` as follows?
```
static void close_connection(MQTT_CLIENT* mqtt_client)
{
    (void)xio_close(mqtt_client->xioHandle, on_connection_closed, &close_complete);

    xio_dowork(mqtt_client->xioHandle);

    mqtt_client->socketConnected = false;
    mqtt_client->clientConnected = false;
}
```

**Comment by ewertons** [comment]
Hi @maxpeng ,
are you getting a failure during compilation? Could you share the traces, just so we have a better look at the error?

**Comment by maxpeng** [comment]
Hi @ewertons,
Because my targeted platform is bare metal system, it is expensive to sleep for more than few milliseconds, because other tasks also need to do their work cooperatively in the single main thread.

For my test, I need to break the the iterative loop, otherwise the TCP close operation of lwip would behave abnormally, because lwip code didn't get called while iterative loop was executed.

**Comment by jebrando** [comment]
@maxpeng I will look at this and let you know when it's fixed.

**Comment by jebrando** [comment]
I added a callback to avoid the loop with the sleep
