### ISSUE TITLE
InitializeConnection Line:2364 mqtt_client timed out waiting for CONNACK

### ISSUE THREAD

**Issue by EI-viren-moradiya** [Azure/azure-iot-sdk-c#1871]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

STM32Cube Microcontroller OS
Toolchain: MDK-Lite Version 5.33.0.0
Cross compiled on Keil® Microcontroller Development Kit (MDK-ARM)
Board : STM32L496G Discovery
Internet : Cellular Interface (4G connectivity)

**SDK Version (Please Give Commit SHA if Manually Compiling)**

**azure-iot-sdk-c**
Branch lts_01_2019

**Protocol**
MQTT

**Description of the issue**

While attempting to do Azure IOT device connection using symmetric key getting **mqtt client timed** out error.
On doing back trace of failure, I have found that mqtt status is not getting update from **MQTT_CLIENT_STATUS_CONNECTING**
**MQTT_CLIENT_STATUS_CONNECTED** due to hand shake time out.

At start IoTHubClientCore_LL_DoWork get called and tcp socket connection is happening and then **on_underlying_io_bytes_received** function start to receive data.
After this tcp socket connection getting closed and then **mqtt_client_dowork** function keep running in loop and at last I am getting **InitializeConnection Line:2364 mqtt_client timed out waiting for CONNACK** error.

I have added my debug log to back trace the problem.

**Console Logs of the issue**

In Func: IoTHubClientCore_LL_CreateFromConnectionString line: 1267
In Func: initialize_iothub_client line: 765
In Func: IoTHubTransportMqtt_Create line: 49
In Func: IoTHubTransport_MQTT_Common_Create line: 2583
In Func: InitializeTransportHandleData line: 2459
In Func: mqtt_client_init line: 922
In Func: getIoTransportProvider line: 14
In Func: xio_create line: 21
In Func: tlsio_mbedtls_create line: 444
In Func: mbedtls_init line: 402
In Func: xio_setoption line: 180
In Func: tlsio_mbedtls_setoption line: 832
In Func: IoTHubClientCore_LL_SendReportedState line: 2374
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_connect line: 991
In Func: xio_open line: 79
In Func: tlsio_mbedtls_open line: 559
In Func: xio_open line: 79
In tcpsocketconnection_create
In tcpsocketconnection_connect
In tcpsocketconnection_set_blocking
In Func: on_underlying_io_open_complete line: 134
In Func: on_io_send line: 339
In Func: xio_send line: 139
In tcpsocketconnection_send
In Func: on_io_recv line: 257
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: xio_dowork line: 164
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_underlying_io_bytes_received line: 176
In tcpsocketconnection_receive
In Func: on_io_recv line: 257
In Func: on_io_send line: 339
In Func: xio_send line: 139
In tcpsocketconnection_send
In Func: xio_close line: 109
In tcpsocketconnection_close
In Func: indicate_open_complete line: 103
In Func: onOpenComplete line: 396
In Func: close_connection line: 80
In set MQTT_CLIENT_STATUS_CONNECTING
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
In Func: mqtt_client_dowork line: 1258
In Func: xio_dowork line: 164
In Func: tlsio_mbedtls_dowork line: 690
tls_io_instance->tlsio_state: 0
In Func: IoTHubClientCore_LL_DoWork line: 2034
In Func: IoTHubTransport_MQTT_Common_DoWork line: 3079
In Func: InitializeConnection line: 2292
In If transport_data->isDestroyCalled
Error: Time:Tue Feb 23 18:01:26 2021 File:../../../../../../Middlewares/Third_Party/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnectio Line:2364 mqtt_client timed out waiting for CONNACK
In Func: tlsio_mbedtls_retrieveoptions line: 962
In else line 968
In Func: tlsio_mbedtls_CloneOption line: 712
In Func: tlsio_mbedtls_CloneOption line: 712
In Func: xio_destroy line: 63
In Func: tlsio_mbedtls_destroy line: 518
In Func: mbedtls_uninit line: 381
In Func: xio_close line: 109
In Func: xio_destroy line: 63
In tcpsocketconnection_destroy

**Comment by ericwol-msft** [comment]
MQTT spec requires a [CONNACK ](https://docs.solace.com/MQTT-311-Prtl-Conformance-Spec/MQTT%20Control%20Packets.htm#_Toc430864897)from the [CONNECT ](https://docs.solace.com/MQTT-311-Prtl-Conformance-Spec/MQTT%20Control%20Packets.htm#_Toc430864892)message.
Your error message `mqtt_client timed out waiting for CONNACK.` implies there is a networking issue with the IoT Hub.

Although this looks like a networking issue, you can enable verbose SDK logs. By setting the log trace option.
```
bool traceOn = true;
IoTHubDeviceClient_SetOption(device_client, OPTION_LOG_TRACE, &traceOn);
```
