### ISSUE TITLE
vcpkg instructions do not result in a working sample

### ISSUE THREAD

**Issue by BillyONeal** [Azure/azure-iot-sdk-c#1872]
The instructions at https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#build-sample-application-using-vcpkg-to-build-the-sdk suggest using vcpkg to acquire the IoT SDK dependencies but don't actually hook vcpkg into the resulting sample, so some customers have reported that they have had difficulties getting samples working. ( example: https://twitter.com/oising/status/1364357979877875714 )

Perhaps the instructions should be changed to use ninja instead:

```
./path/to/wherever/you/put/vcpkg/vcpkg install azure-iot-sdk
cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=./path/to/wherever/you/put/vcpkg/scripts/buildsystems/vcpkg.cmake -S . -B buildtree
cmake --build buildtree
```

**Comment by ericwol-msft** [comment]
The vcpkg are only supported for the .sln that are checked in under the sample directory. For example [iothub_ll_telemetry_sample.sln](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/windows/iothub_ll_telemetry_sample.sln)

For .sln generated by cmake, does not use vcpkg  and will build the SDK along with the samples.

**Comment by BillyONeal** [comment]
> The vcpkg are only supported for the .sln that are checked in under the sample directory. For example [iothub_ll_telemetry_sample.sln](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/windows/iothub_ll_telemetry_sample.sln)

The documentation there suggests to use cmake, not a checked in .sln.

**Comment by ericwol-msft** [comment]
Updated the docs. Thanks.
