### ISSUE TITLE
UploadBlob Timeout is arbitrarily set to 242 seconds.

### ISSUE THREAD

**Issue by czyba** [Azure/azure-iot-sdk-c#188]
Hi Azure SDK Team,

I noticed that the uploadToBlob functionality has an arbitrarily set timeout for Debian Jessie and probably other linux with curl based systems. After investigating where the timeout came from I noticed that [httpapi_curl](https://github.com/Azure/azure-c-shared-utility/blob/bad7ead6cd73fe9e1d95ca0fe812a1e9b4e2a601/adapters/httpapi_curl.c#L124) Sets the timeout to an arbitrary 242s. 

However, I tried to upload a 20MB file over a mobile connection with a roughly 50kB/s upload. Thus I  require to have at least a timeout of 400s. 

Is there some way to achieve this?
Would it be possible to add a method which allows setting the timeout or disabling it altogether?

Kind Regards,
Christopher Czyba

**Comment by ewertons** [comment]
Hi @czyba ,

thanks for the question.

Take a look at [httpapi_curl.c:L643](
https://github.com/Azure/azure-c-shared-utility/blob/bad7ead6cd73fe9e1d95ca0fe812a1e9b4e2a601/adapters/httpapi_curl.c#L643), you will see that the timeout can be set passing OPTION_HTTP_TIMEOUT (azure_c_shared_utility/shared_util_options.h)

If you are using the IoTHubClient with **HTTP transport**, that can be set indirectly by calling:

unsigned int timeout = 400;
IoTHubClient_SetOption(iothubclienthandle, OPTION_HTTP_TIMEOUT, &timeout);

Could you give it a try and let us know if it addresses your need?

Thanks,
Azure IoT Team

**Comment by czyba** [comment]
HI @ewertons,

I am using the AMQP transport and the HTTP transport is unfortunately not an option. I will try your suggestion nonetheless.

If it doesn't work, I would suggest adding additional upload blob options, or making the HTTP options available even when using different transports.

Kind Regards,
Christopher Czyba

**Comment by ewertons** [comment]
You are absolutely correct.
I'll take that request in.

Please let me know if using HTTP transport works for you.

**Comment by czyba** [comment]
Hi @ewertons,

I tried to use the HTTP transport and ran into a couple of errors / problems. For my tests I used the upload_blob sample, which I modified appropriately. See attached [iothub_client_sample_upload_to_blob.c](https://github.com/Azure/azure-iot-sdk-c/files/1204034/iothub_client_sample_upload_to_blob.c.txt).

### logtrace

Setting the logtrace for the HTTP transport does not work and will result in an error:

```
czyba@X1:~/home/czyba/azure-iot-sdk-c> ./cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_upload_to_blob/iothub_client_sample_upload_to_blob
Starting the IoTHub client sample upload to blob...
Info: IoT Hub SDK for C, version 1.1.19
Error: Time:Mon Aug  7 08:22:38 2017 File:/home/czyba/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_CloneOption Line:952 unknown option logtrace
Error: Time:Mon Aug  7 08:22:38 2017 File:/home/czyba/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_SetOption Line:609 error code = HTTPAPIEX_INVALID_ARG
Error: Time:Mon Aug  7 08:22:38 2017 File:/home/czyba/azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:IoTHubTransportHttp_SetOption Line:2367 HTTPAPIEX_SetOption failed
Error: Time:Mon Aug  7 08:22:38 2017 File:/home/czyba/azure-iot-sdk-c/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_SetOption Line:1589 underlying transport failed, returned = IOTHUB_CLIENT_INVALID_ARG
```

Since the option is set in a multitude of samples, a lot of the samples would fail if you were to use the HTTP protocol.

### Setting the trusted certificate fails due to missing BIO although cert does already exist
See trace:
```
czyba@X1:~/home/czyba/azure-iot-sdk-c> ./cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_upload_to_blob/iothub_client_sample_upload_to_blob 
Starting the IoTHub client sample upload to blob...
Info: IoT Hub SDK for C, version 1.1.19
Error: Time:Mon Aug  7 08:26:01 2017 File:/home/ccz/home/czyba/azure-iot-sdk-c/c-utility/src/x509_openssl.c Func:log_ERR_get_error Line:21 failure in X509_STORE_add_cert
Error: Time:Mon Aug  7 08:26:01 2017 File:/home/ccz/home/czyba/azure-iot-sdk-c/c-utility/src/x509_openssl.c Func:log_ERR_get_error Line:28   [0] error:0906D06C:PEM routines:PEM_read_bio:no start line
Error: Time:Mon Aug  7 08:26:01 2017 File:/home/ccz/home/czyba/azure-iot-sdk-c/c-utility/src/x509_openssl.c Func:log_ERR_get_error Line:28   [1] error:0B07C065:x509 certificate routines:X509_STORE_add_cert:cert already in hash table
Error: Time:Mon Aug  7 08:26:01 2017 File:/home/ccz/home/czyba/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:ssl_ctx_callback Line:260 failure in x509_openssl_add_certificates
Error: Time:Mon Aug  7 08:26:01 2017 File:/home/ccz/home/czyba/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:563 curl_easy_perform() failed: Problem with the local SSL certificate

Error: Time:Mon Aug  7 08:26:01 2017 File:/home/ccz/home/czyba/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:565 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Mon Aug  7 08:26:01 2017 File:/home/ccz/home/czyba/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Mon Aug  7 08:26:01 2017 File:/home/ccz/home/czyba/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_step1and2 Line:268 unable to HTTPAPIEX_ExecuteRequest
Error: Time:Mon Aug  7 08:26:01 2017 File:/home/ccz/home/czyba/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_Impl Line:825 error in IoTHubClient_LL_UploadToBlob_step1
```

Apparently openssl returns two errors the BIO one and that the cert is already in the queue. In my opinion it should not return an error if the certificate is already in the store.

### Setting the option
When I comment out the two options, the program finally runs. It does not abort earlier anyways, although I set the timeout to 10 seconds.

So unfortunately the option did not work for me in the end.

**Comment by ewertons** [comment]
Hey, @czyba ,
sorry, unfortunately we were addressing some critical issues and couldn't root cause this issue earlier.

Indeed there is a bug in the code.
There is an option consumed on httpapi_curl to control the timeout, however the iothub_client_ll_uploadtoblob unit [doesn't pass it down](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothub_client_ll_uploadtoblob.c#L1090) when it receives it from iothub_ll_client.

**Comment by JetstreamRoySprowl** [comment]
The latest SDK master adds a new OPTION_BLOB_UPLOAD_TIMEOUT_SECS  option to handle this. Please re-open this issue or start a new one if you have any problems.

**Comment by tameraw** [comment]
@czyba thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
