### ISSUE TITLE
LTS-01-2021 not published to PPA?

### ISSUE THREAD

**Issue by alaendle** [Azure/azure-iot-sdk-c#1880]
As it seems the latest available LTS release hadn't made it to ppa:aziotsdklinux/ppa-azureiot.

The packages are mentioned in https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_01_2021_Ref01
```
azure-iot-sdk-c - 0.2.0.0-31xenial
azure-iot-sdk-c - 0.2.0.0-24bionic
```
but aren't available on https://launchpad.net/~aziotsdklinux/+archive/ubuntu/ppa-azureiot.

**Comment by ericwol-msft** [comment]
investigating

**Comment by ewertons** [comment]
The apt packages are now published.

Thanks,
Azure SDKs Team.
