### ISSUE TITLE
TLS version Restriction for DPS and Iot Hub connection

### ISSUE THREAD

**Issue by CCSrl** [Azure/azure-iot-sdk-c#1882]
I called Prov_Device_LL_SetOption(DPSHandle, OPTION_OPENSSL_CIPHER_SUITE, "hardcodedciphersuite") for DPS connection and IoTHubDeviceClient_LL_SetOption(iotHubClientHandle, OPTION_OPENSSL_CIPHER_SUITE, "hardcodedciphersuite") for Iot Hub connection.

Even the all the hardcoded Cipher Suites only contained TLS version 1.2 or 1.3, but the Wireshark showed supported_versions from TLS version 1.0 to TLS version 1.3.

![image](https://user-images.githubusercontent.com/78889420/109609534-6a959280-7b66-11eb-9647-074a7c6017b3.png)

Does it have a way to limit the TLS supported version for DPS and Iot Hub connection? Thanks

**Comment by ericwol-msft** [comment]
You can your hub to TLS 1.2 only. More info is available on the link below.

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-tls-support

**Comment by CCSrl** [comment]
Hi @ericwol-msft ,

Is it possible to limit the TLS version at Iotclient site?

**Comment by ericwol-msft** [comment]
Try using option OPTION_TLS_VERSION ("tls_version")

https://github.com/Azure/azure-c-shared-utility/search?q=OPTION_TLS_VERSION

**Comment by CCSrl** [comment]
Hi @ericwol-msft,

The tlsInstance->ssl_context is new in create_openssl_instance(TLS_IO_INSTANCE* tlsInstance).

**_IOT SDK Tag: azure-iot-sdk-c-LTS_07_2020_Ref01_**
https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/tlsio_openssl.c#L1063

However, there's no function like SSL_CTX_set_min_proto_version(SSL_CTX *ctx, int version) which able to limit the TLS version to certain range as shown as image above.
https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_set_max_proto_version.html

Is it possible to add in such function into create_openssl_instance(TLS_IO_INSTANCE* tlsInstance)?
https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/tlsio_openssl.c#L1038

**Comment by ericwol-msft** [comment]
I can add min version to the backlog, but there is no guarantee timeframe when we can get this done. 

Have you consider compiling OpenSSL without these protocols?
https://github.com/openssl/openssl/blob/master/INSTALL.md#no-protocol

**Comment by CCSrl** [comment]
We will compile Openssl without ssl_v3

**Comment by ericwol-msft** [comment]
Closing issue.

**Comment by CCSrl** [comment]
Hi @ericwill-msft ,
As mentioned before, there's no Openssl function like SSL_CTX_set_min_proto_version(SSL_CTX *ctx, int version) which able to limit the TLS version as shown as image below.
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_max_proto_version.html
![image](https://user-images.githubusercontent.com/78889420/113847827-6e9e7b00-97ca-11eb-96f1-005f02542365.png)


Is it possible to create a function in create_openssl_instance(TLS_IO_INSTANCE* tlsInstance) to enable to limit the version supported protocol according to the version set in tlsio_openssl_setoption?
https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/tlsio_openssl.c#L1038
https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/tlsio_openssl.c#L1606
