### ISSUE TITLE
How to build the cmake for Linux platform

### ISSUE THREAD

**Issue by Abhi2109** [Azure/azure-iot-sdk-c#1883]
Hi,
I would like to build my cmake for Linux , please let me know what all changes in command line while generating code for Linux via cmake i need to do?

**Comment by danewalton** [comment]
Hi @Abhi2109
CMake allows the building of our SDK to be practically OS agnostic. One Windows it generates Visual Studio projects and on Linux it generates make files. You should be able to use the CMake switches [here](https://github.com/Azure/azure-iot-sdk-c/blob/522197868d5e75ea2ad0f71b339daedf5302d3ba/CMakeLists.txt#L50-L84) to modify how it is built, but it shouldn't change Windows <--> Linux. Let us know if you have any specific questions about features or compile options.

**Comment by ericwol-msft** [comment]
detailed instruction is here:

https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#linux

**Comment by danewalton** [comment]
going to close this. please let us know if you would like it reopened.
