### ISSUE TITLE
IoTHubClient_UploadToBlobAsync blocks the whole iothub

### ISSUE THREAD

**Issue by czyba** [Azure/azure-iot-sdk-c#189]
Hello Azure SDK Team,

I have noticed that the method `IoTHubClient_UploadToBlobAsync` completely blocks any operation of the iothub. This results in messages not being sent in parallel with a potentially long lasting upload.

According to comment in [iothub_client.c source](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothub_client.c#L1760) this actually needn't be. Would it be possible to remove the lock and allow sends to be happen in parallel. It would also be possible to extent the method by using a "file upload" queue as well.

Otherwise I would recommend adjusting the documentation accordingly.

Kind Regards,
Christopher Czyba

**Comment by ewertons** [comment]
hi @czyba ,
thanks for your comment.

I checked the code and it locks only to start a new Thread, then unlocks right away.
I'm checking the rest of the code, but just to confirm: are you experiencing the block or you are concluding there is a block based on the function is written?

**Comment by czyba** [comment]
Hi @ewertons,

I noticed this issue because I actually experienced the block in a program. Afterwards I checked the code to find out why it actually occurs. As far as I can see it is roughly because of this:

1. As you said, `IoTHubClient_UploadToBlobAsync` only blocks in order to create the thread. And indeed, that does not seem to be the issue.
2. The thread however runs the `uploadingThread` function, which in turn calls `Lock(savedData->iotHubClientHandle->LockHandle)`. During the lock when the lock is being held `IoTHubClient_LL_UploadToBlob(savedData->iotHubClientHandle->IoTHubClientLLHandle, savedData->destinationFileName, savedData->source, savedData->size)` is called, which is a blocking call.
3. The `ScheduleWork_Thread` tries to lock the IoTHub before sending messages. Since the file upload still holds the lock for some time no message will be sent until the file upload is completed or aborted.

Furthermore since nearly all methods require to lock the IoTHub, so suddenly the async non-blocking calls and all other "immediate" calls will result in blocking operations. I have modified and attached the
[iothub_client_sample_upload_to_blob.c](https://github.com/Azure/azure-iot-sdk-c/files/1206998/iothub_client_sample_upload_to_blob_c.txt) sample such that it exhibits said behavior. In my sample I have used SetRetryPolicy for simplicity sake, but the issue occurs with nearly all functions.

This also results in the IoTHub not being destroyed, since the file upload is not interrupted. Thus it may happen that a program may not terminate immediately but just in a couple of seconds if a file upload is in progress. I hope this showcases my issues.

Kind Regards,
Christopher Czyba

**Comment by ewertons** [comment]
Hey @czyba ,
thanks, that makes complete sense. I'll bring this issue to the team and discuss about priority and planning.
I'll reply back once I have an update.

**Comment by ewertons** [comment]
@czyba ,

this issue is being tracked by our backlog, but was prioritized lower than other pressing issues and feature implementations.
We will provide another update as soon as we get to investigate it.

If you have any additional information or comments please feel free to share with us.

Thanks,
Azure IoT Team

**Comment by jspaith** [comment]
Thanks for calling to our attention.  I'm working on a fix exactly as you propose and adding some multi-simultaneous upload e2e tests while at it.

**Comment by jspaith** [comment]
Fixed.  95a498a6247c9dccf6a164e31f0d8fc0c52c2d1d

Thanks again for calling this to our attention and apologies in the delay in addressing this.
