### ISSUE TITLE
ImportError: dynamic module does not define init function (init_iothub_client) 

### ISSUE THREAD

**Issue by ramgopikrishna** [Azure/azure-iot-sdk-c#1891]
I have tried to build the iothub_client.so and when I am using that .so and I am not able to import iothub_client in python.
I am using the Linux(ubuntu 16), Even I have manually compiled and also compiled through the build.sh the result was same.
Could you please fix if it is a issue. I have enabled the dynamic ON in Cmakelist file before starting that.

**Comment by CIPop** [comment]
@ramgopikrishna I don't think we've designed or tested the SDK to be imported in Python. 
Instead, I recommend using our Azure IoT SDK for Python from: https://github.com/Azure/azure-iot-sdk-python. 

Please reopen this issue if that won't work for your project adding a bit more details on why you need to use the C-SDK from Python.
