### ISSUE TITLE
 lts_07_2019 still supported? - especially with regard to upload to blob -

### ISSUE THREAD

**Issue by mucar-bmk** [Azure/azure-iot-sdk-c#1896]
Hello, 

first question: 
Is the lts-version 07-2019 still supported? We didnt notice any new releases for this lts-version. 
Are there certain issues that need to be considered when updating to the latest version?

second question:
We are currently facing the issue, that IoTHubDeviceClient_LL_UploadMultipleBlocksToBlob is not working properly: 

First Issue:
If the Upload gets interrupted by some reason (network drop or restart of the device) we are not able to resume the upload. If we try to restart the upload, the cloud respons with 403. (see issue #761)

Second Issue:
If an Upload is finished, we receive 400 from the cloud. (see issue#757)

Are these two Problems have been worked on in newer versions? 

thanks!

**Comment by ericwol-msft** [comment]
That LTS is no longer supported ([link](https://github.com/Azure/azure-iot-sdk-c#schedule1)) There should be no breaking changes between your version and the last LTS release.

There has been no changes wrt to fileupload and your issues would be external to the SDK. How long is your upload? Probably you SAS token life time has expired. I believe it's one hour, but you can look at the SAS 'se' field to determine when it expires.

**Comment by mucar-bmk** [comment]
Hello @ericwill-msft,

I could also notice that the upload worked again after a software restart. So must be any data on the sdk-side (especially with regard to the blob-upload functions) be reseted properly before (re-)starting the file upload?

how does the cloud recognize that a upload has ended ? And can I explicitly notify the cloud that the upload has been finished?

**Comment by ericwol-msft** [comment]
> how does the cloud recognize that a upload has ended ? And can I explicitly notify the cloud that the upload has been finished?

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload#notify-iot-hub-of-a-completed-file-upload

**Comment by ericwol-msft** [comment]
Closing this issue. Please ask to reopen it if your and any further questions.
