### ISSUE TITLE
Error while using nodemcu 

### ISSUE THREAD

**Issue by amazingashis** [Azure/azure-iot-sdk-c#1899]
c:/users/user/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\AzureIoTHub\iothubtransport_mqtt_common.c.o: in function `setMqttMessagePropertyIfPossible':
C:\Users\User\OneDrive\Documents\Arduino\libraries\AzureIoTHub\src/iothubtransport_mqtt_common.c:1417: undefined reference to `mqtt_client_clear_xio'
c:/users/user/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\AzureIoTHub\iothubtransport_mqtt_common.c.o: in function `DestroyXioTransport':
C:\Users\User\OneDrive\Documents\Arduino\libraries\AzureIoTHub\src/iothubtransport_mqtt_common.c:1427: undefined reference to `mqtt_client_clear_xio'
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by danewalton** [comment]
can I ask what your process is building the SDK?

**Comment by amazingashis** [comment]
> can I ask what your process is building the SDK?

I am currently using Arduino ide for board ESP8266.

**Comment by danewalton** [comment]
Do you know what version of the libraries you are using?
https://www.arduinolibraries.info/authors/azure#:~:text=Libraries%20%20%20AzureIoTHub%20%20%20Azure%20IoT,C%20shared%20utility%20library%20for%20Ardui%20...

**Comment by amazingashis** [comment]
I have used following libraries.

AzureIoTHub 
AzureIoTProtocol
AzureIoTProtocol_MQTT

**Comment by danewalton** [comment]
hmmm that function was added somewhat recently so is it possible that you have older versions of some libraries and newer versions of others? Can you try reintegrating the newest of all the libraries?

**Comment by danewalton** [comment]
pinging here. I'll go ahead and close otherwise
