### ISSUE TITLE
Memory leak about calling mallocAndStrcpy_s

### ISSUE THREAD

**Issue by maxpeng** [Azure/azure-iot-sdk-c#190]
Memory leak about calling mallocAndStrcpy_s

OS and version used: Non-RTOS, bare metal system
SDK version: IOTHUB_SDK_VERSION "1.1.20"

At "mqtt_client.c" #450:
```
    if (result == 0 && mqttOptions->willMessage != NULL)
    {
        if (mallocAndStrcpy_s(&mqtt_client->mqttOptions.willMessage, mqttOptions->willMessage) != 0)
        {
            LOG(AZ_LOG_ERROR, LOG_LINE, "mallocAndStrcpy_s willMessage");
            result = __FAILURE__;
        }
```
We want to copy the ```mqttOptions->willMessage``` to ```mqtt_client->mqttOptions.willMessage``` by calling ```mallocAndStrcpy_s```, but neither the caller and the callee functions free the existing memory of ```mqtt_client->mqttOptions.willMessage```, if it is not null, before assigning a new memory block for it, this will cause a memory leak.

Same behaviors at #434, #442, #458 and #466.

**Comment by ewertons** [comment]
Hi @maxpeng ,

thanks for your contribution! 

Indeed this issue was in our radar; a fix is will be checked in promptly.

For reference, this issue is filed under the wrong repo, it is an issue pertaining to https://github.com/Azure/azure-umqtt-c 

At: https://github.com/Azure/azure-umqtt-c/blob/36665a3c845c4d03485c7be6ea2c7f9c2e551f7e/src/mqtt_client.c#L450

**Comment by ewertons** [comment]
A fix has been checked in within umqtt repo, and will be integrated into the azure-iot-sdk-c by tomorrow.

https://github.com/Azure/azure-umqtt-c/commit/ee7a5a9ed6bd5aa368916f8914fa969290cf272d
https://github.com/Azure/azure-umqtt-c/commit/79da9f07893ef92dc722c59cf370f8b83e2caa4b

**Comment by ewertons** [comment]
Update: the fixes are still being rolled out to the C SDK. It shall be done soon, I'll update again once done.

**Comment by ewertons** [comment]
Alright, the changes are available on master branch of the Azure IoT C SDK.
If you have the opportunity, please test the changes and let us know the result as well.

Thanks for contributing to Azure IoT SDKs.

**Comment by maxpeng** [comment]
**I have tested the changes, the problem has been solved.**

However, I have a question about the changes:
```
if (result == 0 && mqttOptions->willMessage != NULL)
{
    char* willMessage;

    if (mallocAndStrcpy_s(&willMessage, mqttOptions->willMessage) != 0)
    {
        LOG(AZ_LOG_ERROR, LOG_LINE, "mallocAndStrcpy_s willMessage");
        result = __FAILURE__;
    }
    else
    {
        if (mqtt_client->mqttOptions.willMessage != NULL)
        {
            free(mqtt_client->mqttOptions.willMessage);
        }

        mqtt_client->mqttOptions.willMessage = willMessage;
    }
}
```
Does this mean the rule is - The caller should be responsible for free the buffer while calling ```mallocAndStrcpy_s```?
