### ISSUE TITLE
Issue related to enrol multiple related devices using GroupEnrollment 

### ISSUE THREAD

**Issue by BinduRao2018** [Azure/azure-iot-sdk-c#1900]
I am trying to use group enrollment to provision multiple devices programmatically. 

I am unable to find enough documentation or sample code to create devices using Group Enrolment. I have looked at an example available in Java. However, there is no equivalent API in C to use SecurityProvider to add intermediate and device keys.
Could you provide more details/sample code that demonstrates this use case?

Here are the steps that I have tried:
- Creation of certificates (root, intermediate & leaf) as per instructions provided in https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md#managing-test-ca-certificates-for-samples-and-tutorials
- Root certificate added to certificates in IOThub with the verification on the Azure Portal
- Able to create a group enrollment using the root certificate using prov_sc_enrollment_group_sample.c

Here are my questions:
- How to use the certificates (intermediate & device) generated to provision a  device?
- Can a common name be added as a device Id?

**Comment by BinduRao2018** [comment]
Update:
I have tried to use GroupEnrolment to provision multiple devices as described in https://docs.microsoft.com/en-gb/azure/iot-dps/tutorial-custom-hsm-enrollment-group-x509?view=iotedge-2018-06.

- root certificate is added to IOTHub and verified
- Group enrolment is created on the portal with intermediate key
- custom_hsm_example.c updated with the device common name, certificate (full-chain), and private_key

I get the following error when I execute prov_dev_client_sample:

==========================================================================================

/home/br/workbench/Azuresphere/azure-iot-sdk-c/cmake-build-debug/provisioning_client/samples/prov_dev_client_sample/prov_dev_client_sample
Provisioning API Version: 1.6.0

Registering Device

Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
Error: Time:Tue Mar 16 17:42:12 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:prov_transport_process_json_reply Line:670 Unsuccessful json encountered: {"errorCode":401002,"trackingId":"fa14c8d0-29f8-49ab-aa0e-31892282bfd1","message":"CA certificate not found.","timestampUtc":"2021-03-16T17:42:12.9197645Z"}
Error: Time:Tue Mar 16 17:42:12 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:prov_transport_common_mqtt_dowork Line:1014 Unable to process registration reply.
Error: Time:Tue Mar 16 17:42:12 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Tue Mar 16 17:42:12 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:771 Failure retrieving data from the provisioning service

Failure registering device: PROV_DEVICE_RESULT_DEV_AUTH_ERROR
Error: Time:Tue Mar 16 17:42:12 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:395 Failure sending control packet data
Error: Time:Tue Mar 16 17:42:12 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1300 Error: mqtt_client_disconnect send failed
Press enter key to exit:
=========================================================================================

**Comment by BinduRao2018** [comment]
Here are the logs with the Trace enabled:
-------------------------------------------------------------------------------------------------------------------------------------------------
Provisioning API Version: 1.6.0

Registering Device

-> 23:08:40 CONNECT | VER: 4 | KEEPALIVE: 0 | FLAGS: 130 | USERNAME: 0ne0017479D/registrations/custom-hsm-device-01/api-version=2019-03-31&ClientVersion=1.6.0 | CLEAN: 1
<- 23:08:40 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0
-> 23:08:40 SUBSCRIBE | PACKET_ID: 1 | TOPIC_NAME: $dps/registrations/res/# | QOS: 1
Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
<- 23:08:40 SUBACK | PACKET_ID: 1 | RETURN_CODE: 1
-> 23:08:40 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/PUT/iotdps-register/?$rid=1 | PAYLOAD_LEN: 41
<- 23:08:40 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/res/401/?$rid=1 | PACKET_ID: 2 | PAYLOAD_LEN: 156
Error: Time:Tue Mar 16 23:08:40 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:prov_transport_process_json_reply Line:670 Unsuccessful json encountered: {"errorCode":401002,"trackingId":"3e660a0e-1c69-45b7-aa9c-f6049998d14f","message":"CA certificate not found.","timestampUtc":"2021-03-16T23:08:40.4214178Z"}
Error: Time:Tue Mar 16 23:08:40 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:prov_transport_common_mqtt_dowork Line:1014 Unable to process registration reply.
Error: Time:Tue Mar 16 23:08:40 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Tue Mar 16 23:08:40 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:771 Failure retrieving data from the provisioning service

Failure registering device: PROV_DEVICE_RESULT_DEV_AUTH_ERROR
Error: Time:Tue Mar 16 23:08:40 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:395 Failure sending control packet data
Error: Time:Tue Mar 16 23:08:40 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1300 Error: mqtt_client_disconnect send failed
Press enter key to exit:
--------------------------------------------------------------------------------------------------------------------------------------------------------------

I have gone through similar queries on this project. However, it is not clear on the usage of certificates:
- Should I upload a root/intermediate certificate for proof of possession?
- Should the group enrollment use an intermediate/root certificate for creation?
- Should custom_hsm_example.c provide a full-chain certificate / public key as CERTIFICATE?

**Comment by danewalton** [comment]
Interesting it seems it's not able to chain up to the CA? What certs are you putting on the device? If you have (CA) -> (Intermediate) -> (Leaf Device) then the intermediate and the leaf device would need to be put on the device and sent to the service on connect.

**Comment by BinduRao2018** [comment]
@danewalton,
I have tried with full-chain certificate chain as explained in Step3 (Configure the custom HSM stub code) - https://docs.microsoft.com/en-gb/azure/iot-dps/tutorial-custom-hsm-enrollment-group-x509?view=iotedge-2018-06 and also with just leaf device. 
I get the same error in both cases.

Please note, am using the Bash scripts on Linux.

**Comment by BinduRao2018** [comment]
Many Thanks, @danewalton. 
I did try by adding CA to IoT Hub instead of provisioning service. It is all working fine now with the following steps:
1. Root CA as DPS certificate
2. Add Intermediate certificate to Group Enrolment
3. Use full-chain and private keys in the custom device (hsm_custom_example) to provision a device.

I have a question further to this:
- We would like to install the C SDK and use the features through the API support available. However, the IoT service client is deprecated (https://github.com/Azure/azure-iot-sdk-c/issues/1906). Should certificate and group enrollment (Steps 1 & 2) be done automatically - set up directly on the portal? What is the mechanism to pass device certificates to the provisioning client to register to IoT Hub?

**Comment by danewalton** [comment]
Certificate management specifically isn't in the purview of our team. That's a process that should be investigated according to the needs and capabilities of the developers.

That being said, if you wanted to programmatically create these enrollment groups with a service SDK, we have others like [Node](https://github.com/Azure/azure-iot-sdk-node/blob/1683f5802f2f30a5c901c6c777183d22c41c46b9/provisioning/service/src/provisioningserviceclient.ts#L131-L137) that you might be interested in.

**Comment by BinduRao2018** [comment]
Thank you for the support @danewalton. We are now focusing on using the C SDK. We will get back in touch if we plan to use other IoT SDK.

**Comment by BinduRao2018** [comment]
Is it required to pass/store full-chain and not leaf certificate in HSM for authorisation? When I try to use leaf certificate in custom_hsm_sample, I get MQTT_communication_error.
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Provisioning API Version: 1.6.0
Iothub API Version: 1.6.0
Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
Error: Time:Mon Mar 22 08:30:46 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Mon Mar 22 08:30:46 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:771 Failure retrieving data from the provisioning service
Failure encountered on registration PROV_DEVICE_RESULT_TRANSPORT
Error: Time:Mon Mar 22 08:30:46 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:395 Failure sending control packet data
Error: Time:Mon Mar 22 08:30:46 2021 File:/home/br/workbench/Azuresphere/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1300 Error: mqtt_client_disconnect send failed
------------------------------------------------------------------------------------------------------------------------------------------------------------

However, device provisioning works fine when I pass 'full-chain certificate.

**Comment by danewalton** [comment]
[Here's a good resource to maybe help with which certs are needed](https://docs.microsoft.com/en-us/azure/iot-dps/concepts-x509-attestation). Are you saying in scenario `A -> B -> C` where `A` is CA, `B` is intermediate, and `C` is device, you are sending only `B` and `C`?

**Comment by BinduRao2018** [comment]
From the device, I have to set the full chain as a certificate i.e A, B & C. Sending only C result in an MQTT Communication error.

**Comment by ericwol-msft** [comment]
You said in your previous post "Root CA as DPS certificate", so yes you would need to send the cert chain. You can't send the leaf cert because the intermediate certs can't be verified. Please reread Dane's link and that explains your question.

**Comment by BinduRao2018** [comment]
@danewalton, thanks for the link. @ericwol-msft, thanks for the clarification. 
If I avoid using an intermediate certificate i.e., Set the root certificate in DPS and the same certificate in enrollment, can I just use the leaf certificate as a Device certificate, though I understand the importance of using intermediate certificates.

**Comment by danewalton** [comment]
You can definitely have scenario `A -> B` where `A` is a CA and `B` is a device cert signed by `A`. You don't need an intermediate. Intermediates help if you were to buy a CA signed cert from someone like Digikey, in which you pay them to sign a CSR and give you a cert signed by their root. That way, the chain of trust goes all the way up to a recognized CA. So you pay for `A -> B`.

If you wanted many certs for devices, you wouldn't want to have to go to Digikey to sign all of those since it would take time and cost a good chunk of money. So you would use your purchased `B` to sign device certs `C`, `D`, `E` etc. So for four devices you'd have
- `A -> B -> C`
- `A -> B -> D`
- `A -> B -> E`
- `A -> B -> F`

**Comment by BinduRao2018** [comment]
Thanks a lot, @danewalton, for all the support. I will close this ticket and open new issues for further queries.
