### ISSUE TITLE
TLS handshake fails using 1.2RC Edge - missing certificate properties?

### ISSUE THREAD

**Issue by vipeller** [Azure/azure-iot-sdk-c#1901]
Hi,

Testing Edge with C sdk (pulled LTS_01_2021_Ref01), and running the iotedge_downstream_device_sample on linux (ubuntu), it fails with the following  error message:

```
Error: Time:Tue Mar 16 21:42:11 2021 File:/home/vipeller/csdk_test/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:724 error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Error: Time:Tue Mar 16 21:42:11 2021 File:/home/vipeller/csdk_test/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
```

The same code works if I leave out the GatewayHostname from the connection string an the code connects directly to IoTHub.

I also tested with openssl s_client, and in that case openssl is happy with the TLS handshake:

```
CONNECTED(00000003)
Can't use SSL_get_servername
depth=1 CN = iotedged workload ca
verify return:1
depth=0 CN = 10.0.0.140
verify return:1

Certificate chain
 0 s:CN = 10.0.0.140
   i:CN = iotedged workload ca
 1 s:CN = iotedged workload ca
   i:CN = iotedged workload ca

Server certificate
-----BEGIN CERTIFICATE-----
MIIC4DCCAcigAwIBAgIBADANBgkqhkiG9w0BAQsFADAfMR0wGwYDVQQDDBRpb3Rl
ZGdlZCB3b3JrbG9hZCBjYTAeFw0yMTAzMTYyMzA2MzRaFw0yMTA0MTUyMzA2MzRa
MBUxEzARBgNVBAMMCjEwLjAuMC4xNDAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
ggEKAoIBAQDQ9usSpNZnYLDfgBpSAlc74L1Ph98BKxigR2UuN3xoDSLsjBFobTfE
1yKT6V3Tj/rePiUghNvhupmWjFP0PAfLlS04XoV6KWWWQG+VoBda4VaV8RkKiJyI
AHF/vPQ4clx34WN0YJn5t+LBm4GN0+Ust5l4rfooffi95SmE9Ter0CMnNrY1/NNc
3uD9U3CYUYeWox15iGBcKNOXsDA5CktMZFiJ2+nbK6PBDyYxB+BHOaA+YqrBs5q/
P2S88DbbRRa9QVukqrpsgAGNlKr8lQiLzIXSsp9FbTwIpXGE7zHek/ThHQF4kFfm
n3NjKDv4AQby+m7dUxXoxXi8EUbNMke7AgMBAAGjMTAvMBMGA1UdJQQMMAoGCCsG
AQUFBwMBMBgGA1UdEQQRMA+CB2VkZ2VodWKHBAoAAIwwDQYJKoZIhvcNAQELBQAD
ggEBAD8bLuQn1AOJtjVftRyGzmjrrzM8p21SODEo4TInN0SVsyPo3G3fXd/9Ry5v
oY7Z/qeu243/3WKf7uzBvtgS01yZwPyIBwbcimSqcJ5Dsh8asAfo3H1Pbr1WzB66
5eEoJGocLPZa5c7g9CUJNzetL1XFckXnKGeq7XEdtwkXoRpkTMk/1FNQcENNOAKL
+dQHyMkxOqFxtxZGY0h3Y3VDr6Fm5G7K1OSIZzVYthbcYelnZuNih7T0p4kWyOj4
qwEQvwyGKEPrr33wVngh1BnJq5jKN98DEMtqZFxg+kkHtcXeBn227L5e0w87770U
1APe2+EKCIMGHdZHbi1HMmu7TFg=
-----END CERTIFICATE-----
subject=CN = 10.0.0.140

issuer=CN = iotedged workload ca


No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA224:RSA+SHA1:DSA+SHA224:DSA+SHA1:DSA+SHA256:DSA+SHA384:DSA+SHA512
Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:RSA+SHA224:DSA+SHA224:DSA+SHA256:DSA+SHA384:DSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits

SSL handshake has read 2023 bytes and written 388 bytes
Verification: OK

New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 86D8053E11C0B9A5115D8C46E17C2A23C653115ACE5233A09D6847F3CE18A2C4
    Session-ID-ctx:
    Master-Key: 8740A78197C2899C8E5183141E743271BF3A51AEF5685F11F9376AFC5E629AF03772F81A57BFF890330AE949520AF80D
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1615956769
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
```

At this moment I assume that the C-SDK configures the tls library slightly differently than the openssl utility and that is the reason why the certificate is not accepted by the sample code. I tried to lookup in the C-SDK code, but I could not notice anything what it can be.

The root certificate is (the server certificate is in the openssl log above):

```
-----BEGIN CERTIFICATE-----
MIIC3zCCAcegAwIBAgIBADANBgkqhkiG9w0BAQsFADAfMR0wGwYDVQQDDBRpb3Rl
ZGdlZCB3b3JrbG9hZCBjYTAeFw0yMTAzMTYyMjMyNTFaFw0yMTAzMTcyMjMyNTFa
MB8xHTAbBgNVBAMMFGlvdGVkZ2VkIHdvcmtsb2FkIGNhMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEA06FhzvYobb1ZbQNu4uw1fDYBEJR1A7B2vTf7w4BE
EZaYQnRYQAT7tlfHxtEkB+l4l/sE9Q7zEAO9RGH0HlaHhTG8fVz8Ner8AmlEr57s
7jabuAewX26FlvmR5lPZDPFVbsIqt4enZ8qbsbilHF1Mu0GD3RGsSDonPFzNv3cC
bXG4CoVfIDc0Ga7oJzEgPKT73N3WmeWG6uUXNpzVTWnaz5PQiCHc6BbSvSvCiQLd
oGrP0PmHKVIiZ/M7odwSnlDd4eexwxVxdI8M3QilzuiM876LlSv02Va0wAaVmfhW
45oyhTQRyfbJO/uPzFa9M4GbbcHAAZZC5wOwoLfLooDDSwIDAQABoyYwJDASBgNV
HRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIChDANBgkqhkiG9w0BAQsFAAOC
AQEAGRomsEelEqM5JM2EJwSzteAAi665lmDA/ohjgVp6cOm+9MWwkcwxPP6EeMmm
VVFLAgGbD2wc1Ji/uTexBnVKp0eXpdUIpsKC+GJbVyAn69k48k4x71mmTAJVz3GX
QfQu/QWhB5BR8jpkbHH+vjnJbEHU/D/KqPoPPhanl6qIg5Y+EAB8YTeKVI2rnyOg
kleCskLT9sYgRjl6q3utFEg+j8FKevbd+VGTRkCxsbUEHHBQx+yB0etnLLjt7gDD
hC8brm1fmTr+gHH4ae31I3+pUYud+D67mSd70nfgDY8/gWTLTQhRhnv3EANSnNDI
anVyOitd0blhOPn0urm7c+WyLw==
-----END CERTIFICATE-----
 ```

(note, that this certificate expires in a day, which is 3/17/2021 early afternoon)

If the reason of the handshake failure is that one of the certificates does not have some proper fields, pls give tell us what to add/change. If the reason maybe something else, let us know that.

I added the root certificate to the OS trusted store by 'update-ca-certificates' but also defined the trusted ca in the sample code (tried with and without specifying it)

**Comment by vipeller** [comment]
Some additional detail, if I remove the alternative name/dns name field from the certificate, that makes thing work:

![image](https://user-images.githubusercontent.com/51135538/111552235-21853700-873f-11eb-99d5-fb4d8b9bfbad.png)

I am not sure at this moment why edge adds that alternative dns name, but also not sure why it causes problems

**Comment by ericwol-msft** [comment]
```
Can't use SSL_get_servername
depth=1 CN = iotedged workload ca
```
The CN does not look right. I would expect it to look like iotedged.workload.ca

`Some additional detail, if I remove the alternative name/dns name field from the certificate, that makes thing work:`
How are you connected to the edge gateway? Is the host name a FQN and does it match the? The cert shows an IP address for the Subject, is that what you are connecting with? The cert at the start of the thread has a different IP address (10.0.0.140) than what you just pasted in the screenshot.

`I am not sure at this moment why edge adds that alternative dns name, but also not sure why it causes problems`
Edge can't add this to the cert. This was on the cert when it was created and uploaded to the edge gateway.

**Comment by vipeller** [comment]
@ericwol-msft Hi, some more context:
- we use ip address (that is what configured to be used for edge, and also that is defined as gatewayhostname)
- yes, the ip addresses are different, that is because the first day I used a full setup (following a bug report), but then it was painful to play with the certificates, so I switched to a different machine/setup where it was easier to quickly generate and change certificates to see how the SDK reacts,
- I use edge in devmode, when it generates all the certificates. On top of that, edge generates the server certificate (which has the alternative name) even if I upload my own ca cert. 

Regarding the workload ca CN, that is a good point but I am not sure that it has any effect on the verification algorithm later which does not accept the certificate (chain) when DNS Name = edgehub is added to the server certificate. (But I can try if you think that this is a problem)

Also, I have not tried if it fails when instead of an ip address, I use a dns name (I can try it)

**Comment by ericwol-msft** [comment]
> Also, I have not tried if it fails when instead of an ip address, I use a dns name (I can try it)
What TLS stack are you using. Also might be helpful capture the network packets using Wireshark and look at the TLS hello cert negotiation.

**Comment by vipeller** [comment]
@ericwol-msft regarding the tls stack, I am not quite sure the answer. I compiled the iothub sdk and the samples on ubuntu 20.04.1 following the walkthrough on github. Assuming that the sdk uses openssl, the related infromation:

```
>dpkg -l | grep -i openssl
ii  libcurl4:amd64                 7.68.0-1ubuntu2.4                  amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libcurl4-openssl-dev:amd64     7.68.0-1ubuntu2.4                  amd64        development files and documentation for libcurl (OpenSSL flavour)
ii  libssh-4:amd64                 0.9.3-2ubuntu2.1                   amd64        tiny C SSH library (OpenSSL flavor)
ii  libxmlsec1-openssl:amd64       1.2.28-2                           amd64        Openssl engine for the XML security library
ii  openssl                        1.1.1f-1ubuntu2                    amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  python3-openssl                19.0.0-1build1                     all          Python 3 wrapper around the OpenSSL library
ii  python3-service-identity       18.1.0-5build1                     all          Service identity verification for pyOpenSSL (Python 3 module)

>openssl version -a
OpenSSL 1.1.1f  31 Mar 2020
built on: Wed Feb 17 12:35:54 2021 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-g4Ey0B/openssl-1.1.1f=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific
```

I can take a look at the tls client/server hello with wireshark, but I am not sure what that could reveal: the only difference between a working version and the not-working version is that the not-working version in the subject alternative name extension has an additional DNS name entry. The root certificate is the same, the key type and size is the same. Also, I assume that the client sends the same extension fields in client hello and the server reacts the same way, regardless if the DNS name is added or not to the certificate.

What I would assume is that when the client verifies the certificate chain and it sees the DNS name in the alternative name extension, it wants to apply some sort of rule (e.g. the only DNS name should be the real host name, however I tried that and it failed). I would like to understand what rule that is and what needs to change to make it work.

**Comment by CIPop** [comment]
@vipeller I am actively working on this.
