### ISSUE TITLE
Even if there is enough signal strength,  Azure C SDK returning NO NETWORK

### ISSUE THREAD

**Issue by seemamathew** [Azure/azure-iot-sdk-c#1916]
Hi, 
We are developing an C++ QT application using azure-iot-sdk -c 1.3.8 version. While keeping system for long run, we are getting IOTHUB_CLIENT_CONNECTION_NO_NETWORK even if there is enough signal strength suggested by network provider. 

Is this error have any relation with IOT library. 
Please note that we are using roaming sim.

Thanks in Advance
Seema

**Comment by ericwol-msft** [comment]
The error is what it describes. There is a network conductivity issue and this error is being reported up from your platform networking layer..

**Comment by seemamathew** [comment]
Thank you Eric. I will check the platform layer.

Thanks and Regards
Seema

**Comment by danewalton** [comment]
closing for now
