### ISSUE TITLE
Baltimore root certificate on ubuntu 16.04 TLS

### ISSUE THREAD

**Issue by samanaz** [Azure/azure-iot-sdk-c#1920]
Dear support,

Since the new Baltimore root certificate is not installed on ubuntu 16.04 by default, I have defined that in my c application. It works fine, but as soon as I want to use the blob upload functionality I get a certificate error. Probably it is because the blob upload is trying to use curl and cul needs to get access to the local certificate store!?

How can I install the new Baltimore root certificate and does it resolve the issue?
This is the error I get if I do not define the Baltimore certificate in my c application.

Error: Time:Fri Mar 26 10:25:44 2021 File:/home/saman/SDKs/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:675 error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

Would you please help me to solve this issue. If I need to install this certificate please give me a step by step guide to follow.

Thank you in advance.

Sincerely yours,
Saman

**Comment by ericwol-msft** [comment]
> How can I install the new Baltimore root certificate and does it resolve the issue?

The root certificate has not changed.

**Azure Certs**
https://techcommunity.microsoft.com/t5/azure-storage/azure-storage-tls-changes-are-coming-and-why-you-care/ba-p/1705518
https://docs.microsoft.com/en-us/azure/security/fundamentals/tls-certificate-changes

**Ubuntu certificate install**
https://www.bing.com/search?q=install%20root%20certificate%20%20ubuntu&qs=n&form=QBRE&msbsrank=2_2__0&sp=-1&pq=install%20root%20certificate%20ubuntu&sc=2-31&sk=&cvid=62802348B3D14D5C90548354080FBBE8

**Comment by samanaz** [comment]
I have an issue connecting to the azure IoT hub with c SDK on Ubuntu 16.04.
I get this error:

Error: Time:Fri Mar 26 10:25:44 2021 File:/home/saman/SDKs/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:675 error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

Would you please give me some suggestions?

**Comment by CIPop** [comment]
@samanaz depending on your Ubuntu deployment, the CA store may not be present (e.g. the Server SKU won't install it). 
Installing it using `apt install ca-certificates` should make things work (Baltimore should be included in the default CA set).

If, for some reason Baltimore is not included, we recommend downloading it from a trusted location such as https://www.digicert.com/kb/digicert-root-certificates.htm, carefully verifying that the hashes and fingerprints match, then manually installing it using:

```bash
sudo cp my.crt /usr/local/share/ca-certificates/
sudo update-ca-certificates
```
