### ISSUE TITLE
How to Initiate Reconnection from the azure SDK

### ISSUE THREAD

**Issue by manojtiwary22** [Azure/azure-iot-sdk-c#1925]
Hi,

I want to know that , is there any way or api that can be used to initiate a reconnection to the IOT hub from the MQTT  client without invoking IoTHubClient_LL_Destroy(iotHubClientHandle) and then connecting again?

Or, can we initiate retry mechanism manually from the application?

Thank you

**Comment by CIPop** [comment]
@manojtiwary22 we have built automatic retry policies within the Azure IoT C-SDK. Here are a few resources that might help:

- https://github.com/Azure/azure-iot-sdk-c/blob/e3e0a0bdfac5755b170bc09091b83a2857843f3a/doc/connection_and_messaging_reliability.md#connection-establishment-and-retry-logic
- https://github.com/Azure/azure-iot-sdk-c/blob/8f6b4823b7f6652578016ae3b19af871204beafb/iothub_client/devdoc/requirement_docs/iothub_client_retry_control_requirements.md
- IoTHubDeviceClient_LL_SetRetryPolicy API: https://github.com/Azure/azure-iot-sdk-c/blob/8f6b4823b7f6652578016ae3b19af871204beafb/iothub_client/src/iothub_device_client_ll.c#L74
