### ISSUE TITLE
Azure_iot_sdk_c build failed with warning C4701 and C4703

### ISSUE THREAD

**Issue by KarenHuang2016** [Azure/azure-iot-sdk-c#193]
I build Azure_iot_sdk_c with Visual studio 2017 compiler on Windows Server 2016, but it failed with with warning C4701 and C4703. could you help have a look about this issue? Thanks in advance!

**Failures:**
 d:\azure_iot_sdk_c\src\c-utility\src\x509_schannel.c(132): **warning C4701**: <func:#75 "_decode_crypt_object"> potentially uninitialized local variable 'result' used [D:\Azure_iot_sdk_c\build_x86\c-utility\aziotsharedutil.vcxproj]
         d:\azure_iot_sdk_c\src\c-utility\src\x509_schannel.c(132): **warning C4703**: <func:#75 "_decode_crypt_object"> potentially uninitialized local pointer variable 'result' used [D:\Azure_iot_sdk_c\build_x86\c-utility\aziotsharedutil.vcxproj]
...
d:\azure_iot_sdk_c\src\c-utility\src\x509_schannel.c(132): error C2220: <func:#75 "_decode_crypt_object"> warning treated as error - no 'object' file generated [D:\Azure_iot_sdk_c\build_x86\c-utility\tests\x509_schannel_ut\x509_schannel_ut_dll.vcxproj]

**Workaround for this issue:**
in x509_schannel.c file line 75:
change 
unsigned char* result;
to
unsigned char* result **= NULL**;

**Repro steps:**
1. Open VS2017 x86 Native tools command tool
2. git clone --recursive http://www.github.com/azure/azure-iot-sdk-c D:\Azure_iot_sdk_c\src
3. cd D:\Azure_iot_sdk_c
4. mkdir build_x86 && pushd build_x86
5. cmake -G "Visual Studio 15" -DCMAKE_SYSTEM_VERSION=10.0.15063.0  -Drun_unittests:BOOL=ON ..\src\
6. msbuild azure_iot_sdks.sln /p:Configuration=Release /p:Platform=win32 /m /t:Rebuild

**Comment by jebrando** [comment]
This Issue has been fixed with the following commit:

https://github.com/Azure/azure-c-shared-utility/commit/c0fdd16f11e0bc8d46f8d27cd21b02e5ce139337#diff-7cf78bb9afe6d4301ff3c78df80ce346

The C-SDK will be undated today to reflect this submodule change.
