### ISSUE TITLE
can i use this SDK on Zephyr RTOS?

### ISSUE THREAD

**Issue by moncef-bibani** [Azure/azure-iot-sdk-c#1935]
Hi guys,

I want to connect a device with the Azure IoT cloud for my project with Zephyr RTOS. The memories on my device are less than 1mb. I tried to connect by using directly the MQTT protocol but the SRAM on the STM32 was not enough. Now I want to try to build an application with this SDK. 

Is that possible to use this SDK in Zephyrproject ? Has someone of you experience with this ??

**Comment by ericwol-msft** [comment]
Please look at the ["Azure SDK for Embedded C"](https://github.com/Azure/azure-sdk-for-c) This SDK is created for memory constrained devices. 

You should also consider using Azure RTOS which includes the Azure embedded C SDK and has samples for the STM32 boards 

https://github.com/azure-rtos/samples

**Comment by moncef-bibani** [comment]
> Please look at the ["Azure SDK for Embedded C"](https://github.com/Azure/azure-sdk-for-c) This SDK is created for memory constrained devices.
> 
> You should also consider using Azure RTOS which includes the Azure embedded C SDK and has samples for the STM32 boards
> 
> https://github.com/azure-rtos/samples

Thank you very much for your answer! I have 64Kb SRAM and 256Kb flash memory available in my STM32. Do you think is enough for this SDK  ? how can i consume the Azure SDK for C to Zephyr?

**Comment by danewalton** [comment]
The Azure SDK for C essentially helps parsing MQTT topics and working with MQTT features of IoT Hub. You will need to bring your own MQTT, TLS, and TCP/IP. It will require more stitching together on your part but it ensures a smaller binary size. Zephyr has their own MQTT stack which you could incorporate [here](https://docs.zephyrproject.org/latest/reference/networking/mqtt.html). Some TLS with MQTT docs seems to be [here](https://docs.zephyrproject.org/latest/samples/net/mqtt_publisher/README.html#connecting-securely-using-tls).

We have a sample here for esp32 that you can use as general guidance of stitching together the embedded sdk and mqtt:
https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/aziot_esp32/aziot_esp32.ino

**Comment by moncef-bibani** [comment]
> The Azure SDK for C essentially helps parsing MQTT topics and working with MQTT features of IoT Hub. You will need to bring your own MQTT, TLS, and TCP/IP. It will require more stitching together on your part but it ensures a smaller binary size. Zephyr has their own MQTT stack which you could incorporate [here](https://docs.zephyrproject.org/latest/reference/networking/mqtt.html). Some TLS with MQTT docs seems to be [here](https://docs.zephyrproject.org/latest/samples/net/mqtt_publisher/README.html#connecting-securely-using-tls).
> 
> We have a sample here for esp32 that you can use as general guidance of stitching together the embedded sdk and mqtt:
> https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/samples/iot/aziot_esp32/aziot_esp32.ino

Thank you very much! I will try it.
