### ISSUE TITLE
IOT Hub is calling connectionStatusCallback non-stop 

### ISSUE THREAD

**Issue by sanjayshekar** [Azure/azure-iot-sdk-c#1947]
Hello All,
We are using Azure IOT SDK (V1.3.4), using this in our product line from past 3 years, recently we found one observation. The IOT Hub is continuously calling connectionStatusCallback with the following result and reason.

IOTHUB_CLIENT_CONNECTION_AUTHENTICATED, IOTHUB_CLIENT_CONNECTION_OK
and 
IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, IOTHUB_CLIENT_CONNECTION_COMMUNICATION_ERROR
and
IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, IOTHUB_CLIENT_CONNECTION_OK

This callback is not stopping which in turn is creating other product issues.

I would like to know in what scenario this callback is called in a continuous manner.
We are using AMQP_Protocol_over_WebSocketsTls for communication and sas token.
Also no retry policy overridden, I assume it will be exponential backoff.

Please let us know the possibility of device getting into this state.

This is a non reproducible issue and happened in only few devices. After restarting, the device is back to normal.

Inputs are highly appreciated.

**Possible Solution** would be to update to the new version, but we would like to make sure about the issue before updating to new version.

Thank you.

**Comment by danewalton** [comment]
Hi @sanjayshekar just to clarify, when you say 

> continuously calling connectionStatusCallback with the following result and reason.

Do you mean it repeatedly calls that callback with that series of return values? And never recovers? Or does it go 
`IOTHUB_CLIENT_CONNECTION_AUTHENTICATED, IOTHUB_CLIENT_CONNECTION_OK` ->
`IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, IOTHUB_CLIENT_CONNECTION_COMMUNICATION_ERROR` -> 
`IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, IOTHUB_CLIENT_CONNECTION_OK` -> 
`IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, IOTHUB_CLIENT_CONNECTION_OK` ->
`IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, IOTHUB_CLIENT_CONNECTION_OK` -> 
`IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, IOTHUB_CLIENT_CONNECTION_OK` ...

**Comment by ericwol-msft** [comment]
Yes, we would need full logs enabled to have better insight what is going on.

        bool traceOn = true;
        IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_LOG_TRACE, &traceOn);

**Comment by sanjayshekar** [comment]
Hello @danewalton , 
           Yes it never recovers and below is the application logs. 
It behaves like option 1 you mentioned above. Also the interesting fact is that, when the device is in this sate, we are able to reach the device to read the diagnostic vitals like CPU usage, memory etc and everything looks normal. More over it is also sending data to cloud. 

**Application Log:**
Line 94936: 2021 Apr 26 12:32:54 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 94981: 2021 Apr 26 12:32:54 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: 
	Line 94988: 2021 Apr 26 12:32:54 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 94990: 2021 Apr 26 12:32:54 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 94999: 2021 Apr 26 12:32:55 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95001: 2021 Apr 26 12:32:55 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95003: 2021 Apr 26 12:32:55 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95005: 2021 Apr 26 12:32:55 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95007: 2021 Apr 26 12:32:55 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95009: 2021 Apr 26 12:32:55 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95011: 2021 Apr 26 12:32:56 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95013: 2021 Apr 26 12:32:56 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95015: 2021 Apr 26 12:32:56 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95022: 2021 Apr 26 12:32:56 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95024: 2021 Apr 26 12:32:56 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95026: 2021 Apr 26 12:32:56 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95036: 2021 Apr 26 12:32:57 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95038: 2021 Apr 26 12:32:57 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95040: 2021 Apr 26 12:32:57 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95052: 2021 Apr 26 12:32:57 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95054: 2021 Apr 26 12:32:57 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95056: 2021 Apr 26 12:32:57 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95058: 2021 Apr 26 12:32:58 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95060: 2021 Apr 26 12:32:58 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95062: 2021 Apr 26 12:32:58 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95065: 2021 Apr 26 12:32:58 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95067: 2021 Apr 26 12:32:58 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95069: 2021 Apr 26 12:32:58 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95071: 2021 Apr 26 12:32:59 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95073: 2021 Apr 26 12:32:59 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95075: 2021 Apr 26 12:32:59 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95077: 2021 Apr 26 12:32:59 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95079: 2021 Apr 26 12:32:59 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95081: 2021 Apr 26 12:32:59 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95083: 2021 Apr 26 12:33:00 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95085: 2021 Apr 26 12:33:00 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95087: 2021 Apr 26 12:33:00 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95089: 2021 Apr 26 12:33:00 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95091: 2021 Apr 26 12:33:00 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95093: 2021 Apr 26 12:33:00 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95096: 2021 Apr 26 12:33:01 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95098: 2021 Apr 26 12:33:01 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95100: 2021 Apr 26 12:33:01 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95102: 2021 Apr 26 12:33:01 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95104: 2021 Apr 26 12:33:01 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95106: 2021 Apr 26 12:33:01 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95108: 2021 Apr 26 12:33:02 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95110: 2021 Apr 26 12:33:02 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95112: 2021 Apr 26 12:33:02 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95114: 2021 Apr 26 12:33:02 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95116: 2021 Apr 26 12:33:02 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95118: 2021 Apr 26 12:33:03 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95121: 2021 Apr 26 12:33:03 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95123: 2021 Apr 26 12:33:03 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95125: 2021 Apr 26 12:33:03 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95127: 2021 Apr 26 12:33:03 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95129: 2021 Apr 26 12:33:03 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95131: 2021 Apr 26 12:33:03 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95133: 2021 Apr 26 12:33:04 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95135: 2021 Apr 26 12:33:04 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95137: 2021 Apr 26 12:33:04 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95139: 2021 Apr 26 12:33:04 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95146: 2021 Apr 26 12:33:04 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95148: 2021 Apr 26 12:33:04 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95158: 2021 Apr 26 12:33:05 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95160: 2021 Apr 26 12:33:05 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95162: 2021 Apr 26 12:33:05 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95164: 2021 Apr 26 12:33:05 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95166: 2021 Apr 26 12:33:05 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95168: 2021 Apr 26 12:33:06 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95170: 2021 Apr 26 12:33:06 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95172: 2021 Apr 26 12:33:06 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95174: 2021 Apr 26 12:33:06 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95180: 2021 Apr 26 12:33:06 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95182: 2021 Apr 26 12:33:06 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95184: 2021 Apr 26 12:33:06 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95194: 2021 Apr 26 12:33:07 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95196: 2021 Apr 26 12:33:07 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95199: 2021 Apr 26 12:33:07 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95206: 2021 Apr 26 12:33:07 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95211: 2021 Apr 26 12:33:07 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95214: 2021 Apr 26 12:33:07 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95220: 2021 Apr 26 12:33:08 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95222: 2021 Apr 26 12:33:08 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95224: 2021 Apr 26 12:33:08 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95226: 2021 Apr 26 12:33:08 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95228: 2021 Apr 26 12:33:08 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95230: 2021 Apr 26 12:33:09 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95232: 2021 Apr 26 12:33:09 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95234: 2021 Apr 26 12:33:09 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95236: 2021 Apr 26 12:33:09 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95239: 2021 Apr 26 12:33:09 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95241: 2021 Apr 26 12:33:09 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95243: 2021 Apr 26 12:33:10 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95245: 2021 Apr 26 12:33:10 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95247: 2021 Apr 26 12:33:10 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95249: 2021 Apr 26 12:33:10 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95251: 2021 Apr 26 12:33:10 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95253: 2021 Apr 26 12:33:10 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95255: 2021 Apr 26 12:33:10 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95257: 2021 Apr 26 12:33:11 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95259: 2021 Apr 26 12:33:11 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95261: 2021 Apr 26 12:33:11 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95264: 2021 Apr 26 12:33:11 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95266: 2021 Apr 26 12:33:11 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95268: 2021 Apr 26 12:33:12 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95270: 2021 Apr 26 12:33:12 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95272: 2021 Apr 26 12:33:12 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95274: 2021 Apr 26 12:33:12 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95276: 2021 Apr 26 12:33:12 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95281: 2021 Apr 26 12:33:12 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95284: 2021 Apr 26 12:33:12 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95293: 2021 Apr 26 12:33:13 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95295: 2021 Apr 26 12:33:13 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95297: 2021 Apr 26 12:33:13 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95299: 2021 Apr 26 12:33:13 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95301: 2021 Apr 26 12:33:13 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95304: 2021 Apr 26 12:33:13 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95306: 2021 Apr 26 12:33:14 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95308: 2021 Apr 26 12:33:14 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95310: 2021 Apr 26 12:33:14 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95315: 2021 Apr 26 12:33:14 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok
	Line 95317: 2021 Apr 26 12:33:14 f1  689 [local1.info]  Sending Event to cloud
	Line 95319: 2021 Apr 26 12:33:15 f1  689 [local1.err]  Cloud Disconnected : Communication_Error
	Line 95322: 2021 Apr 26 12:33:15 f1  689 [local1.err]  Cloud Disconnected : Connection_Ok
	Line 95332: 2021 Apr 26 12:33:15 f1  689 [local1.info] GentDriverEvent.cpp[101]--cloudConnectionMonitor()--Connected: Connection_Ok

**Comment by sanjayshekar** [comment]
Hello @ericwol-msft 
           As mentioned earlier, this is a non reproducible issue occurred in few of our customer sites, we restarted the device and its back to normal. 
If we need to enable logs we need to release a new firmware and I am afraid to say its a long path and even if we do so, reproducing this maybe difficult. 
We will anyways enable the logs in our next firmware release, meanwhile if any analysis on why the device will enter to this state will help a lot. 

Thank you..

**Comment by danewalton** [comment]
Without logs it is difficult for us to help. 

However, looking in the code base this is where the communication error would be reported:
https://github.com/Azure/azure-iot-sdk-c/blob/d9bea2297ac8f9b1463d4825d701668cc4822877/iothub_client/src/iothubtransport_amqp_common.c#L311-L314

So you're looking at either `DEVICE_STATE_ERROR_AUTH_TIMEOUT` or `DEVICE_STATE_ERROR_MSG`. That second value could be a very wide range of things.

**Comment by danewalton** [comment]
Going to go ahead and close this for inactivity for now. Please let us know if you would like this reopened.
