### ISSUE TITLE
iOS/Swift: Timeout on message post

### ISSUE THREAD

**Issue by mmacagno** [Azure/azure-iot-sdk-c#1957]
Apple iOS 14.4.2  / Xcode 12.4 / Swift 5
IoT SDK Cocoa Pods:
  pod 'AzureIoTUtility', '=1.5.0'
  pod 'AzureIoTuMqtt', '=1.5.0'
  pod 'AzureIoTuAmqp', '=1.5.0'
  pod 'AzureIoTHubClient', '=1.5.0'

Using MQTT

Problem: unable to send messages - receive only timeouts

NOTE: the device connection string is verified and working via the counterpart Android application

Most code taken from sample.

Steps:
I open the client calling initToStart():

```
func initToStart(connectionString: String) -> ErrorResult {
        initialized = false        
        var protocolIoTClient: IOTHUB_CLIENT_TRANSPORT_PROVIDER = MQTT_Protocol
        client = IoTHubDeviceClient_LL_CreateFromConnectionString(connectionString, protocolIoTClient)
        
        let traceOn : Bool = true
        let traceOnPointer = UnsafeMutableRawPointer.allocate(byteCount: 1, alignment: 1)
        traceOnPointer.storeBytes(of: traceOn, as: Bool.self)
        IoTHubDeviceClient_LL_SetOption(client, OPTION_LOG_TRACE, traceOnPointer);
        
        // Disable retry policy, using own retry
        IoTHubDeviceClient_LL_SetRetryPolicy(client, IOTHUB_CLIENT_RETRY_NONE, 0)
        
        if (client == nil) {
            print("IoTClient-Error-1")
            return ErrorResult.Error
        }
        
        // Mangle my self pointer in order to pass it as an UnsafeMutableRawPointer
        let that = UnsafeMutableRawPointer(Unmanaged.passUnretained(self).toOpaque())
        
        // Set up the message callback
        if (IOTHUB_CLIENT_OK != (IoTHubClient_LL_SetMessageCallback(client, myReceiveMessageCallback, that))) {
            print("IoTClient-Error-2")
            //showError(message: "Failed to establish received message callback", startState: true, stopState: false)
            return ErrorResult.Error
        }
        
        timerDoWork = Timer.scheduledTimer(timeInterval: 0.1, target: self, selector: #selector(dowork), userInfo: nil, repeats: true)
        initialized = true
        
        return ErrorResult.SUCCESS
    }

    /// Check for waiting messages and send any that have been buffered
    @objc func dowork() {
        IoTHubDeviceClient_LL_DoWork(client)
    }
    

```

I then proceed to send one message from my queue of pending messages, and waiting for a response:

```
func sendEventAsync(messageId: String, payload: String, timestamp: Date, context: Int) -> Bool {
        if !initialized {
            Log.shared.warning("sendEventAsync() invoked without valid client initialized", self)
            return false
        }
        
        if payload.count == 0 {
            Log.shared.warning("sendEventAsync() invoked with empty payload", self)
            return false
        }
        
        // Construct the message
        let messageHandle: IOTHUB_MESSAGE_HANDLE = IoTHubMessage_CreateFromByteArray(payload, payload.utf8.count)
        
        if (messageHandle != OpaquePointer.init(bitPattern: 0)) {
            
            let dateFormatter = DateFormatter()
            dateFormatter.timeZone = TimeZone.current
            dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSS"
            
            let date = dateFormatter.string(from: timestamp)
            IoTHubMessage_SetProperty(messageHandle, "iothub-creation-time-utc", date)
            
            IoTHubMessage_SetProperty(messageHandle, "x-sensoria-app-id", Bundle.main.bundleIdentifier ?? "io.sensoria.ahora")
            IoTHubMessage_SetProperty(messageHandle, "x-sensoria-build-version", "iOS/\(UIApplication.appVersion)")
            
            if (IOTHUB_MESSAGE_OK != IoTHubMessage_SetMessageId(messageHandle, messageId)) {
                return false
            }
            
            let intPointer = UnsafeMutableRawPointer.allocate(byteCount: 8, alignment: 1)
            intPointer.storeBytes(of: context, as: Int.self)
            
            Log.shared.info("sendEventAsync() / IoTHub post, message id \(messageId), payload: \(payload), timestamp: \(date)", self)
            
            if (IOTHUB_CLIENT_OK == IoTHubDeviceClient_LL_SendEventAsync(client, messageHandle, mySendConfirmationCallback, intPointer)) {
                return true
            }
        }
        return false
    }

    let mySendConfirmationCallback: IOTHUB_CLIENT_EVENT_CONFIRMATION_CALLBACK = { result, userContext in
        let context = userContext?.load(as: Int.self)
        userContext?.deallocate()
        
        var status: IotHubStatusCode = IotHubStatusCode.Error
        if (result == IOTHUB_CLIENT_CONFIRMATION_OK) {
            status = IotHubStatusCode.OK
        }
        
        NotificationCenter.default.post(name: NSNotification.Name(rawValue: AppConstants.key.NotificationIoTClient), object: nil, userInfo: ["type": AppConstants.key.Events, "status": status, "context": context])
        
    }

```

These are the logs I receive:

-> 07:25:24 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: ******.azure-devices.net/******/?api-version=2020-09-30&DeviceClientType=iothubclient%2f1.5.0%20(Darwin%3b%20iPhone12%2c1) | PWD: XXXX | CLEAN: 0

<- 07:25:25 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0

-> 07:25:25 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/****/messages/devicebound/# | QOS: 1

<- 07:25:26 SUBACK | PACKET_ID: 2 | RETURN_CODE: 1

-> 07:25:26 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/*****/messages/events/iothub-creation-time-utc=2021-05-10T17:18:06.528&x-sensoria-app-id=io.sensoria.ahora&x-sensoria-build-version=iOS/1.0.2.200&%24.mid=5AF49809-85AB-4522-B803-F7587EF5026E | PACKET_ID: 3 | PAYLOAD_LEN: 83

... NO FURTHER LOGS and then callback with result IOTHUB_CLIENT_CONFIRMATION_RESULT [.IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT]

----

Not sure why this is not working.
thanks

**Comment by mmacagno** [comment]
@danewalton, no I am not. But using the connection string in your Swift sample works... so something in my code definitely. I am checking against it and will report back.

thanks

**Comment by mmacagno** [comment]
@danewalton I reviewed the sample code with mine.
One thing I was doing wrong was to immediately send a message before receiving feedback of the connection status.

I now added the proper wait, but now a weird thing happens.

I create the connection and wait for the response:

-> 11:44:19 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: iotc-d5ec84b3-2366-498f-9a64-26f88599cd0c.azure-devices.net/ahora-a124c2b6-dbde-4f98-80ba-6424e37602b9/?api-version=2020-09-30&DeviceClientType=iothubclient%2f1.5.0%20(Darwin%3b%20iPhone12%2c1) | PWD: XXXX | CLEAN: 0

<- 11:44:23 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0

2021-05-11T11:44:23-0700 debug io.sensoria.ahora : (IoTClient) -> () -> IoTClient: IOTHUB_CLIENT_CONNECTION_STATUS_CALLBACK: IOTHUB_CLIENT_CONNECTION_STATUS_TAG(rawValue: 0)

Then I send the message:

-> 11:44:27 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/ahora-a124c2b6-dbde-4f98-80ba-6424e37602b9/messages/events/iothub-creation-time-utc=2021-05-10T17:18:06.528&x-sensoria-app-id=io.sensoria.ahora&x-sensoria-build-version=iOS/1.0.2.200&%24.mid=5AF49809-85AB-4522-B803-F7587EF5026E | PACKET_ID: 2 | PAYLOAD_LEN: 83

Instead of receiving a IOTHUB_CLIENT_EVENT_CONFIRMATION_CALLBACK, I get two consecutive IOTHUB_CLIENT_CONNECTION_STATUS_CALLBACK calls with UNAUTHENTICATED result:

2021-05-11T11:44:29-0700 debug io.sensoria.ahora : (IoTClient) -> () -> IoTClient: IOTHUB_CLIENT_CONNECTION_STATUS_CALLBACK: IOTHUB_CLIENT_CONNECTION_STATUS_TAG(rawValue: 1)
2021-05-11T11:44:31-0700 debug io.sensoria.ahora : (IoTClient) -> () -> IoTClient: IOTHUB_CLIENT_CONNECTION_STATUS_CALLBACK: IOTHUB_CLIENT_CONNECTION_STATUS_TAG(rawValue: 1)

followed by a timeout response a few minutes later.

2021-05-11T11:53:22-0700 debug io.sensoria.ahora : (IoTClient) -> () -> IoTClient: IOTHUB_CLIENT_EVENT_CONFIRMATION_CALLBACK: IOTHUB_CLIENT_CONFIRMATION_RESULT_TAG(rawValue: 2)

Any idea?
thanks

**Comment by danewalton** [comment]
Ahhh yup that will do it. We have an option which will url encode user parameters as you can see in this sample:
https://github.com/Azure/azure-iot-sdk-c/blob/6971d9d6e3a4b8871c061da5cb58df11b99516b7/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L138-L139
if you don't want to do it manually yourself. But glad to see it working!

I'll close this for now but let me know if you have related issues and would like to see it reopened.
