### ISSUE TITLE
porting Azure Hub sdk-C to yocto

### ISSUE THREAD

**Issue by ClaudioBaldo** [Azure/azure-iot-sdk-c#1963]
We are trying to migrate our device from AWS to Azure IoT and so we need to port this sdk to a device running on yocto.
Can build and run the application but we get an error:

azure-c-shared-utility/adapters/socketio_berkeley.c Func:initiate_socket_connection Line:353 Failure opening connection to endpoint azure-c-shared-utility/adapters/socketio_berkeley.c Func:socketio_open Line:829 lookup_address_and_connect_socket failed azure-umqtt-c/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint

The device client has been disconnected^M

azure-c-shared-utility/adapters/tlsio_mbedtls.c Func:tlsio_mbedtls_open Line:649 Underlying IO open failed azure-umqtt-c/src/mqtt_client.c Func:mqtt_client_connect Line:1093 Error: io_open failed^M azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2530 Failure connecting to address MYHUBNAME.azure-devices.net

At the moment we are using mbedtls over socketio_berkley, transport protocol is mqtt.
Is there a need to add certificates and this could be the reason why the tls connection cannot be started?
If yes, I see the cert.c and header files, but I haven`t included them into the code and I am not getting any error/warning, so is the cert path specified and which source is calling the cert.c functions?

**Comment by danewalton** [comment]
Hi @ClaudioBaldo without going too deep into this yet are you able to attach a Wireshark trace at all? That would give good insight into what step of the connection it is failing.

**Comment by danewalton** [comment]
The error line with `lookup_address_and_connect_socket failed` leads me to believe this is a possible DNS issue. Is the device able to ping that address by itself?

**Comment by ClaudioBaldo** [comment]
I can`t ping the remote hub, but I assume that is related with with the ICMP service as the DNS can resolve the IP for the backend, it just doesn`t get any reply from it. This is the same on my windows PC if I try to ping it from power shell.
Also, when the host`s IP cannot be resolved, the connection will fail with 'DNs can`t be resolved'.

**Comment by ClaudioBaldo** [comment]
@danewalton btw, where do you see the lookup_address_and_connect_socket failed in the logs I have sent?

**Comment by danewalton** [comment]
> azure-c-shared-utility/adapters/socketio_berkeley.c Func:initiate_socket_connection Line:353 Failure opening connection to endpoint azure-c-shared-utility/adapters/socketio_berkeley.c **Func:socketio_open Line:829 lookup_address_and_connect_socket failed** azure-umqtt-c/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint

As for the certs if you don't have a cert store then you have to add in the certs which the device should trust. You can do that with this option here:
https://github.com/Azure/azure-iot-sdk-c/blob/1139bc065c000143e38850337644f991a6651607/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L129-L131

**Comment by ClaudioBaldo** [comment]
I have now defined the 
#define SET_TRUSTED_CERT_IN_SAMPLES
but I still get the same error, I am struggling to understand where the problem is, as the error doesn`t give any clue about the underlying problem.

**Comment by danewalton** [comment]
To clarify here if you are using your own sample/code you need to set the option which is listed above not the compile define. 

Also line 353 in socketio berkeley has this error message:
https://github.com/Azure/azure-c-shared-utility/blob/ff06a49746b2240f54596852652886ce08b07718/adapters/socketio_berkeley.c#L353

It looks like it should be printing out the `errno`. Are verbose logs on? 

https://github.com/Azure/azure-iot-sdk-c/blob/1139bc065c000143e38850337644f991a6651607/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L124-L125

**Comment by ClaudioBaldo** [comment]
These are the logs I get:

socketio_berkeley.c Func:wait_for_connection Line:416 Failure: select failure
socketio_berkeley.c Func:socketio_open Line:834 wait_for_connection failed
mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
tlsio_mbedtls.c Func:tlsio_mbedtls_open Line:649 Underlying IO open failed
mqtt_client.c Func:mqtt_client_connect Line:1093 Error: io_open failed
iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2530 failure connecting to address .....

I have included the:
    IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_TRUSTED_CERT, certificates);

also included the :
 IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_LOG_TRACE, &amp;traceOn);

still see the same logs

**Comment by ClaudioBaldo** [comment]
have tried to use the mqtt over websocket and this is the logs I get:
INFO | mqttClientAzure[15101] | Sending message 1 to IoTHub^M
INFO | mqttClientAzure[15101] | Error: Time:Tue Jun  8 10:49:25 2021 File:/home/claudio/legatoWorkspace/AwsProject/mqttClients/mqttClientAzure/azure-c-shared-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:1068 

Jun  8 10:49:25 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | errno: 22
Jun  8 10:49:25 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Error: Time:Tue Jun  8 10:49:25 2021 File:/home/claudio/legatoWorkspace/AwsProject/mqttClients/mqttClientAzure/azure-umqtt-c/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening
Jun  8 10:49:25 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | The device client has been disconnected^M
Jun  8 10:49:25 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Error: Time:Tue Jun  8 10:49:25 2021 File:/home/claudio/legatoWorkspace/AwsProject/mqttClients/mqttClientAzure/azure-c-shared-utility/adapters/tlsio_mbedtls.c Func:on_underlying_io_open_complete
Jun  8 10:49:25 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Error: Time:Tue Jun  8 10:49:25 2021 File:/home/claudio/legatoWorkspace/AwsProject/mqttClients/mqttClientAzure/azure-c-shared-utility/src/uws_client.c Func:on_underlying_io_open_complete Line:74
Jun  8 10:49:25 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | e request was sent.^M
Jun  8 10:49:25 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Error: Time:Tue Jun  8 10:49:25 2021 File:/home/claudio/legatoWorkspace/AwsProject/mqttClients/mqttClientAzure/azure-c-shared-utility/adapters/tlsio_mbedtls.c Func:tlsio_mbedtls_close Line:674 I
Jun  8 10:49:25 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | The device client has been disconnected^M
Jun  8 10:49:25 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Sending message 2 to IoTHub^M
Jun  8 10:49:25 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Sending message 3 to IoTHub^M
Jun  8 10:49:25 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Sending message 4 to IoTHub^M
Jun  8 10:49:25 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Sending message 5 to IoTHub^M
Jun  8 10:49:56 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Error: Time:Tue Jun  8 10:49:56 2021 File:/home/claudio/legatoWorkspace/AwsProject/mqttClients/mqttClientAzure/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:UpdateMqttConn
Jun  8 10:49:56 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | r CONNACK^M
Jun  8 10:49:56 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Error: Time:Tue Jun  8 10:49:56 2021 File:/home/claudio/legatoWorkspace/AwsProject/mqttClients/mqttClientAzure/azure-c-shared-utility/src/uws_client.c Func:uws_client_close_async Line:1765 close
Jun  8 10:49:57 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Error: Time:Tue Jun  8 10:49:57 2021 File:/home/claudio/legatoWorkspace/AwsProject/mqttClients/mqttClientAzure/azure-c-shared-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:1068
Jun  8 10:49:57 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | errno: 22
Jun  8 10:49:57 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Error: Time:Tue Jun  8 10:49:57 2021 File:/home/claudio/legatoWorkspace/AwsProject/mqttClients/mqttClientAzure/azure-umqtt-c/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening
Jun  8 10:49:57 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | The device client has been disconnected^M
Jun  8 10:49:57 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Error: Time:Tue Jun  8 10:49:57 2021 File:/home/claudio/legatoWorkspace/AwsProject/mqttClients/mqttClientAzure/azure-c-shared-utility/adapters/tlsio_mbedtls.c Func:on_underlying_io_open_complete
Jun  8 10:49:57 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Error: Time:Tue Jun  8 10:49:57 2021 File:/home/claudio/legatoWorkspace/AwsProject/mqttClients/mqttClientAzure/azure-c-shared-utility/src/uws_client.c Func:on_underlying_io_open_complete Line:74
Jun  8 10:49:57 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | e request was sent.^M
Jun  8 10:49:57 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | Error: Time:Tue Jun  8 10:49:57 2021 File:/home/claudio/legatoWorkspace/AwsProject/mqttClients/mqttClientAzure/azure-c-shared-utility/adapters/tlsio_mbedtls.c Func:tlsio_mbedtls_close Line:674 I
Jun  8 10:49:57 fx30s user.info Legato:  INFO | mqttClientAzure[15101] | The device client has been disconnected^M

**Comment by ClaudioBaldo** [comment]
just for the record, I am using the same connection string with the sample code provided on Microsoft website and I can connect properly:

node SimulatedDevice-1.js "HostName=MYHUB.azure-devices.net;DeviceId=MYDEVICE;SharedAccessKey=MYKEY"
IoT Hub troubleshooting tutorial
Simulated device #1
Client connected

Just to confirm that the connection string is correct?

**Comment by danewalton** [comment]
Errno 22 is `EINVAL` so somehow the arguments to `recv()` look to be wrong. Are you able to check the arguments to that function when that happens?

**Comment by ClaudioBaldo** [comment]
This is where it is failing in the socketio_berkeley.c source:
(line 1053)received = recv(socket_io_instance->socket, socket_io_instance->recv_bytes, XIO_RECEIVE_BUFFER_SIZE, MSG_NOSIGNAL);

This is what I have logged:
socket_io_instance socket:10
socket_io_instance recv_bytes:10
socket_io_instance XIO_RECEIVE_BUFFER_SIZE:64
socket_io_instance MSG_NOSIGNAL:16384
socket_io_instance received:-1

Socketio_Failure: Receiving data from endpoint: errno=22

**Comment by danewalton** [comment]
`MSG_NOSIGNAL` suppresses SIGPIPE on send/recv calls. [We had a PR here](https://github.com/Azure/azure-c-shared-utility/pull/479/files) which defines it to 0 is a system doesn't support it. 

It looks like the flag value for it isn't 0 on your program:

> This is what I have logged:
> socket_io_instance socket:10
> socket_io_instance recv_bytes: (nothing is printed as I am printing %s and this the buffer for the rec data)
> socket_io_instance XIO_RECEIVE_BUFFER_SIZE:64
> socket_io_instance **MSG_NOSIGNAL:16384**
> socket_io_instance received:-1

By making it `0` you are essentially adding no flags to the call. It's possible your system doesn't support the option but a value is being passed anyways?

To test, at the top of the socket_io_berkeley where we have
```c
#ifndef MSG_NOSIGNAL
#define MSG_NOSIGNAL 0
#endif
```

you can try changing it to 
```c
#define MSG_NOSIGNAL 0
```
to redefine it to a no-op flag. See if things work with that?

**Comment by ClaudioBaldo** [comment]
This was fixed, the printout was from before manually changing the flags to 0.
I did rad about the flag and the suppression of SIGPIPE, my question is what imply this on the overall operation of the sdk if any?

**Comment by danewalton** [comment]
[Here's a decent writeup here on why we would want to.](http://www.microhowto.info/howto/ignore_sigpipe_without_affecting_other_threads_in_a_process.html#:~:text=Objective.%20To%20disregard%20SIGPIPE%20within%20a%20given%20thread,in%20a%20pipeline%2C%20but%20in%20most%20other%20)

I'll copy a blurb here:

> If you attempt to write to a broken pipe or a disconnected socket then the signal SIGPIPE will be raised, and its default behaviour is to terminate the process responsible. This behaviour is appropriate for programs that are intended for use in a pipeline, but in most other circumstances it is undesirable and should be prevented.

We would rather not have the program crash but instead handle that condition.

I'll go ahead and close this for now but please let us know if you would like it reopened.
