### ISSUE TITLE
Complex JSON arrays in ModuleTwin reported do not work

### ISSUE THREAD

**Issue by gri6507** [Azure/azure-iot-sdk-c#1966]
### PROBLEM:
It appears that simple JSON arrays (e.g. `"xxx" : [ "foo", "bar"]`) in ModuleTwin reported work fine, but more complicated JSON arrays (e.g. `"xxx" : [ {"foo" : [ "bar"] } ]`) do not. Such updates simply don't appear in the azure portal when viewing the module twin.

According to https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-module-twins#tags-and-properties-format, I do not see any reason why the "complicated" example above should not work.

This was tested with `LTS_01_2021_Ref01`, which, at the time of this bug report, is the latest release.

### Additional requested info
- developed on Ubuntu Focal, GCC 9.3
- azure iot c sdk version LTS_01_2021_Ref01
- protocol MQTT
- There are no warnings or error listed in `iotedge` daemon syslog, my module log, or the `edgeHub` log when such a module twin is reported.

### MINIMAL CODE:
```c++
#include <iothub.h>
#include <iothub_module_client_ll.h>
#include <iothub_client_options.h>
#include <azure_c_shared_utility/threadapi.h>
#include <iothubtransportmqtt.h>

int main(void)
{
  int retval = 1;
  IOTHUB_MODULE_CLIENT_LL_HANDLE handle;

  do
  {
    printf("Starting ...\n"); fflush(NULL);
    if (0 != IoTHub_Init())
    {
      printf("Failed to initialize the platform.\n"); fflush(NULL);
      break;
    }

    handle = IoTHubModuleClient_LL_CreateFromEnvironment(MQTT_Protocol);
    if (NULL == handle)
    {
      printf("IoTHubModuleClient_LL_CreateFromEnvironment failed\n"); fflush(NULL);
      break;
    }

    bool traceOn = true;
    IoTHubModuleClient_LL_SetOption(handle, OPTION_LOG_TRACE, &traceOn);


    int i=0;
    while (true)
    {
      IoTHubModuleClient_LL_DoWork(handle);
      ThreadAPI_Sleep(100);
      switch (i)
      {
        case 0:
        {
          const char xx0[] = "null";
          printf("About to set %s\n", xx0); fflush(NULL);
          if (IOTHUB_CLIENT_OK != IoTHubModuleClient_LL_SendReportedState(handle, (const unsigned char *)xx0, strlen(xx0), NULL, NULL))
          {
            printf("IoTHubModuleClient_LL_SendReportedState problem\n"); fflush(NULL);
          }
          break;
        }
        case 1:
        {
          const char xx1[] = "{\"xx1\":\"abc\"}";
          printf("About to set %s\n", xx1); fflush(NULL);
          if (IOTHUB_CLIENT_OK != IoTHubModuleClient_LL_SendReportedState(handle, (const unsigned char *)xx1, strlen(xx1), NULL, NULL))
          {
            printf("IoTHubModuleClient_LL_SendReportedState problem\n"); fflush(NULL);
          }
          break;
        }
        
        // This block does not work!!!!
        case 2:
        {
          const char xx2[] = "{\"xx2\":[{\"abc\":{\"foo\":[1,2,3],\"bar\":[{\"a\":\"yes\"},{\"b\":\"no\"}]}},{\"def\":{\"foo\":[null],\"bar\":[{\"a\":\"yes\"},{\"b\":\"no\"}]}}]}";
          printf("About to set %s\n", xx2); fflush(NULL);
          if (IOTHUB_CLIENT_OK != IoTHubModuleClient_LL_SendReportedState(handle, (const unsigned char *)xx2, strlen(xx2), NULL, NULL))
          {
            printf("IoTHubModuleClient_LL_SendReportedState problem\n"); fflush(NULL);
          }
          break;
        }
        default:
          break;
      }
      i++;
    }
  } while(false);

  if (NULL != handle)
  {
    IoTHubModuleClient_LL_Destroy(handle);
  }
  IoTHub_Deinit();
  printf("Terminated !!!\n"); fflush(NULL);

  return retval;
}
```

**Comment by ericwol-msft** [comment]
It looks like it does not like "foo":[null]

What happens if you put a values there?
`const char xx2[] = "{\"xx2\":[{\"abc\":{\"foo\":[1,2,3],\"bar\":[{\"a\":\"yes\"},{\"b\":\"no\"}]}},{\"def\":{\"foo\":"value",\"bar\":[{\"a\":\"yes\"},{\"b\":\"no\"}]}}]}";`

**Comment by gri6507** [comment]
> It looks like it does not like "foo":[null]

That is only part of it. When I originally stumbled on this, there were other cases with non `null` entries in arrays. It looked like the issue was with anything that is an array of more than just a simple `string` or a `float`

> What happens if ...

Unfortunately, I have moved on to other things for now. It's not that easy for me to go back to this investigation at this point. Luckily, I provided the very simple code in this ticket so that someone else could verify that

**Comment by ericwol-msft** [comment]
null types are not supported 

https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/iot-hub/iot-hub-devguide-device-twins.md#tags-and-properties-format

only top level properties can be set to null, which removed the property

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#back-end-operations

**Comment by ericwol-msft** [comment]
Closing this issue. I verified with the hub team that NULL values in complex types are not supported. We will update the documentation to make that more clearer. Thanks!
