### ISSUE TITLE
iothub_client_sample_upload_to_blob sample returns error "Number of active file upload requests exceeded limit"

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#197]
I am using blob upload sample( iothub_client_sample_upload_to_blob ) to upload file to Azure blob storage associated with Azure IoT Hub. For a **particular** device, I am getting below error message.

> Error: Time:Mon Aug  7 17:16:28 2017 File:/home/user-name/Azure/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:594 Failure in HTTP communication: server reply code is 403
> Info: HTTP Response:{"Message":"{\"errorCode\":403006,\"trackingId\":\"b9fc9b8f8c78496fa241e821bcb43d71-G:10-TimeStamp:08/07/2017 11:46:26\",\"message\":\"Number of active file upload requests exceeded limit\",\"timestampUtc\":\"2017-08-07T11:46:26.9703352Z\"}","ExceptionMessage":""}
> Error: Time:Mon Aug  7 17:16:28 2017 File:/home/user-name/Azure/iot-edge/deps/iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_step1and2 Line:394 HTTP code was 403

All devices except this one can upload files to blob storage. Why am I getting this error? Any document reference?

**Comment by kiranpradeep** [comment]
UPDATE: Today( on 8-Aug-2017 ) the same device is no more giving the error. We are able to upload files to IoTHub attached blob storage.

But the important question is: Why did IoTHub give error response yesterday( 7-Aug-2017)  for the same device? We would like to know what caused the error condition.

**Comment by kiranpradeep** [comment]
UPDATE: Today ( 10-Aug-2017 ), I am getting the same error again. Any document referring this error message.

**Comment by tameraw** [comment]
@kiranpradeep - We'll investigate this issue.

**Comment by ewertons** [comment]
Hi @kiranpradeep, we are investigating this issue but we need more information.

What is the version of the IoTHubClient you are experimenting with?
Also, which environment are you using?

Could you give us more details about the scenario of the device that is failing?
Are you running the sample several times in a row? Are you running it in parallel (using threads, e.g.)?
Is the sample running all the way to completion, with no errors every time?
Do you see any connection failures happening before the failure you posted originally?

It would be great if you could provide complete logs from the whole execution, including [enabling verbose logs](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp.c#L177) in the sample before running it.

Please provide as many details as possible so we can address this quickly. Apologies for keeping this issue on the backlog for so long, we will ensure it gets resolved as soon as possible.

**Comment by kiranpradeep** [comment]
@ewertons I am no more able to reproduce this issue and hence closing. I understand it was a bug in my application code and not to do with SDK. But the error message was confusing as my application was single threaded and could never invoke parallel connections.

**Comment by ewertons** [comment]
Hey @kiranpradeed,

thanks for the reply. I am glad you were able to pin point the failure.
Could you share details of what the bug in your application was? that will help us guard against this failure in the future.
Also, we are discussing adding an option to cancel a download, which would serve as a workaround in case things go wrong during an upload.

Any extra details you can provide would help us greatly.

Please let us know if there is anything we can help with.

Thank you once again for using the Azure IoT SDK.
