### ISSUE TITLE
Device registration for AMQP Protocol throws error, however there is no issue observed

### ISSUE THREAD

**Issue by ykgw-moorthy** [Azure/azure-iot-sdk-c#1973]
Development Machine, OS, Compiler (and Other Relevant Toolchain Info)

Compiled on Windows10 Enterprise with MSVC. compiler

**SDK Version** 

LTS_01_2021_Ref01
Release on Jan 23

**Protocol**

AMQP

**Describe the Bug**

When Device provisioning is used for register a device (using Prov_Device_Register_Device API)with AMQP Protocol, throws error(see below). But there is no issue observed with this behavior. Please let us know if there is any deviation from expected behavior. 
Similar issue is already reported long back, but I don't know, if it is  already considered to fix.
**Provision Device Client Errors with Simulated TPM SampleCode. · Issue #1363 · Azure/azure-iot-sdk-c (github.com)**

Following is error details we observed.
```
27-05-2021 22:04:27 INFO  Registering Device........................................................
27-05-2021 22:04:29 INFO  Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
27-05-2021 22:04:30 INFO  Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
Error: Time:Thu May 27 22:04:32 2021 File:D:\CloudCommunicator\TI\ydx-edge-cloud-communicator\external\azure\azure-iot-sdk-c_LTS_01_2021_Ref01\uamqp\src\amqpvalue.c Func:amqpvalue_get_inplace_described_value Line:7088 NULL value
Error: Time:Thu May 27 22:04:32 2021 File:D:\CloudCommunicator\TI\ydx-edge-cloud-communicator\external\azure\azure-iot-sdk-c_LTS_01_2021_Ref01\provisioning_client\src\prov_transport_amqp_common.c Func:get_retry_after_property Line:341 Failure getting application property description
```

Could you please confirm if this behavior doesn't affect the reliability of message sending mechanism using AMQP Protocol?
Thanks in Advance..

**Comment by ericwol-msft** [comment]
You can ignore this error. I have a PR (#1975 1975) that will stop these error from being reported.

**Comment by ericwol-msft** [comment]
this issue is now fixed
