### ISSUE TITLE
OTA file download taking long time 

### ISSUE THREAD

**Issue by SS-iot-devoted** [Azure/azure-iot-sdk-c#1977]
Hello friends working on a project in which I'm  downloads firmware by OTA is taking near by 2 min. I think that id too long time for 420KB file .. other thing is Im testing the same thing with AWS in that case file is hust downloaded in ~33sec  so Im looking for help like what can be issue or is there sockets configuration or else ???

**Comment by ericwol-msft** [comment]
Below is a link for the Device Update for IoT Hub Troubleshooting Guide

https://docs.microsoft.com/en-us/azure/iot-hub-device-update/troubleshoot-device-update

You can also contact Microsoft Support for help in resolving your issue.

https://docs.microsoft.com/en-us/azure/iot-hub-device-update/troubleshoot-device-update#contact

**Comment by cmknox** [comment]
@SS-iot-devoted thanks for reporting this issue, let's definitely have a look to determine what's going on. The best thing to do next is to get logs from you. We have a script that makes this easy. You can access it here, https://github.com/Azure/iot-hub-device-update/blob/main/scripts/adu-diag.sh. 

Can you please run that and share the output?

**Comment by danewalton** [comment]
closing for now due to inactivity
