### ISSUE TITLE
CC3200: Mqtt-Connection with Azure IOThub

### ISSUE THREAD

**Issue by MaHaXWS** [Azure/azure-iot-sdk-c#199]
Hi
We are currently developing a device with the Azure Iot SDK C for the TI cc3200 Prozessor.  (CC3200 SDK v1.2.0 release)

As OS we are using the RIOT-OS.

At the moment we are able to make a SSL connection to the IOThub with Ports (443 and 8883).

See the following code example, which should only demonstrate the ssl-connection to the server (the code will be used in a tlsio_cc3200.c adapter):

At the board initialisation we make the WIFI-connection and get the time from NTP-timeserver. (This part seem to be OK)

From the main-Function the following ssl-function is called:
`#include "socket.h"
#include "common.h"

//#define SL_SSL_CA_CERT_FILE_NAME        "/cert/google.der"
#define SL_SSL_CA_CERT_FILE_NAME        "/cert/rootCA.der"

//#define SSL_PORT     443 // Port 443 Seems to work, but we do not want to use MQTT over websocket

#define SSL_PORT     8883

static long ssltest(void)
{
    long lRetVal = -1;

    SlSockAddrIn_t    Addr;
    int    iAddrSize;
    unsigned int uiIP;
    int iSockID;

//    signed char    *g_Host = "www.google.com";   // just used as test
    signed char    *g_Host = "TestIoTHub.azure-devices.net";

    lRetVal = Network_IF_GetHostIP((char*)g_Host,(unsigned long*)&uiIP);

    Addr.sin_family = SL_AF_INET;
    Addr.sin_port = sl_Htons(SSL_PORT);
    Addr.sin_addr.s_addr = sl_Htonl(uiIP);
    iAddrSize = sizeof(SlSockAddrIn_t);
    //
    // opens a secure socket
    //
    iSockID = sl_Socket(SL_AF_INET,SL_SOCK_STREAM, SL_SEC_SOCKET);  // all return-values are checked!!!
    if( iSockID < 0 )
    {   printf("Device unable to create secure socket \n\r");
        return lRetVal; }

    //
    // configure the socket as SL_SO_SEC_METHOD_SSLv3_TLSV1_2 (removed for readabbility)
    //

    //
    //configure the socket with CA certificate - for server verification
    //
    lRetVal = sl_SetSockOpt(iSockID, SL_SOL_SOCKET, SL_SO_SECURE_FILES_CA_FILE_NAME, SL_SSL_CA_CERT_FILE_NAME, strlen(SL_SSL_CA_CERT_FILE_NAME));     // all return-values are checked!!!
    //if(lRetVal < 0)
   
    lRetVal = sl_SetSockOpt(iSockID, SL_SOL_SOCKET, SO_SECURE_DOMAIN_NAME_VERIFICATION, g_Host, strlen((const char *)g_Host));    // all return-values are checked!!!
   // if( lRetVal < 0 )
   
    SlDateTime_t timeToGet;

    XWS_GetSLTIME(&timeToGet);  // <- sl_DevGet(SL_DEVICE_GENERAL_CONFIGURATION,&configOpt, &configLen,(_u8*)(timeToGet));
    printf("Day %d,Mon %d,Year %d,Hour %d,Min %d,Sec %d\n",timeToGet.sl_tm_day,timeToGet.sl_tm_mon,timeToGet.sl_tm_year,
            timeToGet.sl_tm_hour,timeToGet.sl_tm_min,timeToGet.sl_tm_sec);

    /* connect to the peer device - server */
    lRetVal = sl_Connect(iSockID, ( SlSockAddr_t *)&Addr, iAddrSize);    // all return-values are checked!!!
    // if(lRetVal < 0)

    XWS_GetSLTIME(&timeToGet);  // <- sl_DevGet(SL_DEVICE_GENERAL_CONFIGURATION,&configOpt, &configLen,(_u8*)(timeToGet));  

//     Durring this call there is a Socket ERROR ("[SOCK ERROR]  -close socket (81) operation remote side down from sevcure to unsecure")

    printf("Day %d,Mon %d,Year %d,Hour %d,Min %d,Sec %d\n",timeToGet.sl_tm_day,timeToGet.sl_tm_mon,timeToGet.sl_tm_year,
            timeToGet.sl_tm_hour,timeToGet.sl_tm_min,timeToGet.sl_tm_sec);
    return 0;
}`

The Problem:

If we use Port 443 for Google or IOThub everything workes fine and we do not get an error!

If we use Port 8883 for Azure IOThub there happens a Socket ERROR ("[SOCK ERROR] -close socket (81) operation remote side down from sevcure to unsecure") during the second call to get the SL_DATE_TIME!

Does anyone have some suggestions what the problem might be?

Is it a problem of SimpleLink?

Is there any possibility to get an pre-release version of the official TI-addapter for cc32xx for azure IOT sdk? Who can I ask?

Best

MaHaXWS

**Comment by markrad** [comment]
I do not believe TI are developing an adapter layer for the CC3200. This device has only been certified for HTTP communication via the Azure IoT Hub client SDK in C.

_Mark Radbourne MSFT_

**Comment by MaHaXWS** [comment]
Do you know something about an adapter for cc3220

**Comment by markrad** [comment]
Hi @MaHaXWS,

I can only comment on software that has been released or definitely will be, particularly when we are talking about a third party developer. However, I have been in contact with TI and they are considering certifying the CC3220 for the Azure IoT Hub.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @MaHaXWS,

Texas Instruments have published a document that describes how to connect a CC3220 to the Azure IoT Hub. I have not tried this for myself but you can find the information here: http://dev.ti.com/tirex/#/?link=Software%2FSimpleLink%20SDK%20Plugins%2FSimpleLink%20CC32XX%20SDK%20Azure%20IoT%20Plugin. 

I hope this is useful to you. I am closing the issue now. 

_Mark Radbourne MSFT_
