### ISSUE TITLE
Linking error on Raspberry Pi

### ISSUE THREAD

**Issue by aegirsystems** [Azure/azure-iot-sdk-c#1990]
I am having a linking error when trying to develop on the raspberry pi - Azure-iot-sdk-c is an addon to an existing application that has been built so there was an active code base that was previously working - i have followed the instructions for issue 732 where the libraries need to be linked in a specific sequence, the include is as follows:

include_directories( ztdKigen PRIVATE
    ${ROOT_DIR}
    ${ROOT_DIR}/inc
    ${ROOT_DIR}/tls_stack/src   
    ${ROOT_DIR}/tls_stack/BearSSL/inc
    /usr/local/include/azureiot    
    /usr/local/include/azureiot/inc    
    /usr/local/include/azureiot/azure_umqtt_c    
    )

target_link_libraries(ztdKigen  
        iothub_client
        iothub_client_mqtt_transport
        prov_device_ll_client
        aziotsharedutil
        pthread
        curl
        ssl
        crypto       
        m
        umqtt     
        uhttp   
        uuid
        parson
        ${CMAKE_DL_LIBS} 
        ${ROOT_DIR}/lib/libiotsafe_driver.a 
        ${ROOT_DIR}/lib/libbearssl_kigen.a 
        )

but when i try to implement the the code, in this case the umqtt functionality i get the following:

[100%] Linking C executable proj1
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): in function `addUserPropertiesTouMqttMessage':
iothubtransport_mqtt_common.c:(.text+0xd64): undefined reference to `IoTHubMessage_Properties'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): in function `addSystemPropertiesTouMqttMessage':
iothubtransport_mqtt_common.c:(.text+0x13a0): undefined reference to `IoTHubMessage_IsSecurityMessage'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x13b0): undefined reference to `IoTHubMessage_GetCorrelationId'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x1408): undefined reference to `IoTHubMessage_GetMessageId'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x1460): undefined reference to `IoTHubMessage_GetContentTypeSystemProperty'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x14b8): undefined reference to `IoTHubMessage_GetContentEncodingSystemProperty'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x1534): undefined reference to `IoTHubMessage_GetMessageCreationTimeUtcSystemProperty'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): in function `addDiagnosticPropertiesTouMqttMessage':
iothubtransport_mqtt_common.c:(.text+0x16ac): undefined reference to `IoTHubMessage_GetDiagnosticPropertyData'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): in function `addPropertiesTouMqttMessage':
iothubtransport_mqtt_common.c:(.text+0x1cac): undefined reference to `IoTHubMessage_GetOutputName'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): in function `addInputNamePropertyToMsg':
iothubtransport_mqtt_common.c:(.text+0x2fdc): undefined reference to `IoTHubMessage_SetInputName'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): in function `setMqttMessagePropertyIfPossible':
iothubtransport_mqtt_common.c:(.text+0x31c8): undefined reference to `IoTHubMessage_SetMessageCreationTimeUtcSystemProperty'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x3278): undefined reference to `IoTHubMessage_SetConnectionDeviceId'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x331c): undefined reference to `IoTHubMessage_SetConnectionModuleId'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x33cc): undefined reference to `IoTHubMessage_SetMessageId'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x3470): undefined reference to `IoTHubMessage_SetCorrelationId'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x3514): undefined reference to `IoTHubMessage_SetMessageUserIdSystemProperty'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x35c4): undefined reference to `IoTHubMessage_SetContentTypeSystemProperty'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x3668): undefined reference to `IoTHubMessage_SetContentEncodingSystemProperty'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): in function `extractMqttProperties':
iothubtransport_mqtt_common.c:(.text+0x37d4): undefined reference to `IoTHubMessage_Properties'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): in function `processIncomingMessageNotification':
iothubtransport_mqtt_common.c:(.text+0x45bc): undefined reference to `IoTHubMessage_CreateFromByteArray'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x4804): undefined reference to `IoTHubMessage_Destroy'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x4890): undefined reference to `IoTHubMessage_Destroy'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): in function `RetrieveMessagePayload':
iothubtransport_mqtt_common.c:(.text+0x57f8): undefined reference to `IoTHubMessage_GetContentType'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x5818): undefined reference to `IoTHubMessage_GetByteArray'
/usr/bin/ld: iothubtransport_mqtt_common.c:(.text+0x58a4): undefined reference to `IoTHubMessage_GetString'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): in function `IoTHubTransport_MQTT_Common_SendMessageDisposition':
iothubtransport_mqtt_common.c:(.text+0xa36c): undefined reference to `IoTHubMessage_Destroy'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): in function `IoTHubClient_Auth_CreateFromDeviceAuth':
iothub_client_authorization.c:(.text+0x6dc): undefined reference to `iothub_device_auth_create'
/usr/bin/ld: iothub_client_authorization.c:(.text+0x784): undefined reference to `iothub_device_auth_get_type'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): in function `IoTHubClient_Auth_Destroy':
iothub_client_authorization.c:(.text+0x81c): undefined reference to `iothub_device_auth_destroy'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): in function `IoTHubClient_Auth_Set_xio_Certificate':
iothub_client_authorization.c:(.text+0xa54): undefined reference to `iothub_device_auth_generate_credentials'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): in function `IoTHubClient_Auth_Get_x509_info':
iothub_client_authorization.c:(.text+0xd5c): undefined reference to `iothub_device_auth_generate_credentials'
/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): in function `IoTHubClient_Auth_Get_SasToken':
iothub_client_authorization.c:(.text+0x1138): undefined reference to `iothub_device_auth_generate_credentials'
/usr/bin/ld: //usr/local/lib/libumqtt.a(mqtt_message.c.o): in function `mqttmessage_getTopicLevels':
mqtt_message.c:(.text+0x908): undefined reference to `StringToken_Split'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ztdKigen.dir/build.make:221: ztdKigen] Error 1
make[1]: *** [CMakeFiles/Makefile2:131: CMakeFiles/ztdKigen.dir/all] Error 2
make: *** [Makefile:117: all] Error 2

been working on this for a couple of days trying to figure out what i am missing, it is probably something fairly streightforward but i probably can't see the trees for the forest - any help would be greatly appreciated.

**Comment by ericwol-msft** [comment]
below are a few links that might be helpful for you building on a Raspberry Pi

https://github.com/Azure/azure-iot-sdk-c/blob/1c1b2c1a3a00bc445165dde44eb3e58ca999ec23/doc/SDK_cross_compile_example.md

https://github.com/Azure/azure-iot-sdk-c/blob/1c1b2c1a3a00bc445165dde44eb3e58ca999ec23/jenkins/raspberrypi_c.sh

**Comment by aegirsystems** [comment]
ok, so is there something specific to the azure-iot-sdk-c that is different from normal development on the raspberry pi - the problem seems to be not the application linking its own libraries but inside the sdk libraries not finding their associate libraries. i pull azure out and the app links and runs as expected. 

/usr/bin/ld: //usr/local/lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): in function addUserPropertiesTouMqttMessage': iothubtransport_mqtt_common.c:(.text+0xd64): undefined reference to IoTHubMessage_Properties'

the  instructions for issue 732 seemed promising but did not fix the issue. 

will keep looking

**Comment by aegirsystems** [comment]
The difference between your links is i am not trying to cross compile the libraries, i am working on the raspberry pi itself. is there something different in the compile configuration files that needs to be updated.

**Comment by danewalton** [comment]
Hi @aegirsystems so I went in and added a section to print out the libs which are linked to our samples to get an idea of what's being linked
![image](https://user-images.githubusercontent.com/36710865/124196982-629d1f00-da82-11eb-8061-e75e4cf3097f.png)
You can ignore the first four or so lines which are for transports that aren't relevant. But it looks like we double include the `aziotsharedutil` to resolve the circular dependency. Can you try that to see if it helps? Otherwise we can look to use compiler flags.

**Comment by danewalton** [comment]
Going to go ahead and close this for inactivity. Please let us know if you would like it reopened.
