### ISSUE TITLE
Application stops sending data to IoT hub after few weeks

### ISSUE THREAD

**Issue by vinayhasyagar3636** [Azure/azure-iot-sdk-c#1992]
**Development Machine**
Cross compiled on Ubuntu 18.04

Protocol
**MQTT**

**Environment**
armV5

I am using azure-iot-sdk-c for one of my applications. The application will be running on a Gateway which collects data from sensors and transfers it to IoT hub. The problem is, after 2-3 weeks the application stops sending data to IoT hub. Below is my code.
```
for (;;)
{
	ThreadAPI_Sleep(1);

	if(iothub_info.connected == 1)
	{
		int bytes = 0;
		if ((bytes = mq_receive (qd_server, in_buffer, MSG_BUFFER_SIZE, NULL)) != -1)
		{
			PushDataToIotHub(in_buffer);
		}
	}
}
```
Above code transfers data to IoT hub if application receives any data from the queue
```
void PushDataToIotHub(const char * message)
{
    EVENT_INSTANCE device1_event;
    strncpy(device1_event.deviceId, dps_config.deviceid_name, strlen(dps_config.deviceid_name));
    if(iothub_info.connected != 0)
    {
        //send a message
        if(message != NULL)
        {
            IOTHUB_MESSAGE_HANDLE msg_handle = IoTHubMessage_CreateFromString(message);
            if(msg_handle == NULL)
            {
                printf("ERROR: iotHubMessageHandle is NULL \r\n");
            }
            else
            {
                //TODO get a logic to set the topic name dynamically
                IOTHUB_MESSAGE_RESULT res = IoTHubMessage_SetProperty(msg_handle, "topic", "stockpiletelemetry");
                if(IoTHubDeviceClient_LL_SendEventAsync(device_handle, msg_handle, SendConfirmationCallback, &device1_event) !=
                        IOTHUB_CLIENT_OK)
                {
                    printf("ERROR: IotHubDeviceClient_LL_SendEventAsync -------------- FAILED \r\n");
                }
                else
                {
                    msg_error_count++;
                    (void)printf("IoTHubClient_LL_SendEventAsync accepted message [%zu] for transmission to  IoT Hub.:%ld\r\n", 
                }
                //free the msg handler
                IoTHubMessage_Destroy(msg_handle);
            }
        }
    } 
}
```
Above code puts the data into linked list by calling **IoTHubDeviceClient_LL_SendEventAsync**  which will be handled by Azure SDK. 
Below is the thread (POSIX thread) which will transfer data into IoT hub. I have used **LL** based APIs . So I have to call **DoWork** method explicitly to transfer the data to IoT hub
```
void *azure_sync_thread(void *args)
{
    while (1)
    {
        IoTHubDeviceClient_LL_DoWork(device_handle);
        ThreadAPI_Sleep(5);
    }
}
```
This works fine until 2-3 weeks. After that data stops flowing to IoT hub. I have to restart the application to once again push data to IoT hub. 
I could not see any connectivity issue with IoT hub. I have registered the call back to see the connectivity status.
```
static void iothub_connection_status(IOTHUB_CLIENT_CONNECTION_STATUS result, 
                                     IOTHUB_CLIENT_CONNECTION_STATUS_REASON reason, 
                                     void* user_context)
{
    // printf("%s: resason: %d \n", __func__, (int)reason);
    if (user_context == NULL)
    {
        printf("iothub_connection_status user_context is NULL\r\n");
    }
    else
    {
        IOTHUB_CLIENT_INFO* iothub_info = (IOTHUB_CLIENT_INFO*)user_context;
        if (result == IOTHUB_CLIENT_CONNECTION_AUTHENTICATED)
        {
            iothub_info->connected = 1;
        }
        else
        {
            iothub_info->connected = 0;
            iothub_info->stop_running = 1;
        }
    }
}
```
The only problem I could see is that, after 2-3 weeks, it stops to give the confirmation message from the IoT hub. 
```
void SendConfirmationCallback(IOTHUB_CLIENT_CONFIRMATION_RESULT result, void* userContextCallback)
{
	msg_error_count--;
	EVENT_INSTANCE* event_info = (EVENT_INSTANCE*)userContextCallback;
	(void)printf("Confirmation msg rcvd, result[%s], msg_err_cnt[%ld]\r\n", 
	                   MU_ENUM_TO_STRING(PROV_DEVICE_REG_STATUS, result),
	                   msg_error_count);
}
```
The above callback never gets called after some time (2-3 weeks). I have to restart the application.  So I am assuming that the data is not reaching the IoT hub. I could not even see the data in **Device Explorer/ Azure IoT explorer**. But application receives data from the queue every time and it calls **IoTHubDeviceClient_LL_SendEventAsync** method and every time it succeeds.
Please someone guide me how to debug the issue and probably a solution would really help
Thank you

**Comment by ericwol-msft** [comment]
Can you capture trace logs?

        bool traceOn = true;
        (void)IoTHubDeviceClient_SetOption(device_handle, OPTION_LOG_TRACE, &traceOn);

**Comment by vinayhasyagar3636** [comment]
@ericwol-msft Thank you for your response. I have already enabled trace in the application as you have mentioned. But the problem is, application is running in background which is added to start-stop-daemon. The logs of SDK will be written to **stdout** which will in turn written to **/dev/null** . I could use **strace** tool by attaching process ID to see logs. But its not giving complete logs.
As I said, the problem will come after **2-3 weeks of starting of application**. Until then there will not be problem. But I saw some time it gets disconnected from IoT hub and reconnects back within 2-3 sec. We are using MQTT protocol as transport layer. Keep alive configuration is set to default i.e 4 min. Here is the log from **iothub_connection_status** callback when disconnect and connect happens.
```
1623687347 connected  0 stop running : 1 reason :  7  
1623687348 connected  1 stop running : 0 reason :  6
```
When it disconnected reason 7 means **IOTHUB_CLIENT_CONNECTION_NO_PING_RESPONSE** . But it gets reconnected within 1-2 sec. Please let me know if you any additional details
Thank you

**Comment by vinayhasyagar3636** [comment]
Update:

The problem has once again occured. Sometimes I could see below failures. Could this be an issue?
Below are the logs obtained using strace tool
```
11:55:15 IoTHubClient_LL_SendEventAsync accepted message [3441] for transmission to  IoT Hub
11:55:15 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: messages/events/topic=stockpiletelemetry | PACKET_ID: 3479 | PAYLOAD_LEN: 434\r\n
**Error: Time:Sat Jul  3 11:59:02 2021 File:/home/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:1064 Socketio_Failure: Receiving data from endpoint: errno=110.\r\n**
** 11:59:02 iothub_connection_status, connected:0 \n->** 
11:59:04 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: api-version=2020-09-30&DeviceClientType=iothubclient%2f1.3.9%20(native%3b%20Linux%3b%20armv5tejl) | CLEAN: 0\r\n<- 
11:59:04 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0\r\n
** 11:59:04 iothub_connection_status, connected:1 \n->**
```

```
12:56:27 IoTHubClient_LL_SendEventAsync accepted message [3444] for transmission to  IoT Hub.
12:56:27 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME:messages/events/topic=stockpiletelemetry | PACKET_ID: 3483 | PAYLOAD_LEN: 434\r\n
**Error: Time:Sat Jul  3 13:02:06 2021 File:/home/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:1064 Socketio_Failure: Receiving data from endpoint: errno=110.\r\n**
**13:02:06 iothub_connection_status, connected:0 \n->** 
13:02:08 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: api-version=2020-09-30&DeviceClientType=iothubclient%2f1.3.9%20(native%3b%20Linux%3b%20armv5tejl) | CLEAN: 0\r\n<- 
13:02:09 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0\r\n
**13:02:09 iothub_connection_status, connected:1 \n->** 
13:02:09 SUBSCRIBE | PACKET_ID: 3484 | TOPIC_NAME: "topic name is deleted"# | QOS: 1\r\n<- 
13:02:09 SUBACK | PACKET_ID: 3484 | RETURN_CODE: 1\r\n
**13:08:09 iothub_connection_status, connected:0 \n->** 
13:08:11 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: \api-version=2020-09-30&DeviceClientType=iothubclient%2f1.3.9%20(native%3b%20Linux%3b%20armv5tejl) | CLEAN: 0\r\n<- 
13:08:11 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0\r\n
**13:08:11 iothub_connection_status, connected:1 \n->** 
13:08:11 SUBSCRIBE | PACKET_ID: 3485 | TOPIC_NAME: devices/messages/devicebound/# | QOS: 1\r\n<- 
13:08:12 SUBACK | PACKET_ID: 3485 | RETURN_CODE: 1
```


```
13:56:07 IoTHubClient_LL_SendEventAsync accepted message [3447] for transmission to  IoT Hub.
**Error: Time:Sat Jul  3 13:57:30 2021 File:/home/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:1064 Socketio_Failure: Receiving data from endpoint: errno=110.\r\n**
**13:57:30 iothub_connection_status, connected:0 \n->** 
13:57:32 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: ?api-version=2020-09-30&DeviceClientType=iothubclient%2f1.3.9%20(native%3b%20Linux%3b%20armv5tejl) | CLEAN: 0\r\n<- 
13:57:32 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0\r\n
**13:57:32 iothub_connection_status, connected:1 \n->** 
13:57:32 SUBSCRIBE | PACKET_ID: 3489 | TOPIC_NAME: "topic name is deleted"# | QOS: 1\r\n<- 
13:57:33 SUBACK | PACKET_ID: 3489 | RETURN_CODE: 1\r\n
```


**iothub_connection_status, connected:1 \n->**  -----> connected : 1 means iothub is connected where as 0 means disconnected.
Now for none of the messages sent we are getting the confirmation message from the IoT hub. But **IoTHubClient_LL_SendEventAsync** api is returning as success and **IoTHubDeviceClient_LL_DoWork** is getting executed every 5ms. 

why does this error occur? **Error: Time:Sat Jul  3 13:57:30 2021 File:/home/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:1064 Socketio_Failure: Receiving data from endpoint: errno=110.\r\n**
What is errno= 110?

This issue occured after 45 days of the device client application started. If I restart the device then it will work and problem comes after many days. 
**Also, I am using azure-iot-sdk-version 1.3.9.** 
please go through the logs and suggest some solutions.

**Comment by vinayhasyagar3636** [comment]
Hi @ericwol-msft ,
Any suggestions on this?

**Comment by danewalton** [comment]
Hi @vinayhasyagar3636 this is a really difficult bug to repro and diagnose. Over a period of 45 days, there could be a range of networking issues which could cause this not necessarily related to the SDK. While it's unfortunate, the important part here seems to be that the connection is recovering and reestablishing correct?

Might I suggest updating to the latest version of the SDK to see if that improves the situation?

**Comment by vinayhasyagar3636** [comment]
Thanks @danewalton for your response. We updated SDK which had the commit
SHA-1 [https://github.com/Azure/azure-iot-sdk-c/commit/6b6e2449672d229d4a0fc9503d8fd3b2b2dde5f1](url)

After updating, we are facing a new issue. When the device is running for a long time continuously (2-3 weeks), the SDK client always returns the status as **IOTHUB_CLIENT_SEND_STATUS_IDLE** after calling **IoTHubDeviceClient_LL_GetSendStatus** . The D2C packet will be sent every 1 min. When we restart the application/service the data will be sent correctly. Is this behavior expected? Other than restarting the service is there any other solution. Please let me know if you need any more details.
Thank you

**Comment by ericwol-msft** [comment]
Can you post the device logs when this happens?

**Comment by vinayhasyagar3636** [comment]
@ericwol-msft Event though we have set **OPTION_LOG_TRACE** to true, we can't see the logs as the application/service runs in the background. Do we have any other option to see the Azure-IoT-SDK-C logs?

**Comment by ericwol-msft** [comment]
You can set a customer logger by using [xlogging_set_log_function()](https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/xlogging-h/xlogging-set-log-function)

**Comment by danewalton** [comment]
Hey @vinayhasyagar3636 I'm curious.....I saw this issue here:
https://github.com/Azure/azure-c-shared-utility/issues/526
What size is the `int` on your system?

**Comment by vinayhasyagar3636** [comment]
Hi @danewalton 
Size of the **int** in our system is 4 bytes.
Size of **time_t** in our system is also 4 bytes.

**Comment by danewalton** [comment]
If that's the case then I'm curious if you're running into the same overflow issue. From that issue:

> The disconnect causes an invocation of the connection status callback with status IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED and reason IOTHUB_CLIENT_CONNECTION_NO_NETWORK, although the network is available, because a subsequent reconnection is successful.

which looks to be similar to your original issue.

**Comment by vinayhasyagar3636** [comment]
Any solution you would suggest? Is it fixed in azure-c-shared-utility?

**Comment by danewalton** [comment]
We have a fix going in [here](https://github.com/Azure/azure-c-shared-utility/pull/557) that you are free to pull and try out. Check out either the branch or master once it's merged in the c-utility submodule.

**Comment by vinayhasyagar3636** [comment]
Hey @danewalton Thank you. We will try and let know.

**Comment by danewalton** [comment]
Are you sure the data isn't being sent? This snippet here shows the logic for showing status idle:
https://github.com/Azure/azure-iot-sdk-c/blob/d1a663b8710893e95bc8421470aee03aa565a550/iothub_client/src/iothubtransport_mqtt_common.c#L3716-L3726

So if you are sending messages to hub infrequently, the message could be sent and removed from the list before the status API would return busy. Have you verified from the service side that they are not being received?

**Comment by vinayhasyagar3636** [comment]
Hi @danewalton 
Yes. We checked and verified. The packets are not received by IoT hub. Also, we did not receive any confirmation message in **SendConfirmationCallback()** API when this issue happened

**Comment by danewalton** [comment]
Hi @vinayhasyagar3636 are there any updates on this? Is the issue persisting? Even after pulling that c-utility update for the clock?

**Comment by vinayhasyagar3636** [comment]
Hi @danewalton  We are still monitoring to see whether the issue still persists or not. Previously this issue was observed after continuing running of the application for more than 45 days. We will update you on this.

**Comment by danewalton** [comment]
Hey @vinayhasyagar3636 just checking in here to see if this is something we need to look into.

**Comment by vinayhasyagar3636** [comment]
Hi @danewalton ,
The issue is still there and we did  a workaround by restarting the app if we do not get the confirmation message

**Comment by danewalton** [comment]
Got it. I'm going to go ahead and close this because the repro doesn't seem consistent and there don't seem to be any leads.
