### ISSUE TITLE
Limitation on messages which Azure-sdk buffer internally in offline mode.

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/azure-iot-sdk-c#1993]
I can see azure-sdk do buffering of messages in offline mode(d2c/reported..etc) and delivering message to IoTHub as soon as device gets online.

Few queries :-

Can you please let me know what is quota/limitation which sdk store messages in offline mode ?
How many messages/reported will be buffered by sdk  in offline mode?

**Comment by ericwol-msft** [comment]
There is no build in quota/limitation. You will have to listen to the IoTHubDeviceClient_SetConnectionStatusCallback events and gate/persist the messages going into the SDK based on the network/memory limitations of your device.

**Comment by rajaggrawal** [comment]
@ericwol-msft   Thanks for update.

Does sdk retries telemetry messages in case of failure ?  if yes , does it maintain sequence/order while retrying of messages ?

**Comment by ericwol-msft** [comment]
> Does sdk retries telemetry messages in case of failure ? 
Yes, until the message timeout, in which your message callback will be called.

> if yes , does it maintain sequence/order while retrying of messages ?
Yes, unless there are networking error when sending specific message.

**Comment by rajaggrawal** [comment]
> Yes, until the message timeout, in which your message callback will be called.
   
May i know how much time sdk retries ?
  
> Yes, unless there are networking error when sending specific message.
 
So in case of network error, unordered messages can be delivered to IoTHub ?

**Comment by danewalton** [comment]
Hi @rajaggrawal 
Link here to where the retry count is checked: https://github.com/Azure/azure-iot-sdk-c/blob/6b6e2449672d229d4a0fc9503d8fd3b2b2dde5f1/iothub_client/src/iothubtransport_mqtt_common.c#L2244

Link here for the value of that macro: https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L48

**Comment by rajaggrawal** [comment]
@danewalton  can user change MAX_SEND_RECOUNT_LIMIT  and timeout ?  does sdk support any function to changes these values ?

**Comment by danewalton** [comment]
No we do not have official support to change those values at this time.

**Comment by rajaggrawal** [comment]
thanks @danewalton .

I can see default retry policy for D2C over MQTT is IOTHUB_CLIENT_RETRY_EXPONENTIAL_BACKOFF_WITH_JITTER .
Retry algorithm is configurable by user for IoTHub connection , But i see its not configurable for D2C .
Would be grateful if you share me a document for D2C(telemetry) retry, OR help me to explain .

I need to implement **retry** for my application but before that i need to understand existing azure-sdk retry logic.
you already shared Retry count is 2 . But would like to know following.

1. How much time retry will happen for a message ?. for eg... if i send a message to sdk and device gets offline immediately , how long this message will be in memory of sdk ?  when i will get timeout in confirmation callback ? 
2. What is time interval in each retry.

**Comment by danewalton** [comment]
Does this thread help answer the questions?
https://github.com/Azure/azure-iot-sdk-c/issues/2070#issuecomment-911933492

Essentially you can queue up the messages again if you receive that confirmation result from the callback.

**Comment by danewalton** [comment]
Going to go ahead and close this for now for inactivity. Please let us know if you would like it reopened.
