### ISSUE TITLE
Fail to upload long Blob using mbedtls+compact

### ISSUE THREAD

**Issue by maallahatem** [Azure/azure-iot-sdk-c#1995]
When the sdk is compiled using **httpAPI_compact** and **mbedtls**, often the blob upload by chunk fails starting from 512Kb (chunk size).
The following log describes the HTTP failure during the operation

````
[DEBUG] -> 14:54:23 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: edge-ih-dev.azure-devices.net/myUserName/?api-version=2020-09-30&DeviceClientType=iothubclient%2f1.6.0%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
[DEBUG] <- 14:54:23 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
[DEBUG] -> 14:54:23 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/myUserName/messages/devicebound/# | QOS: 1 | TOPIC_NAME: $iothub/twin/res/# | QOS: 0 | TOPIC_NAME: $iothub/methods/POST/# | QOS: 0
[DEBUG] <- 14:54:23 SUBACK | PACKET_ID: 2 | RETURN_CODE: 1 | RETURN_CODE: 0 | RETURN_CODE: 0
[DEBUG] -> 14:54:23 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/GET/?$rid=3
[DEBUG] <- 14:54:23 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: QOS_VALUE_INVALID | TOPIC_NAME: $iothub/twin/res/200/?$rid=3 | PAYLOAD_LEN: 1248
[DEBUG] -> 14:54:23 SUBSCRIBE | PACKET_ID: 4 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/# | QOS: 0
[DEBUG] -> 14:54:23 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=5 | PAYLOAD_LEN: 64
[DEBUG] <- 14:54:24 SUBACK | PACKET_ID: 4 | RETURN_CODE: 0
[DEBUG] <- 14:54:24 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: QOS_VALUE_INVALID | TOPIC_NAME: $iothub/twin/res/204/?$rid=5&$version=6399 | PAYLOAD_LEN: 0
[DEBUG] -> 14:54:24 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=6 | PAYLOAD_LEN: 304
[DEBUG] <- 14:54:24 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: QOS_VALUE_INVALID | TOPIC_NAME: $iothub/twin/res/204/?$rid=6&$version=6400 | PAYLOAD_LEN: 0
[ERROR] Send timeout. The HTTP request is incomplete
[ERROR] Send content to HTTP failed (result = HTTPAPI_SEND_REQUEST_FAILED (6))
[ERROR] unable to recover sending to a working state
[ERROR] unable to HTTPAPIEX_ExecuteRequest
[ERROR] unable to Blob_UploadBlock. Returned value=3
[ERROR] Failed in invoking callback/sending blob step
[ERROR] unable to Blob_UploadFromSasUri
````
Note that the seem behavior is reproduced with blob block upload starting from 4MBytes
With other configuration like curl+openssl, the problem is not reproduced at all

**Comment by danewalton** [comment]
Reopened after transfer

**Comment by danewalton** [comment]
Are you able to get logs from mbedTLS or a Wireshark trace?

**Comment by maallahatem** [comment]
Hello,
Youn can find here a [mbedlts.log](https://github.com/Azure/azure-iot-sdk-c/files/6673381/mbedlts.log)

**Comment by ericwol-msft** [comment]
Does the files actually get created on the blob storage? I see a created http status response.

```
ssl_tls.c:4259: |4| 0x7fbf7402c088: 0000:  48 54 54 50 2f 31 2e 31 20 32 30 31 20 43 72 65  HTTP/1.1 201 Cre
ssl_tls.c:4259: |4| 0x7fbf7402c088: 0010:  61 74 65 64 0d 0a 43 6f 6e 74 65 6e 74 2d 4c 65  ated..Content-Le
ssl_tls.c:4259: |4| 0x7fbf7402c088: 0020:  6e 67 74 68 3a 20 30 0d 0a 43 6f 6e 74 65 6e 74  ngth: 0..Content
ssl_tls.c:4259: |4| 0x7fbf7402c088: 0030:  2d 4d 44 35 3a 20 5a 6c 2f 66 2f 33 4c 67 6a 54  -MD5: Zl/f/3LgjT
ssl_tls.c:4259: |4| 0x7fbf7402c088: 0040:  48 43 52 45 72 51 43 67 42 41 36 51 3d 3d 0d 0a  HCRErQCgBA6Q==..
ssl_tls.c:4259: |4| 0x7fbf7402c088: 0050:  53 65 72 76 65 72 3a 20 57 69 6e 64 6f 77 73 2d  Server: Windows-
ssl_tls.c:4259: |4| 0x7fbf7402c088: 0060:  41 7a 75 72 65 2d 42 6c 6f 62 2f 31 2e 30 20 4d  Azure-Blob/1.0 M
ssl_tls.c:4259: |4| 0x7fbf7402c088: 0070:  69 63 72 6f 73 6f 66 74 2d 48 54 54 50 41 50 49  icrosoft-HTTPAPI
ssl_tls.c:4259: |4| 0x7fbf7402c088: 0080:  2f 32 2e 30 0d 0a 78 2d 6d 73 2d 72 65 71 75 65  /2.0..x-ms-reque
ssl_tls.c:4259: |4| 0x7fbf7402c088: 0090:  73 74 2d 69 64 3a 20 31 32 64 35 38 34 34 62 2d  st-id: 12d5844b-
ssl_tls.c:4259: |4| 0x7fbf7402c088: 00a0:  35 30 31 65 2d 30 30 38 38 2d 31 37 39 62 2d 36  501e-0088-179b-6
ssl_tls.c:4259: |4| 0x7fbf7402c088: 00b0:  31 30 35 65 66 30 30 30 30 30 30 0d 0a 78 2d 6d  105ef000000..x-m
ssl_tls.c:4259: |4| 0x7fbf7402c088: 00c0:  73 2d 76 65 72 73 69 6f 6e 3a 20 32 30 31 38 2d  s-version: 2018-
ssl_tls.c:4259: |4| 0x7fbf7402c088: 00d0:  30 33 2d 32 38 0d 0a 78 2d 6d 73 2d 72 65 71 75  03-28..x-ms-requ
ssl_tls.c:4259: |4| 0x7fbf7402c088: 00e0:  65 73 74 2d 73 65 72 76 65 72 2d 65 6e 63 72 79  est-server-encry
ssl_tls.c:4259: |4| 0x7fbf7402c088: 00f0:  70 74 65 64 3a 20 74 72 75 65 0d 0a 44 61 74 65  pted: true..Date
ssl_tls.c:4259: |4| 0x7fbf7402c088: 0100:  3a 20 54 75 65 2c 20 31 35 20 4a 75 6e 20 32 30  : Tue, 15 Jun 20
ssl_tls.c:4259: |4| 0x7fbf7402c088: 0110:  32 31 20 30 34 3a 30 34 3a 35 37 20 47 4d 54 0d  21 04:04:57 GMT.
ssl_tls.c:4259: |4| 0x7fbf7402c088: 0120:  0a 0d 0a     
```                                    ...

**Comment by maallahatem** [comment]
No, the blob is not created on blob storage
In fact, the upload process goes to timeout as you can see here in the log:
````
ssl_tls.c:2696: |2| 0x7fbf7402c088: in_left: 0, nb_want: 5
ssl_tls.c:2720: |2| 0x7fbf7402c088: in_left: 0, nb_want: 5
[ERROR] Send timeout. The HTTP request is incomplete
[ERROR] Send content to HTTP failed (result = HTTPAPI_SEND_REQUEST_FAILED (6))
ssl_tls.c:8725: |2| 0x7fbf7402c088: => write close notify
ssl_tls.c:5250: |2| 0x7fbf7402c088: => send alert message
````
We are working to investigate the problem and propose a fix for it
I think the problem comes from the callback on_send_complete() in tlsio_mbedtls.c
In fact, the tlsio callback ìs never called in the case of fragmented request to avoid time out

````
tls_io_instance->send_complete_info.on_send_complete(ctx, send_result);
````
You can please double-check on your side if this is the root cause of the problem

**Comment by danewalton** [comment]
I believe this is fixed with the merged PR. Please let us know if you would like this reopened and thanks for the contribution!

**Comment by maallahatem** [comment]
Hi,
Thank you for accepting and merging the PR
You can close the issue, it's OK for me

Regards
________________________________
De : Dane Walton ***@***.***>
Envoyé : jeudi 12 août 2021 22:26
À : Azure/azure-iot-sdk-c ***@***.***>
Cc : Hatem Maalla ***@***.***>; Author ***@***.***>
Objet : Re: [Azure/azure-iot-sdk-c] Fail to upload long Blob using mbedtls+compact (#1995)


[External email: Use caution with links and attachments]

________________________________



I believe this is fixed with the merged PR. Please let us know if you would like this reopened and thanks for the contribution!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-iot-sdk-c%2Fissues%2F1995%23issuecomment-897945194&data=04%7C01%7Chatem.maalla%40non.se.com%7C05d5f2f0e08a42b955ac08d95dcf8920%7C6e51e1adc54b4b39b5980ffe9ae68fef%7C0%7C0%7C637643968201838806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VJsb1zK%2FJP%2FkvMovQOmhnzw2kl4g2ZYyxibc%2FNUDhJE%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATSJXYRU4EDJT6GNCHQEYEDT4QVAZANCNFSM46YCM2OQ&data=04%7C01%7Chatem.maalla%40non.se.com%7C05d5f2f0e08a42b955ac08d95dcf8920%7C6e51e1adc54b4b39b5980ffe9ae68fef%7C0%7C0%7C637643968201848762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OhU%2FVEF0igxOb9txS6UfxzTJNrXllW7GDomGfMsnfRA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Chatem.maalla%40non.se.com%7C05d5f2f0e08a42b955ac08d95dcf8920%7C6e51e1adc54b4b39b5980ffe9ae68fef%7C0%7C0%7C637643968201848762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xbYB2%2BoctBvlEaivd8QcF%2Bas1T6MbXqj5Puvei7seTs%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Chatem.maalla%40non.se.com%7C05d5f2f0e08a42b955ac08d95dcf8920%7C6e51e1adc54b4b39b5980ffe9ae68fef%7C0%7C0%7C637643968201848762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aquhL4169lwqjq73fZaW%2F2rVR%2BoY4xwXAtpiJJvlCbY%3D&reserved=0>.


Internal
