### ISSUE TITLE
Sending malformed packets when ServiceInfo.setText(byte[] text)

### ISSUE THREAD

**Issue by CCSrl** [Azure/azure-iot-sdk-c#1997]
I'm running ServiceInfo.setText() after registered with a created JmDNS and I'm getting some malformed packets when ServiceInfo.setText() is called. My code is shown as below:

import java.util.Timer;
import java.util.TimerTask;
import javax.jmdns.JmDNS;
import javax.jmdns.ServiceInfo;

JmDNS mJmdns;
ServiceInfo serviceInfo;
String txt = "HELLO";

protected void jmdnsRegisterService() {
String serviceType = "_otap._tcp.local."
InetAddress inetAddr = InetAddress.getByName("192.168.142.128");
serviceInfo = ServiceInfo.create(serviceType , "foo", 8585, txt);

mJmdns = JmDNS.create(inetAddr);

mJmdns .registerService(serviceInfo);
startSetTextTask();
}

private void startSetTextTask() {
        mRunning = true;
        mTimer = new Timer();
        mTimer.schedule(new setTextTask(), 10000, 10000); //delay 10 seconds
}

private void setTextTask() {
        try {
                    serviceInfo .setText(txt .getBytes());
            }catch (Exception ex) {
                System.out.println("setText failed: " + ex.getMessage());
            }
}

Below is the packet parsed in Wireshark which shows me that PTR query responses are malformed:

0000   01 00 5e 00 00 fb ba 9a 01 22 80 f8 08 00 45 00   ..^......"....E.
0010   00 7f c5 5b 40 00 ff 11 85 ed c0 a8 8e 80 e0 00   ...[@...........
0020   00 fb 14 e9 14 e9 00 6b 16 ae 00 00 84 00 00 00   .......k........
0030   00 03 00 00 00 00 05 5f 6f 74 61 70 04 5f 74 63   ......._otap._tc
0040   70 05 6c 6f 63 61 6c 00 00 0c 00 01 00 00 0e 0f   p.local.........
0050   00 06 03 66 6f 6f c0 0c c0 28 00 21 80 01 00 00   ...foo...(.!....
0060   0e 10 00 18 00 00 00 00 21 89 0f 31 39 32 2d 31   ........!..192-1
0070   36 38 2d 31 34 32 2d 31 32 38 c0 17 c0 28 00 10   68-142-128...(..
0080   80 01 00 00 0e 10 00 05 48 45 4c 4c 4f            ........HELLO

The Data length is 5 (00 05, which is really the length of RDATA) and the TXT Length is 72 (48, aka H). 
As Conclusion, there's 1 byte was missing in between Data length and TXT Length.

**Comment by danewalton** [comment]
opening and closing for internal tooling
