### ISSUE TITLE
Provisioning client with AMQP-WS uses an incorrect port when proxy is configured

### ISSUE THREAD

**Issue by corollaries** [Azure/azure-iot-sdk-c#1999]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
x86_64 Intel Industrial PC, Custom OS built with Yocto.

**SDK Version**
Azure IoT C SDK 0.2.0.0 (LTS_01_2021_Ref01)

**Protocol**
AMQP over WebSockets

**Description**
The destination port for outgoing requests is incorrectly set within `provisioning_client` when using a proxy in combination with AMQP over WebSockets. 

The `CONNECT` request is correctly sent to the proxy server but uses the configured proxy port as a destination port for the request instead of `443`:
```
TCP_DENIED/403 3866 CONNECT global.azure-devices-provisioning.net:3128
```

In `provisioning_client/src/prov_transport_mqtt_ws_client.c` the following code gets executed when a proxy is configured:
```
proxy_config.hostname = tls_io_config.hostname;
proxy_config.port = MQTT_WS_PORT_NUM;
proxy_config.proxy_hostname = proxy_info->host_address;
proxy_config.proxy_port = proxy_info->port;
proxy_config.username = proxy_info->username;
proxy_config.password = proxy_info->password;
```

In `provisioning_client/src/prov_transport_amqp_ws_client.c` it's the following:
```
proxy_config.hostname = tls_io_config.hostname;
proxy_config.port = proxy_info->port;
proxy_config.proxy_hostname = proxy_info->host_address;
proxy_config.proxy_port = proxy_info->port;
proxy_config.username = proxy_info->username;
proxy_config.password = proxy_info->password;
```

In the AMQP transport `proxy_config.port` is incorrectly set to the proxy port while it should be `PROV_AMQP_WS_PORT_NUM`. I have implemented a patch and tested it, and after making the change, the `provisioning_client` works like it should when using a proxy:
```
TCP_TUNNEL/200 8314 CONNECT global.azure-devices-provisioning.net:443
```

**Comment by ericwol-msft** [comment]
Thanks!! I have a PR with the fix.

**Comment by danewalton** [comment]
opening and closing for internal tooling
