### ISSUE TITLE
Will you upgrade libwebsocket ?

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdk-c#20]
Hi,

My understanding is that the SDK uses libwebsocket 1.6.0, on the same branch we have 1.6.3 which bring some corrections (we are chasing a weird crash, always showing ws cleanup, occurring time to time after weeks of runs..)
Between 1.6.0 and 1.6.3 it seems libwebsocket gets some bug fixes (especially e7f9232c1aa48f505c6a317bc25f0430933dab4e).

I don't read all release notes from 1.6.0 to 2.1.0, but it seems we also have bug fixes on the way, the drawback is, the SDK won't compile out of the box with a 2.1.0 upgrade.
Could we, at least, imagine we go from 1.6.0 to 1.6.3 ?

**Comment by anporumb** [comment]
Answer is: v1.6.3 is going to be checked in master tomorrow. I have done a dry run with it, and everything seems fine. Now there's a tiny wee little bit more that I need to do to actually have 1.6.3. Once that happens, I will let you know here in GitHub.

Best Regards,
Andrei Porumb

**Comment by lmussier** [comment]
Perfect, thanks !
(I'll let you close when it's done)

**Comment by anporumb** [comment]
It is in master. I am closing this issue now. 

Best Regards,
Andrei Porumb
