### ISSUE TITLE
Please add GSM support

### ISSUE THREAD

**Issue by Nakul93** [Azure/azure-iot-sdk-c#200]
Hello everyone,
Please someone add support for any GSM module (like SIM800/SIM900) for sending data to IOT Hub

**Comment by ewertons** [comment]
Hi @Nakul93 ,
thanks for your request, we will ask our PM to evaluate it.

- Microsoft Azure IoT Team

**Comment by olivierbloch** [comment]
Hi @Nakul93, As of today, you can do this already. The SDK leverages the data connection the underlying platform (OS, RTOS, other) makes available to apps.
We have tried to not have too much hardware specific controlling in the SDK itself, so I'd be interested to understand better what you would expect the SDK to do, and what you cannot do today with GSM Module connectivity.
Thanks

**Comment by Nakul93** [comment]
Hi @olivierbloch , First of all I am using a SIM800 module and like most of the GSM modules it uses AT commands to send data via internet and there seems to be no support for that in the SDK.
Currently I am trying to send data via HTTP and I can't use the CreateFromConnectionStringfunction directly so I am manually trying to POST the connection string and then the data, but I guess there is problem with SSL certification.
It would be great if SDK has the underlying functions for any GSM module or at least suggest a method to manually connect to IOT hub via HTTP without using that CreateFromConnectionString.
Thanks

**Comment by olivierbloch** [comment]
Hi @Nakul93 , excuse my ignorance in the GSM area, and please correct me if I am writing anything stupid :-).
The IoT Hub requires that an SSL connection is established to accept communication. Then you can use HTTP, AMQP or MQTT to send/receive messages.
So, in addition to having a software stack that allows sending TCP/IP packets using AT commands (which I assume exists), you need to have an SSL cert and establish the SSL connection through AT commands as well.
We had not planned to implement this ourselves in the short term, so for now I am adding a [user voice topic ](https://feedback.azure.com/forums/321918-azure-iot/suggestions/20504953-add-native-support-for-gsm-modules-such-as-sim900) to track this. Please vote for the feature on User Voice and let us know if you'd be willing to help contribute the implementation here.

**Comment by olivierbloch** [comment]
Closing the issue as it is now tracked on User Voice

**Comment by networkfusion** [comment]
To do this the GSM modem needs to support PPP connections. Once the session is created, it should be possible...

**Comment by DanielMarcato** [comment]
Has there been a solution to this? We are also trying to use a Modem connected via serial over AT-commands and are stuck in how to implement this.
The user voice topic link gives me a "page not found" error.
