### ISSUE TITLE
Group enrollment using X.509 certificate and TPM2.0

### ISSUE THREAD

**Issue by amitabhmodak** [Azure/azure-iot-sdk-c#2009]
Hi,
We will use TPM 2.0 device from Infineon to store keys/certificate. The private key will be generated by the TPM and never leaves the hardware.
We will use  TPM_PolicySigned as the authorization mechanism to access the key stored in the TPM. We can use the key to encrypt/decrypt/sign once the authorization is fulfilled. 

Next: The Device key in the TPM,  is an RSA key, that will be signed by our PKI using an ICA. This ICA will be used to perform Group Enrollment in the Device provisioning service.
I read this article : https://docs.microsoft.com/en-us/azure/iot-dps/concepts-tpm-attestation , and looks like it is not relevant for X.509 certificate for authentication.

There is also a similar issue in GitHub: https://github.com/Azure/azure-iot-sdk-c/issues/509

What we need is https://github.com/Azure/azure-c-shared-utility/blob/8fb4dbab432949c687e9679208defe72f37554b7/inc/azure_c_shared_utility/tlsio_cryptodev.h , but looks like the Azure C SDK doesn’t have the support of this yet.

https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/azure_provisioning_faq.md - The Section - TPM Provisioning, is not complete.

From the issue stated in GitHub I cant find real example that solves our problem.
Will the Azure C SDK support, X.509 certificate authentication Group enrollment, using TPM 2.0 ? 
Regards
Amitabh

**Comment by CIPop** [comment]
@amitabhmodak, you are correct about the DPS TPM attestation which directly uses EK/SRK and not an X509 PKI (required for group auth).

C-SDK now supports OpenSSL ENGINEs: https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/devdoc/iothubclient_c_library.md#openssl-engine-examples 
The second example is with TPM2.0 and X509 certificates using the TPM2 TSS OpenSSL Engine (https://github.com/tpm2-software/tpm2-tss-engine) with IoT Hub. Please let me know if you see any issues with DPS.

**Comment by amitabhmodak** [comment]
@CIPop I am not quite following you. Is there an example for DPS?

**Comment by amitabhmodak** [comment]
@CIPop  Do you have any documentation/examples of how to achieve this?

**Comment by CIPop** [comment]
@amitabhmodak sorry for the late answer - I was on leave.
No, unfortunately we're missing tests and a DPS sample to use custom_hsm + OpenSSL Engine. 

We're thinking of adding one although it's not my highest priority. Once we have it, I'll update this issue as well.

**Comment by CIPop** [comment]
For future reference - sample is now available here: https://github.com/Azure/azure-iot-sdk-c/tree/main/provisioning_client/samples/prov_dev_client_ll_x509_sample
