### ISSUE TITLE
Azure-iot-sdk-c MQTT on cc3200

### ISSUE THREAD

**Issue by MaHaXWS** [Azure/azure-iot-sdk-c#201]
After some big problems with the SDK and our MCU, we finally managed to communicate with the IOT-HUB!
Now I have some strange effects, I am not sure, whethereverything runs OK or there is an bug or I made an error.

We are using the SDK mit the **mqtt-protokoll**on port 8883.
For this goal I have writen an own adapter, which is not fully tested but seems to work.
We had some memory problems due to the usage of localtime(), gmtime(), ctime() functions from the stdlib, which I had to replace with own functions (why there are not used the functions from the agenttime-adapter?).
But this works now! so every thing fine with this.

For our test we are using the iothub-explorer to get some feedback and log messages from the IOThub during my tests. With this I am able to send data to the device and monitor all messages send to the cloud from the device .

The connection seems to have the following parts:
-  tls-connect
- Send 
     -> 10:08:49 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: zu | USERNAME: XXXXXXXXXXX.azure-devices.net/myFirstDevice/api-version=2016-11-14&DeviceClientType=iothubclient%2f1.1.15%20(cc3200) | PWD: XXXX | CLEAN: 0
- Recieve 
     <- 10:09:44 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
- Send  
     -> 10:09:46 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/myFirstDevice/messages/devicebound/# | QOS: 1

**After this there is an point I do not understand:
- It seems the AZURE-IOT-C-SDK expects an Message from the cloud
- If I do not send any message from the cloud to the device (C2D) the device is trying to receive a message and is waiting forever till the connection breaks down!
- Is this behavior correct?**

**If the device can receive Message from the cloud:**
- Receive
- Receive
- Send Telemetry data:
     -> 10:11:36 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/myFirstDevice/messages/events/temperatureAlert=false | PACKET_ID: 3 | PAYLOAD_LEN: zu
- Receive
     <- 10:12:32 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE = 0x01 | TOPIC_NAME: devices/myFirstDevice/messages/devicebound/%24.mid=15f3fce0-5297-42b9-87ca-e29160187a84&%24.to=%2Fdevices%2FmyFirstDevice%2Fmessages%2FdeviceBound&iothub-ack=full | PACKET_ID: 21 | PAYLOAD_LEN: zu
     Received Message [0]
      Message ID: 15f3fce0-5297-42b9-87ca-e29160187a84
      Correlation ID: <null>
      Data: <<<11.08.2017 10:01:35 - messageNr1>>> & Size=29
- Send
-  
     <- 10:12:35 SUBACK | PACKET_ID: 2 | RETURN_CODE: 1
     <- 10:12:37 PUBACK | PACKET_ID: 3
     Confirmation[0] received for message tracking id = 0

**Now the device waits again for a message!**
**If there is a second message:**
- Receive
- Send:
     -> 10:16:01 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/myFirstDevice/messages/events/temperatureAlert=false | PACKET_ID: 4 | PAYLOAD_LEN: zu
- Receive
- Receive
- Send
    -> 10:17:50 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/myFirstDevice/messages/events/temperatureAlert=false | PACKET_ID: 4 | PAYLOAD_LEN: zu
- Receive
     <- 10:18:46 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE = 0x01 | TOPIC_NAME: devices/myFirstDevice/messages/devicebound/%24.mid=9d038611-1bd8-47fd-97c9-ffb3191de8a3&%24.to=%2Fdevices%2FmyFirstDevice%2Fmessages%2FdeviceBound&iothub-ack=full | PACKET_ID: 22 | PAYLOAD_LEN: zu
     Received Message [1]
      Message ID: 9d038611-1bd8-47fd-97c9-ffb3191de8a3<\r><\n>
      Correlation ID: <null><\r><\n>
      Data: <<<11.08.2017 10:15:17 - messageNr2>>> & Size=29<\r><\n>
- Send
-  
     <- 10:18:49 PUBACK | PACKET_ID: 4
     Confirmation[1] received for message tracking id = 1
     <- 10:18:51 PUBACK | PACKET_ID: 4
- Send
    -> 10:18:54 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/myFirstDevice/messages/events/temperatureAlert=false | PACKET_ID: 5 | PAYLOAD_LEN: zu
- Receive
    <- 10:19:50 PUBACK | PACKET_ID: 5
    Confirmation[2] received for message tracking id = 2
- Send
     -> 10:19:53 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/myFirstDevice/messages/events/temperatureAlert=false | PACKET_ID: 6 | PAYLOAD_LEN: zu
- Received
    <- 10:20:48 PUBACK | PACKET_ID: 6
    Confirmation[3] received for message tracking id = 3

From now on I can send telemetrie Data to the Cloud without problems.
So the Question now:
- is the message from the cloud to the device necessary
- is there anywere a description about the message flow within the sdk!

Thanks for your help

Best 
MaHaXWS

**Comment by markrad** [comment]
Hi @MaHaXWS,

No I would not expect the SDK to ever block awaiting a message from the cloud. Possibly a defect in your adaptation layer?

_Mark Radbourne MSFT_

**Comment by MaHaXWS** [comment]
Hi
It might be possible that there is an error in my adaption layer! But as far as I can see everything else (all sending and receiving) works fine. From my logs I can see, that the SDK starts DOWORK (recieving an message) directly after the SUBACK message is received. But if there is no message waiting in the cloud the recieving stops after some timeout. And nothing is recieved. Is it possible/necessary to indicate this empty message or how to treat this empty message. 

In the function IoTHubTransport_MQTT_Common_DoWork in iothubtransprot_mqtt_common.c I found that if (transport_data->currPacketState == SUBACK_TYPE) there is just done a change of the currPacketState  = PUBLISH_TYPE in the next step the function mqtt_client_dowork(transport_data->mqttClient); is called (which calls the tls-receive function).

So I think the problem is caused by this function.

**Comment by markrad** [comment]
The DoWork logic will read the socket anytime it is called. Basically it will write any messages waiting and read any incoming messages. As I understand your comments above, you are saying that it blocks on only the first socket read after the SUBACK but not at any other time?

**Comment by markrad** [comment]
Hi @MaHaXWS,

Have you resolved this issue?

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @MaHaXWS,

Since you have not responded to my questions, I have closed this issue. Feel free to reopen it or open a new issue should your problem persist.

_Mark Radbourne MSFT_
