### ISSUE TITLE
vcpkg updates?

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/azure-iot-sdk-c#2019]
Question: it appears that the current version of the vcpkg azure-iot-sdk-c package is 2020-12-09.  Is the vcpkg azure-iot-sdk-c package updated regularly (for all platforms)?

**Comment by momuno** [comment]
Hi @RotateAt60MPH.  Thank you for pointing this out.  That package is out-of-date.  Normally, the package is updated regular with each LTS release, approximately six months apart.  I am preparing the next LTS release and will get this fixed.  Thanks!
