### ISSUE TITLE
Building applications using vcpkg for C SDK - directions not correct

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/azure-iot-sdk-c#2020]
The directions in [setting_up_vcpkg.md](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/setting_up_vcpkg.md) are not correct for trying to build a single linux-based sample that is installed as part of the vcpkg azure-iot-c-sdk package.  If you follow the directions and replace the specified CMakeList.txt file, you get this error on line 6::

```
CMake Error at CMakeLists.txt:6 (if):
  if given arguments:

    "NOT" "AND" "NOT" "AND" "NOT"

  Unknown arguments specified
```

The error is on the following line:

```
if(WIN32)
message(FATAL_ERROR "This CMake file is only support Linux builds!")
endif()
```

Which makes sense because the 'WIN32' is not defined.

And if you even try and comment it out, it will then fail on the one-level up CMakeList.txt file on all of the various 'if' statement symbols not defined.

In a 'normal' cmake build step, you use a much 'higher up' CMakeLists.txt file, which defines all the dependancies.  I don't know how the directions on this page would have _ever_ worked.

**Comment by momuno** [comment]
Hi @RotateAt60MPH.  I was able to reproduce the error you see when I run the document commands from the `linux/` directory. 

```
azure-iot-sdk-c/iothub_client/samples/iothub_ll_telemetry_sample/linux$ cmake .. -DCMAKE_TOOLCHAIN_FILE=~/vcpkg_new/scripts/buildsystems/vcpkg.cmake
```

When I create a `cmake/` directory under `linux/` and run the same command, the cmake command works:

```
azure-iot-sdk-c/iothub_client/samples/iothub_ll_telemetry_sample/linux$ mkdir cmake
azure-iot-sdk-c/iothub_client/samples/iothub_ll_telemetry_sample/linux$ cd cmake
azure-iot-sdk-c/iothub_client/samples/iothub_ll_telemetry_sample/linux/cmake$ cmake .. -DCMAKE_TOOLCHAIN_FILE=~/vcpkg_new/scripts/buildsystems/vcpkg.cmake
```

While the directions currently state "Run following commands in the newly created cmake directory:", this statement requires the user to correctly infer where to make this `cmake/` direcrtory.  As a result this step is both not clear and easily missed.  I will update the documentation.  

Thank you for bringing the issue to our attention.
