### ISSUE TITLE
azure-iot-sdk: compile time issue for custom HSM vs. use_prov_client selection for different clients

### ISSUE THREAD

**Issue by feckert** [Azure/azure-iot-sdk-c#2023]
I am packaging the azure-iot-sdk-c for OpenWrt.
I have already opened a [P/R](https://github.com/openwrt/packages/pull/15607) on the upstream project to get more input from the community.

I am writing two iothub client for two different projects.
I want to use the azure-iot-sdk-c as a shared object for my clients to communicate with the IoT-Hub.
**I do not want to build a static lib for each client!**

I am also using the provisioning service on my clients.

For one client I want to use the TPM provisioning and for the other one I want to use a custom HSM provisioning client implementation. 

But now I have a problem as I see it in your cmake.
I have to decide which provisioning HSM backend I want to use during compile time.

An CUSTOM_HSM or an already defined HSM (hsm_type_x509 or hsm_type_sastoken or hsm_type_symm_key).
https://github.com/Azure/azure-iot-sdk-c/blob/1c1b2c1a3a00bc445165dde44eb3e58ca999ec23/provisioning_client/CMakeLists.txt#L37-L45

And additional if I do not want to use the provisioning service the client can not be compiled because the lib does not find the references ` undefined reference to 'hsm_client_tpm_init'`for example.

**Comment by danewalton** [comment]
Hi @feckert just so I understand the asks correctly.

1. Allow an application to use any of the hsm backends depending on runtime?
2. Have the option to not have the provisioning client compiled at all?

**Comment by feckert** [comment]
Yes it looks like this
Current solution:
In openwrt there is the possibility to compile different versions of a program. So I have different azure-sdk-c with different compile options. This is not the best case, but it is the only way I can compile my two clients. Only one variant of the library can be installed on the system at any one time. The disadvantage is that I cannot install the Azure clients at the same time. This is unpleasant but acceptable in my current use case.

**Comment by danewalton** [comment]
Hi @feckert I don't believe this is something we would look to be doing. At least for the dynamic runtime selection, this would likely require a structural rewrite of components that we would not want to rewrite. I apologize for the unpleasant workaround but I would just like to honest.

I'm going to go ahead and close this for now but feel free to let us know if you think this remains unresolved given the above.
