### ISSUE TITLE
IoTHub Module - Direct Method Callback fail using AMQP

### ISSUE THREAD

**Issue by g1n93r** [Azure/azure-iot-sdk-c#2024]
Module method does not work when IoT Hub module uses AMQP. I receive a 504 (Timeout) when calling a direct method from the cloud interface.
![image](https://user-images.githubusercontent.com/50721341/125958904-b2cbb97b-ee1b-4617-89f2-683dada26a88.png)

Logs from edgeHub shows : 
<4> 2021-07-16 13:53:59.322 +00:00 [WRN] - Did not receive response for method invoke call from device/module nuc-sandbox/SenseAI_Connect for nuc-sandbox/SenseAI_Connect with correlation ID a5118d29-75b4-43c2-9223-d3b1ec0245b1

Switching to MQTT fixes this issue.

In sum,
This fails:
```c
IoTHub_Init();
IOTHUB_MODULE_CLIENT_HANDLE _IoTHubHandle = IoTHubModuleClient_CreateFromEnvironment(AMQP_Protocol);
IoTHubModuleClient_SetModuleMethodCallback(_IoTHubHandle, module_method_callback, NULL);
...
```
This works:
```c
IoTHub_Init();
IOTHUB_MODULE_CLIENT_HANDLE _IoTHubHandle = IoTHubModuleClient_CreateFromEnvironment(MQTT_Protocol);
IoTHubModuleClient_SetModuleMethodCallback(_IoTHubHandle, module_method_callback, NULL);
...
```

Note that the function module_method_callback isn't called at all when used with AMQP

**Comment by g1n93r** [comment]
@danewalton do you have any follow up on this issue ?

**Comment by danewalton** [comment]
Hi @g1n93r unfortunately AMQP and modules are not supported at this time. Please see this comment here for more details:
https://github.com/Azure/azure-iot-sdk-c/issues/1397#issuecomment-719818358
