### ISSUE TITLE
[macOS] Compile error: cast to small integer type from const void

### ISSUE THREAD

**Issue by rbaprokopenko** [Azure/azure-iot-sdk-c#2028]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

![image](https://user-images.githubusercontent.com/59177528/127054356-415e3f4b-1a72-4791-8cc4-0acfb4f3fc82.png)

```
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**SDK Version (Please Give Commit SHA if Manually Compiling)**

`2020-12-09#1` from vcpkg.

**Protocol**

AMQP

**Describe the Bug**

AMQP will not build on macOS due to wrong type cast.

```sh
/Users/siennalloyd/Development/microsoft/vcpkg/buildtrees/azure-iot-sdk-c/src/eff40b92ec-652b85f61b.clean/iothub_client/src/iothubtransport_amqp_telemetry_messenger.c:1024:80: er
ror: cast to smaller integer type 'TELEMETRY_MESSENGER_EVENT_SEND_COMPLETE_RESULT' (aka 'enum TELEMETRY_MESSENGER_EVENT_SEND_COMPLETE_RESULT_TAG') from 'const void *' [-Werror,-W
void-pointer-to-enum-cast]
        TELEMETRY_MESSENGER_EVENT_SEND_COMPLETE_RESULT messenger_send_result = (TELEMETRY_MESSENGER_EVENT_SEND_COMPLETE_RESULT)action_context;
                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Console Logs**

N/A

**Comment by danewalton** [comment]
Thanks for submitting the PR tackling this. I have added comments on it.

**Comment by mxplusb** [comment]
@danewalton great! I couldn't quite figure out how the rebasing was supposed to work since I'm only familiar with this workflow:

```sh
git checkout master
git pull
git checkout <branch>
git rebase master
```

That caused the issue to be closed when I pushed it, so I'm not sure where I went wrong. I'm glad it's getting resolved, though, thank you!

**Comment by danewalton** [comment]
Weird yea my flow is usually the same just with the
```bash
git push -f
```
at the end. Long story short it'll get in thanks for pointing it out.
