### ISSUE TITLE
using device twin for ardunio 

### ISSUE THREAD

**Issue by MehranMazhar** [Azure/azure-iot-sdk-c#203]
i need to use device twin in azure-iot-ardunio simplesample_mqtt example .but when i use this line of codes : ([devicetwin_simplesample](https://github.com/Azure/azure-iot-sdk-c/tree/master/serializer/samples/devicetwin_simplesample) in [azure-iot-c-sdk](https://github.com/Azure/azure-iot-sdk-c) )

    DECLARE_STRUCT(Maker,
        ascii_char_ptr, makerName, /*Fabrikam, Contoso ... */
        ascii_char_ptr, style, /*sedan, minivan ...*/
        int, year
    );

----------

    DECLARE_STRUCT(Geo,
        double, longitude,
        double, latitude
    );

----------

    DECLARE_MODEL(CarState,
        WITH_REPORTED_PROPERTY(int32_t, softwareVersion),
        WITH_REPORTED_PROPERTY(uint8_t, reported_maxSpeed),
        WITH_REPORTED_PROPERTY(ascii_char_ptr, vanityPlate)
    );

----------

    DECLARE_MODEL(CarSettings,
        WITH_DESIRED_PROPERTY(uint8_t, desired_maxSpeed, onDesiredMaxSpeed),
        WITH_DESIRED_PROPERTY(Geo, location)
    );

----------

    DECLARE_DEVICETWIN_MODEL(Car,
        WITH_REPORTED_PROPERTY(ascii_char_ptr, lastOilChangeDate), /*this is a simple reported property*/
        WITH_DESIRED_PROPERTY(ascii_char_ptr, changeOilReminder),
        
        WITH_REPORTED_PROPERTY(Maker, maker), /*this is a structured reported property*/
        WITH_REPORTED_PROPERTY(CarState, state), /*this is a model in model*/
        WITH_DESIRED_PROPERTY(CarSettings, settings) /*this is a model in model*/
    
    );

----------

    Arduino: 1.8.3 (Windows 10), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, 115200, 4M (3M SPIFFS)"
    Build options changed, rebuilding all
    In file included from C:\Users\mehran-pc\Documents\Arduino\libraries\AzureIoTHub\src/AzureIoTHub.h:9:0,
                     from sketch\simplesample_mqtt.c:15:
    C:\Users\mehran-pc\Documents\Arduino\libraries\AzureIoTHub\src/sdk/serializer.h:226:67: error: expected ')' before '(' token
     #define WITH_REPORTED_PROPERTY(type, name) MODEL_REPORTED_PROPERTY(type, name)
    sketch\simplesample_mqtt.c:63:5: note: in expansion of macro 'WITH_REPORTED_PROPERTY'
    
    WITH_REPORTED_PROPERTY(ascii_char_ptr, lastOilChangeDate), /*this is a simple reported property*/
    
    exit status 1
    Error compiling for board NodeMCU 0.9 (ESP-12 Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by jspaith** [comment]
I was able to repro this on Ardunio using your steps.  When I did below everything compiles for me:
* `#include "sdk/serializer_devicetwin.h"`
* Remember you'll need the `BEGIN_NAMESPACE` and `END_NAMESPACE` per the twin sample you're going off of.

**Comment by MehranMazhar** [comment]
@jspaith  thank you for the tips . I did the two. but I get this error : 'undefined reference to `Unlock''
here is my all ardunio project .  
[simplesample_mqtt.zip](https://github.com/Azure/azure-iot-sdk-c/files/1272499/simplesample_mqtt.zip)


can you share simple sample project  using device twin with mqtt and esp8266 . thanks

**Comment by jspaith** [comment]
I wasn't aware at time, but per https://github.com/Azure/azure-iot-arduino/issues/62 twin isn't supported on Arduino.  

Looks like build errors you're hitting in this round are because the platform layer on Arduino doesn't support lock (as it's single threaded), but the twin is doing something to call it in, per it never being a tested/supported scenario.

**Comment by jspaith** [comment]
One last attempt - you may try using the _LL_ versions of the IOTHUB functions.  LL stands for low-layer, and it means that everything happens on a single thread insntead of background.

So you'd want IoTHubClient_LL_CreateFromConnectionString, IotHubClient_LL_Foo.  

Note per the samples you'll need to explicitly call IoTHubClient_LL_DoWork() in your main thread on a loop; this does what a background thread on a bigger OS like Windows/Linux does for you automatically.

We're unfortunately still not officially supporting Twin on Arduino even if this does work, but if you were curious this at least explains why Lock() probably wasn't found..

**Comment by ewertons** [comment]
This item will be closed, but please feel free to re-open it or open another one if needed.

Thanks for using the Azure IoT SDK.
