### ISSUE TITLE
Connecting with TPM, how to retrieve SAS token to provide connection string to other processes ?

### ISSUE THREAD

**Issue by neonsoftware** [Azure/azure-iot-sdk-c#2059]
Hi !

**context**:
- mips linux board which has TPM, openwrt os, non-edge. 
- the main process today connects to IotHub using `IoTHubClient_Auth_CreateFromDeviceAuth`() with TPM, (which internally exchanges to the provisioning service, apparently, as no tokens are known nor stored in the device)
- now needing to add the DeviceUpdate agent (https://github.com/Azure/iot-hub-device-update), which **expects only a connection string as input, which could come from another process via IPC**, as it is currently done for the eis edge module.

**question**:

Connecting to IotHub with `IoTHubClient_Auth_CreateFromDeviceAuth(TPM)`,
I have not yet found, in the SDK any way to **retrieve the SAS token in order to be able to assemble a connection string** (for another process).
Did I miss it ?

Thank you in advance. 
Have a great day.

**Comment by CIPop** [comment]
We don't provide such an extension but we do allow customers to write their own [custom_hsm](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_custom_hsm.md) auth implementation and expose new functionality. TPM client code and SAS key generation is available in `iothub_auth_client.c` (`iothub_device_auth_generate_credentials`).

I think IS/KS is still a better idea as you've already mentioned in the original bug at https://github.com/Azure/iot-hub-device-update/issues/87 . It's worth opening a bug in the [IS/KS repo](https://github.com/Azure/iot-identity-service) to add the requested MIPS/OpenWRT support which is something that might have been missed. (https://github.com/japaric-archived/rust-on-openwrt might be worth a try? - I'm not a RUST expert though so can't guarantee that would work).

/cc @ValOlson @micahl @arsing in case you've already tested IS/KS cross-compiled on MIPS.

**Comment by arsing** [comment]
We haven't tested the IS stack or the tpm2-pkcs11 stack with a mips target, no.

The tpm2-pkcs11 stack is all C so it'll probably work. Rust's mips target is tier 2 so it'll probably work too. They do have a few third-party lib dependencies that may or may not be available in OpenWRT already, so you might have to compile those too.

The code is already set up for cross-compiling because it supports ARM, so I don't anticipate any problems in convincing it to use the OpenWRT cross toolchain. You can see how the build is set up to cross-compile for ARM (start from https://github.com/Azure/iot-identity-service/blob/main/.github/workflows/packages.yaml and follow the scripts that get called) and modify it to cross-compile with the OpenWRT toolchain instead.

**Comment by CIPop** [comment]
Thank you @arsing ! In that case I stand by our recommendation to give the official pattern (IS/KS + SDK + DU) a try on OpenWRT/MIPS. Feedback or issues are welcomed in any of the repos causing issues.

Closing here as the original SDK question has been answered.

**Comment by micahl** [comment]
@arsing aside from cross-compiling for mips, are there runtime assumptions in the IS/KS design that could affect how feasible it is to stand up on something like OpenWRT (e.g. [procd instead of systemd](https://openwrt.org/docs/techref/procd#openwrt_operating_system_architecture))?

**Comment by arsing** [comment]
I don't think so.

systemd isn't a requirement - socket activation is optional and the services will work fine if you start them up manually.

**Comment by neonsoftware** [comment]
Hi, 

Thank you all  for the follow-up,

@CIPop Thank you, I will **look into custom_hsm** within the week and will report back here.

@micahl @arsing Thank you for the additional information. In order to evaluate the runtime requirements, (use case is industrial application with thousands of harsh-environment-located devices), while [Tier1](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-1) rust support is described as "_guaranteed to work_", [Tier2](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2) rust support (in this case mipsel-unknown-linux-**musl** as of default openwrt), is described as only "_guaranteed to build_", and without host-tools.
Does Microsoft keep a list/URL of Tier2 platform triplets that it guarantees and test ? (and with which long term support) 

Thank you in advance,
Have a great day

**Comment by neonsoftware** [comment]
Should I recreate a new issue with the latest question: 

_Will a [custom_hsm](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_custom_hsm.md) work for both devices and modules ?_

Or instead could the issue reopen, let me know.
Thank you in advance.
