### ISSUE TITLE
cmake needs to be called twice for cross compilation

### ISSUE THREAD

**Issue by JuergenKosel** [Azure/azure-iot-sdk-c#207]
- **OS and version used:** <VERSION> 
Build machine: Linux (Debian 9), AMD64
Building for host: Linux (Debian 8), armhf
- **SDK version used:** <VERSION> 
IoT Hub SDK for C, version 1.1.20
git commit id: 57131b57f1f413c6bdfc2e2502cc5ade0daac68f

# Description of the issue:

I have managed to cross compile the sdk for embedded linux-armhf (Debian 8) target.
But I need to add a workaround into my scrip, because cmake does not set the linker flags into the Makefiles during the first run. (See also https://github.com/Azure/azure-c-shared-utility/pull/96#discussion_r133530229 .)

# Code sample exhibiting the issue:

My script (with workaround) to generate the Makefiles:
https://github.com/JuergenKosel/azure-iot-sdk-c/blob/cross-compile-linux-armhf/build_all/linux/build4armhf.sh

# Console log of the issue (with workaround removed):

```
LANG=C make VERBOSE=1 all
/usr/bin/cmake -H/home/klj/azure-iot-sdk-c -B/home/klj/azure-iot-sdk-c/cmake/armhf --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/klj/azure-iot-sdk-c/cmake/armhf/CMakeFiles /home/klj/azure-iot-sdk-c/cmake/armhf/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/klj/azure-iot-sdk-c/cmake/armhf'
make -f c-utility/CMakeFiles/aziotsharedutil.dir/build.make c-utility/CMakeFiles/aziotsharedutil.dir/depend
make[2]: Entering directory '/home/klj/azure-iot-sdk-c/cmake/armhf'
cd /home/klj/azure-iot-sdk-c/cmake/armhf && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/klj/azure-iot-sdk-c /home/klj/azure-iot-sdk-c/c-utility /home/klj/azure-iot-sdk-c/cmake/armhf /home/klj/azure-iot-sdk-c/cmake/armhf/c-utility /home/klj/azure-iot-sdk-c/cmake/armhf/c-utility/CMakeFiles/aziotsharedutil.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/klj/azure-iot-sdk-c/cmake/armhf'
make -f c-utility/CMakeFiles/aziotsharedutil.dir/build.make c-utility/CMakeFiles/aziotsharedutil.dir/build
make[2]: Entering directory '/home/klj/azure-iot-sdk-c/cmake/armhf'
make[2]: Nothing to be done for 'c-utility/CMakeFiles/aziotsharedutil.dir/build'.
make[2]: Leaving directory '/home/klj/azure-iot-sdk-c/cmake/armhf'
[ 19%] Built target aziotsharedutil
make -f c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/build.make c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/depend
make[2]: Entering directory '/home/klj/azure-iot-sdk-c/cmake/armhf'
cd /home/klj/azure-iot-sdk-c/cmake/armhf && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/klj/azure-iot-sdk-c /home/klj/azure-iot-sdk-c/c-utility/samples/iot_c_utility /home/klj/azure-iot-sdk-c/cmake/armhf /home/klj/azure-iot-sdk-c/cmake/armhf/c-utility/samples/iot_c_utility /home/klj/azure-iot-sdk-c/cmake/armhf/c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/klj/azure-iot-sdk-c/cmake/armhf'
make -f c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/build.make c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/build
make[2]: Entering directory '/home/klj/azure-iot-sdk-c/cmake/armhf'
[ 19%] Linking C executable iot_c_utility
cd /home/klj/azure-iot-sdk-c/cmake/armhf/c-utility/samples/iot_c_utility && /usr/bin/cmake -E cmake_link_script CMakeFiles/iot_c_utility.dir/link.txt --verbose=1
/usr/bin/arm-linux-gnueabihf-gcc-4.9   -D_POSIX_C_SOURCE=200112L  -fPIC  -Werror -fPIC -Werror -DUSE_OPENSSL   CMakeFiles/iot_c_utility.dir/iot_c_utility.c.o  -o iot_c_utility -Wl,-rpath,/home/klj/Toolchain/Dev-Rootfs/usr/lib/arm-linux-gnueabihf -rdynamic ../../libaziotsharedutil.a /home/klj/Toolchain/Dev-Rootfs/usr/lib/arm-linux-gnueabihf/libcurl.so /home/klj/Toolchain/Dev-Rootfs/usr/lib/arm-linux-gnueabihf/libssl.so /home/klj/Toolchain/Dev-Rootfs/usr/lib/arm-linux-gnueabihf/libcrypto.so -lpthread -lm -lrt -luuid 
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../../arm-linux-gnueabihf/bin/ld: cannot find -luuid
collect2: error: ld returned 1 exit status
c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/build.make:98: recipe for target 'c-utility/samples/iot_c_utility/iot_c_utility' failed
make[2]: *** [c-utility/samples/iot_c_utility/iot_c_utility] Error 1
make[2]: Leaving directory '/home/klj/azure-iot-sdk-c/cmake/armhf'
CMakeFiles/Makefile2:1056: recipe for target 'c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/all' failed
make[1]: *** [c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/all] Error 2
make[1]: Leaving directory '/home/klj/azure-iot-sdk-c/cmake/armhf'
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

After a 2nd call of cmake, the sdk could be successfully cross compiled!

**Comment by markrad** [comment]
Hi @JuergenKosel,

Is the toolchain you are using publicly available? I would like to test this to understand the behavior you are observing. Can you also provide your CMake toolchain file please?

Thanks.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @JuergenKosel,

I'm awaiting your response to my question above. There is not much I can do if I can't reproduce the issue locally and thus far I have not be able to.

_Mark Radbourne MSFT_

**Comment by JuergenKosel** [comment]
Hello @markrad 
the cross build tool chain is based on Debian cross build tools.
A script to install the tool chain in a chroot-environment is available here: https://github.com/Azure/iot-edge-opc-proxy/blob/master/bld/toolchain/create_cross_chroot.sh
BTW: In https://github.com/Azure/iot-edge-opc-proxy/tree/master/bld/toolchain I have used similar cmake cross scripts, without the need to run cmake twice.

**Comment by markrad** [comment]
Hi @JuergenKosel,

Sorry I've neglected this issue for so long. I was reviewing it once again and I needed a piece of clarification. In your original comment you referred to your pull request at https://github.com/Azure/azure-c-shared-utility/pull/96#discussion_r133530229. I'm inferring that this fix will address your cross compile issue. Is this correct? It doesn't appear to have been merged. If this is all you need then I'll get it pushed through.

_Mark Radbourne MSFT_

**Comment by JuergenKosel** [comment]
Hello @markrad ,

the issue came up with my pull request #232 to this project. (Which has been closed.)
The pull request https://github.com/Azure/azure-c-shared-utility/pull/96 has already been merged and is a necessary for the pull request #232 .

This issue might be a (minor) problem for anyone, who wants to cross build this azure-iot-sdk-c.

Greetings
  Juergen

**Comment by markrad** [comment]
Hi @JuergenKosel,

Though I've not cross compiled with the specific tool chain you referenced above, I have cross compiled the SDK with a variety of different tool chains and I have never observed this behavior. I will need concise repro steps to take this any further or I will have to close this issue.

_Mark Radbourne MSFT_

**Comment by JuergenKosel** [comment]
If this issue occurs with only one toolchain, it might be the problem of the toolchain. Closing!
