### ISSUE TITLE
Could not initialize IoTHubAccount ----Failure retrieving x509 certificate from the environment.

### ISSUE THREAD

**Issue by taroyutao** [Azure/azure-iot-sdk-c#208]
- **OS and version used:** <VERSION> 

Ubuntu 16.04
gcc 5.4

- **SDK version used:** <VERSION> 

git clone --recursive https://github.com/Azure/azure-iot-sdk-c.git

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

[100%] Linking C executable devicemethod_simplesample
[100%] Built target devicemethod_simplesample
Test project /root/azure-iot-sdk-c/cmake/iotsdk_linux
    Start 1: iothubclient_uploadtoblob_e2e
    Start 2: iothubclient_http_e2e
    Start 3: iothubclient_mqtt_e2e
    Start 4: iothubclient_mqtt_dt_e2e
1/8 Test #2: iothubclient_http_e2e .................***Failed    0.03 sec
 === Executing test suite iothubclient_http_e2e ===
Error: Time:Thu Aug 17 08:16:19 2017 File:/root/azure-iot-sdk-c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init_With_Config Line:537 Failure retrieving x509 certificate from the environment.

  Assert failed in line 554: non-NULL expected. 
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.

2/8 Test #4: iothubclient_mqtt_dt_e2e ..............***Failed    0.02 sec
 === Executing test suite iothubclient_mqtt_dt_e2e ===
Error: Time:Thu Aug 17 08:16:19 2017 File:/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:openssl_static_locks_install Line:469 Locks already initialized
Error: Time:Thu Aug 17 08:16:19 2017 File:/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_init Line:1007 Failed to install static locks in OpenSSL!
Error: Time:Thu Aug 17 08:16:19 2017 File:/root/azure-iot-sdk-c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init_With_Config Line:537 Failure retrieving x509 certificate from the environment.

  Assert failed in line 150: non-NULL expected. 
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.

3/8 Test #3: iothubclient_mqtt_e2e .................***Failed    0.03 sec
 === Executing test suite iothubclient_mqtt_e2e ===
Error: Time:Thu Aug 17 08:16:19 2017 File:/root/azure-iot-sdk-c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init_With_Config Line:537 Failure retrieving x509 certificate from the environment.

  Assert failed in line 427: non-NULL expected. Could not initialize IoTHubAccount
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.

4/8 Test #1: iothubclient_uploadtoblob_e2e .........***Failed    0.03 sec
 === Executing test suite iothubclient_uploadtoblob_e2e ===
Error: Time:Thu Aug 17 08:16:19 2017 File:/root/azure-iot-sdk-c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init_With_Config Line:537 Failure retrieving x509 certificate from the environment.

  Assert failed in line 63: non-NULL expected. Could not initialize IoTHubAccount
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.

    Start 5: iothubclient_mqtt_device_method_e2e
    Start 6: iothubclient_mqtt_ws_e2e
    Start 7: iothubclient_amqp_e2e
    Start 8: iothubclient_amqp_ws_e2e
Errors while running CTest
5/8 Test #6: iothubclient_mqtt_ws_e2e ..............***Failed    0.03 sec
 === Executing test suite iothubclient_mqtt_ws_e2e ===
Error: Time:Thu Aug 17 08:16:19 2017 File:/root/azure-iot-sdk-c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init_With_Config Line:537 Failure retrieving x509 certificate from the environment.

  Assert failed in line 427: non-NULL expected. Could not initialize IoTHubAccount
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.

6/8 Test #5: iothubclient_mqtt_device_method_e2e ...***Failed    0.03 sec
 === Executing test suite iothubclient_mqtt_device_method_e2e ===
Error: Time:Thu Aug 17 08:16:19 2017 File:/root/azure-iot-sdk-c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init_With_Config Line:537 Failure retrieving x509 certificate from the environment.

  Assert failed in line 66: non-NULL expected. 
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.

7/8 Test #7: iothubclient_amqp_e2e .................***Failed    0.02 sec
 === Executing test suite iothubclient_amqp_e2e ===
Error: Time:Thu Aug 17 08:16:19 2017 File:/root/azure-iot-sdk-c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init_With_Config Line:537 Failure retrieving x509 certificate from the environment.

  Assert failed in line 427: non-NULL expected. Could not initialize IoTHubAccount
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.

8/8 Test #8: iothubclient_amqp_ws_e2e ..............***Failed    0.02 sec
 === Executing test suite iothubclient_amqp_ws_e2e ===
Error: Time:Thu Aug 17 08:16:19 2017 File:/root/azure-iot-sdk-c/testtools/iothub_test/src/iothub_account.c Func:IoTHubAccount_Init_With_Config Line:537 Failure retrieving x509 certificate from the environment.

  Assert failed in line 427: non-NULL expected. Could not initialize IoTHubAccount
TEST_SUITE_INITIALIZE failed - suite ending
0 tests ran, ALL failed, NONE succeeded.

**Comment by markrad** [comment]
Hi @taroyutao,

As I mention in my other post, e2e tests are not really designed for public consumption. Try running the samples and let me know if you have an issue with those.

Thanks.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Closing due to lack of response.
