### ISSUE TITLE
Prov_Device_Register_Device is not returning callback when there is no internet

### ISSUE THREAD

**Issue by ykgw-moorthy** [Azure/azure-iot-sdk-c#2086]
I am using azure iot c sdk to send data to azure cloud. I observed that when **HTTPS protocol** is configured, Prov_Device_Register_Device API is not returning callback when there is no internet connected to PC. 
For MQTT and AMQP protocol it does return the callback  with PROV_DEVICE_RESULT_TRANSPORT error, where as  for HTTPS, callback is not received.

Is this expected behavior when HTTPS protocol is configured  for provisioning_client ?

**Comment by ericwol-msft** [comment]
Using HTTP transport, the Prov_Device_Register_Device should return an error. In case the callback will not be called because the API failed. The other two, because of the protocol implementation, Prov_Device_Register_Device will return a success code, and the network error will be returned in the notification. 

Is there a reason you are using HTTP over one of the websockets transports?

**Comment by ykgw-moorthy** [comment]
Thank you so much for quick response.
We are using this API to upload file to blob storage. Hence we are using HTTP instead other protocols.

In my case Prov_Device_Register_Device  API is failing (returns **PROV_DEVICE_RESULT_ERROR**) that is reason i am not getting the callback for the HTTP protocol.

Also I would like understand, what values are returned in the positive scenarios.  I understand that following marked value would be  returned in the positive scenarios.
![image](https://user-images.githubusercontent.com/80386183/133993773-cf9911d5-c0f9-41c0-bad3-f806f8779cff.png)
 
Can you please clarify my understanding.

**Comment by ericwol-msft** [comment]
PROV_DEVICE_RESULT_OK

https://github.com/Azure/azure-iot-sdk-c/blob/1689b3881d7637a21b12b92abd5bf9a7092cc869/provisioning_client/src/prov_device_ll_client.c#L952

**Comment by asergaz** [comment]
Same ask in StackOverflow https://stackoverflow.com/questions/69203446/prov-device-register-device-is-not-returning-callback-when-there-is-no-internet

**Comment by ericwol-msft** [comment]
Closing this issue. I fixed the sample to handle this API failure. Also, Prov_Device_LL_Register_Device will return PROV_DEVICE_RESULT_TRANSPORT instead of a generic error (PROV_DEVICE_RESULT_ERROR).
