### ISSUE TITLE
Consume Device Provisioning Feature  in iOS Swift

### ISSUE THREAD

**Issue by UdayKiran-M** [Azure/azure-iot-sdk-c#2088]
I am trying to consume Azure IOT HUB SDK for my iOS project written in Swift.  Added `pod 'AzureIoTHubClient' `to the project.
But didn't find any c files related to the Provisioning service that got added. Below pods got added to the project.
AzureIoTHubClient
AzureIoTuAmqp
AzureIoTuMqtt
AzureIoTUtility
AzureMacroUtils. 

Have following questions
is provisioning service available through cocoapods?
If YES, how can I enable/add to my swift project
Are there any Swift samples/ wrappers that showcase how to consume DPS in iOS? 

I saw few swift samples that explain telemetry but no samples on DPS. I am blocked at this step. Appreciate if you can guide me here

**Comment by danewalton** [comment]
Hi @UdayKiran-M thanks for the message.

We do not have support for DPS on iOS at this time. At the original creation of the cocoapods, I believe there was a technical limitation which meant it was not supported. We currently do not have any plans to add support for DPS to iOS.

**Comment by UdayKiran-M** [comment]
Hi @danewalton, thanks for the swift reply.
If not through cocoapods, is there any other suggested approach from Microsoft on how to use DPS. I mean is there any framework or other way that we can use in iOS?

**Comment by DeanFaizal** [comment]
@UdayKiran-M  did you find a workaround?
