### ISSUE TITLE
Fall back to MQTT over websockets if MQTT connection fails

### ISSUE THREAD

**Issue by c-larsen** [Azure/azure-iot-sdk-c#209]
- **OS and version used:** Yocto  Linux 1.3

- **SDK version used:** 2017-08-11

# Description of the issue:
On some networks it is not possible to establish a MQTT connection from device to cloud because of firewall settings blocking port 8883. In such cases it would be nice if IoTHubClient_Create() could automatically fall back to use MQTT over websockets instead when creating the connection even though IOTHUB_CLIENT_CONFIG.protocol was set to MQTT_Protocol.

**Comment by tameraw** [comment]
@c-larsen - Thanks for filing this issue. 
This is definitely a valid scenario. We'll track it in our backlog to bring it in a future release.

**Comment by kiranpradeep** [comment]
@tameraw Does the SDK really need to do this? What if this is a temporary connection failure? I don't want my application to do this unless I explicitly specify so. Hope it would need explicit permission from SDK user, if this gets implemented

**Comment by tameraw** [comment]
@kiranpradeep - Currently this is not in scope for the near future.
