### ISSUE TITLE
After upgrading azure-iot-sdk-c from LTS_01_2021_Ref01 to LTS_07_2021_Ref01 certificate verify is flailing

### ISSUE THREAD

**Issue by Dasthananda** [Azure/azure-iot-sdk-c#2093]
I have upgraded my azure-iot-sdk-c from LTS_01_2021_Ref01 to LTS_07_2021_Ref01. And I am observing few issues with certificate verification. I have build the sdk with below options

-Dbuild_provisioning_service_client=OFF
-Ddont_use_uploadtoblob=ON
-Duse_prov_client=ON
-Duse_openssl=ON
-Duse_mqtt=ON
-Duse_default_uuid=ON
-Dhsm_type_custom=ON
-Dskip_samples=ON
-Duse_condition=OFF
-Duse_http=OFF
-Duse_amqp=OFF
-Duse_sample_trusted_cert=ON
-Duse_baltimore_cert=ON \

And i am seeing below errors from sdk code.

Error: Time:Fri Sep 24 14:10:03 2021 File:/tmp/ci-U9cA8w3wdj/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:734 error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed Error: Time:Fri Sep 24 14:10:03 2021 File:/tmp/ci-U9cA8w3wdj/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint Error: Time:Fri Sep 24 14:10:03 2021 File:/tmp/ci-U9cA8w3wdj/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error Error: Time:Fri Sep 24 14:10:03 2021 File:/tmp/ci-U9cA8w3wdj/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:771 Failure retrieving data from the provisioning service

{"error":{"ts":1632472803823,"v":"(1009): Registration failed - Retrying. Azure registration state: PROV_DEVICE_RESULT_TRANSPORT"},"processedTs":null}

Do I need to add any flags at the time of build?
could you please help me to understand why it is failing?

Thanks in advance

**Comment by asbarnes** [comment]
I had the exact same error. However the root cause was not related to azure-iot-sdk-c.
Most common cause of this SSL error is wrong date or time. can you verify your date settings? from the logs it seems that you are 1 or 2 days behind.

**Comment by Dasthananda** [comment]
Thanks @asbarnes  for your comments.
Date is correctly i have pasted 2 days back logs here.
how did you resolve this issue?,
could you please help me with the steps you followed .

**Comment by asbarnes** [comment]
In my case the issue was resolved by running `ntpdate -b -s -u pool.ntp.org` before launching the service that using azure-iot-sdk-c.

**Comment by Dasthananda** [comment]
Thanks @asbarnes 
I tried ntpdate command ,it did not work for me.

**Comment by CIPop** [comment]
The main fix within the new LTS is adding proper remote domain name validation during the TLS handshake: https://github.com/Azure/azure-iot-sdk-c/security/advisories/GHSA-p24m-6m44-jm58.

If NTP or time difference was the issue, I would expect it to manifest in both the previous LTS and the new one. 

This error appears to be saying that the remote server you are trying to connect to has an invalid certificate:
```
Error: Time:Fri Sep 24 14:10:03 2021 File:/tmp/ci-U9cA8w3wdj/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:734 error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed Error: Time:Fri Sep 24 14:10:03 2021 File:/tmp/ci-U9cA8w3wdj/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
```

Please verify the endpoint you are connecting to and that there are no proxies or other TLS inspection systems running in your network.

Verify connectivity using `openssl s_client global.azure-devices-provisioning.net:443` for example (replace the endpoint with your global endpoint URI depending on the Azure cloud you are connecting to).

Here's my output:

```
openssl s_client global.azure-devices-provisioning.net:443
CONNECTED(00000003)
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 C = US, O = Microsoft Corporation, CN = Microsoft RSA TLS CA 01
verify return:1
depth=0 CN = *.azure-devices-provisioning.net
verify return:1
```

**Comment by Dasthananda** [comment]
Thanks @CIPop .
Issue is the way we generated the certificate with x509.SubjectAlternativeName.

**Comment by asergaz** [comment]
This relates with: https://stackoverflow.com/questions/69315422/after-upgrading-azure-iot-sdk-c-from-lts-01-2021-ref01-to-lts-07-2021-ref01-cert
