### ISSUE TITLE
Azure process flapping continuously during low network bandwidth

### ISSUE THREAD

**Issue by gopicisco** [Azure/azure-iot-sdk-c#2099]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Alphine Linux, aarch64-linux-musl-g++ GCC 10.2.1

azure sdk cmake compilation command:

```
cmake \
      -DCMAKE_PREFIX_PATH=${cmake_prefix} \
      -DCMAKE_INSTALL_PREFIX=${install_prefix} \
      -DCMAKE_BUILD_TYPE=${buildtype} \
      -DBUILD_TESTING=OFF \
      -DcompileOption_C="-D_FORTIFY_SOURCE=2 -fstack-protector -fPIC" \
      -DcompileOption_CXX="$-D_FORTIFY_SOURCE=2 -fstack-protector -fPIC" \
      -DlinkerOption="-Wl,-z,now" \
      -Dbuild_service_client=OFF \
      -Dbuild_provisioning_service_client=OFF \
      -Ddont_use_uploadtoblob=ON \
      -Duse_prov_client=ON \
      -Duse_openssl=ON \
      -Duse_mqtt=ON \
      -Duse_default_uuid=ON \
      -Dhsm_type_custom=ON \
      -Dskip_samples=ON \
      -Duse_condition=OFF \
      -Duse_http=OFF \
      -Duse_amqp=OFF \
      -Dno_logging=OFF \

```

**SDK Version**

LTS_07_2021_Ref01 
LTS_01_2021_Ref01

**Protocol**

MQTT

**Describe the Bug**

During a low network bandwidth scenario, we are continuously sending data every few milliseconds to Azure IOT Hub. 
After some time, we could see the azure process got crashed and the same is being restarted by the broker process. Not sure the reason for the azure process flapping which is observed very frequently.
The above process flapping is seen continuously and happens more frequently.
Unfortunately, we are unable to collect the core or the backtrace info due to limitations in accessing the remote device.
Few seconds before the process restart, we see the DISCONNECT packet sent from the SDK.

bandwidth: 10 Kbps
message payload size: 460
message sent every: 300ms

Internally we have a message counter which increments for every IoTHubDeviceClient_SendEventAsync call.
When the counter reaches 1000, we simply drop the packet to avoid backpressure. But in the above crash scenario, we see queue size around 400 not reached the max value.

**Logs**

```
INFO SDK(0): No error information - AzureMessageQueueCounter: Message Queue Length: 406
INFO SDK(0): No error information - AzureDevice, send_message: done

-> 07:03:37 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/7171/messages/events/ | PACKET_ID: 649 | PAYLOAD_LEN: 460
-> 07:03:37 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/7171/messages/events/ | PACKET_ID: 446 | PAYLOAD_LEN: 460
-> 07:03:37 DISCONNECT
```

After this, we still publishing data and the counter increased to 407

```
SDK: AzureDevice - send_message: mapping:resultPath value: 
SDK(0): No error information - AzureDevice, send_message: mapping: resultPath value: 
SDK(0): No error information - AzureMessageQueueCounter: Message Queue Length: 407
<- 07:03:38 PUBACK | PACKET_ID: 243
<- 07:03:38 PUBACK | PACKET_ID: 244
```

After the above PUBACK packets, within a few milliseconds, the azure SDK process restarted.

`07:03:38.309842] Link version,`

The above pattern is observed multiple times in the logs.

Appreciate your help in resolving the above issue.

**Comment by ericwol-msft** [comment]
Since you are using DELIVER_AT_LEAST_ONCE, the SDK will wait for the PUBACK, and after it is received, call back into the application into the registered callback. Is the crash happing in the callback? I assume the SDK process restarted because of an AV fault. Is there a way to capture the callstack of the exception on a repo outside the device?

**Comment by ericwol-msft** [comment]
Does your hub name have -rrs- in it? If so, I see ThrottleBacklogLimitExceeded in the logs. What scale size is your hub?

**Comment by ericwol-msft** [comment]
looks like there is an AV at 0xffffffffffffffb1. Is it possible to run this under valgrind? It it possible that application is corrupting memory? Can you post a fill log dump (example the publish of PACKET_ID: 28554)?

**Comment by ericwol-msft** [comment]
Additional info needed. Is the timestamps UTC? If not, what is the offset? Is there a full debug output. Where is the trace that 28554 was sent to the hub? There is a DISCONNECT message, but we are still receiving PUBACKs. Was there a reconnect? What TLS stack is this using? Can you share your hub name?  

You might want to add log trace and printout queue_context/iotHubClientHandle/saved_user_callback_list to figure out which pointer is corrupted in iothub_ll_event_confirm_callback().
https://github.com/Azure/azure-iot-sdk-c/blob/d1de35c54f6d50fb921017465379f893862bbd5a/iothub_client/src/iothub_client_core.c#L459

**Comment by ericwol-msft** [comment]
Are you running an optimized build? I'm saying this because the 0xff0000000000 value is suspect. Also your callstack looks optimized and is missing functions in the stack. A non-optimized build callstack should look like this.

```
iothub_ll_event_confirm_callback(IOTHUB_CLIENT_CONFIRMATION_RESULT_TAG result, void * userContextCallback)
IoTHubClientCore_LL_SendComplete(DLIST_ENTRY_TAG * completed, IOTHUB_CLIENT_CONFIRMATION_RESULT_TAG result, void * ctx)
notifyApplicationOfSendMessageComplete(IOTHUB_MESSAGE_LIST_TAG * iothubMsgList, MQTTTRANSPORT_HANDLE_DATA_TAG * transport_data, IOTHUB_CLIENT_CONFIRMATION_RESULT_TAG confirmResult)
mqttOperationCompleteCallback(MQTT_CLIENT_TAG * handle, MQTT_CLIENT_EVENT_RESULT_TAG actionResult, const void * msgInfo, void * callbackCtx)
recvCompleteCallback(void * context, CONTROL_PACKET_TYPE_TAG packet, int flags, BUFFER_TAG * headerData)
completePacketData(MQTTCODEC_INSTANCE_TAG * codecData)
mqtt_codec_bytesReceived(MQTTCODEC_INSTANCE_TAG * handle, const unsigned char * buffer, unsigned __int64 size)
onBytesReceived(void * context, const unsigned char * buffer, unsigned __int64 size)
decode_ssl_received_bytes(TLS_IO_INSTANCE_TAG * tls_io_instance)
on_underlying_io_bytes_received(void * context, const unsigned char * buffer, unsigned __int64 size)
socketio_dowork(void * socket_io)
xio_dowork(XIO_INSTANCE_TAG * xio)
tlsio_openssl_dowork(void * tls_io)
xio_dowork(XIO_INSTANCE_TAG * xio)
mqtt_client_dowork(MQTT_CLIENT_TAG * handle)
IoTHubTransport_MQTT_Common_DoWork(void * handle)
IoTHubTransportMqtt_DoWork(void * handle)
IoTHubClientCore_LL_DoWork(IOTHUB_CLIENT_CORE_LL_HANDLE_DATA_TAG * iotHubClientHandle)
ScheduleWork_Thread(void * threadArgument)
```

**Comment by ericwol-msft** [comment]
I have tried to reproduce this issue using various throttling amounts, and was not able to see a SIGSEGV crash. Were you able to reproduce this under Valgrind on your end?

**Comment by ericwol-msft** [comment]
Closing this issue due to no responses. If you are able to collect more data please feel free to create another issue on this.
