### ISSUE TITLE
Downloading mb size files from Cloud IOTHUB

### ISSUE THREAD

**Issue by sarangkalbande** [Azure/azure-iot-sdk-c#21]
Hi All,
I wanted few inputs for downloading mb size files from Cloud IOTHUB to device.
Currently I am sending and receiving data in json format to/fro cloud.
Now I need to download big size files,I have seen Raspberry Pi example for firmware download
but its using serializer library Model methods which I dont want to use.

We should have sample example to download from cloud blob? 
How Can I achieve this?

**Comment by anporumb** [comment]
Hello @sarangkalbande,

IoTHubClient does not offer the possibility of downloading from Azure blob storage (therefore no sample on how to leverage IoTHub C Client SDK to do that).

I would point you to the blob storage documentation for C++: https://docs.microsoft.com/en-us/azure/storage/storage-c-plus-plus-how-to-use-blobs

Our firmware download sample does it "by convention" from a URL that is passed to the firmware process. That URL gets (eventually) downloaded by wget.

Best Regards,
Andrei Porumb

**Comment by olivierbloch** [comment]
Now tracked on [User Voice](https://feedback.azure.com/forums/321918-azure-iot/suggestions/19109089-add-samples-support-for-azure-storage-blob-downloa), please vote it up there.
Thanks
