### ISSUE TITLE
Upload large file to IoTHub blob storage with azure-iot-sdk-c

### ISSUE THREAD

**Issue by GeraldSchmitt** [Azure/azure-iot-sdk-c#211]
### What do we need?

From a device using the *azure-iot-sdk-c*, we want to upload a big file. 
This file can't fit in memory (or on the disk/flash), but is generated block by block by the device.
All these blocks should be uploaded one after the other on the cloud, and the corresponding 
file should be reconstructed.

We wish to expose the following  interface to the device, or something similar:

```C
LARGEFILE_HANDLE LARGEFILE_open(const IOTHUB_CLIENT_CONFIG* config,
                                const char* filename);

IOTHUB_CLIENT_RESULT LARGEFILE_write(LARGEFILE_HANDLE handle, 
                                     const unsigned char* source, 
                                     size_t size);

void LARGEFILE_close(LARGEFILE_HANDLE handle);
```
In other words : `fopen, fwrite, fclose`

All the function calls should be synchronous.
It would be the client responsibility to call as many `LARGEFILE_write` as necessary and check
the returned value in case of failure.
It would probably fit in the `_LL_` interface.

### How could we do it?

A similar process already exists in the sdk: the **UploadToBlob** functionnality,
exposed in **iothub_client_ll_uploadtoblob.h**.
The difference with our need is that the blocks are generated from the source buffer inside 
the function `Blob_UploadFromSasUri` (if the buffer is bigger than 64MB), 
in the file **blob.c**.

So basically, we would need to use nearly the same sequence of operations as a typical use of UploadToBlob, 
but expose a different interface.

We feel that there are mainly two ways of doing this:

+ Write a new module independent from **UploadToBlob**
  + *pros*: UploadToBlob left untouched
  + *cons*: Code dupplication
+ Extend the module **UploadToBlob**
  + *pros*: Less code dupplication
  + *cons*: Refactor UploadToBlob. We probably have to split existing function and 
    add more ressource handles, making the code more complex

### What now?

+ We could implement this outside the *azure-iot-sdk-c*, 
  but we think it would be easier and more logical to have *azure-iot-sdk-c* implement it.
+ We are ready to modify the *azure-iot-sdk-c* ourselves and make a pull request, 
  but before doing that, we want to know how to improve our chances to get the PR accepted.

#38 #contribution

**Comment by srberard** [comment]
I think this would be a useful feature.  Today the existing file upload functionality of the C SDK requires passing the file completely in memory.  On constrained devices this can be problematic.  Being able to do this in a buffered manner (similar to how fwrite works in the C standard library) as proposed above would be useful.  

In general, I would like to see more optimizations around memory in the C SDK.  The C SDK is typically used by devices that have limited resources.  Having to allocate large buffers or similar is not practical on many devices.  Especially those that run on microcontrollers (e.g. ARM Cortex-M class).

**Comment by markrad** [comment]
Just kicking around some ideas. Your suggestion would likely require a server change. However, if one added to the SDK an upload to blob function with a callback then (possibly) it could invoke the callback writing data to the socket until the callback returned zero. I'm not particularly familiar with HTTP protocol's handling of file uploads but I would guess the server assumes it is complete when the client closes the socket. We are happy to review pull requests.

_Mark Radbourne MSFT_

**Comment by srberard** [comment]
Hi Mark,
From what I understand this would not require a server change. The file transfer API uses the block transfer mechanism of Azure Storage. This uploads in chunks (i.e. blocks) and then commits them at the end. I think what is being proposed it to have an interface to do a buffered transfer as a series of calls, much like fwrite works. These would be uploaded as a series of blocks individually per call. Then committed at the end. In short, a series of calls to the LL API vs. the one call that exists today. The server side would not need to change.

-Stephen

**Comment by GeraldSchmitt** [comment]
Hi everyone,

I started to work on this contribution.
You can already have a look at the work in progress here :
https://github.com/GeraldSchmitt/azure-iot-sdk-c/tree/feature/upload_blob_by_chunk

I added the following functions to the interface :
```C
IOTHUB_CLIENT_LARGE_FILE_HANDLE IoTHubClient_LargeFileOpen(IOTHUB_CLIENT_HANDLE handle, 
                                                           const char* destinationFileName);
														   
IOTHUB_CLIENT_RESULT IoTHubClient_LargeFileClose(IOTHUB_CLIENT_LARGE_FILE_HANDLE handle);

IOTHUB_CLIENT_RESULT IoTHubClient_LargeFileWrite(IOTHUB_CLIENT_LARGE_FILE_HANDLE fileHandle, 
                                                 const unsigned char* source, 
			                         size_t size);
```

It seems to work well, at least in nominal conditions.
It's still not ready for a pull request though:
It still lacks documentation, tests, and there is some code dupplication left.

Feel free to have a look, test, and maybe tell me what you think!

Also, I won't be available until Monday 25 September, so don't expect a quick answer from me...

Gérald

**Comment by GeraldSchmitt** [comment]
Hi everyone,

One thing I would like to know before I go on with the specs and UT:

__Is the added public interface OK?__

It's in the files _iothub_client.h_ and _iothub_client.c_ and it looks like this:

```C
IOTHUB_CLIENT_LARGE_FILE_HANDLE IoTHubClient_LargeFileOpen(IOTHUB_CLIENT_HANDLE handle, 
                                                           const char* destinationFileName);
														   
IOTHUB_CLIENT_RESULT IoTHubClient_LargeFileClose(IOTHUB_CLIENT_LARGE_FILE_HANDLE handle);

IOTHUB_CLIENT_RESULT IoTHubClient_LargeFileWrite(IOTHUB_CLIENT_LARGE_FILE_HANDLE fileHandle, 
                                                 const unsigned char* source, 
						 size_t size);
```

Can someone validate these new functions, or tell me how to get it validated, or at least reviewed?
I would like to know as early as possible of I'm heading towards the wrong direction, so that I can make corrections.

Thanks in advance,

Gérald

**Comment by GeraldSchmitt** [comment]
The pull request is done.
I've also added a good amount of unit test (more coming soon).
Could someone give me some feedback?

**Comment by ewertons** [comment]
Hi @GeraldSchmitt ,
just leaving an update here, the PR is being handled by one of our engineers as you are aware.
Once it is merged, we will close this issue.
Thanks.

**Comment by jspaith** [comment]
Closing as https://github.com/Azure/azure-iot-sdk-c/pull/247 has addressed this.
