### ISSUE TITLE
Sending message error occurs after longrun

### ISSUE THREAD

**Issue by HITliuyu** [Azure/azure-iot-sdk-c#212]
# Description of the issue:
 Hi, I am using this [sample for edison](https://github.com/Azure-Samples/iot-hub-c-intel-edison-client-app) to develop my own project. Currently, I just send sensor data to IoT Hub so I didn't modify the main function. Since it's a sample by Azure, I guess there should not be some obvious code bugs.

When I kept running the app for few days, I always came across errors that stopped the app sending messages to IoT hub.  The error log output is as below. The messages can always be printed out which means it is stuck there when executing sending message operations. 
I am not sure if it's an issue of code quality or a common issue, could anyone with experiences take a quick pass and give a suggestion? many thanks

- **OS and version used:** Linux intel 3.10.98-poky-edison

- **SDK version used:** 2017-07-28-20-g2c8a62e

# Console log of the issue:
**First time when app was stuck**

Sending message: { "messageId": 653, "deviceId": "Edison", "moisture": 20.42 , "humidity": 20, "temperature": 20 }
Message sent to Azure IoT Hub
Read from Moisture Sensor value is 140 !
data received: 20 %, 20 C
Sending message: { "messageId": 654, "deviceId": "Edison", "moisture": 20.0 , "humidity": 20, "temperature": 20 }
Failed to send message to Azure IoT Hub
Read from Moisture Sensor value is 142 !
data received: 20 %, 20 C
Sending message: { "messageId": 655, "deviceId": "Edison", "moisture": 20.28 , "humidity": 20, "temperature": 20 }
Message sent to Azure IoT Hub
Read from Moisture Sensor value is 142 !
data received: 20 %, 20 C
Sending message: { "messageId": 656, "deviceId": "Edison", "moisture": 20.28 , "humidity": 20, "temperature": 20 }
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1129 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:304 1128: Failure sending control packet data
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1057 Error: mqtt_client_disconnect send failed
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1036 Invalid tlsio_state. Expected state is TLSIO_STATE_NOT_OPEN.
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:868 Error: io_open failed
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1233 failure connecting to address IoTGetStartedOk.azure-devices.net:0.
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1036 Invalid tlsio_state. Expected state is TLSIO_STATE_NOT_OPEN.
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:868 Error: io_open failed
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1233 failure connecting to address IoTGetStartedOk.azure-devices.net:0.
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1036 Invalid tlsio_state. Expected state is TLSIO_STATE_NOT_OPEN.
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:868 Error: io_open failed
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1233 failure connecting to address IoTGetStartedOk.azure-devices.net:0.
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1036 Invalid tlsio_state. Expected state is TLSIO_STATE_NOT_OPEN.
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:868 Error: io_open failed
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1233 failure connecting to address IoTGetStartedOk.azure-devices.net:0.
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1036 Invalid tlsio_state. Expected state is TLSIO_STATE_NOT_OPEN.
Error: Time:Tue Aug  1 18:16:19 2017 File:/home/root/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:868 Error: io_open failed

**Another time output**

Read from Moisture Sensor value is 0 !
checksum success
Sending message: { "messageId": 18119, "deviceId": "Edison", "moisture": 0.0 , "humidity": 25, "temperature": 24 }
Failed to send message to Azure IoT Hub
Read from Moisture Sensor value is 47 !
checksum success
Sending message: { "messageId": 18120, "deviceId": "Edison", "moisture": 6.71 , "humidity": 25, "temperature": 24 }
Error: Time:Thu Aug 17 17:31:40 2017 File:/home/root/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:626 Failure: getaddrinfo failure -3.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Thu Aug 17 17:31:40 2017 File:/home/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:688 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Aug 17 17:31:40 2017 File:/home/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1202 Failed opening the underlying I/O.
Error: Time:Thu Aug 17 17:31:40 2017 File:/home/root/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:974 Error: io_open failed
Error: Time:Thu Aug 17 17:31:40 2017 File:/home/root/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1519 failure connecting to address IoTGetStartedOk.azure-devices.net.
Error: Time:Thu Aug 17 17:31:41 2017 File:/home/root/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:626 Failure: getaddrinfo failure -3.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Thu Aug 17 17:31:41 2017 File:/home/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:688 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Aug 17 17:31:41 2017 File:/home/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1202 Failed opening the underlying I/O.
Error: Time:Thu Aug 17 17:31:41 2017 File:/home/root/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:974 Error: io_open failed
Error: Time:Thu Aug 17 17:31:41 2017 File:/home/root/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1519 failure connecting to address IoTGetStartedOk.azure-devices.net.
Error: Time:Thu Aug 17 17:31:43 2017 File:/home/root/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:626 Failure: getaddrinfo failure -3.

**Comment by sarangkalbande** [comment]
Seems like your network connection is dropping intermediately and Connection handle is no more valid.I faced a similar issue when connection drops and doesn't resume for some time then after
SDK Doesn't start working [sendng and receiving the data]automatically even after device connectivity resumes but if you restart the app things start to work again till it again drops the connection.
workaround:- Try resetting the global connection handle when there are no ACKs for 4-5 send messages.
SDK is still not reliable in terms of network operations.I have been playing with this from last 10 Months and trust me I faced hell lot of issues with respect to connectivity

**Comment by HITliuyu** [comment]
@sarangkalbande 
thanks a lot for your suggestion! I also doubted if this was due to wireless network connectivity issue but could not make sure of it, as every time the error messages were slightly different (but for sure the errors were reported in socketio_berkeley.c/ tlsio_openssl.c/mqtt_client.c/etc. files). I leave the app running for another few days, this time I still get temporary error messages, but it seemed recovered connectivity. The log is as below, maybe you are interested.
`
Read from Moisture Sensor value is 0 !
checksum success
Sending message: { "messageId": 1570, "deviceId": "Edison", "moisture": 0.0 , "humidity": 26, "temperature": 22 }
Message sent to Azure IoT Hub
Read from Moisture Sensor value is 0 !
checksum success
Sending message: { "messageId": 1571, "deviceId": "Edison", "moisture": 0.0 , "humidity": 25, "temperature": 23 }
Error: Time:Tue Aug 22 23:34:59 2017 File:/home/root/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:signal_callback Line:242 Socket received signal 13.
Error: Time:Tue Aug 22 23:34:59 2017 File:/home/root/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:814 Failure: sending socket failed. errno=107 (Transport endpoint is not connected).
Error: Time:Tue Aug 22 23:34:59 2017 File:/home/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:write_outgoing_bytes Line:585 Error in xio_send.
Error: Time:Tue Aug 22 23:34:59 2017 File:/home/root/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1314 Error in write_outgoing_bytes.
Error: Time:Tue Aug 22 23:34:59 2017 File:/home/root/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:323 1315: Failure sending control packet data
Error: Time:Tue Aug 22 23:34:59 2017 File:/home/root/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_publish Line:1033 Error: mqtt_client_publish send failed
Failed to send message to Azure IoT Hub
Read from Moisture Sensor value is 46 !
checksum success
Sending message: { "messageId": 1572, "deviceId": "Edison", "moisture": 6.57 , "humidity": 26, "temperature": 22 }
Message sent to Azure IoT Hub
`
Anyway, it's good to get confirmation from you and I will try to use your work around to see if it helps. Many thanks.

**Comment by ewertons** [comment]
Hi @HITliuyu ,
are you still experiencing this failure? Could you confirm if you still have this problem using the latest version of the SDK please?
Thanks.

**Comment by HITliuyu** [comment]
Hi @ewertons ,
I have not tested with the latest SDK in the same location where I got the issue before. But there is another device that has been running in the lab for more than one month without any issue, I guess the new SDK has greatly improved the stability of network connection. Thank you for your asking.

**Comment by ewertons** [comment]
Thanks for letting us know, @HITliuyu .
May we close this issue then? 
You can re-open this one if you hit the same issue again, or open a new one if you need help on any other point.

**Comment by HITliuyu** [comment]
Thank you @ewertons
