### ISSUE TITLE
socket/SSL errors in MQTT samples, consistently over different platforms, ISPs and SDK versions

### ISSUE THREAD

**Issue by klingonstrawhat** [Azure/azure-iot-sdk-c#214]
- **OS and version used:** <VERSION>Linux 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux, Linux 4.1.39-dey+gf1810a3 #10 SMP PREEMPT Tue Aug 8 11:19:42 CEST 2017 armv7l GNU/Linux

- **SDK version used:** <VERSION>version 1.1.14, version 1.1.15, version 1.1.20, version 1.1.21

# Description of the issue:
This issue seems similar to issue 212 and 213 but the behavior is somewhat different (connection errors before a successful connection was done), hence I opened another issue.

When I start the ./simplesample_mqtt (from serializer samples) or the iothub_client_sample_mqtt, I get connection erros like the ones shown in the Console log. During the past weeks, it became worse. First, I occasionally saw this error, then it appeared more often, especially when I was re-trying the application in short intervals. The last days, devices which where connected already sometimes lost connection for about an hour or half. This night, one device lost connection and never got it back. Right now, all our MQTT applications (on all platforms) don't connect to the IoT hub at all.
The AMQP version of the serializer sample works fine, messages reach the IoT hub, also after starting the app many times.

I'm testing the app on X86_64 Ubuntu and and an arm system (see version details above). I'm also testing it with the embedded Yocto system using not the WiFi and our default ISP, but a cellular connection from a different ISP. I'm furthermore testing with different versions of the SDK (see above). In all situations I have the connection issue right now.

Please request more information in case this is not enough.

# Code sample exhibiting the issue:
Code is the exact code from serializer/samples/simplesample_mqtt/ and iothub_client/samples/iothub_client_sample_mqtt/, just with the connection string applied.
In our production application, we also have device twin stuff. The problem there is the same.

# Console log of the issue:

./simplesample_mqtt 
Info: IoT Hub SDK for C, version 1.1.21
IoTHubClient accepted the message for delivery
Error: Time:Thu Aug 17 19:31:50 2017 File:/home/user/test/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:676 Failure: select failure.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Thu Aug 17 19:31:50 2017 File:/home/user/test/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:688 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Aug 17 19:31:50 2017 File:/home/user/test/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1202 Failed opening the underlying I/O.
Error: Time:Thu Aug 17 19:31:50 2017 File:/home/user/test/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:974 Error: io_open failed
Error: Time:Thu Aug 17 19:31:50 2017 File:/home/user/test/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1522 failure connecting to address sht-iot-hub.azure-devices.net.
Error: Time:Thu Aug 17 19:32:01 2017 File:/home/user/test/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:676 Failure: select failure.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Thu Aug 17 19:32:01 2017 File:/home/user/test/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:688 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Aug 17 19:32:01 2017 File:/home/user/test/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1202 Failed opening the underlying I/O.
Error: Time:Thu Aug 17 19:32:01 2017 File:/home/user/test/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:974 Error: io_open failed
Error: Time:Thu Aug 17 19:32:01 2017 File:/home/user/test/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1522 failure connecting to address sht-iot-hub.azure-devices.net.
Error: Time:Thu Aug 17 19:32:12 2017 File:/home/user/test/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:676 Failure: select failure.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR

A case where the device first fails, then succeeds to connect:

iothub-explorer monitor-ops --login "<connection-string>"
body: 
  protocol:          Mqtt
  authType:          {"scope":"device","type":"sas","issuer":"iothub","acceptingIpFilterRule":null}
  time:              2017-08-25T18:19:40.3166966Z
  operationName:     deviceDisconnect
  category:          Connections
  level:             Error
  statusCode:        404
  statusType:        404104
  statusDescription: DeviceConnectionClosedRemotely
  deviceId:          device-name
  ipAddress:         212.243.161.XXX
enqueuedTimeUtc:       Fri Aug 25 2017 20:19:45 GMT+0200 (CEST)
offset:                0
applicationProperties: 
  category:      Connections
  level:         Error
  operationName: deviceDisconnect
sequenceNumber:        0
annotations: 
  x-opt-sequence-number: 0
  x-opt-offset:          0
  x-opt-enqueued-time:   Fri Aug 25 2017 20:19:45 GMT+0200 (CEST)
offset:                512
enqueuedTimeUtc:       Fri Aug 25 2017 20:20:32 GMT+0200 (CEST)

body: 
  protocol:      Mqtt
  authType:      {"scope":"device","type":"sas","issuer":"iothub","acceptingIpFilterRule":null}
  time:          2017-08-25T18:20:27.4010995Z
  operationName: deviceConnect
  category:      Connections
  level:         Information
  deviceId:      device-name
  ipAddress:     212.243.161.XXX
annotations: 
  x-opt-sequence-number: 1
  x-opt-offset:          512
  x-opt-enqueued-time:   Fri Aug 25 2017 20:20:32 GMT+0200 (CEST)
applicationProperties: 
  category:      Connections
  level:         Information
  operationName: deviceConnect
sequenceNumber:        1

**Comment by Morozov-5F** [comment]
@klingonstrawhat, yeah, sometimes this happened to me, but I couldn't come up with a stable reproduction of this issue. I think that #213 and this one are closely connected. For me it all started after 1.1.14 -- it was latest release that worked somewhat fine.

**Comment by klingonstrawhat** [comment]
@Morozov-5F Yes, I can confirm that! I rolled back to version 1.1.14 and now the samples as well as our production code is working again (including features as device twin and direct methods), also after restarts. Whether it will stay connected will be evaluated during this night.

**Comment by Morozov-5F** [comment]
@klingonstrawhat, it sure works, but there are a couple of issues I've encountered -- lack of retry policies and in this version, connection status reported not in all cases. It just sometimes doesn't report disconnect when Wi-Fi access is gone, for example. Latest version fixes those issues but brings new one you've mentioned.

**Comment by sarangkalbande** [comment]
Guys, I faced these issue many times and solving one issue gives birth to another.
I never faced any issues with Ethernet connectivity since its very stable but wifi and cellular 
I faced lots of similar issues.
The workaround for this whenever connectivity goes down or if there are no send confirmations for continuous 4-5 messages for some time then It's better to reset the connection handle and things starts to work again as expected.

**Comment by klingonstrawhat** [comment]
I also have this issue with Ethernet connection. Maybe I will try resetting connection handle tomorrow...

**Comment by klingonstrawhat** [comment]
Ok, now I'm getting these errors also with the 1.1.14 version. I enabled verbose connection event logging in the IoT hub. Updated the first post.

**Comment by HITliuyu** [comment]
@klingonstrawhat 
Hi, how long time did you keep running before getting these errors? For me the application usually can survive few days before it got errors.

**Comment by klingonstrawhat** [comment]
@tameraw 
About a day or two before I began this post, it appeared every few hours. When I opened this issue, as stated, the program never connected at all.
At least the connection problems at the beginning of the program seem to become worse if I started the application often in the last few hours. After one day, it normally works fine again ("just" a few of these errors at the start of the program but after some retries it works). With the old version (1.1.14) it seems like there are now errors in between anymore, leading to connection loss for an hour or so as described above.

**Comment by ewertons** [comment]
Hi @klingonstrawhat ,
we just posted an update to issue #213 regarding fixes made to tlsio and socketio. 
Could you verify if the latest version of the Azure IoT C SDK fixes the issue you were experiencing?

Also, could you confirm the repro steps for your scenario?

**Comment by ewertons** [comment]
Hi @klingonstrawhat ,
this issue will be closed, but please feel free to reopen it once you have chance to follow up and still experience the problem.
Thanks,
Azure IoT SDK Team
