### ISSUE TITLE
Race condition in IoT-Hub-Device-Client initialization with openssl engine

### ISSUE THREAD

**Issue by Styne13** [Azure/azure-iot-sdk-c#2141]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
Ubuntu 18.04 LTS, Yocto Zeus, Cross Compiler for arm-angstom-linux-gnueabi

**SDK Version (Please Give Commit SHA if Manually Compiling)**
LTS_07_2021_Ref01
NXP plug and trust middleware 3.03.00 (Provides openssl engine for SE050)

**Protocol**
SAMPLE_MQTT_OVER_WEBSOCKETS

**Describe the Bug**
We found a race condition during IoT-Hub-Device-Client initialization.
We use the following code to initialize IoT-Hub-Device-Client using mutual TLS authentication using a private key from an NXP secure element. In small (low latency) network environments the first connect works, every retry does not work. In bigger network environments with higher latency even the first connect does not work.

We see a difference in handling the openssl engine between the working connects and the non-working connects.
When we set the key type to KEY_TYPE_ENGINE, the Azure-IOT-SDK-C tries to load the private key using the load-method from the engine, which is not implemented in the provided openssl engine by NXP.
When we are connected to (small) home-networks, the Azure-IOT-SDK-C tries to connect before all SetOption commands are executed and this leads to successful authentication using the openssl engine (without KEY_TYPE_ENGINE).

The provided sample to reproduce uses iothub_ll_client_x509_sample, sets options and adds sleep to simulate higher latency network:
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include "iothub.h"
#include "iothub_device_client_ll.h"
#include "iothub_client_options.h"
#include "iothub_message.h"
#include "azure_c_shared_utility/threadapi.h"
#include "azure_c_shared_utility/shared_util_options.h"

#define SAMPLE_MQTT_OVER_WEBSOCKETS
#define SAMPLE_OPENSSL_ENGINE "e4sss"

int main(void)
{
    IOTHUB_CLIENT_TRANSPORT_PROVIDER protocol;
    IOTHUB_MESSAGE_HANDLE message_handle;
    size_t messages_sent = 0;
    const char* telemetry_msg = "test_message";
    bool trace_on = true;
    int keep_alive = 60;
    int retry_interval = 30;

    // Select the Protocol to use with the connection
#ifdef SAMPLE_MQTT
    protocol = MQTT_Protocol;
#endif // SAMPLE_MQTT
#ifdef SAMPLE_MQTT_OVER_WEBSOCKETS
    protocol = MQTT_WebSocket_Protocol;
#endif // SAMPLE_MQTT_OVER_WEBSOCKETS
#ifdef SAMPLE_AMQP
    protocol = AMQP_Protocol;
#endif // SAMPLE_AMQP
#ifdef SAMPLE_AMQP_OVER_WEBSOCKETS
    protocol = AMQP_Protocol_over_WebSocketsTls;
#endif // SAMPLE_AMQP_OVER_WEBSOCKETS
#ifdef SAMPLE_HTTP
    protocol = HTTP_Protocol;
#endif // SAMPLE_HTTP

    IOTHUB_DEVICE_CLIENT_LL_HANDLE device_ll_handle;

    // Used to initialize IoTHub SDK subsystem
    (void)IoTHub_Init();

    (void)printf("Creating IoTHub handle\r\n");
    // Create the iothub handle here
    device_ll_handle = IoTHubDeviceClient_LL_CreateFromConnectionString(connectionString, protocol);
    if (device_ll_handle == NULL)
    {
        (void)printf("Failure creating IotHub device. Hint: Check your connection string.\r\n");
    }
    else
    {
        // Set any option that are neccessary.
        // For available options please see the iothub_sdk_options.md documentation
        //bool traceOn = true;
        //IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_LOG_TRACE, &traceOn);

        // Setting the Trusted Certificate. This is only necessary on systems without
        // built in certificate stores.
#ifdef SET_TRUSTED_CERT_IN_SAMPLES
        IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_TRUSTED_CERT, certificates);
#endif // SET_TRUSTED_CERT_IN_SAMPLES

#if defined SAMPLE_MQTT || defined SAMPLE_MQTT_OVER_WEBSOCKETS
        //Setting the auto URL Encoder (recommended for MQTT). Please use this option unless
        //you are URL Encoding inputs yourself.
        //ONLY valid for use with MQTT
        bool urlEncodeOn = true;
        (void)IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_AUTO_URL_ENCODE_DECODE, &urlEncodeOn);
#endif
        IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_LOG_TRACE, &trace_on);
        IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_KEEP_ALIVE, &keep_alive);
        IoTHubDeviceClient_LL_SetRetryPolicy(device_ll_handle, IOTHUB_CLIENT_RETRY_LINEAR_BACKOFF, 30);
        IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_RETRY_INTERVAL_SEC, &retry_interval);

        // Set the X509 certificates in the SDK
        
        //delay here to simulate higher latency network
        sleep(1);

        if (
#ifdef SAMPLE_OPENSSL_ENGINE
            (IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_OPENSSL_ENGINE, opensslEngine) != IOTHUB_CLIENT_OK) ||
            (IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_OPENSSL_PRIVATE_KEY_TYPE, &x509_key_from_engine) != IOTHUB_CLIENT_OK) ||
#endif
            (IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_X509_CERT, x509certificate) != IOTHUB_CLIENT_OK) ||
            (IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_X509_PRIVATE_KEY, x509privatekey) != IOTHUB_CLIENT_OK)
            )
        {
            printf("failure to set options for x509, aborting\r\n");
        }
        else
        {
            do
            {
                if (messages_sent < MESSAGE_COUNT)
                {
                    // Construct the iothub message from a string or a byte array
                    message_handle = IoTHubMessage_CreateFromString(telemetry_msg);
                    //message_handle = IoTHubMessage_CreateFromByteArray((const unsigned char*)msgText, strlen(msgText)));

                    // Set Message property
                    (void)IoTHubMessage_SetMessageId(message_handle, "MSG_ID");
                    (void)IoTHubMessage_SetCorrelationId(message_handle, "CORE_ID");
                    (void)IoTHubMessage_SetContentTypeSystemProperty(message_handle, "application%2Fjson");
                    (void)IoTHubMessage_SetContentEncodingSystemProperty(message_handle, "utf-8");

                    // Add custom properties to message
                    (void)IoTHubMessage_SetProperty(message_handle, "property_key", "property_value");

                    (void)printf("Sending message %d to IoTHub\r\n", (int)(messages_sent + 1));
                    IoTHubDeviceClient_LL_SendEventAsync(device_ll_handle, message_handle, send_confirm_callback, NULL);

                    // The message is copied to the sdk so the we can destroy it
                    IoTHubMessage_Destroy(message_handle);

                    messages_sent++;
                }
                else if (g_message_count_send_confirmations >= MESSAGE_COUNT)
                {
                    // After all messages are all received stop running
                    g_continueRunning = false;
                }

                IoTHubDeviceClient_LL_DoWork(device_ll_handle);
                ThreadAPI_Sleep(1);

            } while (g_continueRunning);
        }
        // Clean up the iothub sdk handle
        IoTHubDeviceClient_LL_Destroy(device_ll_handle);
    }
    // Free all the sdk subsystem
    IoTHub_Deinit();

    printf("Press any key to continue");
    (void)getchar();

    return 0;
}
```

openssl config in /etc/ssl/openssl.cnf:
```
openssl_conf = nxp_engine

[nxp_engine]
engines=engine_section

[engine_section]
e4sss_se050 = e4sss_se050_section

[e4sss_se050_section]
engine_id = e4sss
dynamic_path = /usr/lib/libsss_engine.so
init = 1
default_algorithms = EC
```

**Console Logs**
From our Client:
Oct 28 15:04:58 : [DEBUG] <ASSC_azure_service_dispatcher_azure_sdk_connector.c:217> ASSC_sdk_connector_init_iot_hub(): Retry policy = IOTHUB_CLIENT_RETRY_LINEAR_BACKOFF. Seconds of retry: 300
Oct 28 15:04:58 : [INFO ] <ASD_azure_service_dispatcher_agent_dbus.c:620> ASD_on_handle_connect(): Connection to IoT Hub established using network interface wlan0
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:31 unable to load private key from ENGINE.
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:38   [0] error:2609607D:engine routines:ENGINE_load_private_key:no load function
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/c-utility/adapters/tlsio_openssl.c Func:log_ERR_get_error Line:489 unable to use x509 authentication
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1430 Failed creating the OpenSSL instance.
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/c-utility/src/uws_client.c Func:uws_client_open_async Line:1700 Opening the underlying IO failed
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/c-utility/src/wsio.c Func:wsio_open Line:519 Opening the uws instance failed.
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1118 Error: io_open failed
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2696 failure connecting to address XY.azure-devices.net.
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:31 unable to load private key from ENGINE.
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:38   [0] error:2609607D:engine routines:ENGINE_load_private_key:no load function
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/c-utility/adapters/tlsio_openssl.c Func:log_ERR_get_error Line:489 unable to use x509 authentication
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1430 Failed creating the OpenSSL instance.
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/c-utility/src/uws_client.c Func:uws_client_open_async Line:1700 Opening the underlying IO failed
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/c-utility/src/wsio.c Func:wsio_open Line:519 Opening the uws instance failed.
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1118 Error: io_open failed
Oct 28 15:04:58 : Error: Time:Thu Oct 28 15:04:58 2021 File:/usr/src/debug/azure-iot-sdk-c/2.0.0-r1/git/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2696 failure connecting to ad

From provided sample:
./iothub_ll_client_x509_sample 
ssse-flw: EmbSe_Init(): Entry
[...]
ssse-flw: Version: 1.0.5
ssse-flw: EmbSe_Init(): Exit
Creating IoTHub handle
Sending message 1 to IoTHub
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:31 unable to load private key from ENGINE.
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:38   [0] error:2609607D:engine routines:ENGINE_load_private_key:no load function
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:log_ERR_get_error Line:489 unable to use x509 authentication
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1430 Failed creating the OpenSSL instance.
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/c-utility/src/uws_client.c Func:uws_client_open_async Line:1700 Opening the underlying IO failed
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/c-utility/src/wsio.c Func:wsio_open Line:519 Opening the uws instance failed.
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1118 Error: io_open failed
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2696 failure connecting to address XY.azure-devices.net.
Sending message 2 to IoTHub
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:31 unable to load private key from ENGINE.
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:38   [0] error:2609607D:engine routines:ENGINE_load_private_key:no load function
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:log_ERR_get_error Line:489 unable to use x509 authentication
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1430 Failed creating the OpenSSL instance.
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/c-utility/src/uws_client.c Func:uws_client_open_async Line:1700 Opening the underlying IO failed
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/c-utility/src/wsio.c Func:wsio_open Line:519 Opening the uws instance failed.
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1118 Error: io_open failed
Error: Time:Wed Nov  3 10:13:09 2021 File:/home/irecc/eclipse-workspace/cpp-eclipse/azure_pipeline_work/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2696 failure connecting to address XY.azure-devices.net.

@vslepakov

**Comment by danewalton** [comment]
Hi @Styne13 do you have logs of a successful authentication?

**Comment by danewalton** [comment]
The logs here don't seem to match up in timing. On the logs for the **not working** condition, I see from your application the following:

```log
Oct 28 15:04:58 : [DEBUG] <ASSC_azure_service_dispatcher_azure_sdk_connector.c:217> ASSC_sdk_connector_init_iot_hub(): Retry policy = IOTHUB_CLIENT_RETRY_LINEAR_BACKOFF. Seconds of retry: 300
Oct 28 15:04:58 : [INFO ] <ASD_azure_service_dispatcher_agent_dbus.c:620> ASD_on_handle_connect(): Connection to IoT Hub established using network interface wlan0
```

but on the working its

```log
Oct 28 15:07:44 [DEBUG] <ASD_azure_service_dispatcher_agent_dbus.c:605> ASD_on_handle_connect(): Network connection established on wlan0. Try to connect to IoT Hub
Oct 28 15:07:44 [INFO ] <ASSC_azure_service_dispatcher_azure_sdk_connector.c:181> ASSC_sdk_connector_init_iot_hub(): Creating IoTHub Device handle to IoTHub-URL XY.azure-devices.net.
```

So the `ASD_on_handle_connect()` comes before the `ASSC_sdk_connector_init_iot_hub()` in the working case.

Do you have multiple agents here and the timing between system networking initialization and initialization of the IoT Hub client is not as it should?

Ultimately my question here is: Is the race condition in our code or is it in your application? I see our code failing to initialize an OpenSSL instance and that could be because your initialization code is not ready?

**Comment by esven** [comment]
In the non-working example, you see the OpenSSL instance cannot be initialized because the Azure SDK is trying to initialize it differently to the non-working example.
In the working example the OPTION_OPENSSL_PRIVATE_KEY_TYPE has not yet been set to KEY_TYPE_ENGINE. And therefore the SDK is not trying to call the private_key_load_function of the engine but using the PEM file containing the private key reference to the secure element.
In the non-working example the OPTION_OPENSSL_PRIVATE_KEY_TYPE has been set to KEY_TYPE_ENGINE and therefore the SDK tries to call the private_key_load_function of the engine which is not implemented in the engine by NXP.

We assume the race condition being in the SDK and not in our code. Currently, we don't understand that the IoTHubDeviceClient is trying to reach the IoT Hub before all the SetOption Commands have been issued?

**Comment by danewalton** [comment]
I'm not quite sure that's possible unless you have evidence that it is indeed happening in the SDK. You are using the `_LL_` layer which is the lower-level, single threaded implementation of the library. 

> Currently, we don't understand that the IoTHubDeviceClient is trying to reach the IoT Hub before all the SetOption Commands have been issued?

The options are populated on the client in a serial, synchronous manner. We don't spin up the client to connect and populate the options concurrently.

**Comment by danewalton** [comment]
I'm going to have to close this for now. The platform is not officially supported and without further info detailing how the SDK code is running into a race condition, it is difficult for us to help.
