### ISSUE TITLE
MQTT & MQTT_WS fatal crash when renewing SAS token

### ISSUE THREAD

**Issue by Emb3ddev** [Azure/azure-iot-sdk-c#2148]
OS: Openwrt 18.06, ARM a7 neon
Device: GL-iNet Convexa-S1300

Build enviroment: Ubuntu 20.04 LTS

SDK commit: d1d07b30ff286faf27bb585a1fcc037112fe5111

Issue:
MQTT SAS token renewal that happens 48 minutes after successful authentication causes SDK to crash fatally. Unfortunately I can't pinpoint where problem lies exactly but only once i have seen different error log with tracing info. Logs are below.

Log 1 (The usual kind):
> <- 12:32:09 PUBACK | PACKET_ID: 147
> -> 12:32:12 DISCONNECT
> FATAL: exception not rethrown
> Aborted
> root@OpenWrt:/# 

Log 2 (happened only once):
> -> 10:17:47 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/xxxxxxxxxxxxxxxx/messages/events/ | PACKET_ID: 64 | PAYLOAD_LEN: 282
> Error: Time:Thu Nov  4 10:18:15 2021 File:azure-iot-sdks-1/c-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:1068 Socketio_Failure: Receiving data from endpoint: errno=104.
> FATAL: exception not rethrown
> Aborted
> root@OpenWrt:/#

Unfortunately I can not provide most of the code "as is". However here is how initialization & run is performed. I hope i have missed something trivial.:
```

#define CLOUD_PROTOCOL_MQTT_WS


// Variables
const char* azure_iot_version_info = "";
std::string hub_id = "";
std::string hub_key = "";
std::string hub_url = "";
std::string hub_scope_id = "";
CLIENT_INFO hub_client_ctx = { 0 };
PROV_DEVICE_LL_HANDLE hub_device_provider_handle = NULL;
IOTHUB_DEVICE_CLIENT_LL_HANDLE hub_device_client_handle = NULL;
IOTHUB_CLIENT_TRANSPORT_PROVIDER hub_transport_protocol = NULL;

// SDK initializator
int _init_(int* runflag) {
	int roc, result = 0;
	PROV_DEVICE_RESULT roc_pdrv;
	IOTHUB_CLIENT_RESULT roc_crv;

	// CFGs
	bool cfg_log_trace = true;
	bool cfg_encode_url = true;

	// Clear variables
	hub_url = "";
	hub_scope_id = "";
	hub_key = "";
	hub_device_provider_handle = NULL;
	hub_device_client_handle = NULL;
	hub_transport_protocol = NULL;
	memset(&hub_client_ctx, 0, sizeof(CLIENT_INFO));

	try {

		// Init variables
		azure_iot_version_info = Prov_Device_LL_GetVersionString();
		hub_url = IOT_URL;
		hub_scope_id = IOT_ID_SCOPE;


	#ifdef CLOUD_PROTOCOL_MQTT
		hub_transport_protocol = MQTT_Protocol;
	#endif // CLOUD_PROTOCOL_MQTT

	#ifdef CLOUD_PROTOCOL_MQTT_WS
		hub_transport_protocol = MQTT_WebSocket_Protocol;
	#endif // CLOUD_PROTOCOL_MQTT_WS

		// GENERATE KEY HERE
		hub_key = "IOT-HUB-KEY";

		// Init hub
		roc = IoTHub_Init();

		// Fail check
		if (roc) throw 4;

		// Mark IoTHub initialized 
		state_init_hub = 1;

		// Set key type
		roc = prov_dev_security_init(SECURE_DEVICE_TYPE_SYMMETRIC_KEY);

		// Security provider initialization failed
		if (roc) throw 5;

		// Mark security prov as initialized
		state_init_provSecurity = 1;

		// Set security provider symmetric key
		roc = prov_dev_set_symmetric_key_info(hub_id.c_str(), hub_key.c_str());

		// Failed to set security provider symmetric key
		if (roc) throw 6;

		// Create IoTHub handle
	#ifdef CLOUD_PROTOCOL_MQTT
		hub_device_provider_handle = Prov_Device_LL_Create(hub_url.c_str(), hub_scope_id.c_str(), Prov_Device_MQTT_Protocol);
	#endif // CLOUD_PROTOCOL_MQTT

	#ifdef CLOUD_PROTOCOL_MQTT_WS
		hub_device_provider_handle = Prov_Device_LL_Create(hub_url.c_str(), hub_scope_id.c_str(), Prov_Device_MQTT_WS_Protocol);
	#endif // CLOUD_PROTOCOL_MQTT_WS


		// Failed to create device provider
		if (hub_device_provider_handle == NULL) throw 7;

		// Set option: log trace
		roc_pdrv = Prov_Device_LL_SetOption(hub_device_provider_handle, PROV_OPTION_LOG_TRACE, &cfg_log_trace);

		// Fail check
		if (roc_pdrv != PROV_DEVICE_RESULT_OK) throw 8;

		// Send registration request
		roc_pdrv = Prov_Device_LL_Register_Device(hub_device_provider_handle, __cb_status_dev_reg__, &hub_client_ctx, __cb_status_reg__, &hub_client_ctx);

		// Fail check
		if (roc_pdrv != PROV_DEVICE_RESULT_OK) throw 9;

		// wait for registration to complete or for shutdown command
		while (*runflag) {

			// Process registration
			Prov_Device_LL_DoWork(hub_device_provider_handle);

			// Case: successfull 
			if (hub_client_ctx.registration_complete == 1) break;

			// Case: failed
			if (hub_client_ctx.registration_complete == 2) throw 10;

			// Limit cpu usage
			std::this_thread::sleep_for(std::chrono::milliseconds(hub_client_ctx.sleep_time));
		}

		// Cancel if shutting down
		if (!*runflag) throw 1;

		// Authenticate device
	#ifdef CLOUD_PROTOCOL_MQTT
		hub_device_client_handle = IoTHubDeviceClient_LL_CreateFromDeviceAuth(hub_client_ctx.iothub_uri, hub_client_ctx.device_id, MQTT_Protocol);
	#endif // CLOUD_PROTOCOL_MQTT

	#ifdef CLOUD_PROTOCOL_MQTT_WS
		hub_device_client_handle = IoTHubDeviceClient_LL_CreateFromDeviceAuth(hub_client_ctx.iothub_uri, hub_client_ctx.device_id, MQTT_WebSocket_Protocol);
	#endif // CLOUD_PROTOCOL_MQTT_WS


		// Fail check
		if (hub_device_client_handle == NULL) throw 12;

		// Set log trace option to client handle
		roc_crv = IoTHubDeviceClient_LL_SetOption(hub_device_client_handle, OPTION_LOG_TRACE, &cfg_log_trace);

		// Fail check
		if (roc_crv != IOTHUB_CLIENT_OK) throw 13;

	#if defined CLOUD_PROTOCOL_MQTT || defined CLOUD_PROTOCOL_MQTT_WS

		// Set url encryption option to IoTHub
		roc_crv = IoTHubDeviceClient_LL_SetOption(hub_device_client_handle, OPTION_AUTO_URL_ENCODE_DECODE, &cfg_encode_url);

	#endif // defined CLOUD_PROTOCOL_MQTT || defined CLOUD_PROTOCOL_MQTT_WS

		// Fail check
		if (roc_crv != IOTHUB_CLIENT_OK) throw 14;

		// Set status callback to IoTHub
		roc_crv = IoTHubDeviceClient_LL_SetConnectionStatusCallback(hub_device_client_handle, __cb_status_conn__, NULL);

		// Fail check
		if (roc_crv != IOTHUB_CLIENT_OK) throw 15;

	} catch (int err) {

		// Clean up the mess we made
		_deinit_();

		// Return error code 
		return err;
	}

	// Return OK
	return 0;
}

// Main code executing thread
int thread(int* runflag) {
	int roc;

	// Initialize cloud service (init, register device & connect to IoTHub)
	roc = _init_(runflag);

	// Close thread with error code & log event 
	if (roc) return 1;

	while (*runflag) {

		// Send messages to SDK
		_send_queued_message_();

		// Process data
		IoTHubDeviceClient_LL_DoWork(hub_device_client_handle);

		// Do work on device side if needed
		Prov_Device_LL_DoWork(hub_device_provider_handle);

		// If program is not closing...
		if (*runflag) usleep(10 * 1000); // 10ms
	}

	// Deinitialize azure-sdk
	_deinit_();

	// Return OK
	return 0;
}

```

**Comment by danewalton** [comment]
The socket `104` error is likely happening since the SAS token is expiring (as you have pointed out).
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-troubleshoot-error-404104-deviceconnectionclosedremotely#cause-1

So in scenario 1, it does reconnect....but in scenario 2 it does not?

**Comment by danewalton** [comment]
@Emb3ddev any updates here?

**Comment by danewalton** [comment]
Closing for now for inactivity. Please let us know if you would like it reopened.

**Comment by Emb3ddev** [comment]
@danewalton Yes, issue is still active. Sorry i couldn't answer sooner. I am certain that issue is in IoT device side, but I have not been able to find it.

**Comment by danewalton** [comment]
Without extended logs and instructions to reproduces, unfortunately there isn't a whole lot we can do. I will say it looks like you're using a threaded environment and using the `_LL_` APIs. Know that those are not thread safe by default. If you are attempting to program for a multi-threaded use case, be careful of concurrent accesses.

**Comment by Emb3ddev** [comment]
@danewalton 

I changed all _LL_ commands to non- _LL_ commands (with minor modifications how service thread is handling message processing). Crashing issue appears to be fixed.

Here is log after changes:
> -> 12:49:44 DISCONNECT
> 2021.11.25 12:49:44 INFO CloudService::__cb_status_conn__(): Status = UNAUTHENTICATED, reason = EXPIRED_SAS_TOKEN
> -> 12:49:45 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: xxxxxxxxxxxxxxxx/yyyyyyyyyyyyyyyyyyyy/?api-version=2020-09-30&DeviceClientType=iothubclient%2f1.8.0%20(native%3b%20Linux%3b%20armv7l) | PWD: XXXX | CLEAN: 0
> <- 12:49:45 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
> 2021.11.25 12:49:45 INFO CloudService::__cb_status_conn__(): Status = AUTHENTICATED, reason = OK

Bad side about this is that I no longer can check if service thread is actually working or not.

Asynchronous API uses _LL_ functions but do not appear to have problems with it. Are demo/example files missing important background process call?

Thank you for help. I can finally put this project to bed.
