### ISSUE TITLE
how does this library support SNI working with TLS hostname validation?

### ISSUE THREAD

**Issue by edwardt** [Azure/azure-iot-sdk-c#2154]
It is not clear from documentation how the library works under TLS hostname validation under the case of SNI (Server name indicator). Does it use the hostname set by SNI extension to validation the cert or how that works? How that behavior in library justified against published RFC?

**Comment by danewalton** [comment]
Hi @edwardt we have SNI enabled in various tlsio adpaters. Please see the following where it is enabled or disabled.

- [OpenSSL](https://github.com/Azure/azure-c-shared-utility/blob/2d74785c2b475ca94321114a23f8007094bdac11/adapters/tlsio_openssl.c#L1023-L1047)
- [schannel](https://github.com/Azure/azure-c-shared-utility/blob/2d74785c2b475ca94321114a23f8007094bdac11/adapters/tlsio_schannel.c#L327-L330)
- [WolfSSL](https://github.com/Azure/azure-c-shared-utility/blob/2d74785c2b475ca94321114a23f8007094bdac11/adapters/tlsio_wolfssl.c#L1009-L1014)
- [mbedTLS via compilation](https://tls.mbed.org/kb/how-to/use-sni)

Let me know if that helps answer your question.

**Comment by danewalton** [comment]
closing for now for inactivity
