### ISSUE TITLE
Distributed Tracing support

### ISSUE THREAD

**Issue by eedorenko** [Azure/azure-iot-sdk-c#2167]
I have followed the [guidance on distributed tracing](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-distributed-tracing). I have an updated `iothub_ll_telemetry_sample` working as expected and sending messages with `tracestate` property. I can see this system property in the message on the IoT Hub side.
But! IoT Hub doesn't log anything under DistributedTracing category.
Is this functionality still alive?

**Comment by asergaz** [comment]
Relates with: https://github.com/MicrosoftDocs/azure-docs/issues/84386

**Comment by danewalton** [comment]
Hi @eedorenko. Let me look into that. Just for my knowledge, how are you setting up the diagnostic? AKA sending it to a storage archive, stream to event hub, etc.

**Comment by eedorenko** [comment]
@asergaz Yes, I can see this for all messages
<img width="1110" alt="Screen Shot 2021-11-29 at 4 14 28 PM" src="https://user-images.githubusercontent.com/20337555/143968657-36594a1b-5773-46aa-85fe-939ff5e8dc97.png">

I can also that the message arrives at IoT Hub and it has `tracestate` system property

![Screen Shot 2021-11-29 at 5 19 23 PM](https://user-images.githubusercontent.com/20337555/143968672-a192fe7c-d7bd-486b-8b7f-22a217c17249.png)

**Comment by eedorenko** [comment]
Hi @danewalton,
the diagnostic is configured with "Send to Log Analytics workspace" option.

**Comment by danewalton** [comment]
Hi @eedorenko after asking around this is currently not in a working state. We are working to remove the documentation which you had linked. Sorry for the confusion. I'll consider this closed for now.
