### ISSUE TITLE
Is there a way to to set custom retry policy ?

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/azure-iot-sdk-c#2169]
We are using "IOTHUB_CLIENT_RETRY_INTERVAL" retry policy and it retrying connection in every 5 seconds.
This will increase size of our log incase our device in disconnected state for long duration.

sdk logs for disconnection :
```
INFO: Failed DNS lookup for our-iothub.azure-devices.net: -2
ERROR: DNS resolution failed
ERROR: lookup_address_and_connect_socket failed
ERROR: Error: failure opening connection to endpoint
```
We are seeing these logs in each retry when device is not able to connect with iothub. 
is there a way to avoid these logs ?
Can we support custom retry using c sdk ?

**Comment by danewalton** [comment]
Hi @rajaggrawal have you tried using the [`IOTHUB_CLIENT_RETRY_POLICY`](https://github.com/Azure/azure-iot-sdk-c/blob/32942abb994f6855edc2a4dee8afd80735df4151/iothub_client/inc/iothub_client_core_common.h#L65) option?

**Comment by danewalton** [comment]
Closing this for now for inactivity. Please let us know if you have any further questions.
