### ISSUE TITLE
azure iot sdk c cross compile uuid issue

### ISSUE THREAD

**Issue by HarishKavali** [Azure/azure-iot-sdk-c#218]
Hi i am trying to build azure-iot-sdk for arm

i am getting below error
Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/uniqueid_linux.c.o
/home/vagrant/rfid/CNP_Pkgs/CNP/Linux_Pkgs/output.if2r1/azure_iot_sdk-1.0/azure-iot-sdk-c/c-utility/adapters/uniqueid_linux.c:7: **fatal error: uuid/uuid.h:** No such file or directory

if i  set use_default_uuid=off  then wont get the above error.
what is the purpose of **use_default_uuid** and how it will effect my application.

Thanks,
Harish

**Comment by HarishKavali** [comment]
Update: sorry I won't get error if I set use_default_uuid=ON

**Comment by jcwren** [comment]
It probably wants you to install uuid-dev (azure-uamqp-c needs this, for example). From the instructions for azure-uamqp-c:
```
sudo apt-get update
sudo apt-get install -y git cmake build-essential curl libcurl4-openssl-dev libssl-dev uuid-dev
```

**Comment by jakethiem** [comment]
HarishKavali,
I received that error while cross compiling for arm also. I installed libuuid-1.0.3 into my host filesystem and that alleviated the errors.

**Comment by jebrando** [comment]
@HarishKavali  are you still having issues with uuid?

**Comment by HarishKavali** [comment]
Hi jebrando,

Sorry for very late reply. As suggested in the above comments i had resolved the issue by providing uuid on  my embedded device.

Thanks,
Harish

**Comment by sumitkvsl** [comment]
where i can find use_default_uuid

I'm also getting same issue while compiling the azure iot c program on intel edison

**Comment by jebrando** [comment]
A generic implementation of use_default_uuid of is [here](https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/uniqueid_stub.c.) the cmake variable is defined [here](https://github.com/Azure/azure-c-shared-utility/blob/f0642196af85aeb4f2717d9cc11176290f321fb8/CMakeLists.txt#L25)
