### ISSUE TITLE
Issue with sending telemetry data to azure IoT HUB

### ISSUE THREAD

**Issue by CreativeMnd** [Azure/azure-iot-sdk-c#2185]
Hi,

Facing issue to send the telemetry data to azure iot hub, after porting the device firmware from Ubuntu 14.04 environment to Ubuntu 18.04 environment. 

The device firmware is able to communicate to IoT hub on Ubuntu 14.04 environment.

Create SSL self signed certificate using OpenSSL(v1.0.2), followed by device is able to register to azure IoT hub and can create connection string without any issue using the SSL certificate, also the connection string gets destroyed and re-created as expected.

Able to receive the date & time from the Cloud to sync the device with UTC time.

The issue starts when we are about to send the telemetry data to IoT hub over azure-iot-sdk-c client using protocol(MQTT) and ended up with issue i.e. Telemetry data not getting pushed/populated to IoT hub.

Device OS:

    Ubuntu 18.04

Lib. Versions used:

    azure-iot-sdk-c (v 1.2.2)
    OpenSSL (v 1.0.2)
    JSON-C (v 0.12.99)

Protocol:

    MQTT (of azure-iot-sdk-c)

Azure-iot-sdk-c library build configuration:

    log_dir=$build_root
    run_e2e_tests=OFF
    run_sfc_tests=OFF
    run_longhaul_tests=OFF
    build_amqp=ON
    build_http=ON
    build_mqtt=ON
    use_default_uuid=ON
    no_blob=OFF
    run_unittests=OFF
    build_python=OFF
    build_javawrapper=OFF
    run_valgrind=0
    build_folder=$build_root"/cmake/iotsdk_linux"
    make=true
    toolchainfile=" "
    cmake_install_prefix=" "
    openssl_root_dir=" "
    openssl_include_dir="/usr/local/include/"
    curl_root_dir=" "
    curl_include_dir="/usr/local/include/"
    no_logging=OFF
    prov_auth=OFF
    prov_use_tpm_simulator=OFF

Code Snippet/Flow :

Step 1:- Registration of device using the device details(Device Sl. No, Unique ID etc)during registration process and generate

    HostNam
    SharedAccessKey

Step 2:- Create connectionString using HostName, DeviceId & SharedAccessKey

Step 3:- Create iotHubClientHandle using the below API

    IoTHubClient_LL_CreateFromConnectionString(connectionString, MQTT_Protocol)

Step 4:- Updating the IoT hub messageHandle using byte array also updating the msgTrackID as below

    messages[msgIndex].messageHandle = IoTHubMessage_CreateFromByteArray((const unsigned char*)msgText, strlen(msgText))

Step 5:- Updating MAP_HANDLE using messageHandle and msgTrackID using the below API

    Map_AddOrUpdate()

Step 6:- Sending the message to IoT Hub and also registered a callback to get the confirmation, as below.

    if (IoTHubClient_LL_SendEventAsync(iotHubClientHandle, messages[msgIndex].messageHandle, CLD_SendConfirmationCallback, &messages[msgIndex]) != IOTHUB_CLIENT_OK)

Step 7:- Step 6 is getting success, confirmed as below log

    IoTHubClient_LL_SendEventAsync accepted message for transmission to IoT Hub with msgTrackID=5 and index=1

Issue:-

Telemetry data not getting populated to IoT hub.

Device is able to receive the only confirmation for IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY from IoT Hub reffer the log below.

    CLD_SendConfirmationCallback: Confirmation [0] received for message tracking id = 5 with result = IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY

Need help/support to address this issue!

Kindly Suggest if any issues with this approach of sending message to IoT Hub, or are we missing anything for which it is failing?

Regards,

**Comment by ewertons** [comment]
Hi @CreativeMnd ,

that is highly unexpected.
A few questions come to mind to check first:
1. You are using the _ll_ API; Are you calling  IoTHubClient_LL_DoWork (as shown in the [sample](https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L180) we have)?
2. Did you try running our [sample](https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c) to compare if you are using the API correctly?
3. If nothing works, could you [collect verbose logs](https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L125) from the client please?

If you are getting IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY it means you are calling  IoTHubClient_LL_Destroy before the message gets actually sent. Remember, calling IoTHubClient_LL_SendAsync does not result in the message being actually sent, it results in it being added to the queue to be sent. You have to call _DoWork to cause the I/O to actually happen.

**Comment by CreativeMnd** [comment]
Hi @ewertons,

Please find response below 

Pt. 1: Yes, our code base is having IoTHubClient_LL_DoWork().

Pt. 2: Yes, we are calling the API's as defined in the sample you shared above.

Pt. 3: How to get the verbose logs?

**Comment by ewertons** [comment]
For the logs, please refer to item 3 in the previous reply. Thanks.

**Comment by CreativeMnd** [comment]
Hi @ewertons,

Enabled the collect verbose log option and collected the below log, and observed an interesting behaviour explained below

### Behaviour: 

1. When running the application from the terminal of Ubuntu 18.04 system, in superuser mode found that the D2C data/events/messages are flowing to Azure IoT HUB, with out any issue.

2. But observed that the same application unable to send the D2C data/event/message to Azure IoT HUB, when we are running the same application as a Service on Ubuntu18.04 system.


### Question:

Is this behaviour caused because of application/SDK-library unable to get SUDO environment when running as a service on Ubuntu 18.04? 


### Logs:

Note: **Device UniqueID is replaced with 'X' in the log due to security concerns**


**Log when device not connected to Internet** :- 

_Error: Time:Thu Dec 30 11:19:01 2021 File:/home/gateway/User_Library/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:632 Failure: getaddrinfo failure -3.
Error: Time:Thu Dec 30 11:19:01 2021 File:/home/gateway/User_Library/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:725 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Dec 30 11:19:01 2021 File:/home/gateway/User_Library/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1209 Failed opening the underlying I/O.
Error: Time:Thu Dec 30 11:19:01 2021 File:/home/gateway/User_Library/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:980 Error: io_open failed
Error: Time:Thu Dec 30 11:19:01 2021 File:/home/gateway/User_Library/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1795 failure connecting to address FCTExampleIoTHub.azure-devices.net._


**Log when device connected to Internet and able to send data to cloud** :-

_-> 12:02:50 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: FCTExampleIoTHub.azure-devices.net/XXXxxxxxxXXXXXXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxXXXXXXXXXXXX/api-version=2016-11-14&DeviceClientType=iothubclient%2f1.2.2%20(native%3b%20Linux%3b%20armv7l) | PWD: XXXX | CLEAN: 0
<- 12:02:51 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
-> 12:02:52 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/XXXxxxxxxXXXXXXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxXXXXXXXXXXXX/messages/devicebound/# | QOS: 1
<- 12:02:53 SUBACK | PACKET_ID: 2 | RETURN_CODE: 1
-> 12:02:55 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/XXXxxxxxxXXXXXXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxXXXXXXXXXXXX/messages/events/PropName=PropMsg_5 | PACKET_ID: 3 | PAYLOAD_LEN: 599
<- 12:02:56 PUBACK | PACKET_ID: 3
-> 12:06:55 PINGREQ
<- 12:06:56 PINGRESP
No size specified (using byte-data access)
-> 12:07:11 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/XXXxxxxxxXXXXXXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxXXXXXXXXXXXX/messages/events/PropName=PropMsg_200 | PACKET_ID: 4 | PAYLOAD_LEN: 318
<- 12:07:12 PUBACK | PACKET_ID: 4
-> 12:11:11 PINGREQ
<- 12:11:12 PINGRESP
No size specified (using byte-data access)
-> 12:12:11 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/XXXxxxxxxXXXXXXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxXXXXXXXXXXXX/messages/events/PropName=PropMsg_201 | PACKET_ID: 5 | PAYLOAD_LEN: 311
<- 12:12:12 PUBACK | PACKET_ID: 5
-> 12:16:11 PINGREQ
<- 12:16:12 PINGRESP
No size specified (using byte-data access)
-> 12:17:11 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/XXXxxxxxxXXXXXXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxXXXXXXXXXXXX/messages/events/PropName=PropMsg_202 | PACKET_ID: 6 | PAYLOAD_LEN: 311
<- 12:17:12 PUBACK | PACKET_ID: 6
-> 12:17:50 DISCONNECT
-> 12:17:53 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: FCTTestIoTHub.azure-devices.net/XXXxxxxxxXXXXXXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxXXXXXXXXXXXX/api-version=2016-11-14&DeviceClientType=iothubclient%2f1.2.2%20(native%3b%20Linux%3b%20armv7l) | PWD: XXXX | CLEAN: 0
<- 12:17:54 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
-> 12:17:55 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/XXXxxxxxxXXXXXXxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxXXXXXXXXXXXX/messages/devicebound/# | QOS: 1
<- 12:17:56 SUBACK | PACKET_ID: 2 | RETURN_CODE: 1_

**Comment by danewalton** [comment]
It looks like you're getting the PUBACK for the telemetry message. Are you not seeing the message come in on the IoT Device Explorer?

**Comment by CreativeMnd** [comment]
We see the problem in sending data to IoT hub, when we are running the application as a systemd service and followed by forking scripts to run application, and we are able to receive ACK such as below 

   1. IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY

So I have a question in mind  

Q:  When we are running the same application from terminal it is working perfectly and able to send telemetry data to Azure IoT hub but why its not working in the same way? only we are receiving IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY, ACK response but not IOTHUB_CLIENT_CONFIRMATION_OK ?

**Comment by ericwol-msft** [comment]
There is no SDK requirements for SUDO access. A callstack for IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY might imply why it's being destroyed.

**Comment by CreativeMnd** [comment]
Hi,

Understand the point, now I have one doubt i.e. if the application is able to send and receive the data and confirmation respectively from Cloud, when we are running the application as a separate entity on the IoT gateway(running Ubuntu 18.04 OS) terminal, then the SDK is working properly. 

But when we are running the same application on the IoT gateway(running Ubuntu 18.04 OS) as a service to run the application @ gateway boot that time the SDK is only receiving the "IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY" response but why it's failing to push the data to cloud and get "IOTHUB_CLIENT_CONFIRMATION_OK"?

Do we need to apply more delay? as we have tried with "ThreadAPI_Sleep(1)" & "ThreadAPI_Sleep(1000)" but for both the cases it is not working. 

Any support would be appreciated!


-subhendu

**Comment by CreativeMnd** [comment]
Hi,

Found an work around(Explained Below) to resolve this issue

> Had to add my service Unit to the sudoers to overcome this issue, after which the application is able to Send & Receive Telemetry Data & Commands respectively to&fro Azure IoT Hub without any issue.. 


We can close this..!
