### ISSUE TITLE
Build Error when we include the library in Podspec as cocoapods dependency (  Could not build Objective-C module 'AzureIoTHubClient' )

### ISSUE THREAD

**Issue by CTorrado-Endava** [Azure/azure-iot-sdk-c#2188]
Hi guys.  I am opening this issue to report one bug compiling the last version of the sdk in xCode.

I research about the issue i am attaching  some details to you can do some changes and fix it.  

# **Environment Summary :** 

MacOSx BigSur 11.6 
xCode: 13.1 ( 13A1030d ) 
Deploy target: iOS 14.1

# **Issue details :** 

Issue in link header files including into the Azure-iot-sdk when compile the 1.8.0 version. When i use the library as dependency of my own swift package using cocoapods. 

# **Steps to reproduce it :** 

1) Create a black swift package project with cocoapod support ( Please include an Example project that include the swift package as dependency inside the Podfile.

2) Add the Azure Iot dependencies inside the Podspec as this : 

    s.dependency 'AzureIoTUtility', '1.8.0'
    s.dependency 'AzureIoTuMqtt', '1.8.0'
    s.dependency 'AzureIoTuAmqp', '1.8.0'
    s.dependency 'AzureIoTHubClient', '1.8.0' 

3 ) Add  the xcconfig  definition to add the package 

USER_HEADER_SEARCH_PATHS 
HEADER_SEARCH_PATHS in order to poinnt to the inc folder inside the swift package. : 

 s.xcconfig                = { 'OTHER_LDFLAGS' => '-lz',
        "GCC_PREPROCESSOR_DEFINITIONS": "$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=0",
        "CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES": "NO",
        "USE_HEADERMAP": "YES",
        "USER_HEADER_SEARCH_PATHS": "\"${PODS_ROOT}/AzureIoTHubClient/inc/\" \"${PODS_ROOT}/AzureIoTUtility/inc/\" \"${PODS_ROOT}/AzureIoTuMqtt/inc/\" \"${PODS_ROOT}/AzureIoTuAmqp/inc/\"",
        "HEADER_SEARCH_PATHS": "\"${PODS_ROOT}/AzureIoTHubClient/inc/\" \"${PODS_ROOT}/AzureIoTUtility/inc/\" \"${PODS_ROOT}/AzureIoTuMqtt/inc/\" \"${PODS_ROOT}/AzureIoTuAmqp/inc/\"",
        "ALWAYS_SEARCH_USER_PATHS": "NO"
    }

4) Try to build the Example app including the swift pacakge. 

# **Issue Detail :** 
import AzureIoTHubClient // Could not build Objective-C module 'AzureIoTHubClient'

framework module AzureIoTHubClient [system][extern_c] {
    header "agenttypesystem.h" <- Header 'agenttypesystem.h' not found
    header "codefirst.h"
    header "commanddecoder.h"
    header "datamarshaller.h"
    header "datapublisher.h"
    header "dataserializer.h"
    header "iotdevice.h"
    header "iothub.h"
    header "iothub_client.h"
    header "iothub_client_core.h"
    header "iothub_client_core_common.h"
    header "iothub_client_core_ll.h"
    header "iothub_client_ll.h"
    header "iothub_client_options.h"
    header "iothub_client_version.h"
    header "iothub_device_client.h"
    header "iothub_device_client_ll.h"
    header "iothub_message.h"
    header "iothub_module_client.h"
    header "iothub_module_client_ll.h"
    header "iothub_transport_ll.h"
    header "iothubtransportamqp.h"
    header "iothubtransportamqp_websockets.h"
    header "iothubtransporthttp.h"
    header "iothubtransportmqtt.h"
    header "iothubtransportmqtt_websockets.h"
    header "jsondecoder.h"
    header "jsonencoder.h"
    header "methodreturn.h"
    header "multitree.h"
    header "parson.h"
    header "schema.h"
    header "schemalib.h"
    header "schemaserializer.h"
    header "serializer.h"
    header "serializer_devicetwin.h"
    export *
}

#  **Temproal Workarround:** 

Using  the 1.5.0 version for al dependencies is building without errors. 

Some extra comments: we not e able to add the decencies directly in the main project because we are implementing and sdk for the company products that include your library. And the issues is this scenario as mention in the replication steps section. 

I found the different between the 1.6.0 and 1.8.0 that is generating  the linking issue:  I reviewed the Podspecs for both versión i i found that when you generate the module.modulemap file exist a little difference, in version 1.8.0 you are generating the module file as "framework module" in 1.6.0. version you are generating the file only as "module" : 

Version 1.8.0 : 

```json
framework module AzureIoTHubClient [system][extern_c] {
    header "agenttypesystem.h"
    header "codefirst.h"
    //..............

```

Version 1.5.0 : 

```json
 module AzureIoTHubClient [system][extern_c] {
    header "agenttypesystem.h"
    header "codefirst.h"
    //..............
```

 I reviewed the Podspec from your code and i foun that the prepare script have include the change : 
 
 ## Podspec of version 1.8.0: 
 
 https://github.com/CocoaPods/Specs/blob/master/Specs/3/8/4/AzureIoTHubClient/1.8.0/AzureIoTHubClient.podspec.json
 
##  Podspec of 1.5.0 version: 
 
 https://github.com/CocoaPods/Specs/blob/master/Specs/3/8/4/AzureIoTHubClient/1.5.0/AzureIoTHubClient.podspec.json
 
As you can see  inside the   prepare_command  show can se the difference in the module definition is introducing this generation 

## prepare_command of 1.8.0 version: 

```json 
  "prepare_command": "# Keeping this script idempotent makes using it in a\n# development situation much easier.\ngit submodule update --init deps/parson\nrm -R inc > /dev/null 2>&1 || true\nmkdir -p inc\nmkdir -p inc/internal\ncp deps/parson/parson.h inc\ncp iothub_client/inc/internal/*.h inc/internal\ncp iothub_client/inc/*.h inc\ncp serializer/inc/*.h inc\n\n# Assemble the module.modulemap file\npushd inc > /dev/null\necho \"framework module AzureIoTHubClient [system][extern_c] {\" > module.modulemap\nquote_thing='\"'\nfor filename in *.h; do\n    echo \"    header $quote_thing$filename$quote_thing\" >> module.modulemap\ndone\necho \"    export *\" >> module.modulemap\necho \"}\" >> module.modulemap\npopd > /dev/null\n# Done assembling module.modulemap file",
```

## prepare_command of 1.5.0 version : 

```json
"prepare_command": "# Keeping this script idempotent makes using it in a\n# development situation much easier.\ngit submodule update --init deps/parson\nrm -R inc > /dev/null 2>&1 || true\nmkdir -p inc\nmkdir -p inc/internal\ncp deps/parson/parson.h inc\ncp iothub_client/inc/internal/*.h inc/internal\ncp iothub_client/inc/*.h inc\ncp serializer/inc/*.h inc\n\n# Assemble the module.modulemap file\npushd inc > /dev/null\necho \"module AzureIoTHubClient [system][extern_c] {\" > module.modulemap\nquote_thing='\"'\nfor filename in *.h; do\n    echo \"    header $quote_thing$filename$quote_thing\" >> module.modulemap\ndone\necho \"    export *\" >> module.modulemap\necho \"}\" >> module.modulemap\npopd > /dev/null\n# Done assembling module.modulemap file",
```

I am suspecting that prepare:command would be change depending the way that the library is including inside the xCode project. 

I saw a related to a previous issue but with the previous version i suspecting that change in the way that you are generationt the modulemap files. Here the link : https://github.com/Azure/azure-iot-sdk-c/issues/1314

I would appreciate any extra comment and any suggestion about how we can 
implement the 1.8.0 without this issue please share with us if we need to add extra changes in the Podspec file. And if you can review the prepare_command in order yo know if is necessary to change it depending the way that the library is incluiding in the project. 

Thanks in advance for you time. 

Regards.

**Comment by danewalton** [comment]
Hi @CTorrado-Endava can you please try the versions which are listed here:
https://github.com/Azure/azure-iot-sdk-c/issues/2109#issuecomment-953929920

**Comment by CTorrado-Endava** [comment]
@danewalton  Thanks for the quickly response, sure i going to test those version and post here the result. Thanks

**Comment by CTorrado-Endava** [comment]
@danewalton  Thanks with those versions is working good, only one more question, when do you  release those changes into the stable versión ? only to stay alert in update the version again.

Thanks in advance

**Comment by danewalton** [comment]
We don't currently have plans but with future updates I'm sure they will get scooped up. Glad to see its working now!
