### ISSUE TITLE
HTTP Registering device with x509 is not working

### ISSUE THREAD

**Issue by zygmunt** [Azure/azure-iot-sdk-c#2207]
**Development Machine:**

ArchLinux (27.01.2022)
gcc version 11.1.0
openssl 1.1.1.m-1

**SDK Version**

- LTS_01_2022_Ref01 5805fb669ffe2adff021d68c62725d0bd783ac49
- tested also on main branch with commit: a785c6efb3b40b947a7b455993020e8b0d2bb202

**Protocol**

Registration transport: HTTP
Client transport: MQTT over websockets
Security method: X509 (both for registering and client communication)

**Description**

It is not possible to register device with security method like x509.

Steps for reproducing:
My code first sets certificate and private key like:
```
// NOTE: not full code here, this method calls success
Prov_Device_SetOption(m_prov_device_handle, OPTION_X509_CERT, m_x509certificate.c_str());
Prov_Device_SetOption(m_prov_device_handle, OPTION_X509_PRIVATE_KEY, m_x509privateKey.c_str());
```
Later I'm invoking 
```
Prov_Device_Register_Device(m_prov_device_handle, ....
```
**which fails.**

The problem exists because SDK tries set certificate twice, but it has protection inside.
If I remove this code in file azure-iot-sdk-c/deps/uhttp/src/uhttp.c, between lines: 1100:1113, then all is working
```
                if ((http_data->x509_cert != NULL) && (http_data->x509_pk != NULL))
                {
                    if ((xio_setoption(http_data->xio_handle, SU_OPTION_X509_CERT, http_data->x509_cert) != 0) ||
                        (xio_setoption(http_data->xio_handle, SU_OPTION_X509_PRIVATE_KEY, http_data->x509_pk) != 0))
                    {
                        LogError("Failed setting x509 certificate");
                        result = HTTP_CLIENT_ERROR;
                        free(http_data->host_name);
                        http_data->host_name = NULL;
                        http_data->on_connect = NULL;
                        http_data->connect_user_ctx = NULL;
                        http_data->port_num = 0;
                    }
                }
```

**Comment by CIPop** [comment]
@zygmunt, for [Provisioning Client with X509](https://github.com/Azure/azure-iot-sdk-c/blob/main/provisioning_client/devdoc/azure_provisioning_faq.md#x509-provisioning) you will need to either use DICE/RIoT or implement a [Custom HSM](https://github.com/Azure/azure-iot-sdk-c/blob/main/provisioning_client/devdoc/using_custom_hsm.md). 

I am working on a new feature for the DPS/X509 authentication scenario. If you'd like to give it a try, please use [my branch](https://github.com/CIPop/azure-iot-sdk-c/tree/dpsx509v2) and follow the instructions for the new [provisioning x509 sample](https://github.com/CIPop/azure-iot-sdk-c/tree/dpsx509v2/provisioning_client/samples/prov_dev_client_ll_x509_sample).
Please note that in my branch, the meaning of the hsm_type_x509 CMake option has changed. Instead enabling DICE/RIoT it now enables the use of PEM files. This is similar to what you were trying to do by setting the certificate options.

**Comment by zygmunt** [comment]
@CIPop Hi, that is great. Thank you for information.
I just switch to your branch, and all is working (without any code change in my app).

Is there a chance that your work will be merged into main branch soon?

**Comment by CIPop** [comment]
Excellent to hear! Thank you for the test and feedback and please let me know if you see any other issues. This is my highest priority right now: the code is complete, but I still need to write tests.

It will be some time (likely around 6 months) until the feature makes it to our next LTS.

**Comment by zygmunt** [comment]
@CIPop Can this issue be closed when it will be merged to main branch?

**Comment by CIPop** [comment]
Sure - reopened. I will close when the feature is merged into main.
