### ISSUE TITLE
How to set USE_CUSTOM_HSM when using vcpkg?

### ISSUE THREAD

**Issue by rschiefer** [Azure/azure-iot-sdk-c#2211]
I have the samples working with the custom hsm file but now working on my own c project and pulling the sdk in via vcpkg.  I plan to have my custom hsm file in my c project.  How do I set USE_CUSTOM_HSM?

**Comment by danewalton** [comment]
Hi @rschiefer 

From my understanding of vcpkg, [CMake compile options are set at the portfile level.](https://github.com/microsoft/vcpkg/blob/6ba505cf2c1752d8ea5abb21427e23ff89dc486f/ports/azure-iot-sdk-c/portfile.cmake#L38-L48) With that, the option to use a custom hsm might not be possible.

Are you able to use the SDK separate from VCPKG?

**Comment by rschiefer** [comment]
Yes, I assumed the VCPKG was the best way to add the sdk to my custom project.  

I'm new to C so what would be the best way to include the SDK libraries in my project?

**Comment by ericwol-msft** [comment]
Use git submodule on the SDK git repository (example dir AzureIoTSdk). Then include the SDK folder in your root project cmake file as a include(AzureIoTSdk).

**Comment by ericwol-msft** [comment]
here is a random cmake project that include the C SDK submodule https://github.com/yaweiw/dukIoT/blob/master/CMakeLists.txt

as you can see they added the iot hub client `add_subdirectory(azure-iot-sdk-c/iothub_client)`

If you add the root cmake, you will need to use CMAKE flags to specify which components to include in your application

**Comment by ericwol-msft** [comment]
If you are using USE_CUSTOM_HSM to set the certificate for DPS, we have a new feature APIs that will allow you to set the cert without the HSM implementation.

**Comment by rschiefer** [comment]
@ericwol-msft Thanks for providing the example repo (dukIoT).  I've tried mimic their setup but the build still fails.  Can provide other (possible more recent) repos that do the same.  I've searched around but haven't found any good examples.

**Comment by ericwol-msft** [comment]
Is this what is in your devops repo?

**Comment by rschiefer** [comment]
@ericwol-msft I ended up finding a better example of including the iot sdk source in your own repo:

https://github.com/Azure-Sphere-DevX/DesktopDevX/blob/main/CMakeLists.txt

I got it working with this example.  And that is now committed to my repo.

**Comment by ericwol-msft** [comment]
That cmake file is still overly complicated. Please see my cmake sample project at https://github.com/ericwol-msft/IoT-CMake-Sample

We will make additional changes for the next LTS to simplify this further.

**Comment by ericwol-msft** [comment]
Can I close this issue?

**Comment by rschiefer** [comment]
Yes sir.  Thanks!
