### ISSUE TITLE
Unable to establish connection with Azure IoT Hub with x509 EC certificate from iOS Mobile Platform.

### ISSUE THREAD

**Issue by amitpalo-allegion** [Azure/azure-iot-sdk-c#2214]
Unable to establish connection with Azure IoT Hub with x509 EC certificate from iOS Mobile Platform.

MAC OS:- Big Sur
Version:- 11.3.1

Getting unsupported x509 certificate error when trying to connect with Azure Hub Client.

**Comment by amitpalo-allegion** [comment]
@danewalton  This is the duplicate of this error https://github.com/Azure/azure-iot-sdk-c/issues/2215.

**Comment by danewalton** [comment]
gotcha thanks for letting me know. I'll close this one and use the other to track.
