### ISSUE TITLE
Memory leak in IoTHubDeviceClient_GetTwinAsync

### ISSUE THREAD

**Issue by zygmunt** [Azure/azure-iot-sdk-c#2227]
**Development Machine:**

ArchLinux (11.02.2022)
gcc version 11.1.0
openssl 1.1.1.m

**SDK Version**

- LTS_01_2022_Ref01 5805fb669ffe2adff021d68c62725d0bd783ac49

**Protocol**

Client transport: MQTT over websockets
Security method: Symmetric Key

**Description**

Valgrind result:

24 bytes in 1 blocks are definitely lost in loss record 2 of 18
  w IoTHubClientCore_GetTwinAsync in /home/dev/azure-iot-sdk-c/iothub_client/src/iothub_client_core.c:1842
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: IoTHubClientCore_GetTwinAsync in /home/dev/azure-iot-sdk-c/iothub_client/src/iothub_client_core.c:1842
  3: IoTHubDeviceClient_GetTwinAsync in /home/dev/azure-iot-sdk-c/iothub_client/src/iothub_device_client.c:83
  
Scenerio:

It doesn't matter what is the result state of the call. Looks like there is always memory leak.

**Comment by ericwol-msft** [comment]
please attach the full Valgrind output.

**Comment by ewertons** [comment]
Hi @zygmunt , yes please make sure you include the complete azure iot sdk c verbose logs (instructions below) and the valgrind stack. Please use these valgrind options: `valgrind --leak-check=full --track-origins=yes --num-callers=100 ./your_application`

Please enable SDK verbose logs using this as reference: https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample.c#L323

**Comment by ewertons** [comment]
Hi @zygmunt ,
we will close this issue for now, but please feel free to reopen it or file a new one if you would like to follow up.
Thanks,
Azure IoT SDK team
