### ISSUE TITLE
Azure IoT SDK C - Issue during reconnection attempt when utilizing openSSL and amqp over websockets

### ISSUE THREAD

**Issue by FabianKe** [Azure/azure-iot-sdk-c#223]
Hello,
I have encountered an issue during the reconnection attempt when using openSSL and amqpWS as Protocol. (Windows)

- **OS and version used:** Windows 7
- **SDK version used:** 1.1.21 
-  Dev environment set up according to : https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#windows 
- Visual Studio 2015
- openSSL 1.0.2j or 1.0.2l (should also be reproducible with 1.0.2.k)
- target platform x86

# Description of the issue:
Within c-utility\src\tlsio_openssl.c, the tlsio_openssl_setoption function expects the value as pointer to int during evaluation of the tls_version option. This works fine when invoking IoTHubClient_SetOption. 
However, on a reconnection attempt the tlsio_openssl_setoption function will be invoked like this:

 	exampled.exe!tlsio_openssl_setoption(void * tls_io, const char * optionName, const void * value) Line 1548	C
 	exampled.exe!OptionHandler_FeedOptions(OPTIONHANDLER_HANDLE_DATA_TAG * handle, void * destinationHandle) Line 236	C
 	exampled.exe!xio_setoption(XIO_INSTANCE_TAG * xio, const char * optionName, const void * value) Line 184	C
 	exampled.exe!OptionHandler_FeedOptions(OPTIONHANDLER_HANDLE_DATA_TAG * handle, void * destinationHandle) Line 236	C
 	exampled.exe!uws_client_set_option(UWS_CLIENT_INSTANCE_TAG * uws_client, const char * option_name, const void * value) Line 1841	C
 	exampled.exe!OptionHandler_FeedOptions(OPTIONHANDLER_HANDLE_DATA_TAG * handle, void * destinationHandle) Line 236	C
 	exampled.exe!wsio_setoption(void * ws_io, const char * optionName, const void * value) Line 670	C
 	exampled.exe!OptionHandler_FeedOptions(OPTIONHANDLER_HANDLE_DATA_TAG * handle, void * destinationHandle) Line 236	C
 	exampled.exe!xio_setoption(XIO_INSTANCE_TAG * xio, const char * optionName, const void * value) Line 184	C
 	exampled.exe!OptionHandler_FeedOptions(OPTIONHANDLER_HANDLE_DATA_TAG * handle, void * destinationHandle) Line 236	C
	exampled.exe!restore_underlying_io_transport_options(AMQP_TRANSPORT_INSTANCE_TAG * transport_instance, XIO_INSTANCE_TAG * xio_handle) Line 613	C
 	exampled.exe!get_new_underlying_io_transport(AMQP_TRANSPORT_INSTANCE_TAG * transport_instance, XIO_INSTANCE_TAG * * xio_handle) Line 659	C
 	exampled.exe!establish_amqp_connection(AMQP_TRANSPORT_INSTANCE_TAG * transport_instance) Line 716	C

When invoked like this, the transport_instance->saved_tls_options OPTIONHANDLER_HANDLE gets evaluated which instead of containing a pointer to the value, contains the value itself.
The issue occurs in c-utility\src\tlsio_openssl.c on lines 1548ff, when the passed void pointer gets cast and accessed.

# Code sample exhibiting the issue:
` const int* version_option = value;`
                
`if ((int)(intptr_t)*version_option == 0 || (int)(intptr_t)*version_option == 10)`
`                {`
`                    tls_io_instance->tls_version = VERSION_1_0;`
`                }`

# Console log of the issue:
Exception thrown: read access violation.
version_option was 0x2.

**Comment by tameraw** [comment]
@FabianKe - Thanks for filing this issue. We're investigating it.

**Comment by ewertons** [comment]
Hi @FabianKe ,
a fix was checked in and is now available on the latest code in master branch.
If possible, please validate it on your side and let us know the results.

Thanks for contributing to the Azure IoT SDK!

**Comment by ewertons** [comment]
https://github.com/Azure/azure-c-shared-utility/commit/68470a382a3be1e64ace3082f1a6eb6dedfc4f6c

https://github.com/Azure/azure-c-shared-utility/commit/71ff9b4e900e6f5ecf2195d1f238441463b69449

**Comment by ewertons** [comment]
Hi @FabianKe ,
this issue will be closed, but please feel free to reopen it if you need to follow up on the issue.
Thanks,
Azure IoT SDK Team
