### ISSUE TITLE
Registration ID with x509 in device provisioning client

### ISSUE THREAD

**Issue by rschiefer** [Azure/azure-iot-sdk-c#2234]
What is the practical use for optionally setting Registration ID in the device provisioning client while using x509 attestation?

Just trying to make sure this use case and if there is any scenario where its useful.

**Comment by danewalton** [comment]
Hi @rschiefer good question.

I'll point to some of our docs which help explain it best. Let us know if you would like further clarification.

https://docs.microsoft.com/en-us/azure/iot-dps/concepts-service#registration-id

**Comment by rschiefer** [comment]
That helps thanks
