### ISSUE TITLE
Old version of the c sdk in raspbian cmake build error

### ISSUE THREAD

**Issue by Dandelion0124** [Azure/azure-iot-sdk-c#224]
- **OS and version used:** <raspbian 8-16> 

- **SDK version used:** <2017-03-10>

# Description of the issue:
I want to build the c sdk on raspbian 8-16, I have found that the new version such as 8-25 c sdk can be build successfully but the old version such as 3-10 c sdk can not be build successfully.
tlsio_ssl.c will meet error like follows. I found that the tlsio_ssl will be changed in the new version files but if I want to use the old version c sdk, how can I solve the issue?

[ 16%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/tlsio_openssl.c.o
/home/pi/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c: In function ‘add_certificate_to_store’:
/home/pi/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c:791:38: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
             BIO_METHOD* bio_method = BIO_s_mem();
                                      ^~~~~~~~~
/home/pi/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c: In function ‘create_openssl_instance’:
/home/pi/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c:857:5: error: ‘TLSv1_method’ is deprecated [-Werror=deprecated-declarations]
     const SSL_METHOD* method = TLSv1_method();
     ^~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /home/pi/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c:5:
/usr/include/openssl/ssl.h:1612:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
 ^
/home/pi/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c:861:9: error: ‘TLSv1_2_method’ is deprecated [-Werror=deprecated-declarations]
         method = TLSv1_2_method();
         ^~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /home/pi/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c:5:
/usr/include/openssl/ssl.h:1624:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_method(void)) /* TLSv1.2 */
 ^
/home/pi/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c:865:9: error: ‘TLSv1_1_method’ is deprecated [-Werror=deprecated-declarations]
         method = TLSv1_1_method();
         ^~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /home/pi/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c:5:
/usr/include/openssl/ssl.h:1618:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_method(void)) /* TLSv1.1 */
 ^
/home/pi/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c: In function ‘tlsio_openssl_deinit’:
/home/pi/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c:1003:5: error: ‘ERR_remove_state’ is deprecated [-Werror=deprecated-declarations]
     ERR_remove_state(0);
     ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /home/pi/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c:5:
/usr/include/openssl/err.h:248:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
cc1: all warnings being treated as errors
c-utility/CMakeFiles/aziotsharedutil.dir/build.make:1046: recipe for target 'c-utility/CMakeFiles/aziotsharedutil.dir/src/tlsio_openssl.c.o' failed
make[2]: *** [c-utility/CMakeFiles/aziotsharedutil.dir/src/tlsio_openssl.c.o] Error 1
CMakeFiles/Makefile2:983: recipe for target 'c-utility/CMakeFiles/aziotsharedutil.dir/all' failed
make[1]: *** [c-utility/CMakeFiles/aziotsharedutil.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by markrad** [comment]
Hi @Dandelion0124,

What is the purpose of building an old version of the C SDK? Is there some reason that you can't simply use the latest version? 

The warnings you are seeing appear to be generated by the OpenSSL includes. These are outside of our control. If you really need to build an old version of the SDK then you will likely need to pick up an older version of OpenSSL too in order to avoid the deprecated warnings. Alternatively you could override the setting that treats warnings as errors to circumvent the build failure.

_Mark Radbourne MSFT_
