### ISSUE TITLE
Telemetry call fails with "Not Authorized" if I don't first call Prov_Device_LL_Register_Device

### ISSUE THREAD

**Issue by rschiefer** [Azure/azure-iot-sdk-c#2243]
I have a custom HSM setup and it works great if I provision the device with the provisioning device client and then send telemetry via the iot hub client.

Now I want to cache the iot hub connectionstring and device id that is returned from the provisioning client to avoid provisioning the device on every connection.  If I skip the provision call the telemetry call fails:

`Init HSM clientInit HSM client TPMDisconnection from service encounteredError: Time:Sun Feb 20 02:23:34 2022 File:../azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqttOperationCompleteCallback Line:2072 Connection Not Accepted: 0x5: Not Authorized`

I suspect there is a custom hsm setup call somewhere the provisioning client is setting and is then used by the iot hub client but not finding any helpful documentation.

**Comment by rschiefer** [comment]
I'm an idiot!

**Comment by danewalton** [comment]
Glad we could help with your rubber ducky debugging haha
