### ISSUE TITLE
Module Client does not see to work on Ubuntu 20.04, but does on Yocto Linux OS

### ISSUE THREAD

**Issue by maskimthedog** [Azure/azure-iot-sdk-c#2247]
I had been utilizing the SDK installed via apt for a C module I had written for an IoT Edge Application for Ubuntu 20.04.  That version of the SDK is pretty old, so I built version 1.9 for my container from scratch.  However, now, on an Ubuntu 20.04 host, that module will not start up in the IoT Edge application.  However, if I deploy the same IoT Edge application to a gateway running a custom Yocto Linux host, the aforementioned module comes up and runs with no issue.  Is there something that must be enabled in the Ubuntu 20.04 host kernel that is not for the 1.9 version of the SDK?  I will attempt to get some more details from the module.

**Comment by danewalton** [comment]
Hi @maskimthedog 

We have gate tests for modules in Ubuntu 20.04 so I believe it should work. Do you have any further details on your situation? Logs, build conditions, transports used etc.

**Comment by maskimthedog** [comment]
This can be closed.  A bad Docker file was the issue.
