### ISSUE TITLE
Limitations regarding the AMQP Connection multiplexing support in the SDK

### ISSUE THREAD

**Issue by swanav** [Azure/azure-iot-sdk-c#2252]
We have an application use case where a single ESP32 device needs to host multiple logical IoT Hub devices. We are currently using multiple MQTT Clients on the device to achieve that, but we soon run out of memory as the number of these logical devices increases.

A bit of research on the internet shows me that our use case is better served by *AMQP Connection Multiplexing*.  I even found the example at [iothub_ll_client_shared_sample](https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/samples/iothub_ll_client_shared_sample/iothub_ll_client_shared_sample.c), which seems to solve the problem that I have, but I understand that there are a lot of limitations to the support offered by the SDK as mentioned [here](https://github.com/Azure/azure-iot-sdk-c/blob/main/doc/multiplexing_limitations.md).

Can anyone from the team let me know if this is a limitation of the protocol or IoT Hub or if the implementation in the SDK is incomplete and I can get this working if I put a few things together?

**Comment by danewalton** [comment]
Hi @swanav 
Have you looked into [module identities and module twins](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-module-twins)?

**Comment by danewalton** [comment]
I will say about the limitations, most of those are SDK limitations.

**Comment by swanav** [comment]
Hi @danewalton, I have looked into modules and the concept is almost everything I’m trying to achieve, but my understanding is that all these modules establish different connections to the IoT Hub even though they reside in the same device.

Is there a way we can make all these modules communicate over a single TLS connection?

**Comment by danewalton** [comment]
Unfortunately not with MQTT. That would have to be left to AMQP. Know that the protocol is going to have a hit on binary size as is it much larger. It's a tradeoff with the extra RAM needed for multiple TLS connection using MQTT.

**Comment by swanav** [comment]
That's not a tradeoff that we can make at this point. Are there no alternates available or a plan to support this in the future?

We basically need to have different twins for each logical device. A functionality that is available as device modules. 
I feel it is a perfectly valid use case that multiple logical devices within a single physical device be able to share a connection.

**Comment by danewalton** [comment]
Large investments in AMQP are not being made at this time. There just aren't enough instances with people using this scenario on embedded devices to justify the time investment. This could change in the future but at this time, the current limitations will stand. 

Unfortunately, for now, it's either the hit of the extra TLS session or the hit and limitations of the AMQP protocol.

**Comment by swanav** [comment]
Thanks @danewalton, looks like we've got to make do with what we've got, or add some additional memory to our hardware.
You may close the issue if you'd like.

**Comment by danewalton** [comment]
Yea sorry about that would love to have a golden scenario for everything but there's only so many hours in a day.
