### ISSUE TITLE
Dockcross example for cross-compiling

### ISSUE THREAD

**Issue by rschiefer** [Azure/azure-iot-sdk-c#2258]
I found Dockcross as an interesting way to enable faster cross compiling for multiple target hardware architectures.  Followed their instructions for extending their containers with additional dependencies.  Added 

`RUN apt-get install -y openssl libssl-dev`

but still getting an error from the build on azure sdk regarding openssl includes missing:

```
[63/349] Building C object azure-iot-sdk-c/c-utility/CMakeFiles/aziotsharedutil.dir/adapters/tlsio_openssl.c.o
FAILED: azure-iot-sdk-c/c-utility/CMakeFiles/aziotsharedutil.dir/adapters/tlsio_openssl.c.o
/usr/xcc/mips-unknown-linux-gnu/bin/mips-unknown-linux-gnu-gcc --sysroot=/usr/xcc/mips-unknown-linux-gnu/mips-unknown-linux-gnu/sysroot -DDONT_USE_UPLOADTOBLOB -I/work/azure-iot-sdk-c/deps/azure-macro-utils-c/inc -I/work/azure-iot-sdk-c/deps/umock-c/inc -I/work/azure-iot-sdk-c/c-utility/inc -I/work/azure-iot-sdk-c/c-utility/pal/linux -D_POSIX_C_SOURCE=200112L -fPIC  -Werror -DUSE_PROV_MODULE_FULL -Werror -Werror -Wall -Wextra -Wformat=2 -Wformat-security -DUSE_OPENSSL -Wno-unused-variable -Wno-missing-braces -Wno-missing-field-initializers -Wno-format-nonliteral -fPIC -std=gnu99 -MD -MT azure-iot-sdk-c/c-utility/CMakeFiles/aziotsharedutil.dir/adapters/tlsio_openssl.c.o -MF azure-iot-sdk-c/c-utility/CMakeFiles/aziotsharedutil.dir/adapters/tlsio_openssl.c.o.d -o azure-iot-sdk-c/c-utility/CMakeFiles/aziotsharedutil.dir/adapters/tlsio_openssl.c.o -c /work/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c
/work/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c:5:10: fatal error: openssl/ssl.h: No such file or directory
    5 | #include "openssl/ssl.h"
```

This appears very similar to an old issue - https://github.com/Azure/azure-iot-sdk-c/issues/484

Can someone help a C-noob (me) figure this out?  I think this would be a big help for other folks trying to use the SDK as well.

**Comment by ericwol-msft** [comment]
you need `openssl-dev`

`RUN apt-get install -y openssl-dev libssl-dev`

https://github.com/Azure/azure-iot-sdk-c/blob/32942abb994f6855edc2a4dee8afd80735df4151/doc/devbox_setup.md#set-up-a-linux-development-environment

**Comment by rschiefer** [comment]
openssl-dev wasn't available in Debian; libssl-dev is supposed to be the alternative.  i did confirm I have the openssl includes:

![image](https://user-images.githubusercontent.com/1071761/158022236-9ac46b7f-6a69-46b7-aa1d-3b45a198bcc6.png)

**Comment by momuno** [comment]
Please try with `libcurl4-openssl-dev`.

**Comment by rschiefer** [comment]
Added but same error.

**Comment by momuno** [comment]
When you receive the error, what are the build flags you are using?  Is this build with or without the samples, or is this a general sdk build, or is this a build of your application that is in turn building the sdk?

**Comment by rschiefer** [comment]
This is my application that is in turn building the sdk.  Compilation and executable works locally with CMake on x86, no problems.  

Trying to compile for linux/mips using dockcross.

Here are the flags we are using in CMakeLists:

```
set(use_amqp OFF CACHE  BOOL "Set amqp off" FORCE )
set(use_http OFF CACHE  BOOL "Set http off" FORCE )
set(use_mqtt ON CACHE  BOOL "Set http off" FORCE )
# no need to build SDK samples
set(skip_samples ON CACHE  BOOL "Skip samples" FORCE )
set(use_prov_client ON CACHE  BOOL "Use prov client" FORCE )
set(hsm_type_x509 ON CACHE BOOL "x509 HSM type on" FORCE )
# set(hsm_type_sastoken OFF CACHE BOOL "SAS HSM type off" FORCE )
# set(hsm_type_symm_key OFF CACHE BOOL "Symetric key HSM type off" FORCE )
set(hsm_custom_lib "mm-custom-hsm" CACHE STRING "Path to custom HSM" FORCE )
# better using the default one
set(use_default_uuid ON CACHE BOOL "use platform UUID" FORCE)
```

**Comment by ericwol-msft** [comment]
This is how we build our debian docker container

https://github.com/Azure/azure-iot-sdk-c/blob/32942abb994f6855edc2a4dee8afd80735df4151/samples/dockerbuilds/RaspberryPi/Dockerfile

**Comment by rschiefer** [comment]
Also tried with another dockcross container (armv7a) and received the same error.  I reviewed the Dockerfiles used to build the sdk and didn't see anything that was missing in my setup.

**Comment by rschiefer** [comment]
Still at a loss here. I've verified "openssl/ssl.h" exists in "/usr/include" and OPENSSL_INCLUDE_DIR is set to "/usr/include" in my docker container.  Still get the same error as above. 

I did notice the "/usr/include" dir isn't listed in the compile command as an "I" argument.  Why would that be?

**Comment by danewalton** [comment]
You can probably use this to check (based on the compiler) what the defaults are.

https://stackoverflow.com/questions/4980819/what-are-the-gcc-default-include-directories

I would just try subbing in `/usr/xcc/mips-unknown-linux-gnu/bin/mips-unknown-linux-gnu-gcc`  for  `gcc` which you seem to be using.

**Comment by momuno** [comment]
@rschiefer have you been able to make progress on your work?  Did @danewalton's suggestions help or did you need any further assistance?  Thanks.
