### ISSUE TITLE
Azure IOT SDKs and Libraries for C Packaged on Conan.io

### ISSUE THREAD

**Issue by solvingj** [Azure/azure-iot-sdk-c#226]
*INFO*
Greetings all.  I am pleased to announce a that the Azure IOT SDK and all of it's components are now available on Conan.io, the modern C/C++ Package Manager. 

*DISCLAIMER*
This is not an official Microsoft post.  My team and I are not affiliated with Microsoft or Conan.io. This was an effort by myself and some other community members who are users/fans of this SDK and/or Conan.io. 

*SUMMARY*
If you are unfamiliar with Conan.io, you use it just like package managers from other languages (Maven, NPM, PyPI, Nuget, Etc).  It has to handle a few significant nuances relating to C/C++, but it does so brilliantly.  You can read more about it here: https://www.conan.io/

*GOAL*
Our team created the packages because the Azure IOT SDK and it's depdendencies are a fantastic suite of tools we wanted to use, but we prefer to consume depdendencies in our projects via Conan rather than git-submodules or other methods.  Additionally, we thought it was a good opportunity to demonstrate the solution to the Microsoft team here, as it provides an elegant way to manage these modular dependencies, for both developers and users of the libraries. 

*DETAILS*
We packaged the major pieces as separate modules, which are listed here:

* Parson/0.1.0@bincrafters/stable
* Azure-C-Shared-Utility/1.0.41@bincrafters/stable
* Azure-uAMQP-C/1.0.41@bincrafters/stable
* Azure-uMQTT-C/1.0.41@bincrafters/stable
* Azure-IoT-SDK-C/1.1.21@bincrafters/stable

The conan packages depend upon each other the way you would expect in a package manager.

These packages can be found along with many other community packages published on Bintray by the Bincrafters team here: 
https://bintray.com/bincrafters/public-conan 

*DEMO*
For those new to Conan, we also put together a demo to show what the user experience is like when consuming the packages.  You can get all the information on how to use these packages by reviewing the demo here: 

https://github.com/bincrafters/azure-iot-sdk-demo-conan

*STATUS*
The packages are not perfect, but are considered stable enough to consume. Fixes will be pushed to a testing branch and tested.  As new versions are released, we will release updated versions of the packages.

*FEEDBACK*
If you'd like to contribute or otherwise comment on these packages, please come post an issue at the Github repository above, or email us: bincrafters at gmail dot com. 

If you'd like to chat about Conan and other C++ related topics, you can signup to join the CPPLang team, there is a #conan channel there. 
https://cpplang.now.sh/

We look forward to your feedback, and hope people enjoy using our packages.

**Comment by tameraw** [comment]
@solvingj - This is great! Thank you so much for your effort and contribution. We'll get in touch with you on the best way to feature this.

**Comment by solvingj** [comment]
@tameraw one of our team just spent quite a bit of time over the last two weeks getting it updated , and we're going to try to keep pace with the changes here.  are you still interested in featuring it somehow?  Also, do you have any input on the Edge SDK?  I'd like to see (and foster) Conan becoming a "featured" or at least mentioned option for easy entry into the Azure C/C++ ecosystem.

**Comment by jspaith** [comment]
We had a good discussion offline with Conan folks but at present the Azure IoT C SDK isn't aligned with the Conan packaging model.  Closing out this issue given the mismatch and thanks to Conan team for reaching out.

**Comment by jspaith** [comment]
Just to clarify, we were speaking with a Conan expert and not Conan team per se.  That said, because we have Nuget & apt-get already (both of which are heavily automated) and there is a bit of a mismatch between our models we still don't think this makes sense to invest in at this time.

**Comment by serhiybobyr-tomtom** [comment]
Is this still an issue?
