### ISSUE TITLE
store symmetric key in tpm

### ISSUE THREAD

**Issue by gino-1557** [Azure/azure-iot-sdk-c#2263]
Hello,
currently I am trying to store / load a key (symmetric key for dps) in the tpm. During my research I found the following working example:

tpm2_createprimary -c primary.ctx
tpm2_create -C primary.ctx -u obj.pub -r obj.priv
echo "my key" > seal.dat
tpm2_create -C primary.ctx -i seal.dat -u obj.pub -r obj.priv
tpm2_load -C primary.ctx-u obj.pub -r obj.priv -c keyDecrypted.txt
tpm2_unseal -o keyPlain.txt -c keyDecrypted.txt

Now I want to integrate this example into the tpm example of the azure-iot-sdk-c. The tpm example works and I get the EK. I saw in the code that the srk (the primary key of the example above) was already created, which is the basis for storing data in the tpm. 

Now I am struggeling with the code. I would be happy about a support. Thanks.

**Comment by danewalton** [comment]
Hi @gino-1557. Are you trying to understand how to integrate that into our code? So how to get the key out programmatically and into a sample?

**Comment by gino-1557** [comment]
Yes, I want the example of the tpm2 commands in the project. Store some data in the tpm and read them. I don't know which functions i should call.

**Comment by gino-1557** [comment]
I have seen this code and the docs, but i didn't get it, where the store or the load command for the tpm is.

**Comment by danewalton** [comment]
The loads happen in our openSSL adapter. The application code only needs to set the appropriate credentials (connection string tpm paths etc) and appropriate options listed here: https://github.com/Azure/azure-iot-sdk-c/blob/2fcc76586632e8b81f92faca9e5a6fc0aaa60ad8/iothub_client/samples/iothub_ll_client_x509_sample/iothub_ll_client_x509_sample.c#L81-L84

**Comment by gino-1557** [comment]
Ah ok. I have checked out this example and I have seen that I can build this example only on linux. Now I have a ubuntu 20.04 running in hyper-v with a tpm (enabled in the security settings). Do you know which parameters I have to set in the code ?

**Comment by momuno** [comment]
@gino-1557.  A little further down in the sample I see the following lines to set the options defined above.
https://github.com/Azure/azure-iot-sdk-c/blob/2fcc76586632e8b81f92faca9e5a6fc0aaa60ad8/iothub_client/samples/iothub_ll_client_x509_sample/iothub_ll_client_x509_sample.c#L162-L165

Does this help?  Or are you referring to parameters other than used to set the openSSL adapter?

**Comment by gino-1557** [comment]
Ah thank you. I meant the parameter for example like the path to the tpm.

**Comment by momuno** [comment]
Hi @gino-1557.  Checking to see if you have any other questions.  Is the information provided helping you accomplish your task?

**Comment by gino-1557** [comment]
yes everything is fine so far thank you

**Comment by momuno** [comment]
Thanks @gino-1557 for the update.  I'd like to close this issue since it appears to be resolved.  If the issue comes back, please feel free to reopen.
