### ISSUE TITLE
sas_token_lifetime option for MQTT

### ISSUE THREAD

**Issue by simonemarra** [Azure/azure-iot-sdk-c#227]
Hi,
I'm using the iot-sdk-c on a microcontroller-based embedded device. I noticed a lack of option on MQTT libs: **sas_token_lifetime** option is missing in MQTT, but it seems to be available on AMQP libs.

# SDK version
The SDK version I'm using at the moment is the actual latest release version 1.1.22.

# Description
Our product connectivity type (GPRS/3G) data consumption is highly relevant, so I increased the sas token lifetime for our libs, to reduce the number of connections/disconnections needed. 
Each connection requires the SSL/TLS handshake, so each time the certificates are exchanged between peers (read about 10kB of data are wasted each connection!).
Since your default definition for the param _**SAS_TOKEN_DEFAULT_LIFETIME is 3600**_ and is hardcoded, I modified it and all works well, but each update of the IOT-HUB C sdk I need to remember to update such define!

# Improvement Request
I think to provide a **IoTHubClient_SetOption(iotHubClientHandle, "sas_token_lifetime",...)** API just like AMQP could be a great step over in GPRS/3G devices.

**Comment by tameraw** [comment]
@simonemarra - Thanks for raising this issue. We are working to provide common features across all protocols and all SDKs, so this is in our backlog.

**Comment by simonemarra** [comment]
Thank you!

**Comment by jebrando** [comment]
Fixed and checked In
