### ISSUE TITLE
Provisioning 401002 Invalid certificate Release - LTS_01_2022_Ref01

### ISSUE THREAD

**Issue by MariusTeltonika** [Azure/azure-iot-sdk-c#2270]
OS - Ubuntu 20
SDK veriosn - LTS_01_2022_Ref01

Description of the issue:
I have created certificates using certGen.sh script. Used these commands:

```
./certGen.sh create_root_and_intermediate
./certGen.sh create_device_certificate test20
```
Created Individual Enrollment
![image](https://user-images.githubusercontent.com/102955699/161515385-0a870bae-e83d-4b06-af86-4519505e0ae4.png)

Changed id scope in `prov_dev_client_sample` code:

```
static const char* id_scope = "0ne004DC640";
```
and specified Registration ID from provisioning hub:
```
Prov_Device_SetOption(prov_device_handle, PROV_REGISTRATION_ID, "test20");
```

I get **Invalid Certificate** and these errors:
```
Provisioning API Version: 1.8.0

Registering Device

-> 11:40:13 CONNECT | VER: 4 | KEEPALIVE: 0 | FLAGS: 130 | USERNAME: 0ne004DC640/registrations/test20/api-version=2019-03-31&ClientVersion=1.8.0 | CLEAN: 1
<- 11:40:13 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0
-> 11:40:13 SUBSCRIBE | PACKET_ID: 1 | TOPIC_NAME: $dps/registrations/res/# | QOS: 1
Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
<- 11:40:13 SUBACK | PACKET_ID: 1 | RETURN_CODE: 1
-> 11:40:13 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/PUT/iotdps-register/?$rid=1 | PAYLOAD_LEN: 27
<- 11:40:13 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: $dps/registrations/res/401/?$rid=1 | PACKET_ID: 2 | PAYLOAD_LEN: 150
-> 11:40:13 PUBACK | PACKET_ID: 2
Error: Time:Mon Apr  4 11:40:13 2022 File:/home/mypc/Downloads/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:prov_transport_process_json_reply Line:670 Unsuccessful json encountered: {"errorCode":401002,"trackingId":"9a5e135d-145a-4eb7-ba85-f446ec3c1be7","message":"Invalid certificate.","timestampUtc":"2022-04-04T08:40:13.875046Z"}
Error: Time:Mon Apr  4 11:40:13 2022 File:/home/mypc/Downloads/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:prov_transport_common_mqtt_dowork Line:979 Unable to process registration reply.
Error: Time:Mon Apr  4 11:40:13 2022 File:/home/mypc/Downloads/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Mon Apr  4 11:40:13 2022 File:/home/mypc/Downloads/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:770 Failure retrieving data from the provisioning service

Failure registering device: PROV_DEVICE_RESULT_DEV_AUTH_ERROR
Error: Time:Mon Apr  4 11:40:13 2022 File:/home/mypc/Downloads/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:387 Failure sending control packet data
Error: Time:Mon Apr  4 11:40:13 2022 File:/home/mypc/Downloads/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1342 Error: mqtt_client_disconnect send failed
Press enter key to exit:
```

Do i need to set some Trusted Certificates or do something else?

I have added the Root certificate generated by certGen.sh to provisioning Certificates and verified it. But this did not help with the issue.

**Comment by MariusTeltonika** [comment]
@[danewalton](https://github.com/danewalton)
Yes I have added the certificate and I have verified it.

Also i should mention that with older release version dps worked. But after cloning new release and trying dps of the new release it does not work. I tried same certificates from the older release version, but they did not work (using older version I did not need to add root certificate to dps instance).

Currently i did not manage to create a certificate that would work in DPS. Even if the Certificate is verified.

I tried to create a certifiacte on Windows 10 using Powershell and the same on Ubuntu 20. Azure iot sdk c provisioning still shows certificate as invalid.

**Comment by danewalton** [comment]
Also if you're using x509 certificates, please look into this sample we have recently added which might help: https://github.com/Azure/azure-iot-sdk-c/tree/main/provisioning_client/samples/prov_dev_client_ll_x509_sample#long-x509-client-certificate-chains

**Comment by MariusTeltonika** [comment]
I think I am sending the chain. I have added the chain certificates to this line
`Prov_Device_SetOption(prov_device_handle, OPTION_TRUSTED_CERT, cert);`
But I'm still getting the error.

I have tried generating these certificate chains:
1. RootCa -> IntermediateCA -> LeafCa
2. RootCa -> LeafCa

But **invalid certificate error is present with both**.

Now i have tried your suggestion with 'prov_dev_clent_ll_x509_sample` but I immediately get these errors without modifying any lines of code except for Registration id, id scope, certificate and private key variables.

```
Provisioning API Version: 1.8.0
Iothub API Version: 1.8.0
Error: Time:Thu Apr  7 08:50:09 2022 File:/home/mypc/Downloads/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_setoption Line:1684 unable to set x509 options more than once
Error: Time:Thu Apr  7 08:50:09 2022 File:/home/mypc/Downloads/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:construct_transport Line:568 Failure setting x509 cert on xio
Error: Time:Thu Apr  7 08:50:09 2022 File:/home/mypc/Downloads/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:create_connection Line:620 Failure constructing transport
Error: Time:Thu Apr  7 08:50:09 2022 File:/home/mypc/Downloads/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:prov_transport_common_mqtt_dowork Line:919 unable to create mqtt connection
Error: Time:Thu Apr  7 08:50:09 2022 File:/home/mypc/Downloads/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:770 Failure retrieving data from the provisioning service
Failure encountered on registration PROV_DEVICE_RESULT_TRANSPORT
registration failed!

```

Any idea where the problem is?

**Comment by danewalton** [comment]
I just ran it and it was working for me. Just for a sanity check. Are you able to create a certificate using the following openssl steps? Note the sections within `< >` which you need to change for the `CN` values.

```bash
# CA Cert
openssl ecparam -out ca_key.pem -name prime256v1 -genkey
openssl req -new -days 3650 -nodes -x509 -key ca_key.pem -out ca_cert.pem -subj "/CN=<your CA cert name>"

# Device Cert
openssl ecparam -out device_ec_key.pem -name prime256v1 -genkey
openssl req -new -key device_ec_key.pem -out device_ec.csr -subj "/CN=<name which matches registration ID>"
openssl x509 -req -in device_ec.csr -CA ca_cert.pem -CAkey ca_key.pem -CAcreateserial -out device_ec_cert.pem -days 365 -sha256 -extensions client_auth

# Validation of CA Cert
openssl ecparam -out validation_ec_key.pem -name prime256v1 -genkey
openssl req -new -key validation_ec_key.pem -out validation_ec.csr -subj "/CN=<validation code>"
openssl x509 -req -in validation_ec.csr -CA ca_cert.pem -CAkey ca_key.pem -CAcreateserial -out validation_ec_cert.pem -extensions client_auth -days 365 -sha256

The only changes I made to the `prov_dev_clent_ll_x509_sample` are below.

![image](https://user-images.githubusercontent.com/36710865/162210630-f86fd159-3c22-4788-a155-0a5bec106fbf.png)

**Comment by MariusTeltonika** [comment]
Thank you, it works from Ubuntu. Will perform test on embedded system.

The problem was with RSA based certificates. As I understand RSA certificates and private keys are too long for MQTT headers. Some values might be truncated or corrupted. Provisioning service works immediately with EC (Elliptic Curve) certificates.

**Comment by danewalton** [comment]
Hmmm okay. Just to note, certificates are not used in the MQTT connection but ARE used in the TLS connection. The authentication happens on connection first and then the MQTT CONNECT packet is sent with no password.

I'd love to look further into why your previous certificates weren't working. When you were adding the certificates, were you making another call to `Prov_Device_SetOption(prov_device_handle, OPTION_TRUSTED_CERT, cert);` as if it were appending? Or was the certificate value all one string value?

**Comment by MariusTeltonika** [comment]
All certificates were in one `const char* certificates`. Exactly same as with older release version.

**Comment by danewalton** [comment]
Ahh I think I know where things might have gone wrong. Above you listed that you ran

```bash
./certGen.sh create_root_and_intermediate
./certGen.sh create_device_certificate test20
```

But below in the readme, the indented bullet says if you want to use an intermediate certificate, the second command should be

```bash
./certGen.sh create_device_certificate_from_intermediate test20
```

https://github.com/Azure/azure-iot-sdk-c/blob/main/tools/CACertificates/CACertificateOverview.md#iot-leaf-device-1

Are you able to try that and see if it helps?

**Comment by MariusTeltonika** [comment]
I have tried that as well.
I just tested it, and it does not work with TRUSTED_CERTIFICATES Option.

**Comment by danewalton** [comment]
Oh I'm sorry I've been misreading the option you might have been setting the whole time.

![image](https://user-images.githubusercontent.com/36710865/162958513-3d78b687-e382-402e-ab7a-8894f5418f0e.png)

The value to set for client side certificates is the `OPTION_X509_CERT` and `OPTION_X509_PRIVATE_KEY`. The `OPTION_TRUSTED_CERT` is for the server side CA certificates (DigiCert or Baltimore certificates).

**Comment by momuno** [comment]
@MariusTeltonika have you been able to try `OPTION_X509_CERT` and `OPTION_x509_PRIVATE_KEY`?

**Comment by MariusTeltonika** [comment]
Yes I have tried these options. But they did not work with Realese version and RSA certificates. I had to clone your GitHub repository that is not yet released. And EC certificates worked with cloned code. I have already tested the code and EC certificates on my embedded system. Everything works now. Thank you.

**Comment by ericwol-msft** [comment]
@MariusTeltonika can we close this issue?

**Comment by MariusTeltonika** [comment]
Yes
