### ISSUE TITLE
parson.h is missing in deb packages?

### ISSUE THREAD

**Issue by TheAifam5** [Azure/azure-iot-sdk-c#2272]
Hey,

I'm trying to compile the project in docker (through generated iotedgedev Dockerfiles) and it cannot find "parson.h". I downloaded the deb packages from PPA to check them out and also does not exist there but the library is only present. 

Am I blind? :D 

Best regards,
TheAifam5

**Comment by danewalton** [comment]
Hi @TheAifam5
Do you know if you have submodules initialized?
```bash
git submodule update --init --recursive
```

**Comment by TheAifam5** [comment]
@danewalton it is not bootstrapped through git.

This is the content of Dockerfile:
```dockerfile
FROM ubuntu:bionic AS base
RUN apt-get update && \
  apt-get install -y --no-install-recommends software-properties-common gdb && \
  add-apt-repository -y ppa:aziotsdklinux/ppa-azureiot && \
  apt-get update && \
  apt-get install -y azure-iot-sdk-c-dev && \
  rm -rf /var/lib/apt/lists/*

FROM base AS build-env
ENV IOTEDGE_BUILD=1
RUN apt-get update && \
  apt-get install -y --no-install-recommends cmake gcc g++ make && \
  rm -rf /var/lib/apt/lists/* 
WORKDIR /work
COPY . ./
RUN cmake -DCMAKE_INSTALL_PREFIX="/work/install/usr/local" . && \
  cmake --build . --target install

FROM base
COPY --from=build-env /work/install /
CMD ["my-module"]
```

Source is copied and the CMakeLists.txt just adds include paths to IoT SDK like:
```cmake
find_path(iothub_client_include_dir azureiot/iothub.h)
set(AZURE_IOT_SDK_INCLUDE_DIRS ${iothub_client_include_dir}/azureiot)

target_link_directories(${CMAKE_PROJECT_NAME} PRIVATE
                          ${AZURE_IOT_SDK_LIBARY_DIRS})
```

The `azure-iot-sdk-c-dev` should provide such header.

**Comment by danewalton** [comment]
The parson.h header should have been installed via the parson library. I would recommend trying to install the library via the CMake in the repo, something like the following:

```bash
git clone https://github.com/Azure/azure-iot-sdk-c.git
cd azure-iot-sdk-c
mkdir cmake
cd cmake
cmake ..
cmake --build .
sudo make install
```

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now. Please let us know if you are still running into issues and would like it reopened.
