### ISSUE TITLE
Unable to install the C- SDK in raspberry pi 4 model b using the given instructions

### ISSUE THREAD

**Issue by PPK1996** [Azure/azure-iot-sdk-c#2273]
Following the steps provided I was not able to cross compile and install the C SDKs. Errors as below:

uilding C object iothub_client/samples/iothub_ll_c2d_sample/CMakeFiles/iothub_ll_c2d_sample.dir/iothub_ll_c2d_sample.c.o
[ 86%] Linking C executable iothub_ll_client_x509_sample
[ 87%] Linking C executable iothub_ll_telemetry_sample
[ 88%] Building C object iothub_client/samples/iothub_ll_c2d_sample/CMakeFiles/iothub_ll_c2d_sample.dir/__/__/__/certs/certs.c.o
[ 89%] Linking C executable iothub_convenience_sample
[ 89%] Linking C executable iothub_ll_c2d_sample
/home/administrator/RPiTools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
iothub_client/samples/iothub_ll_client_x509_sample/CMakeFiles/iothub_ll_client_x509_sample.dir/build.make:114: recipe for target 'iothub_client/samples/iothub_ll_client_x509_sample/iothub_ll_client_x509_sample' failed
make[2]: *** [iothub_client/samples/iothub_ll_client_x509_sample/iothub_ll_client_x509_sample] Error 1
CMakeFiles/Makefile2:1865: recipe for target 'iothub_client/samples/iothub_ll_client_x509_sample/CMakeFiles/iothub_ll_client_x509_sample.dir/all' failed
make[1]: *** [iothub_client/samples/iothub_ll_client_x509_sample/CMakeFiles/iothub_ll_client_x509_sample.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/administrator/RPiTools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find -luuid
collect2: error: ld returned 1 exit status
iothub_client/samples/iothub_convenience_sample/CMakeFiles/iothub_convenience_sample.dir/build.make:108: recipe for target 'iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample' failed
make[2]: *** [iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample] Error 1
CMakeFiles/Makefile2:1737: recipe for target 'iothub_client/samples/iothub_convenience_sample/CMakeFiles/iothub_convenience_sample.dir/all' failed
make[1]: *** [iothub_client/samples/iothub_convenience_sample/CMakeFiles/iothub_convenience_sample.dir/all] Error 2
/home/administrator/RPiTools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find -luuid
collect2: error: ld returned 1 exit status
/home/administrator/RPiTools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find -luuid

Request to let know what could be followed to make it work. If someone could provide the exact steps for the latest version of Raspberry Pi OS would be very helpful.

**Comment by danewalton** [comment]
Hi @PPK1996 
Try running

```bash
sudo apt install uuid-dev
```

**Comment by PPK1996** [comment]
> 
Hi @danewalton Did it. uuid-dev is already in the latest version. It would be really helpful if you could help me with the exact steps to complete this. I am currently using OS available at: https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2022-04-07/2022-04-04-raspios-bullseye-armhf-lite.img.xz on Raspberry Pi 4 Model B.

**Comment by danewalton** [comment]
Note that `apt` was deprecated as of this release here: [LINK](https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_07_2021_Ref01)

**Comment by danewalton** [comment]
I'm going to go ahead and close this for now. Please let us know if you need additional help and would like it reopened.
