### ISSUE TITLE
Receive messages from the cloud

### ISSUE THREAD

**Issue by patrickzgubic** [Azure/azure-iot-sdk-c#2277]
Hello,
currently I am working on the cloud to device communication. I want to have the received message in my main() and I have found the example: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-c-intro

The tutorial mentions project "iothub_client_sample_mqtt" but I can't find it.
"Within the iothub_client folder in the [azure-iot-sdk-c](https://github.com/azure/azure-iot-sdk-c) repository, there is a samples folder that contains an application called iothub_client_sample_mqtt."

Does the project still exist? I have found another project, but this is very complex and not easy to understand:
[iothub_ll_c2d_sample](https://github.com/Azure/azure-iot-sdk-c/tree/main/iothub_client/samples/iothub_ll_c2d_sample)

Thank you

**Comment by momuno** [comment]
Hi @patrickzgubic It's possibly been renamed to `iothub_client_sample_mqtt_dm` 
Please take a look here: https://github.com/Azure/azure-iot-sdk-c/tree/main/iothub_client/samples/iothub_client_sample_mqtt_dm

With respect to cloud to device communication, there is Direct Method/Device Method (dm) or Cloud-to-Device messaging (c2d).  Are you interested in both, or only one at the moment?

Device Method functionality can be found in the following samples:
https://github.com/Azure/azure-iot-sdk-c/tree/main/iothub_client/samples/iothub_client_device_twin_and_methods_sample
https://github.com/Azure/azure-iot-sdk-c/tree/main/iothub_client/samples/iothub_client_sample_mqtt_dm (also mentioned above).

Cloud-to-Device Messaging functionality can be found in this sample:
https://github.com/Azure/azure-iot-sdk-c/tree/main/iothub_client/samples/iothub_ll_c2d_sample
There is definitely a lot of info in the C2D sample.  Can you point me to which part you are looking at?

**Comment by patrickzgubic** [comment]
I don't think so that iothub_client_sample_mqtt_dm is the project for which I am looking for.

For now I am looking for infos about c2d.

In this method all the magic with receiving messages happens.
https://github.com/Azure/azure-iot-sdk-c/blob/be4ae0728592c8ab8b67780ce70880f6340d8522/iothub_client/samples/iothub_ll_c2d_sample/iothub_ll_c2d_sample.c#L269

My goal is that i can work with the message in the main().

I have a azure function which sends me the messages from the cloud
`private static ServiceClient serviceClient = ServiceClient.CreateFromConnectionString("<connectionString>");`
`var sendMessage = new Message(Encoding.ASCII.GetBytes("yes"));`
`await serviceClient.SendAsync("<deviceId>", sendMessage);`

**Comment by ericwol-msft** [comment]
Yes, DoWork() will process IoT hub messages. If the hub and send you a message, the receive_msg_callback() will be called with the message.

**Comment by patrickzgubic** [comment]
A thank you, I was looking for such a method.
