### ISSUE TITLE
Cannot send message with message property set

### ISSUE THREAD

**Issue by xjsxujingsong** [Azure/azure-iot-sdk-c#2278]
Hi I am currenlty running the demo code from azure-iot-sdk-c\iothub_client\samples\iothub_client_sample_module_sender. It worked and I can read message from IoTHub, but the message body field is not readable.  Then I added two lines of code below to change message property before calling send function. However, after this, IoTHub cannot receive any messages. Anyone knows the reason? Thanks.
......
(void)IoTHubMessage_SetContentTypeSystemProperty(messages[iterator].messageHandle, "application/json");
(void)IoTHubMessage_SetContentEncodingSystemProperty(messages[iterator].messageHandle, "utf-8");

if (IoTHubModuleClient_LL_SendEventToOutputAsync(iotHubModuleClientHandle, messages[iterator].messageHandle, "temperatureOutput", SendConfirmationCallback, &messages[iterator]) != IOTHUB_CLIENT_OK)
...........

**Comment by ericwol-msft** [comment]
can you please add more specific details?

`but the message body field is not readable`

**Comment by xjsxujingsong** [comment]
For example the message I input is 
sprintf_s(str, sizeof(str), "{\"happy\":true,\"pi\":%d}", message_idx);
This is a json string: {"happy":true,"pi":0}
The message body filed is something like:
"Body":"eyJoYXBweSI6dHJ1ZSwicGkiOjIzOH0="

**Comment by ericwol-msft** [comment]
`eyJoYXBweSI6dHJ1ZSwicGkiOjIzOH0=` is the base64 encoding of `{"happy":true,"pi":238}`

https://codebeautify.org/base64-decode/y227f573f

**Comment by xjsxujingsong** [comment]
Thanks. I figured out the problem by replacing "application/json" to "application%2fjson":
		(void)IoTHubMessage_SetContentTypeSystemProperty(message.messageHandle, "application%2fjson");

I also have another question. 
Using connection string to IoTHUB, we have two ways low-level API (single thread "_ll_") and "high level" API (multi-thread) as demonstrated in 
https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c
vs
https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample.c

Both ways work well in my side. Now I am switching to module based connection using 
azure-iot-sdk-c\iothub_client\samples\iothub_client_sample_module_sender. I can see this is the single thread version. I found the API using multi-thread  in https://github.com/MicrosoftDocs/Azure-IoT-C-SDK-Reference/blob/main/iothub-module-client-h/iothubmoduleclient-sendeventasync.md


However, there is no sample code. Could you provide any sample code? Thank you very much!

**Comment by ericwol-msft** [comment]
No there is no sample. You should be able to figure this out. From the sample, instead of calling the IoTHubDeviceClient_XXX apis, just call the IoTHubModuleClient_XX apis

**Comment by xjsxujingsong** [comment]
Yes, I follow this process by simply replaceing the API names. After running the code, I can see all the logs are good and received "OK". The only issue is that I still cannot find the message in the IoTHUB. Very strange.

**Comment by xjsxujingsong** [comment]
BTW, for the module + low level API way, I can successfully run the sample code. Then I create a new thread to call the sending function, it came up with the error
Error: Time:Fri Apr 22 02:20:35 2022 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:UpdateMqttConnectionStateIfNeeded Line:2783 mqtt_client timed out waiting for CONNACK

**Comment by xjsxujingsong** [comment]
I finally figured out the solutions.
The low level API cannot be used in user defined multi-thread environment. 
For module based multi-thread API, the following two APIs work
(void)IoTHubMessage_SetContentTypeSystemProperty(message_handle, "application/json");
IoTHubModuleClient_SendEventToOutputAsync(client_handle, message_handle, "message_indicator", send_confirm_callback_module, NULL);

But the following two APIs do not work. I dont know why.

(void)IoTHubMessage_SetContentTypeSystemProperty(message_handle, "application%2json");
IoTHubModuleClient_SendEventAsync(client_handle, message_handle, "message_indicator", send_confirm_callback_module, NULL);

**Comment by danewalton** [comment]
I think for the call to `IoTHubModuleClient_SendEventAsync()` you have one too many parameters ("message_indicator").

**Comment by xjsxujingsong** [comment]
@danewalton  You are correct. It is a typo. I just want to list the API workable and not workable for me.
