### ISSUE TITLE
TPM Simulator Registration ID

### ISSUE THREAD

**Issue by patrickzgubic** [Azure/azure-iot-sdk-c#2286]
Hello,
I'm trying to find out which hash function is used to get the registration id from the endorsement key. 
I've read that it's supposed to be a sha-256 hash, but when I use an online encryption tool I don't get the same result.

https://github.com/Azure/azure-iot-sdk-c/blob/7a50ea4ff94606036193a2ae368aa224238bd770/provisioning_client/tools/tpm_device_provision/tpm_device_provision.c#L89

My EK
AToAAQALAAMAsgAgg3GXZ0SEs/gakMyNRqXXJP1S124GUgtk8qHaGzMUaaoABgCAAEMAEAgAAAAAAAEAtKEADl/sNRgmYAjP6gXmbccRaJoTnVixisUaek0OwAzFGN70xt9ZOYp6fhIwfcft3fdVKOrKpXYcTe72CGNkGJGlQz5ti9n2pQ0uJhcX8aefh4Onm7lVlUCQAVp1K0r6zI8vkEXWsBIvwvxk0eMJbFaq146kbTkJHIGczb89RkFH2TX+CgXeZOG9oXQzUNwktmTUacspamune5Wywc/ce8HsDFYchyUHogFhrZ/LPnzyTDXO8sSC5z5dvsUBtUME3iRYDyKgZOfBtmRMqQewD+4iH+ZEJjtsyJiWR8hFhyKROnOuqXfNFwjd5IcNU4wtlKO0cLyXmTOfQK6Da1pr5Q==

My Registration ID
y5wivfciikcievvnsbpkhzcahwm4chuzx6v4hnqnlqfs3fjf6rxa

Thank you

**Comment by danewalton** [comment]
[Based on the docs here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-devices-at-scale-windows-tpm?view=iotedge-2018-06&tabs=physical-tpm#set-up-your-tpm) you can create a registration ID derived from your unique endorsement key (public/private key).

![image](https://user-images.githubusercontent.com/36710865/166262216-b222351d-8e58-4160-bdcf-e4202a74d0c3.png)

As noted above SHA256 is one way you could do that. All that matters is that the one generated by your device and sent to the cloud matches the one registered in the cloud.

**Comment by CIPop** [comment]
In case you'd like to replicate or reuse the code in the SDK:

This is the code producing the SHA256 from the EK: https://github.com/Azure/azure-iot-sdk-c/blob/main/provisioning_client/src/prov_auth_client.c#L89 
You can use this tool to generate the same registration ID from an EK: https://github.com/Azure/azure-iot-sdk-c/blob/main/provisioning_client/src/prov_auth_client.c#L89

**Comment by patrickzgubic** [comment]
Ah ok, thank you
