### ISSUE TITLE
Run a sample documentation

### ISSUE THREAD

**Issue by hegate** [Azure/azure-iot-sdk-c#23]
@olivierbloch  The how to run a sample documentation doesn't seem to be consistent with other languages. All I could find was https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md which is a very long document and kind of difficult for a new dev.

Are there any plans to include a sample like in the Python SDK for example?

**Comment by olivierbloch** [comment]
Hi @hegate 
By nature, the use of the C SDK is different from others, hence the difference in how the instructions are showing up.
Note that even though the document you point to is long, it contains the necessary information to simply run the samples.
On Windows, it [indicates](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#building-the-sample-applications-only) how to run the samples simply using Visual Studio.
On Linux, you can [leverage our apt-get packages](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/ubuntu_apt-get_sample_setup.md).
I'll revisit the readme's to make this path clearer.

**Comment by kevinvle** [comment]
Hi @hegate . This is unrelated and I'm sorry but I really need your help if you can regarding your tutorial on using azure and the feather m0. https://azure.microsoft.com/en-us/resources/samples/iot-hub-c-m0wifi-getstartedkit/

**Comment by hegate** [comment]
Hi @kevinlam1 could you please open an issue here https://github.com/Azure-Samples/iot-hub-c-m0wifi-getstartedkit/issues and loop @mamokarz? Thanks
