### ISSUE TITLE
'AzureIoTHubClient' does not name a type

### ISSUE THREAD

**Issue by snobu** [Azure/azure-iot-sdk-c#230]
What happened to the `AzureIoTHubClient` type in the HTTP sample?

```
static AzureIoTHubClient iotHubClient;
        ^
exit status 1
'AzureIoTHubClient' does not name a type
```

More importantly, a few library updates ago i was using 

```
iotHubClient.setEpochTime(time);
```
to set the current time on the IoTHub client instance. How do i set the Epoch Time now if i no longer instantiate the client myself? I'm running on a Feather M0 (WINC1500 19.5.2) from Adafruit.

Looks like the time doesn't get set, which i believe is the reason for this failure (clock defaults to 1999):

```
% cat /dev/cu.usbmodem1411

IP Address: 192.168.137.123
Fetched NTP epoch time is: 1505294321
Info: IoT Hub SDK for C, version 1.1.18
Error: Time:Tue Nov 30 00:00:00 1999
File:/Users/snobu/Documents/Arduino/libraries/AzureIoTHub/src/sdk/iothubtransporthttp.c
Func:DoMessages Line:2069 expected status code was 200,
but actually was received 401... moving on

also:

Error: Time:Tue Nov 30 00:00:00 1999
File:/Users/snobu/Documents/Arduino/libraries/AzureIoTUtility/src/adapters/tlsio_arduino.c 
Func:tlsio_arduino_create Line:156 Host poorlyfundedskynet.azure-devices.net not found.
```

**Comment by JetstreamRoySprowl** [comment]
@snobu : Hi Adrian, I'm not certain what this is running within, but all of our Arduino samples set up the NTP service in their respective .ino files before any Azure IoT calls are made, and the SDK does depend on having the system time set correctly before it gets used.

I'm not sure where you're getting the AzureIoTHubClient type, as it doesn't show up in our SDK. It _does_ show up in some keywords.txt files, which it probably shouldn't.

**Comment by snobu** [comment]
Thanks for looking into this. That type used to be a thing in the past in the SDK:

See this -
https://github.com/Azure/azure-iot-arduino-protocol-http/commit/657039660f7c5cc9613cca58abfdad8e7eea8ef2#diff-8d3043be8e48c5ae9e21d50b7e2c90d1R60

and this -
https://github.com/Azure/azure-iot-arduino-protocol-http/commit/657039660f7c5cc9613cca58abfdad8e7eea8ef2#diff-8d3043be8e48c5ae9e21d50b7e2c90d1R132

So that's really what i'm asking, is this where the time is set for an Arduino M0 (SAMD architecture)?

````
void initTime() {
#if defined(ARDUINO_SAMD_ZERO) || defined(ARDUINO_SAMD_MKR1000) || defined(ARDUINO_SAMD_FEATHER_M0)
#ifdef ARDUINO_SAMD_FEATHER_M0
    Adafruit_WINC1500UDP ntpUdp; // for Adafruit WINC1500
#else
    WiFiUDP ntpUdp;
#endif
    NTPClient ntpClient(ntpUdp);

    ntpClient.begin();

    while (!ntpClient.update()) {
        Serial.println("Fetching NTP epoch time failed! Waiting 5 seconds to retry.");
        delay(5000);
    }

    ntpClient.end();
```

Because it only works 20% on 50% percent of the time.. and i don't know if your sample sketch is doing it wrong, the NTP library is unreliable or my Adafruit Feather M0 is just stubborn with time.

**Comment by JetstreamRoySprowl** [comment]
I would expect that to work, which it doesn't seem to be doing for you. If ntpClient.update() is returning true when it hasn't actually set the time yet, I'd say there's a bug in ntpClient.update() which should be reported to whoever owns that library. As a workaround you may want to add a loop that keeps trying until the time looks reasonable, but bugs in ntpClient.update() are outside the scope of our SDK. Good luck!

**Comment by snobu** [comment]
The strange thing is i added synthetic sleep statements to make sure i'm not being lied to by that call but it didn't seem to make any difference. If you're ok with it i'll do a little more digging before closing this issue.

**Comment by JetstreamRoySprowl** [comment]
@snobu Hi Adrian, if you don't mind I'm closing this one since the original question seems settled. Although if you found a solution to the time update problem I'd like to hear because I'm seeing it also. Ciao!

**Comment by snobu** [comment]
Im afraid i didn't. Clock get set correctly on the M0, if you print it you'll see it looks right, however the SDK timestamp still says 1999. But not every time. If you remove power and boot again there's a good chnce it works. Could be a race problem? But a bizarre one since sleeping for x seconds does not help.

**Comment by snobu** [comment]
Looks like switching to a SAS instead of key in the Connection String works around the bug.

simplesample_mqtt.c:
```
static const char* connectionString = "HostName=poorlyfundedskynet.azure-devices.net;DeviceId=WINC1500;SharedAccessSignature=SharedAccessSignature sr=poorlyfundedskynet.azure-devices.net%2Fdevices%2FWINC1500&sig=ThESigNatUre"
```

Everything works as it should with the SAS:

```
Fetched NTP epoch time is: 1510733878
Info: IoT Hub SDK for C, version 1.1.26
IoTHubClient accepted the message for delivery
Message Id: 0 Received.
Result Call Back Called! Result is: IOTHUB_CLIENT_CONFIRMATION_OK
```
Can someone track down this bug? Or at least mention it in the README for the time being.
Got the SAS idea from [this answer](https://stackoverflow.com/a/41248939/4148708).
