### ISSUE TITLE
What is the expected error code returned if the IoTHub device is disabled while still connected?

### ISSUE THREAD

**Issue by cabrillosa** [Azure/azure-iot-sdk-c#2300]
I would like to know what is the expected error code returned if the IoTHub device is disabled while still connected in the IoTHub.
I tested it with the scenario below:

Scenario A:
1. Device is connected to iothub.
2. Disable the device in azure iot explorer.
3. Device was disconnected
actual result: error code received was IOTHUB_CLIENT_CONNECTION_NO_NETWORK
I expect that the error code should be IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED

Scenario B:
1. Disable the device first in iothub.
2. Device will attempt the connection.
actual result: error code received was  IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED

Scenario B is expected. How about scenario A?

Thank you very much for your support!

**Comment by jayx2k5** [comment]
Hi cabrillosa,
Since device was initially connected, sdk may have cache of the connection but suddenly disconnected thus NO_NETWORK.
Don't know much on sdk core though, :D May need to handle it accordingly.

**Comment by ericwol-msft** [comment]
What protocol is this over? MQTT?

**Comment by cabrillosa** [comment]
Hi @ericwol-msft .
I am using MQTT over Websockets.

**Comment by ericwol-msft** [comment]
> > 
> 
> So, the current SDK implementing MQTT v3.1.1 returns IOTHUB_CLIENT_CONNECTION_NO_NETWORK in scenario A is expected?

Correct

**Comment by cabrillosa** [comment]
Thank you for answering my question @ericwol-msft. Closing this issue now
