### ISSUE TITLE
Build SDK for arm linux. Linker Error

### ISSUE THREAD

**Issue by lutoepfer** [Azure/azure-iot-sdk-c#2305]
# General Info  
SDK Version: **lts_01_2022**
C Compile: **gcc-arm 4.9.3**
CXX Compiler: **gcc-arm 4.9.3**

# What i done

I build the sdk using the azure-iot-sdk-c/build_all/linux/build.sh.
This provides me the following libraries:

./cmake/umqtt/libumqtt.a
./cmake/iothub_client/libiothub_client_http_transport.a
./cmake/iothub_client/libiothub_client_amqp_ws_transport.a
./cmake/iothub_client/libiothub_client_mqtt_ws_transport.a
./cmake/iothub_client/libiothub_client.a
./cmake/iothub_client/libiothub_client_amqp_transport.a
./cmake/iothub_client/libiothub_client_mqtt_transport.a
./cmake/deps/umock-c/libumock_c.a
./cmake/deps/uhttp/libuhttp.a
./cmake/deps/parson/libparson.a
./cmake/uamqp/libuamqp.a
./cmake/c-utility/libaziotsharedutil.a
./cmake/serializer/libserializer.a
./cmake/iothub_service_client/libiothub_service_client.a

This files i added to the Additional Dependencies.

# My Problem

The Code compiles and then gives me the following Linker error:

1>Linking objects
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function DisconnectFromClient: error: undefined reference to 'mqtt_client_clear_xio'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function DisconnectFromClient: error: undefined reference to 'mqtt_client_disconnect'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function DisconnectFromClient: error: undefined reference to 'mqtt_client_dowork'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function DisconnectFromClient: error: undefined reference to 'mqtt_client_dowork'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function publishDeviceTwinGetMsg: error: undefined reference to 'mqttmessage_create'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function publishDeviceTwinGetMsg: error: undefined reference to 'mqtt_client_publish'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function publishDeviceTwinGetMsg: error: undefined reference to 'mqttmessage_destroy'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function publishTelemetryMsg: error: undefined reference to 'mqttmessage_create_in_place'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function publishTelemetryMsg: error: undefined reference to 'mqttmessage_destroy'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function publishTelemetryMsg: error: undefined reference to 'mqtt_client_publish'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function freeTransportHandleData: error: undefined reference to 'mqtt_client_deinit'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function freeTransportHandleData: error: undefined reference to 'mqtt_client_clear_xio'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function mqttNotificationCallback: error: undefined reference to 'mqttmessage_getTopicName'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function mqttNotificationCallback: error: undefined reference to 'mqttmessage_getApplicationMsg'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function mqttNotificationCallback: error: undefined reference to 'mqttmessage_getApplicationMsg'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function mqttNotificationCallback: error: undefined reference to 'mqttmessage_getApplicationMsg'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function mqttNotificationCallback: error: undefined reference to 'mqttmessage_getPacketId'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function mqttNotificationCallback: error: undefined reference to 'mqttmessage_getQosType'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function mqttNotificationCallback: error: undefined reference to 'mqttmessage_getApplicationMsg'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_Create: error: undefined reference to 'mqtt_client_init'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_Destroy: error: undefined reference to 'mqtt_client_clear_xio'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_Destroy: error: undefined reference to 'mqtt_client_disconnect'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_Destroy: error: undefined reference to 'mqtt_client_dowork'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_Destroy: error: undefined reference to 'mqtt_client_dowork'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_Unsubscribe_DeviceMethod: error: undefined reference to 'mqtt_client_unsubscribe'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_DeviceMethod_Response: error: undefined reference to 'mqttmessage_create_in_place'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_DeviceMethod_Response: error: undefined reference to 'mqtt_client_publish'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_DeviceMethod_Response: error: undefined reference to 'mqttmessage_destroy'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_DeviceMethod_Response: error: undefined reference to 'mqttmessage_destroy'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_Unsubscribe: error: undefined reference to 'mqtt_client_unsubscribe'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_ProcessItem: error: undefined reference to 'mqttmessage_create_in_place'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_ProcessItem: error: undefined reference to 'mqtt_client_publish'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_DoWork: error: undefined reference to 'mqtt_client_disconnect'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_DoWork: error: undefined reference to 'mqtt_client_connect'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_DoWork: error: undefined reference to 'mqtt_client_subscribe'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_DoWork: error: undefined reference to 'mqtt_client_clear_xio'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_SetOption: error: undefined reference to 'mqtt_client_set_trace'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_SetOption: error: undefined reference to 'mqtt_client_set_trace'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_SendMessageDisposition: error: undefined reference to 'mqtt_client_send_message_response'
1>myProjektDir\azure-iot-sdk-c\cmake\iothub_client\libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o) : error : iothubtransport_mqtt_common.c:function IoTHubTransport_MQTT_Common_Unsubscribe_InputQueue: error: undefined reference to 'mqtt_client_unsubscribe'

Can you tell what i am missing ?

Thanks for your help.

**Comment by danewalton** [comment]
Hi @lutoepfer 
Just double checking that you habe submodules initialized?

```
git submodule update --init --depth 1
```

**Comment by lutoepfer** [comment]
Hi @danewalton 
i just run the command. Unfortunately the error persists.

**Comment by danewalton** [comment]
Can you give more details on any options or modifications you've made? I just ran it with `./build_all/linux/build.sh` and it works.

**Comment by lutoepfer** [comment]
Here is my CMake File: 

INCLUDE(CMakeForceCompiler)

SET(CMAKE_SYSTEM_NAME Linux)     
SET(CMAKE_SYSTEM_VERSION 1)     

SET(CMAKE_C_COMPILER /usr/bin/gcc-arm)
SET(CURL_INCLUDE_DIR myProjektDir/armv7a-vfp-neon-oe-linux-gnueabi/usr/include/curl)

i run the build.sh with following command  ./build.sh --toolchain-file my.cmake

**Comment by danewalton** [comment]
Is this the only change you have? So you have that short toolchain file which you pass and then you build? Is this part of a larger build process? I just have a feeling there's some missing steps here.

**Comment by lutoepfer** [comment]
Yes, this is the only change i did. In the meantime, i have tried the other protocols provided by the SDK. They work fine, just MQTT and MQTT_OVER_WEBSOCKETS gives me the mentioned Linker error. For AMQP i had to add "uuid" to the LibraryDependencies.

**Comment by lutoepfer** [comment]
This are the files with were build after i execute the build.sh. I am using all off them as Additional Dependencies for the Linker in the Visual Studio Project Properties.

**Comment by danewalton** [comment]
I would try putting the first line (`./cmake/umqtt/libumqtt.a`) after the `_mqtt_transport.a`. So something like:

```
./cmake/iothub_client/libiothub_client_http_transport.a
./cmake/iothub_client/libiothub_client_amqp_ws_transport.a
./cmake/iothub_client/libiothub_client_mqtt_ws_transport.a
./cmake/iothub_client/libiothub_client.a
./cmake/iothub_client/libiothub_client_amqp_transport.a
./cmake/iothub_client/libiothub_client_mqtt_transport.a
./cmake/deps/umock-c/libumock_c.a
./cmake/umqtt/libumqtt.a
./cmake/deps/uhttp/libuhttp.a
./cmake/deps/parson/libparson.a
./cmake/uamqp/libuamqp.a
./cmake/c-utility/libaziotsharedutil.a
./cmake/serializer/libserializer.a
./cmake/iothub_service_client/libiothub_service_client.a
```

I think what's happening is the mqtt library goes through the linker and the linker doesn't see anything using the code so it drops it. Putting it after the `_mqtt_transport.a` will mark those functions as used but not yet found in a `.a`.

**Comment by lutoepfer** [comment]
Now it runs :D . Thanks a lot for your help and patience.
I am closing this Ticket.
