### ISSUE TITLE
Unable to pod install AzureIoTHubClient (1.8.0-patch-1)

### ISSUE THREAD

**Issue by JoeCoy** [Azure/azure-iot-sdk-c#2309]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

MacBook Pro 
macOS Monterey (Version 12.3.1)

**SDK Version (Please Give Commit SHA if Manually Compiling)**

AzureIoTHubClient (1.8.0-patch-1)
8755147a04b6842c43ed2f596f36503b5e77a188

**Describe the Bug**

When trying to install AzureIoTHubClient 1.8.0-patch-1, I receive the following error:

```
[!] Error installing AzureIoTHubClient
[!] /usr/bin/git -C /var/folders/p5/rm91k1ns49lg26ct83rgp0800000gn/T/d20220526-31435-1pc4fyi checkout --quiet 8755147a04b6842c43ed2f596f36503b5e77a188

error: Your local changes to the following files would be overwritten by checkout:
	SECURITY.MD
Please commit your changes or stash them before you switch branches.
Aborting
```

This error was first brought to my attention by a new developer 6 days ago using our repo that depends on AzureIoTHubClient. I then discovered that upon cloning a new instance of our repo and running `pod install`, I receive the same error. I even created a new user on my machine, cloned the repo, and failed to pod install with this error.

I noticed that this Pull Request https://github.com/Azure/azure-iot-sdk-c/pull/2303 was merged 7 days ago and added SECURITY.MD to this project. I wonder if that is related to this behavior? Any help would be very appreciated as we would like to resolve this issue as quickly as possible to resume development for our affected team members.

**Comment by danewalton** [comment]
Hi @JoeCoy 
It shouldn't have affected it. The pods should be based on a specific commit SHA and not whatever is in master at any given time. Are you saying you clone this repo or your own?

Also I do have to suggest [giving our swift sample SDK a try here](https://github.com/Azure-Samples/azure-sdk-for-c-swift). It is a light wrapper over our Embedded C SDK and gives additional features like x509 client authentication and Device Provisioning.

**Comment by JoeCoy** [comment]
@danewalton Thank you for your quick reply. I am referring to a repo that is our own. It is a consumer of AzureIoTHubClient via cocoapods. It looks like your example app uses AzureIoTHubClient through swift packages, but I did successfully execute `swift package update` in the sample sdk that you linked. Perhaps it's specific to cocoapods or maybe something in our environment that is the problem.

The following steps reproduce the issue:
 - create a new xcode project
 - run `pod init` to create a podfile in the new repo
 - add the following two lines to the new podfile
 ```
source 'https://github.com/CocoaPods/Specs.git'
pod 'AzureIoTHubClient'
 ```
 - in the director containing the new podfile, execute `pod install` or `pod update`
 
 This results in the error I described above.

**Comment by danewalton** [comment]
Is there a reason y'all clone the whole Cocoapods Spec repo? Based on the Cocoapods getting started, you can add dependenceis in this way:

![image](https://user-images.githubusercontent.com/36710865/170606602-08f3b987-f407-44a1-af03-932dc9e887a2.png)

**Comment by JoeCoy** [comment]
@danewalton I get the same result without `source 'https://github.com/CocoaPods/Specs.git'` included in the podfile. Were you able to reproduce this issue?

**Comment by danewalton** [comment]
Ahh I think I found it. PR here to remove a redundant file:

**Comment by danewalton** [comment]
Ahh I think I found it. PR here to remove a redundant file:
https://github.com/Azure/azure-iot-sdk-c/pull/2310

**Comment by JoeCoy** [comment]
Awesome. Thank you!

**Comment by danewalton** [comment]
okay give it a try now

**Comment by JoeCoy** [comment]
That did the trick 👍 Thanks for fixing this so quickly.
