### ISSUE TITLE
File Upload using X509 with Custom HSM 

### ISSUE THREAD

**Issue by pucki91** [Azure/azure-iot-sdk-c#2316]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
Cross Compiled on Yocto Image

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release latest

**Protocol**

MQTT

**Describe the Bug**

File Upload to Blob using X509 Authentication with Custom_HSM
Authentifaction via Provisioning Client and IOThub to send telemetry messages and Device twin works well!, only file upload won't work
iotHubClientHandle_ll = IoTHubDeviceClient_LL_CreateFromDeviceAuth(user_ctx.iothub_uri, user_ctx.device_id, MQTT_Protocol);

IoTHubDeviceClient_LL_UploadToBlob

Func:HTTPAPI_SetOption Line:774 unable to curl_easy_setopt
Func:HTTPAPIEX_ExecuteRequest Line:468 HTTPAPI_SetOption failed when called for option x509privatekey

**Console Logs**

468 HTTPAPI_SetOption failed when called for option x509privatekey
* STATE: INIT => CONNECT handle 0x2670f20; line 1657 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x2670f20; line 1703 (connection #0)
* family0 == v4, family1 == v6
*   Trying xx.xxx.xxx.xxx:443...
* STATE: WAITRESOLVE => WAITCONNECT handle 0x2670f20; line 1785 (connection #0)
* Connected to ***.azure-devices.net () port 443 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x2670f20; line 1848 (connection #0)
* Marked for [keep alive]: HTTP default
* found 129 certificates in /etc/ssl/certs/ca-certificates.crt
* ALPN, offering http/1.1
* STATE: SENDPROTOCONNECT => PROTOCONNECT handle 0x2670f20; line 1869 (connection #0)
* SSL connection using TLS1.2 / DHE_RSA_AES_256_GCM_SHA384
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: *.azure-devices.net (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=*.azure-devices.net
*        start date: Sun, 29 May 2022 03:30:01 GMT
*        expire date: Sat, 29 Oct 2022 03:30:01 GMT
*        issuer: C=US,O=Microsoft Corporation,CN=Microsoft RSA TLS CA 01
* ALPN, server did not agree to a protocol
* STATE: PROTOCONNECT => DO handle 0x2670f20; line 1888 (connection #0)
> POST /devices/xxxx/files/?api-version=2016-11-14 HTTP/1.1
Host: ***.azure-devices.net
Content-Type: application/json
Accept: application/json
User-Agent: iothubclient/1.8.0
Content-Length: 38

* upload completely sent off: 38 out of 38 bytes
* STATE: DO => DO_DONE handle 0x2670f20; line 1943 (connection #0)
* STATE: DO_DONE => PERFORM handle 0x2670f20; line 2064 (connection #0)
* Mark bundle as not supporting multiuse
* HTTP 1.1 or later with persistent connection
< HTTP/1.1 401 Unauthorized
< Content-Length: 161
< Content-Type: application/json; charset=utf-8
< Server: Microsoft-HTTPAPI/2.0
< x-ms-request-id: bd058f54-73bc-44b8-a576-8c0238e05a38
< iothub-errorcode: IotHubUnauthorizedAccess
< Date: Mon, 13 Jun 2022 12:20:16 GMT
<
* STATE: PERFORM => DONE handle 0x2670f20; line 2254 (connection #0)
* multi_done
* Connection #0 to host xxx.azure-devices.net left intact
* Expire cleared (transfer 0x2670f20)
Error: Time:Mon Jun 13 12:20:16 2022 File:azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:690 Failure in HTTP communication: server reply code is 401
Info: HTTP Response:{"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:bd058f5473bc44b8a5768c0238e05a38-G:0-TimeStamp:06/13/2022 12:20:16"}

**Comment by CIPop** [comment]
@pucki91 File Upload is performed using cURL and always via HTTPS which is the likely reason this is failing.

The error indicates an issue when passing the certificate to cURL (Func:HTTPAPIEX_ExecuteRequest Line:468 HTTPAPI_SetOption failed when called for option x509privatekey) which should pass through what your Custom HSM implementation returns from `custom_hsm_get_key`. 

I made relatively recent breaking changes this year: https://github.com/Azure/azure-iot-sdk-c/pull/2229.

Could you try with the latest code please? Also, if you're not using an actual HSM system such as DICE/RIoT, TPM, etc, I believe it's best to switch to the new X509 system presented in the PR above and the new Provisioning X509 sample: https://github.com/Azure/azure-iot-sdk-c/tree/main/provisioning_client/samples/prov_dev_client_ll_x509_sample

**Comment by pucki91** [comment]
@CIPop Thanks for your answer, just updated the files and did set the Options, Authentification works well via Provisioning, IOTHub gets connected via MQTT, but as soon as I trigger the Blob Upload I do get the same issues, but with additional error Code: 
 Func:HTTPAPI_CreateConnection Line:172 curl_sslbackend (2) currently used by cURL does not match TLS platform                                               (OpenSSL) used by C SDK on Linux or OSX. Please configure and compile cURL to use OpenSSL

HTTPAPI_SetOption Line:813 unable to curl_easy_setopt
HTTPAPI_SetOption failed when called for option x509privatekey

Before I start the application I do export the OPENSSL_CONF=/etc/ssl/opensslA71CH_i2c.cnf to our Security Module

Thanks,
Daniel

**Comment by ericwol-msft** [comment]
Can the issue be closed?

**Comment by pucki91** [comment]
yes, can be closed

**Comment by pucki91** [comment]
Yes, thanks

Eric Wolz ***@***.***> schrieb am Mi., 15. Juni 2022, 18:11:
