### ISSUE TITLE
How to properly close/shutdown IoT client?

### ISSUE THREAD

**Issue by zygmunt** [Azure/azure-iot-sdk-c#2317]
Scenerio:
* There is no internet connection (local network works properly, device has connection to the router)
1. IoT client got created (IoTHubDeviceClient_CreateFromConnectionString)
2. I'm sending message (IoTHubDeviceClient_SendEventAsync)
3. I want to get device twin properties (IoTHubDeviceClient_GetTwinAsync)

Point 2 and 3 stays in the memory, and wait for connection.
After some time I want to shutdown client (IoTHubDeviceClient_Destroy).

So for now:
ad 2. My callback eventConfirmationCallback in IoTHubDeviceClient_SendEventAsync got clled with IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY result value - that's GOOD
ad 3. My callback deviceTwinCallback in IoTHubDeviceClient_GetTwinAsync IS NOT CALLED.

Is this correct behavior?
What with other calls? For example:
-IoTHubDeviceClient_SendReportedState
-IoTHubDeviceClient_UploadToBlobAsync
How to properly cleanup resources which are assigned in userContextCallback?

**Comment by ericwol-msft** [comment]
did IoTHubDeviceClient_GetTwinAsync() return an error? If so, you need to free the context there.

**Comment by zygmunt** [comment]
> did IoTHubDeviceClient_GetTwinAsync() return an error? If so, you need to free the context there.

Nope, all is good:
`IoTHubDeviceClient_GetTwinAsync call result IOTHUB_CLIENT_OK`

**Comment by ericwol-msft** [comment]
I repoed the issue. This is a regression from ccbdfafd

**Comment by ericwol-msft** [comment]
Closing this issue. The fix is in the main branch.
