### ISSUE TITLE
IOTHUBDEVICECLIENT - Losing messages if the sleep between SendEventAsync is less than 125 ms

### ISSUE THREAD

**Issue by jlingaa** [Azure/azure-iot-sdk-c#2318]
**Ubuntu 20.04**

**[LTS_01_2022_Ref01](https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_01_2022_Ref01)**

**Protocol**

AMQP_Protocol_over_WebSocketsTls

**Describe the Bug**

We wrote a small sample app in RUST that wraps the C SDK with the convenience api. The sample app is supposed to create the iothub device client handle using the connection string to IotHub and then call SendEventAsync in a loop for a sample message. We noticed we needed to sleep the thread for a few milliseconds between calling the SendEventAsync multiple times. Initially set the sleep to 5 ms and it worked ok. Over further testing, we realized the app is sending messages but the azure portal metrics for D2C telemetry messages chart shows that few messages were missed.

Here are couple of examples.

Sending 100000 messages shows about ~99700 messages received on the azure portal metrics.
Sending 5k messages shows about ~4.94k messages received on the portal.

We ran further tests for 5k messages altering the sleep period and at a sleep of ~125 ms, azure portal shows all the 5k messages reached. Is this a hard limit of ~125 ms to delay between sending messages? This slows us down in max possible performance. Please advise.

**[MCVE](https://stackoverflow.com/help/mcve)**

```
send_message(device_client: *mut azure_iot_sdk: DeviceClientHandle, sample_message: &str) {
    let message_handle = message_create_from_byte_array(sample_message.as_bytes()).unwrap();
    set_content_type_system_property(message_handle, "application/json");
    set_content_encoding_system_property(message_handle, "utf-8");

    device_client_send_event_async(device_client, message_handle, service_report_callback).unwrap();
    iot_ub_message_destroy(message_handle);
}

fn main() {

  let sample_message = r#"{
      "name": "hello"
      }"#;
  
  let device_handle = create_device_handle(); // wraps the CreateFromConnectionString api call here.
  for n in 0..5000 {
      send_message(device_handle, sample_message);
      thread::sleep(time::Duration::from_millis(5)); // 125 ms here works with no message loss
      println!("Message count main thread: {}", n);
  }
  
  loop {
    thread::sleep(time::Duration::from_millis(1000));
  }
}
```

**Comment by jlingaa** [comment]
As an update, we ran the exact code with 125 ms sleep in two different threads each sending 5000 and 10000 messages respectively. Total number of telemetry messages sent count on Azure Portal shows 13.04k which is less than the supposed 15k count. Please advise if we are missing something with the way the IOTHUBDEVICECLIENT is being used.

![image](https://user-images.githubusercontent.com/66787177/173828008-7eae8325-969f-43a7-8b6a-ce473bf5e38c.png)

**Comment by ericwol-msft** [comment]
Are you hitting you hub quota and throttling limit?

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling

**Comment by jlingaa** [comment]
Definitely not hitting the quota. We are set at S1 tier and 1 Unit with 400000 msgs max per day. As I read the throttling limits, is it true that we couldn't send more than 100 msgs per min with S1 and 1 unit? If that is the case, we were able to send all the 5k messages with 125 ms sleep at the rate of 8 msgs per sec. We should be hitting throttling errors at this rate I assume.

I have not seen any throttling errors thrown. Is this something we should turn on?

**Comment by jlingaa** [comment]
Definitely not hitting the quota limit. We are at S1 tier and 1 Unit. No where close to the 400000 message limit per day with the tests. Looking at the throttling numbers, it says 100 per sec/unit. So 1000ms/100 = 10 ms should be enough sleep to send all the messages. Set the test to sleep for 30 ms and tried to send 1K messages. Still lost 28 messages.

![image](https://user-images.githubusercontent.com/66787177/173955507-1ea8ef0d-55ba-4859-bbc3-8ab3f9dc6c22.png)

**Comment by ericwol-msft** [comment]
What are the dispositions (IOTHUB_CLIENT_CONFIRMATION_RESULT) on the callback?

**Comment by jlingaa** [comment]
All the callbacks received comes with OK. Most of the times we have seen all the callbacks not come back. But whatever callbacks were received were all OK.

**Comment by ericwol-msft** [comment]
You should get callback for every successful call to SendEventAsync().

You can enable IoT SDK tracing via:
```
        bool traceOn = true;
        IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_LOG_TRACE, &traceOn);
```

**Comment by jlingaa** [comment]
All the callbacks are coming back with status OK but the metrics on azure portal for Device to Cloud show less than 100% messages with variable numbers on every attempt. I modified the above test to run on a scheduler every 30 sec to send 100 messages. We haven't lost any messages with this code running it for more than 12 hours. At this point, we are not sure if it is the implementation, load or any other factors like network etc. Really confused how the earlier implementation would lose messages on the iothub. Any insight would be really helpful.

```
struct Adapter {
    device_client: *mut DeviceClientHandle
}

impl Adapter {
    pub fn send(&self, sample_message: &str) {
        send_message(self.device_client, sample_message);
    }
}

unsafe impl Send for Adapter {}

fn send_message(device_client: *mut azure_iot_sdk: DeviceClientHandle, sample_message: &str) {
    let message_handle = message_create_from_byte_array(sample_message.as_bytes()).unwrap();
    set_content_type_system_property(message_handle, "application/json");
    set_content_encoding_system_property(message_handle, "utf-8");

    device_client_send_event_async(device_client, message_handle, service_report_callback).unwrap();
    iot_ub_message_destroy(message_handle);
}

fn main() {

  let sample_message = r#"{
      "name": "hello"
      }"#;
  
  let device_handle = create_device_handle(); // wraps the CreateFromConnectionString api call here.
  set_retry_policy(device_handle, IOTHUB_CLIENT_RETRY_POLICY::IOTHUB_CLIENT_RETRY_EXPONENTIAL_BACKOFF, 1);
  let adapter_mtx = Arc::new(Mutex::new(Adapter { device_client: device_handle}));
  let adapter_mtx = Arc::clone(&adapter_mtx);

  const MESSAGE_COUNT:u32 = 100;
  const SEND_INTERVAL_IN_SECONDS:u32 = 30;
  let mut iteration = 0;
  let mut scheduler = Scheduler::new();
  scheduler.every(SEND_INTERVAL_IN_SECONDS.seconds()).run(move || {
       let mut counter = 1;
       iteration += 1;
       while counter <= MESSAGE_COUNT {
           adapter_mtx.lock().unwrap().send(sample_message);
           thread::sleep(time::Duration::from_millis(20));
           println!("Publishing message count: {}", counter);
           counter += 1;
       }
       println!("{}: Completed Iterations: '{}'. Published '{}' messages", chrono::prelude::Local::now(), iteration, MESSAGE_COUNT)
   });

   loop {
       thread::sleep(time::Duration::from_millis(10));
   }
}

```

**Comment by ericwol-msft** [comment]
RUST code is not useful, since that is a layer we don't support here.

Have you tried to route the messages to storage and see if there are all there? Maybe the UI counter can't keep up with that message load.

**Comment by danewalton** [comment]
Closing for now for inactivity. Please let us know if you would like it reopened.
