### ISSUE TITLE
Option OPTION_DO_WORK_FREQUENCY_IN_MS does not work on PPC

### ISSUE THREAD

**Issue by magdsa** [Azure/azure-iot-sdk-c#2323]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Debian 8 (jessie) ppc
Cross Compiled on Debian 8 (jessie) x86_64 using GCC 4.9.2

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release LTS_01_2022_Ref01 (Commit SHA: 5805fb669ffe2adff021d68c62725d0bd783ac49)

**Protocol**

MQTT Websockets

**Describe the Bug**

Setting the option "do_work_freq_ms" does not work on all architectures. When I try to set it on a PowerPC it always fails, because the value seems to be out of the allowed range from 1 to 100 ms.
In the code the pointer to the value (which is of type tickcounter_ms_t) gets converted into an unsigned int:
https://github.com/Azure/azure-iot-sdk-c/blob/5805fb669ffe2adff021d68c62725d0bd783ac49/iothub_client/src/iothub_client_core.c#L1639-L1656
This conversion does not work on PowerPC.
Is it possible that all conversions of the value in the code above should be conversions like this `*(tickcounter_ms_t*)value`, instead of converting to unsigned int in the check and to tickcounter_ms_t after the check passed?

**[MCVE](https://stackoverflow.com/help/mcve)**

```
#include <assert.h>
#include "azureiot/iothub.h"
#include "azureiot/iothub_client_options.h"
#include "azureiot/iothub_device_client.h"
#include "azureiot/iothubtransportmqtt.h"
#include "azureiot/iothubtransportmqtt_websockets.h"
#include "azure_c_shared_utility/tickcounter.h"

int main(void)
{
    char connectionString[] = "HostName=xxxxxxxxxxxxxxxxx.azure-devices.net;DeviceId=xxxxxxxx;SharedAccessKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
    IoTHub_Init();

    IOTHUB_DEVICE_CLIENT_HANDLE deviceHandle = IoTHubDeviceClient_CreateFromConnectionString(connectionString, MQTT_WebSocket_Protocol);
    assert(deviceHandle != NULL);

    tickcounter_ms_t ms_delay= 10;
    assert(IoTHubDeviceClient_SetOption(deviceHandle, OPTION_DO_WORK_FREQUENCY_IN_MS, &ms_delay) == IOTHUB_CLIENT_OK);

    IoTHubDeviceClient_Destroy(deviceHandle);
    IoTHub_Deinit();
}
```

**Console Logs**

>Error: Time:Mon Jun 20 12:10:09 2022 File:/tmp/azure-iot-sdk-c/iothub_client/src/iothub_client_core.c Func:IoTHubClientCore_SetOption Line:1655 Invalid value: OPTION_DO_WORK_FREQUENCY_IN_MS cannot exceed 100 ms. If you wish to reduce the frequency further, consider using the LL layer.
a.out: main.c:18: int main(): Assertion `IoTHubDeviceClient_SetOption(deviceHandle, OPTION_DO_WORK_FREQUENCY_IN_MS, &ms_delay) == IOTHUB_CLIENT_OK' failed.
Aborted

**Comment by danewalton** [comment]
@magdsa I believe my PR did what you were looking for. Let us know if you have any other questions!

**Comment by magdsa** [comment]
Yes, thank you that helps.
