### ISSUE TITLE
Connection Reset by IOT hub after Client Change Spec 

### ISSUE THREAD

**Issue by nilesh27994** [Azure/azure-iot-sdk-c#2325]
Hi ,

I am using Azure IOT c SDK to connect with IOT hub. I have the connection string validated by the IOT hub using that connection string i am trying to connect with IOT hub but I am getting the error "Connection Reset by Peer" just after client change cipher spec state while handshaking. 
Here i am not able to understand why server sending this reset packet in handshaking. the parameters we are passing is correctly.
so we don't have doubt on parameters side. 

i have captured the logs on wire shark.
![image](https://user-images.githubusercontent.com/82876565/175047341-dc983c5b-9b5a-41a2-95f2-be436018a1d4.png).

please help me to understand this issue , i am expecting quick reply from your side.

Thanks in Advance

**Comment by CIPop** [comment]
@nilesh27994 it's unclear from the wireshark logs alone why this is happening. It is likely either a client-side issue (e.g. wrong credentials, incorrect TLS stack configuration, etc) or some other network appliance is terminating the connection (e.g. your router or security appliance).

1. Please use the "bug" issue template. Example below.
2. In addition, please let us know if you are using any Hardware Security Module / OpenSSL ENGINE, etc.

-----

**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Raspberry Pi, Raspbian Stretch Lite (Release 2018-11-13)
Cross Compiled on Ubuntu 18.04 using GCC 6.3.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2019-01-31

**Protocol**

MQTT

**Describe the Bug**

If MQTT is unable to establish a connection, it will keep trying and once it succeeds queued messages will be sent to the Cloud. However, if for some reason we can't get past the initial connection phase, then SDK does not respect message timeouts. 

**[MCVE](https://stackoverflow.com/help/mcve)**

```
#include "iothub.h"

int main(void)
{
    if (lightbulb == ON) {
        iothub_say_hello();
        return 0;
    } else {
        iothub_say_goodbye();
        return 1;
    }
}
```

**Console Logs**

Sending message 1 to IoTHub
-> 15:07:42 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/tracingDevice/messages/events/property_key=property_value | PACKET_ID: 93 | PAYLOAD_LEN: 12
<- 15:07:42 PUBACK | PACKET_ID: 92
Confirmation callback received for message 86 with result IOTHUB_CLIENT_CONFIRMATION_OK

**Comment by nilesh27994** [comment]
Hi @CIPop ,

We are not using any hardware security chip. and the credential that we received is correct that we have verified.
so we have correct HostName, Device ID , SasToken . so i can say credential are correct.
But we have failed just after few steps completed in handshaking process. 
How TLS stack will affect to reset connection by peer? Can you please explain this part. We have given enough stack size to TLS.
How much stack size required to TLS?

i am attaching more logs here , it will more clear to you.

![image](https://user-images.githubusercontent.com/82876565/175290716-ed5ec59d-39a0-4897-8cf3-8679ddda5b0c.png)

**Comment by CIPop** [comment]
I see you are using C-SDK on FreeRTOS with mbedTLS. We do not support his scenario with this SDK. New designs should use our [Azure SDK for Embedded C](https://github.com/Azure/azure-sdk-for-c), or, in your case, the [FreeRTOS Middleware](https://github.com/Azure/azure-iot-middleware-freertos). A sample is available [here](https://github.com/Azure-Samples/iot-middleware-freertos-samples).

The TLS stack requires very specific configuration (e.g. TLS renegotiation is mandatory) as well as a sufficiently large buffer size for TLS records. There are many aspects that we have tweaked to work with Azure IoT services. Please try our FreeRTOS sample and copy our mbedTLS configuration from there. 

Here is one example of mbedTLS configuration we have successfully tested on a STMicro's L475 dev-board with FreeRTOS coreMQTT: https://github.com/Azure-Samples/iot-middleware-freertos-samples/blob/main/demos/projects/ST/b-l475e-iot01a/config/mbedtls_config.h

These are the Azure IoT Hub TLS requirements with details regarding ciphersuites, : https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-tls-support

You can also try out our C-SDK on Linux with mbedTLS which is something we test. Here are instructions using our repo:
1. Download and compile mbedTLS 2.x from sources (I believe we do not have support for mbedTLS 3.x at this time):
```
cmake /path/to/mbedtls_source
make -j
ctest
sudo make install
```

2. Configure C-SDK to use mbedTLS
```
cd build
cmake ..
ccmake

# In `ccmake` set: 
#use_mbedtls=ON
#use_openssl=OFF
#use_baltimore_cert=ON
#use_sample_trusted_cert=ON
```

Running, for example, the [hub telemetry sample with X509 auth](https://github.com/Azure/azure-iot-sdk-c/tree/main/iothub_client/samples/iothub_ll_client_x509_sample), should work as expected.

**Comment by danewalton** [comment]
Closing for now for inactivity. Please let us know if you would like it reopened.
