### ISSUE TITLE
x509certificate specified, but authentication method is not x509

### ISSUE THREAD

**Issue by ArnasTeltonika** [Azure/azure-iot-sdk-c#2335]
OS: Ubuntu 20
SDK: LTS_01_2022_Ref01

Description of the issue:
Trying to create a DeviceClientHandle for Plug and Play using x509 certificates.

I have created certificates and tried them, they are working well. But when trying to create a device for PnP it fails.

The syslog prints this:
![image](https://user-images.githubusercontent.com/108528295/176893873-42c60c61-4fd8-46f9-b4e6-5554fcd442c1.png)

while azure_iothub prints this
![image](https://user-images.githubusercontent.com/108528295/176894179-9254b0f0-8dba-4a63-abb5-1e1aabbd0bdd.png)

**Comment by ericwol-msft** [comment]
validate your connection string looks like this

static const char* connectionString = "HostName=<host_name>;DeviceId=<device_id>;**x509=true**";

**Comment by ArnasTeltonika** [comment]
I am trying to connect using DPS id scope

**Comment by danewalton** [comment]
Hi @ArnasTeltonika 
Have you modeled your sample [off of this sample here](https://github.com/Azure/azure-iot-sdk-c/blob/main/provisioning_client/samples/prov_dev_client_ll_x509_sample/prov_dev_client_ll_x509_sample.c)?

Specifically, [this part here where it initializes the provisioning client security type as x509](https://github.com/Azure/azure-iot-sdk-c/blob/4814abaedf5d90d6394e7ec314f17530e8d32bdc/provisioning_client/samples/prov_dev_client_ll_x509_sample/prov_dev_client_ll_x509_sample.c#L179)?

**Comment by ArnasTeltonika** [comment]
@danewalton 
I modeled my sample off of PnP sample. Anyway I have found that my problem was with how I was creating provDeviceHandle and IotHubDeviceClient.

**Comment by ArnasTeltonika** [comment]
Yes, everything works now.
