### ISSUE TITLE
Message Tracking ID big Number 1960959496 crash 

### ISSUE THREAD

**Issue by sarangkalbande** [Azure/azure-iot-sdk-c#234]
SDK Version:- 1.1.16
Platform:- Ubuntu 14.04 and Core is ARM Cortex A9
Protocol:- MQTT

# Description of the issue:
Send Confirmation coming with Big Number Tracking ID 1960959496 crash.

Actually, In my application, I have assigned dedicated trackIds to differentiate among messages.
I have never faced this issue with Ethernet or wifi since we used to get ACK very quickly but with cellular connectivity with less signal strength [which is not very reliable and delays confirmation ACK] I started facing this issue like suppose when I send message-1 with track id as 12 and before getting send confirmation ack I sent message-2 with track ID 13 and when connectivity comes up and I get send confirmation ACK's back to back for both the messages then sometimes it comes as huge number as said earlier and crash.

# Code sample exhibiting the issue:
Confirmation[885] received for message tracking id =1960959496 with result = IOTHUB_CLIENT_CONFIRMATION_OK

# Console log of the issue:
Confirmation[885] received for message tracking id =1960959496 with result = IOTHUB_CLIENT_CONFIRMATION_OK
free(): invalid pointer: 0x73d6e430 ***

**Comment by markrad** [comment]
Hi @sarangkalbande,

I'm a little confused by your description. You have placed in the _"Code sample exhibiting the issue:"_ section a line from the console log that looks exactly like the lines that are generated by the samples in the SendConfirmationCallback function. In that function, the confirmation id is extracted from the structure addressed by the userContextCallback argument. This value is **not** coming from the cloud but is stored on the device in an array. If you are getting a value other than one you expect then there is likely a bug in your code since it would suggest that the EVENT_INSTANCE structure instance that contains the confirmation id is being overwritten or prematurely freed.

Please post your code. I will be happy to take a look at it..

_Mark Radbourne MSFT_

**Comment by sarangkalbande** [comment]
@markrad 
I am not sure whats going wrong here.
Please find below my functions 
[1] Send data function
GW_ErrorCode_e CLD_SendDataToCloud ( size_t msgTrackID, const char *msgText, bool flag )
{
	pthread_mutex_lock(&iothandle_mutex);
	
	EVENT_INSTANCE messages;
	GW_ErrorCode_e evErrCode = GW_NO_ERROR;
	
	SCH_StartScheduler ( &gsvManagerCtrlParams.svCldAckSchdulrParam, SCH_SCHEDULER_TYPE_ONESHOT, APP_CldAckCallback, NULL, (45 * GW_CLOCK_SECOND_IN_MILLI), 1 );

	g_continueRunning = true;
	{
		if (iotHubClientHandle  == NULL)
		{
			DEBUG_LOG (ERROR, GW_ERROR,"ERROR: iotHubClientHandle is NULL!\n");
		}
		else
		{
			bool msgSent = false;
			do
			{
				if (!msgSent)
				{
					if ((messages.messageHandle = IoTHubMessage_CreateFromByteArray((const unsigned char*)msgText, strlen(msgText))) == NULL)
					{
						DEBUG_LOG (ERROR, GW_ERROR,"ERROR: iotHubMessageHandle is NULL!\r\n");
					}
					else
					{
						//printf("\nSending JSON MSG=%s\r\n",msgText);
						messages.messageTrackingId = msgTrackID;
						MAP_HANDLE propMap = IoTHubMessage_Properties(messages.messageHandle);
						(void)sprintf_s(propText, sizeof(propText), "PropMsg_%zu", msgTrackID);
						if (Map_AddOrUpdate(propMap, "PropName", propText) != MAP_OK)
						{
							DEBUG_LOG (ERROR, GW_ERROR,"ERROR: Map_AddOrUpdate Failed!\r\n");
						}
						if (IoTHubClient_LL_SendEventAsync(iotHubClientHandle, messages.messageHandle, CLD_SendConfirmationCallback, &messages) != IOTHUB_CLIENT_OK)
						{
							DEBUG_LOG (ERROR, GW_ERROR,"ERROR: IoTHubClient_LL_SendEventAsync..........FAILED!\r\n");
						}
						else
						{
							DEBUG_LOG (DEBUG, GW_DEBUG,"IoTHubClient_LL_SendEventAsync accepted message for transmission to IoT Hub.\r\n");
						}
					}

					msgSent = true;
				}

			} while (g_continueRunning);
		}
	}
	pthread_mutex_unlock(&iothandle_mutex);
	return evErrCode;
} 

[2] Callback function 
static void CLD_SendConfirmationCallback( IOTHUB_CLIENT_CONFIRMATION_RESULT result, void* userContextCallback)
{
	pthread_mutex_lock(&rx_callback_mutex);
	static int noOfNacks = 0;

	EVENT_INSTANCE* eventInstance = (EVENT_INSTANCE*)userContextCallback;
	DEBUG_LOG (DEBUG, GW_DEBUG,"Confirmation [%d] received for message tracking id = %zu with result = %s\r\n", callbackCounter, eventInstance->messageTrackingId, ENUM_TO_STRING(IOTHUB_CLIENT_CONFIRMATION_RESULT, result));
	callbackCounter++;
	g_continueRunning = false;

	if (gsvManagerCtrlParams.svCldAckSchdulrParam.evSchedulerStatus == SCH_SCHEDULER_STATUS_RUNNING)
	{
		if( SCH_AbortScheduler(&gsvManagerCtrlParams.svCldAckSchdulrParam) == GW_NO_ERROR)
		{
			DEBUG_LOG (DEBUG, GW_DEBUG,"Cloud Send ACK Received,Stop Scheduler");
		}
	}
if(((eventInstance->messageTrackingId >=5) && (eventInstance->messageTrackingId <=25)) ||
			(eventInstance->messageTrackingId ==2))
	{

		struct local{
			size_t mesTrackingId;
		};
		struct local *Local=NULL;

		Local=calloc(1,sizeof(struct local));

		/*** Take only track ID and Ignore and free message handle here only **/
		Local->mesTrackingId = eventInstance->messageTrackingId;
		GW_MessageStruct_s	asvSendEventMsg;
		asvSendEventMsg.evMessageType = GW_REQUEST_TYPE_EVENT;
		asvSendEventMsg.ui32Message = NMC_SW_EVT_CLOUD_SEND_CONFIRMATION;
		asvSendEventMsg.uvMessageData.p_vData = Local;
		COM_SendMainQMessage ( &asvSendEventMsg );
		DEBUG_LOG(DEBUG, GW_DEBUG, "Address of sent callback a=%x", Local);
	}
	if(eventInstance->messageHandle != NULL)
	{
		IoTHubMessage_Destroy(eventInstance->messageHandle);
	}

	pthread_mutex_unlock(&rx_callback_mutex);
}

**Comment by markrad** [comment]
Hi @sarangkalbande,

Unless I'm mistaken, your send message to cloud function is going to be in a hard loop until g_continueRunning is false. Without any type of yield or wait this will pin your CPU for its entire timeslice. I'm assuming this is running on a thread and when it is running pretty much nothing else is going to happen.

You don't need to wait for an ack before sending another message however, since you are using the low level (LL) functions, you must call IoTHubClient_LL_DoWork or you will not send or receive messages.

The IoT Hub array size is an implementation detail. It is up to you how big it is or even if you use it at all. It is in the sample simply for demonstration purposes. It is not required. 

One other note, you can call IoTHubMessage_Destroy on the message as soon as you have sent it. You do not need to wait for the ack. The SDK copies the message.

_Mark Radbourne MSFT_

**Comment by sarangkalbande** [comment]
Hi @markrad ,
Thanks for the details.
Now I am destroying the message as soon as its given to the SDK send function.
Now I have another issue suppose when I send 4-5 messages without waiting for the confirmation 
Note :- Because of the cellular latency I wont get confirmations quickly. 
lets suppose 4 messages sent with tracking IDs as 1 to 4 but when I get send confirmations after some time for the 4 messages I get Tracking id as always 4 for all the 4 messages.
Any idea whats going on wrong here?
Also I have below questions
[1] On my device I have 3 interfaces wifi,ethernet and cellular,out of these 3 interfaces if any interface goes down I will switch to another interface which has connectivity available,In this scenario I am recreating IOT handle again.
How to handle this scenario better than this?
I think when I have sent 4 messages over cellular and if cellular is down I will switch over to wifi and reset connection IOT handle what will happen in this case?

**Comment by markrad** [comment]
Hi @sarangkalbande,

You will need to post code in order for me to make any kind of comment on why your message id appears incorrect.

Regarding your second question, if you gracefully clean up the IoT hub connection, then your callback function will be notified of any messages that were waiting to be sent thus you can figure out what was sent and what was not. Create a new connection with the replacement interface and resend any messages not sent before if necessary. You'll have to cache the messages though. On a small device, caching messages can quickly eat into your RAM. If it is not critical to send every message then I would recommend you just drop them.

**Comment by markrad** [comment]
Hi  @sarangkalbande,

If you are still encountering this problem please feel free to reopen this issue. For now though I am closing it because you have not responded.

_Mark Radbourne MSFT_
