### ISSUE TITLE
Failed to build **azure-iot**  umqtt

### ISSUE THREAD

**Issue by jiapei100** [Azure/azure-iot-sdk-c#2340]
Details can be found at [https://github.com/Azure/azure-umqtt-c/issues/140](https://github.com/Azure/azure-umqtt-c/issues/140)

My current pastebin result is: [https://pastebin.com/GQc495NR](https://pastebin.com/GQc495NR) .

**Comment by ericwol-msft** [comment]
You should enable pre-processor output and see if there are issues with the macro expansion.

**Comment by ewertons** [comment]
@jiapei100 , please provide the details mentioned in the original github issue you filed.
This issue will be closed, as it is a duplicate.

**Comment by danewalton** [comment]
Closing for now. Please let us know if you would like it reopened or open another issue if you have other questions.
