### ISSUE TITLE
IoTHubDeviceClient_Destroy hangs while IoTHubDeviceClient_UploadMultipleBlocksToBlobAsync is in progress

### ISSUE THREAD

**Issue by zptak-ics** [Azure/azure-iot-sdk-c#2343]
**Development Machine**

PC: Archlinux 20.07.2022
GCC version 12.1.0

**SDK Version**

Release LTS_07_2022_Ref01 

**Protocol**

MQTT over Websockets

**Description**

IoTHubDeviceClient_Destroy hangs while IoTHubDeviceClient_UploadMultipleBlocksToBlobAsync is in progress and there is broken internet connection.

**Comment by zptak-ics** [comment]
All is called from the main thread.

**Comment by ericwol-msft** [comment]
Thanks for the additional info, please kindly provide the information I asked above.

**Comment by zptak-ics** [comment]
Adding option OPTION_BLOB_UPLOAD_TIMEOUT_SECS looks like helps.

Here is a loop which cause lock for me.

```
        /*wait for all uploading threads to finish*/
        while (singlylinkedlist_get_head_item(iotHubClientInstance->httpWorkerThreadInfoList) != NULL)
        {
            // Sleep between runs of the garbage collector in order to give the httpWorker threads time to execute.
            // Otherwise we end up in a spin loop here.
            unsigned int sleeptime_in_ms = (unsigned int)iotHubClientInstance->do_work_freq_ms;
            Unlock(iotHubClientInstance->LockHandle);

            ThreadAPI_Sleep(sleeptime_in_ms);

            if (Lock(iotHubClientInstance->LockHandle) != LOCK_OK)
            {
                LogError("unable to Lock - - will still proceed to try to end the thread without locking");
            }

            garbageCollectorImpl(iotHubClientInstance);
        }
```

**Comment by ericwol-msft** [comment]
Thanks, will investigate.

**Comment by ericwol-msft** [comment]
IoTHubDeviceClient_Destroy() will block, by design, if there is an blob upload operation in progress, until the operation is completed successfully or fails. Your application can choose to about the operation in the callback, if required.

In your case, _I assume you are using CURL_, the blocking timeout is happening in CURL. Setting OPTION_BLOB_UPLOAD_TIMEOUT_SECS calls into CURL set option via `curl_easy_setopt(httpHandleData->curl, CURLOPT_TIMEOUT_MS, httpHandleData->timeout)` at [source](https://github.com/Azure/azure-c-shared-utility/blob/a573357197179356543c74836fe943c4864c94ba/adapters/httpapi_curl.c#L432).

**Comment by zptak-ics** [comment]
> Your application can choose to about the operation in the callback, if required.
If it's blocked, then I can not do it;-/

> IoTHubDeviceClient_Destroy() will block, by design
Ok, but then I'm locked.
Hmmm, so this is different behavior then sending message, because I can get: IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY.
Would be good to have the same for uploading files, instead of using OPTION_BLOB_UPLOAD_TIMEOUT_SECS.

Thank you for clarification.

**Comment by ericwol-msft** [comment]
> Hmmm, so this is different behavior then sending message, because I can get: IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY.
> Would be good to have the same for uploading files, instead of using OPTION_BLOB_UPLOAD_TIMEOUT_SECS

CURL is blocking inside curl_easy_perform() and CURLOPT_XFERINFOFUNCTION does not get called during this. If you have any suggestion on aborting the curl_easy_perform() in CURL we can look into it. I know this topic and feature ask has been posted multiple times as a CURL feature request.
