### ISSUE TITLE
List of dependencies with versions

### ISSUE THREAD

**Issue by FinitelyFailed** [Azure/azure-iot-sdk-c#2352]
Hi,

I recently tried to crosscompile a project which uses azure-iot-sdk-c for a ARM-based platform. I have a sysroot-folder with libs etc. from that platform. However it seems like the version of libcurl was to old for azure-iot-sdk-c to build. So now I'm wondering how do I know which versions of the dependencies are required to make it possible to compile azure-iot-sdk-c?

I found that I should I theses libs (from https://github.com/Azure/azure-iot-sdk-c/blob/de09b35289313665f0d359835c661f8cb2a0fdf1/doc/SDK_cross_compile_example.md), but it doesn't tell me which versions:
- curl
- build-essential
- pkg-config
- libcurl4-openssl-dev
- git
- cmake
- libssl-dev
- uuid-dev
- valgrind

**Comment by ericwol-msft** [comment]
We test against the latest release of the platform (ex, Ubuntu 18.04/Ubuntu 20.04) packages.

https://github.com/Azure/azure-iot-sdk-c/pull/2348/checks

**Comment by ericwol-msft** [comment]
closing this issue

**Comment by FinitelyFailed** [comment]
Thanks, however that doesn't tell me much about the minimum version of the libs.
Can I see which versions of the libs are used in the tests? As far as I can see the only info available is which platforms are tested. But a platform such as Ubuntu 20.04 should still get some security updates etc.?

I want to be able to send a list of libs and their versions needed to run and build azure-iot-sdk-c to a hardware manufacturer.

**Comment by ericwol-msft** [comment]
These are external components and we don't control when they are updated, so the versions can change at anytime. It's your responsibility to validate your application against the versions that you are shipping for that platform, including any security updates that may occur.
