### ISSUE TITLE
Add Arduino example for connection ESP8266 to Arduino IoT Hub via X509 CA-signed certificate

### ISSUE THREAD

**Issue by Vitomir2** [Azure/azure-iot-sdk-c#2354]
I currently find it quite hard to understand fully the documentation of the library, thus, I am not able to make Arduino sample that will authenticate the device to Azure IoT Hub via X509 CA-signed certificate. It will be quite useful to have such a sample pre-defined, similar as the one connected with the symmetric key options (connection string).

**Comment by danewalton** [comment]
Hi @Vitomir2 
The library for Arduino and ESP8266 is currently deprecated for this repository. Going forward, we are directing users to this repo here which uses our new embedded C SDK:

https://github.com/Azure/azure-sdk-for-c-arduino

Please take a look and direct any questions you have on that repository to the source code repo here: https://github.com/azure/azure-sdk-for-c

**Comment by Vitomir2** [comment]
Hi @danewalton ,

Thanks a lot for the quick reply!

On the other repository they stated to open issues in here if we need something. I see that there is a support for X509 certificates, but I do not see samples how to use this and cannot figure that out already for a week. This is the reason I request such a sample, because it will be much easier for me and the other people that want to use the library that way.

BR,
Vitomir

**Comment by danewalton** [comment]
Ahh I see. The link on that repo goes to the `azure-sdk-for-c`

![image](https://user-images.githubusercontent.com/36710865/186024596-d7240df5-a27a-4950-9d3f-c49e32016e61.png)

This repo is the `azure-iot-sdk-c`. I will admit, they are very similar names.

That being said, now that I think about it, I believe you are right in that we do not have support for certificate authentication for the ESP8266, but we do for the ESP32. If you would like, please open an issue on the `azure-sdk-for-c` [here](https://github.com/Azure/azure-sdk-for-c/issues/new?assignees=&labels=&template=feature_request.md&title=) requesting the feature.

**Comment by Vitomir2** [comment]
Thanks for the replies @danewalton . I really appreciate it!
