### ISSUE TITLE
IoTHubMessage_SetProperty error should cause e2e tests to fail 

### ISSUE THREAD

**Issue by ewertons** [Azure/azure-iot-sdk-c#2360]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Any.

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Main branch (dc6b1bc84aa502d371371ffc1cc144fcd571bf5f)

**Protocol**

Any (AMQP/MQTT/HTTP). This issue relates to e2e test framework.

**Describe the Bug**

This bug is being filed on behalf of @jspaith, from comment in PR https://github.com/Azure/azure-iot-sdk-c/pull/2359#discussion_r957610475 :

I get this is pre-existing condition, but... shouldn't a `IoTHubMessage_SetProperty` cause an ASSERT_FAIL.  It suggets something is really wrong if something this basic fails and also later in test we'll see if these are set and fail there if not.  I'd rather stop test at root problem.

**Comment by RLeclair** [comment]
Completed PR which addresses issue.
