### ISSUE TITLE
Failure to build libmsr_riot.so

### ISSUE THREAD

**Issue by dangerousHobo** [Azure/azure-iot-sdk-c#2361]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**
Host: Ubuntu 20.04
Target: Buildroot ARM
Cross Compiler: GCC 7.4.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release LTS_07_2022_Ref01

**Protocol**

MQTT

**Describe the Bug**

I'm attempting to update from LTS_07_2021_Ref01 and it's failing to build the libmsr_riot.so archive. Previously with LTS_07_2021_Ref01 this was created under `provisioning_client/deps/libmsr_riot.so`. 

**Console Logs**

https://gist.github.com/dangerousHobo/c63623efb91e823adea61bd9bf7f2cde

**Comment by danewalton** [comment]
Hi @dangerousHobo 
Can you try adding `-Dhsm_type_riot=ON -Dhsm_type_x509=OFF` to your cmake command?

**Comment by dangerousHobo** [comment]
Hi @danewalton 
I've made the change and now get an error about libparson.so
https://gist.github.com/dangerousHobo/f69c9d09aabd6333a7017126ed07bb35

**Comment by dangerousHobo** [comment]
Looks like the location of libparson.so had changed. Was able to resolve the error after collection the path (deps/parson/libparson.so).
