### ISSUE TITLE
Provisioning fails with error code :401002 - "Unauthorized access"

### ISSUE THREAD

**Issue by BinduRao2018** [Azure/azure-iot-sdk-c#2362]
Release version used: LTS_07_2022_Ref01
System: Ubuntu - 20.04

I have been using the certificates & created group enrollment as described here: https://github.com/Azure/azure-iot-sdk-c/blob/LTS_07_2022_Ref01/tools/CACertificates/CACertificateOverview.md

These were working fine, until recently. However, the provisioning has started to fail with the following error:
[iot-0-0:1662378017238836:console:Debug] Provisioning Status - PROV_DEVICE_REG_STATUS_CONNECTED
[iot-0-0:1662378017639738:console:Debug] Provisioning Status - PROV_DEVICE_REG_STATUS_ASSIGNING
Error: Time:Mon Sep  5 12:40:20 2022 File:/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:prov_transport_process_json_reply Line:658 Provisioning Failure: OperationId: 4.5a514dd79b3cfd8c.4c240f23-a3a7-4ed5-ae73-56680b9ced72 - Date: 2022-09-05T11:40:18.2090058Z - Msg: {"Message":"{\"errorCode\":401002,\"message\":\"Unauthorized access\",\"trackingId\":\"EEC3FA1F7928480391CDF3FE09366AE9-G2:-TimeStamp:2022-09-05T11:40:18.035277889+00:00\",\"timestampUtc\":\"2022-09-05T11:40:18.035277889+00:00\",\"info\":null}","ExceptionMessage":""}
Error: Time:Mon Sep  5 12:40:20 2022 File:/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:prov_transport_common_mqtt_dowork Line:979 Unable to process registration reply.
Error: Time:Mon Sep  5 12:40:20 2022 File:/home/bindu/workbench/Azuresphere/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:770 Failure retrieving data from the provisioning service
[iot-0-0:1662378020545579:console:WARN] Registration Failure - PROV_DEVICE_RESULT_DEV_AUTH_ERROR

Please note, that I have tried to set the date & time using ntpdate, however still see the same issue.
This problem is also seen using the earlier LTS version - LTS_01_2022_Ref01

Has something changed recently? Provisioning worked fine until recently with the same set of certificates.

Additional info: Use the intermediate certificate to enrol in DPS and pass full-chain and private key.

**Comment by BinduRao2018** [comment]
Update:
I regenerated the certificates using the script and .cnf with the instructions as described in azure-iot-sdk-c/blob/LTS_07_2022_Ref01/tools/CACertificates/CACertificateOverview.md and get the following error:

Registration Failure - PROV_DEVICE_RESULT_TRANSPORT
[iot-0-0:1662463007586915:console:Debug] Provisioning Status - PROV_DEVICE_REG_STATUS_CONNECTED
Error: Time:Tue Sep  6 12:16:51 2022 File:/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Tue Sep  6 12:16:51 2022 File:/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:777 Failure retrieving data from the provisioning service
Error: Time:Tue Sep  6 12:16:51 2022 File:/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:387 Failure sending control packet data
Error: Time:Tue Sep  6 12:16:51 2022 File:/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1343 Error: mqtt_client_disconnect send failed
...
...

**Comment by ericwol-msft** [comment]
You can get more detail logs by enabling the log trace option.

```
bool traceOn = true;
Prov_Device_LL_SetOption(user_ctx.handle, PROV_OPTION_LOG_TRACE, &traceOn);
```

**Comment by BinduRao2018** [comment]
With the trace on, here is the log:

-> 13:08:51 CONNECT | VER: 4 | KEEPALIVE: 0 | FLAGS: 130 | USERNAME: 0ne0017479D/registrations/device-01/api-version=2019-03-31&ClientVersion=1.9.0 | CLEAN: 1
<- 13:08:51 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0
-> 13:08:51 SUBSCRIBE | PACKET_ID: 1 | TOPIC_NAME: $dps/registrations/res/# | QOS: 1
[iot-0-1:1662725331460669:console:Debug] Provisioning Status - PROV_DEVICE_REG_STATUS_CONNECTED
<- 13:08:51 SUBACK | PACKET_ID: 1 | RETURN_CODE: 1
-> 13:08:51 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/PUT/iotdps-register/?$rid=1 | PAYLOAD_LEN: 30
<- 13:08:51 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: $dps/registrations/res/401/?$rid=1 | PACKET_ID: 2 | PAYLOAD_LEN: 185
-> 13:08:51 PUBACK | PACKET_ID: 2
Error: Time:Fri Sep  9 13:08:51 2022 File:/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Fri Sep  9 13:08:51 2022 File:/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:777 Failure retrieving data from the provisioning service
Error: Time:Fri Sep  9 13:08:51 2022 File:/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:387 Failure sending control packet data
Error: Time:Fri Sep  9 13:08:51 2022 File:/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1343 Error: mqtt_client_disconnect send failed
[iot-0-1:1662725331764247:console:WARN] Registration Failure - PROV_DEVICE_RESULT_TRANSPORT

**Comment by ericwol-msft** [comment]
401 is an auth error. The DPS logs shows the error is because of this: 

`$X.509 client certificate common name and RegistrationId should match.`

**Comment by BinduRao2018** [comment]
Could you elaborate, please? Where/how should this registration ID be set? Has something changed recently w.r.t this? I have created the device certificate as described in 'IoT Leaf Device' section in https://github.com/Azure/azure-iot-sdk-c/blob/LTS_07_2022_Ref01/tools/CACertificates/CACertificateOverview.md, where CN is set to device-name

**Comment by ericwol-msft** [comment]
The registration ID can be set by this SDK API call. Prov_Device_SetOption(prov_device_handle, PROV_REGISTRATION_ID, "[REGISTRATION ID]");

Additionally, you can request customer support assistance by creating a "New Support Request" in the Azure portal and they can assist you with any DSP service related issues.

**Comment by BinduRao2018** [comment]
Thanks for the info.
Please note, that I call 'Prov_Device_LL_Register_Device' which gets the registration Id (common_name) by calling custom_hsm_get_common_name. Has something changed in DPS recently?

**Comment by ericwol-msft** [comment]
> Has something changed in DPS recently?

I don't know. You would need to create a Support Request for the DPS service.

**Comment by ericwol-msft** [comment]
> Do RSA-based certificates work

Yes

You can try EC. 

Many TLS stacks are sensitive to cert size (usually 4k) and your RSA can exceed this. You need to validate these requirements on your device.

**Comment by BinduRao2018** [comment]
In certGen.sh available in the repository Or the link https://docs.microsoft.com/en-us/azure/iot-dps/tutorial-custom-hsm-enrollment-group-x509?tabs=linux#create-an-x509-certificate-chain used to generate certificates, mention the CN set to 'Azure IoT Hub CA Cert Test Only' for root certificate and 'Azure IoT Hub Intermediate Cert Test Only'  for the intermediate certificate respectively. However, in case #2270, as mentioned by @danewalton, the registration ID corresponds to the common name(registration ID) used. 
Could you clarify this, as I am using it for testing only?

In addition, let me know if certGen.sh is available for algorithm EC that I could use.

**Comment by danewalton** [comment]
Yes the CN for the device cert would have to match the registration ID. [Link to the relevant section of the docs you linked](https://docs.microsoft.com/en-us/azure/iot-dps/tutorial-custom-hsm-enrollment-group-x509?tabs=linux#create-the-device-certificates). 

![image](https://user-images.githubusercontent.com/36710865/190453668-71c03fe5-058e-4e4b-81a9-13eb06139d02.png)


The root and intermediate do not have the same requirement as they are part of the chain.

**Comment by BinduRao2018** [comment]
Thanks for the clarification, @danewalton

**Comment by danewalton** [comment]
@BinduRao2018 and just to double check...you did upload the root cert as well correct?

In this section here:

![image](https://user-images.githubusercontent.com/36710865/190522985-1125d5ed-a106-4978-9823-d3acbebcceb8.png)

**Comment by BinduRao2018** [comment]
@danewalton, Yes I have uploaded the root certificate in DPS/Certificates and used the intermediate certificate to create a group enrollment.

As suggested, I tried to pass the device certificate instead of full-chain but still see the same problem 

-> 11:46:11 CONNECT | VER: 4 | KEEPALIVE: 0 | FLAGS: 130 | USERNAME: 0ne0017479D/registrations/device-01/api-version=2019-03-31&ClientVersion=1.9.0 | CLEAN: 1
<- 11:46:11 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0
-> 11:46:11 SUBSCRIBE | PACKET_ID: 1 | TOPIC_NAME: $dps/registrations/res/# | QOS: 1
[iot-0-0:1663325171208149:console:Debug] Provisioning Status - PROV_DEVICE_REG_STATUS_CONNECTED
<- 11:46:11 SUBACK | PACKET_ID: 1 | RETURN_CODE: 1
-> 11:46:11 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/PUT/iotdps-register/?$rid=1 | PAYLOAD_LEN: 30
<- 11:46:11 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: $dps/registrations/res/401/?$rid=1 | PACKET_ID: 2 | PAYLOAD_LEN: 185
-> 11:46:11 PUBACK | PACKET_ID: 2
Error: Time:Fri Sep 16 11:46:11 2022 File:/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Fri Sep 16 11:46:11 2022 File:/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:777 Failure retrieving data from the provisioning service
Error: Time:Fri Sep 16 11:46:11 2022 File:/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:387 Failure sending control packet data
Error: Time:Fri Sep 16 11:46:11 2022 File:/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1343 Error: mqtt_client_disconnect send failed
[iot-0-0:1663325171511741:console:WARN] Registration Failure - PROV_DEVICE_RESULT_TRANSPORT

Please note, that the certificates are generated using certGen.sh available in the repository that uses the RSA algorithm.

**Comment by BinduRao2018** [comment]
Any feedback on this, please?

**Comment by ericwol-msft** [comment]
> You would need to create a Support Request for the DPS service.

The ask above was to create a Support Request against the Azure DPS service team. This forum is not a support for specific service issues.

**Comment by danewalton** [comment]
Closing this issue for now due to inactivity. If you would like it reopened, please let us know. For any other questions, please open another Github issue.
