### ISSUE TITLE
IOT Azure SDK NO_CONNECTION_ERROR - DPS 

### ISSUE THREAD

**Issue by akramIOT** [Azure/azure-iot-sdk-c#2369]
------------------------------- delete below -------------------------------

INSTRUCTIONS
==========

Please follow the instructions and template below to save us time requesting additional information from you.

1. Search existing issues to avoid creating duplicates.

o  EI  Software is sending the  data  to  MSFT  Azure  IOT  Hub.  As per  agreement  from our  end  customer  to  debug /analyze this  software issue  I have  shared  this  subscription ID  with   you. Cisco  IOT/We  own this entire  solution as  a whole for the  customer  for any  software  engineering caveats.  What is  MSFT’s  Azure  process  to  handle  such  engineering +  Support   engagements  on the  Azure  IOT  -C  SDK  issues (Server side)   ?

[https://developer.cisco.com/codeexchange/github/repo/akramIOT/Cisco_Edge_Intelligence/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.cisco.com%2Fcodeexchange%2Fgithub%2Frepo%2FakramIOT%2FCisco_Edge_Intelligence%2F%23edit&data=05%7C01%7Csupportmail9%40microsoft.com%7C787686ccaf164c64ec6e08da95ab97fd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986861483112428%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0AxOu3pUfujOS7Kz67UDPLmnoVgY2crPvl8orSmE4aQ%3D&reserved=0)   -   PFI  the  implementation   architecture  from  Cisco  EI  Software  to  MSFT  Azure  IOT  Hub for  your  reference

3. If possible test using the latest release to make sure your issues has not already been fixed: 
https://github.com/Azure/azure-iot-sdk-c/releases/latest 
A: Yes 

4. Do not share information from your Azure subscription here (connection strings, service names (IoT Hub name, Device Provisioning Service scope ID), etc...). If you need to share any of this information, you can create a ticket and get assistance from the Microsoft Support.

How to Submit an Azure Support Ticket: https://docs.microsoft.com/azure/azure-supportability/how-to-create-azure-support-request
A: Done, 

Support request ID | 2208310010002839
-- | --

5. Include enough information for us to address the bug:

   -  A detailed description.
   -  A Minimal Complete Reproducible Example (https://stackoverflow.com/help/mcve). This is code we can cut and paste into a readily available sample and run, or a link to a project you've written that we can compile to reproduce the bug. 
   -  Console logs. If you are unsure how to enable logging, refer to this document: https://github.com/Azure/azure-iot-sdk-c/blob/main/doc/Iothub_sdk_options.md
A: Kindly  refer  this  link for architecture   
[https://developer.cisco.com/codeexchange/github/repo/akramIOT/Cisco_Edge_Intelligence/]

6. Delete these instructions before submitting the bug.

Below is a hypothetical bug report. We recommend you use it as a template and replace the information below each header with your own. 

------------------------------- delete above -------------------------------
I am using  Azure  IOT  Hub for  ingesting  the  data  and  we  are  using  the  Azure  C SDK  (client) running on Cisco’s  IOT  gateways  (hardware platforms).

Use this  below  link for   reference   [https://developer.cisco.com/codeexchange/github/repo/akramIOT/Cisco_Edge_Intelligence/#edit](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.cisco.com%2Fcodeexchange%2Fgithub%2Frepo%2FakramIOT%2FCisco_Edge_Intelligence%2F%23edit&data=05%7C01%7Csupportmail9%40microsoft.com%7C787686ccaf164c64ec6e08da95ab97fd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986861483112428%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0AxOu3pUfujOS7Kz67UDPLmnoVgY2crPvl8orSmE4aQ%3D&reserved=0)

 

[https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_07_2022_Ref01](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-iot-sdk-c%2Freleases%2Ftag%2FLTS_07_2022_Ref01&data=05%7C01%7Csupportmail9%40microsoft.com%7C787686ccaf164c64ec6e08da95ab97fd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637986861483112428%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Fd4oOSv7z138a1ymQCsXmbiPMXjN69t5Btxdma1aiRQ%3D&reserved=0)  - This  SDK is being  used.

1. We ran a monitoring script which does trace route and netstat on azure endpoint every 1s
		Azure sdk disconnects frequently and the connection is not stable where you can see most of the time in SYNC_SENT state

	2.	Enabled Azure SDK debug logs which also indicates frequent DISCONNECT. When it reconnects, burst of messages are sent
		which in-turn causes more instability

 time::Wed Aug 17 07:30:42 UTC 2022
     nslookup_op: 
     Server:        10.8.73.17
    Address:    10.8.73.17:53

    Non-authoritative answer:
    DevIOTHub01.azure-devices.net    canonical name = ihsu-westeurope-6.westeurope.cloudapp.azure.com
    Name:    ihsu-westeurope-6.westeurope.cloudapp.azure.com
    Address: 40.113.176.174

    Non-authoritative answer:
    DevIOTHub01.azure-devices.net    canonical name = ihsu-westeurope-6.westeurope.cloudapp.azure.com
     azure_ip: 40.113.176.174netstat: showing only processes with your user ID

     netstat op: 
     tcp        0      0 127.0.0.1:56166         127.0.0.1:8484          ESTABLISHED 29393/dslink-cpp-az
    tcp        0      1 10.8.73.18:37580        40.113.176.174:8883     SYN_SENT    29393/dslink-cpp-az

-> 07:29:55 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/P36Q_PLC02/messages/events/%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 138 | PAYLOAD_LEN: 578
-> 07:29:56 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/P36Q_PLC02/messages/events/%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 78 | PAYLOAD_LEN: 590
-> 07:29:56 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/P36Q_PLC02/messages/events/%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 139 | PAYLOAD_LEN: 636
-> 07:29:57 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/P36Q_PLC02/messages/events/%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 79 | PAYLOAD_LEN: 373
-> 07:29:57 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/P36Q_PLC02/messages/events/%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 140 | PAYLOAD_LEN: 554
-> 07:29:58 DISCONNECT
[2022-08-17 07:29:58.526645] WARNING SDK(1021): Error/time-out on IoTHub client confirmation - Dropping message. Delivery failed due to time-out.
 
==============================================================

**Comment by ericwol-msft** [comment]
@akramIOT this is not a service support form and we don't have the tools to assist you on resolving your stated issue. Please continue to work with your Support Engineer on the Support Request ((2208310010002839) that you created above. Thanks
