### ISSUE TITLE
Broken README.md link

### ISSUE THREAD

**Issue by jamesadevine** [Azure/azure-iot-sdk-c#2379]
Hiya,

The following link is broken in the README:

```
The API reference documentation for the C SDKs can be found [here](https://docs.microsoft.com/azure/iot-hub/iot-c-sdk-ref/).
```

Is the reference now this repository?

**Comment by ericwol-msft** [comment]
Yes, I will update the link.

**Comment by ericwol-msft** [comment]
#2381

**Comment by jamesadevine** [comment]
@ericwol-msft Thanks so much!

Just to let you know, all the learn links are broken too! E.g. all the bing hits are broken: https://learn.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-device-client-ll-h/iothubdeviceclient-ll-setdevicetwincallback

Is there a way to set up a redirect?

**Comment by ericwol-msft** [comment]
I'll look into it.
