### ISSUE TITLE
Make the ubuntu thingy compile ...

### ISSUE THREAD

**Issue by fschwarzer** [Azure/azure-iot-sdk-c#24]
The ubuntu setup did not work for me. I had to edit the CMake file to find `pow` and `azure_c_shared_utility/lock.h`.

```
diff --git a/iothub_client/samples/iothub_client_sample_mqtt/linux/CMakeLists.txt b/iothub_client/samples/iothub_client_sample_mqtt/linu
index eaf8ac9..3cf08b1 100644
--- a/iothub_client/samples/iothub_client_sample_mqtt/linux/CMakeLists.txt
+++ b/iothub_client/samples/iothub_client_sample_mqtt/linux/CMakeLists.txt
@@ -8,7 +8,7 @@ if(WIN32)
     message(FATAL_ERROR "This CMake file is only support Linux builds!")
 endif()
 
-set(AZUREIOT_INC_FOLDER ".." "/usr/include/azureiot")
+set(AZUREIOT_INC_FOLDER ".." "/usr/include/azureiot"  "/usr/include/azureiot/inc")
 
 include_directories(${AZUREIOT_INC_FOLDER})
 
@@ -31,4 +31,5 @@ target_link_libraries(iothub_client_sample_mqtt
     curl
     ssl
     crypto
+    m
 )
```

**Comment by anporumb** [comment]
Hello @fschwarzer 

Thank you for your report. What was your Ubuntu version? (lsb_release -a) will tell you that information. 

Best Regards,
Andrei Porumb

**Comment by fschwarzer** [comment]
Thanks for your answer.
It's 16.04.
I can tell you more once I am back at work tomorrow.

**Comment by fschwarzer** [comment]
More complete:
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

**Comment by anporumb** [comment]
Thank you very much for your answer. I will look into this. Realistically, expect another answer from me next week, by Wednesday.

Best Regards,
Andrei Porumb

**Comment by fschwarzer** [comment]
Thanks. If you need more info, please ask. :)

**Comment by anporumb** [comment]
We will take this in shortly. Thank you! When that is done, I will close this issue.

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
hello @fschwarzer ,

We've checked in to master branch changes for this issue. 

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Published.

**Comment by fschwarzer** [comment]
Thanks. :)
