### ISSUE TITLE
Provisioning error IotHubUnauthorizedAccess using sample programs

### ISSUE THREAD

**Issue by domasgim** [Azure/azure-iot-sdk-c#2404]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

OS - Ubuntu 22.04.1 LTS
SDK version - `LTS_01_2022_Ref01` / `main` branch (commit `285bfc9cafd5807cf74c220ba5afb15492357bc8`)

**Protocol**

MQTT

**Describe the Bug**

Simmilar issue to https://github.com/Azure/azure-iot-sdk-c/issues/2270. I cannot connect to device provisioning service, tried to create certificates both by following the instructions here on github https://github.com/Azure/azure-iot-sdk-c/blob/main/tools/CACertificates/CACertificateOverview.md and by following Dane's answer on the previous issue which seemed to resolve the issue (https://github.com/Azure/azure-iot-sdk-c/issues/2270#issuecomment-1091749124) as well as following tutorials on https://learn.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509?tabs=linux&pivots=programming-language-ansi-c. I have verified my certificates but it seems maybe I am missing a step somewhere.  

I have spoken to the author of the aforementioned issue who had the old certificates which worked for him previously and it appears that he failed to provision his device yesterday as well even though they are not expired.  

I am using `prov_dev_client_ll_x509_sample` and modified `id_scope`, `registration_id`, `x509certificate` and `x509privatekey`.  
I have tried building the project with no additional cmake options, then tried to add flags such as
```
~/azure_c_sdk_latest/cmake$ cmake -Duse_prov_client:BOOL=ON ..
~/azure_c_sdk_latest/cmake$ cmake -Duse_sample_trusted_cert=ON ..
```
without any success.  

**Console Logs**

```
Provisioning API Version: 1.10.0
Iothub API Version: 1.10.0
-> 08:25:11 CONNECT | VER: 4 | KEEPALIVE: 0 | FLAGS: 130 | USERNAME: 0ne004DC640/registrations/dominyko5/api-version=2019-03-31&ClientVersion=1.10.0 | CLEAN: 1
<- 08:25:11 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0
-> 08:25:11 SUBSCRIBE | PACKET_ID: 1 | TOPIC_NAME: $dps/registrations/res/# | QOS: 1
Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
<- 08:25:11 SUBACK | PACKET_ID: 1 | RETURN_CODE: 1
-> 08:25:11 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/PUT/iotdps-register/?$rid=1 | PAYLOAD_LEN: 30
<- 08:25:11 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: $dps/registrations/res/202/?$rid=1&retry-after=3 | PACKET_ID: 2 | PAYLOAD_LEN: 94
-> 08:25:11 PUBACK | PACKET_ID: 2
Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
-> 08:25:14 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $dps/registrations/GET/iotdps-get-operationstatus/?$rid=2&operationId=5.a985effc98b3f40f.63938115-6f85-47e2-a304-bbe74d321ff7 | PAYLOAD_LEN: 30
<- 08:25:14 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: $dps/registrations/res/200/?$rid=2 | PACKET_ID: 2 | PAYLOAD_LEN: 536
-> 08:25:14 PUBACK | PACKET_ID: 2
Error: Time:Wed Nov 16 08:25:14 2022 File:/home/net-gimzunasdo/azure_c_sdk_latest/provisioning_client/src/prov_device_ll_client.c Func:prov_transport_process_json_reply Line:665 Provisioning Failure: OperationId: 5.a985effc98b3f40f.63938115-6f85-47e2-a304-bbe74d321ff7 - Date: 2022-11-16T06:25:12.4976998Z - Msg: {"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:41014c160b9f41009d70c65daf436a7b-G:0-TimeStamp:11/16/2022 06:25:12"}
Error: Time:Wed Nov 16 08:25:14 2022 File:/home/net-gimzunasdo/azure_c_sdk_latest/provisioning_client/src/prov_transport_mqtt_common.c Func:prov_transport_common_mqtt_dowork Line:979 Unable to process registration reply.
Error: Time:Wed Nov 16 08:25:14 2022 File:/home/net-gimzunasdo/azure_c_sdk_latest/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:777 Failure retrieving data from the provisioning service
Failure encountered on registration PROV_DEVICE_RESULT_DEV_AUTH_ERROR
-> 08:25:14 DISCONNECT
registration failed!
``` 

Maybe this has something to do with https://github.com/Azure/azure-iot-sdk-c#critical-upcoming-change-notice? I would guess not since I am using the latest version of the SDK without any modification to the source code except trying out sample programs.

**Comment by ericwol-msft** [comment]
Your device cert is configured correctly and in DPS. The error is coming from when DPS is trying to provision the device in your IoT hub. DPS does not have access to your IoT hub. You can try and remove and readd the hub to DPS to see if that fixes your permission issue. If not, you need to file a support request and have a support engineer help you out. Please give them the additional information below.

`"exception": Microsoft.Azure.Devices.Registration.Bond.RegistrationServiceException: {"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:41014c160b9f41009d70c65daf436a7b-G:0-TimeStamp:11/16/2022 06:25:12"} ---> Microsoft.Azure.Devices.Common.Exceptions.UnauthorizedException: {"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:41014c160b9f41009d70c65daf436a7b-G:0-TimeStamp:11/16/2022 06:25:12"}`

**Comment by domasgim** [comment]
@ericwol-msft seems that this did the trick, thank you.  

Closing issue.

**Comment by ericwol-msft** [comment]
FYI, this can happen if you regenerate your hub keys. You need to re-associate the DSP to the hub.
