### ISSUE TITLE
Dockerfile based on Ubuntu 20.04 - install azure iot sdk c w/ vcpkg

### ISSUE THREAD

**Issue by GKMesh** [Azure/azure-iot-sdk-c#2410]
Hello,

Im tyring to install the azure iot c sdk via vcpkg because building from source created a massive image, and because ppa repository doesnt support 20.04

Following instructions to bootstrap the vcpkg I get errors below, looking for guidance. Dont know why its looking for ninja build

#8 [base 5/8] RUN ./bootstrap-vcpkg.sh
#8 sha256:bf68964bb89450552e64e82366887d6333c86e832342e09a4593c9647b342aa9
#8 0.751 Unable to determine a binary release of vcpkg; attempting to build from source.
#8 0.951 Downloading vcpkg tool sources
#8 5.111 Building vcpkg-tool...
#8 5.846 CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
#8 5.847 CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
#8 5.861 -- Configuring incomplete, errors occurred!
#8 5.861 See also "/vcpkg_new/buildtrees/_vcpkg/build/CMakeFiles/CMakeOutput.log".
#8 ERROR: executor failed running [/bin/sh -c ./bootstrap-vcpkg.sh]: exit code: 1

**Comment by danewalton** [comment]
I believe it defaults to building with Ninja. [You can find the Ninja build tool here](https://ninja-build.org/).
