### ISSUE TITLE
Applicable to RPi 4B

### ISSUE THREAD

**Issue by LaudixGit** [Azure/azure-iot-sdk-c#2413]
note: didn't see a "feedback" option for [this page](https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/samples/iothub_client_sample_mqtt_dm/pi_device/readme.md)
The title and content refer specifically Raspberry Pi **3**.

Does the same process work for Raspberry Pi 4B?

If not, could this be added as note at the beginning of the doc?
If so, could the title be updated to show both Pi 3 and Pi4?

**Comment by CIPop** [comment]
@LaudixGit this is the right place for feedback for our documentation.

We have tested the instructions on RPi3 only. The process should work (maybe with modifications regarding the image source location, etc) for RPI4B.

Feel free to give these a try and then submit a PR to update the documentation to include RPI4 instructions.
