### ISSUE TITLE
Deploy Azure C SDK in OpenWrt

### ISSUE THREAD

**Issue by anhtu91** [Azure/azure-iot-sdk-c#2414]
Hi,

I want to run Azure library and its examples on my small 4G router, which has only 6MB storage and uses OpenWrt OS. Is there any tutorial for deploying Azure C SDK in OpenWrt? 

Thanks in advance

**Comment by domasgim** [comment]
You would need to implement a custom package for OpenWRT system and cross-compile it using OpenWRT SDK. As for any examples I am not currently aware of any publicly available ones.

**Comment by ericwol-msft** [comment]
Crossing compiling documentation to MIPS32 openwrt-sdk can be found here

https://github.com/Azure/azure-iot-sdk-c/tree/main/samples/dockerbuilds/MIPS32

**Comment by ericwol-msft** [comment]
I'm closing this issue with the reply above. Please feel free to reopen if you have any further information.
