### ISSUE TITLE
Override the SAS_TOKEN_DEFAULT_LIFETIME  value instead of getting default 3600

### ISSUE THREAD

**Issue by bgshankars** [Azure/azure-iot-sdk-c#242]
- **OS and version used:** <VERSION> <Ubuntu 16.04.>

# Description of the issue:
    **#include <limits.h>
       #include <inttypes.h>

      #define SAS_TOKEN_DEFAULT_LIFETIME          3600**
How to change the default lifetime of sas token value? It will be better to have an api to override the default value.

**Comment by jebrando** [comment]
With the latest SDK you can send OPTION_SAS_TOKEN_LIFETIME option to adjust this value:

int lifetime_len = 1600
IoTHubClient_SetOption(iotHubClientHandle, OPTION_SAS_TOKEN_LIFETIME, &lifetime_len);
