### ISSUE TITLE
completion of blob storage uploads with unstable connection

### ISSUE THREAD

**Issue by pulkomandy** [Azure/azure-iot-sdk-c#2421]
Hello,

We are using the SDK to upload rather large files to Azure with an unstable connection. Often the connection is lost during an upload.

We upload only one file at a time, and wait until the SDK reports either a success or a failure to try again (with the next file in case of success, or with the same file after 1 minute delay in case of error).

The upload can fail because the connection with the cloud is lost. However, after a while, we also get this error:

```
[azure] Failure in HTTP communication: server reply code is 403
[azure] HTTP Response:{"Message":"{\"errorCode\":403006,\"trackingId\":\"0f369a4a796a4ed6b8b03a50157d4a6b-B:_Backend_0_38-P:033513f8-1371-49cb-a68f-c91d426307d0-TimeStamp:01/02/2023 09:27:55\",\"message\":\"Number of active file upload requests exceeded limit\",\
[azure] HTTP code was 403
[azure] unable to HTTPAPIEX_ExecuteRequest
[azure] error in IoTHubClient_LL_UploadToBlob_step1
```

Our understanding of this (after looking at additional curl debug) is that we end up in this scenario (following the steps documented here: https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload#device-notify-iot-hub-of-a-completed-file-upload):

- Initialize a file upload: no problem
- Upload file using Azure storage APIs: during this step, the connectivity is lost
- File upload notifications: cannot be done because the connectivity is lost

As a result, from the cloud side the upload is still considered in progress. But from the device side, the SDK reports that the upload is failed and we try to upload the next file.

We have looked into the options documented here: https://learn.microsoft.com/en-us/azure/iot-hub/troubleshoot-error-codes#403006-devicemaximumactivefileuploadlimitexceeded that is, reducing the SAS token TTL. However, it is already set at the minimum of 1 hour.

Is there a way we can improve the situation from the other side, making sure our device calls the completion handler on failure, and even if the connectivity is lost? This looks to be handled internally by the SDK but I don't know what the retry policy is on sending this notification. There does not seem to be an API to abort a file upload, for example.

I think we can workaround this problem by having a waif ot 6 minutes after a failed upload. This way, we would never have more than 10 unsuccessful upload attempts per hour (60 minutes divided by 6). But this would slow down our uploads, so it would be better if we can avoid this.

**Comment by ericwol-msft** [comment]
This issue has been addressed with commit #2439 
@pulkomandy Please verify and close this issue when done.

**Comment by pulkomandy** [comment]
Yes, we are testing the fix, I will keep you up to date.

**Comment by ericwol-msft** [comment]
Closing this as this issue is being tracked by the service Request.
