### ISSUE TITLE
Update c-utility to 718ec0 (or later)

### ISSUE THREAD

**Issue by AndWass** [Azure/azure-iot-sdk-c#2425]
**Description**

The current version of c-utility has the following issue: https://github.com/Azure/azure-c-shared-utility/issues/605 which is a blocking me from using the latest LTS unmodified. Please consider updating c-utility to some version that contains the merged fix: https://github.com/Azure/azure-c-shared-utility/pull/606

**Solution**

Update c-utility so that https://github.com/Azure/azure-c-shared-utility/pull/606 is included.

**Comment by JoseSanchez7** [comment]
Hello @AndWass , we have updated c-utility. Please let us know if this unblocks you.
