### ISSUE TITLE
AZUREIOT_INC_FOLDER is unsafe for cross compile [-Werror=poison-system-directories]

### ISSUE THREAD

**Issue by Yadav-Azure** [Azure/azure-iot-sdk-c#243]
Hi,

I am trying to cross compile azure-iot-sdk-c for ARM (i.MX6 device, Yocto 2.1.1). I am able to build it for 64-bit Host machine (Ubuntu 14.04.5) but getting compilation error for cross compilation.

# Console log of the issue:
................................................................
Scanning dependencies of target iothub_client_sample_device_method
[ 83%] Building C object iothub_client/samples/iothub_client_sample_device_method/CMakeFiles/iothub_client_sample_device_method.dir/iothub_client_sample_device_method.c.o
[ 84%] Linking C executable iothub_client_sample_mqtt_esp8266
[ 84%] Built target iothub_client_sample_mqtt_esp8266
Scanning dependencies of target iothub_client_sample_mqtt_dm
[ 84%] Linking C executable iothub_client_sample_device_method
[ 84%] Building C object iothub_client/samples/iothub_client_sample_mqtt_dm/CMakeFiles/iothub_client_sample_mqtt_dm.dir/iothub_client_sample_mqtt_dm.c.o
cc1: error: include location "/usr/include/azureiot" is unsafe for cross-compilation [-Werror=poison-system-directories]
cc1: error: include location "/usr/include/azureiot/inc" is unsafe for cross-compilation [-Werror=poison-system-directories]
................................................................

# Steps I used:
git clone --recursive https://github.com/Azure/azure-iot-sdk-c.git
cd azure-iot-sdk-c
git checkout master
cd build_all/linux
./build.sh --toolchain-file imx.cmake -cl -fPIC

# imx.cmake:
INCLUDE(CMakeForceCompiler)
SET(CMAKE_SYSTEM_NAME Linux)
#this one not so much
SET(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR arm)
#specify the cross compiler
SET(CMAKE_C_COMPILER /opt/poky/2.1.1/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc -mfloat-abi=hard)
SET(CMAKE_CXX_COMPILER /opt/poky/2.1.1/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++ -mfloat-abi=hard)
SET(CMAKE_LINKER /opt/poky/2.1.1/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-ld)
SET(CMAKE_ASSEMBLER /opt/poky/2.1.1/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-as)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE only)

Can you please let me know where I am making mistake and how it can be resolve.

Regards
Anil

**Comment by jebrando** [comment]
As far as I know the poison-system-directories warning means that its picking up a file from the /usr instead of the cross-build environment.  I unfamiliar with the poison-system-directory, but after doing some search I found a post saying that --enable-poison-system-directories is being passed  to the compiler (https://lists.linaro.org/pipermail/linaro-toolchain/2010-October/000351.html)

**Comment by narayanankrish1981** [comment]
Hi Yadav,

As Jebrando specified, the cross compilation is looking for dependencies in the /usr/include/ (X86 location). 

AFAIK, it looks like you have not specified the sysroot path in the cmake configuration. We can specify the sysroot path using :
SET(CMAKE_FIND_ROOT_PATH $ENV{<**PATH OF YOUR SYSROOT (or) the env. variable of the sysroot**})

**Comment by Yadav-Azure** [comment]
@jebrando @narayanankrish1981 

Thank you guys for your prompt feedback. I am able to compile the source code now. 
I was missing  CMAKE_SYSROOT
# new imx.cmake 
INCLUDE(CMakeForceCompiler)
SET(CMAKE_SYSTEM_NAME Linux)
#this one not so much
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(CMAKE_SYSROOT /opt/poky/2.1.1/sysroots/cortexa9hf-neon-poky-linux-gnueabi)

#specify the cross compiler
SET(CMAKE_C_COMPILER /opt/poky/2.1.1/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc -mfloat-abi=hard)
SET(CMAKE_CXX_COMPILER /opt/poky/2.1.1/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++ -mfloat-abi=hard)
SET(CMAKE_LINKER /opt/poky/2.1.1/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-ld)
SET(CMAKE_ASSEMBLER /opt/poky/2.1.1/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-as)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# 
Regards
Anil Yadav
