### ISSUE TITLE
can we configure/set IOTHUB_CLIENT_RETRY_INTERVAL default 5secs to any other value 

### ISSUE THREAD

**Issue by Dasthananda** [Azure/azure-iot-sdk-c#2430]
We are using the azure-iot-sdk -c LTS_07_2022_Ref01 version.

can we configure/set IOTHUB_CLIENT_RETRY_INTERVAL default 5secs to any other value (7,8,9sec) ,if its possible with azure-iot-sdk -c could you please provide sample code/api to use the same.

Thanks

**Comment by cabrillosa** [comment]
@Dasthananda I think you can set the number of seconds between retries by setting the option "OPTION_RETRY_INTERVAL_SEC". For more information, please refer to this  reference document:

https://github.com/Azure/azure-iot-sdk-c/blob/main/doc/Iothub_sdk_options.md#:~:text=%22retry_interval_sec%22

**Comment by CIPop** [comment]
Thank you @cabrillosa !

@Dasthananda , you can achieve the same effect using `IoTHubDeviceClient_SetRetryPolicy`.
These are documented in https://github.com/Azure/azure-iot-sdk-c/blob/main/doc/connection_and_messaging_reliability.md#connection-retry-policies

We recommend using defaults in most cases as they have been tried with large scale device deployments.

If you would like to switch to a constant retry interval of 7 seconds, the call should be:
`IoTHubDeviceClient_SetRetryPolicy(IOTHUB_CLIENT_RETRY_INTERVAL, 7);`

**Comment by Dasthananda** [comment]
Thanks @cabrillosa ,@CIPop
