### ISSUE TITLE
Use IOT Hub Sdk over cellular/GSM

### ISSUE THREAD

**Issue by M-Sakr** [Azure/azure-iot-sdk-c#2450]
I did many search and could not reach to any solution yet.
and there were two closed issues but i could not get a solution from them
https://github.com/Azure/azure-iot-sdk-c/issues/1914
https://github.com/Azure/azure-iot-sdk-c/issues/200

There was a promise since many years that this feature will be added, is that finished or not yet?
Any solution to use GSM/Cellular ?

**Comment by M-Sakr** [comment]
@olivierbloch 
@ericwol-msft 
Any help?

**Comment by ericwol-msft** [comment]
That work is not tracked in this repo. Here is the repo for the cellular framework.

https://github.com/Azure/embedded-wireless-framework

**Comment by ericwol-msft** [comment]
Closing the issue with the answer above.
