### ISSUE TITLE
 Failure in HTTP communication: server reply code is 401

### ISSUE THREAD

**Issue by Yadav-Azure** [Azure/azure-iot-sdk-c#246]
Hi,
I am using I am getting "server reply code is 401" for sample "iothub_client_sample_http" when i run it on a target machine. Same sample work well on host machine using the same connectionString. 
 

- **Target:** 
      i.MX6 (Yocto 2.1.1)
      4.1.15-rt18-1.1.1 GNU/Linux
 **SDK version:** 1.1.23

- **Host:** 
      4.4.0-83-generic GNU/Linux
 **SDK version:** 1.1.23

# Steps
. /iothub_client_sample_http

# Console log 
Starting the IoTHub client sample HTTP...
Info: IoT Hub SDK for C, version 1.1.23
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
RTL871X: rtw_set_ps_mode(wlan0) Leave 802.11 power save - WIFI-TRAFFIC_BUSY
RTL871X: rtl8188e_set_FwPwrMode_cmd: Mode=0 SmartPS=2 UAPSD=0
Error: Time:Sat Aug 19 10:43:55 2017 File:azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:594 Failure in HTTP communication: server reply code is 401
Info: HTTP Response:{"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:651347e20da64d6b8b424979941eacc0-G:11-TimeStamp:09/29/2017 15:53:06"}
Error: Time:Sat Aug 19 10:43:55 2017 File:azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1695 unexpected HTTP status code (401)
Error: Time:Sat Aug 19 10:43:55 2017 File:azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:594 Failure in HTTP communication: server reply code is 401
Info: HTTP Response:{"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:cea30a0271204f709925c054e9c28bc6-G:11-TimeStamp:09/29/2017 15:53:06"}
Error: Time:Sat Aug 19 10:43:55 2017 File:azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:DoMessages Line:2097 expected status code was 200, but actually was received 401... moving on
IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.
Error: Time:Sat Aug 19 10:43:55 2017 File:azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:594 Failure in HTTP communication: server reply code is 401
Info: HTTP Response:{"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:63bdc8e8950e4bffa6a30bc2e72fb83c-G:11-TimeStamp:09/29/2017 15:53:06"}
Error: Time:Sat Aug 19 10:43:55 2017 File:azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1695 unexpected HTTP status code (401)
IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.
Error: Time:Sat Aug 19 10:43:56 2017 File:azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:594 Failure in HTTP communication: server reply code is 401
Info: HTTP

# 
I know this error is occurring due to unauthorized access, could you please let me know where I am making mistake and how it can be resolve. 

Regards
Anil

**Comment by ewertons** [comment]
Hi @Yadav-Azure, 

we need more details to understand the issue. 
What is the target OS?
What is the version of the SDK you are using?
What is the fqdn of the IoT Hub you are trying to reach?

Could you confirm your connection string is correct when running from the target OS?

If you could also paste the console logs here it would make it easier to help on this issue.

**Comment by Yadav-Azure** [comment]
Hi @ewertons 

I was adding the above missing information, By mistake keyboard "Enter" posted the issue before I was able to finished it. 

Regards
Anil

**Comment by Yadav-Azure** [comment]
Hi @ewertons ,

Here is rest of the information:
**FQDN:** yadaviot.azure-devices.net
**connectionString:** I am using same connection string for Target & Host 

Regards
Anil

**Comment by ewertons** [comment]
I'm looking for logs in your iothub, but cannot identify that failure.
It might be because the TLS negotiation failed.

Could you please take two actions?
On the code you are running in Yocto, could you recompile it [enabling verbose logs](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp.c#L177) and forcing certificates to be set for TLS negotiation (remove the defines [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_http/iothub_client_sample_http.c#L186) and let the app set the certificates)?

**Comment by Yadav-Azure** [comment]
Hi @ewertons,

As you mentioned I tried to enable the verbose log, I used "OPTION_LOG_TRACE" and remove cert defines for "iothub_client_sample_http" sample but getting error as below with some new log messages:

# 
**Console Logs:**
Starting the IoTHub client sample HTTP...
Info: IoT Hub SDK for C, version 1.1.23
Error: Time:Wed Aug 23 12:58:05 2017 File:azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_CloneOption Line:938 unknown option logtrace
Error: Time:Wed Aug 23 12:58:05 2017 File:azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_SetOption Line:609 error code = HTTPAPIEX_INVALID_ARG
Error: Time:Wed Aug 23 12:58:05 2017 File:azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:IoTHubTransportHttp_SetOption Line:2426 HTTPAPIEX_SetOption failed
Error: Time:Wed Aug 23 12:58:05 2017 File:azure-iot-sdk-c/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_SetOption Line:1741 underlying transport failed, returned = IOTHUB_CLIENT_INVALID_ARG
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
Error: Time:Wed Aug 23 12:58:06 2017 File:azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:594 Failure in HTTP communication: server reply code is 401
Info: HTTP Response:{"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:aabb730edea54d74ba117a59770cb7eb-G:7-TimeStamp:10/03/2017 18:08:31"}
Error: Time:Wed Aug 23 12:58:06 2017 File:azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1695 unexpected HTTP status code (401)
Error: Time:Wed Aug 23 12:58:06 2017 File:azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:594 Failure in HTTP communication: server reply code is 401
Info: HTTP Response:{"Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:9e080a89b37f4a67a82079a785811b73-G:7-TimeStamp:10/03/2017 18:08:31"}
Error: Time:Wed Aug 23 12:58:06 2017 File:azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:DoMessages Line:2097 expected status code was 200, but actually was received 401... moving on
IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.
# 
I have tried with new FQDN" and "connectionString". Please let me know if you have any other suggestion.

Regards
Anil

**Comment by markrad** [comment]
Hi @Yadav-Azure, 

If you have OpenSSL available to you on your device then please try entering:
```
openssl s_client -connect yadaviot.azure-devices.net:443
```
If you do not get a return code of zero then it is likely that your OpenSSL cannot find the certificates. If that is the case try using the Trusted Certs option and pass the root certificate. You can find it in pem format in certs.c.

_Mark Radbourne MSFT_

**Comment by vbisbest** [comment]
I have the same issue.  openssl s_client -connect did not get any return code.  This is on a Rasberry Pi Zero.  Other ideas?

**Comment by Yadav-Azure** [comment]
Hi @markrad,
 
openssl s_client -connect *****.azure-devices.net:443 returns:

# 
CONNECTED(00000003)
depth=1 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, OU = Microsoft IT, CN = Microsoft IT SSL SHA2
verify error:num=20:unable to get local issuer certificate
\---
Certificate chain
 0 s:/CN=*.azure-devices.net
   i:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
 1 s:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
Server certificate
-----BEGIN CERTIFICATE-----
\**************************************
\**************************************
\**************************************
\**************************************
\**************************************
\**************************************
\**************************************
\**************************************
\**************************************
-----END CERTIFICATE-----
subject=/CN=*.azure-devices.net
issuer=/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
\---
No client certificate CA names sent
Peer signing digest: SHA1
Server Temp Key: ECDH, P-256, 256 bits
\---
SSL handshake has read 3662 bytes and written 473 bytes
\---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-SHA256
    Session-ID: /***********************************************************************************
    Session-ID-ctx:
    Master-Key: /***********************************************************************************
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1503567933
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)

# 

Regards
Anil

**Comment by markrad** [comment]
Hi @Yadav-Azure,

OpenSSL is failing to find the root certificate for the Azure IoT Hub service and thus is unable to validate the certificate chain.

On your device enter:
```
openssl version -d
```
Take that output, add /certs to it and see if the resulting directory contains a certificate starting with the word Baltimore. You can do this all in one line (though I don't verify portability):
```
ls -alL `openssl version -d | cut -f2 -d' ' | tr -d '"'`/certs | grep Baltimore
```
If you don't have Baltimore_CyberTrust_Root.pem you will need to acquire it in order to continue. You will also need to generate the ssl hash symbolic link if it is missing. Try it on a Linux desktop to see the certificate and symbolic link needed.

_Mark Radbourne MSFT_

**Comment by Yadav-Azure** [comment]
Hi @markrad 

Thank you for helping me with this issue.

I am missing symbolic links (under /usr/lib/ssl/) and some files from /etc/ssl/. 
I will make all the changes and will update the this issue accordingly. 

Regards
Anil Yadav

**Comment by Yadav-Azure** [comment]
Hi @markrad @vbisbest @ewertons 

Thank you for prompt help and all the information. Finally it is working. It worked after I made changed the date on target as: 
##
date 2017.10.11-XX:XX:XX
export TZ=UDT  
##  
On my host machine with "PDT" time-zone, application works fine, but on target it only work with "UDT" time-zone.

Regards
Anil Yadav

**Comment by Demonlijianmin** [comment]
> Hi @markrad @vbisbest @ewertons
> 
> Thank you for prompt help and all the information. Finally it is working. It worked after I made changed the date on target as:
> 
> date 2017.10.11-XX:XX:XX
> export TZ=UDT
> 
> On my host machine with "PDT" time-zone, application works fine, but on target it only work with "UDT" time-zone.
> 
> Regards
> Anil Yadav

hi i got the same problem,can u tell m which file you modified or update? thank u

**Comment by markrad** [comment]
Hi @Demonlijianmin,

We do not typically monitor closed issues. You need to have the Balitmore CyberTrust (Baltimore_CyberTrust_Root.pem) root certificate in your root certificate store. Without information about the platform and OS you are using I can't help you further. Please create a new issue with all of the relevant information.

_Mark Radbourne MSFT_
