### ISSUE TITLE
SDK Migration to LTS_07_2022 - Endianness issue

### ISSUE THREAD

**Issue by neonsoftware** [Azure/azure-iot-sdk-c#2461]
Hi,

**context**

- Migrating from LTS_01_2021 to LTS_07_2022
- MIPS32 (big endian)

**Issue**

We have encountered blocking runtime issues with utpm and endianness while migrating the SDK.
We have created [the following open issue on utpm](https://github.com/Azure/azure-utpm-c/issues/113).

**Question**

As the issues is not on your side, we mostly would like to know if you have any information regarding this aspect.
Apart from this, do you have, or plan to have, tests highlighting eventual issues on endianness ?

Thank you in advance for any related information.

**Comment by neonsoftware** [comment]
@ericwol-msft @danewalton I have created this issue as question and not bug, as it is probably a bug on a dependency of yours (utpm)

Should, instead, be considered as a bug (cascading effect of the dependency) also in this repo ?

Thank you in advance.

**Comment by CIPop** [comment]
@neonsoftware we have decided to deprecate DPS-TPM. We will not provide additional changes or testing regarding endianness of the utpm-c library:
* Existing applications will continue to run as-is. 
* For new applications, we recommend using DPS-X509 with keys backed by TPM (e.g., through the tpm2tss engine).
