### ISSUE TITLE
CMake compatibility warning due to azure-macro-utils-c and umock-c requiring deprecated CMake version.

### ISSUE THREAD

**Issue by ryanwinter** [Azure/azure-iot-sdk-c#2464]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Windows 11 with Visual Studio 2022
CMake version cmake version 3.25.1-msvc1

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Commit hash 89db361d241766558b11a142b487228dfc070748

**Protocol**

None - cmake generation warning

**Describe the Bug**

When executing the following command
```cmake -Bcmake -Duse_prov_client=ON -Dhsm_type_symm_key=ON -Drun_e2e_tests=OFF```

I see cmake deprecation warnings regarding `azure-macro-utils-c` and `umock-c`.

**[MCVE](https://stackoverflow.com/help/mcve)**

```
git clone https://github.com/Azure/azure-iot-sdk-c.git
cd azure-iot-sdk-c
git submodule update --init
cmake -Bcmake -Duse_prov_client=ON -Dhsm_type_symm_key=ON -Drun_e2e_tests=OFF
```

**Console Logs**

```
CMake Deprecation Warning at deps/azure-macro-utils-c/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at deps/umock-c/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

**Comment by ericwol-msft** [comment]
Yes, this is a know issue. These are only **warnings** and CMake still functions correctly. Currently there are no plans to update these dependent repos.
