### ISSUE TITLE
Cannot invoke direct method without a payload

### ISSUE THREAD

**Issue by dominicbetts** [Azure/azure-iot-sdk-c#248]
The issue appears in a client running on Windows and Ubuntu

# Description of the issue:

The issue can be seen if you use the serializer device method sample: https://github.com/Azure/azure-iot-sdk-c/blob/master/serializer/samples/devicemethod_simplesample/devicemethod_simplesample.c

If you run the sample and then invoke the direct method (use the Portal or Device Explorer tool for simplicity), with no payload, the sample shows the following error:

```
Error: Time:Mon Oct  2 15:38:57 2017 File:C:\a\azure-iot-sdk-c\serializer\src\commanddecoder.c Func:CommandDecoder_ExecuteMethod Line:734 Decoding JSON to a multi tree failed
failed to EXECUTE_METHOD
Error: Time:Mon Oct  2 15:38:57 2017 File:C:\a\azure-iot-sdk-c\iothub_client\src\iothubtransport_mqtt_common.c Func:mqtt_notification_callback Line:1103 Failure: IoTHubClient_LL_DeviceMethodComplete
```

If you invoke the same sample method with an empty JSON document `{}` it works as expected.

This behaviour is different from the Node.js and .NET C device client SDKs (I haven't tried with Java) - they both allow a direct method to be invoked without a payload.

@timlaverty - making sure you see this for reference, it relates to https://github.com/Azure/iothub-manager-dotnet/issues/98

**Comment by markrad** [comment]
Hi @dominicbetts,

I see your point but this is just sample code. Perhaps we should note that the serializer functionality requires at least an empty payload. Are you asking that this be modified so that an empty payload and a null payload are treated in the same manner?

_Mark Radbourne MSFT_

**Comment by dominicbetts** [comment]
@markrad - Ideally the serializer would treat and empty payload and a null payload in the same manner to make it consistent with the other device SDKs.

**Comment by ewertons** [comment]
Hi @dominicbetts ,
we are discussing with the team about the course of action for this issue, and will provide a resolution soon.
Thanks.

**Comment by ewertons** [comment]
@dominicbetts ,
this is indeed a change we need to make in the C SDK to make it more flexible, and also aligned with the other flavors of the Azure IoT SDK.
We are adding this item to our backlog. There is still no ETA, but I wanted to share this update with you so you are aware of the plans.

**Comment by guybartal** [comment]
Hi, can you please share an update on this issue?

**Comment by dominicbetts** [comment]
Any update on this? Thanks!

**Comment by tameraw** [comment]
Currently not a priority in the backlog.

**Comment by jspaith** [comment]
This bug is specific to the serializer only.  When just the SDK direct method callback, a null payload gets to callee to process.  Per our serializer guidance (https://github.com/Azure/azure-iot-sdk-c/tree/master/serializer) we'll keep fixing critical bugs in serializer, but this one we won't because of the straightforward workaround.

**Comment by az-iot-builder-01** [comment]
@dominicbetts, @guybartal, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)

**Comment by hmxmghl** [comment]
I am facing the same issue even by sending empty JSON object like `{}` as a payload. Any thoughts how to resolve this?

**Comment by jspaith** [comment]
First @hmxmghl - please a open new issue for this.  We don't really track closed issues so this could get lost otherwise.

If this is on the serializer specifically, please be aware that we can provide fixes for critical security/stability issues for it.  But we're actively encouraging folks to use raw json parsers for reasons listed in https://github.com/Azure/azure-iot-sdk-c/tree/master/serializer.
