### ISSUE TITLE
Update Third Party Licensing Disclosures and Clarify Library Usage

### ISSUE THREAD

**Issue by jdswensen** [Azure/azure-iot-sdk-c#249]
During a preliminary license review of this library we have discovered the following issues with [thirdpartynotice.txt](https://github.com/Azure/azure-iot-sdk-c/blob/master/thirdpartynotice.txt):

- Disclosures that do not appear to be directly referenced in the C SDK repo code. For example, Google gson. Is this references obsolete? The commits that reference gson appear to be left over from when all SDKs where in a single repo or directly in java related repos.
- Missing disclosure of third party libraries in submodules (wolf ssl, lwip)

It would also help clarify licensing of this SDK if there was documentation around the following:
- List of library dependencies (curl, crypto, parson, others?) This list becomes a very important part of a license review process if the SDK is distributed as part of a hardgood product (embedded system) instead of deployed to a PC or server.
- optional vs mandatory dependencies
- static vs dynamic linking

**Comment by ewertons** [comment]
Hi @jdswensen , thanks for your questions.
I added @olivierbloch here to help finding the answers.

Thanks for using and contributing to the Azure IoT SDK.

**Comment by olivierbloch** [comment]
Hi @jdswensen great catch and feedback. we will make sure the third party notice files are up to date. they should be the reference in terms of which libraries/code are used in the SDK itself.
Regarding the dependencies (libraries users have to import and install on their systems as they are note part of the SDK, and therefore not redistributed within it) we shall indeed publish a list of them.

**Comment by jspaith** [comment]
We've fixed this - see 90215bb8f4041547f0e64bf5936bf2366fe6d035
