### ISSUE TITLE
"SDK API Reference Documentation" link is invalid

### ISSUE THREAD

**Issue by zh0903** [Azure/azure-iot-sdk-c#2518]
![image](https://github.com/Azure/azure-iot-sdk-c/assets/49020965/667188cd-b7a1-4a11-83d3-778693b93009)

https://docs.microsoft.com/azure/iot-hub/iot-c-sdk-ref/

This link is invalid now.
Would you like to check it?

**Comment by CIPop** [comment]
@RLeclair is this something that was broken after the last release?

At https://learn.microsoft.com/en-us/azure/iot-hub/
I only see a direct link to our repo:
![image](https://github.com/Azure/azure-iot-sdk-c/assets/8635911/8d2ef318-8bbe-493e-8055-31bd0bbfffed)

**Comment by RLeclair** [comment]
@CIPop, looked at a snapshot of https://learn.microsoft.com/en-us/azure/iot-hub/ from June this year and we also had the direct link back then. Looking into why the API reference documentation is not there

**Comment by RLeclair** [comment]
Hi @zh0903 no response for the last 3 weeks so closing for now. Please feel free to re-open the issue if needed.
