### ISSUE TITLE
Getting Unsuccessful json encountered error while simulating a TPM device registering on DPS

### ISSUE THREAD

**Issue by amogh79** [Azure/azure-iot-sdk-c#252]
Hi,

I am using the code from this repo to simulate a TPM device registering on DPS (followed steps from this link https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device#setupdevbox) and getting error, "azure-iot-sdk-c\dps_client\src\dps_client.c Func:_dps_transport_process_json_reply Line:393 Unsuccessful json encountered". Screen dump is attached.

Please help resolve this.

Thanks
Amogh
[dps error.txt](https://github.com/Azure/azure-iot-sdk-c/files/1371619/dps.error.txt)

**Comment by jebrando** [comment]
Amogh, did you correctly setup the Endorsement key in the dps portal?  It looks like the Endorsement key is blank for this registration.

**Comment by amogh79** [comment]
Thanks for your response. Yes I did include the endorsement key while adding the device in the individual enrollment list on Azure portal in DPS blade.

**Comment by jebrando** [comment]
On more question.  There is a "quirk" in the TPM emulator that if you reload the emulator it give you a new EK can you verify that the EK is the same for the emulator as you have it in the json that is sent to DPS service.

**Comment by amogh79** [comment]
Thanks for your response.
Yes I did check and the EK that gets generated and the one that is sent from the code to DPS is a exact match.

**Comment by jebrando** [comment]
I escalated this issue to the DPS service team.  I will follow up with them and let you know their response.

**Comment by amogh79** [comment]
Was able to resolve the issue, the endorsement key that I was using was having additional line breaks while copying, removed additional line breaks and the simulated device was successfully registered. Thanks for all your help.
