### ISSUE TITLE
Azure -c- shared-utility on Raspberry pi

### ISSUE THREAD

**Issue by Chandana-Ramagoni023** [Azure/azure-iot-sdk-c#2528]
Hello,

when I run the application, I'm facing the below issue:

=============================================
------reached to external ----- 

Creating device Handle

---------Success--------

Error: Time:Fri Sep  8 11:38:28 2023 File:/home/pi/Desktop/RPiLockEmulator-Bluetooth-connectivity/iot-application_Extended/c-utility/src/uws_client.c Func:uws_client_close_async Line:1786 close has been called when already CLOSED
Error: Time:Fri Sep  8 11:38:28 2023 File:/home/pi/Desktop/RPiLockEmulator-Bluetooth-connectivity/iot-application_Extended/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:895 SSL channel closed in decode_ssl_received_bytes.
Error: Time:Fri Sep  8 11:38:28 2023 File:/home/pi/Desktop/RPiLockEmulator-Bluetooth-connectivity/iot-application_Extended/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:944 Error in decode_ssl_received_bytes.

I want to send the information from cloud to raspberry pi using mqtt websocket protocol.

**Comment by ericwol-msft** [comment]
This usually happens if you have two devices that use the same device ID on the hub. If another device connects with the same device ID, the previous device connection will be closed by the service.

**Comment by Chandana-Ramagoni023** [comment]
> This usually happens if you have two devices that use the same device ID on the hub. If another device connects with the same device ID, the previous device connection will be closed by the service.

How to check the devices which are having same device id?

**Comment by Chandana-Ramagoni023** [comment]
> look at you other devices on the hub and see what device ID thay are connection with.
> 
> Try and change the name of this device 'RaspPi-Gateway-1' to some other name.
Yeah i had given the other connection string even through it is throwing the same errors. Please help me in solving this. Thanks in advance.

**Comment by ericwol-msft** [comment]
What is the new device ID? The server logs shows you have two devices trying to use the same device ID.
