### ISSUE TITLE
cleanup_prov_info function issue

### ISSUE THREAD

**Issue by haiyang-lhy** [Azure/azure-iot-sdk-c#2529]
I think the function cleanup_prov_info free NULL pointer （prov_info->iothub_info.device_id/prov_info->iothub_info.iothub_key/prov_info->iothub_info.iothub_url）. because I don't find any code to initialize them in SDK.  
 please confirme!

prov_device_ll_client.c (provisioning_client\src) line 702 : static void cleanup_prov_info(PROV_INSTANCE_INFO* prov_info)
    free(prov_info->iothub_info.device_id);
    prov_info->iothub_info.device_id = NULL;
    free(prov_info->iothub_info.iothub_key);
    prov_info->iothub_info.iothub_key = NULL;
    free(prov_info->iothub_info.iothub_url);
    prov_info->iothub_info.iothub_url = NULL;

**Comment by ewertons** [comment]
Addressed by PR #2531
