### ISSUE TITLE
Git submodule errors with the lts_07_2017 branch

### ISSUE THREAD

**Issue by JohnniePeters** [Azure/azure-iot-sdk-c#253]
- **OS and version used:** <VERSION> 
CentOS 7 building a Yocto enviroment

- **SDK version used:** <VERSION> 
Checked out from git on the lts_07_2017 branch.

# Description of the issue:

We have been using the lts_-7_17 branch of git with SHA
61d5414b98fe3cad794e4f6ca66d1eabe196400d. Suddenly today we are getting errors when trying to run git submodule in the checked out archive.  Error output from build:

| Submodule 'azure-c-shared-utility' (https://github.com/Azure/azure-c-shared-utility.git) registered for path 'c-utility'
| Submodule 'iothub_service_client/parson' (https://github.com/kgabis/parson) registered for path 'iothub_service_client/parson'
| Submodule 'parson' (https://github.com/kgabis/parson) registered for path 'parson'
| Submodule 'azure-uamqp-c' (https://github.com/Azure/azure-uamqp-c.git) registered for path 'uamqp'
| Submodule 'azure-umqtt-c' (https://github.com/Azure/azure-umqtt-c.git) registered for path 'umqtt'
| Cloning into 'c-utility'...
| Submodule path 'c-utility': checked out '84e6f95970e54f3889635b95e4cb6b059c08a4fa'
| Submodule 'testtools/ctest' (https://github.com/Azure/azure-ctest.git) registered for path 'testtools/ctest'
| Submodule 'testtools/testrunner' (https://github.com/Azure/azure-c-testrunnerswitcher.git) registered for path 'testtools/testrunner'
| Submodule 'testtools/umock-c' (https://github.com/Azure/umock-c.git) registered for path 'testtools/umock-c'
| Cloning into 'testtools/ctest'...
| fatal: reference is not a tree: 92c82a95fb19255c378cfb56a5ca2b68f2f4b7e7
| Cloning into 'testtools/testrunner'...
| fatal: reference is not a tree: 1f591f650b5314faf5199ec580789047d34f0f57
| Cloning into 'testtools/umock-c'...
| Submodule path 'c-utility/testtools/umock-c': checked out '91d03b2084e65f2ea42ed0a707f52ab043117db3'
| Submodule 'deps/azure-ctest' (https://github.com/Azure/azure-ctest.git) registered for path 'deps/ctest'
| Submodule 'deps/testrunner' (https://github.com/Azure/azure-c-testrunnerswitcher.git) registered for path 'deps/testrunner'
| Cloning into 'deps/ctest'...
| fatal: reference is not a tree: 92c82a95fb19255c378cfb56a5ca2b68f2f4b7e7
| Cloning into 'deps/testrunner'...
| fatal: reference is not a tree: 1f591f650b5314faf5199ec580789047d34f0f57
| Unable to checkout '92c82a95fb19255c378cfb56a5ca2b68f2f4b7e7' in submodule path 'c-utility/testtools/umock-c/deps/ctest'
| Unable to checkout '1f591f650b5314faf5199ec580789047d34f0f57' in submodule path 'c-utility/testtools/umock-c/deps/testrunner'
| Unable to checkout '92c82a95fb19255c378cfb56a5ca2b68f2f4b7e7' in submodule path 'c-utility/testtools/ctest'
| Unable to checkout '1f591f650b5314faf5199ec580789047d34f0f57' in submodule path 'c-utility/testtools/testrunner'
| Failed to recurse into submodule path 'c-utility/testtools/umock-c'

The first thing I tried was moving to the head of lts_07_2017 which is SHA tag 16c6ca75a2725d2543eec505cf43b55e56877239.  I now get the error output:

| Submodule 'azure-c-shared-utility' (https://github.com/Azure/azure-c-shared-utility.git) registered for path 'c-utility'
| Submodule 'iothub_service_client/parson' (https://github.com/kgabis/parson) registered for path 'iothub_service_client/parson'
| Submodule 'parson' (https://github.com/kgabis/parson) registered for path 'parson'
| Submodule 'azure-uamqp-c' (https://github.com/Azure/azure-uamqp-c.git) registered for path 'uamqp'
| Submodule 'azure-umqtt-c' (https://github.com/Azure/azure-umqtt-c.git) registered for path 'umqtt'
| Cloning into 'c-utility'...
| Submodule path 'c-utility': checked out 'bad7ead6cd73fe9e1d95ca0fe812a1e9b4e2a601'
| Submodule 'testtools/ctest' (https://github.com/Azure/azure-ctest.git) registered for path 'testtools/ctest'
| Submodule 'testtools/testrunner' (https://github.com/Azure/azure-c-testrunnerswitcher.git) registered for path 'testtools/testrunner'
| Submodule 'testtools/umock-c' (https://github.com/Azure/umock-c.git) registered for path 'testtools/umock-c'
| Cloning into 'testtools/ctest'...
| Submodule path 'c-utility/testtools/ctest': checked out '5df600df7b5e0f8834f76f1d0f1264ed1304f56e'
| Cloning into 'testtools/testrunner'...
| Submodule path 'c-utility/testtools/testrunner': checked out 'b7b5e37a62cc8663241ef85466c975b8a95b6b85'
| Cloning into 'testtools/umock-c'...
| fatal: reference is not a tree: d9ccbe13b103910618cf3891d8370a426ca4aa2e
| Unable to checkout 'd9ccbe13b103910618cf3891d8370a426ca4aa2e' in submodule path 'c-utility/testtools/umock-c'
| Cloning into 'iothub_service_client/parson'...
| Submodule path 'iothub_service_client/parson': checked out 'ba2a854c27b24068977e5827bd129d0531f4503c'
| Cloning into 'parson'...
| Submodule path 'parson': checked out 'ba2a854c27b24068977e5827bd129d0531f4503c'
| Cloning into 'uamqp'...
| Submodule path 'uamqp': checked out 'a323523aa124f0bfedfc18e43cb19f4fe49c636e'
| Submodule 'deps/azure-c-shared-utility' (https://www.github.com/Azure/azure-c-shared-utility) registered for path 'deps/azure-c-shared-utility'
| Submodule 'deps/azure-c-testrunnerswitcher' (https://www.github.com/Azure/azure-c-testrunnerswitcher) registered for path 'deps/azure-c-testrunnerswitcher'
| Submodule 'deps/azure-ctest' (https://www.github.com/Azure/azure-ctest) registered for path 'deps/azure-ctest'
| Submodule 'deps/umock-c' (https://www.github.com/Azure/umock-c) registered for path 'deps/umock-c'
| Cloning into 'deps/azure-c-shared-utility'...
| Submodule path 'uamqp/deps/azure-c-shared-utility': checked out 'bad7ead6cd73fe9e1d95ca0fe812a1e9b4e2a601'
| Submodule 'testtools/ctest' (https://github.com/Azure/azure-ctest.git) registered for path 'testtools/ctest'
| Submodule 'testtools/testrunner' (https://github.com/Azure/azure-c-testrunnerswitcher.git) registered for path 'testtools/testrunner'
| Submodule 'testtools/umock-c' (https://github.com/Azure/umock-c.git) registered for path 'testtools/umock-c'
| Cloning into 'testtools/ctest'...
| Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/ctest': checked out '5df600df7b5e0f8834f76f1d0f1264ed1304f56e'
| Cloning into 'testtools/testrunner'...
| Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/testrunner': checked out 'b7b5e37a62cc8663241ef85466c975b8a95b6b85'
| Cloning into 'testtools/umock-c'...
| fatal: reference is not a tree: d9ccbe13b103910618cf3891d8370a426ca4aa2e
| Unable to checkout 'd9ccbe13b103910618cf3891d8370a426ca4aa2e' in submodule path 'uamqp/deps/azure-c-shared-utility/testtools/umock-c'
| Cloning into 'deps/azure-c-testrunnerswitcher'...
| Submodule path 'uamqp/deps/azure-c-testrunnerswitcher': checked out 'b7b5e37a62cc8663241ef85466c975b8a95b6b85'
| Cloning into 'deps/azure-ctest'...
| Submodule path 'uamqp/deps/azure-ctest': checked out '5df600df7b5e0f8834f76f1d0f1264ed1304f56e'
| Cloning into 'deps/umock-c'...
| fatal: reference is not a tree: d9ccbe13b103910618cf3891d8370a426ca4aa2e
| Failed to recurse into submodule path 'uamqp/deps/azure-c-shared-utility'
| Unable to checkout 'd9ccbe13b103910618cf3891d8370a426ca4aa2e' in submodule path 'uamqp/deps/umock-c'
| Cloning into 'umqtt'...
| Submodule path 'umqtt': checked out '36665a3c845c4d03485c7be6ea2c7f9c2e551f7e'
| Submodule 'azure-c-shared-utility' (https://github.com/Azure/azure-c-shared-utility.git) registered for path 'c-utility'
| Cloning into 'c-utility'...
| Submodule path 'umqtt/c-utility': checked out 'bad7ead6cd73fe9e1d95ca0fe812a1e9b4e2a601'
| Submodule 'testtools/ctest' (https://github.com/Azure/azure-ctest.git) registered for path 'testtools/ctest'
| Submodule 'testtools/testrunner' (https://github.com/Azure/azure-c-testrunnerswitcher.git) registered for path 'testtools/testrunner'
| Submodule 'testtools/umock-c' (https://github.com/Azure/umock-c.git) registered for path 'testtools/umock-c'
| Cloning into 'testtools/ctest'...
| Submodule path 'umqtt/c-utility/testtools/ctest': checked out '5df600df7b5e0f8834f76f1d0f1264ed1304f56e'
| Cloning into 'testtools/testrunner'...
| Submodule path 'umqtt/c-utility/testtools/testrunner': checked out 'b7b5e37a62cc8663241ef85466c975b8a95b6b85'
| Cloning into 'testtools/umock-c'...
| fatal: reference is not a tree: d9ccbe13b103910618cf3891d8370a426ca4aa2e
| Unable to checkout 'd9ccbe13b103910618cf3891d8370a426ca4aa2e' in submodule path 'umqtt/c-utility/testtools/umock-c'
| Failed to recurse into submodule path 'umqtt/c-utility'
| Failed to recurse into submodule path 'c-utility'
| Failed to recurse into submodule path 'uamqp'
| Failed to recurse into submodule path 'umqtt'

When I backup one rev form our usual build point to SHA tag f5583712a5efae068c22eec2da0054853df9d61a (exactly one before 61d5414b98fe3cad794e4f6ca66d1eabe196400d) the git submodule command works as expected.

**Comment by ewertons** [comment]
Hi @JohnniePeters , 

we are aware of this break and we are working to get it fixed.
We will update your ticket soon.

**Comment by ewertons** [comment]
@JohnniePeters , the lts_07_2017 branch is now fixed and free of submodule breaks.

We apologize for the break, we will make sure this issue does not occur again.

If you have chance please verify and let us know.

Thanks for contributing to the Azure IoT SDKs!
