### ISSUE TITLE
Compile Error on Alpine

### ISSUE THREAD

**Issue by acode-x** [Azure/azure-iot-sdk-c#2530]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

- gcc -dumpmachine
x86_64-alpine-linux-musl
- gcc --version
gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924

**SDK Version**: LTS_08_2023

**Protocol**: MQTT

**Describe the Bug**

![image](https://github.com/Azure/azure-iot-sdk-c/assets/91404478/761e02c6-991a-41c4-9d05-d340225f751c)

**Comment by CIPop** [comment]
The warning is discussed in https://stackoverflow.com/questions/47450718/gcc7-2-argument-range-exceeds-maximum-object-size-9-7-werror-alloc-size-larg and https://gcc.gnu.org/bugzilla//show_bug.cgi?id=85783.

This is very likely a false positive as both operands should be fairly small and never exceed the maximum value of `size_t`.

My recommendation is to disable this warning (set `compileOption_C` to have `-Wno-alloc-size-larger-than` ). E.g. in `ccmake ..`: 
![image](https://github.com/Azure/azure-iot-sdk-c/assets/8635911/c3333e6e-2640-4112-864b-0a269c576dec)

**Comment by acode-x** [comment]
Thanks CIPop. I'll suppress this warning for now.
