### ISSUE TITLE
Sample for ESP32

### ISSUE THREAD

**Issue by reneprins4** [Azure/azure-iot-sdk-c#2533]
Hello,

I'm creating leaf devices, and I'd like to utilize the sample code provided in the "iotedge_downstream_device_sample." I've carefully followed the documentation on building the application, but I've encountered an obstacle when it comes to flashing it onto the ESP32 device. Also installed the Espressif development environment. Is there some manual or some practical examples demonstrating how to deploy the downstream device sample on an ESP32 device? 

Thanks.

**Comment by CIPop** [comment]
We no longer support the C-SDK on non-Linux devices.

For constrained embedded devices such as the ESP32, we recommend either our [FreeRTOS Middleware](https://github.com/Azure-Samples/iot-middleware-freertos-samples) or our new [Arduino package](https://github.com/Azure/azure-sdk-for-c-arduino).
