### ISSUE TITLE
Identity translation gateway

### ISSUE THREAD

**Issue by ClaesIvarsson** [Azure/azure-iot-sdk-c#2535]
Is there any way to implement identity translation gateway using this sdk ?

In my project, we are using esp32 with mesh network and would like to let all nodes in the mesh network connect to an IoT Hub though the root node of the network.

Today we use the NAT feature in the mesh network and let all nodes have their own connection to the IoT Hub I have noticed that the root node struggle to handle the traffic when mesh network becomes larger.
Instead I would like to let the root node be the only one to connect to the IoT Hub and act as a gateway for all the nodes in the network.

I have seen the sdk for Egde node with translation gateway capability but it is implemented en C#, is there a port for c/c++ ?

**Comment by ericwol-msft** [comment]
No, there is no port to C for an Egde node with translation gateway.

**Comment by ClaesIvarsson** [comment]
Is there anyway to implement identity translation gateway functionality using this SDK ? Or can you suggest another solution for for this scenario ?

**Comment by ericwol-msft** [comment]
Identity translation is out of scope for this SDK.

**Comment by ClaesIvarsson** [comment]
> Identity translation is out of scope for this SDK.
> 
> You would need to port this over to a C project. https://github.com/azure-samples/azure-iot-edge-identity-translation-lite/tree/master/

Unfortunately this example has some major features missing. Do you know if there is a description somewhere on how to handle the open points listed in this example?

**Comment by ericwol-msft** [comment]
I don't know. Please follow up these questions directly in that repo for better directed assistance.
