### ISSUE TITLE
IoTHubDeviceClient_LL_SetRetryPolicy and IoTHubDeviceClient_LL_GetRetryPolicy documentation

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [Azure/azure-iot-sdk-c#2538]
The IoTHubDeviceClient_LL_SetRetryPolicy and IoTHubDeviceClient_LL_GetRetryPolicy documentation description text seems to be incorrect:

"Sets up the connection status callback to be invoked representing the status of the connection to IOT Hub."

The function sets/gets the retry policy. 

It seems to be a copy-and-paste error from IoTHubDeviceClient_LL_SetConnectionStatusCallback.

The documentation of how the different retry policies work is lacking, too. One is just left guessing from the enum values how they work.

**Comment by ericwol-msft** [comment]
This retry policies are documented here: https://github.com/Azure/azure-iot-sdk-c/blob/main/doc/connection_and_messaging_reliability.md#connection-retry-policies

**Comment by ericwol-msft** [comment]
#2542
