### ISSUE TITLE
Mininum guaranteed date for DPS-TPM's "work as-is" ?

### ISSUE THREAD

**Issue by neonsoftware** [Azure/azure-iot-sdk-c#2539]
Hi,

Regarding this sentence in the main README:

> 🚨We are announcing the deprecation of the utpm-c library support and DPS-TPM authentication support within the Azure IoT C-SDK.🚨 Starting May 2023, Microsoft will not provide support for this library. Existing applications using this library will continue to work as-is

There see that there is no guaranteed minimum guaranteed date specified for the _**work as-is**_. 

Would it be possible to provide, according to your timeline a minimum guaranteed date, ex.  _**will work as-is at least until Q4 2024**_ ?

Thank you very much in advance.
Have a nice day.

**Comment by ericwol-msft** [comment]
Currently there is no specific timeline as of yet. Any new projects should not take a dependency on DPS-TPM authentication using this SDK,

**Comment by neonsoftware** [comment]
Thank you for the prompt response, @ericwol-msft. I will report this to my team.

I have no further question. [the issue can be closed, should I ?]
