### ISSUE TITLE
Undefined references from iothub_client_properties.h when included in C++ source file

### ISSUE THREAD

**Issue by D-r-P-3-p-p-3-r** [Azure/azure-iot-sdk-c#2540]
I got messages from the linker like

> undefined reference to `IoTHubClient_Properties_Serializer_CreateReported(IOTHUB_CLIENT_PROPERTY_REPORTED_TAG const*, unsigned int, char const*, unsigned char**, unsigned int*)

> undefined reference to `IoTHubClient_Properties_Serializer_Destroy(unsigned char*)'

when including _iothub_client_properties.h_ in a C++ source code file.

The problem is that _iothub_client_properties.h_ does not contain an _extern "C"_ specification like

```
#ifdef __cplusplus
extern "C"
{
#endif

// ...

#ifdef __cplusplus
}
#endif
```

Including the file via 

```
extern "C" {
#include <iothub_client_properties.h>
}
```

works but is ugly like hell.

**Comment by CIPop** [comment]
Thanks @D-r-P-3-p-p-3-r for your report. 
Please feel free to submit a PR.

**Comment by ericwol-msft** [comment]
resolved
