### ISSUE TITLE
IOTHUB_CLIENT_RETRY_INTERVAL not working correctly( documentation? )

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#256]
- **OS and version used:** macOS 10.12.4, Ubuntu 14.04 LTS 

- **SDK version used:** 1.1.24 

# Description of the issue:
In iothub mqtt sample([1](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c)), I added IOTHUB_CLIENT_RETRY_INTERVAL to 60 seconds. I pulled out the ethernet cable before publishing was complete. Reconnect ethernet cable after 5 minutes. The mqtt publish acknowledgment messages are not received( `SendConfirmationCallback` is not invoked).

# Code sample exhibiting the issue:
Added to iothub-client mqtt sample([1](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c))
```
int timeout = 60;
IoTHubClient_LL_SetRetryPolicy(iotHubClientHandle, IOTHUB_CLIENT_RETRY_INTERVAL, timeout ) 
```

# Console log of the issue:
Info: IoT Hub SDK for C, version 1.1.24
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [3] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [4] for transmission to IoT Hub.

# Query
If lib user sets IOTHUB_CLIENT_RETRY_INTERVAL to X seconds, what is expected? Does this mean SDK will retry message in another X seconds infinite times? Doubt is since there is mention to `initial_wait_time_in_secs` in docs([2](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/devdoc/requirement_docs/iothub_client_retry_control_requirements.md#calculate_next_wait_time))

**Comment by ewertons** [comment]
Hi @kiranpradeep, thanks for reporting this issue.
Are you running this [sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c)?

I would expect to the see in the log all the other traces generated by MQTT client.
Could you attach the full log please? Make sure that the sample you are running has [verbose logging enabled](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c#L156) please.

I will attempt to repro the issue on our side, and also verify the documentation.

**Comment by lukka** [comment]
@kiranpradeep The last argument you passed to the following function
```IoTHubClient_LL_SetRetryPolicy(iotHubClientHandle, IOTHUB_CLIENT_RETRY_INTERVAL, timeout )  ```
is not the retry interval, but it is the time after which 'connection retry' attempts are given up. You waited 5 minutes in your test, hence no reconnection are expected with a ```timeout=60seconds```.

You should use instead:

```IoTHubClient_LL_SetOption(iothub_client_handle, "initial_wait_time_in_secs", retryConnectionPeriod);```

to set the reconnection period to 'retryConnectionPeriod'.

**Comment by ewertons** [comment]
Thanks @lukka , you explained it perfectly !
@kiranpradeep , were you able to unblock your project following his recommendation?

One more detail: you can disable the retry timeout by passing 0 for the `timeout` parameter.

**Comment by ewertons** [comment]
@lukka ,

The _SetOption function takes a pointer to the option value, so you should call:

```c
size_t retryConnectionPeriod = 60; // seconds
IoTHubClient_LL_SetOption(iothub_client_handle, "initial_wait_time_in_secs", &retryConnectionPeriod);
```

That should work for you. 
Could you try it out please?

**Comment by lukka** [comment]
@ewertons just to report, it does not work yet on recent version of the SDK:


```
#define OPTION_RETRY_INTERVAL "initial_wait_time_in_secs"
if (IoTHubClient_LL_SetOption(iothub_client_handle, OPTION_RETRY_INTERVAL, &retryInterval) !=
				IOTHUB_CLIENT_OK) {

```


`Error: Time:Thu Mar  8 21:57:34 2018 File:/usr/src/debug/azure-iot-sdks/2018-2-1.AUTOINC+1b60611bac-r0/git/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_SetOption Line:1783 underlying transport failed, returned = IOTHUB_CLIENT_INVALID_ARG`
