### ISSUE TITLE
Version 1.12.0 does not have a git tag

### ISSUE THREAD

**Issue by Timple** [Azure/azure-iot-sdk-c#2560]
The template is a bit verbose, but version 1.12.0 does not have a git tag: https://github.com/Azure/azure-iot-sdk-c/tags

The other versions do. Can this be corrected?

**Comment by ericwol-msft** [comment]
1.12.0 has not been release yet. Current version is 1.11

https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_08_2023

**Comment by Timple** [comment]
Aah, my bad.

**Comment by Timple** [comment]
But on the same note. Where is the `1.11` tag?

**Comment by Timple** [comment]
Ah that is a pitty. Your version.txt does show the three digit version number. So that is how our tooling correlates this with the releases.

Would it be a burden to add these tags? Otherwise we (and potentially others) need to maintain a shadow list of which tag corresponds to which version.

**Comment by besquivel-pivotal** [comment]
> Ah that is a pitty. Your version.txt does show the three digit version number. So that is how our tooling correlates this with the releases.
> 
> Would it be a burden to add these tags? Otherwise we (and potentially others) need to maintain a shadow list of which tag corresponds to which version.

The tags used to be there. Our build references the version that is written in version.txt and it recently started failing because the 1.11.0 tag was removed. 

@ericwol-msft, it would be a tremendous help if you kept the tags that were already created.

**Comment by RLeclair** [comment]
Hi @besquivel-pivotal, I've gone ahead and added the 1.11.0 tag and added the 1.12.0 tag. Closing the issue now

**Comment by Timple** [comment]
Thank you!
