### ISSUE TITLE
IoTHubDeviceClient_UploadMultipleBlocksToBlob_Async can miss some errors

### ISSUE THREAD

**Issue by pulkomandy** [Azure/azure-iot-sdk-c#2569]
** Environment **

- Development system: Yocto Kirkstone, ARM64, using custom hardware.
- SDK version: LTS_08_2823

** Problem description **

We use IoTHubDeviceClient_UploadMultipleBlocksToBlob_Async  to start an upload. However, there is an error during the upload setup. Logs extract:

```
[warning]: [azure] Failure in HTTP communication: server reply code is 404
[info]: [azure] HTTP Response:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
                                                         <HTML><HEAD><TITLE>Not Found</TITLE>
                                                         <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
                                                         <BODY><h2>Not Found</h2>
                                                         <hr><p>HTTP Error 404. The requested resource is not found.</p>
                                                         </BODY></HTML>
[warning]: [azure] HTTP failed response code was 404
[warning]: [azure] unable to HTTPAPIEX_ExecuteRequest
[warning]: [azure] error in IoTHubClient_LL_UploadToBlob_GetBlobCredentialsFromIoTHub
[warning]: [azure] Failed initializing upload in IoT Hub
```

These error come from https://github.com/Azure/azure-iot-sdk-c/blob/6b7753837ee18d2198759aa625d99081e255248f/iothub_client/src/iothub_client_ll_uploadtoblob.c#L908 and https://github.com/Azure/azure-iot-sdk-c/blob/6b7753837ee18d2198759aa625d99081e255248f/iothub_client/src/iothub_client_core_ll.c#L2881

In our case we are using asynchronous upload so this is called from here inside uploadMultipleBlock_thread:

https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/src/iothub_client_core.c#L2437

The thread function returns an error, but this is not propagated to the caller function that started the thread: https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/src/iothub_client_core.c#L2475 (and it can't be, because it's happening asynchronously in another thread).

There is no way for the caller code to know that the upload has failed. IoTHubClientCore_UploadMultipleBlocksToBlobAsync but the upload callback is never called. I think it could make sense in this case to call the callback (IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_CALLBACK_EX getDataCallbackEx) with an IOTHUB_CLIENT_FILE_UPLOAD_RESULT error code indicating a failed upload. Otherwise, our software has no way to know that the upload is failed and should be retried. In our case, we make sure to only have one upload at a time, so we stay blocked and never upload anything anymore if this happens.

**Comment by ewertons** [comment]
Hi @pulkomandy , could you please take a look at these new more-granular upload-to-blob API functions?
https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_client/samples/iothub_client_sample_upload_to_blob_with_retry/iothub_client_sample_upload_to_blob_with_retry.c 

They would give you more control over detecting intermediary errors and attemping retries.

**Comment by pulkomandy** [comment]
Hello,

We have been using this patch to fix the problem:

```
From f9d46850bc024989c16110f7c7f8b1a25d51823f Mon Sep 17 00:00:00 2001
From: Nicolas Savatier <nicolas.savatier@viveris.fr>
Date: Thu, 1 Feb 2024 10:22:46 +0000
Subject: [PATCH] [LCB-1144] Add callback call on upload failure in Azure
 Worker Thread

---
 iothub_client/src/iothub_client_core.c | 12 ++++++++++++
 1 file changed, 12 insertions(+)

diff --git a/iothub_client/src/iothub_client_core.c b/iothub_client/src/iothub_client_core.c
index 6da8b7216..08b911b7f 100644
--- a/iothub_client/src/iothub_client_core.c
+++ b/iothub_client/src/iothub_client_core.c
@@ -2431,10 +2431,22 @@ static int uploadMultipleBlock_thread(void* data)
     if (threadInfo->uploadBlobMultiblockSavedData.getDataCallback != NULL)
     {
         result = IoTHubClientCore_LL_UploadMultipleBlocksToBlob(llHandle, threadInfo->destinationFileName, threadInfo->uploadBlobMultiblockSavedData.getDataCallback, threadInfo->context);
+        if(result != IOTHUB_CLIENT_OK)
+        {
+            //An error happened during IoTHubClientCore_LL_UploadMultipleBlocksToBlob(),
+            //notify the caller by calling its callback function.
+            threadInfo->uploadBlobMultiblockSavedData.getDataCallback(result, NULL, NULL, threadInfo->context);
+        }
     }
     else
     {
         result = IoTHubClientCore_LL_UploadMultipleBlocksToBlobEx(llHandle, threadInfo->destinationFileName, threadInfo->uploadBlobMultiblockSavedData.getDataCallbackEx, threadInfo->context);
+        if(result != IOTHUB_CLIENT_OK)
+        {
+            //An error happened during IoTHubClientCore_LL_UploadMultipleBlocksToBlobEx(),
+            //notify the caller by calling its callback function.
+            threadInfo->uploadBlobMultiblockSavedData.getDataCallbackEx(result, NULL, NULL, threadInfo->context);
+        }
     }
     (void)markThreadReadyToBeGarbageCollected(threadInfo);
 
-- 
2.39.2
```

Sorry, we forgot to update the issue with the patch. We have confirmed that it works for us and solves the problem.

We know of the new granular API, but if we can avoid rewriting our code with a simple fix like this, it saves us a lot of time.

**Comment by ewertons** [comment]
Hi @pulkomandy , we merged a fix for this issue. Thank you very much for reporting it!
We will close this issue early next week. If you have a chance to verify the fix from your side, we would appreciate it.
Thanks,
Azure IoT SDK Team.

**Comment by pulkomandy** [comment]
Hello,

Thanks for the fix. I don't know if we can fully verify it, since we noticed the error after a problem on the Azure IoT cloud side, which we can't reproduce predictably.

We will try to update the version of the SDK we use whenever possible (possibly waiting for the next release).

**Comment by pulkomandy** [comment]
Hello,

I made some sequence diagrams to explain the problem more clearly:

![image](https://github.com/Azure/azure-iot-sdk-c/assets/2964297/10ad9364-ab26-4afd-9e49-e7d96d818055)

And the modification I made:

![image](https://github.com/Azure/azure-iot-sdk-c/assets/2964297/c304ad3c-58ed-4649-b1d7-148e632b1606)

**Comment by ewertons** [comment]
Hi @pulkomandy , I was investigating this latest issue and I think I got it wrong the first time. 
For iothub_client_core, this should be the logic:
- Capture the last callback invocation from IoTHubClientCore_LL_UploadMultipleBlocksToBlob (uploadToBlobMultiblockCallbackWrapper) or IoTHubClientCore_LL_UploadMultipleBlocksToBlobEx (uploadToBlobMultiblockCallbackWrapperEx), **no matter the result** - name it `blobStorageResult`
- Save the result of the upload to blob API call (IoTHubClientCore_LL_UploadMultipleBlocksToBlob or IoTHubClientCore_LL_UploadMultipleBlocksToBlobEx) - name it `result`
- In uploadMultipleBlock_thread, after the upload to blob API call, if `result` is IOTHUB_CLIENT_OK and `blobStorageResult` is FILE_UPLOAD_OK, invoke threadInfo->uploadBlobMultiblockSavedData.getDataCallback (or Ex) with FILE_UPLOAD_OK. Otherwise invoke it with FILE_UPLOAD_ERROR


That way, for the convenience layer the final callback will always be called after the whole upload to blob logic is completed. I'll post a PR with those changes, once I do that could you please validate it as well before we merged it?

**Comment by pulkomandy** [comment]
Hello,

Thanks for the update.

The solution you describe seems fine to me, and may be a bit simpler than what I suggested in my merge request. I am out of office this week, but that isn't a problem, let me know when you have a patch ready for testing and I'll forward it to my colleagues, or look into it when I'm back.

It will take some time before we ship a release to our customer and they are able to test it. Unfortunately, we could reproduce these problems only with on-the-field device and not with our testing platform.

**Comment by ewertons** [comment]
This is the initial PR.
https://github.com/Azure/azure-iot-sdk-c/tree/ewertons/FixThreadedUploadToBlob

I could not run our pipeline against it yet, but it worked locally in my sample run.

**Comment by ewertons** [comment]
PR https://github.com/Azure/azure-iot-sdk-c/pull/2615 posted and pipeline tests run. Please review if possible, we will be merging it soon.

**Comment by ewertons** [comment]
HI @pulkomandy,
The PR with the fix has been merged.
Please let us know if you have any other feedback. Feel free to reopen this case if you need to.
And thank you once more for your contributions, we really value your feedback and investment in this project.
Thanks,
Azure IoT SDKs Team
