### ISSUE TITLE
URL encoded properties map in messages

### ISSUE THREAD

**Issue by alexmrtn** [Azure/azure-iot-sdk-c#257]
- **OS and version used:** Ubuntu 16.04 

- **SDK version used:** 2017-10-09 

# Description of the issue:
We use the MQTT transport protocol and messages sent from cloud to device contains URL encoded properties. 

When we receive the message on the device, we get a `IOTHUB_MESSAGE_HANDLE` and it contains the properties in a `MAP_HANDLE`. We fetch the key/value pairs and the obtained strings are still URL encoded : 

> MAP_HANDLE properties = IoTHubMessage_Properties(p_message);
const char* const * keys = NULL;
const char* const * values = NULL;
size_t propertyCount = 0;
Map_GetInternals(properties, &keys, &values, &propertyCount );

The SDK does not contain any `IoTHubMessage_GetPropertiesMap(properties, &keys, &values, &propertyCount)` function that could give us the decoded properties strings. 

Currently, the device has to decode the strings, it is the correct behavior ? As we send the string non-encoded from the cloud, I think the device should receive it non-encoded as well. 

Adding this capability will also solve the similar problem we have if we try to send a message with non encoded string in properties.

Thanks,
Alexis.

**Comment by ewertons** [comment]
Hi @alexmrtn ,
indeed the client as of now does not decode the content it receives from the cloud.
It seems correct that the properties should be presented URL-decoded, so the issue you are presenting would be a bug in the client.
We will reply back when we have an estimate for the fix.

**Comment by alexmrtn** [comment]
Thanks @ewertons !
Let me know when you have an estimate for the fix and if I can help in any way.

**Comment by ewertons** [comment]
Hi @alexmrtn ,
to have this issue fixed we need the following:
1. Implement the APIs to decode URLs (in [azure-c-shared-utility](https://github.com/Azure/azure-c-shared-utility/blob/69ac01eda585d90ddf1f7d675f92a3795a6b377f/inc/azure_c_shared_utility/urlencode.h));
2. Use those APIs in the MQTT transport when handling the maps properties.

We still do not have an ETA for this fix.
If you have opportunity and would like to give it a stab, please feel free to send us a PR.
Otherwise, we will update you again once we have an ETA.

**Comment by jebrando** [comment]
@alexmrtn the sdk uses properties as pass through and does not modify them.  If the property is url encoded the sdk will not inspect the data.  If you have any more issues please reopen this issue.

**Comment by alexmrtn** [comment]
Hi @jebrando 

I double checked the behavior and we definitely have the issue here:

When I send a message with properties using the Azure portal, the properties are URL encoded.

Let's suppose I send a message that contains a property with special characters ( ':' '/' ' ' ...) 
![screenshot from 2018-02-06 16-57-28](https://user-images.githubusercontent.com/9555254/35869315-0a7a39f2-0b5f-11e8-8a35-a81fe187c879.png)

This is what I obtain in the value property map: `http%3A%2F%2Fmicrosoft.com`

In the `extractMqttProperties` function of the `iothubtransport_mqtt_common.c` file the parameter `topic_name` is the following string:

```
topic_name=0x7fffec015ee0 "devices/alex/messages/devicebound/%24.to=%2Fdevices%2Falex%2Fmessages%2FdeviceBound&test=http%3A%2F%2Fmicrosoft.com"
```
and then line 1108 the extracted token is copied in the buffer as is (using the % string format).

As properties are passed in the topic name, it seems fair that those strings are URL encoded to prevent any errors. But from my point of view, the device should receive the string as it was sent, without any changes.
In addition, using AMQP protocol the obtained string is non-encoded. Thus there is a consistency problem here between different transport protocols.

We still need to use a workaround on our side to fix this problem. We are ready to help you to implement the fix as a PR. Maybe you can guide us for this?

Thanks, Alexis.
