### ISSUE TITLE
LTS_03_2024 release/tag not part of lts_03_2024 branch

### ISSUE THREAD

**Issue by JanZachmann** [Azure/azure-iot-sdk-c#2595]
We use LTS releases in our cicd and recognized for the first time that the [release tag](https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_03_2024) is not part of the corresponding [lts branch](https://github.com/Azure/azure-iot-sdk-c/tree/lts_03_2024).

Why was this changed compared to previous LST releases?

**Comment by ewertons** [comment]
Hi @JanZachmann , for the past two releases (including this last one), we have not created a branch for LTS unless we need to port security fixes until that release gets [expired](https://github.com/azure/azure-iot-sdk-c?tab=readme-ov-file#lts-schedule).
Branch lts_03_2024 was created apparently by mistake by a stale script and has now been removed.
Please use the git tag to reference the [latest release](https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_03_2024).

I do realize that the [instructions for how our releases are done](https://github.com/azure/azure-iot-sdk-c?tab=readme-ov-file#release-example) has not been updated, which I will do briefly.

**Comment by JanZachmann** [comment]
@ewertons why did you change the workflow again? pls. be aware that there are depending projects that always have to adapt due to your changes as well. I really would appreciate a more stable process!

Regards
Jan
