### ISSUE TITLE
A way to query IoT Hub from device and get response?

### ISSUE THREAD

**Issue by aleksandarkrstic** [Azure/azure-iot-sdk-c#2611]
Hello,

I am using Azure C SDK to connect my device to IoT Hub and must say that everything is working fine for me and I didn't have any problems. However, I was wondering if there is a way to invoke some service or query IoT Hub from device side and get response (something similar to Direct Method but not cloud to device, rather like device to cloud "Direct Method" where device can query some service on the IoT Hub and get response as string for example)? Is that possible and how?

Thanks in advance.

**Comment by ericwol-msft** [comment]
although the [iothub_service_client](https://github.com/Azure/azure-iot-sdk-c/tree/main/iothub_service_client) is depercated in this SDK, it's still functional. There are no current plans to remove this, other than no new hub features will be added. 

Sample:
https://github.com/Azure/azure-iot-sdk-c/blob/main/iothub_service_client/samples/iothub_devicemethod_sample/iothub_devicemethod_sample.c

**Comment by aleksandarkrstic** [comment]
Thanks, but isn't this still Cloud to Device direct method but from back-end app?
I am looking for a way to "invoke" some "method" on IoT Hub and get response from IoTHub Client SDK if possible.

**Comment by ericwol-msft** [comment]
Are you looking for Azure Functions?

https://azure.microsoft.com/en-us/products/functions

**Comment by ericwol-msft** [comment]
https://learn.microsoft.com/en-us/training/modules/intro-azure-functions-iot/

**Comment by ewertons** [comment]
Closing this issue based on the last instructions from @ericwol-msft 
Please feel free to reopen this issue if you would like to follow up.
Thanks,
Azure IoT SDK Team
