### ISSUE TITLE
Error while processing: __float128 is not supported on this target

### ISSUE THREAD

**Issue by Losdanmartin** [Azure/azure-iot-sdk-c#2617]
Hi I just wrote a code and bumped into this problem. I've never seen a bug like this before please help me, im a beginner

#include <iostream>
#include <string>
#include "Network.h"
#include "Host.h"

int main(){

Network network;

Router *router1 = new Router("192.168.0.1");
Router *router2 = new Router("192.168.1.1");
Router *router3 = new Router("192.168.2.1");

Host *host1 = new Host ("192.168.0.100");
Host *host2 = new Host ("192.168.0.101");
Host *host3 = new Host ("192.168.0.102");

router1->addDevice (host1);
router2->addDevice (host2);
router3->addDevice (host3);

network.addRouter(router1);
network.addRouter(router2);
network.addRouter(router3);

network.addHost(host1);
network.addHost(host2);
network.addHost(host3);

host1->sendPacket("Hi Host!", "192.168.0.102");        

}

**Comment by ewertons** [comment]
Hi @Losdanmartin ,
thank you for your question, but it unfortunately is not related to the product hosted by this repo.
We do understand your situation as we've all been there before, so as a recommendation please try posting your question on a more general forum like [StackOverflow](https://stackoverflow.com/). You will need to be more specific though, including which host are you compiling for and which compiler you are using.

Good luck!
Azure IoT SDKs Team.
