### ISSUE TITLE
documentation request - IoTHubClient_LL_SendEventAsync - when exactly is callback?

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#262]
IoTHubClient_LL_SendEventAsync method has a send confirmation callback. If I use MQTT protocol, when exactly is callback invoked? By default MQTT is at QOS 0 and so there is no delivery confirmation for this SDK. Does that only indicates written to the wire?

Also, when is the same callback invoked for HTTP protocol? Is it on an HTTP response?

**Comment by ewertons** [comment]
@kiranpradeep ,

across any protocol you use IoTHubClient_LL_SendEventAsync will fire the callback you provide after either:
a. With success result when the message has been successfully sent (through the wire and) to the IoTHub, or
b. With error result if the message fails to be sent (either by a bad connection or timeout).

**Comment by kiranpradeep** [comment]
@ewertons Thanks. But, that term "successfully sent" is ambiguous. Take two below protocols used by Azure IoT Hub.

1. HTTP - The SDK fires an HTTP request and get back an HTTP response. Is that callback invoked as early as you fire HTTP request? Or is it on success/failure HTTP response? 
2. MQTT with QOS 1 - Do you wait for MQTT PUBACK acknowledgment to invoke the callback? Or is it as early message is written to the wire.

**Comment by ewertons** [comment]
Answers:

The term "successfully sent" means "received a success response from the IoT Hub".
Whenever you receive a callback from the device client SDKs, if it is a success result, the message has successfully been received by the Azure IoT Hub.

1. On success/failure HTTP response;
2. MQTT transport uses only QOS 0. The callback is fired only after the PUB is acknowledged by the Azure IoT Hub.

Please let us know if we can help in any other way.

**Comment by kiranpradeep** [comment]
@ewertons Thanks for the reply. But two concerns still remaining. As per this Azure [document](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#using-the-mqtt-protocol-directly)

1. Agreed with success/failure part of HTTP. But, I am not aware of any acknowledgment([1](https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels)) for MQTT at QOS 0. What is this acknowledgment you are mentioning about for MQTT? 
2. MQTT transport uses QOS 1 as per the [document](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support). Is that document wrong?

**Comment by ewertons** [comment]
Sorry, I made a mistake. 
For telemetry the MQTT transport uses QOS 1 (DELIVER_AT_LEAST_ONCE).
The documentation is correct.

**Comment by ravitejaveeragandam** [comment]
Recently i started working on Azure IOT client and server communication. As part of this i am sending few messages from my device and receiving at server side which i am capturing using device explorer(TWIN). And also i am able to receive the data from server to client with no problem.

But i am failing in one scenario like Sending 20 bytes of data for every sec from client to server, the same time sending data to client continuously from server. Control is getting stuck in the function **"DoTimeouts"** and it is not coming out. **How to come out this function?**

And also what is the function need to use to set a callback function when timeouts?
