### ISSUE TITLE
Why does `LTS_08_2024` not have a new version number?

### ISSUE THREAD

**Issue by Timple** [Azure/azure-iot-sdk-c#2642]
I would expect a version bump to 1.14.0 or something similar.

Or am I misunderstanding your versioning scheme?

**Comment by ewertons** [comment]
The LTS is cut from the current version in main. Then main is moved to a new version.

https://github.com/azure/azure-iot-sdk-c?tab=readme-ov-file#release-example

"July 9, 2020: A new LTS release occurs. A new release is created, the version remains 1.9.0, and the LTS release is tagged LTS_07_2020. The main branch bumps to 1.10.0 and is tagged 1.10.0."

**Comment by ewertons** [comment]
We treat main branch as a development (dev) branch.

**Comment by Timple** [comment]
Ah, alright 

> A new LTS release occurs. A new release is created, the version remains 1.9.0, and the LTS release is tagged LTS_07_2020. The main branch bumps to 1.10.0 and is tagged 1.10.0."

This still sounds like a new tag should have been created on the main branch 🙂

**Comment by ewertons** [comment]
You are correct. As far as I can see, the new tag is there:
https://github.com/Azure/azure-iot-sdk-c/tree/1.14.0 
 
If it is not what you were expecting, please elaborate.

**Comment by Timple** [comment]
Ah, I guess I was a bit impatient. Thank you!

**Comment by ewertons** [comment]
No problem at all. Thanks for checking it out, it made us double-check our release and that's always a good thing. Much appreciated.
