### ISSUE TITLE
Get error when run build_all\windows\build.cmd -c

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-iot-sdk-c#27]
Seems the default platform Win32 is not valid for some projects, I have to specify --platform x86/x64 to work around.

1>Project "D:\IoT\azure-iot-develop\serializer\samples\remote_monitoring\windows\remote_monitoring.sln" on node 1
       (Clean target(s)).
     1>D:\IoT\azure-iot-develop\serializer\samples\remote_monitoring\windows\remote_monitoring.sln.metaproj : error MSB
       4126: **The specified solution configuration "Debug|Win32" is invalid**. Please specify a valid solution configurati
       on using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Plat
       form="Any CPU") or leave those properties blank to use the default solution configuration. [D:\IoT\azure-iot-dev
       elop\serializer\samples\remote_monitoring\windows\remote_monitoring.sln]

**Comment by anhashia** [comment]
Investigating !

**Comment by anhashia** [comment]
Hi @erich-wang 
There are 2 ways to build these solutions

1.) Directly opening .SLN file that is in the GitHub repository

**Example**
https://github.com/Azure/azure-iot-sdk-c/blob/master/serializer/samples/remote_monitoring/windows/remote_monitoring.sln
This as x86 and x64 as active solution platform.

2.) The other is open azure_iot_sdks.sln   after running the **build.cmd** command with vaiorus build options By default it creates Win32

This will create ) cmake\iotsdk_win32 folder (as an example)
\azure-iot-sdk-c\cmake\iotsdk_win32\azure_iot_sdks.sln which has all projects.
If you do it via #2, you will get Win32 solution as a default for build,cmd

You need to open 
F:\works\azure-iot-sdk-c\cmake\iotsdk_win32\azure_iot_sdks.sln in VS 2015 and select remote monitoring project to should see **Win32** as Active Solution Platform option.

**Log snippet below for reference**
````
28>------ Rebuild All started: Project: remote_monitoring, Configuration: Debug Win32 ------
28>  remote_monitoring.vcxproj -> F:\works\azure-iot-sdk-c\cmake\iotsdk_win32\serializer\samples\remote_monitoring\Debug\remote_monitoring.exe
````

**Comment by anporumb** [comment]
Closing this, Please reopen if you still have the issue.

Best Regards,
Andrei Porumb
