### ISSUE TITLE
DPS registration failed ERROR in dps_client_sample 

### ISSUE THREAD

**Issue by LeonardBae** [Azure/azure-iot-sdk-c#271]
I tested IoT Hub Device Provisioning Services using azure-iot-sdk-c.
However, the SDK that worked well until last week does not work from yesterday. I did not change the source.
When I ran dps_client_sample in SDK, the following error occurred.
Do you have something to refer to?

[192.168.xxx.xxx]: PS C:\windows\system32> .\dps_client_sample.exe
   DPS Version: 1.1.01

Iothub Version: 1.1.22

DPS Status: DPS_REGISTRATION_STATUS_CONNECTED

PUT /0ne00000XXX/registrations/6rek5qncnygnkzflohxz4u6zlfly6ktm4klsc7xrbgvesqyllnfa/register?api-version=2017-08-31-preview HTTP/1.1

UserAgent: iothub_dps_client/1.0

Accept: application/json

Connection: keep-alive

Content-Type: application/json; charset=utf-8

Host: global.azure-devices-provisioning.net:443

Content-Length: 926

len: 926

{"registrationId":"6rek5qncnygnkzflohxz4u6zlfly6ktm4klsc7xrbgvesqyllnfa","tpm":{"endorsementKey":"AToAAQALAAMAsgAgg3GXZ0SEs/gakMyNRqXXJP1S124GUgtk8qHaGzMUaaoABgCAAEMAEAgAAAAAAAEAopqgkUBwtpr1sCgVJcEZxsJtpmtOAt9K7SjGFe4hsp6DJ/dd2E5UFzBC+Jp8Fzqf5ukRBkqrAgIuAvHRsruIedk1uarJSLhbDpFLHxFd7iDNcYfrvdgVNT2T9zrvkh2y04WuRQg2D5qf0tZF82jeTjR/YJK7uWhaRwWOwZ3b1XD9l6wFOrwK/Ic0PEsjneFXQzL0n9uKyuHmHNz+wHppmOiMAabvnXXEin9ou7/iowY/+YhFm3j7atsVvxMI5HEM3Mq+W4imUuzPxVX7fZH+oWPKP5ofpWBTf+MdttGby1AjGnv8JE69JriOYoZG2/4qbsfv9M7a7NFrBlaW7Rt36w==", "storageRootKey":"ARoAAQALAAMEcgAAAAYAgABDABAIAAAAAAABAOf8RazECx9w/lWBGgCjWhrGX5pnPf67Az529esaeO/1pZtB6lQ7+8S1ezJfB0oiP16NoFxV6ay8lX+e/T6elEsCDpg9sHKji818729QdEidorKfxmTsnClHugTUe7nmaHGNZvqSKVJY2LfVSlHSaPgNmhZtIcsUefzV8fUBTxWSK57fXRfBMCXsE+nCz4dOqZ+VADhk4Lg6PI/RvxFPjUbUElsbmvAEZoyvgkRlPcmKkr+aQDoXTHVM6LjJ4nFe45uQ+gjMuGCVkWGpQ/ZfZNy9ZNHvaDaW0d1C++KBn95ymhYTS29tTDVKhfUJ/c1xuAu61IBNXt9uyoRJ9QuvVVU="}}

Reply Status: 401

Content Len: 1383

{"message":"Authorization required, resend request using supplied key","authenticationKey":"ADQAIJcwySGrzNbl/gPEYZQrxRqyhQfuETFzO6NF7Sd64P6ca2kvW7spPBVEOodYZgzp/5dvAQAVfZDF6Me2IIB1kE5Ed0H3YMqeMEKH+NOBHZbD5zvJ/440P+P+0l4fuId49X4a/hnJ+TpxUb6MHk9MR/PqmfpyMV3EOYH1ur0QrMHxleue3SgucxU6PepjG/HXz8QH4yk7zXCI0GzhP6ccAVwiSNPB4szxxqlTaKxjKPy7akrVjNl7UwUwACsSr1NaCn4V+fbxUeveB5xSoOOopE3flKtpwLvfMoLlDduEEtAQ5Ejmsv+Y6KJgxV+pfBzVVrK+QLKKkA40TZUpvZWfo5XsAsysc1UJvvcdHKXJneDWDGV9LuU7Xq19mnQj6m0b8jSFtKwqxTVDpn4WAYZobIAMSe3oAI4AILxo4BNhMqnpiHapPwtmr+yFpOWeCoKMwBI/gyO298GEoszxVxMcRhPxjlKG0UaRRRhEzG0kxVON6EYmcBALt+QoeknSGPJG4gOPEHjrLCPmaONUfI9aB2qv7k3zsgX7iMC7CDc34zfMDzNveElfoyCKVZBZ7HpdkxnyhZFTFJQ16QcJ6KelkcIrcCTUAQCU48ZV5rs159IN27tspruzzCcbSO9ms3tKhiMdJFtVx6YAvsR/PiS6DZ7uJAjIwd8o0oMooECezitbYNuvfAhC7vTm4yraEU53h/mvW+hxLwWeI6eBCnT5NO1v1N8Shk6+SVcfUFxYMOc1g1DH0l+U66msHYJN/qmpQsuSA3siC3qCKG5UvDWLKmwZFM7ZKEZdK4++pE0ZZVqDgW7gMKUocJourcY1cxfplTTgbHi+3pbAjqMgwmlI7B1bQtJqcHYFJprJnVkQe2xorpuAiFlFxiUdkp1QOB3iAZGMwjWFYI19AEajsKXLQ2ERljP0o6J9lxZR8oMS9++fBXLnp3iAADAACAALAAQEQAAAAAUACwAghgoQbA0ynntsOS93soob9UM0ukR4WB+Pgl3ffVauuJwAtEtHXH1SQj9T43VvUqkak+9mm0x8vB9rSUVETiDefw3OojNjt3yx6yFGraZMK+tCzIRpNay1IY3p0k6C35XKpU5yH0ARwD6Bgeu89tzeYPZhW0hAjtwjwsQZ870aFaugkU5aIXuiy6ztBUae/cHTywKeyZ/g5VCT0WQhzBMlPtf7dyUQAGId45pAWNvdNBHfjHX+Y7125zeZari0SdS3X5i0j5GChBzVxYd/YsZfv2rxs3F+vg==","keyName":"registration"}

Error: Time:Mon Oct 23 21:19:39 2017 File:C:\iot-azure-dps-client\deps\azure-iot-sdk-c\dps_client\adapters\dps_hsm_tpm.c Func:insert_key_in_tpm Line:348 Failed Load Id key.

Error: Time:Mon Oct 23 21:19:39 2017 File:C:\iot-azure-dps-client\deps\azure-iot-sdk-c\dps_client\adapters\dps_hsm_tpm.c Func:dps_hsm_tpm_import_key Line:582 Failure inserting key into tpm

Error: Time:Mon Oct 23 21:19:39 2017 File:C:\iot-azure-dps-client\deps\azure-iot-sdk-c\dps_client\src\dps_sec_client.c Func:dps_sec_import_key Line:344 failure importing key into tpm

Error: Time:Mon Oct 23 21:19:39 2017 File:C:\iot-azure-dps-client\deps\azure-iot-sdk-c\dps_client\src\dps_client.c Func:dps_transport_challenge_callback Line:161 Failure to import the dps key

Error: Time:Mon Oct 23 21:19:39 2017 File:C:\iot-azure-dps-client\deps\azure-iot-sdk-c\dps_client\src\dps_transport_http_client.c Func:dps_transport_http_dowork Line:925 NULL sas_token provided in challenge callback.

Error: Time:Mon Oct 23 21:19:39 2017 File:C:\iot-azure-dps-client\deps\azure-iot-sdk-c\dps_client\src\dps_client.c Func:on_transport_registration_data Line:463 Failure retrieving data from the dps service

Failure encountered in DPS info DPS_ERROR_TRANSPORT

DPS registration failed!

Press any key to continue:

**Comment by jebrando** [comment]
@LeonardBae Are you using an hardware tpm or tpm simulator?

**Comment by LeonardBae** [comment]
Hi jebrando,
i'm using an hardware tpm.
This issue is the same as the issue I asked below.
Could you please answer the last answer I asked in the issue below?
https://github.com/Azure/azure-iot-sdk-c/issues/294

**Comment by jebrando** [comment]
Yes, I have been working to repo this, but I have been unable to get it working.  I will continue to try with a new desktop on 11/28.  I will close this one and track on issue #294

**Comment by LeonardBae** [comment]
Thanks jebrando,

What I really want is to register the DPS on an x64-based system with an INTC's TPM(hardware TPM).
