### ISSUE TITLE
unable to  register device in IoT Hub using dps_client(x509) 

### ISSUE THREAD

**Issue by lakshmisivareddy** [Azure/azure-iot-sdk-c#273]
i am facing with bellow error .

Setting Certificates
   DPS Version: 1.1.01
Iothub Version: 1.1.24
DPS Status: DPS_REGISTRATION_STATUS_CONNECTED
PUT /0ne00000E59/registrations/riot-device-cert/register?api-version=2017-08-31-preview HTTP/1.1
UserAgent: iothub_dps_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
Content-Length: 39

len: 39
{ "registrationId":"riot-device-cert" }

Reply Status: 202
Content Len: 92
{"operationId":"riot-device-cert.bbd1c883-da07-4d2e-b82b-9c319e1c3b34","status":"assigning"}
DPS Status: DPS_REGISTRATION_STATUS_ASSIGNING
GET /0ne00000E59/registrations/riot-device-cert/operations/riot-device-cert.bbd1c883-da07-4d2e-b82b-9c319e1c3b34?api-version=2017-08-31-preview HTTP/1.1
UserAgent: iothub_dps_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
Content-Length: 0

Reply Status: 200
Content Len: 385
{"operationId":"riot-device-cert.bbd1c883-da07-4d2e-b82b-9c319e1c3b34","status":"failed","registrationStatus":{"registrationId":"riot-device-cert","createdDateTimeUtc":"2017-10-24T09:26:00.9944915Z","status":"failed","lastUpdatedDateTimeUtc":"2017-10-24T09:26:01.5000365Z","errorCode":401002,"errorMessage":"CA certificate not found","etag":"\"00003956-0000-0000-0000-59ef07270000\""}}
Error: Time:Tue Oct 24 14:55:23 2017 File:/home/test/iot-edge-dp/azure-iot-sdk-c/azure-iot-sdk-c/dps_client/src/dps_client.c Func:dps_transport_process_json_reply Line:393 Unsuccessful json encountered: {"operationId":"riot-device-cert.bbd1c883-da07-4d2e-b82b-9c319e1c3b34","status":"failed","registrationStatus":{"registrationId":"riot-device-cert","createdDateTimeUtc":"2017-10-24T09:26:00.9944915Z","status":"failed","lastUpdatedDateTimeUtc":"2017-10-24T09:26:01.5000365Z","errorCode":401002,"errorMessage":"CA certificate not found","etag":"\"00003956-0000-0000-0000-59ef07270000\""}}
Error: Time:Tue Oct 24 14:55:23 2017 File:/home/test/iot-edge-dp/azure-iot-sdk-c/azure-iot-sdk-c/dps_client/src/dps_transport_http_client.c Func:dps_transport_http_dowork Line:959 Unable to process status reply
Error: Time:Tue Oct 24 14:55:23 2017 File:/home/test/iot-edge-dp/azure-iot-sdk-c/azure-iot-sdk-c/dps_client/src/dps_client.c Func:on_transport_registration_data Line:456 Failure retrieving data from the dps service
Failure encountered in DPS info DPS_ERROR_TRANSPORT
DPS registration failed!

**Comment by AndyLiTaiwan** [comment]
I also have the same issue...
I have upload the Root cerwhich provided by sample(Provision_Tools/dice_device_enrollment) to DPS and IoTHub, and make sure the status of certificate is Verified. 

![image](https://user-images.githubusercontent.com/23305864/32928600-92603edc-cb8d-11e7-8f8a-5bf26e5f000f.png)

Then set the Enrollment Groups' rule by using this certificate and run the sample(Provision_Samples/prov_dev_client_sample). Below is my execution log :
Provisioning API Version: 1.1.01
Iothub API Version: 1.1.27

Registering... Press any key to interrupt.

Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED

Registration status: CONNECTED
PUT /0ne00002A95/registrations/riot-device-cert/register?api-version=2017-08-31-preview HTTP/1.1
UserAgent: prov_device_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
Content-Length: 39


len: 39
{ "registrationId":"riot-device-cert" }


HTTP Status: 202

Date: Fri, 17 Nov 2017 03:24:35 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Location: https://global.azure-devices-provisioning.net:443/MY_ID_Scope/registrations/riot-device-cert/register
x-ms-request-id: b6bf829e-c8a2-4626-848f-5397581d84e0
Strict-Transport-Security: max-age=31536000; includeSubDomains

{"operationId":"0.riot-device-cert.913b2474-0bae-4ec9-8dd0-99773ffcb0ab","status":"assigning"}

Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING

Registration status: ASSIGNING
GET /MY_ID_Scope/registrations/riot-device-cert/operations/0.riot-device-cert.913b2474-0bae-4ec9-8dd0-99773ffcb0ab?api-version=2017-08-31-preview HTTP/1.1
UserAgent: prov_device_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
Content-Length: 0



HTTP Status: 202

Date: Fri, 17 Nov 2017 03:24:35 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Location: https://global.azure-devices-provisioning.net:443/MY_ID_Scope/registrations/riot-device-cert/operations/0.riot-device-cert.913b2474-0bae-4ec9-8dd0-99773ffcb0ab
Retry-After: 3
x-ms-request-id: f8b09ff0-3a79-4796-bb64-b6dbce27255c
Strict-Transport-Security: max-age=31536000; includeSubDomains

{"operationId":"0.riot-device-cert.913b2474-0bae-4ec9-8dd0-99773ffcb0ab","status":"assigning","registrationStatus":{"registrationId":"riot-device-cert","status":"assigning"}}

Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING

Registration status: ASSIGNING
GET /MY_ID_Scope/registrations/riot-device-cert/operations/0.riot-device-cert.913b2474-0bae-4ec9-8dd0-99773ffcb0ab?api-version=2017-08-31-preview HTTP/1.1
UserAgent: prov_device_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
Content-Length: 0

HTTP Status: 200

Date: Fri, 17 Nov 2017 03:24:38 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
x-ms-request-id: 1b14b235-1249-4924-9132-66aa8b0b76dc
Strict-Transport-Security: max-age=31536000; includeSubDomains

{"operationId":"0.riot-device-cert.913b2474-0bae-4ec9-8dd0-99773ffcb0ab","status":"failed","registrationStatus":{"registrationId":"riot-device-cert","createdDateTimeUtc":"2017-11-17T03:24:35.5024158Z","status":"failed","lastUpdatedDateTimeUtc":"2017-11-17T03:24:35.5110061Z","errorCode":401002,"errorMessage":"CA certificate not found","etag":"\"00002702-0000-0000-0000-5a0e56730000\""}}

Error: Time:Fri Nov 17 11:24:38 2017 File:C:\Users\Andy\Documents\GitHub\azure-iot-sdk-c\provisioning_client\src\prov_device_ll_client.c Func:_prov_transport_process_json_reply Line:386 Unsuccessful json encountered: {"operationId":"0.riot-device-cert.913b2474-0bae-4ec9-8dd0-99773ffcb0ab","status":"failed","registrationStatus":{"registrationId":"riot-device-cert","createdDateTimeUtc":"2017-11-17T03:24:35.5024158Z","status":"failed","lastUpdatedDateTimeUtc":"2017-11-17T03:24:35.5110061Z","errorCode":401002,"errorMessage":"CA certificate not found","etag":"\"00002702-0000-0000-0000-5a0e56730000\""}}
Error: Time:Fri Nov 17 11:24:38 2017 File:C:\Users\Andy\Documents\GitHub\azure-iot-sdk-c\provisioning_client\src\prov_transport_http_client.c Func:_prov_transport_http_dowork Line:946 Unable to process status reply
Error: Time:Fri Nov 17 11:24:38 2017 File:C:\Users\Andy\Documents\GitHub\azure-iot-sdk-c\provisioning_client\src\prov_device_ll_client.c Func:_on_transport_registration_data Line:449 Failure retrieving data from the provisioning service

**Comment by jebrando** [comment]
A fix is has been added to the repo in this commit 8b8cba3

**Comment by joergjo** [comment]
Can somebody confirm that this actually works? Like Andy, I was able to provision and verify my root cert, but I still get "CA certificate not found" in both `prov_dev_client_ll_sample` and `prov_dev_client_sample`.

**Comment by tojuasp** [comment]
Enrollment group provisioning only seems to work now if the device certificate is signed with the Root CA cert. All the tutorials and tools instruct / use the intermediate cert to sign the device certificate but this does not work.

**Comment by Mandur** [comment]
Hello, I am encountering exactly the same issue, even with the fix detailed above. I tried from the node sdk and my certificates work perfectly. I also try certificate generated directly from the root CA, but I still get this error, did any of you managed to find a solution?

**Comment by lakshmisivareddy** [comment]
Hi 
i fixed the issue

**Comment by MZDN** [comment]
> Hi
> i fixed the issue

Hi,
how did you fix this issue?
Thanks in advance

**Comment by shruthika-ziosk** [comment]
I have same error. "CA certificate not found".. created certs using this instructions. https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md

Can anyone help me how to fix that?
