### ISSUE TITLE
MQTT keeplivetimer PING response

### ISSUE THREAD

**Issue by DandelionWenjing** [Azure/azure-iot-sdk-c#275]
Hi,
When we use MQTT client to connect to iothub , in the keep Alive Time,  the client will send PING request to the server similar to the heart rate data, how many times does the server receive heart rate data before it send to the client response? Once or a few times? 
Because when it is once, the disconnect will be of frequent occurrence when the network instability. if so, how can we change the times? Thanks a lot.

- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by ewertons** [comment]
Hi @DandelionWenjing 

The default keep alive frequency is defined [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L41).

#define DEFAULT_MQTT_KEEPALIVE              4*60 // 4 min

And it is passed from the MQTT transport layer to the MQTT client through these calls:
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L1993
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L1769
https://github.com/Azure/azure-umqtt-c/blob/c22a4c7995a397442e2043b8e95f3602539074cc/src/mqtt_client.c#L560

**Comment by ewertons** [comment]
You can modify the Keep Alive value for MQTT using the following call:

```c
#include "iothub_client_options.h"
...
uint16_t keepAliveFreqInSecs = 60; // every 1 minute
IoTHubClient_SetOption(iotHubClientHandle, OPTION_KEEP_ALIVE, keepAliveFreqInSecs);

// Do not forget to check the result from IoTHubClient_SetOption.
```

Be mindful that increasing this value makes the IoTHub client reconnection slower.

Also, just to mention, the parameters for AMQP are different.

**Comment by ewertons** [comment]
Hi @DandelionWenjing ,

I will close the issue. If you have further questions on this topic please feel free to reopen it, or open a new one if you would like to follow up on any other issue.

Thanks for using the Azure IoT SDKs!

**Comment by DandelionWenjing** [comment]
Thanks for answering.
