### ISSUE TITLE
Device connects to the IoT Hub with TLS certificate

### ISSUE THREAD

**Issue by v-liujxu** [Azure/azure-iot-sdk-c#277]
- **OS and version used:** Windows 10 

- **SDK version used:** c345373 

# Description of the issue:

I test the two projects(iothub_client_sample_mqtt and iothub_client_sample_mqtt) with using trusted certificates, the application works fine,and I can receive messages from IoT Hub by Device Explorer.
But I tried to modified the certificates in certs.c, it seems that it does not impact the connection and message transport whatever I changed the variable certificates, such as empty string.

Im confused about this option for TLS, and how to generate the certificates.

# Code sample exhibiting the issue:
            // For mbed add the certificate information
            if (IoTHubClient_LL_SetOption(iotHubClientHandle, OPTION_TRUSTED_CERT, certificates) != IOTHUB_CLIENT_OK)
            {
                printf("failure to set option \"TrustedCerts\"\r\n");
            }

# Console log of the issue:

**Comment by markrad** [comment]
Hi @v-liujxu,

You need to be a little more specific. I would expect the connection to fail only if you corrupted the Baltimore certificate. I don't believe the intermediate certificates in that list are necessary on most platforms and will be ignored. Sending an empty string, I would suggest, likely tells the SSL layer to ignore any certificates passed and rely upon the certificate store.

If you corrupt the Baltimore certificate and it will still successfully connects I would be surprised. If this is the case please let us know and I will take a look at it.

_Mark Radbourne MSFT_

**Comment by ewertons** [comment]
Hi @v-liujxu ,
this issue will be closed, but please feel free to reopen it once you have more details (see the comment from @markrad ).
Thanks,
Azure IoT SDK Team

**Comment by v-liujxu** [comment]
OK,Thanks.
