### ISSUE TITLE
Questions about the parameter of times of MQTT PING request lost before device is considered offline

### ISSUE THREAD

**Issue by THULiusj** [Azure/azure-iot-sdk-c#279]
- **OS and version used:** <Ubuntu 16.04>

- **SDK version used:** <c sdk latest>

# Description of the issue:
I know that  MQTT will send PING request to the IoT Hub like a heartbeat. And in the c sdk, the default timer is 4 minutes. But how many times of MQTT PING request lost will the IoT Hub considers the device is offline, and how to change this parameter?

**Comment by ewertons** [comment]
Hi @THULiusj ,

MQTT transport sends pings every 4 minutes, and it triggers a reconnection if a ping response is not received within 4 minutes.
So using the default values the MQTT transport might take up to 7 minutes, 59 seconds to detect a connection failure.

The frequency can be changed for MQTT transport using the following option:

```c
#include "iothub_client_options.h"
...
int mqttPingFreqInSecs = 60;
IoTHubClient_SetOption(iotHubClientHandle, OPTION_KEEP_ALIVE, &mqttPingFreqInSecs);
```

[This](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L2668) is the code that consumes the option.

**Comment by ewertons** [comment]
This question had already been posted in our repo. 
https://github.com/Azure/azure-iot-sdk-c/issues/275

**Comment by THULiusj** [comment]
Hi, if I use Python SDK, then how can I modify this parameter?
Thanks

**Comment by THULiusj** [comment]
Find the function in Python SDK, close this issue.
