### ISSUE TITLE
Messages come back with data length 0

### ISSUE THREAD

**Issue by basyskom-engelke** [Azure/azure-iot-sdk-c#28]
Hello,

When building the iothub_client_sample_mqtt messages get sent and arrive on the server but aren't coming back. When sending messages using iothub_messaging_sample. The client sample receives them but has a PAYLOAD_LEN of 0, so no data is displayed.

Do you have any idea why this could be happening or how to fix it?
Is there any way to check what the package contains when it's being sent to check if it actually contains data or view the data on IoT-Hub?

I have built the SDK myself.
Azure IoT-Hub was set up with the guide from your documentation.

```
Info: IoT Hub SDK for C, version 1.1.3

<- 10:21:28 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE = 0x01 | TOPIC_NAME: devices/xxxx/messages/devicebound %24.to=%2Fdevices%2Fxxxx%2Fmessages%2FdeviceBound | PACKET_ID: 27 | PAYLOAD_LEN: 0
Received Message [1] with Data: <<<>>> & Size=0
```

gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

**Comment by markrad** [comment]
Investigating this.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @basyskom-engelke,

I am unable to reproduce this issue. I ran the iothub_client_sample_mqtt and then the iothub_messaging_sample. Here is the output I observed:

```
<- 16:34:21 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE = 0x01 | TOPIC_NAME: devices/cTest/messages/devicebound/%24.to=%2Fdevices%2FcTest%2Fmessages%2FdeviceBound | PACKET_ID: 3 | PAYLOAD_LEN: 43
Received Message [0] with Data: <<<{"deviceId":cTest,"windSpeed":10.00, "i":0}>>> & Size=43
<- 16:34:21 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE = 0x01 | TOPIC_NAME: devices/cTest/messages/devicebound/%24.to=%2Fdevices%2FcTest%2Fmessages%2FdeviceBound | PACKET_ID: 4 | PAYLOAD_LEN: 43
Received Message [1] with Data: <<<{"deviceId":cTest,"windSpeed":10.00, "i":1}>>> & Size=43
<- 16:34:21 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE = 0x01 | TOPIC_NAME: devices/cTest/messages/devicebound/%24.to=%2Fdevices%2FcTest%2Fmessages%2FdeviceBound | PACKET_ID: 5 | PAYLOAD_LEN: 43
Received Message [2] with Data: <<<{"deviceId":cTest,"windSpeed":10.00, "i":2}>>> & Size=43
```

I would suggest you make sure you have the very latest copy of the GitHub repository master branch from https://GitHub.com/Azure/Azure-iot-SDK-C.git, rebuild and try running your test again. You might also try the "Messages To Device" feature in the Device Explorer if you have a Windows machine. You can find this tool here: https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer.

_Mark Radbourne MSFT_

**Comment by basyskom-engelke** [comment]
Hi,

Thank you. Could you tell me what the minimum configuration / setup for the IoT-Hub is to run these examples? Because I just updated everything to the most recent version and the error remains.

I went through your documentation of the setup steps.
The Device explorer is quite useless because no matter which connection string of the users I enter it exceptions out with "unauthorized" which can't be because the same connection strings work fine with iothub-explorer under linux.

**Comment by anporumb** [comment]
@basyskom-engelke 

We need more information: how does your command line look like in Linux for sending the command? What version of iothub-explorer are you using for send-command? What's the commit-id for the C SDK? If you are using IoTHub explorer from the github repo, what's the commit-id of your clone?

Best Regards,
Andrei Porumb

**Comment by markrad** [comment]
Hi @basyskom-engelke,

Further to Andrei's comments above, other than modifying the connection strings in the two sample files, did you make any additional modifications to the code?

_Mark Radbourne MSFT_
