### ISSUE TITLE
Errors printed out in the standard output unconditionally, no way to disable them by the client of the azureiotsdk library

### ISSUE THREAD

**Issue by lukka** [Azure/azure-iot-sdk-c#282]
- **OS and version used:** Ubuntu 15.04

- **SDK version used:** 1.1.24

# Description of the issue:

```MULTITREE_RESULT MultiTree_GetChildByName(MULTITREE_HANDLE treeHandle, const char* childName, MULTITREE_HANDLE *childHandle)```

unconditionally prints out the following error in this code when the children with the given name is not found:

```LogError("(result = %s)", ENUM_TO_STRING(MULTITREE_RESULT, result));```

**Expected result:** no errors are printed out on standard output, and MULTITREE_CHILD_NOT_FOUND is returned. The caller can handle the case without writing an error on the output.

**Comment by ewertons** [comment]
Hi @lukka ,
just to confirm, are you experiencing this only on the Serializer module?

**Comment by lukka** [comment]
@ewertons you are perfectly right: the MultiTree TU is indeed contained into a submodule of this repository, should i move this issue over?

**Comment by ewertons** [comment]
Not at all. When I mentioned "module", I meant a .c file, not a git submodule.
This issue is on the right repo, I just wanted to confirm if you saw that only on the [Serializer client](https://github.com/Azure/azure-iot-sdk-c/tree/master/serializer).

**Comment by ewertons** [comment]
Would that address your issue?
Be mindful that disabling logging will make it near impossible to debug in case you have failures.

**Comment by Shakti213** [comment]
Chiming in with an alternative I use to enable or disable logging during run-time as well:
```
#include "azure_c_shared_utility/xlogging.h"

static LOGGER_LOG default_logger = NULL;

void disable_azure_log()
{
    if (default_logger == NULL)
    {
        default_logger = xlogging_get_log_function();
    }
    xlogging_set_log_function(NULL);
}

void enable_azure_log()
{
    if (default_logger == NULL)
    {
        default_logger = xlogging_get_log_function();
    }
    xlogging_set_log_function(default_logger);
}
```

**Comment by lukka** [comment]
@ewertons thanks a lot for your support, I understand that I can either disable entirely diagnostic logging or use my own logging function as @Shakti213 shown, thanks to both.

Anyway what I really want to report is that the are a lot of LogError invocation that should be instead LogWarning (which does not exists by the way), or nothing at all. In the specific example I reported, the code ask the MultiTree node whethere there is a node called in some way: if this node is not existent, the client code gets the return code of "child not found", and that should be enough. No errors should be raised at all anywhere (nor on printed out on the output). 

It is a design issue: the clients want to be notified of real errors (hence no_logging is not really a viable solution), but they do not want to get false errors too. In the example above, the client get the "child not found" value, and they know how to deal with it.

**Comment by ewertons** [comment]
I see.
So to make sure I understand it further, you are expecting to have a Twin json tree in the cloud with nodes names that are not mapped on the model defined on the client side?

**Comment by ewertons** [comment]
Hi @lukka ,
we hope our conversation provided enough info to solve the issues you encountered.
This issue will be closed, but please feel free to reopen it if you need to follow up on it.
Thanks,
Azure IoT SDK Team

**Comment by lukka** [comment]
@ewertons 

Basically the conclusion is:
  - the error messages (that are not really errors, they should not be printed out)  cannot be turned off;
  - a workaround is to disable entirely the message compiing the iotsdk with defining -DNO_LOGGING;
  - another workaround is to not use directly the MultiTree API functions, but to use the serializer module which is on top of the MultiTree;

**Comment by ewertons** [comment]
Yes, that is a good summary.
As we spoke, the json online on the cloud is supposed to be 100% the same one mapped on the serializer client. In such case, the errors won't show up.

If you believe the functionality should be different, please feel free to reopen it and add a good description of the expected behavior, and we will mark it as an enhancement.
