### ISSUE TITLE
documentation - MinimumPollingTime and timeout - sdk options

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#283]
iothub_client_sample_http([1](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_http/iothub_client_sample_http.c#L181)) uses two options named _MinimumPollingTime_ and _timeout_. Both options are not mentioned in IoTHub C SDK options page([2](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Iothub_sdk_options.md)). Could they be added?

**Comment by jebrando** [comment]
I have fixed the document and it should be checked in.  Thank you for the issues.

**Comment by kiranpradeep** [comment]
@jebrando Thanks. But, can you add bit more clarity regarding `MinimumPollingTime`?. From a lib user perspective, what do you mean by 2 consecutive GET requests. We only use `IoTHubClient_LL_SendEventAsync`.  What use does a lib user has from tweaking this variable?
