### ISSUE TITLE
documentation - retry policy and http protocol

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#284]
The feature matrix in readme([1](https://github.com/Azure/azure-iot-sdk-c#key-features-and-roadmap)) page lists no retry policy for HTTP protocol. Does that imply that a message is never retried? If not, could the feature matrix be updated to reflect the correct retry status for HTTP.

I tried using iothub_client_sample_http.c([2](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_http/iothub_client_sample_http.c#L235)). But saw that even if there are periods of network loss, we get send confirmation callbacks([3](https://github.com/Azure/azure-iot-sdk-c/blob/999786715040aba6533c2c5eb04b2eb1c8e152b5/iothub_client/samples/iothub_client_sample_http/iothub_client_sample_http.c#L129)) once the network connectivity is recovered. That does not match the retry behavior specified in feature matrix.

**Comment by yzhong94** [comment]
@kiranpradeep thank you for raising this issue!  

For the C and Python SDK, retry policy is implemented at the transport level.  Each message sent to the cloud results in a new connection and a new HTTP request (along with a new SAS token), which are terminated upon receiving the HTTP response.  Since HTTP transport does not establish a persistent connection, there is no retry policy (custom, no retry, exponential backoff with jitter) for network connection.  However, the client does have retry logic, which is what you are seeing.  The client will retry for sending messages in case of network loss.

Hopefully, this answers your question.  We will modify the description of retry policy on feature matrix.  In addition, we will publish a conceptual doc for retry policy on [Azure IoT Hub Documentation](https://docs.microsoft.com/en-us/azure/iot-hub/).

**Comment by kiranpradeep** [comment]
@yzhong94 Thanks for the reply.

> However, the client does have retry logic, which is what you are seeing.

Could you please clarify this quote? Does the client retry forever? How frequently does it retry? Does the lib user has any control over this behavior? Is there any limit to the number of messages being retried?

**Comment by ewertons** [comment]
Good questions.
All answers bellow are regarding using the Azure IoT Hub Client with HTTP transport.

Q: Is the client any different from this azure-iot-sdk-c library? 
A: No, it's the same Azure IoT C SDK. By "the client" Yi meant the HTTP transport layer within the Azure IoT SDK.

Q: Does the client retry forever? 
A: For HTTP transport, yes.
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransporthttp.c#L1413

Q: How frequently does it retry? 
A: For HTTP transport, Immediately.

Q: Does the lib user has any control over this behavior? 
A: no.

Q: Is there any limit to the number of messages being retried?
A: No.

**Comment by kiranpradeep** [comment]
@ewertons Thanks. HTTP is the only way to upload files blob store(tied to Azure IoTHub). When there is no network connection, the above behavior could use up all system memory (the UploadToBlob API needs the full file in memory) when we try to upload files one after another. Is it possible to add `IOTHUB_CLIENT_RETRY_NONE` (or similar) to HTTP?

Also, I assume we won't get any send confirmation callbacks( either failure or success ) until network connectivity is restored.

Use case: In addition to sending streaming data as messages, we are uploading aggregated file data (>256kb) to blob store associated with Azure IoTHub.

**Comment by ewertons** [comment]
That changes the topic quite a lot.
Upload to blob is a different layer, it is not related to the retry logic or retry policies implemented on the IoT Hub Client transports, namely:
[iothubtransportamqp.c](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransportamqp.c)
[iothubtransportamqp_websockets.c](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransportamqp_websockets.c)
[iothubtransportmqtt.c](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransportmqtt.c)
[iothubtransportmqtt_websockets.c](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransportmqtt_websockets.c)
[iothubtransporthttp.c](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransporthttp.c)

Uploading to Azure blob storage is only supported via HTTP. 
To be able to expose functions to upload to blob even when users select AMQP or MQTT on the iothubclient we had to implement that feature as a separate unit, talking directly to the HTTP stacks (not going through the iothubtransporthttp.c).

When you try to upload a file to a blob storage (for example, using [IoTHubClient_UploadToBlobAsync](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client.h#L359)), there is one HTTP request sent to the IoT Hub to get the address of the Azure Blob Storage (ABS), and one sent to the ABS itself to upload a file. All of these are single requests, that are **not automatically retried if any failure occur**. 

Please feel free to check here:
[blob.c](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/blob.c)
[iothub_client_ll_uploadtoblob.c](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothub_client_ll_uploadtoblob.c)

**Comment by kiranpradeep** [comment]
Thanks @ewertons for the detailed reply. This really helps. Maybe, infinite, immediate and uncontrollable retry part of HTTP messages should be documented. That could still consume system memory( during network loss ) although at low rates. Currently we are using _OPTION_MESSAGE_TIMEOUT_ option to stop the infinite retries of HTTP messages.
