### ISSUE TITLE
Device connect to IoT hub but output not occured 

### ISSUE THREAD

**Issue by vnn0804** [Azure/azure-iot-sdk-c#285]
- **OS and version used:**  Ubuntu 16.04... -->

# Description of the issue:
i run sample code for mqtt.  two days  back successfully got output but right nw some problem

# Console log of the issue:
~/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_mqtt$ sudo ./iothub_client_sample_mqtt Info: IoT Hub SDK for C, version 1.1.26
IoTHubClient_LL_SetMessageCallback...successful.
Serial Port /dev/ttyUSB0 is now open 
Successfully wrote  bytes
epoch: 1510130315
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [3] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [4] for transmission to IoT Hub.

**Comment by markrad** [comment]
Hi @vnn0804,

I'm curious to know why you are using sudo. It shouldn't be necessary but it is unlikely related to your problem. Is this the entire log? Can you turn on tracing please? You should see in the sample something akin to this:
```C
bool traceOn = true;
IoTHubClient_LL_SetOption(iotHubClientHandle, OPTION_LOG_TRACE, &traceOn);
```
This will provide more information about the connection. You could also try checking if you have connectivity to the Azure IoT hub by entering the following:
```
openssl s_client -connect <your hub name>.azure-devices.net:8883
```
If you can successfully connect and validate the certificate you should see 
```
Verify return code: 0 (ok)
```
at the end of the output.

_Mark Radbourne MSFT_

**Comment by vnn0804** [comment]
hi markrad,
 i am using serial port for connect sensor directly to dell box. for opening serial port require root login thats why i used sudo.

**Comment by tameraw** [comment]
@vnn0804 - Is this problem still persistent? If it is, can you please follow instruction from @markrad and give us more data? Thanks.

**Comment by vnn0804** [comment]
Hello,
Solve the issue and got data from sensor and successful send to cloud.

Thanks &  Regards,
Vaibhav Nanoti
8308844796

**Comment by ewertons** [comment]
Hi @vnn0804 ,
could you share the details of what the issue was and how you fixed it?
Thanks

**Comment by ewertons** [comment]
@vnn0804 ,
Thanks for using the Azure IoT SDK.
This issue will be closed, but feel free to reopen it if you need to follow up on the topic.
