### ISSUE TITLE
Azure c sdk - failed crosscompiling on ARM device

### ISSUE THREAD

**Issue by Zanna-93** [Azure/azure-iot-sdk-c#287]
- Linux (none) 2.6.36
- 2017-11-03 Sdk release

# Description of the issue:
I'm trying to crosscompile the azure-iothub-sdk-c for an ARM device, I need to generate these libraries and headers in order to start developing in my device.

I've created a custom Cmake toolchain in order to resolve libraries dependencies, directories and includes.
Inside azure/sdk/path/cmake/ I run followings commands:

`cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake _DCMAKE_INSTALL_PREFIX=/opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi/libc/usr/ ..

cmake --build .`

the first command runs successfully and return this output:

-- The C compiler identification is GNU 4.4.1
-- The CXX compiler identification is GNU 4.4.1
-- Check for working C compiler: /opt/crosstool/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-gcc
-- Check for working C compiler: /opt/crosstool/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/crosstool/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-g++
-- Check for working CXX compiler: /opt/crosstool/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- target architecture: ARM
-- Found OpenSSL: /opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi/libc/usr/lib/libcrypto.so.1.0.0 (found version "1.0.2m") 
-- Cross compiling not using pkg-config
-- Found CURL: /opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi/libc/usr/lib/libcurl.a  
-- Found CURL: /opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi/libc/usr/lib/libcurl.a  
-- target architecture: ARM
-- target architecture: ARM
-- target architecture: ARM
-- iothub architecture: ARM
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/azure-iot-sdk-c/cmake

I got an issue when running the second command, compilation reaches 20% and then fails while linking libraries, this is the output:

[ 19%] Built target aziotsharedutil
Scanning dependencies of target iot_c_utility
[ 20%] Building C object c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/iot_c_utility.c.o
[ 20%] Linking C executable iot_c_utility
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `log_ERR_get_error':
tlsio_openssl.c:(.text+0x1198): undefined reference to `ERR_get_error'
tlsio_openssl.c:(.text+0x11d4): undefined reference to `ERR_error_string'
tlsio_openssl.c:(.text+0x1224): undefined reference to `ERR_get_error'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `openssl_dynamic_locks_uninstall':
tlsio_openssl.c:(.text+0x1450): undefined reference to `CRYPTO_set_dynlock_create_callback'
tlsio_openssl.c:(.text+0x1458): undefined reference to `CRYPTO_set_dynlock_lock_callback'
tlsio_openssl.c:(.text+0x1460): undefined reference to `CRYPTO_set_dynlock_destroy_callback'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `openssl_dynamic_locks_install':
tlsio_openssl.c:(.text+0x1484): undefined reference to `CRYPTO_set_dynlock_destroy_callback'
tlsio_openssl.c:(.text+0x1494): undefined reference to `CRYPTO_set_dynlock_lock_callback'
tlsio_openssl.c:(.text+0x14a4): undefined reference to `CRYPTO_set_dynlock_create_callback'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `openssl_static_locks_lock_unlock_cb':
tlsio_openssl.c:(.text+0x14ec): undefined reference to `CRYPTO_num_locks'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `openssl_static_locks_uninstall':
tlsio_openssl.c:(.text+0x15f4): undefined reference to `CRYPTO_set_locking_callback'
tlsio_openssl.c:(.text+0x1658): undefined reference to `CRYPTO_num_locks'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `openssl_static_locks_install':
tlsio_openssl.c:(.text+0x1790): undefined reference to `CRYPTO_num_locks'
tlsio_openssl.c:(.text+0x18ec): undefined reference to `CRYPTO_num_locks'
tlsio_openssl.c:(.text+0x1908): undefined reference to `CRYPTO_num_locks'
tlsio_openssl.c:(.text+0x1980): undefined reference to `CRYPTO_set_locking_callback'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `write_outgoing_bytes':
tlsio_openssl.c:(.text+0x1b60): undefined reference to `BIO_ctrl_pending'
tlsio_openssl.c:(.text+0x1c18): undefined reference to `BIO_read'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `send_handshake_bytes':
tlsio_openssl.c:(.text+0x1d38): undefined reference to `ERR_clear_error'
tlsio_openssl.c:(.text+0x1d48): undefined reference to `SSL_do_handshake'
tlsio_openssl.c:(.text+0x1d70): undefined reference to `SSL_get_error'
tlsio_openssl.c:(.text+0x1db8): undefined reference to `ERR_get_error'
tlsio_openssl.c:(.text+0x1dc8): undefined reference to `ERR_error_string'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `decode_ssl_received_bytes':
tlsio_openssl.c:(.text+0x21d0): undefined reference to `SSL_read'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `on_underlying_io_bytes_received':
tlsio_openssl.c:(.text+0x22e8): undefined reference to `BIO_write'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `close_openssl_instance':
tlsio_openssl.c:(.text+0x241c): undefined reference to `SSL_free'
tlsio_openssl.c:(.text+0x2448): undefined reference to `SSL_CTX_free'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `add_certificate_to_store':
tlsio_openssl.c:(.text+0x249c): undefined reference to `SSL_CTX_get_cert_store'
tlsio_openssl.c:(.text+0x24d0): undefined reference to `BIO_s_mem'
tlsio_openssl.c:(.text+0x2508): undefined reference to `BIO_new'
tlsio_openssl.c:(.text+0x2544): undefined reference to `BIO_puts'
tlsio_openssl.c:(.text+0x25b4): undefined reference to `X509_STORE_add_cert'
tlsio_openssl.c:(.text+0x25c8): undefined reference to `X509_free'
tlsio_openssl.c:(.text+0x25e4): undefined reference to `X509_free'
tlsio_openssl.c:(.text+0x2600): undefined reference to `PEM_read_bio_X509'
tlsio_openssl.c:(.text+0x263c): undefined reference to `BIO_free'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `create_openssl_instance':
tlsio_openssl.c:(.text+0x26b0): undefined reference to `TLSv1_2_method'
tlsio_openssl.c:(.text+0x26d0): undefined reference to `TLSv1_1_method'
tlsio_openssl.c:(.text+0x26e0): undefined reference to `TLSv1_method'
tlsio_openssl.c:(.text+0x26f0): undefined reference to `SSL_CTX_new'
tlsio_openssl.c:(.text+0x2758): undefined reference to `SSL_CTX_free'
tlsio_openssl.c:(.text+0x27e4): undefined reference to `SSL_CTX_free'
tlsio_openssl.c:(.text+0x2870): undefined reference to `SSL_CTX_free'
tlsio_openssl.c:(.text+0x2904): undefined reference to `SSL_CTX_set_cert_verify_callback'
tlsio_openssl.c:(.text+0x2908): undefined reference to `BIO_s_mem'
tlsio_openssl.c:(.text+0x2914): undefined reference to `BIO_new'
tlsio_openssl.c:(.text+0x2940): undefined reference to `SSL_CTX_free'
tlsio_openssl.c:(.text+0x296c): undefined reference to `BIO_s_mem'
tlsio_openssl.c:(.text+0x2978): undefined reference to `BIO_new'
tlsio_openssl.c:(.text+0x29a4): undefined reference to `BIO_free'
tlsio_openssl.c:(.text+0x29b4): undefined reference to `SSL_CTX_free'
tlsio_openssl.c:(.text+0x29f8): undefined reference to `BIO_ctrl'
tlsio_openssl.c:(.text+0x2a20): undefined reference to `BIO_ctrl'
tlsio_openssl.c:(.text+0x2a3c): undefined reference to `BIO_free'
tlsio_openssl.c:(.text+0x2a4c): undefined reference to `BIO_free'
tlsio_openssl.c:(.text+0x2a5c): undefined reference to `SSL_CTX_free'
tlsio_openssl.c:(.text+0x2ae0): undefined reference to `SSL_CTX_set_verify'
tlsio_openssl.c:(.text+0x2af0): undefined reference to `SSL_CTX_set_default_verify_paths'
tlsio_openssl.c:(.text+0x2b60): undefined reference to `SSL_new'
tlsio_openssl.c:(.text+0x2b8c): undefined reference to `BIO_free'
tlsio_openssl.c:(.text+0x2b9c): undefined reference to `BIO_free'
tlsio_openssl.c:(.text+0x2bac): undefined reference to `SSL_CTX_free'
tlsio_openssl.c:(.text+0x2bfc): undefined reference to `SSL_set_bio'
tlsio_openssl.c:(.text+0x2c0c): undefined reference to `SSL_set_connect_state'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `tlsio_openssl_init':
tlsio_openssl.c:(.text+0x2c88): undefined reference to `SSL_library_init'
tlsio_openssl.c:(.text+0x2c8c): undefined reference to `SSL_load_error_strings'
tlsio_openssl.c:(.text+0x2c90): undefined reference to `ERR_load_BIO_strings'
tlsio_openssl.c:(.text+0x2c94): undefined reference to `OPENSSL_add_all_algorithms_noconf'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `tlsio_openssl_deinit':
tlsio_openssl.c:(.text+0x2d40): undefined reference to `FIPS_mode_set'
tlsio_openssl.c:(.text+0x2d48): undefined reference to `CRYPTO_set_locking_callback'
tlsio_openssl.c:(.text+0x2d50): undefined reference to `CRYPTO_set_id_callback'
tlsio_openssl.c:(.text+0x2d54): undefined reference to `ERR_free_strings'
tlsio_openssl.c:(.text+0x2d58): undefined reference to `EVP_cleanup'
tlsio_openssl.c:(.text+0x2d60): undefined reference to `ERR_remove_thread_state'
tlsio_openssl.c:(.text+0x2d64): undefined reference to `SSL_COMP_free_compression_methods'
tlsio_openssl.c:(.text+0x2d68): undefined reference to `CRYPTO_cleanup_all_ex_data'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `tlsio_openssl_send':
tlsio_openssl.c:(.text+0x38e4): undefined reference to `SSL_write'
../../libaziotsharedutil.a(tlsio_openssl.c.o): In function `tlsio_openssl_setoption':
tlsio_openssl.c:(.text+0x423c): undefined reference to `SSL_CTX_set_cert_verify_callback'
tlsio_openssl.c:(.text+0x42ac): undefined reference to `SSL_CTX_set_cert_verify_callback'
../../libaziotsharedutil.a(x509_openssl.c.o): In function `log_ERR_get_error':
x509_openssl.c:(.text+0x80): undefined reference to `ERR_get_error'
x509_openssl.c:(.text+0xbc): undefined reference to `ERR_error_string'
x509_openssl.c:(.text+0x10c): undefined reference to `ERR_get_error'
../../libaziotsharedutil.a(x509_openssl.c.o): In function `load_certificate_chain':
x509_openssl.c:(.text+0x170): undefined reference to `BIO_new_mem_buf'
x509_openssl.c:(.text+0x1b4): undefined reference to `PEM_read_bio_X509_AUX'
x509_openssl.c:(.text+0x1f0): undefined reference to `SSL_CTX_use_certificate'
x509_openssl.c:(.text+0x250): undefined reference to `sk_pop_free'
x509_openssl.c:(.text+0x274): undefined reference to `SSL_CTX_ctrl'
x509_openssl.c:(.text+0x288): undefined reference to `X509_free'
x509_openssl.c:(.text+0x2ac): undefined reference to `PEM_read_bio_X509'
x509_openssl.c:(.text+0x2d0): undefined reference to `ERR_peek_last_error'
x509_openssl.c:(.text+0x300): undefined reference to `ERR_clear_error'
x509_openssl.c:(.text+0x31c): undefined reference to `X509_free'
x509_openssl.c:(.text+0x324): undefined reference to `BIO_free'
x509_openssl.c:(.text+0x344): undefined reference to `X509_free'
../../libaziotsharedutil.a(x509_openssl.c.o): In function `load_alias_key_cert':
x509_openssl.c:(.text+0x374): undefined reference to `BIO_new_mem_buf'
x509_openssl.c:(.text+0x3b8): undefined reference to `PEM_read_bio_PrivateKey'
x509_openssl.c:(.text+0x3f4): undefined reference to `SSL_CTX_use_PrivateKey'
x509_openssl.c:(.text+0x470): undefined reference to `EVP_PKEY_free'
x509_openssl.c:(.text+0x478): undefined reference to `BIO_free'
../../libaziotsharedutil.a(x509_openssl.c.o): In function `load_private_key_RSA':
x509_openssl.c:(.text+0x4c8): undefined reference to `BIO_new_mem_buf'
x509_openssl.c:(.text+0x50c): undefined reference to `PEM_read_bio_RSAPrivateKey'
x509_openssl.c:(.text+0x548): undefined reference to `SSL_CTX_use_RSAPrivateKey'
x509_openssl.c:(.text+0x580): undefined reference to `RSA_free'
x509_openssl.c:(.text+0x588): undefined reference to `BIO_free'
../../libaziotsharedutil.a(x509_openssl.c.o): In function `x509_openssl_add_certificates':
x509_openssl.c:(.text+0xa1c): undefined reference to `SSL_CTX_get_cert_store'
x509_openssl.c:(.text+0xa50): undefined reference to `BIO_s_mem'
x509_openssl.c:(.text+0xa88): undefined reference to `BIO_new'
x509_openssl.c:(.text+0xac4): undefined reference to `BIO_puts'
x509_openssl.c:(.text+0xb1c): undefined reference to `X509_STORE_add_cert'
x509_openssl.c:(.text+0xb2c): undefined reference to `ERR_peek_error'
x509_openssl.c:(.text+0xb60): undefined reference to `X509_free'
x509_openssl.c:(.text+0xb6c): undefined reference to `X509_free'
x509_openssl.c:(.text+0xb88): undefined reference to `PEM_read_bio_X509'
x509_openssl.c:(.text+0xbc4): undefined reference to `BIO_free'
../../libaziotsharedutil.a(crt_abstractions.c.o): In function `splitFloatString':
crt_abstractions.c:(.text+0x10b8): undefined reference to `pow'
crt_abstractions.c:(.text+0x1150): undefined reference to `pow'
../../libaziotsharedutil.a(crt_abstractions.c.o): In function `strtof_s':
crt_abstractions.c:(.text+0x127c): undefined reference to `pow'
../../libaziotsharedutil.a(crt_abstractions.c.o): In function `strtold_s':
crt_abstractions.c:(.text+0x158c): undefined reference to `pow'
collect2: ld returned 1 exit status
c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/build.make:95: set di istruzioni per l'obiettivo "c-utility/samples/iot_c_utility/iot_c_utility" non riuscito
make[2]: *** [c-utility/samples/iot_c_utility/iot_c_utility] Errore 1
CMakeFiles/Makefile2:1056: set di istruzioni per l'obiettivo "c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/all" non riuscito
make[1]: *** [c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/all] Errore 2
Makefile:140: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2

I've tried to recompile the sdk in different ways but I still got this error and I'm not able to figure out what I'm doing wrong.

There is someone who can help me?

# Custom toolchain file (toolchain.cmake)

```
 INCLUDE(CMakeForceCompiler)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)

set(CMAKE_C_COMPILER /opt/crosstool/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-gcc)
set(CMAKE_CXX_COMPILER /opt/crosstool/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-g++)

set(CMAKE_C_FLAGS "${CMAKE_CC_FLAGS} -L/opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi/libc/usr/lib -ldl -lcrypto -lssl")
#set(CMAKE_C_FLAGS "--std=c99 ${CMAKE_C_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -L/opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi/libc/usr/lib -ldl -lcrypto -lssl")
set(CXX_FLAG_CXX11 "--std=c++11 ${CMAKE_CXX_FLAGS}")

set(CMAKE_FIND_ROOT_PATH /opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi)

#OpenSSL path
set(OPENSSL_ROOT_DIR /opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi/libc/usr/ssl)
set(OPENSSL_CRYPTO_LIBRARY /opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi/libc/usr/lib/libcrypto.so.1.0.0)
#set(OPENSSL_CRYPTO_LIBRARY /opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi/libc/armv4t/usr/lib/libcrypt.a)
set(OPENSSL_SSL_LIBRARY /opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi/libc/usr/lib/libssl.a)
set(OPENSSL_INCLUDE_DIR /opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi/libc/usr/include)

#libcurl path
set(CURL_INCLUDE_DIR /opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi/libc/usr/include/curl)
set(CURL_LIBRARY /opt/crosstool/arm-none-linux-gnueabi/arm-none-linux-gnueabi/libc/usr/lib/libcurl.a)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

**Comment by JetstreamRoySprowl** [comment]
@Zanna-93 : Hi, I have not tested this suggestion, but when you're compiling the Azure IoT SDK for use with OpenSSL, you need to include `-Duse_openssl:bool=ON' in the CMAKE command.

**Comment by Zanna-93** [comment]
I've solved that problem, it was a mistake in the linked library.
Now when I run the iothub client mqtt sample on the ARM device I got this error for each message to the hub.

```
Info: error1416F086: SSL routines: tls_process_server_cerfiticate: certificate verify failed
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
```
If I compile and run the same program on an x86 architecture I got no errors and the message reaches the IoTHub succesfully.

**Comment by ollyw** [comment]
@Zanna-93 perhaps it is an issue with the ca-certificates not being on the device so the IoT hub cert is not trusted? Check those are installed (normally the package is called something like ca-certificates). Otherwise if you run `ssh -vvv <host specified in your connection string>` it may give you some more clues.

**Comment by Zanna-93** [comment]
I've run that command and there's a verification erron  in the certs  chain.
I've recompiled and reinstalled openssl on the ARM device and copied certificates on /usr/lib/ssl/certs but I still got  **error 20: unable to get local issuer certificate**

```
root@owa3x]$ openssl s_client -connect <host>.azure-devices.net:8883
CONNECTED(00000003)
depth=1 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, OU = Microsoft IT, CN = Microsoft IT SSL SHA2 verify error:num=20:unable to get local issuer certificate
---
Certificate chain
  0 s:/CN=*.azure-devices.net
    i:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
  1 s:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
    i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
---
Server certificate
-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
subject=/CN=*.azure-devices.net
issuer=/C=US/ST=Washington/L=Redmond/O=Microsoft
Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign Requested Signature Algorithms: 
RSA+SHA512:ECDSA+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDS
RSA+A+SHA384:ECDSA+SHA1:DSA+SHA1
Shared Requested Signature Algorithms: 
RSA+SHA512:ECDSA+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDS
RSA+A+SHA384:ECDSA+SHA1:DSA+SHA1
Peer signing digest: SHA1
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 3696 bytes and written 354 bytes 
Verification error: unable to get local issuer certificate
```

if i run this command:

`awk -v cmd='openssl x509 -noout -subject' '/BEGIN/{close(cmd)};{print | cmd}' < /etc/ssl/certs/ca-certificates.crt | grep Baltimore`

I will find the Baltimore certificate which is used by azure.

This problem persist even with any host 
`root@owa3x]$ openssl s_client -connect  google.com;443` returns the same error, only at a different depth of certs' chain

**Comment by markrad** [comment]
Hi @Zanna-93,

I suggest you use the TrustedCerts option that is typically #ifdefed out in the samples. Look close to the top of the main function. You will need to include the certificates from certs.c. If openssl s_client cannot validate then the SDK will also not be able to. This option will often resolve that.

_Mark Radbourne MSFT_

**Comment by jspaith** [comment]
@Zanna-93 - As this issue has been open for a bit after Mark's response (and I the TrustedCerts should be the trick here) I'm going to close this out.

If you need further help here by all means re-open the issue or open a new one.  

Thanks

**Comment by chinnaece** [comment]
> I've solved that problem, it was a mistake in the linked library.
> Now when I run the iothub client mqtt sample on the ARM device I got this error for each message to the hub.
> 
> ```
> Info: error1416F086: SSL routines: tls_process_server_cerfiticate: certificate verify failed
> Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
> ```
> If I compile and run the same program on an x86 architecture I got no errors and the message reaches the IoTHub succesfully.
> 
> This is the exact output from the linux command line:
> 
> ```
> 
> [root@owa3x]$ /home/test_ARM
> Info: IoT Hub SDK for C, version 1.1.27
> IoTHubClient_LL_SetMessageCallback...successful.
> IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
> IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.
> IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.
> IoTHubClient_LL_SendEventAsync accepted message [3] for transmission to IoT Hub.
> IoTHubClient_LL_SendEventAsync accepted message [4] for transmission to IoT Hub.
> Info: error:1416F086:SSL
> routines:tls_process_server_certificate:certificate verify failed
> Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
> Info: error:1416F086:SSL
> routines:tls_process_server_certificate:certificate verify failed
> Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
> ```



> I've solved that problem, it was a mistake in the linked library.
> Now when I run the iothub client mqtt sample on the ARM device I got this error for each message to the hub.
> 
> ```
> Info: error1416F086: SSL routines: tls_process_server_cerfiticate: certificate verify failed
> Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
> ```
> If I compile and run the same program on an x86 architecture I got no errors and the message reaches the IoTHub succesfully.
> 
> This is the exact output from the linux command line:
> 
> ```
> 
> [root@owa3x]$ /home/test_ARM
> Info: IoT Hub SDK for C, version 1.1.27
> IoTHubClient_LL_SetMessageCallback...successful.
> IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
> IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.
> IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.
> IoTHubClient_LL_SendEventAsync accepted message [3] for transmission to IoT Hub.
> IoTHubClient_LL_SendEventAsync accepted message [4] for transmission to IoT Hub.
> Info: error:1416F086:SSL
> routines:tls_process_server_certificate:certificate verify failed
> Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
> Info: error:1416F086:SSL
> routines:tls_process_server_certificate:certificate verify failed
> Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
> ```
Could you please tell me how did you link libraries in that .cmake script

**Comment by chinnaece** [comment]
chinna@chinna-VirtualBox:~/azure-iot-sdk-c/cmake$ cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain_BBG.cmake _DCMAKE_INSTALL_PREFIX=/home/chinna/Downloads/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf /libc/usr/ ..-- IoT Client SDK Version = 1.2.8
-- Provisioning client OFF
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- iothub architecture: x86_64
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_TOOLCHAIN_FILE


-- Build files have been written to: /home/chinna/azure-iot-sdk-c/cmake

**Comment by jspaith** [comment]
@chinnaece  - could you please open a new GitHub issue to track this if my response doesn't help?  This is a bit different than initial question and we don't really follow closed issues.

Looking at the error, what's likely happening is that there is no trusted root for this certificate in your SSL setup.  Normally when you go to https://microsoft.com through a web browser on Windows, microsoft.com chains up to a certificate issued by a well known, trusted CA your OS / browser trust.

Some embedded systems don't have the baked in trusted certificate store, which means going to azure-iot.com (or whatever it is) will present a certificate that the underlying TLS stack shouldn't trust.  This is why your code may work on some distros of Linux and Windows, but not on some of more stripped down versions without cert store.

https://github.com/Azure/azure-iot-sdk-c/issues/435 has some more details.  In general the `OPTION_TRUSTED_CERT` is a way to tell the SDK that it should trust given cert issuers.

If you need more help, on your issue please re-include the logs and also let us know which distro of Linux you're hitting problems on and which tls stack (openssl, wolfssl, ...) you're using?

Thanks
