### ISSUE TITLE
[Question] Minimizing network data traffic

### ISSUE THREAD

**Issue by AndWass** [Azure/azure-iot-sdk-c#289]
What is the best way to minimize the network traffic using the SDK? Is MQTT better than AMQP in this regard? What is the overhead of meta-data etc. being sent with each event, and can this be minimized somehow?

**Comment by olivierbloch** [comment]
Hi @Shakti213 , our SDKs use the bare minimum of each of the protocols. Both are designed for different requirements. I would invite you to read some of the literature out there such as this [whitepaper ](https://lists.oasis-open.org/archives/amqp/201202/msg00086/StormMQ_WhitePaper_-_A_Comparison_of_AMQP_and_MQTT.pdf) to understand the differences.
While MQTT has the reputation of being low-overhead, AMQP has some advantages that allow for better handling of larger messages or bulk send operations, so the optimization very much depends our your scenario and how you intend to send device data.

**Comment by Shakti213** [comment]
Thanks! That was my interpretation of it all as well, and in my case we have a gateway that collects and sends data from multiple sensors (everywhere from just a few to potentially say 100 sensors) so in that case AMQP with a single transport and batching is what I think (and hope) will be the most efficient solution.

Do you have any numbers on how big any meta-data being sent is? Such as property data sent with AMQP etc?

**Comment by olivierbloch** [comment]
I think you have the right approach. we do not have numbers that we can publish at this point, but we do intend to run some tests and gather benchmarks for our SDKs soon. stay tuned.

**Comment by jspaith** [comment]
Marking as enhancement, namely getting information about bandwidth usage in terms of #'s and best practices docs.

**Comment by NickDarvey** [comment]
@olivierbloch how's that benchmarking going?

**Comment by Shakti213** [comment]
Any updates on this?

We are seeing quite big overhead, especially on mostly-idle connections. Or rather the signal-to-overhead ratio is quite big, and it would be very interesting if this could be dialed down somehow.

**Comment by massand** [comment]
@jebrando - could you post the numbers from our analysis on Linux x64 environment here for now and close the issue? 
@AndWass - we are working on publishing documentation more broadly per LTS release going forward. Stay tuned!

**Comment by AndWass** [comment]
@massand Sounds great! Will you link to this info in the README or where can I find them once they are published?

**Comment by yzhong94** [comment]
I will close this issue now since we have the benchmark publicly.   @AndWass  for follow up after you review the benchmark, please file another issue.

**Comment by az-iot-builder-01** [comment]
@AndWass, @jspaith, @NickDarvey, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
