### ISSUE TITLE
Mqtt Ping Response was not encountered. Reconnecting device...

### ISSUE THREAD

**Issue by FrankZhcz** [Azure/azure-iot-sdk-c#290]
Hello,
I also get the error "Mqtt Ping Response was not encountered. Reconnecting device..." as below:

1. [Thu Nov 02 18:20:37.007 2017] Error: Time:Thu Nov 2 10:20:37 2017 File:/home/user/bin/qsdk/build_dir/target-mips_34kc_uClibc-1.0.14/azure-iot-sdk-2017-05-19/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_error_callback Line:1560 Mqtt Ping Response was not encountered. Reconnecting device...

2. [Thu Nov 02 18:07:37.701 2017] Error: Time:Thu Nov 2 10:07:37 2017 File:/home/user/bin/qsdk/build_dir/target-mips_34kc_uClibc-1.0.14/azure-iot-sdk-2017-05-19/iothub_client/src/iothubtransport_mqtt_common.c Func:CreateRetryLogic Line:359 Use IOTHUB_CLIENT_RETRY_LINEAR_BACKOFF Policy

[Reference:OpenWRT/OpenVPN Client Login Problem](https://forum.openwrt.org/viewtopic.php?id=26725)
**Log was attached:
[2017-11-03_box-mqtt-log copy.txt](https://github.com/Azure/azure-iot-sdk-c/files/1461599/2017-11-03_box-mqtt-log.copy.txt)**

Could you give some advice?

**Comment by ewertons** [comment]
Hi @FrankZhcz,
are you downloading the source code and compiling it for your system?
If so, could you use the latest version of the SDK?
The one you are using is quite old, there have been many fixes and improvements since then.

[Thu Nov 02 18:07:37.701 2017] Info: IoT Hub SDK for C, version 1.1.15

**Comment by ewertons** [comment]
Hi @FrankZhcz ,
we will close this issue, but please feel free to reopen it if you need to. Make sure you follow up on the last comment we left, it might resolve your issue.
Thanks,
Azure IoT SDK Team

**Comment by VJThippavajjula** [comment]
We are using SDK 1.2.13 and I still see this issue
 [mqtt_error_callback:1864] Mqtt Ping Response was not encountered.  Reconnecting device...
