### ISSUE TITLE
Unable to locate package iothub_client_sample_firmware_update

### ISSUE THREAD

**Issue by scout208** [Azure/azure-iot-sdk-c#291]
- **OS and version used:** <VERSION>  Windows 10

- **SDK version used:** <VERSION>  Latest (1.1.27)

# Description of the issue:

Working through the sample, [Firmware update of a Raspberry Pi 3 using Azure IoT Hub device management](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_mqtt_dm/pi_device), I was able to get as far as [Install the sample application](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_mqtt_dm/pi_device#install-the-sample-application), but running `sudo apt-get install -y iothub_client_sample_firmware_update` returns `E: Unable to locate package iothub_client_sample_firmware_update`.

# Code sample exhibiting the issue:

`sudo apt-get install -y iothub_client_sample_firmware_update`

# Console log of the issue:

Here's my log. I've included the contents of the /etc/apt/sources.list file so you can see they match the instructions.

![image](https://user-images.githubusercontent.com/9426329/32694860-2cc0f4f2-c711-11e7-8bdc-267b9f15ba7d.png)

**Comment by markrad** [comment]
Hi @scout208,

What version of Raspbian are you running? It is possible that the packages have not been built for the latest version (Stretch if my memory serves).

_Mark Radbourne MSFT_

**Comment by scout208** [comment]
I thought I was running Raspbian 4.1, as that was the version suggested by the tutorial that I tried to download. I can go check though and post it here when I find it.

**Comment by jspaith** [comment]
The readme has a typo.  Instead of 'iothub_client_sample_firmware_update' it should be 'iothub-client-sample-firmware-update'.  I'll get a fix in shortly.

Note I haven't tried the pi sample further but fixing the typo did at least make progress.

My apologies for the problem & delay here.

**Comment by jspaith** [comment]
Marking as closed since the comments here address the issue.  The fix for the docs themselves is tracked separately and will be checked in soon.
