### ISSUE TITLE
Serializer throws error when a desired property is deleted

### ISSUE THREAD

**Issue by ArsalanSaleemGhuman** [Azure/azure-iot-sdk-c#292]
- **OS and version used:** <VERSION> Nucleus RTOS 

- **SDK version used:** <VERSION>  Tag 2017-08-25   

# Description of the issue:
 This issue is related specific to the handling of device twin by serializer.
Inorder to delete a desired property the azure sdk requires a null to be the value to the deleted property. In our case when the null value is given the webapp(remote monitoring application) invokes the desired property callback. The serializer expects the callback to be called with an integer value. Calling it will a null value causes serializer to report error.

**Comment by jspaith** [comment]
Could you please provide a short snippet of code that shows this repro'ng and I'll take a look.  Thanks.

**Comment by ArsalanSaleemGhuman** [comment]
here is the serial log that i get when i try to delete the desired property from the azure remote monitoring demo

```
Error: Time:Tue Nov 14 09:41:17 2017 File:/azure/serializer/src/agenttypesystem.c Func:CreateAgentDataType_From_String Line:3307 (result = AGENT_DATA_TYPES_INVALID_ARG)
Error: Time:Tue Nov 14 09:41:17 2017 File:/azure/serializer/src/commanddecoder.c Func:DecodeValueFromNode Line:165 Failed parsing node null.
Error: Time:Tue Nov 14 09:41:17 2017 File:/azure/serializer/src/commanddecoder.c Func:validateModel_vs_Multitree Line:864 failure in DecodeValueFromNode
Error: Time:Tue Nov 14 09:41:17 2017 File:/azure/serializer/src/commanddecoder.c Func:validateModel_vs_Multitree Line:931 not all constituents of the JSON have been ingested
Error: Time:Tue Nov 14 09:41:17 2017 File:/azure/serializer/src/iotdevice.c Func:Device_IngestDesiredProperties Line:440 failure in CommandDecoder_IngestDesiredProperties
Error: Time:Tue Nov 14 09:41:17 2017 File:/azure/serializer/src/codefirst.c Func:CodeFirst_IngestDesiredProperties Line:1612 failure in Device_IngestDesiredProperties
Error: Time:Tue Nov 14 09:41:17 2017 File:/azure/serializer/inc/serializer_devicetwin.h Func:serializer_ingest Line:38 failure ingesting desired properties




```

**Comment by jspaith** [comment]
I took a look at logs but it's still not clear what's up.

By remote monitoring, do you mean $serializer\samples\remote_monitoring as part of the C SDK or is the code someplace else?  Could you give more specifics RE code and the actual JSON changing around here?  

Thanks

**Comment by ArsalanSaleemGhuman** [comment]
@jspaith  @tameraw ,

Remote monitoring is a pre configured solution that Microsoft provides. 
More details can be found here : https://docs.microsoft.com/en-us/azure/iot-suite/iot-suite-remote-monitoring-deploy. 
I have built my application based on the sample https://github.com/Azure-Samples/iot-remote-monitoring-c-raspberrypi-getstartedkit/tree/master/basic/remote_monitoring.

However if you want to reproduce the issue then you can use the samples given within the sdk .
In order to reproduce the issue all you need to do is following:
1)run the samples serializer/samples/devicetwin_simplesample. 
2) in the sample comment the API call  IoTHubClient_SetDeviceTwinCallback() , as mentioned within the demo.
```
                        // Comment out the following three lines if you want to enable callback(s) for updates of the existing model (example: onDesiredMaxSpeed)
//                        if (IoTHubClient_SetDeviceTwinCallback(iotHubClientHandle, deviceTwinGetStateCallback, NULL) != IOTHUB_CLIENT_OK)
//                        {
//                            (void)printf("Failed subscribing for device twin properties\n");
//                        }
```
3) use a backend app to set the desired property to :
```
"{
  "properties": 
  {
    "desired": 
    {
      "changeOilReminder":null
	}
   }
}"
```
i used postman to make an API call to set the desired proeprty.

4) you will see the following error:
```
Error: Time:Mon Nov 20 14:17:33 2017 File: azure-iot-sdk-c/serializer/src/agenttypesystem.c Func:CreateAgentDataType_From_String Line:3723 (result = AGENT_DATA_TYPES_INVALID_ARG)
Error: Time:Mon Nov 20 14:17:33 2017 File: azure/azure-iot-sdk-c/serializer/src/commanddecoder.c Func:DecodeValueFromNode Line:165 Failed parsing node null.
Error: Time:Mon Nov 20 14:17:33 2017 File: azure-iot-sdk-c/serializer/src/commanddecoder.c Func:validateModel_vs_Multitree Line:864 failure in DecodeValueFromNode
Error: Time:Mon Nov 20 14:17:33 2017 File: azure-iot-sdk-c/serializer/src/commanddecoder.c Func:validateModel_vs_Multitree Line:931 not all constituents of the JSON have been ingested
Error: Time:Mon Nov 20 14:17:33 2017 File: azure-iot-sdk-c/serializer/src/iotdevice.c Func:Device_IngestDesiredProperties Line:440 failure in CommandDecoder_IngestDesiredProperties
Error: Time:Mon Nov 20 14:17:33 2017 File: azure-iot-sdk-c/serializer/src/codefirst.c Func:CodeFirst_IngestDesiredProperties Line:1612 failure in Device_IngestDesiredProperties
Error: Time:Mon Nov 20 14:17:33 2017 File: azure-iot-sdk-c/serializer/inc/serializer_devicetwin.h Func:serializer_ingest Line:38 failure ingesting desired properties

```


PS: my initial error and the one given in this comment has difference of line numbers, that is because in the intial reported error i was setting int type desired property to null, in the error given in this comment i am setting a char type desired property to null.

**Comment by jspaith** [comment]
@ArsalanSaleemGhuman - thank you for very detailed repro steps.  

What's happening here is that when you declare 'changeOilReminder' as changeOilReminder, it needs to be a string.  Per http://www.json.org/, a string is either "" or else "chars" which means (unlike a language like C where a string pointer can point at NULL) I don't think null is a valid string in JSON.  This is what initial error `CreateAgentDataType_From_String` is complaining about.

Our serializer doesn't have the concept of optional NULL values, so to represent something as empty I'd recommend using the empty string in the JSON.

**Comment by ArsalanSaleemGhuman** [comment]
@jspaith , 

Thanks for your reply.

My problem here is that i am using the serializer APIs on my device side. From the back end(postman or remote monitoring demo) i am trying to delete a desired property and i am getting an error. To delete a desired property the back end has to set the property value to Null irrespective of the type(char, int, object, etc). This is according to the[ azure iot sdk documentation ](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#back-end-operations) , section : "Partially update device twin". 

If the serializer is not supporting a core feature mentioned in the azure documentation then i think it shall be added to serializer.

**Comment by jspaith** [comment]
@ArsalanSaleemGhuman - I'm following up on this, though there maybe some delays as folks (including me) are going to be out for a bit for Thanksgiving.  We'll have some answer next week at latest.

**Comment by jspaith** [comment]
Apologies for delay here.  We don't have a mechanism to plumb deletes but there maybe a workaround.  When you create the object during the IotHubDeviceTwin_Create<Whatever>, that same pointer that you have initialized is what is pointed to during the callbacks.

So potentially for desired properties, you could do something like
Car* car = IoTHubDeviceTwin_CreateCar(iotHubClientHandle);
car->desired->propertyThatMaybeDeleted = SOME_DEFAULT_VALUE;
--

When you actually get the callbacks unwound, you can see if the PropertyThatMaybeDeleted still has default or not.  This is a good practice never mind deletion scenario, e.g. when the service doesn't specify a value.

**Comment by jspaith** [comment]
Since haven't heard back in a bit, closing.  Feel free to re-open or create new if needed.
