### ISSUE TITLE
Can not create SSL connection to Iot Hub - Handshake missing

### ISSUE THREAD

**Issue by 59985** [Azure/azure-iot-sdk-c#293]
I can’t connect to the Iot Hub by using the iothub_client_sample_mqtt.c. I can create and open the socket. The next step is SSL connection. After sending “hello server” I never get a response “Handshake”.

I am using following threadX, NetX - BSD API, WolfSSL “using the tlsio_wolfssl.c”.

Connect:
    sock.sin_family = AF_INET;
    sock.sin_port = htons(8883);
    sock.sin_addr.s_addr = 0xXXXXXXXX; 
    err = connect(socket_io_instance->socket, (struct sockaddr*)& sock, sizeof(sock));  
//Response here is 0

I tried to set the endpoint to my local laptop and changed the port to 80 just to test the receive function. That was working. I am using the certificate from “certs.c”. 

Have some of you used wolfssl and would like to share the “setting.h” file that wolfssl is using?
Is there a way to do some logging/diagnostic in Azure for this problem?
Is it possible to use a local simulated Iot Hub?
Any other things that I should be aware of.

Regards
Kasper Olsen

**Comment by 59985** [comment]
Here are my Wolfssl defines:

    #define  NO_FILESYSTEM
    #define  WOLFSSL_HAVE_MIN
    #define  WOLFSSL_HAVE_MAX
    #define  NO_ASN_TIME
    #define  HAVE_AES_CBC
    #define  HAVE_AES_DECRYPT        
    #define WOLFSSL_USER_IO
    #define NO_SESSION_CACHE
    #define NO_WOLFSSL_SERVER
    #define FP_MAX_BITS           4096
    #define USE_FAST_MATH
    #define WOLFSSL_SMALL_STACK
    #define TFM_TIMING_RESISTANT 
    #define NO_PSK
    #define KEEP_PEER_CERT
    #define NO_WRITEV
    #define NO_MD2
    #define NO_MD4
    #define NO_DSA
    #define NO_DES3
    #define NO_ERROR_STRINGS
    #define NO_HC128
    #define NO_RC4
    #define NO_RABBIT
    #define NO_WOLFSSL_DIR
    #define USE_CERT_BUFFERS_2048
    #define NO_DEV_RANDOM
    #define NO_MAIN_DRIVER
    #define NO_INLINE
    #define TIME_OVERRIDES
    #define HAVE_TIME_T_TYPE
    #define HAVE_TM_TYPE
    #define HAVE_VALIDATE_DATE
    #define XVALIDATE_DATE(d, f, t) Validate_Date((d), (f), (t))

**Comment by JetstreamRoySprowl** [comment]
@59985 : A few questions:

- What socket_io file are you using? (the underlying_io) of tlsio_wolfssl.c
- What device are you targeting?
- What is the return value from [here?](https://github.com/Azure/azure-c-shared-utility/blob/5949a63d4545be336cff6fe0f2bb5e63e028344b/src/tlsio_wolfssl.c#L252)

**Comment by 59985** [comment]
I am using the "socketio_berkeley.c". I have attached "tlsio_wolfssl.c" and "socketio.c". Socket-io is using the NetX BSD Api.
[tlsio_socket-io.zip](https://github.com/Azure/azure-iot-sdk-c/files/1470001/tlsio_socket-io.zip)

User guide for BSD 4.3 Socket API
https://ko-kr.knowledgebase.renesas.com/@api/deki/files/1407/nxd_bsd.pdf?revision=1

The microprocessor is Renesas R5F563NY

It never returns from wolfSSL_connect(). The function is waiting for handshake.

**Comment by 59985** [comment]
I tried to change to an earlier version of WolfSSL 3.12.0 to 3.4.6 that I use in another project.

int wolfSSL_connect(WOLFSSL* ssl) is now returning with -1

Inside wolfSSL_connect this piece of code returns  the ssl->error “INCOMPLETE_DATA  = -310,        /* don't have enough data to complete task”

            while (ssl->options.serverState < neededState) {
                if ( (ssl->error = ProcessReply(ssl)) < 0) {
                    WOLFSSL_ERROR(ssl->error);   // INCOMPLETE_DATA  = -310,        /* don't have enough data to
                    return SSL_FATAL_ERROR;
                }
                /* if resumption failed, reset needed state */
                else if (neededState == SERVER_FINISHED_COMPLETE)
                    if (!ssl->options.resuming) {
                        if (!ssl->options.dtls)
                            neededState = SERVER_HELLODONE_COMPLETE;
                        else
                            neededState = SERVER_HELLOVERIFYREQUEST_COMPLETE;
                    }
            }

**Comment by JetstreamRoySprowl** [comment]
I know this is a dumb question, but the only time I've seen the handshake fail to complete was when the cert had not gotten set (SET_TRUSTED_CERT_IN_SAMPLES had not gotten set [here](https://github.com/Azure/azure-iot-sdk-c/blob/aaee7baf9deead2cd8efdadaea6bbdb67bf35420/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c#L158)). Is that cert making it all the way down into wolfSSL?

**Comment by 59985** [comment]
I can see in certs.c that there are 4 certificates. Witch one of them shall I use?

**Comment by JetstreamRoySprowl** [comment]
It's a single chain, and you use all of it as the certificates[] value. Make sure you satisfy the define I mentioned [earlier](https://github.com/Azure/azure-iot-sdk-c/blob/aaee7baf9deead2cd8efdadaea6bbdb67bf35420/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c#L158) and it will set the certs as they need to be.

**Comment by 59985** [comment]
I don't know if this is the right place to ask this question, but I will give it a try.

This is in WolfSSL:

My next problem is, that I get the error "MP_EXPTMOD_E".
   /* prevent overflows */
   if (P->used > (FP_SIZE/2)) {
      return FP_VAL;
   }
Somehow I get an overflow, but not sure why.
I can see that the default value of FP_MAX_BITS is 4096.

Do this have anything to do with the large certificate.

**Comment by 59985** [comment]
Thank you for your support. I turned out that the problem was related to Threadx OS.
