### ISSUE TITLE
DPS Client issue in x64

### ISSUE THREAD

**Issue by LeonardBae** [Azure/azure-iot-sdk-c#294]
- **OS and version used:**  Target : Windows 10 IoT Enterprise 

- **SDK version used:** 15063 

# Description of the issue:
I'm doing test the dps client sdk using **TPM(not simulator).**
it is working properly in ARM build.
but, there is some error in x64 build.
An error occurred when iotdpsclient.exe was executed after registering with azure dps service based on TPM. Please refer to the following.

# Code sample exhibiting the issue:
**1. IoT DPS Client SDK (https://github.com/ms-iot/iot-azure-dps-client)
2. IoT SDK C Sample**

# Console log of the issue:
**1. IoT DPS Client SDK Log**
01-07-07 PM [00007236] ----New Session----------------------------------------------------------------
01-07-07 PM [00007236] Entering wmain...
01-07-07 PM [00007236] DoDpsWork
01-07-07 PM [00007236] GetDpsTpmSlot
01-07-07 PM [00007236] tpm slot: 0
01-07-07 PM [00007236] GetServiceUrl
01-07-07 PM [00007236] RunLimpet
01-07-07 PM [00007236] Launching: C:\WINDOWS\system32\limpet.exe 0 -rur
01-07-07 PM [00007236] Exception:
01-07-07 PM [00007236] Exception error code: 2
01-07-07 PM [00007236] Failed to get ServiceUrl:
01-07-07 PM [00007236] Setting ServiceUrl:
01-07-07 PM [00007236] Service URL not found in TPM, query DPS
01-07-07 PM [00007236] GetDpsTpmSlot
01-07-07 PM [00007236] tpm slot: 0
01-07-07 PM [00007236] uri from registry: global.azure-devices-provisioning.net
01-07-07 PM [00007236] uri to char: global.azure-devices-provisioning.net
01-07-07 PM [00007236] scope from registry: 0ne0000XXXX
01-07-07 PM [00007236] scope to char: 0ne0000XXXX
01-07-07 PM [00007236] ResetDps
01-07-07 PM [00007236] GetDpsTpmSlot
01-07-07 PM [00007236] tpm slot: 0
01-07-07 PM [00007236] call limpet <slot> -EHK
01-07-07 PM [00007236] EvictHmacKey
01-07-07 PM [00007236] RunLimpet
01-07-07 PM [00007236] Launching: C:\WINDOWS\system32\limpet.exe 0 -ehk
01-07-07 PM [00007236] Exception:
01-07-07 PM [00007236] Exception error code: 2

**Debug Error!
Program: IotDpsClient.exe
abort() has been called**

**2. IoT SDK C Sample**
Provisioning API Version: 1.1.01
Iothub API Version: 1.1.27

Registering... Press any key to interrupt.

Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED

Registration status: CONNECTED
PUT /0ne0000291F/registrations/bbhmn6nghevsatgkeezbhut3ln6re4zb65pitmxx636kbrevnqea/register?api-version=2017-08-31-preview HTTP/1.1
UserAgent: prov_device_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
Content-Length: 926

len: 926
{"registrationId":"xxxxxxxxxxxxxxxxxxxxxxx","tpm":{"endorsementKey":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}}

Reply Status: 401
Content Len: 1383
{"message":"Authorization required, resend request using supplied key","authenticationKey":"xxxxxxxxxxxxxxxxxxxxx","keyName":"registration"}
Error: Time:Tue Nov 14 16:37:42 2017 File:C:\test\azure-iot-sdk-c\provisioning_client\deps\utpm\src\tpm_codec.c Func:CleanResponseCode Line:196 invalid rawResponse (0x80280400)
Error: Time:Tue Nov 14 16:37:42 2017 File:C:\test\azure-iot-sdk-c\provisioning_client\adapters\hsm_client_tpm.c Func:insert_key_in_tpm Line:299 Failure: TPM2_ActivateCredential
Error: Time:Tue Nov 14 16:37:42 2017 File:C:\test\azure-iot-sdk-c\provisioning_client\adapters\hsm_client_tpm.c Func:hsm_client_tpm_import_key Line:588 Failure inserting key into tpm
Error: Time:Tue Nov 14 16:37:42 2017 File:C:\test\azure-iot-sdk-c\provisioning_client\src\prov_auth_client.c Func:prov_auth_import_key Line:400 failure importing key into tpm
Error: Time:Tue Nov 14 16:37:42 2017 File:C:\test\azure-iot-sdk-c\provisioning_client\src\prov_device_ll_client.c Func:prov_transport_challenge_callback Line:152 Failure to import the provisioning key
Error: Time:Tue Nov 14 16:37:42 2017 File:C:\test\azure-iot-sdk-c\provisioning_client\src\prov_transport_http_client.c Func:prov_transport_http_dowork Line:924 NULL sas_token provided in challenge callback.
Error: Time:Tue Nov 14 16:37:42 2017 File:C:\test\azure-iot-sdk-c\provisioning_client\src\prov_device_ll_client.c Func:on_transport_registration_data Line:454 Failure retrieving data from the provisioning service

**Comment by jebrando** [comment]
Thanks for the bug, I will look at this today and let you know what I find out.

**Comment by jebrando** [comment]
@LeonardBae I was able to setup my VM with a TPM and it worked correctly for 64bit.  I see that you're using the msiot repo which uses the sdk as a submodules and may contribute to some differences.  What kind of tpm are you using?

**Comment by LeonardBae** [comment]
I used dTPM (manufacturer : INTC) on Desktop PC (not using VM).

**Comment by jebrando** [comment]
I'm not able to repo the issue, but I will try to get the TPM that you're working with.  I will comment in a few days and let you know my progress.

**Comment by LeonardBae** [comment]
Thanks, jebrando.
but, I have seen the following forum.
https://social.msdn.microsoft.com/Forums/aspnet/en-US/5e04e461-768e-4e79-88ec-56e3ceb4c68f/tpm-how-to-enable?forum=WindowsIoT
The answer to that question seems not to support INTC's TPM.
Is it right?
In addition, when I test the fTPM of Win10 IoT Core, the key value of fTPM is changed every time it reboots. Is there any scenario that can be used without changing the key value without using integrated TPM?

**Comment by jebrando** [comment]
@LeonardBae I am able to repro the issues.  I sent a message to our hardware security experts and hopefully have a resolution soon.

**Comment by LeonardBae** [comment]
Thanks, @jebrando 
Can you tell me when it will be resolved?
Or is there an update to the Azure IoT SDK?

**Comment by jebrando** [comment]
@LeonardBae If you are still see this as an issue we will have to get the Windows IoT Team involved, the TPM should be able to handle x64 code now.  Please reopen if this remains a problem and we shall contact the Windows IoT Team
