### ISSUE TITLE
Linker error after SSL library exchanged

### ISSUE THREAD

**Issue by TomK7** [Azure/azure-iot-sdk-c#295]
Hi ,
after I proceed the solution steps described in #265 I get the next problem. The execution of the make produces this error:
```
_pi@raspberryfruit:~/Mod1Lab4 $ make all
[ 33%] Linking C executable app
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/6/../../../libaziotsharedutil.a(tlsio_openssl.c.o): undefined reference to symbol 'SSL_load_error_strings@@OPENSSL_1.0.2d'
//usr/lib/arm-linux-gnueabihf/libssl.so.1.0.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/app.dir/build.make:120: die Regel für Ziel „app“ scheiterte
make[2]: *** [app] Fehler 1
CMakeFiles/Makefile2:67: die Regel für Ziel „CMakeFiles/app.dir/all“ scheiterte
make[1]: *** [CMakeFiles/app.dir/all] Fehler 2
Makefile:83: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2_
```
It seems that the Azure IoT SDK for C will also removed with the execution of
`sudo apt-get purge libssl-dev`

Best Regrds
Thomas

**Comment by markrad** [comment]
Hi @TomK7,

My response from https://github.com/Azure/azure-iot-sdk-c/issues/265:

Are you using apt-get to acquire any parts of the Azure IoT SDK? That will likely not work. You will need to build the entire SDK from scratch including the sub modules.

Also possible is that you used the setup script in the SDK. This will inadvertently reinstall the wrong version of OpenSSL. If you do that then follow the instructions in https://github.com/Azure/azure-iot-sdk-c/issues/265 once again to get back to the correct version of OpenSSL.

Mark Radbourne MSFT

**Comment by ewertons** [comment]
Hi @TomK7 , did the suggestions from @markrad address your issue?

**Comment by ewertons** [comment]
@TomK7 ,
we will close this issue for now, but please feel free to reopen it once you have chance to follow up on @markrad 's comment.
Thanks,
Azure IoT Team
