### ISSUE TITLE
how to send data every 10 min in cloud

### ISSUE THREAD

**Issue by vnn0804** [Azure/azure-iot-sdk-c#297]
- **OS and version used:** <VERSION> 

# Description of the issue:

hello i want data transmission time above 10 min how to add this time slot in code please help me , i am using  "iothub_client_sample_mqtt.c" this code.  and /azure-iot-sdk-c/iothub_client/samples/iothub_client_sample_mqtt this is path of this folder

**Comment by ewertons** [comment]
Hi @vnn0804 ,
what do you mean by "data transmission time above 10 min"?
Could you perhaps describe the functionality you are looking for?

**Comment by markrad** [comment]
HI @vnn0804,

Are you asking how to send data every ten minutes? If yes then there is no real easy way to do that with the sample you are looking at. Currently it sends a fixed number of messages at a rate of 1 per millisecond. You would need to main loop such that it would count the number of iterations through the loop. Once that value hits 1000 * 60 * 10 then roughly ten minutes will have passed and you would send your message. There are other mechanisms you could use if the ten minute interval is critical but that is outside the scope of the purpose of this forum. The other issue you would have to address is that the code uses a fixed length array to save the messages it sends and match them to the message confirmation callbacks. You would need to modify this to a dynamic collection such as a linked list.

_Mark Radbourne MSFT_

**Comment by vnn0804** [comment]
thanks markrad..

**Comment by vnn0804** [comment]
thanks mark....

**Comment by vnn0804** [comment]
hi mark,

can you please tell me where is save this 1 per millisecond? is it system
clock file or any other location.

**Comment by ewertons** [comment]
Hi @vnn0804 ,
the Azure IoT C SDK has two client types, one threaded and one non-threaded.

**Non-threaded client:**
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client_ll.h
All the APIs in this client get queued when they are called, and to send/receive messages to the IoT hub the developer needs to constantly call [IoTHubClient_LL_DoWork](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client_ll.h#L417). The recommended frequency is between 1 and 100 milliseconds.

**Threaded client:**
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client.h
This client is a wrapper around the non-threaded client, and it automatically calls the [IoTHubClient_LL_DoWork](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothub_client.c#L581) every [1 millisecond](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothub_client.c#L603), as stated by @markrad .

**Comment by ewertons** [comment]
Hi @vnn0804 ,
we will close this issue. Please feel free to reopen it if you need any more information.
Thanks,
Azure IoT SDK Team
