### ISSUE TITLE
Documentation should be updated to reflect change in Azure IoT SDKs repository

### ISSUE THREAD

**Issue by scout208** [Azure/azure-iot-sdk-c#298]
- **OS and version used:** <VERSION>  N/A

- **SDK version used:** <VERSION>  N/A

# Description of the issue:

The documentation instructions are wrong now in the following areas:

> We need to acquire the SDK source code. This is available in a GitHub repository at https://github.com/Azure/azure-iot-sdks.git. We clone this too our host machine as follows:
```
cd ~
mkdir Source
cd Source
git clone --recursive https://github.com/Azure/azure-iot-sdks.git
```
>Further information regarding this step, which also includes important other set up requirements, can be found at https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md. This step is only included in this document to establish the directory structure used for the rest of the example.

According to a note on the [Azure IoT SDKs](https://github.com/azure/azure-iot-sdks) repository,

>All SDKs have now been moved in their own repositories (see links below). We are not accepting pull-requests on this repository anymore.

So the documentation should be updated to reflect this change. 

- Any reference to https://github.com/Azure/azure-iot-sdks.git should probably be changed to https://github.com/Azure/azure-iot-sdk-c.git
- The link to https://github.com/Azure/azure-iot-sdks/blob/master/c/doc/devbox_setup.md returns 404. This should probably be updated to point to https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md
- Any commands that include the file path `~/Source/azure-iot-sdks/c/` should probably be changed to the file path `~Source/azure-iot-sdk-c/`

**Comment by yzhong94** [comment]
@scout208 Thank you for catching this!  We will release an updated version of the [cross-compiling guide](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md) shortly.
