### ISSUE TITLE
Could NOT Find OpenSSL error when running build on Debian 8.6

### ISSUE THREAD

**Issue by scout208** [Azure/azure-iot-sdk-c#299]
- **OS and version used:** <VERSION>  Debian 8.6

- **SDK version used:** <VERSION>  master

# Description of the issue:

Following the guide [Cross Compiling the Azure IoT Hub SDK](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md), I got to the section [Building the SDK](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md#building-the-sdk) without any issues. However, trying to run the command `./build.sh --toolchain-file toolchain-rpi.cmake -cl --sysroot=$RPI_ROOT` gives me an error message, "Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES  OPENSSL_INCLUDE_DIR)". I know I have openssl installed because I can run `openssl version` and it gives me the openssl version number.

# Code sample exhibiting the issue:

Here's the stack trace in order:

![screenshot from 2017-11-15 14-58-15](https://user-images.githubusercontent.com/9426329/32859873-6c55b3bc-ca15-11e7-9509-3675cd479793.png)

![screenshot from 2017-11-15 15-01-36](https://user-images.githubusercontent.com/9426329/32860020-e4efa3b4-ca15-11e7-9a48-7a1d30b1e9fa.png)

![screenshot from 2017-11-15 14-52-41](https://user-images.githubusercontent.com/9426329/32859627-ac6bdf72-ca14-11e7-8013-7c1822416bd2.png)

# Console log of the issue:

Here's my console log:

![screenshot from 2017-11-15 14-48-10](https://user-images.githubusercontent.com/9426329/32859415-0f357024-ca14-11e7-8528-cc9d1b4ec68e.png)

**Comment by markrad** [comment]
Hi @scout208,

You will need the OpenSSL development package installed which includes the headers etc. I don't have a Debian system up at the moment to test with but I think running
```
sudo apt-get install libssl-dev
```
will resolve your issue. 

_Mark Radbourne MSFT_

**Comment by scout208** [comment]
My mistake was I forgot to run the setup script on my Raspberry Pi before copying the files over. I'm able to get past this now.
