### ISSUE TITLE
X509 Authentication to Azure IoT Hub

### ISSUE THREAD

**Issue by domenicoamelino** [Azure/azure-iot-sdk-c#301]
Hi,

I am working in Windows 10 with a C# Application in order to connect to Azure IoT HUB with X509 Certificates. 

# Description of the issue
I am using the bash linux to generate the CA Identity tutorial shown on the Azure Website support and in this git repository.
I succeed to authenticate and verify the RootCA certificate but the C# Applications (from the example code on https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-security-x509-get-started) does successfully connect to the cloud. 

The device certificate, RootCA and proof of ownership of Root CA Certificate are generated using the certGen.sh  bash script.

# Code sample exhibiting the issue:
using Microsoft.Azure.Devices.Client;
using Microsoft.Azure.Devices.Shared;
using System.Security.Cryptography.X509Certificates;
```sh
namespace SimulateX509Device
{
    class Program
    {
        private static int MESSAGE_COUNT = 5;
        private const int TEMPERATURE_THRESHOLD = 30;
        private static String deviceId = "MyDevice";
        private static float temperature;
        private static float humidity;
        private static Random rnd = new Random();

        static async Task SendEvent(DeviceClient deviceClient)
        {
            string dataBuffer;
            Console.WriteLine("Device sending {0} messages to IoTHub...\n", MESSAGE_COUNT);

            for (int count = 0; count < MESSAGE_COUNT; count++)
            {
                temperature = rnd.Next(20, 35);
                humidity = rnd.Next(60, 80);
                dataBuffer = string.Format("{{\"deviceId\":\"{0}\",\"messageId\":{1},\"temperature\":{2},\"humidity\":{3} }}", deviceId, count, temperature, humidity);
                Message eventMessage = new Message(Encoding.UTF8.GetBytes(dataBuffer));
                eventMessage.Properties.Add("temperatureAlert", (temperature > TEMPERATURE_THRESHOLD) ? "true" : "false");
                Console.WriteLine("\t{0}> Sending message: {1}, Data: [{2}]", DateTime.Now.ToLocalTime(), count, dataBuffer);

                await deviceClient.SendEventAsync(eventMessage);
            }
        }

        static void Main(string[] args)
        {
            try
            {
                var cert = new X509Certificate2(@"<new-device.cert.pfx>", "123");
                var auth = new DeviceAuthenticationWithX509Certificate("MyDevice", cert);
                var deviceClient = DeviceClient.Create("<NameoftheServer>.azure-devices.net", auth, TransportType.Amqp_Tcp_Only);

                if (deviceClient == null)
                {
                    Console.WriteLine("Failed to create DeviceClient!");
                }
                else
                {
                    Console.WriteLine("Successfully created DeviceClient!");
                   
                    SendEvent(deviceClient).Wait();
                }

                Console.WriteLine("Exiting...\n");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error in sample: {0}", ex.ToString());
            }
            Console.ReadLine();
        }
    }


}
```
In particular, when the C# Application tries to connect, i retrieve this Unexpected exception:
Successfully created DeviceClient!

>Device sending 5 messages to IoTHub...
>
>
>
>      14/11/2017 11:58:58> Sending message: 0, Data: >[{"deviceId":"MyDevice","messageId":0,"temperature":23,"humidity":72 }]
>
>Error in sample: System.AggregateException: One or more errors occurred. ---> >Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException:
>
>Tracking Id:3bfa37ae5da74bb4a24c7a1aba2bbda1-G:0-TimeStamp:11/14/2017 10:58:59
>
>  at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass64_0.<ApplyTimeout>b__2(Task t)
>
>   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
>
>   at System.Threading.Tasks.Task.Execute()
>
>--- End of stack trace from previous location where exception was thrown ---
>
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>
>   at SimulateX509Device.Program.<SendEvent>d__6.MoveNext() in C:\Users\amelino\source\repos\SimulateX509Device\SimulateX509Device\Program.cs:line 35

>   --- End of inner exception stack trace ---
>
>   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>
>   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>
>   at System.Threading.Tasks.Task.Wait()
>
>   at SimulateX509Device.Program.Main(String[] args) in C:\Users\amelino\source\repos\SimulateX509Device\SimulateX509Device\Program.cs:line 55
>
>---> (Inner Exception #0) Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException:
>
>Tracking Id:3bfa37ae5da74bb4a24c7a1aba2bbda1-G:0-TimeStamp:11/14/2017 10:58:59
>
>   at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass64_0.<ApplyTimeout>b__2(Task t)
>
>   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
>
>   at System.Threading.Tasks.Task.Execute()
>
>--- End of stack trace from previous location where exception was thrown ---
>
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>
>   at SimulateX509Device.Program.<SendEvent>d__6.MoveNext() in C:\Users\amelino\source\repos\SimulateX509Device\SimulateX509Device\Program.cs:line 35

Any help? Thanks.

**Comment by ewertons** [comment]
@domenicoamelino ,
GitHub doesn't have a nice way to transfer issues between repos. 
This should have been filed under https://github.com/Azure/azure-iot-sdk-csharp

I will file this on the other repo for you and close this issue here.
Be right back with the new issue link.
