### ISSUE TITLE
Broken links on "Firmware update of a Raspberry Pi 3 using Azure IoT Hub device management - The device application sample"

### ISSUE THREAD

**Issue by scout208** [Azure/azure-iot-sdk-c#305]
- **OS and version used:** <VERSION>  N/A

- **SDK version used:** <VERSION>  N/A

# Description of the issue:

Going through the README for [Firmware update of a Raspberry Pi 3 using Azure IoT Hub device management](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_mqtt_dm/pi_device), there are a couple of broken links in the section, [The device application sample](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_mqtt_dm/pi_device#the-device-application-sample), the paragraph as follows:

> The code for the sample application is available in the [azure-io-sdks](https://github.com/azure/azure-io-sdks) repository, but to simplify the exercise, we have compiled and published the sample application in a package. If you want to compile the application along with the rest of the SDK directly on the Pi, you can do so following these [instructions](https://github.com/Azure/azure-iot-sdk-c/blob/doc/get_started/raspbian-3gpi-c.md), but the below instructions assume that you are downloading the app package.

The links in this paragraph both give 404 errors.

# Possible Solution:
I'm not sure about where the second link is supposed to be pointed to, but I'm almost certain the first link is meant to be https://github.com/azure/azure-iot-sdk-c, but that's just a guess as I'm obviously not the one who wrote this README.

**Comment by JetstreamRoySprowl** [comment]
@scout208 Thanks for the report, Connor. I'm checking the link fixes into master now.
