### ISSUE TITLE
Missing documentation on how to run the samples

### ISSUE THREAD

**Issue by scout208** [Azure/azure-iot-sdk-c#306]
- **OS and version used:** <VERSION>  Raspbian 4.1

- **SDK version used:** <VERSION> 1.1.27

# Description of the issue / Steps to reproduce:

Starting on the [Samples for the Azure IoT device SDK for C - How to compile and run the samples](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples#how-to-compile-and-run-the-samples), it reads:

> It is recommended to leverage the library packages when available to run the samples, but sometimes you will need to compile the SDK for/on your device in order to be able to run the samples.

>[This document](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md) describes in detail how to prepare your development environment as well as how to run the samples on Linux, Windows or other platforms.

So, as suggested, I look for a library package for the sample I want to run, **iothub_client_sample_mqtt_dm**. The library package doesn't exist (see https://github.com/Azure/azure-iot-sdk-c/issues/291).

So, next step, as suggested, I look at [This document](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md), which "describes in detail how to prepare your development environment as well as how to run the samples...".

That page describes in detail how to prepare the development environment, but it's missing how to run the samples.

# Proposed Solution
1. Update https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md with detail on how to run the samples.
1. Until https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md is update as in step 1, remove any suggestion that it will contain details on how to run the sample, because I think it does not.

There may be some relevant documentation in a different location. If so, these pages could be updated to reflect this.

Let me know if it looks like I'm missing anything and this is just my mistake.

**Comment by jebrando** [comment]
I added a section in this doc to describe running the samples.  If you have any more issues you can reopen this issue.

Thanks you.
