### ISSUE TITLE
Questions about mqtt_dm

### ISSUE THREAD

**Issue by zmsoft** [Azure/azure-iot-sdk-c#309]
# Console log of the issue:
zmsoft@Vostro-3400:~/Project/iot/fota/azure-iot-sdk-c/cmake/iothub_client/samples/iothub_client_sample_mqtt_dm$ sudo ./iothub_client_sample_mqtt_dm 
[sudo] password for zmsoft: 
isService
device_run_service
pid > 0 and exit
pid < 0 umask
close out the standard file descriptors
zmsoft@Vostro-3400:~/Project/iot/fota/azure-iot-sdk-c/cmake/iothub_client/samples/iothub_client_sample_mqtt_dm$ 

cmake -Dset_trusted_cert_in_samples=ON <path to Azure IoT C SDK>
cmake --build .

**Comment by ewertons** [comment]
If you have pending cloud-to-device messages, as soon as you connect you receive them on the client.
That can cause this sample to terminate right away.

To better assist on this, could you:
1. Paste just the path to the sample (like [this](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt_dm/iothub_client_sample_mqtt_dm.c)) - you can do that on all issues you open, no need to paste the whole code unless you made changes to it;
2. Please run the sample and collect [verbose logs](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_amqp_shared/iothub_client_sample_amqp_shared.c#L259), then share them with us.

**Comment by zmsoft** [comment]
`if (isService)
            {
                printf("isService\n");
                traceOn = false;
                if (device_run_service() == false)
                {
                    printf("Failed to run as a service\n");
                    LogError("Failed to run as a service.");
                    exitCode = -3;
                }
            }`


If turn this part of the code off,the log is:
zmsoft@Vostro-3400:~/Project/iot/fota/azure-iot-sdk-c/cmake/iothub_client/sames/iothub_client_sample_mqtt_dm$ sudo ./iothub_client_sample_mqtt_dm 
[sudo] password for zmsoft: 
Info: Initialize Platform
Info: Instantiate the device.
Info: Initialize From Connection String.
Info: IoT Hub SDK for C, version 1.1.28
Info: Device successfully connected.
Info: DeviceTwin CallBack: Status_code = 204




If you open this part of the code，the log is:
zmsoft@Vostro-3400:~/Project/iot/fota/azure-iot-sdk-c/cmake/iothub_client/sames/iothub_client_sample_mqtt_dm$ sudo ./iothub_client_sample_mqtt_dm 
isService
device_run_service
pid > 0 and exit
pid < 0 umask
close out the standard file descriptors
zmsoft@Vostro-3400:~/Project/iot/fota/azure-iot-sdk-c/cmake/iothub_client/samples/iothub_client_sample_mqtt_dm$ 

There's no pending cloud-to-device messages.But the program is automatically exit.

OS and version used: Ubuntu 14.04

SDK version used: 1.1.28

cmake -Dset_trusted_cert_in_samples=ON
cmake --build .

**Comment by ewertons** [comment]
Hi @zmsoft ,
I am not sure what happened here, since there is not a description on the first message of what the problem is.
Did you edit the initial description?
Please describe the issue you are experiencing in details.

**Comment by ewertons** [comment]
Hi @zmsoft ,
this issue will be closed. Please feel free to reopen it when you have the details to follow up.
Thanks,
Azure IoT Client SDK Team
