### ISSUE TITLE
Never receiving a CONNACK

### ISSUE THREAD

**Issue by 59985** [Azure/azure-iot-sdk-c#313]
Hi there! 

I have problems with connecting to the IoT Hub. The SSL connection is OK and I am getting the callback "onOpenComplete". 

When trying to send the CONNECT messages "sendPacketItem" I never get any response.

Any idears?

Regards
Kasper

**Comment by ewertons** [comment]
@59985 , we need more details to assist you.
Following the template we provide for filling issues when you hit "New Issue", could you please provide the information requested there?
