### ISSUE TITLE
Never receiving a CONNACK when trying to connect with MQTT

### ISSUE THREAD

**Issue by 59985** [Azure/azure-iot-sdk-c#315]
Hi there!

I have problems with connecting to the IoT Hub. The SSL connection is OK and I am getting the callback "onOpenComplete".

When trying to send the CONNECT messages "sendPacketItem" I never get any response.

Any idears?

Regards
Kasper

OS : ThreadX  version ? 
SDK: Azure-iot-sdk "up to date"
TCP/IP: NetX
SSL: WolfSSL 3.12.2

# Description of the issue:
1. After creating the SSL connection I receive the callback 
_static void onOpenComplete(void* context, IO_OPEN_RESULT open_result)_
2. Right after I send the Mqtt connect message
_if (sendPacketItem(mqtt_client, BUFFER_u_char(connPacket), size) != 0)_
3. I then expect a callback, but that is never received 
_static void recvCompleteCallback(void* context, CONTROL_PACKET_TYPE packet, int flags, BUFFER_HANDLE headerData)_

I created an example with WolfMqtt that is working, so I could compare the buffers that is send. They are  exactly the same.

**Comment by ewertons** [comment]
Hi @59985 ,
which sample are you running?
There is a way to enable verbose logging on the iothubclient, like how it's done here:

            bool traceOn = true;
            IoTHubClient_LL_SetOption(iotHubClientHandle, "logtrace", &traceOn);

Could you enable the logs on the sample (if it's not already) and send us the full log printed on the console, please? That will help us addressing this issue.

**Comment by 59985** [comment]
Hi,

Here is my tracelog. I hope this is what you are asking for. That is saved from IAR

[trace.txt](https://github.com/Azure/azure-iot-sdk-c/files/1530682/trace.txt)

Regards
Kasper

**Comment by jebrando** [comment]
@59985 We have fixed a few issues with wolfssl and fixed the connection issues.  If you have any issues with this or find something around this, please reopen.
