### ISSUE TITLE
Unable to Complete Firmware Update Sample on Raspberry Pi 3 Using IoT Hub

### ISSUE THREAD

**Issue by scout208** [Azure/azure-iot-sdk-c#318]
- **OS and version used:** <VERSION>  Windows 10 1709, Raspbian 4.1.18-v7+

- **SDK version used:** <VERSION>  1.1.28

# Description of the issue:

I'm trying to follow the [Firmware Update on Raspberry Pi 3](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_mqtt_dm/pi_device) sample. There's no precompiled app package (https://github.com/Azure/azure-iot-sdk-c/issues/291), so I compiled it myself and ran it. 
 
I think it is working so far because I see my device twin shows "waiting" for firmware update status:

![image](https://user-images.githubusercontent.com/9426329/33575437-41ac5dcc-d902-11e7-98a4-5b1d21e67ac5.png)

Similarly, the [suggested ](https://aka.ms/azureiotfirmwareupdate) Node.js app when I run it:

![image](https://user-images.githubusercontent.com/9426329/33575495-78691dd2-d902-11e7-889e-d0770c647d4b.png)

However, the status never changes, and my Raspberry Pi's output never displays any new lines in the console.

# Code sample exhibiting the issue:

Here's my Node.js code:

````
'use strict';

var Registry = require('azure-iothub').Registry;
var Client = require('azure-iothub').Client;

var connectionString = '{myconnectionstring}';
var registry = Registry.fromConnectionString(connectionString);
var client = Client.fromConnectionString(connectionString);
var deviceToUpdate = 'raspbian-guy';

var queryTwinFWUpdateReported = function() {
    registry.getTwin(deviceToUpdate, function(err, twin){
        if (err) {
          console.error('Could not query twins: ' + err.constructor.name + ': ' + err.message);
        } else {
          console.log((JSON.stringify(twin.properties.reported.iothubDM.firmwareUpdate)) + "\n");
        }
    });
};

var startFirmwareUpdateDevice = function() {
    var params = {
        fwPackageUri: 'https://raspbianfirmwareblob.blob.core.windows.net/myblobs/patched_NOOBS_latest.zip'
    };
  
    var methodName = "firmwareUpdate";
    var payloadData =  JSON.stringify(params);
  
    var methodParams = {
      methodName: methodName,
      payload: payloadData,
      timeoutInSeconds: 30
    };
  
    client.invokeDeviceMethod(deviceToUpdate, methodParams, function(err, result) {
      if (err) {
        console.error('Could not start the firmware update on the device: ' + err.message)
      } 
    });
};

startFirmwareUpdateDevice();
setInterval(queryTwinFWUpdateReported, 500);
````

**Comment by jspaith** [comment]
First, apologies for our delayed response.

For clarification, are you concerned primarily on the C SDK sample or the Node?  It looks like it's Node?

https://github.com/Azure/azure-iot-sdk-node/issues would be a better venue if Node specific.  If from the C sample, I'd need more details about what problem is (as it seems it's OK??).

**Comment by jspaith** [comment]
@scout208 - closing out.  Feel free to re-open this in C SDK (or Node, if appropriate) or create a new issue if you still need assistance here.
