### ISSUE TITLE
delete reported property of device twin

### ISSUE THREAD

**Issue by Zanna-93** [Azure/azure-iot-sdk-c#319]
Ubuntu 17.10 

SDK Version 2017-11-03 

# Description of the issue:
Unable to delete a reported property of a device twin.
I'm doing some tests with the device twin feature, and I've compiled the iothub_client_device_twin sample and I've been able to write on reported properties, set them to different values and create new one.

I've read that in order to delete a reported property I have to send a JSON formatted in this way  `{'property-to-remove': null}`
I've done this with success  passing a static string writing these lines

`const char *reportedState = "{'property-to-remove': null}"`
`(void)IoTHubClient_LL_SendReportedState(iothubclientHandle, (const unsigned char *)reportedState, ... );`
This has worked.
Now I want to automate the serialization because will be a waste to statically fromat a string for every update of the device twin.
I'm struggling when I have to pass the null value, the serializer won't handle it and the program crash.
How do i delete a reported property in the device twin?

# Code sample exhibiting the issue:
Create a model and pass a null value to a field, then try to serialize it.

**Comment by ewertons** [comment]
Hi @Zanna-93 ,
are you trying to use the [Serializer](https://github.com/Azure/azure-iot-sdk-c/tree/master/serializer) code to delete a property?

**Comment by Zanna-93** [comment]
Yes, exactly: I want to serialize reported properties to send back to the hub in order to synchronize the device twin, I also want to be able to remove unused reported properties to avoid bandwidth consumption.
My goal is to create a model which will hold the device twin and serialize/deserialize it to update the confuguration; when I send it back to the iothub I will have both populated and null properties which have to be removed.

**Comment by ewertons** [comment]
@Zanna-93 ,
I believe that is not possible using the serializer client as of now.
The current design expects you to model on the client based exactly on the json you have on the cloud. 

Is it an option for you to serialize/deserialize the json using a third-party lib like parson? 
that way you can skip using the serializer and delete the properties the way you did above.

**Comment by Zanna-93** [comment]
I'm trying to use parson, but if I supply a NULL value the serialiser will exlude that field from the string, so the old reported property will remain

**Comment by jspaith** [comment]
@Zanna-93 - Could you clarify your scenario a bit please?  

An app using the serializer and parson are (as far as I know at least) mutually exclusive.  Either the serializer sits on the raw json stream and then parses it for your app, or else you get the json directly and the serializer isn't in the picture.

**Comment by jspaith** [comment]
@Zanna-93 - As this thread has been quiet for a bit, I'm closing it.  By all means though re-open this issue or create a new one if you need any further help.  Thanks
