### ISSUE TITLE
Cannot send data through AMQP-WS

### ISSUE THREAD

**Issue by suhasdjoshi** [Azure/azure-iot-sdk-c#320]
After establishing a connection with IoT Hub, cannot send data through AMQP-WS.  

- **OS and version used:** <VERSION> <Ubuntu 16.04 64 bit x86 in a Docker container>

- **SDK version used:** <VERSION> <1.1.28 (Latest)>

# Description of the issue:

When we run the IOT SDK C in a stand-alone manner we can send telemetry messages using AMQP-WS. When we add an application called "App1" in the container, even though App1 is not using the cloud connector, we have the following problem. When we try to send data through the AMQP-WS, we get an error from the IOT SDK C. We can send data through HTTPS but not through AMQP-WS. It is a reproducible problem. A retry results into the same error. Can you help us understand why App1 is impacting the IOT SDK C?

# Code sample exhibiting the issue:

IoTHubClient_LL_SendEventAsync(iotHubClientHandle,msgSlot->messageHandle, SendConfirmationCallback, msgSlot);
# Console log of the issue:

Info: Transport state changed from AMQP_TRANSPORT_STATE_NOT_CONNECTED to AMQP_TRANSPORT_STATE_CONNECTING
Info: Transport state changed from AMQP_TRANSPORT_STATE_CONNECTING to AMQP_TRANSPORT_STATE_CONNECTED Error: Time:Thu Dec  7 05:56:50 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:992 Failed performing DoWork for device xxxxxxxxxxxxxxxxxxxxxxx (device reported state 5; number of previous failures: 0)
/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:992 Failed performing DoWork for device 'xxxxxxxxxxxxxxxxxxx' (device reported state 5; number of previous failures: 1) 
Error: Time:Thu Dec  7 05:57:20 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:992 Failed performing DoWork for device xxxxxxxxxxxxxxxxx
Info: Transport state changed from AMQP_TRANSPORT_STATE_CONNECTED to AMQP_TRANSPORT_STATE_BEING_DESTROYED
Error: Time:Thu Dec  7 05:57:25 2017 File:/azure-iot-sdk-c/uamqp/src/amqp_management.c Func:amqp_management_close Line:885 AMQP management instance not open
Error: Time:Thu Dec  7 05:57:25 2017 File:/ /azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_connection.c Func:on_cbs_open_complete Line:149 CBS open failed
Error: Time:Thu Dec  7 05:57:25 2017 File:/ /azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:on_cbs_put_token_complete_callback Line:188 CBS reported status code 0, error: '(null)' for put-token operation for device 'ure=Shar�'
Error: Time:Thu Dec  7 05:57:25 2017 File:/ /azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:on_cbs_put_token_complete_callback Line:188 CBS reported status code 0, error: '(null)' for put-token operation for device 'ure=Shar�'
Error: Time:Thu Dec  7 05:57:25 2017 File:/ /azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:on_cbs_put_token_complete_callback Line:188 CBS reported status code 0, error: '(null)' for put-token operation for device 'ure=Shar�'
Error: Time:Thu Dec  7 05:57:25 2017 File:/ /azure-iot-sdk-c/uamqp/src/saslclientio.c Func:saslclientio_send Line:1131 send called while not open
Error: Time:Thu Dec  7 05:57:25 2017 File:/ /azure-iot-sdk-c/uamqp/src/connection.c Func:on_bytes_encoded Line:239 Cannot send encoded bytes
Error: Time:Thu Dec  7 05:57:25 2017 File:/ /azure-iot-sdk-c/uamqp/src/saslclientio.c Func:on_underlying_io_open_complete Line:177 Open complete received in unexpected state
Error: Time:Thu Dec  7 05:57:25 2017 File:/ /azure-iot-sdk-c/uamqp/src/saslclientio.c Func:saslclientio_close Line:1081 saslclientio_close called while not open
Error: Time:Thu Dec  7 05:57:25 2017 File:/ /azure-iot-sdk-c/uamqp/src/connection.c

**Comment by ewertons** [comment]
@suhasdjoshi , with the info you provided alone we do not have a way to say what could be causing the issue.
As you diligently verified, you can connect to the Azure IoT Hub if using the SDK directly, so that does not point to any issue in the SDK directly.

Have you verified for sure that the connection string you are using is correct? The logs point to some issue related to authentication. Look for hidden characters as well, that's pretty common in Linux environments.
Next, we would suggest to try using your application out of the docker container, to verify if that is causing some specific issue related to connection.

**Comment by ewertons** [comment]
Hi @suhasdjoshi ,
we will close this issue since it has been stale for quite a while.
Once you have more information please feel free to reopen it.
Thanks.
