### ISSUE TITLE
Need Support for Resuming File Uploads to Blob Storage

### ISSUE THREAD

**Issue by MichaelDenczek** [Azure/azure-iot-sdk-c#321]
- **OS and version used:** Windows 7 x64
- **SDK version used:** Latest IoT SDK for C

# Description of the issue:
No support for resuming paused file uploads to Blob Storage.  Especially important for large files.

# Code sample exhibiting the issue:
Code based on Blob_UploadFromSasUri, in blob.c.

# Console log of the issue:
HTTP status from storage does not indicate success (400)

Which occurs when attempting to resume file uploads.

**Comment by ewertons** [comment]
Hi @MichaelDenczek ,
the SDK does not provide a way for pausing an upload. How are you pausing it on the first place?

**Comment by MichaelDenczek** [comment]
Consider the case where a large file is being uploaded to blob storage from an embedded device and the network connectivity is lost.  Upon resumption of network connectivity the current support in the IoT SDK requires the file to be re-uploaded in entirety.

**Comment by ewertons** [comment]
Sounds like a reasonable scenario [emoji suppressed for more formal response].
Let me check the design out and see what we can do to mitigate that.

**Comment by GeraldSchmitt** [comment]
We have similar needs. We would also like to be able to resume after a `IoTHubClient_UploadMultipleBlocksToBlobAsync`.
I suggest an API in issue #371.

**Comment by GeraldSchmitt** [comment]
Hi guys,

About this feature:
 - Is this feature somewhere in your backlog?
    - If yes, is there an ETA?
    - If no, would you consider accepting a PR?
      - Would the API described in issue #371 be OK for the PR?

**Comment by tameraw** [comment]
@GeraldSchmitt - Currently we do not have plans to add this feature at the moment in the SDK. If you are willing to provide a PR we can review and comment. Most probably would not be able to merge this in before end of June.

**Comment by GeraldSchmitt** [comment]
Hi @tameraw 

I would gladly start to work on a PR, but in order to avoid unnecessary work, wouldn't it be better to first settle down an API everybody agrees on?

I suggest an API in issue #371, could you have a look?

Also, in issue #375, after some discussion, emerged the idea of providing directly the blob URI (this simple solution would solve most of our needs concerning blobs), but you guys seems to need more time to think this through. Did you make any progress?

**Comment by GeraldSchmitt** [comment]
Hi guys,

I'm leaving Schneider Electric, and I will no longer follow these topics.
@lmussier (Ludovic Mussier) and @alexmrtn (Alexis Martin) will take care of that from now on.
Have fun !

Cheers,

Gérald

**Comment by rbagree** [comment]
Hi Guys,
Any update on the enhancement in the discussion?

**Comment by yzhong94** [comment]
@rbagree We have multiple conversations with the Azure Storage team to have a Azure Storage C SDK.  Can you help confirm if resume is still a requirement from your end?

**Comment by rbagree** [comment]
@yzhong94 Yes. This is still a requirement as this will allow us to use the SDK in a remote locations where network connectivity is very intermittent.

**Comment by lmussier** [comment]
@yzhong94 We are on the same use case on our side. So this is still a waited feature on our side.

**Comment by yzhong94** [comment]
@rbagree @lmussier thank you for confirming!  We have not dropped this request and we are working with the blob storage team on a solution that works for future blob storage improvement.  We will get back to you on the plan and ETA as soon as it's finalized.

**Comment by mms-** [comment]
Would be nice to have this. Given that the SDK through MQTT/IoT Hub uses Azure blob upload as the only way to upload files from devices?

**Comment by gregman-msft** [comment]
Thank you everyone for the feedback on this issue. This will require new work on the blob storage support, which we are transitioning to a new repository. I have opened up a request on your behalf in this new repository [here](https://github.com/Azure/azure-sdk-for-c/issues/100). Please track the request there and feel free to add any additional comments.

**Comment by az-iot-builder-01** [comment]
@ewertons, @MichaelDenczek, @rbagree, @jspaith, @lmussier, @mms-, @gregman-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
