### ISSUE TITLE
prov_dev_client_sample doesn't work with error on Func:_decode_crypt_object

### ISSUE THREAD

**Issue by SunghwanBae** [Azure/azure-iot-sdk-c#325]
- **OS and version used:** <VERSION>  Windows 7 Enterprise & Microsoft Visual Studio Community 2015

- **SDK version used:** <VERSION>  Iothub API Version: 1.1.28

# Description of the issue:

Device Registration doesn't work.
I followed procedures from link below.
https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509

When I run prov_dev_client_sample, it fails at x509_schannel.c Func:_decode_crypt_object.

Here's the full error messages.
Error: Time:Mon Dec 11 11:42:23 2017 File:D:\Project\Azure IoT Hub\new_azure2\az
ure-iot-sdk-c\c-utility\src\x509_schannel.c Func:_decode_crypt_object Line:87 Fa
iled to CryptDecodeObjectEx x509 private key

# Code sample exhibiting the issue:

# Console log of the issue:

Provisioning API Version: 1.1.01
Iothub API Version: 1.1.28
Error: Time:Mon Dec 11 12:15:44 2017 File:D:\Project\Azure IoT Hub\new_azure3\az
ure-iot-sdk-c\c-utility\src\x509_schannel.c Func:_decode_crypt_object Line:87 Fa
iled to CryptDecodeObjectEx x509 private key
Error: Time:Mon Dec 11 12:15:44 2017 File:D:\Project\Azure IoT Hub\new_azure3\az
ure-iot-sdk-c\c-utility\src\x509_schannel.c Func:_decode_crypt_object Line:87 Ge
tLastError: The system cannot find the file specified.
.
Error: Time:Mon Dec 11 12:15:44 2017 File:D:\Project\Azure IoT Hub\new_azure3\az
ure-iot-sdk-c\c-utility\src\x509_schannel.c Func:_x509_schannel_create Line:357
Failure decoding x509 private key
Error: Time:Mon Dec 11 12:15:44 2017 File:D:\Project\Azure IoT Hub\new_azure3\az
ure-iot-sdk-c\c-utility\src\tlsio_schannel.c Func:_tlsio_schannel_setoption Line
:1357 x509_schannel_create failed

Registering... Press any key to interrupt.

Error: Time:Mon Dec 11 12:19:44 2017 File:D:\Project\Azure IoT Hub\new_azure3\az
ure-iot-sdk-c\provisioning_client\src\prov_device_ll_client.c Func:_Prov_Device_
LL_DoWork Line:792 Timed out connecting to provisioning service
Error: Time:Mon Dec 11 12:19:44 2017 File:D:\Project\Azure IoT Hub\new_azure3\az
ure-iot-sdk-c\provisioning_client\src\prov_device_ll_client.c Func:_Prov_Device_
LL_DoWork Line:792 Timed out connecting to provisioning service

**Comment by jebrando** [comment]
@SunghwanBae this seems like the OS that you're using doesn't support ECC certificates.  Can you send me the release version of your OS or upgrade if at all possible.

**Comment by Senthamizhgp** [comment]
Would like to highlight that I too face the same issue while trying to register device to the provisioning service (using X509 certificate generated using the procedure mentioned in the below link)
https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_provisioning_client.md

Error : 
Provisioning API Version: 1.1.01
Iothub API Version: 1.1.30
Error: Time:Mon Jan 22 20:23:51 2018 File:D:\test\azure-iot-sdk-c\c-utility\src\x509_schannel.c Func:_decode_crypt_
object Line:87 Failed to CryptDecodeObjectEx x509 private key
Error: Time:Mon Jan 22 20:23:51 2018 File:D:\test\azure-iot-sdk-c\c-utility\src\x509_schannel.c Func:_decode_crypt_
object Line:87 GetLastError: The system cannot find the file specified.
.
Error: Time:Mon Jan 22 20:23:51 2018 File:D:\test\azure-iot-sdk-c\c-utility\src\x509_schannel.c Func:_x509_schannel
_create Line:357 Failure decoding x509 private key
Error: Time:Mon Jan 22 20:23:51 2018 File:D:\test\azure-iot-sdk-c\c-utility\src\tlsio_schannel.c Func:_tlsio_schann
el_setoption Line:1366 x509_schannel_create failed

Registering... Press any key to interrupt.

Error: Time:Mon Jan 22 20:23:51 2018 File:D:\test\azure-iot-sdk-c\provisioning_client\src\prov_transport_http_clien
t.c Func:_on_http_connected Line:197 Http connection failed to connect
Error: Time:Mon Jan 22 20:23:51 2018 File:D:\test\azure-iot-sdk-c\provisioning_client\src\prov_device_ll_client.c F
unc:_on_transport_registration_data Line:454 Failure retrieving data from the provisioning service


OS details : Windows 7 Enterprise (Service Pack 1)
VS details : Microsoft Visual Studio Enterprise 2015

**Comment by SunghwanBae** [comment]
Dear @jebrando

I don't understand your comment.
I already shared the information.

Here's the information
- OS and version used: Windows 7 Enterprise (Service Pack 1) & Microsoft Visual Studio Community 2015

It seems that Senthamizhgp has same issue with me.

If ECC certificates could be a problem, could you let me know how to update it on Windows 7?

Thanks~

**Comment by jebrando** [comment]
@SunghwanBae I will try to look at how to update and let you know.

**Comment by jebrando** [comment]
@SunghwanBae I just ran the provisioning sample with your setup and was able to reproduce your issue.  I talk to some of the windows team and ECC certificate support (the provisioning service only uses ECC certificates) was not supported in windows 7.  If you can upgrade to windows 8 the provisioning service should complete successfully.  If you have any more question on this please re-open the issue.

**Comment by wbowers** [comment]
I am running Windows 10 and seeing the same:
IoTHubClient sending 1 messages
IoTHubClient.send_event_async accepted message [0] for transmission to IoT Hub.
IoTHubClient waiting for commands, press Ctrl-C to exit
Send status: IDLE
Error: Time:Mon May 28 15:59:05 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\c-utility\adapters\x509_schannel.c Func:decode_crypt_object Line:87 Failed to CryptDecodeObjectEx x509 private key

Error: Time:Mon May 28 15:59:05 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\c-utility\adapters\x509_schannel.c Func:decode_crypt_object Line:87 GetLastError: An error occurred during encode or decode operation.

.

Error: Time:Mon May 28 15:59:05 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\c-utility\adapters\x509_schannel.c Func:x509_schannel_create Line:357 Failure decoding x509 private key

Error: Time:Mon May 28 15:59:05 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\c-utility\adapters\tlsio_schannel.c Func:tlsio_schannel_setoption Line:1356 x509_schannel_create failed

Error: Time:Mon May 28 15:59:05 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_SetOption Line:2105 transport failed setting option 'x509privatekey' (xio_setoption failed)

Error: Time:Mon May 28 15:59:05 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_ll.c Func:IoTHubClient_LL_SetOption Line:1790 unable to IoTHubTransport_SetOption

Error: Time:Mon May 28 15:59:05 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client.c Func:IoTHubClient_SetOption Line:1506 IoTHubClient_LL_SetOption failed

**Comment by krakorar-mesh** [comment]
I am also encountering this problem.  Please Advise.

**Comment by Bnjmn83** [comment]
The same here:

`(env) PS C:\projects\cp\azure-iot\azure-iot-sdk-python\device\samples> python .\iothub_client_sample_x509.py

Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]
Starting the IoT Hub Python sample...
    Protocol HTTP
    Connection string = HostName=xyz.azure-devices.net;DeviceId=riot-device-cert;x509=true
IoTHubClient sending 5 messages
Error: Time:Wed Aug 15 13:20:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\c-utility\adapters\x509_schannel.c Func:decode_crypt_object Line:87 Failed to CryptDecodeObjectEx x509 private key
Error: Time:Wed Aug 15 13:20:50 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\c-utility\adapters\x509_schannel.c Func:decode_crypt_object Line:87 GetLastError: Bei der Codierung bzw. Decodierung ist ein Fehler aufgetreten.`
