### ISSUE TITLE
Need help for send data to iothub

### ISSUE THREAD

**Issue by zmsoft** [Azure/azure-iot-sdk-c#326]
- **OS and version used:** Linux raspberrypi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux

- **SDK version used:** 1.1.28

# Description of the issue:
I am currently learning to send messages from devices to iothub.
I don't know if I have successfully sent the data,how do I use analog data to send?
How do I set the interval time for each message?
How do I get it to send messages continuously?
Many thanks

# Code sample exhibiting the issue:
[iothub_client_sample_mqtt](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_mqtt)

# Console log of the issue:
pi@raspberrypi:~/azure-iot-sdk-c/cmake/iothub_client/samples/iothub_client_sample_mqtt $ sudo ./iothub_client_sample_mqtt 
Info: IoT Hub SDK for C, version 1.1.28
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [3] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [4] for transmission to IoT Hub.
-> 08:21:43 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: xxx.xxx-xxx.xx/xxx/api-version=2016-11-14&DeviceClientType=iothubclient%2f1.1.28%20(native%3b%20Linux%3b%20armv7l) | PWD: XXXX | CLEAN: 0
<- 08:21:43 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
-> 08:21:43 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/xxx/messages/devicebound/# | QOS: 1
-> 08:21:43 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/xxx/messages/events/temperatureAlert=false&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 3 | PAYLOAD_LEN: 83
-> 08:21:43 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/xxx/messages/events/temperatureAlert=false&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 4 | PAYLOAD_LEN: 83
-> 08:21:43 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/xxx/messages/events/temperatureAlert=false&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 5 | PAYLOAD_LEN: 83
-> 08:21:43 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/xxx/messages/events/temperatureAlert=false&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 6 | PAYLOAD_LEN: 83
-> 08:21:43 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/xxx/messages/events/temperatureAlert=false&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 7 | PAYLOAD_LEN: 83
<- 08:21:43 SUBACK | PACKET_ID: 2 | RETURN_CODE: 1
<- 08:21:44 PUBACK | PACKET_ID: 3
Confirmation[0] received for message tracking id = 0 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- 08:21:44 PUBACK | PACKET_ID: 4
Confirmation[1] received for message tracking id = 1 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- 08:21:44 PUBACK | PACKET_ID: 5
Confirmation[2] received for message tracking id = 2 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- 08:21:44 PUBACK | PACKET_ID: 6
Confirmation[3] received for message tracking id = 3 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- 08:21:44 PUBACK | PACKET_ID: 7
Confirmation[4] received for message tracking id = 4 with result = IOTHUB_CLIENT_CONFIRMATION_OK

**Comment by ewertons** [comment]
Hi @zmsoft ,
your log is great, thanks for sharing it. Make sure you obfuscate your iothub name and device id before posting the logs, so they don't get exposed.

As I can see above, everything is working great. You successfully sent your messages to the IoT Hub.

In the [sample you run](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c), if [SendConfirmationCallback](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c#L119) gets called the Send operation has completed. And the `IOTHUB_CLIENT_CONFIRMATION_OK` result indicates the message was sent with success.

You can verify the messages received by the IoT Hub by using our [Device Explorer](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer).

You should also read these articles to help understand the Azure IoT infrastructure:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-what-is-iot-hub
https://azure.microsoft.com/en-us/services/iot-hub/

**Comment by zmsoft** [comment]
Hi @ewertons ,
Thank you very much for your help.
[Device Explorer](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer)Follow this document to monitor the device,then run the sample application [iothub_client_sample_mqtt](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_mqtt)
the log is the same as above,but Device Explorer seems to doesn't receive anything.
In addition,messages from the cloud to the device can be sent successfully.
![image](https://user-images.githubusercontent.com/8024438/33972329-53223e42-e0b8-11e7-83a2-865213584c8d.png)




![image](https://user-images.githubusercontent.com/8024438/33973156-587b4c22-e0bc-11e7-9bce-be2b381deee3.png)

**Comment by ewertons** [comment]
Hey @zmsoft ,
so if you can send cloud to device messages, it means DeviceExplorer is pointing to the correct IoTHub connection string. Good job on getting it right.

Now make sure you follow this sequence:
1. Open DeviceExplorer and start listening for d2c messages (like you did above) before running the sample; also, do not select the Consumer group, keep it disabled;
2. Run the sample you ran before (make sure the connection string is correct).

Could you give it a try following the above? specially the part about not Enabling the Consumer Group option.

**Comment by zmsoft** [comment]
Hi @ewertons 
As you said, disable the Consumer group,the sequence of operations and the connection string are also correct.The result is the same as above.
![image](https://user-images.githubusercontent.com/8024438/34023464-10cacffa-e180-11e7-96ff-ca4754d30faa.png)
![image](https://user-images.githubusercontent.com/8024438/34023492-2fe81d70-e180-11e7-9207-42c90511e6d9.png)

**Comment by ewertons** [comment]
Well @zmsoft , I am not sure why Device Explorer is not working for you. Your sample for sure is working fine.

Would you be able to try Device Explorer in another machine?
We also have have a version of Device explorer for node.js, if you would like to try: https://www.npmjs.com/package/iothub-explorer

**Comment by markrad** [comment]
Firewall maybe? Device explorer will need to connect out on TCP port 5671.

**Comment by ewertons** [comment]
Hi @zmsoft ,
were you able to verify your network and successfully connection to the IoT Hub?

**Comment by jspaith** [comment]
Hi @zmsoft, since this has been open for a while I'm going to close it out.  If you have followup questions on this or any other area, by all means re-open this issue on create a new one.  Thanks
