### ISSUE TITLE
iothubtransportmqtt_websockets.h does not get installed

### ISSUE THREAD

**Issue by rk-bp** [Azure/azure-iot-sdk-c#327]
- **OS and version used:** <VERSION> 
Yocto Krogoth

- **SDK version used:** <VERSION> 
1.0.28

# Description of the issue:

iothubtransportmqtt_websockets.h does not get installed

# Code sample exhibiting the issue:

From 98d3faf0ce993e9c0c3980c8588d85575b4e252f Mon Sep 17 00:00:00 2001
From: Robert Vincent Krakora <rob.krakora@bluepillar.com>
Date: Wed, 13 Dec 2017 11:30:31 -0500
Subject: [PATCH] Add iothubtransportmqtt_websockets.h to install

---
 iothub_client/CMakeLists.txt | 1 +
 1 file changed, 1 insertion(+)

diff --git a/iothub_client/CMakeLists.txt b/iothub_client/CMakeLists.txt
index 9a4c8622..6d79d380 100644
--- a/iothub_client/CMakeLists.txt
+++ b/iothub_client/CMakeLists.txt
@@ -207,6 +207,7 @@ if(${use_mqtt})
     set(iothub_client_h_install_files
         ${iothub_client_h_install_files}
         ${iothub_client_mqtt_transport_h_files}
+       ./inc/iothubtransportmqtt_websockets.h
     )
 endif()

-- 
2.15.1

# Console log of the issue:

Unless I modify the iothub_client/CMakeLists.txt file via the patch above, iothubtransportmqtt_websockets.h does not get installed.

**Comment by ewertons** [comment]
Hi @rk-bp , could you send us a PR? we will get it merged right away.

**Comment by ewertons** [comment]
This issue has been addressed by this pull request: https://github.com/Azure/azure-iot-sdk-c/pull/324
We will close this issue, but please feel free to reopen it if you need any follow up.

Thanks for contributing to the Azure IoT SDKs!
