### ISSUE TITLE
Provisioning Sample dosen't work with TPM Simulator

### ISSUE THREAD

**Issue by SunghwanBae** [Azure/azure-iot-sdk-c#329]
- **OS and version used:** <VERSION> windows 7 enterprise, Microsoft visual studio 2015

- **SDK version used:** <VERSION> 
Provisioning API Version: 1.1.01
Iothub API Version: 1.1.28

# Description of the issue:

I tried to follow the tutorial from the link below, but I couldn't do it because there is no dps_client directory.
https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device

1. run following command
    cmake -Duse_prov_client:BOOL=ON ..

2. Right Click the "tpm_device_provision" and select "Set as Startup Project"
3. Run Simulator.exe and run the solution
4. It didn't work. It was trying to use functions "in tpm_comm_win32.c". I modified "CMakeLists.txt" to make it use functions in "tpm_comm_emulator.c".
5. Run the solution and get Endormence Key and Registration ID
6. Added it under enrollment list as described at https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device
7. Get ID Scope and put it on prov_dev_client_sample.c
8. Right Click the "prov_dev_client_sample.c" and select "Set as Startup Project"
9. Change "hsm_type" to "SECURE_DEVICE_TYPE_TPM" on prov_dev_client_sample.c
10. Run the solution

There was Timeout error for connecting to provision service.

# Code sample exhibiting the issue:

# Console log of the issue:

Provisioning API Version: 1.1.01
Iothub API Version: 1.1.28

Registering... Press any key to interrupt.

Error: Time:Thu Dec 14 11:03:04 2017 File:D:\Project\Azure IoT Hub\Azure_devicep
rovision\azure-iot-sdk-c\provisioning_client\src\prov_device_ll_client.c Func:_P
rov_Device_LL_DoWork Line:792 Timed out connecting to provisioning service
Error: Time:Thu Dec 14 11:03:04 2017 File:D:\Project\Azure IoT Hub\Azure_devicep
rovision\azure-iot-sdk-c\provisioning_client\src\prov_device_ll_client.c Func:_P
rov_Device_LL_DoWork Line:792 Timed out connecting to provisioning service

**Comment by jebrando** [comment]
@SunghwanBae - Have you tried this with the latest sdk, we have a bunch of fixes to this?  If not can you please try with the latest sdk and if this is still an issue can you retry.

**Comment by SunghwanBae** [comment]
Dear Jebrando

I tried it with latest code today, but it's not working.
I followed the tutorial from the link below.
https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device

Here's the log message when I run "prov_dev_client_sample" project.
========================================

Provisioning API Version: 1.1.2
Iothub API Version: 1.1.30

Registering... Press any key to interrupt.

Error: Time:Mon Jan 29 13:46:13 2018 File:D:\Project\Azure IoT Hub\azure-iot-sdk
-c\provisioning_client\src\prov_transport_http_client.c Func:_on_http_connected
Line:197 Http connection failed to connect
Error: Time:Mon Jan 29 13:46:13 2018 File:D:\Project\Azure IoT Hub\azure-iot-sdk
-c\provisioning_client\src\prov_device_ll_client.c Func:_on_transport_registrati
on_data Line:454 Failure retrieving data from the provisioning service

...

Error: Time:Mon Jan 29 13:47:19 2018 File:D:\Project\Azure IoT Hub\azure-iot-sdk
-c\provisioning_client\src\prov_device_ll_client.c Func:_Prov_Device_LL_DoWork L
ine:801 Timed out connecting to provisioning service
========================================
