### ISSUE TITLE
iothub_client_sample_mqtt work error

### ISSUE THREAD

**Issue by ftnkn** [Azure/azure-iot-sdk-c#330]
iothub_client_sample_mqtt work ok on ubuntu;
when i compile it to arm platfrom, run on device, it work error , log is below:

[root@mdvr:/]# ./app/bin/iothub_client_sample_mqtt 
Info: IoT Hub SDK for C, version 1.1.28
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.
Info: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
IoTHubClient_LL_SendEventAsync accepted message [3] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [4] for transmission to IoT Hub.
Info: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Info: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Info: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR

**Comment by ewertons** [comment]
@ftnkn ,
could you provide all the details required on the template that shows up when you click on "New issue"? 
Please also check if there are issues already opened that match the problem your are experiencing.
It seems very related to https://github.com/Azure/azure-iot-sdk-c/issues/328

**Comment by ewertons** [comment]
Hi @ftnkn ,
we will close this issue since it has been stale for quite a while.
Once you have more information please feel free to open a new one with the full description.
Thanks.
