### ISSUE TITLE
Question regarding ContentType

### ISSUE THREAD

**Issue by davidbuechi** [Azure/azure-iot-sdk-c#331]
- **SDK version used:** current master

# Description of the issue:
The usage of `IoTHubMessage_SetContentTypeSystemProperty()` the the samples is not consistent and therefore a bit confusing.

# Code sample exhibiting the issue:

**iothub_client_sample_http:**
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_http/iothub_client_sample_http.c#L228

-> function in comments with a TODO to be enabled again (?)

**iothub_client_sample_mqtt**
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c#L195

-> function active with URL encoded string

**iothub_client_sample_amqp**
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_amqp/iothub_client_sample_amqp.c#L226

-> function active without URL encoding

# Questions

1. should we use it?
1. if yes: with or without URL encoding?
1. what happens on IoTHub if:
   1. not using it
   1. using it wrongly

**Comment by ewertons** [comment]
1. Yes. The commented lines in the http sample were M.I.A.
2. Should be without URL encoding, that should be done automatically by the client. The misbehavior in MQTT transport seems like a bug. AFAIK AMQP should be doing it correctly;
3. IoT Hub should be URL decoding it before it's used; let me get an official confirmation and reply back to you.

Sorry if the next replies are a little slow, most people are leaving on vacation.

**Comment by davidbuechi** [comment]
any update on this?

**Comment by jspaith** [comment]
We're beginning investigation on this currently and will let you know what we find.

**Comment by jspaith** [comment]
Just a quick update here -- we're working on a fix.  We'll have more details when the fix comes out, but you're correct we'll need to add MQTT url encoding/decoding as an option (we can't do by default because of back-compat).  Coming soon.

**Comment by cartertinney** [comment]
Update: We have completed a fix that adds automatic URL encoding/decoding on MQTT. You can now optionally turn on this feature by using the following SetOption:

bool urlEncodeOn = true;
IoTHubClient_LL_SetOption(iothub_ll_handle, OPTION_AUTO_URL_ENCODE_DECODE, &urlEncodeOn);

This feature is currently available now in the master branch of the source code repository, and will be included in the next release of packages later this month.

**Comment by davidbuechi** [comment]
Hi @cartertinney 

where do I find the a documentation about this new parameter? There is no reference in [Iothub_sdk_options.md](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Iothub_sdk_options.md)!

And back to my original question: how/when should I use `IoTHubMessage_SetContentTypeSystemProperty()`?



In the mean time the samples have been reworked, but they still seem to be inconsistent:
**iothub_ll_telemetry_sample.c** and **iothub_ll_client_x509_sample.c** are using `IoTHubMessage_SetContentTypeSystemProperty(message_handle, "application%2Fjson")`, all the other samples do not use this function. What are the reason for using resp. not using it? What are the consequences, esp. regarding the behaviour on the IoT-Hub side?

**Comment by cartertinney** [comment]
1) I'll be updating the documentation as soon as possible with the relevant details. Thanks for catching that. In the meantime, you can use the parameter as outlined in the post above. Simply turning it on will activate automatic URL encoding on "device to cloud" messages, and URL decoding on "cloud to device" messages when using MQTT. We recommend you always use this option unless URL Encoding on your own.

2) `IoTHubMessage_SetContentTypeSystemProperty` allows you to set the content type for the message payload as per supported values on RFC 2046 (i.e. text/plain, application/json, etc.). As for why you would want to use that, setting the content type to application/json is required for utilizing [IoTHub Message Routing][https://azure.microsoft.com/en-us/blog/iot-hub-message-routing-now-with-routing-on-message-body/]. Please refer to the IoT-Hub documentation for questions regarding it's functionality.

**Comment by yzhong94** [comment]
@davidbuechi , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
