### ISSUE TITLE
x.509 use with HSM

### ISSUE THREAD

**Issue by rari2012** [Azure/azure-iot-sdk-c#332]
Hello Azure IoT Team,
First of all - thank you for this SDK.
But i need to forward this issue, regarding security.

I was working with the new Device Provisioning Service and the provided SDK for it.
While I was testing with the x.509 and my college also – we experienced a strange thing:
I deployed a self-signed certificate to the DPS and configured a individual deployment.
It was the certificate, created with the tool provided by the SDK.
 
My deployment went pretty well. To test the security, my college went on to test also the DPS with individual deployment.
To test - her used the same DPS with no extra deployment, just the one I configured with my certificate in the DPS – and wonder what: he was able to deploy his device!
 
Why could this happen? He used the same SDK like I did – and there in is a hard configured DeviceID Key to sign the certificate:
[Here ](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/adapters/hsm_client_riot.c) start reading on line 89.
 
There is no #IF DEBUG and no hint any where in the documentation – just in the implementation of the Key.
 
Also we see trouble with using a HSM – there is no implementation for it, just a comment: Ask the manufacturer.
 
If we are talking about an SDK for such high potential risk implementation like this, with all the disussions about security – it must be documented and it should have a hint how to implement then the HSM.

**Comment by jebrando** [comment]
Currently the provisioning client use the hsm_client_riot.c file as a canned x509 generator for development purposes (Most people don't have a DICE security chip in there device).  If you would like to create a custom x509 certificate we have a document detailing how to do it (https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_custom_hsm.md).  Let me know if you have any questions on this.
