### ISSUE TITLE
Read data from the Iot Hub "C2D" using the mqtt protocol. 

### ISSUE THREAD

**Issue by 59985** [Azure/azure-iot-sdk-c#333]
Hi there! 

Do some of you have an example how to read data from the Iot Hub "C2D" using the mqtt protocol. 

Regards
Kasper

**Comment by ewertons** [comment]
Using the device client?
Please explore here: https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples

**Comment by jspaith** [comment]
@59985, I'm closing because this has been inactive for a while.  If you have followups on this or other issues though please re-open this or open a new issue.
