### ISSUE TITLE
error building without uAMQP 

### ISSUE THREAD

**Issue by pilotone56** [Azure/azure-iot-sdk-c#336]
building on linux ubuntu x86-64 host for an arm target

- **OS and version used:** <VERSION> 
host: ubuntu 15.04 -> target:rasperian
- **SDK version used:** <VERSION> 
release-2017-12-14

# Description of the issue:

with a configuration for umqtt only (i.e amqp switched off) this fails to build. looks like code is on the wrong side of #ifndef
# Code sample exhibiting the issue:

# Console log of the issue:
Building C object uamqp/CMakeFiles/uamqp.dir/src/async_operation.c.o
cd ..../Home/linuxspud/azure-iot-sdk-c/cmake/iotsdk_linux/uamqp && /opt/vcharge/rpitools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc  -DARCHITECTURE_ARM=1 -DDONT_USE_UPLOADTOBLOB -DREFCOUNT_ATOMIC_DONTCARE -D__STDC_NO_ATOMICS__=1 --std=c99   -D_POSIX_C_SOURCE=200112L   -fPIC  -Werror -Werror -Werror -fPIC -I..../Home/linuxspud/azure-iot-sdk-c/uamqp/deps/azure-c-shared-utility/inc -I..../Home/linuxspud/azure-iot-sdk-c/uamqp/deps/azure-c-shared-utility/pal/linux -I..../Home/linuxspud/azure-iot-sdk-c/uamqp/inc -I..../Home/linuxspud/azure-iot-sdk-c/c-utility/inc -I..../Home/linuxspud/azure-iot-sdk-c/c-utility/pal/linux    -o CMakeFiles/uamqp.dir/src/async_operation.c.o   -c ..../Home/linuxspud/azure-iot-sdk-c/uamqp/src/async_operation.c
In file included from ..../Home/linuxspud/azure-iot-sdk-c/iothub_client/inc/blob.h:31:0,
                 from ..../Home/linuxspud/azure-iot-sdk-c/iothub_client/src/blob.c:7:
..../Home/linuxspud/azure-iot-sdk-c/iothub_client/inc/blob.h:61:92: error: unknown type name ‘IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_CALLBACK’
 MOCKABLE_FUNCTION(, BLOB_RESULT, Blob_UploadMultipleBlocksFromSasUri, const char*, SASURI, IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_CALLBACK, getDataCallback, void*, context, unsigned int*, httpStatus, BUFFER_HANDLE, httpResponse, const char*, certificates, HTTP_PROXY_OPTIONS*, proxyOptions)
                                                                                            ^
..../Home/linuxspud/azure-iot-sdk-c/c-utility/inc/azure_c_shared_utility/umock_c_prod.h:25:66: note: in definition of macro ‘UMOCK_C_PROD_ARG_IN_SIGNATURE’
 #define UMOCK_C_PROD_ARG_IN_SIGNATURE(count, arg_type, arg_name) arg_type arg_name IFCOMMA(count)
                                                                  ^
..../Home/linuxspud/azure-iot-sdk-c/c-utility/inc/azure_c_shared_utility/macro_utils.h:7169:1: note: in expansion of macro ‘FOR_EACH_2_COUNTED_12’
 FOR_EACH_2_COUNTED_12(X, P3, P4, P5, P6, P7, P8, P9, P10, P11, P12, P13, P14)
 ^
..../Home/linuxspud/azure-iot-sdk-c/c-utility/inc/azure_c_shared_utility/macro_utils.h:4355:18: note: in expansion of macro ‘FOR_EACH_2_COUNTED_14’
 #define C2_(x,y) x##y
                  ^
..../Home/linuxspud/azure-iot-sdk-c/c-utility/inc/azure_c_shared_utility/umock_c_prod.h:31:64: note: in expansion of macro ‘FOR_EACH_2_COUNTED’
     result modifiers function(IF(COUNT_ARG(__VA_ARGS__),,void) FOR_EACH_2_COUNTED(UMOCK_C_PROD_ARG_IN_SIGNATURE, __VA_ARGS__));
                                                                ^
..../Home/linuxspud/azure-iot-sdk-c/iothub_client/inc/blob.h:61:1: note: in expansion of macro ‘MOCKABLE_FUNCTION’
 MOCKABLE_FUNCTION(, BLOB_RESULT, Blob_UploadMultipleBlocksFromSasUri, const char*, SASURI, IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_CALLBACK, getDataCallback, void*, context, unsigned int*, httpStatus, BUFFER_HANDLE, httpResponse, const char*, certificates, HTTP_PROXY_OPTIONS*, proxyOptions)
 ^
..../Home/linuxspud/azure-iot-sdk-c/iothub_client/src/blob.c:127:69: error: unknown type name ‘IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_CALLBACK’
 BLOB_RESULT Blob_UploadMultipleBlocksFromSasUri(const char* SASURI, IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_CALLBACK getDataCallback, void* context, unsigned int* httpStatus, BUFFER_HANDLE httpResponse, const char* certificates, HTTP_PROXY_OPTIONS *proxyOptions)
                                                                     ^
make[2]: *** [iothub_client/CMakeFiles/iothub_client_amqp_ws_transport.dir/src/blob.c.o] Error 1

**Comment by jebrando** [comment]
@pilotone56 I have a fix for the issue that you encountered.  I will put this into code review and work on getting this in the repo, but due to the holiday there shall be a slight delay in getting this in.

**Comment by jebrando** [comment]
This fix is in the code base and should be working correctly.  Please open a new issue if you encounter any more errors.
