### ISSUE TITLE
CA certificate generation errors using powershell scripts for IoT Edge devices

### ISSUE THREAD

**Issue by mrohera** [Azure/azure-iot-sdk-c#337]
- **OS and version used:** Windows 10

- **SDK version used:**  C Device SDK (version 1.1.29)

# Description of the issue:

The documentation to configure and operate the Azure IoT Edge as a gateway is documented here: [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway
](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway) 

As part of the instructions, it is required to create a CA and an Edge device certificate and to be able to generate these, the documentation links to [https://github.com/Azure/azure-iot-sdk-c/blob/modules-preview/tools/CACertificates/CACertificateOverview.md](https://github.com/Azure/azure-iot-sdk-c/blob/modules-preview/tools/CACertificates/CACertificateOverview.md).

The issue is that the instructions to create the required certificates using Powershell scripts results in errors when setting up the IoT Edge. There are a few problems but the very first error users will run into when setting up the Edge using the _iotedgectl_ utility: "Currently RSA is only supported".

The good news is that it appears that there a fix is available in branch [https://github.com/Azure/azure-iot-sdk-c/tree/CACertToolEdge/tools/CACertificates](https://github.com/Azure/azure-iot-sdk-c/tree/CACertToolEdge/tools/CACertificates)

Could these changes in the _CACertificates_ branch be merged to the appropriate branches such as _master_ and _modules-preview_?

**Comment by jspaith** [comment]
I've brought them into modules-preview.  #d820337e0e15fb01c3660b791641e5347a235971.
