### ISSUE TITLE
failed to recover from connection errors

### ISSUE THREAD

**Issue by kireli** [Azure/azure-iot-sdk-c#338]
- **OS and version used:** Linux  4.1.15 Embedded 

- **SDK version used:** 1.1.28

# Description of the issue:
Yesterday, device connection with iothub does not recover for around 10 hours, and finally, it get it through without human intervention. I didn't add status callback, but only message confirmation callback. When disconnection happens, four messages are outbound, but no TIMEOUT or ERROR confirmation callback are triggered. I confirmed during this time, the device's network connection was good.
This happens since around 3:30 util 14:30, and the log shows repeatedly CONNACK errors from 3:38 to 9:58, but nothing pop up during 10:00 to 14:40. Please check the log details below! Thanks!

# Console log of the issue:
Error: Time:Thu Dec 21 03:38:32 2017 File:/home/yohn/sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:1845 mqtt_client timed out waiting for CONNACK
Error: Time:Thu Dec 21 03:38:32 2017 File:/home/yohn/sdk/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:814 Failure: sending socket failed. errno=32 (Broken pipe).
Error: Time:Thu Dec 21 03:38:32 2017 File:/home/yohn/sdk/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:write_outgoing_bytes Line:628 Error in xio_send.
Error: Time:Thu Dec 21 03:38:32 2017 File:/home/yohn/sdk/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1357 Error in write_outgoing_bytes.
Error: Time:Thu Dec 21 03:38:32 2017 File:/home/yohn/sdk/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1358: Failure sending control packet data
Error: Time:Thu Dec 21 03:38:32 2017 File:/home/yohn/sdk/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1176 Error: mqtt_client_disconnect send failed
Error: Time:Thu Dec 21 03:42:33 2017 File:/home/yohn/sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:1845 mqtt_client timed out waiting for CONNACK
Error: Time:Thu Dec 21 03:42:33 2017 File:/home/yohn/sdk/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1334 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Thu Dec 21 03:42:33 2017 File:/home/yohn/sdk/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1335: Failure sending control packet data
Error: Time:Thu Dec 21 03:42:33 2017 File:/home/yohn/sdk/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1176 Error: mqtt_client_disconnect send failed
.......
.......
.......
Error: Time:Thu Dec 21 07:39:14 2017 File:/home/yohn/sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:1845 mqtt_client timed out waiting for CONNACK
Error: Time:Thu Dec 21 07:39:14 2017 File:/home/yohn/sdk/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:814 Failure: sending socket failed. errno=32 (Broken pipe).
Error: Time:Thu Dec 21 07:39:14 2017 File:/home/yohn/sdk/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:write_outgoing_bytes Line:628 Error in xio_send.
Error: Time:Thu Dec 21 07:39:14 2017 File:/home/yohn/sdk/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1357 Error in write_outgoing_bytes.
Error: Time:Thu Dec 21 07:39:14 2017 File:/home/yohn/sdk/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1358: Failure sending control packet data
Error: Time:Thu Dec 21 07:39:14 2017 File:/home/yohn/sdk/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1176 Error: mqtt_client_disconnect send failed
Error: Time:Thu Dec 21 09:58:09 2017 File:/home/yohn/sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:1845 mqtt_client timed out waiting for CONNACK
Error: Time:Thu Dec 21 09:58:09 2017 File:/home/yohn/sdk/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1334 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Thu Dec 21 09:58:09 2017 File:/home/yohn/sdk/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1335: Failure sending control packet data
Error: Time:Thu Dec 21 09:58:09 2017 File:/home/yohn/sdk/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1176 Error: mqtt_client_disconnect send failed

**Comment by jebrando** [comment]
@kireli How did you confirm that the network connection was good?  I see an log at 7:39:14 that state errno 32 broken pipe.  This usually indicates a bad network connection.  Did you see anything on your end that indicated that the network connection is good?

Thanks,
Jelani

**Comment by kireli** [comment]
@jebrando Hi! Yes. Our device now is under field test, we have a process to periodically (4 min) ping two public website's domain name to check the connection status, and we would log down all the results of the ping response. During the time the iothub connection broke, we don't see even one failure of the ping, so we believe the network connection should be good!

Thanks,
Kire

**Comment by jebrando** [comment]
@kireli We have made changes to our underlying socket connection to detect failure.  This should be a fix for issues like yours.  Let us know if you have any more issues.

**Comment by kireli** [comment]
@jebrando Thank you a lot!
I would apply the change and test it in the field!

**Comment by mbalija** [comment]
I too have similar issue, could you give the process of upgrading the packages, 
Error: Time:Wed Feb 14 20:32:19 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:814 Failure: sending socket failed. errno=32 (Broken pipe).
Error: Time:Wed Feb 14 20:32:19 2018 File:/usr/sdk/src/c/c-utility/src/tlsio_openssl.c Func:write_outgoing_bytes Line:628 Error in xio_send.
Error: Time:Wed Feb 14 20:32:19 2018 File:/usr/sdk/src/c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1357 Error in write_outgoing_bytes.
Error: Time:Wed Feb 14 20:32:19 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1358: Failure sending control packet data
Error: Time:Wed Feb 14 20:32:19 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_publish Line:1030 Error: mqtt_client_publish send failed
Error: Time:Wed Feb 14 20:32:19 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:publish_mqtt_telemetry_msg Line:777 Failed attempting to publish mqtt message
Confirmation[0] received for message with result = ERROR

**Comment by kireli** [comment]
@mbalija I just upgrade the sdk to the newest version. Till now, no problem happens, but this problem itself is hard to reproduce.
