### ISSUE TITLE
How to configure MQTT retry connection ?

### ISSUE THREAD

**Issue by andychu15** [Azure/azure-iot-sdk-c#339]
- **OS and version used:** <Linux mebed 4.1.0>

- **SDK version used:** <Info: IoT Hub SDK for C, version 1.1.29>

# Description of the issue:
The issue happens when network is disconnected. The iothub_client_sample_mqtt program is able to retry connection. However, the interval of retry behavior will get longer and longer. How can I configure the interval of retry behavior in a specific period ? e.g, retry connection in every 20 seconds.

# Console log of the issue:
Error: Time:Mon Dec 25 12:26:45 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1245 Failed opening the underlying I/O.
Error: Time:Mon Dec 25 12:26:45 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:971 Error: io_open failed
Error: Time:Mon Dec 25 12:26:45 2017 File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1782 failure connecting to address Moxa-IoT-Lab.azure-devices.net.
Error: Time:Mon Dec 25 12:27:05 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:627 Failure: getaddrinfo failure -3.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Mon Dec 25 12:27:05 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:731 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Dec 25 12:27:05 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1245 Failed opening the underlying I/O.
Error: Time:Mon Dec 25 12:27:05 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:971 Error: io_open failed
Error: Time:Mon Dec 25 12:27:05 2017 File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1782 failure connecting to address Moxa-IoT-Lab.azure-devices.net.
Error: Time:Mon Dec 25 12:27:25 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:627 Failure: getaddrinfo failure -3.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Mon Dec 25 12:27:25 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:731 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Dec 25 12:27:25 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1245 Failed opening the underlying I/O.
Error: Time:Mon Dec 25 12:27:25 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:971 Error: io_open failed
Error: Time:Mon Dec 25 12:27:25 2017 File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1782 failure connecting to address Moxa-IoT-Lab.azure-devices.net.
Error: Time:Mon Dec 25 12:27:45 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:627 Failure: getaddrinfo failure -3.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Mon Dec 25 12:27:45 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:731 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Dec 25 12:27:45 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1245 Failed opening the underlying I/O.
Error: Time:Mon Dec 25 12:27:45 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:971 Error: io_open failed
Error: Time:Mon Dec 25 12:27:45 2017 File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1782 failure connecting to address Moxa-IoT-Lab.azure-devices.net.
Error: Time:Mon Dec 25 12:27:46 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1334 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Mon Dec 25 12:27:46 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1335: Failure sending control packet data
-> 12:27:46 PINGREQ
Error: Time:Mon Dec 25 12:28:18 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:627 Failure: getaddrinfo failure -3.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Mon Dec 25 12:28:18 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:731 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Dec 25 12:28:18 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1245 Failed opening the underlying I/O.
Error: Time:Mon Dec 25 12:28:18 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:971 Error: io_open failed
Error: Time:Mon Dec 25 12:28:18 2017 File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1782 failure connecting to address Moxa-IoT-Lab.azure-devices.net.
Error: Time:Mon Dec 25 12:28:18 2017 File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_error_callback Line:1447 Mqtt Ping Response was not encountered.  Reconnecting device...
Error: Time:Mon Dec 25 12:28:18 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1334 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Mon Dec 25 12:28:18 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1335: Failure sending control packet data
Error: Time:Mon Dec 25 12:28:18 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1176 Error: mqtt_client_disconnect send failed
**Error: Time:Mon Dec 25 12:29:22 2017** File:/home/moxa/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:627 Failure: getaddrinfo failure -3.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Mon Dec 25 12:29:22 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:731 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Dec 25 12:29:22 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1245 Failed opening the underlying I/O.
Error: Time:Mon Dec 25 12:29:22 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:971 Error: io_open failed
Error: Time:Mon Dec 25 12:29:22 2017 File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1782 failure connecting to address Moxa-IoT-Lab.azure-devices.net.
Error: Time:Mon Dec 25 12:29:22 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1334 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Mon Dec 25 12:29:22 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1335: Failure sending control packet data
-> 12:29:22 PINGREQ
Error: Time:Mon Dec 25 12:29:38 2017 File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_error_callback Line:1447 Mqtt Ping Response was not encountered.  Reconnecting device...
Error: Time:Mon Dec 25 12:29:38 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1334 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Mon Dec 25 12:29:38 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1335: Failure sending control packet data
Error: Time:Mon Dec 25 12:29:38 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1176 Error: mqtt_client_disconnect send failed

**Error: Time:Mon Dec 25 12:31:33 2017** File:/home/moxa/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:627 Failure: getaddrinfo failure -3.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Mon Dec 25 12:31:33 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:731 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Dec 25 12:31:33 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1245 Failed opening the underlying I/O.
Error: Time:Mon Dec 25 12:31:33 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:971 Error: io_open failed
Error: Time:Mon Dec 25 12:31:33 2017 File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1782 failure connecting to address Moxa-IoT-Lab.azure-devices.net.
Error: Time:Mon Dec 25 12:31:33 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1334 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Mon Dec 25 12:31:33 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1335: Failure sending control packet data
-> 12:31:33 PINGREQ
Error: Time:Mon Dec 25 12:31:49 2017 File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_error_callback Line:1447 Mqtt Ping Response was not encountered.  Reconnecting device...
Error: Time:Mon Dec 25 12:31:49 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1334 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Mon Dec 25 12:31:49 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1335: Failure sending control packet data
Error: Time:Mon Dec 25 12:31:49 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1176 Error: mqtt_client_disconnect send failed
**Error: Time:Mon Dec 25 12:36:00 2017** File:/home/moxa/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:627 Failure: getaddrinfo failure -3.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Mon Dec 25 12:36:00 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:731 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Dec 25 12:36:00 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1245 Failed opening the underlying I/O.
Error: Time:Mon Dec 25 12:36:00 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:971 Error: io_open failed
Error: Time:Mon Dec 25 12:36:00 2017 File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1782 failure connecting to address Moxa-IoT-Lab.azure-devices.net.
Error: Time:Mon Dec 25 12:36:00 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1334 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Mon Dec 25 12:36:00 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1335: Failure sending control packet data
-> 12:36:00 PINGREQ
Error: Time:Mon Dec 25 12:36:15 2017 File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_error_callback Line:1447 Mqtt Ping Response was not encountered.  Reconnecting device...
Error: Time:Mon Dec 25 12:36:15 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1334 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Mon Dec 25 12:36:15 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1335: Failure sending control packet data
Error: Time:Mon Dec 25 12:36:15 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1176 Error: mqtt_client_disconnect send failed

**Error: Time:Mon Dec 25 12:44:35 2017** File:/home/moxa/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:627 Failure: getaddrinfo failure -3.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Mon Dec 25 12:44:35 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:731 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Dec 25 12:44:35 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1245 Failed opening the underlying I/O.
Error: Time:Mon Dec 25 12:44:35 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:971 Error: io_open failed
Error: Time:Mon Dec 25 12:44:35 2017 File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1782 failure connecting to address Moxa-IoT-Lab.azure-devices.net.
Error: Time:Mon Dec 25 12:44:35 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1334 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Mon Dec 25 12:44:35 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1335: Failure sending control packet data
-> 12:44:35 PINGREQ
**Error: Time:Mon Dec 25 12:44:50 2017** File:/home/moxa/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_error_callback Line:1447 Mqtt Ping Response was not encountered.  Reconnecting device...
Error: Time:Mon Dec 25 12:44:50 2017 File:/home/moxa/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1334 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Mon Dec 25 12:44:50 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1335: Failure sending control packet data
Error: Time:Mon Dec 25 12:44:50 2017 File:/home/moxa/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1176 Error: mqtt_client_disconnect send failed

**Comment by RivaStyle** [comment]
You can use the **IoTHubClient_LL_SetRetryPolicy(_client handler_, _policy_, _timeout in seconds_)** function.

The _policy_ parameter is an enum ([iothub_client_ll.h:48](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client_ll.h#L48)): the default value is **IOTHUB_CLIENT_RETRY_EXPONENTIAL_BACKOFF_WITH_JITTER**, and how it works is well explained here: https://aws.amazon.com/it/blogs/architecture/exponential-backoff-and-jitter/ .
You can try to set **IOTHUB_CLIENT_RETRY_INTERVAL** as your retry policy, but keep in mind that the third parameter of the **IoTHubClient_LL_SetRetryPolicy** function is not the retry interval itself, but the timeout after which any "connection retry" attempt is given up.

The retry interval (according to Issue #256 ) can be set this way:
`size_t retryConnectionPeriod = 60; // seconds
IoTHubClient_LL_SetOption(iothub_client_handle, "initial_wait_time_in_secs", &retryConnectionPeriod);`

**Comment by ewertons** [comment]
Hi @andychu15 ,
@RivaStyle is correct* on the way to set the retry logic. 
Could you confirm if that addresses your question please?

**Comment by andychu15** [comment]
IoTHubClient_LL_SetRetryPolicy works. thanks.
