### ISSUE TITLE
[ServiceClient] Messages properties are not sent

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdk-c#34]
Hi,

On master branch, it seems that adding properties to sent messages does not work anymore.
I've slightly modified iothub_messaging_ll_sample.c to illustrate the issue.

```
for (int i = 0; i < MESSAGE_COUNT; i++)
{
	double avgWindSpeed = 10.0;
	static char msgText[1024];
	sprintf_s(msgText, sizeof(msgText), "{\"deviceId\":%s,\"windSpeed\":%.2f, \"i\":%d}", deviceId, avgWindSpeed + (rand() % 4 + 2), i);
	IOTHUB_MESSAGE_HANDLE messageHandle = IoTHubMessage_CreateFromByteArray((const unsigned char*)msgText, strlen(msgText));
	if (messageHandle == NULL)
	{
		(void)printf("IoTHubMessage_CreateFromByteArray failed\n");
		break;
	}
	else
	{
	/* Here comes the mod */
		MAP_HANDLE properties = IoTHubMessage_Properties(messageHandle);
		if(Map_Add(properties, "the key", "the value") != MAP_ERROR) {
		(void)printf("Property added\n");
		}
	/* End of mod */
		iotHubMessagingResult = IoTHubMessaging_LL_Send(iotHubMessagingHandle, deviceId, messageHandle, sendCompleteCallback, NULL);
		if (iotHubMessagingResult != IOTHUB_MESSAGING_OK)
		{
			(void)printf("IoTHubMessaging_LL_Send failed\n");
		}
		else
		{
			(void)printf("IoTHubMessaging_LL_Send accepted data for transmission to IoT Hub.\r\n");
		}
	}
	IoTHubMessage_Destroy(messageHandle);
}
```

The API does not return error when properties are added, however the message does not contains any properties on the amqp wire (I've check with one of my AMQP device, not check in hub, not check with other transports).

Is this a bug or a new (it was working on november 2016 for sure) limitation of the service_client?

Thanks.

**Comment by anporumb** [comment]
Hello @lmussier ,

Thank you for your report. 

Now I will answer your question: it is a bug. 

I will close this issue when the bug fix is checked in master. 

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Hello @lmussier ,

We have a fix checked in master branch for your report. Would be really great if you could let us know if the fix works for you. Thank you.

Best Regards,
Andrei Porumb

**Comment by lmussier** [comment]
Hi @anporumb,

I've check df13ec1ac17f671e927ad4b2eab9ed9049861c0e, we have the message properties et correctly. But we are missing the message Id.

`IoTHubMessage_SetMessageId(messageHandle, "42");`

Does not make 42 being the id of the message received on the device side.
I can't tell you if this a regression of the fix or a part of the previous bug I've don't seen.
