### ISSUE TITLE
crash in tlsio_wolfssl.c when I call the function of tlsio_wolfssl_send 

### ISSUE THREAD

**Issue by mollonpj** [Azure/azure-iot-sdk-c#341]
- **OS and version used:** <VERSION> 
 FREERTOS
- **SDK version used:** <VERSION> 
LTS

# Description of the issue:

when I call the function of tlsio_wolfssl_send, if the connection break down, the SDK will crash.
function flow:
tlsio_wolfssl_send->wolfSSL_write->SendData->SendBuffered->(ssl->ctx->CBIOSend)
ssl->ctx->CBIOSend is callback, the real function is on_io_send , on_io_send->xio_send when xio_send err, the funtion will call tlsio_wolfssl_close and finally the function destroy_wolfssl_instance will free the ssl. at the this point the callback function of (ssl->ctx->CBIOSend) has finished, but the ssl obj has been free, the rest of code in the function of SendBuffered will use the ssl obj, so it will case crash. Can u give a solution about the crash?
# Code sample exhibiting the issue:

# Console log of the issue:

(gdb) l*0x00000001
(gdb) l*0x40136bd5
0x40136bd5 is in SendData (/home/mollon/project2/sentience.edge.sdk.esp32/components/wolfssl-3.9.10/src/internal.c:10923).
10918           if (sendSz < 0)
10919               return BUILD_MSG_ERROR;
10920
10921           ssl->buffers.outputBuffer.length += sendSz;
10922
10923           if ( (ret = SendBuffered(ssl)) < 0) {
10924               WOLFSSL_ERROR(ret);
10925               /* store for next call if WANT_WRITE or user embedSend() that
10926                  doesn't present like WANT_WRITE */
10927               ssl->buffers.plainSz  = len;
(gdb) l*0x401311c1
0x401311c1 is in wolfSSL_write (/home/mollon/project2/sentience.edge.sdk.esp32/components/wolfssl-3.9.10/src/ssl.c:1088).
1083
1084    #ifdef HAVE_ERRNO_H
1085        errno = 0;
1086    #endif
1087
1088        ret = SendData(ssl, data, sz);
1089
1090        WOLFSSL_LEAVE("SSL_write()", ret);
1091
1092        if (ret < 0)
(gdb) l*0x4016fd80
0x4016fd80 is in tlsio_wolfssl_send (/home/mollon/project2/sentience.edge.sdk.esp32/components/azure-iot-sdk/azure-c-shared-utility/src/tlsio_wolfssl.c:1116).
1111                    result = __LINE__;
1112                    LogError("wolfssl closed in tlsio_wolfssl_send\r\n");
1113                    return result;
1114                }
1115
1116                int res = wolfSSL_write(tls_io_instance->ssl, buffer, size);
1117                if (res != size)
1118                {
1119                    result = __LINE__;
1120                }
(gdb) l*0x4018b71b
0x4018b71b is in xio_send (/home/mollon/project2/sentience.edge.sdk.esp32/components/azure-iot-sdk/azure-c-shared-utility/src/xio.c:152).
147
148             /* Codes_SRS_XIO_01_008: [xio_send shall pass the sequence of bytes pointed to by buffer to the concrete IO implementation specified in xio_create, by calling the concrete_io_send function while passing down the buffer and size arguments to it.] */
149             /* Codes_SRS_XIO_01_009: [On success, xio_send shall return 0.] */
150             /* Codes_SRS_XIO_01_015: [If the underlying concrete_io_send fails, xio_send shall return a non-zero value.] */
151             /* Codes_SRS_XIO_01_027: [xio_send shall pass to the concrete_io_send function the on_send_complete and callback_context arguments.] */
152             result = xio_instance->io_interface_description->concrete_io_send(xio_instance->concrete_xio_handle, buffer, size, on_send_complete, callback_context);
153         }
154
155         return result;
156     }
(gdb) l*0x401798a2
0x401798a2 is in saslclientio_send (/home/mollon/project2/sentience.edge.sdk.esp32/components/azure-iot-sdk/azure-uamqp-c/src/saslclientio.c:1077).
1072                result = __LINE__;
1073            }
1074            else
1075            {
1076                /* Codes_SRS_SASLCLIENTIO_01_020: [If the SASL client IO state is IO_STATE_OPEN, saslclientio_send shall call xio_send on the underlying_io passed to saslclientio_create, while passing as arguments the buffer, size, on_send_complete and callback_context.] */
1077                if (xio_send(sasl_client_io_instance->underlying_io, buffer, size, on_send_complete, callback_context) != 0)
1078                {
1079                    /* Codes_SRS_SASLCLIENTIO_01_024: [If the call to xio_send fails, then saslclientio_send shall fail and return a non-zero value.] */
1080                    result = __LINE__;
1081                }
(gdb) l*0x4018b71b
0x4018b71b is in xio_send (/home/mollon/project2/sentience.edge.sdk.esp32/components/azure-iot-sdk/azure-c-shared-utility/src/xio.c:152).
147
148             /* Codes_SRS_XIO_01_008: [xio_send shall pass the sequence of bytes pointed to by buffer to the concrete IO implementation specified in xio_create, by calling the concrete_io_send function while passing down the buffer and size arguments to it.] */
149             /* Codes_SRS_XIO_01_009: [On success, xio_send shall return 0.] */
150             /* Codes_SRS_XIO_01_015: [If the underlying concrete_io_send fails, xio_send shall return a non-zero value.] */
151             /* Codes_SRS_XIO_01_027: [xio_send shall pass to the concrete_io_send function the on_send_complete and callback_context arguments.] */
152             result = xio_instance->io_interface_description->concrete_io_send(xio_instance->concrete_xio_handle, buffer, size, on_send_complete, callback_context);
153         }
154
155         return result;
156     }
(gdb) l*0x40178a41
0x40178a41 is in on_bytes_encoded (/home/mollon/project2/sentience.edge.sdk.esp32/components/azure-iot-sdk/azure-uamqp-c/src/connection.c:228).
223     }
224
225     static void on_bytes_encoded(void* context, const unsigned char* bytes, size_t length, bool encode_complete)
226     {
227         CONNECTION_INSTANCE* connection_instance = (CONNECTION_INSTANCE*)context;
228         if (xio_send(connection_instance->io, bytes, length, encode_complete ? connection_instance->on_send_complete : NULL, connection_instance->on_send_complete_callback_context) != 0)
229         {
230             xio_close(connection_instance->io, NULL, NULL);
231             connection_set_state(connection_instance, CONNECTION_STATE_END);
232         }
(gdb) l*0x4018c6bd
0x4018c6bd is in frame_codec_encode_frame (/home/mollon/project2/sentience.edge.sdk.esp32/components/azure-iot-sdk/azure-uamqp-c/src/frame_codec.c:602).
597                 frame_header[4] = doff;
598                 /* Codes_SRS_FRAME_CODEC_01_069: [TYPE Byte 5 of the frame header is a type code.] */
599                 frame_header[5] = type;
600
601                 /* Codes_SRS_FRAME_CODEC_01_088: [Encoded bytes shall be passed to the on_bytes_encoded callback.] */
602                 on_bytes_encoded(callback_context, frame_header, sizeof(frame_header), ((frame_body_size + type_specific_bytes + padding_byte_count) == 0) ? true : false);
603
604                 /* Codes_SRS_FRAME_CODEC_01_088: [Encoded bytes shall be passed to the on_bytes_encoded callback.] */
605                 if (type_specific_size > 0)
606                 {
(gdb) l*0x401821e9
0x401821e9 is in amqp_frame_codec_encode_empty_frame (/home/mollon/project2/sentience.edge.sdk.esp32/components/azure-iot-sdk/azure-uamqp-c/src/amqp_frame_codec.c:322).
317
318             channel_bytes[0] = channel >> 8;
319             channel_bytes[1] = channel & 0xFF;
320
321                     /* Codes_SRS_AMQP_FRAME_CODEC_01_044: [amqp_frame_codec_encode_empty_frame shall use frame_codec_encode_frame to encode the frame.] */
322                     if (frame_codec_encode_frame(amqp_frame_codec->frame_codec, FRAME_TYPE_AMQP, NULL, 0, channel_bytes, sizeof(channel_bytes), on_bytes_encoded, callback_context) != 0)
323                     {
324                             /* Codes_SRS_AMQP_FRAME_CODEC_01_046: [If encoding fails in any way, amqp_frame_codec_encode_empty_frame shall fail and return a non-zero value.]  */
325                             result = __LINE__;
326                     }
(gdb) l*0x40178f95
0x40178f95 is in connection_handle_deadlines (/home/mollon/project2/sentience.edge.sdk.esp32/components/azure-iot-sdk/azure-uamqp-c/src/connection.c:1400).
1395                        remote_deadline = remote_idle_timeout - time_since_last_sent;
1396                    }
1397                    else
1398                    {
1399                        connection->on_send_complete = NULL;
1400                        if (amqp_frame_codec_encode_empty_frame(connection->amqp_frame_codec, 0, on_bytes_encoded, connection) != 0)
1401                        {
1402                            /* close connection */
1403                            close_connection_with_error(connection, "amqp:internal-error", "Cannot send empty frame");
1404                        }
(gdb) l*0x40179019
0x40179019 is in connection_dowork (/home/mollon/project2/sentience.edge.sdk.esp32/components/azure-iot-sdk/azure-uamqp-c/src/connection.c:1430).
1425    void connection_dowork(CONNECTION_HANDLE connection)
1426    {
1427        /* Codes_SRS_CONNECTION_01_078: [If handle is NULL, connection_dowork shall do nothing.] */
1428        if (connection != NULL)
1429        {
1430            if (connection_handle_deadlines(connection) > 0)
1431            {
1432                /* Codes_SRS_CONNECTION_01_076: [connection_dowork shall schedule the underlying IO interface to do its work by calling xio_dowork.] */
1433                xio_dowork(connection->io);
1434            }
(gdb) l*0x4017528a
0x4017528a is in IoTHubTransportAMQP_DoWork (/home/mollon/project2/sentience.edge.sdk.esp32/components/azure-iot-sdk/iothub_client/src/iothubtransportamqp.c:1564).
1559                prepareForConnectionRetry(transport_state);
1560            }
1561            else
1562            {
1563                // Codes_SRS_IOTHUBTRANSPORTAMQP_09_103: [IoTHubTransportAMQP_DoWork shall invoke connection_dowork() on AMQP for triggering sending and receiving messages]
1564                connection_dowork(transport_state->connection);
1565            }
1566        }
1567    }
1568
(gdb) l*0x40176f57
0x40176f57 is in IoTHubClient_LL_DoWork (/home/mollon/project2/sentience.edge.sdk.esp32/components/azure-iot-sdk/iothub_client/src/iothub_client_ll.c:763).
758         {
759             IOTHUB_CLIENT_LL_HANDLE_DATA* handleData = (IOTHUB_CLIENT_LL_HANDLE_DATA*)iotHubClientHandle;
760             DoTimeouts(handleData);
761
762             /*Codes_SRS_IOTHUBCLIENT_LL_02_021: [Otherwise, IoTHubClient_LL_DoWork shall invoke the underlaying layer's _DoWork function.]*/
763             handleData->IoTHubTransport_DoWork(handleData->transportHandle, iotHubClientHandle);
764         }
765     }
766
767     IOTHUB_CLIENT_RESULT IoTHubClient_LL_GetSendStatus(IOTHUB_CLIENT_LL_HANDLE iotHubClientHandle, IOTHUB_CLIENT_STATUS *iotHubClientStatus)
(gdb) l*0x4015c00f

**Comment by JetstreamRoySprowl** [comment]
@mollonpj : Thanks for the report; we've got this in the queue to investigate. BTW, what machine are you running this on?

**Comment by mollonpj** [comment]
@JetstreamRoySprowl the SDK running on the esp32 platform. But the issue has nothing to do with the machine. The SDK Running on any machine will crash.

**Comment by mollonpj** [comment]
@JetstreamRoySprowl how long will you starting investigate this bug? Thanks

**Comment by jebrando** [comment]
@mollonpj I have done some work in this area and I believe that the crash is fixed.  If you have any more issues with or find a different issue around this, please reopen.

**Comment by mollonpj** [comment]
@jebrando hi, what protocol you testing? I test the situation using the amqp protocl. The bug will come up soon. Can you use the amqp protocol to test the  situation, thanks
