### ISSUE TITLE
memory leak when Connection Not Accepted: 0x3: Server Unavailable

### ISSUE THREAD

**Issue by songwei1984** [Azure/azure-iot-sdk-c#342]
- **OS and version used:** <VERSION> Embedded Linux 3.18.20 ARM
- **SDK version used:** <VERSION> 1.1.29

# Description of the issue:
When MQTT SDK connect Azure IoTHub and receive error "Connection Not Accepted: 0x3: Server Unavailable", MQTT SDK reconnect many times, but the memory occupy should raise more and more not release.

# Code sample exhibiting the issue:
None.

# Console log of the issue:
Info: IoT Hub SDK for C, version 1.1.29
-> 03:44:37 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: */api-version=2016-11-14&DeviceClientType=iothubclient%2f1.1.29%20(native%3b%20Linux%3b%20armv7l) | CLEAN: 0
<- 03:44:37 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Fri Dec 29 03:44:37 2017 File:/home/azure/release_2017_12_14/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1354 Connection Not Accepted: 0x5: Not Authorized
-> 03:44:37 DISCONNECT
-> 03:44:41 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: */api-version=2016-11-14&DeviceClientType=iothubclient%2f1.1.29%20(native%3b%20Linux%3b%20armv7l) | CLEAN: 0
<- 03:44:41 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x3
Error: Time:Fri Dec 29 03:44:41 2017 File:/home/azure/release_2017_12_14/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1354 Connection Not Accepted: 0x3: Server Unavailable
-> 03:44:41 DISCONNECT
-> 03:44:46 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: */api-version=2016-11-14&DeviceClientType=iothubclient%2f1.1.29%20(native%3b%20Linux%3b%20armv7l) | CLEAN: 0
<- 03:44:46 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x3
Error: Time:Fri Dec 29 03:44:46 2017 File:/home/azure/release_2017_12_14/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1354 Connection Not Accepted: 0x3: Server Unavailable
-> 03:44:46 DISCONNECT
-> 03:44:51 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: */api-version=2016-11-14&DeviceClientType=iothubclient%2f1.1.29%20(native%3b%20Linux%3b%20armv7l) | CLEAN: 0
<- 03:44:51 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x3
Error: Time:Fri Dec 29 03:44:51 2017 File:/home/azure/release_2017_12_14/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1354 Connection Not Accepted: 0x3: Server Unavailable
-> 03:44:51 DISCONNECT
-> 03:44:56 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: */api-version=2016-11-14&DeviceClientType=iothubclient%2f1.1.29%20(native%3b%20Linux%3b%20armv7l) | CLEAN: 0
<- 03:44:56 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x3
Error: Time:Fri Dec 29 03:44:56 2017 File:/home/azure/release_2017_12_14/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1354 Connection Not Accepted: 0x3: Server Unavailable
-> 03:44:56 DISCONNECT
-> 03:45:02 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: */api-version=2016-11-14&DeviceClientType=iothubclient%2f1.1.29%20(native%3b%20Linux%3b%20armv7l) | CLEAN: 0
<- 03:45:02 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x3
Error: Time:Fri Dec 29 03:45:02 2017 File:/home/azure/release_2017_12_14/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1354 Connection Not Accepted: 0x3: Server Unavailable
-> 03:45:02 DISCONNECT
......

**Comment by ewertons** [comment]
Hi @songwei1984 ,
we were able to catch a memory leak in MQTT transport during reconnection, where it's not releasing the openssl components allocated in certain conditions.
We will have the fix checked in soon and will let you know.
Thanks for contributing to the Azure IoT SDK!

**Comment by songwei1984** [comment]
Hi @ewertons ,
Thanks for your quick feedback.
But could you give the bug fix solution in soon before next release version, our project & product is waiting for this bug fix solution.
Sorry to urge to fix this bug!

**Comment by songwei1984** [comment]
Hi @ewertons ,
Whether this bug have been fixed in this release version named "release_2018-01-12"?

**Comment by kcpoduru** [comment]
Hi @ewertons 

We are also having the same issue waiting for the fix. Please let us know when this is available. Thanks.

**Comment by ewertons** [comment]
Hi @songwei1984 ,
@jebrando has checked in a fix for this issue.
If possible please get the latest code from master branch and confirm it addresses the issue.
In case you still see errors please feel free to reopen this ticket and we will follow up on it.

Thanks,
-Azure IoT Team
