### ISSUE TITLE
Detecting Failed IoT Hub Connection

### ISSUE THREAD

**Issue by MichaelDenczek** [Azure/azure-iot-sdk-c#343]
- OS and version used: Windows 7 x64
- SDK version used: Latest IoT SDK for C

# Description of the issue:

Using the IoTHubClient_CreateFromConnectionString method with the MQTT_WebSocket_Protocol parameter, the call returns a valid handle when the connection is blocked via a firewall.

How can we tell when the connection actually fails or succeeds?  Is there a callback that can be used or does a call need to be made, perhaps to attempt to send data?

Looking for a reliable way to detect when the IoT Hub connection fails or succeeds.

# Code sample exhibiting the issue:

IOTHUB_CLIENT_HANDLE iotHubClientHandle = IoTHubClient_CreateFromConnectionString(strConnectionString.c_str(), MQTT_WebSocket_Protocol);

# Console log of the issue:

Error output does not occur until after call to:  IoTHubClient_Destroy(iotHubClientHandle);

Error: Time:Thu Jan  4 13:44:16 2018 File:C:\devl\fwd360\trunk\AzureServices\azure-iot-sdk-c\c-utility\src\xio.c Func:_xio_retrieveoptions Line:262 invalid argument detected: XIO_HANDLE xio=00000000
Error: Time:Thu Jan  4 13:44:16 2018 File:C:\devl\fwd360\trunk\AzureServices\azure-iot-sdk-c\umqtt\src\mqtt_client.c Func:_sendPacketItem Line:332 141: Failure sending control packet data
Error: Time:Thu Jan  4 13:44:16 2018 File:C:\devl\fwd360\trunk\AzureServices\azure-iot-sdk-c\umqtt\src\mqtt_client.c Func:_mqtt_client_disconnect Line:1176 Error: mqtt_client_disconnect send failed

**Comment by dehng** [comment]
Hi,
you must add a 'ClientConnectionCallback'.

Sample Code:
static void ClientConnectionCallback(IOTHUB_CLIENT_CONNECTION_STATUS result, IOTHUB_CLIENT_CONNECTION_STATUS_REASON reason, void* userContextCallback)
{
	(void)printf("ClientConnectionCallback with result = %d, reason = %d\r\n", result, reason); 
}

....
// after create connectionstring
if (IoTHubClient_LL_SetConnectionStatusCallback(iotHubClientHandle, ClientConnectionCallback, NULL) != IOTHUB_CLIENT_OK)
	(void)printf("ERROR: IoTHubClient_LL_SetConnectionStatusCallback..........FAILED!\r\n");
else
	(void)printf("IoTHubClient_LL_SetConnectionStatusCallback...successful.\r\n");

**Comment by MichaelDenczek** [comment]
I was able to use the IoTHubClient_SetConnectionStatusCallback method to set the callback.  The connection status does not get returned until an attempt to send data over the connection occurs.  Is an attempt to send data always required in order to get the callback to occur?

**Comment by ewertons** [comment]
Hi @MichaelDenczek ,
The Azure IoT SDK uses delayed initialization of the TLS/TCP stacks. 
They are only truly initialized if data is sent, or if a subscription for data is made.
So the answer is yes, you need to attempt to send data at least once, otherwise there will be no connection status callbacks triggered.

**Comment by jspaith** [comment]
Hi @MichaelDenczek , I believe @ewertons has addressed the question.  I'm closing out this issue, but if you followups by all means re-open this or open a new issue.  Thanks
