### ISSUE TITLE
Missing callback event "SetConnectionStatusCallback" with sample "iothub_client_sample_http"

### ISSUE THREAD

**Issue by dehng** [Azure/azure-iot-sdk-c#345]
- **OS and version used:** Windows Compact 2013

- **SDK version used:** Release_2017-11-17

# Description of the issue:
I am not receiving "ConnectionStatusCallback" if the connectionstring is invalid or the connection to the IoT Hub is lost (No LAN connection).

With the example "iothub_client_sample_mqtt" I get an error callback if the connection to the IoT Hub is interrupted.

Is the "ConnectionStatusCallback" supported in the example "iothub_client_sample_http"?

# Code sample exhibiting the issue:
static void ClientConnectionCallback(IOTHUB_CLIENT_CONNECTION_STATUS result, IOTHUB_CLIENT_CONNECTION_STATUS_REASON reason, void* userContextCallback)
{
    (void)printf("ClientConnectionCallback with result = %d, reason = %d\r\n", result, reason);
}
...
if (IoTHubClient_LL_SetConnectionStatusCallback(iotHubClientHandle, ClientConnectionCallback, NULL) != IOTHUB_CLIENT_OK)
{
    (void)printf("ERROR: IoTHubClient_LL_SetConnectionStatusCallback..........FAILED!\r\n");
}
else
{
    (void)printf("IoTHubClient_LL_SetConnectionStatusCallback...successful.\r\n");
}

# Console log of the issue:
Debug output with mqtt example (use invalid connectionstring):
Info: IoT Hub SDK for C, version 1.1.28
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SetConnectionStatusCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
Error: Time:Sat Jan  6 14:45:14 2018 File:....\SDKs\SDK_2017_11_17\c-utility\adapters\socketio_win32.c Func:_socketio_open Line:296 Failure: getaddrinfo failure 11001.
ClientConnectionCallback with result = 1, reason = 4

Debug otput with http example (use invalid connectionstring):
Starting the IoTHub client sample HTTP...
Info: IoT Hub SDK for C, version 1.1.28
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
Error: Time:Sat Jan  6 14:48:21 2018 File:....\SDKs\SDK_2017_11_17\c-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:438 WinHttpSendRequest: (result = HTTPAPI_SEND_REQUEST_FAILED).
Error: Time:Sat Jan  6 14:48:21 2018 File:....\SDKs\SDK_2017_11_17\c-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:438 GetLastError: Der Servername oder die Serveradresse konnte nicht verarbeitet werden.
.
Error: Time:Sat Jan  6 14:48:21 2018 File:....\SDKs\SDK_2017_11_17\c-utility\src\httpapiex.c Func:_HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Sat Jan  6 14:48:21 2018 File:....\SDKs\SDK_2017_11_17\iothub_client\src\iothubtransporthttp.c Func:_DoEvent Line:1680 unable to HTTPAPIEX_SAS_ExecuteRequest
Error: Time:Sat Jan  6 14:48:27 2018 File:....\SDKs\SDK_2017_11_17\c-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:438 WinHttpSendRequest: (result = HTTPAPI_SEND_REQUEST_FAILED).
Error: Time:Sat Jan  6 14:48:27 2018 File:....\SDKs\SDK_2017_11_17\c-utility\adapters\httpapi_winhttp.c Func:_HTTPAPI_ExecuteRequest Line:438 GetLastError: Der Servername oder die Serveradresse konnte nicht verarbeitet werden.
.

**Comment by ewertons** [comment]
Hi @dehng ,
HTTP protocol is a connection-less protocol, so Connection Status callback is not applicable to this flavor of transport.
It is only applicable to AMQP and MQTT transports as of now.

**Comment by davidbuechi** [comment]
from a user point of view it would be very handy if this would be independent of the protocol. Maybe the SDK could mimic a connection behaviour? Like reporting OK as soon as the first message has been successfully sent/received and NOK after the first failing transfer?

Like this the connection monitoring for an application would be much easier (given the timeouts, keep alives, polling periods, etc. are all selected thoroughly)

**Comment by ewertons** [comment]
We can discuss that as a possible improvement. 
I'll mark this issue as such and discuss internally when we have our next review of improvement requests.

**Comment by tameraw** [comment]
@dehng - per the comments above we are not proceeding with this feature.
