### ISSUE TITLE
Compiling sdk requires http support due to sample utility

### ISSUE THREAD

**Issue by jakethiem** [Azure/azure-iot-sdk-c#348]
- **OS and version used:** Linux 14.04 Cross Compiling for custom Linux kernel 

- **SDK version used:** Latest available on Master branch 

# Description of the issue:
Getting this repeated error when trying to compile:
[azure-iot-sdk-c] Configuring
Configuring files
Setting dont_use_uploadtoblob to ON because use_http is OFF
CMake Warning:
  Manually-specified variables were not used by the project:

    run_valgrind
    use_tpm_simulator

CMakeFiles/iot_c_utility.dir/iot_c_utility.c.o: In function `http_examples':
iot_c_utility.c:(.text+0x5c): undefined reference to `HTTPAPIEX_Create'
iot_c_utility.c:(.text+0x98): undefined reference to `HTTPAPIEX_Destroy'
collect2: error: ld returned 1 exit status
make[3]: *** [c-utility/samples/iot_c_utility/iot_c_utility] Error 1
make[2]: *** [c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all] Error 2
make: *** [build] Error 2
make: Leaving directory `.../board-support/packages/azure'

There is no need for http or amqp support on this product, but it appears there is a sample app that requires http support which should not be built if there is no http support. This happens every time it is compiled.

# Code sample exhibiting the issue:
Here is the file from the reported error above:
static void test_http_proxy_io()
{
    const IO_INTERFACE_DESCRIPTION* interface_desc = http_proxy_io_get_interface_description();
    if (interface_desc == NULL)
    {
        LogError("Failed to create interface_desc.\n");
    }
}

static void http_examples()
{
    HTTPAPIEX_HANDLE handle = HTTPAPIEX_Create("www.bing.com");
    if (handle == NULL)
    {
        LogError("Failed creating httpApiEx handle");
    }
    else
    {
        HTTPAPIEX_Destroy(handle);
    }
}

static void show_sastoken_example()
{
    STRING_HANDLE sas_token = SASToken_CreateString("key", "scope", "name", 987654321);
    if (sas_token == NULL)
    {
        LogError("Failed to create SAS Token.\n");
    }
    else
    {
        STRING_delete(sas_token);
    }
}

int main(int argc, char** argv)
{
    (void)argc, (void)argv;

    if (platform_init() != 0)
    {
        LogError("Cannot initialize platform.\n");
    }
    else
    {
        show_sastoken_example();
        test_http_proxy_io();
        platform_deinit();
        http_examples();
    }
    return 0;
}

# Console log of the issue:

**Comment by ewertons** [comment]
Hi @jakethiem ,
just to confirm, could you paste the exact cmake command you are running, with all parameters? We need to confirm what you are disabling specifically (AMQP, HTTP, etc).
Also, giving the version number of the SDK gives us definitive info about what code you have. "Latest from master" is like a moving reference.
We will check the combinations of features again to confirm, but please let us know which features you are disabling during compilation.

**Comment by ewertons** [comment]
Bug confirmed. 
Command used: `cmake -Duse_http=OFF ~/azure-iot-sdk-c`

**Comment by jakethiem** [comment]
SDK version used: 1.1.29

The cmake command is being run through the build_all/linux/build.sh command with the following config options:

NOTE: no-http, no-amqp and no-uploadtoblob are commented out to get it to work, the no-amqp does work without errors.

CONFIG_OPTS=\
	--toolchain-file toolchain-arm-linux-gnueabihf.cmake \
	-cl -I$(ROOTFS)/include \
	-cl -I$(ROOTFS)/usr/include \
	-cl -L$(ROOTFS)/lib \
	-cl -L$(ROOTFS)/usr/lib \
	--install-path-prefix $(ROOTFS)/usr \
	# --no-http \
	# --no-amqp \
	# --no_uploadtoblob \

**Comment by ewertons** [comment]
Hi @jakethiem ,
the fix was already made available on the main C SDK repo.
If you have the chance please confirm it addresses the bug, and if you find any other problem feel free to reopen this issue so we can follow up.

Thanks for your contribution.

- Azure IoT Team.

**Comment by jakethiem** [comment]
That fixed the issue. Thank you.
