### ISSUE TITLE
Provisioning_client: "azure_hub_modules" is missing  

### ISSUE THREAD

**Issue by 59985** [Azure/azure-iot-sdk-c#352]
Hi there! 

I am trying to implement the Provisioning_client, but missing the azure_hub_modules. It should be located in azure-iot-device-auth.git, which I do not have access to:

#include "**azure_hub_modules**/device_auth_tpm.h"

Regards
Kasper

OS: Treadx /ARM

**Comment by jebrando** [comment]
Can you please let me know what repo url that you're using?

**Comment by 59985** [comment]
Here is the url:
https://github.com/Azure/azure-iot-device-auth/tree/1eaa27df4b8f6dd17d6ec1b5f31e020ea24586be/dps_client/inc/azure_hub_modules

**Comment by jebrando** [comment]
That public preview repo have been deleted and move to the main this SDK repo.  All the code and samples are found here: https://github.com/Azure/azure-iot-sdk-c/tree/master/provisioning_client.  Let us know if you have any issues with the latest code base.

**Comment by ArsalanSaleemGhuman** [comment]
where are the following files being pointed to by provisioning_client/src/sec_device_module_tpm.c

`#include "azure_hub_modules/device_auth_tpm.h"
#include "azure_hub_modules/device_auth.h"
#include "azure_hub_modules/tpm_comm.h"
#include "azure_hub_modules/tpm_codec.h"`

**Comment by 59985** [comment]
[AzureHubModules.zip](https://github.com/Azure/azure-iot-sdk-c/files/2615608/AzureHubModules.zip)

**Comment by ArsalanSaleemGhuman** [comment]
cant see the two files in the attached zip:
#include "azure_hub_modules/device_auth_tpm.h"
#include "azure_hub_modules/device_auth.h"

i guess the file sec_device_module_tpm.c  is not being used. Not sure though
