### ISSUE TITLE
iothub_client: devdoc: iothubclient_c_library.md: github markdown is mangled

### ISSUE THREAD

**Issue by jdswensen** [Azure/azure-iot-sdk-c#359]
# Description of the issue:
Markdown view on github is mangled making it harder to read.

# Code sample exhibiting the issue:
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/devdoc/iothubclient_c_library.md

**Comment by jspaith** [comment]
Good catch.  I have a change going through gates right now on way to master to fix this.  Thanks for calling this out.

**Comment by jspaith** [comment]
Fixed commit #8eff31afee5d88ebbbbf6f527b40ad5ec38e1dd2
