### ISSUE TITLE
Consider moving reference docs for C APIs to docs.microsoft.com

### ISSUE THREAD

**Issue by BryanLa** [Azure/azure-iot-sdk-c#361]
Moving to docs.microsoft.com would give us better integration with other Azure content, including the reference docs for other IoT SDKs (below), and [IoT conceptual content](https://docs.microsoft.com/azure/index#pivot=products&panel=iot) specifically. 

Currently we only have CI for the languages below, but if we switched from HTML to Markdown output, we would be able to begin the migration path to docs.microsoft.com. Then once the tooling/CI becomes available for C/C++, it can be automated. These links will give you an idea of how docs renders for REST and the supported languages:

- REST APIs
    - IoT Hub: https://docs.microsoft.com/rest/api/iothub/
    - DPS: https://docs.microsoft.com/rest/api/iot-dps/ 
- .NET libraries: https://docs.microsoft.com/dotnet/api/overview/azure/iot?view=azure-dotnet 
- Python libraries: https://docs.microsoft.com/python/api/overview/azure/iot?view=azure-python 
- Java libraries: https://docs.microsoft.com/java/api/overview/azure/iot 

As mentioned, we should also eventually have a CI story, which will help keep the docs in sync w/the current source. In addition, Docs provides us w/better BI tooling around article performance, SEO and feedback mechanisms.

It would be interesting to see what others think about this?

**Comment by massand** [comment]
We are in the final stages of releasing updated reference docs to replace our raw Doxygen output that is reference from docs.microsoft.com. Our content team has done some awesome work to ingest the Doxygen output into the cleaner looking docs.microsoft.com format. I will post the final link when it is ready.

**Comment by az-iot-builder-01** [comment]
@BryanLa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by BryanLa** [comment]
@timlt - FYI

**Comment by timlt** [comment]
@BryanLa, thanks, haha, my team (Wesley) is actually running this project and created the tooling to move it. :-)  Thanks!

**Comment by BryanLa** [comment]
@timlt  - that's awesome! He needs to sell it to the Docs/OPS engineering team ;)
