### ISSUE TITLE
How  to set the System Properties of  "EventData"

### ISSUE THREAD

**Issue by thematrix9** [Azure/azure-iot-sdk-c#366]
Hello, 

I  want to set  following System Properties of  MQTT Message from  Non-SDK  C client  ( I am not  using Azure SDK-C but using Open Source MQTT Client written in C) ?

**_message-id
user-id
to
correlation-id_**

This the simplified code that I use for testing ...

_mqtt_publish((mqtt_broker_handle_t *)TRMqttGetBroker(), "devices/MyDeviceID1/messages/events/MessageId=12&To=myIotHub\.azure-devices\.net&CorrelationId=0&UserId=MyUserID1&Type=Telemetry&Subtype=Telemetry&Priority=5&Version=1.1.0", "Hello World", 11, 0);_

![image](https://user-images.githubusercontent.com/32825194/35502596-7f6ee7a6-0503-11e8-9899-56c48321521f.png)

I can see that my "Application Properties" does get set correctly ... but how to set "System Properties" 

![image](https://user-images.githubusercontent.com/32825194/35502662-b4f9f42e-0503-11e8-8a4b-46a3e01ec814.png)

When I use Azure C-SDK , these message-id, user-id, to , correlation-id does get set correctly  as shown in following image...

Here I am using  SDK code as follows -

                            (void)IoTHubMessage_SetMessageId(messages[iterator].messageHandle, "MSG_ID");
                            (void)IoTHubMessage_SetCorrelationId(messages[iterator].messageHandle, "CORE_ID");
                       (void)IoTHubMessage_SetContentTypeSystemProperty(messages[iterator].messageHandle, "application%2Fjson");                          (void)IoTHubMessage_SetContentEncodingSystemProperty(messages[iterator].messageHandle, "utf-8");

https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c

![image](https://user-images.githubusercontent.com/32825194/35502783-183e3d56-0504-11e8-8a9b-79b9f31c001d.png)

In  Azure documentation , they are talking about "property_bag"
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support

and they mention to use $ for System Property but I am not able to use it. Can someone explain how to use it ?

![image](https://user-images.githubusercontent.com/32825194/35502922-8a136e38-0504-11e8-978c-b2078d65fd97.png)

I will appreciate if any help is available.

Thanks,
Kum

**Comment by ewertons** [comment]
Hi @thematrix9 ,
you mention C language, but your screenshots look like from C# code.
Could you clarify about that? If you want c# code you should post your question on https://github.com/Azure/azure-iot-sdk-csharp

**Comment by ewertons** [comment]
You can explore how we do that in the C SDK by looking at this code:
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L655

**Comment by thematrix9** [comment]
@ewertons  this helps https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L655

Thanks !

**Comment by ewertons** [comment]
Alright, glad to hear that @thematrix9 .
Thanks for using the Azure IoT SDKs.
- Azure IoT Team
