### ISSUE TITLE
curl 27 Out of memory after change the protocol from amqp to websocket

### ISSUE THREAD

**Issue by rajvael** [Azure/azure-iot-sdk-c#37]
In my application i am using libcurl and Iot SDK with websocket support. Recently I am facing one issue curl "curl 27 Out warning Out of memory" whenever i call API using libcurl to get SAS token. 

My application execute in the below order.
1) It use libcurl library to get SAS token
2) Once it get SAS token then it use that token to connect to IoTHub and start sending messages using websocket over amqp
3) In case if the token expired then it will use libcurl to request for new token. 

I am facing out of memory in step 3. Initially in step 1 it is working but later if it ask SAS token for second time after connected with IotHub its start failing. But if I change the protocol from websocket to AMQP then all working good.  I am doubting there is an issue in libwebsocket implementation. Its not releasing the resources properly. 

Note: Both libWebsocket and libcurl using same openssl library version 1.0.1

**Comment by anporumb** [comment]
Hello @rajvael ,

Can you please attach here a minimal repro? Thank you.

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Closing this, Please reopen if you still have the issue.

Best Regards,
Andrei Porumb
