### ISSUE TITLE
Add the Resume Upload Multiple Blocks To Blob functionnality

### ISSUE THREAD

**Issue by GeraldSchmitt** [Azure/azure-iot-sdk-c#371]
# The problem

A device wants to upload a big file to a blob storage through an unreliable connection (GPRS...).
The upload start uploading blocks with `IoTHubClient_UploadMultipleBlocksToBlobAsync(Ex)`, 
and there is a problem (connection lost, reboot...).

The device has then to start all the upload over, 
and it's really too bad 'cause the upload was at 99%, 
and the device feels desperate because it's been the third attempt...

# A solution ?

## Resume the upload of multiple blocks to blob

An API like this could do the job for us (with just one new parameter `blockOffset`):

```C
IOTHUB_CLIENT_RESULT IoTHubClient_ResumeUploadMultipleBlocksToBlobAsync(
    IOTHUB_CLIENT_HANDLE iotHubClientHandle, 
    const char* destinationFileName, 
    unsigned int blockOffset,
    IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_CALLBACK getDataCallback, 
    void* context);
```

## Get the uploaded block count

We would also need a way to know where the upload stopped, that is, how many blocks have been correctly uploaded. (Some device can be stateless, or might not have the time to save the state in case of brutal reboot.)
This is possible with the [Get Block List](https://docs.microsoft.com/en-us/rest/api/storageservices/get-block-list) operation, but the result could be simplified to the biggest blockId (given the Id are consecutive starting at 1):

```C
/**
 * Returns an error if:
 * - connection error
 * - destinationFileName does not exist
 * - some blocks are already commited
 * - the blockIds are NOT a consecutive list of ints starting at 1
 * Otherwise:
 * - Returns OK and sets blockCount to the biggest blockId
 */
IOTHUB_CLIENT_RESULT IoTHubClient_GetUploadedBlockCount(
    IOTHUB_CLIENT_HANDLE iotHubClientHandle, 
    const char* destinationFileName, 
    unsigned int *blockCount);
```

## What now ?

Do you have something similar in your backlog?

Would this functionality fit into the SDK?

Is the suggested API ok, or does it need refinement?

Cheers,

Gérald

Edit: Issue #321 shows similar needs

**Comment by jspaith** [comment]
I'm going to close out this issue so we can track discussion in #321 without forks.  Thank you.

**Comment by InfiniteYuan1** [comment]
@Gabedlm Hi, can you share your source code for GPRS to connect to Azure?
Thank you  in advanced.

**Comment by Gabedlm** [comment]
@InfiniteYuan1 I am not a contributor to this repo. 
Wrong username?
