### ISSUE TITLE
mqtt_operation_complete_callback: CONN_REFUSED_NOT_AUTHORIZED

### ISSUE THREAD

**Issue by angelobt** [Azure/azure-iot-sdk-c#373]
ENVIRONMENT:
sdk version 1.1.27 build with yocto 2.2.2 (morty)
hw: nxp imx6 solo 
arch: arm
connection to IOTHUB: mqtt

At startup, my application tries to open a new connection to IOThub: very often the mqtt_operation_complete_callback returns me IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED for some seconds/minutes.
The connection string is always the same (when the connection works and when it does not).
After some retries the connection becomes OK.

Error: Time:Mon Feb  5 10:32:02 2018 File:/usr/src/debug/azure-iot-sdk/1.1.23-r0/git/c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1352 Connection Not Accepted: 0x5: Not Authorized

In my mind IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED should mean that the device has been deleted/invalidated inside IOTHUB. Am I wrong ? (In my application, if I receive this error, the idea is to delete the connection data, thinking that they are no more valid).
Checking the latest commits I saw that also SERVER UNAVAILABLE is translated as DEVICE DISABLED error (commit d829f86cbb347ac0d5215b18de2227772b38713b).

Do I have to threat "DEVICE DISABLED" as a warning instead of an error ?
Why at the beginning I get a lot of  CONN_REFUSED_NOT_AUTHORIZED errors ?

This is a little piece of my code when I prepare the IOThub connection

       iotHubClientHandle =
                        IoTHubClient_LL_CreateFromConnectionString(conn,
                                                                 MQTT_Protocol);

        if (!iotHubClientHandle) {
                WARNING("IOT hub can't create the mqtt socket handler");
                g_free(conn);
                return ret;
        }

        elt->az_conn->azure_hl = iotHubClientHandle;

        /* set up certificates verification */
        if (elt->az_conn->certs) {
                g_file_get_contents(elt->az_conn->certs, &cert, NULL, &error);
                if (error) {
                        DEBUG("failed to load %s: %s", cert, error->message);
                        g_clear_error(&error);

                        goto exit_error;
                }

                if (IoTHubClient_LL_SetOption(elt->az_conn->azure_hl,
                                "TrustedCerts", cert) != IOTHUB_CLIENT_OK) {

                        g_free(cert);
                        goto exit_error;
                }
                g_free(cert);
        }
        /* setup the function for the callbacks */
        if (IoTHubClient_LL_SetMessageCallback(elt->az_conn->azure_hl,
                        iothub_receive_msg, pdata) != IOTHUB_CLIENT_OK) {
                DEBUG("ERROR: IoTHubClient_LL_SetMessageCallback");
                goto exit_error;
        }
        if (IoTHubClient_LL_SetConnectionStatusCallback(elt->az_conn->azure_hl,
                        iothub_conn_status, pdata) != IOTHUB_CLIENT_OK) {
                DEBUG("ERROR: IoTHubClient_LL_SetConnectionStatusCallback");
                goto exit_error;
        }
        if (IoTHubClient_LL_SetDeviceTwinCallback(elt->az_conn->azure_hl,
                         iothub_twin_rec_update, pdata) != IOTHUB_CLIENT_OK) {
                DEBUG("ERROR: IoTHubClient_LL_SetDeviceTwinCallback");
                goto exit_error;
        }

        IoTHubClient_LL_SetOption(elt->az_conn->azure_hl, "messageTimeout",
                                  &msg_timeout);

then I start to call 
         IoTHubClient_LL_DoWork(elt->az_conn->azure_hl);

Thanks in advance for any hints.
Best regards,
Angelo

**Comment by ewertons** [comment]
Hi @angelobt ,
this seems odd, you should not be getting the DEVICE_DISABLED value if the device is enabled in the hub.
Would it be possible for you to collect and post verbose logs so we can have a better view of the issue?
Please also print the returns of ConnectionStatusCallback, so we know what it raised.

To enable the verbose logging, please add these lines to your code (don't forget to uncomment):
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L80

On the side, would it be possible to run the same code above using AMQP transport, to compare?
Any additional piece of information helps a lot.

**Comment by angelobt** [comment]
root@shark:~# -> 08:15:41 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: eliot-iotHub-c100x.azure-devices.net/05a8e45f-b65c-4bd4-af2c-a3944c8a8dac/api-version=2016-11-14&DeviceCli
entType=iothubclient%2f1.1.27%20(Linux%3b%20armv7l) | PWD: XXXX | CLEAN: 0
<- 08:15:42 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Tue Feb  6 08:15:42 2018 File:/usr/src/debug/azure-iot-sdk/1.1.23-r0/git/c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1352 Connecti
on Not Accepted: 0x5: Not Authorized
-> 08:15:42 DISCONNECT
-> 08:15:43 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: eliot-iotHub-c100x.azure-devices.net/05a8e45f-b65c-4bd4-af2c-a3944c8a8dac/api-version=2016-11-14&DeviceClientType=iothub
client%2f1.1.27%20(Linux%3b%20armv7l) | PWD: XXXX | CLEAN: 0
<- 08:15:43 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Tue Feb  6 08:15:43 2018 File:/usr/src/debug/azure-iot-sdk/1.1.23-r0/git/c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1352 Connecti
on Not Accepted: 0x5: Not Authorized
-> 08:15:43 DISCONNECT
-> 08:15:45 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: eliot-iotHub-c100x.azure-devices.net/05a8e45f-b65c-4bd4-af2c-a3944c8a8dac/api-version=2016-11-14&DeviceClientType=iothub
client%2f1.1.27%20(Linux%3b%20armv7l) | PWD: XXXX | CLEAN: 0
<- 08:15:45 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Tue Feb  6 08:15:45 2018 File:/usr/src/debug/azure-iot-sdk/1.1.23-r0/git/c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1352 Connecti
on Not Accepted: 0x5: Not Authorized
-> 08:15:45 DISCONNECT
-> 08:15:52 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: eliot-iotHub-c100x.azure-devices.net/05a8e45f-b65c-4bd4-af2c-a3944c8a8dac/api-version=2016-11-14&DeviceClientType=iothub
client%2f1.1.27%20(Linux%3b%20armv7l) | PWD: XXXX | CLEAN: 0
<- 08:15:52 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Tue Feb  6 08:15:52 2018 File:/usr/src/debug/azure-iot-sdk/1.1.23-r0/git/c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1352 Connecti
on Not Accepted: 0x5: Not Authorized
-> 08:15:52 DISCONNECT
-> 08:15:57 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: eliot-iotHub-c100x.azure-devices.net/05a8e45f-b65c-4bd4-af2c-a3944c8a8dac/api-version=2016-11-14&DeviceClientType=iothub
client%2f1.1.27%20(Linux%3b%20armv7l) | PWD: XXXX | CLEAN: 0
<- 08:15:57 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5




Seems that the problem is related to the system date.

The system boots with the date of Tue Feb  6 08:15:52 2018 (date of YOCTO compilation).
As soon as the ntp sets the rigth date, the connection becomes ok.
What could be the problem ?
I think nothing about certificates, because the date is only two days in the past.
If the device has been created inside IOThub at date X and the connection starts at date Y,  and Y < X, it could generate this issue ?
What controls are implemented inside IOThub ?

Best regards,

Angelo

**Comment by angelobt** [comment]
news ?

thanks

**Comment by ewertons** [comment]
Hi @angelobt ,
sorry, overhead with paging has blocked progress here.

Yes, the problem is the system time. Your system cannot have its time off by more than 5 minutes to successfully establish connection with the Azure IoT Hub. That applies to the TLS connection, as well as the SAS token if you are authenticating using SAS (i.e., not using x509 certs for authentication).

**Comment by ewertons** [comment]
Hi @angelobt ,
just one small correction: the system time is critical only for the SAS-token based authentication. The system time would need to be extremely off to affect TLS (only what related to certificate expiration verification).
But in the end, yes, your system clock needs to be correct (i.e., in sync with current UTC time).

**Comment by ewertons** [comment]
If you have further comments or questions about this, please feel free to reopen the issue.
Thanks,
Azure IoT Team.

**Comment by sagar448** [comment]
I have a very similar error and Im using x509 certs for authentication. Just in case i've also set the time properly. Yet I still get not authorized, please help!
