### ISSUE TITLE
Calling Direct Methods not working on Esp8266

### ISSUE THREAD

**Issue by MehranMazhar** [Azure/azure-iot-sdk-c#378]
when i add the model :
`WITH_METHOD(TurnOn)`

and define this function :

```
METHODRETURN_HANDLE TurnOn(ContosoAnemometer* device)
{
  (void)device;
  (void)printf("Turning fan on with Method.\r\n");

  METHODRETURN_HANDLE result = MethodReturn_Create(1, "{\"Message\":\"Turning fan on with 
  Method\"}");
  return result;
}
```

Calling direct methods does not work
But in previous versions of this solution it responded.

I have to work with the direct method in arduino for the following reasons:

Durability :
Disconnected devices are not contacted. The solution back end is notified that the device is not
connected.

Data flow:
Two-way. The device app can respond to the method right away. The solution back end receives the outcome contextually to the request.

**Comment by mamokarz** [comment]
Hi @MehranMazhar,

It is nice that you are using our SDK. DeviceMethod is not currently supported for Arduino. It is on our backlog, but we don't have any ETA.

As workaround you can use DeviceTwin to do that. On the service client, you can convert the function name and parameters in desired properties, and in the device cliente, you can call your function on the desired property callback.

Thank you,
Marcos

**Comment by tameraw** [comment]
Given the workaround above, we currently would not be adding support to ESP8266.

**Comment by MehranMazhar** [comment]
For the following reasons M2C(Message to Device) with using device twin  can not be an alternative solution .

Durability :
Disconnected devices are not contacted. The solution back end is notified that the device is not
connected.

Data flow:
Two-way. The device app can respond to the method right away. The solution back end receives the outcome contextually to the request.


I think we should have a closer look at this feature.
