### ISSUE TITLE
IoTHub blob storage upload from file

### ISSUE THREAD

**Issue by VolkerKamin** [Azure/azure-iot-sdk-c#38]
AFAIU, the upload to the blob storage using the C SDK is limited to data that is 100% in-memory.

Is that correct?
Are there plans to support FILE* or callback methods to read large files in chunks but still upload them as one file to the cloud?

Having to buffer the whole file would either significantly limit the file size or require a chunking / dechunking mechanism on top of the blog storage.

Unfortunately, using C# is not option; C or C++ is set.

**Comment by anporumb** [comment]
Hello @VolkerKamin ,

You are perfectly right - at the moment the only functionality we expose in C is to upload a byte array from memory.

*At the moment*, there are no plans to allow other sources (such as FILE*) for file uploading. We might consider such features at a later time in the SDK development. I am sorry if this is not the answer you were looking for.

Best Regards,
Andrei Porumb
