### ISSUE TITLE
request: implement cmake library version check 

### ISSUE THREAD

**Issue by jdswensen** [Azure/azure-iot-sdk-c#382]
# Description of the issue:
I recently had [an issue](https://github.com/Azure/azure-iot-sdk-c/issues/360) that was resolved by upgrading my openssl library version. I suggest using CMake's `find_package` routine (or similar routine) to require a minimum version of all libraries the SDK links against so that others don't run into version specific issues in the future.

Thanks!

**Comment by jspaith** [comment]
This is a good idea.  No ETA but we'll definitely track this.

**Comment by tameraw** [comment]
@jdswensen - If interested in submitting a PR, we can review that. Thanks.

**Comment by massand** [comment]
We welcome a PR for addressing any concerns this issue. Thanks.

**Comment by az-iot-builder-01** [comment]
@jdswensen, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
