### ISSUE TITLE
Adding serializer.h to iothub_client

### ISSUE THREAD

**Issue by s103619** [Azure/azure-iot-sdk-c#388]
I've made an application for a mips-based device using the iothub_client as a jumping off point and has served me well so far. Now, however, I need to add some JSON functionalities, namely reading a JSON file. I know there's one in the Seralizer project folder, but unsure how I should import it to the iothub_client project I am working on. 

Is there some documentation for which .c and .h files I should copy over (if any) and how to write the CMakeLists.text file? When I look at a project in the Serializer folder, I can see that it has `serializer` in its target_link_libraries, but when building my project still cannot find the `serializer.h` file.

EDIT 1: Tried copying the `serializer.h` file over from the serializer/inc folder and then copy all .h files it's asking for when building and currently get an `cannot find -lserializer` error.

EDIT 2: Added all necessary src files as well.

EDIT 3: Added everything from the serializer CMakeLists.txt file that seemed relevant to the serializer library and now get these errors: 

	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_double':
	cloud_to_device.c:(.text+0x38): undefined reference to `Create_AGENT_DATA_TYPE_from_DOUBLE'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_float':
	cloud_to_device.c:(.text+0x154): undefined reference to `Create_AGENT_DATA_TYPE_from_FLOAT'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_int':
	cloud_to_device.c:(.text+0x268): undefined reference to `Create_AGENT_DATA_TYPE_from_SINT32'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_long':
	cloud_to_device.c:(.text+0x38c): undefined reference to `Create_AGENT_DATA_TYPE_from_SINT64'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_int8_t':
	cloud_to_device.c:(.text+0x4ac): undefined reference to `Create_AGENT_DATA_TYPE_from_SINT8'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_uint8_t':
	cloud_to_device.c:(.text+0x5c4): undefined reference to `Create_AGENT_DATA_TYPE_from_UINT8'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_int16_t':
	cloud_to_device.c:(.text+0x6dc): undefined reference to `Create_AGENT_DATA_TYPE_from_SINT16'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_int32_t':
	cloud_to_device.c:(.text+0x7ec): undefined reference to `Create_AGENT_DATA_TYPE_from_SINT32'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_int64_t':
	cloud_to_device.c:(.text+0x904): undefined reference to `Create_AGENT_DATA_TYPE_from_SINT64'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE__Bool':
	cloud_to_device.c:(.text+0xa30): undefined reference to `Create_EDM_BOOLEAN_from_int'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_ascii_char_ptr':
	cloud_to_device.c:(.text+0xb48): undefined reference to `Create_AGENT_DATA_TYPE_from_charz'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_ascii_char_ptr_no_quotes':
	cloud_to_device.c:(.text+0xd80): undefined reference to `Create_AGENT_DATA_TYPE_from_charz_no_quotes'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_EDM_DATE_TIME_OFFSET':
	cloud_to_device.c:(.text+0xff4): undefined reference to `Create_AGENT_DATA_TYPE_from_EDM_DATE_TIME_OFFSET'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_EDM_GUID':
	cloud_to_device.c:(.text+0x1184): undefined reference to `Create_AGENT_DATA_TYPE_from_EDM_GUID'
	CMakeFiles/axis_comm.dir/cloud_to_device.c.o: In function `ToAGENT_DATA_TYPE_EDM_BINARY':
	cloud_to_device.c:(.text+0x1300): undefined reference to `Create_AGENT_DATA_TYPE_from_EDM_BINARY'

**Comment by jspaith** [comment]
Have you had a look at https://github.com/Azure/azure-iot-sdk-c/tree/master/serializer/samples, samples using the serializer?  It'll likely be easier to use one of these cmakelist.txt as a jumping off point than building everything up from scratch.

We're going to add better documentation for serializer soon, but before you use it (as opposed to a raw json parser like parson), just be aware:
* It assumes that the schema will never change and if it sees elements it doesn't know, it stops parsing.
* It only takes up to 61 fields as children of any given parent.  (You can go as deep as you want, so it is *not* a 61 field max total, but only no 61 siblings).
* It's pretty efficient, but... if you're targeting a very constrained device (think a few MB) it's going to add additional overhead on a device where every byte counts.

The serializer obviously does do a lot of nice typing help for you, but want you to go in fully understanding its pros/cons.

**Comment by s103619** [comment]
I did, but the CMakeLists files were significantly larger in the iothub_client project, so assumed it would be easier to add its functionality to iothub_client instead, but, in hindsight, the size probably has more to do with higher quantity of samples. 

It will be used on a fairly constrained device, and only needs to read very simple, small JSON messages, so maybe it's a bit overkill to use the Serializer. Thank you for the quick answer, it was very helpful and informative.
