### ISSUE TITLE
Valgrind reports memory loss in xio.c

### ISSUE THREAD

**Issue by mm-mhr** [Azure/azure-iot-sdk-c#39]
I am observing a memory increase when using Azure Device SDK from 2017-01-13.
It is several 100k a day. On my embedded device this means that it will not run over a long time.
So I tested my application using valgrind and it reports a memory loss in xio.c.

Here is the report from valgrind:
131 (16 direct, 115 indirect) bytes in 1 blocks are definitely lost in loss record 877 of 1,038
  in xio_create in /home/mm/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:39
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: xio_create in /home/mm/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:39
  3: create_openssl_instance in /home/mm/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:861
  4: tlsio_openssl_open in /home/mm/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1051
  5: xio_open in /home/mm/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:90
  6: mqtt_client_connect in /home/mm/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:865
  7: SendMqttConnectMsg in /home/mm/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1553
  8: InitializeConnection in /home/mm/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1594
  9: IoTHubTransport_MQTT_Common_DoWork in /home/mm/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2287
  10: IoTHubTransportMqtt_DoWork in /home/mm/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:89
  11: IoTHubClient_LL_DoWork in /home/mm/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:949
  12: TransmitterIoTHubLL::WaitForSdkToBecomeReady(double) in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/src/Connection/TransmitterIoTHubLL.cpp:357
  13: TransmitterIoTHubLL::Run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/src/Connection/TransmitterIoTHubLL.cpp:210
  14: void std::_Mem_fn<void (TransmitterIoTHubLL::*)()>::operator()<, void>(TransmitterIoTHubLL*) const in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/build-DataAgent-Desktop-Debug/DataAgent
  15: void std::_Bind_simple<std::_Mem_fn<void (TransmitterIoTHubLL::*)()> (TransmitterIoTHubLL*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) in /usr/include/c++/4.8/functional:1732
  16: std::_Bind_simple<std::_Mem_fn<void (TransmitterIoTHubLL::*)()> (TransmitterIoTHubLL*)>::operator()() in /usr/include/c++/4.8/functional:1720
  17: std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (TransmitterIoTHubLL::*)()> (TransmitterIoTHubLL*)> >::_M_run() in /usr/include/c++/4.8/thread:115
  18: /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
  19: start_thread in /build/eglibc-3GlaMS/eglibc-2.19/nptl/pthread_create.c:312
  20: clone in /build/eglibc-3GlaMS/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111

I am using "LL" API and I have selected MQTT for transport protocol.

**Comment by dcristoloveanu** [comment]
Identified the leak in that the underlying_io is not destroyed in destroy_openssl_instance.
A fix will be checked in shortly.

Thanks,
/Dan

**Comment by dcristoloveanu** [comment]
This fix has been checked in the master branch and will be picked up in the next release.

**Comment by anporumb** [comment]
Published
