### ISSUE TITLE
Recommendation: Please consider moving the samples into separate repo.

### ISSUE THREAD

**Issue by paloukari** [Azure/azure-iot-sdk-c#391]
- **OS and version used**: ALL

- **SDK version used**: ALL

It's difficult to start experimenting with the SDK Samples because the samples are coupled with the SDK. Please consider moving the samples into a separate repo.

Also, although the samples use the Nuget packages, they also include files directly from the SDK, making it difficult for developers to start using the SDK in a new empty project.

It would be nice to have a simple sample console app, referencing the minimum packages, that demonstrates a simple D2C scenario with the minimum required code. 

**Example**: 
The the iothub_ll_telemetry_sample VS project uses the certs.c from the SDK.

![image](https://user-images.githubusercontent.com/7554503/37217770-46fd2ade-2373-11e8-95bf-5c5570f4ab92.png)

**Comment by jspaith** [comment]
We're going to leave the samples in existing repo; we have enough subrepos as-is and I don't want to further complicate life.

Git has a mechanism to just clone individual files - https://askubuntu.com/questions/460885/how-to-clone-git-repository-only-some-directories.  I've tried it out and it works and it's FAST, but we'd need to document it in our readme (it's not a one-shot git command) so the question would be whether this added complexity would be worth it versus the standard existing standard?

**Comment by jspaith** [comment]
On further consideration, trying to have the fast sync doc'd just adds one extra path that folks have to read through and we believe most people clone whole repo sooner or later anyway..  So closing this guy out.
