### ISSUE TITLE
Recommendation: Simplify that API names 

### ISSUE THREAD

**Issue by paloukari** [Azure/azure-iot-sdk-c#392]
- **OS and version used:** ALL

- **SDK version used:**  ALL 

# Description of the issue:
It's not clear why the API contains names like **IoTHubClient_LL_CreateFromConnectionString**. 
Moreover, this naming convention is even more confusing when is used in the filenames in lowercase, it looks like the Latin number 2: **iothub_ll_telemetry_sample.c**

**Comment by jspaith** [comment]
If and when we ever decide to break API compat with a V2 of SDK, we'll definitely take this into account and get consultation from community.  For now though, we don't have enough justification to break folks SDK's out there so this isn't something we can take on right now.  Thanks
