### ISSUE TITLE
In some samples, all communication protocols are defined

### ISSUE THREAD

**Issue by paloukari** [Azure/azure-iot-sdk-c#393]
- **OS and version used:** ALL

- **SDK version used:** ALL

# Description of the issue:
In the samples, all communication protocol compiler directives are being used: **USE_HTTP;USE_AMQP;USE_MQTT;**

This is confusing and makes it difficult to understand which protocol is actually used.

# Example:
 
![image](https://user-images.githubusercontent.com/7554503/37218755-49e2b31a-2376-11e8-8d29-cc42521d9e56.png)

**Comment by jspaith** [comment]
We've refactored many of our samples to make them easier to follow.  However we don't want to create a sample per protocol, so adding them together is the best option for a quick start and us having code fit in one .c file.
