### ISSUE TITLE
Windows build script fails after it downloads nuget to wrong location

### ISSUE THREAD

**Issue by idavis** [Azure/azure-iot-sdk-c#394]
- **OS and version used:** <VERSION> 
Windows 10 Enterprise Version 1709 (OS Build 16299.251)
- **SDK version used:** <VERSION> 
2018-03-07 3d6109b130e24c325b4d81d734ef6449fb1f7240

# Description of the issue:

Building the windows code from the `.\build_all\windows\build.cmd` downloads nuget but then fails to find it. The script is downloading the nuget.exe to the parent of the repo folder.

# Code sample exhibiting the issue:

# Console log of the issue:

After cloning the repo
```
C:\dev\azure-iot-sdk-c [master]> cd .\build_all\windows\                         
C:\dev\azure-iot-sdk-c\build_all\windows [master]> & .\build.cmd                 
Build Root: C:\dev\azure-iot-sdk-c                                               
Repo Root: C:\                                                                   
Azure IoT SDK needs to download nuget.exe from https://www.nuget.org/nuget.exe   
https://www.nuget.org                                                            
Do you want to download and run nuget.exe? [Y,N]?Y                               
nuget does not exist
C:\dev\azure-iot-sdk-c [master]>
```

Looking at the repos' parent folder:

```
C:\dev\azure-iot-sdk-c\build_all\windows [master]> ls C:\dev\


    Directory: C:\dev


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         3/9/2018   9:11 AM                azure-iot-sdk-c
-a----         3/9/2018   9:12 AM        1686528 nuget.exe
```

**Comment by jspaith** [comment]
Moving to area-documentation.  Please (a) put a readme stating that these are internal only and (b) make sure no samples reference this.

**Comment by massand** [comment]
@bikamani - The CI scripts and YAMLs are being restructured into different folders after our recent CI rework.  As @jspaith said, the new folder structure (and corresponding READMEs) should have clear labelling for internal CI vs externally consumable files. Long term, we should make available docker images for all our CI for the community to run.

**Comment by bikamani** [comment]
I have added a read me for the build scripts which are for internal builds. Our long term plan is to have CI scripts restructured in build directory.
