### ISSUE TITLE
Recommendation: Simplify the outbound message creation

### ISSUE THREAD

**Issue by paloukari** [Azure/azure-iot-sdk-c#395]
- **OS and version used:** <VERSION> ALL

- **SDK version used:** <VERSION> ALL

# Description of the issue:
There is no simple way in the API to create a new message.

# Code sample exhibiting the issue:
The **iothub_ll_telemetry_sample** code

```
            // Construct the iothub message from a string or a byte array
            message_handle = IoTHubMessage_CreateFromString(telemetry_msg);
            //message_handle = IoTHubMessage_CreateFromByteArray((const unsigned char*)msgText, strlen(msgText)));

            // Set Message property
            (void)IoTHubMessage_SetMessageId(message_handle, "MSG_ID");
            (void)IoTHubMessage_SetCorrelationId(message_handle, "CORE_ID");
            (void)IoTHubMessage_SetContentTypeSystemProperty(message_handle, "application%2Fjson");
            (void)IoTHubMessage_SetContentEncodingSystemProperty(message_handle, "utf-8");

            // Add custom properties to message
            MAP_HANDLE propMap = IoTHubMessage_Properties(message_handle);
            Map_AddOrUpdate(propMap, "property_key", "property_value");

            (void)printf("Sending message %d to IoTHub\r\n", (int)(messages_sent+1) );
            IoTHubClient_LL_SendEventAsync(iothub_ll_handle, message_handle, send_confirm_callback, NULL);

            // The message is copied to the sdk so the we can destroy it
            IoTHubMessage_Destroy(message_handle);
```

is demonstrating a simple scenario of sending multiple telemetry messages. 
Please consider extending the SDK to offer a _simple_ version of this code like:

```
IoTHubClient_PostMessage("data");
IoTHubClient_Flush();

```

for an 'asynchronous' scenario or  

```
IoTHubClient_SendMessage("data");

```

for a blocking scenario.

**Comment by massand** [comment]
The sample is intended to demonstrate the options available for sending messages (telemetry). So, I don't believe we can compare the sample code snippet to the API design. 
The proposed simple version does not consider the C SDK conventions of using client handle, callbacks for error handling, context, etc. All of those parameters form a consistent set of behaviors C SDK users have come to expect. If an API design or PR is proposed with all the relevant details, we welcome ideas to enhance our convenience layer.

**Comment by az-iot-builder-01** [comment]
@paloukari, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
