### ISSUE TITLE
Fix the SDK API definitions 

### ISSUE THREAD

**Issue by paloukari** [Azure/azure-iot-sdk-c#396]
- **OS and version used:** <VERSION> ALL

- **SDK version used:** <VERSION> ALL

# Description of the issue:
In Visual Studio, open the telemetry sample project and go to the definition of one of the SDKs methods, like the **IoTHubClient_LL_CreateFromConnectionString**. 

VS takes me to a non standard C method definition like the one bellow:

`MOCKABLE_FUNCTION(, IOTHUB_CLIENT_LL_HANDLE, IoTHubClient_LL_CreateFromConnectionString, const char*, connectionString, IOTHUB_CLIENT_TRANSPORT_PROVIDER, protocol); `

**Comment by zvrba** [comment]
Yes, it's a big hindrance in trying to understand the implementation. In addition, I find these declarations horrible to read also when just writing client code and browsing the headers.

**Comment by rspielmann** [comment]
This also affects the generated documentation and makes it almost unreadable, see for example [1]. The Doxygen parser appears to see the MOCKABLE_FUNCTION macro as the function name, so in turn, effectively every function is called (and linked under that name) MOCKABLE_FUNCTION in the HTML output. It's great to see that the code is supposed to be unit-testable, but maybe there is some way to make the documentation a bit easier on the eyes?

[1] https://azure.github.io/azure-iot-sdk-c/iothub__client__ll_8h.html

**Comment by rspielmann** [comment]
Addition: maybe it would work if Doxygen was simply applied to the headers after pre-processing, i.e. as soon as the macros have been replaced by actual function declarations. This would have to happen within a build where `ENABLE_MOCKS` is not defined, which I assume will be the case for release builds.

**Comment by massand** [comment]
Our docs are now updated - https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/
This is a first take at making our Doxygen content more useful. We will be continually improving on these soon. Stay tuned

**Comment by az-iot-builder-01** [comment]
@paloukari, @zvrba, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
