### ISSUE TITLE
Code comments instruct the user to enter the wrong connection string

### ISSUE THREAD

**Issue by idavis** [Azure/azure-iot-sdk-c#398]
- **OS and version used:** <VERSION> 
ALL

- **SDK version used:** <VERSION> 
2018-03-07 3d6109b

# Description of the issue:

Code comments instruct the user to enter the wrong connection string. All other samples just use `
static const char* connectionString = "[device connection string]";` but the samples listed below have incorrect comments.

# Code sample exhibiting the issue:

https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_c2d_sample/iothub_ll_c2d_sample.c#L32

https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L36-L37

**Comment by jebrando** [comment]
I believe this issue is fixed.  Please reopen if you see any more issues.

**Comment by tameraw** [comment]
@idavis thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
