### ISSUE TITLE
iothub_ll_c2d_sample will not work with HTTP or MQTT without code modifications

### ISSUE THREAD

**Issue by idavis** [Azure/azure-iot-sdk-c#399]
- **OS and version used:** <VERSION> 
ALL
- **SDK version used:** <VERSION> 
2018-03-07 3d6109b

# Description of the issue:

The initialization of the protocols is commented out for USE_MQTT and USE_HTTP.  Trying to use either of them will result in an error. 

# Code sample exhibiting the issue:

https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_c2d_sample/iothub_ll_c2d_sample.c#L94-L104

# Console log of the issue:

```"Run-Time Check Failure #3 - The variable 'protocol' is being used without being initialized." ```

**Comment by jebrando** [comment]
Fixed in new samples.
