### ISSUE TITLE
Valgrind reports memory loss in crt_abstractions.c

### ISSUE THREAD

**Issue by mm-mhr** [Azure/azure-iot-sdk-c#40]
I am observing a memory increase when using Azure Device SDK from 2017-01-13.
It is several 100k a day. On my embedded device this means that it will not run over a long time.
So I tested my application using valgrind and it reports a memory loss in crt_abstractions.c

21 bytes in 1 blocks are definitely lost in loss record 48 of 1,038
  in mallocAndStrcpy_s in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/crt_abstractions.c:689
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: mallocAndStrcpy_s in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/crt_abstractions.c:689
  3: cloneMqttOptions in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:402
  4: mqtt_client_connect in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:859
  5: SendMqttConnectMsg in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1553
  6: InitializeConnection in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1594
  7: IoTHubTransport_MQTT_Common_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2287
  8: IoTHubTransportMqtt_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:89
  9: IoTHubClient_LL_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:949
  10: TransmitterIoTHubLL::WaitForSdkToBecomeReady(double) in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/src/Connection/TransmitterIoTHubLL.cpp:357
  11: TransmitterIoTHubLL::Run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/src/Connection/TransmitterIoTHubLL.cpp:210
  12: void std::_Mem_fn<void (TransmitterIoTHubLL::*)()>::operator()<, void>(TransmitterIoTHubLL*) const in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/build-DataAgent-Desktop-Debug/DataAgent
  13: void std::_Bind_simple<std::_Mem_fn<void (TransmitterIoTHubLL::*)()> (TransmitterIoTHubLL*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) in /usr/include/c++/4.8/functional:1732
  14: std::_Bind_simple<std::_Mem_fn<void (TransmitterIoTHubLL::*)()> (TransmitterIoTHubLL*)>::operator()() in /usr/include/c++/4.8/functional:1720
  15: std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (TransmitterIoTHubLL::*)()> (TransmitterIoTHubLL*)> >::_M_run() in /usr/include/c++/4.8/thread:115
  16: /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
  17: start_thread in /build/eglibc-3GlaMS/eglibc-2.19/nptl/pthread_create.c:312
  18: clone in /build/eglibc-3GlaMS/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111

  I am using "LL" API and I have selected MQTT for transport protocol.

**Comment by anporumb** [comment]
Hello @mm-mhr ,

Could you please attach here a minimal repro or detailed information on how to repro this? Thank you.

Best Regards,
Andrei Porumb

**Comment by mm-mhr** [comment]
`#include <iostream>
#include <unistd.h>
#include <stdexcept>

// Azure IoT Hub SDK
#include <iothub_client_version.h>
#include <iothub_message.h>
#include <iothub_client.h>
#include <azure_c_shared_utility/threadapi.h>
#include <azure_c_shared_utility/crt_abstractions.h>
#include <iothubtransportmqtt.h>
#include <azure_c_shared_utility/platform.h>
#include <certs/certs.c>


struct TrackedMessage
{
    IOTHUB_MESSAGE_HANDLE iotHubMessageHandle = nullptr;
    bool isHeartbeat = false;
};

IOTHUB_CLIENT_HANDLE iotHubClientHandle = nullptr;

// Forward declarations
void SendConfirmationCallback(IOTHUB_CLIENT_CONFIRMATION_RESULT result, void* userContextCallback);
void InitAzureSDK();
void SendHeartBeatMessage();
void CleanUpSdk();

int main(int argc, char *argv[])
{
      InitAzureSDK();

      // Run for two hours
      for (size_t i=0; i<7200; i++)
      {
        // Send any message
        SendHeartBeatMessage();
        sleep(1);
      }

      CleanUpSdk();

    // Make sure we have a clean "exit" to not confuse valgind.
    // Do not call exit, do not Ctrl+C, just return!
    return 0;
}


void SendConfirmationCallback(IOTHUB_CLIENT_CONFIRMATION_RESULT result, void* userContextCallback)
{
    TrackedMessage* trackedMessage = reinterpret_cast<TrackedMessage*>(userContextCallback);

    if (result == IOTHUB_CLIENT_CONFIRMATION_OK)
    {
            std::cout << "Sending message ok." << std::endl;
    }
    else
    {
            std::cout << "Sending heartbeat message failed: " << result << std::endl;
    }

    IoTHubMessage_Destroy(trackedMessage->iotHubMessageHandle);
    delete trackedMessage;
}


void InitAzureSDK()
{
    std::cout << "Initialize Azure SDK, version:" << IoTHubClient_GetVersionString() << std::endl;

    xlogging_set_log_function(nullptr); // Silence out the SDK

    if (platform_init() != 0)
    {
        throw std::runtime_error("Azure SDK platform_init failed.");
    }

    std::string conString = "HostName=GetYourOwn.azure-devices.net;DeviceId=valgindTest;SharedAccessKey=mdkufFo4DWo43IZSTKXs3GLc3OkeEEaX2ctTwyyfsnI=";
    if ((iotHubClientHandle = IoTHubClient_CreateFromConnectionString(conString.c_str(), MQTT_Protocol)) == NULL)
    {
        throw std::runtime_error("IoTHubClient_CreateFromConnectionString failed with connection string:" + conString );
    }

    // Set the  root certificate for simplicity from the SDK provided file.
    // For real world we have to load the certificate from somewhere and make it exchangable
    if (IOTHUB_CLIENT_OK != IoTHubClient_SetOption(iotHubClientHandle, "TrustedCerts", certificates))
    {
        throw std::runtime_error("IoTHubClient_SetOption TrustedCerts failed");
    }

    // IOTHUB_CLIENT_RETRY_EXPONENTIAL_BACKOFF_WITH_JITTER is actually the only supported one :(
    if (IoTHubClient_SetRetryPolicy(iotHubClientHandle, IOTHUB_CLIENT_RETRY_EXPONENTIAL_BACKOFF_WITH_JITTER, 120) != IOTHUB_CLIENT_OK)
    {
        throw std::runtime_error("IoTHubClient_SetRetryPolicy failed");
    }
}

void SendHeartBeatMessage()
{
    std::string heartbeat = "{ \"MessageType\":\"Heartbeat\"}";
    auto messageHandle = IoTHubMessage_CreateFromByteArray(reinterpret_cast<const unsigned char*>(heartbeat.c_str()), heartbeat.size());

    if (!messageHandle)
    {
        throw std::runtime_error("IoTHubMessage_CreateFromByteArray failed");
    }

    TrackedMessage* trackedMessage = new TrackedMessage; // cannot use shared_ptr because of Azure-SDK-API (confirmation callback)
    trackedMessage->iotHubMessageHandle = messageHandle;
    trackedMessage->isHeartbeat = true;

    if (IOTHUB_CLIENT_OK == IoTHubClient_SendEventAsync(iotHubClientHandle, messageHandle, SendConfirmationCallback, trackedMessage))
    {
        std::cout << "Sending heartbeat message" << std::endl;
    }
    else
    {
        throw std::runtime_error("IoTHubClient_SendEventAsync failed");
    }
}

void CleanUpSdk()
{
    std::cout << "Cleaning up SDK" << std::endl;
    IoTHubClient_Destroy(iotHubClientHandle);
    platform_deinit();
}
`

**Comment by anporumb** [comment]
Thank you! I will return here once we have investigated/fixed it.

Best Regards,
Andrei Porumb

**Comment by jebrando** [comment]
Thanks for the sample.  I was able to repo and I'll have a fix tomorrow.

**Comment by jebrando** [comment]
The issue should be fixed with the round of check in going in today.
