### ISSUE TITLE
Missing project/solution/<platform> folder for iothub_client\samples\iothub_ll_c2d_sample

### ISSUE THREAD

**Issue by idavis** [Azure/azure-iot-sdk-c#400]
- **OS and version used:** <VERSION> 
Windows
- **SDK version used:** <VERSION> 
2018-03-07 3d6109b

# Description of the issue:

iothub_client\samples\iothub_ll_c2d_sample doesn't have a windows folder (or any other platform) to be runnable.

Worked around this by copying the iothub_ll_c2d_sample.c to the iothub_ll_telemetry_sample folder and adding it to the project.

**Comment by JetstreamRoySprowl** [comment]
@idavis What steps did you take to enter this state? I just cloned the SDK on my Windows box and ran</br>
` cmake ..\azure-iot-sdk-c   -Drun_e2e_tests=ON -Drun_unittests:bool=ON`</br>
which created an iothub_ll_c2d_sample project containing `iothub_ll_c2d_sample.c` two lines up from the telemetry sample.

**Comment by JetstreamRoySprowl** [comment]
Thanks Ian, this has been added to the latest master. Please re-open if you have any issues.
