### ISSUE TITLE
Missing sln/proj file in sample

### ISSUE THREAD

**Issue by idavis** [Azure/azure-iot-sdk-c#402]
- **OS and version used:** <VERSION> 
ALL
- **SDK version used:** <VERSION> 
2018-03-07 3d6109b

# Description of the issue:

`serializer\samples\devicemethod_simplesample\windows` has neither a solution nor project file.

**Comment by JetstreamRoySprowl** [comment]
This is normal behavior. You need to run cmake against the SDK, which will generate the appropriate system-specific build files. Here's a link for building: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md

**Comment by JetstreamRoySprowl** [comment]
Thanks for the report. This has been added to the latest master. Please re-open if you have any issues.
