### ISSUE TITLE
Sample shouldn't throw away return codes and should have expected usage

### ISSUE THREAD

**Issue by idavis** [Azure/azure-iot-sdk-c#403]
- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 
2018-03-07 3d6109b

# Description of the issue:

# Code sample exhibiting the issue:

The `iothub_client/samples/iothub_ll_telemetry_sample` isn't inspecting API calls for failure.

```
            (void)IoTHubMessage_SetMessageId(message_handle, "MSG_ID");
            (void)IoTHubMessage_SetCorrelationId(message_handle, "CORE_ID");
            (void)IoTHubMessage_SetContentTypeSystemProperty(message_handle, "application%2Fjson");
            (void)IoTHubMessage_SetContentEncodingSystemProperty(message_handle, "utf-8");
```
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L98-L101

**Comment by jebrando** [comment]
Yes, since these are samples we do not want to clutter the functionality with error checking and things that take away from the functionality.  We are adding a disclaimer at the top saying that these are not production code and is just a sample to show functionality.
