### ISSUE TITLE
IoTHubClient_LL_(SendEventAsync | DoWork) Documentation

### ISSUE THREAD

**Issue by idavis** [Azure/azure-iot-sdk-c#404]
- **OS and version used:** <VERSION> 
ALL
- **SDK version used:** <VERSION> 
ALL

# Description of the issue:

The documentation needs to clearly call out that `IoTHubClient_LL_SendEventAsync` does not send anything, and in fact queues work which is only processed during `IoTHubClient_LL_DoWork` calls.

**Comment by massand** [comment]
Please review the [Connection and Messaging Reliability](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/connection_and_messaging_reliability.md#behavior-of-the-device-client-sdk-while-re-connecting) guidelines. We hope the details there are clearer. Thanks for pointing this out, @idavis!
