### ISSUE TITLE
Use lowercase devicename (registrationId) in CA certificate tooling sample

### ISSUE THREAD

**Issue by ddewaele** [Azure/azure-iot-sdk-c#405]
The [CACertificates guide](https://github.com/Azure/azure-iot-sdk-c/tree/master/tools/CACertificates) and scripts are a great resource for learning to work with certificates in Azure IoT.

In the guide, a device called `myDevice` is created. (notice the camelcasing)

Azure IoT Device Provisioning Service uses a registration ID to uniquely identify a device in the Device Provisioning Service.  The registration ID is alphanumeric, lowercase, and may contain hyphens.

In the case of X.509-based attestation, the registration ID is provided as the subject name of the certificate.

Lost about 1 hour of finding out why my devices could not enroll to IoT HUB via DPS because of this :)

Kept getting 

`{"errorCode":400004,"trackingId":"xxx","message":"Invalid RegistrationId","timestampUtc":"2018-03-10T15:40:43.7120109Z"}` 

because of the fact the CN contained an uppercase character

**Comment by jspaith** [comment]
@ddewaele - first happy you had success (almost) with the certs, and thanks for calling out the issue.

Let me talk with DPS experts on my side to make sure I fully have my head around this issue.  Once I do, it's a trivial fix which we'll happily make to save other folks time.

Thanks again and sorry for bumpiness you've hit.

**Comment by jspaith** [comment]
I've confirmed that what you're seeing is expected behavior from DPS side, which means that the readme needs to get updated.  I'm in process of getting this addressed and it should be in soon.  (Please ignore the commit referencing this issue, #405, this was a bad commit message on my part.)

Thanks again for reaching out here.

**Comment by jspaith** [comment]
Fixed with commit #c22aa0a9766c745a37da3779c89c44c7a428174f
