### ISSUE TITLE
Cmake fails with -Duse_prov_client:BOOL=ON

### ISSUE THREAD

**Issue by zvrba** [Azure/azure-iot-sdk-c#407]
I'm trying to build the SDK on Windows 10 using VS 2017 for x64. When I run cmake (v3.8.2) with the above option (I want to use the TPM), I get the following error:

```
C:\Users\Stian Vrba\Documents\QUINE\azure-iot-sdk-c\build>cmake -Duse_prov_client:BOOL=ON ..
-- IoT Client SDK Version = 1.2.0
CMake Error at configs/azure_iot_sdksFunctions.cmake:48 (message):
  Unable to find version in #define PROV_DEVICE_CLIENT_VERSION "1.2.0"
Call Stack (most recent call first):
  CMakeLists.txt:92 (getProvSDKVersion)
```

I have traced it to the following statement in `getProvSDKVersion`: `if (CMAKE_MATCH_3)`. In this case, the captured group `CMAKE_MATCH_3` evaluates to string "0" which is interpreted as false, which wrongly results in the above message. Fixing the statement to `if (NOT "${CMAKE_MATCH_3}" STREQUAL "")` fixes the problem and the version is correctly parsed and detected:

```
-- Provisioning SDK Version = 1.2.0
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- iothub architecture: x86_64
-- target architecture: x86_64
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Stian Vrba/Documents/QUINE/azure-iot-sdk-c/build
```

**Comment by ferantivero** [comment]
I can reprod it!

**Comment by JetstreamRoySprowl** [comment]
I'm working on this right now.
