### ISSUE TITLE
Question about usage of TLS Certificates

### ISSUE THREAD

**Issue by mm-mhr** [Azure/azure-iot-sdk-c#41]
In the programming examples, the TLS certificates are compiled into the code (certs.c).
I realize that it is actually three certificates where only one of them is a root certificate.
The certificates for “*.azure-devices.net” and “MSIT” are provided by the example in addition to the root certificate.
In my understanding only the root certificate ("baltimore") should be passed. Is there a specifc reason to pass the non-root certificates?

**Comment by dcristoloveanu** [comment]
Hi @mm-mhr 

We put there the other 2 cert information for completeness at the time (when IoTHub went public).
I will look at removing the other 2 certificates in the chain soon. I will close this issue when that is done.

Thanks,
/Dan

**Comment by dcristoloveanu** [comment]
@mm-mhr 

The removal of the extra certs has been checked in to master.
Closing this issue.

Thanks,
/Dan
