### ISSUE TITLE
Missing function implementations (DEFINE_ENUM_STRINGS)

### ISSUE THREAD

**Issue by zvrba** [Azure/azure-iot-sdk-c#411]
When linking to release 2018-03-02 I get the following errors:
```
1>IoTHub.obj : error LNK2001: unresolved external symbol IOTHUB_CLIENT_CONNECTION_STATUSStrings
1>IoTHub.obj : error LNK2001: unresolved external symbol IOTHUB_CLIENT_CONNECTION_STATUS_REASONStrings
```
A quick global search through the entire generated solution for the SDK indicates that the necessary `DEFINE_ENUM_STRINGS` for these enums simply aren't present.

**Comment by jspaith** [comment]
Thanks again for this feedback.The commit referenced above should fix this.
