### ISSUE TITLE
Packaging for ubuntu 17.10?

### ISSUE THREAD

**Issue by darobs** [Azure/azure-iot-sdk-c#412]
- **OS and version used:** <VERSION> 
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
- **SDK version used:** <VERSION> 
latest.

# Description of the issue:

Attempted apt-get for Ubuntu following these instructions:
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/ubuntu_apt-get_sample_setup.md

But the package source isn't working with 17.10.

# Console log of the issue:

sudo apt-get update
Hit:1 https://download.docker.com/linux/ubuntu artful InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu artful InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu artful-updates InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu artful-backports InRelease
Ign:5 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu artful InRelease
Get:6 http://security.ubuntu.com/ubuntu artful-security InRelease [78.6 kB]
Err:7 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu artful Release
  404  Not Found
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
$ sudo apt-get install -y azure-iot-sdk-c-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package azure-iot-sdk-c-dev

# Code sample exhibiting the issue:

**Comment by jebrando** [comment]
We will not be supporting 17.10 due to the end of life support for this release is July 2018.  We shall release an 18.04 apt-get once that release is out.
