### ISSUE TITLE
Device provisioning with x509 individual & Group  are not working 

### ISSUE THREAD

**Issue by lakshmisivareddy** [Azure/azure-iot-sdk-c#415]
-  @`<!--`

Hi ,
i tried with 

Provisioning API Version: 1.1.2
Iothub API Version: 1.1.32

my self signed certificates are verified in DPS certificates   still getting below error 

Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
<- [FLOW]* {0,5000,1,2147483647,1,0,1000,0,NULL,false,NULL}
-> [TRANSFER]* {1,0,<01 00 00 00>,0,false,false}
<- [TRANSFER]* {0,0,<F6 94 25 C8 21 E9 A6 4C 81 74 65 A1 2E 22 3F 28>,0,true,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,0,0,true,* {}}
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
-> [TRANSFER]* {1,1,<02 00 00 00>,0,false,false}
<- [TRANSFER]* {0,1,<FB 58 AB 52 5E 47 C7 4D A9 24 89 D0 A9 95 F5 5A>,0,true,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,1,1,true,* {}}
<- [DISPOSITION]* {true,1,NULL,true,* {},NULL}
Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
-> [TRANSFER]* {1,2,<03 00 00 00>,0,false,false}
<- [TRANSFER]* {0,2,<3A 29 1D 24 15 1E 95 4C B0 DE 3D 78 01 E7 30 D5>,0,true,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,2,2,true,* {}}
<- [DISPOSITION]* {true,2,NULL,true,* {},NULL}
Error: Time:Wed Mar 14 14:28:34 2018 File:/home/cpx/Development/New-SDK/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:prov_transport_process_json_reply Line:387 Unsuccessful json encountered: {"operationId":"2.87f7851aaaa18ed1.53c122cf-f188-4171-a7db-7bf89f958cc2","status":"failed","registrationState":{"registrationId":"riot-device-cert","createdDateTimeUtc":"2018-03-14T14:28:31.3898659Z","status":"failed","errorCode":401002,"errorMessage":"CA certificate not found","lastUpdatedDateTimeUtc":"2018-03-14T14:28:31.5532753Z","etag":"\"00006026-0000-0000-0000-5aa9318f0000\""}}
Error: Time:Wed Mar 14 14:28:34 2018 File:/home/cpx/Development/New-SDK/azure-iot-sdk-c/provisioning_client/src/prov_transport_amqp_common.c Func:prov_transport_common_amqp_dowork Line:1155 Unable to process registration reply.
Error: Time:Wed Mar 14 14:28:34 2018 File:/home/cpx/Development/New-SDK/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:454 Failure retrieving data from the provisioning service
Failure encountered on registration!
-> [DETACH]* {1,true}
-> [DETACH]* {0,true}
-> [END]* {}
-> [CLOSE]* {}
registration failed!

**Comment by jspaith** [comment]
Could you please provide additional information to help us understand what's up here?  In particular:




- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 


# Description of the issue:


# Code sample exhibiting the issue:


# Console log of the issue:

**Comment by lakshmisivareddy** [comment]
<!--
Hi ,
i tried with 

Provisioning API Version: 1.1.2
Iothub API Version: 1.1.32

my self signed certificates are verified in DPS certificates   still getting below error 

Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
<- [FLOW]* {0,5000,1,2147483647,1,0,1000,0,NULL,false,NULL}
-> [TRANSFER]* {1,0,<01 00 00 00>,0,false,false}
<- [TRANSFER]* {0,0,<F6 94 25 C8 21 E9 A6 4C 81 74 65 A1 2E 22 3F 28>,0,true,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,0,0,true,* {}}
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
-> [TRANSFER]* {1,1,<02 00 00 00>,0,false,false}
<- [TRANSFER]* {0,1,<FB 58 AB 52 5E 47 C7 4D A9 24 89 D0 A9 95 F5 5A>,0,true,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,1,1,true,* {}}
<- [DISPOSITION]* {true,1,NULL,true,* {},NULL}
Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
-> [TRANSFER]* {1,2,<03 00 00 00>,0,false,false}
<- [TRANSFER]* {0,2,<3A 29 1D 24 15 1E 95 4C B0 DE 3D 78 01 E7 30 D5>,0,true,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,2,2,true,* {}}
<- [DISPOSITION]* {true,2,NULL,true,* {},NULL}
Error: Time:Wed Mar 14 14:28:34 2018 File:/home/cpx/Development/New-SDK/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:prov_transport_process_json_reply Line:387 Unsuccessful json encountered: {"operationId":"2.87f7851aaaa18ed1.53c122cf-f188-4171-a7db-7bf89f958cc2","status":"failed","registrationState":{"registrationId":"riot-device-cert","createdDateTimeUtc":"2018-03-14T14:28:31.3898659Z","status":"failed","errorCode":401002,"errorMessage":"CA certificate not found","lastUpdatedDateTimeUtc":"2018-03-14T14:28:31.5532753Z","etag":"\"00006026-0000-0000-0000-5aa9318f0000\""}}
Error: Time:Wed Mar 14 14:28:34 2018 File:/home/cpx/Development/New-SDK/azure-iot-sdk-c/provisioning_client/src/prov_transport_amqp_common.c Func:prov_transport_common_amqp_dowork Line:1155 Unable to process registration reply.
Error: Time:Wed Mar 14 14:28:34 2018 File:/home/cpx/Development/New-SDK/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:454 Failure retrieving data from the provisioning service
Failure encountered on registration!
-> [DETACH]* {1,true}
-> [DETACH]* {0,true}
-> [END]* {}
-> [CLOSE]* {}
registration failed!

**Comment by jebrando** [comment]
Can you please let us know what OS you are using.  Group provisioning does not work on windows due to schannel tls, please use openssl.

**Comment by lakshmisivareddy** [comment]
Hi jebrando, 

i was able to fix the problem , i am using ubuntu 14.04

**Comment by jebrando** [comment]
Thank you @lakshmisivareddy.  Let us know if you have any more questions.

**Comment by jspaith** [comment]
Indeed thanks for followup @lakshmisivareddy.  

If there's anything in our docs or samples that were missing that could have got you going faster, please let us know.
