### ISSUE TITLE
CMake configuration errors with -Duse_installed_depencenceis:BOOL=On

### ISSUE THREAD

**Issue by truschival** [Azure/azure-iot-sdk-c#416]
- **OS and version used:** Debian Stretch, CMake 3.7.2-->

- **SDK version used:**  1.2.0  (master) 76e5700c825e3208b4fe56fc5a8dc015d728efab

# Description of the issue:
Building revision 76e5700c825e3208b4fe56fc5a8dc015d728efab with the flag 
` -Duse_installed_depencenceis:BOOL=On` fails.

## short analysis
provisioning_client/CMakelists.txt tries to use access a non-existent file

# Steps to reproduce
`cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF  -Duse_amqp:BOOL=ON   -Duse_http:BOOL=ON -Duse_mqtt:BOOL=OFF  -Drun_e2e_tests:BOOL=OFF -Drun_unittests:BOOL=OFF -Drun_longhaul_tests:BOOL=OFF -Dskip_samples:BOOL=ON -Dbuild_service_client:BOOL=ON -Dbuild_python:STRING="OFF" -Dbuild_javawrapper:STRING="OFF" -Ddont_use_uploadtoblob:BOOL=ON -Dno_logging:BOOL=OFF -Duse_installed_dependencies:BOOL=ON -Dbuild_as_dynamic:BOOL=ON -Dbuild_network_e2e:BOOL=OFF -Dwip_use_c2d_amqp_methods:BOOL=OFF -Dnuget_e2e_tests:BOOL=OFF -Duse_prov_client:BOOL=ON -Dhsm_custom_lib=/home/me/lib/libx509filecerts.a`

# Console log of the issue:
```
...
-- IoT Client SDK Version = 1.2.0
-- Provisioning SDK Version = 1.2.0
-- iothub architecture: x86_64
CMake Error: File /home/me/platform/firmware/.builds/festo_native_iotgw/azure-iot-sdk/azure-iot-sdk-2018-03-14/provisioning_client/configs/azure_iot_sdksConfig.cmake does not exist.
CMake Error at provisioning_client/CMakeLists.txt:289 (configure_file):
  configure_file Problem configuring file
```

**Comment by jebrando** [comment]
There is an issue in the installing of the provisioning client.  I will see about addressing this and get a fix complete.

**Comment by jebrando** [comment]
@truschival we believe that this should be fixed now in master.  If you have any more issues with this let us know and reopen the issue.

**Comment by tameraw** [comment]
@truschival thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
