### ISSUE TITLE
IotHub throws exception when receive serialized data in Method-Payload

### ISSUE THREAD

**Issue by raycon94** [Azure/azure-iot-sdk-c#417]
- **OS and version used:** <Windows 10> 
- **SDK version used:** <1.1.16>

# Description of the issue:
I want to send data of my data-modell to the iothub when some methods are called from the device-explorer. For that, i serialize the data and put it to the payload of the methodreturn-handle.
Unfortunately the iothub (device-explorer) throws an exception with the Errorcode: 502101 "Payload is not a valid document of type application/json". 

# Code sample exhibiting the issue:

METHODRETURN_HANDLE cMethod(AzureModel_t *Azure)
{
    unsigned char* destination;
    size_t destinationSize;
    METHODRETURN_HANDLE result;

        if(SERIALIZE(&destination, &destinationSize, AzureModelInstance->DataTest) != CODEFIRST_OK)
        {
            strcpy(destination, "error");
        } 
        result = MethodReturn_Create(200, (const char*)destination);
 }

**Comment by ewertons** [comment]
Hi @raycon94 ,
as we understand you are experiencing an issue on the [DeviceExplorer](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer), not [azure-iot-sdk-c](https://github.com/Azure/azure-iot-sdk-c), correct?

The method return must have a json content there.
You can encapsulate your serialized content as:

{ "data": "some serialized data"}

Could you try that and see if you get past the issue you are experiencing?

**Comment by raycon94** [comment]
Thank you for your answer. I believe that I didn´t use the Serializer correctly.
I want to Serialize following data:




BEGIN_NAMESPACE(AzureModel);


DECLARE_DEVICETWIN_MODEL(AzureDeviceTwin,
WITH_DATA(testStruct, testStructData),
);
END_NAMESPACE(AzureModel);

**Comment by raycon94** [comment]
Thank you for your answer. I believe that I didn´t use the Serializer correctly.
I want to serialize one single struct-data:

SERIALIZE(&destination, &destinationSize, AzureDeviceTwinInstance->testStructData.testValue1);

from the following Data-Model:
BEGIN_NAMESPACE(AzureModel);

DECLARE_STRUCT(testStruct,
int, testValue1,                       
 int, testValue1
);              
       
DECLARE_DEVICETWIN_MODEL(AzureDeviceTwin,
WITH_DATA(testStruct, testStructData),
);
END_NAMESPACE(AzureModel);

As I understand, I cant serialize an single struct-element, is that correct?

**Comment by jspaith** [comment]
Per our discussion in #425, the problem here I believe is using `WITH_DATA` in `DECLARE_DEVICETWIN_MODEL`.  If you want to do your own `SERIALIZE()` call then you should do it in `DECLARE_MODEL` as in simplesample_mqtt.c.

**Comment by jspaith** [comment]
Since it's been a while since this thread has been active, closing it out.  If you have further questions here, as always please reopen this issue or create a new one.  Thanks

**Comment by tameraw** [comment]
@raycon94 thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
