### ISSUE TITLE
CMake configuration errors with -Dbuild_as_dynamic:BOOL=On

### ISSUE THREAD

**Issue by truschival** [Azure/azure-iot-sdk-c#418]
- **OS and version used:** Debian Stretch, CMake 3.7.2

- **SDK version used:**  1.2.0  (master) 76e5700c825e3208b4fe56fc5a8dc015d728efab

# Description of the issue:
Building revision 76e5700c825e3208b4fe56fc5a8dc015d728efab with the flag 
` -Dbuild_as_dynamic:BOOL=On` fails.

## short analysis
`provisioning_service_client/CMakeLists.txt `references `./src/provisioning_service_client.def` which does not exist. 

# Steps to reproduce
`cmake -Dbuild_as_dynamic:BOOL=On -Duse_prov_client:BOOL=ON ../../azure-iot-sdk`

# Console log of the issue:
```
-- IoT Client SDK Version = 1.2.0
-- Provisioning client ON
-- Provisioning SDK Version = 1.2.0
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- iothub architecture: x86_64
-- target architecture: x86_64
-- Configuring done
CMake Error at provisioning_service_client/CMakeLists.txt:60 (add_library):
  Cannot find source file:

    ./src/provisioning_service_client.def

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: provisioning_service_client
CMake Error: Cannot determine link language for target "provisioning_service_client".
-- Generating done
```

**Comment by jebrando** [comment]
This has been fix in the repo.  Thank you.
