### ISSUE TITLE
Cross compilation - Build error

### ISSUE THREAD

**Issue by narendranaren14** [Azure/azure-iot-sdk-c#421]
Hi,

I am running Ubuntu 64-bit operating system. I followed the steps to set up linux development environment provided in the following link. It worked like a charm.
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md?utf8=%E2%9C%93#linux
Next, I wanted to step cross compilation environment in ubuntu system for Raspberry pi. I followed the steps provided in the link below.
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md

I reached the step of Building the SDK in the above. Running the command ./build.sh --toolchain-file toolchain-rpi.cmake -cl --sysroot=$RPI_ROOT gives the following error.

sudo ./build.sh --toolchain-file toolchain-rpi.cmake -cl --sysroot=$RPI_ROOT
~/azure-iot-sdk-c/cmake/iotsdk_linux ~/azure-iot-sdk-c/build_all/linux
-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: ~/RPiTools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/../bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: ~/RPiTools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/../bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: ~/RPiTools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-c++
-- Check for working CXX compiler: ~/RPiTools/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IoT Client SDK Version = 1.2.0
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- target architecture: ARM
-- Performing Test CXX_FLAG_CXX11
-- Performing Test CXX_FLAG_CXX11 - Success
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindOpenSSL.cmake:370 (find_package_handle_standard_args)
  c-utility/CMakeLists.txt:150 (find_package)

-- Configuring incomplete, errors occurred!
See also "~/azure-iot-sdk-c/cmake/iotsdk_linux/CMakeFiles/CMakeOutput.log".
See also "~/azure-iot-sdk-c/cmake/iotsdk_linux/CMakeFiles/CMakeError.log".

I have installed latest openssl package. I see the header files for the package in /usr/local/include/openssl, library in /usr/local/lib/libssl.a and openssl in /usr/local/bin/openssl.

Why is that CMake is not able to find the OpenSSL eventhough package is installed? Please suggest a solution to fix the problem.

**Comment by lakshmisivareddy** [comment]
Hi narendranaren14 ,
use the fallowing curl & openssl versions 
curl 7.52.1 libcurl/7.52.1 OpenSSL/1.0.2j
and export your tool chain path to build script location-->(azure-iot-sdk-c/build_all/linux)

**Comment by narendranaren14** [comment]
Hi lakshmisivareddy,

Thanks for the response. I updated the curl and libcurl to version 7.52.1 as suggested. It letting me install only Openssl/1.0.2n verion instead of j. I still get the error, it appears cmake is unable to find the openssl.

Regards
Narendra

**Comment by lakshmisivareddy** [comment]
Hi ,
openssl > 1.0.2j will work...
have you exported the tool chain path(which contains all library path) to the location (azure-iot-sdk-c/build_all/linux)

**Comment by JetstreamRoySprowl** [comment]
The CMake complaint is saying that you need to export OPENSSL_ROOT_DIR, OPENSSL_LIBRARIES, and OPENSSL_INCLUDE_DIR so that CMake can find them when it runs. We have several kinds of systems where installing OpenSSL does not set these and it has to be done manually.

On my Windows box I have to provide these:
set OpenSSLDir=C:\OpenSSL-1.0.1
set OPENSSL_CONF=C:\OpenSSL-1.0.1
set OPENSSL_ROOT_DIR=C:\OpenSSL-1.0.1

**Comment by markrad** [comment]
> _I have installed latest openssl package. I see the header files for the package in /usr/local/include/openssl, library in /usr/local/lib/libssl.a and openssl in /usr/local/bin/openssl._

You have referring to the version of openssl on your host system. This is not going to be of use to your cross compile. You need to have openssl installed in your **cross compile** environment. If you followed the document you referenced and copied the required files from your Raspberry Pi then make sure that the openssl developer package was installed on your Raspberry Pi before you did that. Do you see libssl.so and libcrypto.so in your cross compile tool chain?

**Comment by narendranaren14** [comment]
Thanks All! @markrad, you are right. I did figure out eventually and installed Openssl on pi and transferred the files. Now it works, thanks for the response.

**Comment by jspaith** [comment]
First big thanks to @markrad for helping out here!

@markrad, @narendranaren14, do we think we can make the doc clearer here?  I'm happy to fix it but I need guidance RE best way since I haven't tried this myself.

It looks like in [cross-compile](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md),  I'm thinking we could add a note after " At this point you will need to copy some files from a running Raspberry Pi to your host machine." that says "Your Raspberry Pi needs openssl and development libraries.  To get them, on your Rasberry Pi itself run:"

```
sudo apt-get install openssl libssl-dev
```

Does this solve the problem or are there additional/missing steps?

**Comment by jspaith** [comment]
Thanks for your very prompt response.  We're going to have a big docs push shortly so we'll take care of fixing this then, if not sooner as this is pretty straightforward.

**Comment by markrad** [comment]
It's probably worth making a note that the Raspberry Pi needs to have all of the SDK prerequisites installed before copying the files to the tool chain on the host.

**Comment by massand** [comment]
We have added some documentation related to this topic here - https://github.com/Azure/azure-iot-sdk-c/pull/608

Let us know if there are any other gaps. Thanks!

**Comment by az-iot-builder-01** [comment]
@lakshmisivareddy, @narendranaren14, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by hamburml** [comment]
Could someone provide the files which are needed to cross-compile for a raspberry pi?

**Comment by jspaith** [comment]
@hamburml  - could you please open a new GitHub issue for this & reference this one in new issue?  We don't really track closed items so I'm worried this is going to get lost.  Thanks
