### ISSUE TITLE
simplesample_mqtt.c stuck in a loop

### ISSUE THREAD

**Issue by handcyclist** [Azure/azure-iot-sdk-c#423]
This sample appears to get stuck somewhere while in the loop
							while (1)
							{
								IoTHubClient_LL_DoWork(iotHubClientHandle);
								ThreadAPI_Sleep(100);
							}
It just produces (1) message and hangs
It does the same on Windows 10 using Visual Studio 2017 as it does in Ubuntu 14.04

**Comment by jebrando** [comment]
Yes, this is due to this sample is just showing how to use the sdk.  We are in the middle of reworking the samples to just show the basics.  In the next week we will have a new sample for this.
