### ISSUE TITLE
No project managers monitoring issues .../Azure-Samples/iot-hub-c-raspberrypi-client-app

### ISSUE THREAD

**Issue by handcyclist** [Azure/azure-iot-sdk-c#424]
The latest version of azure-iot-sdk-c does not work for the sample in

https://github.com/Azure-Samples/iot-hub-c-raspberrypi-client-app

It produces an JSON error and does not build the "app"

There are 3 issues open, the oldest is 13 days old, and there are no responses.

I suggest that if a project is not to be supported by the Azure team, maybe it should not be listed in the Azure supported samples section
Txs

**Comment by jspaith** [comment]
@handcyclist  - the SDK team doesn't own this repo, but I've reached out to the owners and let them know about these untracked problems.  They should be getting back to you in the next few days.

I'm closing this out for now, but if don't get traction by say next week please let me know and I'll reach out to them again.

Thanks

**Comment by handcyclist** [comment]
Thank you
