### ISSUE TITLE
Serializing Reportet-Properties together with "normal"-Properties

### ISSUE THREAD

**Issue by raycon94** [Azure/azure-iot-sdk-c#425]
Hello,

i want to send a Message to the IotHub that contains some serialized data of my devicetwin-model. The data i want to send consists of one reported-propertie (declared with the WITH_REPORTED_PROPERTY-macro) and some other data (declared with the WITH_DATA macro). However, when i try to serialize the data, the serializer Fails. Is there any way to serialize the reported properties together with "normal" properties? Thank you for your answer.

**Comment by JetstreamRoySprowl** [comment]
@raycon94 Can you give us the code that you're working with plus log output showing the failure?

**Comment by raycon94** [comment]
@JetstreamRoySprowl sorry, i forgot to add some information:

- **OS and version used:** <Windows 10> 
- **SDK version used:** <1.1.16>

# Code sample exhibiting the issue: 

DECLARE_DEVICETWIN_MODEL(Azure,
WITH_REPORTED_PROPERTY(int, testRepProp),
WITH_DATA(int, testData)
);

static Azure_t *AzureInstance; 

SERIALIZE(pSerializedData, pSerializedDataSize, AzureInstance->testRepProp, AzureInstance->testData);


LOG: (CODEFIRST = INVALID_ARG)

# Note
I believe that the serializer fails because the "Codefirst_SendAsync"-function calls the "FindValue"-function which searches only normal properties, hence the reported-property will not be found.

**Comment by jspaith** [comment]
Can you help me understand why you want to mix the WITH_DATA in your twin?  Twins have two types of data - WITH_REPORTED_PROPERTY (that the device itself generates) and WITH_DESIRED_PROPERTY (that service sets that it wants device to have).  This is reflected in underlying JSON itself.

The WITH_DATA in my experience is used not on DECLARE_DEVICETWIN_MODEL, but instead with DECLARE_MODEL.  This is used to help serialize data when sending to telemetry messages or receiving device methods but NOT twin related.

Also you should understand tradeoffs of using the serializer.  We're going to doc this up more formally, but for now my comment in https://github.com/Azure/azure-iot-sdk-c/issues/388 has details.

**Comment by raycon94** [comment]
i don't want to use the WITH_DATA-properties in my device-twin itself but send my reported properties together with the "normal" data as an Event to the hub, hence i need to mix them as one serialized data. 

The documentation of the serializer (serializer_apis.md ) says, that the DECLARE_DEVICETWIN_MODEL implements additional device-twin-features like automatically update the desired-propeties. In my Project I only use the device-twin-model, it contains some WITH_DATA elements too for telemetry messages and everthing works fine, but maybe I misunderstood the purpose of the DECLARE_DEVICETWIN_MODEL.

**Comment by jspaith** [comment]
I'm pretty sure you'll need separate models if you want to hand-serialize data for telemetry and do a twin at same time.  The doc you reference says that "serializer has been enhanced with a layer specially crafted for Device Twin."

If you look at IoTHubDeviceTwinCreate_Impl [DECLARE_DEVICETWIN_MODEL](https://github.com/Azure/azure-iot-sdk-c/blob/8ba33b240e31f0be0be3614af512962488b24f4e/serializer/inc/serializer_devicetwin.h#L434) implementation this is very tightly coupled to `IoTHubDeviceTwinCreate_Impl`, and twins only know about reported & desired properties.

```c
    DECLARE_MODEL(name, __VA_ARGS__)           \
    static name* C2(IoTHubDeviceTwin_Create, name)(IOTHUB_CLIENT_HANDLE iotHubClientHandle)                                                                                         \
    {                                                                                                                                                                               \
        SERIALIZER_DEVICETWIN_PROTOHANDLE protoHandle;                                                                                                                              \
        protoHandle.iothubClientHandleVariant.iothubClientHandleType = IOTHUB_CLIENT_CONVENIENCE_HANDLE_TYPE;                                                                       \
        protoHandle.iothubClientHandleVariant.iothubClientHandleValue.iothubClientHandle = iotHubClientHandle;                                                                      \
        return (name*)IoTHubDeviceTwinCreate_Impl(#name, sizeof(name), &protoHandle);                                                                                               \
    }                                                                                                                                                                               \
```

**Comment by jspaith** [comment]
Since it's been a while since this thread has been active, closing it out. If you have further questions here, as always please reopen this issue or create a new one. Thanks

**Comment by tameraw** [comment]
@raycon94 thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
