### ISSUE TITLE
Use Warning instead of Error when  MULTITREE_CHILD_NOT_FOUND in azure-iot-sdk-c/serializer/src/multitree.c

### ISSUE THREAD

**Issue by SLdragon** [Azure/azure-iot-sdk-c#426]
Hi, team,
When I use the function below in [multitree.c](https://github.com/Azure/azure-iot-sdk-c/blob/a7e59fdfe64f5f4cb6ede89f8b91a82ca8a7dbbf/serializer/src/multitree.c),
`
MultiTree_GetLeafValue(MULTITREE_HANDLE treeHandle, const char* leafPath, const void** destination);
`

if the leafPath is not exist, I will always get error logs,

Error: Time:Tue Mar 20 18::55 2018 File: /home/**/serializer/src/multitree.c Func:MultiTree_GetLeafValue Line:727 (result = MULTITREE_CHILD_NOT_FOUND)

I think maybe we should use Warning instead of Error, because we can handle this by using the returned value, and if the Error logs always show up, it would be very confused for other people who use this code.

```
if (MULTITREE_OK == MultiTree_GetLeafValue(child, "interval", &value))
{
       interval = atoi((const char *)value);
}
```

On the other side, are there some other functions I can use to determine whether a child is exist or not without error logs?

Thanks

**Comment by jspaith** [comment]
First @SLdragon can I understand your scenario of using `MultiTree_GetLeafValue` directly?  The multitree stuff as far as I know is an internal construct for the serializer, so we'd expect people to use either serializer directly or else a json parser (e.g. parson).  I don't see MultiTree referenced anywhere in serializer\samples, for instance.

So my 1st suggestion would be checking out parson.  It's already a submodule of the C-SDK (https://github.com/Azure/azure-iot-sdk-c/tree/master/deps) and code will be a bit more portable and the API is designed for wider use, unlike the MultiTree stuff.

Our logger does not have a Warning, and we can't just add one to existing log function without breaking back-compat (customers are creating custom loggers and they'd have no knowledge of a new WARN enum).

**Comment by SLdragon** [comment]
OK, thanks for your information, maybe we can use parson instead.

**Comment by jspaith** [comment]
OK - I'm going to close this out.  If you have other questions on this or any other topic, reactivate this or open a new issue.  Thanks

**Comment by tameraw** [comment]
@SLdragon thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
