### ISSUE TITLE
Parson library references missing from Ubuntu azure-iot-sdk-c release 2018-03-20

### ISSUE THREAD

**Issue by hhirvonen** [Azure/azure-iot-sdk-c#429]
Hi,

Ubuntu azure-iot-sdk-c packet 2018-03-20 build is not working properly. There is missing Parson library references on installation package. Previous build worked ok, but after upgrading latest changes (2018-03-20) with apt-get upgrade, codes are not compiled anymore.  
 
/usr/lib/libiothub_client_amqp_ws_transport.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x164f): undefined reference to `json_parse_string'
/usr/lib/libiothub_client_amqp_ws_transport.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x1667): undefined reference to `json_value_get_object'
/usr/lib/libiothub_client_amqp_ws_transport.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x1682): undefined reference to `json_object_get_string'
/usr/lib/libiothub_client_amqp_ws_transport.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x16ea): undefined reference to `json_value_free'
/usr/lib/libiothub_client_amqp_ws_transport.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x17e8): undefined reference to `json_object_get_string'
/usr/lib/libiothub_client_amqp_ws_transport.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x1805): undefined reference to `json_object_get_string'
/usr/lib/libiothub_client_amqp_ws_transport.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x1822): undefined reference to `json_object_get_string'
/usr/lib/libiothub_client_amqp_ws_transport.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x183f): undefined reference to `json_object_get_string'

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

br Hannu

**Comment by jebrando** [comment]
@hhirvonen We are seeing this error and will work to fix it.  I shall keep you up to date on our progress.

**Comment by jebrando** [comment]
@hhirvonen We have updated our sample to handle the new library that is need. [ See here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/linux/CMakeLists.txt).  You will need to link against parson library.

Thank you for the issue.

**Comment by jebrando** [comment]
@hhirvonen We updated the sample to included the parson library.  Please look at the telemetry sample [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/linux/CMakeLists.txt)

Thanks for the issue.

**Comment by tameraw** [comment]
@hhirvonen thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
