### ISSUE TITLE
MQTT - M2M?

### ISSUE THREAD

**Issue by vpopescu** [Azure/azure-iot-sdk-c#43]
I am trying to accomplish M2M communication, simulating a server using IOT Hub to contact clients. Is this possible?

I'm seeing the following behaviour:

Start listener:

1484894290:0469] NOTICE: Initial logging level 7
[1484894290:0471] NOTICE: Libwebsockets version: 1.6.3 1e9c1a5
[1484894290:0471] NOTICE: IPV6 not compiled in
[1484894290:0471] NOTICE: libev support not compiled in
[1484894290:0471] NOTICE:  ctx mem: 135784 bytes
[1484894290:0472] NOTICE:  canonical_hostname = yxc
[1484894290:0472] NOTICE:  per-conn mem: 256 + 2126 headers + protocol rx buf
-> 00:38:10 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: xxxxx.azure-devices.net/icicle0/api-version=2016-11-14&DeviceClientType=iothubclient%2F1.1.4 | PWD: XXXX | CLEAN: 0
<- 00:38:10 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
-> 00:38:10 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/icicle0/messages/devicebound/# | QOS: 1
<- 00:38:11 SUBACK | PACKET_ID: 2 | RETURN_CODE: 1
-> 00:42:01 PINGREQ
<- 00:42:01 PINGRESP
-> 00:45:52 PINGREQ
<- 00:45:52 PINGRESP
-> 00:49:43 PINGREQ
<- 00:49:43 PINGRESP
-> 00:53:34 PINGREQ
<- 00:53:34 PINGRESP

Then send:

Sender:

Client icicle1 sending CONNECT
Client icicle1 received CONNACK
Client icicle1 sending PUBLISH (d0, q0, r0, m1, 'devices/icicle0/events/', ... (14 bytes))
Client icicle1 sending DISCONNECT

Why is my message not arriving at the subscriber? What should I check? AFAIk the topics look correct. I am listening using the sample in the SDK (MQTT over websockets) and sending using mosquitto_pub. Do I have some work to do on the portal side?

Also as a side question, where is the documentation for subscribing to a specific topic (e.g. .../messages/devicebound/this/specific/topic/#) ?

**Comment by olivierbloch** [comment]
Hi @vpopescu 
Azure IoT Hub doesn't allow to do a direct M2M communication for security reasons. The MQTT support in IoT Hub doesn't include the usual MQTT broker and you will need to implement an architecture that does a D2C, then some back-end job that gets the message from the device and sends it back (through IoT Hub) to the device you want to send it to.
There is an example of this using an Azure Function here: http://aka.ms/azureiotping

**Comment by vpopescu** [comment]
Thanks. I found that the hard way, and got it to work as you described. Appreciate the confirmation though.
