### ISSUE TITLE
on_amqp_send_complete_callback masks result and reason

### ISSUE THREAD

**Issue by seank-com** [Azure/azure-iot-sdk-c#431]
Found porting to TI-RTOS based CC3220SF LAUNCHXL

Discovered on tags/2018-03-02 but it is also in master

# Description of the issue:
[on_amqp_send_complete_callback](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_amqp_twin_messenger.c#L902) in iothubtransport_amqp_twin_messenger.c always calls on_report_state_complete_callback with TWIN_REPORT_STATE_RESULT_ERROR and TWIN_REPORT_STATE_REASON regardless of the results from get_twin_messenger_result_from and get_twin_messenger_reason_from. This appears to violate the requirement just a few lines above

```C
// Codes_IOTHUBTRANSPORT_AMQP_TWIN_MESSENGER_09_095: [If operation is a reported state PATCH, if a failure occurs `on_report_state_complete_callback` shall be invoked with TWIN_REPORT_STATE_RESULT_ERROR, status code from the AMQP response and the saved context]  
```

**Comment by jebrando** [comment]
@seank-com This is by design, the state is coming from the uamqp protocol and should not be sent back up to the upper layer.  The requirement is stale and should state that the reason will be none here.  I have informed the team on this and we'll update the requirement at the next update.

Thank you for the issue.

**Comment by tameraw** [comment]
@seank-com thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
