### ISSUE TITLE
add_link_properties ignores failures and always returns success

### ISSUE THREAD

**Issue by seank-com** [Azure/azure-iot-sdk-c#432]
Found porting to TI-RTOS based CC3220SF LAUNCHXL

Discovered on tags/2018-03-02 but it is also in master

# Description of the issue:

[add_link_properties](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/src/prov_transport_amqp_common.c#L489) in prov_transport_amqp_common.c always returns success regardless of any failure. This, I think, is a bug because there is now dead error handling code in the [two](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/src/prov_transport_amqp_common.c#L527) [places](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/src/prov_transport_amqp_common.c#L605) it is called.

**Comment by jebrando** [comment]
Good catch.  I will fix this today.  Thank you for the issue.

**Comment by jebrando** [comment]
The fix had been added to the repo.

**Comment by tameraw** [comment]
@seank-com thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
