### ISSUE TITLE
Device Provisioning with x509 Group Enrollment 

### ISSUE THREAD

**Issue by lakshmisivareddy** [Azure/azure-iot-sdk-c#437]
Hi 
i am using 1.1.32 version 

i have question regarding Device Provisioning with x509  Group Enrollment 
in Group Enrollment using (CA or Intermediate) is it  mandatory  to upload the root CA certificate in Certificates & verify it ?

when i am tried without  uploading  the root-CA certificate in Certificates i am getting below error,
 when i am uploaded root -CA  & verified , without any problem  device was provisioned .

"i want to know like uploading  the root-CA certificate in Certificates & verify is  mandatory or not ?"

ansport_process_json_reply Line:387 Unsuccessful json encountered: {"operationId":"2.36e237c8db462f45.5977b369-ae65-413d-8c90-771c27c2ba65","status":"failed","registrationState":{"registrationId":"mydevice","createdDateTimeUtc":"2018-03-29T06:12:46.9462581Z","status":"failed","errorCode":401002,"errorMessage":"Invalid certificate","lastUpdatedDateTimeUtc":"2018-03-29T06:12:47.0558811Z","etag":"\"3300514a-0000-0000-0000-5abc83df0000\""}}

Regards
lakshmisivareddy.challa

**Comment by jebrando** [comment]
@lakshmisivareddy What OS are you using?  Group enrollment does not currently work using Windows Schannel due to it not sending the certificate chain on the TLS stream.  If you are using Windows you must use OpenSSL to send the full chain to be validated by the service.

**Comment by lakshmisivareddy** [comment]
Hi @jebrando  thanks for response 
i am using linux device only

**Comment by jebrando** [comment]
You must upload the full chain excluding the root certificate.  For example, you have a root CA cert which creates an intermediate Certificate which creates a leaf certificate.  Then the tls stream will need to contain the Intermediate Cert and the Leaf Cert.

Let me know if that is the answer you need.

**Comment by lakshmisivareddy** [comment]
@jebrando  Thanks for the support

**Comment by jspaith** [comment]
@lakshmisivareddy - thanks for letting us know.  Changing this to area-docs so we can clarify this.
