### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by darzu** [Azure/azure-iot-sdk-c#44]
In the README.md, these links are broken:
- https://aka.ms/howtocreateazureiothub
- https://aka.ms/manageiothub

They lead to a github 404 page.

Me: Chrome 55, Windows 10

**Comment by olivierbloch** [comment]
Hi @darzu 
Thanks for the heads up. I just fixed the 2 aka links.
Let me know if you still see issues
Thanks
