### ISSUE TITLE
x509 certificate revocation in Azure IoT Hub 

### ISSUE THREAD

**Issue by lakshmisivareddy** [Azure/azure-iot-sdk-c#440]
Hi ,

i have a question regarding x509 certificate revocation in IoT hub ,
Example:
if a device provisioned  with dps using x509 to IoT Hub. After certain  period of time device certificate about to expire  or got expired 
how can i revoke the device certificate without  again provisioning the device to IoT hub 

Regards
lakshmisivareddy.challa

**Comment by jebrando** [comment]
You will have to disable the device in the IoThub, currently dps does not support the revocation of a device certificate.

**Comment by lakshmisivareddy** [comment]
Hi @jebrando  thanks for the response

**Comment by yzhong94** [comment]
@lakshmisivareddy , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
