### ISSUE TITLE
documentation: using custom HSM with x509 certs (not TPM)

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#442]
I was trying to use SoftHSM via PKCS11 interface on Ubuntu machine for Azure provisioning. As per custom hsm [readme](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_custom_hsm.md), I created a static library from custom_hsm_example.c([1](https://github.com/Azure/azure-iot-sdk-c/blob/2018-03-16/provisioning_client/adapters/custom_hsm_example.c))  for use with cmake -Dhsm_custom_lib. But the doc is not very clear on what to return from each of 3 key methods to be implemented a) `custom_hsm_get_certificate` b) `custom_hsm_get_alias_key` and c) `custom_hsm_get_common_name`. I assume the below steps needs to be followed.

1. openssl req  -nodes -new -x509  -keyout `private.key` -out `public.cert`
2. Adding public.cert to provisioning portal as in Azure [doc](https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509)
3. custom_hsm_get_certificate should return full content of `public.cert` as char*
4. custom_hsm_get_alias_key should return full content of `private.key` as char*
5. custom_hsm_get_common_name should return the same common used in response the above openssl command

Queries:
1. What is the format of private/public certs? DER, PEM etc ?
2. Are the above 5 steps correct way for using custom HSM library?
3. If yes, I was assuming the point of using an HSM is that your private key never leaves the HSM hardware. If the above steps are correct, the private key (in step 4) is returned in plain text to that azure-iot-sdk-c SDK thereby leaving it vulnerable. What am I missing here? I cannot return a PKCS11 handle to the private key.

<sub>Of lesser importance: I could also put this is as in Azure support ticket. But feels the documentation is nonexisting here and a reply or an updated documentation could help future users. For e.g see that Azure doc on x509 attestation ([doc](https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509)) correctly mentions about uploading public cert to provisioning service portal, but leaves out what to do with the private key part. Something should be done with the private part for provisioning to work. But the doc ignores it.</sub>

**Comment by lakshmisivareddy** [comment]
@kiranpradeep  
the above 5 steps are correct 
i tried like this i wrote wrapper around HSM module which  reads the pkcs file & fetches 
public & private keys & common names  from pkcs and handle to HSM  
it was working fine for me what i  observed was 
in SSL handshake device certificate & private key has to be present

**Comment by jebrando** [comment]
1. @kiranpradeep The format of the certificates usually is PEM format, but if you would like to us a different format you will need to write a custom tlsio layer in shared utility.
2. Yes, the 5 steps are correct
3. If you do not want to have the Private key leave the HSM you will also have to write a tlsio layer that understands how to interprete the key they is returned from the the call of custom_hsm_get_alias_key.  The SDK does not inspect this key and just passes it down to the tlsio to be handled by that layer.  By default the sdk returns the private key as a string, but hsm could return a value of the slot the HSM keeps the private key.  I believe I need to update some documentation to this fact. 

Let me know if you have any more question and be on the lookout for a document update.

**Comment by kiranpradeep** [comment]
@jebrando With the existing APIs, lib users will need to have the private key left open in the file system or wrap (for security) it with an some key already in HSM. The existing APIs as is, doesn't not take full advantage of HSM. 

Normal lib users will find it hard to work at tlsio layer for making the suggested changes.

**Comment by yzhong94** [comment]
@kiranpradeep @lakshmisivareddy , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
