### ISSUE TITLE
custom_hsm_example.c contains syntax errors

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#444]
On master branch, the [custom_hsm_example.c](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/adapters/custom_hsm_example.c) contains below syntax errors. 

1. Multiple definitions of x509_interface and tpm_interface([1](https://github.com/Azure/azure-iot-sdk-c/blob/a89145f6ee6398875dc2541e22cdbde0d07ddfcd/provisioning_client/adapters/custom_hsm_example.c#L249))
2. Semi colon missing at line ([2](https://github.com/Azure/azure-iot-sdk-c/blob/a89145f6ee6398875dc2541e22cdbde0d07ddfcd/provisioning_client/adapters/custom_hsm_example.c#L161))
3. Missing header custom_hsm_abstract.h

**Comment by jebrando** [comment]
Thank you @kiranpradeep I shall update this with the next check.

**Comment by jebrando** [comment]
This file has been removed and replaced with a full sample.  Thanks.

**Comment by yzhong94** [comment]
@kiranpradeep , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
