### ISSUE TITLE
prov_dev_client_ll_sample completes provisioning. But, fails to register with IotHub

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#445]
- **OS and version used:** macOS 10.12.3 and Ubuntu 16.04

- **SDK version used:** 2018-04-02 release

# Description of the issue:
1. Create public/private key pair.
2. Built custom hsm static library (named libhsm.a) out of custom_hsm_examples.c (update methods custom_hsm_get_certificate, custom_hsm_get_alias_key and custom_hsm_get_common_name)
3. cmake -Duse_prov_client:BOOL=ON -Dhsm_custom_lib=libhsm.a azure-iot-sdk-c
4. Run prov_dev_client_ll_sample
5. register_device_callback method in prov_dev_client_ll_sample.c gets invoked with correct iothub URL and device ID. Device gets correctly enabled in Azrure IoTHub as well. But registration with iothub fails. IoTHubClient_LL_CreateFromDeviceAuth() API invoked methods in previously built custom hsm library(libhsm.a). 

I like to know if I missed any important step here.

# Code sample exhibiting the issue:
prov_dev_client_ll_sample

# Console log of the issue:
-----------libhsm invokes hsm_client_x509_init
-----------libhsm invokes hsm_client_tpm_init
-----------libhsm invokes hsm_client_x509_init
-----------libhsm invokes hsm_client_tpm_init
Provisioning API Version: 1.2.2
Iothub API Version: 1.2.2
-----------libhsm invokes custom_hsm_create
-----------libhsm invokes custom_hsm_get_common_name
-----------libhsm invokes custom_hsm_get_certificate
-----------libhsm invokes custom_hsm_get_alias_key
Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
PUT /0ne00002116/registrations/xyz/register?api-version=2017-11-15 HTTP/1.1
UserAgent: prov_device_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
Content-Length: 26

len: 26
{ "registrationId":"xyz" }

HTTP Status: 202

Date: Thu, 05 Apr 2018 08:35:45 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Location: https://global.azure-devices-provisioning.net:443/0ne00002116/registrations/xyz/register
x-ms-request-id: d3e65fcb-9db6-4172-a246-033a05a6b586
Strict-Transport-Security: max-age=31536000; includeSubDomains

{"operationId":"2.2a0d6744fb473dc3.892d8d20-baa9-4914-9c7b-2c36916437de","status":"assigning"}

Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
GET /0ne00002116/registrations/xyz/operations/2.2a0d6744fb473dc3.892d8d20-baa9-4914-9c7b-2c36916437de?api-version=2017-11-15 HTTP/1.1
UserAgent: prov_device_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
Content-Length: 0

HTTP Status: 202

Date: Thu, 05 Apr 2018 08:35:45 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Location: https://global.azure-devices-provisioning.net:443/0ne00002116/registrations/xyz/operations/2.2a0d6744fb473dc3.892d8d20-baa9-4914-9c7b-2c36916437de
Retry-After: 3
x-ms-request-id: 1724d272-5a61-4751-9edf-8cb8d2f4d072
Strict-Transport-Security: max-age=31536000; includeSubDomains

{"operationId":"2.2a0d6744fb473dc3.892d8d20-baa9-4914-9c7b-2c36916437de","status":"assigning","registrationState":{"registrationId":"xyz","status":"assigning"}}

Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
GET /0ne00002116/registrations/xyz/operations/2.2a0d6744fb473dc3.892d8d20-baa9-4914-9c7b-2c36916437de?api-version=2017-11-15 HTTP/1.1
UserAgent: prov_device_client/1.0
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Host: global.azure-devices-provisioning.net:443
Content-Length: 0

HTTP Status: 200

Date: Thu, 05 Apr 2018 08:35:47 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
x-ms-request-id: 3db084af-9ea9-462c-9c79-426a84502450
Strict-Transport-Security: max-age=31536000; includeSubDomains

{"operationId":"2.2a0d6744fb473dc3.892d8d20-baa9-4914-9c7b-2c36916437de","status":"assigned","registrationState":{"x509":{"certificateInfo":null,"signingCertificateInfo":null},"registrationId":"xyz","createdDateTimeUtc":"2018-04-05T08:35:45.7681841Z","assignedHub":"xxxxxxxxxxxx.azure-devices.net","deviceId":"E44","status":"assigned","lastUpdatedDateTimeUtc":"2018-04-05T08:35:45.8704255Z","etag":"\u00220000e2a7-0000-0000-0000-5ac5dfe10000\u0022"}}

Registration Information received from service: xxxxxxxxxxxx.azure-devices.net!
-----------libhsm invokes custom_hsm_destroy
-----------libhsm invokes custom_hsm_create
-----------libhsm invokes custom_hsm_get_certificate
-----------libhsm invokes custom_hsm_get_alias_key
Error: Time:Thu Apr  5 14:06:32 2018 File:/Users/779591ardp/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:IoTHubTransport_MQTT_Common_SetOption Line:2739 Cannot set proxy option once the underlying IO is created
Error: Time:Thu Apr  5 14:06:32 2018 File:/Users/779591ardp/azure-iot-sdk-c/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_SetOption Line:1794 underlying transport failed, returned = IOTHUB_CLIENT_ERROR
Sending 1 messages to IoTHub every 2 seconds for 2 messages (Send any message to stop)
Error: Time:Thu Apr  5 14:06:38 2018 File:/Users/779591ardp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:702 Failure: connect failure 61.
Error: Time:Thu Apr  5 14:06:38 2018 File:/Users/779591ardp/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:725 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Apr  5 14:06:38 2018 File:/Users/779591ardp/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1209 Failed opening the underlying I/O.
Error: Time:Thu Apr  5 14:06:38 2018 File:/Users/779591ardp/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:980 Error: io_open failed
Error: Time:Thu Apr  5 14:06:38 2018 File:/Users/779591ardp/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1795 failure connecting to address xxxxxxxxxxxx.azure-devices.net.
Error: Time:Thu Apr  5 14:06:38 2018 File:/Users/779591ardp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:702 Failure: connect failure 61.
Error: Time:Thu Apr  5 14:06:38 2018 File:/Users/779591ardp/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:725 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Apr  5 14:06:38 2018 File:/Users/779591ardp/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1209 Failed opening the underlying I/O.
Error: Time:Thu Apr  5 14:06:38 2018 File:/Users/779591ardp/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:980 Error: io_open failed
Error: Time:Thu Apr  5 14:06:38 2018 File:/Users/779591ardp/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1795 failure connecting to address xxxxxxxxxxxx.azure-devices.net.
-----------libhsm invokes custom_hsm_destroy
-----------libhsm invokes hsm_client_x509_deinit
hsm_client_tpm_deinit
Press any key to continue:

**Comment by jebrando** [comment]
@kiranpradeep The error is the proxy information is being set too late in the process.  Moving the proxy set option above the other SetOptions function should fix the issue.  I will be update the samples for this.

Thanks you.

**Comment by lakshmisivareddy** [comment]
Hi @kiranpradeep
Which version openssl & curl you are using

**Comment by jebrando** [comment]
I restructured the sample to set the proxy information before the certificate information.  This will enable the device to successfully use the proxy.  I will add this to the documentation of the options.

Thanks,
Jelani
