### ISSUE TITLE
Xcode build fails when openssl is enabled

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#447]
- **OS and version used:** mac OS 10.12.3

- **SDK version used:** 2018-04-02 release

# Description of the issue:
On macOS, when openssl is enabled, build in XCode fails. Use below command to enable openssl with command `cmake -Duse_openssl:BOOL=ON  -GXcode azure-iot-sdk-c`

# Code sample exhibiting the issue:
Build fails on projects azureiotsharedutil target first.

**Comment by JetstreamRoySprowl** [comment]
Without seeing the failure it's hard to be sure what's happening, but you'll also need to add `-DOPENSSL_ROOT_DIR:PATH=/usr/local/opt/openssl` or your appropriate path.

**Comment by kiranpradeep** [comment]
@JetstreamRoySprowl This issue is only regarding XCode builds. Command line build are successful. Also I had set OPENSSL_ROOT_DIR earlier.

**Comment by jebrando** [comment]
@kiranpradeep I have found the error and I will have an update in a day or so.

**Comment by kiranpradeep** [comment]
@jebrando I am not sure why is this closed. Fixed or Will not fix? Usually commit ids which fixes the issue is referred in issue closure message. That helps easier reference and review.
