### ISSUE TITLE
Transport Attempt Retry is hardcoded, but should be customizable

### ISSUE THREAD

**Issue by cedricmelancon** [Azure/azure-iot-sdk-c#448]
- **OS and version used:** Windows 10 and Linux 

- **SDK version used:** 2018-03-02 

# Description of the issue:

There is a retry policy feature for the re-connection mechanism, but the transport attempt retry is hardcoded to 5. In the case of a wrong credential by example, the message will be sent 5 times always with the same wrong credentials. It generates useless communication which has a cost.

A retry policy principle should also be applied for the transport attempt retry or at least, a way to change the number of attempts should be available especially for the DEVICE_STATE_ERROR_AUTH.

# Code sample exhibiting the issue:

In iothubtransport_amqp_common.c, the following line shows the problem:

if (registered_device->number_of_previous_failures >= MAX_NUMBER_OF_DEVICE_FAILURES)

MAX_NUMBER_OF_DEVICE_FAILURES is set to 5.

https://github.com/climbeault/azure-iothub-sdkc-retry-policy-example

# Console log of the issue:

Starting the IoTHub client sample AMQP...
IoTHubClient_SetMessageCallback...successful.
IoTHubClient_SendEventAsync accepted data for transmission to IoT Hub.
-> Header (AMQP 0.1.0.0)
<- Header (AMQP 0.1.0.0)
-> [OPEN]* ...
<- [OPEN]* ...
-> [BEGIN]* {NULL,0,4294967295,100,4294967295}
<- [BEGIN]* {0,1,5000,4294967295,262143,NULL,NULL,NULL}
-> [ATTACH]* {$cbs-sender,0,false,0,0,* {$cbs},* {$cbs},NULL,NULL,0,0}
-> [ATTACH]* {$cbs-receiver,1,true,0,0,* {$cbs},* {$cbs},NULL,NULL,NULL,0}
<- [ATTACH]* {$cbs-sender,0,true,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,NULL}
<- [FLOW]* {0,5000,1,4294967295,0,0,100,0,NULL,false,NULL}
-> [TRANSFER]* {0,0,<01 00 00 00>,0,false,false}
<- [ATTACH]* {$cbs-receiver,1,false,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,1048576,NULL,NULL,NULL}
-> [FLOW]* {1,4294967295,1,99,1,0,10000}
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
<- [TRANSFER]* {1,0,<01 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
Error: Time:Tue Mar 13 22:48:42 2018 File:V:\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_cbs_auth.c Func:_on_cbs_put_token_complete_callback Line:168 CBS reported status code 401, error: 'The specified SAS token has an invalid signature. It does not match either the primary or secondary key.' for put-token operation for device '...'
-> [DISPOSITION]* {true,0,0,true,* {}}
Connection status with result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED and reason = IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL
Error: Time:Tue Mar 13 22:48:42 2018 File:V:\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:1132 Failed performing DoWork for device '...' (device reported state 4; number of previous failures: 0)
Connection status with result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED and reason = IOTHUB_CLIENT_CONNECTION_OK
-> [TRANSFER]* {0,1,<02 00 00 00>,0,false,false}
<- [DISPOSITION]* {true,1,NULL,true,* {},NULL}
<- [TRANSFER]* {1,1,<02 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
Error: Time:Tue Mar 13 22:48:42 2018 File:V:\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_cbs_auth.c Func:_on_cbs_put_token_complete_callback Line:168 CBS reported status code 401, error: 'The specified SAS token has an invalid signature. It does not match either the primary or secondary key.' for put-token operation for device '...'
-> [DISPOSITION]* {true,1,1,true,* {}}
Connection status with result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED and reason = IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL
Error: Time:Tue Mar 13 22:48:42 2018 File:V:\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:1132 Failed performing DoWork for device '...' (device reported state 4; number of previous failures: 1)
Connection status with result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED and reason = IOTHUB_CLIENT_CONNECTION_OK
-> [TRANSFER]* {0,2,<03 00 00 00>,0,false,false}
<- [DISPOSITION]* {true,2,NULL,true,* {},NULL}
<- [TRANSFER]* {1,2,<03 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
Error: Time:Tue Mar 13 22:48:42 2018 File:V:\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_cbs_auth.c Func:_on_cbs_put_token_complete_callback Line:168 CBS reported status code 401, error: 'The specified SAS token has an invalid signature. It does not match either the primary or secondary key.' for put-token operation for device '...'
-> [DISPOSITION]* {true,2,2,true,* {}}
Connection status with result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED and reason = IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL
Error: Time:Tue Mar 13 22:48:42 2018 File:V:\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:1132 Failed performing DoWork for device '...' (device reported state 4; number of previous failures: 2)
Connection status with result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED and reason = IOTHUB_CLIENT_CONNECTION_OK
-> [TRANSFER]* {0,3,<04 00 00 00>,0,false,false}
<- [DISPOSITION]* {true,3,NULL,true,* {},NULL}
<- [TRANSFER]* {1,3,<04 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
Error: Time:Tue Mar 13 22:48:42 2018 File:V:\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_cbs_auth.c Func:_on_cbs_put_token_complete_callback Line:168 CBS reported status code 401, error: 'The specified SAS token has an invalid signature. It does not match either the primary or secondary key.' for put-token operation for device '...'
-> [DISPOSITION]* {true,3,3,true,* {}}
Connection status with result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED and reason = IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL
Error: Time:Tue Mar 13 22:48:42 2018 File:V:\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:1132 Failed performing DoWork for device '...' (device reported state 4; number of previous failures: 3)
Connection status with result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED and reason = IOTHUB_CLIENT_CONNECTION_OK
-> [TRANSFER]* {0,4,<05 00 00 00>,0,false,false}
<- [DISPOSITION]* {true,4,NULL,true,* {},NULL}
<- [TRANSFER]* {1,4,<05 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
Error: Time:Tue Mar 13 22:48:42 2018 File:V:\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_cbs_auth.c Func:_on_cbs_put_token_complete_callback Line:168 CBS reported status code 401, error: 'The specified SAS token has an invalid signature. It does not match either the primary or secondary key.' for put-token operation for device '...'
-> [DISPOSITION]* {true,4,4,true,* {}}
Connection status with result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED and reason = IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL
Error: Time:Tue Mar 13 22:48:42 2018 File:V:\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_Device_DoWork Line:1132 Failed performing DoWork for device '...' (device reported state 4; number of previous failures: 4)
Error: Time:Tue Mar 13 22:48:42 2018 File:V:\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:_IoTHubTransport_AMQP_Common_DoWork Line:1611 Device '...' reported a critical failure; connection retry will be triggered.
Connection status with result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED and reason = IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED

**Comment by Shakti213** [comment]
With version 2017-12-14 (I know very old one but has worked wonderful for us so far) this issue is even more pressing when used in a field gateway or the likes, where a single transport is used for multiple clients. In that case a single wrong credential will cause all clients connected to the transport to be disconnected, even the correct ones, and will have to be reconnected. Then you enter a loop of connect and disconnect for all clients associated with the transport.

This causes the data cost to rise very quickly. A per-client backoff or reconnect policy is very preferrable since it then is possible to minimize the impact of a single bad credential with regards to all working clients.

**Comment by tameraw** [comment]
@cedricmelancon & @Shakti213 - This is currently in our backlog but has not bubbled up in priority yet. If interested in submitting a PR, we'd be happy to review. Thanks.

**Comment by AndWass** [comment]
@jspaith Thanks for the comment.

I have considered IoT Edge but as you suspected, the targetted hardware is constrained and runs in a sandboxed environment which means that docker etc. is out of the question.

**Comment by gregman-msft** [comment]
Thanks for the feedback. This is currently in our backlog but do not have an ETA for this yet. Please vote on this [User voice ](https://feedback.azure.com/forums/321918-azure-iot/suggestions/38869930-customizable-transport-attempt-retry-in-c-sdk) item, which can also be used for tracking our plans. The link may take some time to be published, try again in a few hours if it does not work at first.

**Comment by az-iot-builder-01** [comment]
@cedricmelancon, @AndWass, @jspaith, @gregman-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
