### ISSUE TITLE
Need to override libwebsockets.a proxy detection (linux)

### ISSUE THREAD

**Issue by vpopescu** [Azure/azure-iot-sdk-c#45]
Apparently libwebsockets.a expects an environment variable "http_proxy" set to "hostname:port".
Ref: https://libwebsockets.org/lws-api-doc-master/html/md_README_8test-apps.html

On every linux distribution I've seen, http_proxy is set to "http://hostname:port".  
Ref: https://wiki.archlinux.org/index.php/proxy_settings

This breaks libwebsockets.a and consequently the azure-iot-sdk for C, when trying to use WS over proxy. At the very least it should be documented, but ideally the SDK would override libsockets' handling via lws_set_proxy(), until the websockets library developers fix it.

At least, this is the behavior I'm seeing while using MQTT over WS.

**Comment by dcristoloveanu** [comment]
Hi @vpopescu 

It is unfortunate that libwebsockets uses a different format for the HTTP proxy settings than archlinux. I would suggest filing this issue with libwebsockets.

As a workaround, the Azure IoT SDK does have a proxy option that gets passed down to libwebsockets (not through lws_set_proxy, but as part of lws_context_creation_info). The option is named "proxy_data" and the value is a pointer to a structure of type HTTP_PROXY_OPTIONS. This can be achieved with the API IoTHubClient_SetOption (or the _LL equivalent IoTHubClient_LL_SetOption if you are using the _LL APIs).

Hope this helps,
/Dan

**Comment by vpopescu** [comment]
I can certainly file it with libwebsockets.a if it's not already there, but.. it would be nice if you considered fixing it in your product in case the libwebsockets.a guys take their time fixing it. It's a fairly odd bug for them to have inserted into your product.

**Comment by vpopescu** [comment]
FYI, the great team at libwebsockets.a committed a fix for the proxy issue:

https://github.com/warmcat/libwebsockets/issues/764

How will it make its way into the product?

**Comment by dcristoloveanu** [comment]
Hi @vpopescu,

I am looking at picking up the latest master of libwesockets which includes the above commit.
I'll let you know once this made it to master.

Thanks,
/Dan

**Comment by dcristoloveanu** [comment]
@vpopescu 

A change has been checked in to the master branch that picks up the libwebsockets fix.
This should fix the reported issue, let us know if it does not.

Thanks,
/Dan
