### ISSUE TITLE
Let provisioning client with hsm_custom_lib option build on macOS

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#455]
- **OS and version used:** macOS 10.12.3
- **SDK version used:** 2018-04-02

# Description of the issue:
Currently provisioning client cannot be built on macOS for a check in CMakeLists.txt. But, when using `cmake -Dhsm_custom_lib=hsm.a` option, there is nothing that is preventing an macOS/Xcode build. Can this check in CMakeLists.txt([1](https://github.com/Azure/azure-iot-sdk-c/blob/master/CMakeLists.txt#L79)) be disabled, when built with hsm_custom_lib flag?

**Comment by jebrando** [comment]
I can remove this from IOS until we add the feature to ios.

**Comment by jebrando** [comment]
This has been disable and we shall evaluate when we will enable dps for Mac.  If you have any more issue please reopen or open a new issue.
