### ISSUE TITLE
Provisioning Client requires optional SocketIO implementation in the PAL layer.

### ISSUE THREAD

**Issue by seank-com** [Azure/azure-iot-sdk-c#456]
Found while trying to port 2018-03-02 on master to the [TI CC3220SF](http://www.ti.com/product/CC3220)

# Description of the issue:

[mqtt_transport_io](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/src/prov_transport_mqtt_client.c#L17) and [amqp_transport_io](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/src/prov_transport_amqp_client.c#L19) both take a ```HTTP_PROXY_OPTIONS*``` as a second parameter. Even if you pass NULL the existence of ```http_proxy_io_get_interface_description``` still needs to link with code implemented by the SocketIO component of the PAL layer. The SocketIO component is optional according to the [porting guide](https://github.com/Azure/azure-c-shared-utility/blob/master/devdoc/porting_guide.md#overview).

# Code sample exhibiting the issue:

We had to work around this with code like the following:
```
#ifndef TI_RTOS
    HTTP_PROXY_IO_CONFIG proxy_config;

    if (proxy_info != NULL)
    {
        /* Codes_PROV_TRANSPORT_MQTT_CLIENT_07_012: [ If proxy_info is not NULL, amqp_transport_io shall construct a HTTP_PROXY_IO_CONFIG object and assign it to TLSIO_CONFIG underlying_io_parameters ] */
        proxy_config.hostname = tls_io_config.hostname;
        proxy_config.port = MQTT_PORT_NUM;
        proxy_config.proxy_hostname = proxy_info->host_address;
        proxy_config.proxy_port = proxy_info->port;
        proxy_config.username = proxy_info->username;
        proxy_config.password = proxy_info->password;

        tls_io_config.underlying_io_interface = http_proxy_io_get_interface_description();
        tls_io_config.underlying_io_parameters = &proxy_config;
    }
#endif
```

# Recommendation

Ideally, the provisioning client would require you pass NULL, otherwise error if the PAL layer did not implement the SocketIO component.

**Comment by jebrando** [comment]
The only time that proxy_info would not be NULL is if the application has called the following API:

Prov_Device_LL_SetOption(handle, OPTION_HTTP_PROXY, &http_proxy)

I'm unable to see where the proxy would be getting set.  is this the case in the application?

**Comment by seank-com** [comment]
Sorry for not being more clear. The PAL layer for the TI CC3220 does not implement the socketio PAL module because it is optional (which is good because there is no easy way to implement it).  Consequently, when you try to compile the provisioning_client, the call to ```http_proxy_io_get_interface_description``` in the code fragment above will generate a link error because the socketio interface is not defined.

**Comment by jebrando** [comment]
Gotcha, ok let me see how I can fix this.  Give me a day or two.

**Comment by seank-com** [comment]
Great! I was thinking if there is a way to determine at compile time if the socketio module is implemented in the PAL layer then #ifdef the code to return an error if you try to call it with a non-null value. I just didn't know the code well enough to put together a PR.

**Comment by BigPeteB** [comment]
This is fixed by adding an HTTP proxy stub implementation that will satisfy the linker, but does nothing and shouldn't be called. This will be available in the next release when the `c-utility` submodule is updated.

**Comment by az-iot-builder-01** [comment]
@seank-com, @BigPeteB, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
