### ISSUE TITLE
Provisioning Client dependency utpm bypasses PAL layer and uses sockets directly.

### ISSUE THREAD

**Issue by seank-com** [Azure/azure-iot-sdk-c#457]
Found while trying to port 2018-03-02 on master to the [TI CC3220SF](http://www.ti.com/product/CC3220)

Thankfully, we ended up implementing our own [custom hsm](https://github.com/seank-com/azure-iot-sdk-tirtos-cc3220/blob/master/source/third_party/azure-iot-sdk-c/provisioning_client/adapters/custom_hsm_tirtos.c) and didn't end up needing either the RIoT or TPM code so this is FYI only, we are not blocked.

# Description of the issue:

TIRTOS does not implement [shutdown](https://github.com/Azure/azure-utpm-c/blob/db5470684de1419bf626d15a51a340f86467b4c8/src/tpm_socket_comm.c#L170) or [inet_addr](https://github.com/Azure/azure-utpm-c/blob/db5470684de1419bf626d15a51a340f86467b4c8/src/tpm_socket_comm.c#L204) in it's socket layer and the official port of the Azure IoT SDK from TI does not implement the SocketIO component because it is optional according to the [porting guide](https://github.com/Azure/azure-c-shared-utility/blob/master/devdoc/porting_guide.md#overview).

# Code sample:

This is the type of code we added to tpm_socket_comm.c to overcome the issue, but the whole module should really just use the PAL layer instead.

```

#ifdef TI_RTOS

int shutdown_unsupported()
{
  return 0;
}
#define shutdown(...) shutdown_unsupported()

u_int32_t inet_addr(const char* str)
{
  u_int32_t a, b, c, d, val;
  sscanf(str, "%d.%d.%d.%d", &a, &b, &c, &d);
  a = (a << 24) & 0xff000000;
  b = (b << 16) & 0xff0000;
  c = (c << 8) & 0xff00;
  d = d & 0xff;
  val = a | b | c | d;
  return htonl(val);
}

#endif

```

# Recommendation

Ideally, the utpm layer would utilize the socketio PAL layer in c-utility (which is already one of its dependencies). Additionally, it would be nice if the utpm gracefully degraded in the absence of a socketio implementation. Or if required, the documentation should be updated to reflect that.

**Comment by jebrando** [comment]
@seank-com Thanks for the issue, I have entered this in our backlog task list to get this done.

**Comment by tameraw** [comment]
@seank-com , thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
