### ISSUE TITLE
Extra characters returned from IoTHubMessage_GetByteArray

### ISSUE THREAD

**Issue by ritazh** [Azure/azure-iot-sdk-c#46]
Using this [sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c), I wanted to get the raw message sent by cloud to the device, but what I got from [IoTHubMessage_GetByteArray](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothub_message.c#L332) is always the original message with some extra characters attached at the end. 

For example:
From iothub-explorer or Device Explorer, you can send a message like `hello3` and this code will return: `hello3�`.

**Comment by anporumb** [comment]
Hello @ritazh 

Can you please attach a minimal repro? Thank you. On a side note, if you are using a byte array, then it will not be null terminated.

Best Regards,
Andrei Porumb

**Comment by ritazh** [comment]
@anporumb I used this [mqtt sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c). To reproduce, output the buffer returned by `IoTHubMessage_GetByteArray` [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c#L43), like this:
```
(void)printf("IoTHubMessage_GetByteArray buffer sample: \"%s\" \n", buffer);
```
you will see the extra characters at the end of the buffer.

**Comment by anporumb** [comment]
Hello @ritazh ,

I beleive the way you are printing the message is wrong. The message is not guaranteed to contain a null terminated string, and that's why you are seeing extraneous characters. The same sample you've pointed you contains the right way of printing the byte array (which is assumed to contain printable characters):

```c
 (void)printf("Received Message [%d] with Data: <<<%.*s>>> & Size=%d\r\n", *counter, (int)size, buffer, (int)size);
```

Let me know if this answer works for you.

Best Regards,
Andrei Porumb

**Comment by ritazh** [comment]
@anporumb You are right that works as intended on Linux. 

But running the same code on a device that is not linux based, it seems the compiler does not like `%.*s` and just returns:
 `Received Message [0] with Data: <<<*s>>> & Size=6`
when sending a message: `hello3`. 

Instead, I'm converting the byte array to a string by appending `'\0'` at the end:
```
static void bytearray_to_str(const unsigned char *buffer, int len)
 {
    char ret[len + 1];
    strncpy(ret, buffer, len);
    ret[len] = '\0';
    printf("%s \n", ret);   
 }
```
WDYT?

**Comment by anporumb** [comment]
Hello @ritazh ,

These are my observations: `len` should be of type `size_t`. Use `memcpy` instead of `strncpy` (for performance reasons, if nothing else). `ret` is a C99 definition type (aka "flexible array", your compile rmight like it or not). Otherwise, looks good to me!

Best Regards,
Andrei Porumb

**Comment by ritazh** [comment]
Thanks @anporumb! Here is my latest based on your feedback:
```
static unsigned char* bytearray_to_str(const unsigned char *buffer, size_t len)
 {
    unsigned char* ret = (unsigned char*)malloc(len+1);
    memcpy(ret, buffer, len);
    ret[len] = '\0';
    //printf("%s \n", ret);  
    return ret; 
 }
```
Do you have any idea why `%.*s` is not working for me?

**Comment by anporumb** [comment]
Hello @ritazh,

The above code looks good to me.

I do not know why `%.*s` does not work for you. %.*s in C means: "maximum number of bytes to be written for s conversion". Personally, I would contact the compiler's support.

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Hello @ritazh ,

As this is not related to an SDK change, we will close this issue.

Best Regards,
Andrei Porumb

**Comment by SummerSun** [comment]
Hi, met the same issue and resolve it the same way suggested above.

@anporumb Though the issue close, I still want to ask, why the message is not null terminated guaranteed? Is there anything we could we do to make sure it nul terminated? Thank you.
