### ISSUE TITLE
Question: Sending device-to-device messages

### ISSUE THREAD

**Issue by VitSolcik** [Azure/azure-iot-sdk-c#461]
Hi,

My goal is to demonstrate communication via IoT hub, that provides device-to-device messaging.

Now I can send device-to-cloud messages and receive cloud-to-device messages.

My question is, which service is needed to process and route message from device A (device-to-cloud msg) to device B (probably cloud-to-device msg).

Do You have any example of this kind of messaging?

Thanks for reply,
Vit.

**Comment by ewertons** [comment]
Hi @VitSolcik ,

You can explore using Azure Functions, but would be expensive.

Your best option would be using the event hub SDK to listen for messages and send them back to your other device.

https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-programming-guide

**Comment by VitSolcik** [comment]
Hi @ewertons ,

Thanks for your reply.

I saw some samples of receiving events on Event HUB with IoT HUB, but could You be more specific about sending them back to other device from Event HUB? I can't find any samples or solution like this.

Regards,
Vit.
