### ISSUE TITLE
Azure IoT hub fails to link after latest upgrade.

### ISSUE THREAD

**Issue by SergiyIvanovAtGTI** [Azure/azure-iot-sdk-c#462]
Hi there. After latest upgrade of iot Hub soft c library i obtained:

/usr/lib/libiothub_client.a(iothub_client_ll.c.o):-1: In function `IoTHubClient_LL_Destroy':
(.text+0x9ba):-1: error: undefined reference to `IoTHubClient_Auth_Destroy'
/usr/lib/libiothub_client.a(iothub_client_ll.c.o):-1: In function `initialize_iothub_client':
(.text+0x1b65):-1: error: undefined reference to `IoTHubClient_Auth_Create'
...

Latest upgrade that creates issue is:
Upgrade: libpam0g:amd64 (1.1.8-3.2ubuntu2, 1.1.8-3.2ubuntu2.1), libpam-modules:amd64 (1.1.8-3.2ubuntu2, 1.1.8-3.2ubuntu2.1), azure-umqtt-c-lib:amd64 (0.2.0.0-2xenial, 0.2.0.0-3xenial), plymouth-label:amd64 (0.9.2-3ubuntu13.3, 0.9.2-3ubuntu13.4), azure-iot-sdk-c-dev:amd64 (0.2.0.0-2xenial, 0.2.0.0-3xenial), plymouth-theme-ubuntu-text:amd64 (0.9.2-3ubuntu13.3, 0.9.2-3ubuntu13.4), libpam-runtime:amd64 (1.1.8-3.2ubuntu2, 1.1.8-3.2ubuntu2.1), ibus-gtk:amd64 (1.5.11-1ubuntu2, 1.5.11-1ubuntu2.1), ibus-gtk3:amd64 (1.5.11-1ubuntu2, 1.5.11-1ubuntu2.1), libplymouth4:amd64 (0.9.2-3ubuntu13.3, 0.9.2-3ubuntu13.4), apport:amd64 (2.20.1-0ubuntu2.15, 2.20.1-0ubuntu2.16), azure-iot-sdk-c-lib:amd64 (0.2.0.0-2xenial, 0.2.0.0-3xenial), python3-apport:amd64 (2.20.1-0ubuntu2.15, 2.20.1-0ubuntu2.16), azure-c-shared-util-dev:amd64 (0.2.0.0-2xenial, 0.2.0.0-3xenial), libpam-modules-bin:amd64 (1.1.8-3.2ubuntu2, 1.1.8-3.2ubuntu2.1), plymouth:amd64 (0.9.2-3ubuntu13.3, 0.9.2-3ubuntu13.4), azure-uamqp-c-dev:amd64 (0.2.0.0-2xenial, 0.2.0.0-3xenial), ibus:amd64 (1.5.11-1ubuntu2, 1.5.11-1ubuntu2.1), apport-gtk:amd64 (2.20.1-0ubuntu2.15, 2.20.1-0ubuntu2.16), libibus-1.0-5:amd64 (1.5.11-1ubuntu2, 1.5.11-1ubuntu2.1), gir1.2-ibus-1.0:amd64 (1.5.11-1ubuntu2, 1.5.11-1ubuntu2.1), azure-c-shared-util-lib:amd64 (0.2.0.0-2xenial, 0.2.0.0-3xenial), plymouth-theme-ubuntu-logo:amd64 (0.9.2-3ubuntu13.3, 0.9.2-3ubuntu13.4), azure-uamqp-c-lib:amd64 (0.2.0.0-2xenial, 0.2.0.0-3xenial), python3-problem-report:amd64 (2.20.1-0ubuntu2.15, 2.20.1-0ubuntu2.16), azure-umqtt-c-dev:amd64 (0.2.0.0-2xenial, 0.2.0.0-3xenial)

System is :
uname -a
Linux ice-vm 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 16.04

**Comment by hhirvonen** [comment]
I have same problem with latest Ubuntu release. Seems that Parson library is missing (again) from latest build:
/usr/lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x166a): undefined reference to `json_parse_string'
/usr/lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x1682): undefined reference to `json_value_get_object'
/usr/lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x169d): undefined reference to `json_object_get_string'
/usr/lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x1705): undefined reference to `json_value_free'
/usr/lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x1803): undefined reference to `json_object_get_string'
/usr/lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x1820): undefined reference to `json_object_get_string'
/usr/lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x183d): undefined reference to `json_object_get_string'
/usr/lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x185a): undefined reference to `json_object_get_string'

**Comment by jebrando** [comment]
@SergiyIvanovAtGTI & @hhirvonen Are you using apt-get or are you cloning the repo?

**Comment by hhirvonen** [comment]
I am using apt-get for installing azure-iot-sdk-c because I need latest stable version in our project. Parson library is now missing from latest (2018-04-16) release. It was missing earlier from 2018-03-20 release and I created an issue #429 which was solved to next build.

**Comment by jebrando** [comment]
We are taking in a PR to fix this error.  We shall get it out to the apt-gets as soon as possible.

**Comment by formulahendry** [comment]
I have tried latest package `Apt-get Xenial: 0.2.0.0-4xenial`, but still meet with below error when running `make`
```
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll.c.o): In function `IoTHubClient_LL_Destroy':
(.text+0x9ba): undefined reference to `IoTHubClient_Auth_Destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll.c.o): In function `initialize_iothub_client':
(.text+0x1b65): undefined reference to `IoTHubClient_Auth_Create'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll.c.o): In function `initialize_iothub_client':
(.text+0x1dbd): undefined reference to `IoTHubClient_Auth_CreateFromDeviceAuth'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll.c.o): In function `initialize_iothub_client':
(.text+0x20c7): undefined reference to `IoTHubClient_Auth_Destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll.c.o): In function `initialize_iothub_client':
(.text+0x2187): undefined reference to `IoTHubClient_Auth_Destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll.c.o): In function `initialize_iothub_client':
(.text+0x2219): undefined reference to `IoTHubClient_Auth_Destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll.c.o): In function `initialize_iothub_client':
(.text+0x22f4): undefined reference to `IoTHubClient_Auth_Destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll.c.o): In function `initialize_iothub_client':
(.text+0x238f): undefined reference to `IoTHubClient_Auth_Destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x166a): undefined reference to `json_parse_string'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x1682): undefined reference to `json_value_get_object'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x169d): undefined reference to `json_object_get_string'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x1705): undefined reference to `json_value_free'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x1803): undefined reference to `json_object_get_string'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x1820): undefined reference to `json_object_get_string'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x183d): undefined reference to `json_object_get_string'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client.a(iothub_client_ll_uploadtoblob.c.o): In function `IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl':
(.text+0x185a): undefined reference to `json_object_get_string'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `free_transport_handle_data':
(.text+0xff): undefined reference to `retry_control_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `mqtt_operation_complete_callback':
(.text+0x470): undefined reference to `retry_control_reset'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `GetTransportProviderIfNecessary.part.6':
(.text+0x16e0): undefined reference to `IoTHubClient_Auth_Get_Credential_Type'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `GetTransportProviderIfNecessary.part.6':
(.text+0x172c): undefined reference to `IoTHubClient_Auth_Set_xio_Certificate'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `IoTHubTransport_MQTT_Common_SetRetryPolicy':
(.text+0x248e): undefined reference to `retry_control_create'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `IoTHubTransport_MQTT_Common_SetRetryPolicy':
(.text+0x24a8): undefined reference to `retry_control_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `IoTHubTransport_MQTT_Common_Create':
(.text+0x2750): undefined reference to `retry_control_create'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `IoTHubTransport_MQTT_Common_DoWork':
(.text+0x3a40): undefined reference to `retry_control_should_retry'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `IoTHubTransport_MQTT_Common_DoWork':
(.text+0x3f0d): undefined reference to `IoTHubClient_Auth_Get_Credential_Type'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `IoTHubTransport_MQTT_Common_DoWork':
(.text+0x433c): undefined reference to `IoTHubClient_Auth_Get_SasToken'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `IoTHubTransport_MQTT_Common_DoWork':
(.text+0x4497): undefined reference to `IoTHubClient_Auth_Is_SasToken_Valid'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `IoTHubTransport_MQTT_Common_DoWork':
(.text+0x454f): undefined reference to `IoTHubClient_Auth_Get_SasToken'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `IoTHubTransport_MQTT_Common_SetOption':
(.text+0x4716): undefined reference to `IoTHubClient_Auth_Get_Credential_Type'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `IoTHubTransport_MQTT_Common_SetOption':
(.text+0x4a12): undefined reference to `IoTHubClient_Auth_Set_x509_Type'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `IoTHubTransport_MQTT_Common_Register':
(.text+0x4d10): undefined reference to `IoTHubClient_Auth_Get_Credential_Type'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libiothub_client_mqtt_transport.a(iothubtransport_mqtt_common.c.o): In function `IoTHubTransport_MQTT_Common_Register':
(.text+0x4dbc): undefined reference to `IoTHubClient_Auth_Get_DeviceKey'
```
@jebrando Does the latest package `Xenial: 0.2.0.0-4xenial` include the fix?

**Comment by jebrando** [comment]
This has been release and it should be fixed.  If you see any more issue please reopen or open a new issue.

**Comment by formulahendry** [comment]
Hi @jebrando , I still meet with this error. I have open a new issue #483 for this,

**Comment by yzhong94** [comment]
@jebrando can you take a look at the issue raised?
