### ISSUE TITLE
Question: Device provisioning multiple devices understanding

### ISSUE THREAD

**Issue by syedelec** [Azure/azure-iot-sdk-c#463]
- **OS and version used:** <VERSION> 
Ubuntu 16.04
- **SDK version used:** <VERSION> 
master

# Description of the issue:

Hi,

I have some questions regarding Device Provisioning Client.

First of all, here are the steps I am currently performing, if there are any ambiguities or incorrect way of doing it, please let me know.

- I created an IoT Hub instance and an IoT Hub DPS instance.

- I linked my IoT Hub with the IoT Hub DPS instance.

- I enrolled 3 devices using self-signed certificate [following this tutorial](https://docs.microsoft.com/en-us/azure/iot-dps/tutorial-provision-device-to-hub#enroll-the-device) :
For that, I used openssl with command (replacing xxx with 1, 2 and 3) :
`openssl req -nodes -x509 -newkey rsa:4096 -keyout key_xxx.pem -out certificate_xxx.pem -subj "/CN=azure-test-xxx"`
According to this [documentation](https://docs.microsoft.com/en-us/azure/iot-dps/concepts-device#registration-id), the registration ID is provided as the subject name of the certificate so in my case "azure-test-xxx". 
I also specified an initial device twin desired property : `version: xxx`

- I want to provision my device using the SDK, for that I modified [this sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/samples/prov_dev_client_ll_sample/prov_dev_client_ll_sample.c)

My problem is that how can I provision only one device using this sample ? for example azure-test-2
How can I select my returned device ID from the callback `Prov_Device_Register_Device`
The only variables I can modify are Scope ID and Global URI.

# Code sample exhibiting the issue:
```
#include <azure_c_shared_utility/platform.h>
#include <azure_c_shared_utility/shared_util_options.h>
#include <azureiot/iothub_client.h>
#include <azureiot/iothub_client_options.h>
#include <azureiot/iothub_message.h>

#include <azure_prov_client/prov_device_client.h>
#include <azure_prov_client/prov_security_factory.h>

#include <stdlib.h>
#include <unistd.h>
#include <stdbool.h>

#include <azureiot/iothubtransportamqp_websockets.h>
#include <azure_prov_client/prov_transport_amqp_ws_client.h>

static PROV_DEVICE_TRANSPORT_PROVIDER_FUNCTION prov_transport = Prov_Device_AMQP_WS_Protocol;

static IOTHUB_CLIENT_TRANSPORT_PROVIDER iothub_transport = AMQP_Protocol_over_WebSocketsTls;

typedef struct prov_ctx
{
    char* iothub_uri;
    char* device_id;
    bool registration_complete;
} prov_ctx;

DEFINE_ENUM_STRINGS(PROV_DEVICE_REG_STATUS, PROV_DEVICE_REG_STATUS_VALUES);

static void registation_status_callback(PROV_DEVICE_REG_STATUS reg_status, void* user_context)
{
    prov_ctx *prov_ctx = user_context;
    prov_ctx->registration_complete = 0;

    switch ( reg_status)
    {
    case PROV_DEVICE_REG_STATUS_CONNECTED:
        printf("\r\nRegistration status: PROV_DEVICE_REG_STATUS_CONNECTED\r\n");
        break;
    default:
        printf("\r\nUnknown registration status\r\n");
        break;
    }
}

static void register_device_callback(PROV_DEVICE_RESULT register_result, const char* iothub_uri, const char* device_id, void* user_context)
{
    prov_ctx *prov_ctx = user_context;

    switch ( register_result)
    {
    case PROV_DEVICE_RESULT_OK:
        prov_ctx->registration_complete = 1;

        size_t len = strlen(iothub_uri) + 1;
        prov_ctx->iothub_uri = malloc(len);
        memcpy(prov_ctx->iothub_uri, iothub_uri, len);

        len = strlen(device_id) + 1;
        prov_ctx->device_id = malloc(len);
        memcpy(prov_ctx->device_id, device_id, len);

        printf("\r\ndevice result: PROV_DEVICE_RESULT_OK\r\n");
        printf("\r\nRegistration Information received from service: %s, deviceId: %s\r\n", iothub_uri, device_id);
        break;
    default:
        printf("\r\nUnknown device result\r\n");
        break;
    }
}

static void provisioning_connection_cb (IOTHUB_CLIENT_CONNECTION_STATUS result, IOTHUB_CLIENT_CONNECTION_STATUS_REASON reason, void *user_ctx_cb)
{
    (void)user_ctx_cb;

    switch ( result )
    {
    case IOTHUB_CLIENT_CONNECTION_AUTHENTICATED:
        printf("\r\nconnection status result: IOTHUB_CLIENT_CONNECTION_AUTHENTICATED\r\n");
        break;
    default:
        printf("\r\nunknown message result: 0x%08x", result);
        break;
    }

    switch ( reason )
    {
    case IOTHUB_CLIENT_CONNECTION_OK:
        printf("\r\nconnection status reason: IOTHUB_CLIENT_CONNECTION_OK\r\n");
        break;
    default:
        printf("\r\nunknown message response: 0x%08x", reason);
        break;
    }
}

int main( void ){
    SECURE_DEVICE_TYPE hsm_type = SECURE_DEVICE_TYPE_X509;
    PROV_DEVICE_HANDLE prov_device_handle;
    bool g_trace_on = false;

    const char *global_prov_uri = "global.azure-devices-provisioning.net";
    const char *id_scope = "<SCODE_ID>";
    const char *registration_id = "azure-test-xxx"

    prov_ctx *prov_ctx = calloc( 1, sizeof(prov_ctx) );

    printf("Provisioning API Version: %s\r\n", Prov_Device_GetVersionString());

    platform_init() == 0;

    prov_dev_security_init(hsm_type);

    prov_device_handle = Prov_Device_Create(global_prov_uri, id_scope, prov_transport);

    Prov_Device_SetOption(prov_device_handle, OPTION_LOG_TRACE, &g_trace_on);
    Prov_Device_SetOption(prov_device_handle, PROV_REGISTRATION_ID, registration_id);

    if ( Prov_Device_Register_Device(prov_device_handle, register_device_callback, prov_ctx, registation_status_callback, prov_ctx);

    printf("\r\nRegistering... Press any key to interrupt.\r\n\r\n");
    getchar();

    Prov_Device_Destroy(prov_device_handle);

    IOTHUB_CLIENT_HANDLE iothub_client = IoTHubClient_CreateFromDeviceAuth(prov_ctx->iothub_uri, prov_ctx->device_id, iothub_transport);

    IoTHubClient_SetConnectionStatusCallback(iothub_client, provisioning_connection_cb, NULL);

    printf("\r\nConnecting... Press any key to interrupt.\r\n\r\n");
    getchar();

    IoTHubClient_Destroy(iothub_client);

    printf("calling platform_deinit\n");
    prov_dev_security_deinit();
    platform_deinit();

    return 0;
}
```

Thank you for your help.

**Comment by lakshmisivareddy** [comment]
Hi @syedelec  This samples looks fine 
you mentioned you already Enrolled Devices in Azure DPS 
if you are trying to provision device with x509 , you have to pass your device private key & device public certificate chain to hsm module . if certificates are correct you will receive IoT Hub uri & Device From 
Prov_Device_Register_Device callback

**Comment by syedelec** [comment]
Hi @lakshmisivareddy 
Thank you for your reply.

Currently I am not using HSMs such as TPM or crypto chips.
Do I still need to use a custom HSM lib to pass the private key and public certificate ?

**Comment by lakshmisivareddy** [comment]
Hi @syedelec  in provisioning_client/adapters 
you have to write your adapter to read device public certificate & key or you can customise
'provisioning_client/adapters/hsm_client_riot.c'  to read your  device certificates

**Comment by jebrando** [comment]
@syedelec I'll try to explain the mindset we have on provisioning client.

1. For Development
If you would like to just see provisioning work you can just use our x509/dice emulator that is built into the sdk.  This will generate a canned certificate that you can use to provision your device (you can run the dice_device_enrollment tool to save the certificate).

2. For Production
If you would like to us a certificate that you have created, you will need to create a custom [HSM](https://github.com/Azure/azure-iot-sdk-c/tree/master/provisioning_client/samples/custom_hsm_example) and return the certificate, the private key and the common_name.

Let me know if you have any questions.

**Comment by syedelec** [comment]
@jebrando 
Currently I am only trying to understand how provisioning work and reproduce with a self-signed certificate. I took the [first certificate](https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509#create-a-self-signed-x509-device-certificate-and-individual-enrollment-entry) generated by `dice_device_enrollment` binary, I noticed that the `CN=riot-device-cert` which corresponds to the device I receive in my sample using this callback `register_device_callback`.

If I understood correctly, in order to have another device registered with a self-signed certificate, I will need to create the custom [HSM](https://github.com/Azure/azure-iot-sdk-c/tree/master/provisioning_client/samples/custom_hsm_example) or customize the [HSM riot](provisioning_client/adapters/hsm_client_riot.c) as @lakshmisivareddy specified to return the certificate, the key and the CN.

**Comment by jebrando** [comment]
@syedelec 
You are correct, if you want have multiple device registered you will need to create a custom hsm that create the certificates to be used.

**Comment by yzhong94** [comment]
@syedelec , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
