### ISSUE TITLE
Azure devicemethod_simplesample application compilation error using arm 5 compiler (arm_cc).

### ISSUE THREAD

**Issue by vpulimi** [Azure/azure-iot-sdk-c#465]
Cross-compiling on ARM 5 compiler. 

- **OS and version used:** <VERSION> 

Cygwin on Windows 10.

- **SDK version used:** <VERSION> 

git clone -b 2018-03-02 --recursive https://github.com/Azure/azure-iot-sdk-c.git

# Description of the issue:

Trying to cross compile the sample devicemethod_simplesample application using arm 5 compiler (arm_cc). I do see errors with the __COUNTER__ macro expansion which happens when the following model example gets expanded. 

DECLARE_MODEL(ContosoAnemometer,

WITH_DATA(ascii_char_ptr, DeviceId),
WITH_DATA(int, WindSpeed),
WITH_ACTION(TurnFanOn_with_Action),
WITH_ACTION(TurnFanOff_with_Action),
WITH_METHOD(TurnFanOn_with_Method),
WITH_METHOD(TurnFanOff_with_Method)
);

"../test-app/src/devicemethod_simplesample.c", line 42: Error:  #20: identifier "REFLECTED_DECDEC__COUNTER__" is undefined   DECLARE_MODEL(ContosoAnemometer,
"../test-app/src/devicemethod_simplesample.c", line 42: Error:  #148: variable "REFLECTED_INC__COUNTER__" has already been initialized   DECLARE_MODEL(ContosoAnemometer,
"../test-app/src/devicemethod_simplesample.c", line 51: Error:  #20: identifier "REFLECTED_DEC__COUNTER__" is undefined DECLARE_MODEL(ContosoAnemometer

I checked the following ARM predefined macro document and I don’t see the macro defined.

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0472k/chr1359125007083.html

More information:

I am cross-compiling for an ARM device using ARM CC compiler. I have no issues cross-compiling the Azure SDK. Compilation issue happens when I try to build the devicemethod_simplesample application. 

Here are the steps that I used to build the devicemethod_simplesample.
1. I cross-compiled and built the Azure SDK library separately first. No issues. 
2. Then I took just the devicemethod_simplesample and tried to cross-compile and link to the Azure SDK library. 
3. During the cross-compilation I am seeing issues with devicemethod_simplesample.

I looked into the issue a bit deeper and here are my findings. 

Here are the macros in the devicemethod_simplesample application 

DECLARE_MODEL(ContosoAnemometer,
WITH_DATA(ascii_char_ptr, DeviceId),
WITH_DATA(int, WindSpeed),
WITH_ACTION(TurnFanOn_with_Action),
WITH_ACTION(TurnFanOff_with_Action),
WITH_METHOD(TurnFanOn_with_Method),
WITH_METHOD(TurnFanOff_with_Method)
);

Gets expanded to the following expressions under serializer\inc\serializer.h  
#define REFLECTED_MODEL(name) \
    static const REFLECTED_SOMETHING C2(REFLECTED_, C1(INC(__COUNTER__))) = { REFLECTION_MODEL_TYPE, &C2(REFLECTED_, C1(DEC(DEC(__COUNTER__)))), { {0}, {0}, {0}, {0}, {0}, {0}, {0}, {TOSTRING(name)} } };

With ARM CC 5.5 tool chain, I don’t see the __COUNTER__ getting expanded and it just gets tokenized during preprocessing as shown below for some reason. 

static const REFLECTED_SOMETHING REFLECTED___COUNTER__ = { REFLECTION_NOTHING, 0, { {0},{0}, {0}, {0}, {0}, {0}, {0}, {0}} };;
static const REFLECTED_SOMETHING REFLECTED_INC__COUNTER__ = { REFLECTION_MODEL_TYPE, &REFLECTED_DECDEC__COUNTER__, { {0}, {0}, {0}, {0}, {0}, {0}, {0}, {"ContosoAnemometer"} } };

Is there any specific ARM CC complier that you would recommend me to compile the sample application? Any specific options/config for expanding __COUNTER__? 

Please provide your inputs to resolve the problem.

Appreciate your help!

Thanks!

**Comment by jspaith** [comment]
Apologies for the delay here.  You're correct, the COUNTER variable is available on Visual Studio/gcc/clang but isn't available universally and the serializer relies on this.

For workarounds:
* You can precompile the serializer header files using a compiler that respects the COUNTER and then use these headers to build against.
* You can not use the serializer but instead use parson for json parsing.  (We're working on a sample demonstrating this, tracked https://github.com/Azure/azure-iot-sdk-c/issues/458).  Some of reasons not to use serializer are at https://github.com/Azure/azure-iot-sdk-c/issues/388#issuecomment-369992487.

**Comment by jspaith** [comment]
Since this thread has been quiet for about a week, I'm going to close it just for book-keeping.  As always, if you have followups here or anywhere else please re-active this or open a new thread.  Thanks.
