### ISSUE TITLE
MQTT - System Properties are always NULL when receiving C2D-Messages

### ISSUE THREAD

**Issue by raycon94** [Azure/azure-iot-sdk-c#468]
- **OS and version used:**  Windows 10<VERSION> 

- **SDK version used:** 1.1.6<VERSION> 

# Description of the issue:

When the device is receiving C2D-Messages (with MQTT) all the System Properties are always set to Null, altough they are set in the Device-Explorer-Twin. 

# Code sample exhibiting the issue:

    static IOTHUBMESSAGE_DISPOSITION_RESULT ReceiveMessageCallback(IOTHUB_MESSAGE_HANDLE   message, void* userContextCallback)
    {
      IOTHUBMESSAGE_DISPOSITION_RESULT result;
    
    
        const char* messageId;
        const char* correlationId;
        const unsigned char* string_msg;
        IOTHUBMESSAGE_CONTENT_TYPE content_type;

        // Message properties
        if ((messageId = IoTHubMessage_GetMessageId(message)) == NULL)
        {
            messageId = "<unavailable>";
        }

        if ((correlationId = IoTHubMessage_GetCorrelationId(message)) == NULL)
        {
            correlationId = "<unavailable>";
        }

    ...
    }

**Comment by jebrando** [comment]
@raycon94 I just tested this and was able to see the message Id and the Correlation ID.
![msgid_corrid](https://user-images.githubusercontent.com/8583083/39139981-34647cb4-46d8-11e8-8631-481f6aed4f0e.PNG).  Can you upgrading your SDK version?

**Comment by raycon94** [comment]
thank you! it works with the newest SDK-Version

**Comment by yzhong94** [comment]
@raycon94 , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
