### ISSUE TITLE
iOS Not able to set TLS version using IoTHubClient_SetOption()

### ISSUE THREAD

**Issue by Gokul-Radhakrishnan** [Azure/azure-iot-sdk-c#469]
- **OS and version used:** <VERSION> 
OS - iOS
Version - 11.1.1
- **SDK version used:** <VERSION> 
AzureIoTHubClient 1.2.3 (Cocoapod) 

# Description of the issue:

Not able to set the TLS version using IoTHubClient_SetOption(). Protocol used AMQP_Protocol_over_WebSocketsTls
# Code sample exhibiting the issue:

`let connectionString = try getConnectionString()`

`iotHubClientHandle = IoTHubClient_CreateFromConnectionString(connectionString, AMQP_Protocol_over_WebSocketsTls)`

 ` var version:Int32?`

  `version = 12`          

  `IoTHubClient_SetOption(iotHubClientHandle,"tls_version",&version)`

# Console log of the issue:

Error: Time:Mon Apr 23 14:23:44 2018 File:/Users/sentienceedge/Documents/ChangingVersionSample/sentience.cloudconnector.ios.sample/CloudConnectorSample/Pods/AzureIoTUtility/pal/ios-osx/tlsio_appleios.c Func:tlsio_appleios_setoption Line:607 Failed tlsio_options_set

Error: Time:Mon Apr 23 14:23:44 2018 File:/Users/sentienceedge/Documents/ChangingVersionSample/sentience.cloudconnector.ios.sample/CloudConnectorSample/Pods/AzureIoTUtility/src/uws_client.c Func:uws_client_set_option Line:1869 xio_setoption failed.

Error: Time:Mon Apr 23 14:23:44 2018 File:/Users/sentienceedge/Documents/ChangingVersionSample/sentience.cloudconnector.ios.sample/CloudConnectorSample/Pods/AzureIoTUtility/src/wsio.c Func:wsio_setoption Line:691 Setting the option tls_version failed

Error: Time:Mon Apr 23 14:23:44 2018 File:/Users/sentienceedge/Documents/ChangingVersionSample/sentience.cloudconnector.ios.sample/CloudConnectorSample/Pods/AzureIoTHubClient/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_SetOption Line:2105 transport failed setting option 'tls_version' (xio_setoption failed)

Error: Time:Mon Apr 23 14:23:44 2018 File:/Users/sentienceedge/Documents/ChangingVersionSample/sentience.cloudconnector.ios.sample/CloudConnectorSample/Pods/AzureIoTHubClient/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_SetOption Line:1790 unable to IoTHubTransport_SetOption

Error: Time:Mon Apr 23 14:23:44 2018 File:/Users/sentienceedge/Documents/ChangingVersionSample/sentience.cloudconnector.ios.sample/CloudConnectorSample/Pods/AzureIoTHubClient/iothub_client/src/iothub_client.c Func:IoTHubClient_SetOption Line:1506 IoTHubClient_LL_SetOption failed

**Comment by jebrando** [comment]
@Gokul-Radhakrishnan this functionality has not been implemented for ios yet.  I will add it to the task list and it will be prioritized and implemented as soon as possible.

Thank  you for the issue.

**Comment by jebrando** [comment]
@Gokul-Radhakrishnan Thank you once again for the issue, I looked at this and for the apple TLS connections we only want to support the default TLS version that apple provides which I believe is 1.2. depending on iOS version (See documentation for verification).
