### ISSUE TITLE
Reconnect interval and backoff

### ISSUE THREAD

**Issue by Shakti213** [Azure/azure-iot-sdk-c#470]
- **OS and version used:** Windows 10, Raspbian

- **SDK version used:** 2017-12-14

# Description of the issue:
If a device attempts to connect to a hub with wrong credentials the connection will fail, which is correct. However there is no way to set either a reconnect interval or a backoff strategy which will cause the client to attempt to reconnect very quickly again which will again fail and so on until the credentials are added to the hub. This can cause quite alot of data to be sent and in the case of a GSM-connection etc. it might get costly.

If a single transport is used for multiple client connections, most of which are valid, it is enough for one invalid client credential to cause all the valid ones to be disconnected as well and thus you enter a loop of disconnecting and reconnecting all active clients associated with one transport. This can cause further issues with GSM bandwidth etc.

Is there a plan to implement a backoff strategy or a settable reconnect interval, either on the transport layer or on the client layer (preferrably I would say would be to have it on the client layer).

**Comment by Shakti213** [comment]
Found a better described issue, will comment on that instead

**Comment by tameraw** [comment]
@Shakti213, thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
