### ISSUE TITLE
Question: parsing received json-string to data of the device-model 

### ISSUE THREAD

**Issue by raycon94** [Azure/azure-iot-sdk-c#471]
- **OS and version used:** <Windows 10> 

- **SDK version used:** <1.2.3> 

# Description of the issue:

I am receiving json-strings over C2D-Messages that contain serialized data, for example:
{"mydata" : 0}. 

Is there any way to parse this json value to an WITH_DATA-field that is defined as WITH_DATA(int8_t, mydata) with the serializer-libary?

**Comment by jspaith** [comment]
The serializer interacting with C2D messages isn't supported.  For c2d could you use parson, the lightweight json parser, instead?

We'd also like to understand why you're using C2D messages, as device methods are we think a bit easier to use.  And the serializer has support for them including a sample, see https://github.com/Azure/azure-iot-sdk-c/tree/master/serializer/samples/devicemethod_simplesample.

**Comment by jspaith** [comment]
Since this thread has been inactive for a bit, closing out.  As always feel free to reopen or create a new issue if you need more assistance. Thanks

**Comment by kiranpradeep** [comment]
@jspaith Regarding query on usage of C2D messages (unrelated to OP) - Devices could be offline when device method is invoked. Now, if we use scheduled jobs with higher `maxExecutionTimeInSeconds`, S1 tier IoT Hub limits to maximum 1 concurrent job. A C2D device message (with method parameters seperated) help over come these limitations as it has 7 day retention. Is this not advised?

**Comment by jspaith** [comment]
@kiranpradeep - great question.  Could you please reopen on a new thread (we don't actively follow closed issues).  I'm actually not sure what the answer is, but once you get the new thread opened I'll forward it onto some folks who can help.

**Comment by kiranpradeep** [comment]
@jspaith Thanks for the reply. Raised new ticket at #500
