### ISSUE TITLE
Including Header-File which contains DECLARE_MODEL to different Source-Files

### ISSUE THREAD

**Issue by raycon94** [Azure/azure-iot-sdk-c#473]
- **OS and version used:** <Windows 10> 

- **SDK version used:** <1.2.3> 
 

# Description of the issue:

When I try to include an Header-file where the DECLARE_MODEL is defined in different source-files, the linker throws an error: 

    Symbol FromAGENT_DATA_TYPE_AzureTestModel_t(const AGENT_DATA_TYPE_TAG*, void) multiply defined (by file1.o and file2.o).

(Using uVision V5.25.2.0 with ARM-Linker V5.06, ARM-Compiler V5.06)

**Comment by jspaith** [comment]
If I understand correctly, you're doing a

header.h that has DECLARE_MODEL
file1.c includes header.h
file2.c includes header.h

If so, this isn't supported.  The DECLARE_MODEL ultimately turns into a static struct which is going to get name collisions if multiple C files reference it.

On Visual Studio based compiler, you could get around this with __declspec(selectany) in front of DECLARY_MODEL and the compiler/linker would do the right thing.  Your compiler may have same concept.  Generally I avoid these though and would DECLARE_MODEL in some core .c file and have helper functions in it to handle any access from outside the .C.

**Comment by jspaith** [comment]
Since this thread has been inactive for a bit, closing out.  As always feel free to reopen or create a new issue if you need more assistance. Thanks
