### ISSUE TITLE
Unresolved external symbol _json_parse_string

### ISSUE THREAD

**Issue by AleksandarRB** [Azure/azure-iot-sdk-c#474]
Hi, everyone! Needs some help. :)

- **OS and version used:** Windows 10

- **SDK version used:** 2018-04-13

# Description of the issue:
I tried to build the telemetry sample but errors occurs with JSON parsing. Can you please tell me how to fix?

# Code sample exhibiting the issue:
Just SDK sample "iothub_ll_telemetry_sample" .
No changes in the source code except adding library paths in the solution project to build it without errors on including header files.

# Console log of the issue:
`1>------ Build started: Project: iothub_ll_telemetry_sample, Configuration: Debug Win32 ------
1>iothub_client.lib(iothub_client_ll_uploadtoblob.obj) : error LNK2019: unresolved external symbol _json_parse_string referenced in function _IoTHubClient_LL_UploadToBlob_step1and2
1>iothub_client.lib(iothub_client_ll_uploadtoblob.obj) : error LNK2019: unresolved external symbol _json_object_get_string referenced in function _IoTHubClient_LL_UploadToBlob_step1and2
1>iothub_client.lib(iothub_client_ll_uploadtoblob.obj) : error LNK2019: unresolved external symbol _json_value_free referenced in function _IoTHubClient_LL_UploadToBlob_step1and2
1>iothub_client.lib(iothub_client_ll_uploadtoblob.obj) : error LNK2019: unresolved external symbol _json_value_get_object referenced in function _IoTHubClient_LL_UploadToBlob_step1and2
1>C:\azure-iot-sdk-c\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\windows\Win32\Debug\iothub_ll_telemetry_sample.exe : fatal error LNK1120: 4 unresolved externals
1>Done building project "iothub_ll_telemetry_sample.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

**Comment by RivaStyle** [comment]
May be related to the missing Parson library, see issues #429 and #462.

**Comment by jebrando** [comment]
We are taking in the PR which fixes this issues.  The change should be in 4/26

**Comment by AleksandarRB** [comment]
Hi,

I forgot to mention that I build locally the SDK following your [instructions](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#windows). 
After I did this, I tried to run the sample from main folder of the SDK and then the problem with the JSON occured.

Now, I have found some kind of solution for my problem. I succeeded to build the sample when I start "azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\windows\iothub_ll_telemetry_sample.sln"

**Comment by jebrando** [comment]
We are tentatively scheduling a release for 5/2 to have a permanent solution for this.

If you have any more troubles with this issue please reopen or submit a new issue.

**Comment by jebrando** [comment]
This has been released and should be fixed.  If you find an issue please reopen or open a new issue.

**Comment by rkathire** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol _json_parse_string referenced in function _IoTHubClient_LL_UploadToBlob_step1and2	iothub_ll_telemetry_sample	C:\Users\rkathire\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\windows\iothub_client.lib(iothub_client_ll_uploadtoblob.obj)	1	
Error	LNK2019	unresolved external symbol _json_object_get_string referenced in function _IoTHubClient_LL_UploadToBlob_step1and2	iothub_ll_telemetry_sample	C:\Users\rkathire\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\windows\iothub_client.lib(iothub_client_ll_uploadtoblob.obj)	1	
Error	LNK2019	unresolved external symbol _json_value_free referenced in function _IoTHubClient_LL_UploadToBlob_step1and2	iothub_ll_telemetry_sample	C:\Users\rkathire\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\windows\iothub_client.lib(iothub_client_ll_uploadtoblob.obj)	1	
Error	LNK2019	unresolved external symbol _json_value_get_object referenced in function _IoTHubClient_LL_UploadToBlob_step1and2	iothub_ll_telemetry_sample	C:\Users\rkathire\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\windows\iothub_client.lib(iothub_client_ll_uploadtoblob.obj)	1

**Comment by rkathire** [comment]
i have v1.2.5
