### ISSUE TITLE
prov_dev_client_ll_sample fails on arm: TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR

### ISSUE THREAD

**Issue by AnneSt** [Azure/azure-iot-sdk-c#475]
Host OS (x86, 64bit) and version used: 
- Debian 9 + OpenSSL 1.1.0 (<=?)

Target (imx6 / arm) OS and version used:
- Yocto SDK version used: Poky f3e674cb654d4dab3e4ba5b2ae1fac72ef8363da
- Azure-Iot-SDK-C version used: bc9b67773348a44a87972a558288805650a7db38 
(Configuration: 
> -Duse_amqp:BOOL=OFF -Dhsm_type_sastoken:BOOL=ON -Duse_prov_client:BOOL=ON -Duse_tpm_simulator:BOOL=ON
)
- OpenSSL used: 1.0.2n
- IBM-TPMSimulator: 1.1.19

## Description of the issue:
I have compiled the sample prov_dev_client_ll_sample for x86 and arm with the same versions of azure-iot-sdk-c/ibmtpmserver/.. - excluded the openssl-version.
This example gets starting on x86 but not on arm. On ARM I get the follwing error-message:

## Console Output on arm:
> root@jetfuture-imx6sx:~# /usr/bin/provsample 
> Provisioning API Version: 1.2.2
> Iothub API Version: 1.2.2
> Http connection failed to connect: 1
> Error: Time:Thu Apr 26 07:45:01 2018 File:/usr/src/debug/azure-iot-sdk-c/git/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:454 Failure retrieving data from the provisioning service
> Failure encountered on registration!
> Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
> TPM command server listening on port 2321
> registration failed!

**Comment by AnneSt** [comment]
Error occurs even with the following versions:
- Yocto SDK version used: Poky f3e674cb654d4dab3e4ba5b2ae1fac72ef8363da
- Azure-Iot-SDK-C version used: 1.2.3
- OpenSSL used: 1.0.2o
- IBM-TPMSimulator: 1.1.19

**Comment by AnneSt** [comment]
I compiled the ibm tpm simulator sourcecode for arm. I take the sourcecode from sourceforge. I wrote a recipe for yocto and a CMakeLists.txt. I will contribute it on my Github (https://github.com/AnneSt/ibmswtpm).

Further more it seems the error which causes this errror is SSL_ERROR_WANT_READ. Should you read out the socket for a "while"? Like it is written in https://www.openssl.org/docs/manmaster/man3/SSL_read.html Topic "Warning"? (See in function "send_handshake_bytes", implemented in azure-c-shared-utility/src/tlsio_openssl.c)

**Comment by jebrando** [comment]
Thanks, @AnneSt let me try to get this working and I'll give you some feedback on my findings.

**Comment by AnneSt** [comment]
The Problem is solved ... I guess. Excuse me for making trouble. 

I upgraded to OpenSSL 1.1.0g. 
After this point the SSL-Handshake went properly. (?)
The next problem was, that by trying to create an SSL-Instance, OpenSSL wasn't able to find any certificates. Because of this I added in tlsio_openssl.c, in function:
`static int create_openssl_instance(TLS_IO_INSTANCE* tlsInstance)`
the following lines:
`#if (OPENSSL_VERSION_NUMBER == 0x1010007fL)
    if (tlsInstance->ssl_context != NULL)
    {
        SSL_CTX_load_verify_locations(tlsInstance->ssl_context, cafile, capath);
    }
#endif`
In addition, there will be now "TLS_method()" instead of "TLSv1_2_method()" called. 
Unfortunately I am not able to say what was the exact reason.

I am able now to register my device by DPS with an Endorsment-Key generated by the SW-TPM-Simulator and to get the IotHub-Link to communicate with. Everything is fine.
Thanks.

**Comment by jebrando** [comment]
@AnneSt I ran this on my Ubuntu setup and it worked successfully so it points to differences somewhere in the stack on the yocto vs Ubuntu.  Can you send me all the errors that you get form the SDK, I'm assuming there should be some error getting reported from the tpm_socket_comm.c or tpm_comm_emulator.c files

**Comment by jebrando** [comment]
Thanks for the update if you have any more issues, just let me know.

**Comment by yzhong94** [comment]
@AnneSt , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
