### ISSUE TITLE
IoTHubRegistryManager_GetDevice returns IOTHUB_REGISTRYMANAGER_HTTP_STATUS_ERROR if the device does not exist instead of IOTHUB_REGISTRYMANAGER_DEVICE_NOT_EXIST

### ISSUE THREAD

**Issue by zoe-mcelderry** [Azure/azure-iot-sdk-c#481]
# Environment:

OS: Debian 9.
SDK: 2018-04-13 

# Description of the issue:

The issue occurs when calling the IoTHubRegistryManager_GetDevice function with a device ID that does not exist in the IoT Hub.

I would expect it to return the value IOTHUB_REGISTRYMANAGER_DEVICE_NOT_EXIST, but what it actually returns is IOTHUB_REGISTRYMANAGER_HTTP_STATUS_ERROR .

What I want is a "create if not exists" scenario, I was hoping to use the GetDevice function to identify when a device does not already exist and then use CreateDevice to create the device.  It looks like the SDK should support this, so I was surprised by the result returned by GetDevice when the device doesn't exist -- is this intentional or a bug?  Is there a better way to do a "create if not exists" using the SDK?

Calling the GetDevice function with a device ID for a device that does not exist also results in Errors being logged, which is not desirable for this use case.

# Code sample exhibiting the issue:

IOTHUB_SERVICE_CLIENT_AUTH_HANDLE serviceHandle = IoTHubServiceClientAuth_CreateFromConnectionString ("...");
IOTHUB_REGISTRYMANAGER_HANDLE registryHandle = IoTHubRegistryManager_Create (serviceHandle);
IOTHUB_DEVICE device;
IOTHUB_REGISTRYMANAGER_RESULT result;
result = IoTHubRegistryManager_GetDevice (registryHandle, "new-device", &device);

# Console log of the issue:

Error: Time:Fri May  4 08:55:49 2018 File:/src/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:624 Failure in HTTP communication: server reply code is 404
Info: HTTP Response:{"Message":"ErrorCode:DeviceNotFound;new-device","ExceptionMessage":"Tracking ID:622cd16543c24cad8152861964d8f6d9-G:4-TimeStamp:05/04/2018 08:55:49"}
Error: Time:Fri May  4 08:55:49 2018 File:/src/azure-iot-sdk-c/iothub_service_client/src/iothub_registrymanager.c Func:sendHttpRequestCRUD Line:999 Http Failure status code 404

**Comment by jebrando** [comment]
@zoe-mcelderry Thank you for the issue, this has been fixed and checked in.  Let us know if you have any questions.

thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute customer [satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)

**Comment by zoe-mcelderry** [comment]
Thanks, the return code is much better now, but it's a shame that it still provides error logs.  It would be nice to have a mechanism for getting a device (creating it if it does not already exist) that does not result in error logs.

Also, do you know when this will become part of a tagged release?  I prefer not to build against the master branch for stability.
