### ISSUE TITLE
installation of apt-get install -y azure-iot-sdk-c-dev under ubuntu bionic

### ISSUE THREAD

**Issue by SergiyIvanovAtGTI** [Azure/azure-iot-sdk-c#482]
Hi there. Cannot install azure iot under ubuntu bionic.
Steps are:
1) add-apt-repository ppa:aziotsdklinux/ppa-azureiot
 PPA for AzureIoT apt-get packages
 More info: https://launchpad.net/~aziotsdklinux/+archive/ubuntu/ppa-azureiot
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://ua.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://ua.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                       
Hit:3 http://ua.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                     
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                        
Ign:5 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu bionic InRelease                  
Err:6 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                                                 
E: The repository 'http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

2) apt-get update
Hit:1 http://ua.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://ua.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                                     
Hit:3 http://ua.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                                   
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                                      
Ign:5 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu bionic InRelease                                                
Err:6 http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
3)  apt-get install -y azure-iot-sdk-c-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package azure-iot-sdk-c-dev

**Comment by jebrando** [comment]
@SergiyIvanovAtGTI We will roll out this in an upcoming release.  I will update you when we are getting close to finishing.

**Comment by saidimu** [comment]
@SergiyIvanovAtGTI @jebrando I manually changed the apt sources file and it worked.

`sudo vim /etc/apt/sources.list.d/aziotsdklinux-ubuntu-ppa-azureiot-bionic.list`

Change the first line from `deb http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu bionic main` to `deb http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu xenial main`

Essentially I'm using `xenial` packages and they seem to work fine so far.

**Comment by jebrando** [comment]
@SergiyIvanovAtGTI We have just created a package for bionic, the package will be release within a week.
