### ISSUE TITLE
Cross Compilation of Azure SDK with MIPS32 compiler is not working!!

### ISSUE THREAD

**Issue by Pavan2358** [Azure/azure-iot-sdk-c#484]
# Console log of the issue:
In file included from /home/test/azure_3/azure-iot-sdk-c/c-utility/src/x509_openssl.c:4:0:
/home/test/azure_3/azure-iot-sdk-c/c-utility/inc/azure_c_shared_utility/x509_openssl.h:7:25: fatal error: openssl/ssl.h: No such file or directory
compilation terminated.
make[2]: *** [c-utility/CMakeFiles/aziotsharedutil.dir/build.make:661: c-utility/CMakeFiles/aziotsharedutil.dir/src/x509_openssl.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....

I have attached the toolchain that I am using to cross compile
Note: build.sh works fine with normal gcc compiler and creakes make file for sample code

I just want to compile the code using mips compiler and run sample in my Dlink device... 
please help!!:(
[toolchain-mips.zip](https://github.com/Azure/azure-iot-sdk-c/files/1986577/toolchain-mips.zip)

**Comment by lakshmisivareddy** [comment]
Hi @Pavan2358 
try setting your environment path 
SET(CMAKE_FIND_ROOT_PATH $ENV{SYS_ROOT})
your environment path should contain all your library paths 
and remove all comment ssl,curl,crypto library path

**Comment by Pavan2358** [comment]
Hi @lakshmisivareddy 

I commented as suggested by you....I am stll facing the below mentioned issue

-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- target architecture: GENERIC
-- Performing Test CXX_FLAG_CXX11
-- Performing Test CXX_FLAG_CXX11 - Failed
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  **Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "1.1.0h")**
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindOpenSSL.cmake:379 (find_package_handle_standard_args)
  c-utility/CMakeLists.txt:85 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/test/azure_3/azure-iot-sdk-c/cmake/iotsdk_linux/CMakeFiles/CMakeOutput.log".
See also "/home/test/azure_3/azure-iot-sdk-c/cmake/iotsdk_linux/CMakeFiles/CMakeError.log".

Could not find openssl crypto library

**I am new to linux.**....I dont know where curl or openssl libraries are linked...
Please help :(
Please find the attachment of toolchain..
[toolchain-mips.zip](https://github.com/Azure/azure-iot-sdk-c/files/1988095/toolchain-mips.zip)

**Comment by markrad** [comment]
Hi @Pavan2358,

Are you using a CMake toolchain file such as in the example here: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md. If so can you also post that here too.

Thanks.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @Pavan2358,

Looking at your toolchain file you would appear to be pointing it at the OpenSSL versions on your host as in /usr/bin/openssl. These will not work. You need to have the OpenSSL headers and libraries in your toolchain. Can you send a link to the toolchain you are using? Is it publicly available?

_Mark Radbourne MSFT_

**Comment by Pavan2358** [comment]
Hi @markrad 
Sorry for the delayed response
How to include headers and libraries in the toolchain....I have tried most options....but none of them worked
**I have attached a file containing the places where openssl is found in my PC**
**Please can you provide snapshot/file on how to provide headers and libraries in the toolchain**
I guess openssl has to be installed in my host machine for my mediak tek(processor) Dlink device
system type             : MT7628
processor               : 0
cpu model               : MIPS 24Kc V5.5

**Please can you provide the steps if possible....I just want to send/receive message in my device with sample app
Please help :(**
[openssl_location.txt](https://github.com/Azure/azure-iot-sdk-c/files/1990967/openssl_location.txt)

**Comment by lakshmisivareddy** [comment]
hi @Pavan2358 
install opnssl >= 1.0.2j in your root file system 
export SYS_ROOT = your root file system 
SET(CMAKE_FIND_ROOT_PATH $ENV{SYS_ROOT}) in your toolchain file

**Comment by markrad** [comment]
Hi @Pavan2358,

I cannot tell you how to get OpenSSL for your cross compile environment. I can explain how you need to have your environment set up. 

You need a version of OpenSSL that matches the architecture of your target device. This will need to be in the tool chain that you are using. A typical tool chain will have a directory called sysroots. In this directory there is usually two directories. 

The first contains the tools used to compile the code for the target architecture. In your case this would contain, for example, a version of gcc that runs on your host (Intel 64 bit perhaps) but creates executables that will run on a MIPS32.

The second directory is a representation of the file system on your MIPS 32 device in that you will see it has the standard directories found at the root such as etc, usr, bin, sbin, opt, etc. This contains the binaries that are compiled for MIPS32, both libraries and executables. These will be used to resolve link externs in the executables you build with the toolchain.

The versions of OpenSSL, libssl.so and libcrypto.so that are found in your root file system are built for you local machine. They **will not** run on your MIPS 32 machine. You will need to have these libraries compiled for MIPS 32 and installed in the toolchain at <toolchain root>/sysroots/<device root file system>/usr/lib. If they are not there then you might be able to find them precompiled. If not then you will need to build OpenSSL with your toolchain and install it into your toolchain.

Does your device have OpenSSL installed on it? You could copy those files from your device to your toolchain if it does.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @Pavan2358,

Yes you will need to create curl in the same manner. I will look into your other questions. 

_Mark Radbourne MSFT_

**Comment by lakshmisivareddy** [comment]
Hi @Pavan2358 
based on your tool chain file i am hoping 
/opt/buildroot-gcc463/ is your build root 
place cross compiled openssl & curl in your build root 
comment all openssl & curl path in your toolchain file & 
SET(CMAKE_FIND_ROOT_PATH /opt/buildroot-gcc463)
in your toolchain file

**Comment by jspaith** [comment]
@Pavan2358 - have you got your issue addressed here or are you facing additional issues we can help with?  Thanks to @markrad and @lakshmisivareddy for help so far.

**Comment by Pavan2358** [comment]
Hi @jspaith @markrad and @lakshmisivareddy 

I was able to cross compile for openssl and curl errors, but I am facing a new issue as below
[ 21%] Linking C static library libaziotsharedutil.a
[ 21%] Built target aziotsharedutil
[ 21%] Building C object c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/iot_c_utility.c.o
[ 21%] Linking C executable iot_c_utility
/opt/buildroot-gcc463/usr/lib/gcc/mipsel-buildroot-linux-uclibc/4.6.3/../../../../mipsel-buildroot-linux-uclibc/bin/ld: cannot find -luuid
/home/test/openssl1/final/lib/libcrypto.so: warning: gethostbyname is obsolescent, use getnameinfo() instead.
collect2: ld returned 1 exit status
make[2]: *** [c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/build.make:87: c-utility/samples/iot_c_utility/iot_c_utility] Error 1
make[1]: *** [CMakeFiles/Makefile2:1100: c-utility/samples/iot_c_utility/CMakeFiles/iot_c_utility.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

and I still get the above mentioned warning in previous thread
I am not able to figure out!! 
Please help:(

**Comment by jspaith** [comment]
Looks like uuid is missing.

On a Debian based setup I think issue's fix would be 'sudo apt-get uuid-dev', but given cross-compilation I think you need to follow same steps you did in bringing over curl.

Also note that the C SDK has an option for bringing in its own uuid functions that it needs instead of depending on a library.  This is usually for embedded devices, but you should be able to get it with an argument to your cmake command line of '-Duse_default_uuid=ON'.  Note you'll need to call srand() before invoking this private copy.  https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/uniqueid_stub.c

In general I'd recommend cross-compiling 'uuid' as it'll be a more random uuid you should get from system library, but want you to have additional knowledge here.

**Comment by markrad** [comment]
Hi @Pavan2358,

I did this once before sometime ago. You will find libuuid is part of util-linux. As I recall there are configure flags you can set so that it only builds libuuid.

_Mark Radbourne MSFT_

**Comment by lakshmisivareddy** [comment]
Hi @Pavan2358  as @jspaith  said   try 'sudo apt-get uuid-dev' i hope this will solve your problem

**Comment by markrad** [comment]
Hi @lakshmisivareddy,

> try 'sudo apt-get uuid-dev' i hope this will solve your problem

This will **not** work. This will install uuid-dev on the host system. The binaries will not be suitable for linking in a cross compile environment. He will need to build uuid in his cross compile environment to get a binary compatible with his target device.

_Mark Radbourne MSFT_

**Comment by lakshmisivareddy** [comment]
Hi @markrad  your correct i checked his toolchain.cmake file he is referring system rootfs 
referring that i gave that comment , thanks for  updating it

**Comment by markrad** [comment]
For the benefit of anyone else who might visit this page looking for help cross compiling the Azure IoT SDK for C, I have put together a dockerfile that downloads a toolchain, in this case for WRTnode, OpenSSL, curl and util-Linux. There are then cross compiled for the device. Following that the Azure IoT SDK for C is built against the new binaries.

```dockerfile
FROM ubuntu:latest

# Run commands that require root authority
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y cmake git wget

RUN useradd -d /home/builder -ms /bin/bash -G sudo -p builder builder

# Switch to new user
USER builder
WORKDIR /home/builder

# Download all required files
RUN mkdir MIPSBuild
WORKDIR MIPSBuild

# Cross compile toolchain
RUN wget https://downloads.openwrt.org/barrier_breaker/14.07/ramips/mt7620n/OpenWrt-Toolchain-ramips-for-mipsel_24kec%2bdsp-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
RUN tar -xvf OpenWrt-Toolchain-ramips-for-mipsel_24kec+dsp-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2

# Azure IoT SDK for C
RUN git clone --recursive https://github.com/azure/azure-iot-sdk-c.git

# OpenSSL
RUN wget https://www.openssl.org/source/openssl-1.0.2o.tar.gz
RUN tar -xvf openssl-1.0.2o.tar.gz

# Curl
RUN wget http://curl.haxx.se/download/curl-7.60.0.tar.gz
RUN tar -xvf curl-7.60.0.tar.gz

# Linux utilities for libuuid
RUN wget https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.32/util-linux-2.32-rc2.tar.gz
RUN tar -xvf util-linux-2.32-rc2.tar.gz

# Set up environment variables in preperation for the builds to follow
ENV WORK_ROOT=/home/builder/MIPSBuild
ENV TOOLCHAIN_ROOT=${WORK_ROOT}/OpenWrt-Toolchain-ramips-for-mipsel_24kec+dsp-gcc-4.8-linaro_uClibc-0.9.33.2
ENV TOOLCHAIN_SYSROOT=${TOOLCHAIN_ROOT}/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2
ENV TOOLCHAIN_EXES=${TOOLCHAIN_SYSROOT}/bin
ENV TOOLCHAIN_NAME=mipsel-openwrt-linux-uclibc
ENV AR=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-ar
ENV AS=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-as
ENV CC=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-gcc
ENV LD=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-ld
ENV NM=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-nm
ENV RANLIB=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-ranlib

ENV LDFLAGS="-L${TOOLCHAIN_SYSROOT}/usr/lib"
ENV LIBS="-lssl -lcrypto -ldl -lpthread"
ENV TOOLCHAIN_PREFIX=${TOOLCHAIN_SYSROOT}/usr
ENV STAGING_DIR=${TOOLCHAIN_SYSROOT}

# Build OpenSSL
WORKDIR openssl-1.0.2o
RUN ./Configure linux-generic32 shared --prefix=${TOOLCHAIN_PREFIX} --openssldir=${TOOLCHAIN_PREFIX}
RUN make
RUN make install
WORKDIR ..

# Build curl
WORKDIR curl-7.60.0
RUN ./configure --with-sysroot=${TOOLCHAIN_SYSROOT} --prefix=${TOOLCHAIN_PREFIX} --target=${TOOLCHAIN_NAME} --with-ssl --with-zlib --host=${TOOLCHAIN_NAME} --build=x86_64-pc-linux-uclibc; cat config.log
RUN make
RUN make install
WORKDIR ..

# Build uuid
WORKDIR util-linux-2.32-rc2
RUN ./configure --prefix=${TOOLCHAIN_PREFIX} --with-sysroot=${TOOLCHAIN_SYSROOT} --target=${TOOLCHAIN_NAME} --host=${TOOLCHAIN_NAME} --disable-all-programs  --disable-bash-completion --enable-libuuid
RUN make
RUN make install
WORKDIR ..

WORKDIR azure-iot-sdk-c
RUN mkdir cmake
WORKDIR cmake

# Create a toolchain file on the fly
RUN echo "SET(CMAKE_SYSTEM_NAME Linux)     # this one is important" > toolchain.cmake
RUN echo "SET(CMAKE_SYSTEM_VERSION 1)      # this one not so much" >> toolchain.cmake
RUN echo "SET(CMAKE_SYSROOT ${TOOLCHAIN_SYSROOT})" >> toolchain.cmake
RUN echo "SET(CMAKE_C_COMPILER ${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-gcc)" >> toolchain.cmake
RUN echo "SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-g++)" >> toolchain.cmake
RUN echo "SET(CMAKE_FIND_ROOT_PATH $ENV{TOOLCHAIN_SYSROOT})" >> toolchain.cmake
RUN echo "SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)" >> toolchain.cmake
RUN echo "SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)" >> toolchain.cmake
RUN echo "SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)" >> toolchain.cmake
RUN echo "SET(set_trusted_cert_in_samples true CACHE BOOL \"Force use of TrustedCerts option\" FORCE)" >> toolchain.cmake

RUN cmake -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake -DCMAKE_INSTALL_PREFIX=${TOOLCHAIN_PREFIX} ..
RUN make
RUN make install

WORKDIR ..
RUN ls -al ${TOOLCHAIN_PREFIX}/lib
RUN ls -al ${TOOLCHAIN_PREFIX}/include
```
If you have docker installed you can run this file by putting it in its own directory and, from that directory, issue the command:
```bash
docker build -t mipsbuild:latest . --network=host
```

_Mark Radbourne MSFT_

**Comment by Pavan2358** [comment]
Hi @markrad @lakshmisivareddy and others

I was able to cross compile successfully with mips32 compiler and run it on my target machine, **but I one problem I want to cross compile iothub_ll_telemetry_sample alone with my toolchain....Can anyone tell me how to compile one sample program without building all the samples and test samples**
Please help:(

**Comment by markrad** [comment]
Hi @Pavan2358,

I made a small change to my Dockerfile above. I found out that there is not a file editor in the image so I added nano to the apt-get install line. Once you have an editor you can do the following:
Start your docker container with the command
```
docker run -i -t mipsbuild
```
This will bring you to a command prompt in your docker container. From there you can issue:
```
cd ~/MIPSBuild/azure-iot-sdk-c/iothub_client/samples/iothub_ll_telemetry_sample/
nano iothub_ll_telemetry_sample.c
```
Make your required changes to the sample such as adding your connection string
```
cd ../../../cmake/
make
```
The make command will only build the changed files which, in this case, will be iothub_ll_telemetry_sample.c. Hopefully this will answer your questions.

_Mark Radbourne MSFT_

**Comment by Pavan2358** [comment]
Hi @markrad @lakshmisivareddy 

**I actually want to use the sample code in my makefile that I have created to do other things and which in turn calls telemetry sample api to send it to the cloud, without using cmake how to normally compile the telemetry sample program like for ex: gcc iothub_ll_telemetry sample.c <with other dependecies>?**
Please help:(

**Comment by markrad** [comment]
HI @Pavan2358, 

As in your example, you need to use the compiler from the toolchain (rather than gcc from the host) and add flags to tell the compiler where to find the included headers and the libraries it needs to link with. If you only have one file you don't even need to use make. You can just type the command to invoke the compiler with the required flags and source file name into the command line and it will get built (assuming you have all the flags entered correctly). 

I can't go into much detail here because using make is not within the scope of an issue in this GitHub repository. There are many webpages that describe this process. Try this one for example: http://www.fabriziodini.eu/posts/cross_compile_tutorial/.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Closing issue.
