### ISSUE TITLE
MQTT iothubtransport_mqtt_common.c (IOTHUB_SDK_VERSION "1.2.1" vs IOTHUB_SDK_VERSION "1.2.2")

### ISSUE THREAD

**Issue by VitSolcik** [Azure/azure-iot-sdk-c#487]
Hi,

I am using iothub_ll_client with MQTT protocol, after I updated library on version 1.2.2 from version 1.2.1
I am getting these errors:

> IoTHubClient_LL_SetMessageCallback...successful.
> IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
> Error: Time:Mon May 14 14:07:50 2018 File:C:\GIT4\mcu-sdk-2.0\middleware\azure_iot\c-utility\src\optionhandler.c Func:OptionHandler_FeedOptions
> Line:238 failure while trying to _SetOption
> Error: Time:Mon May 14 14:07:50 2018 File:C:\GIT4\mcu-sdk-2.0\middleware\azure_iot\c-utility\src\xio.c Func:xio_setoption 
> Line:187 unable to OptionHandler_FeedOptions
> Error: Time:Mon May 14 14:07:50 2018 File:C:\GIT4\mcu-sdk-2.0\middleware\azure_iot\c-utility\src\optionhandler.c Func:OptionHandler_FeedOptions
> Line:238 failurewhile trying to _SetOption
> Error: Time:Mon May 14 14:07:50 2018 File:C:\GIT4\mcu-sdk-2.0\middleware\azure_iot\iothub_client\src\iothubtransport_mqtt_common.c Func:GetTransportProviderIfNecessary 
> Line:1635 Failed feeding existing options to new TLS instance.

As I understand it's caused by this code segment in iothubtransport_mqtt_common.c file:

```
if (transport_data->saved_tls_options != NULL)
{
    if (OptionHandler_FeedOptions(transport_data->saved_tls_options, transport_data->xioTransport) != OPTIONHANDLER_OK)
    {
        LogError("Failed feeding existing options to new TLS instance.");
        result = __FAILURE__;
    }
    else
    {
        // The tlsio has the options, so our copy can be deleted
        set_saved_tls_options(transport_data, NULL);
        result = 0;
    }
}
```
I am using socketio_berkeley.

Please, do you have any idea what could be wrong?

Thanks for reply,
Vit.

**Comment by VitSolcik** [comment]
Hi again,

after some debugging and git reversing I figure out, that this problem dissapear if you aren't using new
ResetConnectionIfNecessary function in iothubtransport_mqtt_common.c 

```
// Prior to creating a new connection, if we have an existing xioTransport we need to clear 
// it now or else cached settings (especially TLS when communicating with HTTP proxies) will 
// break reconnection attempt.  
static void ResetConnectionIfNecessary(PMQTTTRANSPORT_HANDLE_DATA transport_data)
{
    if (transport_data->xioTransport != NULL)
    {
        OPTIONHANDLER_HANDLE options = xio_retrieveoptions(transport_data->xioTransport);
        set_saved_tls_options(transport_data, options);

        xio_destroy(transport_data->xioTransport);
        transport_data->xioTransport = NULL;
    }
}
```

**Comment by jebrando** [comment]
@VitSolcik Thank you for the issues, I will dig into it and make sure there is not problems.

**Comment by jebrando** [comment]
@VitSolcik I am unable to reproduce the issue in the latest version.  Let me know if you see any more issues.
