### ISSUE TITLE
Device twin not updating when using transport

### ISSUE THREAD

**Issue by AndWass** [Azure/azure-iot-sdk-c#491]
- **OS and version used:** Windows 10 

- **SDK version used:** 2018-05-04 

# Description of the issue:
Sending device twin reported state does not work if client handle is created with a transport. Event if the transport only has one device associated with it.

# Code sample exhibiting the issue:
```C
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full
// license information.

#include <stdio.h>
#include <stdlib.h>

#include "azure_c_shared_utility/crt_abstractions.h"
#include "azure_c_shared_utility/macro_utils.h"
#include "azure_c_shared_utility/platform.h"
#include "azure_c_shared_utility/threadapi.h"
#include "iothub_client.h"
#include "iothub_client_options.h"
#include "iothub_message.h"

// The protocol you wish to use should be uncommented
//
#define SAMPLE_AMQP
//#define SAMPLE_MQTT_OVER_WEBSOCKETS
//#define SAMPLE_AMQP
//#define SAMPLE_AMQP_OVER_WEBSOCKETS
//#define SAMPLE_HTTP

#ifdef SAMPLE_MQTT
#include "iothubtransportmqtt.h"
#endif // SAMPLE_MQTT
#ifdef SAMPLE_MQTT_OVER_WEBSOCKETS
#include "iothubtransportmqtt_websockets.h"
#endif // SAMPLE_MQTT_OVER_WEBSOCKETS
#ifdef SAMPLE_AMQP
#include "iothubtransportamqp.h"
#endif // SAMPLE_AMQP
#ifdef SAMPLE_AMQP_OVER_WEBSOCKETS
#include "iothubtransportamqp_websockets.h"
#endif // SAMPLE_AMQP_OVER_WEBSOCKETS
#ifdef SAMPLE_HTTP
#include "iothubtransporthttp.h"
#endif // SAMPLE_HTTP

#ifdef SET_TRUSTED_CERT_IN_SAMPLES
#include "certs.h"
#endif // SET_TRUSTED_CERT_IN_SAMPLES

static bool g_continueRunning;
#define DOWORK_LOOP_NUM 3

static void deviceTwinCallback(DEVICE_TWIN_UPDATE_STATE update_state,
                               const unsigned char *payLoad, size_t size,
                               void *userContextCallback)
{
    (void)userContextCallback;

    printf("Device Twin update received (state=%s, size=%zu): %s\r\n",
           ENUM_TO_STRING(DEVICE_TWIN_UPDATE_STATE, update_state), size,
           payLoad);
}

static void reportedStateCallback(int status_code, void *userContextCallback)
{
    (void)userContextCallback;
    printf(
        "Device Twin reported properties update completed with result: %d\r\n",
        status_code);

    g_continueRunning = false;
}

void iothub_client_sample_device_twin_run(void)
{
    IOTHUB_CLIENT_TRANSPORT_PROVIDER protocol;
    IOTHUB_CLIENT_HANDLE iotHubClientHandle;
    g_continueRunning = true;

// Select the Protocol to use with the connection
#ifdef SAMPLE_MQTT
    protocol = MQTT_Protocol;
#endif // SAMPLE_MQTT
#ifdef SAMPLE_MQTT_OVER_WEBSOCKETS
    protocol = MQTT_WebSocket_Protocol;
#endif // SAMPLE_MQTT_OVER_WEBSOCKETS
#ifdef SAMPLE_AMQP
    protocol = AMQP_Protocol;
#endif // SAMPLE_AMQP
#ifdef SAMPLE_AMQP_OVER_WEBSOCKETS
    protocol = AMQP_Protocol_over_WebSocketsTls;
#endif // SAMPLE_AMQP_OVER_WEBSOCKETS
#ifdef SAMPLE_HTTP
    protocol = HTTP_Protocol;
#endif // SAMPLE_HTTP

    if (platform_init() != 0)
    {
        (void)printf("Failed to initialize the platform.\r\n");
    }
    else
    {
        TRANSPORT_HANDLE transport = IoTHubTransport_Create(
            AMQP_Protocol, "[hub name]", "azure-devices.net");

        IOTHUB_CLIENT_CONFIG client_config;
        // This must be done to ensure that fields are correctly set to null
        // etc.
        std::memset(&client_config, 0, sizeof(client_config));
        client_config.deviceId = "[device id]";
        client_config.deviceKey =
            "[device key]";
        client_config.protocol = AMQP_Protocol;

        client_config.iotHubName = "[hub name]";
        client_config.iotHubSuffix = "azure-devices.net";

        // iotHubClientHandle = IoTHubClient_Create(&client_config);
        // Comment the line below and uncomment the line above for demo to work
        iotHubClientHandle =
            IoTHubClient_CreateWithTransport(transport, &client_config);
        if (!iotHubClientHandle)
        {
            (void)printf("ERROR: iotHubClientHandle is NULL!\r\n");
        }
        else
        {
            bool traceOn = true;
            const char *reportedState = "{ \"device_property\": \"WHEEEEEEE\"}";
            size_t reportedStateSize = strlen(reportedState);

            (void)IoTHubClient_SetOption(iotHubClientHandle, OPTION_LOG_TRACE,
                                         &traceOn);

            (void)IoTHubClient_SetDeviceTwinCallback(
                iotHubClientHandle, deviceTwinCallback, iotHubClientHandle);
            (void)IoTHubClient_SendReportedState(
                iotHubClientHandle, (const unsigned char *)reportedState,
                reportedStateSize, reportedStateCallback, iotHubClientHandle);

            do
            {
                ThreadAPI_Sleep(1);
            } while (g_continueRunning);

            for (size_t index = 0; index < DOWORK_LOOP_NUM; index++)
            {
                ThreadAPI_Sleep(1);
            }

            IoTHubClient_Destroy(iotHubClientHandle);
        }
        platform_deinit();
    }
}

int main(void)
{
    iothub_client_sample_device_twin_run();
    return 0;
}

```
# Console log of the issue:
Log of non-working sample:
```
-> Header (AMQP 0.1.0.0)
<- Header (AMQP 0.1.0.0)
-> [OPEN]* {28e7a63d-848a-48b7-878f-fb6650215be6,REDACTED.azure-devices.net,4294967295,65535,240000}
<- [OPEN]* {DeviceGateway_cdeaac5ddb16476ab809fe3eb3d93065,10.0.4.70,65536,8191,240000,NULL,NULL,NULL,NULL,NULL}
-> [BEGIN]* {NULL,0,4294967295,100,4294967295}
<- [BEGIN]* {0,1,5000,4294967295,262143,NULL,NULL,NULL}
-> [ATTACH]* {$cbs-sender,0,false,0,0,* {$cbs},* {$cbs},NULL,NULL,0,0}
-> [ATTACH]* {$cbs-receiver,1,true,0,0,* {$cbs},* {$cbs},NULL,NULL,NULL,0}
<- [ATTACH]* {$cbs-sender,0,true,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,NULL}
<- [FLOW]* {0,5000,1,4294967295,0,0,100,0,NULL,false,NULL}
-> [TRANSFER]* {0,0,<01 00 00 00>,0,false,false}
<- [ATTACH]* {$cbs-receiver,1,false,0,0,* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,1048576,NULL,NULL,NULL}
-> [FLOW]* {1,4294967295,1,99,1,0,10000}
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
<- [TRANSFER]* {1,0,<01 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,0,0,true,* {}}
-> [ATTACH]* {link-snd-REDACTED-ae0a59c7-e491-44e8-9db3-00ed32d139a1,2,false,0,0,* {link-snd-REDACTED-ae0a59c7-e491-44e8-9db3-00ed32d139a1-source},* {amqps://REDACTED.azure-devices.net/devices/REDACTED/messages/events},NULL,NULL,0,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.2.4 (native; WindowsProduct:0x00000030 6.2; x64)]}}
-> [ATTACH]* {link-snd-REDACTED-2e012b23-057e-4864-9907-1251c0a71f25,3,false,0,0,* {link-snd-REDACTED-2e012b23-057e-4864-9907-1251c0a71f25-source},* {amqps://REDACTED.azure-devices.net/devices/REDACTED/twin},NULL,NULL,0,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.2.4 (native; WindowsProduct:0x00000030 6.2; x64)],[com.microsoft:channel-correlation-id:twin:c123c82c-26fb-4493-85b9-d181e9ca9176],[com.microsoft:api-version:2016-11-14]}}
<- [ATTACH]* {link-snd-REDACTED-ae0a59c7-e491-44e8-9db3-00ed32d139a1,2,true,0,NULL,* {link-snd-REDACTED-ae0a59c7-e491-44e8-9db3-00ed32d139a1-source,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {amqps://REDACTED.azure-devices.net/devices/REDACTED/messages/events,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.2.4 (native; WindowsProduct:0x00000030 6.2; x64)]}}
<- [FLOW]* {1,5000,2,4294967295,2,0,1000,0,NULL,false,NULL}
<- [ATTACH]* {link-snd-REDACTED-2e012b23-057e-4864-9907-1251c0a71f25,3,true,1,0,* {link-snd-REDACTED-2e012b23-057e-4864-9907-1251c0a71f25-source,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {amqps://REDACTED.azure-devices.net/devices/REDACTED/twin,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.2.4 (native; WindowsProduct:0x00000030 6.2; x64)],[com.microsoft:channel-correlation-id:twin:c123c82c-26fb-4493-85b9-d181e9ca9176],[com.microsoft:api-version:2016-11-14]}}
<- [FLOW]* {1,5000,2,4294967295,3,0,1000,0,NULL,false,NULL}
-> [ATTACH]* {link-rcv-REDACTED-5e4d2092-d247-4d9c-812c-c905bb80e8ea,4,true,0,0,* {amqps://REDACTED.azure-devices.net/devices/REDACTED/twin},* {link-rcv-REDACTED-5e4d2092-d247-4d9c-812c-c905bb80e8ea-target},NULL,NULL,NULL,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.2.4 (native; WindowsProduct:0x00000030 6.2; x64)],[com.microsoft:channel-correlation-id:twin:c123c82c-26fb-4493-85b9-d181e9ca9176],[com.microsoft:api-version:2016-11-14]}}
<- [ATTACH]* {link-rcv-REDACTED-5e4d2092-d247-4d9c-812c-c905bb80e8ea,4,false,1,0,* {amqps://REDACTED.azure-devices.net/devices/REDACTED/twin,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {link-rcv-REDACTED-5e4d2092-d247-4d9c-812c-c905bb80e8ea-target,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.2.4 (native; WindowsProduct:0x00000030 6.2; x64)],[com.microsoft:channel-correlation-id:twin:c123c82c-26fb-4493-85b9-d181e9ca9176],[com.microsoft:a

```

**Comment by ewertons** [comment]
Hi @Shakti213 , this would be a bug. 
Let us investigate to confirm the issue.
Thanks.

**Comment by massand** [comment]
@ewertons, @AndWass  - were you able to repro this issue with the latest 11-20-2018 release?

**Comment by ksaye** [comment]
All, I am seeing the same issue, using a Node client from our SDK and using the transparent gateway.  It processes TWINs for the first 5 - 10 seconds, and then never again (unless you reboot the client).

**Host OS:**  Ubuntu 16.04 (Linux 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)
**EdgeAgent:**  1.0.6.19913336
**EdgeHub:**     1.0.6.19913336
**Node Version:**  v11.11.0

Gateway configured per: [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway]

Viewing the edgeHub, I do see the subscription:
2019-03-08 22:30:16.852 +00:00 [INF] - New cloud connection created for device leafDevice
2019-03-08 22:30:16.852 +00:00 [INF] - Authenticated leafDevice with IotHub
2019-03-08 22:30:16.922 +00:00 [INF] - New device connection for device leafDevice
2019-03-08 22:30:16.963 +00:00 [INF] - Bind device proxy for device leafDevice
2019-03-08 22:30:16.970 +00:00 [INF] - Initialized device listener in the AMQP protocol head for leafDevice
2019-03-08 22:30:17.021 +00:00 [INF] - Processing subscription C2D for client leafDevice.
2019-03-08 22:30:17.022 +00:00 [INF] - Start listening for C2D messages for device leafDevice
2019-03-08 22:30:17.095 +00:00 [INF] - Opened link TwinReceiving for leafDevice
2019-03-08 22:30:17.238 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client leafDevice.
2019-03-08 22:30:17.255 +00:00 [INF] - Opened link C2D for leafDevice
2019-03-08 22:30:18.563 +00:00 [INF] - Opened link TwinSending for leafDevice
2019-03-08 22:30:18.711 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client leafDevice.


Node Client Code, from our sample:
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

'use strict';

var fs = require('fs');
var Protocol = require('azure-iot-device-mqtt').Mqtt;
// Uncomment one of these transports and then change it in fromConnectionString to test other transports
// var Protocol = require('azure-iot-device-http').Http;
// var Protocol = require('azure-iot-device-amqp').Amqp;
var Client = require('azure-iot-device').Client;
var Message = require('azure-iot-device').Message;

// 1) Obtain the connection string for your downstream device and to it
//    append this string GatewayHostName=<edge device hostname>;
// 2) The Azure IoT Edge device hostname is the hostname set in the config.yaml of the Azure IoT Edge device
//    to which this sample will connect to.
//
// The resulting string should look like the following
//  "HostName=<iothub_host_name>;DeviceId=<device_id>;SharedAccessKey=<device_key>;GatewayHostName=<edge device hostname>"
var connectionString = 'HostName=XXXXXXXXXXX.azure-devices.net;DeviceId=leafDevice;SharedAccessKey=x4bXXXXXXXXXXXLKsPqgy8=;GatewayHostName=nuc';

// Path to the Edge "owner" root CA certificate
var edge_ca_cert_path = '/certs/azure-iot-test-only.root.ca.cert.pem';

// fromConnectionString must specify a transport constructor, coming from any transport package.
var client = Client.fromConnectionString(connectionString, Protocol);

var connectCallback = function (err) {
  if (err) {
    console.error('Could not connect: ' + err.message);
  } else {
    console.log('Client connected');
    
    // Create device Twin
    client.getTwin(function(err, twin) {
          if (err) {
        console.error('could not get twin');
      } else {
        console.log('twin created');
        
        twin.on('properties.desired', function(delta) {
            console.log('new desired properties received:');
            console.log(JSON.stringify(delta));
        });
        
      };
    });

    // Create a message and send it to the IoT Hub every two seconds
    var sendInterval = setInterval(function () {
      var windSpeed = 10 + (Math.random() * 4); // range: [10, 14]
      var temperature = 20 + (Math.random() * 10); // range: [20, 30]
      var humidity = 60 + (Math.random() * 20); // range: [60, 80]
      var data = JSON.stringify({ deviceId: 'myFirstDownstreamDevice', windSpeed: windSpeed, temperature: temperature, humidity: humidity });
      var message = new Message(data);
      message.properties.add('temperatureAlert', (temperature > 28) ? 'true' : 'false');
      console.log('Sending message: ' + message.getData());
      client.sendEvent(message, printResultFor('send'));
    }, 600000);
    
    client.on('message', function (msg) {
      console.log('Id: ' + msg.messageId + ' Body: ' + msg.data);
      // When using MQTT the following line is a no-op.
      client.complete(msg, printResultFor('completed'));
      // The AMQP and HTTP transports also have the notion of completing, rejecting or abandoning the message.
      // When completing a message, the service that sent the C2D message is notified that the message has been processed.
      // When rejecting a message, the service that sent the C2D message is notified that the message won't be processed by the device. the method to use is client.reject(msg, callback).
      // When abandoning the message, IoT Hub will immediately try to resend it. The method to use is client.abandon(msg, callback).
      // MQTT is simpler: it accepts the message by default, and doesn't support rejecting or abandoning a message.
    });

    client.on('error', function (err) {
      console.error(err.message);
    });

    client.on('disconnect', function () {
      clearInterval(sendInterval);
      client.removeAllListeners();
      client.open(connectCallback);
    });
  }
};

// Provide the Azure IoT device client via setOptions with the X509
// Edge root CA certificate that was used to setup the Edge runtime
var options = {
  ca : fs.readFileSync(edge_ca_cert_path, 'utf-8'),
};

client.setOptions(options, function(err) {
  if (err) {
    console.log('SetOptions Error: ' + err);
  } else {
    client.open(connectCallback);
  }
});

// Helper function to print results in the console
function printResultFor(op) {
  return function printResult(err, res) {
    if (err) console.log(op + ' error: ' + err.toString());
    if (res) console.log(op + ' status: ' + res.constructor.name);
  };
}

**Comment by cwluxul** [comment]
I am also experiencing this issue using the C-SDK.  I'm currently using version '2019-04-11' of the C-SDK.  If I make my connection with the following code (specific to my app):
`std::stringstream connectionString; connectionString << "HostName=XXXXXX.azure-devices.net;DeviceId=" << device_id << ";SharedAccessKey=" << device_key << "";
    if ((tmp_device_handle = IoTHubDeviceClient_CreateFromConnectionString(connectionString.str().c_str(), protocol_)) == NULL)`

Then the reported properties of a device twin will update and the 'reportedStateCallback' is called.

If I make my connection with the following code (again, specific to my app):
`if (( tmp_device_handle = IoTHubDeviceClient_CreateWithTransport(this->transport_handle_, &client_config1)) == nullptr)`

Then the reported properties of a device twin will NOT update and the 'reportedStateCallback' is never called.  In my code I can simply comment and uncomment to switch between these two methods to change the behavior from working to not working.

**Comment by SeriousD** [comment]
I had exactly the same issue and found a workaround by using 
`IOTHUB_CLIENT_HANDLE IoTHubClient_Create(const IOTHUB_CLIENT_CONFIG* config)`
The config can contain all information provided by the transport handle, the only thing you cant to is connection multiplexing.

**Comment by cwluxul** [comment]
SeriousD,

Thank you for the suggestion, and hopefully it helps someone.  In my case my library is used by two applications.  One where I use multiplexing and one where I don't.  For me I had to pass a flag down to the connect method I created and when I'm multiplexing the connection I CreateWithTransport, and when I'm using a single connection I use CreateFromConnectionString.  Total hack but it works.  Another super lucky coincidence with my particular application is that I only need device twins to work when I'm not multiplexing the connection.  If I needed the device twins to work on the multiplexed connection I would be completely stuck.  I'm very surprised how broken this is and the lack of official response to what appears to be a clear defect, which has been reproduced over several release versions across multiple operating systems.

**Comment by ericwol-msft** [comment]
This only happens on AMQP multiplexing for this C SDK. Please consider using the C# IoT SDK.

**Comment by dmcamens-legrand** [comment]
@ericwol-msft We are experiencing this issue on an embedded linux system that is based on C++.  We are unable to use C#.  Can you reopen this issue?  This is blocking us because we have to use AMQP multiplexing in our application.
