### ISSUE TITLE
documentation: group enrollment - custom HSM with x509 certs

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#492]
- **OS and version used:** mac OS 10.12.3
- **SDK version used:** 1.2.4

# Description of the issue:
The existing documentation[1] and samples[2] explains steps on using custom HSM with individual enrolment. But they don't cover group enrolment well for C SDK. Unlike Java or Node.JS SDKs, there are no docs or samples. Closest is this comment[3] in response to GitHub issue. It appears it asks to upload both leaf and intermediate. But it is ambiguous. 

I will create root, intermediate and leaf certificates as specified using `certGen.sh`[4]. But, what should be returned from each of `custom_hsm_get_certificate`, `custom_hsm_get_alias_key` and `custom_hsm_get_common_name` ? Please provide code sample to do group enrolment.

[1] https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509
[2] https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_custom_hsm.md
[3] https://github.com/Azure/azure-iot-sdk-c/issues/437#issuecomment-379410547
[4] https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md#step-2---create-the-certificate-chain

**Comment by lakshmisivareddy** [comment]
Hi @kiranpradeep
if you are going with  root, intermediate and leaf certificates & do Group Enrollment 
 In Azure Portal in DPS in Group Enrollment 
you can Go with CA or Intermediate  & Verify it 
custom_hsm_get_certificate should contain your Device cert,intermediate cert,CA cert
custom_hsm_get_alias_key should contain your Device Private Key 
custom_hsm_get_common_name should contain Device cert common name

**Comment by jebrando** [comment]
@kiranpradeep Thank you for your comments, I will add some documentation to better describe group enrollments in the C SDK.

**Comment by kiranpradeep** [comment]
@jebrando Even forgetting the documentation, there is neither a source sample nor a simple README.md to do group provisioning with this SDK.

**Comment by jebrando** [comment]
@kiranpradeep From a device perspective Group enrollment & individual enrollment are exactly the same.  The device will return the certificate chain the same way and the service makes the determination of how to do group or individual enrollments.  I will admit having that above statement in some md file will help.

**Comment by kiranpradeep** [comment]
Part of question remains unanswered. 
1. What should be returned on `custom_hsm_get_common_name` for group enrollment. Yes, I can assume that is leaf name. But not specified.
2. Even now no where it is specified what should be certificate format(PEM/DER etc) other than in my earlier Github ticket. Also no where in C SDK it is specified we should limit alphanumeric and hyphens in common name. The lib user will need to read Node.JS SDK docs to get to that point.

Please imagine what a new developer have to go through to get this working. They are not at lib developers expertise level. The point I want to bring out is, things like these are left unspecified and left to the imagination or common sense of lib user (azure-iot-sdk-c) which shouldn't be the case. Also, regarding functionality, the point of HSM is keys never leave the HSM. That is broken from beginning. Yes, lib user can modify this open source library to make sure keys never leaves HSM. But again, the provisioning service is a paid service. Regarding HSM functionality or C SDK documentation, this provisioning service as of today, is better left in public preview.

The intention is not to be offensive here. Just letting developers know the thoughts.

**Comment by krakorar-mesh** [comment]
Please provide and example of group enrollment.

**Comment by AjiGopal** [comment]
@kiranpradeep  @jebrando @lakshmisivareddy 

We are looking for the same group enrollment code in c SDK. So kindly share some sample codes or the supporting documents as soon as possible.
