### ISSUE TITLE
How to use "http_proxy_io" with "httpapi_compact"?

### ISSUE THREAD

**Issue by mohamedibrahimabdelrahman33** [Azure/azure-iot-sdk-c#495]
- **OS and version used:** <VERSION>  FreeRTOS v9.0.0
STM32F769I-Disco Kit

- **SDK version used:** <VERSION>  azure-iot-sdk-c :  v1.1.31

# Description of the issue:
 currently i'm  using HTTP protocol to send massages to the HUB and now  i'm trying to use proxy configuration, so i want to use "http_proxy_io" file with httpapi_compact but i found that the proxy option is not in the "httpapi_compact" file, so what should i do?

# Code sample exhibiting the issue:
Currently I'm using the example 'iothub_client_sample_http'  

# Console log of the issue:

**Comment by mohamedibrahimabdelrahman33** [comment]
hey jebrando, is there any update my question?

**Comment by jebrando** [comment]
@mohamedibrahimabdelrahman33 We don't want to make enhancements to httpapi_compact, due to the lack of http protocol features.  Is there any reason you are using http for communications and not MQTT?

**Comment by mohamedibrahimabdelrahman33** [comment]
hey @jebrando , due to the project requirements i have to use the http protocol, because Corporate networks typically block most outgoing ports. and Port 80 is not optimal for MQTT traffic, and i know that i can Use MQTT over websockets. This may work with some HTTP Proxies if websockets are supported, but not definitely.

**Comment by jebrando** [comment]
@mohamedibrahimabdelrahman33 We don't have updating http_compact on our backlog at the moment. 
 Also are you using iothub client to send messages, I am unaware of http_compact being compatible with iothub client.

**Comment by mohamedibrahimabdelrahman33** [comment]
yes, i'm using iothub client to send messages, and httpapi_compact works fine with iothub client.

**Comment by jspaith** [comment]
I'm closing since as I said, I think we've addressed your concerns as we can here.  If I've misread or you have other followups, as always reactivate this or open a new issue.
