### ISSUE TITLE
include transport static library to libprov_device_client.so

### ISSUE THREAD

**Issue by syedelec** [Azure/azure-iot-sdk-c#496]
- **OS and version used:** <VERSION> 
Ubuntu

- **SDK version used:** <VERSION> 
master

# Description of the issue:

When compiling a DPS application linking with `-lprov_device_client`, I still need to link against static library corresponding to the correct protocol I am using (e.g: AMQP_WS `-lprov_amqp_ws_transport`)

I thought that linking was done the same way as iothub_client library, all static library are included in the dynamic library. Instead we should use the `use_amqp` or `use_http` options in cmake to select the needed transport

The error is :
`undefined reference to "Prov_Device_AMQP_WS_Protocol"`

# Code sample exhibiting the issue:
N/A

# Console log of the issue:

`undefined reference to 'Prov_Device_AMQP_WS_Protocol'`
`collect2: error: ld returned 1 exit status`

**Comment by jebrando** [comment]
Currently for DPS we try to minimize dependencies that are automatically included and require the user to add the libraries.  I don't believe that add the protocol library is not an unreasonable request, but I shall talk to the project managers to see if this should remain this way.

**Comment by jebrando** [comment]
I has been decided that requiring the library is a step that must be done.  Thank you for the issue.
