### ISSUE TITLE
C2D message vs Device Methods - usage suggestion

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#500]
We need to initiate actions on device which could be online or offline. DeviceMethods fail if device is offline. On S1 tier IoTHub, we can only have 1 scheduled job. 

C2D messages has a retention period of 7 days. Is it advisable to use C2D over device methods to handle scenarios when device could be offline?

**Comment by jspaith** [comment]
I've asked around and we do have documentation on this - https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-c2d-guidance

In general we're encouraging twin and direct method usage over c2d, though you'll need to be conscious of twin size & throttling limits.

Does this doc help?  If not, we'd definitely appreciate your feedback (either through this GH issue and I can relay on, though probably feedback on doc will be fastest).
