### ISSUE TITLE
Problems compiling a C proyect.

### ISSUE THREAD

**Issue by yoyonstantine** [Azure/azure-iot-sdk-c#502]
Hi, I'm download and build the azure c iot sdk and run a example an every thing complile good, but when i try complile a custom proyect shown me this error:

![image](https://user-images.githubusercontent.com/11838259/40622407-79dc8900-626f-11e8-9452-83b677536832.png)

But if i'm going to this directory the archive exist but i dont know why can't compile. this occurs when use a cmake to create a makefile and when y do the make file. 

Cmake: This is my cmake.txt

![image](https://user-images.githubusercontent.com/11838259/40622484-e801c51c-626f-11e8-83b4-691dbc022ab4.png)

makefile: This is my own makefile
![image](https://user-images.githubusercontent.com/11838259/40622519-0a432756-6270-11e8-895f-3795441dc820.png)

If annyone can helpme with this, i'm be glad.

PD. I'm using a raspberry pi, and use this method to instal de azure c iothub sdk.
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md

**Comment by jspaith** [comment]
A few things- 1st before you get too deep into using the serializer, you should understand it has some limitations. We'll (soon) be documenting this better, but for now https://github.com/Azure/azure-iot-sdk-c/issues/388#issuecomment-369992487 comment has some additional pros/cons.

RE the Makefile question here, I've never actually tried to hand-craft a makefile to play with the SDK.  I'm looking at the makefile that CMake generates on Ubuntu in "azure-iot-sdk-c/cmake/serializer/samples/devicetwin_simplesample" and its... complex.

When I'm building my personal test apps that I don't check into the main repro, I just use cmake here too.  So add_subdirectory(my_directory) and in the my_directory\CMakeLists.txt I copy from the {SomeSampleThatIsLikeWhatIAmBuilding}\CMakeLists.txt and modify it for my purposes.

If you really wanted to do a Makefile by hand - which again I'd be hesitant to do - you should examine the makefile's that cmake generates to understand what complexity you do & don't need.

**Comment by markrad** [comment]
Hi @yoyonstantine,

I didn't try this but I was under the impression that if you run make install on our SDK it will install into _/usr/**local**/include_ not _/usr/include_. You should ensure the file actually exists in the location you are attempting to include it from.

_Mark Radbourne MSFT_

**Comment by lakshmisivareddy** [comment]
Hi yoyonstantine,
as @markrad said all azure  includes will present in /usr/local/include 
check all the azure includes are present in /usr/local/include  from the above error i can tell it is unable to find serializer.h  if includes are properly copied it is present in /usr/local/include/azureiot/

**Comment by ewertons** [comment]
Hi @yoyonstantine ,

we will close the issue but feel free to reopen it if you would like to follow up or if you have further questions about it.
Thanks for using the Azure IoT SDKs.

**Comment by ewertons** [comment]
@yoyonstantine , thank you for your contribution to our open-sourced project!  
Please help us improve by filling out this 2-minute customer satisfaction survey.
