### ISSUE TITLE
Unchecked values causing potentially uninitialized variables

### ISSUE THREAD

**Issue by gmileka** [Azure/azure-iot-sdk-c#507]
- Windows 10 - 17624.180312-1347
- ModulePreview branch - snapshot on February.

# Description of the issue:

on_amqp_frame_received: The status of amqpvalue_get_ulong is not checked potentially leaving performative_ulong uninitialized. Target defined amqpvalue_get_ulong

<pre>
static void on_amqp_frame_received(void* context, uint16_t channel, AMQP_VALUE performative, const unsigned char* payload_bytes, uint32_t payload_size) 
{ 
CONNECTION_HANDLE connection = (CONNECTION_HANDLE)context; 

(void)channel; 

if (tickcounter_get_current_ms(connection->tick_counter, &connection->last_frame_received_time) != 0) 
{ 

...
uint64_t performative_ulong; <---- HERE 

if (connection->is_trace_on == 1) 
{ 
log_incoming_frame(performative); 
} 

if (is_open_type_by_descriptor(descriptor)) 
</pre>

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by ewertons** [comment]
Hi @gmileka ,
that is bug in the solution. It was already in our fix list, but with low priority (since the failures in the function would be really unexpected). 
But we will provide a fix soon. Thanks for bringing it up.

One note: for the next bugs related to submodules please file issues in their respective repos.

**Comment by ewertons** [comment]
Hi @gmileka , the bug has been fixed in uamqp repo, pending updating azure-iot-sdk-c to consume those changes.
https://github.com/Azure/azure-uamqp-c/commit/85e5c23bd28e6117a62f7d79fc4b88107716a52b

**Comment by ewertons** [comment]
@gmileka , the fix has been checked in and is available through the azure-iot-sdk-c.
Please verify, and feel free to reopen this issue if you would like to follow up.
Thanks for contributing to the Azure IoT SDKs!
