### ISSUE TITLE
Cross Compile Tutorial.

### ISSUE THREAD

**Issue by samanaz** [Azure/azure-iot-sdk-c#508]
Hi all,

It has been four weeks that I am trying to understand how to run a very simple Azure IoT hub C SDK on Raspberry and it is not possible.

I am using a windows 10 machine and latest version of Visual Studio 2017, Raspberry Pi 3 with Raspbian.
I can run the Blink simple app for Raspberry successfully. It works fine. I install all the prerequisites of the SDK by first running build_all/linux and then ./setup.sh. Then installing C-Shared library. Then umqtt as well as uamqp. At the end I install all the library by creating a cmake folder on the root folder of the SDK and run cmake command to install all the library.

I can confirm all the *.h files are installed under /usr/local/include/azureiot as well as  /usr/local/lib.
Please someone help me to understand this as it is taking a huge amount of time from me and there is no good instructions online.

I am new to programming and Azure IoT hub. I know networking very well but not programming.

I will appreciate if you can guide me to some tutorial or some video to being able to run my first app with the mentioned setup. I need to write my application in C so I need to use Azure Iot Hub C SDK.

Thanks

**Comment by samanaz** [comment]
I am a beginner and I would like to find a simple instruction to cross compile between windows (Visual Studio 2017) and Raspberry but there is no good instructions outside at all. It has been more than four weeks that I even could not run a simple demo.

Thanks to Microsoft there is no Tutorial about that. Not on Microsoft Virtual Academy. Not on Linda which is purchased by Microsoft. Not on on Channel 9. Not on Linkedin Academy which is the new version of Linda.

I am not sure why Microsoft needs so many teaching channels and on none of them there is a tutorial about it.

**Comment by markrad** [comment]
See my comments on your other post.

**Comment by massand** [comment]
We have added some documentation related to this topic here - #608
Let us know if there are any other gaps. Thanks!

**Comment by az-iot-builder-01** [comment]
@samanaz, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
