### ISSUE TITLE
CA Certificates created by Bash Script doesn't work

### ISSUE THREAD

**Issue by taroyutao** [Azure/azure-iot-sdk-c#511]
As [issue256 ](https://github.com/Azure/azure-iot-sdk-java/issues/256) in java sdk.

I follow the [document](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md) step by step.

When I use the powershell script in windows, everything works fine, and I can connect to my Iot hub in my device by cercertificate's info.

But when I followed the Bash script to create certificate step by step in linux, There is no problem in the generation of certificates. But when I used the information in certificates, it doesn't work.

From the readme:
The PS1 and Bash scripts are functionally equivalent.

Certificates generated in these two ways should all work properly. But the Bash script doesn't work.

I hava test the CA Certificates  in both java and C# SDK, the result is the same. Works fine by Powershell Script, but doesn't work in Bash Script.

**I think it may be an issue with the bash script?**

Thanks in advance.

**Comment by taroyutao** [comment]
Any update？

**Comment by jebrando** [comment]
@taroyutao When you say it doesn't work are you getting an error message, or is it that it doesn't connect?  Are you using this generated cert on a windows machine or linux?

**Comment by taroyutao** [comment]
Yes, I have written the detailed wrong information in issue [256](https://github.com/Azure/azure-iot-sdk-java/issues/256). 

Thanks.

**Comment by taroyutao** [comment]
Any update？

**Comment by jspaith** [comment]
Coming back to this one.  One of the problems here is that Java SDK wasn't handling intermediates correctly, which was fixed yesterday in https://github.com/Azure/azure-iot-sdk-java/commit/d79f860321148f7b8e8cd88f082a979526f5e8e7 and will be in next Java release.

@timtay-microsoft comment above ([More context on this issue including a possible solution in this issue discussion](https://github.com/Azure/azure-iot-sdk-java/issues/266)) should provide guidance for C# case & cert stores.

Will this address the issues here?

**Comment by taroyutao** [comment]
This issue can been closed.

Thank you very much for all your help.

**Comment by az-iot-builder-01** [comment]
@taroyutao, @Another007, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
