### ISSUE TITLE
Riot and utpm libraries missing files?

### ISSUE THREAD

**Issue by mohamedibrahimabdelrahman33** [Azure/azure-iot-sdk-c#512]
currently i using the "stm32f7-disco" kit to run "prov_dev_client_ll_sample.c".

- **OS and version used:** <VERSION>  freeRTOS v9
STM32F7 Kit

- **SDK version used:** <VERSION>  v1.1.31

# Description of the issue:

when i tried add Riot and utpm libraries i found that there are missing files, so the question is if the "prov_dev_client_ll_sample.c" in only work for windows platform?

# Code sample exhibiting the issue:
 prov_dev_client_ll_sample.c

# Console log of the issue:

**Comment by jebrando** [comment]
Currently we only support provisioning on Linux and Windows, but this does not mean that you can't build the code on other platforms and it not work.  On other platforms you must create a custom HSM library to retrieve the x509 certificate or TPM Information.

**Comment by jebrando** [comment]
If you have any more question about this issue please reopen, or create a new one if that is necessary.
