### ISSUE TITLE
Problem with the SSL CA cert (path? access rights?)

### ISSUE THREAD

**Issue by pmshkung** [Azure/azure-iot-sdk-c#513]
Hi.

On MTK7621 platform, cross compilation of Azure SDK is success.
And, I make under folder /serializer/samples/simplesample_mqtt and /simplesample_http.
Thc compliaton has been passed.

Now, I run the binary(simplesample_mqtt) in MTK7621 device. 
In the Azure Site, the data sent from MTK7621 device  have been received.

And, I run the binary(simplesample_http) in MTK7621 device.
But, the error occurs. The error mssage =>

Error: Time:Wed Jun  6 03:27:57 2018 File:/home/webb/Azure/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:584 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Wed Jun  6 03:27:57 2018 File:/home/webb/Azure/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Wed Jun  6 03:27:57 2018 File:/home/webb/Azure/azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1685 unable to HTTPAPIEX_SAS_ExecuteRequest
Error: Time:Wed Jun  6 03:27:57 2018 File:/home/webb/Azure/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:582 curl_easy_perform() failed: Problem with the SSL CA cert (path? access rights?)

MTK7621 Device:
kernel:
2.6.36+

curl:
curl 7.19.6 (mipsel-unknown-linux-uclibc) libcurl/7.19.6 OpenSSL/1.0.2m zlib/1.2.5
Protocols: tftp ftp telnet dict http file https ftps 
Features: Largefile NTLM SSL libz

openssl:
OpenSSL 1.0.2m  2 Nov 2017

**Comment by jebrando** [comment]
@pmshkung Thanks for the update.
