### ISSUE TITLE
Azure-iot-hub for Arduino - issue with strftime

### ISSUE THREAD

**Issue by Tintin4000** [Azure/azure-iot-sdk-c#514]
I have posted a comment on https://github.com/Azure/azure-iot-arduino/issues/78, regarding the exclusion strftime in the latest available release.  Can this be solved and a new compilation performed with the latest version of azure-iot-sdk-c?  There seems to be very little activities on the Arduino project.

I am using  a NodeMCU 1.0 ESP8266.

**Comment by JetstreamRoySprowl** [comment]
@Tintin4000 : We've just pushed version 1.0.45 out which fixes this. That time.c file has been deleted because the recent versions of the ESP8266 library implement those functions.

**Comment by Tintin4000** [comment]
I hove now compile my application with the new version and works fine, thank you so much for your help.
