### ISSUE TITLE
Set static library for libssl and libcrypto?

### ISSUE THREAD

**Issue by trillykins** [Azure/azure-iot-sdk-c#515]
Cross-compiling a Azure IoT SDK C app for a MIPS32 processor. It works, but it requires adding shared library files to `/usr/lib` on every device, which I would prefer not to if possible.

	#Copyright (c) Microsoft. All rights reserved.
	#Licensed under the MIT license. See LICENSE file in the project root for full license information.

	#this is CMakeLists.txt for axis_comm

	compileAsC99()

	if(NOT ${use_http})
		message(FATAL_ERROR "axis_comm being generated without HTTP support")
	endif()

	set(axis_comm_c_files
	axis_comm.c
	telemetry.c
	)

	set(axis_comm_c_files ${axis_comm_c_files})

	set(axis_comm_h_files
	axis_comm.h
	telemetry.h
	)

	include_directories(.)
	include_directories(../../../certs)
	include_directories(/home/axis/mips-gcc-backup/mipsisa32r2el/r23/curl/include/)
	include_directories(/home/axis/mips-gcc-backup/mipsisa32r2el/r23/include/)

	add_executable(axis_comm ${axis_comm_c_files} ${axis_comm_h_files})

	target_link_libraries(axis_comm 
	#iothubclient is here only because locking... in gballoc no less.
		iothub_client
		iothub_client_http_transport
	)

	linkSharedUtil(axis_comm)
	linkHttp(axis_comm)

	if(${use_http})
		target_link_libraries(axis_comm iothub_client_http_transport)
		add_definitions(-DUSE_HTTP)
	endif()

	if(${use_amqp})
		target_link_libraries(axis_comm iothub_client_amqp_transport iothub_client_amqp_ws_transport)
		linkUAMQP(axis_comm)
		add_definitions(-DUSE_AMQP)
	endif()

	add_library(axis ${axis_comm_c_files})

Can I tell CMake to use a static library? I thought it would work by adding `add_library(axis ${axis_comm_c_files})`, but, while it produces an `*.a` file, libssl and libcrypto are not part of it.

**Comment by jebrando** [comment]
@trillykins I have not statically link openssl, but I know you will have to build openssl to be statically link [openssl wiki](https://wiki.openssl.org/index.php/Compilation_and_Installation).  This may help you

**Comment by trillykins** [comment]
Thank you, I will give it a try. Should these library files then be included in the resulting `.a` file from `add_library(axis ${axis_comm_c_files})`?

**Comment by jebrando** [comment]
Yes, you'll have to link the new library in your target_link_libraries(axis ${openssl_library_filename}).

**Comment by trillykins** [comment]
Hi, sorry for the extremely long delay. 

For whatever reason I am not able to get it to create a static library for `libssl` and `libcrypto`. 

This is my current `CMakeLists.txt` file:

```
compileAsC99()

if(NOT ${use_http})
	message(FATAL_ERROR "axis_comm being generated without HTTP support")
endif()

set(axis_comm_c_files
    a_lot_of_c_files.c
)

set(axis_comm_c_files ${axis_comm_c_files})

set(axis_comm_h_files
    a_lot_of_header_files.h
)

include_directories(.)
include_directories(../../../certs)
include_directories(/home/axis/mips-gcc-backup/mipsisa32r2el/r23/curl/include/)
include_directories(/home/axis/mips-gcc-backup/mipsisa32r2el/r23/include/)

add_executable(axis_comm ${axis_comm_c_files} ${axis_comm_h_files})

message(${CMAKE_SOURCE_DIR})

target_link_libraries(axis_comm 
    iothub_client
    ${CMAKE_SOURCE_DIR}/../mips/openssl/lib/libcrypto.so.1.1
    ${CMAKE_SOURCE_DIR}/../mips/openssl/lib/libssl.so.1.1
)

linkSharedUtil(axis_comm)
linkHttp(axis_comm)

if(${use_http})
    target_link_libraries(axis_comm iothub_client_http_transport)
    add_definitions(-DUSE_HTTP)
endif()

if(${use_amqp})
    target_link_libraries(axis_comm iothub_client_amqp_transport iothub_client_amqp_ws_transport)
    linkUAMQP(axis_comm)
    add_definitions(-DUSE_AMQP)
endif()

add_library(axis ${axis_comm_c_files})
```

I get `.a` library file after compiling, but it doesn't seem to make any difference. Doing a `ldd -t libaxis.a` only shows the `.o` files from the c and h files.
