### ISSUE TITLE
parson library is locale dependant (fails to parse JSON number when locale uses ',' decimal point)

### ISSUE THREAD

**Issue by janoosthoek** [Azure/azure-iot-sdk-c#517]
Hi, 

just wanted to share:
https://github.com/kgabis/parson/issues/98

It contains my rough patch to fix the problem with `strtod` that is being used in parson library. Main problem is that the patch is not very nice. If someone has a cleaner approach (and cross-compiler friendly) please let me know.

Without the patch, JSON number parsing will fail in other locales! 

Example of failure:

`JSON_Value* v = json_parse_string("{"softwareVersion":1, "reported_maxSpeed":100, "vanityPlate":"1I1"}");`

Inside the samples it will manifest as: (added to get a google hit on the issue)

```
Error: Time:Mon Jun 11 16:12:38 2018 File:/home/jan/azure-iot-sdk-c-2018-05-04/azure-iot-sdk-c/serializer/src/datamarshaller.c Func:DataMarshaller_SendData_ReportedProperties Line:291 failure calling json_parse_string

Error: Time:Mon Jun 11 16:12:38 2018 File:/home/jan/azure-iot-sdk-c-2018-05-04/azure-iot-sdk-c/serializer/src/datapublisher.c Func:DataPublisher_CommitTransaction_ReportedProperties Line:532 unable to DataMarshaller_SendData_ReportedProperties

Error: Time:Mon Jun 11 16:12:38 2018 File:/home/jan/azure-iot-sdk-c-2018-05-04/azure-iot-sdk-c/serializer/src/iotdevice.c Func:Device_CommitTransaction_ReportedProperties Line:392 unable to DataPublisher_CommitTransaction_ReportedProperties

Error: Time:Mon Jun 11 16:12:38 2018 File:/home/jan/azure-iot-sdk-c-2018-05-04/azure-iot-sdk-c/serializer/src/codefirst.c Func:CodeFirst_SendAsyncReported Line:1509 (result = CODEFIRST_DEVICE_PUBLISH_FAILED)

Error: Time:Mon Jun 11 16:12:38 2018 File:/usr/local/include/azureiot/serializer_devicetwin.h Func:IoTHubDeviceTwin_SendReportedState_Impl Line:380 Failed serializing reported state
```

Hope this helps someone else. Cost me a day to track this down... Because my locale was set by other library that was linked it might not be obvious to spot.

**Comment by ewertons** [comment]
Hi @janoosthoek ,
thanks for investigating that issue. 
Currently we do not have localization implemented in the C SDK. That will require a good evaluation of support for locales since we build the SDK for many platforms.

**Comment by vkuzmichev** [comment]
Hi @janoosthoek 
Per [ECMA-404 The JSON Data Interchange Standard](http://json.org/) JSON numbers can not use comma character as decimal point. Otherwise, I guess it would be hard to distinguish it from comma character separating array values and object attributes.

**Comment by zolvarga** [comment]
@janoosthoek 

Thank you for reporting this, and also for creating an issue in the parson repo.

I am closing this  issue/request as it has been tracked in the parson repo. 
We regularly update the parson submodule and created a backlog item to follow up on this if the parson has the fix.

Note: I just recently updated to the latest parson.

Best Regards,
Zoltan

**Comment by az-iot-builder-01** [comment]
@janoosthoek, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
