### ISSUE TITLE
"Active file upload requests exceeded limit" in blob-upload

### ISSUE THREAD

**Issue by trillykins** [Azure/azure-iot-sdk-c#518]
I have a few IoT devices. The code I'm using is based on the 'iothub_client_sample_upload_to_blob' sample project. The code has been working fine for months, but suddenly I'm consistently getting this error on one device (but not others). 

```
Error: Time:Tue Jun 12 13:10:44 2018 File:/home/user/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:629 Failure in HTTP communication: server reply code is 403
Info: HTTP Response:{"Message":"{\"errorCode\":403006,\"trackingId\":\"1d6e304a8d2d48beaccd13562f723e22-G:11-TimeStamp:06/12/2018 13:10:44\",\"message\":\"Number of active file upload requests exceeded limit\",\"timestampUtc\":\"2018-06-12T13:10:44.5224913Z\"}","ExceptionMessage":""}
Error: Time:Tue Jun 12 13:10:44 2018 File:/home/user/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_step1and2 Line:415 HTTP code was 403
Error: Time:Tue Jun 12 13:10:44 2018 File:/home/user/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl Line:915 error in IoTHubClient_LL_UploadToBlob_step1
```

I changed the code to upload multiple files, one at a time. The blob-upload function is in its own thread. Only one blob-upload thread is spawned at a time and the other thread, the main thread of the app, only handles incoming and outgoing messages using another protocol.

**Comment by ewertons** [comment]
Hi @trillykins ,
your IoT Hub has a setting limiting the maximum number of active upload to blobs currently in progress.

If you do not complete the file upload (for example, you kill the thread or device client instance before uploading the last block) that entry gets stale in the IoT Hub, in a pending completion state.
That counts against your maximum number of parallel uploads. 
A stale file upload like this will timeout and be cleared after 1 hour (you can fine tune this in your IoT Hub settings), so if you wait for a while you will be able to upload more files in parallel.

You need to make sure you are completing your file uploads. 
Check [this part](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_upload_to_blob_mb/iothub_client_sample_upload_to_blob_mb.c#L58) of the sample to see how that is done.

Besides that, would you be able to run some checks on your app, like after how many uploads in row you get that failure? That will help us clarify the root cause of the issue you are experiencing.

**Comment by trillykins** [comment]
I'm using `IoTHubClient_LL_UploadToBlob` from the [iothub_client_sample_upload_to_blob](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_upload_to_blob/iothub_client_sample_upload_to_blob.c) sample. It doesn't seem to have a callback overload where I can abort the upload.

This is more or less what I'm doing. I have to upload a selection of files. I loop through and upload them individually. 

```
void upload_files(IOTHUB_CLIENT_LL_HANDLE iotblob_ll_handle, const char* from, const char* to, const unsigned int interval) {
    time_t from_t = _get_time_t_value("%4d-%2d-%2dT%2d:%2d:%2dZ", from);
    time_t to_t = _get_time_t_value("%4d-%2d-%2dT%2d:%2d:%2dZ", to);

    time_t duration = abs(from_t - to_t);
    for (time_t i = from_t; i <= to_t; i += interval) {
        char blobname[19];
        strftime(blobname, 19, "%Y%m%dT%H%M%S.jpg", gmtime(&i));
        if (access(blobname, F_OK) != -1) {
            FILE* fp;
            unsigned long fl;
            fp = fopen(blobname, "rb");

            fseek(fp, 0, SEEK_END);
            fl = ftell(fp);
            fseek(fp, 0, SEEK_SET);

            unsigned char* buffer = malloc(sizeof(char) * fl);
            if (buffer != NULL) {

                // Read file into buffer
                fread(buffer, fl, 1, fp);

                if (IoTHubClient_LL_UploadToBlob(iotblob_ll_handle, blobname, (const unsigned char*)buffer, sizeof(unsigned char) * fl) != IOTHUB_CLIENT_OK) {
                    (void)printf("Failed to upload %s\n", blobname);
                } else {
                    (void)printf("%s uploaded successfully\n", blobname);
                }

                fclose(fp);
                free(buffer);
            } else {
                printf("Not found: %s\n", fname);
            }
        } else {
            printf("Not found: %s\n", fname);
        }
    }
}
```

```
void upload_to_blob(const char* connectionString, const char* from, const char* to, const unsigned int interval) {
    IOTHUB_CLIENT_LL_HANDLE iotblob_ll_handle;

    if ((iotblob_ll_handle = IoTHubClient_LL_CreateFromConnectionString(connectionString, HTTP_Protocol)) == NULL) {
        (void)printf("ERROR: iotHubClientHandle is NULL!\r\n");
    } else {
        size_t log = 1;
        (void)IoTHubClient_LL_SetOption(iotblob_ll_handle, OPTION_CURL_FRESH_CONNECT, &log);

        if (IoTHubClient_LL_SetOption(iotblob_ll_handle, OPTION_TRUSTED_CERT, certificates) != IOTHUB_CLIENT_OK) {
            (void)printf("failure in IoTHubClient_LL_SetOption (TrustedCerts)");
        } else {
            upload_files(iotblob_ll_handle, from, to, interval);
        }
        IoTHubClient_LL_Destroy(iotblob_ll_handle);
    }
}

```

Should I use the `IoTHubClient_LL_UploadMultipleBlocksToBlobEx` instead so that I can return an abort in case the upload fails?

**Comment by ewertons** [comment]
This should be working for you, unless you are having repeated failures uploading (to a number that ammounts to the limit of parallel uploads).

I see you have several printfs in your code, do you see any failures being printed? 

And yes, if you have bigger files for sure we would advise to use the multi-block function.

**Comment by trillykins** [comment]
I've only noticed failures being printed when this started happening. It hasn't happened since, though.

Is there a way to send an abort message when a failure is encountered?

**Comment by ewertons** [comment]
Not with IoTHubClient_LL_UploadToBlob.
You will need to use IoTHubClient_LL_UploadMultipleBlocksToBlobEx.

**Comment by trillykins** [comment]
Ah okay. Thank you very much for your help!

**Comment by trillykins** [comment]
Can you tell, or link me to an example that tells me, how I am supposed to pass `unsigned char const** data` and `size_t* size` into the callback function for `IoTHubClient_LL_UploadMultipleBlocksToBlobEx`?

**Comment by ewertons** [comment]
Hi @trillykins , our sample for UploadMultipleBlocksToBlob is [here](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_upload_to_blob_mb).

**Comment by raycon94** [comment]
> A stale file upload like this will timeout and be cleared after 1 hour (you can fine tune this in your IoT Hub settings), so if you wait for a while you will be able to upload more files in parallel.

Hello,
Where can I set those Settings, I didnt´t find anything.

**Comment by AndreRicardo-Zoetis** [comment]
> > A stale file upload like this will timeout and be cleared after 1 hour (you can fine tune this in your IoT Hub settings), so if you wait for a while you will be able to upload more files in parallel.
> 
> Hello, Where can I set those Settings, I didnt´t find anything.

I suspect @ewertons is mentioning the "SAS TTL" under "File Upload"

![image](https://github.com/user-attachments/assets/00295124-1961-4cca-a026-a167871ef8ae)

Microsoft documentation:

> 403006 Device maximum active file upload limit exceeded
>
> You may see that your file upload request fails with the error code 403006 DeviceMaximumActiveFileUploadLimitExceeded and a message "Number of active file upload requests cannot exceed 10".
>
> This error occurs because each device client is limited for [concurrent file uploads](https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#other-limits). You can easily exceed the limit if your device doesn't notify IoT Hub when file uploads are completed. This problem is commonly caused by an unreliable device side network.
>
> To resolve this error, ensure that the device can promptly [notify IoT Hub file upload completion](https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload#device-notify-iot-hub-of-a-completed-file-upload). Then, try [reducing the SAS token TTL for file upload configuration](https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-configure-file-upload).

Source: https://learn.microsoft.com/en-us/azure/iot-hub/troubleshoot-error-codes#403006-device-maximum-active-file-upload-limit-exceeded
