### ISSUE TITLE
Make device twin sample to run on ESP8266

### ISSUE THREAD

**Issue by compulim** [Azure/azure-iot-sdk-c#52]
[serializer/samples/devicetwin_simplesample](../blob/master/serializer/samples/devicetwin_simplesample/) is one good example how to use device twin (`WITH_DESIRED_PROPERTY`) and device method (`WITH_METHOD`).

But unfortunately, it currently does not work with ESP8266 (Sparkfun Thing Dev). I am not proficient in C but when I drill down I found that `parson.c` use `sscanf` but ESP8266 does not support `sscanf` ([issue](https://github.com/esp8266/Arduino/issues/488)).

I really hope the device twin sample can work because it enables ESP8266 to be invoked with device method.

**Comment by anporumb** [comment]
We suggest changing parson source code to use some of the functions we wrote in order to work around the sscanf problem. We have no time to make this change ourselves for the foreseeable future.

If you manage to get it running, we'd take a pull request on that. Thank you.

Best Regards,
Andrei Porumb

**Comment by compulim** [comment]
I have forked [parson](https://github.com/kgabis/parson) and made a [version](https://github.com/compulim/parson/commit/7920413af9599f376db500285441b2f5ccdafd39) of it without `sscanf`. It passed all parson tests.

Since it is not a bug in parson, I filed [an issue](https://github.com/kgabis/parson/issues/68) (a.k.a. suggestion) to them and see if they like my commit.

**Comment by compulim** [comment]
Waiting for my [pull request](https://github.com/kgabis/parson/pull/69) at [`parson`](https://github.com/kgabis/parson) to be accepted.

**Comment by compulim** [comment]
@anporumb Although device twin is still not working on ESP8266 (lack of `Lock`/`Unlock`/`Lock_init`), the latest [parson@96150ba](https://github.com/kgabis/parson/commit/96150ba1fd7f3398aa6a4dead0a63d9d9ac1c189) remove dependency to `sscanf`. Bringing one closer step.

**Comment by JetstreamRoySprowl** [comment]
The Azure IoT team has twin support for Arduino scheduled before the end of the year.

**Comment by JetstreamRoySprowl** [comment]
Twin support for Arduino is near the front of my task queue. I'll post here when it's complete.

**Comment by jantielens** [comment]
Any update @JetstreamRoySprowl ? Is it still far away?
Thanks!

**Comment by JetstreamRoySprowl** [comment]
@jantielens Real Soon Now. I've gotten it running, and just need to get it into the next release.

**Comment by JetstreamRoySprowl** [comment]
The 1.0.44 versions of the Azure IoT libraries now have twin support. Running this version will require the latest library and devices files. Here is the sample for Huzzah, but it also fits in Thing Dev: https://github.com/Azure-Samples/iot-hub-c-huzzah-getstartedkit
