### ISSUE TITLE
Question: Device-Twin - read reported properties on device-side

### ISSUE THREAD

**Issue by raycon94** [Azure/azure-iot-sdk-c#522]
As I understand the standard way is to read-only desired properties and write-only reported properties on device-side. So it´s not possible to get the reported properties from the devicetwin on device-side over twin-notification-messages like for the desired-properties. But the graphic below from the azure-documentations confuses me a bit, as it illustrates that we can write and read reported properties on device-side. Does the SDK support any functions to get the reported properties on device-side?

![devicetwin](https://user-images.githubusercontent.com/9380012/41351484-c99b33a2-6f16-11e8-8b88-4fd78884b8ed.png)

**Comment by ewertons** [comment]
Hi @raycon94 ,
The graph is correct, you can access the full twin document from the device client, which includes the reported properties.
The answer here has two parts:
- Currently, after you [subscribe for Device Twin updates](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client_ll.h#L301), the first time the callback is invoked you will get the full twin document, which contains both desired and reported properties. All subsequent incremental updates will have Desired properties only;
- We are working on a new function to allow users to get the full Device Twin json on demand (like _GetDeviceTwin(...)) which will make it even easier to retrieve the properties. This is work in progress and should come within one or two months.

**Comment by ewertons** [comment]
@raycon94 ,
we will close this issue for now but feel free to reopen it if you would like to follow up.
Thanks for using the Azure IoT SDKs!

**Comment by ewertons** [comment]
@raycon94 , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
