### ISSUE TITLE
Call IoTHubClient_LL_SendReportedState in device twin callback cause timeout

### ISSUE THREAD

**Issue by Einzelkampfer** [Azure/azure-iot-sdk-c#525]
- **OS and version used:** <VERSION> <Windows 10>

- **SDK version used:** <VERSION> 1.2.4

# Description of the issue:
I call IoTHubClient_LL_SendReportedState() in a device twin callback function and it will cause timeout, though the reported device twin can be received by IotHub. But if I call it in a Arduino loop() function, the timeout doesn't appear.

**Comment by ewertons** [comment]
Hi @Einzelkampfer ,
Are you calling IoTHubClient_LL_DoWork with the recommended frequency?
If you are not sure about what that means, please take a look at this [article](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-c-iothubclient).

By the way the sample in the article uses a frequency of once in 1000ms (a thousand), but 100ms (one hundred) would be more appropriate in general.

**Comment by ewertons** [comment]
@Einzelkampfer ,
we will close this issue for now but feel free to reopen it if you would like to follow up.
Thanks for using the Azure IoT SDKs!

**Comment by ewertons** [comment]
@Einzelkampfer , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)

**Comment by Einzelkampfer** [comment]
I call IoTHubClient_LL_DoWork in a 100ms interval. Actually what I called is a wrapped API in Microsoft's DevKit SDK, which calls Azure C SDK. It is in [here](https://github.com/Microsoft/devkit-sdk/blob/master/AZ3166/src/libraries/AzureIoT/src/DevKitMQTTClient.cpp#L338), the SendEventOnce API.
