### ISSUE TITLE
Possible attempt to dereference NULL pointer 

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#527]
- **OS and version used:** macOS 10.13.4
- **SDK version used:** master

# Description of the issue:
In serialzier_devicetwin.h:355[[1](https://github.com/Azure/azure-iot-sdk-c/blob/717ce7baf3610b28f05615b7437c0a351485ef29/serializer/inc/serializer_devicetwin.h#L355)], if `protoHandle` could be NULL. The source above explicitly checks for NULL and logs the error. But continues to deference.

**Comment by jebrando** [comment]
You are correct @kiranpradeep, I will fix this.

**Comment by jebrando** [comment]
@kiranpradeep Thank for the issues.  One question that we have is how did you find this possible bug, was it a static analysis tool or simply code review?

**Comment by kiranpradeep** [comment]
@jebrando XCode static analysis. My attempts to get this full project built on XCode was mercilessly killed by you #447 and #455 :)

**Comment by jebrando** [comment]
Yes, I have a tendency to do that.  I have talk to our PM and provisioning support is on the road map for Mac.  I checked in this fix for under commit  id f680bfb.  Let me know if you have any more issues.
