### ISSUE TITLE
Service Client Send Message Example

### ISSUE THREAD

**Issue by gregjesl** [Azure/azure-iot-sdk-c#529]
OS:  Windows 10 Pro Version 1803 OS Build 17134.112 running as VM in Hyper-V
IDE:  Visual Studio Community 2017 Version 15.6.6
Compiler: MSVC 19.13.26131.1

# Description of the issue:
The [service messaging sample](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_service_client/samples/iothub_messaging_sample) fails on the [second call of the message loop](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_service_client/samples/iothub_messaging_sample/iothub_messaging_sample.c#L128-L134).  

# Code sample exhibiting the issue:
- Changed sample file extension from .c to .cpp
- Added my device ID and connection string into the placeholders
- Compiled using C++ compiler
- Ran the sample

# Console log of the issue:
First message sent successfully.  
Second message: 
[IoTHubMessaging_LL_Send](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_service_client/src/iothub_messaging.c#L315) returns `IOTHUB_MESSAGING_ERROR`.  
The error response is set [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_service_client/src/iothub_messaging_ll.c#L1437-L1441).  It appears the lower level messaging handle is not open the second time.

**Comment by ewertons** [comment]
Hi @gregjesl ,
we need more info to be able to help. 
You should have messages printed on the console, could you please share?

**Comment by gregjesl** [comment]
@ewertons Sorry for the delay: 
Creating Messaging object...
IoTHubMessaging_LL_Send accepted data for transmission to IoT Hub.
IoTHubMessaging_LL_Send accepted data for transmission to IoT Hub.
IoTHubMessaging_LL_Send accepted data for transmission to IoT Hub.
IoTHubMessaging_LL_Send accepted data for transmission to IoT Hub.
IoTHubMessaging_LL_Send accepted data for transmission to IoT Hub.
Error: Time:Tue Jul  3 17:52:27 2018 File:c:\users\gregory\documents\github\azure-iot-sdk-c\uamqp\src\saslclientio.c Func:_on_sasl_frame_received_callback Line:909 SASL handshake failed with code 02

**Comment by gregjesl** [comment]
It looks like this is related to #419

**Comment by gregjesl** [comment]
The previous console output was for [serve messaging ll sample](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_service_client/samples/iothub_messaging_ll_sample)

This is the console output for the the [service messaging sample](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_service_client/samples/iothub_messaging_sample)
Creating Messaging object...
Error: Time:Tue Jul  3 17:58:00 2018 File:c:\users\gregory\documents\github\azure-iot-sdk-c\uamqp\src\saslclientio.c Func:_on_sasl_frame_received_callback Line:909 SASL handshake failed with code 02
Error: Time:Tue Jul  3 17:58:00 2018 File:c:\users\gregory\documents\github\azure-iot-sdk-c\iothub_service_client\src\iothub_messaging_ll.c Func:_IoTHubMessaging_LL_Send Line:1439 Messaging is not opened - call IoTHubMessaging_LL_Open to open
IoTHubMessaging_SendAsync failed. Exiting...
Press any key to exit the application.

Send failed
Error: Time:Tue Jul  3 17:58:13 2018 File:c:\users\gregory\documents\github\azure-iot-sdk-c\uamqp\src\saslclientio.c Func:_saslclientio_send_async Line:1181 send called while not open
Error: Time:Tue Jul  3 17:58:13 2018 File:c:\users\gregory\documents\github\azure-iot-sdk-c\uamqp\src\connection.c Func:_on_bytes_encoded Line:268 Cannot send encoded bytes
Error: Time:Tue Jul  3 17:58:13 2018 File:c:\users\gregory\documents\github\azure-iot-sdk-c\uamqp\src\saslclientio.c Func:_saslclientio_close_async Line:1130 saslclientio_close called while not open
Error: Time:Tue Jul  3 17:58:13 2018 File:c:\users\gregory\documents\github\azure-iot-sdk-c\uamqp\src\connection.c Func:_on_bytes_encoded Line:272 xio_close failed
Error: Time:Tue Jul  3 17:58:13 2018 File:c:\users\gregory\documents\github\azure-iot-sdk-c\uamqp\src\saslclientio.c Func:_saslclientio_close_async Line:1130 saslclientio_close called while not open
Error: Time:Tue Jul  3 17:58:13 2018 File:c:\users\gregory\documents\github\azure-iot-sdk-c\uamqp\src\connection.c Func:_connection_close Line:1431 xio_close failed

**Comment by ewertons** [comment]
Hi @gregjesl ,thanks for the info!
So let me ask a question, in the initial statement you said that the "First message sent successfully.". In the [logs you sent](https://github.com/Azure/azure-iot-sdk-c/issues/529#issuecomment-402206232) I don't see any message succeeding at being sent. Could you share how you got to understand that the first message was sent successfully?

Also, about your device and iot hub connection strings, what is the value you have for the "SharedAccessKeyName" argument?

**Comment by ewertons** [comment]
@gregjesl ,
we will close this issue since it has been stale for quite while, but please feel free to reopen it if you would like to follow up.
Thanks,
Azure IoT Team

**Comment by az-iot-builder-01** [comment]
@gregjesl, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
