### ISSUE TITLE
LNK2019	unresolved external symbol _json_parse_string referenced in function _IoTHubClient_LL_UploadToBlob_step1and2

### ISSUE THREAD

**Issue by rkathire** [Azure/azure-iot-sdk-c#535]
- **OS and version used:** <VERSION> 
Windows 10

- **SDK version used:** <VERSION> 
<packages>
  <package id="Microsoft.Azure.C.SharedUtility" version="1.1.6" targetFramework="native" />
  <package id="Microsoft.Azure.IoTHub.IoTHubClient" version="1.2.6" targetFramework="native" />
  <package id="Microsoft.Azure.IoTHub.MqttTransport" version="1.2.6" targetFramework="native" />
  <package id="Microsoft.Azure.umqtt" version="1.1.6" targetFramework="native" />
</packages>

# Description of the issue:

LNK2019	unresolved external symbol _json_parse_string referenced in function _IoTHubClient_LL_UploadToBlob_step1and2

# Code sample exhibiting the issue:
Very basic connection fails with sdk linker error.

int main()
{
	char *connectionString = NULL ;
	IOTHUB_DEVICE_CLIENT_HANDLE iotHubClientHandle = NULL;

	if(mallocAndStrcpy_s(&connectionString, "HostName=[IoTHub Name].azure-devices.net;DeviceId=[Device Id];SharedAccessKey=[Device Key]") != 0)
		iotHubClientHandle = IoTHubDeviceClient_CreateFromConnectionString(connectionString, MQTT_WebSocket_Protocol);
	if (iotHubClientHandle == NULL)
	{
   	      printf("cannot create connection. \r\n");
	}
	IoTHubDeviceClient_Destroy(iotHubClientHandle); 
    return 0;
}

# Console log of the issue:
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol _json_parse_string referenced in function _IoTHubClient_LL_UploadToBlob_step1and2	IotHubMqttWebsocketsProxy	C:\Users\rkathire\source\repos\IotHubMqttWebsocketsProxy\IotHubMqttWebsocketsProxy\iothub_client.lib(iothub_client_ll_uploadtoblob.obj)	1	
Error	LNK2019	unresolved external symbol _json_object_get_string referenced in function _IoTHubClient_LL_UploadToBlob_step1and2	IotHubMqttWebsocketsProxy	C:\Users\rkathire\source\repos\IotHubMqttWebsocketsProxy\IotHubMqttWebsocketsProxy\iothub_client.lib(iothub_client_ll_uploadtoblob.obj)	1	
Error	LNK2019	unresolved external symbol _json_value_free referenced in function _IoTHubClient_LL_UploadToBlob_step1and2	IotHubMqttWebsocketsProxy	C:\Users\rkathire\source\repos\IotHubMqttWebsocketsProxy\IotHubMqttWebsocketsProxy\iothub_client.lib(iothub_client_ll_uploadtoblob.obj)	1	
Error	LNK2019	unresolved external symbol _json_value_get_object referenced in function _IoTHubClient_LL_UploadToBlob_step1and2	IotHubMqttWebsocketsProxy	C:\Users\rkathire\source\repos\IotHubMqttWebsocketsProxy\IotHubMqttWebsocketsProxy\iothub_client.lib(iothub_client_ll_uploadtoblob.obj)	1

**Comment by ewertons** [comment]
Hi @rkathire ,
Thanks for your question.

Have you tried running one of our [samples](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_upload_to_blob_mb)?

You will need to link your solution against parson, a library for parsing json.
Parson can be obtained from [here](https://github.com/kgabis/parson.git).

**Comment by rkathire** [comment]
Yes, I have used the sample, but hit the same issue. Perhaps its not linked in the samples automatically?

I cloned the git, how do I link this to my project. Do I have to use nmake to build a lib and reference it? Or is there nuget package available for this? Or should I just include those source files directly in my project?

Thanks,
Ram

**Comment by rkathire** [comment]
Never mind. That worked. Thanks for quick help!

But I had to compile it as a static library and link it in the libraries. Is that the best practice or I can get it as nuget package?

Thanks,
Ram

From: Ramanathan Kathiresan (CW)
Sent: Thursday, June 28, 2018 11:23 AM
To: Azure/azure-iot-sdk-c <reply@reply.github.com>; Azure/azure-iot-sdk-c <azure-iot-sdk-c@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-iot-sdk-c] LNK2019 unresolved external symbol _json_parse_string referenced in function _IoTHubClient_LL_UploadToBlob_step1and2 (#535)

Yes, I have used the sample, but hit the same issue. Perhaps its not linked in the samples automatically?

I cloned the git, how do I link this to my project. Do I have to use nmake to build a lib and reference it? Or is there nuget package available for this? Or should I just include those source files directly in my project?

Thanks,
Ram

**Comment by ewertons** [comment]
You can get the code as nugets:
https://www.nuget.org/packages/Microsoft.Azure.IoTHub.AmqpTransport
https://www.nuget.org/packages/Microsoft.Azure.IoTHub.MqttTransport
https://www.nuget.org/packages/Microsoft.Azure.IoTHub.HttpTransport

**Comment by rkathire** [comment]
Yes I have those, what about the parson library?

**Comment by ewertons** [comment]
Parson doesn't have nugets published, you need to download it and add to your solution.

However we pack parson.lib in our nugets for now.
If you search under your solution folder, look for a "packages" folder (created after you try to build the solition). Inside that, look for parson.lib.

All you need in VS is to add the path to parson.lib into the Linker additional libraries:
<project> / Properties / Linker / Input / Additional Dependencies

**Comment by rkathire** [comment]
thanks you can close this!

**Comment by ewertons** [comment]
Thanks for using the Azure IoT SDKs!
