### ISSUE TITLE
Problem building a client app on Windows

### ISSUE THREAD

**Issue by dominicbetts** [Azure/azure-iot-sdk-c#536]
I'm using Windows 10 and Visual Studio 2017.

I'm stepping through this tutorial: https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-connecting-devices
I've added the following Nuget packages to the project:

- Microsoft.Azure.IoTHub.Serializer
- Microsoft.Azure.IoTHub.IoTHubClient
- Microsoft.Azure.IoTHub.MqttTransport

I have the following include statements:

```c
#include "iothubtransportmqtt.h"
#include "schemalib.h"
#include "iothub_client.h"
#include "serializer_devicetwin.h"
#include "schemaserializer.h"
#include "azure_c_shared_utility/threadapi.h"
#include "azure_c_shared_utility/platform.h"
#include <string.h>
```

With version 1.2.4 or earlier of the **Microsoft.Azure.IoTHub.IoTHubClient** package, the project builds. Any later version fails to build with:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "iothub_client_core_ll.h"	RMDevice	c:\temp\RMDevice\packages\Microsoft.Azure.IoTHub.IoTHubClient.1.2.5\build\native\include\iothub_client.h	24	
Error (active)	E1696	cannot open source file "iothub_client_core.h"	RMDevice	c:\temp\RMDevice\packages\Microsoft.Azure.IoTHub.IoTHubClient.1.2.5\build\native\include\iothub_client.h	25	

...

Error	C1083	Cannot open include file: 'iothub_client_core_ll.h': No such file or directory	RMDevice	c:\temp\rmdevice\packages\microsoft.azure.iothub.iothubclient.1.2.5\build\native\include\iothub_client.h	24	
```

**Comment by ewertons** [comment]
Hi @dominicbetts ,
apologize for the issue, it indeed seems to be a bug either in the nuget (less likely) or in the documentation. We will address that briefly.

**Comment by yzhong94** [comment]
@ewertons any update on this issue?  Is it an issue with the sample/bug?

**Comment by ewertons** [comment]
We are releasing a new set of nugets today, then I'll check the state of the failure.

**Comment by ewertons** [comment]
Hi @dominicbetts ,
could you try again, using the new nuget packages released today (1.2.8)?

For reference:
https://www.nuget.org/packages/Microsoft.Azure.IoTHub.MqttTransport/1.2.8
https://www.nuget.org/packages/Microsoft.Azure.IoTHub.Serializer/1.2.8

**Comment by dominicbetts** [comment]
It's working with the new nuget packages.

**Comment by ewertons** [comment]
Thanks for contributing to the Azure IoT SDKs.
