### ISSUE TITLE
Unable to run Azure IOT SDK Firmware update in c 

### ISSUE THREAD

**Issue by Pavan2358** [Azure/azure-iot-sdk-c#537]
Hi 
**I am trying to run FIrmware update sample that is available in SDK source file by running **iothub_devicemethod_**sample present in **"iothub_service_client"** but I am receiving the following error:**

Calling IoTHubServiceClientAuth_CreateFromConnectionString with connectionString
Invoking method firmwareUpdate on device...
Error: Time:Thu Jun 28 13:45:25 2018 File:/home/test/azure_4/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:582 curl_easy_perform() failed: Peer certificate cannot be authenticated with given CA certificates

Error: Time:Thu Jun 28 13:45:25 2018 File:/home/test/azure_4/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:584 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Thu Jun 28 13:45:25 2018 File:/home/test/azure_4/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Thu Jun 28 13:45:25 2018 File:/home/test/azure_4/azure-iot-sdk-c/iothub_service_client/src/iothub_devicemethod.c Func:sendHttpRequestDeviceMethod Line:324 HTTPAPIEX_SAS_ExecuteRequest failed
Error: Time:Thu Jun 28 13:45:25 2018 File:/home/test/azure_4/azure-iot-sdk-c/iothub_service_client/src/iothub_devicemethod.c Func:IoTHubDeviceMethod_Invoke Line:492 Failure sending HTTP request for device method invoke
IoTHubDeviceMethod_Invoke failed with result: 2
Calling IoTHubDeviceMethod_Destroy...
Calling IoTHubServiceClientAuth_Destroy...

I tried running  **iothub_client_sample_mqtt_dm** as well but i am not getting any error/logs from the executable....no output is displayed
**My goal is to send a dummy firmware payload from the service client and the device responds by doing all the initiations
Please someone provide a step on how to do a firmware process in c..**.
I am unable to figure it out

**Comment by ewertons** [comment]
Hi @Pavan2358 ,
you are probably running the service client sample from a device that doesn't have a certificate store. Could you confirm?

Unfortunately, unlike the device client, there is no API function to set the [certificates](https://github.com/Azure/azure-iot-sdk-c/tree/master/certs) directly on the service client.

**Comment by jspaith** [comment]
@Pavan2358 - since this thread has been quite for a bit, I'm going to close out.  If you need further assistance though by all means re-activate this or open a new item.
