### ISSUE TITLE
Microsoft.Azure.IoTHub.MqttTransport 1.2.7 Nugetpackage is bringing dependency to tpm tbs.dll

### ISSUE THREAD

**Issue by rkathire** [Azure/azure-iot-sdk-c#542]
Please first tell us a little bit about the environment you're running:
Windows 7 / Windows 7 POSReady

- **OS and version used:** <VERSION> 
Windows 7 POSReady
C sdk

- **SDK version used:** <VERSION> 
C Sdk 
V10.0.17134.0

# Description of the issue:
When we install nuget package Microsoft.Azure.IotHub.MQTTTransport 1.2.7, we get the dependency to tbs.dll. This is bad because this is not available in POSReady7 and hence we cannot run our app there.

# Code sample exhibiting the issue:
any sample, but add nuget package, instead of building the sdk.

# Console log of the issue:
[?6/?29/?2018 4:55 PM]  
  <package id="Microsoft.Azure.C.SharedUtility" version="1.1.7" targetFramework="native" />
  <package id="Microsoft.Azure.IoTHub.IoTHubClient" version="1.2.7" targetFramework="native" />
  <package id="Microsoft.Azure.IoTHub.MqttTransport" version="1.2.7" targetFramework="native" />
  <package id="Microsoft.Azure.umqtt" version="1.1.7" targetFramework="native" /> 
 
C:\Users\rkathire\source\repos\IotHubMqttWebsocketsProxy\packages\Microsoft.Azure.IoTHub.IoTHubClient.1.2.7\build\native\Win32\Release 
 contain
utpm.lib

**Comment by ewertons** [comment]
Thanks for the feedback, @rkathire .
We will address that for the next release.
To help with the fix, would you mind running systeminfo in your environment (the one mentioned in your issue) and send us back the OS name and version lines?

**Comment by ewertons** [comment]
And as a mitigation for your project, please use the previous version of nugets until we get this fixed.

**Comment by ewertons** [comment]
Hi @rkathire ,
new [nuget packages](https://www.nuget.org/packages?q=microsoft.azure.iothub) have been released today and they address the issue you filed.
They no longer bring dependency on tbs.dll.
Please validate if possible.

**Comment by ewertons** [comment]
We will close this issue, but please feel free to reopen it if you would like to follow up.
Thanks for using the Azure IoT SDKs.
