### ISSUE TITLE
Memory loss in case there is no Network

### ISSUE THREAD

**Issue by mm-mhr** [Azure/azure-iot-sdk-c#55]
I am experiencing memory loss in case the sdk is started with no internet connection.
I have attached a minimum example which can be used to reproduce by either making sure that the thing is not connected or by providing a connection string for a non existing url.

Valgind reports the follwoing two definite memory losses:

100 bytes in 5 blocks are definitely lost in loss record 17 of 94
  in mallocAndStrcpy_s in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/crt_abstractions.c:683
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: mallocAndStrcpy_s in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/crt_abstractions.c:683
  3: cloneMqttOptions in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:421
  4: mqtt_client_connect in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:875
  5: SendMqttConnectMsg in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1596
  6: InitializeConnection in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1637
  7: IoTHubTransport_MQTT_Common_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2371
  8: IoTHubTransportMqtt_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  9: IoTHubClient_LL_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  10: ScheduleWork_Thread in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client.c:438
  11: ThreadWrapper in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/adapters/threadapi_pthreads.c:34
  12: start_thread in /build/eglibc-3GlaMS/eglibc-2.19/nptl/pthread_create.c:312
  13: clone in /build/eglibc-3GlaMS/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111

54,860 (4,040 direct, 50,820 indirect) bytes in 5 blocks are definitely lost in loss record 94 of 94
  in create_openssl_instance in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:870
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: CRYPTO_malloc in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
  3: SSL_new in /lib/x86_64-linux-gnu/libssl.so.1.0.0
  4: create_openssl_instance in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:870
  5: tlsio_openssl_open in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1045
  6: xio_open in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:87
  7: mqtt_client_connect in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:881
  8: SendMqttConnectMsg in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1596
  9: InitializeConnection in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1637
  10: IoTHubTransport_MQTT_Common_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2371
  11: IoTHubTransportMqtt_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  12: IoTHubClient_LL_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  13: ScheduleWork_Thread in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client.c:438
  14: ThreadWrapper in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/adapters/threadapi_pthreads.c:34
  15: start_thread in /build/eglibc-3GlaMS/eglibc-2.19/nptl/pthread_create.c:312
  16: clone in /build/eglibc-3GlaMS/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111

[test.zip](https://github.com/Azure/azure-iot-sdk-c/files/746126/test.zip)

**Comment by jebrando** [comment]
The fix for this was checked in and is now in master.  Thank you.

**Comment by mm-mhr** [comment]
I cloned master c861ec3f26a7ff4debedf6dbb916072cec1be768 from 2017-02-09.
I am still experiencing one of the two leaks when I run the sample with no internet connection available.

This is what valgrind reports:
65,832 (4,848 direct, 60,984 indirect) bytes in 6 blocks are definitely lost in loss record 86 of 86
  in create_openssl_instance in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:870
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: CRYPTO_malloc in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
  3: SSL_new in /lib/x86_64-linux-gnu/libssl.so.1.0.0
  4: create_openssl_instance in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:870
  5: tlsio_openssl_open in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1045
  6: xio_open in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:87
  7: mqtt_client_connect in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:891
  8: SendMqttConnectMsg in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1596
  9: InitializeConnection in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1637
  10: IoTHubTransport_MQTT_Common_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2371
  11: IoTHubTransportMqtt_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  12: IoTHubClient_LL_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  13: ScheduleWork_Thread in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client.c:438
  14: ThreadWrapper in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/adapters/threadapi_pthreads.c:34
  15: start_thread in /build/eglibc-3GlaMS/eglibc-2.19/nptl/pthread_create.c:312
  16: clone in /build/eglibc-3GlaMS/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Could you please have a look again?

**Comment by anporumb** [comment]
oh uh....

**Comment by ewertons** [comment]
Hello @mm-mhr , 

I am verifying if the issue still reproes, but I encountered an inconsistency.
While I investigate here I would like to ask you try it again as well on your side.

You mentioned you checked out c861ec3. But when I used that revision, the call stack I get is different than yours, what makes me believe you might have tried using a different version of the code.

Could you please rerun your test using the latest revision from master?
**And please reply back with the commit id you checked out.**
Also make sure your submodules are updated according to the hashes referenced by that commit (i.e., run 'git submodule update --init --recursive' after cloning/checking out azure-iot-sdk-c).

This is what I had checked out:

```
E:\Repos\shelf1\azure-iot-sdk-c>git status
**HEAD detached at c861ec3**
...
E:\Repos\shelf1\azure-iot-sdk-c>git remote -v
origin  https://github.com/Azure/azure-iot-sdk-c.git (fetch)
origin  https://github.com/Azure/azure-iot-sdk-c.git (push)


Callstack (notice the top 2 line numbers, how they differ from your log):
>	iothub_client_sample_mqtt.exe!cloneMqttOptions(MQTT_CLIENT_TAG * mqtt_client, const MQTT_CLIENT_OPTIONS_TAG * mqttOptions) Line 435	C
 	iothub_client_sample_mqtt.exe!mqtt_client_connect(MQTT_CLIENT_TAG * handle, XIO_INSTANCE_TAG * xioHandle, MQTT_CLIENT_OPTIONS_TAG * mqttOptions) Line 885	C
 	iothub_client_sample_mqtt.exe!SendMqttConnectMsg(MQTTTRANSPORT_HANDLE_DATA_TAG * transport_data) Line 1596	C
 	iothub_client_sample_mqtt.exe!InitializeConnection(MQTTTRANSPORT_HANDLE_DATA_TAG * transport_data) Line 1637	C
 	iothub_client_sample_mqtt.exe!IoTHubTransport_MQTT_Common_DoWork(void * handle, IOTHUB_CLIENT_LL_HANDLE_DATA_TAG * iotHubClientHandle) Line 2371	C
 	iothub_client_sample_mqtt.exe!IoTHubTransportMqtt_DoWork(void * handle, IOTHUB_CLIENT_LL_HANDLE_DATA_TAG * iotHubClientHandle) Line 95	C
 	iothub_client_sample_mqtt.exe!IoTHubClient_LL_DoWork(IOTHUB_CLIENT_LL_HANDLE_DATA_TAG * iotHubClientHandle) Line 950	C
```

**Comment by ewertons** [comment]
Ok, I got a repro using the latest from master (a47f31a0448f1539c97349c09408091900d09a68).
Working on it.

```
==44397== 23,865 (2,472 direct, 21,393 indirect) bytes in 3 blocks are definitely lost in loss record 38 of 38
==44397==    at 0x4C2DBB6: malloc (vg_replace_malloc.c:299)
==44397==    by 0x5373E77: CRYPTO_malloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==44397==    by 0x50E811F: SSL_new (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==44397==    by 0x432E87: create_openssl_instance (tlsio_openssl.c:867)
==44397==    by 0x43353B: tlsio_openssl_open (tlsio_openssl.c:1069)
==44397==    by 0x426182: xio_open (xio.c:88)
==44397==    by 0x420875: mqtt_client_connect (mqtt_client.c:892)
==44397==    by 0x41B6BF: SendMqttConnectMsg (iothubtransport_mqtt_common.c:1668)
==44397==    by 0x41B86C: InitializeConnection (iothubtransport_mqtt_common.c:1709)
==44397==    by 0x41D4E2: IoTHubTransport_MQTT_Common_DoWork (iothubtransport_mqtt_common.c:2443)
==44397==    by 0x4113D7: IoTHubTransportMqtt_DoWork (iothubtransportmqtt.c:104)
==44397==    by 0x40D4CD: IoTHubClient_LL_DoWork (iothub_client_ll.c:1087)
```

**Comment by mm-imr** [comment]
Hello @ewertons,

it seems that Zlotan is working on an issue on the same source file, https://github.com/Azure/azure-iot-sdk-c/issues/61#issuecomment-284851749.

Best,

Ingo

**Comment by ewertons** [comment]
Yes, we have been working together on this.

**Comment by ewertons** [comment]
Hi @mm-imr ,

the fix was checked in azure-c-shared-utility in master (d8d3cc7032fb929014b76f3e80cdc094dcc8123d)

To verify it, please clone the latest azure-iot-sdk-c and check out the latest master of c-utility.

git clone -b master --recursive https://github.com/Azure/azure-iot-sdk-c.git
cd azure-iot-sdk-c/c-utility
git checkout master
cd ../umqtt/c-utility
git checkout master

then go back to azure-iot-sdk-c, build it and run the mqtt sample.

Soon the submodules will be updated and you will no longer need to do the steps above for c-utility.

**Comment by mm-ark** [comment]
Hey @evertons,

I checked commit 577bb8c4fa93180abc8f4f9ae0abf97f66768105 (release 2017-03-10). It looks good for valgrind: no complains anymore for this test case :-)
Currently i am also running tests on target devices for some days. We will report or close this issue dependent on result.
