### ISSUE TITLE
Library build fails: again.

### ISSUE THREAD

**Issue by SergiyIvanovAtGTI** [Azure/azure-iot-sdk-c#550]
- **OS and version used:** Ubuntu 16.04

- **SDK version used:** 0.2.0.0-7xenial/0.2.0.0-8xenial. After latest upgrade i obtained:
dpkg -l '*azure*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-===============================================================================================
ii  azure-c-shared-util-dev                       0.2.0.0-8xenial             amd64                       AzureIoT Shared Utility Development Library Package
ii  azure-c-shared-util-lib                       0.2.0.0-8xenial             amd64                       AzureIoT Shared Utility Library Package
ii  azure-iot-sdk-c-dev                           0.2.0.0-7xenial             amd64                       Microsoft Azure IoT device SDK for C Library
ii  azure-iot-sdk-c-lib                           0.2.0.0-7xenial             amd64                       Microsoft Azure IoT device SDK for C Library
ii  azure-uamqp-c-dev                             0.2.0.0-8xenial             amd64                       uAMQP is a general purpose C library for AMQP.
ii  azure-uamqp-c-lib                             0.2.0.0-8xenial             amd64                       uAMQP is a general purpose C library for AMQP.
ii  azure-umqtt-c-dev                             0.2.0.0-8xenial             amd64                       azure-umqtt-c is a general purpose library build for MQTT protocol
ii  azure-umqtt-c-lib                             0.2.0.0-8xenial             amd64                       azure-umqtt-c is a general purpose library build for MQTT protocol

My program is statically linked against azure SDK and next libraries are used:

    iothub_client
    iothub_client_http_transport
    iothub_client_mqtt_transport
    umqtt
    aziotsharedutil
    serializer
    parson

After latest upgrade (see above) i obtained:
/usr/lib/libiothub_client.a(iothub_client_core_ll.c.o):-1: In function `IoTHubClientCore_LL_CreateFromEnvironment':
(.text+0x3bc8):-1: error: undefined reference to `iothub_security_init'
/usr/lib/libiothub_client_http_transport.a(iothub_client_authorization.c.o):-1: In function `IoTHubClient_Auth_CreateFromDeviceAuth':
(.text+0x35f):-1: error: undefined reference to `iothub_device_auth_create'
/usr/lib/libiothub_client_http_transport.a(iothub_client_authorization.c.o):-1: In function `IoTHubClient_Auth_CreateFromDeviceAuth':
(.text+0x3a2):-1: error: undefined reference to `iothub_device_auth_get_type'
/usr/lib/libiothub_client_http_transport.a(iothub_client_authorization.c.o):-1: In function `IoTHubClient_Auth_CreateFromDeviceAuth':
(.text+0x4d9):-1: error: undefined reference to `iothub_device_auth_destroy'
/usr/lib/libiothub_client_http_transport.a(iothub_client_authorization.c.o):-1: In function `IoTHubClient_Auth_CreateFromDeviceAuth':
(.text+0x529):-1: error: undefined reference to `iothub_device_auth_destroy'
/usr/lib/libiothub_client_http_transport.a(iothub_client_authorization.c.o):-1: In function `IoTHubClient_Auth_Set_xio_Certificate':
(.text+0x6d7):-1: error: undefined reference to `iothub_device_auth_generate_credentials'
/usr/lib/libiothub_client_http_transport.a(iothub_client_authorization.c.o):-1: In function `IoTHubClient_Auth_Get_SasToken':
(.text+0xa7a):-1: error: undefined reference to `iothub_device_auth_generate_credentials'
/usr/lib/libiothub_client_http_transport.a(iothub_client_authorization.c.o):-1: In function `IoTHubClient_Auth_Get_TrustBundle':
(.text+0xe15):-1: error: undefined reference to `iothub_device_auth_get_trust_bundle'
/usr/lib/libaziotsharedutil.a(uniqueid_linux.c.o):-1: In function `UniqueId_Generate':
(.text+0xad):-1: error: undefined reference to `uuid_generate'
/usr/lib/libaziotsharedutil.a(uniqueid_linux.c.o):-1: In function `UniqueId_Generate':
(.text+0xc7):-1: error: undefined reference to `uuid_unparse'
======
Now i don't think there is a workaround like in [#483](https://github.com/Azure/azure-iot-sdk-c/issues/483) would work .
For example ,
ce@ice_pre_prod:/usr/lib$ nm * -o 2>/dev/null | grep iothub_security_init
libiothub_client.a:iothub_client_core_ll.c.o:                 U iothub_security_init

=> there is not lib with definition of iothub_security_init at all.

**Comment by SergiyIvanovAtGTI** [comment]
Seems to be same as [#543](https://github.com/Azure/azure-iot-sdk-c/issues/543)

**Comment by amoldixit-Git** [comment]
While building azure-iot-gateway-sdk on Ubuntu 16.04 using cmake, got error for uamqp. Can you please confirm if this is an issue or I am missing something?

-- CMake Install Prefix is /usr/local
-- AIG architecture: x86_64
-- NANOMSG LIBRARIES: nanomsg
-- NANOMSG CFLAGS: -I/usr/local/include
-- NANOMSG LOCATION: /usr/local/lib/libnanomsg.so
-- uamqp not found...
-- Building uamqp...
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- AMQP Target architecture: x86_64
-- Configuring done
-- Generating done
-- Build files have been written to: /home/..../azure-iot-gateway-sdk/deps/uamqp/build
-- Installing uamqp. Please wait...
CMake Error at gatewayFunctions.cmake:170 (message):
  Error installing uamqp: 2
Call Stack (most recent call first):
  modules/dependencies.cmake:9 (findAndInstall)
  modules/CMakeLists.txt:6 (include)

**Comment by jebrando** [comment]
@amoldixit-Git The best way to get an answer to your issue with the gateway is to post to the [Gateway Repo](https://github.com/Azure/iot-edge-v1).

**Comment by az-iot-builder-01** [comment]
@SergiyIvanovAtGTI, @amoldixit-Git, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
