### ISSUE TITLE
downgrade to specific version

### ISSUE THREAD

**Issue by SergiyIvanovAtGTI** [Azure/azure-iot-sdk-c#551]
Ubuntu: 16.04
Since i encountered to errors mentioned nearby 
[#550](https://github.com/Azure/azure-iot-sdk-c/issues/550)
i want to be able to downgrade to previous versions of library. I did:

sudo apt-get install -y azure-iot-sdk-c-dev=0.2.0.0-5 =>
E: Version '0.2.0.0-5' for 'azure-iot-sdk-c-dev' was not found

sudo apt-get install -y azure-iot-sdk-c-dev=0.2.0.0-5xenial =>
E: Version '0.2.0.0-5xenial' for 'azure-iot-sdk-c-dev' was not found

However i see that previous version is available in library:
https://launchpad.net/~aziotsdklinux/+archive/ubuntu/ppa-azureiot/+packages?field.name_filter=sdk&field.status_filter=&field.series_filter=

Why i can't downgrade directly?

**Comment by jspaith** [comment]
Apologies for delay here.

A few things.  First we've addressed the problematic build in the latest release.  Its problematic in that you'll need to link to - for now - prov_auth_client, hsm_security_client, uhttp, uuid - libraries.  We're looking into trimming this.

I did not have success in doing the same command for getting a specifc version above, which looks perfectly legit.

If you want to be on older ones (I'd recommend just going to latest though) you can download the .deb packages following off the link above and then manually install them.  I had success getting files by downloading and then 'dpkg' installing.

```
sudo dpkg -i /mnt/jspaith/temp/azure-iot-sdk-c-lib_0.2.0.0-5xenial_amd64.deb
sudo dpkg -i /mnt/jspaith/temp/azure-iot-sdk-c-dev_0.2.0.0-5xenial_amd64.deb
```

**Comment by jspaith** [comment]
I'm going to close this out given we have updated packages that fix this and a workaround for direct consumption of .deb in worst case.  If you have further concerns with this or have other issues, by all means reactive/open new ones.  Thanks

**Comment by az-iot-builder-01** [comment]
@SergiyIvanovAtGTI, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
