### ISSUE TITLE
Windows 10 C SDK build with OpenSSL_1_1_0-stable

### ISSUE THREAD

**Issue by DataWerkt** [Azure/azure-iot-sdk-c#553]
Because I would like to do a group enrollment using this C SDK, I need to build the SDK using OpenSSL. 

- **OS and version used:** Windows 10  

- **VS version used:** Visualstudio 2017

- **SDK version used:** 1.2.5 

- **OpenSSL version used:** OpenSSL_1_1_0-stable

# Description of the issue:

How to do that is described here: [https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509](https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509) (See Purple Information section, step 1.) This document on its turn refers to this page [https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md) specifically to the section "Using OpenSSL in the SDK". This document seems to be very outdated. Nevertheless I gave it a try. Outcome: The OpenSSL build itself seems to be working fine, but building the SDK with OpenSLL is not.

# Code sample exhibiting the issue:

cd azure-iot-sdk-c
mkdir cmake
cd cmake
cmake -Duse_openssl:BOOL=ON ..

# Console log of the issue:

CMake Error at configs/azure_iot_sdksFunctions.cmake:65 (file):
  file COPY cannot find "C:/Build-OpenSSL-VC-64/bin/libeay32.dll".
Call Stack (most recent call first):
  iothub_service_client/samples/iothub_messaging_sample/CMakeLists.txt:23 (linkUAMQP)

CMake Error at configs/azure_iot_sdksFunctions.cmake:66 (file):
  file COPY cannot find "C:/Build-OpenSSL-VC-64/bin/ssleay32.dll".
Call Stack (most recent call first):
  iothub_service_client/samples/iothub_messaging_sample/CMakeLists.txt:23 (linkUAMQP)

Anyone familiar with this issue?

**Comment by jspaith** [comment]
I just tried out openssl on Windows and it builds & sample runs for me.

Some thoughts:
* Could you please double check that the files 'C:/Build-OpenSSL-VC-64/bin/libeay32.dll' and 'C:/Build-OpenSSL-VC-64/bin/ssleay32.dll' exist?
* Could you make sure that 'OpenSSLDir' and 'OPENSSL_ROOT_DIR' environment variables are setup pointing to it?
* Finally I initially hit an issue where my openssl had been built for 32 bit but my IoT SDK was in a 64 bit mode.  The symptom here was getting a few warnings about mismatching 32/64 buried under tons of link errors.  Changing to 32 bit SDK build got things going.

For reference, the cmake options I used were below.  All the test stuff you don't want for production but shouldn't matter here.
```
cmake -G "Visual Studio 15 2017" -Drun_e2e_tests=ON -Drun_unittests=ON -Drun_sfc_tes
ts=ON -Duse_edge_modules=ON ..\..\azure-iot-sdk-c -Duse_openssl=ON
```

**Comment by jspaith** [comment]
OK, lets try an alternate route.

Please visit https://github.com/Microsoft/vcpkg and follow the setup instructions there.  vcpkg is an open source dependency manager that MS's Visual Studio team has created.  After you have the core vcpkg installed, run `.\vcpkg install openssl`.

At this point get the environment variables pointed at `<YourVcxpkRoot>\packages\openssl_x86-windows`. 

This one *should* work as vcpkg is pretty solid.  Let me know either way, and if it does work we will update our docs to get folks on the vcpkg route.

**Comment by jspaith** [comment]
A few followups.  In the CMake* files attached, I'm not seeing references to the libeay32.dll.  Instead I see `c:\users\matthijshoogwerf\azure-iot-sdk-c\cmake\cmakefiles\cmaketmp\checksymbolexists.c(7): error C2065: '_M_AMD64': undeclared identifier`.  Is this what you'd meant to send?

On the copy/paste error above, I know I'm being over cautious but could in the "C/users/<user>"... line above, did you remove your Windows user name for GitHub (which is fine) or is the <user> what the variable is pointing to which would need to be expanded.

**Comment by jspaith** [comment]
Hmm... the error string `C:/Users/<user>/azure-iot-sdk-c/iothub_service_client/samples/iothub_messaging_sample/
  C:/Users/<user>/vcpkg/packages/openssl_x86-windows/bin/libeay32.dll` looks suspicious to me.

When I ran this same cmake with an non-existant directory pointed to by the env variable, I got below.  I'm wondering when you setup your environment variable if its correct, since the C:/users/<users> repeated twice looks off.
```
CMake Error at configs/azure_iot_sdksFunctions.cmake:65 (file):
  file COPY cannot find
  "E:/developer/local/vcpkg/packages/openssl_x86-windows2/bin/libeay32.dll".
Call Stack (most recent call first):
  iothub_service_client/samples/iothub_messaging_sample/CMakeLists.txt:23 (linkUAMQP)
```

Also could you please git pull and then a git submodule update --recursive.  The 1.2.5 SDK you're using is almost a month old; shouldn't impact this inv but lets get you on latest&greatest anyway.

**Comment by DataWerkt** [comment]
Just to be sure I got the correct version, I've started from scratch in a new directory. I've bumped into an error that might cause the issue further up the road.

This is what I did:

1.	Open “x64 Native Tools Command Prompt for VS 2017” as Administrator
2.	Cd development\sdk
3.	git clone https://github.com/Azure/azure-iot-sdk-c.git --recursive
4.	git clone https://github.com/Microsoft/vcpkg.git
5.	.\bootstrap-vcpkg.bat
6.	.\vcpkg integrate install

Output:
```
Applied user-wide integration for this vcpkg root.
All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.
CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/Development/sdk/vcpkg/scripts/buildsystems/vcpkg.cmake"
```
7.	.\vcpkg install sdl2 curl
8.	cmake -DCMAKE_TOOLCHAIN_FILE=C:/Development/sdk/vcpkg/scripts/buildsystems/vcpkg.cmake

Output:
```
CMake Error: The source directory "C:/Development/sdk/vcpkg" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

It's my understanding that this toolchain provides library link functionality. So this could be the real issue, if I'm not mistaken. Should this file be there or is this something I should implement manually?

**Comment by jspaith** [comment]
We're investigating Azure IoT C SDK integrated more properly with vcpkg and setting as a toolchain might work but it's not something I've ever used at least.

For openssl/Windows today however, you should keep following the devbox_setup.md instructions and just use vcpkg to build openssl for you and then set environment variables to have Azure IoT cmake's rules kick in.

Sorry you're having so much trouble with this and we'll definitely use this experience to drive doc improvements, starting with vpckg for building openssl and anything else we uncover.

**Comment by DataWerkt** [comment]
Ok. So I skipped setting the toolchain and got the same result as my post from three days ago (containing the logs). Not much I can do anymore. I'll await an update from you side.

Good to know that you're looking into it and using this to improve!

**Comment by jspaith** [comment]
Could you review my post with "Hmm... the error string" as I had some q's there.

**Comment by DataWerkt** [comment]
Sorry, my bad. These are the variables I have set:

set OpenSSLDir= C:\Development\sdk\vcpkg\packages\openssl_x86-windows
set OPENSSL_ROOT_DIR= C:\Development\sdk\vcpkg\packages\openssl_x86-windows 

I did a new git clone and verified I have the 1.2.8. sdk in the version.txt file.

**Comment by jspaith** [comment]
I think that the problem is the fact that you have an extra space between the OpenSSLDir= and the file itself.  At least playing around with the same setting on my box I could repro the problem with pretty similar results to a dir that otherwise exists.

If this doesn't help, lets get some more diagnostics RE what cmake thinks its doing.  In `<IotRoot>\configs\azure_iot_sdksFunctions.cmake`, find the `if(${use_openssl})` in the WIN32 block and then update with my code below.  Note that I intentionally throw an error at end of this script - whether it should succeed or otherwise - just to shorten dev cycle.  If space trick doesn't work, please give me output from below.  If you want to remove your username prior to post, please in an editor do a straight replace of username=>"foo" or something so that there's no risk of white space being lost.

```
        if(${use_openssl})
		    message(STATUS "OpenSSLDir = <$ENV{OpenSSLDir}>")
			message(STATUS "ssleay32.lib file = <$ENV{OpenSSLDir}/lib/ssleay32.lib>")
			message(STATUS "libeay32.lib file = <$ENV{OpenSSLDir}/lib/libeay32.lib>")
			message(STATUS "target/debug file = <${CMAKE_CURRENT_BINARY_DIR}/Debug>")
			message(STATUS "target/release file = <${CMAKE_CURRENT_BINARY_DIR}/Release>")
			
            target_link_libraries(${whatExecutableIsBuilding} $ENV{OpenSSLDir}/lib/ssleay32.lib $ENV{OpenSSLDir}/lib/libeay32.lib)
			
			if(EXISTS "$ENV{OpenSSLDir}/bin/libeay32.dll")
			    message("bin/libeay32.dll exists")
			else()
			    message("bin/libeay32.dll does not exist")
			endif()
			
			if(EXISTS "$ENV{OpenSSLDir}/bin/ssleay32.dll")
			    message("bin/ssleay32.dll exists")
			else()
			    message("bin/ssleay32.dll does not exist")
			endif()
        
            file(COPY $ENV{OpenSSLDir}/bin/libeay32.dll DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/Debug)
            file(COPY $ENV{OpenSSLDir}/bin/ssleay32.dll DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/Debug)

            file(COPY $ENV{OpenSSLDir}/bin/libeay32.dll DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/Release)
            file(COPY $ENV{OpenSSLDir}/bin/ssleay32.dll DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/Release)
			
			message(FATAL_ERROR "ending run here")
        endif()
```

**Comment by ras0219-msft** [comment]
Just to chime in here:
>Output:
>>CMake Error: The source directory "C:/Development/sdk/vcpkg" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

This sounds like your command line didn't point to the project you want to build (a common issue for new CMake users). If the project you want to build lives at `C:\foo` then the right way to use cmake is:

```
C:\foo>mkdir build
C:\foo>cd build
C:\foo\build>cmake .. -DCMAKE_TOOLCHAIN_FILE=C:\path\to\vcpkg\scripts\buildsystems\vcpkg.cmake
```

Note that you need to pass `..` as the first argument to cmake to tell it where to find the project to build. Unlike MSBuild, CMake prefers to do "out of source" builds -- you shouldn't just run `cmake` at the root of the git clone!

**Comment by DataWerkt** [comment]
@jspaith 

Since removing the space in the set variable statement didn't resolve the issue, I added you code as described. The result is this:

![image](https://user-images.githubusercontent.com/38495817/43073383-a6e786da-8e79-11e8-8375-17467960041d.png)

I also tried if changing the slashes (backward- forward) made any difference. It didn't.

**Comment by DataWerkt** [comment]
@ras0219-msft I tried it and it builds. So pointing to the correct project was the issue. The thing is that I need to build it with OpenSSL, which is not happening with this type of build for as far as I can see. Thanks for thinking along!

**Comment by jspaith** [comment]
Indeed, thanks a lot @ras0219-msft A TON for guidance here.

Before I close this I want to get general agreement on how to update [this](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#using-openssl-in-the-sdk).  I'll put appropriate poetry and remove cruft around the instructions later, but at its core customers need:

* https://github.com/Microsoft/vcpkg, follow its instructions on initial setup.  Assume install dir is c:\vcpkg
* .\vcpkg install openssl
* Call out that version is currently `OpenSSL 1.0.2`.
* When running cmake, add `-DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake`.    
* Remember that cmake needs to be in .\cmake off C SDK repro.

Also an important note for @DataWerkt and I'll call out in instructions.  YOU are responsible for keeping up to date with openssl fixes (security fixes explicitly).  There's no Windows Update (for schannel) or apt-get (for Linux based openssl).

**Comment by jspaith** [comment]
@DataWerkt - did you copy/paste @ras0219-msft cmake command line directly?  If so, you're not linking to openssl because there's no `-Duse_openssl:BOOL=ON` anymore.  This is straight to Windows crypto library which is always going to just work.

Azure IoT C SDK wants to tie into vpckg for everything eventually but we're not there yet.  When I tried this experiment with pointing OpenSSLDir at a garbage directory but using the cmake in the chain, I got failures as expected since the C SDK is still using the openssl variable to copy.

One thing I see looking at the screen shot is in your explorer window, the directory is named `openssl-windows_x86-windows` (or something like that) which doesn't match the files output in my cmake log.

**Comment by DataWerkt** [comment]
@jspaith Yes I did and also concluded that this wasn't working / building with OpenSSL. I tried some variations on the statement, but it didn't make any difference.

> One thing I see looking at the screen shot is in your explorer window, the directory is named openssl-windows_x86-windows (or something like that) which doesn't match the files output in my cmake log

So where do you expect them to be? 

Can you elaborate a bit more on what the actions and the timeline will be regarding this issue? As much as I appreciate the time and effort you've spend, on my end it doesn't feel like there is much progress.

**Comment by jspaith** [comment]
I'm afraid I don't have a timeline as this is some config / interaction process.

For the hypen I was referring to above, the directory name that your files live in the screen capture of your file explorer window don't match the name of the file being output from CMake.  I can't copy/paste from a gif directly, but the windows explorer is showing these files in a directory of something like "...\openssl-windows_x86-windows\..." whereas cmake is looking for them in "...\openssl_x86-windows\...".  

Either there's a typo in how you setup the `OpenSSLDir` variable or something weird is happening on mangling of the `OpenSSLDir` in cmake, but it's not clear how the var could get so mangled.  Could you please see if the directory output by cmake really match and re-print out here what `OpenSSLDir` is ?

**Comment by DataWerkt** [comment]
It was indeed a wrong variable reference. 

![image](https://user-images.githubusercontent.com/38495817/43447227-543d51fc-94ab-11e8-857b-65ef3ac6b16f.png)

I assumed everything was ok at this stage and went to this [manual](https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509#create-a-self-signed-x509-device-certificate). Don't know if these steps still apply, but looking at my build solution I see that the "Provision_Tools" folder is not there after the build.

**Comment by jspaith** [comment]
Per the link, you need to set `-Duse_prov_client:BOOL=ON` at cmake time.  The C SDK is design to run on everything from small devices to full OS's like Win/Linux and the provisioning stuff gets into TPM stuff quickly so we don't want to flip that on by default.

Since we've addressed the initial problem here and I've clarified docs some, I'm going to close out this particular issue.  If there's other issues - either on provisioning or across the board - by all means open a new request.

Thanks

**Comment by az-iot-builder-01** [comment]
@DataWerkt, @ras0219-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
