### ISSUE TITLE
IoTHubClient_Auth_CreateFromDeviceAuth fails if cred_type IOTHUB_CREDENTIAL_TYPE_X509_ECC

### ISSUE THREAD

**Issue by ghost** [Azure/azure-iot-sdk-c#557]
- **OS and version used: Ubuntu 16.04

- **SDK version used: 1.2.7 

# Description of the issue:

After DPS successfully completes, attempting to utilized the credentials obtained from it fails unless this line in the function IoTHubClient_Auth_CreateFromDeviceAuth in azure-iot-sdk-c/iothub_client/src/iothub_client_authorization.c is changed from this...
result->cred_type = IOTHUB_CREDENTIAL_TYPE_X509_ECC;
...to this...
result->cred_type = IOTHUB_CREDENTIAL_TYPE_X509;

# Code sample exhibiting the issue:
Available upon request.

# Console log of the issue:

**Comment by jebrando** [comment]
@jdhuntington What failure are you seeing when the this fails?

**Comment by jebrando** [comment]
I have been unable to repro the issue if you continue to see this, please reopen the issue or create a new issue and reference this one.  Thank you.
