### ISSUE TITLE
This is a test issue. Please disregard

### ISSUE THREAD

**Issue by ewertons** [Azure/azure-iot-sdk-c#558]
- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by ewertons** [comment]
Test comment 1

**Comment by ewertons** [comment]
Please help us improve by filling out

**Comment by ewertons** [comment]
BLABLABLA

**Comment by yzhong94** [comment]
hi

**Comment by ewertons** [comment]
@ewertons, @yzhong94, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)

**Comment by az-iot-builder-01** [comment]
@ewertons, @yzhong94, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)

**Comment by kiranpradeep** [comment]
@ewertons. Sorry for not using this issue correct. But the "Submit new issue" button is disabled when we attempt to create new issues.
