### ISSUE TITLE
[question] What does LL mean clearly?

### ISSUE THREAD

**Issue by LJenny** [Azure/azure-iot-sdk-c#559]
- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

I am studying Azure IoT SDK.
I had a question while looking at the client SDK.
Some APIs are tagged with LL.
What's the difference between these two?
#include "iothub_device_client_ll.h" VS #include "iothub_device_client.h"
(Ex) IoTHubDeviceClient_SetOption vs. IoTHubDeviceClient_LL _ SetOption
I know it's roughly low level APIs. But I don't know exactly what the difference is.
Thank you in advance.

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by ewertons** [comment]
Hi @LJenny ,
please take a look at this documentation: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-c-iothubclient

**Comment by LJenny** [comment]
Thank you. I missed it. You've been a great help to me.

**Comment by ewertons** [comment]
That's what we are here for.
Let us know if we can help in any other way.
