### ISSUE TITLE
logStream only works on AMQP

### ISSUE THREAD

**Issue by lucarv** [Azure/azure-iot-sdk-c#561]
- **OS and version used:** <VERSION>  Embedded Linux 4.9.40

- **SDK version used:** <VERSION>  latest as per 11th of June 2018

# Description of the issue:

LogStream set to true only outputs to stdout if the protocol is AMQP

# Code sample exhibiting the issue:

iothub_ll_telemetry_sample from SDK with 
        bool traceOn = false;
        IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_LOG_TRACE, &traceOn);

# Console log of the issue:

I have a customer with an intermittent error and we need to be able to set traces. At the moment we can only trace with AMQP.

**Comment by jebrando** [comment]
@lucarv tracing does not work on HTTP, only errors are logged.  What happens when you add trace to MQTT does anything come out?

**Comment by lucarv** [comment]
@jebrando correct, nothing comes out

**Comment by jspaith** [comment]
One thing I notice is in the sample code above, you're setting 'traceOn=false'.  This needs to be set to true.

**Comment by lucarv** [comment]
@jspaith tha was a ctrlC ctrlV error, i had the trace set to true of course ;)

**Comment by lucarv** [comment]
@jspaith we were using the telemetry sampl as above, the only difference is what protocol we were commenting in and out. One after the other, several times, in different orders. nothing else happening on the device.
We will try your suggestion on last bullet....

**Comment by jspaith** [comment]
Have you got a chance to look deeper into this or need any more guidance from us?  If in the sample you put `#include "azure_c_shared_utility/xlogging.h"` and just `LogInfo("HI!");` that'll give a sense of whether logger itself is properly wired <=> stdout, and if it is give sense of where to put breakpoints for when MQTT starts trying to invoke it.

**Comment by lucarv** [comment]
I have forwarded this to the customer and apparently nothing has changed and still not working.
I suppose/assume You confirm that this work on practice and that is definitely something we are doing wrong.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jspaith** [comment]
Hi @lucarv - since this has been quiet for a bit I'm closing.  That said, I'm quite curious about what's up here so if you can provide some of additional data from above and think we can help continue to debug by all means re-activate this.

**Comment by az-iot-builder-01** [comment]
@lucarv, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
