### ISSUE TITLE
parson.lib missing from the Microsoft.Azure.IoTHub.IoTHubClient.targets in the IoTHubClient NuGet package

### ISSUE THREAD

**Issue by paloukari** [Azure/azure-iot-sdk-c#571]
- **SDK version used:** 1.2.8

# Description of the issue:

Installing the Microsoft.Azure.IoTHub.IoTHubClient nuget package (1.2.8) does add **parson.lib** reference in the linker, resulting linker errors.

# Console log of the issue:

`1>iothub_client.lib(iothub_client_edge.obj) : error LNK2019: unresolved external symbol _json_parse_string referenced in function _parseResponseJson
1>iothub_client.lib(iothub_client_ll_uploadtoblob.obj) : error LNK2001: unresolved external symbol _json_parse_string
1>hsm_security_client.lib(hsm_client_http_edge.obj) : error LNK2001: unresolved external symbol _json_parse_string
1>iothub_client.lib(iothub_client_edge.obj) : error LNK2019: unresolved external symbol _json_serialize_to_string referenced in function _parseResponseJson
1>hsm_security_client.lib(hsm_client_http_edge.obj) : error LNK2001: unresolved external symbol _json_serialize_to_string
1>iothub_client.lib(iothub_client_edge.obj) : error LNK2019: unresolved external symbol _json_object_get_value referenced in function _parseResponseJson
1>iothub_client.lib(iothub_client_edge.obj) : error LNK2019: unresolved external symbol _json_value_free referenced in function _parseResponseJson
1>iothub_client.lib(iothub_client_ll_uploadtoblob.obj) : error LNK2001: unresolved external symbol _json_value_free
1>hsm_security_client.lib(hsm_client_http_edge.obj) : error LNK2001: unresolved external symbol _json_value_free
1>iothub_client.lib(iothub_client_edge.obj) : error LNK2019: unresolved external symbol _json_value_get_object referenced in function _parseResponseJson
1>iothub_client.lib(iothub_client_ll_uploadtoblob.obj) : error LNK2001: unresolved external symbol _json_value_get_object
1>hsm_security_client.lib(hsm_client_http_edge.obj) : error LNK2001: unresolved external symbol _json_value_get_object
1>iothub_client.lib(iothub_client_edge.obj) : error LNK2019: unresolved external symbol _json_value_get_number referenced in function _parseResponseJson
1>iothub_client.lib(iothub_client_ll_uploadtoblob.obj) : error LNK2019: unresolved external symbol _json_object_get_string referenced in function _IoTHubClient_LL_UploadToBlob_step1and2
1>hsm_security_client.lib(hsm_client_http_edge.obj) : error LNK2019: unresolved external symbol _json_free_serialized_string referenced in function _construct_json_signing_blob
1>hsm_security_client.lib(hsm_client_http_edge.obj) : error LNK2019: unresolved external symbol _json_object_dotget_string referenced in function _parse_json_signing_response
1>hsm_security_client.lib(hsm_client_http_edge.obj) : error LNK2019: unresolved external symbol _json_object_set_string referenced in function _construct_json_signing_blob
1>hsm_security_client.lib(hsm_client_http_edge.obj) : error LNK2019: unresolved external symbol _json_object_clear referenced in function _construct_json_signing_blob
1>hsm_security_client.lib(hsm_client_http_edge.obj) : error LNK2019: unresolved external symbol _json_value_init_object referenced in function _construct_json_signing_blob`

**Comment by jspaith** [comment]
Thanks for calling this to our attention.  I've fixed the samples - see commit referenced above.  And we'll make it so our pre-release Nuget process builds samples.  Currently it builds and runs e2e tests but not samples.

**Comment by az-iot-builder-01** [comment]
@paloukari, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
