### ISSUE TITLE
Unable to send message even when the SendEventAsync is successful 

### ISSUE THREAD

**Issue by hiteshpratyushv** [Azure/azure-iot-sdk-c#579]
- **OS and version used:** <Windows 10 - on MSYS2 along with ESP-IDF> 

- **SDK version used:** <VERSION> 

# Description of the issue:
I am able to create a connection. The SendEventAsync also functions correctly as it shows correct output.
But I don't get a confirmation. I have split the connection part and sending part as I need them to work separetely.

# Code sample exhibiting the issue:
`
static IOTHUB_CLIENT_LL_HANDLE iotHubClientHandle;

static void SendConfirmationCallback(IOTHUB_CLIENT_CONFIRMATION_RESULT result, void* userContextCallback)
{
    EVENT_INSTANCE* eventInstance = (EVENT_INSTANCE*)userContextCallback;

    (void)printf("Confirmation received for message\r\n");
    IoTHubMessage_Destroy(eventInstance->messageHandle);
}

void mqtt_connect()
{
    int receiveContext = 0;
    if (platform_init() != 0)
    {
        (void)printf("Failed to initialize the platform.\r\n");
    }
    else
    {
        if ((iotHubClientHandle = IoTHubClient_LL_CreateFromConnectionString(connectionString, MQTT_Protocol)) == NULL)
        {
            (void)printf("ERROR: iotHubClientHandle is NULL!\r\n");
        }
        else
        {
            bool traceOn = true;
            //(void)printf("size before IoTHubClient_LL_SetOption: %d \n", system_get_free_heap_size());
            IoTHubClient_LL_SetOption(iotHubClientHandle, "logtrace", &traceOn);

#ifdef MBED_BUILD_TIMESTAMP
            // For mbed add the certificate information
            if (IoTHubClient_LL_SetOption(iotHubClientHandle, "TrustedCerts", certificates) != IOTHUB_CLIENT_OK)
            {
                printf("failure to set option \"TrustedCerts\"\r\n");
            }
#endif // MBED_BUILD_TIMESTAMP

            /* Setting Message call back, so we can receive Commands. */
            //(void)printf("size before IoTHubClient_LL_SetMessageCallback: %d \n", system_get_free_heap_size());
            if (IoTHubClient_LL_SetMessageCallback(iotHubClientHandle, ReceiveMessageCallback, &receiveContext) != IOTHUB_CLIENT_OK)
            {
                (void)printf("ERROR: IoTHubClient_LL_SetMessageCallback..........FAILED!\r\n");
            }
            else
            {
                (void)printf("IoTHubClient_LL_SetMessageCallback...successful.\r\n");                
            }
        }
    }

    vTaskDelete(NULL);

}

void mqtt_publish(void *param)
{
    EVENT_INSTANCE message;
    char *TOPIC = "locdata/topic";
    int TOPIC_LEN = strlen(TOPIC);

    char *buffer = (char*)param;

    //sprintf_s(msgText, sizeof(msgText), "{\"deviceId\":\"AirConditionDevice_001\",\"windSpeed\":%.2f}", avgWindSpeed + (rand() % 4 + 2));
    printf("Ready to Send String:%s\n",(const char*)buffer);
            //(void)printf("size before IoTHubMessage_CreateFromByteArray: %d \n", system_get_free_heap_size());
    if ((message.messageHandle = IoTHubMessage_CreateFromByteArray((const unsigned char*)buffer, strlen(buffer))) == NULL)
    {
        (void)printf("ERROR: iotHubMessageHandle is NULL!\r\n");
    }
    else
    {
        message.messageTrackingId = 0;
                //(void)printf("size before IoTHubMessage_Properties: %d \n", system_get_free_heap_size());
        MAP_HANDLE propMap = IoTHubMessage_Properties(message.messageHandle);
        if (Map_AddOrUpdate(propMap, "topic", TOPIC) != MAP_OK)
        {
            (void)printf("ERROR: Map_AddOrUpdate Failed!\r\n");
        }
                //(void)printf("free heap size before IoTHubClient_LL_SendEventAsync: %d \n", system_get_free_heap_size());
        if (IoTHubClient_LL_SendEventAsync(iotHubClientHandle, message.messageHandle, SendConfirmationCallback, &message) != IOTHUB_CLIENT_OK)
        {
            (void)printf("ERROR: IoTHubClient_LL_SendEventAsync..........FAILED!\r\n");
        }
        else
        {
            (void)printf("IoTHubClient_LL_SendEventAsync Completed\r\n");
        }
        IoTHubClient_LL_DoWork(iotHubClientHandle);
        ThreadAPI_Sleep(1);
    } 
    vTaskDelete(NULL);
}
`
# Console log of the issue:
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync Completed

Please let me know if it's my code's problem or not.

**Comment by jspaith** [comment]
I *think* the problem here is how you're using the IotHubClient_LL_DoWork().  Basically when using the _LL_ API's, you are responsible for repeatedly calling IotHubClient_LL_DoWork() since **all** work - including sending of the message, listening for data off network, etc. - is done on this worker thread.  Just calling IotHubClient_LL_DoWork the first time will be enough to send the message but you'd need subsequent calls to it to receive any confirmation callbacks from IoTHub.  I'm not seeing a loop above.

If you don't want to be in the business of repeatedly calling DoWork and you're on a platform where an extra worker thread is OK (i.e. you're not on some pretty limited embedded platform) you can use the convenience layer.  Here you'd just do IotHubClient_SendEventAsync() and a worker thread automatically created would be interacting with networking stack and calling your callback.

**Comment by hiteshpratyushv** [comment]
@jspaith Can you walk me through or point me to any post that can help me through it ?
I am very new to ESP coding so any help would be good

**Comment by ewertons** [comment]
Hi @hiteshpratyushv ,
you could follow the [sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c) we have. It shows how to call the LL_DoWork function with the proper frequency.

**Comment by jspaith** [comment]
Since this has been quiet for a week, I'm going to close out.  @hiteshpratyushv if you have specific follow up questions based on the sample, by all means reactivate or create a new issue.  Thanks

**Comment by az-iot-builder-01** [comment]
@hiteshpratyushv, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
