### ISSUE TITLE
C++ Implementation for iothub_device_client_ll failure

### ISSUE THREAD

**Issue by racecannon** [Azure/azure-iot-sdk-c#585]
Linux Embedded for ARM

- **OS and version used:** <VERSION>  Ubuntu 14.04

- **SDK version used:** <VERSION>  1.2.8

# Description of the issue:

During compilation, I get 273 errors. They all say "template with C linkage" or "conflicting declaration of C function". It looks like the library is not compatible with C++. I have been able to utilize other files without issue. So far, this issue seems to be linked directly to the iothub_device_client_ll library. 

# Code sample exhibiting the issue:

I can make this happen with an empty C++ file that only contains the line:

#include "iothub_device_client_ll.h"

Without this line, I get no errors. With this line, I get 273 errors.

# Console log of the issue:

**Comment by jspaith** [comment]
Could you please checkout #577 and the PR associated with it.  It turns out there are problems with sdk over-doing extern "C", which a PR was recently put out for.

**Comment by racecannon** [comment]
Yes. That looks like the same issue.

**Comment by jspaith** [comment]
OK.  I'm going to close it out then; if new issues arrise after the PR we can reactivate.  The fix should hopefully be on its way through our gates shortly.  Thanks & sorry you ran into this, too.

**Comment by az-iot-builder-01** [comment]
@racecannon, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
