### ISSUE TITLE
IoTHubMessaging_Open failed despite having a internet connectivity 

### ISSUE THREAD

**Issue by Purnanandj** [Azure/azure-iot-sdk-c#588]
Despite Having the internet connectivity all of sudden the iothub throughs following error messages:

Can anyone help on debugging the below issue.

Opening Messaging...
Error: Time:Wed Aug  8 12:56:44 2018 File:/usr/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_ope                                                                                                                                                      n Line:676 Failure: select failure.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Wed Aug  8 12:56:44 2018 File:/usr/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open                                                                                                                                                      _complete Line:688 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Wed Aug  8 12:56:44 2018 File:/usr/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Li                                                                                                                                                      ne:1202 Failed opening the underlying I/O.
Error: Time:Wed Aug  8 12:56:44 2018 File:/usr/azure-iot-sdk-c/uamqp/src/saslclientio.c Func:saslclientio_open_async Li                                                                                                                                                      ne:1081 xio_open failed
Error: Time:Wed Aug  8 12:56:44 2018 File:/usr/azure-iot-sdk-c/uamqp/src/connection.c Func:connection_open Line:1253 Op                                                                                                                                                      ening the underlying IO failed
Error: Time:Wed Aug  8 12:56:44 2018 File:/usr/azure-iot-sdk-c/iothub_service_client/src/iothub_messaging_ll.c Func:IoT                                                                                                                                                      HubMessaging_LL_Open Line:1255 Could not open the message sender.
Error: Time:Wed Aug  8 12:56:44 2018 File:/usr/azure-iot-sdk-c/uamqp/src/amqpvalue.c Func:amqpvalue_destroy Line:3302 N                                                                                                                                                      ULL value
Error: Time:Wed Aug  8 12:56:44 2018 File:/usr/azure-iot-sdk-c/uamqp/src/amqpvalue.c Func:amqpvalue_destroy Line:3302 N                                                                                                                                                      ULL value
IoTHubMessaging_Open failed

**Comment by ewertons** [comment]
Hi @Purnanandj ,
perhaps you missed the template for filing issues, could you please fill those up first?

What version of the client you are using?
Which OS, version?

**Comment by Purnanandj** [comment]
Hi @ewertons ,

apologies for not providing the relevant information. Kindly find the same as mentioned below: 

What version of the client you are using?
SDK Version in C is IOT_SDK_VERSION 1.1.23

Which OS, version?
Yocto Embedded Linux , Kernel : 4.1.15.1

**Comment by lakshmisivareddy** [comment]
Hi @Purnanandj 

Error: Time:Wed Aug 8 12:56:44 2018 File:/usr/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_ope n Line:676 Failure: select failure.
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR

it look like it's openssl error , this error may  come be from incorrect version of openssl or if certificates are not properly configured 
can u provide details about which sample u r trying

**Comment by Purnanandj** [comment]
Hi @lakshmisivareddy ,

Thanks for the reply.

The issue is actually popping up all of sudden while running it for long time.

Wrt to sample which  i am running is from iothub_service_client/iothub_messaging_sample

**Comment by ewertons** [comment]
Hi @Purnanandj ,
Looking at the log you shared it says select() failed on your environment.

The trace is printed in [this line](https://github.com/Azure/azure-c-shared-utility/blob/942909698415cc0bd6483e063a2cfa8da626edc6/adapters/socketio_berkeley.c#L676) of the code.


[select()](http://man7.org/linux/man-pages/man2/select.2.html) failed on your environment, however the code doesn't print the errno, so we cannot conclude for sure what happened.

Did you make any changes to your environment?
Are you able to reach your iothub hub (using telnet against port 5671, if you are using AMQP)?


Other than that we would need to make a code change to print the specific errno. 
If we check in the change, would you be able to update your version of SDK and test it again?

**Comment by chinnaece** [comment]
Facing same problem please help me .


root@am57xx-evm:~# ./iothub_ll_telemetry_sample 
Creating IoTHub handle
Sending message 1 to IoTHub
Error: Time:Tue Oct  9 13:00:42 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:632 Failure: getaddrinfo failure -5.
Error: Time:Tue Oct  9 13:00:42 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:725 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Oct  9 13:00:42 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1209 Failed opening the underlying I/O.
Error: Time:Tue Oct  9 13:00:42 2018 File:/home/kdasari/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:981 Error: io_open failed
Error: Time:Tue Oct  9 13:00:42 2018 File:/home/kdasari/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1893 failure connecting to address IH-Embedded-COE.azure-devices.net.
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
Error: Time:Tue Oct  9 13:00:43 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:632 Failure: getaddrinfo failure -5.
Error: Time:Tue Oct  9 13:00:43 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:725 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Oct  9 13:00:43 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1209 Failed opening the underlying I/O.
Error: Time:Tue Oct  9 13:00:43 2018 File:/home/kdasari/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:981 Error: io_open failed
Error: Time:Tue Oct  9 13:00:43 2018 File:/home/kdasari/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1893 failure connecting to address IH-Embedded-COE.azure-devices.net.
^C

**Comment by ewertons** [comment]
Hi @Purnanandj ,
we will close this issue for now, but please feel free to reopen it if you would like to follow up.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@ewertons, @Purnanandj, @lakshmisivareddy, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by NguyenGiangTruong** [comment]
@ewertons could you please re-open this issue. we got a similar error here, with select "select failure" issue appearing on the log.

**Comment by jelalanne** [comment]
Hello, any solution ?
