### ISSUE TITLE
socketio_dowork design/implementation failure

### ISSUE THREAD

**Issue by jflynn129** [Azure/azure-iot-sdk-c#591]
- **OS and version used:** <VERSION> 
Mbed v5.9 OS,  GNU tools, …

- **SDK version used:** <VERSION> 
Version: 2018-07-11

# Description of the issue:
I am building/using the azure-iot-sdk-c and iothub_client_sample_http sample while porting the software to a cellular enabled device, i.e., the device uses a cellular data connection instead of a wired Ethernet connection. I have verified it the build works correctly when running with a wired Ethernet connection. When I switch over to a Cellular Data connection, the software fails consistently.

I have investigated this issue and have narrowed the problem down to the functioin ‘void socketio_dowork(CONCRETE_IO_HANDLE socket_io)’.  This function appears to do three things:

(1)	Process any data that was previously placed in the receive queue
(2)	Process any data that has been requested to be sent
(3)	Receive and store any data into the receive queue (to be processed during next socketio_dowork call)

As currently implemented, Azure assumes that data coming from the in step #3 will all arrive contiguously in time with no breaks as a complete message. For a Ethernet adapter, this is the case, but for a cellular connection, it is not.  There can be lags between data transmissions so it is possible to get a chunk of data, then the remainder of the data at a later time.  This means you will get a segment of data followed by a ‘no more data available’ indication from the socket driver.  This partial message is then 
stored in the Rx queue. 

During the next call to socketio_dowork, this partial message is will be acted on as it assumes the message is the queue is a complete message, it fails (because it is not a complete message).  Then step #2 occurs (tx’ing messages), then step #3 occurs (and the remained of the first message is received and stored).  Then during the next call to socketio_dowork, the software tries to act on the second half of the message and it fails again.

This problem can be fixed if you enable blocking during the socketio_open call.  If you do enable blocking the system will block rather than report back no data and a complete message will be received and successfully processed, e.g., no errors and everything works as expected only excruciatingly slow due to the blocking. 

I was able to improve the responsiveness by adding a delay to my tcpsocketconnection_receive() function so that the inter-message delay was overlooked which helped but still resulted in sluggish performance.

I believe you can simulate the same behavior by adding a random delay in the tcpsocketconnection_receive() function.  When the delay is active, return 0 so that you get a message sequence such as:

`<msg start><msg middle>**<0>**<msg end>`

 (move the <0> anywhere between consecutive message parts to simulate the cellular data connection).
I would propose a solution but I do not fully understand the design behind the socketio_dowork() function/the queues used/expected flows.

**Comment by jflynn129** [comment]
@terrymandin

**Comment by jflynn129** [comment]
@terrymandin

**Comment by az-iot-builder-01** [comment]
@jflynn129, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by jflynn129** [comment]
Just curious if anyone has reviewed this yet?

**Comment by jspaith** [comment]
@jflynn129  - sorry for delay here, we have folks getting back from various states of being out of office so were a bit shorthanded.  And thanks for *very* detailed analysis here.

You definitely don't want to do blocking I/O.  Beyond the slowness, our SDK is designed to run on one thread per client handle (hence the polling) so it'd block operations across SDK.

I'm not as familiar with the MBED PAL layer, so one thing I'd need help understanding is in your (1) above - looking at `socketio_dowork` I'm seeing us processing pending IOs but these seem to only come from sends.  The recv call I don't see interacting with previous state, but just calling the `tcpsocketconnection_receive` and invoking the `on_bytes_received` if there's data.  I'm likely missing something here so please set me straight.  

Also let's double check we're referencing the same file here for mbed PAL - i'm using [this](https://github.com/Azure/azure-c-shared-utility/blob/009eb4b3dced8186f9ddb0ab0dddb24dda9cea8f/adapters/socketio_mbed.c).

**Comment by jflynn129** [comment]
@jspaith thank you for the response. You are correct, that is the file I am looking at. The project I am building is at https://github.com/jflynn129/mbedv5_iothub_client_sample_http to be specific.

I am only speculating on some of this based on what I have tried to understand about the operation of the socketio_dowork function. My (1) could very possibly be incorrect after I am looking at it again. But the basic behavior does follow my explanation above.

The section of code:
```
    while (received > 0) {
        unsigned char* recv_bytes = (unsigned char*)malloc(MBED_RECEIVE_BYTES_VALUE);
        if (recv_bytes == NULL) {
            LogError("Socketio_Failure: NULL allocating input buffer.");
            indicate_error(psock);
            }
        else {
            received = tcpsocketconnection_receive(psock->socket, (char*)recv_bytes, MBED_RECEIVE_BYTES_VALUE);
            if (received > 0) {
                if (psock->on_bytes_received != NULL) {
                    /* explictly ignoring here the result of the callback */
                    (void)psock->on_bytes_received(psock->on_bytes_received_context, recv_bytes, received);
                    }
                }
            free(recv_bytes);
            }
        }

```
Is where it gets hung up and the incorrect behavior occurs. The function `on_bytes_received` actually resolves to `on_underlying_io_bytes_received` in the file **tlsio_mbedtls.c**.  This function looks like it is copying the received data from the original buffer to another buffer and exiting.  I am not sure where or when this second buffer gets processed, I just assumed it was at the beginning of the do_work function though it could be somewhere else... it isn't clear to me where or when it is processed.

What does happen though is chunks of the message is received often separated by multiple _no-data-available_ responses from the socket and this situation is what appears to cause the failure.

Possible responses from` tcpsocketconnection_receive` are 0 (zero) meaning there is no data available and a receive time-out occured, a positive number representing the number of bytes received (which may be less than the number requested), a NSAPI_ERROR_WOULD_BLOCK (negative number) which indicates that no data was received yet but the read request is still pending, or another negative response indicating some other error.

When the 0 response is returned (the socket has timed out with no data being received for 3 seconds [I can change this value to shorten or lengthen the time-out in the driver]) is when the problems seem to occur.

**Comment by jflynn129** [comment]
@jspaith 
Found the problem!  it was a combination of my driver and the socketio_dowork routine. The socketio_dowork routine mallocs memory then calls socket read, when it doesn't get any data, it frees the memory and exits.  In the socket read, if it would block, it returns but keeps trying to read the data for a time-out period.  But the socketio_dowork routine has already freed the buffer that socket read is putting data into so it was causing a memory corruption.

I created a static interim buffer in the `tcpsocketconnection_read()` routine and use that for all socket calls then if data is available, I copy it to the callers buffer.

**Comment by jspaith** [comment]
@jflynn129  - just to make sure I understand, it sounds like::
1 - socketio_dowork() allocates data, passes this pointer down
2 - someplace in your driver you save off this pointer
3 - no data available, so socketio_dowork() frees the data
4 - the driver has a reference to this and then writes the freed memory.

Is this correct?  And it sounds like it was in the underlying driver, so the SDK PAL layer doesn't have problems?

If this is correct we'll close out this issue, but if there's something wrong with Azure's PAL we want to understand & fix.

Thanks for really deep debugging across our code & yours here.

**Comment by jflynn129** [comment]
Close, step #2 were the pointer gets saved off, it doesn't return no data, it returns NSAPI_ERROR_WOULD_BLOCK but it continues to try and get the requested data, then when it is received the data, it saves it for the caller.  But that pointer was already freed so it is basically corrupting memory at that point.

I fixed it by placing a static buffer into the tcpsocketconnection_receive() function to buffer all data received from the socket. The fix is in the SDK file `c-utility/adapters/tcpsocketconnection_c.cpp`. But this file is expected to be modified for any port so I don't believe there is anything to fix other than better documentation describing the expected behavior of the tcpsocketconnection* functions.

For purposes of this issue though, I believe this is resolved and could be closed. BTW, this fix was:
```
int tcpsocketconnection_receive(TCPSOCKETCONNECTION_HANDLE tcpSocketHandle, char* data, int length)
{
    TCPSocket* socket = (TCPSocket*)tcpSocketHandle;
    static char loc_data[MBED_RECEIVE_BYTES_VALUE];

    int cnt = socket->recv(loc_data, MBED_RECEIVE_BYTES_VALUE);
    if( cnt > 0 )
        memcpy(data,loc_data,cnt);

    return cnt;
}

```

**Comment by jspaith** [comment]
@jflynn129 - thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute customer satisfaction survey.
