### ISSUE TITLE
Notes and questions about Azure integration

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [Azure/azure-iot-sdk-c#592]
- **OS and version used:**  Windows 10

- **SDK version used:** 1.2.8

# Description of the issue:
I would like to share my observations obtained during integration of Azure C SDK to NXP MCUX SDK.

# Environment description:
**Related middlewares:**
    LWIP TCP/IP stack
    FreeRTOS Operation system
    mbedTLS SSL layer

**Supported tool-chains:**
    armgcc
    IAR EWARM
    MDK
    MCUXpresso IDE

# Issues overview:
**Code formatting issues:**
    - trailing white spaces
    - mix of tabs and spaces (spaces recommended)
    - missing new line on the end of files (causing warnings in MDK)
**Code architecture:**
    - missing Freertos adapter
    - too general file names, hmac.c, version.h cause conflicts with other middlewares, unique prefix "azure_" would be more practical.
**Repository structure:**
    - repo contains identical submodules in several places. I think the nested submodules are not best choice. Flat structure could avoid such issue.
    - release zip contains empty folders. It is strange. Release package should contain all necessary parts.
**Toolchain specific issues:**
    - warnings, Could you introduce build tests for some embedded toolchains like IAR, MDK, ARMGCC or MCUXPRESSO IDE?
    - limitations of toolchain specific system libraries

# Comments:
Because of the repository structure, I cannot add azure-iot-sdk-c as submodule directly into NXP MSDK repository. I am using snapshot without submodules.
Main issue is existence of redundant submodules - it slows down repository synchronization. I have created socketio layer for lwip based on socketio_berkeley.c I am currently supporting only LL api only, but I would like to provide also multitasking version.

# Questions:
Could you create FreeRTOS adapter (avoid thread_join usage in code)?
Could you change submodule strategy to reduce duplicities?
Could you introduce build tests for IAR, MDK, ARMGCC and MCUXPRESSO IDE?
Could you eliminate formatting issues mentioned above?
Could you eventually review azure c sdk integrated in NXP MSDK? I can provide package.

# Attachments:

**List of all submodule locations (It is a lot from my perspective):** 
azure-iot-sdk-c\deps\uhttp\.git
azure-iot-sdk-c\uamqp\.git
azure-iot-sdk-c\umqtt\.git
azure-iot-sdk-c\deps\parson\.git
azure-iot-sdk-c\c-utility\.git
azure-iot-sdk-c\provisioning_client\deps\RIoT\.git
azure-iot-sdk-c\provisioning_client\deps\utpm\.git
azure-iot-sdk-c\uamqp\deps\umock-c\.git
azure-iot-sdk-c\deps\uhttp\deps\c-utility\.git
azure-iot-sdk-c\umqtt\deps\c-utility\.git
azure-iot-sdk-c\uamqp\deps\azure-ctest\.git
azure-iot-sdk-c\c-utility\testtools\ctest\.git
azure-iot-sdk-c\c-utility\testtools\umock-c\.git
azure-iot-sdk-c\uamqp\deps\azure-c-shared-utility\.git
azure-iot-sdk-c\c-utility\testtools\testrunner\.git
azure-iot-sdk-c\uamqp\deps\azure-c-testrunnerswitcher\.git
azure-iot-sdk-c\provisioning_client\deps\utpm\deps\c-utility\.git
azure-iot-sdk-c\uamqp\deps\umock-c\deps\testrunner\.git
azure-iot-sdk-c\uamqp\deps\umock-c\deps\ctest\.git
azure-iot-sdk-c\deps\uhttp\deps\c-utility\testtools\ctest\.git
azure-iot-sdk-c\umqtt\deps\c-utility\testtools\ctest\.git
azure-iot-sdk-c\deps\uhttp\deps\c-utility\testtools\umock-c\.git
azure-iot-sdk-c\umqtt\deps\c-utility\testtools\umock-c\.git
azure-iot-sdk-c\deps\uhttp\deps\c-utility\testtools\testrunner\.git
azure-iot-sdk-c\umqtt\deps\c-utility\testtools\testrunner\.git
azure-iot-sdk-c\c-utility\testtools\umock-c\deps\testrunner\.git
azure-iot-sdk-c\c-utility\testtools\umock-c\deps\ctest\.git
azure-iot-sdk-c\uamqp\deps\azure-c-shared-utility\testtools\ctest\.git
azure-iot-sdk-c\uamqp\deps\azure-c-shared-utility\testtools\umock-c\.git
azure-iot-sdk-c\uamqp\deps\azure-c-shared-utility\testtools\testrunner\.git
azure-iot-sdk-c\provisioning_client\deps\utpm\deps\c-utility\testtools\ctest\.git
azure-iot-sdk-c\provisioning_client\deps\utpm\deps\c-utility\testtools\umock-c\.git
azure-iot-sdk-c\provisioning_client\deps\utpm\deps\c-utility\testtools\testrunner\.git
azure-iot-sdk-c\deps\uhttp\deps\c-utility\testtools\umock-c\deps\testrunner\.git
azure-iot-sdk-c\umqtt\deps\c-utility\testtools\umock-c\deps\testrunner\.git
azure-iot-sdk-c\deps\uhttp\deps\c-utility\testtools\umock-c\deps\ctest\.git
azure-iot-sdk-c\umqtt\deps\c-utility\testtools\umock-c\deps\ctest\.git
azure-iot-sdk-c\uamqp\deps\azure-c-shared-utility\testtools\umock-c\deps\testrunner\.git
azure-iot-sdk-c\uamqp\deps\azure-c-shared-utility\testtools\umock-c\deps\ctest\.git
azure-iot-sdk-c\provisioning_client\deps\utpm\deps\c-utility\testtools\umock-c\deps\testrunner\.git
azure-iot-sdk-c\provisioning_client\deps\utpm\deps\c-utility\testtools\umock-c\deps\ctest\.git

**Identical submodules checking out also identical SHA:**
```
Submodule path 'c-utility': checked out 'b28bb6caa00a1bd7264bb22de8a36ca582405920'
Submodule path 'c-utility/testtools/ctest': checked out 'b1d09aff8212f1fb62ca9d6014cb3509d8b5559a'
Submodule path 'c-utility/testtools/testrunner': checked out '721daafd8c34616f77a7697210470c0227dca20b'
Submodule path 'c-utility/testtools/umock-c': checked out 'c2c0f18d785ba85fef213302266f520c64201bb1'
Submodule path 'c-utility/testtools/umock-c/deps/ctest': checked out 'b1d09aff8212f1fb62ca9d6014cb3509d8b5559a'
Submodule path 'c-utility/testtools/umock-c/deps/testrunner': checked out '721daafd8c34616f77a7697210470c0227dca20b'
Submodule path 'deps/parson': checked out 'bef4969d258d5bcce0d686b7bf514550e2ac346d'
Submodule path 'deps/uhttp': checked out '99d93eab71c7478321b41fcfa9b4722bdce80d8a'
Submodule path 'deps/uhttp/deps/c-utility': checked out 'b28bb6caa00a1bd7264bb22de8a36ca582405920'
Submodule path 'deps/uhttp/deps/c-utility/testtools/ctest': checked out 'b1d09aff8212f1fb62ca9d6014cb3509d8b5559a'
Submodule path 'deps/uhttp/deps/c-utility/testtools/testrunner': checked out '721daafd8c34616f77a7697210470c0227dca20b'
Submodule path 'deps/uhttp/deps/c-utility/testtools/umock-c': checked out 'c2c0f18d785ba85fef213302266f520c64201bb1'
Submodule path 'deps/uhttp/deps/c-utility/testtools/umock-c/deps/ctest': checked out 'b1d09aff8212f1fb62ca9d6014cb3509d8b5559a'
Submodule path 'deps/uhttp/deps/c-utility/testtools/umock-c/deps/testrunner': checked out '721daafd8c34616f77a7697210470c0227dca20b'
Submodule path 'provisioning_client/deps/RIoT': checked out 'bc97a5eaff53535eddbdf95b4f477c6caf3b7788'
Submodule path 'provisioning_client/deps/utpm': checked out '05de9e051485e7a48c86c4f547cd582ee057d312'
Submodule path 'provisioning_client/deps/utpm/deps/c-utility': checked out 'b28bb6caa00a1bd7264bb22de8a36ca582405920'
Submodule path 'provisioning_client/deps/utpm/deps/c-utility/testtools/ctest': checked out 'b1d09aff8212f1fb62ca9d6014cb3509d8b5559a'
Submodule path 'provisioning_client/deps/utpm/deps/c-utility/testtools/testrunner': checked out '721daafd8c34616f77a7697210470c0227dca20b'
Submodule path 'provisioning_client/deps/utpm/deps/c-utility/testtools/umock-c': checked out 'c2c0f18d785ba85fef213302266f520c64201bb1'
Submodule path 'provisioning_client/deps/utpm/deps/c-utility/testtools/umock-c/deps/ctest': checked out 'b1d09aff8212f1fb62ca9d6014cb3509d8b5559a'
Submodule path 'provisioning_client/deps/utpm/deps/c-utility/testtools/umock-c/deps/testrunner': checked out '721daafd8c34616f77a7697210470c0227dca20b'
Submodule path 'uamqp': checked out 'fbea000035666a918ebc36180c8eebdb4ee2bd71'
Submodule path 'uamqp/deps/azure-c-shared-utility': checked out 'b28bb6caa00a1bd7264bb22de8a36ca582405920'
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/ctest': checked out 'b1d09aff8212f1fb62ca9d6014cb3509d8b5559a'
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/testrunner': checked out '721daafd8c34616f77a7697210470c0227dca20b'
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/umock-c': checked out 'c2c0f18d785ba85fef213302266f520c64201bb1'
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/umock-c/deps/ctest': checked out 'b1d09aff8212f1fb62ca9d6014cb3509d8b5559a'
Submodule path 'uamqp/deps/azure-c-shared-utility/testtools/umock-c/deps/testrunner': checked out '721daafd8c34616f77a7697210470c0227dca20b'
Submodule path 'uamqp/deps/azure-c-testrunnerswitcher': checked out '721daafd8c34616f77a7697210470c0227dca20b'
Submodule path 'uamqp/deps/azure-ctest': checked out 'b1d09aff8212f1fb62ca9d6014cb3509d8b5559a'
Submodule path 'uamqp/deps/umock-c': checked out 'c2c0f18d785ba85fef213302266f520c64201bb1'
Submodule path 'uamqp/deps/umock-c/deps/ctest': checked out 'b1d09aff8212f1fb62ca9d6014cb3509d8b5559a'
Submodule path 'uamqp/deps/umock-c/deps/testrunner': checked out '721daafd8c34616f77a7697210470c0227dca20b'
Submodule path 'umqtt': checked out '80c641c0a16e393495cf18fe6186938256b3b7f5'
Submodule path 'umqtt/deps/c-utility': checked out 'b28bb6caa00a1bd7264bb22de8a36ca582405920'
Submodule path 'umqtt/deps/c-utility/testtools/ctest': checked out 'b1d09aff8212f1fb62ca9d6014cb3509d8b5559a'
Submodule path 'umqtt/deps/c-utility/testtools/testrunner': checked out '721daafd8c34616f77a7697210470c0227dca20b'
Submodule path 'umqtt/deps/c-utility/testtools/umock-c': checked out 'c2c0f18d785ba85fef213302266f520c64201bb1'
Submodule path 'umqtt/deps/c-utility/testtools/umock-c/deps/ctest': checked out 'b1d09aff8212f1fb62ca9d6014cb3509d8b5559a'
Submodule path 'umqtt/deps/c-utility/testtools/umock-c/deps/testrunner': checked out '721daafd8c34616f77a7697210470c0227dca20b'
```

**Reading of deps folders is like watching of Inception movie:**
```
azure-iot-sdk-c\c-utility\testtools\umock-c\deps\
    ctest
    testrunner
azure-iot-sdk-c\deps\
    parson
    uhttp
azure-iot-sdk-c\deps\uhttp\deps\
    c-utility
azure-iot-sdk-c\deps\uhttp\deps\c-utility\testtools\umock-c\deps\
    ctest
    testrunner
azure-iot-sdk-c\provisioning_client\deps\
    RIoT\
    utpm\
azure-iot-sdk-c\provisioning_client\deps\utpm\deps\
    c-utility
azure-iot-sdk-c\provisioning_client\deps\utpm\deps\c-utility\testtools\umock-c\deps\
    ctest
    testrunner
azure-iot-sdk-c\uamqp\deps\
    azure-c-shared-utility
    azure-ctest
    azure-c-testrunnerswitcher
    umock-c
azure-iot-sdk-c\uamqp\deps\azure-c-shared-utility\testtools\umock-c\deps\
    ctest
    testrunner
azure-iot-sdk-c\uamqp\deps\umock-c\deps\
    ctest
    testrunner
azure-iot-sdk-c\umqtt\deps\
    c-utility
azure-iot-sdk-c\umqtt\deps\c-utility\testtools\umock-c\deps\
    ctest
    testrunner
```

Regards,
David Jurajda

**Comment by DavidJurajdaNXP** [comment]
Issue was split in several standalone issues.

#615 Toolchain tests - ARM GCC, NXP MCUXpresso IDE, Keil MDK, IAR EWARM,
#614 Code formating - trailing whitespaces
#612 Release zip contains empty folders.
#611 Nested submodules introducing redundant folders
#610 General file names causing conflicts with other middlewares
#609 Missing FreeRTOS adapter

**Comment by az-iot-builder-01** [comment]
@DavidJurajdaNXP, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
