### ISSUE TITLE
out of memory error from libcurl 7.54 on macOS 10.13.4

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#593]
- **OS and version used:** mac OS 10.13.4

- **SDK version used:** 2018-07-11 (1.2.8)

# Description of the issue:
I feel this is specific to my mac OS 10.13.4. Default libcurl version is 7.54. I get below _out of memory error_ from libcurl on sample programs.  More importantly, I then built, libcurl 7.58. With that(DYLD_LIBRARY_PATH) I am no more getting the below error. But macOS 10.13.4 ships with libcurl 7.54 and all other programs work well except azure-iot-sdk-c

# Code sample exhibiting the issue:
I tried iothub_convenience_sample and iothub_client_sample_upload_to_blob. But I feel this exists for all HTTP samples

# Console log of the issue:

> xxxxxx:build xxxxxxx$ ./iothub_client/samples/iothub_convenience_sample/iothub_convenience_sample 
> This sample will send 5 messages and wait for any C2D messages.
> Press the enter key to end the sample
> 
> Creating IoTHub handle
> Sending message 1 to IoTHub
> Error: Time:Mon Aug 13 22:48:15 2018 File:/Users/779591/src/git/FLSmidth/connection_manager/3rdparty/iot-sdk-c/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:582 curl_easy_perform() failed: Out of memory
> 
> Error: Time:Mon Aug 13 22:48:15 2018 File:/Users/779591/src/git/FLSmidth/connection_manager/3rdparty/iot-sdk-c/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:584 (result = HTTPAPI_OPEN_REQUEST_FAILED)
> Error: Time:Mon Aug 13 22:48:15 2018 File:/Users/779591/src/git/FLSmidth/connection_manager/3rdparty/iot-sdk-c/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
> Error: Time:Mon Aug 13 22:48:15 2018 File:/Users/779591/src/git/FLSmidth/connection_manager/3rdparty/iot-sdk-c/azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:DoMessages Line:2078 unable to HTTPAPIEX_SAS_ExecuteRequest
> Sending message 2 to IoTHub
> Sending message 3 to IoTHub
> Sending message 4 to IoTHub
> Sending message 5 to IoTHub
> 
> Press any key to continue
> Error: Time:Mon Aug 13 22:48:15 2018 File:/Users/779591/src/git/FLSmidth/connection_manager/3rdparty/iot-sdk-c/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:582 curl_easy_perform() failed: Out of memory
> 
> Error: Time:Mon Aug 13 22:48:15 2018 File:/Users/779591/src/git/FLSmidth/connection_manager/3rdparty/iot-sdk-c/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:584 (result = HTTPAPI_OPEN_REQUEST_FAILED)
> Error: Time:Mon Aug 13 22:48:15 2018 File:/Users/779591/src/git/FLSmidth/connection_manager/3rdparty/iot-sdk-c/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
> Error: Time:Mon Aug 13 22:48:15 2018 File:/Users/779591/src/git/FLSmidth/connection_manager/3rdparty/iot-sdk-c/azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1685 unable to HTTPAPIEX_SAS_ExecuteRequest
> Error: Time:Mon Aug 13 22:48:15 2018 File:/Users/779591/src/git/FLSmidth/connection_manager/3rdparty/iot-sdk-c/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:582 curl_easy_perform() failed: Out of memory
> 
>

**Comment by ewertons** [comment]
@kiranpradeep ,
that is a limitation set by this specific operating system.
Your workaround is correctly applied, and you seem unblocked.
What is your specific question?

**Comment by ewertons** [comment]
More details here: this issue in older versions of curl seems related to [using SSLv3](https://stackoverflow.com/questions/28048885/initializing-ssl-and-libcurl-and-getting-out-of-memory/37295100#37295100).
Upgrading to the latest versions of curl is the recommended solution.
We do not recommend falling back to SSLv2.

**Comment by kiranpradeep** [comment]
@ewertons feels like a cop out answer. Issue was raised since all other application on same machine worked well with default libcurl. I saw only azure-iot-sdk-c failing. Closing.

**Comment by az-iot-builder-01** [comment]
@kiranpradeep, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by kiranpradeep** [comment]
@ewertons On a second thought, that reply implies that all developers using macOS 10.13 cannot run this SDK unless they update libcurl. Is that a correct understanding? If yes, this should be added to a known issue list somewhere.

OTOH updating libcurl not macOS is not very straightforward as it needs keychain access. That is secondary though.

**Comment by ewertons** [comment]
The information is contained in the guide to setup a development box for Azure IoT C SDK:
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#macos

Please take a look at the documentation.

"Patch CURL to the latest version available.
The minimum version of curl required is 7.56, as recent previous versions presented critical failures. To upgrade see "Upgrade CURL on Mac OS" steps below."


We even provided steps on how to upgrade curl, just in case.
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#upgrade-curl-on-mac-os

**Comment by kiranpradeep** [comment]
@ewertons Apologies. My bad.
