### ISSUE TITLE
openssl 1.1.1 build fails on macOS 10.13

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#595]
- **OS and version used:** macOS 10.13.4

- **SDK version used:** 2018-07-11 (1.2.8)

# Description of the issue:
Build succeeds with openssl 1.0.2. Fails on openssl 1.1.0h

# Console log of the issue:
```
$: cmake -Duse_openssl:BOOL=ON  ..
$: make
[ 21%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/x509_openssl.c.o
/Users/779591/src/git/FLSmidth/connection_manager/3rdparty/iot-sdk-c/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c:194:32: error: incomplete definition of
      type 'struct evp_pkey_st'
                int evp_type = EVP_PKEY_id(evp_key);
                               ^           ~~~~~~~
/Users/779591/src/git/FLSmidth/connection_manager/3rdparty/iot-sdk-c/azure-iot-sdk-c/c-utility/adapters/x509_openssl.c:16:45: note: expanded from macro
      'EVP_PKEY_id'
        #define EVP_PKEY_id(evp_key) evp_key->type
                                     ~~~~~~~^
/usr/local/Cellar/openssl@1.1/1.1.0h/include/openssl/ossl_typ.h:93:16: note: forward declaration of 'struct evp_pkey_st'
typedef struct evp_pkey_st EVP_PKEY;
               ^
1 error generated.
```

**Comment by ewertons** [comment]
Hi @kiranpradeep ,
thanks for reporting this issue. We will investigate and report briefly.

**Comment by jebrando** [comment]
@kiranpradeep Question, when you run Openssl version on your mac what value do you get?  How did you install OpenSSL, did you use homebrew or another installation method?

**Comment by kiranpradeep** [comment]
@jebrando 

> $ openssl version
> LibreSSL 2.2.7

For the azure-iot-sdk-c build, I installed openssl with homebrew and set OPENSSL_ROOT_DIR to openssl path installed by homebrew. Let me know if you need further info.

**Comment by jebrando** [comment]
@kiranpradeep I'm using the same openssl version that you are using and I am building successfully with the following cmake:

`
$ cmake ../.. -DOPENSSL_ROOT_DIR:PATH=/usr/local/opt/openssl -Duse_openssl=ON`<br>`
-- The C compiler identification is AppleClang 9.1.0.9020039`<br>`
...`<br>`
$ cmake --build . -- --jobs=4`<br>`
...`<br>`
[100%] Built target devicetwin_simplesample
`
Can you enter in your whole cmake command and the output for that.

Thanks,
Jelani

**Comment by kiranpradeep** [comment]
@jebrando I don't have access to macOS workstation for a while. Will update as soon as I get that.

**Comment by ewertons** [comment]
Hi @kiranpradeep ,
we will close this issue for now, but please feel free to reopen it if you would like to follow up.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@ewertons, @jebrando, @kiranpradeep, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by jbobotek** [comment]
Note that a resolution to this issue has now been found, via [Issue # 1247](https://github.com/Azure/azure-iot-sdk-c/issues/1247#issuecomment-546273588). When building the SDK using openssl for Mac OSX or iOS, please use the [OpenSSL-Universal Pod](https://github.com/krzyzanowskim/OpenSSL#cocoapods) linked in that issue. Then make sure to use the pod location as the openssl library, header, and static library location as specified in the linked issue and comment.
