### ISSUE TITLE
Build fails with missing library files

### ISSUE THREAD

**Issue by trillykins** [Azure/azure-iot-sdk-c#598]
I have a project that uses the Azure IoT SDK. Up until now I've just used the sample library to build it, but now I would like to clean up the project to only the necessary files. Seems like I am missing some target library.

CMakeLists.txt

```
cmake_minimum_required(VERSION 2.8.11)

set (CMAKE_C_FLAGS "--std=c99 ${CMAKE_C_FLAGS}")

set(AZUREIOT_INC_FOLDER ".." "/usr/include/azureiot" "/usr/include/azureiot/inc")

include_directories(.)
include_directories(./certs)
include_directories(${AZUREIOT_INC_FOLDER})

set(axis_comm_c_files
        ./myfiles.c
	./certs/certs.c
)

set(axis_comm_h_files
        ./myfiles.h
)

add_executable(axis_comm ${axis_comm_c_files} ${axis_comm_h_files})

target_link_libraries(axis_comm 
    iothub_client
    iothub_client_amqp_transport
    iothub_client_amqp_ws_transport
    iothub_client_http_transport
    aziotsharedutil
    uamqp
    pthread
    curl
    ssl
    crypto
    m
    uuid
    parson
)

# Get the current working branch
execute_process(
  COMMAND git rev-parse --abbrev-ref HEAD
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE GIT_BRANCH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

# Get the build date
execute_process(
  COMMAND date --iso=seconds
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE BUILD_DATE
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

# Get the latest abbreviated commit hash of the working branch
execute_process(
  COMMAND git --no-pager describe --tags --always
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE GIT_COMMIT_HASH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

add_definitions("-DGIT_BRANCH=${GIT_BRANCH}")
add_definitions("-DBUILD_DATE=${BUILD_DATE}")
add_definitions("-DGIT_COMMIT_HASH=${GIT_COMMIT_HASH}")

configure_file(
    ${CMAKE_CURRENT_SOURCE_DIR}/version_git.h.in
    ${CMAKE_CURRENT_SOURCE_DIR}/version_git.h
)
```

And the error message I get when compiling:
```
Linking C executable axis_comm
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libiothub_client.a(iothub_client_core_ll.c.o): In function `IoTHubClientCore_LL_CreateFromEnvironment':
(.text+0x3bcc): undefined reference to `iothub_security_init'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libiothub_client_amqp_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_CreateFromDeviceAuth':
(.text+0x38b): undefined reference to `iothub_device_auth_create'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libiothub_client_amqp_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_CreateFromDeviceAuth':
(.text+0x3ce): undefined reference to `iothub_device_auth_get_type'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libiothub_client_amqp_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_CreateFromDeviceAuth':
(.text+0x509): undefined reference to `iothub_device_auth_destroy'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libiothub_client_amqp_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_CreateFromDeviceAuth':
(.text+0x559): undefined reference to `iothub_device_auth_destroy'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libiothub_client_amqp_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Destroy':
(.text+0x58e): undefined reference to `iothub_device_auth_destroy'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libiothub_client_amqp_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Set_xio_Certificate':
(.text+0x707): undefined reference to `iothub_device_auth_generate_credentials'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libiothub_client_amqp_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Get_SasToken':
(.text+0xa8a): undefined reference to `iothub_device_auth_generate_credentials'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libiothub_client_amqp_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Get_TrustBundle':
(.text+0xe5a): undefined reference to `iothub_device_auth_get_trust_bundle'
collect2: error: ld returned 1 exit status
make[2]: *** [axis_comm] Error 1
make[1]: *** [CMakeFiles/axis_comm.dir/all] Error 2
make: *** [all] Error 2

```

I tried looking for which target libraries are used in the sample folders, but cannot find find the ones I am missing.

**Comment by jspaith** [comment]
Hmm.. on a quick look that's surprising.  Those functions *should* be in `iothub_client`.  We'll investigate and let you know.

**Comment by jebrando** [comment]
@trillykins The reason you're getting this failure is due to an inclusion of a library in azure iothub client.  You will need to add the following libraries to the build: prov_auth_client, hsm_security_client, and uhttp.

Sorry for the inconvenience.

**Comment by trillykins** [comment]
@jebrando Hmm, now I'm getting different errors, this time seemingly connected to prov_auth_client and hsm_security.

```
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libprov_auth_client.a(iothub_auth_client.c.o): In function `iothub_device_auth_create':
(.text+0x8e): undefined reference to `hsm_client_http_edge_interface'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libprov_auth_client.a(iothub_security_factory.c.o): In function `iothub_security_init':
(.text+0xe8): undefined reference to `initialize_hsm_system'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libprov_auth_client.a(iothub_security_factory.c.o): In function `iothub_security_deinit':
(.text+0xf3): undefined reference to `deinitialize_hsm_system'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libprov_auth_client.a(prov_security_factory.c.o): In function `prov_dev_security_init':
(.text+0xe8): undefined reference to `initialize_hsm_system'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libprov_auth_client.a(prov_security_factory.c.o): In function `prov_dev_security_deinit':
(.text+0xf3): undefined reference to `deinitialize_hsm_system'
collect2: error: ld returned 1 exit status
make[2]: *** [axis_comm] Error 1
make[1]: *** [CMakeFiles/axis_comm.dir/all] Error 2
make: *** [all] Error 2
```

```
target_link_libraries(axis_comm 
    iothub_client
    iothub_client_amqp_transport
	iothub_client_amqp_ws_transport
	iothub_client_http_transport
	hsm_security_client
	prov_auth_client
    aziotsharedutil
	serializer
	parson
    uamqp
	uhttp
    pthread
    curl
    ssl
    crypto
    m
	uuid
)
```

Could there be something else I'm missing somewhere in the CMakeLists file? Do I need to have some includes or dependency files inside my project?

**Comment by jebrando** [comment]
@trillykins you need to add hsm_security_client library.  I have updated the [telemetry samples](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/linux/CMakeLists.txt) to show this.

If you have any more issues please reopen, or you can open a new issue.

**Comment by az-iot-builder-01** [comment]
@trillykins, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by trillykins** [comment]
@jebrando but I already have hsm_security_client in my target_link_libraries.

**Comment by fernandoBRS** [comment]
@jebrando I'm having the same issue even when I include hsm_security_client on target_link_libraries: **undefined reference to `hsm_client_http_edge_interface'**

**Comment by fernandoBRS** [comment]
@trillykins try to add **prov_auth_client** before **hsm_security_client**. I'm not sure why but it worked for me. For example:

```
target_link_libraries(
    prov_auth_client
    hsm_security_client
)
```

**Comment by trillykins** [comment]
@fernandoBRS Oh, yeah that worked for me as well... thanks!

**Comment by jorunv** [comment]
Hi,

I'm currently trying to do the same thing as described above, with a similar error report:

`/usr/bin/ld: CMakeFiles/cloud.dir/home/jorun/Documents/Linux/sb-linux/nano-esp32/components/cloud/cloud.c.o: in function `init_connection':
/home/jorun/Documents/Linux/sb-linux/nano-esp32/components/cloud/cloud.c:652: undefined reference to `MQTT_WebSocket_Protocol'
/usr/bin/ld: /home/jorun/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): in function `IoTHubClient_Auth_CreateFromDeviceAuth':
/home/jorun/Documents/Linux/azure-iot-sdk-c/iothub_client/src/iothub_client_authorization.c:181: undefined reference to `iothub_device_auth_create'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/iothub_client/src/iothub_client_authorization.c:192: undefined reference to `iothub_device_auth_get_type'
/usr/bin/ld: /home/jorun/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): in function `IoTHubClient_Auth_Destroy':
/home/jorun/Documents/Linux/azure-iot-sdk-c/iothub_client/src/iothub_client_authorization.c:217: undefined reference to `iothub_device_auth_destroy'
/usr/bin/ld: /home/jorun/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): in function `IoTHubClient_Auth_Set_xio_Certificate':
/home/jorun/Documents/Linux/azure-iot-sdk-c/iothub_client/src/iothub_client_authorization.c:275: undefined reference to `iothub_device_auth_generate_credentials'
/usr/bin/ld: /home/jorun/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): in function `IoTHubClient_Auth_Get_x509_info':
/home/jorun/Documents/Linux/azure-iot-sdk-c/iothub_client/src/iothub_client_authorization.c:323: undefined reference to `iothub_device_auth_generate_credentials'
/usr/bin/ld: /home/jorun/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): in function `IoTHubClient_Auth_Get_SasToken':
/home/jorun/Documents/Linux/azure-iot-sdk-c/iothub_client/src/iothub_client_authorization.c:402: undefined reference to `iothub_device_auth_generate_credentials'
`

However when I add the 'prov_auth_client' and 'hsm_security_client' as target link libraries, I encounter a lot of issues in linking the hsm security client.

`/usr/bin/ld: /home/jorun/local/lib/libhsm_security_client.a(hsm_client_tpm.c.o): in function `GetEkTemplate':
/home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:79: undefined reference to `ToTpmaObject'
/usr/bin/ld: /home/jorun/local/lib/libhsm_security_client.a(hsm_client_tpm.c.o): in function `GetSrkTemplate':
/home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:96: undefined reference to `ToTpmaObject'
/usr/bin/ld: /home/jorun/local/lib/libhsm_security_client.a(hsm_client_tpm.c.o): in function `dps_umarshal_array':
/home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:140: undefined reference to `UINT32_Unmarshal'
/usr/bin/ld: /home/jorun/local/lib/libhsm_security_client.a(hsm_client_tpm.c.o): in function `unmarshal_array':
/home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:160: undefined reference to `UINT32_Unmarshal'
/usr/bin/ld: /home/jorun/local/lib/libhsm_security_client.a(hsm_client_tpm.c.o): in function `marshal_array_values':
/home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:192: undefined reference to `UINT32_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:199: undefined reference to `UINT32_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:206: undefined reference to `UINT32_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:213: undefined reference to `TPM2B_PUBLIC_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:220: undefined reference to `UINT16_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:227: undefined reference to `TPM2B_PRIVATE_Unmarshal'
/usr/bin/ld: /home/jorun/local/lib/libhsm_security_client.a(hsm_client_tpm.c.o): in function `create_tpm_session':
/home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:244: undefined reference to `TSS_StartAuthSession'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:249: undefined reference to `TSS_PolicySecret'
/usr/bin/ld: /home/jorun/local/lib/libhsm_security_client.a(hsm_client_tpm.c.o): in function `insert_key_in_tpm':
/home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:286: undefined reference to `TPM2B_ID_OBJECT_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:287: undefined reference to `TPM2B_ENCRYPTED_SECRET_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:288: undefined reference to `TPM2B_PRIVATE_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:289: undefined reference to `TPM2B_ENCRYPTED_SECRET_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:290: undefined reference to `TPM2B_PUBLIC_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:295: undefined reference to `UINT16_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:297: undefined reference to `TPM2_ActivateCredential'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:303: undefined reference to `TPM2_Import'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:323: undefined reference to `ToTpmaObject'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:331: undefined reference to `TSS_Create'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:336: undefined reference to `TPM2_Load'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:344: undefined reference to `TPM2_EvictControl'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:346: undefined reference to `TPM2_EvictControl'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:351: undefined reference to `TPM2_FlushContext'
/usr/bin/ld: /home/jorun/local/lib/libhsm_security_client.a(hsm_client_tpm.c.o): in function `decrypt_data':
/home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:377: undefined reference to `TSS_GetTpmProperty'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:396: undefined reference to `TPM2B_ID_OBJECT_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:397: undefined reference to `TPM2B_ENCRYPTED_SECRET_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:398: undefined reference to `TPM2B_PRIVATE_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:399: undefined reference to `TPM2B_ENCRYPTED_SECRET_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:400: undefined reference to `TPM2B_PUBLIC_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:405: undefined reference to `UINT16_Unmarshal'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:423: undefined reference to `TPM2_ActivateCredential'
/usr/bin/ld: /home/jorun/local/lib/libhsm_security_client.a(hsm_client_tpm.c.o): in function `initialize_tpm_device':
/home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:445: undefined reference to `TSS_CreatePwAuthSession'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:450: undefined reference to `Initialize_TPM_Codec'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:455: undefined reference to `TSS_CreatePersistentKey'
/usr/bin/ld: /home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:460: undefined reference to `TSS_CreatePersistentKey'
/usr/bin/ld: /home/jorun/local/lib/libhsm_security_client.a(hsm_client_tpm.c.o): in function `hsm_client_tpm_destroy':
/home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:499: undefined reference to `Deinit_TPM_Codec'
/usr/bin/ld: /home/jorun/local/lib/libhsm_security_client.a(hsm_client_tpm.c.o): in function `hsm_client_tpm_get_endorsement_key':
/home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:561: undefined reference to `TPM2B_PUBLIC_Marshal'
/usr/bin/ld: /home/jorun/local/lib/libhsm_security_client.a(hsm_client_tpm.c.o): in function `hsm_client_tpm_get_storage_key':
/home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:603: undefined reference to `TPM2B_PUBLIC_Marshal'
/usr/bin/ld: /home/jorun/local/lib/libhsm_security_client.a(hsm_client_tpm.c.o): in function `hsm_client_tpm_sign_data':
/home/jorun/Documents/Linux/azure-iot-sdk-c/provisioning_client/adapters/hsm_client_tpm.c:639: undefined reference to `SignData'
`

Did anyone else encounter this or has an idea of a workaround or fix for this?
