### ISSUE TITLE
Blocking recv() with TPM simulator on Linux

### ISSUE THREAD

**Issue by truschival** [Azure/azure-iot-sdk-c#600]
- **OS and version used:** Debian 9.5
- **SDK version used:**  2018-06-15 + TPM Simulator IBMTPM 1119

# Description of the issue:
Running DPS-Client and IoT-Hub client in Host x64 Linux environment with a TPM Simulator on localhost blocks. On a embedded linux with TPMv2 chip and kernel resource management the same code does not block.  
See Line 51  in function `azure_iot_hub_connect(void* ctx) `  of the sample code

**The example is configured to use a proxy!** if you don't have a proxy comment out the line `Prov_Device_SetOption(prov_device_handle, OPTION_HTTP_PROXY, &azure_proxy_settings);` in `dps_init_client()`.

Call stack on host when blocking:
```
Thread #2 [libcloud-test] 17254 [core: 1] (Suspended : Container)	
	__libc_recv() at recv.c:28 0x7ffff6b7c4ff	
	read_socket_bytes() at tpm_socket_comm.c:136 0x555555617754	
	tpm_socket_read() at tpm_socket_comm.c:251 0x555555617b38	
	read_sync_bytes() at tpm_comm_emulator.c:58 0x555555616731	
	read_sync_cmd() at tpm_comm_emulator.c:65 0x555555616761	
	execute_simulator_setup() at tpm_comm_emulator.c:185 0x555555616c3b	
	tpm_comm_create() at tpm_comm_emulator.c:250 0x555555616fca	
	Initialize_TPM_Codec() at tpm_codec.c:256 0x555555611fec	
	initialize_tpm_device() at hsm_client_tpm.c:449 0x5555555fd153	
	hsm_client_tpm_create() at hsm_client_tpm.c:487 0x5555555fd34d	
```

# Code sample exhibiting the issue:
In this minimal sample (stripped error handling and mutex locking form the original) the IoTHub client connection should be established in the `PROV_DEVICE_CLIENT_REGISTER_DEVICE_CALLBACK` 

To compile the example make sure to add the libraries  `provisioning_client/deps/libmsr_riot.a` and
`provisioning_client/deps/utpm/libutpm.a` from the Azure-IoT-SDK build. 

**This code is not production code! YOU have to implement error checking etc.!**
```
#include <assert.h>
#include <stdbool.h>
#include <stdio.h>
#include <unistd.h>

#include <azure_c_shared_utility/platform.h>
#include <azure_c_shared_utility/shared_util_options.h>
#include <azure_prov_client/prov_device_client.h>    // azure sdk
#include <azure_prov_client/prov_security_factory.h> // macros for DPS
#include <azure_prov_client/prov_transport_http_client.h>
#include <azureiot/iothub_client.h>
#include <azureiot/iothub_client_options.h>
#include <azureiot/iothubtransportamqp_websockets.h>

DEFINE_ENUM_STRINGS(PROV_DEVICE_RESULT, PROV_DEVICE_RESULT_VALUE);
DEFINE_ENUM_STRINGS(PROV_DEVICE_REG_STATUS, PROV_DEVICE_REG_STATUS_VALUES);

/* Global vars - only for demo!!*/
bool connected = false;

typedef struct azure_data {
    char dps_iothub[256];
    char dps_device_id[256];
    PROV_DEVICE_HANDLE prov_device_handle;
    PROV_DEVICE_RESULT prov_device_result;
    PROV_DEVICE_REG_STATUS dps_reg_status;
    IOTHUB_CLIENT_HANDLE iothubclient;
    bool dps_trace;
    bool iothub_trace;
    size_t trackingid;
} azure_data_t;

const char* dps_uri = "global.azure-devices-provisioning.net";
const char* dps_idscope = "<YOUR_SCOPE_HERE>";

HTTP_PROXY_OPTIONS azure_proxy_settings = {
    .host_address = "10.X.X.X", .port = 0000,
};


azure_data_t data;
azure_data_t* data_ptr = &data;

/*****************************************************************************/
static int azure_iot_hub_connect(void* ctx) {
    printf(">%s\n", __func__);

    printf(" got IoT-Hub: %s, setting up client", data_ptr->dps_iothub);

// !!! BLOCKS HERE !!!
    data_ptr->iothubclient =
        IoTHubClient_CreateFromDeviceAuth(data_ptr->dps_iothub,
            data_ptr->dps_device_id, AMQP_Protocol_over_WebSocketsTls);
    if (data_ptr->iothubclient == NULL) {
        printf(" Creating IoT-Hub client failed\n");
        return -1;
    }
    printf(" client created: setting options\n");

    IoTHubClient_SetOption(
        data_ptr->iothubclient, OPTION_LOG_TRACE, &data_ptr->iothub_trace);

    IoTHubClient_SetOption(
        data_ptr->iothubclient, OPTION_HTTP_PROXY, &azure_proxy_settings);

    connected = true;
    return 0;
    printf("<%s\n", __func__);
}

/*****************************************************************************/
static void register_device_callback(PROV_DEVICE_RESULT register_result,
    const char* iothub_uri, const char* device_id, void* user_context) {
    printf(">%s\n", __FUNCTION__);

    // if (register_result == PROV_DEVICE_RESULT_OK) {
    printf(" received config from DPS - IoT Hub: %s, deviceId: %s\n", iothub_uri,
        device_id);

    strncpy(data_ptr->dps_iothub, iothub_uri, sizeof(data_ptr->dps_iothub));
    strncpy(
        data_ptr->dps_device_id, device_id, sizeof(data_ptr->dps_device_id));
    data_ptr->dps_reg_status = PROV_DEVICE_REG_STATUS_ASSIGNED;
    /* setup connection to IoT Hub */
    azure_iot_hub_connect(NULL);
    //}

    printf("<%s\n", __FUNCTION__);
}
/*****************************************************************************/

static void registation_status_callback(
    PROV_DEVICE_REG_STATUS reg_status, void* user_context) {
    printf(">%s", __FUNCTION__);

    printf(" Provisioning Status: %s\n",
        ENUM_TO_STRING(PROV_DEVICE_REG_STATUS, reg_status));
    data_ptr->dps_reg_status = reg_status;

    printf("<%s", __FUNCTION__);
}
/*****************************************************************************/

int dps_init_client() {
    printf(">%s\n", __FUNCTION__);
    int result = -1;
    SECURE_DEVICE_TYPE hsm_type = SECURE_DEVICE_TYPE_TPM;

    data_ptr->prov_device_handle = NULL;
    data_ptr->prov_device_result = PROV_DEVICE_RESULT_ERROR;
    data_ptr->dps_reg_status = PROV_DEVICE_REG_STATUS_ASSIGNING;


    if (platform_init() != 0) {
        printf("platform_init failed\r\n");
        return -1;
    } else if (prov_dev_security_init(hsm_type) != 0) {
        printf("prov_dev_security_init failed\r\n");
        return -1;
    } else {
        PROV_DEVICE_TRANSPORT_PROVIDER_FUNCTION prov_transport =
            Prov_Device_HTTP_Protocol;

        PROV_DEVICE_HANDLE prov_device_handle =
            Prov_Device_Create(dps_uri, dps_idscope, prov_transport);

        if (prov_device_handle == NULL) {
            printf("failed calling Prov_Device_Create\n");
            return -1;
        } else {
            Prov_Device_SetOption(
                prov_device_handle, "logtrace", &data_ptr->dps_trace);
            Prov_Device_SetOption(
                prov_device_handle, OPTION_HTTP_PROXY, &azure_proxy_settings);

            PROV_DEVICE_RESULT prov_device_result = Prov_Device_Register_Device(
                prov_device_handle, register_device_callback, NULL,
                registation_status_callback, NULL);
            // Copy local handles to user context
            data_ptr->prov_device_result = prov_device_result;
            data_ptr->prov_device_handle = prov_device_handle;
        }
        result = 0;
    }
    printf("<%s\n", __FUNCTION__);
    return result;
}

/*****************************************************************************/
int main(int argc, const char** argv) {
    data_ptr->dps_trace = true;
    dps_init_client();
    while (!connected) {
        printf(".");
        sleep(1);
    }

    return 0;
}
```

**Comment by jebrando** [comment]
@truschival Thanks for the issue, I will investigate and let you know what I find out.  A question I have is what TLS stack are you using?  I don't have an embedded system on hand so I'll just have to develop against ubuntu and the stacks may be a little different.

**Comment by jebrando** [comment]
@truschival I figured this out, the issue is that the DPS module and the IoTHub client modules are separate entities and they both have contention on the TPM.  So the IoTHub Module is waiting to gain access to the TPM.  There is a few ways to fix this in my code, but the quickest way to for you to fix this is to destroy the dps module.  I've included the code that works.

I also updated the iothub code to use the newer iothub device client.  It's just a newer way going forward to access the IoTHub.

`#include <assert.h>
#include <stdbool.h>
#include <stdio.h>
#include <unistd.h>

#include "azure_c_shared_utility/shared_util_options.h"
#include "azure_prov_client/prov_device_client.h"    // azure sdk
#include "azure_prov_client/prov_security_factory.h" // macros for DPS
#include "azure_prov_client/prov_transport_http_client.h"
#include "iothub.h"
#include "iothub_device_client.h"
#include "iothub_client_options.h"
#include "iothubtransportamqp_websockets.h"

DEFINE_ENUM_STRINGS(PROV_DEVICE_RESULT, PROV_DEVICE_RESULT_VALUE);
DEFINE_ENUM_STRINGS(PROV_DEVICE_REG_STATUS, PROV_DEVICE_REG_STATUS_VALUES);

/* Global vars - only for demo!!*/
bool dps_connected = false;
bool iothub_connected = false;
bool iothub_msg_recv = false;

typedef struct azure_data
{
    char dps_iothub[256];
    char dps_device_id[256];
    PROV_DEVICE_HANDLE prov_device_handle;
    PROV_DEVICE_RESULT prov_device_result;
    PROV_DEVICE_REG_STATUS dps_reg_status;
    IOTHUB_DEVICE_CLIENT_HANDLE iothubclient;
    bool dps_trace;
    bool iothub_trace;
    size_t trackingid;
} azure_data_t;

const char* dps_uri = "global.azure-devices-provisioning.net";
const char* dps_idscope = "0ne00000032";

HTTP_PROXY_OPTIONS azure_proxy_settings = 
{
    .host_address = "10.X.X.X", .port = 0000,
};

azure_data_t data;
azure_data_t* data_ptr = &data;

/*****************************************************************************/
static int azure_iot_hub_connect(void* ctx)
{
    (void)ctx;
    printf(">%s\n", __func__);

    printf(" got IoT-Hub: %s, setting up client", data_ptr->dps_iothub);

    // !!! NO LONGER BLOCKS HERE !!!
    data_ptr->iothubclient =
        IoTHubDeviceClient_CreateFromDeviceAuth(data_ptr->dps_iothub,
            data_ptr->dps_device_id, AMQP_Protocol_over_WebSocketsTls);
    if (data_ptr->iothubclient == NULL) {
        printf(" Creating IoT-Hub client failed\n");
        return -1;
    }
    printf(" client created: setting options\n");

    IoTHubDeviceClient_SetOption(
        data_ptr->iothubclient, OPTION_LOG_TRACE, &data_ptr->iothub_trace);

    //IoTHubDeviceClient_SetOption(data_ptr->iothubclient, OPTION_HTTP_PROXY, &azure_proxy_settings);

    iothub_connected = true;
    return 0;
    //printf("<%s\n", __func__);
}

static void send_confirm_callback(IOTHUB_CLIENT_CONFIRMATION_RESULT result, void* userContextCallback)
{
    (void)userContextCallback;
    (void)printf("Confirmation callback received with result %s\r\n", ENUM_TO_STRING(IOTHUB_CLIENT_CONFIRMATION_RESULT, result));
    iothub_msg_recv = true;
}

static int send_iothub_message(void)
{
    int result;
    const char* iothub_msg = "Test iothub message";

    IOTHUB_MESSAGE_HANDLE msg_handle = IoTHubMessage_CreateFromString(iothub_msg);
    if (msg_handle == NULL)
    {
        (void)printf("ERROR: iotHubMessageHandle is NULL!\r\n");
        result = -1;
    }
    else
    {
        if (IoTHubDeviceClient_SendEventAsync(data_ptr->iothubclient, msg_handle, send_confirm_callback, NULL) != IOTHUB_CLIENT_OK)
        {
            (void)printf("ERROR: IoTHubDeviceClient_SendEventAsync..........FAILED!\r\n");
            result = -1;
        }
        else
        {
            (void)printf("IoTHubDeviceClient_SendEventAsync accepted message for transmission to IoT Hub.\r\n");
            result = 0;
        }
        IoTHubMessage_Destroy(msg_handle);
    }
    return result;
}

/*****************************************************************************/
static void register_device_callback(PROV_DEVICE_RESULT register_result,
    const char* iothub_uri, const char* device_id, void* user_context) 
{
    (void)user_context;
    (void)register_result;
    printf(">%s\n", __FUNCTION__);

    // if (register_result == PROV_DEVICE_RESULT_OK) {
    printf(" received config from DPS - IoT Hub: %s, deviceId: %s\n", iothub_uri,
        device_id);

    strncpy(data_ptr->dps_iothub, iothub_uri, sizeof(data_ptr->dps_iothub));
    strncpy(
        data_ptr->dps_device_id, device_id, sizeof(data_ptr->dps_device_id));
    data_ptr->dps_reg_status = PROV_DEVICE_REG_STATUS_ASSIGNED;

    dps_connected = true;
    printf("<%s\n", __FUNCTION__);
}
/*****************************************************************************/

static void registation_status_callback(
PROV_DEVICE_REG_STATUS reg_status, void* user_context) 
{
    (void)user_context;
    printf(">%s", __FUNCTION__);

    printf(" Provisioning Status: %s\n",
        ENUM_TO_STRING(PROV_DEVICE_REG_STATUS, reg_status));
    data_ptr->dps_reg_status = reg_status;

    printf("<%s", __FUNCTION__);
}
/*****************************************************************************/

int dps_init_client()
{
    printf(">%s\n", __FUNCTION__);
    int result = -1;
    SECURE_DEVICE_TYPE hsm_type = SECURE_DEVICE_TYPE_TPM;

    data_ptr->prov_device_handle = NULL;
    data_ptr->prov_device_result = PROV_DEVICE_RESULT_ERROR;
    data_ptr->dps_reg_status = PROV_DEVICE_REG_STATUS_ASSIGNING;


    if (IoTHub_Init() != 0) {
        printf("platform_init failed\r\n");
        return -1;
    }
    else if (prov_dev_security_init(hsm_type) != 0) {
        printf("prov_dev_security_init failed\r\n");
        return -1;
    }
    else {
        PROV_DEVICE_TRANSPORT_PROVIDER_FUNCTION prov_transport =
            Prov_Device_HTTP_Protocol;

        PROV_DEVICE_HANDLE prov_device_handle = 
            Prov_Device_Create(dps_uri, dps_idscope, prov_transport);

        if (prov_device_handle == NULL) {
            printf("failed calling Prov_Device_Create\n");
            return -1;
        }
        else {
            Prov_Device_SetOption(
                prov_device_handle, "logtrace", &data_ptr->dps_trace);
            //Prov_Device_SetOption(prov_device_handle, OPTION_HTTP_PROXY, &azure_proxy_settings);

            PROV_DEVICE_RESULT prov_device_result = Prov_Device_Register_Device(
                prov_device_handle, register_device_callback, NULL,
                registation_status_callback, NULL);
            // Copy local handles to user context
            data_ptr->prov_device_result = prov_device_result;
            data_ptr->prov_device_handle = prov_device_handle;
        }
        result = 0;
    }
    printf("<%s\n", __FUNCTION__);
    return result;
}

/*****************************************************************************/
int main(int argc, const char** argv)
{
    (void)argc;
    (void)argv;
    data_ptr->dps_trace = false;
    dps_init_client();

    while (!dps_connected) {
        printf(".");
        sleep(2);
    }
    // You must destroy the provisioning device before you
    // can use the iothub device for the tpm
    Prov_Device_Destroy(data_ptr->prov_device_handle);
    data_ptr->prov_device_handle = NULL;

    /* setup connection to IoT Hub */
    azure_iot_hub_connect(NULL);
    
    send_iothub_message();

    // Send one iothub message just to make sure we can
    while (!iothub_msg_recv) {
        printf(".");
        sleep(2);
    }

    // clear data
    IoTHubDeviceClient_Destroy(data_ptr->iothubclient);

    return 0;
}
`
Let me know if you have any more issues.
Jelani

**Comment by jebrando** [comment]
If you have any more issue please either re-open this issue or open another.

**Comment by truschival** [comment]
Hi thanks for the quick response. Your solution is the most obvious one.

I was trying to get a connection with one no-blocking call from a client program without waiting for DPS-client to succeed, this is why I put the iothub client connection in the callback.

The main question is why the DPS client keeps a connection to the TPM and therefore the IOTHubclient can't get it? After my holidays I will look into the issue. 

As far as I understand this doesn't happen with the real TPM since it is not connected via socket but uses the kernel-space resource manager.
