### ISSUE TITLE
ubantu 14.04 unknown option logtrace

### ISSUE THREAD

**Issue by dongranqi** [Azure/azure-iot-sdk-c#601]
I compile the sdk on ubantu 14.04,and run iothub_ll_telemetry_sampe ,shows errors. but the messages can be sent successfully.

Please give me a favor!
Log is below:
Creating IoTHub Device handle
Error: Time:Mon Aug 20 17:35:12 2018 File:/home/qidongran/code/Azure/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_CloneOption Line:968 unknown option logtrace
Error: Time:Mon Aug 20 17:35:12 2018 File:/home/qidongran/code/Azure/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_SetOption Line:609 error code = HTTPAPIEX_INVALID_ARG
Error: Time:Mon Aug 20 17:35:12 2018 File:/home/qidongran/code/Azure/azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:IoTHubTransportHttp_SetOption Line:2431 HTTPAPIEX_SetOption failed
Error: Time:Mon Aug 20 17:35:12 2018 File:/home/qidongran/code/Azure/azure-iot-sdk-c/iothub_client/src/iothub_client_core_ll.c Func:IoTHubClientCore_LL_SetOption Line:2220 unable to IoTHubTransport_SetOption

**Comment by ewertons** [comment]
Hi @dongranqi , could you please provide the information requested in the issue template?

Which version of the SDK are you using?

**Comment by ewertons** [comment]
This is a known, minor issue and should not affect your functionality at all.

**Comment by dongranqi** [comment]
The sdk version is 1.2.8



dongran.qi@simcom.com
 
From: ewertons
Date: 2018-08-20 23:50
To: Azure/azure-iot-sdk-c
CC: dongranqi; Mention
Subject: Re: [Azure/azure-iot-sdk-c] ubantu 14.04 unknown option logtrace (#601)
Hi @dongranqi , could you please provide the information requested in the issue template?
Which version of the SDK are you using?

**Comment by jebrando** [comment]
THanks for the issues, in the telemetry sample I made it so it won't add a logging to HTTP samples.

**Comment by az-iot-builder-01** [comment]
@ewertons, @dongranqi, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
