### ISSUE TITLE
Make CMake scripts friendly to add_subdirectory`

### ISSUE THREAD

**Issue by rcdailey** [Azure/azure-iot-sdk-c#603]
I'd like to add the IoT SDK to my project as a submodule and include the root CMakeLists.txt via `add_subdirectory()`. However, this doesn't work, especially in cases where I need to specify OpenSSL. You use `find_package()` to obtain OpenSSL, instead of first checking to see if the `OpenSSL::SSL` and `OpenSSL::Crypto` targets exist. You should check for the targets _first_, because this means that the parent project has already found OpenSSL for you. You should then link these targets. If the targets do not exist, then use `find_package()`. Example:

```
if (NOT TARGET OpenSSL::SSL OR NOT TARGET OpenSSL::Crypto)
    find_package(OpenSSL)
endif()

target_link_libraries(MyIoTLibrary PUBLIC OpenSSL::SSL OpenSSL::Crypto)
```

**Comment by ewertons** [comment]
Hi @rcdailey , please don't forget to specify which version of the SDK  and platform you are using (the fields requested on the template).

**Comment by ewertons** [comment]
Other projects have included the Azure IoT C SDK as a submodule successfully, so perhaps there is something missing in your CMakeLists.txt?

Have you tried specifying the path to your custom OpenSSL using:
```
cmake -DCMAKE_PREFIX_PATH=<path to openssl> <path to your project>
```

That cmake option controls where find_package() should look first for libraries. If you specify the path to your custom openssl library there, it will pick the package from that location.
As an example, we recently run the following (look for the line that reads "Found OpenSSL"):

```shell
ewertons@debian:~/azure-iot-sdk-c/cmake$ cmake -DCMAKE_PREFIX_PATH=/home/ewertons/openssl-1.1.0i ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IoT Client SDK Version = 1.2.8
-- Provisioning client OFF
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- target architecture: x86_64
-- Performing Test CXX_FLAG_CXX11
-- Performing Test CXX_FLAG_CXX11 - Success
-- Found OpenSSL: /home/ewertons/openssl-1.1.0i/libssl.so;/home/ewertons/openssl-1.1.0i/libcrypto.so (found version "1.1.0i")
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
-- Checking for module 'libcurl'
--   Found libcurl, version 7.52.1
-- Found CURL: curl
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- iothub architecture: x86_64
-- Configuring done
-- Generating done
```

**Comment by rcdailey** [comment]
I'm using the latest on master as of today. I did t use find package to
find openssl, I have my own custom structure for it. As such even if you
use find package it won't work.

**Comment by rcdailey** [comment]
Also checking for targets as I recommended is more flexible and supports
more methods of injecting the dependency into your library. Boost CMake
support is using the model I suggested, so the approach is proven.

**Comment by jebrando** [comment]
@rcdailey if you set OPENSSL_ROOT_DIR on the cmake command line
`cmake .. -DOPENSSL_ROOT_DIR:PATH=[openssl path]`

this would set the find_package to look at this directory for openssl.  For full disclosure I'm unfamiliar with the OpenSSL::SSL and OpenSSL::Crypto values and when I tried to set them in the cmake it did not get set correctly.

So the question is can you set the OPENSSL_ROOT_DIR variable?

**Comment by rcdailey** [comment]
Like I was explaining earlier, I cannot use the find module for my particular installation of OpenSSL since the structure of that library is non-standard on my platform. I literally arrange the headers and libraries in a unique way. Using `find_package()` is a non-starter for me. And because I can't use `find_package()`, there's no point in specifying `OPENSSL_ROOT_DIR`, which is merely a hint to the find module as to where it can find the root directory of OpenSSL, but it still expects a standard installation otherwise it can't find what it needs inside.

The [FindOpenSSL documentation page](https://cmake.org/cmake/help/latest/module/FindOpenSSL.html?highlight=findopenssl) explains the targets. I can (and do) create these targets by hand. So from the perspective of *your* CMake code, those targets came from a `find_package(OpenSSL)` call that occurred upstream of your root `CMakeLists.txt`.

**Comment by jebrando** [comment]
@rcdailey would something like this work for you:

```
if (NOT TARGET OpenSSL::SSL OR NOT TARGET OpenSSL::Crypto)
    find_package(OpenSSL REQUIRED)
endif()
target_link_libraries(aziotsharedutil ${OPENSSL_LIBRARIES})
```
It's a small change from what you want, but we'd like to keep the OPENSSL_LIBRARIES.

**Comment by rcdailey** [comment]
Close, but it should be:

```
if (NOT TARGET OpenSSL::SSL OR NOT TARGET OpenSSL::Crypto)
    find_package(OpenSSL REQUIRED)
endif()
target_link_libraries(aziotsharedutil PUBLIC OpenSSL::SSL OpenSSL::Crypto)
```

Per the documentation page I linked before, those 2 imported targets are guaranteed. So basically you will link the targets (which will give you the include directories and libraries) from one of three sources:

1. The upstream project has defined those import targets themselves (this is my case)
2. The upstream project has invoked `find_package(OpenSSL)` themselves, making the imported targets available to you
3. The upstream project does not exist or has not provided those imported targets, so you have introduced them via `find_package()` yourself.

**Comment by jebrando** [comment]
We prefer to use ${OPENSSL_LIBRARIES} instead of OpenSSL::SSL OpenSSL::Crypto.  Both are acceptable in the FindOpenSSL documentation page referenced above.  All the other changes shall be made and get into the repo at my first opportunity.

**Comment by jcar87** [comment]
@rcdailey: 
```find_package(OpenSSL REQUIRED)``` this doesnt overwrite the targets `OpenSSL::SSL` and `OpenSSL::Crypto` if they already exist. Look at the official `FindOpenSSL.cmake`: https://github.com/Kitware/CMake/blob/master/Modules/FindOpenSSL.cmake#L427. The targets are only added if they have not already been defined.
Therefore a check like this:
```
if (NOT TARGET OpenSSL::SSL OR NOT TARGET OpenSSL::Crypto)
    find_package(OpenSSL REQUIRED)
endif()
```

should be redundant.


@jebrando: I believe you most certainly use the targets these days, as opposed to `${OPENSSL_LIBRARIES}`. Variables like that are kept there these days for legacy purposes, and should not be used. Not using the imported targets actually make this project harder to integrate in other projects that use cmake (in particular with regards to libraries such as OpenSSL or CURL that may already be used by other projects that also depend on this one). I'd be happy to point to examples or link to cmake current best practices.

**Comment by dandrestor** [comment]
> Other projects have included the Azure IoT C SDK as a submodule successfully, so perhaps there is something missing in your CMakeLists.txt?

I'm guessing these projects might have done so having to use workarounds in their own cmake projects to counteract the problems in the Azure SDK cmake files. In any case, this is what I have done.

Specifically for `iothub_client`, CMakeLists.txt is missing something along the lines of:
```cmake
target_include_directories(iothub_client
+	INTERFACE
+		$<BUILD_INTERFACE:${CMAKE_CURRENT_LIST_DIR}/inc>
+)
```

**Comment by gregman-msft** [comment]
Thanks for the feedback. This is now on our backlog but do not have an ETA for the work yet. Please vote on this [User voice ](https://feedback.azure.com/forums/321918-azure-iot/suggestions/38869972-make-cmake-scripts-friendly-to-add-subdirectory-in) item, which can also be used for tracking our plans. It may take some time for the link to work, please try again in a few hours if it does not work when you first tried it.

**Comment by az-iot-builder-01** [comment]
@ewertons, @rcdailey, @jebrando, @jcar87, @dandrestor, @gregman-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by rcdailey** [comment]
In what commit (and repo) was this resolved?

**Comment by gregman-msft** [comment]
Hi @rcdailey see my comment above for more details. We'd like to track this in our user voice forum for further feedback while it is in our backlog.

**Comment by rcdailey** [comment]
The issue was closed here, which to me implied the issue was resolved with a fix in the repository somewhere. Was it closed instead to be tracked elsewhere? If so that's a bit misleading; why even have the issue tracker enabled here?

**Comment by gregman-msft** [comment]
We're preferring to track items in our backlog in a location that gives us a better ability to aggregate feedback via both comments and voting, as well as keep our GitHub issues fresh/up-to-date to maximize visibility on incoming issues. This is an evolving process to figure out how to best keep track of everything, so we appreciate your feedback and will continue improving based on it.
