### ISSUE TITLE
Problem with implementation of provisioning client in Renesas microprocessor

### ISSUE THREAD

**Issue by 59985** [Azure/azure-iot-sdk-c#606]
I am trying to implement provisioning client in one of our products. The iothub_client is already up running, so we really would like to get the provisioning client up running.

Just some information’s our product. 
- The microprocessor is a Renesas R5F563NY
- Using Wolfssl Version 3.15.3. 
- OS ThreadX
- NetX Tcp/Ip stack

I think my problem is related to the X.509, but not 100% sure. I have followed the Quickstart https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509. Everything is working in Visual Studio. 

Here is what I have done. By debugging “dice_device_enrollment” in VS I copied the public and private certificate and hardcoded into my embedded code. I am not sure that is the right way. When the device is trying to do the key exchange it fails when UnPad Rsa. I really not an expert in X.509 and Wolfssl have a lot of compiler defines how to handle the X.509 certificated.

I can see from shared utility that somebody have tried to use wolfssl
https://github.com/Azure/azure-c-shared-utility/blob/master/adapters/tlsio_wolfssl.c

Any ideas or experience? 

**WolfSSL defines:**
#define HAVE_ECC
#define HAVE_ECC_KEY_IMPORT
#define HAVE_ECC_VERIFY
#define HAVE_ECC_DHE
#define HAVE_ECC_KEY_EXPORT
#define HAVE_ECC_SIGN
#define HAVE_ALL_CURVES
#define HAVE_CURVE25519
#define HAVE_CURVE25519_SHARED_SECRET
#define HAVE_CURVE25519_KEY_IMPORT
#defin HAVE_CURVE25519_KEY_EXPORT
#define SIZEOF_LONG_LONG 8
#define WOLFSSL_SHA384
#define WOLFSSL_SHA512
#define WOLFSSL_AES_DIRECT
#define maybe more or less

**Log file "Wolfssl"**
Provisioning API Version: 1.2.8
wolfSSL Entering WOLFSSL_CTX_new_ex
wolfSSL Entering wolfSSL_Init
wolfSSL Entering wolfCrypt_Init
wolfSSL Entering wolfSSL_CertManagerNew
wolfSSL Leaving WOLFSSL_CTX_new, return 0
wolfSSL Entering wolfSSL_CTX_load_verify_locations
Getting dynamic buffer
Processing CA PEM file
wolfSSL Entering PemToDer
wolfSSL error occurred, error = -8
CA Parse failed, with progress in file.

**Comment by jebrando** [comment]
@59985 do you have an SDK log so I can see if I can diagnose the issue.

**Comment by 59985** [comment]
@jebrando I have attached the trace lo
[trace.txt](https://github.com/Azure/azure-iot-sdk-c/files/2322715/trace.txt)
g.

**Comment by az-iot-builder-01** [comment]
@59985, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by 59985** [comment]
Reopen

**Comment by jebrando** [comment]
@59985 When building wolfssl we use the following config line:
--enable-ecc --enable-debug --enable-hkdf --enable-eccencryptmake --enable-harden

This should enable wolfssl to run against ecc certificates.

If this doesn't work please open a new issue for tracking.
