### ISSUE TITLE
Missing FreeRTOS adapter

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [Azure/azure-iot-sdk-c#609]
- **OS and version used:**  Windows 10

- **SDK version used:** 1.2.8

# Description of the issue:

Our system is based on FreeRTOS. I would like to support multitasking API, but I am currently able to support only LL API. Are you planing to add FreeRTOS adapter? One obstacle for adaptation is function thread_join used in code. It might be emulated in adapter or avoided in code.

**Comment by jspaith** [comment]
@DavidJurajdaNXP  - my understanding is that for FreeRTOS there's a way to implement the `ThreadAPI_Join` at the PAL layer, analogous to [this](https://github.com/Azure/azure-c-shared-utility/blob/009eb4b3dced8186f9ddb0ab0dddb24dda9cea8f/adapters/threadapi_pthreads.c)?  One of our engineers says task.h should have this from freertos sdk?

**Comment by DavidJurajdaNXP** [comment]
I have realized there is new [POSIX wrapper](https://github.com/aws/amazon-freertos/tree/master/lib/FreeRTOS-Plus-POSIX) in FreeRTOS. It should make the adaptation easy now.

**Comment by massand** [comment]
We recommend using the LL layer on RTOS so you avoid the use of threadapi_join. Thanks!

**Comment by az-iot-builder-01** [comment]
@DavidJurajdaNXP, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
