### ISSUE TITLE
Release zip contains empty folders.

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [Azure/azure-iot-sdk-c#612]
- **OS and version used:**  Windows 10

- **SDK version used:** 1.2.8

# Description of the issue:

Release zip contains empty folders. Could you add all resources to prevent manual completion? It would be useful for referencing to unique package.

**Comment by massand** [comment]
This is by design in GitHub.

**Comment by az-iot-builder-01** [comment]
@DavidJurajdaNXP, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
