### ISSUE TITLE
sas token renewal

### ISSUE THREAD

**Issue by ThomasNauwelaerts** [Azure/azure-iot-sdk-c#613]
- **OS and version used:** Embedded platform with FreeRTOS

- **SDK version used:** own implementation

# Description of the issue:
Since a couple of days/weeks there has been a non documented change to the IoT Hub server to solve the following 'bug': https://github.com/Azure/azure-iot-sdk-c/issues/163 
I cannot find any documentation on the expected actions and reactions on the sas token, more specifically the renewal of them. 
So we implemented in our devices the following flow:
A device generates the sas token with the primary key, with an expiry of one hour.
It connects and stays connected as long as the ping is maintained.

A token that is captured by a third party, can be used to make a connection within one hour. Afterwards it cannot be used anymore.

Now this (non documented?) philosophy has changed, what brings some connection issues to our already deployed devices. Consequence: unhappy customers and a needed firmware update.

Now, how should the sas token renewal be implemented? Should the token be expired after the expiry time and then just reconnect? That seems to be quite strange? I think it should be possible to renew the token before expiry, so the devices stay connected?
Also, I cannot find any example on the best practice to renew the token. All examples seem to use a already pre-made hard coded sas token.

Please advice on how to implement the new philosophy and why no notification has been given to the customers?
Thank you.

# Code sample exhibiting the issue:
N/A

# Console log of the issue:
N/A

**Comment by ThomasNauwelaerts** [comment]
Hi @markrad

Thank you for the response.
We're indeed using MQTT with sas token authentication.
Where can I find the specification of the sas token - MQTT combination? We implemented it as a connection setup token, not a token to maintain the connection (how it was working before). That also seemed better than the implementation now:
It takes half a minute to disconnect and make a new connection. To limit this to the minimum, this forces us to use an expiry of one month. If someone tries to use the key afterwards, it will be valid for one month.
When we keep the previous implementation, it was possible to set an expiry of 1 minute. If the device gets connected within one minute, it will stay connected forever. If someone tries to use the token afterwards, it will be useless.

So, why choose for the other implementation?
Thanks for the info.

Best regards
Thomas

**Comment by ewertons** [comment]
Hi @ThomasNauwelaerts ,
first of all, we apologize for the disruption. 
We do not take breaking changes lightly, our commitment is to never disrupt the existing API and protocol contract within a given major version release (e.g., current 1.x.x) of the SDKs.
Unfortunately, this was a security bug that needed to be addressed.

The intent of the expiration time is to define for how long the SAS token is valid, which translates to for how long a given connection is valid if authenticated with such token. 
Not to define the time window a client could authenticate and then remain authenticated with no expiration. That was the bug, and now it has been addressed.

To work with the correct design, the Azure IoT SDKs "refresh" the SAS token with a fixed frequency so the client remains "connected". The quotes are intended - on AMQP, as explained by @markrad , the iothub client indeed remains connected, while with MQTT a reconnection must occur, using then a new SAS token every time. The reason behind the implementation is that AMQP supports authentication using [Claims Based Security (cbs)](https://lists.oasis-open.org/archives/amqp/201307/msg00002/amqp-cbs-v1.0-wd01_2013-07-08.pdf), which allows an existing connection with AMQP to be re-authenticated. 
MQTT only supports it starting at version 5, which the IoT Hub does not support yet.


If you look at our [code](https://github.com/Azure/azure-iot-sdk-c/blob/2018-07-11/iothub_client/src/iothubtransport_mqtt_common.c#L2126), you will see that we keep track of the SAS token expiration time and reconnect within a fixed frequency (as mentioned above by Mark) using a freshly-generated one (containing a new, valid expiration time).

You will need to update your code with such mechanism to make it work against the IoT Hub with MQTT again.

**Comment by az-iot-builder-01** [comment]
@ThomasNauwelaerts, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
