### ISSUE TITLE
Code formating - trailing whitespaces

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [Azure/azure-iot-sdk-c#614]
- **OS and version used:**  Windows 10

- **SDK version used:** 1.2.8

# Description of the issue:

Code formatting issues:
    - trailing white spaces
    - mix of tabs and spaces
    - missing new line on the end of files (causing warnings in Keil MDK)

**Comment by massand** [comment]
Fix is in. Thanks.

**Comment by az-iot-builder-01** [comment]
@DavidJurajdaNXP, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
