### ISSUE TITLE
Toolchain tests - ARM GCC, NXP MCUXpresso IDE, Keil MDK, IAR EWARM,  

### ISSUE THREAD

**Issue by DavidJurajdaNXP** [Azure/azure-iot-sdk-c#615]
- **OS and version used:**  Windows 10

- **SDK version used:** 1.2.8

# Description of the issue:

I am experiencing warnings in some toolchains. Could you introduce build tests for some embedded toolchains like IAR, MDK, ARMGCC or MCUXPRESSO IDE?

**Comment by massand** [comment]
Currently, we have a list of validated toolchains and platforms under our [platform support](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-platform-support). That page also contains a list of partner-supported platforms, which we are looking to expand with community support.

**Comment by az-iot-builder-01** [comment]
@DavidJurajdaNXP, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
