### ISSUE TITLE
documentation: how to attempt re-connection at specified interval for infinite duration

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#618]
- **OS and version used:** macOS 10.13.4
- **SDK version used:** 1.28

# Description of the issue:
IOTHUB_CLIENT_RETRY_INTERVAL attempts reconnection at 5 seconds until succeeds. This 5 seconds is not configurable. What is configurable with IOTHUB_CLIENT_RETRY_INTERVAL is only the max duration for which reconnects are attempted.

If a lib user has a simple need of attempting reconnection every X seconds infinitely, it doesn't appear possible with sdk(?). Is is possible to add an option to make the 5 second fixed interval of IOTHUB_CLIENT_RETRY_INTERVAL configurable?

The connection_and_messaging_reliability.md[[1](
      azure-iot-sdk-c/doc/connection_and_messaging_reliability.md
    )] docs suggest that it is configurable? Is the document correct?

**Comment by ewertons** [comment]
Hi @kiranpradeep ,
although the module that controls the retry frequency does have an [option](https://github.com/Azure/azure-iot-sdk-c/blob/2018-07-11/iothub_client/src/iothub_client_retry_control.c#L396) for that, it is not exposed in the [upper layers](https://github.com/Azure/azure-iot-sdk-c/blob/2018-07-11/iothub_client/src/iothubtransport_amqp_common.c#L1906). 

That would be an improvement we will add to our list.

**Comment by bikamani** [comment]
Hi @kiranpradeep Thanks for bringing this to our attention. I have updated the document to reflect current functionality (https://github.com/Azure/azure-iot-sdk-c/pull/849). Also the option to configure time interval is in our enhancement list.

**Comment by gregman-msft** [comment]
Hi @kiranpradeep we have implemented this functionality, and it is documented in this file: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Iothub_sdk_options.md You can search for "retry_interval_sec" for the details.

**Comment by az-iot-builder-01** [comment]
@kiranpradeep, @ewertons, @bikamani, @gregman-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
