### ISSUE TITLE
Valgrind reports use of uninitialized memory

### ISSUE THREAD

**Issue by mm-mhr** [Azure/azure-iot-sdk-c#62]
When sending a cloud to device message valgrind reports usage of uninitialized memory.
I am not able to tell if this is a false positive or not. 
So I'd like you to kindly ask you to have a look at this.

This can be reproduced like this:
1) Start the iot hub client sample with valgrind.
(https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_mqtt)
2) Send any Cloud to device message (e.g. using Device Explorer)
-> Valgrind reports the use of uninitialized memory.

**Comment by anporumb** [comment]
Hello @mm-mhr,

We are going to look at this, thank you for your report.

Best Regards,
Andrei Porumb

**Comment by BertKleewein** [comment]
Hi @mm-mhr,
Can you please provide a call stack for the reported errors?  valgrind will report using uninitialized memory when using openssl because openssluses uninitialized memory as a source of entropy.
thanks
-Bert

**Comment by BertKleewein** [comment]
You can disable this feature of SSL and verify that the warnings go away.  I was unable produce any warnings after following the instructions [here](https://bertkblog.wordpress.com/2017/02/27/getting-past-valgrind-warnings-by-building-a-private-openssl/)

**Comment by mm-mhr** [comment]
Dear Bert,

Thank you very much for looking into this.
Below is what valgrind reports after receiving a cloud to device message.
Note that valgrind reports a lot of "Conditional jump or move depends on uninitialised value(s)" which are not listed below.

Syscall param write(buf) points to uninitialised byte(s)
  in consolelogger_log in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/consolelogger.c:34
Address 0x4026062 is not stack'd, malloc'd or (recently) free'd  1: __write_nocancel in /build/eglibc-3GlaMS/eglibc-2.19/io/../sysdeps/unix/syscall-template.S:81
  2: _IO_file_write@@GLIBC_2.2.5 in /build/eglibc-3GlaMS/eglibc-2.19/libio/fileops.c:1261
  3: new_do_write in /build/eglibc-3GlaMS/eglibc-2.19/libio/fileops.c:538
  4: _IO_do_write@@GLIBC_2.2.5 in /build/eglibc-3GlaMS/eglibc-2.19/libio/fileops.c:511
  5: _IO_file_overflow@@GLIBC_2.2.5 in /build/eglibc-3GlaMS/eglibc-2.19/libio/fileops.c:876
  6: puts in /build/eglibc-3GlaMS/eglibc-2.19/libio/ioputs.c:42
  7: consolelogger_log in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/consolelogger.c:34
  8: log_incoming_trace in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:275
  9: recvCompleteCallback in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:602
  10: completePacketData in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:584
  11: mqtt_codec_bytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:1103
  12: onBytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:390
  13: decode_ssl_received_bytes in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:665
  14: on_underlying_io_bytes_received in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:704
  15: socketio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/adapters/socketio_berkeley.c:615
  16: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  17: tlsio_openssl_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1177
  18: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  19: mqtt_client_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:1120
  20: IoTHubTransport_MQTT_Common_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2487
  21: IoTHubTransportMqtt_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95


Use of uninitialised value of size 8
  in STRING_construct_sprintf in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/strings.c:140
  1: _itoa_word in /build/eglibc-3GlaMS/eglibc-2.19/stdio-common/_itoa.c:179
  2: vfprintf in /build/eglibc-3GlaMS/eglibc-2.19/stdio-common/vfprintf.c:1660
  3: vsnprintf in /build/eglibc-3GlaMS/eglibc-2.19/libio/vsnprintf.c:119
  4: STRING_construct_sprintf in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/strings.c:140
  5: recvCompleteCallback in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:543
  6: completePacketData in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:584
  7: mqtt_codec_bytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:1103
  8: onBytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:390
  9: decode_ssl_received_bytes in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:665
  10: on_underlying_io_bytes_received in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:704
  11: socketio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/adapters/socketio_berkeley.c:615
  12: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  13: tlsio_openssl_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1177
  14: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  15: mqtt_client_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:1120
  16: IoTHubTransport_MQTT_Common_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2487
  17: IoTHubTransportMqtt_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  18: IoTHubClient_LL_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  19: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:164
  20: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:186
Uninitialised value was created by a stack allocation  1: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0


Use of uninitialised value of size 8
  in STRING_construct_sprintf in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/strings.c:151
  1: _itoa_word in /build/eglibc-3GlaMS/eglibc-2.19/stdio-common/_itoa.c:179
  2: vfprintf in /build/eglibc-3GlaMS/eglibc-2.19/stdio-common/vfprintf.c:1660
  3: vsnprintf in /build/eglibc-3GlaMS/eglibc-2.19/libio/vsnprintf.c:119
  4: STRING_construct_sprintf in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/strings.c:151
  5: recvCompleteCallback in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:543
  6: completePacketData in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:584
  7: mqtt_codec_bytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:1103
  8: onBytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:390
  9: decode_ssl_received_bytes in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:665
  10: on_underlying_io_bytes_received in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:704
  11: socketio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/adapters/socketio_berkeley.c:615
  12: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  13: tlsio_openssl_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1177
  14: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  15: mqtt_client_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:1120
  16: IoTHubTransport_MQTT_Common_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2487
  17: IoTHubTransportMqtt_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  18: IoTHubClient_LL_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  19: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:164
  20: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:186
Uninitialised value was created by a stack allocation  1: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0


Use of uninitialised value of size 8
  in byteutil_readUTF in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:130
  1: byteutil_readUTF in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:130
  2: recvCompleteCallback in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:549
  3: completePacketData in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:584
  4: mqtt_codec_bytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:1103
  5: onBytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:390
  6: decode_ssl_received_bytes in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:665
  7: on_underlying_io_bytes_received in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:704
  8: socketio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/adapters/socketio_berkeley.c:615
  9: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  10: tlsio_openssl_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1177
  11: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  12: mqtt_client_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:1120
  13: IoTHubTransport_MQTT_Common_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2487
  14: IoTHubTransportMqtt_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  15: IoTHubClient_LL_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  16: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:164
  17: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:186
Uninitialised value was created by a stack allocation  1: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0


Use of uninitialised value of size 8
  in byteutil_read_uint16 in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:107
  1: byteutil_read_uint16 in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:107
  2: recvCompleteCallback in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:569
  3: completePacketData in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:584
  4: mqtt_codec_bytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:1103
  5: onBytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:390
  6: decode_ssl_received_bytes in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:665
  7: on_underlying_io_bytes_received in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:704
  8: socketio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/adapters/socketio_berkeley.c:615
  9: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  10: tlsio_openssl_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1177
  11: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  12: mqtt_client_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:1120
  13: IoTHubTransport_MQTT_Common_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2487
  14: IoTHubTransportMqtt_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  15: IoTHubClient_LL_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  16: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:164
  17: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:186
Uninitialised value was created by a stack allocation  1: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0


Use of uninitialised value of size 8
  in mqttmessage_create in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_message.c:59
  1: memcpy@@GLIBC_2.14 in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: mqttmessage_create in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_message.c:59
  3: recvCompleteCallback in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:577
  4: completePacketData in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:584
  5: mqtt_codec_bytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:1103
  6: onBytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:390
  7: decode_ssl_received_bytes in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:665
  8: on_underlying_io_bytes_received in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:704
  9: socketio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/adapters/socketio_berkeley.c:615
  10: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  11: tlsio_openssl_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1177
  12: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  13: mqtt_client_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:1120
  14: IoTHubTransport_MQTT_Common_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2487
  15: IoTHubTransportMqtt_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  16: IoTHubClient_LL_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  17: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:164
  18: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:186
Uninitialised value was created by a stack allocation  1: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0


Use of uninitialised value of size 8
  in STRING_sprintf in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/strings.c:533
  1: _itoa_word in /build/eglibc-3GlaMS/eglibc-2.19/stdio-common/_itoa.c:179
  2: vfprintf in /build/eglibc-3GlaMS/eglibc-2.19/stdio-common/vfprintf.c:1660
  3: vsnprintf in /build/eglibc-3GlaMS/eglibc-2.19/libio/vsnprintf.c:119
  4: STRING_sprintf in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/strings.c:533
  5: recvCompleteCallback in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:601
  6: completePacketData in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:584
  7: mqtt_codec_bytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:1103
  8: onBytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:390
  9: decode_ssl_received_bytes in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:665
  10: on_underlying_io_bytes_received in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:704
  11: socketio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/adapters/socketio_berkeley.c:615
  12: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  13: tlsio_openssl_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1177
  14: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  15: mqtt_client_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:1120
  16: IoTHubTransport_MQTT_Common_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2487
  17: IoTHubTransportMqtt_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  18: IoTHubClient_LL_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  19: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:164
  20: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:186
Uninitialised value was created by a stack allocation  1: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0


Use of uninitialised value of size 8
  in STRING_sprintf in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/strings.c:556
  1: _itoa_word in /build/eglibc-3GlaMS/eglibc-2.19/stdio-common/_itoa.c:179
  2: vfprintf in /build/eglibc-3GlaMS/eglibc-2.19/stdio-common/vfprintf.c:1660
  3: vsnprintf in /build/eglibc-3GlaMS/eglibc-2.19/libio/vsnprintf.c:119
  4: STRING_sprintf in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/strings.c:556
  5: recvCompleteCallback in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:601
  6: completePacketData in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:584
  7: mqtt_codec_bytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:1103
  8: onBytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:390
  9: decode_ssl_received_bytes in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:665
  10: on_underlying_io_bytes_received in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:704
  11: socketio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/adapters/socketio_berkeley.c:615
  12: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  13: tlsio_openssl_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1177
  14: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  15: mqtt_client_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:1120
  16: IoTHubTransport_MQTT_Common_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2487
  17: IoTHubTransportMqtt_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  18: IoTHubClient_LL_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  19: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:164
  20: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:186
Uninitialised value was created by a stack allocation  1: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0


Use of uninitialised value of size 8
  in BUFFER_create in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/buffer.c:82
  1: memcpy@@GLIBC_2.14 in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: BUFFER_create in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/buffer.c:82
  3: IoTHubMessage_CreateFromByteArray in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_message.c:99
  4: mqtt_notification_callback in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1212
  5: recvCompleteCallback in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:606
  6: completePacketData in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:584
  7: mqtt_codec_bytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_codec.c:1103
  8: onBytesReceived in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:390
  9: decode_ssl_received_bytes in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:665
  10: on_underlying_io_bytes_received in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:704
  11: socketio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/adapters/socketio_berkeley.c:615
  12: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  13: tlsio_openssl_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1177
  14: xio_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:163
  15: mqtt_client_dowork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:1120
  16: IoTHubTransport_MQTT_Common_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2487
  17: IoTHubTransportMqtt_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  18: IoTHubClient_LL_DoWork in /home/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  19: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:164
  20: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test5_ReceiveCommand/main.cpp:186
Uninitialised value was created by a stack allocation  1: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0


Best regards,
Michael

**Comment by mm-mhr** [comment]
Dear Bert,

Thank you for this detailed investigation and the blog posting. 
I did not realize that uninitialized memory is used as a source for entropy, so I was wondering over and over again how to deal with this.
It is now clear to me that it is a false positive. Thank you for your efforts tracking this down.

Best Regards,
Michael
