### ISSUE TITLE
Internal compiler error building unittests on Ubuntu

### ISSUE THREAD

**Issue by seank-com** [Azure/azure-iot-sdk-c#620]
- **OS and version used:** Docker ```ubuntu:latest``` (18.04), ```ubuntu:xenial``` (16.04) and ```ubuntu:trusty``` (14.04)

This repos from a docker container hosted on either mac or windows, I've tested both. I used this build method for #460 (Silence Warnings) so I know it worked at one point. This has got to be similar to the way you run your CI/CD, so I'm surprised it is failing.

- **SDK version used:** Today's ```master``` branch since I am try to create a PR

# Description of the issue:

Trying to build the sdk with unittests enabled causes an internal compiler error on Ubuntu.

# Code sample exhibiting the issue:

Create a Dockerfile

```Dockerfile
FROM ubuntu:xenial

RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y git && \
  apt-get install -y cmake && \
  apt-get install -y build-essential && \
  apt-get install -y curl && \
  apt-get install -y libcurl4-openssl-dev && \
  apt-get install -y libssl-dev && \
  apt-get install -y uuid-dev && \
  apt-get install -y nano && \
  cmake --version && \
  gcc --version && \
  mkdir /src

WORKDIR /src

CMD ["bash"]
```

### For Windows
**Note:** _The first command assumes you are running from the folder where the Dockerfile above is located. The second command assumes your local copy of ```azure-iot-sdk-c``` is in ```Users\seank\Development\azure-iot-sdk-c```_ 
```
C:>docker build -t azure-build .
C:>docker run -it --rm --mount type=bind,src=c:/Users/seank/Development/azure-iot-sdk-c,dst=/src/azure-iot-sdk-c azure-build
```

### For Mac

```bash
$ docker build -t azure-build .
$ docker run -it --rm --mount type=bind,src=/Users/seank/Development/azure-iot-sdk-c,dst=/src/azure-iot-sdk-c azure-build
```

### From the container's bash shell

run the following commands:

```bash
# cd azure-iot-sdk-c
# rm -rf cmake/
# mkdir cmake
# cd cmake/
# cmake .. -Drun_unittests:bool=ON
# cmake --build .
```

# Console log of the issue:

```
...build output clipped for brevity...
Scanning dependencies of target iothub_messaging_ll_ut_exe
[ 24%] Building C object iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/iothub_messaging_ll_ut.c.o
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/build.make:62: recipe for target 'iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/iothub_messaging_ll_ut.c.o' failed
make[2]: *** [iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/iothub_messaging_ll_ut.c.o] Error 4
CMakeFiles/Makefile2:2217: recipe for target 'iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/all' failed
make[1]: *** [iothub_service_client/tests/iothub_msging_ll_ut/CMakeFiles/iothub_messaging_ll_ut_exe.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
root@bdcf604bce47:/src/azure-iot-sdk-c/cmake#
```

**Comment by ewertons** [comment]
Hi @seank-com , 
the failures on the log show:
"cc: internal compiler error: Killed (program cc1)"

Searching around it seems related to the compiler running out of memory in the host machine.

Could you check if you have the same amount of disc and ram available for the docker machine as before?

If you do, while we investigate here why the memory usage is so high, could you try either:

1. Increasing the memory available for the docker container, or
2. Building the SDK without unit tests

**Comment by seank-com** [comment]
Good call. I had recently reinstalled Docker to test the new kubernetes integration. By default, Both Docker for Windows and Docker for Mac limit memory to 2GB (upping it to 4GB fixed the problem).

The SDK compiles fine without unit tests with 2GB of memory.

**Comment by az-iot-builder-01** [comment]
@seank-com, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
