### ISSUE TITLE
Build fails with undefined references

### ISSUE THREAD

**Issue by trillykins** [Azure/azure-iot-sdk-c#621]
I have a project that works, but it is encased in the sample directories and I would like to make a clean build only containing my project. I have the following CMakeLists.txt file:

```
cmake_minimum_required(VERSION 2.8.11)

set (CMAKE_C_FLAGS "--std=c99 ${CMAKE_C_FLAGS}")

set(AZUREIOT_INC_FOLDER ".." "/usr/include/azureiot" "/usr/include/azureiot/inc")

include_directories(${AZUREIOT_INC_FOLDER})

include_directories("certs");

set(axis_comm_c_files
    myfiles.c
)

set(axis_comm_h_files
    myfiles.h
)

add_definitions(-DUSE_AMQP)
add_definitions(-DUSE_HTTP)

add_executable(axis_comm ${axis_comm_c_files} ${axis_comm_h_files})

target_link_libraries(axis_comm 
    iothub_client_mqtt_transport
    iothub_client_amqp_transport
    iothub_client_http_transport
    iothub_client
    parson
    aziotsharedutil
    umqtt
    prov_auth_client
    hsm_security_client
    uhttp
    uuid
    pthread
    curl
    ssl
    crypto
    m
)

# Get the current working branch
execute_process(
  COMMAND git rev-parse --abbrev-ref HEAD
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE GIT_BRANCH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

# Get the build date
execute_process(
  COMMAND date --iso=seconds
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE BUILD_DATE
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

# Get the latest abbreviated commit hash of the working branch
execute_process(
  COMMAND git --no-pager describe --tags --always
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE GIT_COMMIT_HASH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

add_definitions("-DGIT_BRANCH=${GIT_BRANCH}")
add_definitions("-DBUILD_DATE=${BUILD_DATE}")
add_definitions("-DGIT_COMMIT_HASH=${GIT_COMMIT_HASH}")

configure_file(
    ${CMAKE_CURRENT_SOURCE_DIR}/version_git.h.in
    ${CMAKE_CURRENT_SOURCE_DIR}/version_git.h
)
```

However, when I build it, I get the following error when it reaches 100%:
```
...
[50%] Building C object CMakeFiles/axis_comm.dir/...c.o
[60%] Building C object CMakeFiles/axis_comm.dir/...c.o
[70%] Building C object CMakeFiles/axis_comm.dir/...c.o
[80%] Building C object CMakeFiles/axis_comm.dir/...c.o
[90%] Building C object CMakeFiles/axis_comm.dir/...c.o
[100%] Building C object CMakeFiles/axis_comm.dir/...c.o
Linking C executable axis_comm
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libprov_auth_client.a(iothub_auth_client.c.o): In function `iothub_device_auth_create':
(.text+0x8e): undefined reference to `hsm_client_http_edge_interface'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libprov_auth_client.a(iothub_security_factory.c.o): In function `iothub_security_init':
(.text+0xe8): undefined reference to `initialize_hsm_system'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libprov_auth_client.a(iothub_security_factory.c.o): In function `iothub_security_deinit':
(.text+0xf3): undefined reference to `deinitialize_hsm_system'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libprov_auth_client.a(prov_security_factory.c.o): In function `prov_dev_security_init':
(.text+0xe8): undefined reference to `initialize_hsm_system'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libprov_auth_client.a(prov_security_factory.c.o): In function `prov_dev_security_deinit':
(.text+0xf3): undefined reference to `deinitialize_hsm_system'
collect2: error: ld returned 1 exit status
make[2]: *** [axis_comm] Error 1
make[1]: *** [CMakeFiles/axis_comm.dir/all] Error 2
make: *** [all] Error 2
```

I have 'hsm_security_client' in my target link libraries. Could I be missing some library directory inside my project?

**Comment by ewertons** [comment]
Hi @trillykins ,
your CMakeLists.txt seems ok, you are adding the correct libraries (for reference, [this](https://github.com/Azure/azure-iot-sdk-c/blob/2018-07-11/iothub_client/samples/iothub_ll_telemetry_sample/linux/CMakeLists.txt#L26) should be the list).

What is the version of the SDK you have installed?
Could you verify if you have the header (hsm_client_data.h) and library (hsm_security_client.*) available within the paths you provided in the CMakeLists.txt ("/usr/include/azureiot" "/usr/include/azureiot/inc")?

**Comment by trillykins** [comment]
@ewertons How do I check the SDK version? If I do a `sudo apt list azure-iot-sdk-c-dev` I get the following `azure-iot-sdk-c-dev/trusty,now 0.2.0-10trusty amd64`.

But neither hsm_client_data nor hsm_security_client seem to be present in either "/usr/include/azureiot" "/usr/include/azureiot/inc".

**Comment by ewertons** [comment]
Yes, your question makes perfect sense.
The version of the apt package (0.2.0-10trusty) is different than the version of the SDK code. 
You can see the version of the SDK when you enable [verbose logging](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L126) right after creating the device client. The traces printed will show the code version.
However, tracking back through the date this [apt package was released](https://launchpad.net/~aziotsdklinux/+archive/ubuntu/ppa-azureiot/+packages?field.name_filter=&field.status_filter=published&field.series_filter=trusty) (2018-07-24) I can see that you have pretty much the most recent code installed. 

Let me check this further.

**Comment by trillykins** [comment]
Is the SDK supposed to be updated when you do a `apt update` or does it require you do anything more?

**Comment by ewertons** [comment]
On that aspect it behaves entirely like any other apt package, so update is supposed to work.

**Comment by rspielmann** [comment]
> On that aspect it behaves entirely like any other apt package, so update is supposed to work.

Don't forget to run `apt upgrade` afterwards. `apt update` only pulls the latest package database. If you both just made a typo, ignore my comment :) @trillykins @ewertons

**Comment by trillykins** [comment]
@rspielmann  oops, yes, that was supposed to be, `apt upgrade`.

**Comment by ewertons** [comment]
Good catch @rspielmann ! Indeed I meant `apt get upgrade`. Thanks for the comment.

**Comment by ewertons** [comment]
Oh @trillykins, that's a very important piece of information.
You cannot compile the latest code using binaries from a old package release.
If you notice [here](https://packages.ubuntu.com/), Ubuntu 14.04 consumes Trusty packages.
We stopped releasing Trusty packages a while ago, before the latest changes that brought in the modules your linker is complaining about.

So either you:
- Upgrade your OS to the latest version, or
- Clone the Azure IoT SDK repo to an older release (say, from the beginning of 2018).

We do not recommend going back to older versions of the SDK though, you should upgrade your system.

**Comment by trillykins** [comment]
@ewertons I started a new Ubuntu 18.04 OS and cloned my project into it. Followed the [guideline for installing Azure IoT SDK for C on Ubuntu](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/ubuntu_apt-get_sample_setup.md) and now I am getting the following error output:

```
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libprov_auth_client.a(iothub_auth_client.c.o): In function `iothub_device_auth_create':
(.text+0xaa): undefined reference to `hsm_client_http_edge_interface'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libprov_auth_client.a(iothub_security_factory.c.o): In function `iothub_security_init':
(.text+0x24): undefined reference to `initialize_hsm_system'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libprov_auth_client.a(iothub_security_factory.c.o): In function `iothub_security_deinit':
(.text+0x103): undefined reference to `deinitialize_hsm_system'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libprov_auth_client.a(prov_security_factory.c.o): In function `prov_dev_security_init':
(.text+0x24): undefined reference to `initialize_hsm_system'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libprov_auth_client.a(prov_security_factory.c.o): In function `prov_dev_security_deinit':
(.text+0x103): undefined reference to `deinitialize_hsm_system'
collect2: error: ld returned 1 exit status
CMakeFiles/axis_comm.dir/build.make:328: recipe for target 'axis_comm' failed
make[2]: *** [axis_comm] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/axis_comm.dir/all' failed
make[1]: *** [CMakeFiles/axis_comm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by avranju** [comment]
FWIW, here's the list of libraries that finally worked for me:
```cmake
target_link_libraries(iot-sdk-c-app
    iothub_client
    iothub_client_mqtt_transport
    iothub_client_amqp_transport
    iothub_client_http_transport
    parson
    prov_auth_client
    hsm_security_client
    aziotsharedutil
    uamqp
    umqtt
    uhttp
    pthread
    curl
    ssl
    uuid
    crypto
    m
)
```

**Comment by ewertons** [comment]
@trillykins ,
we will close this issue for now, but if you still need help please feel free to reopen it.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@ewertons, @trillykins, @avranju, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
