### ISSUE TITLE
Cannot use AMQP protocol over a basic tier subscription

### ISSUE THREAD

**Issue by pierreca** [Azure/azure-iot-sdk-c#630]
Reference issue: https://github.com/Azure/azure-iot-sdk-python/issues/178

When using AMQP, the C SDK tries to establish twin links immediately after connecting, which creates a problem when connecting to a Basic Tier hub (that only supports telemetry and not twin).

Details are explained [in the original issue](https://github.com/Azure/azure-iot-sdk-python/issues/178).

**Comment by zolvarga** [comment]
We are aware of the behaviour of the C/AMQP stack and added a work item to our backlog.

**Comment by jspaith** [comment]
It appears that c2d messages are also auto-subscribed.

**Comment by gregman-msft** [comment]
Thanks for the feedback. This is currently in our backlog but do not have an ETA for this yet. Please vote on this [User voice ](https://feedback.azure.com/forums/321918-azure-iot/suggestions/38870053-support-amqp-with-c-sdk-connecting-to-basic-subscr) item, which can also be used for tracking our plans.

**Comment by az-iot-builder-01** [comment]
@jspaith, @gregman-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
