### ISSUE TITLE
Azure IoT Hub SDK fails to notify about device twin changes (MQTT)

### ISSUE THREAD

**Issue by Morozov-5F** [Azure/azure-iot-sdk-c#631]
- **OS and version used:** MIPS Linux OpenWrt 3.18.29

- **SDK version used:** IoT Hub SDK for C, version 1.2.3 (2018-04-13), also reproduces on version 1.2.8 (2018-07-11).

# Description of the issue:
I've noticed that sometimes under undefined conditions the following thing happens: Azure SDK doesn't notify the application about device twin update. For example, when a user changes desired properties on the Azure device doesn't receive notification about that although it's online and sends telemetry messages to Azure. 

I've also captured Azure SDK logs and here's what I've found (for better understanding I've marked the most significant lines in the logs with numbers):

1. At first, we can see that Azure SDK subscribes to device twin.
2. Next, we can see that Azure SDK received confirmation for the reported properties update, application logs confirm that too.
3. After the bunch of telemetry messages in Azure SDK logs, we can see that SDK received new desired properties from IoT Hub. There are no entries in the application log for the corresponding event. 
4. After a while, the new telemetry message is being sent. 
5. Again, Azure SDK receives the device twin update but fails to call the Device Twin callback.

Sometimes the device is able to recover from this state, not sure if this is related to SAS token expiration, but this is my assumption. If you need more details I'll try to provide them. 

I didn't see any initial device twin reception. According to SRS_IOTHUBCLIENT_LL_07_015 defined in [requirements](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/devdoc/requirement_docs/iothubclient_ll_requirements.md), Azure SDK won't call Device Twin callback because for some reason it didn't receive Complete Device Twin update. What's the proper fix for that -- is it OK just to remove such logic and process every device twin update?

# Code sample exhibiting the issue:
It's a highly simplified code sample, but all the Azure routines are in place.

- [azure.c](https://gist.github.com/Morozov-5F/916d461921d0f6f9d3f3447de95adb66#file-azure-c)

# Console log of the issue:

- Azure SDK log: [azure_sdk_log.txt](https://gist.github.com/Morozov-5F/916d461921d0f6f9d3f3447de95adb66#file-azure_sdk_log-txt)
- Application log: [application_log.txt](https://gist.github.com/Morozov-5F/916d461921d0f6f9d3f3447de95adb66#file-application_log-txt)

**Comment by jebrando** [comment]
@Morozov-5F I will need to investigate this and let you know how long this will take to fix.

**Comment by jebrando** [comment]
@Morozov-5F I have not been able to reproduce the error on my end.  I have a couple of question.
1. Where does the function IoTHubDeviceClient_LL_DoWork get called I didn't see in the sample where it was being invoked?
2. Is there a certain interval when you send the telemetry message?

I'll keep trying to repro, let me know if you have any ideas on these questions.

**Comment by vladimir-didenko** [comment]
@jebrando Evgeny is on vacation next week so I will answer on your questions.

> Where does the function IoTHubDeviceClient_LL_DoWork get called I didn't see in the sample where it was being invoked?
> Is there a certain interval when you send the telemetry message?

We call following callback once a second
```
static void
s_azure_main_loop(uv_timer_t * handle)
{
   azure_ctx_t * azure_ctx = NULL;
   azure_msg_ctx_t * msg_ctx = NULL;

   int iot_sdk_ret = IOTHUB_CLIENT_OK;

   TRACELN_FNBEGIN();
   ASSERT(NULL != handle);
   azure_ctx = (azure_ctx_t *)handle->data;
   ASSERT(NULL != azure_ctx);

   /* Just a precaution -- this timer would be stopped anyway. */
   if (!azure_enabled(azure_ctx))
   {
      TRACELN_INFO("Ignoring main loop iteration -- Azure is disabled");
      goto done;
   }

   /* Check message queue: maybe we have new messages */
   s_azure_ctx_lock(azure_ctx);
   msg_ctx = IM_RING_BUFFER_PEEK(&azure_ctx->azct_msg_queue);
   s_azure_ctx_unlock(azure_ctx);

   if (msg_ctx != NULL)
   {
      /* We are sending telemetry messages one by one */
      if (!msg_ctx->azmc_sending)
      {
         msg_ctx->azmc_sending = TRUE;
         /* We can add message to Azure IoT SDK internal message queue */

         TRACELN_INFO("TELEMETRY: sending a message to Azure");
         iot_sdk_ret = IoTHubDeviceClient_LL_SendEventAsync(azure_ctx->azct_client,
                                                            msg_ctx->azmc_msg_handle,
                                                            s_azure_send_confirmation_cb,
                                                            azure_ctx);
         ASSERT(IOTHUB_CLIENT_OK == iot_sdk_ret);
      }
   }
   IoTHubDeviceClient_LL_DoWork(azure_ctx->azct_client);

done:
   TRACELN_FNEND();
   return;
}
```

Also you could provide to us patch for SDK that adds additional debug logging and we will try to reproduce this problem on our side (usually we could reproduce it pretty quickly) and provide this debug logs back.

**Comment by jebrando** [comment]
@Morozov-5F 

The first thing I see is that DoWork is only called once.  The DoWork function is the function that call down into the networking layer and send on the socket and then receives any data that has been received by the socket.  By only calling DoWork once it's probably not getting enough cycles to get all the data messages that it needs.

The best way to figure this one out would be for you to turn on tracing in the SDK.  This will spit out all the protocol level messages that are sent from the SDK to the IoTHub.  To turn this on you need to add this line right after the device handle is created and run your test:

```c
bool traceOn = true;
IoTHubDeviceClient_LL_SetOption(azure_ctx->azct_client, OPTION_LOG_TRACE, &traceOn);
```

Hopefully this shows the message from the hub and then we can trace if the message is getting acknowledged

This plus a change to DoWork (calling it in a loop  every 50 - 100 ms will ensure you don't miss any messages or calling a bunch of DoWorks).

**Comment by vladimir-didenko** [comment]
@jebrando 
>The first thing I see is that DoWork is only called once

Why do you think it is called once? As I said before we call s_azure_main_loop() that calls DoWork() every second. Moreover even log for IoT Hub SDK shows some activity during the whole period of time that will not be possible without returning control to SDK via DoWork() call.

**Comment by jebrando** [comment]
@vladimir-didenko how long is the device running before you see this issue?  Does it have to run for hours or initially?

**Comment by vladimir-didenko** [comment]
@jebrando 
> how long is the device running before you see this issue? Does it have to run for hours or initially?

Initially. I don't know if it is important but on device start there is no network for about a 30-60 seconds. When device become online this issue happens.

**Comment by vladimir-didenko** [comment]
> When device become online this issue happens.

Just to clarify. It is not always reproducible. Moreover after upgrading to 1.2.9 and reducing DoWork timeout to 100ms we don't see it anymore though we are not sure that issue has been fixed.

**Comment by jebrando** [comment]
@vladimir-didenko We have done a lot of work around this area to be consolidate and simplify code, but I can not say that we have seen this exact error.  Since I'm working in this area, I will continue to look at this for the next week.  If you see any more errors on this reply on this issue, if not then I shall close.

**Comment by az-iot-builder-01** [comment]
@Morozov-5F, @vladimir-didenko, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
