### ISSUE TITLE
IoT Edge runtime error running Python module

### ISSUE THREAD

**Issue by Bnjmn83** [Azure/azure-iot-sdk-c#633]
My RPI3 runs the iotedge service which in turn runs a module that uses a python module (example code) to communicate with the Hub. But on every startup this error shows up:

```
pi@raspberrypi:~ $ docker logs -f httpserver

Python 2.7.15 (default, Jun 22 2018, 18:43:23)
[GCC 4.9.2]

IoT Hub Client for Python
Error: Time:Mon Sep 10 08:02:07 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:383 Failure: connect failure 111.
Error: Time:Mon Sep 10 08:02:07 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:767 wait_for_connection failed
Error: Time:Mon Sep 10 08:02:07 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:748 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Sep 10 08:02:07 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Mon Sep 10 08:02:07 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Mon Sep 10 08:02:07 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2037 failure connecting to address raspberrypi.
Starting the IoT Hub Python sample using protocol MQTT...
The sample is now waiting for messages and will indefinitely.  Press Ctrl-C to exit.
...
Error: Time:Mon Sep 10 08:02:22 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Mon Sep 10 08:02:22 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Mon Sep 10 08:02:22 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2037 failure connecting to address raspberrypi.

Twin callback called with:
updateStatus = COMPLETE
payload = {"desired":{"TemperatureThreshold":37,"$version":14},"reported":{"$version":1}}
context = <__main__.HubManager object at 0x76ae5f30>
Total calls confirmed: 1
```
The twin callback is called once on startup. Any further changes I make to its twin on the cloud won't invoke the callback of the edge device. Something seems to be broken here.

**edit**: Using an edge deployment where I adjust the properties via the module directly doesn't work either. The Device twin callback gets never triggered. After a container restart the device twin gets updated. This seems broken to me!

- Raspberry PI3
- azure-iothub-device-client==1.4.0

**Comment by jspaith** [comment]
For the startup error logs you're seeing, as I commented from https://github.com/Azure/iotedge/issues/243#.

<
When the docker containers for Edge start up, there's no master orchestration that waits until EdgeHub is 100% ready to accept connections and only then starts client modules.  Both EdgeHub and your Python module start at the same time.  

So those errors you're seeing from Python SDK are expected because the client can start connecting much faster than EdgeHub itself is ready.  The Python SDK retry logic ultimately does connect, as your logs show.
>

The twin issue we'll need to investigate, doesn't ring bells.

**Comment by Bnjmn83** [comment]
Thanks, this makes sense. I restarted the App docker container and I can confirm that the error does not show up again since the EdgeHub is already up and running.

Just to be clear: Whenever I change the device twin remotely e.g. in the Hub a subsequent invocation of the _devin_twin_callback_ is expected to happen right?

**Comment by az-iot-builder-01** [comment]
@Bnjmn83, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
