### ISSUE TITLE
Fail to reconnect

### ISSUE THREAD

**Issue by lucarv** [Azure/azure-iot-sdk-c#636]
Note that i am running on my laptop just to reproduce the error, I have a customer that is running on an embedded Linux platform.
- **OS and version used:** <VERSION> 
Mac OSX High Sierra
- **SDK version used:** <VERSION> 
The latest one as per 12th of September 2018
Compiling with cmake 3.11.4

# Description of the issue:

I downloaded the latest version of the SDK.  
I have modified the iothub_ll_telemetry_sample to loop indefinitely,  firing off messages every 30th second.   

This is the first message trace:
```
Sending message 1 to IoTHub
-> 12:58:22 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: xxxyyyzzz.azure-devices.net/bwt-c-mqtt/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.8%20(Darwin%3b%20x86_64) | PWD: XXXX | CLEAN: 0
<- 12:58:23 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0
The device client is connected to iothub
-> 12:58:23 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/bwt-c-mqtt/messages/events/ | PACKET_ID: 2 | PAYLOAD_LEN: 12
<- 12:58:23 PUBACK | PACKET_ID: 2  
```
Confirmation callback received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_OK
This repeats for 48 minutes perfectly.
```
Sending message 96 to IoTHub
-> 13:45:53 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/bwt-c-mqtt/messages/events/ | PACKET_ID: 97 | PAYLOAD_LEN: 12
<- 13:45:53 PUBACK | PACKET_ID: 96
Confirmation callback received for message 95 with result IOTHUB_CLIENT_CONFIRMATION_OK
Message Delivered
Sleep for 30 seconds
```
Then on the next message this is what happens:
```
Sending message 97 to IoTHub
-> 13:46:24 DISCONNECT
The device client has been disconnected
Message Delivered
Sleep for 30 seconds
---
Sending message 98 to IoTHub
-> 13:46:54 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: xxxyyyzzz.azure-devices.net/bwt-c-mqtt/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.8%20(Darwin%3b%20x86_64) | PWD: XXXX | CLEAN: 0
Message Delivered
Sleep for 30 seconds
---
Sending message 99 to IoTHub
Error: Time:Wed Sep 12 13:47:24 2018 File:/Users/lucarv/source/c/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2110 mqtt_client timed out waiting for CONNACK
Message Delivered
Sleep for 30 seconds
---
```
My interpretation is that the IoT Hub terminates the connection (the default TLL of the token was 60 minutes) after 48 minutes. Next time the client wants to send a message, a CONNECT is sent to IoT Hub, but a CONNACK is never received. No further messages reach the Iot Hub, and the Error message above comes for all messages.

# Code sample exhibiting the issue:

Using the sample as per latest SDK.

# Console log of the issue:

See above.

**Comment by markrad** [comment]
Hi @lucarv,

This may not be related but worth looking at. Since you are sleeping for 30 seconds I'm assuming that you are **not** calling _IoTHubDeviceClient_LL_DoWork_ during that period. This may lead to problems. You should try and call that function at least every 10ms to avoid potential side affects.

_Mark Radbourne MSFT_

**Comment by lucarv** [comment]
@markrad It is unrelated :(

**Comment by Andre-Nascimento-MS** [comment]
Hi @markrad,

Just confirmed offline with @lucarv, the issue seemed to be _sleep()_, which caused the _IoTHubDeviceClient_LL_DoWork_ function to **not** do any work for 30s, thus unexpected behaviour happened later on at 48m.

To send a message every 30s, using the _time()_ function from _time.h_ stdlib worked just fine:
https://en.cppreference.com/w/c/chrono/time

**Comment by markrad** [comment]
If you are using the low level API, those with LL in the name, you must call _IoTHubDeviceClient_LL_DoWork_ much more frequently than every 30 seconds. The high level API will put that task on to a background thread in which case you can pause your main thread for 30 seconds.

_Mark Radbourne MSFT_

**Comment by az-iot-builder-01** [comment]
@lucarv, @Andre-Nascimento-MS, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
