### ISSUE TITLE
Does azure-iot-sdk-c supports connecting through transparent HTTP proxy?

### ISSUE THREAD

**Issue by mohamedibrahimabdelrahman33** [Azure/azure-iot-sdk-c#637]
Running on STM32F7 Platform.

- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 
1.2.8

# Description of the issue:

currently i'm sending messages using (MQTT over WebSocket) through an explicit HTTP proxy and i did that by setting Proxy configurations like ( proxy_host, proxy_port, proxy_username, proxy_password ).
but now i need to connect to the Hub through transparent proxy, and in this case i don't now the proxy_host or the proxy_port due to the nature of the transparent proxy.

so i need to ask if there a solution for my case, Does azure-iot-sdk-c supports connecting through transparent HTTP proxy?

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by jspaith** [comment]
My understanding with a transparent proxy is that it will either (A) be running someplace on the network - like a router - where the client SDK or even OS would not not it was there.  Or (B), it would involve needed to change the OS's IP routing table such that outgoing messages went to the specific proxy.

In both cases (A) & (B), the SDK isn't really involved in the network topology or IP routing.  We don't have any specific SDK options to configure this.

Your scenario though maybe (C), which I don't have my head around.  If you could explain what you're trying to do a bit more that may help us provide a better answer here.

**Comment by jspaith** [comment]
Closing since this thread has been quiet for a while.  If you have further questions on this and can help educate me more about the specific scenario, by all means re-activate the thread or create a new issue.  Thanks.

**Comment by az-iot-builder-01** [comment]
@mohamedibrahimabdelrahman33, @jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
