### ISSUE TITLE
HSM auth with Module identity

### ISSUE THREAD

**Issue by pocokurfi** [Azure/azure-iot-sdk-c#638]
- **OS and version used:** <VERSION> 
Linux
- **SDK version used:** <VERSION> 
2018-09-11

# Description of the issue:
Is it possible to use provisioned HSM based authentication with Modules?

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by jebrando** [comment]
@p-nagpal Currently due to technical difficulties modules does not have this functionality.

**Comment by az-iot-builder-01** [comment]
@pocokurfi, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by tameraw** [comment]
@p-nagpal - Clarifying that this is not supported on the service side as of yet.
