### ISSUE TITLE
Comment incorrect

### ISSUE THREAD

**Issue by Arty29** [Azure/azure-iot-sdk-c#639]
https://github.com/Azure/azure-iot-sdk-c/blob/575b739f2dd39cea5f722ae0e7fd9a9064e0ec14/iothub_client/src/iothubtransport_mqtt_common.c#L1643

Should read "// The subscribe packet has been acked"

**Comment by jebrando** [comment]
Thank you for the update.  Will be check in this weekend

**Comment by az-iot-builder-01** [comment]
@Arty29, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
