### ISSUE TITLE
Memory loss in case SDK is started with no Internet Connection

### ISSUE THREAD

**Issue by mm-mhr** [Azure/azure-iot-sdk-c#64]
This is a follow up to issue #55 which was closed.

I did a regression test (I cloned master c861ec3f26a7ff4debedf6dbb916072cec1be768 from 2017-02-09) and there is still a memory loss reported by valgrind and observable in /proc in case the SDK is started with no internet connection.
Looks like one of the two reported leaks is fixed, but the second one is still there.
I don't know how to reopen an issue so I decided to create a new one.

The attached sample can be used to reproduce by either making sure that the thing is not connected or by providing a connection string for a non existing url.

Here is valgrind output:

65,832 (4,848 direct, 60,984 indirect) bytes in 6 blocks are definitely lost in loss record 86 of 86
  in create_openssl_instance in /home/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:870
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: CRYPTO_malloc in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
  3: SSL_new in /lib/x86_64-linux-gnu/libssl.so.1.0.0
  4: create_openssl_instance in /home/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:870
  5: tlsio_openssl_open in /home/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1045
  6: xio_open in /home/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:87
  7: mqtt_client_connect in /home/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:891
  8: SendMqttConnectMsg in /home/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1596
  9: InitializeConnection in /home/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1637
  10: IoTHubTransport_MQTT_Common_DoWork in /home/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2371
  11: IoTHubTransportMqtt_DoWork in /home/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  12: IoTHubClient_LL_DoWork in /home/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  13: ScheduleWork_Thread in /home/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client.c:438
  14: ThreadWrapper in /home/mm/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/adapters/threadapi_pthreads.c:34
  15: start_thread in /build/eglibc-3GlaMS/eglibc-2.19/nptl/pthread_create.c:312
  16: clone in /build/eglibc-3GlaMS/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111

[test.zip](https://github.com/Azure/azure-iot-sdk-c/files/746126/test.zip)

I'd appreciate if you could have a look at this again.

**Comment by mm-ark** [comment]
Hey @evertons,

I checked commit 577bb8c4fa93180abc8f4f9ae0abf97f66768105 (release 2017-03-10). It looks good for valgrind: no complains anymore for this test case :-)
Currently i am also running tests on target devices for some days. We will report or close this issue dependent on result.
