### ISSUE TITLE
not able to install azure-iot-sdk-c

### ISSUE THREAD

**Issue by nagarathna321** [Azure/azure-iot-sdk-c#641]
HI I am trieng to install the azure-iot-sdk-c in esp-idf I am getting the error while installing ,
i perfer bellow link to install
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#linux.

this is a error I am getting while instaling
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IoT Client SDK Version = 1.2.9
-- Provisioning client OFF
CMake Error at dependencies.cmake:22 (add_subdirectory):
  The source directory

    /home/zlt-b26/esp/esp-idf/components/azure-iot-sdk-c/c-utility

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:205 (include)

CMake Error at dependencies.cmake:25 (add_subdirectory):
  The source directory

    /home/zlt-b26/esp/esp-idf/components/azure-iot-sdk-c/uamqp

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:205 (include)

CMake Error at dependencies.cmake:29 (add_subdirectory):
  The source directory

    /home/zlt-b26/esp/esp-idf/components/azure-iot-sdk-c/umqtt

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:205 (include)

CMake Error at dependencies.cmake:33 (add_subdirectory):
  The source directory

    /home/zlt-b26/esp/esp-idf/components/azure-iot-sdk-c/deps/uhttp

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:205 (include)

CMake Warning (dev) at dependencies.cmake:40 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target "aziotsharedutil".
Call Stack (most recent call first):
  CMakeLists.txt:205 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:212 (set_platform_files):
  Unknown CMake command "set_platform_files".

-- Configuring incomplete, errors occurred!
See also "/home/zlt-b26/esp/esp-idf/components/azure-iot-sdk-c/cmake/CMakeFiles/CMakeOutput.log".

**Comment by az-iot-builder-01** [comment]
@nagarathna321, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by nagarathna321** [comment]
I solved issue

**Comment by teransantiago** [comment]
how did you solved????

**Comment by teransantiago** [comment]
how did you solve????

**Comment by nagarathna321** [comment]
Make saparete folder of azure and add path in script in your project and try

**Comment by kgalic** [comment]
@nagarathna321 Can you please clarify a bit more the steps you did?

**Comment by dhmuech** [comment]
I solved the problem based on the docs:
[Quickstart: Provision a simulated symmetric key device](https://learn.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-symm-key?pivots=programming-language-ansi-c#prerequisites)

```
cd azure-iot-sdk-c
git submodule update --init
```
