### ISSUE TITLE
IoT SDK on Azure Sphere: IoTHubClient_LL_DoWork() blocks for 5 seconds the execution while wifi nic is down

### ISSUE THREAD

**Issue by richardtaylorrt** [Azure/azure-iot-sdk-c#643]
- **OS and version used:** [Azure Sphere OS](https://docs.microsoft.com/en-us/azure-sphere/product-overview/what-is) 

- **SDK version used:** SDK version bundled with Azure Sphere OS  

# Description of the issue:

Scenario: 

Note: porting this issue from [here](https://feedback.azure.com/forums/321918-azure-iot/suggestions/33647845-iothubclient-ll-dowork-blocks-for-5-seconds-the).

- Run [the Azure IoT sample application for Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/app-development/azure-iot-sample).
- Disable wifi on the Azure Sphere device so it loses internet connectivity: `azsphere device wifi disable -i 0`
- Observe the IoTHubClient_LL_DoWork() call blocks execution for 5 seconds each time is being called.

# Code sample exhibiting the issue:

See the sample code produced by following the steps in the link above.

# Console log of the issue:

Looks like the getaddinfo() underlying call is blocking, this is in the log traces each five seconds indeed:

/git/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:627 Failure: getaddrinfo failure -3.

**Comment by massand** [comment]
@richardtaylorrt It appears the name resolution step is temporarily failing during socketio_open operation, which is really OS dependent behavior. It could take upto 5 seconds in theory and getaddrinfo is a blocking call. Is there anything you expected the SDK to not cause this behavior?

**Comment by richardtaylorrt** [comment]
Hi - as discussed offline, I think this actually becomes a feature request.  We'd like the SDK to support the option of using the [c-ares](https://c-ares.haxx.se/) library for asynchronous DNS requests.

**Comment by angelobt** [comment]
Hi,
Any news about this issue ?
If the network has no internet connection, "IoTHubClient_LL_DoWork" blocks for about 30 seconds.

<elt> [15:51:07,266]	->>>>>>>>>>>>>>>>>>>> before

IoTHubClient_LL_DoWork

<elt> [15:51:35,382]	UNAUTHENTICATED
<elt> [15:51:35,386]	NO_NETWORK
<elt> [15:51:35,390]	->>>>>>>>>>>>>>>>>>>> after

The connection type is MQTT.
I have tried setting "connect_timeout" option, but with no luck.

Thanks in advance

**Comment by massand** [comment]
@angelobt Could you provide the OS and SDK version details for your issue? The original issue pertains to Azure Sphere that runs on a custom Linux distro. The DNS lookup is a blocking call in that case.

**Comment by angelobt** [comment]
**OS**: linux built with Yocto sumo
**SDK**: built with yocto starting from azure-iot-sdk-c_1.2.4.bb recipe (meta-iot-cloud layer)

Seems that also in this case the DNS lookup is blocking.

(gitsm://github.com/Azure/azure-iot-sdk-c.git commit: ad28b943aceea95df07d27d97206c987ebdd86f8)

**Comment by angelobt** [comment]
Hi,
Have you already planned to add c-ares support ? If yes, do you have a timeline ?
If not, I could try to work some time on it.
Is there someone that can point me out where to act and tell me the best way to modify the sdk ? The aim is to produce a patch that can be maintained in the future.

Thanks in advance for any help.

**Comment by massand** [comment]
@angelobt - There are two paths we can go down to resolve this issue - 
1) add a PAL API to support asynchronous DNS API via c-ares, which would help preserve our current transport logic
2) modify queue logic in our transport layer whereby we bump (re)connection request priority above other requests

Option 1 requires some dependency management, whereby we submodule and build the c-ares static library (similar to how we deal with parson). This needs to be called in from a PAL interface, which will be utilized instead of getaddrinfo() call. We already have an interface for async_dns under the c-shared-utility library - https://github.com/Azure/azure-c-shared-utility/blob/master/pal/dns_async.c. So, we might tie c-ares into that interface. 

Option 2 requires some major rework to our transport layer, which currently doesn't prioritize connection requests (when disconnected) over message send requests. This approach needs to be designed up as an alternative. We will post a design on this next week and see what works better.

**Comment by massand** [comment]
I am working on the spike with c-ares (option 1) at the moment, and hopefully have a PR within the next week. 

For MQTT, I am also trying to locally compile curl with —enable-ares configure option to see if it works with our current transport pipeline. Here is the way to do it locally in case you haven’t tried it - https://stackoverflow.com/questions/14466130/how-do-i-install-curl-with-ares-enabled

**Comment by angelobt** [comment]
Hi,

also using MQTT seems that socket_io is required:

Error: Time:Tue Feb 12 08:13:29 2019 File:/usr/src/debug/azure-c-shared-utility/1.1.4-r0/git/adapters/socketio_berkeley.c Func:socketio_open Line:632 Failure: getaddrinfo failure -5.
Error: Time:Tue Feb 12 08:13:29 2019 File:/usr/src/debug/azure-c-shared-utility/1.1.4-r0/git/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:725 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Feb 12 08:13:29 2019 File:/usr/src/debug/azure-c-shared-utility/1.1.4-r0/git/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1209 Failed opening the underlying I/O.
Error: Time:Tue Feb 12 08:13:29 2019 File:/usr/src/debug/azure-umqtt-c/1.1.4-r0/git/src/mqtt_client.c Func:mqtt_client_connect Line:981 Error: io_open failed
Error: Time:Tue Feb 12 08:13:29 2019 File:/usr/src/debug/azure-iot-sdk-c/1.2.4-r0/git/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1893 failure connecting to address eliot-iotHub-pp.azure-devices.net.

The question is: when the c-ares implementation will be completed, do I have also to compile curl with async dns ?

thanks in advance,
Angelo

**Comment by angelobt** [comment]
Hi,
I have compiled curl with c-ares, but I have the same behavior.

**Comment by massand** [comment]
@angelobt Apologies - I meant building curl with c-ares support for HTTP protocol. However, for MQTT, the only place we can support c-ares is within socket_io (as you correctly indicated). Good news is I completed my [spike for c-ares support in socket_io](https://github.com/massand/azure-c-shared-utility/commit/5d7bfd4378c56678c4ce035205479b7e4c65b8ee) last week and it worked with MQTT, MQTT_WS, AMQP and AMQP_WS transports. I am in the process of wrapping the core c-ares logic within dns_async and figuring out cmake changes very soon. Thanks for your patience.

**Comment by massand** [comment]
Please add your feedback for the socket_io and dns_resolver changes on the PR here - https://github.com/Azure/azure-c-shared-utility/pull/279

**Comment by massand** [comment]
This issue is not yet resolved because the SDK team is not taking PRs related to DNS yet. The primary reason is that the c-ares lib does not handle DNS-SD. Other packages / alternatives are being discussed at the moment. But, this change will not make the cut for another month.

**Comment by gregman-msft** [comment]
This PR was merged into master and will be in the next release.

**Comment by az-iot-builder-01** [comment]
@massand, @richardtaylorrt, @angelobt, @gregman-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
