### ISSUE TITLE
Question about using DONT_USE_UPLOADTOBLOB

### ISSUE THREAD

**Issue by jflynn129** [Azure/azure-iot-sdk-c#645]
I am building using gcc and I'm trying to exclude blob upload to blob capability. Per the documents at https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-develop-for-constrained-devices I am throwing the "-DDONT_USE_UPLOADTOBLOB" command line switch but when I do, I get an error:
**iothub_client/iothub_client_ll_uploadtoblob.c:5:2: error: #error "trying to compile iothub_client_ll_uploadtoblob.c while the symbol DONT_USE_UPLOADTOBLOB is #define'd"!**

can you explain this error and how to avoid it.  Specifically, are there some files that should be excluded from the compile when this switch is present?

- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by jebrando** [comment]
@jflynn129 The cmake flags are case sensitive.  Your cmake command needs to look like this:

```
cmake -Ddont_use_uploadtoblob=ON ..\..
```
with it all in lower case.  The uppercase version is used in the code which turns off the #define, but cmake will still add the file in the project.

**Comment by az-iot-builder-01** [comment]
@jflynn129, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by jflynn129** [comment]
Yea, I wasn't asking a question about **CMAKE**.  I dug into it myself and **to disable blob upload**, you need to make sure:
1. throw the flag **-DDONT_USE_UPLOADTOBLOB** during compile
2. do not compile the files:

- **iothub_client/blob.c**

- **iothub_client/iothub_client_ll_uploadtoblob.c**

this appears to successfully remove upload to blob capability.

**Comment by massand** [comment]
#697 has addressed building the code directly using gcc on a flat folder structure (which I suspect you did). Generally speaking, we fully support the cmake workflow for building C SDK because it generates appropriate project files for a variety of compilers and it helps us easily reproduce issues on our end. Thanks @jflynn129 for reporting this! Thanks @jebrando for addressing the cmake version of the same issue :)
