### ISSUE TITLE
Difference between PROV_DEVICE_RESULT_OK and  PROV_DEVICE_RESULT_SUCCESS

### ISSUE THREAD

**Issue by truschival** [Azure/azure-iot-sdk-c#646]
Is there any difference between  `PROV_DEVICE_RESULT_OK` and  `PROV_DEVICE_RESULT_SUCCESS` in the `PROV_DEVICE_RESULT` of `PROV_DEVICE_CLIENT_REGISTER_DEVICE_CALLBACK`?

The macro is defined in: [prov_device_ll_client.h](https://github.com/Azure/azure-iot-sdk-c/blob/2d67c86e939bee1395751e7891189985654aa1fa/provisioning_client/inc/azure_prov_client/prov_device_ll_client.h#L20)

grepping the sdk I couldn't find any usage of  `PROV_DEVICE_RESULT_SUCCESS` ....

**Comment by jebrando** [comment]
@truschival The PROV_DEVICE_RESULT_SUCCESS is an oversight that I can't removed due to backwards comparability.  I will document that it is not used and unfortunately I will have to live with it.

**Comment by az-iot-builder-01** [comment]
@truschival, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
