### ISSUE TITLE
Unusual CPU utilization in iothub_client sample

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#648]
- **OS and version used:** Ubuntu 18.04. macOS 10.13.4
- **SDK version used:** 1.2.9 (master)
**Processor**: Core i5.

# Description of the issue:
I ran the iothub_client_device_twin_and_methods_sample in iothub_client/sample directory with _MQTT_WebSocket_Protocol_ (feels this issue is irrespective of transport protocol used). Sample works. But CPU utilization (_top -p_) is varying between 2 to 7% on both computers. To reduce this, am I expected to use _LL_ APIs with lesser duration of _DoWork. Say 100ms? But even then, for an SDK to be used in low end devices, I feel this is unsual. 

# Code sample exhibiting the issue:
iothub_client_device_twin_and_methods_sample[[1](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_device_twin_and_methods_sample)] in iothub_client/samples.

# Libs/Build for Ubuntu 18.04:
```
curl - 7.58.0
openssl - 1.1.0g
apt-get install  azure-iot-sdk-c-dev
cc  iothub_client_device_twin_and_methods_sample.c -I /usr/include/azureiot -I /usr/include/azureiot/inc -liothub_client -liothub_client_mqtt_ws_transport -laziotsharedutil  -lprov_auth_client -lhsm_security_client -lumqtt -luhttp -lparson -lssl -lcrypto -lpthread -lcurl -lm -luuid -I /home/roots/src/parson
```

**Comment by bikamani** [comment]
@kiranpradeep I will investigate this and get back.

**Comment by jebrando** [comment]
@kiranpradeep for low end device we would expect a client to use the LL layer.  This would give them greater control on the networking layer and allow greater flexibility.  Looking at the convenience layer when I run an sample application that send a message every 5 seconds in a loop on my ubuntu 18.04 laptop the % CPU that is used never goes over 1 (see attached image).
![sdk_cpu_sample_app](https://user-images.githubusercontent.com/8583083/48096947-760e6400-e1cd-11e8-90f4-b8b7d09478ca.png).  Did you see this behavior on a mac or ubuntu device?

**Comment by jebrando** [comment]
@kiranpradeep we have added a OPTION_DO_WORK_FREQUENCY_IN_MS option that enable you to set the amount of sleep time in the do work thread.

**Comment by az-iot-builder-01** [comment]
@bikamani, @jebrando, @kiranpradeep, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
