### ISSUE TITLE
release 2018-09-11 submodules directories are empty

### ISSUE THREAD

**Issue by MZDN** [Azure/azure-iot-sdk-c#649]
![image](https://user-images.githubusercontent.com/16664882/45958582-1b072000-c018-11e8-805d-5430ab77bc9e.png)

**Comment by MZDN** [comment]
please make sure to clone with option --recursive before uploading it

**Comment by massand** [comment]
Hello @MZDN! For each submodule you specified above, there are tarballs generated in their corresponding Github repositories. You should reach out to those Github repositories for tarballs that corresponds to the desired C SDK release. Github generates release tarballs with source code from the released repository only (not submodules). This has been the case for all our C SDK releases. 

Thanks for your query.

**Comment by az-iot-builder-01** [comment]
@MZDN, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
