### ISSUE TITLE
[parson] Undefined behavoiur sanitizer runtime errors

### ISSUE THREAD

**Issue by mm-imr** [Azure/azure-iot-sdk-c#65]
Hi there,

I'm on c861ec3f26a7ff4debedf6dbb916072cec1be768 and switched on the undefined behaviour sanitizer on clang. That gives me two runtime errors according to parson.

1) c/parson/parson.c:388:24: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'size_t' (aka 'unsigned long')
    #0 0x42bc0c in json_object_free c/parson/parson.c:388

2) c/parson/parson.c:443:24: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'size_t' (aka 'unsigned long')
    #0 0x42c209 in json_array_free /c/parson/parson.c:443

Best Regards,

Ingo

**Comment by anporumb** [comment]
Hello @mm-imr,

We are just using parson, parson is here: https://github.com/kgabis/parson

I believe this should be a parson issue. Let me know if you agree.

Best Regards,
Andrei Porumb

**Comment by IngoMaindorfer** [comment]
Hi Andrei,

please tell me which Parson hash you currently use and I'll post it over there.

Best,

Ingo

**Comment by anporumb** [comment]
We are @ dcf85b8.

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Hello @IngoMaindorfer ,

Do you have any updates on this issue? Thank you.

Best Regards,
Andrei Porumb

**Comment by mm-imr** [comment]
Hello @Andrei,

I've posted it here https://github.com/kgabis/parson/issues/72.

Best,

Ingo

**Comment by mm-imr** [comment]
Hello @Andrei,

they fixed it over there. So please pull newest PARSON lib and after that please close this issue.

Best,

Ingo

**Comment by anporumb** [comment]
Hello @mm-imr ,

Much apreciated! I will do that as soon as possible.

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Hello @mm-imr ,

I have checked in master branch parson @ ba2a854c27b24068977e5827bd129d0531f4503c, which is the lastest revision.

Best Regards,
Andrei Porumb
