### ISSUE TITLE
segmentation fault on Azure SDK - name conflicts (device_create/device_destroy)

### ISSUE THREAD

**Issue by syedelec** [Azure/azure-iot-sdk-c#651]
- **OS and version used:** <VERSION> 
Ubuntu 18.04

- **SDK version used:** <VERSION> 
master

# Description of the issue:

I simplified a sample of iothub_client to a simple Azure SDK call and added calls to function `device_create` which produces a Segmentation Fault. 

In the code, I am not calling the function, however it seems that it's called internally since I have the output : `inside device_create`

# Code sample exhibiting the issue:

```
#include <stdio.h>

#include <azureiot/iothub_client.h>
#include <azure_c_shared_utility/platform.h>
#include <azureiot/iothubtransportamqp_websockets.h>

void device_create(void);

void device_create(void) {
    printf("inside device_create\n");
}

int main(void)
{
    IOTHUB_CLIENT_HANDLE handle;
    const char *connection_string = "[connection_string]";

    platform_init();

    if ( (handle = IoTHubClient_CreateFromConnectionString(connection_string, AMQP_Protocol_over_WebSocketsTls)) != NULL )
    {
        printf("iot client handle worked\n");
    }
    else
    {
        printf("ERROR: handle is NULL!\r\n");
    }

    platform_deinit();
    return 0;
}
```

# Console log of the issue:

```
inside device_create
Segmentation fault (core dumped)
```

**Comment by jebrando** [comment]
@syedelec We have a poorly named function in the SDK, we will look to change to something a little more descriptive.  If you are using c you should/could have the static keyword in front of the function to decrease the change of name collisions.

```C
static void device_create(void) {
    printf("inside device_create\n");
}
```

**Comment by syedelec** [comment]
@jebrando Thank you, however this is a simple reproducible program to show the issue. In our case, we cannot consider using `static` functions because our functions are called across a larger project.

**Comment by YoDaMa** [comment]
The PR #925 addresses this, so I’m going to go ahead and close this issue.

**Comment by az-iot-builder-01** [comment]
@jebrando, @syedelec, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
