### ISSUE TITLE
using invalid HTTP_PROXY_IO_CONFIG

### ISSUE THREAD

**Issue by OznOg** [Azure/azure-iot-sdk-c#655]
at this point https://github.com/Azure/azure-iot-sdk-c/blob/1.2.9/provisioning_client/src/prov_transport_http_client.c#L540
the code takes the address of a structure allocated on the stack just before exiting the block (releasing the data)
This leads to undefined behaviour (and especially crashes)
running tag 1.2.9 on fedora 28

**Comment by OznOg** [comment]
pleased to hear that :)

**Comment by az-iot-builder-01** [comment]
@OznOg, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by OznOg** [comment]
could you give me the patch that fixed the bug?

**Comment by bikamani** [comment]
@OznOg Here's the commit added to master - https://github.com/Azure/azure-iot-sdk-c/commit/835c8752196a8c7246e190d0348cfc391270d07c

**Comment by OznOg** [comment]
tank you
