### ISSUE TITLE
./iothub_ll_telemetry_sample  / azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:632 Failure: getaddrinfo failure -5.

### ISSUE THREAD

**Issue by chinnaece** [Azure/azure-iot-sdk-c#658]
Same application is run on linux successfully , when i cross  compliled for ARM it's showing below erroe in my machine (AM 5728 EVM) please help me .

root@am57xx-evm:~# ./iothub_ll_telemetry_sample 
Creating IoTHub handle
Sending message 1 to IoTHub
Error: Time:Tue Oct  9 13:16:15 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:632 Failure: getaddrinfo failure -5.
Error: Time:Tue Oct  9 13:16:15 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:725 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Oct  9 13:16:15 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1209 Failed opening the underlying I/O.
Error: Time:Tue Oct  9 13:16:15 2018 File:/home/kdasari/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:981 Error: io_open failed
Error: Time:Tue Oct  9 13:16:15 2018 File:/home/kdasari/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1893 failure connecting to address IH-Embedded-COE.azure-devices.net.
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
Error: Time:Tue Oct  9 13:16:16 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:632 Failure: getaddrinfo failure -5.
Error: Time:Tue Oct  9 13:16:16 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:725 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.

**Comment by massand** [comment]
@chinnaece Thanks for reporting this. Can you resolve any DNS addresses and access the internet on this device? If not, the message sends to IoThub will fail. This is likely the issue you are experiencing on your ARM system, judging by the platform's getaddrinfo -5 failure. 
A quick search revealed some troubleshooting tips on Ti's support site [here](http://e2e.ti.com/support/processors/f/791/t/701598?AM5728-Ethernet-issue).

**Comment by chinnaece** [comment]
I did flash a new image on EVM  , it's connecting network through ethernet 

**here is my ifconfig result**: 

eth1      Link encap:Ethernet  HWaddr A4:D5:78:D6:C2:E5  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1%763612/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:224 errors:0 dropped:0 overruns:0 frame:0
          TX packets:224 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:23735 (23.1 KiB)  TX bytes:23735 (23.1 KiB)

wlan0     Link encap:Ethernet  HWaddr 84:DD:20:98:65:19  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
Now i got  a new error as shown below 

root@am57xx-evm:~# ./iothub_ll_telemetry_sample 
./iothub_ll_telemetry_sample: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory


Please help on this .

**Comment by az-iot-builder-01** [comment]
@chinnaece, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by chinnaece** [comment]
> I did flash a new image on EVM , it's connecting network through ethernet
> 
> **here is my ifconfig result**:
> 
> eth1 Link encap:Ethernet HWaddr A4:D5:78:D6:C2:E5
> UP BROADCAST MULTICAST MTU:1500 Metric:1
> RX packets:0 errors:0 dropped:0 overruns:0 frame:0
> TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
> collisions:0 txqueuelen:1000
> RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)
> 
> lo Link encap:Local Loopback
> inet addr:127.0.0.1 Mask:255.0.0.0
> inet6 addr: ::1%763612/128 Scope:Host
> UP LOOPBACK RUNNING MTU:65536 Metric:1
> RX packets:224 errors:0 dropped:0 overruns:0 frame:0
> TX packets:224 errors:0 dropped:0 overruns:0 carrier:0
> collisions:0 txqueuelen:1000
> RX bytes:23735 (23.1 KiB) TX bytes:23735 (23.1 KiB)
> 
> wlan0 Link encap:Ethernet HWaddr 84:DD:20:98:65:19
> UP BROADCAST MULTICAST MTU:1500 Metric:1
> RX packets:0 errors:0 dropped:0 overruns:0 frame:0
> TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
> collisions:0 txqueuelen:1000
> RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)
> 
> **Now i got a new error as shown below**
> 
> root@am57xx-evm:~# ./iothub_ll_telemetry_sample
> ./iothub_ll_telemetry_sample: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
> 
> Please help on this .

i Copied libssl.so.1.0.0 , libcypto.so.1.0.0 from ti-sdk /linuxdevkit/sysroots/usr/lib to my target usr/lib , then it's working fine .
