### ISSUE TITLE
Timeout when sending message with IoTHubDeviceClient_LL_SendEventAsync()

### ISSUE THREAD

**Issue by shaoshanfan** [Azure/azure-iot-sdk-c#659]
I am developing IoT application using Azure Sphere.

In my app, I need to send one IoTHub message every 1 minutes and the message size is about 13k. I am using Azure IoT C SDK and using mqtt as transport layer protocol.

Most of the time, message send successfully, but occasionally, it the callback indicate message sent timeout with result IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT.

According to document, it mentioned unless I call IoTHubClient_SetOption() to set "messageTimeout" option, it default to disable which means never expired. In my code, I never set this option but why I still get timeout?

Is there anyway to find out why it's timeout and how to avoid this?

Shaoshan

- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by shaoshanfan** [comment]
@Andre-Nascimento-MSFT. For IoTHubDeviceClient_LL_DoWork() may not be called exactly every 100ms, there are some peek and valley time. My app logic is like below

while(true) {
    if ((now() - last) >= 1 min) {
         last = now()
         collect_data()
         IoTHubDeviceClient_LL_SendEventAsync()
   }
   IoTHubDeviceClient_LL_DoWork()
}

Collect_data() sometime can take few seconds. After invoke ...SendEventAsync(), it will have around 1 minutes to invoke IoTHubDeviceClient_LL_DoWork() multiple times.

**Comment by jebrando** [comment]
@shaoshanfan Can you point me to the documentation that states the messages don't timeout unless the setoption is called.  I believe this is stated incorrectly and would like to point it out to the appropriate people.  With MQTT a message will attempt to be send again after 1 min from failure.  After that the message will timeout 1 mins if it was unsuccessful at being received by the IoTHub.

**Comment by shaoshanfan** [comment]
It been mentioned at
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/connection_and_messaging_reliability.md#current-configuration-options

I noticed there are some explanation at https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/connection_and_messaging_reliability.md#known-issue-duplicated-timeout-control-for-sending-telemetry-messages regarding duplicate timeout control, one for "waiting to send" and one for "in progress". Seems the "messageTimeout" option is for "waiting to send" which is deprecated, I don't see any option for "in progress" timeout control.

**Comment by jebrando** [comment]
@shaoshanfan We've change the documentation to better detail exactly what happens and how to tweek the time for your benefit.  As with most documentation we are forever expanding and trying to make it better.  If you have any more issues please open a new item.

**Comment by az-iot-builder-01** [comment]
@shaoshanfan, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
