### ISSUE TITLE
compiler warnings

### ISSUE THREAD

**Issue by mm-imr** [Azure/azure-iot-sdk-c#66]
Hi there,

I'm on c861ec3f26a7ff4debedf6dbb916072cec1be768 and compiling with my own makefile which turned on -Wall which gives roughly 100 warnings. Our coding guideline requires -Wall and that there are no warning et all.  Some are more cosmetically but some are more serious ones like forgotten enums in a switch e.g.
Please give your code base a review with some modern compiler like clang 3.9 and turned on all warnings.

Best Regards,

Ingo

**Comment by anporumb** [comment]
Hello @mm-imr ,

Thanks for submitting the issue. This is very unlikely to make it to the top priority list, so the best course of action would be to either submit a PR or not enable -Wall for our projects. 

Best Regards,
Andrei Porumb
