### ISSUE TITLE
git clone issue, cr/lf - on 32bit linux

### ISSUE THREAD

**Issue by uei-fork** [Azure/azure-iot-sdk-c#663]
I have some build automation, where I spin up VMs and run builds, I am having trouble with his package.

Machines:

Fresh machines UBUNTU 16 (i686 - 32 bit machine) machine - 
And Fresh Ubuntu18 (x86_64) 
Just install from the CD (ISO) using virtual box.

Then type: "sudo apt-get install git"  (not present by default)

On both machines execute the commands:

```
GIT_HASH=eccfda0b7cbb16b37e03e4c1ff2f1ebce6dac12d
git clone --recursive https://github.com/Azure/azure-iot-sdk-c.git repo
cd repo
git submodule init
git checkout ${GIT_HASH}
git submodule update
```

**EXPECTED**:  Above works on Ubuntu 18 (x86_64)

**PROBLEM**: Above FAILS on Ubuntu 16 (i686) - 

Complains that the file:  iothub_service_client/tests/iothub_rm_ut/iothub_rm_ut.c

Has local modifications (specifically CR/LF issues)

This is a corner of Git that I'm not that good with
I think, I'm not sure - that this is an issue in the REPO i self - because the error occurs during clone step.

Error is like this:
```
Cloning into 'deps/ctest'...
Submodule path 'umqtt/deps/c-utility/testtools/umock-c/deps/ctest': checked out 'ee4e06f0a5827a98417f389e013122decc1a3765'
Cloning into 'deps/testrunner'...
Submodule path 'umqtt/deps/c-utility/testtools/umock-c/deps/testrunner': checked out 'c52b67126e10a2697b6d069e2b3f38b4d4229a42'
error: Your local changes to the following files would be overwritten by checkout:
	iothub_service_client/tests/iothub_rm_ut/iothub_rm_ut.c
Please, commit your changes or stash them before you can switch branches.
Aborting
```

**Comment by AndWass** [comment]
Same issue here, saw it the first time yesterday

**Comment by uei-fork** [comment]
@dcristoloveanu - Belief this issue is caused by your recent commit on Oct 10.

**Comment by jebrando** [comment]
@uei-fork I will fix this and let you know when it's in.

**Comment by jebrando** [comment]
@uei-fork the crlf have been removed from the file.  If you have any more issues, let me know.

**Comment by az-iot-builder-01** [comment]
@AndWass, @uei-fork, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
