### ISSUE TITLE
Media file upload using azure

### ISSUE THREAD

**Issue by arulraj17993** [Azure/azure-iot-sdk-c#665]
Is it possible to upload video files of 50-100MB (even more) using azure-iot-sdk c? 
Can I follow the same procedure which was used to upload the image files?

Thanks.

_Originally posted by @arulraj17993 in https://github.com/Azure/azure-iot-sdk-c/issues/520#issuecomment-425883452_

**Comment by jebrando** [comment]
@arulraj17993 Are you using upload to blob to upload the images or something else.

**Comment by arulraj17993** [comment]
@jebrando 
I am trying to use upload to blob to upload recorded video files.
If possible, can I get sample c source files to achieve the same?

**Comment by jebrando** [comment]
@arulraj17993 We have an sample that uploads the data in blocks [upload blocks sample](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_upload_to_blob_mb/iothub_client_sample_upload_to_blob_mb.c).  This give you the ability to send data in chunks to enable sending large amounts of data.  Let me know if this is not what you're looking for.

**Comment by arulraj17993** [comment]
@jebrando 
Thanks for the sample. I could able to upload the image files of KB size successfully. But when trying to upload the video file of size 4.2MB it throws the following error,

**Error: Time:Mon Oct 29 12:33:11 2018 File:/home/koil/Projects/Walmart/src/arm/azure-iot-sdk-c/iothub_client/src/blob.c Func:Blob_UploadMultiple
BlocksFromSasUri Line:249 tried to upload block of size 4432016, max allowed size is 4194304
Error: Time:Mon Oct 29 12:33:11 2018 File:/home/koil/Projects/Walmart/src/arm/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c
 Func:IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl Line:995 unable to Blob_UploadFromSasUri
Received unexpected result FILE_UPLOAD_ERROR**

It seems I am trying to upload more than allowed block size. Is there any sample code to manage large file transfer?

Thanks

**Comment by jebrando** [comment]
@arulraj17993 This is a bug in the SDK, I shall look to get these removed.

**Comment by danewalton** [comment]
This is likely because a compiled and used version of openssl with the `--without-ssl` option. The logs will be output if it can't set the trusted cert option. For safety reasons we will keep the log message in master.

**Comment by az-iot-builder-01** [comment]
@jebrando, @arulraj17993, @danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
