### ISSUE TITLE
Software update using azure iot sdk c

### ISSUE THREAD

**Issue by cgoma** [Azure/azure-iot-sdk-c#666]
- **OS and version used:** <VERSION> 
Ububtu 16.04
- **SDK version used:** <VERSION> 

# Description of the issue:

I am working on software update using azure iot c sdk. I started following this link https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_mqtt_dm/pi_device. This link is specific to raspberry pi. But I am assuming the steps mentioned will work for Ubuntu laptop. as I am updating application or configuration file using azure iot. As mentioned in link I am compiling the application for software update with rest of the SDK as mentioned in link https://github.com/Azure/azure-iot-device-ecosystem/blob/master/get_started/raspbian-3gpi-c.md. Once everything is build correctly I am successfully connected to cloud using sample application  "azure-iot-sdk-c/cmake/iotsdk_linux/serializer/samples/simplesample_http/simplesample_http" as menttioned in link.
![simple-http-success](https://user-images.githubusercontent.com/10756434/46948396-913cf680-d09b-11e8-943b-a225b926559e.png)

For running application mentioned for firmware update, I have added the unit file as below to path /lib/systemd/system/iothub_client_sample_mqtt_dm.service. The content of the unit file are as below
```
[Unit]
Description=Azure-IoTHub Client DM Sample
After=network.target auditd.service
ConditionPathExists=/usr/share/iothub_client_sample/.device_connection_string

[Service]
Type=forking
ExecStart=/home/cgoma/azure/azure-iot-sdk-c/iothub_client/samples/iothub_client_sample_mqtt_dm
KillMode=process

[Install]
WantedBy=multi-user.target
Alias=iothub_client_sample_firmware_update
```
Also added the connection string in file /usr/share/iothub_client_sample/.device_connection_string
But when I am running application for software update I am not getting anyting on console. When I am checking the status of the service using "systemctl" command, it shows service is failed as in attached screen shot
![fail-iot-app](https://user-images.githubusercontent.com/10756434/46948485-e11bbd80-d09b-11e8-98ac-31de191e0042.png)

I am not sure what I am doing wrong. Also there is no documentation available for running the application "iothub_client_sample_mqtt_dm". Please let me know what I am doing wrong here. 

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by ewertons** [comment]
Hi @cgoma ,
according to what you posted your application is working fine when you run it from the console, right?
The issue seems to be when you run it as a service.
So this is technically not an issue on azure-iot-sdk-c.
However, you might be having a permission issue. Confirm if your application can run successfully from the shell using your own user ID. That clears the code from having any issues. Then investigate if you are giving the application the proper permissions.
Here are a couple results from a search:
https://unix.stackexchange.com/questions/207469/systemd-permission-issue-with-mkdir-execstartpre
https://serverfault.com/questions/806469/how-to-allow-a-user-to-use-journalctl-to-see-user-specific-systemd-service-logs/814913

**Comment by ewertons** [comment]
Hi @cgoma ,
we will close this issue for now but please feel free to reopen it if you would like to follow up.
Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment]
@cgoma, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
