### ISSUE TITLE
Stay connected continuous to the server Or Retry to connect 

### ISSUE THREAD

**Issue by MahendraSondagar** [Azure/azure-iot-sdk-c#667]
Hey there

             I'm using Azure IOT SDK-c having version  **1.1.31** with my IOT hardware STM32F429Zi with the Ethernet.
I'm getting communication from device to cloud and cloud to device. Now the problem is, my client is not continuous. That will send the data to the server when the specific condition meets, but I'm expecting contentious connections from the server in case of the OTA (Over the air update)
How may i keep the connections alive

Thanks

**Comment by jebrando** [comment]
@MahendraSondagar What protocol are you using for this device MQTT, AMQP, or HTTP.  Both MQTT, and AMQP are connected protocols, HTTP is not.

**Comment by az-iot-builder-01** [comment]
@MahendraSondagar, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by massand** [comment]
@MahendraSondagar we are closing since we haven't heard back. Feel free to reopen this or a new issue. Thanks!
