### ISSUE TITLE
undefined reference to `hsm_client_key_interface'

### ISSUE THREAD

**Issue by vanti** [Azure/azure-iot-sdk-c#668]
I am able to rebuild the repository successfully on my Ubuntu 14.04 machine. However, when I build the repository with the provisioning client turned on, I get the following error message:

> /home/local/workdir/azure/azure-iot-sdk-c_provisioning/provisioning_client/src/iothub_auth_client.c:179: undefined reference to `hsm_client_key_interface'

I am using the LTS_10_2018 branch, and am building using these commands:

```
$ cmake -Duse_prov_client:BOOL=ON -Dhsm_custom_lib=/home/local/workdir/azure/azure-iot-sdk-c_provisioning/cmake/provisioning_client/samples/custom_hsm_example/libcustom_hsm_example.a -DCMAKE_BUILD_TYPE=Debug ..
$ cmake -- .
```

The same error seems to apply to all examples. Any idea what is causing this?

**Comment by jebrando** [comment]
This is a bug that got introduced.  I will fix shortly and let you know when it get in.

**Comment by jebrando** [comment]
@vanti I have found the issue and have changed it locally.  I will be setting up tests and code review and I shall try to get it checked in by the end of day.

Thank you,
Jelani

**Comment by jebrando** [comment]
@vanti I checked the fix into both master and the lts branch.  Thank you for the issue, please let us know if you find any more issues.

**Comment by az-iot-builder-01** [comment]
@vanti, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by vincent-ti** [comment]
Thanks. I was able to build the sample with the changes, after I add back the line

> compileAsC99()

to provisioning_client/samples/custom_hsm_example/CMakeLists.txt. Otherwise it'd complain that "//" style comment is not valid in custom_hsm_example.c.

**Comment by vanti** [comment]
Thanks. I was able to build the sample with the changes, after I add back the line

    compileAsC99()

to provisioning_client/samples/custom_hsm_example/CMakeLists.txt. Otherwise it'd complain that "//" style comment is not valid in custom_hsm_example.c.
