### ISSUE TITLE
[ServiceClient] Messages ID is not sent

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdk-c#68]
tHi,

I believe I should have open a new issue right after this one #34 but anyway, here is what we saw.

> Hi @anporumb,
> 
> I've check df13ec1, we have the message properties et correctly. But we are missing the message Id.
> 
> IoTHubMessage_SetMessageId(messageHandle, "42");
> 
> Does not make 42 being the id of the message received on the device side.
> I can't tell you if this a regression of the fix or a part of the previous bug I've don't seen.

Here is how we set message id

```
    IoTHubMessage_SetMessageId(messageHandle, "the id");
    IoTHubMessage_SetCorrelationId(messageHandle, "the correlation id));

    _iotHubMessagingResult = (int)IoTHubMessaging_LL_Send((IOTHUB_MESSAGING_HANDLE)_iotHubMessagingHandle, deviceId, messageHandle, (IOTHUB_SEND_COMPLETE_CALLBACK)_sendCompleteCallback, (void*)SEND_CONTEXT_STRING);
```

On the device side the message is received with no ID.
I've also check with 2017-02-10 and we encounter the same behavior.

**Comment by anporumb** [comment]
Hello @lmussier ,

Thank you for your report. Is it a cloud-to-device message that you are trying to send and when received by the device, it does not bear the message-id?

Best Regards,
Andrei Porumb

**Comment by lmussier** [comment]
Hi,

Yes this is cloud to device.

Le 14 févr. 2017 7:44 PM, "anporumb" <notifications@github.com> a écrit :

Hello @lmussier <https://github.com/lmussier> ,

Thank you for your report. Is it a cloud-to-device message that you are
trying to send and when received by the device, it does not bear the
message-id?

Best Regards,
Andrei Porumb

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/azure-iot-sdk-c/issues/68#issuecomment-279796865>,
or mute the thread

**Comment by zolvarga** [comment]
Hello @lmussier ,

The Service Client sends the message id and correlation id fine.
The device client you are using probably uses MQTT protocol and that case you won't see the IDs transferred. Could you please verify if that is the case? Also if that is the case, could you try with either AMQP or HTTP to see if it works or not?

Best Regards,
Zoltan

**Comment by lmussier** [comment]
You are right, we are using MQTT/WS on the device side. I'll try switching to AMQP to check, but what's the point on devices running MQTT/WS ? The fact that devices don't get message id is an issue(?) with the device_client lib in coordination with MQTT/WS or does MQTT/WS never expose message id in received messages?

**Comment by zolvarga** [comment]
Hello @lmussier ,

Yes, you are right it is (was) an issue :)
I have checked in the fix for MQTT. Now message id and correlation id will be received in MQTT too.
I also verified the behavior across all the protocols and updated all the samples to print out both IDs.

Best Regards,
Zoltan

**Comment by lmussier** [comment]
Hi @zolvarga, we finally have a chance to test to fix.
We encounter a crash when enabling the portion of **OUR** when the service_client is used. we are investigating what's going one.

It seems we are removing a device from the hub too quick, stay tuned.
I'll close the issue as soon as we understand where is the issue.

Tks.

**Comment by lmussier** [comment]
Hi,

We finally chase down the bug, you'll find it in #75
I close here assuming the this bug is corrected.

Thanks :)
