### ISSUE TITLE
Expected long run and continuous connections towards server 

### ISSUE THREAD

**Issue by MahendraSondagar** [Azure/azure-iot-sdk-c#686]
Hey there, 

             I'm using Azure IOT SDK version **1.1.34** with my embedded hardware . I'm able to send the data from client to cloud and cloud to client including the **direct call**  and **Message to device**

Now I have observed that when my client gets deactivate or not sending the data at certain minutes then the connection goes in Idle mode and at that time I'm not getting any data from cloud to device (I'm using device explorer to send and trace the data ). Every time get the error **"Timeout Waiting for the response from the device"**

I believe, that is the normal scenario as my client is in Idle mode then the cloud will close the half opened (idle)TCP Connections, but that is strange, as I'm maintaining the **keep alive** time at the client side !

My **MQTT keep alive time is 2 min** and from azure api I'm continuous calling    **IoTHubClient_LL_DoWork(iotHubClientHandle)** at every 100ms interval, infect I'm also maintaining retry policy that is for **immediate connections** in case of the any disconnections happens, still I'm not getting connections connections especially from cloud 

But the good part is when my client send the data then it immediately appear and when i detach the Ethernet cable then it auto connects, here I'm exacting keep the connections continuous any how from cloud to device

I need to ask the community is there anything else that I'm missing to configure ?
Thanks

**Comment by ewertons** [comment]
Hi @MahendraSondagar , we will close this issue for now, but please feel free to reopen it if you would like to follow up.

Thanks for using the Azure IoT SDKs.

**Comment by az-iot-builder-01** [comment]
@MahendraSondagar, @jebrando, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
