### ISSUE TITLE
[upload2blob] Some question about upload to blob

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdk-c#69]
Hi,

 We may wan to use the upload to blob feature from the SDK, and we have some unanswered questions:
- If we use MQTT/WS as transport for messaging stuff, do we have to create another iotHubClientHandle with HTPP as transport for the blob upload ?
- Does the upload to blob feature support a kind of stream upload.
i.e call multiple IoTHubClient_LL_UploadToBlob with the same destination file.

Thanks.

**Comment by olivierbloch** [comment]
Hi @lmussier 
* you actually don't need to create a separate iothubclient handle to so telemetry over MQTT and file upload (which uses REST APIs). The transport specified when creating the instance of the client is only for telemetry and doesn't impact file upload. The stacks necessary for file update are in the shared utility lib, not in the transports ones.
* Streaming is not supported in the actual file upload implementation in IoT Hub and if you use the same destination file, the new one will replace the previous one.

**Comment by lmussier** [comment]
Thanks for the quick answers.
