### ISSUE TITLE
cross compilation issues and usage of the build library for arm devices

### ISSUE THREAD

**Issue by hamburml** [Azure/azure-iot-sdk-c#691]
# Description of the issue:
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md mentions that the raspberrypi/tools don't provide all files necessary to cross compile from a debian-host. I think it's user-friendly if you could provide the necessary files.

Thank you!

Reference Issue https://github.com/Azure/azure-iot-sdk-c/issues/421

**Comment by markrad** [comment]
Hi @hamburml 

You will need to use apt-get to install the following packages on your Raspberry Pi before performing the copy:

- curl
- libcurl4-openssl-dev 
- uuid-dev
- libssl-dev unless you are running Raspbian Stretch in which case use libssl1.0-dev

_Mark Radbourne MSFT_

**Comment by hamburml** [comment]
Hi @markrad 

thanks for the reply. I was able to build it if I copy the files from the Raspberry Pi.

But what if a user doesn't have a Raspberry Pi right now or the whole building process is automated and the process of copying files from an (updated) Raspberry Pi with Raspbian is counteractive. Shouldn't it be buildable without having the physical device in front of you?

Thanks

**Comment by markrad** [comment]
Hi @hamburml,

Please remember that the document that details the cross compile for the Raspberry Pi is to be considered a sample. It demonstrates the techniques one can use to cross compile for any platform. It depends upon a third party toolchain that we have no control over. It is a very minimal toolchain so hence the need to supplement it. Other toolchains may or may not be more complete.

If you don't have a Raspberry Pi you basically have these options:

1. Contact the owner of the toolchain referenced in the document and ask for the additional files to be added. Seems an unlikely solution but included for the sake of completeness. 
2. Build the prerequisites from source. There is a second document that demonstrates that process that can be found here: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Docker_SDK_Cross_Compile.md. This sample, though targeting a MIPS platform, downloads and builds all of the SDK prerequisites before building the SDK. Care must be taken though to build the same versions of the prerequisites as those that are found on the target device or you experience version mismatch errors at runtime. 
3. Run Raspbian in a virtual machine and copy the files from there. You can find a variety of webpages that describe how one achieves that.

_Mark Radbourne MSFT_

**Comment by hamburml** [comment]
Hello! I created a Dockerfile which builds the Azure Iot SDK C for ARM devices.

It uses the Linaro toolchains and not the fairly old raspberrypi/tools toolchain. It builds the dependendies (openssl, curl, ...) and uses them to compile the sdk. It currently uses the dps_symm_key branch which I need for IoT Central.

If you like you could add this file to your examples :)

```
# Start with the latest version of the Ubuntu Docker container
FROM debian:stretch

# Fetch and install all outstanding updates
RUN apt-get update && apt-get -y upgrade

# Install wget git cmake xz-utils
RUN apt-get install -y wget git cmake xz-utils

WORKDIR /root

# Don't use RPiTools because gcc is old, use linaro's toolchain
#RUN mkdir RPiTools
#WORKDIR RPiTools
#RUN git clone https://github.com/raspberrypi/tools.git

RUN wget https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf.tar.xz
RUN tar -xvf gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf.tar.xz

ENV WORK_ROOT=/root
ENV TOOLCHAIN_ROOT=${WORK_ROOT}/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf
ENV TOOLCHAIN_SYSROOT=${TOOLCHAIN_ROOT}
ENV TOOLCHAIN_EXES=${TOOLCHAIN_SYSROOT}/bin
ENV TOOLCHAIN_NAME=arm-linux-gnueabihf
ENV TOOLCHAIN_PREFIX=${TOOLCHAIN_SYSROOT}/usr

ENV AR=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-ar
ENV AS=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-as
ENV CC=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-gcc
ENV LD=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-ld
ENV NM=${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-nm

ENV LDFLAGS="-L${TOOLCHAIN_SYSROOT}/usr/lib"
ENV LIBS="-lssl -lcrypto -ldl -lpthread"
ENV TOOLCHAIN_PREFIX=${TOOLCHAIN_SYSROOT}/usr
ENV STAGING_DIR=${TOOLCHAIN_SYSROOT}

WORKDIR /root

# Download OpenSSL
# use newer openssl version for current raspbian compatibility
#RUN wget https://www.openssl.org/source/openssl-1.0.2p.tar.gz
#RUN tar -xvf openssl-1.0.2p.tar.gz

# Build OpenSSL
#WORKDIR openssl-1.0.2p
#RUN ./Configure linux-generic32 shared --prefix=${TOOLCHAIN_PREFIX} --openssldir=${TOOLCHAIN_PREFIX}
#RUN make
#RUN make install
#WORKDIR ..

# Download OpenSSL
RUN wget https://www.openssl.org/source/openssl-1.1.0f.tar.gz
RUN tar -xvf openssl-1.1.0f.tar.gz

# Build OpenSSL
WORKDIR openssl-1.1.0f
RUN ./Configure linux-generic32 shared --prefix=${TOOLCHAIN_PREFIX} --openssldir=${TOOLCHAIN_PREFIX}
RUN make
RUN make install
WORKDIR ..

# Download cURL source and expand it
RUN wget http://curl.haxx.se/download/curl-7.60.0.tar.gz
RUN tar -xvf curl-7.60.0.tar.gz

# Build cURL
# we need to set the path for openssl with --with-ssl=...
WORKDIR curl-7.60.0
RUN ./configure --with-sysroot=${TOOLCHAIN_SYSROOT} --prefix=${TOOLCHAIN_PREFIX} --target=${TOOLCHAIN_NAME} --with-ssl=${TOOLCHAIN_PREFIX} --with-zlib --host=${TOOLCHAIN_NAME} --build=x86_64-linux-gnu
RUN make
RUN make install
WORKDIR ..

# Download the Linux utilities for libuuid and expand it
RUN wget https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.32/util-linux-2.32-rc2.tar.gz
RUN tar -xvf util-linux-2.32-rc2.tar.gz

# Build uuid
WORKDIR util-linux-2.32-rc2
RUN ./configure --prefix=${TOOLCHAIN_PREFIX} --with-sysroot=${TOOLCHAIN_SYSROOT} --target=${TOOLCHAIN_NAME} --host=${TOOLCHAIN_NAME} --disable-all-programs  --disable-bash-completion --enable-libuuid
RUN make
RUN make install
WORKDIR ..

# clone azure (use dps_symm_key branch for IoT Central Support)
RUN git clone -b dps_symm_key --recursive https://github.com/Azure/azure-iot-sdk-c.git
WORKDIR azure-iot-sdk-c

# Create a working directory for the cmake operations
RUN mkdir cmake
WORKDIR cmake

# Create a cmake toolchain file on the fly
RUN echo "SET(CMAKE_SYSTEM_NAME Linux)     # this one is important" > toolchain.cmake
RUN echo "SET(CMAKE_SYSTEM_VERSION 1)      # this one not so much" >> toolchain.cmake

RUN echo "SET(CMAKE_C_COMPILER ${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-gcc)" >> toolchain.cmake
RUN echo "SET(CMAKE_CXX_COMPILER ${TOOLCHAIN_EXES}/${TOOLCHAIN_NAME}-gcc)" >> toolchain.cmake
RUN echo "SET(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_SYSROOT})" >> toolchain.cmake
RUN echo "SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)" >> toolchain.cmake
RUN echo "SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)" >> toolchain.cmake
RUN echo "SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)" >> toolchain.cmake

# Build the SDK. This will use the OpenSSL, cURL and uuid binaries that we built before
RUN cmake -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake -Duse_prov_client:BOOL=ON -DCMAKE_INSTALL_PREFIX=${TOOLCHAIN_PREFIX} ..
RUN make
RUN make install

CMD ["/bin/bash"]
```

Cheers
Michael

**Comment by markrad** [comment]
Hi @hamburml,

Coincidentally I have been working on something very similar. I will take a look at your solution. Thank you for your contribution. My intention was to combine the MIPS build documentation (that you obviously looked at) with the Raspberry Pi build documentation pretty much as you have done above. Thanks for the note about the better toolchain.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Your Dockerfile works well. I did modify it so that it doesn't all run as root. Typically, if you see an access denied, this is a good indicator that something is not right. If you run as root you won't have that benefit.

Thanks again.

**Comment by hamburml** [comment]
I think this can be closed. @markrad Do you think your modified version will be added to the examples soon?

**Comment by hamburml** [comment]
I try to this [example](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Docker_SDK_Cross_Compile.md#building-your-application).

I was able to change the CMakeLists.txt to find the azure_c_shared_utility header files.

CMakeLists.txt:

```
cmake_minimum_required(VERSION 2.8.11)
project(myapp_project)

# The demonstration uses C99 but it could just as easily be a C++ application
set (CMAKE_C_FLAGS "--std=c99 ${CMAKE_C_FLAGS}")

set(iothub_c_files
    iothub_convenience_sample.c
)

# Set up the include and library paths
include_directories(/root/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf/usr/include/azureiot;/root/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf/usr/include)
link_directories(/root/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf/usr/lib)

add_executable(myapp ${iothub_c_files})

# Redundant in this case but shows how to rename your output executable
set_target_properties(myapp PROPERTIES OUTPUT_NAME "myapp") 

# List the libraries required by the link step
target_link_libraries(myapp iothub_client aziotsharedutil iothub_client_mqtt_transport umqtt ssl crypto curl pthread parson m)
```

The output is now:

```
root@e65c519e69d7:~/myapp/cmake# make
Scanning dependencies of target myapp
[ 50%] Building C object CMakeFiles/myapp.dir/iothub_convenience_sample.c.o
[100%] Linking C executable myapp
/root/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf/usr/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_CreateFromDeviceAuth':
iothub_client_authorization.c:(.text+0x35a): undefined reference to `iothub_device_auth_create'
iothub_client_authorization.c:(.text+0x3dc): undefined reference to `iothub_device_auth_destroy'
iothub_client_authorization.c:(.text+0x430): undefined reference to `iothub_device_auth_destroy'
iothub_client_authorization.c:(.text+0x450): undefined reference to `iothub_device_auth_get_type'
/root/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf/usr/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Destroy':
iothub_client_authorization.c:(.text+0x4cc): undefined reference to `iothub_device_auth_destroy'
/root/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf/usr/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Set_xio_Certificate':
iothub_client_authorization.c:(.text+0x604): undefined reference to `iothub_device_auth_generate_credentials'
/root/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf/usr/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Get_SasToken':
iothub_client_authorization.c:(.text+0x848): undefined reference to `iothub_device_auth_generate_credentials'
collect2: error: ld returned 1 exit status
CMakeFiles/myapp.dir/build.make:94: recipe for target 'myapp' failed
make[2]: *** [myapp] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/myapp.dir/all' failed
make[1]: *** [CMakeFiles/myapp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Any advice? :/

**Comment by markrad** [comment]
Hi @hamburml,

Can you post the source of the application you are trying to build? I can test it locally.

_Mark Radbourne MSFT_

**Comment by hamburml** [comment]
@markrad I tried the prov_dev_client_ll_sample from the dps_symm_key branch.

I created a new folder (not inside the azure sdk, I want to use the libs from azure sdk which are now inside the toolchain), added this [file](https://github.com/Azure/azure-iot-sdk-c/blob/dps_symm_key/provisioning_client/samples/prov_dev_client_ll_sample/prov_dev_client_ll_sample.c), added a [CMakeLists.txt](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Docker_SDK_Cross_Compile.md#building-your-application), created a cmake folder inside that folder and let cmake create the makefiles (`cmake -DCMAKE_TOOLCHAIN_FILE=${WORK_ROOT}/azure-iot-sdk-c/cmake/toolchain.cmake ..`).

During the build with make I saw the errors.

I can try and add all the steps to a new Dockerfile so you can simply build and spawn the container and see for yourself.

**Comment by markrad** [comment]
Hi @hamburml,

If you could put it all in a Dockerfile script that would be ideal.

Thanks.

**Comment by hamburml** [comment]
Hello @markrad,

sorry for taking so long. In this [repo](https://github.com/hamburml/azure-iot-sdk-c-docker-example) you can find the CMakeLists.txt, the prov_dev_client_ll_sample.c and the Dockerfile which builds the sdk, adds these files and tries to build an application using the toolchain.

You build and run the container and enter `make`. After that you see the errors I mentioned.

Thanks for your help!

Michael

**Comment by hamburml** [comment]
Just a reminder for @markrad  :)

**Comment by markrad** [comment]
HI @hamburml,

I overlooked this issue. Are you still having a problem with the build that includes the provisioning client?

**Comment by hamburml** [comment]
Hi @markrad,

we switched to the nodejs sdk. I couldn't get it to work with the c-sdk and I didn't have time left. We needed a fast and working solution. Maybe we will try it with the c-sdk again but right now it's not our priority.

Thanks for answering.

**Comment by ewertons** [comment]
Hi @hamburml ,

we are triaging these old issues and trying to close them as possible.
Have you tried using the C SDK again? do you still face any issues?
If not, can this be closed?
Thanks.

**Comment by az-iot-builder-01** [comment]
@hamburml, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by hamburml** [comment]
Haven't had time to use the C SDK again. You can still see the issues I had and maybe find a solution (or show the right way how it's done).
