### ISSUE TITLE
IoTHubMessaging_Destroy should block on worker threads even if _Close not yet called

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#693]
See https://github.com/Azure/azure-iot-sdk-python/issues/223 - basically we need to change the `IoTHubMessaging_Destroy` so that it drains off any worker threads even if `IoTHubMessaging_Close` hasn't been called.

**Comment by jspaith** [comment]
Going to not-fix this.  Reasons:
* The service SDK is fairly static for C and we don't think a lot of people are using it, if any.
* Using the API correctly does NOT have this problem.  The samples demonstrate correct way to do this.
* Fixing this becomes somewhat complex - we can't just call Close() from destroy level as a safety, since Close() itself isn't setup to be called multiple times and we'd need to fix that.

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
