### ISSUE TITLE
(De-)Connection Status Reason - SAS Tokens

### ISSUE THREAD

**Issue by raycon94** [Azure/azure-iot-sdk-c#695]
- **OS and version used:** <Keil RTX 4> 

- **SDK version used:** <1.2.10> 

# Description of the issue:

Hello,

is there any incompatibility between the Azure-Hub and the Version 1.2.3 ?

Especially in relation to the SAS-Generation-Logic:
The last time I tested my application (about June 2018), every Time the SAS-Token expired, I got IOTHUB_CLIENT_CONNECTION_NO_NETWORK as deconnection-reason and my device automatically reconnected itself within a few seconds.
Now I get IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED as deconnection reason, every time the SAS-Token expires. The sdk does not do any reconnects, so I have to restart my azure-client manually.

When I get which deconnection reason?

More important question:
Is the SDK-Version I am currently using still compatible with the Azure-Hub? Will there any changes on the Iot-Hub on near future that will affect my application?

**Comment by jebrando** [comment]
@raycon94 The SDK should be compatible now and with all foreseeable future version of the IoTHub.  To diagnose your issue I have a couple of question for you.

1. Turn on MQTT logging 
`
bool traceOn = true;
IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_LOG_TRACE, &traceOn);
`
 and send me the result of the CONNACK mqtt packet reply.

1. Are you supplying your own SAS token or is the SDK generating the SAS token for you?

1. If you are supplying your own SAS token what is the expiry on that token?

**Comment by raycon94** [comment]
Hello @jebrando.

the time-source for the SAS-Token was invalid.

**Comment by az-iot-builder-01** [comment]
@jebrando, @raycon94, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
