### ISSUE TITLE
Control got struck in "DoTimeouts" function

### ISSUE THREAD

**Issue by ravitejaveeragandam** [Azure/azure-iot-sdk-c#698]
Recently i started working on Azure IOT client and server communication. As part of this i am sending few messages from my device and receiving at server side which i am capturing using device explorer(TWIN). And also i am able to receive the data from server to client with no problem.

But i am failing in one scenario like Sending 20 bytes of data for every sec from client to server, the same time sending data to client continuously from server. Control is getting stuck in the function "DoTimeouts" and it is not coming out. How to come out this function?

And also what is the function need to use to set a callback function when timeouts?

**Comment by ewertons** [comment]
Hi @ravitejaveeragandam ,

on your first statement, 

> Recently i started working on Azure IOT client and server communication. As part of this i am sending  few messages from my device and receiving at server side which i am capturing using device explorer(TWIN). And also i am able to receive the data from server to client with no problem.

could you clarify these points please?
1. Are you using Telemetry?
2. How often are you sending messages? (what "few messages" mean?)
3. What environment/device are you using? 
4. Which OS are you using?
5. What version of the SDK are you using?

For the second part of your question,

> But i am failing in one scenario like Sending 20 bytes of data for every sec from client to server, the same time sending data to client continuously from server. Control is getting stuck in the function "DoTimeouts" and it is not coming out. How to come out this function?

1. Are you running the same code as in the test above, but with higher frequency?
2. What indications are you noticing to conclude the execution is hanging on DoTimeouts?
3. Are you using the *_LL_* functions of the SDK or the non-*_LL_* functions?

**Comment by ewertons** [comment]
> And also what is the function need to use to set a callback function when timeouts?

If you are sending Telemetry messages, the callback you pass to [IoTHubDeviceClient_LL_SendEventAsync](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L163) is the same invoked when a message times out to be sent.

**Comment by ewertons** [comment]
Also, I see @jebrando fixed and closed the other MQTT issue mentioned above.
Does that resolve this issue for you? Please confirm so we can close it.

**Comment by ravitejaveeragandam** [comment]
What id mean by LL functions and Non-LL functions?

Fix given by @jebrando resolves this issue i feel. For now we can close the issue.

**Comment by ewertons** [comment]
LL functions relate to our [Low Level API](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_device_client_ll.h).
Non-LL functions are the ones from our [convenience layer](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_device_client.h), which is a threaded layer on top of the one abpve.

**Comment by az-iot-builder-01** [comment]
@ravitejaveeragandam, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
