### ISSUE TITLE
Upload text file using NodeMCU ESP8266 CP2102 WIFI

### ISSUE THREAD

**Issue by vrbagal** [Azure/azure-iot-sdk-c#699]
I am using **NodeMCU ESP8266 CP2102 WIFI Serial Wireless Module** to upload images from SD card to Blob storage
using
https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_upload_to_blob

when I run this i get following error in serial monitor

_unknown option CURLOPT_VERBOSE
error code = HTTPAPIEX_INVALID_ARG
No SSL clients available.
Error signalled by underlying IO
Open HTTP connection failed (result = HTTPAPI_OPEN_REQUEST_FAILED)
unable to recover sending to a working state
unable to HTTPAPIEX_ExecuteRequest
unable to Blob_UploadBlock. Returned value=3, httpStatus=1073741552
unable to Blob_UploadFromSasUri
hello world failed to upload_

**Azure_file_upload.ino**

```
#include <stdbool.h>
#include <string.h>
#include "iot_configs.h"

#include <AzureIoTHub.h>
#if defined(IOT_CONFIG_MQTT)
#include <AzureIoTProtocol_MQTT.h>
#elif defined(IOT_CONFIG_HTTP)
#include <AzureIoTProtocol_HTTP.h>
#endif

#include "iot_upload.h"
#include "esp8266/sample_init.h"

static char ssid[] = IOT_CONFIG_WIFI_SSID;
static char pass[] = IOT_CONFIG_WIFI_PASSWORD;
static int count = 0;

void setup() {
  Serial.begin(115200);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for Leonardo only
  }
  Serial.println("testing ..");
  sample_init(ssid, pass);

}

// Azure IoT samples contain their own loops, so only run them once
static bool done = false;
void loop() {
   Serial.print("Loop Start "); 
  
  if (count < 10)
  {
    
    Serial.println(count);
  
    char *deviceid= "device ";
   
    Serial.println(deviceid);

    bool result =  upload_file(deviceid);
    Serial.println(result);
    done = true;
    count++;
    delay(500);
  }
  else
  {
    delay(500);
  }
}
```

**iot_file_upload.c**

```
#include <AzureIoTProtocol_HTTP.h>

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>

#include "AzureIoTHub.h"
 
#include "iot_configs.h"
#include "iot_upload.h"

static const char* connectionString = IOT_CONFIG_CONNECTION_STRING;

bool upload_file(char* deviceId)
{
  (void)printf(connectionString);

  (void)printf("Testing ..\r\n");
  unsigned char* data_to_upload = "device test 1111 ";
  //strcat(data_to_upload,deviceId);

  if (platform_init() != 0)
  {
    printf("Failed to initialize the platform.\r\n");
  }
  else
  {
    (void)printf("initialized platform..\r\n");
    if (serializer_init(NULL) != SERIALIZER_OK)
    {
      (void)printf("Failed on serializer_init\r\n");
    }
    else
    {
      (void)printf("initialized serializer..\r\n");

      IOTHUB_CLIENT_LL_HANDLE device_ll_handle = IoTHubClient_LL_CreateFromConnectionString(connectionString, HTTP_Protocol);
      if (device_ll_handle == NULL)
      {
        (void)printf("Failure createing Iothub device.  Hint: Check you connection string.\r\n");
      }
      else
      {
        (void)printf("initialized device_ll_handle..\r\n");
 
        if (IoTHubClient_LL_UploadToBlob(device_ll_handle, "atest.txt", (const unsigned char*)data_to_upload, sizeof(data_to_upload) - 1) != IOTHUB_CLIENT_OK)
        {
          (void)printf("hello world failed to upload\n");
        }
        else
        {
          (void)printf("hello world has been created\n");
        }
        //}
      }

      IoTHubClient_LL_Destroy(device_ll_handle);
    }
    serializer_deinit();
  }
  platform_deinit();  
  return true;
}
```

**Comment by massand** [comment]
It seems somehow there is a dependency on httpapi_curl.c created through a call to HTTPAPIEX_SetOption(OPTION_CURL_VERBOSE) somewhere in the upload_to_blob call path. I traced the call path leading to httpapi_compact.c on your end though, which would definitely not have this option. I will need to investigate how you got in this state. If you can share how you built the sample, it would be useful for our investigation, since we generally rely on the Espressif Github community for assistance on the right way to build for ESP boards currently.

**Comment by tshauck** [comment]
Just to follow up, I was able to resolve this by commenting out the `Serial.setDebugOutput(true)` in: https://github.com/Azure/azure-iot-pal-arduino/blob/49252a41dcb772a8dd65d518ea977078e0e698de/build_all/base-libraries/AzureIoTUtility/src/esp8266/sample_init.cpp#L16-L20

It would be nice to have debugging though, as now there's another error :).

**Comment by massand** [comment]
@markrad  does your latest PR on arduino-pal repo fix this type of issue or the followup from @tshauck?

**Comment by markrad** [comment]
Curl is not available in the Arduino environment. I doubt that file upload is supported.

**Comment by massand** [comment]
@markrad - that is an excellent point I totally missed when I started looking into this issue. 
@ewertons - since you are looking into Arduino packages, could you look into explicitly removing upload to blob logic within Arduino until we are fully ready to support it (say in newer devices)? Here is the CMake file that needs to have the dont_use_upload_to_blob cmake option - https://github.com/Azure/azure-iot-pal-arduino/blob/master/CMakeLists.txt

**Comment by gregman-msft** [comment]
@jbobotek once we have our Arduino support up, can you please re-investigate this issue?

**Comment by markrad** [comment]
@ewertons @jbobotek Possibly this could be supported by adding httpapi_compact into the build. This doesn't depend on third party libraries.

**Comment by jbobotek** [comment]
We have explicitly removed upload to blob support for Arduino devices. The ESP8266 also does not have the RAM to support storage of large files anyways. @ewertons , correct me if I'm wrong, but I think we can close this as not supported.

**Comment by ericwol-msft** [comment]
Closing issue. Upload to blob will be handled in the [azure-c-shared-utility](https://github.com/Azure/azure-c-shared-utility) sdk.

**Comment by az-iot-builder-01** [comment]
@vrbagal, @tshauck, @gregman-msft, @jbobotek, @ericwol-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
