### ISSUE TITLE
Failed to transmit the data(via MQTT) after reception of data from server

### ISSUE THREAD

**Issue by ravitejaveeragandam** [Azure/azure-iot-sdk-c#705]
- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by ewertons** [comment]
Hi @ravitejaveeragandam ,
there is no possible way we can help without having information about what the failure was, environment you used, version of the SDK you used, etc.

Could you please fill the description template with the details. As many as possible, please.

**Comment by ravitejaveeragandam** [comment]
Hi,

I taken the latest software and started working. Observed a strange behavior.

I will explain my scenario first
On power on i use to send 9 packets of data, each size of 14 bytes. And my program waits for response for the 9 packets what i sent. Once it get response it will send next packets.

With earlier software version 1.2.8, i am able to receive the response message and send the data(10th packet) one or two times and gets hang in "DoTimeouts".

But with software version 1.2.10, i am able to receive correct response for one of the 9 packets which i am sending and able to place next one packet data in IOT buffer to transfer. But from IOT i am unable to send the data to Server(not able to receive in TWIN device explorer). And also i confirmed that "SendConfirmationCallback" is not getting called.

Is there anything extra care i need to take in new software? I have doubt like did connection gets closed once after first transaction? Because every time i restart i am able to send the data.. Once after first transaction i am not able send data.

Note: Using function "IoTHubClient_LL_GetSendStatus" i got the status as "IOTHUB_CLIENT_SEND_STATUS_BUSY".

Control is not coming out of below loop
do
{
IoTHubClient_LL_DoWork(IOTHubClientHandle);
ThreadAPI_Sleep(10);

    IoTHubClient_LL_GetSendStatus(IOTHubClientHandle , &iothub_send_status);
                  
  } while (iothub_send_status == IOTHUB_CLIENT_SEND_STATUS_BUSY);

**Comment by ewertons** [comment]
Are you using code based on one of our [samples](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples)?

When you are sending your 9 packets of data (the ones with 14kb of data), are you using Telemetry (i.e., through [IoTHubDeviceClient_LL_SendEventAsync](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L163))?

Or are you sending your data through [Device Twin API](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_device_twin_and_methods_sample/iothub_client_device_twin_and_methods_sample.c#L328)? What do you mean by TWIN device explorer?

Right after you create the iothubclient, could you enable [verbose logging](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L126)? Then copy the printouts you get in the console and paste here please. That will help understand your scenario a little better.

**Comment by ewertons** [comment]
Hi @ravitejaveeragandam ,
we will close this issue for now, but please feel free to reopen it if you would like to follow up.
Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment]
@ewertons, @ravitejaveeragandam, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
