### ISSUE TITLE
Connect a downstream device to an Azure IoT Edge gateway 

### ISSUE THREAD

**Issue by anfelbeghoura** [Azure/azure-iot-sdk-c#707]
For a C-Application, I used the Azure-IOT-Hub-C with ESP32, I fixed the libraries .. but I facing this issue with the ''xQueueGenericReceive'' (related to the ESP-IDF).
So is there a special SDK to connect ESP32 with the IoT Edge?
Thank you.

**Comment by yzhong94** [comment]
Hi there, are you using this library from Espressif? https://github.com/espressif/esp-azure

**Comment by jspaith** [comment]
@anfelbeghoura - could you please answer Yi's question to help us understand more.

I recommend you checkout https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iotedge_downstream_device_sample which shows what setting up a device downstream of Edge.  The most important aspect here is that you are going to have to tell the C SDK to trust the certificate that Edge is using for TLS.

Also please let us know which version of C SDK you're on, get on latest if not already, let us know any error codes and more specifically logging would help.  Something like below:

```c
        bool traceOn = true;
        (void)IoTHubDeviceClient_SetOption(device_handle, OPTION_LOG_TRACE, &traceOn);
```

**Comment by anfelbeghoura** [comment]
I used the esp32 as a downstream device to connect to the iotEdge (Gateway) not to connect to the cloud

**Comment by jspaith** [comment]
I understand you're working to a gateway, not hub directly.  The [sample](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iotedge_downstream_device_sample) should help you to this end.

You should also checkkout [this](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway) for conceptual background.

To provide further C SDK specific guidance I'm going to need the additional logs mentioned in my post above.

**Comment by anfelbeghoura** [comment]
well, yes I used the azure iot hub C sdk (iotedge_downstream_device_sample) and I configured my iot edge as a gateway, and It didn't work (actually neither with raspberry pi3 nor ESP32) I'm just asking if there is  any special "iotedge_downstream_device" program for ESP32 to communicate with the ESP32 because I tryed to do that but I faced some troubles with ESP libraries esp-IDF.
Thank you

**Comment by jspaith** [comment]
I'm not familiar with esp32 specific issues, but I don't think we've tested that explicitly or at least I haven't.

The pi should work though since it's "just" Linux on the inside.

Where are you getting the provisioning certificates for the downstream sample from?  Namely what you're setting in `edge_ca_cert_path `.  The downstream sample needs that so that it trusts the (presumably?) self-signed root certificate that IoT Edge is using.

A few other questions:
* Can the device connect directly to IoTHub, without Edge?  If not, could point to something else being off.
* Please get the trace messages I've asked for above.  I'm just guessing this is a cert issue based on experience here but logs might reveal something else.

**Comment by anfelbeghoura** [comment]
For the ESP32 I'll keep trying till I get something.
For the raspberry pi 3 I'm using the 1.0.6.1 iotedge vertion and I used the 1.2.13 azure-iot-sdk-c version ( azure-iot-sdk-c/tools/CACertificates/certGen.sh ) to create the certificate. I put the hostname 'iotedgegateway'.

the path: static const char* edge_ca_cert_path = "/home/pi/azure-iot-sdk-c/certs/azure-iot-test-only.root.ca.cert.pem";

and in the yaml file :
certificates:
  device_ca_cert: "home//pi//WRKDIR//certs//new-edge-device-full-chain.cert.pem"
  device_ca_pk: "home//pi//WRKDIR//private//new-edge-device.key.pem"
  trusted_ca_certs: "home//pi//WRKDIR//certs//azure-iot-test-only.root.ca.cert.pem"

and yes,  both iotedge device and downstream device connect to the iot hub


when I use the iotedge's IP adress in the iot hub device's connection string I get this:

pi@brandtiothub:~/azure-iot-sdk-c/cmake $ ./iothub_client/samples/iotedge_downstream_device_sample/iotedge_downstream_device_sample
This sample will send 20 messages and wait for any C2D messages.
Press the enter key to end the sample

Creating IoTHub handle
Sending message 1 to Edge Hub
Sending message 2 to Edge Hub
Sending message 3 to Edge Hub
Sending message 4 to Edge Hub
Sending message 5 to Edge Hub
Sending message 6 to Edge Hub
Sending message 7 to Edge Hub
Sending message 8 to Edge Hub
Sending message 9 to Edge Hub
Sending message 10 to Edge Hub
Sending message 11 to Edge Hub
Sending message 12 to Edge Hub
Sending message 13 to Edge Hub
Sending message 14 to Edge Hub
Sending message 15 to Edge Hub
Sending message 16 to Edge Hub
Sending message 17 to Edge Hub
Sending message 18 to Edge Hub
Sending message 19 to Edge Hub
Sending message 20 to Edge Hub

Press any key to continue
The device client has been disconnected
The device client has been disconnected
The device client is connected to IoT Edge
Confirmation callback received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 2 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 3 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 4 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 5 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 6 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 7 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 8 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 9 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 10 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 11 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 12 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 13 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 14 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 15 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 16 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 17 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 18 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 19 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 20 with result IOTHUB_CLIENT_CONFIRMATION_OK

but when I use the hostname 'iotedgegateway' or the 'iotedgegateway.theiothubhostname' I get this:

pi@brandtiothub:~/azure-iot-sdk-c/cmake $ ./iothub_client/samples/iotedge_downstream_device_sample/iotedge_downstream_device_sample
This sample will send 20 messages and wait for any C2D messages.
Press the enter key to end the sample

Creating IoTHub handle
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:277 Failure: getaddrinfo failure -3.
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:760 lookup_address_and_connect_socket failed
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2261 failure connecting to address iotedgegateway.
The device client has been disconnected
Sending message 1 to Edge Hub
Sending message 2 to Edge Hub
Sending message 3 to Edge Hub
Sending message 4 to Edge Hub
Sending message 5 to Edge Hub
Sending message 6 to Edge Hub
Sending message 7 to Edge Hub
Sending message 8 to Edge Hub
Sending message 9 to Edge Hub
Sending message 10 to Edge Hub
Sending message 11 to Edge Hub
Sending message 12 to Edge Hub
Sending message 13 to Edge Hub
Sending message 14 to Edge Hub
Sending message 15 to Edge Hub
Sending message 16 to Edge Hub
Sending message 17 to Edge Hub
Sending message 18 to Edge Hub
Sending message 19 to Edge Hub
Sending message 20 to Edge Hub

Press any key to continue
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:277 Failure: getaddrinfo failure -3.
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:760 lookup_address_and_connect_socket failed
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2261 failure connecting to address iotedgegateway.
The device client has been disconnected
Error: Time:Thu Feb  7 09:29:37 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:277 Failure: getaddrinfo failure -3.
Error: Time:Thu Feb  7 09:29:37 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:760 lookup_address_and_connect_socket failed
Error: Time:Thu Feb  7 09:29:37 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Feb  7 09:29:37 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Thu Feb  7 09:29:37 2019 File:/home/pi/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Thu Feb  7 09:29:37 2019 File:/home/pi/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2261 failure connecting to address iotedgegateway.
The device client has been disconnected


thank you

**Comment by jspaith** [comment]
From your logs, `getaddrinfo failure -3`.  This shows that the DNS is not resolved (it's EAI_AGAIN), which is consistent with your using the IP address just working for you. 

I imagine this is something you tried early on, but is a ping of the device (from your pi itself) is working?

I'm going to assume ping works for above, so I'm going to go on to next step here.

In your Azure C SDK repo, please do something like

```shell
git fetch
git checkout downstream-extra-debug
git pull
git submodule update --recursive
```

This is going to give you some extra debugging to make sure nothing is catastrophically wrong in parsing the ProtocolGateway.  Which it shouldn't or else Iot Edge modules would be broken.

It also will show us exactly what C SDK is passing to `getaddrinfo`, to see again if we're getting a reasonable request or unreasonable, and if we're reasonable to understand why on your device/network topology getaddrinfo is unhappy.

**Comment by jspaith** [comment]
@anfelbeghoura - since this has been quite for about a month, I'm going to close out the thread.  If you still have issues here, please reactivate/open a new issue and see if any of the debugging thoughts in my post above are helpful.

**Comment by az-iot-builder-01** [comment]
@jspaith, @anfelbeghoura, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by anfelbeghoura** [comment]
hey there;
sorry for not replying earlier, yes actually it was a DNS problem the IP@ wasn't linked to the hostName.
Now everything is working very well. I used the TempSens and CModule for the IoT Edge to see how the tow modules communicate between each other.
But we have faced an other issue, the downstream device is sending a test_message to the Iot Edge (gateway). when I verified the edgeAgent module's logs I can see the authentication success between the downstream and the gateway. What we need to work on now is to send/receive messages to/from IoT Edge (gateway)  using the test_message in a json frame as an example with MQTT or AMQP protocole.

**Comment by jspaith** [comment]
@anfelbeghoura - first happy to hear that the DNS issue is resolved.

For your next question, please open up a new GitHub issue as this one has been closed and we don't really track those.  You'd need to clarify a bit what you're looking for since it's not clear to me from the question specifically is asking since i'm not sure what a json frame means here or why you'd care about mqtt or amqp level given the SDK should hide all those details from you.

Also for this issue, if its C SDK specific please open the issue here.  But if it is more general to IoT Edge and its protocol layer, the appropriate GitHub would be at https://github.com/azure/iotedge .

**Comment by anfelbeghoura** [comment]
thank you
