### ISSUE TITLE
Cannot connect to same protocol at the same time!!

### ISSUE THREAD

**Issue by Pavan2358** [Azure/azure-iot-sdk-c#709]
My usecase is to use MQTT protocol for sending messages to the cloud and send upload Log files to the blob storage after a minute or so after sending the message, due to some reasons I am getting this error

2018-11-14 09:43:44.686819 INFO  [CLOUD_Interface.c:123] - Starting the IoTHub client sample upload to blob
Error: Time:Wed Nov 14 09:43:44 2018 File:3rdParty/Cloud/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:582 curl_easy_perform() failed: Couldn't connect to server

Error: Time:Wed Nov 14 09:43:44 2018 File:3rdParty/Cloud/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:584 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Wed Nov 14 09:43:44 2018 File:3rdParty/Cloud/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Wed Nov 14 09:43:44 2018 File:3rdParty/Cloud/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_step1and2 Line:407 unable to HTTPAPIEX_SAS_ExecuteRequest
Error: Time:Wed Nov 14 09:43:44 2018 File:3rdParty/Cloud/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadMultipleBlocksToBlob_Impl Line:939 error in IoTHubClient_LL_UploadToBlob_step1
2018-11-14 09:43:44.953120 INFO  [CLOUD_Interface.c:152] - ===============================================================
2018-11-14 09:43:44.954439 INFO  [CLOUD_Interface.c:153] - hello world failed to upload

2018-11-14 09:43:44.955659 INFO  [CLOUD_Interface.c:154] - ===============================================================

Below is the code where I am getting the error

1) gw_cloud_UploadLogsToCloud();
 2)   if ((iothub_client = IoTHubDeviceClient_LL_CreateFromConnectionString((const char *)GW_CONFIG_GetConfigItem(CONNECTION_STRING), MQTT_Protocol)) == NULL)
    {
        LOG_ERROR("Failure creating device Auth!");
}
second will run first as gw_cloud_UploadLogsToCloud has 60 second timer. After the timer has expired
In gw_cloud_UploadToCLoud I am calling " IoTHubDeviceClient_LL_CreateFromConnectionString" with HTTP protocol, that is when I am getting the error. Without "gw_cloud_UploadLogsToCloud()" the code runs fine

Can you please advice on this issue?
Do I have to de initialize the IOT for 2 and then run IoTHubDeviceClient_LL_CreateFromConnectionString for HTTP protocol or is there any better way?

I tried de initialisation IOT for 2) code and initializing it again in code 1), I am getting segmentation fault for it

**Comment by ewertons** [comment]
Hi @Pavan2358 ,
Could you just post your whole code here, so we can better understand what the problem is?

Two things to be mindful of:
1. You can call UploadToBlob even when you create a client using MQTT transport. Just create the client ONCE, use it for telemetry and later use the same client for upload to blob;
2. You need to be calling IoTHubDeviceClient_LL_DoWork constantly and frequently (at least every 100ms).

**Comment by markrad** [comment]
Adding to @ewertons response, it's not clear to me from your comments but if you are attempting to create two connections to the IoT hub from a single application each connection will need it's own connection string (with a different device id). You cannot concurrently connect the same device multiple times. The IoT hub only allows one connection from a device. 

_Mark Radbourne MSFT_

**Comment by Pavan2358** [comment]
Hi @ewertons and @markrad,

**As suggested I used two devices id's and created clients for MQTT and HTTP Protocol,** Still I am facing the Above mentioned issue. **I have attached code as requested by you. "MQTT PROTOCOL for Sending Messages" sends messages over mqtt protocol which is sent in "gw_cloud_SendMessage" API.** Timer is created using "GW_CLOUD_SetLogToCloudTimer" API and HTTP Protocol is executed in "check" API. Tick Counter is added as a 2 second delay for overflow of requests for other API's
Please can you tell where am I going wrong?

MQTT PROTOCOL for Sending Messages
===============================================================
if (!a)
  {
    LOG_ERROR("IOT Hub Client platform_init");
  }
  else
  {
    /* Create the iothub handle here */
    GW_CLOUD_SetLogToCloudTimer();
    (void)IoTHub_Init();
    if ((iothub_client = IoTHubDeviceClient_LL_CreateFromConnectionString(connectionString, MQTT_Protocol)) == NULL)
    {
        LOG_ERROR("Failure creating device Auth!");
        GW_LED_SetCloudStatus(UNAUTHORIZEDCLOUD);
    }
    else
    {

#ifdef SET_TRUSTED_CERT_IN_SAMPLES
  // Setting the Trusted Certificate.  This is only necessary on system with without
  // built in certificate stores.
  IoTHubClient_LL_SetOption(iothub_client, OPTION_TRUSTED_CERT, certificates);
#endif
      TICK_COUNTER_HANDLE tick_counter_handle = tickcounter_create();
      tickcounter_ms_t current_tick;
      tickcounter_ms_t last_send_time = 0;
      iothub_info.stop_running = false;
      bool cacheLoaded = false;
      char *telMsg = ALLOC(sizeof(char)*MAXIMUM_ALLOWED_SIZE);
      GW_CLOUD_ConfigureLiveElecTimer(GW_CONFIG_GetConfigItem(POWER_DURATION), false);
      gw_cloud_PlaformInit();
      if(telMsg != NULL)
      {
        do
        {
          if (iothub_info.connected != false)
          {
            (void)tickcounter_get_current_ms(tick_counter_handle, &current_tick);
            if ((current_tick - last_send_time) / CLOUD_MILLISECOND_TICKS_PER_SECOND > CLOUD_MIN_MSG_DURATION_SECONDS)
            {
              CloudMsgType messageType = CLOUD_MSG_INVALID;
              void *data = NULL;
              if(GW_STATUS_OK == gw_cloud_GetMsgFromCache(&messageType, &data))
              {
                if((CLOUD_MSG_INVALID != messageType) && (NULL != data))
                {
                  memset(telMsg, 0, sizeof(MAXIMUM_ALLOWED_SIZE));
                  if((GW_STATUS_OK == gw_cloud_ProcessMessage(messageType, data, &telMsg)))
                  {
                    LOG_INFO("Msg JSON: %s", telMsg);
                    if(strlen(telMsg) > 0)
                    {
                      if(gw_cloud_SendMessage(telMsg, messageType) == GW_STATUS_OK)
                      {
                        /*Destorys IoT hub client*/
                        LOG_INFO("Message sent, update tick_counter...");
                        (void)tickcounter_get_current_ms(tick_counter_handle, &last_send_time);
                        if(!cacheLoaded && (CLOUD_MSG_GATEWAY_METADATA == messageType))
                        {
                          /* load persisted cache messages from flash */
                          CLOUD_Cache_Load();
                          LOG_INFO("cache data loaded...");
                          cacheLoaded = true;
                        }
                      }
                      else
                      {
                        LOG_ERROR("Could Not Send the Message");
                      }
                    }
                    else
                    {
                      /***MISRA**/
                    }
                  }
                  else
                  {
                    LOG_ERROR("Could Not Process the Message");
                  }
                }
                else
                {
                  LOG_ERROR("MessageType(%u) or data(%p) invalid", messageType, data);
                }
              }

              /* this releases memory allocated by IHD task for each data item pushed into queue */
              if(data != NULL)
              {
                LOG_DEBUG("Releasing Ptr: %p", data);
                DEALLOC(&data);
              }
            }
          }
          IoTHubClient_LL_DoWork(iothub_client);
        } while (iothub_info.stop_running == false);

        /* release mem */
        DEALLOC(&telMsg);

        /*May Require in the Future
         gw_cloud_PlatformDeinit(iothub_client);*/
      }
      else
      {
        LOG_ERROR("Could Not Allocate Memory for the Message");
      }
    }
  }
=======================================================================

HTTP FOR BLOB STORAGE
=======================================================================
void GW_CLOUD_SetLogToCloudTimer(void)
{
  int32_t logTimer;
  LOG_INFO("========================================");
  LOG_INFO("Creating Timer");
  LOG_INFO("========================================");
  logTimer = GW_TIMER_CreateSecondsTimer(ONESHOT, 1, check);
}

void check(void)
{
static const char* proxyHost = NULL;
static int proxyPort = 0;
long bufsize;
char *source = NULL;
FILE *fp = fopen("logCapture.log", "r");
if (fp != NULL) {
      /* Go to the end of the file. */
     if (fseek(fp, 0L, SEEK_END) == 0) 
  {
        /* Get the size of the file. */
  bufsize = ftell(fp);
        /* Allocate our buffer to that size. */
        source = malloc(sizeof(char) * (bufsize + 1));

        /* Go back to the start of the file. */
        if (fseek(fp, 0L, SEEK_SET) != 0) 
  { /* Handle error here */ 
  }

        /* Read the entire file into memory. */
        size_t newLen = fread(source, sizeof(char), bufsize, fp);
        if (newLen == 0) 
  {
            fputs("Error reading file", stderr);
        } 
  else 
  {
            source[newLen] = '\0'; /* Just to be safe. */
        }
      }
    fclose(fp);
}
    // Used to initialize IoTHub SDK subsystem
    LOG_INFO("Starting the IoTHub client sample upload to blob...\r\n");
    device_ll_handle_check = IoTHubDeviceClient_LL_CreateFromConnectionString(connectionString_secondary, HTTP_Protocol);
    if (device_ll_handle_check == NULL)
    {
        LOG_INFO("Failure createing Iothub device.  Hint: Check you connection string.\r\n");
    }
    else
    {
#ifndef WIN32
        size_t log = 1;
        (void)IoTHubDeviceClient_LL_SetOption(device_ll_handle_check, OPTION_CURL_VERBOSE, &log);
#endif // !WIN32

#ifdef SET_TRUSTED_CERT_IN_SAMPLES
        // Setting the Trusted Certificate.  This is only necessary on system with without
        // built in certificate stores.
        IoTHubDeviceClient_LL_SetOption(device_ll_handle_check, OPTION_TRUSTED_CERT, certificates);
#endif // SET_TRUSTED_CERT_IN_SAMPLES

        HTTP_PROXY_OPTIONS http_proxy_options = { 0 };
        http_proxy_options.host_address = proxyHost;
        http_proxy_options.port = proxyPort;

        if (proxyHost != NULL && IoTHubDeviceClient_LL_SetOption(device_ll_handle_check, OPTION_HTTP_PROXY, &http_proxy_options) != IOTHUB_CLIENT_OK)
        {
          LOG_INFO("failure to set proxy\n");
        }
        else
        {
            if (IoTHubDeviceClient_LL_UploadToBlob(device_ll_handle_check, "Dlink_Dev_Bhargav/Logs1.txt", (const unsigned char*)source, bufsize) != IOTHUB_CLIENT_OK)
            { 
                LOG_INFO("==============================================");
                LOG_INFO("hello world failed to upload\n");
                LOG_INFO("==============================================");
            }
            else
            {
                LOG_INFO("===============================================");
                (void)printf("hello world has been created\n");
                LOG_INFO("===============================================");
            }
        }
        // Clean up the iothub sdk handle
        IoTHubDeviceClient_LL_Destroy(device_ll_handle_check);
    }
    // Free all the sdk subsystem
    //IoTHub_Deinit();

    //printf("Press any key to continue");
    //getchar();

    return;
}
=============================================================================

**Comment by Pavan2358** [comment]
I was able to work it out with same device id for both mqtt and http protocol in the same application

**Comment by az-iot-builder-01** [comment]
@Pavan2358, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
