### ISSUE TITLE
libcrypto.so.1.0.0/ libssl.so.1.0.0: version `OPENSSL_1.0.2d' not found (required by ./Iot_App)  azure iothub_client running on beagle bone balck

### ISSUE THREAD

**Issue by chinnaece** [Azure/azure-iot-sdk-c#711]
- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by chinnaece** [comment]
Hello all,
            I choose Beagle bone black is my target to run Azure iothub_client , i cross compiled  with Ti-sdk of AM335X, when i run this on my target, i got below error in my console !
**Error :**  
root@beaglebone:~/apps# ./Iot_App 
./Iot_App: /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0: version `OPENSSL_1.0.2d' not found (required by ./Iot_App)
./Iot_App: /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0: version `OPENSSL_1.0.2d' not found (required by ./Iot_App)

I Reviewed the error , i came to know that the libraries(libssl,libcrypto) which are in Ti-sdk linked with the  executable are **libssl.so.1.0.2  libcrypto.so.1.0.2** (higher version) . But the same libraries in my target usr/lib/arm-gnueabhf  are  **libssl.so.1.0.0  libcrypto.so.1.0.0** (older version) . is this the problem ?
if this is only the problem how can i resolve that . Please help me .

**Comment by az-iot-builder-01** [comment]
@chinnaece, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by chinnaece** [comment]
1) http://e2e.ti.com/support/processors/f/791/t/246082
please scroll down and find the Franklin Cooper(    Feb 21, 2013 2:10 PM ) Answer in that link .
If you get below error at ./Configure Run below command 
**Error :** [linux-devkit]:~/Downloads/openssl-1.0.1k>  chmod +x configure
chmod: cannot access 'configure': No such file or directory

Run :   chmod +x Configure

2)fallow as usual and finally you will get the cross compiled version libraries.
3) replace all what you find by searching libssl / libcrypto files in the TI-sdk with, what you find in the same search in Openssl cross compiled folder.(libssl.so , libssl.so.1.0.0, ......etc)
4)now the libraries matched successfully code is running .
