### ISSUE TITLE
Branch lts_10_2018 produces 1.2.9 packages

### ISSUE THREAD

**Issue by ling0015** [Azure/azure-iot-sdk-c#720]
# Description of the issue:
Build produces packages with version 1.2.9 on the lts_10_2018 branch. Looks like the commit https://github.com/Azure/azure-iot-sdk-c/commit/7851827648785b666648b2e52caf5075e89a5605#diff-afcc8c2b1312990cf2fc424adae366be needs to be brought over.

Also would it be possible to start creating a tag for each lts branch that will track it?

**Comment by massand** [comment]
@ling0015 - thanks for reporting the issue. We haven't received any recent security fixes for the branch which justified bumping the version specifically on the October LTS branch. We did bump versions on our packages, however, that were released in October. Is there specific tools or general patterns you suggest we review, in reference to the LTS branch tagging suggestion? Are you looking for a new tag per patched version of LTS release (say if we release a hotfix)?

**Comment by ling0015** [comment]
The tags "1.2.10" and "2018-10-03" and lts_10_2018 branch should all refer to the branch that was produced version 1.2.10. 
However, lts_10_2018 will produce packages with version [1.2.9](https://github.com/Azure/azure-iot-sdk-c/blob/lts_10_2018/iothub_client/inc/iothub_client_version.h).
The tag "1.2.10" produce packages with version [1.2.10](https://github.com/Azure/azure-iot-sdk-c/blob/1.2.10/iothub_client/inc/iothub_client_version.h).
The tag "2018-10-03" also produces builds with version [1.2.10](https://github.com/Azure/azure-iot-sdk-c/blob/2018-10-03/iothub_client/inc/iothub_client_version.h).

I would expect that the branch lts_01_2019 and the tags "1.2.14" and "2019-01-31" would also all produce the same build, however in this case the tag 2019-01-31 produces a build with number [1.2.13](https://github.com/Azure/azure-iot-sdk-c/blob/2019-01-31/iothub_client/inc/iothub_client_version.h).

It is very difficult to track down what code was used to build a version when seemingly the version numbers are not well maintained. Is there a method to the madness that I am just not seeing?

It seems that the date and version number tags should be frozen in time. However, the lts_ branch should be able to move with fixes, also there should be a tags prefixed with lts_ that can float to pick up fixes.

**Comment by ewertons** [comment]
Hi @ling0015 ,
indeed we have version issue. We apologize for that.
When we were releasing the LTS version, we should have kept it 1.2.9 and the releases from master should be bumped to 1.3.0.
We will address that in the next release of LTS. If we get to fix it earlier, we will update you here.

**Comment by ewertons** [comment]
Hi @ling0015 ,
so we have made a change, and now master@azure-iot-sdk-c has version [1.3.0](https://github.com/Azure/azure-iot-sdk-c/tree/1.3.0) (next release it will bump to 1.3.1 and so on).

LTS should always be one minor version below, having only the patch numbers increased if any updates are made (i.e., from 1.2.9 to 1.2.10, 1.2.11, ...).

Thanks for bringing this to our attention.

Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@massand, @ling0015, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
