### ISSUE TITLE
Provision group  enrollments can't found Device certificate 

### ISSUE THREAD

**Issue by v-jiq** [Azure/azure-iot-sdk-c#724]
I  want to realize Provision group  enrollments, but i can't found  the  {deviceName}-public.pem and {deviceName}-all.pem certificate mention in this link -- https://docs.microsoft.com/en-us/Azure/iot-dps/tutorial-group-enrollments.

I can't found the above certificate in this link -- https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md.

How can  generate the above certificate, whether had a guide link?

Thanks

**Comment by az-iot-builder-01** [comment]
@v-jiq, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
