### ISSUE TITLE
Multiple Calls to IoTHubDeviceClient_LL_DoWork

### ISSUE THREAD

**Issue by racecannon** [Azure/azure-iot-sdk-c#726]
- **OS and version used:** <VERSION> Ubuntu 18.04

- **SDK version used:** <VERSION> 1.2.7

# Description of the issue:

This issue could be a result of my ignorance on the SDK internal workings. However, when I send messages using MQTT, I call the IoTHubDeviceClient_LL_DoWork function. However, this function, in itself, does not return anything. Instead, I eventually get a response from the send_confirm_callback function. This would be fine, if it were consistent. However, I seem to have to run the IoTHubDeviceClient_LL_DoWork function numerous times before the send_confirm_callback ever executes. If I only call it once, the confirmation callback will never respond. 

# Code sample exhibiting the issue:

The code used to prove this is the iothub_ll_telemtatry_sample, which is included in the SDK.
I only modified it to send one message at a time.

# Console log of the issue:

I don't get any output from the DoWork function. There is no other relevant output.

**Comment by photomoose** [comment]
From what I understand, this is correct behaviour. You are supposed to call IoTHubDeviceClient_LL_DoWork continuously in a loop - I think the recommended frequency is to call it every 100ms. 

See this page for more details: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-c-iothubclient

In the section titled "The lower-level APIs", there is an explanation as to why you have to call it multiple times.

**Comment by racecannon** [comment]
That makes sense. It is not how the SDK implemented the sample code, which is what lead to my confusion. But, calling it every 100ms works much better in my implementation.

**Comment by az-iot-builder-01** [comment]
@photomoose, @racecannon, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
