### ISSUE TITLE
Duplicate ".." in devbox setup

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#728]
In [dev box setup](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md),  we have this:

```
cmake .. -G "Visual Studio 14 2015" ..
```
And something similar one other place.

The extra set of ".." are redundant.

**Comment by jspaith** [comment]
Fixed c07b61a643990af37822858a9f3923ce55d1f9ad.

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
