### ISSUE TITLE
Remote server closing connection not handled in all cases

### ISSUE THREAD

**Issue by vjrantal** [Azure/azure-iot-sdk-c#73]
An example how to reproduce:

* Create a free tier Azure IoT Hub
* Send 8000 messages to the Hub to consume the daily quota
* Run the `iothub_client_sample_mqtt` as is towards the Hub which doesn't allow new messages anymore

Here https://gist.github.com/vjrantal/4f4981466751b19e5b2c939a5f31ba1e is an example output from the error scenario.

~As fix proposal, one possibility might be a change like this:~

```
diff --git a/adapters/socketio_berkeley.c b/adapters/socketio_berkeley.c
index fae59d1..0d92249 100644
--- a/adapters/socketio_berkeley.c
+++ b/adapters/socketio_berkeley.c
@@ -480,7 +480,7 @@ int socketio_send(CONCRETE_IO_HANDLE socket_io, const void* buffer, size_t size,
             }
             else
             {
-                int send_result = send(socket_io_instance->socket, buffer, size, 0);
+                int send_result = send(socket_io_instance->socket, buffer, size, MSG_NOSIGNAL);
```

~and then to handle the connection cut properly and inform the right callback functions about the status so that application code can react as suitable.~

(see updated fix proposal at https://github.com/Azure/azure-iot-sdk-c/issues/73#issuecomment-282228110)

Here http://stackoverflow.com/a/108192 is also relevant discussion about the topic.

**Comment by mm-imr** [comment]
Hello @vjrantal 

I've posted that issue already on 19 Oct 2016, but they won't fix it. 
Here is the ID for this: https://github.com/Azure/azure-iot-sdks/issues/878

Maybe it's time to reopen it because there are more people affected by that issue and the workaround by disable signal handling worked not well.

Best,

Ingo

**Comment by vjrantal** [comment]
@mm-imr Thanks for pointing that out.

After reading the discussion under the linked issue, I have to say I agree with the fact the ignoring the `SIGPIPE` should not be done in the SDK library, but rather in the calling layer. However, having said, the SDK should work properly in case app ignores the signal and based on my testing, that might not be currently happening. Here is the log what happens in that case https://gist.github.com/vjrantal/cf3eb8b0e1ba4d90568c0793630de615.

I believe this is because in case of a send error, we end up to this line:

https://github.com/Azure/azure-c-shared-utility/blob/4461e2b09dd9e854865a53a22da894b1b21235d1/adapters/socketio_berkeley.c#L496

The issue might be that with this code path, the `on_send_complete` is not called. If I am not mistaken, the idea would be that in case of errors, the call should look something like: `on_send_complete(callback_context, IO_SEND_ERROR);`. The reason I suspect this would be the right behavior is that I can see, for example, the following in the requirements:

```
devdoc/tlsio_arduino_requirements.md:**SRS_TLSIO_ARDUINO_21_056: [** if the ssl was not able to send any byte in the buffer, the tlsio_arduino_send shall call the on_send_complete with IO_SEND_ERROR, and return _LINE_. **]**
```

**Comment by anporumb** [comment]
Thank you for reporting this, we will definitely look at it this month (March).

Best Regards,
Andrei Porumb

**Comment by ewertons** [comment]
Hi @vjrantal, the issue you reported has been fixed, and the changes are in master already.

If possible, please verify it by cloning the latest version of master from the repo.

Thank you for reporting the issue.

**Comment by ewertons** [comment]
Thanks for reporting this problem.
Please let us know if you have any further comments or suggestions.
This issue will be closed, but feel free to reopen it if you need.
