### ISSUE TITLE
how to set retry initial_wait_time_in_secs

### ISSUE THREAD

**Issue by larsonmpdx** [Azure/azure-iot-sdk-c#731]
see related issue #256
see https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/connection_and_messaging_reliability.md

after setting the retry policy to something different:
````
size_t iothub_retry_giveup_timer_s = 0;
IoTHubClientCore_LL_SetRetryPolicy(device_ll_handle, IOTHUB_CLIENT_RETRY_INTERVAL, iothub_retry_giveup_timer_s);
````
this does work

then I want to change the retry timer, this code sample doesn't work:
````
size_t iothub_reconnect_period_s = 60;
IoTHubClientCore_LL_SetOption(device_ll_handle, "initial_wait_time_in_secs", &iothub_reconnect_period_s);
````
changing the call to IoTHubDeviceClient_LL_SetOption() also doesn't work (I can't tell which is supposed to be used - this has been refactored since the #256 sample)

both give something like "Error: Time:Tue Nov 27 11:30:20 2018 File:/build/azure-iot-sdk-c-vmxBvx/azure-iot-sdk-c-0.2.0.0/iothub_client/src/iothub_client_core_ll.c Func:IoTHubClientCore_LL_SetOption Line:2214 unable to IoTHubTransport_SetOption"

**Comment by ewertons** [comment]
Hi @larsonmpdx ,
why are you using the IoTHubClientCore* functions?
If you look at the samples, you will see that you are either expected to use:
IoTHubDeviceClient_LL_* functions for Device Client non-threaded functionality,
IoTHubDeviceClient_* functions for Device Client threaded functionality,
IoTHubModuleClient_LL_* functions for Module Client non-threaded functionality,
IoTHubModuleClient_LL_* functions for Module Client threaded functionality.

You should be using IoTHubDeviceClient_LL_* functions by what I see in your post.
Could you try again with the proper public API?

**Comment by larsonmpdx** [comment]
changing the call to IoTHubDeviceClient_LL_SetOption() also doesn't work (I can't tell which is supposed to be used - this has been refactored since the #256 sample)

**Comment by ewertons** [comment]
Have you changed IoTHubClientCore_LL_SetRetryPolicy to IoTHubDeviceClient_LL_SetRetryPolicy as well?

**Comment by ewertons** [comment]
@larsonmpdx ,
so the issue you are reporting is separate from the other issues we are discussing. You should not use *Core* functions directly, please use the public APIs mentioned in my previous comment.

As for "initial_wait_time_in_secs", it is not exposed through the layers, so it is not a publicly supported option as of now.
We will mark this issue as an enhancement.

**Comment by ewertons** [comment]
This issue is related to https://github.com/Azure/azure-iot-sdk-c/issues/618

**Comment by gregman-msft** [comment]
Hi @larsonmpdx, we have implemented this functionality, and it is documented in this file: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Iothub_sdk_options.md You can search for "retry_interval_sec" for the details.

**Comment by az-iot-builder-01** [comment]
@ewertons, @larsonmpdx, @gregman-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by larsonmpdx** [comment]
thanks!
