### ISSUE TITLE
apt-get and source-built libraries have different link requirements

### ISSUE THREAD

**Issue by larsonmpdx** [Azure/azure-iot-sdk-c#742]
see PR #735

prov_auth_client and hsm_security_client cause conflicts with the source-built library but are necessary with the apt-get version

run the docker files in the PR to see this in action, only one can be built at a time because they point to the same cmakelists which needs to be edited one way or the other
````
docker build -t azure_iot_test -f Dockerfile.out_of_tree_build_example .
````

````
docker build -t azure_iot_test -f Dockerfile.out_of_tree_build_example_apt_get .
````

**Comment by jebrando** [comment]
The reason this is the case is that apt-get package has to include all files that are being built into the package.  For source packages you only need the files that you are included.  For example the apt-get packages is include module support for edge and this needs prov_auth_client & hsm_security_client.  I'm guessing that when you build the project you don't include edge module support.  The only way around this is to create multiple packages which will provide confusion.

**Comment by ewertons** [comment]
Hi @larsonmpdx , 
we will close this issue for now, but please feel free to reopen it if you would like to follow up.
Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment]
@larsonmpdx, @jebrando, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
