### ISSUE TITLE
Add srand() call per-thread

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#749]
Many of our samples have legitimate need to invoke `srand()` for seeding because they're generating random data, like temps, for test.

However `iothub_client_sample_module_filter` doesn't need to do this and has caused some confusion RE whether it's required for callers to do this on behalf of the C SDK (they do not).  The module_filter was just a copy/paste issue, which we should cleanup.

Should review other samples while at it to see if other issues like this.

**Comment by jspaith** [comment]
Retitling to slightly broaden scope of this.

Beyond just the sample srand() use, we should also discuss / make sure that we're calling srand() in core code paths.  In particular in the stub function of `UniqueId_Generate` there's a comment that `// TODO: The User will need to call srand before calling this function` but I don't think on the worker thread we're guaranteed to call srand().  

This could impact non Windows/Linux using convenience layer specifically (on \_LL\_ we're calling srand()), but something we should follow up on.  Note that Windows/Linux use OS calls to do guid generation.

**Comment by az-iot-builder-01** [comment]
@jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
