### ISSUE TITLE
Add a way to check on low-level AMQP or MQTT connect failures

### ISSUE THREAD

**Issue by brennantj** [Azure/azure-iot-sdk-c#750]
- **OS and version used:** Linux

- **SDK version used:** release_2018_10_03

# Description of the issue:
The problem to be solved is that the attempt to connect to Azure sometimes fails at the low level, and the low level debug messages make this plain, but nothing is communicated back to the high level functions that we are using. (Either they return void, or the cases where they return an opaque handle only fail when something seriously bad happens, like a malloc failure or null input argument.) Examples would be an unauthorized ConnectionString or bad proxy settings. Without this, much time passes until you find that you can’t send messages; that is your clue that the connection was not opened.

The callback for the Connection Status change is not being invoked here, presumably because it has not yet *changed*.

Looking at the existing Azure APIs, none is quite right for getting at this. Adding a getter for the Connection Status would be one option, though that may be a fair amount of work since the mocking function must also be provided, and tests to validate it.

What I chose to do was to patch the closest of the existing APIs, GetSendStatus. Normally this returns IOTHUB_CLIENT_OK if it is able to get the SendStatus (which is either Idle or Busy, returned as an output parameter). My simple patch was to return IOTHUB_CLIENT_ERROR from the low level IoTHubTransport_AMQP_Common_GetSendStatus() function if transport’s state is not Connected or Connecting.

I think a better choice, if still using the same API signature for GetSendStatus, would be to extend the set of enums from just Idle and Busy to add NotConnected or somesuch. The justification for leaning on this API could be that NotConnected is an indication of "why you can’t Send right now".

# Code sample exhibiting the issue:
My patch, for AMQP over websockets, is provided here. I recommend adding the new enum instead of what I did, but the patch shows the way. I think MQTT will have a similar solution.
[ll_ampq_extensions.patch.txt](https://github.com/Azure/azure-iot-sdk-c/files/2634678/ll_ampq_extensions.patch.txt)

# Console log of the issue:

**Comment by yzhong94** [comment]
@brennantj We are still evaluating when we can tackle this issue.  Can you remind me again of your development timeline?  When do you need this feature by for production?

**Comment by brennantj** [comment]
I asked our management, and their timeline was "yesterday".
This is impacting our smaller IoT devices now, since they can't move from
MQTT to AMQP transport, as we have done for our embedded Linux products.
So our vote for priority would be ASAP.

Best regards,
Tom Brennan, Eaton Corp

**Comment by bikamani** [comment]
Hi @brennantj 

Connection status callback is supposed to inform you anytime you have connection issues. If you are not getting a callback we need to investigate that first and fix it. In GetSendStatus was designed specifically for verifying if there are telemetry messages pending to be sent. So it wouldn't be appropriate place to check for connection status.

Can you tell us about all the cases where you are seeing callback not being invoked?

Thank you.

**Comment by brennantj** [comment]
**Console log of the issue:**
In our corporate network setting, a proxy is required. I have changed the configuration of my device to disable the proxy settings (not use that option when connecting) to cause an attempt to connect to fail, so you can see the low level debug output that I see in that situation.
So starting with 2 messages from my code, then what Azure low-level reports, ending with two lines of my code. Here I have my patch in place for GetSendStatus (that's the state of 3 it reports), otherwise my code would not know/be told that the connection had failed right at the start:

```
Info: iot_open: IoT Hub Connection: HostName=EatonTestIothub1.azure-devices.net;DeviceId=9e2724fa-5634-5771-8e09-4ff16164213e;SharedAccessKey=gd4V5j0/aPHaxFdHy9WaD1jLot7T7SdpZHsGxj6Gr0s=
Debug: iot_open: Connecting to IoT Hub using AMQP Websockets

Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:369 Failure: select failure.
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:769 wait_for_connection failed
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/c-utility/src/wsio.c Func:internal_close Line:150 wsio_close when not open.
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/c-utility/src/uws_client.c Func:uws_client_open_async Line:1684 Opening the underlying IO failed
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/c-utility/src/wsio.c Func:wsio_open Line:516 Opening the uws instance failed.
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/uamqp/src/saslclientio.c Func:saslclientio_open_async Line:1097 xio_open failed
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/uamqp/src/connection.c Func:connection_open Line:1344 Opening the underlying IO failed
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/uamqp/src/link.c Func:link_attach Line:1154 Begin session failed
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/uamqp/src/message_receiver.c Func:messagereceiver_open Line:362 Link attach failed
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/uamqp/src/amqp_management.c Func:amqp_management_close Line:1020 AMQP management instance not open
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/iothub_client/src/iothubtransport_amqp_connection.c Func:on_cbs_open_complete Line:153 CBS open failed
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/uamqp/src/amqp_management.c Func:amqp_management_open_async Line:981 Failed opening message receiver
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/iothub_client/src/iothubtransport_amqp_connection.c Func:create_cbs_handle Line:278 Failed to open the connection with CBS.
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/iothub_client/src/iothubtransport_amqp_connection.c Func:amqp_connection_create Line:421 amqp_connection_create failed (failed creating the CBS handle)
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/iothub_client/src/iothubtransport_amqp_common.c Func:establish_amqp_connection Line:839 Failed establishing connection (failed to create the amqp_connection instance).
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_DoWork Line:1584 AMQP transport failed to establish connection with service.
Error: Time:Thu Feb  7 10:01:12 2019 File:/home/tbrennan/src/stash/bbb/px-toolkit/vendor_source/build/azure/azure-iot-sdk-c-release_2018_10_03/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_GetSendStatus Line:1934 AMQP connection not ready for sending (not connected, state = 3).

Error: initializeConnection: Failed to make low-level connection.
Error: iot_open: Failed to create connection

```

**Comment by az-iot-builder-01** [comment]
@brennantj, @bikamani, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by brennantj** [comment]
I didn't mean to close the issue; misunderstood what "Comment and close" meant.

**Comment by brennantj** [comment]
There is no evidence of a ConnectionStatusCallback() in my logged output. Presumably because it hasn't changed status - was closed before I tried, is still closed after the attempt failed.

**Comment by brennantj** [comment]
By contrast, here's a successful connection; you can see that the ConnectionStatusCallback has been called here:

```
Info: iot_open: IoT Hub Connection: HostName=EatonTestIothub1.azure-devices.net;DeviceId=9e2724fa-5634-5771-8e09-4ff16164213e;SharedAccessKey=...
Debug: iot_open: Connecting to IoT Hub using AMQP Websockets
Info: initializeConnection: Setting proxy options for proxy.etn.com

Info: AMQP connection still being established.
Info: initializeConnection: Low-level Connection established now.
...
Info: Provisional success opening IoT Connection.
...
Info: handleConnectionStatusCallback: Connection Status Received, Result: 0, Reason: 6
...
Info: (Tentatively) Confirmed valid connection to IoT Hub.
```

**Comment by bikamani** [comment]
Hi @brennantj  Thanks for your patience and for the logs, as noticed this is a bug in AMQP and not MQTT. I will be working on providing a fix for IOTHUB_CLIENT_CONNECTION_NO_NETWORK callback not seen in AMQP here.

**Comment by yzhong94** [comment]
@brennantj This [PR ](https://github.com/Azure/azure-iot-sdk-c/pull/848)contains the fix for AMQP.  Please try the latest master bits and let us know if this works for you.

**Comment by brennantj** [comment]
@bikamani @yzhong94 Just tried out this patch to release_2019_02_11 and I can confirm that it does invoke the callback to inform us of the change to IOTHUB_CLIENT_CONNECTION_NO_NETWORK when the initial atttempt to connect fails.
So I will close this issue. 
Thank you for the fix!
