### ISSUE TITLE
unable to set x509 options more than once error when using x509 for file uploads

### ISSUE THREAD

**Issue by ling0015** [Azure/azure-iot-sdk-c#753]
- **OS and version used:** <VERSION> 
Ubuntu 16.04
- **SDK version used:** <VERSION> 
1.2.11
- **Issue**
When using x509 authentication for file uploads, the sdk attempts to use the certificates that were used for creating the main connection to azure, in our case amqp-ws, for setting up the new http connection. In order to do this, it performs a set option on the iothub_client_handle, the sdk then attempts to call IoTHubTransport_SetOption in addition to IoTHubClient_LL_UploadToBlob_SetOption. This results in the following errors:
azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_setoption Line:1504 unable to set x509 options more than once
azure-iot-sdk-c/c-utility/src/uws_client.c Func:uws_client_set_option Line:2078 xio_setoption failed.
azure-iot-sdk-c/c-utility/src/wsio.c Func:wsio_setoption Line:691 Setting the option x509certificate failed
azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_SetOption Line:2123 transport failed setting option 'x509certificate' (xio_setoption failed)
azure-iot-sdk-c/iothub_client/src/iothub_client_core_ll.c Func:IoTHubClientCore_LL_SetOption Line:2246 unable to IoTHubTransport_SetOption
azure-iot-sdk-c/iothub_client/src/iothub_client_core.c Func:IoTHubClientCore_SetOption Line:1620 IoTHubClientCore_LL_SetOption failed
azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_setoption Line:1525 unable to set more than once x509 options
azure-iot-sdk-c/c-utility/src/uws_client.c Func:uws_client_set_option Line:2078 xio_setoption failed.
azure-iot-sdk-c/c-utility/src/wsio.c Func:wsio_setoption Line:691 Setting the option x509privatekey failed
azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_SetOption Line:2123 transport failed setting option 'x509privatekey' (xio_setoption failed)
azure-iot-sdk-c/iothub_client/src/iothub_client_core_ll.c Func:IoTHubClientCore_LL_SetOption Line:2246 unable to IoTHubTransport_SetOption
azure-iot-sdk-c/iothub_client/src/iothub_client_core.c Func:IoTHubClientCore_SetOption Line:1620 IoTHubClientCore_LL_SetOption failed

- **Solution**
The following patch isn't suggested as a long term solution, however, it works to show that x509 authentication works with file uploads.
```
diff --git a/c-utility b/c-utility
--- a/c-utility
+++ b/c-utility
@@ -1 +1 @@
-Subproject commit 9492af7317a1d9eb88cb5659af48338dfc21676e
+Subproject commit 9492af7317a1d9eb88cb5659af48338dfc21676e-dirty
diff --git a/iothub_client/src/iothub_client_core_ll.c b/iothub_client/src/iothub_client_core_ll.c
index dddcfb2..cc48cf4 100755
--- a/iothub_client/src/iothub_client_core_ll.c
+++ b/iothub_client/src/iothub_client_core_ll.c
@@ -2238,9 +2238,13 @@ IOTHUB_CLIENT_RESULT IoTHubClientCore_LL_SetOption(IOTHUB_CLIENT_CORE_LL_HANDLE
             // This section is unusual for SetOption calls because it attempts to pass unhandled options
             // to two downstream targets (IoTHubTransport_SetOption and IoTHubClientCore_LL_UploadToBlob_SetOption) instead of one.
 
-            result = handleData->IoTHubTransport_SetOption(handleData->transportHandle, optionName, value);
+            result = IOTHUB_CLIENT_OK;

+            if((strcmp(optionName, OPTION_X509_CERT) != 0) && (strcmp(optionName, OPTION_X509_PRIVATE_KEY) != 0))
+            {
+               result = handleData->IoTHubTransport_SetOption(handleData->transportHandle, optionName, value);
+            }
             if(result != IOTHUB_CLIENT_OK)
             {
                 LogError("unable to IoTHubTransport_SetOption");
```

- **Desired Solution**
Instead of fighting/implementing different security schemes for each feature, it would be desirable to be able to authenticate once, then get a session token that can be reused for other features.

**Comment by ewertons** [comment]
Hi @ling0015 ,

we took a look at your code above.

Unfortunately it does not align well with all the functionality of the transports. 

This will require more investigation. We will update it according to our availability, since it is an enhancement.

**Comment by gregman-msft** [comment]
Thank you for the feedback. This will require new work on the blob storage support that we are transitioning to a new repository. I have opened up a request on your behalf in this repository [here](https://github.com/Azure/azure-sdk-for-c/issues/102). Please track the request there and feel free to add any additional comments.

**Comment by az-iot-builder-01** [comment]
@ling0015, @ewertons, @gregman-msft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
