### ISSUE TITLE
Building simple sample of new system fails

### ISSUE THREAD

**Issue by dwhiteddsoft** [Azure/azure-iot-sdk-c#755]
Win10 OS with VS 2017 15.9.3 and CMake 3.13.1
Trying to build telemetry message sample and open iothub_client\samples\iothub_ll_telemetry_sample\windows\iothub_ll_telemetry_sample.sln. It is my understanding as part of the build, NuGet Package Manager will download packages for dependencies so you don't have to build the entire SDK. See windows\packages.config for the list of packages that will be downloaded. What happens is when I build is all of the include files for IoT hub cannot be found
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "iothub.h"	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	11	
Error (active)	E1696	cannot open source file "iothub_device_client_ll.h"	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	12	
Error (active)	E1696	cannot open source file "iothub_client_options.h"	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	13	
Error (active)	E1696	cannot open source file "iothub_message.h"	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	14	
Error (active)	E1696	cannot open source file "azure_c_shared_utility/threadapi.h"	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	15	
Error (active)	E1696	cannot open source file "azure_c_shared_utility/crt_abstractions.h"	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	16	
Error (active)	E1696	cannot open source file "azure_c_shared_utility/shared_util_options.h"	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	17	
Error (active)	E1696	cannot open source file "iothubtransportmqtt.h"	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	36	
Error (active)	E0020	identifier "bool" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	58	
Error (active)	E0020	identifier "true" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	58	
Error (active)	E0020	identifier "IOTHUB_CLIENT_CONFIRMATION_RESULT" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	61	
Error (active)	E0020	identifier "IOTHUB_CLIENT_CONFIRMATION_RESULT" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	66	
Error (active)	E0020	identifier "IOTHUB_CLIENT_CONNECTION_STATUS" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	69	
Error (active)	E0020	identifier "IOTHUB_CLIENT_CONNECTION_STATUS_REASON" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	69	
Error (active)	E0020	identifier "IOTHUB_CLIENT_CONNECTION_AUTHENTICATED" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	74	
Error (active)	E0020	identifier "IOTHUB_CLIENT_TRANSPORT_PROVIDER" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	86	
Error (active)	E0020	identifier "IOTHUB_MESSAGE_HANDLE" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	87	
Error (active)	E0020	identifier "MQTT_Protocol" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	93	
Error (active)	E0020	identifier "IOTHUB_DEVICE_CLIENT_LL_HANDLE" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	111	
Error (active)	E0020	identifier "bool" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	125	
Error (active)	E0020	identifier "true" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	125	
Error (active)	E0020	identifier "OPTION_LOG_TRACE" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	126	
Error (active)	E0020	identifier "false" is undefined	iothub_ll_telemetry_sample	C:\Users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	173	
Error	C1083	Cannot open include file: 'iothub.h': No such file or directory	iothub_ll_telemetry_sample	c:\users\davwhite\source\repos\azure-iot-sdk-c\iothub_client\samples\iothub_ll_telemetry_sample\iothub_ll_telemetry_sample.c	11

**Comment by yzhong94** [comment]
@massand we can close this issue with the fix you checked in right?

**Comment by az-iot-builder-01** [comment]
@dwhiteddsoft, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by massand** [comment]
@yzhong94 @dwhiteddsoft - I closed the issue since our samples under the windows folders should just work. I have added a warning to each package that states the steps to perform to grab the vcpkg. If the steps don't work, please reopen this issue. Thanks!
