### ISSUE TITLE
Server unavailable when using x.509 and MQTT over Websockets

### ISSUE THREAD

**Issue by koalo** [Azure/azure-iot-sdk-c#756]
Using the `iothub_ll_client_x509_sample` results in a `0x3: Server Unavailable` error when using MQTT over Websockets. That is not the case for plain MQTT. Also, the `iothub_ll_telemetry_sample` works correctly for both MQTT over Websockets and plain MQTT.

- **OS and version used:** Ubuntu 18.04.1 and up-to-date Gentoo 

- **SDK version used:** Master branch @ 5ca3c6f 

# Console log of the issue
```
$ ./iothub_client/samples/iothub_ll_client_x509_sample/iothub_ll_client_x509_sample 
Creating IoTHub handle
Sending message 1 to IoTHub
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
Error: Time:Wed Dec  5 21:25:16 2018 File:/home/koalo/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1616 Connection Not Accepted: 0x3: Server Unavailable
Error: Time:Wed Dec  5 21:25:17 2018 File:/home/koalo/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1616 Connection Not Accepted: 0x3: Server Unavailable
Error: Time:Wed Dec  5 21:25:19 2018 File:/home/koalo/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1616 Connection Not Accepted: 0x3: Server Unavailable
Error: Time:Wed Dec  5 21:25:23 2018 File:/home/koalo/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1616 Connection Not Accepted: 0x3: Server Unavailable
```
# Steps to reproduce

* [Perform the described steps to generate and set up development CA certificates](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md).
* Insert the resulting `private/new-device.key.pem` into the `x509privatekey` variable of the `iothub_client/samples/iothub_ll_client_x509_sample/iothub_ll_client_x509_sample.c`
* Do the same with the `certs/new-device-full-chain.cert.pem` and the `x509certificate`
* Set the `connectionString` to `HostName=<host_name>;DeviceId=<device_id>;x509=true`
* Uncomment `SAMPLE_MQTT`, build and run --> Does not result in an error
* Uncomment `SAMPLE_MQTT_OVER_WEBSOCKETS` instead, build and run --> Results in the error shown above

**Comment by jebrando** [comment]
@koalo I was unable to recreate this issue with x509 certificate.  If you see this error any more, please reopen or open a new issue.

**Comment by az-iot-builder-01** [comment]
@koalo, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
