### ISSUE TITLE
Upload to Blob returns 400 in step3

### ISSUE THREAD

**Issue by raycon94** [Azure/azure-iot-sdk-c#757]
- **OS and version used:** Keil RTX v4 

- **SDK version used:** 1.2.10 

# Description of the issue:

Hello, 

I am uploading some files to the Blob-Storage over IoTHubDeviceClient_LL_UploadMultipleBlocksToBlob. Everything works fine, the files are uploaded to the Blob. But I always get 400 "Bad Request"  as Response from the Server in IoTHubClient_LL_UploadToBlob_step3 in Line 727, why I get this Response? 
# Code

Description: this function gets our newest log file and starts the azureblob-client
    
    int UploadLogFile()
    {
        /* buffer for the logfile name and path */
        char aFilePath[CDataLogger::m_ui8FilePathStringSize] = {0};
        char aFileName[CDataLogger::m_ui8FileNameStringSize] = {0};
        
        uint64_t ui64ActFileSize = 0;
        static uint32_t ui32ActFileNumber = 0;
        uint16_t ui16ActFilesInFolder = 0;
        
        
        bool bFound = CDataLogger::GetNewestFile(&aFileName[0], &ui32ActFileNumber, &ui64ActFileSize, &ui16ActFilesInFolder);
        
        if(bFound == true)
        {
            /* build the total url*/
            CDataLogger::setFilePath(aFileName,aFilePath);   
            AzureUploadToBlob((const char*)aFilePath, (const char*)aFileName);        
        }
    }

Description: this function was taken from the example-code: https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_upload_to_blob_mb/iothub_client_sample_upload_to_blob_mb.c

    int AzureUploadToBlob(const char* aFilePath, const char* aFileName)
    {
        int iRetval = -1;
        IOTHUB_DEVICE_CLIENT_LL_HANDLE device_ll_handle;
        FILE *pData = NULL;
        size_t timeout = 6000;
        
        device_ll_handle = IoTHubDeviceClient_LL_CreateFromConnectionString(connectionString, HTTP_Protocol);    
        if (device_ll_handle != NULL)
        {
            IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_TRUSTED_CERT, certificates);
            //IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_HTTP_TIMEOUT, &timeout);
            pData = fopen(aFilePath,"r");     
            if(pData != NULL)
            {
            
                bDoOnce = false;
                if (IoTHubDeviceClient_LL_UploadMultipleBlocksToBlob(device_ll_handle, aFileName, getDataCallback, (void*)pData) == IOTHUB_CLIENT_OK)
                {
                    iRetval = 1;
                }
                else
                {       
                    iRetval = -1;
                }
                
                fclose(pData);
            }
            else
            {
                iRetval = -1;
            }     
            
            // Clean up the iothub sdk handle
            IoTHubDeviceClient_LL_Destroy(device_ll_handle);
        }
        else
        {
            iRetval = -1;
        }
        
        return iRetval;
    }

    static IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_RESULT getDataCallback(IOTHUB_CLIENT_FILE_UPLOAD_RESULT result, unsigned char const ** data, size_t* size, void* context)
    {
        
        FILE *logdata = static_cast<FILE*>(context);
        uint16_t ui16DataRead = 0;
        if (result == FILE_UPLOAD_OK)
        {
            if (data != NULL && size != NULL)
            {           
                ui16DataRead = fread((char*)buffer, sizeof(char), MAX_BLOCK_SIZE, logdata);
                if(ui16DataRead > 0)
                {                
                    bDoOnce = true;
                    *data = "test test";//(const unsigned char*)buffer;
                    *size = 9;//ui16DataRead;
                }
                else
                {
                    // This simulates reaching the end of the file. At this point all the data content has been uploaded to blob.
                    // Setting data to NULL and/or passing size as zero indicates the upload is completed.
                    *data = NULL;
                    *size = 0;
                }
            }
            else
            {        
                /* upload ok, next file */
                // The last call to this callback is to indicate the result of uploading the previous data block provided.
                // Note: In this last call, data and size pointers are NULL.
            }
        }
        // This callback returns IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_OK to indicate that the upload shall continue.
        // To abort the upload, it should return IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_ABORT
        return IOTHUB_CLIENT_FILE_UPLOAD_GET_DATA_OK;
    }

# Console log of the issue:

Http-Response-Body: iothub-errorcode: InvalidFileUploadCompletionStatus

**Comment by Pavan2358** [comment]
Hi @raycon94,

You are getting 400 bad request error because your IoT hub is not linked to Storage Account in azure portal.
1) create storage account in same resource group as IoT hub and create a container under blobs option
2) Got to IoT hub->File Upload and add Storage account and Container names
3)Run your program, It should upload

**Comment by raycon94** [comment]
Hi @Pavan2358,

thanks for your answer. Already done. The Files are uploaded to the Blob-Storage. But the Hub Responses with 400 bad request after every finished file upload.

**Comment by jebrando** [comment]
@raycon94 I have just refactor this code can you please try it again and let me know if you still are seeing the 400.

**Comment by raycon94** [comment]
Hello @jebrando ,

yes, still the same response after the file has been completed.

**Comment by jkhax0r** [comment]
@jebrando Has there been any resolution on this issue or anybody know a work-around?  I think I'm seeing the same error - haven't dug in much yet, but figured I'd google around first and saw this thread that seems 100% the same.    On an embedded system running STM32, LwIP, and mbedTLS.

**Comment by ewertons** [comment]
Hi @raycon94 ,
please when you have a chance to follow up on the comment from @jebrando, please post the curl verbose logs so we can assist further.

@jkhax0r , do you have any logs from your HTTP stack?

**Comment by ewertons** [comment]
@raycon94 , we will close this issue for now, but please feel free to reopen it if you would like to follow up.

Thanks,
Azure IoT SDKs Team

**Comment by az-iot-builder-01** [comment]
@Pavan2358, @raycon94, @jebrando, @jkhax0r, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by Abhi2109** [comment]
I am seeing this issue again
