### ISSUE TITLE
SetOption for Sleep timeout in convenience layer

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-sdk-c#758]
In https://github.com/Azure/azure-iot-sdk-c/issues/648 , we've got feedback about CPU usage in convenience layer of SDK.  The issue is that we have a loop running through all the pending items in IoT SDK and we're only sleeping for 1 millisecond between runs.

The workaround today is to use the _LL_ layer, in which the caller controls the loop.  

A better solution though would be to have a SetOption() to allow the caller to specify the sleep timeout.

**Comment by YoDaMa** [comment]
To address this I've created a branch and submitted a [PR here](https://github.com/Azure/azure-iot-sdk-c/pull/813).

**Comment by YoDaMa** [comment]
This is addressed in https://github.com/Azure/azure-iot-sdk-c/pull/813

**Comment by az-iot-builder-01** [comment]
@jspaith, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
