### ISSUE TITLE
When sending fails, MQTT client goes to the unknown error code path

### ISSUE THREAD

**Issue by vjrantal** [Azure/azure-iot-sdk-c#76]
If sending fails, for example, in a scenario like https://github.com/Azure/azure-iot-sdk-c/issues/73 the MQTT client ends up logging `INTERNAL ERROR: unexpected error value received`.

This is because in `mqtt_client.c`, the error is returned like this:

```
        else if (send_result == IO_SEND_ERROR)
        {
            LOG(AZ_LOG_ERROR, LOG_LINE, "MQTT Send Complete Failure send_result: %d", (int)send_result);
            set_error_callback(mqtt_client, MQTT_CLIENT_COMMUNICATION_ERROR);
        }
```

And in `iothubtransport_mqtt_common.c` that error is considered unknown:

```
            case MQTT_CLIENT_COMMUNICATION_ERROR:
            case MQTT_CLIENT_UNKNOWN_ERROR: 
            {
                LogError("INTERNAL ERROR: unexpected error value received %s", ENUM_TO_STRING(MQTT_CLIENT_EVENT_ERROR, error));
            }
```

Sending data through a socket may fail for various reasons and one option for better handling of this scenario might be to try to reconnect.

**Comment by anporumb** [comment]
Hello @vjrantal ,

Thank you for your report. We will look at it this month (march).

best Regards,
Andrei Porumb

**Comment by ewertons** [comment]
Hello @vjrantal ,
I looked at your report and the PR you submitted.

As per the current code 0045d2f1d471a0fde3cbf660732a85ff190dc026, the logic in iothubtransport_mqtt_common.c is (for the scenario you are mentioning):

1. `mqtt_error_callback` is invoked with MQTT_CLIENT_COMMUNICATION_ERROR
2. `transport_data->isConnected` is set to **false**;
3. Next call to `IoTHubTransport_MQTT_Common_DoWork` invokes `InitializeConnection`;
4. `InitializeConnection` will then try to reconnect (through `SendMqttConnectMsg`)
> note that isRecoverableError is true by default

So in that case the retry will be attempted.

And the PR you submitted only adds a log trace (which prints info already logged in that function).

**Comment by ewertons** [comment]
We still need to investigate #73 , which will be done next.
I would suggest closing this issue (#76) and tackle the other one.

If you have any comments or questions about the explanation above, or if there was some other point missed on the issue description, please let us know.

**Comment by vjrantal** [comment]
@ewertons Without the PR, the execution goes to this line:

```
LogError("INTERNAL ERROR: unexpected error value received %s", ENUM_TO_STRING(MQTT_CLIENT_EVENT_ERROR, error));
```

In my opinion, that isn't necessarily the best error to be logged in a scenario that is relatively commonly expected to happen (at least in environments where the device is behind unreliable connection).

Do you see any downside if the PR is accepted as it is?

**Comment by ewertons** [comment]
Hi @vjrantal , we understand your request but we are focusing on issues which have higher priority at this moment.

If #76 requires any changes we will consider adding your change.
