### ISSUE TITLE
Desired twin updates gets reverted when a connection is restored

### ISSUE THREAD

**Issue by gmileka** [Azure/azure-iot-sdk-c#775]
- Windows 10.0.17763.194
- Azure C-SDK 1.2.10

# Description of the issue:
I’m seeing a very weird issue – basically, I do the following:
 
- Client gets connected and receives the full device twin as expected.
- Iunplug the network cable of the device. 
   - The client SDK output shows that it lost connectivity and is retrying. The pause between each try increases as expected.
- I update the device twin desired properties using Device Explorer. 
    - Hitting refresh shows the new values as expected.
- I plug-in the network cable again. 
    - The client SDK output shows that it regained connectivity.
    - I wait a few seconds, and it successfully gets the entire device twin again.
 
Now, at this point, I expect to get the updates I made in #3 – however, I get the old version. Moreover, if I look at the desired properties using Device Explorer, I see my changes from #3 got reverted. The version stamp remains the same – but the values are the old one.

**Comment by ewertons** [comment]
Hi @gmileka ,
Are you using a custom application or one of our samples (e.g., https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_device_twin_and_methods_sample)?

Are you using AMQP or MQTT transport?

**Comment by gmileka** [comment]
Hi @ewertons,

I'm using a custom application.

I'm using AMQP.

**Comment by ewertons** [comment]
Hi @gmileka,

this is indeed a bug. For reference, when the amqp twin messenger is stopped, it doesn't reset itself to re-subscribe for Twin messages when it get started again (when the client eventually reconnects to Azure IoT Hub).
I am working on getting the fix rolled out.

**Comment by ewertons** [comment]
Hi @gmileka ,
this issue was fixed by this PR: https://github.com/Azure/azure-iot-sdk-c/pull/965

Thanks for contributing to Azure IoT SDKs.

**Comment by az-iot-builder-01** [comment]
@ewertons, @gmileka, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
