### ISSUE TITLE
 Unable to connect to the remote server - While getting device twin

### ISSUE THREAD

**Issue by kudlatiger** [Azure/azure-iot-sdk-c#777]
I have following code deployed on the device which is of OS - **Windows Embedded Standard**

    using Microsoft.Azure.Devices.Client
       
    ConfigHubClient = DeviceClient.CreateFromConnectionString(deviceConnectionString, TransportType.Mqtt_WebSocket_Only);
    var twin = await ConfigHubClient.GetTwinAsync();
    TwinCollection deviceTwinConfig;
    deviceTwinConfig = twin.Properties.Desired;`

It's working totally fine locally (Windows 7 OS) but not on **Windows Embedded Standard**

It returns below exception message

> Unable to connect to the remote server

- I have all the basic certificate available on the device. 
- I have .NET Core self contained deployment on the target OS
- Same code working fine in some other device with same configuration!

So now how do I troubleshoot?

**IMPORTANT NOTE**

I have written small application to troubleshoot. I created a code which reads only the device twin but this time I used **RegistryManager** from Microsoft.Azure.Devices.Client and **did not specify any TransportType** . This connects without any issue!

Anything to do with Mqtt_WebSocket_Only?

**Comment by jebrando** [comment]
@kudlatiger This looks like you are using the c# SDK and these issues are for the C SDK.  Please open this issue under this [sdk](https://github.com/Azure/azure-iot-sdk-csharp)

**Comment by az-iot-builder-01** [comment]
@kudlatiger, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
