### ISSUE TITLE
Need to upgrade to SDK1.2.0 which is not supported by iot-hub sdk

### ISSUE THREAD

**Issue by ruthpozuelo** [Azure/azure-iot-sdk-c#78]
Hi,
 We have built an application on the azure-iot-sdk-c SDK for TI-RTOS
 (CC3200) platform. Our code is based on the simplesample_http serializer example for tirtos.

We need now to upgrade to CC3200SDK version 1.2.0 in order to use AP provisioning, but the iot-sdk requires version 1.1.0.

We need help to make the iot-hub work with TI SDK 1.2.0. Are you planning to update the library?
 /Ruth

**Comment by anporumb** [comment]
Hello @ruthpozuelo ,

Can you please explain us what is exactly the failure here? With using 1.2.0?

Best Regards,
Andrei Porumb

**Comment by ruthpozuelo** [comment]
Hi @anporumb ,
We have solved the issue for now, I will let you know if we have problems moving forward. Sometimes you only need to ask to get an answer, thanks!
/Ruth

**Comment by arnsoft** [comment]
Hello ,
Is there any progress in updating the sdk for CC3200SDK_1.2.0 ?
