### ISSUE TITLE
The serializer lib support  UTF-8? Encode faild when add Chinese string to the payload

### ISSUE THREAD

**Issue by cloverclose3** [Azure/azure-iot-sdk-c#780]
- **OS and version used:** <VERSION> 
Mac OS

- **SDK version used:** <VERSION> 
git tag       : 2018-12-13
commit id : 350b51f5abaedc975dae5419ad1fa4add7635fd2

# Description of the issue:

Hi all! I have just test the serializer demo located at `azure-iot-sdk-c/cmake/serializer/samples/simplesample_mqtt`. I just modify 3 lines which as follows:
```c
...
static const char* connectionString = "my connection string ofcurse balabala...";
...

DECLARE_MODEL(ContosoAnemometer,
WITH_DATA(ascii_char_ptr, DeviceId),
WITH_DATA(int, WindSpeed),
WITH_DATA(float, Temperature),
WITH_DATA(float, Humidity),
WITH_DATA(ascii_char_ptr, Desc),        /* add a new element to model */
WITH_ACTION(TurnFanOn),
WITH_ACTION(TurnFanOff),
WITH_ACTION(SetAirResistance, int, Position)
);
...

myWeather->DeviceId = "myFirstDevice";
myWeather->WindSpeed = avgWindSpeed + (rand() % 4 + 2);
myWeather->Temperature = minTemperature + (rand() % 10);
myWeather->Humidity = minHumidity + (rand() % 20);
myWeather->Desc = "这是测试";         /* just a chinese sentense, encoded by UTF-8 */
{
       unsigned char* destination;
       size_t destinationSize;
        if (SERIALIZE(&destination, &destinationSize, myWeather->DeviceId, myWeather->WindSpeed, myWeather->Temperature, myWeather->Humidity, myWeather->Desc) != CODEFIRST_OK)
         {
                (void)printf("Failed to serialize\r\n");
          }
         else
          {
                 sendMessage(iotHubClientHandle, destination, destinationSize, myWeather);
                 free(destination);
          }
}
```
compile ok, run failed! The log shows encoding the module failed:
```
Error: Time:Wed Dec 19 11:36:46 2018 File:/Users/stv/azure-iot-sdk-c/serializer/src/agenttypesystem.c Func:AgentDataTypes_ToString Line:1862 (result = AGENT_DATA_TYPES_INVALID_ARG)
Error: Time:Wed Dec 19 11:36:46 2018 File:/Users/stv/azure-iot-sdk-c/serializer/src/jsonencoder.c Func:JSONEncoder_EncodeTree Line:149 (result = JSON_ENCODER_TOSTRING_FUNCTION_ERROR)
Error: Time:Wed Dec 19 11:36:46 2018 File:/Users/stv/azure-iot-sdk-c/serializer/src/datamarshaller.c Func:DataMarshaller_SendData Line:187 (result = DATA_MARSHALLER_JSON_ENCODER_ERROR)
Error: Time:Wed Dec 19 11:36:46 2018 File:/Users/stv/azure-iot-sdk-c/serializer/src/datapublisher.c Func:DataPublisher_EndTransaction Line:270 (result = DATA_PUBLISHER_MARSHALLER_ERROR)
Error: Time:Wed Dec 19 11:36:46 2018 File:/Users/stv/azure-iot-sdk-c/serializer/src/iotdevice.c Func:Device_EndTransaction Line:226 (result = DEVICE_DATA_PUBLISHER_FAILED)
Error: Time:Wed Dec 19 11:36:46 2018 File:/Users/stv/azure-iot-sdk-c/serializer/src/codefirst.c Func:CodeFirst_SendAsync Line:1351 (result = CODEFIRST_DEVICE_PUBLISH_FAILED)
Failed to serialize
```
If I delete the chinese sentense, it will run successfully as expected. 

# Console log of the issue:
Do the serializer lib support  UTF-8 or not? Or should i do some special processing with these chinese sentense before i upload? In my application, i need to upload some chinese strings! How can I do?  Thanks!

**Comment by jebrando** [comment]
@cloverclose3 currently we don't support UTF-8 in the serializer.  In the future we may add features to better support Chinese characters

**Comment by jspaith** [comment]
Hi @cloverclose3  - actually for the serializer, it's not something we're making continued enhancements in per the documentation at https://github.com/Azure/azure-iot-sdk-c/blob/master/serializer/readme.md and in particular "We will continue to fix critical serializer bugs, but we do not plan on adding additional features to the serializer."

To see what a sample of parsing json in the C SDK without the serializer entails - where you'll have full control - please see [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_device_twin_and_methods_sample/iothub_client_device_twin_and_methods_sample.c).

Hope this helps and if you have questions on the sample in particular (or anything else across C SDK of course) by all means file additional issues.

**Comment by az-iot-builder-01** [comment]
@cloverclose3, @jebrando, @jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
