### ISSUE TITLE
OPTION_TRUSTED_CERT not included in header files

### ISSUE THREAD

**Issue by ukluk** [Azure/azure-iot-sdk-c#781]
Set the switch `SET_TRUSTED_CERT_IN_SAMPLES` and the compiler won't be able to resolve symbol `OPTION_TRUSTED_CERT`.
Couldn't find the implementation handler for the `IoTHubDeviceClient_LL_SetOption` for this particular option

**Comment by ewertons** [comment]
Hi @ukluk , could you please fill all the details that were presented in the github issue template for us to assist you? Thanks.

**Comment by jebrando** [comment]
@ukluk The Option `OPTION_TRUSTED_CERT` is defined in file "azure_c_shared_utility\shared_util_options.h".  All the samples should have this file included.

**Comment by az-iot-builder-01** [comment]
@ukluk, @ewertons, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
