### ISSUE TITLE
Error: Time:File:/home/test/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2229 mqtt_client timed out waiting for CONNACK

### ISSUE THREAD

**Issue by chinnaece** [Azure/azure-iot-sdk-c#782]
**OS**:Linux
**SDK Version** : 2018-12-13

### **Description of the issue:**
**iothub_ll_telemetry_sample.c** 
when i placed 60000 in the function **ThreadAPI_Sleep(60000)** works well but  Tried with 120000 facing the timeout error.

 IoTHubDeviceClient_LL_DoWork(device_ll_handle);
 ThreadAPI_Sleep(120000);

cd ~/azure-iot-sdk-c/cmake/iothub_client/samples/iothub_ll_telemetry_sample
$ ./iothub_ll_telemetry_sample

**Console log of the issue:**
Creating IoTHub Device handle
Sending message 1 to IoTHub
Sending message 2 to IoTHub
Error: Time:Fri Dec 21 11:12:19 2018 File:/home/test/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2229 mqtt_client timed out waiting for CONNACK
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Error: Time:Fri Dec 21 11:16:19 2018 File:/home/test/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2229 mqtt_client timed out waiting for CONNACK
Sending message 5 to IoTHub
Error: Time:Fri Dec 21 11:18:19 2018 File:/home/test/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2229 mqtt_client timed out waiting for CONNACK
Error: Time:Fri Dec 21 11:20:19 2018 File:/home/test/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2229 mqtt_client timed out waiting for CONNACK
Error: Time:Fri Dec 21 11:22:19 2018 File:/home/test/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2229 mqtt_client timed out waiting for CONNACK
Error: Time:Fri Dec 21 11:24:19 2018 File:/home/test/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2229 mqtt_client timed out waiting for CONNACK
Error: Time:Fri Dec 21 11:26:19 2018 File:/home/test/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2229 mqtt_client timed out waiting for CONNACK

**Note:**
**_In previous version you said it's resolved but here it's not working form me. Please Explain me where is the problem._**

**Comment by lakshmisivareddy** [comment]
Hi @chinnaece 
if you are tiring to sleep main thread for 2min which is responsible for IoT Hub connection you will get timeout error. don't sleep the thread

**Comment by chinnaece** [comment]
> Hi @chinnaece
> if you are tiring to sleep main thread for 2min which is responsible for IoT Hub connection you will get timeout error. don't sleep the thread

what can i do then ? Suggest me the way .

**Comment by jebrando** [comment]
@chinnaece you will need to call IoTHubDeviceClient_LL_DoWork(device_ll_handle); periodically.  Ideally you should call it at least once a second (ThreadAPI_Sleep(1000) ), with sub-millisecond calls be better.  The DoWork function is what keeps the network connection alive and also handles keep alive for the protocols.  Only calling DoWork every 2 min will have negative consequences since network traffic will not have the proper timing and probably won't work successfully.  Change the timing to a more reasonable value and it should work.

**Comment by chinnaece** [comment]
@jebrando Suppose, if i want to send the telemetry for every 15 minutes to hub then how can i use this  IoTHubDeviceClient_LL_DoWork(device_ll_handle) , in that case i can not run it for every second right?

**Comment by chinnaece** [comment]
Problem has solved by running  **IoTHubDeviceClient_LL_DoWork(device_ll_handle);** API in a different thread  for every seconds (upto 30 sec works for me) . I put (void)IoTHubDeviceClient_LL_SendEventAsync(mpDeviceHandle, message_handle1, SendConfirmCallback, NULL); API in other thread which will run for the rate what we want .
thanks for your valuable suggestion @jebrando @lakshmisivareddy

**Comment by az-iot-builder-01** [comment]
@lakshmisivareddy, @chinnaece, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
