### ISSUE TITLE
Broken pipe when sending iot message

### ISSUE THREAD

**Issue by shaoshanfan** [Azure/azure-iot-sdk-c#783]
- **OS and version used:** <VERSION> 
The host OS is Windows 10, target OS is Azure Sphere. I am doing development for Azure Sphere.

- **SDK version used:** <VERSION> 

Azsphere 18.11, not exactly sure about which IoT SDK version been bundled. Let me know how to find out.

# Description of the issue:

I am doing some development on Azure Sphere which try to send telemetry data to IoT Hub, I am working on some logic to ensure the device can recover in unstable network conditions. 

I randomly toggle on/off my AP hotspot to simulate a unstable network environment and noticed two issues.

1. There is significant delay between disconnect network and iot SDK callback to notifice iothub disconnected. (The callback been set with
IoTHubDeviceClient_LL_SetConnectionStatusCallback())
normally, there will be around 30 seconds delay.  If client continue to call IoTHubDeviceClient_LL_SendEventAsync() to send a lot message before been notified about the disconnection, that will result in process crash in my case, I believe it may because all the message been queued in iot transportation layer and cause some system level monitor to kill the process.

2. Sometimes, there is broken pipe crash happens in iot sdk. 
In my case, I need to ensure program is very robust and can't crash. Why there is a broken pipe, how to prevent this?

# Code sample exhibiting the issue:

code to register callback
```
    // Set callbacks for connection status related events.
    if (IoTHubDeviceClient_LL_SetConnectionStatusCallback(
            iothub_client_handle, hubConnectionStatusCallback, NULL) != IOTHUB_CLIENT_OK) {
        LogMessage("ERROR: failure setting callback\n");
        return false;
    }

void hubConnectionStatusCallback(..)
    iothub_authenticated = (result == IOTHUB_CLIENT_CONNECTION_AUTHENTICATED);
    if (hubConnectionStatusCb) {
        hubConnectionStatusCb(iothub_authenticated);
    }
    const char *reasonString = getReasonString(reason);
    if (!iothub_authenticated) {
        LogMessage("INFO: IoT Hub connection is down (%s), retrying connection...\n", reasonString);
    } else {
        LogMessage("INFO: connection to the IoT Hub has been established (%s).\n", reasonString);
    }
```
Code to send message
```
        IOTHUB_MESSAGE_HANDLE message_handle = IoTHubMessage_CreateFromString(messagePayload);

        // use message type property for message routing
        IoTHubMessage_SetProperty(message_handle, "messageType", messageType);


        if (message_handle == 0) {
            LogMessage("ERROR: unable to create a new IoTHubMessage\n");
        } else {
            if (IoTHubDeviceClient_LL_SendEventAsync(iothub_client_handle, message_handle,
                                                     sendMessageCallback,
                                                     /*&callback_param*/ 0) != IOTHUB_CLIENT_OK) {
                LogMessage("ERROR: failed to hand over the message to IoTHubClient\n");
            } else {
                LogMessage("INFO: IoTHubClient accepted the message for delivery\n");
            }
            // SendEventAsync will deep clone message, so destroy message handle here
            IoTHubMessage_Destroy(message_handle);
```
# Console log of the issue:

Log for delayed disconnection notification
```
// network is connected
2018-12-21 21:03:48 INFO  iot.c: Send telemetry message
2018-12-21 21:03:48 INFO  agent.c: Telemetry message delivered
// disconnect network here
2018-12-21 21:03:53 ERROR iot.c: Network not ready, can't send telemetry message
2018-12-21 21:03:58 ERROR iot.c: Network not ready, can't send telemetry message
2018-12-21 21:04:03 ERROR iot.c: Network not ready, can't send telemetry message
2018-12-21 21:04:08 ERROR iot.c: Network not ready, can't send telemetry message
2018-12-21 21:04:13 ERROR iot.c: Network not ready, can't send telemetry message
2018-12-21 21:04:18 ERROR iot.c: Network not ready, can't send telemetry message
// receive notification 30s after network disconnection
2018-12-21 21:04:23 INFO  iot.c: iot hub disconnected
```

for the broken pipe issue, I managed to capture one stack trace as below
```
 	ld-musl-armhf.so.1![Unknown/Just-In-Time compiled code]	
 	ld-musl-armhf.so.1!sendto	
 	ld-musl-armhf.so.1!send	
 	libazureiot.so.1!socketio_send	
 	libazureiot.so.1![Unknown/Just-In-Time compiled code]	
 	libwolfssl.so.15!wolfSSL_write	
 	libazureiot.so.1!tlsio_wolfssl_send	
 	libazureiot.so.1![Unknown/Just-In-Time compiled code]	
 	libazureiot.so.1!mqtt_client_publish	
 	libazureiot.so.1![Unknown/Just-In-Time compiled code]	
 	libazureiot.so.1!IoTHubTransport_MQTT_Common_DoWork	
 	libazureiot.so.1!IoTHubClientCore_LL_DoWork	
>	AzureIoT_DoPeriodicTasks() Line 343	C
 	app_main() Line 111	C
 	main(int argc, char ** argv) Line 128	C
```

**Comment by massand** [comment]
For your first issue, #643 is being used to track the blocking call (getaddrinfo) that blocks the DoWork pump from processing other events. I am in the process of adding support for asynchronous DNS, such that we can report back connectivity loss faster (as opposed to after returning from a synchronous DNS resolution call on the same bad socket connection). Please reopen track that issue for resolution. 

For the second issue, the callstack ends in a device-specific area. I recommend using the [Azure sphere support resources](https://docs.microsoft.com/en-us/azure-sphere/resources/support) for platform-specific queries. 

Thanks!

**Comment by az-iot-builder-01** [comment]
@shaoshanfan, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
