### ISSUE TITLE
Cross compilation for RPi not working

### ISSUE THREAD

**Issue by prashantbadgujar** [Azure/azure-iot-sdk-c#784]
When I tries to cross compile azure-iot-sdk-c for RPi platform with following command - ./build.sh --toolchain-file toolchain-rpi.cmake -cl --sysroot=$RPI_ROOT, I am getting following error -
CMake Error at build_all/linux/toolchain-rpi.cmake:1 (INCLUDE):
include could not find load file:
CmakeForceCompiler
Call Stack(most recent call first):
/usr/share/cmake-3.7/Modules/CMakeDeterminSystem.cmake:88(include)
CMakeLists.txt:5(project)

--The C compiler identification is unknown
--The CXX compiler identification is GNU 6.3.0
CMake Error at CMakeLists.txt:5 (project):
The CMAKE_C_COMPILER
/../bin/arm-linux-gnueabihf-gcc
is not a full path to an existing compiler tool.

Please help.

**Comment by jebrando** [comment]
@prashantbadgujar Have you looked at this doc [SDK_cross_compile_example](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md)

**Comment by massand** [comment]
@prashantbadgujar - We have cross-compilation articles using Docker, as well as daily builds using cross-compiler tools. Please refer the articles for latest instructions on obtaining the cross compilation tools and building them using Docker. Thanks!

**Comment by az-iot-builder-01** [comment]
@prashantbadgujar, @lakshmisivareddy, @jebrando, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
