### ISSUE TITLE
Failed to connect to IOTHUB after DPS. It use to work on 1.2.7 (similar to #557)

### ISSUE THREAD

**Issue by ukluk** [Azure/azure-iot-sdk-c#786]
- **OS and version used:** FreeRTOS and mbedTLS

- **SDK version used:** 1.2.12

# Description of the issue:
Unable to SetOptions:
```
IoTHubDeviceClient_LL_SetOption(device_ll_handle, SU_OPTION_X509_CERT, cert);
IoTHubDeviceClient_LL_SetOption(device_ll_handle, SU_OPTION_X509_PRIVATE_KEY, key);
```
after registering the device with DPS using `IoTHubDeviceClient_LL_CreateFromDeviceAuth` The handle has a cred_type = `IOTHUB_CREDENTIAL_TYPE_X509_ECC`
It appears to me that the x509 certificate that IoTHub expects to see x509 RSA.
## with version 1.2.7 I was able to set these options and the device connected to IoTHub after DPS registers.

I cannot do all the testing in my environment, but are you sure that the following sample still works on 1.2.12? I suspect it doesn't:
azure-iot-sdk-c/provisioning_client/samples/prov_dev_client_ll_sample/

# Code sample exhibiting the issue:

In file iothubtransport_mqtt_comon.c
```
        else if ((strcmp(OPTION_X509_CERT, option) == 0) && (cred_type != IOTHUB_CREDENTIAL_TYPE_X509 && cred_type != IOTHUB_CREDENTIAL_TYPE_UNKNOWN))
        {
            LogError("x509certificate specified, but authentication method is not x509");
            result = IOTHUB_CLIENT_INVALID_ARG;
        }
        /* Codes_SRS_IOTHUB_MQTT_TRANSPORT_07_040: [If the option parameter is set to "x509privatekey" then the value shall be a const char of the RSA Private Key to be used for x509.] */
        else if ((strcmp(OPTION_X509_PRIVATE_KEY, option) == 0) && (cred_type != IOTHUB_CREDENTIAL_TYPE_X509 && cred_type != IOTHUB_CREDENTIAL_TYPE_UNKNOWN))
        {
            LogError("x509privatekey specified, but authentication method is not x509");
            result = IOTHUB_CLIENT_INVALID_ARG;
        }
```

# Console log of the issue:
Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
Provisioning Status: PROV_DEVICE_REG_STATUS_ASSIGNING
ERROR: mqtt_error_callback L#138 MQTT communication error
***  D E V I C E  P R O V I S I O N E D  ***
Uri: [secret].azure-devices.net
ID: [secret]
IoTHub Client API Version: 1.2.12
Creating IoTHub Device handle

ERROR: iothub_provision_LL_open_internal L#865 failure to set option "SU_OPTION_X509_CERT"
ERROR: iothub_provision_LL_open_internal L#872 failure to set option "SU_OPTION_X509_PRIVATE_KEY"
IoTHub Connection Status = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, Reason = IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED

**Comment by jebrando** [comment]
@ukluk I'm a little confused as to what you're attempting to do.  If you are using provisioning why are setting the x509 certificates using SU_OPTION_X509_CERT?  For provisioning the x509 cert should be transferred to the iothub without setting the option for the x509 certificates.  Can you explain your scenario so I can have an idea as to when my have gone wrong.

Thanks

**Comment by ukluk** [comment]
@jebrando Thank you, For the leaf certificates that are required in DPS. Are these ECC or RSA? Maybe this is has to do with invalid certificates, but before 1.2.7, I was able to connect with IoTHub after DPS completed with the existing 509 certificates. The console that I reported, ignores the errors setting the options. Yet it still fails with IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED.

**Comment by ukluk** [comment]
@jebrando I tested with the Linux built. You are correct, there is no need to use the RSA Cert with `SU_OPTION_X509_CERT` the EccCert is the only one required.

I am scratching my head because the exact same code on the embedded device fails.
I thought maybe the cipher library or some timing. But after enabling traces it is clear the handshake completes.
Here are the latest traces, I know this is not a support ticket, but appreciate any suggestion on how to check why mqtt CONNECTACK fails.


**ssl_cli.c (3622): handshake: done**
ssl_cli.c (3511): client state: 15
ssl_tls.c (2781): => flush output
ssl_tls.c (2793): <= flush output
ssl_tls.c (8120): <= handshake
ssl_tls.c (8708): => write
ssl_tls.c (3369): => write record
ssl_tls.c (1471): => encrypt buf
ssl_tls.c (1807): <= encrypt buf
ssl_tls.c (2781): => flush output
ssl_tls.c (2800): message length: 277, out_left: 277
ssl_tls.c (2805): ssl->f_send() returned 277 (-0xfffffeeb)
ssl_tls.c (2833): <= flush output
ssl_tls.c (3502): <= write record
ssl_tls.c (8736): <= write
ssl_tls.c (8296): => read
ssl_tls.c (4337): => read record
ssl_tls.c (2562): => fetch input
ssl_tls.c (2723): in_left: 0, nb_want: 5
ssl_tls.c (2747): in_left: 0, nb_want: 5
ssl_tls.c (8296): => read
ssl_tls.c (4337): => read record
ssl_tls.c (2562): => fetch input
ssl_tls.c (2723): in_left: 0, nb_want: 5
ssl_tls.c (2747): in_left: 0, nb_want: 5
ssl_tls.c (8296): => read
ssl_tls.c (4337): => read record
ssl_tls.c (2562): => fetch input
ssl_tls.c (2723): in_left: 0, nb_want: 5
ssl_tls.c (2747): in_left: 0, nb_want: 5
ssl_tls.c (8296): => read
ssl_tls.c (4337): => read record
ssl_tls.c (2562): => fetch input
ssl_tls.c (2723): in_left: 0, nb_want: 5
ssl_tls.c (2747): in_left: 0, nb_want: 5
ssl_tls.c (8296): => read
ssl_tls.c (4337): => read record
ssl_tls.c (2562): => fetch input
ssl_tls.c (2723): in_left: 0, nb_want: 5
ssl_tls.c (2747): in_left: 0, nb_want: 5
ssl_tls.c (8296): => read
ssl_tls.c (4337): => read record
ssl_tls.c (2562): => fetch input
ssl_tls.c (2723): in_left: 0, nb_want: 5
ssl_tls.c (2747): in_left: 0, nb_want: 5
ssl_tls.c (8296): => read
ssl_tls.c (4337): => read record
ssl_tls.c (2562): => fetch input
ssl_tls.c (2723): in_left: 0, nb_want: 5
ssl_tls.c (2747): in_left: 0, nb_want: 5
ssl_tls.c (2748): ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)
ssl_tls.c (2768): <= fetch input
ssl_tls.c (2562): => fetch input
ssl_tls.c (2723): in_left: 5, nb_want: 69
ssl_tls.c (2747): in_left: 5, nb_want: 69
ssl_tls.c (2748): ssl->f_recv(_timeout)() returned 64 (-0xffffffc0)
ssl_tls.c (2768): <= fetch input
ssl_tls.c (1820): => decrypt buf
ssl_tls.c (2402): <= decrypt buf
ssl_tls.c (4411): <= read record
ssl_tls.c (8584): <= read
IoTHub Connection Status = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, Reason = IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED
ERROR: mqtt_operation_complete_callback L#1616
Connection Not Accepted: 0x5: Not Authorized

**Comment by YoDaMa** [comment]
@ukluk did @jebrando's suggestions flush out the issue?

**Comment by ukluk** [comment]
Thank you Yoseph for checking out,  the issue is still open.

I do use the option to set the trusted certificate.

We have a signed root certificate and enrollment groups, just as the sdk tools and scripts, we exchange the intermediary and leaf certificates.

Just for test, we tried RSA and ECC. Same results.

We use the custom HSM module.

It could be a certificate issue, but the mock test on Linux with exact same hardcoded certs, rules out this variable.

It could be a problem with the mbedTls vs openSSL, but the fact that provisioning client completes makes me doubt it.

Question:
If Provisioning client uses MQTT as transport,
Is it wrong to assume that if provisioning client completes,  and I use the Uri and DeviceId that it returns,  then iothub_client should connect?

Or DPS doesn't care about the client's x509?, just the common name?

Any recommendations on how to troubleshoot? I have the full verbose traces from TLS stack, but nothing indicates that the server is unhappy. I see the 15 handshake steps completing with no errors.


Best,
Uri

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ukluk** [comment]
@jebrando @YoDaMa, The adaptation for `tlsio_mbed `does not include the **CLONE** and **RETRIEVE** options for `OPTION_X509_ECC_CERT `and `OPTION_X509_ECC_KEY`, needed when iothub creates the connection string from the existing authentication from DPS.

the tsio_openssl file does, yet it is not a simple copy paste as the certs are stored parsed in mbed.

I am happy to fork the repo and push the fix, if you guys believe it helps the community

**Comment by jebrando** [comment]
@ukluk We have check in this change into shared utility master repo.  It has not made it into the SDK yet, but you can update to the lastest shared util and it shall be fixed.  Let me know if you have any more issues with this.

**Comment by az-iot-builder-01** [comment]
@jebrando, @ukluk, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
