### ISSUE TITLE
SetOption failure when using MQTT

### ISSUE THREAD

**Issue by jflynn129** [Azure/azure-iot-sdk-c#789]
Running under linux, embedded-c

- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

I  have code that runs correctly when using HTTPS and switched it to MQTT to run.  In previous versions of the Azure IOT SDK, this simply involved switching the transport from HTTPS to MQTT and it worked correctly.  I recently updated to the latest SDK and now after I switch to MQTT it says:

```
Error: Time:Wed Jan  2 23:48:50 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to _SetOption
Error: Time:Wed Jan  2 23:48:50 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/xio.c Func:xio_setoption Line:187 unable to OptionHandler_FeedOptions
Error: Time:Wed Jan  2 23:48:50 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to _SetOption
Error: Time:Wed Jan  2 23:48:50 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:GetTransportProviderIfNecessary Line:1998 Failed feeding existing options to new TLS instance.

```
I've looked through the code but it isn't clear what options are being modified.  Can you provide some background on what options are being saved in the code and why.  I was able to eliminate the problem with the following modifications:

```
// Prior to creating a new connection, if we have an existing xioTransport that has been connected before
// we need to clear it now or else cached settings (especially TLS when communicating with HTTP proxies)
// will break reconnection attempt.
static void ResetConnectionIfNecessary(PMQTTTRANSPORT_HANDLE_DATA transport_data)
{
    if (transport_data->xioTransport != NULL && transport_data->conn_attempted)
    {
printf("JMF:in ResetConnectionIfNecessary, call xio_retrieveoptions\n");
//        OPTIONHANDLER_HANDLE options = xio_retrieveoptions(transport_data->xioTransport);
//        set_saved_tls_options(transport_data, options);

//        xio_destroy(transport_data->xioTransport);
        transport_data->xioTransport = NULL;
    }
}

```
It appears this happens from the first time a connection is setup which makes me wonder if this function is called even though no connection exists (?).  With the set/destroy commented out, the code executes as expected.

**Comment by jebrando** [comment]
@jflynn129 Which sample are you building to see this error on?  Also are you using embedded linux or just a linux distro?

**Comment by jebrando** [comment]
@jflynn129 Quick question, where is your example failing.  I have an idea what could be the issue, but I'm not sure where the failure is happening.  Can you point me to what file the error is happening and which options you are setting (All I see is "trusted cert" for MQTT).

**Comment by jflynn129** [comment]
I have isolated all the azure calls to the file azClientFuncs.cpp (https://github.com/Avnet/M18QxAzureIoT/blob/jflynn129_dev/azClientFuncs.cpp) with the exception of 'IoTHubClient_LL_DoWrork' and 'IoTHubClient_LL_Destroy' which are in azIoTClient.cpp (https://github.com/Avnet/M18QxAzureIoT/blob/jflynn129_dev/azIoTClient.cpp). The only options I am setting in the code is "TrustedCerts" (when compiling with MQTT).

**Comment by jebrando** [comment]
@jflynn129 I looked at the code and everything looks correct.  Can you send me more of the log because it seems the log snippet doesn't have the originating error in it.  If you don't have any other errors, then maybe if you can send me the logs around the lines to see if we're missing a log on an error or something.

**Comment by jflynn129** [comment]
The errors that are generated by the SW are:
```
Error: Time:Mon Jan  7 18:59:35 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to _SetOption
Error: Time:Mon Jan  7 18:59:35 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/xio.c Func:xio_setoption Line:187 unable to OptionHandler_FeedOptions
Error: Time:Mon Jan  7 18:59:35 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to _SetOption
Error: Time:Mon Jan  7 18:59:35 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:GetTransportProviderIfNecessary Line:1997 Failed feeding existing options to new TLS instance.

```

**Comment by jflynn129** [comment]
I am only calling SetOption with "TrustedCerts", so I would like to know how to determine if this is the option that is failing at line 187 in xio_setoption or if there is some option that is being set internally by the Azure SW. Basically, I would like to determine what option it believes it needs to set yet is failing on. I should be able to track the options from the point I set it (when I called "TrustedCerts") until it is failing in iothubtransport_mqtt_common.c and determine a pointer has been corrupted somewhere in the azure software.

Can you provide a summary of changes that has occured between the last two releases that could have impacted the behavior such that it was previously working but no longer does?

**Comment by jflynn129** [comment]
Looking at this additionally, it looks like:
ResetConnectionIfNecessary is being called, and options are being obtained from the transport_data->xioTransport handle then saved to the transport handle saved_tls_options
after this, the transport handle is being deleted

At some point later, a new xio_transport handle is being setup but the saved_tls_options are not restored to the new handle. Instead a pointer to a different options is trying to be setup to the new xioTransport handle. At this point, errors are being generated.  

This is what it looks like based on my instrumentation of the source.

JMF:#2 (this is line 3154 of azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c; this call to ResetConnectionIfNecessary does not fail)
JMF:#1 (this is line 2200 of azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c; this call always generates the error messages reported in the above comments)

I instrumented ResetConnectionIfNecessary to save the handle of transport_data->xioTransport and options:
JMF:transport_data->xioTransport=0xab978, options=0xb8c68
JMF:transport_data->saved_tls_options=0xb8c68

Then I instrumented OptionHandler_FeedOptions in azure-iot-sdk-c/c-utility/src/optionhandler.c to print the option name and storage location:
JMF:OptionHandler_FeedOptions---> option->name=0xb93e8, option->storage=0xb92e8
JMF:OptionHandler_FeedOptions---> option->name=0xb9388, option->storage=0xb9310

It looks like the option storage location is never that of the saved_tls_options.  Wouldn't the saved options be feed into the new handle?  The errors are repeated each time a tx attempt is made.
It is also interesting that it attempts to feed options in twice, even though I know only 1 option was set.

```
Error: Time:Sat Jan 12 01:32:08 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:239 failure while trying to _SetOption
Error: Time:Sat Jan 12 01:32:08 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/xio.c Func:xio_setoption Line:187 unable to OptionHandler_FeedOptions
Error: Time:Sat Jan 12 01:32:08 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:239 failure while trying to _SetOption
Error: Time:Sat Jan 12 01:32:08 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:GetTransportProviderIfNecessary Line:2000 Failed feeding existing options to new TLS instance.

```

JMF:#1
JMF:transport_data->xioTransport=0xab978, options=0xab8e8
JMF:transport_data->saved_tls_options=0xab8e8
JMF:OptionHandler_FeedOptions---> option->name=0xac170, option->storage=0xab900
JMF:OptionHandler_FeedOptions---> option->name=0xab938, option->storage=0xac0f8
Error: Time:Sat Jan 12 01:32:09 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:239 failure while trying to _SetOption
Error:

**Comment by jebrando** [comment]
@jflynn129 Can you update the c-utility folder with a test branch to see what option is giving you issues.

In a git shell go to the root of the azure-iot-sdk-c folder and issue the following commands:
```Shell
cd c-utility
git fetch
git checkout setOption_test
--
build and run your app and let me know the error that you see.

**Comment by jflynn129** [comment]
I did that, and it is says:
```
Error: Time:Thu Jan 24 22:18:07 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option underlying_io_options
Error: Time:Thu Jan 24 22:18:07 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/xio.c Func:xio_setoption Line:187 unable to OptionHandler_FeedOptions
Error: Time:Thu Jan 24 22:18:07 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option concreteOptions
Error: Time:Thu Jan 24 22:18:07 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:GetTransportProviderIfNecessary Line:1997 Failed feeding existing options to new TLS instance.
Error: Time:Thu Jan 24 22:18:08 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option underlying_io_options
Error: Time:Thu Jan 24 22:18:08 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/xio.c Func:xio_setoption Line:187 unable to OptionHandler_FeedOptions
Error: Time:Thu Jan 24 22:18:08 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option concreteOptions
Error: Time:Thu Jan 24 22:18:08 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:GetTransportProviderIfNecessary Line:1997 Failed feeding existing options to new TLS instance.
Error: Time:Thu Jan 24 22:18:10 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option underlying_io_options
Error: Time:Thu Jan 24 22:18:10 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/xio.c Func:xio_setoption Line:187 unable to OptionHandler_FeedOptions
Error: Time:Thu Jan 24 22:18:10 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option concreteOptions
Error: Time:Thu Jan 24 22:18:10 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:GetTransportProviderIfNecessary Line:1997 Failed feeding existing options to new TLS instance.

```
If I let it then just run, each time it tires to TX, it says:
```
Error: Time:Thu Jan 24 22:20:17 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option underlying_io_options
Error: Time:Thu Jan 24 22:20:17 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/xio.c Func:xio_setoption Line:187 unable to OptionHandler_FeedOptions
Error: Time:Thu Jan 24 22:20:17 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/c-utility/src/optionhandler.c Func:OptionHandler_FeedOptions Line:238 failure while trying to SetOption with option concreteOptions
Error: Time:Thu Jan 24 22:20:17 2019 File:./msft_azure_iot_sdk/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:GetTransportProviderIfNecessary Line:1997 Failed feeding existing options to new TLS instance.

```
Does that help any?  BTW,I am using azure-iot-sdk-c/c-utility/adapters/tlsio_mbedtls.c

**Comment by jflynn129** [comment]
@jebrando Was that info I provided any help in diagnosing this issue?

**Comment by jflynn129** [comment]
@jebrando 
I debugged this issue and discovered the problem is in  azure-iot-sdk-c/c-utility/adapters/tlsio_mbedtls.c, in the function tlsio_mbedtlsl_setoption. You were not taking account for  the case where the option name was OPTION_UNDERLYING_IO_OPTIONS which resulted in xio_setoption being incorrectly called.  I added a case to basically ignore the case where OPTION_UNDERLYING_IO_OPTIONS is being used and MQTT now appears to be working correctly.  I attached the modified file.
[tlsio_mbedtls.txt](https://github.com/Azure/azure-iot-sdk-c/files/2814423/tlsio_mbedtls.txt)

if this is correct, please update the SDK and let me know, your welcome.

**Comment by az-iot-builder-01** [comment]
@jebrando, @jflynn129, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
