### ISSUE TITLE
Proxy option not set for file upload

### ISSUE THREAD

**Issue by AlexandreMarechalSE** [Azure/azure-iot-sdk-c#79]
Hello,

On Linux, file upload does not use proxy set by IoTHubClient_SetOption(), but uses the system proxy which is set. Is there a way the file upload uses the proxy set for the client connection ?

Thanks.

Alexandre

**Comment by tameraw** [comment]
@AlexandreMarechalSE - Apologies for the delay in response. This currently in our backlog; however, the support for this has not bubbled up at the top of the list in terms of priority. If interested in contributing, we'd happily review your Pull Request. Thanks.

**Comment by kiranpradeep** [comment]
This has been unattended for 3 months. I don't see this as an enhancement. This is a blocker bug or crucial feature missing.

Consider a real world scenario of data acquisition from control systems in plant. In real world, plant engineers, won't allow public internet access in same plant network and so will need to use gateway with dual NICs. One NIC for plant network and another for public internet access. Setting proxy in environment at system level messes if we use HTTP on both NICs. Microsoft Azure proudly announces pre-configured solutions as "Connected Factory" for plants - But none of that will work in real world, unless this issue( not an enhancement ) is fixed.

**Comment by tameraw** [comment]
@kiranpradeep - Understand your scenario. Very valid. We'll revise our priority for enabling this and get back to you with an ETA.

**Comment by tameraw** [comment]
FYI - We'll pull this in and try to unblock you ASAP.

**Comment by jebrando** [comment]
@kiranpradeep - Try setting the environment variable “http_proxy” in the format
"[protocol://][user:password@]machine[:port]" (e.g. https://user:password123@myproxy.domain.com:8080).  If you set this within a terminal it will only be set for executables started in that terminal.  We hope this can unblock you till we have a solution within the SDK.

**Comment by kiranpradeep** [comment]
@jebrando We follow Azure/iot-edge architecture where in which each of component are written as in process modules([1](https://github.com/Azure/iot-edge/blob/master/core/devdoc/module.md)) and so don't have multiple executables. It is just one process with multiple modules as dlls.

**Comment by bakrish** [comment]
@kiranpradeep Perhaps you can consider setenv(3) and unsetenv(3) to manage proxy environment variables within that specific module ? The proxy address could be kept in a configuration file. I guess this is not ideal, but could still help unblock this scenario for now. Bala

**Comment by kiranpradeep** [comment]
@bakrish We have two in process modules doing HTTP on each NIC. Each could be with or with out proxy. Each proxy could be different.  If we take the setenv/unsetenv route,  we will need to take care of many race conditions so that each of the two modules don't do HTTP at the same time. We will then need to synchronise between modules before HTTP calls. That is too tough on the users of this SDK.

**Comment by markrad** [comment]
This issue has been addressed. When the web proxy option is sent to the SDK, this will also be respected by the file upload process.
