### ISSUE TITLE
SAS Token expiration check does not work correctly in Linux 32-bit kernel environment

### ISSUE THREAD

**Issue by riwaida** [Azure/azure-iot-sdk-c#792]
**OS and version used:** Linux, 32bit (gcc 4.8.2)
**SDK version used**: release_2018_12_13

### Description of the issue:
gcc 4.8.2 compiler always generates value 0xFFFFFFFF if the code like example below.
```
double dblValue = 50000000000; // the value will overflow in case of 32bit unsigned integer.
                               //  > 4294967295 (0xFFFFFFFF)
uint32 uiValue = (uint32)dblValue; // uiValue will be become 0xFFFFFFFF
```

There is similar code existing in Linux code at https://github.com/Azure/azure-c-shared-utility/blob/1d622902d7842f94193fc394987f2b4e978bb700/adapters/tickcounter_linux.c#L68
```
TICK_COUNTER_INSTANCE* tick_counter_instance = (TICK_COUNTER_INSTANCE*)tick_counter;
tick_counter_instance->current_ms = (tickcounter_ms_t)(difftime(time_value, tick_counter_instance->init_time_value) * 1000);
*current_ms = tick_counter_instance->current_ms;
result = 0;
```

If _difftime()_ returns over 4294967295 in double, then _tick_counter_instance->current_ms_ is always stored 0xFFFFFFFF unexpectedly. The result of this, SDK cannot detect SAS expiration date correctly, and then it does not update Token expiration time.

The C language standard [ISO/IEC 9899:201x](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf) describes as follows. Converted value as 0xFFFFFFFF is the neared higher value in the example above.
_6.3.1.4 Real floating and integer
1 When a finite value of real floating type is converted to an integer type other than _Bool, the fractional part is discarded (i.e., the value is truncated toward zero). If the value of the integral part 
  cannot be represented by the integer type, the behavior is unde?ned.50)

6.3.1.5 Real floating types
  If the value being converted is in the range of values that can be represented but cannot be represented exactly, the result is either the nearest higher or nearest lower representable value, chosen in an implementation-defined manner._

### Proposal code for fixing the issue:

The code below is a proposal fix of this issue. Converting from 64bit integer to 32bit one can avoid this issue. Please consider the fix for next release.

```
    TICK_COUNTER_INSTANCE* tick_counter_instance = (TICK_COUNTER_INSTANCE*)tick_counter;
    unsigned long long temp64 = (unsigned long long)difftime(time_value, tick_counter_instance->init_time_value) * 1000; // To ulonglong from double
    tick_counter_instance->current_ms = (tickcounter_ms_t)(temp64 & 0xFFFFFFFF); // Get rid of high part of 32bit
    *current_ms = tick_counter_instance->current_ms;
```

Best regards,
Ryoichi

**Comment by jebrando** [comment]
@riwaida The tickcounter code always captures the delta between two points in time and not an absolute time.  So if a person marks a SAS Token to expire after 49.7 days then we probably will have a problem with overflow, but the user should not set an expiry date that long in the future.

**Comment by riwaida** [comment]
@jebrando Thanks for your comment.
>  The tickcounter code always captures the delta between two points in time and not an absolute time.

Yes, I can agree the counter is the delta between two point, but it seems to me that the first point ([_tickcounter_create()_](https://github.com/Azure/azure-c-shared-utility/blob/3b246a742d87395efe6bc576a111cb7ddd7ec7e1/adapters/tickcounter_linux.c#L26)) is unchanged until MQTT transport handle is re-created.
Is it un-realistic situation that the device holds the handle over 49.7 days?

Call sequence of _tickcounter_create()_ is as follows.
[tickcounter_create()](https://github.com/Azure/azure-c-shared-utility/blob/3b246a742d87395efe6bc576a111cb7ddd7ec7e1/adapters/tickcounter_linux.c#L26)
[InitializeTransportHandleData()](https://github.com/Azure/azure-iot-sdk-c/blob/90d9fb4b94dcf12c5defa3a29d9d4fc2f987bddf/iothub_client/src/iothubtransport_mqtt_common.c#L2326)
[IoTHubTransport_MQTT_Common_Create()](https://github.com/Azure/azure-iot-sdk-c/blob/90d9fb4b94dcf12c5defa3a29d9d4fc2f987bddf/iothub_client/src/iothubtransport_mqtt_common.c#L2506)
[IoTHubTransportMqtt_Create()](https://github.com/Azure/azure-iot-sdk-c/blob/f6979c66ad6f27b9c21efaa5fa1f9d773df6aec0/iothub_client/src/iothubtransportmqtt.c#L49)

**Comment by jebrando** [comment]
Tickcounter_create does not hold the time values, the time values are held in the tickcounter_ms_t that get returned from the tickcounter_get_current_ms call.  So it doesn't matter how long the tickcounter handle is stored, it gets return and the user holds the value.

**Comment by az-iot-builder-01** [comment]
@jebrando, @riwaida, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
