### ISSUE TITLE
Error running cmake

### ISSUE THREAD

**Issue by terrymandin** [Azure/azure-iot-sdk-c#793]
Tag: 2018-12-13

I am running the following in a Hyper-V Ubuntu 18.04 VM:

cd azure-iot-sdk-c
mkdir cmake
cd cmake
cmake ..

When I run "cmake .." I get the following error

root@ubuntuedge:/home/tmandin/azure-iot-sdk-c/cmake# cmake ..
-- The CXX compiler identification is unknown
-- Check for working CXX compiler: /usr/bin/cmake
-- Check for working CXX compiler: /usr/bin/cmake -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/usr/bin/cmake"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/tmandin/azure-iot-sdk-c/cmake/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_6bcda/fast"
    /usr/bin/make -f CMakeFiles/cmTC_6bcda.dir/build.make CMakeFiles/cmTC_6bcda.dir/build
    make[1]: Entering directory '/home/tmandin/azure-iot-sdk-c/cmake/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_6bcda.dir/testCXXCompiler.cxx.o
    /usr/bin/cmake     -o CMakeFiles/cmTC_6bcda.dir/testCXXCompiler.cxx.o -c /home/tmandin/azure-iot-sdk-c/cmake/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    CMake Error: The source directory "/home/tmandin/azure-iot-sdk-c/cmake/CMakeFiles/CMakeTmp/testCXXCompiler.cxx" is a file, not a directory.
    Specify --help for usage, or press the help button on the CMake GUI.
    CMakeFiles/cmTC_6bcda.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_6bcda.dir/testCXXCompiler.cxx.o' failed
    make[1]: *** [CMakeFiles/cmTC_6bcda.dir/testCXXCompiler.cxx.o] Error 1
    make[1]: Leaving directory '/home/tmandin/azure-iot-sdk-c/cmake/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_6bcda/fast' failed
    make: *** [cmTC_6bcda/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:5 (project)

-- Configuring incomplete, errors occurred!
See also "/home/tmandin/azure-iot-sdk-c/cmake/CMakeFiles/CMakeOutput.log".
See also "/home/tmandin/azure-iot-sdk-c/cmake/CMakeFiles/CMakeError.log".

**Comment by YoDaMa** [comment]
Yep let us know if installing build-essential solves your issues. This SO post also offers potential solutions to the error you're seeing: [cmake-complains-the-cxx-compiler-identification-is-unknown](https://stackoverflow.com/questions/9699930/cmake-complains-the-cxx-compiler-identification-is-unknown)

**Comment by terrymandin** [comment]
Thanks for the feedback.  I was able to compile when I cloned the previous tag and that got me going.  Because I was able to compile with the previous tag the compiler must have been installed.  I have since removed the vm.  If no one else is encountering this issue you can close the issue.

**Comment by az-iot-builder-01** [comment]
@YoDaMa, @terrymandin, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
