### ISSUE TITLE
Func:HTTPAPI_ExecuteRequest Line:556 curl_easy_perform() failed: **Timeout was reached**

### ISSUE THREAD

**Issue by PRAVEENBADIGER** [Azure/azure-iot-sdk-c#796]
Hi Team,

platform : LINUX 14.04

SDK Used - c Language.

![error](https://user-images.githubusercontent.com/36441456/50787610-e2483980-12dc-11e9-820e-ddbc523eb0e4.PNG)

error:
Time:Mon Jan  7 16:43:58 2019 File:/home/root/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:556 curl_easy_perform() failed: **Timeout was reached**
Error: Time:Mon Jan  7 16:43:58 2019 File:/home/root/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:558 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Mon Jan  7 16:43:58 2019 File:/home/root/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Mon Jan  7 16:43:58 2019 File:/home/root/azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:DoMessages Line:2073 unable to HTTPAPIEX_SAS_ExecuteRequest 

when i'am trying to read message from cloud i have encountered this problem ,can you please let me know how can i resolve this .

Thanks in advance ......

**Comment by YoDaMa** [comment]
from the snippet given it isn't clear what is causing the error. Can you include a code snippet of what it is that is failing? Additionally sometimes errors are caused because you running behind a proxy? Does your network use a proxy to connect?

**Comment by PRAVEENBADIGER** [comment]
Hi YaDaMa,

thanks for your response,

The same code was working fine from long days ,suddenly i was facing this problem .

system is already have curl package as below,

![curl](https://user-images.githubusercontent.com/36441456/50806762-09732b00-131e-11e9-90b3-74e781fae1a5.PNG)

can you pls explain in steps how to resolve above error.

Thanks.

**Comment by PRAVEENBADIGER** [comment]
Hi YaDaMa,

i have updated curl to version 7.5 as below,still i have same problem.

![7 5](https://user-images.githubusercontent.com/36441456/50820406-8fa96480-1352-11e9-87d5-5125d0cf7333.PNG)

**Comment by PRAVEENBADIGER** [comment]
Hi YoDaMa,

main moto is ,

**device1** to **device2** communication between azure cloud with the help of **functional app** 
i have encountered below error in functional app as below,
![capture](https://user-images.githubusercontent.com/36441456/50823565-4a893080-135a-11e9-92e1-e1f63dbedd3c.PNG)

and device end when i poll data from cloud same error reflecting as below,

error:
Time:Mon Jan  7 16:43:58 2019 File:/home/root/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:556 curl_easy_perform() failed: Timeout was reached
Error: Time:Mon Jan  7 16:43:58 2019 File:/home/root/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:558 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Mon Jan  7 16:43:58 2019 File:/home/root/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Mon Jan  7 16:43:58 2019 File:/home/root/azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:DoMessages Line:2073 unable to HTTPAPIEX_SAS_ExecuteRequest 

please help me on this ..

Thanks

**Comment by YoDaMa** [comment]
Hi @PRAVEENBADIGER,

Based on the error I'm seeing and a bit of skimming through the old post, it looks like you're trying to someone send telemetry over HTTP to EventHub and then have and Azure Function process and immediately send that message to another IoT Device as a C2D Message. 

The errors indicate that somehow, your device client is not able to connect to what it wants to connect with. Without any further knowledge though I can't say what's the actual issue. How is the system set up exactly? 

Also, it seems you're using a very old version of Linux and an old version of our SDK. Updating those might at the very least reduce the amount of unknowns. Currently understanding your error codes is a bit more difficult since the line numbers don't line up with the most up to date version of the SDK.

**Comment by az-iot-builder-01** [comment]
@YoDaMa, @PRAVEENBADIGER, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by chc69** [comment]
@YoDaMa @PRAVEENBADIGER , do you find the root cause of this issue? We also facing the same problem at Ubuntu16.04 and 18.04 with azure-iot-sdk-c 1.3.3. 
Could anyone help on this? It is urgent for our project, thank you.

**Comment by ranjith-t** [comment]
@PRAVEENBADIGER , is this issue resolved, we are facing same issue with large file of size 100 MB, but it works with 10MB/20MB files.

**Comment by danewalton** [comment]
@ranjith-t are you not able to use `IoTHubDeviceClient_LL_UploadMultipleBlocksToBlob()`?
