### ISSUE TITLE
Question: "Fix twin subscription timing issue" in release 2018-09-11

### ISSUE THREAD

**Issue by alexmrtn** [Azure/azure-iot-sdk-c#798]
- **OS and version used:** Ubuntu 18.04

- **SDK version used:** 2018-07-11, 2018-09-11 and lts_10_2018

# Description of the issue:

Hi,

I would like to have more detail about the fix you made in the release `2018-09-11`, in particular the "twin subscription timing issue". 

In fact, since the version `2018-09-11`, I am facing a random issue where desired properties are not pushed on the device. Everything works great with version `2018-07-11`.

I'm using the MQTT/WS protocol to connect to the iothub, and the serializer to manage device-twin.

From what I understood in version `2018-09-11` and above (thus `lts_10_2018`), the device after establishing the MQTT connection, publish a message on the topic `$iothub/twin/GET/` in order to ask for the full device-twin (desired+reported). Then it subscribe to the topic `$iothub/twin/PATCH/properties/desired/#` in order to be notified of partial updates of the twin.

In version `2018-07-11` there is no (or not logged) subscribe to the topic `$iothub/twin/PATCH/properties/desired/#` as there is in the version `2018-09-11`. Is that subscribe is still done somewhere?

I suspect that my issue is related to a bad timing of publish/subscribe messages. The bug occurs during some testing where I start a device, and then update the desired properties. So the first twin that the device receive does not contain any desired, and they are pushed afterward. 

What happen if someone update the desired properties just after the iothub have sent the desired to the device, but before the device subscribe to the topic `$iothub/twin/PATCH/properties/desired/#`? Are messages are retained and still received by the device even though the subscrive have been done after the update of the twin on the iothub side? The following sequence diagram may be more helpful to understand:

![image](https://user-images.githubusercontent.com/9555254/50827110-e48eb000-133d-11e9-9a69-92bf69d45519.png)

# Console log of the issue:

Log of correct execution:

```
-> 11:56:09 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: XXXXX.azure-devices.net/DDDDD/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.9%20(native%3b%20Linux%3b%20x86_64)  | PWD: XXXX | CLEAN: 0
<- 11:56:09 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0

-> 11:56:09 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/DDDDD/messages/devicebound/# | QOS: 1 | TOPIC_NAME: $iothub/twin/res/# | QOS: 0 | TOPIC_NAME: $iothub/methods/POST/# | QOS: 0
Set Twin Desired for 'DDDDD'
<- 11:56:09 SUBACK | PACKET_ID: 2 | RETURN_CODE: 1 | RETURN_CODE: 0 | RETURN_CODE: 0

-> 11:56:09 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/GET/?$rid=3
-> 11:56:09 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=4 | PAYLOAD_LEN: 683
<- 11:56:09 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/200/?$rid=3 | PAYLOAD_LEN: 203

-> 11:56:09 SUBSCRIBE | PACKET_ID: 5 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/# | QOS: 0

-> 11:56:09 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=6 | PAYLOAD_LEN: 685
-> 11:56:09 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=7 | PAYLOAD_LEN: 697
-> 11:56:09 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=8 | PAYLOAD_LEN: 696

<- 11:56:09 SUBACK | PACKET_ID: 5 | RETURN_CODE: 0

<- 11:56:09 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/204/?$rid=4&$version=2 | PAYLOAD_LEN: 0
<- 11:56:09 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/204/?$rid=6&$version=3 | PAYLOAD_LEN: 0
<- 11:56:09 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/204/?$rid=7&$version=4 | PAYLOAD_LEN: 0
<- 11:56:09 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/204/?$rid=8&$version=5 | PAYLOAD_LEN: 0

-> 11:56:13 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=9 | PAYLOAD_LEN: 695
<- 11:56:14 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/204/?$rid=9&$version=6 | PAYLOAD_LEN: 0

-> 11:56:17 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=10 | PAYLOAD_LEN: 695
<- 11:56:18 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/204/?$rid=10&$version=7 | PAYLOAD_LEN: 0
```

Log of bad execution:
```
-> 11:47:54 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: XXXXX.azure-devices.net/DDDDD/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.9%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
<- 11:47:54 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0

-> 11:47:54 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/DDDDD/messages/devicebound/# | QOS: 1 | TOPIC_NAME: $iothub/twin/res/# | QOS: 0 | TOPIC_NAME: $iothub/methods/POST/# | QOS: 0
<- 11:47:54 SUBACK | PACKET_ID: 2 | RETURN_CODE: 1 | RETURN_CODE: 0 | RETURN_CODE: 0

-> 11:47:54 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/GET/?$rid=3
-> 11:47:54 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=4 | PAYLOAD_LEN: 683
<- 11:47:54 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/200/?$rid=3 | PAYLOAD_LEN: 86

-> 11:47:54 SUBSCRIBE | PACKET_ID: 5 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/# | QOS: 0

<- 11:47:54 SUBACK | PACKET_ID: 5 | RETURN_CODE: 0

<- 11:47:54 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/204/?$rid=4&$version=2 | PAYLOAD_LEN: 0
```

In the second log, we can observe that the initial twin received is smaller than in the other one, which means that the twin does not contain the desired. The desired are correctly pushed by the service to the iothub but never pushed to the device afterward.

If the desired are pushed after the subscribe to the `$iothub/twin/PATCH/properties/desired/` topic, the update is correctly received on device side.

Regards,
Alexis.

**Comment by alexmrtn** [comment]
Hi all,

Just an update to know if you had time to investigate on this issue?

While it is unlikely to happen on a real device, it happens quite often in our test pipeline and give us hard time to validate what we are building on top of the SDK.

Thank you in advance,
Best regards

Alexis.

**Comment by massand** [comment]
@alexmrtn - we are currently investigating the possibility of twin feature changes done (around timing) in this commit - https://github.com/Azure/azure-iot-sdk-c/commit/51c315776cd6641c4463c1a59363c8ca6e886fb5#diff-499918c19cc19c4a745af7837b6c3c72

We will get around to reproducing this bug next week and get back to you on further details. Thanks.

**Comment by massand** [comment]
@alexmrtn - thank you for your good question. I looked through the current functionality for device twin subscription when using the `IoTHubDeviceClient_SetDeviceTwinCallback()` API and it was fixed because the SDK could not SUBSCRIBE for desired property changes unless the full twin was obtained. That said, your sequence diagram is accurate about an extremely slim chance of missing a twin update. I believe a race condition is inevitable if you simply rely on `IoTHubDeviceClient_SetDeviceTwinCallback()` API for all twin updates.  The only way to obtain the entire device twin after the initial $iothub/twin/GET is by taking advantage of the new `IoTHubDeviceClient_GetTwinAsync()` API (part of 2019-01-31 LTS release branch) that always performs another PUBLISH $iothub/twin/GET call to refresh the full twin payload _after_ the `IoTHubDeviceClient_SetDeviceTwinCallback()` API callback is successfully called. This is in fact recommended as per the [guidelines for device reconnection flow for the IoT Hub service](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#device-reconnection-flow)

Here is the expected MQTT flow if a `IoTHubDeviceClient_GetTwinAsync()` was performed after `IoTHubDeviceClient_SetDeviceTwinCallback()` API callback was called - 

```
-> 16:44:30 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: $iothub/twin/res/# | QOS: 0 | TOPIC_NAME: $iothub/methods/POST/# | QOS: 0
<- 16:44:30 SUBACK | PACKET_ID: 2 | RETURN_CODE: 0 | RETURN_CODE: 0
-> 16:44:30 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/GET/?$rid=3
-> 16:44:30 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=4 | PAYLOAD_LEN: 163
<- 16:44:30 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/200/?$rid=3 | PAYLOAD_LEN: 1691
-> 16:44:41 SUBSCRIBE | PACKET_ID: 5 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/# | QOS: 0
<- 16:44:41 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/204/?$rid=4&$version=21 | PAYLOAD_LEN: 0
<- 16:44:41 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/?$version=15 | PAYLOAD_LEN: 39
Device Twin reported properties update completed with result: 204
<- 16:44:58 SUBACK | PACKET_ID: 5 | RETURN_CODE: 0

-> 16:45:01 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/GET/?$rid=6
<- 16:45:01 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/200/?$rid=6 | PAYLOAD_LEN: 1691
```

**Comment by az-iot-builder-01** [comment]
@alexmrtn, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by alexmrtn** [comment]
@massand - Thanks for the detailed answer! We will add to the (re)connection flow a manual call to `IoTHubDeviceClient_GetTwinAsync()` as you suggested to prevent this chance of missing a twin update.
