### ISSUE TITLE
CONNECT failed: RefusedNotAuthorized C# 

### ISSUE THREAD

**Issue by CRACKbomber** [Azure/azure-iot-sdk-c#80]
{Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: CONNECT failed: RefusedNotAuthorized
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.

When I try to set method handlers I get the above inner exception.

**Comment by anporumb** [comment]
Hello @CRACKbomber ,

Can you please open this issue for the C# SDK? This is the link https://github.com/Azure/azure-iot-sdk-csharp. Thank you.

Best Regards,
Andrei Porumb
