### ISSUE TITLE
Fatal Error: Boost Python library not found

### ISSUE THREAD

**Issue by AlexanderHermann** [Azure/azure-iot-sdk-c#801]
- **OS and version used:** Windows 10 x64 

- **Azure IoT SDK Python version used:** Cloned repo and pulled latest release 1.4.6 

- **Azure IoT SDK C version used:** Cloned repo and pulled latest release 2018-12-13  

- **Python version used:**  3.7.2 x86  

- **cmake version used:**  3.12.4  

- **boost c++ lib version used:**  1.69.0  

# Description of the issue:

Originally, I am following the procedure of [How to use the Azure IoT SDKs for Python](https://github.com/Azure/azure-iot-sdk-python#how-to-use-the-azure-iot-sdks-for-python). Trying to build the libraries and work with the SDK code, directs me towards [Devbox Setup](https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md). Over there, I follow the steps given in
- [Prepare Development Environment](https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#prepare-your-development-environment) and
- [Build the Python device and service client modules on Windows using Nuget packages (recommended)](https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#windows).

Setting up the [Azure IoT SDK C on Windws](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#windows) is successful. Continuing with the steps in [Compile the Python Modules](https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#compile-the-python-modules-in-visual-studio), I also follow [Compile the Python modules using boost::python libraries in Windows](https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#compile-the-python-modules-using-boostpython-libraries-in-windows).

Therefore, I
- successfully installed the latest version of [boost](https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.7z),
- set environment variables `BOOST_ROOT=C:\boost_1_69_0` and `BOOST_LIBRARYDIR=C:\boost_1_69_0\stage\lib`,
- successfully ran `.\bootstrap` script and
- successfully ran `.\b2` script from the boost root folder. 

Step 11 in the same paragraph involves running the batch-script at **/build_all/windows/build_client.cmd**, which causes a *FATAL ERROR: Boost Python library not found* (see console output of the command below). 

I am new to the Azure IoT SDK as well as cmake and C++, therefore any help directing me into the right direction is appreciated, thanks in advance. If necessary, I can provide further details or clarifications. 

# Console log of the issue:

C:\azure-iot-sdk-python\build_all\windows>build_client.cmd
Using Python found in: C:\Python37, building Python 3.7 Win32 extension
CMAKE Output Path: C:\Users\de6u5942\cmake_Win32
***Running CMAKE for Win32***
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.16.27026.1
-- The CXX compiler identification is MSVC 19.16.27026.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IoT Client SDK Version = 1.2.12
-- Provisioning SDK Version = 1.2.12
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- target architecture: x86
-- Performing Test CXX_FLAG_CXX11
-- Performing Test CXX_FLAG_CXX11 - Success
-- target architecture: x86
-- target architecture: x86
-- target architecture: x86
-- target architecture: x86
-- iothub architecture: x86
-- target architecture: x86
CMake Warning (dev) at C:/azure-iot-sdk-python/provisioning_device_client/CMakeLists.txt:28 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Boost_ROOT is set to:

    C:\boost_1_69_0

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at C:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:847 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  C:/azure-iot-sdk-python/provisioning_device_client/CMakeLists.txt:28 (find_package)

CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:2048 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.69.0

  Boost include path: C:\boost_1_69_0

  Could not find the following static Boost libraries:

          boost_python

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  C:/azure-iot-sdk-python/provisioning_device_client/CMakeLists.txt:28 (find_package)

FATAL ERROR: Boost Python library not found
On windows, get boost from http://www.boost.org/users/history/version_1_60_0.html
Extract zip to a folder, then perform bootstrap and build libs with b2 command
The BOOST_ROOT environment variable should point to the root folder
of the extracted boost package with headers and libraries
CMake Error at C:/azure-iot-sdk-python/provisioning_device_client/CMakeLists.txt:35 (message):
  iothub_client_python needs Boost library

-- Configuring incomplete, errors occurred!
See also "C:/Users/de6u5942/cmake_Win32/CMakeFiles/CMakeOutput.log".
See also "C:/Users/de6u5942/cmake_Win32/CMakeFiles/CMakeError.log".

C:\azure-iot-sdk-python\build_all\windows>

**Comment by YoDaMa** [comment]
@AlexanderHermann I'm going to refer you to the Python team since they have more expertise. @pierreca will look into it.

**Comment by pierreca** [comment]
@AlexanderHermann looks like a Python SDK issue - which would belong there:
https://github.com/azure/azure-iot-sdk-python

In the Python repository there are already a few issues with folks who have figured this out - like the error says, it's a configuration issue: CMake seems to have trouble finding your version of Boost and exits. the suggestions from the logs to add the BOOST_ROOT or Boost_LibraryDir environment variables usually solve this.

The one thing you want to be careful about is aligning your versions of Boost and Python with your processor architecture: You must use Python x64 if you're on an x64 system.

Another, simpler way to work this out would be to install Python 3.6.6 instead of 3.7 (for x64) and pip install our pre-compiled packages.

If this doesn't solve it I would recommend re-opening the issue in the Python repo rather than here, and try to format it so that the following info is clear:
- The version and path of Boost
- The version and path of Python
- The path to the SDK
- which script you're running
- a properly formatted console log (github issues support markdown)

Thanks a lot!

**Comment by az-iot-builder-01** [comment]
@AlexanderHermann, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by AlexanderHermann** [comment]
> 
> 
> @AlexanderHermann looks like a Python SDK issue - which would belong there:
> https://github.com/azure/azure-iot-sdk-python
> 
> In the Python repository there are already a few issues with folks who have figured this out - like the error says, it's a configuration issue: CMake seems to have trouble finding your version of Boost and exits. the suggestions from the logs to add the BOOST_ROOT or Boost_LibraryDir environment variables usually solve this.
> 
> The one thing you want to be careful about is aligning your versions of Boost and Python with your processor architecture: You must use Python x64 if you're on an x64 system.
> 
> Another, simpler way to work this out would be to install Python 3.6.6 instead of 3.7 (for x64) and pip install our pre-compiled packages.
> 
> If this doesn't solve it I would recommend re-opening the issue in the Python repo rather than here, and try to format it so that the following info is clear:
> 
>     * The version and path of Boost
> 
>     * The version and path of Python
> 
>     * The path to the SDK
> 
>     * which script you're running
> 
>     * a properly formatted console log (github issues support markdown)
> 
> 
> Thanks a lot!

Alright, thanks for the help. I'm going to try the provided suggestions the next working day and report back.
