### ISSUE TITLE
Messages are not received after network disconnect

### ISSUE THREAD

**Issue by ajaskumarpa** [Azure/azure-iot-sdk-c#804]
Hi ,
I am using Iot c sdk for my development. Protocol used is HTTP. Platform is Ubuntu . After I sent message to Iot hub I have disconnected my LAN cable for 3 hours and then I connected it back but I didn't receive any messages back from Iot hub which I am suppose to get. I did the same scenario for 30 minutes and I am getting the response. Please help

**Comment by YoDaMa** [comment]
@ajaskumarpa so when you disconnect the LAN cable for 3 hours, the device no longer receives messages from IoT Hub, but when you disconnect the LAN cable for 30 minutes, the device reconnects and receives information, correct? 

Based on the provided information, there's no clear indication what could be failing on the Device side. If the device client is using the HTTP transport on Ubuntu, the device is most likely using the cURL HTTP API adapter. If you can verify this (check if _httpapi_curl.c_ is included in your build), then set the option `OPTION_CURL_VERBOSE` in your application so we can collect logs on what might be failing. The logs will help us debug the issue.

**Comment by YoDaMa** [comment]
@ajaskumarpa pinging again for more information. Without it this issue is blocked. And if things have been resolved let us know what the issue was for future troubleshooting.

**Comment by YoDaMa** [comment]
This issue has been inactive for a while so I'm going to go ahead and close it, however @ajaskumarpa feel free to reopen it if the problem is persisting and you have more information.

**Comment by az-iot-builder-01** [comment]
@ajaskumarpa, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
