### ISSUE TITLE
error while connecting esp32 to azure

### ISSUE THREAD

**Issue by naznaaa** [Azure/azure-iot-sdk-c#806]
Hi,
I am using esp-idf version v3.1.2 in windows and while connecting esp32 to azure,i couldn't connect following are seen in the verbose log.
File:C:/msys32/home/Nazna/esp/Smart_Bulb/main/iothub_client_sample_mqtt.c Compile Time:Jan 11 2019 15:20:55
Info: IoT Hub SDK for C, version 1.1.12
IoTHubClient_LL_SetMessageCallback...successful.
Ready to Send String:{"deviceId":"AirConditionDevice_001","windSpeed":14.00}
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.

-> 00:00:09 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: aflex-iot-hub.azure-devices.net/MyDotnetDevice/api-version=2016-11-14&DeviceClientType=iothubclient%2F1.1.12 | PWD: XXXX | CLEAN: 0
<- 00:00:09 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Thu Jan  1 00:00:09 1970 File:C:/msys32/home/Nazna/esp/esp-idf/components/AzureIoTHub/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1400 Connection Not Accepted: 0x5: Not Authorized
-> 00:00:09 DISCONNECT.
 kindly reply soon to solve this issue.

Thank you.

**Comment by bikamani** [comment]
Hi @naznaaa ,

Had it worked since then or are you still facing same issue? Authentication failure means connection string could be incorrect. Can you recheck and share logs?

**Comment by bikamani** [comment]
Closing the issue as have not heard back and the issue is not reproducible. Please feel free to reach out to us further if there are any questions. Thank you.

**Comment by az-iot-builder-01** [comment]
@naznaaa, @bikamani, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
