### ISSUE TITLE
Azure IoT Hub raspberry c example not compiled

### ISSUE THREAD

**Issue by naakar** [Azure/azure-iot-sdk-c#811]
Hi

I trying to compile next raspberry c example:

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-raspberry-pi-kit-c-get-started

OS version:

Raspberry image is 2017-07-05 Rasbian-jessie, 
Rasberry is Pi 3 model B

After first compile with errors 
next missing libraries installed:

sudo apt-get install libssl-dev
 sudo apt-get install git-core
sudo apt-get install build-essential cmake

And I'll get next errors with and without simulation on:

Is there any working c/c++ examples available for raspberry ?

Br Kari

pi@raspberrypi:~/iot-hub-c-raspberrypi-client-app $ sudo ./setup.sh --simulated-data
Hit http://archive.raspberrypi.org jessie InRelease
Hit http://mirrordirector.raspbian.org jessie InRelease
Hit http://archive.raspberrypi.org jessie/main armhf Packages
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'libssl-dev' is not installed, so not removed
The following package was automatically installed and is no longer required:
  libssl-doc
Use 'apt-get autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 215 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libssl1.0-dev
E: Couldn't find any package by regex 'libssl1.0-dev'
mkdir: cannot create directory ‘Source’: File exists
fatal: destination path 'azure-iot-sdk-c' already exists and is not an empty directory.
~/Source/azure-iot-sdk-c/cmake/iotsdk_linux ~/Source/azure-iot-sdk-c/build_all/linux
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IoT Client SDK Version = 1.2.12
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- target architecture: ARM
-- Performing Test CXX_FLAG_CXX11
-- Performing Test CXX_FLAG_CXX11 - Success
CMake Error at /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.6/Modules/FindOpenSSL.cmake:380 (find_package_handle_standard_args)
  c-utility/CMakeLists.txt:95 (find_package)

-- Configuring incomplete, errors occurred!
See also "/root/Source/azure-iot-sdk-c/cmake/iotsdk_linux/CMakeFiles/CMakeOutput.log".
See also "/root/Source/azure-iot-sdk-c/cmake/iotsdk_linux/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
gcc version check pass (current:4.9.2,require:4.4.7)
cmake version check pass (current:3.6.2,require:2.8.12)
fatal: destination path 'wiringPi' already exists and is not an empty directory.
wiringPi Build script
=====================

WiringPi Library
[UnInstall]
make: Nothing to be done for 'all'.
[Install Headers]
[Install Dynamic Lib]

WiringPi Devices Library
[UnInstall]
make: Nothing to be done for 'all'.
[Install Headers]
[Install Dynamic Lib]

GPIO Utility
make: Nothing to be done for 'all'.
[Install]

All Done.

NOTE: To compile programs with wiringPi, you need to add:
    -lwiringPi
  to your compile line(s) To use the Gertboard, MaxDetect, etc.
  code (the devLib), you need to also add:
    -lwiringPiDev
  to your compile line(s).

Using simulated data
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/iot-hub-c-raspberrypi-client-app
Scanning dependencies of target app
[ 20%] Building C object CMakeFiles/app.dir/main.c.o
/home/pi/iot-hub-c-raspberrypi-client-app/main.c:9:45: fatal error: azure_c_shared_utility/xlogging.h: No such file or directory
 #include <azure_c_shared_utility/xlogging.h>
                                             ^
compilation terminated.
CMakeFiles/app.dir/build.make:62: recipe for target 'CMakeFiles/app.dir/main.c.o' failed
make[2]: *** [CMakeFiles/app.dir/main.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/app.dir/all' failed
make[1]: *** [CMakeFiles/app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
pi@raspberrypi:~/iot-hub-c-raspberrypi-client-app $

**Comment by chinnaece** [comment]
You can see the error related to openssl path missing here as in quote.
> Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
> system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
> OPENSSL_INCLUDE_DIR)

can resolve by set the path for  OPENSSL_ROOT_DIR variable as below in terminal 

**export OPENSSL_ROOT_DIR=$SDK_PATH_TARGET/usr/lib**(in my case this the path for openssl library).
Give a try let me know back .

**Comment by naakar** [comment]
Thanks chinnaece and jebrando

I tried to set the path, but it didn't help, but I was not even able to find where openssl library is located ?
So might be that above path is not correct in my Rpi.
I tried google help for that but not yet get feasible answear.

Also compiled ssl but no help.
https://raspberrypi.stackexchange.com/questions/66782/how-to-install-openssl-1-0-2-on-raspberry-pi3

I'll also try cross compile all, any suggestion shall I try that with old jessie 2017 image that was proposed in MS tutotorial or use latest Raspian image ?

Br Kari

**Comment by markrad** [comment]
Reviewing the error messages, it would appear that the script you are running has been designed to run on Raspbian Stretch. It was attempting to remove libssl-dev and install libssl1.0-dev. See this section:
```
Package 'libssl-dev' is not installed, so not removed
The following package was automatically installed and is no longer required:
libssl-doc
Use 'apt-get autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 215 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libssl1.0-dev
```
Due to an issue in Debian which has been ported to the Pi, you cannot use the latest version of libssl-dev because they linked curl with an earlier version. You need to install libssl1.0-dev. All of this though is only applicable to Raspbian Stretch. On Jessie you can use libssl-dev but the script has a) removed it and b) attempted to install an non-existent package for that version. 

You have three options here:
1) Hope that someone in Microsoft fixes the script so that it is Raspbian version aware.
2) Hack the script so that it does not attempt to install libssl1.0-dev and instead uses libssl-dev.
3) Upgrade your Raspberry Pi to Raspbian Stretch.

This is also of some concern:
```
/home/pi/iot-hub-c-raspberrypi-client-app/main.c:9:45: fatal error: azure_c_shared_utility/xlogging.h: No such file or directory
```
Typically this is caused by failing to use the ```--recursive``` flag when cloning the GitHub repository.

_Mark Radbourne MSFT_

**Comment by jebrando** [comment]
@naakar if you have any more question please reopen this or create a new issue.  Thanks

**Comment by az-iot-builder-01** [comment]
@jebrando, @chinnaece, @naakar, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
