### ISSUE TITLE
X.509 Certificates with HTTPS

### ISSUE THREAD

**Issue by d3lt3k** [Azure/azure-iot-sdk-c#812]
Hi I've followed the tutorials ([this](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md)  and [this](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-security-x509-get-started)) to generate the CA certificates and keys, verified the root certificate in the hub and tested with DeviceClient example successfully (however only works with mqtt and amqp).

My application should connect to IoT Hub using HTTP. I am using a GSM modem that has builtin HTTP and SSL layers with certificates support. I've copied the certificates and key to the modem but I am getting unauthorized error (401).

I've also tried with nodered using http-request node adding the certificates but I am getting the same result. I've tried all possible combinations of all generated .pem (by the way, the tutorial does not describe what each .pem is).
![image](https://user-images.githubusercontent.com/46755625/51278908-c545f180-19d3-11e9-9cd9-66d69c9489ae.png)

![image](https://user-images.githubusercontent.com/46755625/51278753-58325c00-19d3-11e9-844c-0ce7bc158ec0.png)

![image](https://user-images.githubusercontent.com/46755625/51278992-03431580-19d4-11e9-95a7-f016c6d7b602.png)

Q1. Are HTTPS connections to the IoT Hub stable when using certificates? It [appears](https://github.com/Azure/azure-iot-sdk-java/issues/239#issuecomment-389606135) from the  DeviceClient example is not. If it is stable, can you provide a reference of a working example?

Q2. My modem requires "cacert.pem", "clientcert.pem" and "clientkey.pem" files. From the script in the tutorial are these the "RootCA.pem",  "\<device\>-public.pem" and "\<device\>-private.pem" respectively?

- **OS and version used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by jebrando** [comment]
@d3lt3k can you send what sample are you using when seeing this answer.  Also can you send the OS and SDK version that you are using.

**Comment by d3lt3k** [comment]
Below you can see the HTTP header and body sent to the GSM modem and the 401 error being received. Note that the .pem certificates were loaded previously.
![image](https://user-images.githubusercontent.com/46755625/51665993-eb135d80-1fb4-11e9-9ea5-a8f3c8313440.png)

OSs
Modem - this is an AT command 3G modem (Quectel UC20), and it will be hard to know what OS is running there.
Nodered - installed in my local windows 10 machine, but I have eliminated the certificates from the "manage computer certificates" that were generated after running the script. Why? Because I wanted to simulate what my modem would do, since it asks for the same kind of certificate file formats.

SDKs Versions
azure-iot-sdk-c 1.2.12
Microsoft.Azure.Devices.Client v1.19.0

**Comment by jebrando** [comment]
@d3lt3k The issue looks like the certificate is not getting sent on the TLS stream.  To figure out what's happening I need to know which transport are you using (curl, winhttp, http_compact).  Also if you have any error messages that the SDK is showing.

**Comment by d3lt3k** [comment]
Hi. I can't tell you what transport is being used. I have asked the module supplier but no clear feedback yet.
Anyway, I've got some interesting results from a couple of tests. I have nodered simulating an IoT device in the field and transmitting to IoT Hub:
1) MQTTS with certificates works ok on port 8883 but it fails on port 443
2) MQTTS with SAS tokens works ok on port 8883 but it fails on port 443
3) HTTPS with certificates fails using the 443 default port
4) HTTPS with SAS tokens works ok using the 443 default port

This is pretty similar to what I have experienced on the DeviceClient where MQTT/AMQP-over-secure-socket and HTTPS didn't work with certificates.
Unfortunately my GSM module doesn't support MQTT yet, but a new firmware release is about to come out soon. I would expect pretty much the same results as in nodered and DeviceClient.

Again, if you can provide an example using HTTPS w/ certificates (working) would be a great advantage.

**Comment by jebrando** [comment]
@d3lt3k which language would you like to see this example?  If you are looking at C then the example is [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_ll_client_x509_sample/iothub_ll_client_x509_sample.c).  If you're interested in node then the example is [here](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device_x509.js).  

MQTT only works on 8883 which is the TLS port for mqtt (443 is only for http).  As far as HTTPS not working on 443, I believe that the certificate is not being added to the TLS stream.  If you can get a wireshark trace that shows the TLS data it should show if the certificate is being added or not.

**Comment by ewertons** [comment]
Hi @d3lt3k ,
could you confirm if @jebrando 's last comment address your issue?

**Comment by ewertons** [comment]
@d3lt3k ,
we will close this issue for now, but please feel free to reopen it if you would like to follow up.
Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment]
@jebrando, @d3lt3k, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
