### ISSUE TITLE
Individual enrollments can't upload pem certificate。

### ISSUE THREAD

**Issue by v-jiq** [Azure/azure-iot-sdk-c#817]
always can't upload the pem certificate to dps service.
the pem file generate by dice_device_enrollment.
![default](https://user-images.githubusercontent.com/39880470/51425161-4e973700-1c13-11e9-8c1c-c2cd264ddaad.png)

**Comment by yzhong94** [comment]
@v-jiq Are you walking through this [tutorial](https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509)?  I just went to the same steps and I was able to upload my pem file.  Can you verify if the pem file was saved correctly from Visual Studio (e.g. txt removed?)?

**Comment by v-jiq** [comment]
Thanks @yzhong94 . Yes ,I reference this guidance to upload pem file，but my pem file is  generated by Linux instead of visual studio. So, I will retry do it completely according to document.

**Comment by v-jiq** [comment]
I just tried the above guidance by the same steps but still can't upload the X509testcert.pem file.
In addition i have repeatedly confirmed the pem file format:
![pic](https://user-images.githubusercontent.com/39880470/51594352-371bbf00-1f2f-11e9-8b8d-c8c22a8b311d.png)

**Comment by yzhong94** [comment]
@v-jiq That's very strange.  Can you create a [support ticket](https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request) from the portal so we can take a look from your account?

**Comment by yzhong94** [comment]
Closing this issue on our repo.  Please create a support ticket from the portal so we can take a look from your account.  Thanks!

**Comment by az-iot-builder-01** [comment]
@v-jiq, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by yzhong94** [comment]
@v-jiq  thanks for the follow up!  It seems like a localization bug.   If you still observe this problem, please help us by opening a support ticket and specify that uploading PEM certificate fails on localized Azure Portal.
