### ISSUE TITLE
Not able to set “message-id” before the body in Azure IoT HUB message using Azure C# SDK.

### ISSUE THREAD

**Issue by vaniayyar** [Azure/azure-iot-sdk-c#818]
@czyba based on your comment above I will close this thread.

_Originally posted by @chrit-msft in https://github.com/Azure/azure-iot-sdk-c/issues/111#issuecomment-313187531_

**Comment by yzhong94** [comment]
Hi there, this repo is for Azure IoT C SDK.  Due to the lack of information, I will close this issue.

**Comment by az-iot-builder-01** [comment]
@vaniayyar, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
