### ISSUE TITLE
DPS with custom HSM and symmetric key not supported

### ISSUE THREAD

**Issue by AndWass** [Azure/azure-iot-sdk-c#821]
- **OS and version used:** Windows 10 

- **SDK version used:** 2018-12-13 

# Description of the issue:

Configuring HSM to use a custom library doesn't enable symmetric keys. There appear to be two defines, one in `prov_auth_client.c` and one in `iothub_auth_client.c` missing, there is an

`#if defined(HSM_TYPE_SYMM_KEY)` but it should probably be
`#if defined(HSM_TYPE_SYMM_KEY) || defined(HSM_AUTH_TYPE_CUSTOM)`

This ties in with the fact that it is impossible to isolate symmetric key support without using a custom HSM. If custom isn't built you will get everything which is less than ideal.

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by jebrando** [comment]
@AndWass We do not include a symm key for custom HSM because if you are using symm key you don't need to have custom hsm because you feed the symm key to the sdk and there is not deriving any keys.  

So here is the question; why do you want to use a custom HSM is it just to not have x509 & tpm code in your application or is there some other reason?

**Comment by AndWass** [comment]
@jebrando Yes that is exactly what I want; no x509 or TPM code. Prov client doesn't build with MingW on Windows due to incompatible TPM code for instance.

A custom symmetric key HSM can also solve the timing issue that you hinted at in #815, using some cleverness (although I don't like that idea but it is possible)

**Comment by jebrando** [comment]
I enable the Symm key to be included in the custom HSM and have merged this in the master.  Let me know if you have any issues with this.

Thank you.

**Comment by az-iot-builder-01** [comment]
@jebrando, @AndWass, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
