### ISSUE TITLE
SAS reconnect is executed even when we use X509 authentication.

### ISSUE THREAD

**Issue by riwaida** [Azure/azure-iot-sdk-c#829]
**OS and version used: Windows 10 1809 64bit
SDK version used: release_2018_12_13**

We are using iothub_ll_client_x509_sample to send telemetry data to IoT Hub and noticed that this sample renews its connection after 48 minutes. Digging deeper, we realized that this is because of the following code in iothubtransport_mqtt_common.c.

https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L2358

```
    size_t sas_token_expiry = IoTHubClient_Auth_Get_SasToken_Expiry(transport_data->authorization_module);
    if ((current_time - transport_data->mqtt_connect_time) / 1000 > (sas_token_expiry*SAS_REFRESH_MULTIPLIER))
    {
        /* Codes_SRS_IOTHUB_TRANSPORT_MQTT_COMMON_07_058: [ If the sas token has timed out IoTHubTransport_MQTT_Common_DoWork shall disconnect from the mqtt client and destroy the transport information and wait for reconnect. ] */
        DisconnectFromClient(transport_data);
```

(sas_token_expiry * SAS_REFRESH_MULTIPLIER) is 3600 sec*0.8 which turns out to be 2880 sec (48 min). This code seems to process the reconnection for SAS Token but we use x509 for authentication. 

We want to know whether this reconnection is expected behavior since our understanding is that connection renewal happens only when we use SAS token for authentication.

BTW, we get IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN (after 48 min) when we check the connection status by using IoTHubClient_SetConnectionStatusCallback which seems odd.

**Comment by massand** [comment]
@riwaida - Yes, the SAS tokens issued to the device generally has an expiration of an hour and the SDK proactively attempts to refresh it over the active link, before the service severs the connection.

**Comment by az-iot-builder-01** [comment]
@riwaida, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by riwaida** [comment]
@massand 
Are you saying that SAS tokens are used even when we use x509 certificate for authentication in C SDK? Our understanding is that SAS tokens aren't used when we use x509 for authentication which is stated in the following document.

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security

A device may either use an X.509 certificate or a security token for authentication, but not both.

Are we misunderstanding here?

**Comment by massand** [comment]
@jebrando - reopening and assigning to you since you have touched the SAS token expiration area recently. Should we add a condition in our InitializeConnection to prevent the SAS token refresh when it is X509 cred type?

**Comment by jebrando** [comment]
@riwaida I just added code to fix this issue.  Get the latest master and it should be fixed.  Let me know if you see any more issues.
