### ISSUE TITLE
Windows Compilation with websockets Support Fails

### ISSUE THREAD

**Issue by MichaelDenczek** [Azure/azure-iot-sdk-c#83]
When attempting to compile the SDK for C on Windows with websocket support CMake errors prevent compilation.

After building OpenSSL and setting the OpenSSLDir and OPENSSL_ROOT_DIR environment variables in the Visual Studio 2015 Developer Command Prompt, the following command lines all fail to build:

_cmake -Duse_wsio=ON -G "Visual Studio 14 2015" ..
cmake -Duse_wsio=ON -Duse_openssl=ON -G "Visual Studio 14 2015" ..
cmake -Duse_wsio=ON -Duse_openssl=ON -Duse_installed_dependencies=ON -G "Visual Studio 14 2015" .._

**Comment by MichaelDenczek** [comment]
Compilation of the same library on Linux succeeds with websockets enabled.

**Comment by lmussier** [comment]
@MichaelDenczek Thanks I was about to report the same thing.

The question is, do we have to use openssl on windows to use websockets ?

**Comment by MichaelDenczek** [comment]
Yes, you need to use openssl.  The issue is that the cmake files appear to not be set up to actually see the openssl libraries, even after indicating their location and even updating the windows path environment variables.  Working with CMake GUI to try and get past this but the inability to see the built and provided libraries is the showstopper.

**Comment by MichaelDenczek** [comment]
Compilation of the same openssl and azure IoT SDK for C libraries succeed with websocket support on Windows 10, but fail on Windows 7.

**Comment by lmussier** [comment]
I've read deeper the code related to websocket in the SDK and I don't found any use of an adapter layer.
Does it mean even on windows where, if I'm not wrong winhttp can be use to perform secured websocket connection the SDK will use libwebsocket and openssl for the security layer?
So on a windows box, we'll have to configure both winhttp (through HTTP_API) and openssl (for libwebsockets) to secure our connection?

Is that correct?

**Comment by MichaelDenczek** [comment]
When the process works, Visual Studio project and solution files are created for compiling the SDK.  If you check the iothub_client_sample_sqtt_websockets project settings, you'll see the dependencies on both winhttp and openssl, in addition to crypt32.lib and secur32.lib.

**Comment by lmussier** [comment]
Ok I've made some more tests on my side :

Windows 10, Openssl 1.0.2k installed from https://slproweb.com/products/Win32OpenSSL.html

1- Without openssl installed, the build system generation fails (can't find openssl). So for sure Openssl is a required dependency, even on windows.

2 - After Openssl installation I've test the exact same CMake configuration we use under linux

```
cmake ..\azure-iot-sdk-c -DCMAKE_INSTALL_PREFIX=C:\Users\lmussier\workspace\build-azure\install_folder^
 -Duse_amqp:BOOL=ON -Duse_http:BOOL=ON^
 -Duse_mqtt:BOOL=ON -Drun_e2e_tests:BOOL=OFF^
 -Duse_wsio:BOOL=ON -Drun_longhaul_tests:BOOL=OFF^
 -Dskip_unittests:BOOL=ON
```
It fails, when it works correctly on our linux build machine. 
[log.txt](https://github.com/Azure/azure-iot-sdk-c/files/830980/log.txt)

@MichaelDenczek how do manage to compile the project correctly on windows 10?
Don't tell me I've to install every single lib to do so...

**Comment by olivierbloch** [comment]
Hi @MichaelDenczek and @lmussier 
I confirm Openssl libraries ssleay32 and libeay32 are necessary dependencies for having AMQP over Websocket work.
Can you please confirm you went through the steps described in the dev-box-setup.md file pointed out by @lmussier [(this one)](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#build-a-sample-that-uses-websocket)?
If that's not the case, can you please go through them and confirm whether or not you still have the issue?
Thanks

**Comment by olivierbloch** [comment]
Update on this one. I have not yet understood why, but I noticed that when building openssl using the commands listed in our devbox-setup doc the dlls ssleay32.dll and libeay32.dll are not copied from the out32dll folder (which you can find in the folder where you extracted openssl) to the install dir (which is C:\usr\local\ssl\bin by default). I have manually copied the 2 files in there and then I was able to successfully generate the build system then run the amqp websocket sample.
I will look into what's missing in the openssl install instructions to make sure the dlls are copied and will update the doc once I have the solution.
Please confirm if my workaround works for you
Thanks
Olivier

**Comment by lmussier** [comment]
Hi,

I follow all the steps described on the dev box setup but skip the openssl compilation.
I've installed openssl on my dev machine from one of the binary release pointed by openssl (1.0.2k from here  https://slproweb.com/products/Win32OpenSSL.html)

From the logs CMake (find_package command) is happy with the installation. This package does not install stuff in 
`C:\usr\local\ssl`
I'll check if setting those variables do the trick and if it fails, I'll install openssl exactly where the SDK need it. What I don't understand is, since CMake finds openssl (with the binary installer) why it fails afterwards.

**Comment by MichaelDenczek** [comment]
The problem is with the CMake configuration files.  When passing the paths to the openssl libraries, the values seem to be ignored.  Verified this is not an issue on Windows 10, but is an issue on Windows 7.

**Comment by lmussier** [comment]
Ok build is also ok for me on Win10.

**Comment by olivierbloch** [comment]
Good to hear @lmussier 
Can you confirm that setting the environment variables for openssldir and OPENSSL_ROOT_DIR in the system is what did the trick, or did you change something in the CMake configuration files or in the command line?
If the former, then feel free to close the issue.
Thanks

**Comment by MichaelDenczek** [comment]
The compilation worked "out of the box" on Windows 10, but I could not achieve any success on Windows 7.  I had to create the solution files on Windows 10 and copy to Windows 7 to use them (after switching compiler versions).

**Comment by lmussier** [comment]
@olivierbloch Yes this is simply the **env** var to set correctly.
I won't close the issue since it was open by @MichaelDenczek and his problem seems to not be solved.
But thanks for the support, I can compile the SDK now without modification.

**Comment by MichaelDenczek** [comment]
Upgrading CMake from version 3.1.0 rc3 to 3.7.2 fixed the problem on Windows 7.  Apparently just the documentation needs updating with the corrected CMake min version.
