### ISSUE TITLE
IoTHubClientCore_LL_DoWork may block if there are enough DirectMethod requests

### ISSUE THREAD

**Issue by XMrVertigoX** [Azure/azure-iot-sdk-c#831]
- **OS and version used:** <VERSION> 
ESP32 platform with FreeRTOS from ESP-IDF (v3.1.1)

- **SDK version used:** <VERSION> 
2018-09-11/v1.2.11

# Description of the issue:

If there are a constant stream of DirectMethod requests `IoTHubClientCore_LL_DoWork()` blocks implicitly.

This does the following:
- The task may never enter blockd state and therefore shadows all tasks with lower priority
- If there is a watchdog it is impossible to feed it

# Code sample exhibiting the issue:

The following snippet shows the problematic loop:
```
static void dowork_read(TLS_IO_INSTANCE* tls_io_instance)
{
    // ...

    while (rcv_bytes > 0)
    {
        // ...
    }
}
```
As long as `rcv_bytes > 0` this loop never breaks.

**Comment by XMrVertigoX** [comment]
Short update: The problem seems to be in lower io layer which handles incoming raw bytes. As long as it reveices soething it runs through the decode.

**Comment by massand** [comment]
@XMrVertigoX - the DoWork() loop is driven differently if the _LL_ APIs are used vs the convenience (non _LL_ version is used). So, we need a few additional pieces of info: 1) is this over all protocols (MQTT, AMQP), 2) is there outgoing messages blocked due to the incoming direct method calls, and 3) can you provide a concise sample demonstrating the issue using direct method callback (along with any other processing you are attempting to do - e.g telemetry sends at the same time getting block) for ESP32, so we can repro the issue faster?

**Comment by XMrVertigoX** [comment]
@massand - Regarding to your questions:
1) I can't confirm that this problem occurs also with AMQP. I'm using MQTT at the moment.
2) Outgoing messages are in deed blocked. After all message are processed I get a bunch of 'send confirmation callbacks'.
3) Unfortunately I cannot. It's all customer code and I hanen't done an isolated example yet. But I went a bit further down the rabbit hole and can confirm the following:

I send three parallel (threaded) requests to the IoT Hub targeting the same device and this piece of code (the prints are inserted by me) from 'tlsio_openssl_compact.c'
```
printf(">>>\r\n");
while (rcv_bytes > 0)
{
    // tls_io_instance->on_bytes_received was already checked for NULL
    // in the call to tlsio_openssl_open_async
    /* Codes_SRS_TLSIO_30_100: [ As long as the TLS connection is able to provide received data, tlsio_dowork shall repeatedly read this data and call on_bytes_received with the pointer to the buffer containing the data, the number of bytes received, and the on_bytes_received_context. ]*/
    tls_io_instance->on_bytes_received(tls_io_instance->on_bytes_received_context, buffer, rcv_bytes);
    rcv_bytes = SSL_read(tls_io_instance->ssl, buffer, sizeof(buffer));
}
printf("<<<\r\n");
```
results in this output
```
>>>
D (08:41:36) <CIoTHubClient_callback.cpp> ENTER: DeviceMethodCallback
D (08:41:36) <CIoTHubClient_callback.cpp> EXIT: DeviceMethodCallback
D (08:41:36) <CIoTHubClient_callback.cpp> ENTER: DeviceMethodCallback
D (08:41:36) <CIoTHubClient_callback.cpp> EXIT: DeviceMethodCallback
D (08:41:36) <CIoTHubClient_callback.cpp> ENTER: DeviceMethodCallback
D (08:41:36) <CIoTHubClient_callback.cpp> EXIT: DeviceMethodCallback
<<<
```
I hope this enables you to reproduce this behaviour.

Regards
Caspar

**Comment by YoDaMa** [comment]
Hey @XMrVertigoX thanks for showing this to us, and I'm working on spiking a solution to it. Would you be able to test a solution to this issue once published to a branch?

**Comment by ewertons** [comment]
Pasting link for reference: https://github.com/Azure/azure-iot-pal-esp32/blob/master/pal/src/tlsio_openssl_compact.c

**Comment by YoDaMa** [comment]
@XMrVertigoX I've opened up a PR in the ESP32 repo to patch this infinite loop.

**Comment by YoDaMa** [comment]
Talking with the team some more, there's some confusion still. Are you using the PAL layer in the link referenced? It has been deprecated and is about to be archived, and we encourage folks to use the PAL layer espressif offers for the client library: https://github.com/espressif/esp-azure.

**Comment by YoDaMa** [comment]
@XMrVertigoX, because we've identified the code to be from a deprecated branch, I'm going to go ahead and close this. If you're having issues with the ESP-Azure code please let us know and reopen.

**Comment by az-iot-builder-01** [comment]
@XMrVertigoX, @massand, @YoDaMa, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
