### ISSUE TITLE
SSL Errors

### ISSUE THREAD

**Issue by mshafique** [Azure/azure-iot-sdk-c#84]
Hi,

I am using Device SDK on Linux and seeing following errors:

Error: Time:Mon Mar  6 23:42:29 2017 File:iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:951 Connection Not Accepted: 0x5: Not Authorized
Error: Time:Mon Mar  6 23:42:29 2017 File:c-utility/src/tlsio_openssl.c Func:decode_ssl_received_bytes Line:654 SSL channel closed in decode_ssl_received_bytes.
Error: Time:Mon Mar  6 23:42:29 2017 File:c-utility/src/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:709 Error in decode_ssl_received_bytes.

I have checked the time of the system and also the certificates. They look OK. What am I missing? Any suggestions pointers will be helpful.

**Comment by mm-imr** [comment]
Hi there,
we have seen that a wrong system time leads to failing TLS stuff. So turn on your NTP by default.

Best,

Ingo

**Comment by mshafique** [comment]
Thanks for prompt response.  I am checking on NTP in my system. Is there any timezone setting that the device time should conform to? 

Also is there any persistence in SSL connections? e.g. if I connect and disconnect quickly again and again ... will this cause any issues like this? with one session overlapping other and potentially creating conflict situation?

**Comment by mm-imr** [comment]
As I remember it was an certificate thing: if your local time is to far behind, the certification's is only valid in the future and that makes the trouble. So, I thing your time zone doesn't play such a role here.

Best,

Ingo

**Comment by anporumb** [comment]
Hello all,

It seems you've figured it out. I will close now the issue. Feel free to reopen if needed.

Best Regards,
Andrei Porumb
