### ISSUE TITLE
After Expiration of Retry, IoTHubDeviceClient_LL_SetRetryPolicy API is sending IOTHUB_CLIENT_CONNECTION_NO_NETWORK instead of IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED to IoTHubDeviceClient_LL_SetConnectionStatusCallback

### ISSUE THREAD

**Issue by Pavan2358** [Azure/azure-iot-sdk-c#841]
Hi 
1) I am trying to use IoTHubDeviceClient_LL_SetRetryPolicy with Retry Policy as IOTHUB_CLIENT_RETRY_INTERVAL and giving time out value as 300 seconds. As per my understanding Azure SDK retries every 5 seconds(default) for about 300 seconds and stops using the above mentioned api after the time out of 300 seconds. Each time the retry is triggered due to disconnection ConnectionStatus Callback is triggered and reason for failure is printed. I believe that after 300 seconds reason has to be IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED(3) and not IOTHUB_CLIENT_CONNECTION_NO_NETWORK(4).
 As per the below Document
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/connection_and_messaging_reliability.md
which says "When the device client ceases attempting to re-connect (if the Retry Policy no longer allows to)." Connection Status Callback will be invoked, I believe my understanding is correct.
PFA Sample Code and Log File. Please Correct me if I have done wrong
2) Also Can you please suggest which API to call, to change the interval default time from 5 seconds to may be 15-20 seconds
[telemetry_sample.txt](https://github.com/Azure/azure-iot-sdk-c/files/2821227/telemetry_sample.txt)
[Log.txt](https://github.com/Azure/azure-iot-sdk-c/files/2821232/Log.txt)

**Comment by bikamani** [comment]
#750 (Related to same investigation)

**Comment by bikamani** [comment]
https://github.com/Azure/azure-iot-sdk-c/issues/618
https://github.com/Azure/azure-iot-sdk-c/issues/731

**Comment by bikamani** [comment]
Hi @Pavan2358 , 

1. I looked at the sample you provided and could repro it with MQTT, we will be adding a fix for this soon. Also if it helps for it works on AMQP and I do see IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED for the callback with same telemetry sample.

2. Currently there's not an API to change the default interval time but we will mark this as an enhancement. Here's where it is set:  https://github.com/Azure/azure-iot-sdk-c/blob/c97cf4bd1c0f6652103999f5fe4d3a2fe1bf1c22/iothub_client/src/iothub_client_retry_control.c#L295

Hope this helps. 

Thanks,
Binal

**Comment by Pavan2358** [comment]
Hi @bikamani 

Thanks for the response, We need to work with MQTT as per our business requirement. I hope the bug fix and enhancement will be available in the next release(Fingers Crossed)!!:)

**Comment by bikamani** [comment]
Bug fix for MQTT retry expired callback status is added here https://github.com/Azure/azure-iot-sdk-c/pull/848

**Comment by Pavan2358** [comment]
Hi @bikamani 

2. "Currently there's not an API to change the default interval time but we will mark this as an enhancement. Here's where it is set:"
Is this fix included in #848 ?
If so can you please help me with the API and values to be passed to it

**Comment by bikamani** [comment]
Hi, The fix is only addressing callback issue for retry expired. We will keep you posted for the time interval enhancement.

**Comment by Pavan2358** [comment]
Hi @bikamani

Thank you for the update

**Comment by bikamani** [comment]
Assigning to @ewertons for taking care of the enhancement of interval time configuration.

**Comment by ewertons** [comment]
Removing the bug tag since the original issue was fixed.
The enhancement is still in progress.

**Comment by jspaith** [comment]
This is the only request we've heard of for configurable time limit statically like this, so unfortunately it's not something we're going to address.  We're looking at a model where the app itself can get more control over this, which would ultimately be the way we'd want to address this issue, but that's not in the immediate term.

**Comment by az-iot-builder-01** [comment]
@bikamani, @Pavan2358, @ewertons, @jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
