### ISSUE TITLE
Double Free?

### ISSUE THREAD

**Issue by maskimthedog** [Azure/azure-iot-sdk-c#859]
STM32F4 32 vit ARM CM3

- **OS and version used:** <VERSION> 
FreeRTOS 9

- **SDK version used:** <VERSION> 
1.2.13

# Description of the issue:

It looks like a double free is occurring in wsio.c in the function called  wsio_send() on pending_socket_io.  Free RTOS heap free API function indicates that the block being freed is not allocated.  In the code snippet below, I have fixed the issue so that pending_socket_io is freed only if it was successfully removed from the list.  If it is not in the list, has it most likely been freed by another layer?

Code sample exhibiting the issue:

```
int wsio_send(CONCRETE_IO_HANDLE ws_io, const void* buffer, size_t size, ON_SEND_COMPLETE on_send_complete, void* callback_context)
{
    int result;

    /* Codes_SRS_WSIO_01_100: [ If any of the arguments ws_io or buffer are NULL, wsio_send shall fail and return a non-zero value. ]*/
    if ((ws_io == NULL) ||
        (buffer == NULL) ||
        /* Codes_SRS_WSIO_01_101: [ If size is zero then wsio_send shall fail and return a non-zero value. ]*/
        (size == 0))
    {
        LogError("Bad arguments: ws_io=%p, buffer=%p, size=%u",
            ws_io, buffer, (unsigned int)size);
        result = __FAILURE__;
    }
    else
    {
        WSIO_INSTANCE* wsio_instance = (WSIO_INSTANCE*)ws_io;

        if (wsio_instance->io_state != IO_STATE_OPEN)
        {
            /* Codes_SRS_WSIO_01_099: [ If the wsio is not OPEN (open has not been called or is still in progress) then wsio_send shall fail and return a non-zero value. ]*/
            LogError("Attempting to send when not open");
            result = __FAILURE__;
        }
        else
        {
            LIST_ITEM_HANDLE new_item;
            PENDING_IO* pending_socket_io = (PENDING_IO*)malloc(sizeof(PENDING_IO));
            if (pending_socket_io == NULL)
            {
                /* Codes_SRS_WSIO_01_134: [ If allocating memory for the pending IO data fails, wsio_send shall fail and return a non-zero value. ]*/
                result = __FAILURE__;
            }
            else
            {
                /* Codes_SRS_WSIO_01_103: [ The entry shall contain the on_send_complete callback and its context. ]*/
                pending_socket_io->on_send_complete = on_send_complete;
                pending_socket_io->callback_context = callback_context;
                pending_socket_io->wsio = wsio_instance;

                /* Codes_SRS_WSIO_01_102: [ An entry shall be queued in the singly linked list by calling singlylinkedlist_add. ]*/
                if ((new_item = singlylinkedlist_add(wsio_instance->pending_io_list, pending_socket_io)) == NULL)
                {
                    /* Codes_SRS_WSIO_01_104: [ If singlylinkedlist_add fails, wsio_send shall fail and return a non-zero value. ]*/
                    free(pending_socket_io);
                    result = __FAILURE__;
                }
                else
                {
                    /* Codes_SRS_WSIO_01_095: [ wsio_send shall call uws_client_send_frame_async, passing the buffer and size arguments as they are: ]*/
                    /* Codes_SRS_WSIO_01_097: [ The is_final argument shall be set to true. ]*/
                    /* Codes_SRS_WSIO_01_096: [ The frame type used shall be WS_FRAME_TYPE_BINARY. ]*/
                    if (uws_client_send_frame_async(wsio_instance->uws, WS_FRAME_TYPE_BINARY, (const unsigned char*)buffer, size, true, on_underlying_ws_send_frame_complete, new_item) != 0)
                    {
                        **if (singlylinkedlist_remove(wsio_instance->pending_io_list, new_item) != 0)
                        {
                            LogError("Failed removing pending IO from linked list.");
                        }
                        else
                        {
                            free(pending_socket_io);
                        }**
                        result = __FAILURE__;
                    }
                    else
                    {
                        /* Codes_SRS_WSIO_01_098: [ On success, wsio_send shall return 0. ]*/
                        result = 0;
                    }
                }
            }
        }
    }

    return result;
}
```
# Console log of the issue:

Code just freezes in FreeRTOS assert in heap free API function.

**Comment by ewertons** [comment]
Hi @maskimthedog ,

thanks for reporting this. 
However, I am not so sure the change above addresses a potential double-free issue. It might actually be hiding it more.

If uws_client_send_frame_async fails, there is an expectation that on_underlying_ws_send_frame_complete will not be called from within.
If it is, then that would cause a double-free when a few lines later `free(pending_socket_io);` gets called, because on_underlying_ws_send_frame_complete also has code to destroy that instance.

Checking uws_client_send_frame_async (latest from master) there is no call to the callback if an error occurs within the function.

Another data point on this investigation is that we run this code under valgrind, which is pretty accurate pointing memory allocation issues.

I know freertos is a little limited in terms of gathering logs, but do you get a specific error message? How did you assert that "Free RTOS heap free API function indicates that the block being freed is not allocated."?

If you have access to the memory to verify, one situation that we handled before was that there was a memory corruption cause somewhere else that would change a pointer, then when code block that owned the pointer tried to free it, it would also report similar message. Again, in that case valgrind helped pinpoint the error. Is it possible for you to put a breakpoint when pending_socket_io gets created and when free is invoked, and see if the address is the same?

**Comment by maskimthedog** [comment]
Without the hack I put in, I can get this to happen very, very frequently.  Without the hack, it does not seem to happen.  I was previously utilizing a very, very old version (1.1.16) of Azure IoT Hub C SDK and I did not see this issue.  However, I do realize that the source has probably undergone many re-archs since then.  The FreeRTOS heap management "free" function can detect a double free.  I can take out the hack and set some breakpoints and put in some prints to gather more information.  Thank you for your very quick response!

**Comment by ewertons** [comment]
Hi @maskimthedog ,
thanks for the reply. 
So to clarify, you did not see the issue with version 1.1.16, but you are seeing it now with 1.2.13 (which you are using now), is that correct?
Did you have a chance to get those traces by any chance? Thanks for you collaboration on this.

**Comment by maskimthedog** [comment]
That is correct.  I did not see the issue on 1.1.16.  However, on 1.1.16 I was utilizing MQTT, but on 1.2.14, I am using MQTT over websockets.  So, not exactly apples-to-apples here.  Websockets did not appear to be that mature in 1.1.16, so I moved to 1.2.xx.  Our product is WiFi based and we need to utilize port 443 in order to circumvent customer firewalls.

**Comment by maskimthedog** [comment]
My ecosystem is STM32F4, FreeRTOS 9 and Azure IoT Hub C SDK 1.2.xx.

**Comment by maskimthedog** [comment]
You can close this.  I have another model of gateway running FreeRTOS and 1.2.14 and different application code that runs beautifully.  After some testing on the other model of gateway, it looks like there is heap trashing going on.  :(

**Comment by maskimthedog** [comment]
Wait, my other gateway runs MQTT without websockets.  The gateway exhibiting the issue still exhibits it.  I will collect more information.

**Comment by maskimthedog** [comment]
This issue is still present in 1.3.4 and the fix is still the same.

**Comment by rafilho** [comment]
@maskimthedog: which freeRTOS heap are you using so I can try to repro?

**Comment by maskimthedog** [comment]
STM32F4 is the MCU and I am using heap 5 (SRAM and CCRAM combined to form the heap).  I do not think that this is a heap issue.  It looks as though the item that is presumed to be in the linked list has already been removed and freed.  I get an error from the heap when an attempt to free the item is made to the affect that it cannot be freed because it is not allocated.  Due to the recursive nature of this SDK it seems likely that this may be likely?

**Comment by rafilho** [comment]
I don't think it is a heap issue either. I was just trying to collect enough info to repro it, which I wasn't able yet. Do you have by any chance the call stack at the moment the issue happen? Would you also be able to put a break point in this memory address as a way to figure it out which other piece of code is releasing this memory? Also, I am assuming you have created a port for FreeRTOS and therefore implemented a tlsio for it, corrrect?

**Comment by maskimthedog** [comment]
I will try to get you a call stack (have to work to make uws_client_send_frame_async fail).  I can share our FreeRTOS shim files such as TLSIO with you out-of-band if you provide me with a Dropbox location via a private email.

**Comment by maskimthedog** [comment]
It really seems like this can happen if on_underlying_io_send_complete() is called by xio_send() call tree on the failure within the same thread of execution removing the item from the list and freeing it.  When xio_send() returns, the item is gone from the list and has already been freed.

**Comment by maskimthedog** [comment]
Could this be happening on mbedtls renegotiate?  Maybe there is something there?

**Comment by rafilho** [comment]
We just enabled mbedtls renegotiation in a check-in few days ago. Since you hit this issue way before, I don't think this is the case. However, it would be nice if we could double check your FreeRTOS implementation for the xio layer. I will follow up privately.

**Comment by maskimthedog** [comment]
I know.  However, I have had renegotiation enabled for mbedtls for a year now in my tlsio.

**Comment by maskimthedog** [comment]
I cannot get to fail now.  ;-)

**Comment by maskimthedog** [comment]
Working on it.

**Comment by maskimthedog** [comment]
I am using 1.3.4.

**Comment by rafilho** [comment]
Thanks. If you are able to repro it, please try to collect the call stack. It will help me to repro it on my side or at least have a better understanding of the code flow up to the issue.

**Comment by maskimthedog** [comment]
I have attached my tlsio file.  I attempted to use your tlsio file from the adapters directory (bottom half of #ifdef).  However, I could never successfully connect using it and the added layers made it a little difficult debug.  So, I decided to stick with my original.

[az_tlsio_mbedtls.c.txt](https://github.com/Azure/azure-iot-sdk-c/files/3602340/az_tlsio_mbedtls.c.txt)

**Comment by jspaith** [comment]
Thanks @maskimthedog for letting us know the issue doesn't reproduce anymore.  Closing out the GitHub item.

**Comment by az-iot-builder-01** [comment]
@ewertons, @maskimthedog, @rafilho, @jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
