### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by Norman0406** [Azure/azure-iot-sdk-c#86]
Hello,

We are developing an agent that is supposed to be continously connected to the platform and sending data using MQTT from our machines to the Azure platform. Although we see in the logs that the SDK gets disconnected from time to time, it usually reconnects soon after. After some time however (typically > 12h), the SDK does not connect to the Iot Hub anymore.

The following log messages are generated:

> Info: Evaluated delay 0 at 0 attempt to retry
> 
> Error: Time:Tue Mar  7 18:47:43 2017 File:D:\dev\external\azure-iot-sdk-c\umqtt\src\mqtt_client.c Func:_sendPacketItem Line:322 992: Failure sending control packet data
> Error: Time:Tue Mar  7 18:47:43 2017 File:D:\dev\external\azure-iot-sdk-c\umqtt\src\mqtt_client.c Func:_mqtt_client_disconnect Line:1093 Error: mqtt_client_disconnect send failed
> Info: Evaluated delay 0 at 1 attempt to retry
> 
> Error: Time:Tue Mar  7 18:47:43 2017 File:D:\dev\external\azure-iot-sdk-c\umqtt\src\mqtt_client.c Func:_mqtt_client_connect Line:894 Error: io_open failed
> Error: Time:Tue Mar  7 18:47:43 2017 File:D:\dev\external\azure-iot-sdk-c\iothub_client\src\iothubtransport_mqtt_common.c Func:_SendMqttConnectMsg Line:1598 failure connecting to address Tomra-Insight-RM-DEVa9187.azure-devices.net:0.
> Info: Evaluated delay 0 at 2 attempt to retry
> 
> Error: Time:Tue Mar  7 18:47:49 2017 File:D:\dev\external\azure-iot-sdk-c\umqtt\src\mqtt_client.c Func:_mqtt_client_connect Line:894 Error: io_open failed
> Error: Time:Tue Mar  7 18:47:49 2017 File:D:\dev\external\azure-iot-sdk-c\iothub_client\src\iothubtransport_mqtt_common.c Func:_SendMqttConnectMsg Line:1598 failure connecting to address Tomra-Insight-RM-DEVa9187.azure-devices.net:0.
> Info: Evaluated delay 1 at 3 attempt to retry

These kinds of messages then go on for hours without the connection being reestablished, and the time between connection attempts gets bigger. I suppose this is because of the exponential backoff function. When the client is reinitialized (i.e. IoTHubClient_LL_Destroy followed by IoTHubClient_LL_Create), it connects successfully again.

We use SDK version 1.1.7 and compiled for Windows.

Best regards,
Norman

**Comment by anporumb** [comment]
Hello @Norman0406 ,

We will look into your report this month (March). Thank you.

Meanwhile, what is minimal repro for your problem? That would help us.

Best Regards,
Andrei Porumb

**Comment by Norman0406** [comment]
Hi @anporumb,

The problem seems to be resolved for now, our test machines have been running about a week now without further interruptions.
Our IT department noticed that when the machines reconnect to the platform (which happens a few times per day), they sometimes reconnect from a different IP address. Our company has a fixed set of outward IP addresses, and the machines sometimes got assigned a different one than before on the reconnection attempt.
Our guess is that the platform detected this, maybe got suspicious due to the change between IP addresses, and then blocked further connections.
Our IT department fixed this in our IT infrastructure, and we haven't gotten any problems since.

Best regards,
Norman

**Comment by ewertons** [comment]
Hi @Norman0406 , we are glad you were able to root cause and mitigate the issue.
Please let us know if the ticket can be closed.
Thanks for using the Azure IoT SDK, feel free to post any additional questions, comments or suggestions.

**Comment by Norman0406** [comment]
Hi @ewertons ,

Thanks, you can close the ticket.

Best regards,
Norman
