### ISSUE TITLE
IoTHub messages are getting timeout after 2 minutes even when the connectivity is ON.

### ISSUE THREAD

**Issue by JesvinJoseph** [Azure/azure-iot-sdk-c#867]
- **OS and version used: Ubuntu 16.04** <VERSION> 

- **SDK version used: 1.2.14, 1.2.12** <VERSION> 

# Description of the issue:
I used the iothub client telemetry sample code(azure-iot-sdk-c/iothub_client/samples/iothub_ll_telemetry_sample). The default message count in that sample is 5. I changed that to 20000. Then I run the sample with MQTT protocol. After 2 minutes(that is around 5300 messages in my machine), I am getting TIMEOUT error for all the rest of the messages till 20000. This is because the MQTT is getting disconnected after 2 minutes. I increased the OPTION_MESSAGE_TIMEOUT and OPTION_KEEP_ALIVE, but still after 2 minutes messages are getting TIMEOUT. 

# Changes made on the sample:

#define MESSAGE_COUNT 20000

tickcounter_ms_t timeout = 10 * 60 * 1000;
        if (IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_MESSAGE_TIMEOUT, &timeout) != IOTHUB_CLIENT_OK)
        {
            printf("\n\nFailure to set mqtt message timeout mode\n\n");
        }
        else
        {
            printf("\n\n successful to set mqtt message timeout mode\n\n");
        }
        int keep_alive = 2 * 60;
        if (IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_KEEP_ALIVE, &keep_alive) != IOTHUB_CLIENT_OK)
        {
            printf("\n\nFailure to set mqtt keep alive\n\n");
        }
        else
        {
            printf("\n\n successful to set mqtt keep alive\n\n");
        }

# Console log of the issue:

Confirmation callback received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 2 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 3 with result IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation callback received for message 4 with result IOTHUB_CLIENT_CONFIRMATION_OK
.
.
Confirmation callback received for message 5303 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 08:10:24 PUBACK | PACKET_ID: 5305
Confirmation callback received for message 5304 with result IOTHUB_CLIENT_CONFIRMATION_OK
**-> 08:10:24 DISCONNECT**
Confirmation callback received for message 5305 with result IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT
Confirmation callback received for message 5306 with result IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT
Confirmation callback received for message 5307 with result IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT
Confirmation callback received for message 5308 with result IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT
Confirmation callback received for message 5309 with result IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT
.
.
.
Confirmation callback received for message 19997 with result IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT
Confirmation callback received for message 19998 with result IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT
Confirmation callback received for message 19999 with result IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT
Confirmation callback received for message 20000 with result IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT

Azure sdk error is :- 

/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2351 mqtt_client timed out waiting for CONNACK
-> 08:11:00 CONNECT | VER: 4 | KEEPALIVE: 120 | FLAGS: 192 | USERNAME: test_iothub/test_device/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.14%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
<- 08:11:00 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0

**Comment by JesvinJoseph** [comment]
Telemetry sample is perfectly working for 20K messages in azure iot sdk c version 1.2.10.

**Comment by JesvinJoseph** [comment]
Is there any issue in the MQTT broker in IoTHuB?

**Comment by bikamani** [comment]
Hi @JesvinJoseph I am looking at verifying this issue, will keep you posted. Thank you.

**Comment by bikamani** [comment]
Hi @JesvinJoseph What is the region of your IoTHub? You can find this on the Overview page of your IoTHub in azure portal.

**Comment by JesvinJoseph** [comment]
It's North Europe.

**Comment by bikamani** [comment]
Thanks @JesvinJoseph . We had couple repro but with latest code, I haven't seen a repro anymore. Could you please verify if you are still seeing an issue with the latest code?

**Comment by bikamani** [comment]
Closing the issue as not a repro. Please reopen it if still facing issue and we can look further into this. Thank you.

**Comment by az-iot-builder-01** [comment]
@JesvinJoseph, @bikamani, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
