### ISSUE TITLE
Please provide x64 library in vcpkg

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-iot-sdk-c#868]
It seems there's no x64 bits in vcpkg, do you have plan to release x64 bits in vcpkg?

**Comment by ras0219-msft** [comment]
Hi @erich-wang, did you try installing the x64 version via `vcpkg install azure-iot-sdk-c:x64-windows`?

**Comment by massand** [comment]
Yes - we have installed x64 packages via the vcpkg triplet feature.

**Comment by az-iot-builder-01** [comment]
@ras0219-msft, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
