### ISSUE TITLE
Some characters in message property bag and/or message ID can disconnect MQTT client

### ISSUE THREAD

**Issue by AndWass** [Azure/azure-iot-sdk-c#869]
- **OS and version used:** Windows, Linux 

- **SDK version used:** All 

# Description of the issue:

If I send a message with a message ID of say `00:11:22:33`, or I have an ISO 8601 formatted timestamp (`2019-02-15T13:14:15Z`) as a header property I will get disconnected if I use the MQTT protocol. If I use AMQP everything works, but due to the fact that properties are sent as parameters in the PUBLISH endpoint name, Azure will disconnect me.

Is there a workaround available? Can I URL-encode property name/values and that will work? Will they automatically be decoded before triggering an Azure function for instance?

# Code sample exhibiting the issue:

# Console log of the issue:

Here is a logtrace where right after the last publish I get disconnected. Everything up to that point works.
```text
-> 16:11:31 SUBSCRIBE | PACKET_ID: 5 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/# | QOS: 0
<- 16:11:31 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/204/?$rid=4&$version=12 | PAYLOAD_LEN: 0
<- 16:11:31 SUBACK | PACKET_ID: 5 | RETURN_CODE: 0
Indicate state -> 16:11:31 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/<redacted>/messages/events/timestamp=2019-02-15T15:11:31Z&%24.mid=4429df08-2bc4-4a22-996a-2ddc7a4056ef&%24.ct=application/json | PACKET_ID: 6 | PAYLOAD_LEN: 218
DEBUG: Disconnected from Azure with reason = 4
```

**Comment by jebrando** [comment]
@AndWass Yes this is due to the properties having characters that IoTHub interprets as the separators.  The way you can fix this is set the following option on the device:

```c
bool urlEncodeOn = true;
IoTHubDeviceClient_LL_SetOption(iothub_ll_handle, OPTION_AUTO_URL_ENCODE_DECODE, &urlEncodeOn);
```

This will encode all properties going to and from the IoTHub.  You will then be able to safely add characters that are necessary.

Let me know if you have any issues with this.

**Comment by AndWass** [comment]
Ah ok! Will the hub automatically decode the properties as well before making them available on the events service bus for instance?

**Comment by ewertons** [comment]
Hi @AndWass ,
No, there is no decoding that happens on the service side.
Whenever you receive the data on the other end, you need to decode it on your application.

**Comment by AndWass** [comment]
@ewertons Ok thanks for the clarification!

Will close for now.

**Comment by az-iot-builder-01** [comment]
@jebrando, @AndWass, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
