### ISSUE TITLE
[CRITICAL]  - MQTT protocol does not work with TrustedCerts

### ISSUE THREAD

**Issue by mm-ark** [Azure/azure-iot-sdk-c#87]
Hi everyone,

MQTT protocol does not work (no connection to IoT Hub) when setting option TrustedCerts by IoTHubClient_LL_SetOption and the order of root certificates is "wrong".

--- This issue very CRITICAL and currently BLOCKING our release ---

Reproducable with latest code from master and any IoT Hub like myIoTHub.azure-devices.net
The mentioned IoT Hub needs baltimore root certificate, but it is not the first one within TrustedCerts ( certs.c)

Please use following steps to reproduce:
1. Make sure that your development computer can not connect to your IoT Hub  (e.g. delete all related root certificates from /etc/ssl/certs or other folders)
2. Enter your valid connection string into attached iothub_client_sample_mqtt.c
3. Compile and run attached iothub_client_sample_mqtt.c
4. Observe that client still can not connect to iothub with certs from attached certs.c

After delete WoSign cert only from certs.c and recompile the client will connect properly with baltimore cert.

[iothub_client_sample_mqtt.zip](https://github.com/Azure/azure-iot-sdk-c/files/828151/iothub_client_sample_mqtt.zip)
[certs.zip](https://github.com/Azure/azure-iot-sdk-c/files/828153/certs.zip)

**Comment by lmussier** [comment]
Hi @mm-ark are you able to test the same thing with MQTT over websockets?
We are looking for solutions to give certificates to the SDK, and I wonder if this issue also affect MQTT/WS.

Thanks.

**Comment by anporumb** [comment]
Hello @mm-ark ,

What is WoSign? We did not provide that certificate (as far as I know!). It so happens that just yesterday I've investigated a case where I could 100% prove that Baltimore is the only certificate needed for connecting to IoTHub. Since some while ago we are only providing Baltimore for in certs.c

How do I help you?

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Hello @mm-ark ,

I will correct myself. We are using different CA for different clouds. This is something I learned in the last hour.

It would seem we'd need to provide multiple root CAs. However, we are not doig that and did not test that. This is an important issue.

I would expect that sticking multiple CA roots in the certs.c file would cause the underlying TLS libraries to select "the proper one". Based on your issue, that does not seem to happen.

Best Regards,
Andrei Porumb

**Comment by mm-ark** [comment]
Hey Andrei,

I agree, to me it looks that SDK does not parse the given TrustedCerts correctly, so only the first one will be given to libssl. The first always wins is actually what i meant with "wrong" order above.

Our solution is required to support multiple root CAs (*.azure-devices.net, *.azure-devices.cn, *.azure-devices.de, ...)

Best regards
Anatolij

**Comment by anporumb** [comment]
You are perfectly right and I am working at the moment on 2 fronts: gather all the root CA that IoTHub uses throughout the world and providing a fix. 

I will keep you posted when both are checked in :).

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Hello @mm-ark ,

I have recently checked in master branch fixes that would allow openssl to receive a multitude of certificates. The certificates are also checked in.

I am hoping this unblocks you. If you still encounter issues, please reply here.

Best Regards,
Andrei Porumb

**Comment by rasheedaasir** [comment]
Hello @mm-ark ,
am having issue with compiling code for wago could you please help me out.
