### ISSUE TITLE
Device Streaming with amqp over websockets dies with Error in decode_ssl_received_bytes

### ISSUE THREAD

**Issue by ling0015** [Azure/azure-iot-sdk-c#870]
- **OS and version used:** <VERSION> 
Ubuntu: 16.04.5
dotnet:  2.2.103
OpenSSL: 1.0.2g 

- **SDK version used:** <VERSION> 
2019-01-22-public-preview 74b03316ec90f1602c20ebeab67a3b4a61065d8e

# Description of the issue:
I am running the C# service side proxy located at:
azure-iot-samples-csharp-master/iot-hub/Quickstarts/device-streams-proxy/service

I am running the device side proxy located at:
azure-iot-sdk-c/iothub_client/samples/iothub_client_c2d_streaming_proxy_sample

I am using amqp over websockets.

I am able to connect using:
```
ssh username@localhost -p 2222
```
Once connected I am able to repeatedly ping google and cat /proc/cpuinfo. However, after a short time my connection is dropped with the error "Error in decode_ssl_received_bytes". The service side application remains running and I am able to connect again by running the device side program.

# Console log of the issue:
-> Header (AMQP 0.1.0.0)
<- Header (AMQP 0.1.0.0)
-> [OPEN]. {...................,...................,4294967295,65535,240000}
<- [OPEN]. {DeviceGateway_.........................,10.0.0.39,65536,8191,240000,NULL,NULL,NULL,NULL,NULL}
-> [BEGIN]. {NULL,0,4294967295,100,4294967295}
<- [BEGIN]. {0,1,5000,4294967295,262143,NULL,NULL,NULL}
-> [ATTACH]. {$cbs-sender,0,false,0,0,. {$cbs},. {$cbs},NULL,NULL,0,0}
-> [ATTACH]. {$cbs-receiver,1,true,0,0,. {$cbs},. {$cbs},NULL,NULL,NULL,0}
<- [ATTACH]. {$cbs-sender,0,true,0,0,. {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},. {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,NULL}
<- [FLOW]. {0,5000,1,4294967295,0,0,100,0,NULL,false,NULL}
-> [TRANSFER]. {0,0,<01 00 00 00>,0,false,false}
<- [ATTACH]. {$cbs-receiver,1,false,0,0,. {$cbs,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},. {$cbs,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,1048576,NULL,NULL,NULL}
-> [FLOW]. {1,4294967295,1,99,1,0,10000}
<- [DISPOSITION]. {true,0,NULL,true,. {},NULL}
<- [TRANSFER]. {1,0,<01 00 00 00>,0,NULL,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]. {true,0,0,true,. {}}
-> [ATTACH]. {link-snd-...................,2,false,0,0,. {link-snd-...................-source},. {amqps://.................../devices/.................../messages/events},NULL,NULL,0,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.2.12 (native; Linux; x86_64)]}}
-> [ATTACH]. {link-snd-...................,3,false,0,0,. {link-snd-...................-source},. {amqps://.................../devices/.................../twin},NULL,NULL,0,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.2.12 (native; Linux; x86_64)],[com.microsoft:channel-correlation-id:twin:...................],[com.microsoft:api-version:2016-11-14]}}
<- [ATTACH]. {link-snd-...................,2,true,0,NULL,. {link-snd-...................-source,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},. {amqps://.................../devices/.................../messages/events,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.2.12 (native; Linux; x86_64)]}}
<- [FLOW]. {1,5000,2,4294967295,2,0,1000,0,NULL,false,NULL}
<- [ATTACH]. {link-snd-...................,3,true,1,0,. {link-snd-...................-source,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},. {amqps://.................../devices/.................../twin,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.2.12 (native; Linux; x86_64)],[com.microsoft:channel-correlation-id:twin:...................],[com.microsoft:api-version:2016-11-14]}}
<- [FLOW]. {1,5000,2,4294967295,3,0,1000,0,NULL,false,NULL}
-> [ATTACH]. {link-rcv-...................,4,true,0,0,. {amqps://.................../devices/.................../twin},. {link-rcv-...................-target},NULL,NULL,NULL,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.2.12 (native; Linux; x86_64)],[com.microsoft:channel-correlation-id:twin:90ae1665-23d4-4501-857a-8558e5cf101a],[com.microsoft:api-version:2016-11-14]}}
<- [ATTACH]. {link-rcv-...................,4,false,1,0,. {amqps://.................../devices/.................../twin,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},. {link-rcv-...................-target,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.2.12 (native; Linux; x86_64)],[com.microsoft:channel-correlation-id:twin:...................],[com.microsoft:api-version:2016-11-14]}}
-> [FLOW]. {2,4294967294,1,99,4,0,10000}
-> [ATTACH]. {link-snd-...................,5,false,0,0,. {link-snd-...................feb-source},. {amqps://.................../devices/.................../streams},NULL,NULL,0,18446744073709551615,NULL,NULL,{[com.microsoft:channel-correlation-id:streams:...................],[com.microsoft:client-version:iothubclient/1.2.12 (native; Linux; x86_64)],[com.microsoft:api-version:2016-11-14]}}
<- [ATTACH]. {link-snd-...................,5,true,1,0,. {link-snd-...................feb-source,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},. {amqps://.................../devices/.................../streams,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:channel-correlation-id:streams:...................],[com.microsoft:client-version:iothubclient/1.2.12 (native; Linux; x86_64)],[com.microsoft:api-version:2016-11-14]}}
<- [FLOW]. {1,5000,2,4294967294,5,0,1000,0,NULL,false,NULL}
-> [ATTACH]. {link-rcv-...................,6,true,0,0,. {amqps://.................../devices/.................../streams},. {link-rcv-...................-target},NULL,NULL,NULL,18446744073709551615,NULL,NULL,{[com.microsoft:channel-correlation-id:streams:...................],[com.microsoft:client-version:iothubclient/1.2.12 (native; Linux; x86_64)],[com.microsoft:api-version:2016-11-14]}}
<- [ATTACH]. {link-rcv-...................,6,false,1,0,. {amqps://.................../devices/.................../streams,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},. {link-rcv-...................-target,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,1048576,NULL,NULL,{[com.microsoft:channel-correlation-id:streams:...................],[com.microsoft:client-version:iothubclient/1.2.12 (native; Linux; x86_64)],[com.microsoft:api-version:2016-11-14]}}
-> [FLOW]. {2,4294967294,1,99,6,0,10000}
<- [TRANSFER]. {6,1,<15 36 F7 D6 7C 42 B2 4C 82 D1 80 55 BC A0 9B DD>,0,true,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]. {true,1,1,true,. {}}
Received stream request (TestStream)
-> [TRANSFER]. {5,1,<01 00 00 00>,0,false,false}
<- [DISPOSITION]. {true,1,NULL,true,. {},NULL}
Client connected to the streaming gateway (WS_OPEN_OK)
Reporting traffic statistics every 10 seconds.
[2019-02-13 08:18:16 UTC-0600] Network traffic (in bytes) (sent=41; received=41)
[2019-02-13 08:18:26 UTC-0600] Network traffic (in bytes) (sent=4784; received=3272)
[2019-02-13 08:18:36 UTC-0600] Network traffic (in bytes) (sent=1456; received=324)
[2019-02-13 08:18:46 UTC-0600] Network traffic (in bytes) (sent=11768; received=504)
on_ws_peer_closed (Code: 1011, Data: WS disconnected)
Error: Time:Wed Feb 13 08:19:16 2019 File:/home/....../Repositories/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Error: Time:Wed Feb 13 08:19:16 2019 File:/home/....../Repositories/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
-> [DETACH]. {5,true}
-> [DETACH]. {6,true}
-> [DETACH]. {2,true}
-> [DETACH]. {3,true}
-> [DETACH]. {4,true}
-> [DETACH]. {0,true}
-> [DETACH]. {1,true}
-> [END]. {}
-> [CLOSE]. {}
Press any key to continue

**Comment by ewertons** [comment]
Hi @ling0015 ,

do you see these lines?

[2019-02-13 08:18:16 UTC-0600] Network traffic (in bytes) (sent=41; received=41)
[2019-02-13 08:18:26 UTC-0600] Network traffic (in bytes) (sent=4784; received=3272)
[2019-02-13 08:18:36 UTC-0600] Network traffic (in bytes) (sent=1456; received=324)
[2019-02-13 08:18:46 UTC-0600] Network traffic (in bytes) (sent=11768; received=504)
on_ws_peer_closed (Code: 1011, Data: WS disconnected)

This means the device streaming connection got established (websocket connection to the streaming gateway). However, the C-sdk side got a websocket CLOSE frame and disconnected, which is expected on that sample.
That means that the other side (C#) has closed the websocket connection.
Could you verify what happened on the C# side of your experiment? did you disconnect, or did you get any exceptions printed in the console?

**Comment by ling0015** [comment]
Yes, as I said I was able to connect through ssh and perform operations like pinging google etc.

I just went back and tested again. It seems that the connection hangs up on the C-SDK side after 60s whether the ssh is idle or pinging continuously. The SSH session says "Connection to localhost closed by remote host." which leads me to believe the hangup is on the C-SDK side.

As for the C# side. When the C-SDK program terminates I am able to simply restart it without doing anything with the C# side. It does not encounter any errors or exceptions:

$ sudo dotnet run "HostName=................azure-devices.net;SharedAccessKeyName=service;SharedAccessKey=.......... .........@1 2222
Stream response received: Name=TestStream IsAccepted=True
Starting streaming
Done streaming
Stream response received: Name=TestStream IsAccepted=True
Starting streaming
Done streaming
Stream response received: Name=TestStream IsAccepted=True
Starting streaming
Done streaming
Stream response received: Name=TestStream IsAccepted=True
Starting streaming
Done streaming

**Comment by ewertons** [comment]
Hi @ling0015 ,
many fixes have been provided and it might have addressed your issue.
Please verify again whenever possible, and feel free to reopen this issue to follow up if you would like to.
Thanks for contributing to the Azure IoT SDKs.

**Comment by az-iot-builder-01** [comment]
@ewertons, @ling0015, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
