### ISSUE TITLE
Deinit and Handle destroy is blocking thread.

### ISSUE THREAD

**Issue by ajaskumarpa** [Azure/azure-iot-sdk-c#872]
Hi, 

I am using IOT C sdk with HTTP protocol. I have a thread which is monitoring network connectivity. Which will do IoTHubClient_Destroy() then platform_deinit() if network is not available. Once the network is up it is suppose to do platform_init() and re initialization of the handle. My issue is, after calling IoTHubClient_Destroy() my thread has stopped running. If I comment out the IoTHubClient_Destroy() then thread is running fine. But my CPU usage is becoming high. Please help.

**Comment by jebrando** [comment]
@ajaskumarpa Can you send us sample code that exhibits this issue.

**Comment by ajaskumarpa** [comment]
hi below code is creating thread blockage 

IOTCommunicationHandler::~IOTCommunicationHandler()
{
	//std::lock_guard<std::mutex> lock(m_mutex);
	if (m_IoTHubClientHandle != nullptr)
	{

		IoTHubClient_Destroy(m_IoTHubClientHandle);
		m_IoTHubClientHandle = nullptr;
		platform_deinit();
	}
}

**Comment by ajaskumarpa** [comment]
Any update on this? @jebrando @massand

**Comment by ewertons** [comment]
Hi @ajaskumarpa , we have a few questions to help understand this:
- What do you specifically mean by your thread stops running? Are you saying your main thread gets blocked? What indications are you getting that that is happening?
- Also, we have template that you can use to provide details about your environment, SDK version, etc (the one it shows up when you open an issue); could you fill it up with all the details of your environment please?
- Based on the info above, if there is a way for your to run your application under a debugger, would you be able to break when the thread gets stuck and get a callstack? that will be the most direct way to understand what is getting blocked.
- On your application, are you subscribing for C2D messages or using any other feature?

**Comment by ajaskumarpa** [comment]
* What do you specifically mean by your thread stops running? Are you saying your main thread gets blocked? What indications are you getting that that is happening?
Ans:- I have a thread which is monitoring the network connectivity every 20 second.If the network is not connected this thread will call 
IoTHubClient_Destroy(m_IoTHubClientHandle);. What I observed is after executing this line my thread has stopped running. I need this thread to be run then only i can continue my monitoring and re initialize my IOT sdk connection.
* Also, we have template that you can use to provide details about your environment, SDK version, etc (the one it shows up when you open an issue); could you fill it up with all the details of your environment please?
Ans:- 

- **OS and version used:** Ubuntu 15.04 

- **SDK version used:** azure-iot-sdk-c Feb 2018


* Based on the info above, if there is a way for your to run your application under a debugger, would you be able to break when the thread gets stuck and get a callstack? that will be the most direct way to understand what is getting blocked.
Ans: This i will try
* On your application, are you subscribing for C2D messages or using any other feature?
Ans:- Yes. I am sending messages using IoTHubClient_SendEventAsync() and subscribed to C2D to receive the response.

**Comment by ewertons** [comment]
Hi @ajaskumarpa ,
thanks for the details.
Were you able to get a callstack of the application when it gets blocked?

**Comment by YoDaMa** [comment]
@ajaskumarpa it's been a while since you last responded so I will go ahead and close this issue. If you have further questions feel free to open a new issue.

**Comment by az-iot-builder-01** [comment]
@jebrando, @ajaskumarpa, @ewertons, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
