### ISSUE TITLE
Arduino Feather Huzzah ESP8266 Sample Unable to Compile

### ISSUE THREAD

**Issue by YoDaMa** [Azure/azure-iot-sdk-c#877]
Arduino Version: 1.8.8
ESP8266 Library Version: 2.5.0

When running the Feather Huzzah Sample Code I get an error on compile time:

![image](https://user-images.githubusercontent.com/8214060/53206654-64b75f00-35e6-11e9-8403-45eb64c75dee.png)

**Comment by YoDaMa** [comment]
The solution to this issue is to comment out the line mentioned in the errors in the ESP8266/Arduino.h file. It seems to be clashing with the main Arduino.h file defined in the Arduino program folder itself.

**Comment by az-iot-builder-01** [comment]
@YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
