### ISSUE TITLE
UploadToBlob does not work with TrustedCerts and AMQP

### ISSUE THREAD

**Issue by czyba** [Azure/azure-iot-sdk-c#88]
I have noticed that the TrustedCert Option does not work on Linux systems when using UploadBlob when using AMQP. It seems that the certs are not given to libcurl.
This issue should be similar and might possibly be fixed by fixing #87. 

I was able to reproduce this issue on Debian Jessie i386 and powerpc, as well as x86_64 gentoo with the 2017-02-24 tag (I believe version 1.1.8) of the SDK.

Steps to reproduce:

1. Make sure that your development computer can not connect to your IoT Hub (e.g. delete all related root certificates from /etc/ssl/certs or other folders)
2. Enter your valid connection string into attached iothub_client_sample_upload_to_blob.c
3. Compile and run attached iothub_client_sample_upload_to_blob.c
4. Observe that the method fails inside of curl.

You should get a similar log:
```
Starting the IoTHub client sample upload to blob...
Info: IoT Hub SDK for C, version 1.1.8
Error: Time:Mon Mar 13 10:29:02 2017 File:/home/ccz/develop/develop_azure-client/azure-2017-02-24/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:534 curl_easy_perform() failed: Problem with the SSL CA cert (path? access rights?)

Error: Time:Mon Mar 13 10:29:02 2017 File:/home/ccz/develop/develop_azure-client/azure-2017-02-24/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:536 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Mon Mar 13 10:29:02 2017 File:/home/ccz/develop/develop_azure-client/azure-2017-02-24/azure-iot-sdk-c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Mon Mar 13 10:29:02 2017 File:/home/ccz/develop/develop_azure-client/azure-2017-02-24/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_step1and2 Line:235 unable to HTTPAPIEX_ExecuteRequest
Error: Time:Mon Mar 13 10:29:02 2017 File:/home/ccz/develop/develop_azure-client/azure-2017-02-24/azure-iot-sdk-c/iothub_client/src/iothub_client_ll_uploadtoblob.c Func:IoTHubClient_LL_UploadToBlob_Impl Line:780 error in IoTHubClient_LL_UploadToBlob_step1
hello world failed to upload
```

Our use case is actually slightly different because our libcurl does not have default paths to search for certificates, resulting in the error instead of the error above:

`Error: Time:Sun Mar 12 14:39:00 2017 File:/home/dsa/packages/BUILD/dsa-libazureiotsdk-dev-2017.02.24/develop/ppc-l06/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:534 curl_easy_perform() failed: Peer certificate cannot be authenticated with given CA certificates`

[iothub_client_sample_upload_to_blob.tar.gz](https://github.com/Azure/azure-iot-sdk-c/files/837855/iothub_client_sample_upload_to_blob.tar.gz)

**Comment by anporumb** [comment]
Hello @czyba ,

We will look at this in March.
 
Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Hello @czyba,

Indeed, certificates are not passed to the FileUpload part of the SDK. Thank you for your report.

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment]
Hello @czyba ,

I have checked in master branch code that I believe would allow you to upload files when certificates are not provided by the OS.

If it is not too much to ask, could you confirm my fixes? Thank you.

Best Regards,
Andrei Porumb

**Comment by czyba** [comment]
Hello @anporumb ,

great, I'll gladly verify it. I can do so on monday at the earliest though. I hope that's ok with you.

Kind regards,
Christopher Czyba

**Comment by czyba** [comment]
Hello @anporumb 

I was able to verify that the changes worked on commit 83b26045f2aad3a3f897e0f07b498dc207ddad8b .

Thanks and Kind Regards,
Christopher Czyba
