### ISSUE TITLE
Download links for tag archives not working properly

### ISSUE THREAD

**Issue by christophtramnitz** [Azure/azure-iot-sdk-c#883]
# Please first tell us a little bit about the environment you're running:
- **OS and version used:** Windows 10 / Ubuntu 16.04
- **SDK version used:** 1.2.9

# Description of the issue:
The links for downloading the *.zip and *.tar.gz archives on the download page for the azure-iot-sdk-c [tags ](https://github.com/Azure/azure-iot-sdk-c/tags) are not working properly.

If you download one of these archives and extract its contents, some of the top level directories are empty. As an example in case of the [1.2.9.tar.gz](https://github.com/Azure/azure-iot-sdk-c/archive/1.2.9.tar.gz) following directories are empty:
- azure-iot-sdk-c-1.2.9/c-utility
- azure-iot-sdk-c-1.2.9/uamqp
- azure-iot-sdk-c-1.2.9/umqtt
- azure-iot-sdk-c-1.2.9/deps/

This is a big problem for us, because we would like to download the SDK with ptxdist via the provided download links.

**Comment by massand** [comment]
@christophtramnitz Compilation isn't possible with just the azure-iot-sdk-c tarball. In order to build the SDK, you need to clone recursively using this command 
`git clone -b <yyyy-mm-dd> --recursive https://github.com/Azure/azure-iot-sdk-c.git` 

The other option to build your application is using the vcpkg or apt-get instructions in our [Devbox setup documentation](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md).

**Comment by christophtramnitz** [comment]
@massand Thanks for your fast response!

I know that it is possible to clone the SDK recursively with git. In fact that is the way I downloaded the SDK so far.

But since we use ptxdist we would like to specifiy a URL to a certain Tag of the SDK wihtin the build system. As a consequence ptxdist would be able to download the corresponding *.tar.gz archive and no manual steps would be needed. Another advantage is that we could update the SDK by simply adjusting the URL.

Don't you think that the archives to download via the described links should have all sources inside? Looks to me like something going wrong.

**Comment by massand** [comment]
@christophtramnitz I understand that you would like to download one set of sources. However, some sources (e.g. parson) belong to non-Azure repos and we cannot pull in sources for their code in our release. We treat our submodule repos the same as parson - they are independent repos (even if they are all within Azure). You still need to download the sources (via tarball) from each submodule repo separately and use the “use_installed_dependencies” cmake flag to build each individually. Currently, our vcpkg package management feature uses this cmake flag to locate dependency packages in an installed location for each package. vcpkg does similar actions to ptxdist, i.e. downloads tarballs for the SDK and submodules and builds them in order and installs them to a central location. Please review the [vcpkg portfiles for azure-iot-sdk-c ](https://github.com/Microsoft/vcpkg/blob/master/ports/azure-iot-sdk-c/portfile.cmake)(and its dependencies) in the vcpkg repo.

**Comment by massand** [comment]
@christophtramnitz I hope you were able to figure out the use_installed_dependencies path to build the SDK and download independent tarballs. If you still have issues with the approach, please reopen the issue and send us the script you attempted to use to build the SDKs. We will be happy to provide additional guidance if needed.

**Comment by az-iot-builder-01** [comment]
@massand, @christophtramnitz, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by christophtramnitz** [comment]
@massand Since the whole project is built with ptxdist, we cannot switch so vcpkg that easily. But we will have a look at your solution. Maybe we can achieve something similar with ptxdist. Thanks for your support!
