### ISSUE TITLE
Sample for Raspberry Pi Fails to Compile

### ISSUE THREAD

**Issue by tessxd** [Azure/azure-iot-sdk-c#885]
- **OS and version used:** <VERSION> 
Raspbian 8 (jessie)
- **SDK version used:** <VERSION> 
Cloned from Repo (

# Description of the issue:

I am trying to use the iot sdk for c on raspberry pi. I'm using the commands here: 

https://azure.microsoft.com/en-us/resources/samples/iot-hub-c-raspberrypi-getstartedkit/

When I reach the following part of the sample, the command fails on /samples/build.sh:
```
cd ~/iot-hub-c-raspberrypi-getstartedkit/
sudo ~/iot-hub-c-raspberrypi-getstartedkit/azure-iot-sdks/c/build_all/linux/setup.sh
chmod +x ~/iot-hub-c-raspberrypi-getstartedkit/samples/build.sh
~/iot-hub-c-raspberrypi-getstartedkit/samples/build.sh
```

When running build.sh though, the script fails with multiple errors, so I'm blocked at that point.

**Comment by ewertons** [comment]
Hi @tessxd ,

could you paste the entire output showing the failures you are getting, please?

**Comment by bikamani** [comment]
Hi @tessxd , 

Please refer to the links below for set up of raspberry pi with azure iot sdk:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-raspberry-pi-kit-c-get-started
https://github.com/Azure-Samples/iot-hub-c-raspberrypi-docker

There is not enough information in the issue for us to debug further. Please let us know more details if the issue still exists. 

Thanks.

**Comment by az-iot-builder-01** [comment]
@tessxd, @ewertons, @bikamani, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
