### ISSUE TITLE
Managing of X.509 certificate and of private key

### ISSUE THREAD

**Issue by ma2teo** [Azure/azure-iot-sdk-c#887]
- **OS and version used:** FreeRTOS

- **SDK version used:** 1.2.13

# Description of the issue:
Dear All,

I’m writing this issue about some difficulties in the managing of X.509 certificate and of private key in my IoT device.

I use the 1.2.13 release version of C Device SDK in my embedded platform and I choose the MQTT protocol for the communication between my IoT device and IoT Hub. The MQTT is made secure through the TLS layer implemented by the mbedTLS library.

In the first part of my test I use a Sas authentication device and all works fine. I set only one client option, _OPTION_TRUSTED_CERT_, in way to guarantee a successfully one way TLS authentication.

In the second part of my test I use a self signed authentication device. So I set three client options:  _OPTION_TRUSTED_CERT_, _SU_OPTION_X509_CERT_ and _SU_OPTION_X509_PRIVATE_KEY_. However my device, during the TLS handshake, provides a null certificate, then the IoT Hub can’t authenticate my device.
The client options are configured successfully through the _IoTHubClient_LL_SetOption_ function. 
In order to run my MQTT client I invoke the _IoTHubClient_LL_DoWork_ function.
Before the establishment of the MQTT connection between my IoT device and IoT Hub I notice that the client options are resetted inside the _ResetConnectionIfNecessary_ function. Theoretically all the existing client options are first retrieved and then saved before the cancellation through the _xio_retrieveoptions_ and _set_saved_tls_options_ functions respectively. However the _xio_retrieveoptions_->_tlsio_mbedtls_retrieveoptions_ function don’t retrieved the _SU_OPTION_X509_CERT_ and _SU_OPTION_X509_PRIVATE_KEY_ client options, so they aren’t saved.
Before the MQTT connection, the client options previously saved are restored through the _GetTransportProviderIfNecessary_->_OptionHandler_FeedOptions_ function. Unfortunately the _SU_OPTION_X509_CERT_ and _SU_OPTION_X509_PRIVATE_KEY_ client options isn’t saved and so they can’t be restored.
For this reason during the TLS handshake my IoT device provides a null certificate and this invalidates the authentication procedure in IoT Hub.

At this point I would ask how can I fix this problem? Should I implement custom code inside the _tlsio_mbedtls_retrieveoptions_ function in order to retrieve the _SU_OPTION_X509_CERT_ and _SU_OPTION_X509_PRIVATE_KEY_ client options? Or is there some other function already ready?.

Thanks in advance.
Regards.
Matteo

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by Sahityatarumani** [comment]
@ma2teo can you please post some sample code? How do you set the value of OPTION_TRUSTED_CERT?

**Comment by massand** [comment]
@ma2teo - thanks for reporting the issue. 

> the xio_retrieveoptions->tlsio_mbedtls_retrieveoptions function don’t retrieved the SU_OPTION_X509_CERT and SU_OPTION_X509_PRIVATE_KEY client options, so they aren’t saved.

It appears there was a fix specifically targeting the tlsio_mbedtls option handler logic, few days ago. Could you double check that this commit has fixed the issue by update to the latest master branch of c-utility (within all submodule folders including azure-iot-sdk-c/,  umqtt/deps and uamqp/deps) and building the SDK again?

Here is the commit - 
https://github.com/Azure/azure-c-shared-utility/commit/244cfa4c2eed5bdb979ac7b76af02eafece9de29

**Comment by massand** [comment]
@ma2teo - It appears this PR fixed it: https://github.com/Azure/azure-c-shared-utility/pull/301
Thank you for reporting this issue, which drove @jebrando to this fix in April!

**Comment by az-iot-builder-01** [comment]
@ma2teo, @Sahityatarumani, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
