### ISSUE TITLE
What is needed to reconnect?

### ISSUE THREAD

**Issue by ukluk** [Azure/azure-iot-sdk-c#893]
Hello SDK developers,
I am not completely sure how to recover from a network or IoTHub disconnection.

Could you share guidelines about best practices?

Here is what I have, and it is not optimal:
When the network or the IoT Hub disconnects, the callback fires up showing a change of state, example:
`IoTHub Connection Status = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, Reason = IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN`
And my only way to recover is to teardown the TCP socket, the MQTT connection, the serializer and the platform, and only then restart.

Q1:
After a disconnect occurs, if I keep **looping** calling DoWork, does the code try to reconnect? because I am not seeing it.
Q2: If SDK reconnects on its own, can you outline the properties and retry policy to make this happen? Since the changes from 1.2.13+ the property descriptions are not clearly documented.
```
while(running) {
		IoTHubDeviceClient_LL_DoWork(iotHubClientHandle);
		osDelay(10);
}
```

If the best practice could also explain each reason for disconnection and what is expected.

For example: If the connection callback returns: IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Does that mean that a client_destroy is needed?
From the following results, do we need to provide handlers, or the SDK recovers each case?

```
     IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN,            \
     IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED,              \
     IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL,               \
     IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED,                \
     IOTHUB_CLIENT_CONNECTION_NO_NETWORK,                   \
     IOTHUB_CLIENT_CONNECTION_COMMUNICATION_ERROR,          \
     IOTHUB_CLIENT_CONNECTION_OK                            \

    IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY,      \
    IOTHUB_CLIENT_CONFIRMATION_MESSAGE_TIMEOUT,      \
    IOTHUB_CLIENT_CONFIRMATION_ERROR                 \
```

**Comment by ewertons** [comment]
Hi @ukluk ,
here is some documentation to help you get a better picture of how reconnection works on the Azure IoT C SDK:
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/connection_and_messaging_reliability.md

If you provided a device connection string to the SDK and it is generating the SAS token automatically, the device client will reconnect automatically whenever network is available (considering you have not modified the default retry policy [see the link above]).

So if it is not reconnecting, you should provide all the details relevant to your platform, sdk version, etc so we can investigate. Note that we do have test coverage for reconnections, so they are tested.

For the meaning of the reasons returned by connection status callback, please check it out in the link above (look for "Connection Status Callback").
"IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY" means you got this status connection callback because the user (ie., you), have invoked IoTHubDeviceClient_LL_Destroy().

Also, make sure you follow the recommendation and invoke IoTHubDeviceClient_LL_DoWork at least every 100 (one hundred) milliseconds.

**Comment by ukluk** [comment]
Thank you @ewertons ! a lot of insight in your response and links

I have a **special case** because I am using the **Modem internal IP stack**. When xio calls the concrete raw sockets, the code uses AT commands to Connect, Read, Write and Destroy. 
I suspect that the recovery is not able to manage correctly the socket framing, but I never see a socket DISCONNECT or CONNECT call during recovery.

In my case, it is **not** recovering from a Network problem.

In cellular networks, it is expected to lose coverage, but more important, it is a requirement to disconnect from the carrier once a day.

> I suggest a fail fast or cancellation parameter to abort the retry policy.

I suggest something like this:
`IoTHubDeviceClient_LL_DoWork(bool abort);`

This development is based on a STM32 and it runs the SDK using FreeRTOS, mbedTLS and the IP stack is internal to the modem.

I want to show some traces to demonstrate that recovery, for SAS, did not work correctly leaving the code broken. My workaround is to add another state machine on top the `DoWork()` loop, but then state machine race each other.



```
IoTHub Connection Status = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, Reason = IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN
{"v":"33","c":111,"rt":5201,"csq":25,"bt":4.19,"bl":100,"iv":11.83,"tc":25.8,"rh":9.0,"mr":0,"ic":0,"mid":193,"ssc":2905,"heap":61904,"dv":94,"x":-0.013,"y":-0.158,"z":0.963,"dv":9.4,"ae":"1"}
Sending Message:193
{"utc":"120209.000","location":{"lon":-87.718994,"lat":42.001625},"hdop":500.0,"alt":178.2,"fix":2,"cog":288.000,"spkm":2.7,"date":"070319","nsat":2}
Sending Message:194
ERROR: InitializeConnection L#2351
mqtt_client timed out waiting for CONNACK
IoTHub Connection Status = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, Reason = IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED
{"v":"33","c":111,"rt":5261,"csq":25,"bt":4.19,"bl":100,"iv":11.86,"tc":25.8,"rh":8.9,"mr":0,"ic":0,"mid":195,"ssc":2965,"heap":61904,"dv":94,"x":-0.011,"y":-0.159,"z":0.967,"dv":9.4,"ae":"1"}
Sending Message:195
{"utc":"120309.000","location":{"lon":-87.718826,"lat":42.001850},"hdop":500.0,"alt":178.0,"fix":2,"cog":0.000,"spkm":0.0,"date":"070319","nsat":2}
Sending Message:196
{"v":"33","c":111,"rt":5321,"csq":26,"bt":4.19,"bl":100,"iv":11.86,"tc":25.8,"rh":8.9,"mr":0,"ic":0,"mid":197,"ssc":3025,"heap":61904,"dv":94,"x":-0.011,"y":-0.159,"z":0.966,"dv":9.4,"ae":"1"}
Sending Message:197
{"utc":"120409.000","location":{"lon":-87.718369,"lat":42.002121},"hdop":500.0,"alt":180.3,"fix":2,"cog":212.005,"spkm":2.6,"date":"070319","nsat":2}
Sending Message:198
{"v":"33","c":111,"rt":5381,"csq":27,"bt":4.19,"bl":100,"iv":11.86,"tc":25.8,"rh":8.8,"mr":0,"ic":0,"mid":199,"ssc":3085,"heap":61904,"dv":95,"x":-0.013,"y":-0.160,"z":0.965,"dv":9.5,"ae":"1"}
[{"st_Mesh00001F":"5"},{"st_Mesh000020":"5"}]
Sending Message:199
Sending Message:200
```

I am not getting `SendConfirmationCallback `confirmation anymore.

**Comment by ewertons** [comment]
Hi @ukluk ,
I suppose you are using the SDK on top of a linux-based system, is that correct?
Down on our code we make calls to the regular socket API functions. If in your system these functions are not behaving the way they are expected, socketio_berkeley.c will not be prepared to handle that (by default).

However, I think your system is behaving as expected (thanks for the logs btw!).
See that IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED in your log?
It means the transport has detected some failure, has tried to reconnect. However, **if you reach IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED, the transport will not longer attempt to reconnect**.
Either you need to:
. Change the retry policy not to expire (pass 0 on last arg of *_SetRetryPolicy(...), or
. when you get IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED, destroy the client and recreate it, which will guarantee that you have a fresh connection (the expiration of the retry policy, in conjunction with the connection status callback was a feature requested by customers exactly because they wanted to handle reconnection themselves on their application layer).

**Comment by qiying** [comment]
> Hi @ukluk ,
> I suppose you are using the SDK on top of a linux-based system, is that correct?
> Down on our code we make calls to the regular socket API functions. If in your system these functions are not behaving the way they are expected, socketio_berkeley.c will not be prepared to handle that (by default).
> 
> However, I think your system is behaving as expected (thanks for the logs btw!).
> See that IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED in your log?
> It means the transport has detected some failure, has tried to reconnect. However, **if you reach IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED, the transport will not longer attempt to reconnect**.
> Either you need to:
> . Change the retry policy not to expire (pass 0 on last arg of *_SetRetryPolicy(...), or
> . when you get IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED, destroy the client and recreate it, which will guarantee that you have a fresh connection (the expiration of the retry policy, in conjunction with the connection status callback was a feature requested by customers exactly because they wanted to handle reconnection themselves on their application layer).

Hi, when user get IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED, is there any way (maybe let user call some API) not destroy-recreate client, but reconnect the client again?
If there is no way to do that, do you plan to add this feature in the future?

**Comment by ukluk** [comment]
@ewertons ,

We are developing a constrained device without Linux or Windows.
It is FreeRTOs and the mbed TLS stack.

After your comments, I review the code that handles the socket and it was not signaling the network error:
In this file:
https://github.com/Azure/azure-c-shared-utility/blob/0756cea3675a453222e4880c475eb91fd9d5a950/adapters/socketio_mbed.c

I changed:
```
received = tcpsocketconnection_receive(socket_io_instance->tcp_socket_connection, (char*)recv_bytes, MBED_RECEIVE_BYTES_VALUE);
if (received > 0)
{
    if (socket_io_instance->on_bytes_received != NULL)
    {
        /* explictly ignoring here the result of the callback */
         (void)socket_io_instance->on_bytes_received(socket_io_instance->on_bytes_received_context, 
        recv_bytes, received);
     }
}
```
to
```
received = tcpsocketconnection_receive(socket_io_instance->tcp_socket_connection, (char*)recv_bytes, MBED_RECEIVE_BYTES_VALUE);
if (received > 0)
{
    if (socket_io_instance->on_bytes_received != NULL)
    {
        /* explictly ignoring here the result of the callback */
        (void)socket_io_instance->on_bytes_received(socket_io_instance->on_bytes_received_context, 
        recv_bytes, received);
    }
}
else if (received < 0)
{
    socket_io_instance->io_state = IO_STATE_ERROR;
    indicate_error(socket_io_instance);
}

```

And now it appears to be aware of the Network status, yet I am seeing the following traces and it never recovers. 

## Do I need to teardown after **IOTHUB_CLIENT_CONFIRMATION_ERROR** or the retry policy should have taken care?

ERROR: SendConfirmationCallback L#708 D2C ...IOTHUB_CLIENT_CONFIRMATION_ERROR
ERROR: sendPacketItem L#371
717: Failure sending control packet data
ERROR: mqtt_client_publish L#1059
Error: mqtt_client_publish send failed
ERROR: publish_mqtt_telemetry_msg L#865
Failed attempting to publish mqtt message
ERROR: SendConfirmationCallback L#708 D2C ...IOTHUB_CLIENT_CONFIRMATION_ERROR
ERROR: sendPacketItem L#371
717: Failure sending control packet data
ERROR: mqtt_client_publish L#1059
Error: mqtt_client_publish send failed
ERROR: publish_mqtt_telemetry_msg L#865
Failed attempting to publish mqtt message
ERROR: SendConfirmationCallback L#708 D2C ...IOTHUB_CLIENT_CONFIRMATION_ERROR
ERROR: sendPacketItem L#371
717: Failure sending control packet data
ERROR: mqtt_client_publish L#1059
Error: mqtt_client_publish send failed
ERROR: publish_mqtt_telemetry_msg L#865
Failed attempting to publish mqtt message
ERROR: SendConfirmationCallback L#708 D2C ...IOTHUB_CLIENT_CONFIRMATION_ERROR

**Comment by ewertons** [comment]
@ukluk ,
your change makes sense, as it is clear that we are not handling failure well in the mbedTLS wrapper.

we will need to investigate further why the reconnection is not succeeding.
Technically you do not need to destroy the iothub_client and recreate it for reconnection to succeed.
However, since it is clear that is some gap in this wrapper, would you be able to run a little experiment and whenever you start getting the failures, could you stop the application, destroy and recreate the iothub_client? 
That will give us additional insight about how your network is behaving, if you have connection available while the Azure IoT SDK is trying to reconnect.

**Comment by ukluk** [comment]
@ewertons 
As per your request, capture logs with failure, destroy and recreate.
Let me know what else can I do to help clarify the recovery on constrained devices

First, the SAS token expires, it tries to reconnect but after a few attempts, my code destroys the client and recreates. I was expecting that `IoTHubClientCore_LL_DoWork` will reconnect, but it never happened

IoTHub Connection Status = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, Reason = IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN
socketConnect(0,40.114.53.146,8883,0)
socketClose(0)
ERROR: InitializeConnection L#2351
mqtt_client timed out waiting for CONNACK
IoTHub Connection Status = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, Reason = IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED
ERROR: IoTHubClientCore_LL_DoWork L#2035
Request to reconnect
ERROR: IoTHubClientCore_LL_DoWork L#2035
Request to reconnect
ERROR: IoTHubClientCore_LL_DoWork L#2035
Request to reconnect
ERROR: IoTHubClientCore_LL_DoWork L#2035
Request to reconnect
ERROR: IoTHubClientCore_LL_DoWork L#2035
Request to reconnect
ERROR: IoTHubClientCore_LL_DoWork L#2035
Request to reconnect
ERROR: IoTHubClientCore_LL_DoWork L#2035
Request to reconnect
ERROR: IoTHubClientCore_LL_DoWork L#2035
Request to reconnect
ERROR: IoTHubClientCore_LL_DoWork L#2035
Request to reconnect

iothubapp_close
ERROR: SendConfirmationCallback L#717 D2C ...IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY

IoTHub Client API Version: 1.2.14
socketConnect(0,40.114.53.146,8883,0)
IoTHub Connection Status = IOTHUB_CLIENT_CONNECTION_AUTHENTICATED, Reason = IOTHUB_CLIENT_CONNECTION_OK

**Comment by ranjit1314** [comment]
Hi ukluk , 
We are developing a constrained device without Linux or Windows.
It is FreeRTOs and the mbed TLS stack.
I am facing the same issue for reconnection. 
If you find any solution , can you please help me out.

Thanks & regards
Ranjit

**Comment by ukluk** [comment]
Ranjit,

This helped:

  1.  Ensure your retry policy in IoTHub can complete
  2.  Compare these highlighted snippet in  az_socketio_mbed.c, it was not signaling the socket when there was a network error receiving bytes

void socketio_dowork(CONCRETE_IO_HANDLE socket_io)
{
    if (socket_io != NULL)
    {
        SOCKET_IO_INSTANCE* socket_io_instance = (SOCKET_IO_INSTANCE*)socket_io;
        if (socket_io_instance->io_state == IO_STATE_OPEN)
        {
            int received = 1;

            LIST_ITEM_HANDLE first_pending_io = singlylinkedlist_get_head_item(socket_io_instance->pending_io_list);
            while (first_pending_io != NULL)
            {
                PENDING_SOCKET_IO* pending_socket_io = (PENDING_SOCKET_IO*)singlylinkedlist_item_get_value(first_pending_io);
                if (pending_socket_io == NULL)
                {
                    socket_io_instance->io_state = IO_STATE_ERROR;
                    indicate_error(socket_io_instance);
                    break;
                }

                int send_result = tcpsocketconnection_send(socket_io_instance->tcp_socket_connection, (const char*)pending_socket_io->bytes, pending_socket_io->size);
                if (send_result != pending_socket_io->size)
                {
                    if (send_result < 0)
                    {
                        if (send_result < UNABLE_TO_COMPLETE)
                        {
                            // Bad error.  Indicate as much.
                            socket_io_instance->io_state = IO_STATE_ERROR;
                            indicate_error(socket_io_instance);
                        }
                        break;
                    }
                    else
                    {
                        /* send something, wait for the rest */
                        (void)memmove(pending_socket_io->bytes, pending_socket_io->bytes + send_result, pending_socket_io->size - send_result);
                    }
                }
                else
                {
                    if (pending_socket_io->on_send_complete != NULL)
                    {
                        pending_socket_io->on_send_complete(pending_socket_io->callback_context, IO_SEND_OK);
                    }

                   free(pending_socket_io->bytes);
                    free(pending_socket_io);
                    if (singlylinkedlist_remove(socket_io_instance->pending_io_list, first_pending_io) != 0)
                    {
                        socket_io_instance->io_state = IO_STATE_ERROR;
                        indicate_error(socket_io_instance);
                    }
                }

                first_pending_io = singlylinkedlist_get_head_item(socket_io_instance->pending_io_list);
            }

            while (received > 0)
            {
                unsigned char* recv_bytes = malloc(MBED_RECEIVE_BYTES_VALUE);
                if (recv_bytes == NULL)
                {
                    LogError("Socketio_Failure: NULL allocating input buffer.");
                    indicate_error(socket_io_instance);
                }
                else
                {
                    received = tcpsocketconnection_receive(socket_io_instance->tcp_socket_connection, (char*)recv_bytes, MBED_RECEIVE_BYTES_VALUE);
                    if (received > 0)
                    {
                        if (socket_io_instance->on_bytes_received != NULL)
                        {
                            /* Explicitly ignoring here the result of the callback */
                            (void)socket_io_instance->on_bytes_received(socket_io_instance->on_bytes_received_context, recv_bytes, received);
                        }
                    }
                    else if (received < 0)
                    {
                        socket_io_instance->io_state = IO_STATE_ERROR;
                        indicate_error(socket_io_instance);
                    }
                    free(recv_bytes);
                }
            }
        }
    }
}

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ewertons** [comment]
Hi @ukluk , given you found a way to resolve the reconnection, can this issue be closed or do you still have any point you would like to follow up on?

Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment]
@ewertons, @ukluk, @qiying, @ranjit1314, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
