### ISSUE TITLE
Provision group enrollments

### ISSUE THREAD

**Issue by alexanderbikk** [Azure/azure-iot-sdk-c#897]
- **OS and version used:** <Windows 10> 

- **SDK version used:** <1.2.14> 

# Description of the issue:

I followed this guide to provision individual enrollment using X509 certificate https://docs.microsoft.com/en-us/azure/iot-dps/tutorial-set-up-device and enverything works fine for me. But when I tried to simulate group enrollment using this instruction and generated group certificate I faced with issue.

I do the following steps:
- do same steps as in  individual enrollment
- follow this guide https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_group_enrollment_dice.md to generate the group enrollment certificate, create new group enrollment and verify the certificate through the portal
- start the prov_dev_client_sample(same configuration as for individual enrollment in article). And here I faced with MQTT communication error(the generated certificate already verified and assigned to enrolment group).

# Console log of the issue:
The issue occurs when I try to run the prov_dev_client_sample 

Provisioning API Version: 1.2.14

Registering Device

Provisioning Status: PROV_DEVICE_REG_STATUS_CONNECTED
Error: Time:Thu Mar  7 18:04:07 2019 File:..\azure-iot-sdk-c\provisioning_client\src\prov_transport_mqtt_common.c Func:_mqtt_error_callback Line:136 MQTT communication error
Error: Time:Thu Mar  7 18:04:07 2019 File:..\azure-iot-sdk-c\provisioning_client\src\prov_device_ll_client.c Func:_on_transport_registration_data Line:572 Failure retrieving data from the provisioning service

Failure registering device: PROV_DEVICE_RESULT_TRANSPORT

What I'm doing wrong?

Thanks in advance

**Comment by jebrando** [comment]
@alexanderbikk Can you enable logging by commenting the following code

```c
bool traceOn = true;
...
Prov_Device_LL_SetOption(handle, PROV_OPTION_LOG_TRACE, &traceOn);
```
It will give us some more information as to what's happening.

**Comment by alexanderbikk** [comment]
@jebrando ok I will do it as soon as possible. Sorry but it was 18 days ago and I can not switch to this task immediately.

**Comment by chinnaece** [comment]
@alexanderbikk  In my case i got this error when problem with certificates like certificate parsing , openssl version.

**Comment by jebrando** [comment]
@alexanderbikk If this is still an issue with you, please reopen the issue.

Thanks

**Comment by az-iot-builder-01** [comment]
@jebrando, @alexanderbikk, @chinnaece, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by scout208** [comment]
I just ran into the same issue.
