### ISSUE TITLE
Send reported properties 

### ISSUE THREAD

**Issue by rextremotabaresDtt** [Azure/azure-iot-sdk-c#898]
I'm struggling with the IOT Central iOS SDK to send reported properties to my IOT Central but so far I haven't found any way to do it.

I have no problem sending properties or events / telemetries but I've been struggling with this for a while with no results. Can you enlighten my way? SDK's documentation is pretty scarce at leas in IOS.

**Comment by ewertons** [comment]
Hi @rextremotabaresDtt ,

Could you provide some more info please?
1. What documentation are you following?
2. Are you looking to use a SDK in c language?

**Comment by ewertons** [comment]
@rextremotabaresDtt ,
we will close this issue for now, but please feel free to reopen it if you would like to follow up.
Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment]
@rextremotabaresDtt, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
