### ISSUE TITLE
Test server with invalid TLS certificate

### ISSUE THREAD

**Issue by VolkerKamin** [Azure/azure-iot-sdk-c#90]
I would like to test my Azure client against an IoT Hub server whose TLS certificates have been revoked / are outdated to validate that invalid TLS server certificates are correctly handled by my implementation and the C SDK.

Are there any public IoT Hub test servers that I could run such a test against?

**Comment by ewertons** [comment]
Hey @rajeevmv , do you know if there is a way to achieve that?

**Comment by rajeevmv** [comment]
I am not aware of any such IoT Hub test servers.
Perhaps you can try something like [this](https://security.stackexchange.com/questions/60804/creating-an-x-509-certificate-with-an-invalid-signature). 
i.e., you could corrupt the Microsoft server certificate on the client and try to connect to a real IoTHub. The certificates should not match and hence the TLS connection should fail.

**Comment by ewertons** [comment]
Hi @VolkerKamin , I would follow @rajeevmv 's recommendation.
Would that suffice for your testing?
Please let us know if you need any more information.

**Comment by VolkerKamin** [comment]
Hi everyone,

Sorry for answering so late; it's been a busy week.

Unfortunately, the suggestion by @rajeevmv would not target the right issue. I have tests for invalid certificates of all sorts (broken chain, untrusted root CA, invalid server certificate). However, certificate revocation is much more tricky! You need a valid certificate and a CRL server and a CRL list with the corresponding entry.

I have found a site that offers something similar:
https://www.grc.com/revocation.htm

This is, however, only for HTTPS. AFAIK both HTTPS and Azure will first secure the TCP/IP connection using TLS which includes the certificate checking. Hence, I will configure my firewall to redirect Azure traffic to that site.
This is quite some manipulation and, hence, an artificial situation. Since Azure puts a lot of focus on thorough security, I would have guessed that there is a public test server, that allows developers to ensure all security mechanisms are working properly.

Do you know who I could contact to petition for just a test server?

For Microsoft it would be easy to setup a few URLs

- wronghostname.azure-devices.net
- invalidservercertificate.azure-devices.net
- brokencertificatechain.azure-devices.net
- wrongca.azure-devices.net
- revokedservercertificate.azure-devices.net
- revocedintermediatecertificate.azure-devices.net

There are so many applications that lack proper certificate handling. Providing easy testing environments helps to build a secure eco system.

**Comment by olivierbloch** [comment]
This is now tracked in [User Voice](https://feedback.azure.com/forums/321918-azure-iot/suggestions/19109110-add-samples-or-support-for-tls-cert-test-servers). Please vote it up there.
Thanks
