### ISSUE TITLE
Device Streams - API Review Feedback: stream_c2d_* -> prefix these with "IoTHubClient_" and replace underscore-seperate with capital-seperated

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-c#900]
Tracking issue for DeviceStreams API review feedback

# Description of the issue:

stream_c2d_* -> prefix these with "IoTHubClient_" and replace underscore-separate with capital-separated

**Comment by ewertons** [comment]
Fixed.

**Comment by az-iot-builder-01** [comment]
@wickste, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
