### ISSUE TITLE
Device Streams - API Review Feedback: stream_c2d_response_create -> DEVICE_STREAM_C2D_REQUEST should be const

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-c#901]
Tracking issue for DeviceStreams API review feedback

# Description of the issue:

stream_c2d_response_create -> DEVICE_STREAM_C2D_REQUEST should be const

**Comment by ewertons** [comment]
Fixed.

**Comment by az-iot-builder-01** [comment]
@wickste, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
