### ISSUE TITLE
Prepare Your Development Environment

### ISSUE THREAD

**Issue by hhmahmoud** [Azure/azure-iot-sdk-c#904]
- **OS and version used:** <Windows 10> 

- **SDK version used:** <NA> 

# Description of the issue:

I am following the URL: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md to prepare my development environment.  I reached to the step where it says " Clone the latest release of SDK to your local machine using the tag name you found:"  When I ran the following on VS 2017 via "Package Manager Console":
git clone -b <2019-01-31> --recursive https://github.com/Azure/azure-iot-sdk-c.git

_I get the following error:_

# Code sample exhibiting the issue:

At line:1 char:14
  "+" git clone -b <2019-01-31> --recursive https://github.com/Azure/azure- ...
  "+"            ~
The '<' operator is reserved for future use.

# Console log of the issue:

**Comment by YoDaMa** [comment]
Remove the `<` and it should work. So the command would be: 

```
git clone -b 2019-01-31 --recursive https://github.com/Azure/azure-iot-sdk-c.git
```

**Comment by az-iot-builder-01** [comment]
@hhmahmoud, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by hhmahmoud** [comment]
Thanks a lot Mr. YoDaMa.  It worked!
