### ISSUE TITLE
rsync during Raspberry Pi Cross Compile Hangs

### ISSUE THREAD

**Issue by YoDaMa** [Azure/azure-iot-sdk-c#905]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Raspberry Pi, Raspbian Stretch Lite (Release 2018-11-13)
Cross Compiled on Ubuntu 18.04 VM

**SDK Version (Please Give Commit SHA if Manually Compiling**

Manually Compiling Latest

**Describe the Bug**

I am using the following doc: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md

On the cross compiling instructions, the step to copy files from the raspberry pi seems to hang up. 

```
rsync -rl --safe-links pi@111.111.1.1:/{lib,usr} .
```

After a few minutes of waiting, nothing seems to be happening so I will `CTRL-C`, at which point the following error is printed:

```
^Crsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(644) [generator=3.1.2]rsync error: received SIGUSR1 (code 19) at main.c(1447) [receiver=3.1.2]

rsync: [generator] write error: Broken pipe (32)
```

This is probably from ending the rsync command... but I'm not sure. Regardless, this step is blocking me from cross-compiling on the Raspberry Pi.

**Comment by YoDaMa** [comment]
note I am able to ssh into the raspberry pi from my machine, so it's not a connection issue. I'm not sure what the rsync command does to begin with...

**Comment by YoDaMa** [comment]
Closing because of merge

**Comment by az-iot-builder-01** [comment]
@YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
