### ISSUE TITLE
Getting Openssl error while device provisioning using hsm_client_riot.c 

### ISSUE THREAD

**Issue by chinnaece** [Azure/azure-iot-sdk-c#913]
As i placed my own certificate , private key , common name in the hsm_client _riot.c  getting below error.  please help me . #662 shows similar problem , even i updated new openssl getting same error.

Error: Time:Wed Mar 20 11:58:11 2019 File:/home/test/Desktop/proj_arm/just_iot-sdk/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:29 Failure creating private key evp_key
Error: Time:Wed Mar 20 11:58:11 2019 File:/home/test/Desktop/proj_arm/just_iot-sdk/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36   [0] error:0906D06C:PEM routines:PEM_read_bio:no start line
Error: Time:Wed Mar 20 11:58:11 2019 File:/home/test/Desktop/proj_arm/just_iot-sdk/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36   [1] error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
Error: Time:Wed Mar 20 11:58:11 2019 File:/home/test/Desktop/proj_arm/just_iot-sdk/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36   [2] error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error
Error: Time:Wed Mar 20 11:58:11 2019 File:/home/test/Desktop/proj_arm/just_iot-sdk/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36   [3] error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error
Error: Time:Wed Mar 20 11:58:11 2019 File:/home/test/Desktop/proj_arm/just_iot-sdk/c-utility/adapters/x509_openssl.c Func:log_ERR_get_error Line:36   [4] error:0907B00D:PEM routines:PEM_READ_BIO_PRIVATEKEY:ASN1 lib
Error: Time:Wed Mar 20 11:58:11 2019 File:/home/test/Desktop/proj_arm/just_iot-sdk/c-utility/adapters/tlsio_openssl.c Func:log_ERR_get_error Line:428 unable to use x509 authentication
Error: Time:Wed Mar 20 11:58:11 2019 File:/home/test/Desktop/proj_arm/just_iot-sdk/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1251 Failed creating the OpenSSL instance.

**Comment by ewertons** [comment]
Hi @chinnaece ,

these failures come straight from the openssl layer.
This could be because of the certificate you are using.

Could you follow the comments on this question below, and see if they address your issue?
https://stackoverflow.com/questions/20837161/openssl-pem-routinespem-read-biono-start-linepem-lib-c703expecting-truste

**Comment by chinnaece** [comment]
@ewertons Thanks for your response , i  saw #662 , my error is similar one. Hope your  suggestion will solve my problem.

**Comment by chinnaece** [comment]
@ewertons  it didn't helps me . Thank you

**Comment by chinnaece** [comment]
It's a issue with versions of openssl and x.509 client in azure-sdk-c , So i  genrated certificates in  linux machine with existing Opennssl made it successful earlier i generated certificates on windows.

**Comment by az-iot-builder-01** [comment]
@ewertons, @chinnaece, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
