### ISSUE TITLE
Build error in "iothub_client_ll_uploadtoblob.c" (probably a typo)

### ISSUE THREAD

**Issue by eLEcTRiCZiTy** [Azure/azure-iot-sdk-c#92]
Build error when comparing two enumerators in the current version.

error: comparison between 'HTTPAPIEX_RESULT {aka enum HTTPAPIEX_RESULT_TAG}' and 'enum IOTHUB_CLIENT_RESULT_TAG'

([iothub_client/src/iothub_client_ll_uploadtoblob.c#L754](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothub_client_ll_uploadtoblob.c#L754))

**Comment by ewertons** [comment]
Hi @eLEcTRiCZiTy , thanks for reporting this issue.
A fix will be provided briefly.

**Comment by ewertons** [comment]
Hi @eLEcTRiCZiTy , the issue has been fixed.
Please verify, and let us know if the ticket can be closed.

Thanks for using the Azure IoT Hub Client SDK.

**Comment by eLEcTRiCZiTy** [comment]
Hi @ewertons , the typo has been fixed and build is OK, thanks. :)
