### ISSUE TITLE
issues compiling iot sdk shared libraries on arm64

### ISSUE THREAD

**Issue by arunmohre** [Azure/azure-iot-sdk-c#921]
I was trying to compile the azure iot c sdk on jetson platform(aarch64) and particularly trying to build a shared library.

The build option "-Dbuild_as_dynamic:BOOL=ON" certainly works fine when I compile it on x86. But I see failures while building on jetson.   cmake for sure is unable to detect the arm64 architecture. Any idea if I am missing something?

(NOTE: I am successfully able to build static libs. which can also be fetched via ubuntu apt-get packages)

Please find the detailed log files attached (build.make and the cmake error)
[cmake-err.txt](https://github.com/Azure/azure-iot-sdk-c/files/2998043/cmake-err.txt)
[build.make.txt](https://github.com/Azure/azure-iot-sdk-c/files/2998055/build.make.txt)

-- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "1.1.0g")
-- target architecture: GENERIC
-- iothub architecture: GENERIC

[ 82%] Linking C shared library libiothub_client.so
CMake Error: cmake version 3.10.2

iothub_client/CMakeFiles/iothub_client_dll.dir/build.make:571: recipe for target 'iothub_client/libiothub_client.so.1.2.13' failed
make[2]: *** [iothub_client/libiothub_client.so.1.2.13] Error 1
CMakeFiles/Makefile2:1278: recipe for target 'iothub_client/CMakeFiles/iothub_client_dll.dir/all' failed
make[1]: *** [iothub_client/CMakeFiles/iothub_client_dll.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ewertons** [comment]
Hi @arunmohre ,
we believe that is an issue with that version of cmake, which one of our engineers has encountered before.
While we verify that on our side, would it be possible to try to upgrade cmake to 3.11 or higher and try again please?

Thanks,
Azure IoT SDK Team

**Comment by arunmohre** [comment]
Yes using cmake 3.14 - the issue not seen

Thank you very much @ewertons !

**Comment by az-iot-builder-01** [comment]
@ewertons, @arunmohre, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
