### ISSUE TITLE
Install particular version of c sdk using ubuntu azureppa

### ISSUE THREAD

**Issue by arunmohre** [Azure/azure-iot-sdk-c#922]
I am trying to install particular version of azure iot c sdk prebuilt libs directly from ubuntu ppa-azureiot - but seeing error

 

sudo apt-get install -y azure-iot-sdk-c-dev=0.2.0.0-8xenial

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '0.2.0.0-8xenial' for 'azure-iot-sdk-c-dev' was not found

The package seems to be available though, although it says superseded - https://launchpad.net/~aziotsdklinux/+archive/ubuntu/ppa-azureiot/+packages?field.name_filter=sdk&field.status_filter=&field.series_filter=xenial

Anything I am missing here? Or is there an other way of fetching this particular version of the sdk ?

**Comment by ewertons** [comment]
Hi @arunmohre ,
launchpad deprecates packages frequently after new versions get released, superseding previous ones.
Here are the details for this package:
https://launchpad.net/~aziotsdklinux/+archive/ubuntu/ppa-azureiot/+sourcepub/9228887/+listing-archive-extra

If you would like to use that version of the code, you can clone that release and build it locally:
https://github.com/Azure/azure-iot-sdk-c/tree/2018-07-03

**Comment by ewertons** [comment]
One question: would it be possible for you to use the latest version of the SDK instead? Could you share reason to use the old one?
Thanks,
Azure IoT SDK team

**Comment by arunmohre** [comment]
@ewertons : The azure iot api's used in our message broker library are the ones from c sdk v1.2.8
The reason for not using the latest library is due to the point that api's might be different. We would like to stick to one version and note our users to download azure libs on their system from that particular version.

**Comment by ewertons** [comment]
@arunmohre ,
if the major version of the SDK doesn't change, there should be no breaking changes to the API for you.
But anyways, in this case looks like launchpad.net has the policy of deprecating older packages. If you would like to use an older version, you will need to download the code and compile it for your platform.

**Comment by arunmohre** [comment]
Alright thank you. Will document to notify users download particular version of sdk and build the libs.

**Comment by az-iot-builder-01** [comment]
@ewertons, @arunmohre, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
