### ISSUE TITLE
Version 1.2.14 Memory Leak when client handle is released while MQTT trying to reconnect

### ISSUE THREAD

**Issue by maskimthedog** [Azure/azure-iot-sdk-c#924]
**Development Machine, OS, Compiler**

STM32F405, FreeRTOS, GCC

**SDK Version**

1.2.14

**Protocol**

MQTT

**Describe the Bug**

So, this has been kicking my butt for the past week and a half in regards to Azure IoT Hub C SDK Version 1.2.14 (latest recommended by Microsoft).  A 2K leak when MQTT is in constant reconnect state and IoT Hub client handle is destroyed.  /*This*/ code was originally in the if statement and I replaced it with this code (transport_data->xioTransport).  In this scenario, the currPacketState can be DISCONNECT_TYPE, with transport still allocated and needing to be freed.  The file is Mesh_FwLib_STM32CubeExpansion_Cloud_AZURE\Middlewares\Third_Party\azure-iot-sdk-c\iothub_client\src\iothubtransport_mqtt_common.c

```
static void DisconnectFromClient(PMQTTTRANSPORT_HANDLE_DATA transport_data)
{
    if (transport_data->xioTransport/*transport_data->currPacketState != DISCONNECT_TYPE*/)
    {
        if (!transport_data->isDestroyCalled)
        {
            OPTIONHANDLER_HANDLE options = xio_retrieveoptions(transport_data->xioTransport);
            set_saved_tls_options(transport_data, options);
        }
        // Ensure the disconnect message is sent
        if (transport_data->mqttClientStatus == MQTT_CLIENT_STATUS_CONNECTED)
        {
            transport_data->disconnect_recv_flag = 0;
            (void)mqtt_client_disconnect(transport_data->mqttClient, mqtt_disconnect_cb, &transport_data->disconnect_recv_flag);
            size_t disconnect_ctr = 0;
            do
            {
                mqtt_client_dowork(transport_data->mqttClient);
                disconnect_ctr++;
                ThreadAPI_Sleep(50);
            } while ((disconnect_ctr < MAX_DISCONNECT_VALUE) && (transport_data->disconnect_recv_flag == 0));
        }
        xio_destroy(transport_data->xioTransport);
        transport_data->xioTransport = NULL;

        transport_data->device_twin_get_sent = false;
        transport_data->mqttClientStatus = MQTT_CLIENT_STATUS_NOT_CONNECTED;
        transport_data->currPacketState = DISCONNECT_TYPE;
    }
}
```

**Comment by maskimthedog** [comment]
STM32F04, FreeRTOS, Azure IoT Hub C SDK 1.2.14

So, **this** has been kicking my butt for the past week and a half in regards to Azure IoT Hub C SDK Version 1.2.14 (latest recommended by Microsoft).  A 2K leak when MQTT is in constant reconnect and the IoT Hub client handle is destroyed.  **This** code was originally in the if statement and I replaced it with _this_ code.  In this scenario, the currPacketState can be DISCONNECT_TYPE, with transport still allocated and needing to be freed.  The file is Mesh_FwLib_STM32CubeExpansion_Cloud_AZURE\Middlewares\Third_Party\azure-iot-sdk-c\iothub_client\src\iothubtransport_mqtt_common.c

I cannot presume that my hack is the correct fix.  However, the leak stops with the hack.

static void DisconnectFromClient(PMQTTTRANSPORT_HANDLE_DATA transport_data)
{
    if (_transport_data->xioTransport_/***transport_data->currPacketState != DISCONNECT_TYPE*/**)
    {
        if (!transport_data->isDestroyCalled)
        {
            OPTIONHANDLER_HANDLE options = xio_retrieveoptions(transport_data->xioTransport);
            set_saved_tls_options(transport_data, options);
        }
        // Ensure the disconnect message is sent
        if (transport_data->mqttClientStatus == MQTT_CLIENT_STATUS_CONNECTED)
        {
            transport_data->disconnect_recv_flag = 0;
            (void)mqtt_client_disconnect(transport_data->mqttClient, mqtt_disconnect_cb, &transport_data->disconnect_recv_flag);
            size_t disconnect_ctr = 0;
            do
            {
                mqtt_client_dowork(transport_data->mqttClient);
                disconnect_ctr++;
                ThreadAPI_Sleep(50);
            } while ((disconnect_ctr < MAX_DISCONNECT_VALUE) && (transport_data->disconnect_recv_flag == 0));
        }
        xio_destroy(transport_data->xioTransport);
        transport_data->xioTransport = NULL;

        transport_data->device_twin_get_sent = false;
        transport_data->mqttClientStatus = MQTT_CLIENT_STATUS_NOT_CONNECTED;
        transport_data->currPacketState = DISCONNECT_TYPE;
    }
}

**Comment by maskimthedog** [comment]
**Development Machine, OS, Compiler**

STM32F405, FreeRTOS, GCC

**SDK Version**

1.2.14

**Protocol**

MQTT

**Describe the Bug**

So, this has been kicking my butt for the past week and a half in regards to Azure IoT Hub C SDK Version 1.2.14 (latest recommended by Microsoft).  A 2K leak when MQTT is in constant reconnect state and IoT Hub client handle is destroyed.  /*This*/ code was originally in the if statement and I replaced it with this code (transport_data->xioTransport).  In this scenario, the currPacketState can be DISCONNECT_TYPE, with transport still allocated and needing to be freed.  The file is Mesh_FwLib_STM32CubeExpansion_Cloud_AZURE\Middlewares\Third_Party\azure-iot-sdk-c\iothub_client\src\iothubtransport_mqtt_common.c

...
static void DisconnectFromClient(PMQTTTRANSPORT_HANDLE_DATA transport_data)
{
    if (transport_data->xioTransport/*transport_data->currPacketState != DISCONNECT_TYPE*/)
    {
        if (!transport_data->isDestroyCalled)
        {
            OPTIONHANDLER_HANDLE options = xio_retrieveoptions(transport_data->xioTransport);
            set_saved_tls_options(transport_data, options);
        }
        // Ensure the disconnect message is sent
        if (transport_data->mqttClientStatus == MQTT_CLIENT_STATUS_CONNECTED)
        {
            transport_data->disconnect_recv_flag = 0;
            (void)mqtt_client_disconnect(transport_data->mqttClient, mqtt_disconnect_cb, &transport_data->disconnect_recv_flag);
            size_t disconnect_ctr = 0;
            do
            {
                mqtt_client_dowork(transport_data->mqttClient);
                disconnect_ctr++;
                ThreadAPI_Sleep(50);
            } while ((disconnect_ctr < MAX_DISCONNECT_VALUE) && (transport_data->disconnect_recv_flag == 0));
        }
        xio_destroy(transport_data->xioTransport);
        transport_data->xioTransport = NULL;

        transport_data->device_twin_get_sent = false;
        transport_data->mqttClientStatus = MQTT_CLIENT_STATUS_NOT_CONNECTED;
        transport_data->currPacketState = DISCONNECT_TYPE;
    }
}

**Comment by ewertons** [comment]
Hi @maskimthedog ,
thanks for reporting this issue! Sorry for the memory leak, that is a high-priority issue and we will address right away.

**Comment by jebrando** [comment]
@maskimthedog,

I'm looking into this bug and have one question.  Do you the exact steps to repro this issue.

Thanks,
Jelani

**Comment by maskimthedog** [comment]
Attempting to close the client handle while MQTT over websockets is continuously trying to reconnect of failed MQTT ping.

**Comment by maskimthedog** [comment]
I am using the LL calls on a single thread.

**Comment by maskimthedog** [comment]
I can send you my code if need be.

**Comment by maskimthedog** [comment]
I believe what is happening is this...

MQTT connection is active and a ping failure occurs because of a signal disruption.
Then transport_data->currPacketState != DISCONNECT_TYPE when DisconnectFromClient() is called the transport is freed and transport_data->currPacketState is set to DISCONNECT_TYPE within the function.
Next the SDK attempts to reconnect calling InitializeConnection() which calls ResetConnectionIfNecessary() freeing up the transport (if a connection attempt has been made previously) prior to calling SendMqttConnectMsg() which calls GetTransportProviderIfNecessary() to allocate the transport.
This all plays well until IoTHubTransport_MQTT_Common_Destroy() is called which calls DisconnectFromClient().  Since transport_data->currPacketState is still set to DISCONNECT_TYPE, DisconnectFromClient() does not free the transport.

**Comment by maskimthedog** [comment]
Ping.

**Comment by maskimthedog** [comment]
This bug still exists in 1.3.4.  The fix is still the same.

**Comment by maskimthedog** [comment]
No worries.  Thanks for the patch.  I am testing now with it applied to 1.3.4.

**Comment by az-iot-builder-01** [comment]
@ewertons, @jebrando, @maskimthedog, @rafilho, @jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
