### ISSUE TITLE
Build error by VS2017 on Windows

### ISSUE THREAD

**Issue by ms-iotkithol-jp** [Azure/azure-iot-sdk-c#926]
When this SDK is built by VS2017 development command prompt on Windows 10, some compile error occure in c-utility/adapters/socketio_win32.c

In afunix.h(C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared\afunix.h), SOCKADDR_UN is defined as follow
typedef struct _SOCKADDR_UN
{
     ADDRESS_FAMILY Family;
     wchar_t Path[63];
} SOCKADDR_UN, *PSOCKADDR_UN;.

But in socketio_win32.c, several parts mistake member's name.
I edit these mistake then compile errors disappeared.

Please check and fix.

**Comment by YoDaMa** [comment]
Hi @ms-iotkithol-jp, thanks for identifying an issue! Can you let me know if I'm understanding your problem correctly? Here's what I'm seeing:

1. You're trying to compile the SDK from scratch using the VS 2017 Developer Command Prompt.  
2. There's an external header file called `afunix.h` that has a struct defined as `SOCKADDR_UN`. 
3. In socketio_win32.c, there's a variable declared with the same name, `SOCKADDR_UN`, which is only defined for newer versions of Windows that support unix domain sockets. 

I'm not seeing an error on compiling the sample `iothub_ll_telemetry_sample`. Do you have a sample that I could use to reproduce this error?

**Comment by ewertons** [comment]
Hi @ms-iotkithol-jp ,
according to @YoDaMa 's verification we are not being able to repro the issue you reported. Please provide more details about your environment and repo steps.

We will close this issue for now, but please feel free to reopen it if you would like to follow up.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@ms-iotkithol-jp, @YoDaMa, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
