### ISSUE TITLE
Applicaton build fails at Linking CXX executable  using my CmakeLists.txt

### ISSUE THREAD

**Issue by chinnaece** [Azure/azure-iot-sdk-c#927]
CmakeLists.txt:

cmake_minimum_required(VERSION 3.5)
set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)
set (CMAKE_CXX_FLAGS "--std=c++11 ${CMAKE_CXX_FLAGS}")
set(AZUREIOT_INC_FOLDER ".." "/usr/local/include/azureiot" "/usr/local/include/azureiot/inc" "/usr/local/include/azureiot/inc/internal")
include_directories( ${AZUREIOT_INC_FOLDER} )   
link_directories(/usr/local/lib)
file(GLOB SOURCES "*.cpp" "*.h")

add_executable(Iot_App ${SOURCES})
target_link_libraries(Iot_App   serializer
				iothub_client			
				iothub_client_mqtt_transport 
				iothub_client_http_transport				
                                umqtt
                                aziotsharedutil                               
                                uhttp                               
                                curl					
				ssl				
			        crypto
				m
				parson
				uuid	
                                pthread
				m                                                    
	               )
################ERROR###################

/usr/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_CreateFromDeviceAuth':
iothub_client_authorization.c:(.text+0x526): undefined reference to `iothub_device_auth_create'
iothub_client_authorization.c:(.text+0x604): undefined reference to `iothub_device_auth_destroy'
iothub_client_authorization.c:(.text+0x694): undefined reference to `iothub_device_auth_destroy'
iothub_client_authorization.c:(.text+0x6ca): undefined reference to `iothub_device_auth_get_type'
/usr/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Destroy':
iothub_client_authorization.c:(.text+0x71a): undefined reference to `iothub_device_auth_destroy'
/usr/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Set_xio_Certificate':
iothub_client_authorization.c:(.text+0x8e6): undefined reference to `iothub_device_auth_generate_credentials'
/usr/local/lib/libiothub_client_mqtt_transport.a(iothub_client_authorization.c.o): In function `IoTHubClient_Auth_Get_SasToken':
iothub_client_authorization.c:(.text+0xc3d): undefined reference to `iothub_device_auth_generate_credentials'
collect2: error: ld returned 1 exit status
CMakeFiles/Iot_App.dir/build.make:250: recipe for target 'Iot_App' failed
make[2]: *** [Iot_App] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Iot_App.dir/all' failed
make[1]: *** [CMakeFiles/Iot_App.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Where i am missing , Not able to find. saw similar problem #598 , which is not help me .

**Comment by chinnaece** [comment]
The building static libs while using cmake .. , cmake [options BOOL=ON] .. , are different . they are internally depended .

**Comment by az-iot-builder-01** [comment]
@chinnaece, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
