### ISSUE TITLE
C equivalent code for ProvisioningDeviceClient.RegisterAsync()

### ISSUE THREAD

**Issue by shmisra** [Azure/azure-iot-sdk-c#929]
Provisioning is achieved by using a single call to the ProvisioningDeviceClient.RegisterAsync() API specifying the GlobalDeviceEndpoint, the IDScope (unique for each Provisioning Service deployment), a SecurityProvider and a ProvisioningTransportHandler:

ProvisioningDeviceClient provClient = ProvisioningDeviceClient.Create(globalDeviceEndpoint, s_idScope, security, transport);
DeviceRegistrationResult result = await provClient.RegisterAsync();

For example: 

        public async Task Provision()
        {
            var certificate = LoadPrivateKey("key.pfx"); // Multiple devices should use their leaf certificate (for which the ROOT is in the Azure DPS) and call RegisterAsync(). 

            using (var securityProvider = new SecurityProviderX509Certificate(certificate))
            using (var transport = new ProvisioningTransportHandlerAmqp(TransportFallbackType.TcpOnly))
            {
                var client = ProvisioningDeviceClient.Create("global.azure-devices-provisioning.net", this.c, securityProvider, transport);

                var result = await client.RegisterAsync();

                Console.WriteLine($"Provisioning result: {result.Status}");

                if (result.Status != ProvisioningRegistrationStatusType.Assigned) 
                {
                    throw new InvalidOperationException("Something went wrong while trying to provision.");
                }

                this.assignedHub = result.AssignedHub;
                this.auth = new DeviceAuthenticationWithX509Certificate(result.DeviceId, securityProvider.GetAuthenticationCertificate());
            }
        }

**Ask#1** - I need an equivalent C code to do the above using which we can pass in the PFX and its password to do ProvisioningClient RegisterAsync. Do you have a sample? 
The C sample https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/samples/prov_dev_client_sample/prov_dev_client_sample.c is not clear to me. I cannot see a way to pass in a PFX certificate. 

Question#1 - We are doing DPS Enrollment Groups here, for which I have created a group named smgroup. For device provisioning do we need to add the GROUP NAME anywhere in the above code? Asking as the previous sample uses only the scopeId. 

Question#2 - Enrollment Groups is done to provision multiple devices (having their own certificates) to ONE group in DPS. The above code shows enrolling ONE device. For enrolling multiple devices is the procedure same (just run the same code for all devices with their specific device leaf certificates)?

**Comment by ewertons** [comment]
Hi @shmisra ,

For Question#1: no, just the scope ID is required in the C SDK API.

We will be replying to the other two questions soon.

**Comment by ewertons** [comment]
Regarding #Ask1:
Currently the C SDK does not support using pfx certs. We advise to convert the certificate to the pem format supported by the SDK.

Question2#: For group enrollment the code is exactly the same, with the difference that you should pass the full certificate chain when setting the certificates.

**Comment by ewertons** [comment]
Hi @shmisra ,
we will close this issue for now, but please feel free to reopen it if you would like to follow up.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@shmisra, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
