### ISSUE TITLE
Build errors with 1.3.0 under linux

### ISSUE THREAD

**Issue by Tiziano** [Azure/azure-iot-sdk-c#930]
git clone  --recursive https://github.com/Azure/azure-iot-sdk-c.git
goto tag 1.3.0
git co 1.3.0
create cmake directory: cd cmake
cmake .. -DCMAKE_INSTALL_PREFIX=../libs/host -Duse_amqp=OFF -Dskip_samples=ON
make install

on ubuntu 16.10

we get compile errors: 
I've posted a few of them at the bottom 

#note: taking the head of master to build, the build errors are fixed.
My expectation is that commits to master branch would not break the build. 
I would expect that a tagged version would build, or did I missed something? 

In file included from /home/tiziano/azure-iot-sdk-c/iothub_client/src/iothub_client_authorization.c:19:0:
/home/tiziano/azure-iot-sdk-c/iothub_client/inc/internal/iothub_client_authorization.h:30:1: error: data definition has no type or storage class [-Werror]
 DEFINE_ENUM(IOTHUB_CREDENTIAL_TYPE, IOTHUB_CREDENTIAL_TYPE_VALUES);
 ^~~~~~~~~~~
/home/tiziano/azure-iot-sdk-c/iothub_client/inc/internal/iothub_client_authorization.h:30:1: error: type defaults to ‘int’ in declaration of ‘DEFINE_ENUM’ [-Werror=implicit-int]
/home/tiziano/azure-iot-sdk-c/iothub_client/inc/internal/iothub_client_authorization.h:30:1: error: parameter names (without types) in function declaration [-Werror]
/home/tiziano/azure-iot-sdk-c/iothub_client/inc/internal/iothub_client_authorization.h:37:1: error: data definition has no type or storage class [-Werror]
 DEFINE_ENUM(SAS_TOKEN_STATUS, SAS_TOKEN_STATUS_VALUES);
 ^~~~~~~~~~~
/home/tiziano/azure-iot-sdk-c/iothub_client/inc/internal/iothub_client_authorization.h:37:1: error: type defaults to ‘int’ in declaration of ‘DEFINE_ENUM’ [-Werror=implicit-int]
/home/tiziano/azure-iot-sdk-c/iothub_client/inc/internal/iothub_client_authorization.h:37:1: error: parameter names (without types) in function declaration [-Werror]
In file included from /home/tiziano/azure-iot-sdk-c/c-utility/inc/azure_c_shared_utility/xio.h:9:0,
                 from /home/tiziano/azure-iot-sdk-c/iothub_client/inc/internal/iothub_client_authorization.h:9,
                 from /home/tiziano/azure-iot-sdk-c/iothub_client/src/iothub_client_authorization.c:19:
/home/tiziano/azure-iot-sdk-c/iothub_client/inc/internal/iothub_client_authorization.h:42:21: error: unknown type name ‘IOTHUB_CREDENTIAL_TYPE’
 MOCKABLE_FUNCTION(, IOTHUB_CREDENTIAL_TYPE, IoTHubClient_Auth_Set_x509_Type, IOTHUB_AUTHORIZATION_HANDLE, handle, bool, enable_x509);

....
                     ^

**Comment by ewertons** [comment]
Hi @Tiziano ,
thanks for the detailing the steps you took.
After you checked out version 1.3.0, did you run a `git submodule update --init --recursive`?
If not, it could be that you have the current submodule versions used by master checked out, while trying to compile the C SDK code from release 1.3.0 (which is behind master).

**Comment by TizianoFranzoi** [comment]
Hi @ewertons 
fine, that worked. Thank you very much
But is surprising to me, because I cloned just before from the repo in the way it 
described here:
https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#linux

Probably the mentioned git command should be mentioned there ?

**Comment by massand** [comment]
@TizianoFranzoi - It is mentioned clearly here:

**Comment by az-iot-builder-01** [comment]
@Tiziano, @ewertons, @TizianoFranzoi, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
