### ISSUE TITLE
MQTT vs. MQTT with Websockets

### ISSUE THREAD

**Issue by christophtramnitz** [Azure/azure-iot-sdk-c#934]
I have read the following file: [c_sdk_resource_information.md](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/c_sdk_resource_information.md)

The bytes send for the same payload seem to be equal for MQTT and MQTT with Websockets. Above the table there is a sentence which says "This value excludes the connection and disconnection headers."

As far as I understood the websocket connection is established at the beginning of the communication and persists till the end of the communication. Consequently, the implementations for MQTT and MQTT with Websockets should have a pretty similar effective data usage. Is that right?

Thanks for your help in advance!

**Comment by ewertons** [comment]
Hi @christophtramnitz ,
yes, absolutely you got it right.
The options we offer on top of WebSockets are a way to make the Azure IoT C SDK integrate more easily with HTTP proxies.
But discounting the initial HTTP request for upgrade to WS and WS pings the traffic should be pretty similar to the option directly over TLS.

**Comment by ewertons** [comment]
Hi @christophtramnitz ,
we will close this issue for now, but please feel free to reopen it if you would like to follow up.
Thank,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@christophtramnitz, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
