### ISSUE TITLE
Endorsement key format/requirements for custom HSM

### ISSUE THREAD

**Issue by OYTIS** [Azure/azure-iot-sdk-c#937]
Greetings!

I'm trying to create a custom HSM as described in [using_custom_hsm.md](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_custom_hsm.md). The goal is to expose a security element (not a TPM, but holding an RSA key pair)  as a TPM.

Now I'm trying to create an individual enrollment. What I do for that is I convert the RSA public key in DER format to TPM2B_PUBLIC (basically hacking [tpm2_loadexternal](https://github.com/tpm2-software/tpm2-tools/blob/master/tools/tpm2_loadexternal.c) to spit out marshalled structure instead of loading it to a TPM), base64 encode it and provide it as an endorsement key to the web form.

What I get as response is `Endorsement key is invalid, or does not match the Enrollment`. That makes me think that there are some requirements to the key that I couldn't find. The keys provided in the [example](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/samples/custom_hsm_example/custom_hsm_example.c) look pretty short and probably wouldn't pass the check either.

Would be grateful for any hints.

Thanks!

**Comment by jebrando** [comment]
@OYTIS I'm fielded questions on what you're trying to accomplish, but I have yet to figure out exactly how to do it.  The TPM formats remain a mystery to me and the TPM RFC is not a lot of help.  Let me ask some security people around here if there is a good resource.  I shall ping back when they reply.

**Comment by OYTIS** [comment]
@jebrando Thanks a lot. My end goal is to have DPS provisioning working without providing the private key as a file. I originally thought that playing TPM would be an easier way to achieve it than adding support for non-extractable keys to X509 provisioning, but apparently these are at least comparable.

**Comment by mlilien** [comment]
@OYTIS @jebrando Any new insights to this topic?

I also wonder that I do not find any documentation which EK format the DPS accepts.
Is the format only relevant to the custom hsm implementation itself?

**Comment by OYTIS** [comment]
@mlilien I personaly have taken a different path and am working to add support of private keys living in crypto devices to X509 HSMs. I hope we can bring it upstream soon.

As for TPM data formats - still no idea.

**Comment by ewertons** [comment]
Hi @mlilien ,

We apologize for the long delay, but we were assigned to work on new code development and that affected our github response time.

Is this still an issue for you?

**Comment by ewertons** [comment]
@OYTIS , we will close this issue according to our prioritization for this repo.
If you would like to follow up on this matter please feel free to file a new issue.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@OYTIS, @mlilien, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
