### ISSUE TITLE
IoT edge device in transparent gateway mode with downstream device : which features are not enabled ?

### ISSUE THREAD

**Issue by krokoko** [Azure/azure-iot-sdk-c#938]
Hello guys,

   I was wondering if you have a clear list / roadmap for the features which are available/not available from a downstream device connected to an iot edge device in transparent gateway mode, something like this : https://github.com/Azure/azure-iot-sdk-c#key-features-and-roadmap . I would like to use the file upload to blob storage and automatic provisioning, which are not available yet. Also I would like to add a firmware update, is a supported scenario ?

Thank you for the good job ! :)

**Comment by krokoko** [comment]
Any update ?

**Comment by ewertons** [comment]
Hi @krokoko ,

Are you using code from https://github.com/Azure/iot-edge-v1 ?

**Comment by ewertons** [comment]
Or  https://github.com/Azure/iotedge ?

**Comment by krokoko** [comment]
Hello @ewertons,

I am using https://github.com/Azure/iotedge

**Comment by ewertons** [comment]
I see. 
In this case, this question would be better posted on that repo.
Here it is: https://github.com/Azure/iotedge/issues/1075
@chipalost should be able to help with that.

If you have any other questions related specifically to Azure IoT C SDK, please feel free to open a new issue.
Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@krokoko, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by krokoko** [comment]
Perfect, thank you @ewertons !
