### ISSUE TITLE
Busy-waiting deep in MQTT Client close_connection() when executing IoTHub Client destroy

### ISSUE THREAD

**Issue by eLEcTRiCZiTy** [Azure/azure-iot-sdk-c#94]
Hi,

When I try IotHub Client MQTT sample (with mbedTLS and socketio_berkley from azure-c-shared-utility /adapters), everything works good but when I try to destroy IoTHub Client, then program hangs. I traced where the problem is.

Used: 
- Windows 10, MSYS32 with ESP-IDF (ESP32 toolkit - uses Freertos, Berkley sockets, mbedTLS)
- IoTHub Client (with customized build process for ESP-IDF), with dependencies:
    - azure-c-shared-utility (with adapters from /adapters)
    - MQTT (without AMQP, Websockets)

Source code:
[iothub_client_sample_mqtt](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_mqtt)

Trace:
-> iothub_client_sample_mqtt_run(...) ([/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c#L199](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c#L199))
IoTHubClient_LL_Destroy(...) ([iothub_client_ll.c#L707](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothub_client_ll.c#L707))
-> IoTHubTransport_Destroy(...) ([iothubtransport_mqtt_common.c#L2120](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L2120))
-> DisconnectFromClient(...) ([iothubtransport_mqtt_common.c#L1742](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L1742))
-> mqtt_client_disconnect(...) ([mqtt_client.c#L1091](https://github.com/Azure/azure-umqtt-c/blob/master/src/mqtt_client.c#L1091))
-> sendPacketItem(...) ([mqtt_client.c#L320](https://github.com/Azure/azure-umqtt-c/blob/master/src/mqtt_client.c#L320))
-> tlsio_mbedtls_send(...) ([tlsio_mbedtls.c#L571](https://github.com/Azure/azure-c-shared-utility/blob/243a825cfc7a16034c68401b6327a697728c9224/adapters/tlsio_mbedtls.c#L571))
-> on_io_send(...) ([tlsio_mbedtls.c#L296](https://github.com/Azure/azure-c-shared-utility/blob/243a825cfc7a16034c68401b6327a697728c9224/adapters/tlsio_mbedtls.c#L296))
-> socketio_send(...) ([socketio_berkeley.c#L526](https://github.com/Azure/azure-c-shared-utility/blob/243a825cfc7a16034c68401b6327a697728c9224/adapters/socketio_berkeley.c#L526))
-> sendComplete(...) ([mqtt_client.c#L177](https://github.com/Azure/azure-umqtt-c/blob/master/src/mqtt_client.c#L177))
-> close_connection(...) ([mqtt_client.c#L72](https://github.com/Azure/azure-umqtt-c/blob/master/src/mqtt_client.c#L72)) <- There is maybe source of the problem
-> tlsio_mbedtls_dowork(...) ([tlsio_mbedtls.c#L595](https://github.com/Azure/azure-c-shared-utility/blob/243a825cfc7a16034c68401b6327a697728c9224/adapters/tlsio_mbedtls.c#L595))
-> decode_ssl_received_bytes(...) ([tlsio_mbedtls.c#L116](https://github.com/Azure/azure-c-shared-utility/blob/243a825cfc7a16034c68401b6327a697728c9224/adapters/tlsio_mbedtls.c#L116))
-> on_io_recv(...) ([tlsio_mbedtls.c#L249](https://github.com/Azure/azure-c-shared-utility/blob/243a825cfc7a16034c68401b6327a697728c9224/adapters/tlsio_mbedtls.c#L249)) <- There is spinning because receive nothing

I think... In the MQTT Client ([mqtt_client.c#L75](https://github.com/Azure/azure-umqtt-c/blob/master/src/mqtt_client.c#L75)) `close_complete` is equal to 1 (determined by sample executing) before entering the do-while loop. So the do-while loop will be terminated anyway, but the program calls `xio_dowork` and hangs in loop that receiving nothing.

I tried to rewrite do-while loop into only while. The while condition evaluates, the while loop is skipped and IoTHub Client is successfully destroyed but this workaround is probably not a real solution.

**Comment by anporumb** [comment]
Hello @eLEcTRiCZiTy ,

We will capture this in our backlog, thank you for your report.

Best Regards,
Andrei Porumb

**Comment by JetstreamRoySprowl** [comment]
Hi @eLEcTRiCZiTy, thank you for the well-formed report. Is the spinning you're seeing permanent, or does it time out after a couple of minutes?

**Comment by eLEcTRiCZiTy** [comment]
Spinning seems to be permanent and triggers the Watchdog Task (ESP-IDF implementation, triggers after 5s).

IotHubClient runs in task named "mqtt" and task function is `iothub_mqtt_run`.  Internet connection is available and system time is synchronized.

Console output is formatted:
`function_name[free_heap]$ debug message`

Console output after quit message:
```
...
iothub_mqtt_run[117956]$ MQTT Client destroying, call DoWork 3 more time to complete final sending...
iothub_mqtt_run[117956]$ IotHubClient DoWork.
iothub_mqtt_run[117956]$ IotHubClient DoWork.
iothub_mqtt_run[117956]$ IotHubClient DoWork.
Task watchdog got triggered. The following tasks did not feed the watchdog in time:
 - IDLE (CPU 1)
Tasks currently running:
CPU 0: IDLE
CPU 1: mqtt
Task watchdog got triggered. The following tasks did not feed the watchdog in time:
 - IDLE (CPU 1)
Tasks currently running:
CPU 0: IDLE
CPU 1: mqtt
Task watchdog got triggered. The following tasks did not feed the watchdog in time:
 - IDLE (CPU 1)
Tasks currently running:
CPU 0: IDLE
CPU 1: mqtt
...
```

**Comment by JetstreamRoySprowl** [comment]
Thanks, @eLEcTRiCZiTy. We've got this captured in our bug list and it's near the top of my to-do list.

**Comment by JetstreamRoySprowl** [comment]
Hey there, I'm finally ready to work on this problem. Can you send me your build stuff like makefile, etc.

**Comment by eLEcTRiCZiTy** [comment]
I use Azure IoTHub Client as an ESP-IDF component for Espressif ESP32.

Dir Tree:
[iothub_dir_tree.pdf](https://github.com/Azure/azure-iot-sdk-c/files/1047800/iothub_dir_tree.pdf)
Custom Makefile for ESP-IDF component system:
[component.zip](https://github.com/Azure/azure-iot-sdk-c/files/1047804/component.zip)

I am not authorized to provide custom adapter source codes. If necessary, I will discuss it with my superiors.

**Comment by JetstreamRoySprowl** [comment]
We've got this one reproduced and fixed, and are moving it through the checkin procedure.

**Comment by JetstreamRoySprowl** [comment]
@eLEcTRiCZiTy : Did the fixes to tlsio_embedtls.c take care of this for you?
