### ISSUE TITLE
How to validate hostname of iothub certificate?

### ISSUE THREAD

**Issue by ohmyandy** [Azure/azure-iot-sdk-c#943]
It seems that hostname of iothub's certificate is not validated when connecting to it. So, I basically want to make sure that we are connected to the hub we are connecting to. The questions is, can it be done automatically by the SDK? Are there any examples how to do that? Or if not, how can I integrate openssl's library hostname checking?

There is the following function in the SDK:

**x509Certificate_getSubjectName()**

but, from skimming of the sdk, it is not used much other then in unit tests.

I'd like to enabled hostname validation in Azure SDK (C), in the similar way how it is done by means of ssl library, for example:

  ...
  SSL_set_hostflags(ssl, X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS);
  if (!SSL_set1_host(ssl, "www.example.com")) {
    /* handle error */
  }
  /* Enable peer verification (with a non-null callback if desired) */
  SSL_set_verify(ssl, SSL_VERIFY_PEER, NULL);
  ...
/*
 * Establish SSL connection, hostname should be checked
 * automatically test with a hostname that should not match,
 * the connection will fail (unless you specify a callback
 * that returns despite the verification failure.  In that
 * case SSL_get_verify_status() can expose the problem after
 * connection completion.
 */

**Comment by ewertons** [comment]
Hi @ohmyandy ,

thanks for the question! Server cert validation is a must have and the Azure IoT C SDK does it automatically by default.

Azure IoT C SDK uses "azure-c-shared-utility" library to provide the abstraction for the TLS layer. It does have a [TLS abstraction layer for OpenSSL](
https://github.com/Azure/azure-c-shared-utility/blob/10136150741c622eb5b6e96149ae370c5f89554d/adapters/tlsio_openssl.c).

If you search for function "create_openssl_instance", you will see that it invokes the following:

`add_certificate_to_store(tlsInstance, tlsInstance->certificate)`
> This passes to OpenSsl the certificate provided by the user when calling, for example, `IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_TRUSTED_CERT, certificates)` (see our [sample](https://github.com/Azure/azure-iot-sdk-c/blob/1.3.0/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L134)).
> Our certificates are published in the repo (see ["certs"](https://github.com/Azure/azure-iot-sdk-c/tree/1.3.0/certs) directory).

`SSL_CTX_set_cert_verify_callback`
> You do have the option to use your own callback function if you would like. This is not an option we do advertise, but you might be able to set it by calling `IoTHubDeviceClient_LL_SetOption(device_ll_handle, "tls_validation_callback_data", context_for_your_validation_function)` and `IoTHubDeviceClient_LL_SetOption(device_ll_handle, "tls_validation_callback", your_validation_function)` right afer you call `IoTHubDeviceClient_LL_CreateFromConnectionString` (and before you do anything else with the iothub_device_client handle). Please see [here](https://github.com/Azure/azure-c-shared-utility/blob/10136150741c622eb5b6e96149ae370c5f89554d/adapters/tlsio_openssl.c#L1543) for reference.

`SSL_CTX_set_verify(tlsInstance->ssl_context, SSL_VERIFY_PEER, NULL);`
> Enables server certificate validation.
> See [the openssl documentation](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_verify.html)

**Comment by YoDaMa** [comment]
Hey @ohmyandy, I'm going to go ahead and close this issue since @ewertons 's response gives a great summary of our server cert validation. let us know if you need more information on this question by reopening. Thanks for asking, it's a good question.

**Comment by az-iot-builder-01** [comment]
@ohmyandy, @ewertons, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
