### ISSUE TITLE
MQTT packet size attacks

### ISSUE THREAD

**Issue by ohmyandy** [Azure/azure-iot-sdk-c#945]
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

IMX6UL
Cross Compiled on Ubuntu 16.04 using GCC 6.2.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**

commit db8f7d5ef1d1a2781c3e594ba250a46df7fd7258
1.2.8

**Protocol**

MQTT

**Describe the Bug**

It seems like,  invalid  MQTT packet size is not handled correctly. If the MQTT packet contains a to big value, like MAX_INT (signed), the allocation of the needed memory fails and followed by an endless loop of wrongly reading MQTT packets.

MQTT Fixed Header:
Type: Publish
Remaining Length: **2147483647**

**Console Logs**

 azure-iot-sdk-c/c-utility/src/buffer.c Func:BUFFER_pre_build Line:248 Failure allocating buffer

azure-iot-sdk-c/umqtt/src/mqtt_codec.c Func:prepareheaderDataInfoLine:584 Failed BUFFER_pre_build

azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_error_callback Line:1752 INTERNAL ERROR: unexpected error value received MQTT_CLIENT_PARSE_ERROR

azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_re-ceived_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.

azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underly-ing_io_bytes_received Line:846 Error in decode_ssl_received_bytes.

then the last 3 errors just continue coming non stop.

**Comment by jebrando** [comment]
@ohmyandy I will look at this.  Thank you.

**Comment by enesuysal** [comment]
@jebrando Any update on that ?

**Comment by jebrando** [comment]
This has been checked in on Thursday.  Let me know if there is any more issue with this.

**Comment by az-iot-builder-01** [comment]
@ohmyandy, @jebrando, @enesuysal, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by enesuysal** [comment]
@jebrando Could you send to us the fix's commit hash?
