### ISSUE TITLE
Make Install not working

### ISSUE THREAD

**Issue by bakarydiarra** [Azure/azure-iot-sdk-c#95]
- **Ubuntu 14.04** <VERSION> 

- **1.1.9** <VERSION> 

# Description of the issue:
I was able to compile thesdk in my environment. I am currently looking to install the build artifacts (i.e. the include folder and library files) into a custom folder without success.
I was able to overwrite the default usr/share folder by using
export DESTDIR=/home/myvm/test
but the only files that were copied are 
iothub_client_sample_mqtt_dm and iothub_client_sample_firmware_update.service.

I am pretty sure that I am missing something here because I should not have to manually copy the libraries and the includes.

Thank you in advance for your help

**Comment by ewertons** [comment]
Hi @bakarydiarra , thanks for your question.
Sure, please take a look at the bottom of https://github.com/Azure/azure-iot-sdk-c/issues/71 (last 4 comments).
Hope this helps.

Thanks for using the Azure IoT Client SDK.

**Comment by bakarydiarra** [comment]
@ewertons It fix my issue. Thank you
