### ISSUE TITLE
Select network interface

### ISSUE THREAD

**Issue by amitabhmodak** [Azure/azure-iot-sdk-c#960]
Hi,
I have a device that has a 2 network interface (ppp0 and eth0). I want the Azure IOT agent to connect to the DPS or IOT hub using a specific network interface. Is it supported in the Azure-iot-sdk-c, that the client code can specify which network interface the agent should bind into?

br
Amitabh

**Comment by ewertons** [comment]
That can be done for the Azure IoT Hub connection on Linux only.
You would use like this:
```c
char* mac_address = "02-15-86-1D-03-AD"; // change this to your network interface mac address.
IoTHubDeviceClient_SetOption(iothub_deviceclient_handle, OPTION_NET_INT_MAC_ADDRESS, mac_address);
```
You can check [this function](https://github.com/Azure/azure-iot-sdk-c/blob/1.3.1/iothub_client/tests/common_e2e/iothubclient_common_e2e.c#L424) we have to retrieve the mac addresses, if you need that to be done dynamically.

We haven't verified that for DPS recently, but it should work as well (using the same option name). The APi to use would be: 
```c
char* mac_address = "02-15-86-1D-03-AD"; // change this to your network interface mac address.
Prov_Device_LL_SetOption(prov_device_ll_handle, OPTION_NET_INT_MAC_ADDRESS, mac_address);
```

**Comment by ewertons** [comment]
Hi @amitabhmodak ,
we will close this issue for now, but please feel free to reopen it if you would like to follow up.

Thanks,
Azure IoT SDK Team.

**Comment by az-iot-builder-01** [comment]
@amitabhmodak, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by deepakraparti** [comment]
@amitabhmodak, @ewertons does above mentioned API (IoTHubDeviceClient_SetOption) is supported on the AMQP over websocket?
