### ISSUE TITLE
'segment fault' - after closing SSH session to a device via device streams

### ISSUE THREAD

**Issue by zombinary** [Azure/azure-iot-sdk-c#967]
# description:

* running proxy in fedora 30 (vm):

  ``` $ node azure-iot-samples-node-streams-previw/iot-hub/Quickstart/device-streams-service/proxy.js```

* running stream example ubuntu 18.04 / azure-iot-sdk-c v1.3.0:

  ```$ ./cmake/iothub_client/samples/iothub_client_c2d_streaming_proxy_sample/iothub_client_c2d_streaming_proxy_sample```

* connect with ssh from host to device (fedora=>ubuntu/device):

  ```$ ssh <user>@localhost -p 2222```

* close the ssh sesison:
  
  ```<user>@<hostname>$ exit```

* the iothub_client return an **segement fault**:
 
 ```
 $ ./iothub_client_c2d_streaming_proxy_sample
-> 14:16:15 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: devicestream.azure-devices.net/julienTestSshStream/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.0%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
<- 14:16:16 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
-> 14:16:16 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: $iothub/streams/POST/# | QOS: 0 | TOPIC_NAME: $iothub/streams/res/# | QOS: 0
<- 14:16:16 SUBACK | PACKET_ID: 2 | RETURN_CODE: 0 | RETURN_CODE: 0
<- 14:16:48 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/streams/POST/TestStream/?$rid=1&$url=wss%3A%2F%2Fcentralus.centralus-001.streams.azure-devices.net%3A443%2Fbridges%2Fih%2Fdevicestream%2Fd%2FjulienTestSshStream%2Fsid%2Fb430f350d8914e00a40f89c6154fb655%2Fr%2Fany&$auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NTYwMjE4NzMsImp0aSI6ImtDMzVwVGlrb2VMSUprbVdMamdpQVBZc2ZtZy1oa3A0TDJtVUFGSmJYaEEiLCJpb3RodWIiOiJkZXZpY2VzdHJlYW0ifQ.cj7j54SyLwePkUVDK4mzoDqBvYeSawol0ghurBdtohk&$ip=0.0.0.0 | PAYLOAD_LEN: 0
Received stream request (TestStream)
-> 14:16:48 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/streams/res/200/?$rid=1
Client connected to the streaming gateway (WS_OPEN_OK)
Reporting traffic statistics every 10 seconds.
[2019-04-23 14:16:55 UTC+0200] Network traffic (in bytes) (sent=41; received=21)
[2019-04-23 14:17:05 UTC+0200] Network traffic (in bytes) (sent=3400; received=2956)
Segmentation fault (core dumped)
```

* **dmesg log** from iothub_client:

  ``` $ dmesg [689391.356120] iothub_client_c[14626]: segfault at 0 ip 0000558669c7aa53 sp 00007fff94b107f0 error 4 in iothub_client_c2d_streaming_proxy_sample[558669c6a000+85000] ```
---
I used the azure-iot-sdk-c v1.3.0 and could not found an streaming example in a newer version?
Is this no longer maintained?

The same problem I have, when I copy a file with scp to the client.
The iothub_client is closed with an 'segment fault' after creating the file, too.

I am looking for a solution, why the iothub_client crashes or which component is causing the problem?

**Comment by az-iot-builder-01** [comment]
@zombinary, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
