### ISSUE TITLE
build IoT Edge c sample project failed

### ISSUE THREAD

**Issue by czgtest** [Azure/azure-iot-sdk-c#968]
Repo of IoT Edge c sample: https://github.com/Azure/azure-iot-edge-c-module
I can build the sample project successfully (docker build Dockerfile.amd64.debug) previously  
now the build will fail with bellow error. Could you help take a look?
Here's part of the error message:

![image](https://user-images.githubusercontent.com/35018765/56638077-c6a44b80-669f-11e9-817a-655f37cdfc84.png)

**Comment by formulahendry** [comment]
I have the same error with @czgtest 
![image](https://user-images.githubusercontent.com/1050213/56638207-1aaf3000-66a0-11e9-8b20-5417d65d06eb.png)

**Comment by YoDaMa** [comment]
Sounds like this is related to https://github.com/Azure/azure-iot-sdk-c/issues/966. @jebrando @massand can you take a look?

**Comment by massand** [comment]
Please run docker build command with --no-cache option when building the module. I suspect the apt-get step is being skipped by default. I just built the sample module successfully from your repo in VS Code. Please provide all the logs from the build step if you would like us to investigate further, after you try --no-cache option. Thanks!

**Comment by az-iot-builder-01** [comment]
@czgtest, @formulahendry, @YoDaMa, @massand, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
