### ISSUE TITLE
[Question/Feature Request] Is there a way to receive Cloud 2 Device messages with the C SDK?

### ISSUE THREAD

**Issue by czyba** [Azure/azure-iot-sdk-c#97]
Is there a way to receive messages from my device with the C SDK?

I am currently aware of being able to send D2C messages (via iothub_client) and C2D  messages (via iothub_service_client), however I have not yet found a way to receive messages send by a device. I basically want to receive messages, similar to the iothub-explorer tool as iothubowner. Is there some way to do this with the C SDK?

Rationale: 
 1. My payloads are usually serialized in some way, so the iothub-explorer and device-explorer tools only print binary garbage. 
 2. Not being able to receive my own messages makes automatic unit testing rather difficult in my scenario. 
  3. Since I only have small systems (i.e. <= 128MB RAM), receiving messages via java, node.js or C# is sadly not an option due to the required resources.

If this is currently not possible, I would like to request this feature. If this feature is already planned, is there some ETA for this?

Kind regards,
Christopher Czyba

**Comment by zolvarga** [comment]
Hi @czyba,

Receiving events on the service side please take a look at the C implementation of the Event-Hub library:
[https://github.com/Azure/azure-event-hubs-c](url)
What you are looking for is the eventhub_client receiver.

Best Regarsds,
Zoltan

**Comment by czyba** [comment]
Hi @zolvarga,

Thanks. I thought I would find it here, but I guess I was wrong.

Thanks again and kind regards,
Christopher
