### ISSUE TITLE
Building vcpkg.exe failed errorMSB1009

### ISSUE THREAD

**Issue by simon-jun** [Azure/azure-iot-sdk-c#996]
hello,
so i was following the [guide](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#windows) to setup the development environment. I did the first 5 steps. Then in the next section "Build a sample application without building the SDK" i switched over to [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/setting_up_vcpkg.md#setup-c-sdk-vcpkg-for-windows-development-environment) to complete those steps aswell. 

Then the following error occured: 
`C:\Windows\System32>pushd vcpkg_new`

`C:\Windows\System32\vcpkg_new>.\bootstrap-vcpkg.bat`

`Building vcpkg.exe ...`

`MSBUILD : error MSB1009: Project file does not exist.`
`Switch: C:\Windows\System32\vcpkg_new\toolsrc\dirs.proj`
`C:\Windows\System32\vcpkg_new\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you` `have installed`
`Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.`
`In Line:1 Symbol:4`
+ & {& 'C:\Windows\System32\vcpkg_new\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1`
C++ and SDK is installed, see pictue:
![grafik](https://user-images.githubusercontent.com/48299178/57382917-21fd3000-71ae-11e9-9a56-5b1f8ab86aaa.png)

thanks for your help.

**Comment by YoDaMa** [comment]
@simon-jun have you tried following the steps on the vcpkg github? Comment back if those don't work. https://github.com/Microsoft/vcpkg

**Comment by simon-jun** [comment]
Folliwing the steps in vcpkg also ends up in an error.
I ran the first two in cmd, then i switched to powershell in admin mode :
`> git clone https://github.com/Microsoft/vcpkg.git`
`> cd vcpkg`

`PS> .\bootstrap-vcpkg.bat`

Cloning worked without a problem. After that the powershell command causes an error. Info: I translated the error message to english:  
`PS C:\WINDOWS\system32\vcpkg> .\bootstrap-vcpkg.bat`
`Error at execution of the application "bootstrap-vcpkg.bat": The given executable file is not a valid`
`application for this os platform.In Line:1 Symbol:1`
`+ .\bootstrap-vcpkg.bat`
`+ ~~~~~~~~~~~~~~~~~~~~~.`
`In Line:1 Symbol:1`
`+ .\bootstrap-vcpkg.bat`
`+ ~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException`
`    + FullyQualifiedErrorId : NativeCommandFailed`

**Comment by simon-jun** [comment]
Turns out i don't even need to do all that, since the Azure IoT SKD for C is included in the Azure Sphere SDK. 
The [instructions](https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-c#prerequisites) are really misleading. The step "prepare your development environment" is not needed when you already have the Azure Sphere SDK. To include the necessary files for telemetry can be included with: 
`#include "applibs_versions.h"`
`#include <azureiot/iothub_client_options.h>`
`#include <azureiot/iothub.h>`
`//etc..`
just like the applibs APIs.

**Comment by az-iot-builder-01** [comment]
@YoDaMa, @simon-jun, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by YoDaMa** [comment]
Thanks for your documentation feedback @simon-jun. If you'd like to to help improve the docs you can submit feedback to the linked instructions so that other folks might not hit the same snag.
